void postfit_projx0_fail_logy()
{
//=========Macro generated from canvas: plots_fit_b/base_figs/postfit_projx0_fail_logy/plots_fit_b/base_figs/postfit_projx0_fail_logy
//=========  (Fri Jan 12 20:33:15 2024) by ROOT version 6.14/09
   TCanvas *plots_fit_b/base_figs/postfit_projx0_fail_logy = new TCanvas("plots_fit_b/base_figs/postfit_projx0_fail_logy", "plots_fit_b/base_figs/postfit_projx0_fail_logy",0,0,800,700);
   gStyle->SetOptFit(1);
   gStyle->SetOptStat(0);
   plots_fit_b/base_figs/postfit_projx0_fail_logy->SetHighLightColor(2);
   plots_fit_b/base_figs/postfit_projx0_fail_logy->Range(0,0,1,1);
   plots_fit_b/base_figs/postfit_projx0_fail_logy->SetFillColor(0);
   plots_fit_b/base_figs/postfit_projx0_fail_logy->SetBorderMode(0);
   plots_fit_b/base_figs/postfit_projx0_fail_logy->SetBorderSize(2);
   plots_fit_b/base_figs/postfit_projx0_fail_logy->SetTickx(1);
   plots_fit_b/base_figs/postfit_projx0_fail_logy->SetTicky(1);
   plots_fit_b/base_figs/postfit_projx0_fail_logy->SetLeftMargin(0.16);
   plots_fit_b/base_figs/postfit_projx0_fail_logy->SetRightMargin(0);
   plots_fit_b/base_figs/postfit_projx0_fail_logy->SetTopMargin(0);
   plots_fit_b/base_figs/postfit_projx0_fail_logy->SetBottomMargin(0);
   plots_fit_b/base_figs/postfit_projx0_fail_logy->SetFrameFillStyle(0);
   plots_fit_b/base_figs/postfit_projx0_fail_logy->SetFrameBorderMode(0);
  
// ------------>Primitives in pad: data_obs_fail_postfit_projx0_main
   TPad *data_obs_fail_postfit_projx0_main = new TPad("data_obs_fail_postfit_projx0_main", "data_obs_fail_postfit_projx0_main",0,0.35,1,1);
   data_obs_fail_postfit_projx0_main->Draw();
   data_obs_fail_postfit_projx0_main->cd();
   data_obs_fail_postfit_projx0_main->Range(-0.2179487,-2.139535,1.064103,1.348837);
   data_obs_fail_postfit_projx0_main->SetFillColor(0);
   data_obs_fail_postfit_projx0_main->SetBorderMode(0);
   data_obs_fail_postfit_projx0_main->SetBorderSize(2);
   data_obs_fail_postfit_projx0_main->SetLogy();
   data_obs_fail_postfit_projx0_main->SetTickx(1);
   data_obs_fail_postfit_projx0_main->SetTicky(1);
   data_obs_fail_postfit_projx0_main->SetLeftMargin(0.17);
   data_obs_fail_postfit_projx0_main->SetRightMargin(0.05);
   data_obs_fail_postfit_projx0_main->SetBottomMargin(0.04);
   data_obs_fail_postfit_projx0_main->SetFrameFillStyle(0);
   data_obs_fail_postfit_projx0_main->SetFrameBorderMode(0);
   data_obs_fail_postfit_projx0_main->SetFrameFillStyle(0);
   data_obs_fail_postfit_projx0_main->SetFrameBorderMode(0);
   Double_t xAxis73[10] = {0, 0.05, 0.1, 0.15, 0.2, 0.25, 0.3, 0.35, 0.4, 1}; 
   
   TH1D *data_obs_fail_postfit_projx0__49 = new TH1D("data_obs_fail_postfit_projx0__49","",9, xAxis73);
   data_obs_fail_postfit_projx0__49->SetMinimum(0.001);
   data_obs_fail_postfit_projx0__49->SetMaximum(0);
   data_obs_fail_postfit_projx0__49->SetStats(0);

   Int_t ci;      // for color index setting
   TColor *color; // for color definition with alpha
   ci = TColor::GetColor("#000000");
   data_obs_fail_postfit_projx0__49->SetLineColor(ci);

   ci = TColor::GetColor("#000000");
   data_obs_fail_postfit_projx0__49->SetMarkerColor(ci);
   data_obs_fail_postfit_projx0__49->SetMarkerStyle(8);
   data_obs_fail_postfit_projx0__49->GetXaxis()->SetTitle("G_{i}^{Strips}");
   data_obs_fail_postfit_projx0__49->GetXaxis()->SetLabelFont(42);
   data_obs_fail_postfit_projx0__49->GetXaxis()->SetLabelOffset(0.05);
   data_obs_fail_postfit_projx0__49->GetXaxis()->SetLabelSize(0.07);
   data_obs_fail_postfit_projx0__49->GetXaxis()->SetTitleSize(0.09);
   data_obs_fail_postfit_projx0__49->GetXaxis()->SetTitleOffset(1.15);
   data_obs_fail_postfit_projx0__49->GetXaxis()->SetTitleFont(42);
   data_obs_fail_postfit_projx0__49->GetYaxis()->SetTitle("Events / bin");
   data_obs_fail_postfit_projx0__49->GetYaxis()->SetNdivisions(508);
   data_obs_fail_postfit_projx0__49->GetYaxis()->SetLabelFont(42);
   data_obs_fail_postfit_projx0__49->GetYaxis()->SetLabelSize(0.07);
   data_obs_fail_postfit_projx0__49->GetYaxis()->SetTitleSize(0.09);
   data_obs_fail_postfit_projx0__49->GetYaxis()->SetTitleOffset(0.8);
   data_obs_fail_postfit_projx0__49->GetYaxis()->SetTitleFont(42);
   data_obs_fail_postfit_projx0__49->GetZaxis()->SetLabelFont(42);
   data_obs_fail_postfit_projx0__49->GetZaxis()->SetLabelSize(0.035);
   data_obs_fail_postfit_projx0__49->GetZaxis()->SetTitleSize(0.035);
   data_obs_fail_postfit_projx0__49->GetZaxis()->SetTitleFont(42);
   data_obs_fail_postfit_projx0__49->Draw("pe X0");
   
   THStack *postfit_projx0_fail_logy_stack = new THStack();
   postfit_projx0_fail_logy_stack->SetName("postfit_projx0_fail_logy_stack");
   postfit_projx0_fail_logy_stack->SetTitle("postfit_projx0_fail_logy_stack");
   postfit_projx0_fail_logy_stack->SetMinimum(0.001);
   Double_t xAxis74[10] = {0, 0.05, 0.1, 0.15, 0.2, 0.25, 0.3, 0.35, 0.4, 1}; 
   
   TH1F *postfit_projx0_fail_logy_stack_stack_13 = new TH1F("postfit_projx0_fail_logy_stack_stack_13","postfit_projx0_fail_logy_stack",9, xAxis74);
   postfit_projx0_fail_logy_stack_stack_13->SetMinimum(-0);
   postfit_projx0_fail_logy_stack_stack_13->SetMaximum(-nan);
   postfit_projx0_fail_logy_stack_stack_13->SetDirectory(0);
   postfit_projx0_fail_logy_stack_stack_13->SetStats(0);
   postfit_projx0_fail_logy_stack_stack_13->SetLineStyle(0);
   postfit_projx0_fail_logy_stack_stack_13->GetXaxis()->SetLabelFont(42);
   postfit_projx0_fail_logy_stack_stack_13->GetXaxis()->SetLabelOffset(0.007);
   postfit_projx0_fail_logy_stack_stack_13->GetXaxis()->SetLabelSize(0.05);
   postfit_projx0_fail_logy_stack_stack_13->GetXaxis()->SetTitleSize(0.08);
   postfit_projx0_fail_logy_stack_stack_13->GetXaxis()->SetTitleOffset(0.9);
   postfit_projx0_fail_logy_stack_stack_13->GetXaxis()->SetTitleFont(42);
   postfit_projx0_fail_logy_stack_stack_13->GetYaxis()->SetNdivisions(508);
   postfit_projx0_fail_logy_stack_stack_13->GetYaxis()->SetLabelFont(42);
   postfit_projx0_fail_logy_stack_stack_13->GetYaxis()->SetLabelOffset(0.007);
   postfit_projx0_fail_logy_stack_stack_13->GetYaxis()->SetLabelSize(0.05);
   postfit_projx0_fail_logy_stack_stack_13->GetYaxis()->SetTitleSize(0.08);
   postfit_projx0_fail_logy_stack_stack_13->GetYaxis()->SetTitleOffset(1.25);
   postfit_projx0_fail_logy_stack_stack_13->GetYaxis()->SetTitleFont(42);
   postfit_projx0_fail_logy_stack_stack_13->GetZaxis()->SetLabelFont(42);
   postfit_projx0_fail_logy_stack_stack_13->GetZaxis()->SetLabelOffset(0.007);
   postfit_projx0_fail_logy_stack_stack_13->GetZaxis()->SetLabelSize(0.05);
   postfit_projx0_fail_logy_stack_stack_13->GetZaxis()->SetTitleSize(0.08);
   postfit_projx0_fail_logy_stack_stack_13->GetZaxis()->SetTitleFont(42);
   postfit_projx0_fail_logy_stack->SetHistogram(postfit_projx0_fail_logy_stack_stack_13);
   
   Double_t xAxis75[10] = {0, 0.05, 0.1, 0.15, 0.2, 0.25, 0.3, 0.35, 0.4, 1}; 
   
   TH1D *Background_fail_postfit_projx0_stack_1 = new TH1D("Background_fail_postfit_projx0_stack_1","Background, fail, postfit, 200-200",9, xAxis75);
   Background_fail_postfit_projx0_stack_1->SetMinimum(0.001);
   Background_fail_postfit_projx0_stack_1->SetStats(0);

   ci = TColor::GetColor("#ffff00");
   Background_fail_postfit_projx0_stack_1->SetFillColor(ci);

   ci = 1185;
   color = new TColor(ci, 1, 1, 1, " ", 0);
   Background_fail_postfit_projx0_stack_1->SetLineColor(ci);
   Background_fail_postfit_projx0_stack_1->GetXaxis()->SetTitle("G_{i}^{Strips}");
   Background_fail_postfit_projx0_stack_1->GetXaxis()->SetLabelFont(42);
   Background_fail_postfit_projx0_stack_1->GetXaxis()->SetLabelSize(0.035);
   Background_fail_postfit_projx0_stack_1->GetXaxis()->SetTitleSize(0.035);
   Background_fail_postfit_projx0_stack_1->GetXaxis()->SetTitleFont(42);
   Background_fail_postfit_projx0_stack_1->GetYaxis()->SetTitle("Events / bin");
   Background_fail_postfit_projx0_stack_1->GetYaxis()->SetLabelFont(42);
   Background_fail_postfit_projx0_stack_1->GetYaxis()->SetLabelSize(0.035);
   Background_fail_postfit_projx0_stack_1->GetYaxis()->SetTitleSize(0.035);
   Background_fail_postfit_projx0_stack_1->GetYaxis()->SetTitleOffset(0);
   Background_fail_postfit_projx0_stack_1->GetYaxis()->SetTitleFont(42);
   Background_fail_postfit_projx0_stack_1->GetZaxis()->SetLabelFont(42);
   Background_fail_postfit_projx0_stack_1->GetZaxis()->SetLabelSize(0.035);
   Background_fail_postfit_projx0_stack_1->GetZaxis()->SetTitleSize(0.035);
   Background_fail_postfit_projx0_stack_1->GetZaxis()->SetTitleFont(42);
   postfit_projx0_fail_logy_stack->Add(Background_fail_postfit_projx0_stack_1,"");
   postfit_projx0_fail_logy_stack->Draw("hist same");
   
   postfit_projx0_fail_logy_stack = new THStack();
   postfit_projx0_fail_logy_stack->SetName("postfit_projx0_fail_logy_stack");
   postfit_projx0_fail_logy_stack->SetTitle("postfit_projx0_fail_logy_stack");
   postfit_projx0_fail_logy_stack->SetMinimum(0.001);
   Double_t xAxis76[10] = {0, 0.05, 0.1, 0.15, 0.2, 0.25, 0.3, 0.35, 0.4, 1}; 
   
   TH1F *postfit_projx0_fail_logy_stack_stack_13_stack_14 = new TH1F("postfit_projx0_fail_logy_stack_stack_13_stack_14","postfit_projx0_fail_logy_stack",9, xAxis76);
   postfit_projx0_fail_logy_stack_stack_13_stack_14->SetMinimum(-0);
   postfit_projx0_fail_logy_stack_stack_13_stack_14->SetMaximum(-nan);
   postfit_projx0_fail_logy_stack_stack_13_stack_14->SetDirectory(0);
   postfit_projx0_fail_logy_stack_stack_13_stack_14->SetStats(0);
   postfit_projx0_fail_logy_stack_stack_13_stack_14->SetLineStyle(0);
   postfit_projx0_fail_logy_stack_stack_13_stack_14->GetXaxis()->SetLabelFont(42);
   postfit_projx0_fail_logy_stack_stack_13_stack_14->GetXaxis()->SetLabelOffset(0.007);
   postfit_projx0_fail_logy_stack_stack_13_stack_14->GetXaxis()->SetLabelSize(0.05);
   postfit_projx0_fail_logy_stack_stack_13_stack_14->GetXaxis()->SetTitleSize(0.08);
   postfit_projx0_fail_logy_stack_stack_13_stack_14->GetXaxis()->SetTitleOffset(0.9);
   postfit_projx0_fail_logy_stack_stack_13_stack_14->GetXaxis()->SetTitleFont(42);
   postfit_projx0_fail_logy_stack_stack_13_stack_14->GetYaxis()->SetNdivisions(508);
   postfit_projx0_fail_logy_stack_stack_13_stack_14->GetYaxis()->SetLabelFont(42);
   postfit_projx0_fail_logy_stack_stack_13_stack_14->GetYaxis()->SetLabelOffset(0.007);
   postfit_projx0_fail_logy_stack_stack_13_stack_14->GetYaxis()->SetLabelSize(0.05);
   postfit_projx0_fail_logy_stack_stack_13_stack_14->GetYaxis()->SetTitleSize(0.08);
   postfit_projx0_fail_logy_stack_stack_13_stack_14->GetYaxis()->SetTitleOffset(1.25);
   postfit_projx0_fail_logy_stack_stack_13_stack_14->GetYaxis()->SetTitleFont(42);
   postfit_projx0_fail_logy_stack_stack_13_stack_14->GetZaxis()->SetLabelFont(42);
   postfit_projx0_fail_logy_stack_stack_13_stack_14->GetZaxis()->SetLabelOffset(0.007);
   postfit_projx0_fail_logy_stack_stack_13_stack_14->GetZaxis()->SetLabelSize(0.05);
   postfit_projx0_fail_logy_stack_stack_13_stack_14->GetZaxis()->SetTitleSize(0.08);
   postfit_projx0_fail_logy_stack_stack_13_stack_14->GetZaxis()->SetTitleFont(42);
   postfit_projx0_fail_logy_stack->SetHistogram(postfit_projx0_fail_logy_stack_stack_13_stack_14);
   
   Double_t xAxis77[10] = {0, 0.05, 0.1, 0.15, 0.2, 0.25, 0.3, 0.35, 0.4, 1}; 
   
   TH1D *Background_fail_postfit_projx0_stack_1_stack_1 = new TH1D("Background_fail_postfit_projx0_stack_1_stack_1","Background, fail, postfit, 200-200",9, xAxis77);
   Background_fail_postfit_projx0_stack_1_stack_1->SetMinimum(0.001);
   Background_fail_postfit_projx0_stack_1_stack_1->SetStats(0);

   ci = TColor::GetColor("#ffff00");
   Background_fail_postfit_projx0_stack_1_stack_1->SetFillColor(ci);

   ci = 1185;
   color = new TColor(ci, 1, 1, 1, " ", 0);
   Background_fail_postfit_projx0_stack_1_stack_1->SetLineColor(ci);
   Background_fail_postfit_projx0_stack_1_stack_1->GetXaxis()->SetTitle("G_{i}^{Strips}");
   Background_fail_postfit_projx0_stack_1_stack_1->GetXaxis()->SetLabelFont(42);
   Background_fail_postfit_projx0_stack_1_stack_1->GetXaxis()->SetLabelSize(0.035);
   Background_fail_postfit_projx0_stack_1_stack_1->GetXaxis()->SetTitleSize(0.035);
   Background_fail_postfit_projx0_stack_1_stack_1->GetXaxis()->SetTitleFont(42);
   Background_fail_postfit_projx0_stack_1_stack_1->GetYaxis()->SetTitle("Events / bin");
   Background_fail_postfit_projx0_stack_1_stack_1->GetYaxis()->SetLabelFont(42);
   Background_fail_postfit_projx0_stack_1_stack_1->GetYaxis()->SetLabelSize(0.035);
   Background_fail_postfit_projx0_stack_1_stack_1->GetYaxis()->SetTitleSize(0.035);
   Background_fail_postfit_projx0_stack_1_stack_1->GetYaxis()->SetTitleOffset(0);
   Background_fail_postfit_projx0_stack_1_stack_1->GetYaxis()->SetTitleFont(42);
   Background_fail_postfit_projx0_stack_1_stack_1->GetZaxis()->SetLabelFont(42);
   Background_fail_postfit_projx0_stack_1_stack_1->GetZaxis()->SetLabelSize(0.035);
   Background_fail_postfit_projx0_stack_1_stack_1->GetZaxis()->SetTitleSize(0.035);
   Background_fail_postfit_projx0_stack_1_stack_1->GetZaxis()->SetTitleFont(42);
   postfit_projx0_fail_logy_stack->Add(Background_fail_postfit_projx0_stack_1_stack_1,"");
   postfit_projx0_fail_logy_stack->Draw("hist same");
   Double_t xAxis78[10] = {0, 0.05, 0.1, 0.15, 0.2, 0.25, 0.3, 0.35, 0.4, 1}; 
   
   TH1D *Signal_gluinomI1800_fail_postfit_projx0__50 = new TH1D("Signal_gluinomI1800_fail_postfit_projx0__50","HSCP gluino 1800 GeV, fail, postfit, 200-200",9, xAxis78);
   Signal_gluinomI1800_fail_postfit_projx0__50->SetMinimum(0.001);
   Signal_gluinomI1800_fail_postfit_projx0__50->SetStats(0);
   Signal_gluinomI1800_fail_postfit_projx0__50->SetLineColor(4);
   Signal_gluinomI1800_fail_postfit_projx0__50->SetLineWidth(2);
   Signal_gluinomI1800_fail_postfit_projx0__50->GetXaxis()->SetTitle("G_{i}^{Strips}");
   Signal_gluinomI1800_fail_postfit_projx0__50->GetXaxis()->SetLabelFont(42);
   Signal_gluinomI1800_fail_postfit_projx0__50->GetXaxis()->SetLabelSize(0.035);
   Signal_gluinomI1800_fail_postfit_projx0__50->GetXaxis()->SetTitleSize(0.035);
   Signal_gluinomI1800_fail_postfit_projx0__50->GetXaxis()->SetTitleFont(42);
   Signal_gluinomI1800_fail_postfit_projx0__50->GetYaxis()->SetTitle("Events / bin");
   Signal_gluinomI1800_fail_postfit_projx0__50->GetYaxis()->SetLabelFont(42);
   Signal_gluinomI1800_fail_postfit_projx0__50->GetYaxis()->SetLabelSize(0.035);
   Signal_gluinomI1800_fail_postfit_projx0__50->GetYaxis()->SetTitleSize(0.035);
   Signal_gluinomI1800_fail_postfit_projx0__50->GetYaxis()->SetTitleOffset(0);
   Signal_gluinomI1800_fail_postfit_projx0__50->GetYaxis()->SetTitleFont(42);
   Signal_gluinomI1800_fail_postfit_projx0__50->GetZaxis()->SetLabelFont(42);
   Signal_gluinomI1800_fail_postfit_projx0__50->GetZaxis()->SetLabelSize(0.035);
   Signal_gluinomI1800_fail_postfit_projx0__50->GetZaxis()->SetTitleSize(0.035);
   Signal_gluinomI1800_fail_postfit_projx0__50->GetZaxis()->SetTitleFont(42);
   Signal_gluinomI1800_fail_postfit_projx0__50->Draw("hist same");
   Double_t xAxis79[10] = {0, 0.05, 0.1, 0.15, 0.2, 0.25, 0.3, 0.35, 0.4, 1}; 
   
   TH1D *Signal_ppStaumI557_fail_postfit_projx0__51 = new TH1D("Signal_ppStaumI557_fail_postfit_projx0__51","HSCP stau 557 GeV, fail, postfit, 200-200",9, xAxis79);
   Signal_ppStaumI557_fail_postfit_projx0__51->SetMinimum(0.001);
   Signal_ppStaumI557_fail_postfit_projx0__51->SetStats(0);
   Signal_ppStaumI557_fail_postfit_projx0__51->SetLineColor(2);
   Signal_ppStaumI557_fail_postfit_projx0__51->SetLineWidth(2);
   Signal_ppStaumI557_fail_postfit_projx0__51->GetXaxis()->SetTitle("G_{i}^{Strips}");
   Signal_ppStaumI557_fail_postfit_projx0__51->GetXaxis()->SetLabelFont(42);
   Signal_ppStaumI557_fail_postfit_projx0__51->GetXaxis()->SetLabelSize(0.035);
   Signal_ppStaumI557_fail_postfit_projx0__51->GetXaxis()->SetTitleSize(0.035);
   Signal_ppStaumI557_fail_postfit_projx0__51->GetXaxis()->SetTitleFont(42);
   Signal_ppStaumI557_fail_postfit_projx0__51->GetYaxis()->SetTitle("Events / bin");
   Signal_ppStaumI557_fail_postfit_projx0__51->GetYaxis()->SetLabelFont(42);
   Signal_ppStaumI557_fail_postfit_projx0__51->GetYaxis()->SetLabelSize(0.035);
   Signal_ppStaumI557_fail_postfit_projx0__51->GetYaxis()->SetTitleSize(0.035);
   Signal_ppStaumI557_fail_postfit_projx0__51->GetYaxis()->SetTitleOffset(0);
   Signal_ppStaumI557_fail_postfit_projx0__51->GetYaxis()->SetTitleFont(42);
   Signal_ppStaumI557_fail_postfit_projx0__51->GetZaxis()->SetLabelFont(42);
   Signal_ppStaumI557_fail_postfit_projx0__51->GetZaxis()->SetLabelSize(0.035);
   Signal_ppStaumI557_fail_postfit_projx0__51->GetZaxis()->SetTitleSize(0.035);
   Signal_ppStaumI557_fail_postfit_projx0__51->GetZaxis()->SetTitleFont(42);
   Signal_ppStaumI557_fail_postfit_projx0__51->Draw("hist same");
   Double_t xAxis80[10] = {0, 0.05, 0.1, 0.15, 0.2, 0.25, 0.3, 0.35, 0.4, 1}; 
   
   TH1D *TotalBkg_fail_postfit_projx0__52 = new TH1D("TotalBkg_fail_postfit_projx0__52","TotalBkg, fail, postfit, 200-200",9, xAxis80);
   TotalBkg_fail_postfit_projx0__52->SetMinimum(0.001);
   TotalBkg_fail_postfit_projx0__52->SetStats(0);
   TotalBkg_fail_postfit_projx0__52->SetMarkerStyle(0);
   TotalBkg_fail_postfit_projx0__52->GetXaxis()->SetTitle("G_{i}^{Strips}");
   TotalBkg_fail_postfit_projx0__52->GetXaxis()->SetLabelFont(42);
   TotalBkg_fail_postfit_projx0__52->GetXaxis()->SetLabelSize(0.035);
   TotalBkg_fail_postfit_projx0__52->GetXaxis()->SetTitleSize(0.035);
   TotalBkg_fail_postfit_projx0__52->GetXaxis()->SetTitleFont(42);
   TotalBkg_fail_postfit_projx0__52->GetYaxis()->SetTitle("Events / bin");
   TotalBkg_fail_postfit_projx0__52->GetYaxis()->SetLabelFont(42);
   TotalBkg_fail_postfit_projx0__52->GetYaxis()->SetLabelSize(0.035);
   TotalBkg_fail_postfit_projx0__52->GetYaxis()->SetTitleSize(0.035);
   TotalBkg_fail_postfit_projx0__52->GetYaxis()->SetTitleOffset(0);
   TotalBkg_fail_postfit_projx0__52->GetYaxis()->SetTitleFont(42);
   TotalBkg_fail_postfit_projx0__52->GetZaxis()->SetLabelFont(42);
   TotalBkg_fail_postfit_projx0__52->GetZaxis()->SetLabelSize(0.035);
   TotalBkg_fail_postfit_projx0__52->GetZaxis()->SetTitleSize(0.035);
   TotalBkg_fail_postfit_projx0__52->GetZaxis()->SetTitleFont(42);
   TotalBkg_fail_postfit_projx0__52->Draw("hist same");
   Double_t xAxis81[10] = {0, 0.05, 0.1, 0.15, 0.2, 0.25, 0.3, 0.35, 0.4, 1}; 
   
   TH1D *TotalBkg_fail_postfit_projx0__53 = new TH1D("TotalBkg_fail_postfit_projx0__53","TotalBkg, fail, postfit, 200-200",9, xAxis81);
   TotalBkg_fail_postfit_projx0__53->SetMinimum(0.001);
   TotalBkg_fail_postfit_projx0__53->SetStats(0);
   TotalBkg_fail_postfit_projx0__53->SetFillColor(1);
   TotalBkg_fail_postfit_projx0__53->SetFillStyle(3354);
   TotalBkg_fail_postfit_projx0__53->SetLineWidth(0);
   TotalBkg_fail_postfit_projx0__53->SetMarkerStyle(0);
   TotalBkg_fail_postfit_projx0__53->GetXaxis()->SetTitle("G_{i}^{Strips}");
   TotalBkg_fail_postfit_projx0__53->GetXaxis()->SetLabelFont(42);
   TotalBkg_fail_postfit_projx0__53->GetXaxis()->SetLabelSize(0.035);
   TotalBkg_fail_postfit_projx0__53->GetXaxis()->SetTitleSize(0.035);
   TotalBkg_fail_postfit_projx0__53->GetXaxis()->SetTitleFont(42);
   TotalBkg_fail_postfit_projx0__53->GetYaxis()->SetTitle("Events / bin");
   TotalBkg_fail_postfit_projx0__53->GetYaxis()->SetLabelFont(42);
   TotalBkg_fail_postfit_projx0__53->GetYaxis()->SetLabelSize(0.035);
   TotalBkg_fail_postfit_projx0__53->GetYaxis()->SetTitleSize(0.035);
   TotalBkg_fail_postfit_projx0__53->GetYaxis()->SetTitleOffset(0);
   TotalBkg_fail_postfit_projx0__53->GetYaxis()->SetTitleFont(42);
   TotalBkg_fail_postfit_projx0__53->GetZaxis()->SetLabelFont(42);
   TotalBkg_fail_postfit_projx0__53->GetZaxis()->SetLabelSize(0.035);
   TotalBkg_fail_postfit_projx0__53->GetZaxis()->SetTitleSize(0.035);
   TotalBkg_fail_postfit_projx0__53->GetZaxis()->SetTitleFont(42);
   TotalBkg_fail_postfit_projx0__53->Draw("e2 same");
   Double_t xAxis82[10] = {0, 0.05, 0.1, 0.15, 0.2, 0.25, 0.3, 0.35, 0.4, 1}; 
   
   TH1D *data_obs_fail_postfit_projx0__54 = new TH1D("data_obs_fail_postfit_projx0__54","",9, xAxis82);
   data_obs_fail_postfit_projx0__54->SetMinimum(0.001);
   data_obs_fail_postfit_projx0__54->SetMaximum(0);
   data_obs_fail_postfit_projx0__54->SetStats(0);

   ci = TColor::GetColor("#000000");
   data_obs_fail_postfit_projx0__54->SetLineColor(ci);

   ci = TColor::GetColor("#000000");
   data_obs_fail_postfit_projx0__54->SetMarkerColor(ci);
   data_obs_fail_postfit_projx0__54->SetMarkerStyle(8);
   data_obs_fail_postfit_projx0__54->GetXaxis()->SetTitle("G_{i}^{Strips}");
   data_obs_fail_postfit_projx0__54->GetXaxis()->SetLabelFont(42);
   data_obs_fail_postfit_projx0__54->GetXaxis()->SetLabelOffset(0.05);
   data_obs_fail_postfit_projx0__54->GetXaxis()->SetLabelSize(0.07);
   data_obs_fail_postfit_projx0__54->GetXaxis()->SetTitleSize(0.09);
   data_obs_fail_postfit_projx0__54->GetXaxis()->SetTitleOffset(1.15);
   data_obs_fail_postfit_projx0__54->GetXaxis()->SetTitleFont(42);
   data_obs_fail_postfit_projx0__54->GetYaxis()->SetTitle("Events / bin");
   data_obs_fail_postfit_projx0__54->GetYaxis()->SetNdivisions(508);
   data_obs_fail_postfit_projx0__54->GetYaxis()->SetLabelFont(42);
   data_obs_fail_postfit_projx0__54->GetYaxis()->SetLabelSize(0.07);
   data_obs_fail_postfit_projx0__54->GetYaxis()->SetTitleSize(0.09);
   data_obs_fail_postfit_projx0__54->GetYaxis()->SetTitleOffset(0.8);
   data_obs_fail_postfit_projx0__54->GetYaxis()->SetTitleFont(42);
   data_obs_fail_postfit_projx0__54->GetZaxis()->SetLabelFont(42);
   data_obs_fail_postfit_projx0__54->GetZaxis()->SetLabelSize(0.035);
   data_obs_fail_postfit_projx0__54->GetZaxis()->SetTitleSize(0.035);
   data_obs_fail_postfit_projx0__54->GetZaxis()->SetTitleFont(42);
   data_obs_fail_postfit_projx0__54->Draw("pe X0 same");
   
   TLegend *leg = new TLegend(0.65,0.61,0.9,0.88,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(1001);
   TLegendEntry *entry=leg->AddEntry("data_obs_fail_postfit_projx0","Data","pe X0");

   ci = TColor::GetColor("#000000");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);

   ci = TColor::GetColor("#000000");
   entry->SetMarkerColor(ci);
   entry->SetMarkerStyle(8);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("TotalBkg_fail_postfit_projx0","Total bkg unc.","F");
   entry->SetFillColor(1);
   entry->SetFillStyle(3354);
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("Signal_gluino-1800_fail_postfit_projx0","HSCP gluino 1800 GeV","L");
   entry->SetLineColor(4);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("Signal_ppStau-557_fail_postfit_projx0","HSCP stau 557 GeV","L");
   entry->SetLineColor(2);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("Background_fail_postfit_projx0_stack_1_stack_1","Background","f");

   ci = TColor::GetColor("#ffff00");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = 1185;
   color = new TColor(ci, 1, 1, 1, " ", 0);
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   leg->Draw();
   Double_t xAxis83[10] = {0, 0.05, 0.1, 0.15, 0.2, 0.25, 0.3, 0.35, 0.4, 1}; 
   
   TH1D *data_obs_fail_postfit_projx0_copy__55 = new TH1D("data_obs_fail_postfit_projx0_copy__55","",9, xAxis83);
   data_obs_fail_postfit_projx0_copy__55->SetMinimum(0.001);
   data_obs_fail_postfit_projx0_copy__55->SetMaximum(0);
   data_obs_fail_postfit_projx0_copy__55->SetDirectory(0);
   data_obs_fail_postfit_projx0_copy__55->SetStats(0);

   ci = TColor::GetColor("#000000");
   data_obs_fail_postfit_projx0_copy__55->SetLineColor(ci);

   ci = TColor::GetColor("#000000");
   data_obs_fail_postfit_projx0_copy__55->SetMarkerColor(ci);
   data_obs_fail_postfit_projx0_copy__55->SetMarkerStyle(8);
   data_obs_fail_postfit_projx0_copy__55->GetXaxis()->SetTitle("G_{i}^{Strips}");
   data_obs_fail_postfit_projx0_copy__55->GetXaxis()->SetLabelFont(42);
   data_obs_fail_postfit_projx0_copy__55->GetXaxis()->SetLabelOffset(0.05);
   data_obs_fail_postfit_projx0_copy__55->GetXaxis()->SetLabelSize(0.07);
   data_obs_fail_postfit_projx0_copy__55->GetXaxis()->SetTitleSize(0.09);
   data_obs_fail_postfit_projx0_copy__55->GetXaxis()->SetTitleOffset(1.15);
   data_obs_fail_postfit_projx0_copy__55->GetXaxis()->SetTitleFont(42);
   data_obs_fail_postfit_projx0_copy__55->GetYaxis()->SetTitle("Events / bin");
   data_obs_fail_postfit_projx0_copy__55->GetYaxis()->SetNdivisions(508);
   data_obs_fail_postfit_projx0_copy__55->GetYaxis()->SetLabelFont(42);
   data_obs_fail_postfit_projx0_copy__55->GetYaxis()->SetLabelSize(0.07);
   data_obs_fail_postfit_projx0_copy__55->GetYaxis()->SetTitleSize(0.09);
   data_obs_fail_postfit_projx0_copy__55->GetYaxis()->SetTitleOffset(0.8);
   data_obs_fail_postfit_projx0_copy__55->GetYaxis()->SetTitleFont(42);
   data_obs_fail_postfit_projx0_copy__55->GetZaxis()->SetLabelFont(42);
   data_obs_fail_postfit_projx0_copy__55->GetZaxis()->SetLabelSize(0.035);
   data_obs_fail_postfit_projx0_copy__55->GetZaxis()->SetTitleSize(0.035);
   data_obs_fail_postfit_projx0_copy__55->GetZaxis()->SetTitleFont(42);
   data_obs_fail_postfit_projx0_copy__55->Draw("sameaxis");
   TLatex *   tex = new TLatex(0.21,0.83,"200 < p_{T} < 200 , F^{Pixels}_{i} < 0.9");
tex->SetNDC();
   tex->SetTextAlign(12);
   tex->SetTextFont(42);
   tex->SetTextSize(0.06);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.17,0.92,"CMS");
tex->SetNDC();
   tex->SetTextFont(61);
   tex->SetTextSize(0.0675);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.25,0.92,"Preliminary");
tex->SetNDC();
   tex->SetTextFont(52);
   tex->SetTextSize(0.0485);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.95,0.92,"101 fb^{-1} (13 TeV)");
tex->SetNDC();
   tex->SetTextAlign(31);
   tex->SetTextFont(42);
   tex->SetTextSize(0.07);
   tex->SetLineWidth(2);
   tex->Draw();
   data_obs_fail_postfit_projx0_main->Modified();
   plots_fit_b/base_figs/postfit_projx0_fail_logy->cd();
  
// ------------>Primitives in pad: data_obs_fail_postfit_projx0_sub
   TPad *data_obs_fail_postfit_projx0_sub = new TPad("data_obs_fail_postfit_projx0_sub", "data_obs_fail_postfit_projx0_sub",0,0,1,0.35);
   data_obs_fail_postfit_projx0_sub->Draw();
   data_obs_fail_postfit_projx0_sub->cd();
   data_obs_fail_postfit_projx0_sub->Range(-0.2179487,-6.023077,1.064103,2.9);
   data_obs_fail_postfit_projx0_sub->SetFillColor(0);
   data_obs_fail_postfit_projx0_sub->SetBorderMode(0);
   data_obs_fail_postfit_projx0_sub->SetBorderSize(2);
   data_obs_fail_postfit_projx0_sub->SetTickx(1);
   data_obs_fail_postfit_projx0_sub->SetTicky(1);
   data_obs_fail_postfit_projx0_sub->SetLeftMargin(0.17);
   data_obs_fail_postfit_projx0_sub->SetRightMargin(0.05);
   data_obs_fail_postfit_projx0_sub->SetTopMargin(0);
   data_obs_fail_postfit_projx0_sub->SetBottomMargin(0.35);
   data_obs_fail_postfit_projx0_sub->SetFrameFillStyle(0);
   data_obs_fail_postfit_projx0_sub->SetFrameBorderMode(0);
   data_obs_fail_postfit_projx0_sub->SetFrameFillStyle(0);
   data_obs_fail_postfit_projx0_sub->SetFrameBorderMode(0);
   Double_t xAxis84[10] = {0, 0.05, 0.1, 0.15, 0.2, 0.25, 0.3, 0.35, 0.4, 1}; 
   
   TH1D *data_obs_fail_postfit_projx0_pull__56 = new TH1D("data_obs_fail_postfit_projx0_pull__56","",9, xAxis84);
   data_obs_fail_postfit_projx0_pull__56->SetMinimum(-2.9);
   data_obs_fail_postfit_projx0_pull__56->SetMaximum(2.9);
   data_obs_fail_postfit_projx0_pull__56->SetEntries(18);
   data_obs_fail_postfit_projx0_pull__56->SetStats(0);

   ci = TColor::GetColor("#0000ff");
   data_obs_fail_postfit_projx0_pull__56->SetFillColor(ci);

   ci = TColor::GetColor("#000000");
   data_obs_fail_postfit_projx0_pull__56->SetLineColor(ci);

   ci = TColor::GetColor("#000000");
   data_obs_fail_postfit_projx0_pull__56->SetMarkerColor(ci);
   data_obs_fail_postfit_projx0_pull__56->SetMarkerStyle(8);
   data_obs_fail_postfit_projx0_pull__56->GetXaxis()->SetTitle("G_{i}^{Strips}");
   data_obs_fail_postfit_projx0_pull__56->GetXaxis()->SetLabelFont(42);
   data_obs_fail_postfit_projx0_pull__56->GetXaxis()->SetLabelOffset(0.05);
   data_obs_fail_postfit_projx0_pull__56->GetXaxis()->SetLabelSize(0.13);
   data_obs_fail_postfit_projx0_pull__56->GetXaxis()->SetTitleSize(0.15);
   data_obs_fail_postfit_projx0_pull__56->GetXaxis()->SetTitleOffset(1.15);
   data_obs_fail_postfit_projx0_pull__56->GetXaxis()->SetTitleFont(42);
   data_obs_fail_postfit_projx0_pull__56->GetYaxis()->SetTitle("(Data-Bkg)/#sigma");
   data_obs_fail_postfit_projx0_pull__56->GetYaxis()->SetNdivisions(306);
   data_obs_fail_postfit_projx0_pull__56->GetYaxis()->SetLabelFont(42);
   data_obs_fail_postfit_projx0_pull__56->GetYaxis()->SetLabelSize(0.13);
   data_obs_fail_postfit_projx0_pull__56->GetYaxis()->SetTitleSize(0.12);
   data_obs_fail_postfit_projx0_pull__56->GetYaxis()->SetTitleOffset(0.4);
   data_obs_fail_postfit_projx0_pull__56->GetYaxis()->SetTitleFont(42);
   data_obs_fail_postfit_projx0_pull__56->GetZaxis()->SetLabelFont(42);
   data_obs_fail_postfit_projx0_pull__56->GetZaxis()->SetLabelSize(0.035);
   data_obs_fail_postfit_projx0_pull__56->GetZaxis()->SetTitleSize(0.035);
   data_obs_fail_postfit_projx0_pull__56->GetZaxis()->SetTitleFont(42);
   data_obs_fail_postfit_projx0_pull__56->Draw("hist");
   data_obs_fail_postfit_projx0_sub->Modified();
   plots_fit_b/base_figs/postfit_projx0_fail_logy->cd();
   plots_fit_b/base_figs/postfit_projx0_fail_logy->Modified();
   plots_fit_b/base_figs/postfit_projx0_fail_logy->cd();
   plots_fit_b/base_figs/postfit_projx0_fail_logy->SetSelected(plots_fit_b/base_figs/postfit_projx0_fail_logy);
}
