void postfit_projx1_fail_logy()
{
//=========Macro generated from canvas: plots_fit_b/base_figs/postfit_projx1_fail_logy/plots_fit_b/base_figs/postfit_projx1_fail_logy
//=========  (Fri Jan 12 20:33:15 2024) by ROOT version 6.14/09
   TCanvas *plots_fit_b/base_figs/postfit_projx1_fail_logy = new TCanvas("plots_fit_b/base_figs/postfit_projx1_fail_logy", "plots_fit_b/base_figs/postfit_projx1_fail_logy",0,0,800,700);
   gStyle->SetOptFit(1);
   gStyle->SetOptStat(0);
   plots_fit_b/base_figs/postfit_projx1_fail_logy->SetHighLightColor(2);
   plots_fit_b/base_figs/postfit_projx1_fail_logy->Range(0,0,1,1);
   plots_fit_b/base_figs/postfit_projx1_fail_logy->SetFillColor(0);
   plots_fit_b/base_figs/postfit_projx1_fail_logy->SetBorderMode(0);
   plots_fit_b/base_figs/postfit_projx1_fail_logy->SetBorderSize(2);
   plots_fit_b/base_figs/postfit_projx1_fail_logy->SetTickx(1);
   plots_fit_b/base_figs/postfit_projx1_fail_logy->SetTicky(1);
   plots_fit_b/base_figs/postfit_projx1_fail_logy->SetLeftMargin(0.16);
   plots_fit_b/base_figs/postfit_projx1_fail_logy->SetRightMargin(0);
   plots_fit_b/base_figs/postfit_projx1_fail_logy->SetTopMargin(0);
   plots_fit_b/base_figs/postfit_projx1_fail_logy->SetBottomMargin(0);
   plots_fit_b/base_figs/postfit_projx1_fail_logy->SetFrameFillStyle(0);
   plots_fit_b/base_figs/postfit_projx1_fail_logy->SetFrameBorderMode(0);
  
// ------------>Primitives in pad: data_obs_fail_postfit_projx1_main
   TPad *data_obs_fail_postfit_projx1_main = new TPad("data_obs_fail_postfit_projx1_main", "data_obs_fail_postfit_projx1_main",0,0.35,1,1);
   data_obs_fail_postfit_projx1_main->Draw();
   data_obs_fail_postfit_projx1_main->cd();
   data_obs_fail_postfit_projx1_main->Range(-0.2179487,-2.139535,1.064103,1.348837);
   data_obs_fail_postfit_projx1_main->SetFillColor(0);
   data_obs_fail_postfit_projx1_main->SetBorderMode(0);
   data_obs_fail_postfit_projx1_main->SetBorderSize(2);
   data_obs_fail_postfit_projx1_main->SetLogy();
   data_obs_fail_postfit_projx1_main->SetTickx(1);
   data_obs_fail_postfit_projx1_main->SetTicky(1);
   data_obs_fail_postfit_projx1_main->SetLeftMargin(0.17);
   data_obs_fail_postfit_projx1_main->SetRightMargin(0.05);
   data_obs_fail_postfit_projx1_main->SetBottomMargin(0.04);
   data_obs_fail_postfit_projx1_main->SetFrameFillStyle(0);
   data_obs_fail_postfit_projx1_main->SetFrameBorderMode(0);
   data_obs_fail_postfit_projx1_main->SetFrameFillStyle(0);
   data_obs_fail_postfit_projx1_main->SetFrameBorderMode(0);
   Double_t xAxis85[10] = {0, 0.05, 0.1, 0.15, 0.2, 0.25, 0.3, 0.35, 0.4, 1}; 
   
   TH1D *data_obs_fail_postfit_projx1__57 = new TH1D("data_obs_fail_postfit_projx1__57","",9, xAxis85);
   data_obs_fail_postfit_projx1__57->SetMinimum(0.001);
   data_obs_fail_postfit_projx1__57->SetMaximum(0);
   data_obs_fail_postfit_projx1__57->SetStats(0);

   Int_t ci;      // for color index setting
   TColor *color; // for color definition with alpha
   ci = TColor::GetColor("#000000");
   data_obs_fail_postfit_projx1__57->SetLineColor(ci);

   ci = TColor::GetColor("#000000");
   data_obs_fail_postfit_projx1__57->SetMarkerColor(ci);
   data_obs_fail_postfit_projx1__57->SetMarkerStyle(8);
   data_obs_fail_postfit_projx1__57->GetXaxis()->SetTitle("G_{i}^{Strips}");
   data_obs_fail_postfit_projx1__57->GetXaxis()->SetLabelFont(42);
   data_obs_fail_postfit_projx1__57->GetXaxis()->SetLabelOffset(0.05);
   data_obs_fail_postfit_projx1__57->GetXaxis()->SetLabelSize(0.07);
   data_obs_fail_postfit_projx1__57->GetXaxis()->SetTitleSize(0.09);
   data_obs_fail_postfit_projx1__57->GetXaxis()->SetTitleOffset(1.15);
   data_obs_fail_postfit_projx1__57->GetXaxis()->SetTitleFont(42);
   data_obs_fail_postfit_projx1__57->GetYaxis()->SetTitle("Events / bin");
   data_obs_fail_postfit_projx1__57->GetYaxis()->SetNdivisions(508);
   data_obs_fail_postfit_projx1__57->GetYaxis()->SetLabelFont(42);
   data_obs_fail_postfit_projx1__57->GetYaxis()->SetLabelSize(0.07);
   data_obs_fail_postfit_projx1__57->GetYaxis()->SetTitleSize(0.09);
   data_obs_fail_postfit_projx1__57->GetYaxis()->SetTitleOffset(0.8);
   data_obs_fail_postfit_projx1__57->GetYaxis()->SetTitleFont(42);
   data_obs_fail_postfit_projx1__57->GetZaxis()->SetLabelFont(42);
   data_obs_fail_postfit_projx1__57->GetZaxis()->SetLabelSize(0.035);
   data_obs_fail_postfit_projx1__57->GetZaxis()->SetTitleSize(0.035);
   data_obs_fail_postfit_projx1__57->GetZaxis()->SetTitleFont(42);
   data_obs_fail_postfit_projx1__57->Draw("pe X0");
   
   THStack *postfit_projx1_fail_logy_stack = new THStack();
   postfit_projx1_fail_logy_stack->SetName("postfit_projx1_fail_logy_stack");
   postfit_projx1_fail_logy_stack->SetTitle("postfit_projx1_fail_logy_stack");
   postfit_projx1_fail_logy_stack->SetMinimum(0.001);
   Double_t xAxis86[10] = {0, 0.05, 0.1, 0.15, 0.2, 0.25, 0.3, 0.35, 0.4, 1}; 
   
   TH1F *postfit_projx1_fail_logy_stack_stack_15 = new TH1F("postfit_projx1_fail_logy_stack_stack_15","postfit_projx1_fail_logy_stack",9, xAxis86);
   postfit_projx1_fail_logy_stack_stack_15->SetMinimum(-0);
   postfit_projx1_fail_logy_stack_stack_15->SetMaximum(-nan);
   postfit_projx1_fail_logy_stack_stack_15->SetDirectory(0);
   postfit_projx1_fail_logy_stack_stack_15->SetStats(0);
   postfit_projx1_fail_logy_stack_stack_15->SetLineStyle(0);
   postfit_projx1_fail_logy_stack_stack_15->GetXaxis()->SetLabelFont(42);
   postfit_projx1_fail_logy_stack_stack_15->GetXaxis()->SetLabelOffset(0.007);
   postfit_projx1_fail_logy_stack_stack_15->GetXaxis()->SetLabelSize(0.05);
   postfit_projx1_fail_logy_stack_stack_15->GetXaxis()->SetTitleSize(0.08);
   postfit_projx1_fail_logy_stack_stack_15->GetXaxis()->SetTitleOffset(0.9);
   postfit_projx1_fail_logy_stack_stack_15->GetXaxis()->SetTitleFont(42);
   postfit_projx1_fail_logy_stack_stack_15->GetYaxis()->SetNdivisions(508);
   postfit_projx1_fail_logy_stack_stack_15->GetYaxis()->SetLabelFont(42);
   postfit_projx1_fail_logy_stack_stack_15->GetYaxis()->SetLabelOffset(0.007);
   postfit_projx1_fail_logy_stack_stack_15->GetYaxis()->SetLabelSize(0.05);
   postfit_projx1_fail_logy_stack_stack_15->GetYaxis()->SetTitleSize(0.08);
   postfit_projx1_fail_logy_stack_stack_15->GetYaxis()->SetTitleOffset(1.25);
   postfit_projx1_fail_logy_stack_stack_15->GetYaxis()->SetTitleFont(42);
   postfit_projx1_fail_logy_stack_stack_15->GetZaxis()->SetLabelFont(42);
   postfit_projx1_fail_logy_stack_stack_15->GetZaxis()->SetLabelOffset(0.007);
   postfit_projx1_fail_logy_stack_stack_15->GetZaxis()->SetLabelSize(0.05);
   postfit_projx1_fail_logy_stack_stack_15->GetZaxis()->SetTitleSize(0.08);
   postfit_projx1_fail_logy_stack_stack_15->GetZaxis()->SetTitleFont(42);
   postfit_projx1_fail_logy_stack->SetHistogram(postfit_projx1_fail_logy_stack_stack_15);
   
   Double_t xAxis87[10] = {0, 0.05, 0.1, 0.15, 0.2, 0.25, 0.3, 0.35, 0.4, 1}; 
   
   TH1D *Background_fail_postfit_projx1_stack_1 = new TH1D("Background_fail_postfit_projx1_stack_1","Background, fail, postfit, 200-200",9, xAxis87);
   Background_fail_postfit_projx1_stack_1->SetMinimum(0.001);
   Background_fail_postfit_projx1_stack_1->SetStats(0);

   ci = TColor::GetColor("#ffff00");
   Background_fail_postfit_projx1_stack_1->SetFillColor(ci);

   ci = 1186;
   color = new TColor(ci, 1, 1, 1, " ", 0);
   Background_fail_postfit_projx1_stack_1->SetLineColor(ci);
   Background_fail_postfit_projx1_stack_1->GetXaxis()->SetTitle("G_{i}^{Strips}");
   Background_fail_postfit_projx1_stack_1->GetXaxis()->SetLabelFont(42);
   Background_fail_postfit_projx1_stack_1->GetXaxis()->SetLabelSize(0.035);
   Background_fail_postfit_projx1_stack_1->GetXaxis()->SetTitleSize(0.035);
   Background_fail_postfit_projx1_stack_1->GetXaxis()->SetTitleFont(42);
   Background_fail_postfit_projx1_stack_1->GetYaxis()->SetTitle("Events / bin");
   Background_fail_postfit_projx1_stack_1->GetYaxis()->SetLabelFont(42);
   Background_fail_postfit_projx1_stack_1->GetYaxis()->SetLabelSize(0.035);
   Background_fail_postfit_projx1_stack_1->GetYaxis()->SetTitleSize(0.035);
   Background_fail_postfit_projx1_stack_1->GetYaxis()->SetTitleOffset(0);
   Background_fail_postfit_projx1_stack_1->GetYaxis()->SetTitleFont(42);
   Background_fail_postfit_projx1_stack_1->GetZaxis()->SetLabelFont(42);
   Background_fail_postfit_projx1_stack_1->GetZaxis()->SetLabelSize(0.035);
   Background_fail_postfit_projx1_stack_1->GetZaxis()->SetTitleSize(0.035);
   Background_fail_postfit_projx1_stack_1->GetZaxis()->SetTitleFont(42);
   postfit_projx1_fail_logy_stack->Add(Background_fail_postfit_projx1_stack_1,"");
   postfit_projx1_fail_logy_stack->Draw("hist same");
   
   postfit_projx1_fail_logy_stack = new THStack();
   postfit_projx1_fail_logy_stack->SetName("postfit_projx1_fail_logy_stack");
   postfit_projx1_fail_logy_stack->SetTitle("postfit_projx1_fail_logy_stack");
   postfit_projx1_fail_logy_stack->SetMinimum(0.001);
   Double_t xAxis88[10] = {0, 0.05, 0.1, 0.15, 0.2, 0.25, 0.3, 0.35, 0.4, 1}; 
   
   TH1F *postfit_projx1_fail_logy_stack_stack_15_stack_16 = new TH1F("postfit_projx1_fail_logy_stack_stack_15_stack_16","postfit_projx1_fail_logy_stack",9, xAxis88);
   postfit_projx1_fail_logy_stack_stack_15_stack_16->SetMinimum(-0);
   postfit_projx1_fail_logy_stack_stack_15_stack_16->SetMaximum(-nan);
   postfit_projx1_fail_logy_stack_stack_15_stack_16->SetDirectory(0);
   postfit_projx1_fail_logy_stack_stack_15_stack_16->SetStats(0);
   postfit_projx1_fail_logy_stack_stack_15_stack_16->SetLineStyle(0);
   postfit_projx1_fail_logy_stack_stack_15_stack_16->GetXaxis()->SetLabelFont(42);
   postfit_projx1_fail_logy_stack_stack_15_stack_16->GetXaxis()->SetLabelOffset(0.007);
   postfit_projx1_fail_logy_stack_stack_15_stack_16->GetXaxis()->SetLabelSize(0.05);
   postfit_projx1_fail_logy_stack_stack_15_stack_16->GetXaxis()->SetTitleSize(0.08);
   postfit_projx1_fail_logy_stack_stack_15_stack_16->GetXaxis()->SetTitleOffset(0.9);
   postfit_projx1_fail_logy_stack_stack_15_stack_16->GetXaxis()->SetTitleFont(42);
   postfit_projx1_fail_logy_stack_stack_15_stack_16->GetYaxis()->SetNdivisions(508);
   postfit_projx1_fail_logy_stack_stack_15_stack_16->GetYaxis()->SetLabelFont(42);
   postfit_projx1_fail_logy_stack_stack_15_stack_16->GetYaxis()->SetLabelOffset(0.007);
   postfit_projx1_fail_logy_stack_stack_15_stack_16->GetYaxis()->SetLabelSize(0.05);
   postfit_projx1_fail_logy_stack_stack_15_stack_16->GetYaxis()->SetTitleSize(0.08);
   postfit_projx1_fail_logy_stack_stack_15_stack_16->GetYaxis()->SetTitleOffset(1.25);
   postfit_projx1_fail_logy_stack_stack_15_stack_16->GetYaxis()->SetTitleFont(42);
   postfit_projx1_fail_logy_stack_stack_15_stack_16->GetZaxis()->SetLabelFont(42);
   postfit_projx1_fail_logy_stack_stack_15_stack_16->GetZaxis()->SetLabelOffset(0.007);
   postfit_projx1_fail_logy_stack_stack_15_stack_16->GetZaxis()->SetLabelSize(0.05);
   postfit_projx1_fail_logy_stack_stack_15_stack_16->GetZaxis()->SetTitleSize(0.08);
   postfit_projx1_fail_logy_stack_stack_15_stack_16->GetZaxis()->SetTitleFont(42);
   postfit_projx1_fail_logy_stack->SetHistogram(postfit_projx1_fail_logy_stack_stack_15_stack_16);
   
   Double_t xAxis89[10] = {0, 0.05, 0.1, 0.15, 0.2, 0.25, 0.3, 0.35, 0.4, 1}; 
   
   TH1D *Background_fail_postfit_projx1_stack_1_stack_1 = new TH1D("Background_fail_postfit_projx1_stack_1_stack_1","Background, fail, postfit, 200-200",9, xAxis89);
   Background_fail_postfit_projx1_stack_1_stack_1->SetMinimum(0.001);
   Background_fail_postfit_projx1_stack_1_stack_1->SetStats(0);

   ci = TColor::GetColor("#ffff00");
   Background_fail_postfit_projx1_stack_1_stack_1->SetFillColor(ci);

   ci = 1186;
   color = new TColor(ci, 1, 1, 1, " ", 0);
   Background_fail_postfit_projx1_stack_1_stack_1->SetLineColor(ci);
   Background_fail_postfit_projx1_stack_1_stack_1->GetXaxis()->SetTitle("G_{i}^{Strips}");
   Background_fail_postfit_projx1_stack_1_stack_1->GetXaxis()->SetLabelFont(42);
   Background_fail_postfit_projx1_stack_1_stack_1->GetXaxis()->SetLabelSize(0.035);
   Background_fail_postfit_projx1_stack_1_stack_1->GetXaxis()->SetTitleSize(0.035);
   Background_fail_postfit_projx1_stack_1_stack_1->GetXaxis()->SetTitleFont(42);
   Background_fail_postfit_projx1_stack_1_stack_1->GetYaxis()->SetTitle("Events / bin");
   Background_fail_postfit_projx1_stack_1_stack_1->GetYaxis()->SetLabelFont(42);
   Background_fail_postfit_projx1_stack_1_stack_1->GetYaxis()->SetLabelSize(0.035);
   Background_fail_postfit_projx1_stack_1_stack_1->GetYaxis()->SetTitleSize(0.035);
   Background_fail_postfit_projx1_stack_1_stack_1->GetYaxis()->SetTitleOffset(0);
   Background_fail_postfit_projx1_stack_1_stack_1->GetYaxis()->SetTitleFont(42);
   Background_fail_postfit_projx1_stack_1_stack_1->GetZaxis()->SetLabelFont(42);
   Background_fail_postfit_projx1_stack_1_stack_1->GetZaxis()->SetLabelSize(0.035);
   Background_fail_postfit_projx1_stack_1_stack_1->GetZaxis()->SetTitleSize(0.035);
   Background_fail_postfit_projx1_stack_1_stack_1->GetZaxis()->SetTitleFont(42);
   postfit_projx1_fail_logy_stack->Add(Background_fail_postfit_projx1_stack_1_stack_1,"");
   postfit_projx1_fail_logy_stack->Draw("hist same");
   Double_t xAxis90[10] = {0, 0.05, 0.1, 0.15, 0.2, 0.25, 0.3, 0.35, 0.4, 1}; 
   
   TH1D *Signal_gluinomI1800_fail_postfit_projx1__58 = new TH1D("Signal_gluinomI1800_fail_postfit_projx1__58","HSCP gluino 1800 GeV, fail, postfit, 200-200",9, xAxis90);
   Signal_gluinomI1800_fail_postfit_projx1__58->SetMinimum(0.001);
   Signal_gluinomI1800_fail_postfit_projx1__58->SetStats(0);
   Signal_gluinomI1800_fail_postfit_projx1__58->SetLineColor(4);
   Signal_gluinomI1800_fail_postfit_projx1__58->SetLineWidth(2);
   Signal_gluinomI1800_fail_postfit_projx1__58->GetXaxis()->SetTitle("G_{i}^{Strips}");
   Signal_gluinomI1800_fail_postfit_projx1__58->GetXaxis()->SetLabelFont(42);
   Signal_gluinomI1800_fail_postfit_projx1__58->GetXaxis()->SetLabelSize(0.035);
   Signal_gluinomI1800_fail_postfit_projx1__58->GetXaxis()->SetTitleSize(0.035);
   Signal_gluinomI1800_fail_postfit_projx1__58->GetXaxis()->SetTitleFont(42);
   Signal_gluinomI1800_fail_postfit_projx1__58->GetYaxis()->SetTitle("Events / bin");
   Signal_gluinomI1800_fail_postfit_projx1__58->GetYaxis()->SetLabelFont(42);
   Signal_gluinomI1800_fail_postfit_projx1__58->GetYaxis()->SetLabelSize(0.035);
   Signal_gluinomI1800_fail_postfit_projx1__58->GetYaxis()->SetTitleSize(0.035);
   Signal_gluinomI1800_fail_postfit_projx1__58->GetYaxis()->SetTitleOffset(0);
   Signal_gluinomI1800_fail_postfit_projx1__58->GetYaxis()->SetTitleFont(42);
   Signal_gluinomI1800_fail_postfit_projx1__58->GetZaxis()->SetLabelFont(42);
   Signal_gluinomI1800_fail_postfit_projx1__58->GetZaxis()->SetLabelSize(0.035);
   Signal_gluinomI1800_fail_postfit_projx1__58->GetZaxis()->SetTitleSize(0.035);
   Signal_gluinomI1800_fail_postfit_projx1__58->GetZaxis()->SetTitleFont(42);
   Signal_gluinomI1800_fail_postfit_projx1__58->Draw("hist same");
   Double_t xAxis91[10] = {0, 0.05, 0.1, 0.15, 0.2, 0.25, 0.3, 0.35, 0.4, 1}; 
   
   TH1D *Signal_ppStaumI557_fail_postfit_projx1__59 = new TH1D("Signal_ppStaumI557_fail_postfit_projx1__59","HSCP stau 557 GeV, fail, postfit, 200-200",9, xAxis91);
   Signal_ppStaumI557_fail_postfit_projx1__59->SetMinimum(0.001);
   Signal_ppStaumI557_fail_postfit_projx1__59->SetStats(0);
   Signal_ppStaumI557_fail_postfit_projx1__59->SetLineColor(2);
   Signal_ppStaumI557_fail_postfit_projx1__59->SetLineWidth(2);
   Signal_ppStaumI557_fail_postfit_projx1__59->GetXaxis()->SetTitle("G_{i}^{Strips}");
   Signal_ppStaumI557_fail_postfit_projx1__59->GetXaxis()->SetLabelFont(42);
   Signal_ppStaumI557_fail_postfit_projx1__59->GetXaxis()->SetLabelSize(0.035);
   Signal_ppStaumI557_fail_postfit_projx1__59->GetXaxis()->SetTitleSize(0.035);
   Signal_ppStaumI557_fail_postfit_projx1__59->GetXaxis()->SetTitleFont(42);
   Signal_ppStaumI557_fail_postfit_projx1__59->GetYaxis()->SetTitle("Events / bin");
   Signal_ppStaumI557_fail_postfit_projx1__59->GetYaxis()->SetLabelFont(42);
   Signal_ppStaumI557_fail_postfit_projx1__59->GetYaxis()->SetLabelSize(0.035);
   Signal_ppStaumI557_fail_postfit_projx1__59->GetYaxis()->SetTitleSize(0.035);
   Signal_ppStaumI557_fail_postfit_projx1__59->GetYaxis()->SetTitleOffset(0);
   Signal_ppStaumI557_fail_postfit_projx1__59->GetYaxis()->SetTitleFont(42);
   Signal_ppStaumI557_fail_postfit_projx1__59->GetZaxis()->SetLabelFont(42);
   Signal_ppStaumI557_fail_postfit_projx1__59->GetZaxis()->SetLabelSize(0.035);
   Signal_ppStaumI557_fail_postfit_projx1__59->GetZaxis()->SetTitleSize(0.035);
   Signal_ppStaumI557_fail_postfit_projx1__59->GetZaxis()->SetTitleFont(42);
   Signal_ppStaumI557_fail_postfit_projx1__59->Draw("hist same");
   Double_t xAxis92[10] = {0, 0.05, 0.1, 0.15, 0.2, 0.25, 0.3, 0.35, 0.4, 1}; 
   
   TH1D *TotalBkg_fail_postfit_projx1__60 = new TH1D("TotalBkg_fail_postfit_projx1__60","TotalBkg, fail, postfit, 200-200",9, xAxis92);
   TotalBkg_fail_postfit_projx1__60->SetMinimum(0.001);
   TotalBkg_fail_postfit_projx1__60->SetStats(0);
   TotalBkg_fail_postfit_projx1__60->SetMarkerStyle(0);
   TotalBkg_fail_postfit_projx1__60->GetXaxis()->SetTitle("G_{i}^{Strips}");
   TotalBkg_fail_postfit_projx1__60->GetXaxis()->SetLabelFont(42);
   TotalBkg_fail_postfit_projx1__60->GetXaxis()->SetLabelSize(0.035);
   TotalBkg_fail_postfit_projx1__60->GetXaxis()->SetTitleSize(0.035);
   TotalBkg_fail_postfit_projx1__60->GetXaxis()->SetTitleFont(42);
   TotalBkg_fail_postfit_projx1__60->GetYaxis()->SetTitle("Events / bin");
   TotalBkg_fail_postfit_projx1__60->GetYaxis()->SetLabelFont(42);
   TotalBkg_fail_postfit_projx1__60->GetYaxis()->SetLabelSize(0.035);
   TotalBkg_fail_postfit_projx1__60->GetYaxis()->SetTitleSize(0.035);
   TotalBkg_fail_postfit_projx1__60->GetYaxis()->SetTitleOffset(0);
   TotalBkg_fail_postfit_projx1__60->GetYaxis()->SetTitleFont(42);
   TotalBkg_fail_postfit_projx1__60->GetZaxis()->SetLabelFont(42);
   TotalBkg_fail_postfit_projx1__60->GetZaxis()->SetLabelSize(0.035);
   TotalBkg_fail_postfit_projx1__60->GetZaxis()->SetTitleSize(0.035);
   TotalBkg_fail_postfit_projx1__60->GetZaxis()->SetTitleFont(42);
   TotalBkg_fail_postfit_projx1__60->Draw("hist same");
   Double_t xAxis93[10] = {0, 0.05, 0.1, 0.15, 0.2, 0.25, 0.3, 0.35, 0.4, 1}; 
   
   TH1D *TotalBkg_fail_postfit_projx1__61 = new TH1D("TotalBkg_fail_postfit_projx1__61","TotalBkg, fail, postfit, 200-200",9, xAxis93);
   TotalBkg_fail_postfit_projx1__61->SetMinimum(0.001);
   TotalBkg_fail_postfit_projx1__61->SetStats(0);
   TotalBkg_fail_postfit_projx1__61->SetFillColor(1);
   TotalBkg_fail_postfit_projx1__61->SetFillStyle(3354);
   TotalBkg_fail_postfit_projx1__61->SetLineWidth(0);
   TotalBkg_fail_postfit_projx1__61->SetMarkerStyle(0);
   TotalBkg_fail_postfit_projx1__61->GetXaxis()->SetTitle("G_{i}^{Strips}");
   TotalBkg_fail_postfit_projx1__61->GetXaxis()->SetLabelFont(42);
   TotalBkg_fail_postfit_projx1__61->GetXaxis()->SetLabelSize(0.035);
   TotalBkg_fail_postfit_projx1__61->GetXaxis()->SetTitleSize(0.035);
   TotalBkg_fail_postfit_projx1__61->GetXaxis()->SetTitleFont(42);
   TotalBkg_fail_postfit_projx1__61->GetYaxis()->SetTitle("Events / bin");
   TotalBkg_fail_postfit_projx1__61->GetYaxis()->SetLabelFont(42);
   TotalBkg_fail_postfit_projx1__61->GetYaxis()->SetLabelSize(0.035);
   TotalBkg_fail_postfit_projx1__61->GetYaxis()->SetTitleSize(0.035);
   TotalBkg_fail_postfit_projx1__61->GetYaxis()->SetTitleOffset(0);
   TotalBkg_fail_postfit_projx1__61->GetYaxis()->SetTitleFont(42);
   TotalBkg_fail_postfit_projx1__61->GetZaxis()->SetLabelFont(42);
   TotalBkg_fail_postfit_projx1__61->GetZaxis()->SetLabelSize(0.035);
   TotalBkg_fail_postfit_projx1__61->GetZaxis()->SetTitleSize(0.035);
   TotalBkg_fail_postfit_projx1__61->GetZaxis()->SetTitleFont(42);
   TotalBkg_fail_postfit_projx1__61->Draw("e2 same");
   Double_t xAxis94[10] = {0, 0.05, 0.1, 0.15, 0.2, 0.25, 0.3, 0.35, 0.4, 1}; 
   
   TH1D *data_obs_fail_postfit_projx1__62 = new TH1D("data_obs_fail_postfit_projx1__62","",9, xAxis94);
   data_obs_fail_postfit_projx1__62->SetMinimum(0.001);
   data_obs_fail_postfit_projx1__62->SetMaximum(0);
   data_obs_fail_postfit_projx1__62->SetStats(0);

   ci = TColor::GetColor("#000000");
   data_obs_fail_postfit_projx1__62->SetLineColor(ci);

   ci = TColor::GetColor("#000000");
   data_obs_fail_postfit_projx1__62->SetMarkerColor(ci);
   data_obs_fail_postfit_projx1__62->SetMarkerStyle(8);
   data_obs_fail_postfit_projx1__62->GetXaxis()->SetTitle("G_{i}^{Strips}");
   data_obs_fail_postfit_projx1__62->GetXaxis()->SetLabelFont(42);
   data_obs_fail_postfit_projx1__62->GetXaxis()->SetLabelOffset(0.05);
   data_obs_fail_postfit_projx1__62->GetXaxis()->SetLabelSize(0.07);
   data_obs_fail_postfit_projx1__62->GetXaxis()->SetTitleSize(0.09);
   data_obs_fail_postfit_projx1__62->GetXaxis()->SetTitleOffset(1.15);
   data_obs_fail_postfit_projx1__62->GetXaxis()->SetTitleFont(42);
   data_obs_fail_postfit_projx1__62->GetYaxis()->SetTitle("Events / bin");
   data_obs_fail_postfit_projx1__62->GetYaxis()->SetNdivisions(508);
   data_obs_fail_postfit_projx1__62->GetYaxis()->SetLabelFont(42);
   data_obs_fail_postfit_projx1__62->GetYaxis()->SetLabelSize(0.07);
   data_obs_fail_postfit_projx1__62->GetYaxis()->SetTitleSize(0.09);
   data_obs_fail_postfit_projx1__62->GetYaxis()->SetTitleOffset(0.8);
   data_obs_fail_postfit_projx1__62->GetYaxis()->SetTitleFont(42);
   data_obs_fail_postfit_projx1__62->GetZaxis()->SetLabelFont(42);
   data_obs_fail_postfit_projx1__62->GetZaxis()->SetLabelSize(0.035);
   data_obs_fail_postfit_projx1__62->GetZaxis()->SetTitleSize(0.035);
   data_obs_fail_postfit_projx1__62->GetZaxis()->SetTitleFont(42);
   data_obs_fail_postfit_projx1__62->Draw("pe X0 same");
   
   TLegend *leg = new TLegend(0.65,0.61,0.9,0.88,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(1001);
   TLegendEntry *entry=leg->AddEntry("data_obs_fail_postfit_projx1","Data","pe X0");

   ci = TColor::GetColor("#000000");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);

   ci = TColor::GetColor("#000000");
   entry->SetMarkerColor(ci);
   entry->SetMarkerStyle(8);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("TotalBkg_fail_postfit_projx1","Total bkg unc.","F");
   entry->SetFillColor(1);
   entry->SetFillStyle(3354);
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("Signal_gluino-1800_fail_postfit_projx1","HSCP gluino 1800 GeV","L");
   entry->SetLineColor(4);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("Signal_ppStau-557_fail_postfit_projx1","HSCP stau 557 GeV","L");
   entry->SetLineColor(2);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("Background_fail_postfit_projx1_stack_1_stack_1","Background","f");

   ci = TColor::GetColor("#ffff00");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = 1186;
   color = new TColor(ci, 1, 1, 1, " ", 0);
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   leg->Draw();
   Double_t xAxis95[10] = {0, 0.05, 0.1, 0.15, 0.2, 0.25, 0.3, 0.35, 0.4, 1}; 
   
   TH1D *data_obs_fail_postfit_projx1_copy__63 = new TH1D("data_obs_fail_postfit_projx1_copy__63","",9, xAxis95);
   data_obs_fail_postfit_projx1_copy__63->SetMinimum(0.001);
   data_obs_fail_postfit_projx1_copy__63->SetMaximum(0);
   data_obs_fail_postfit_projx1_copy__63->SetDirectory(0);
   data_obs_fail_postfit_projx1_copy__63->SetStats(0);

   ci = TColor::GetColor("#000000");
   data_obs_fail_postfit_projx1_copy__63->SetLineColor(ci);

   ci = TColor::GetColor("#000000");
   data_obs_fail_postfit_projx1_copy__63->SetMarkerColor(ci);
   data_obs_fail_postfit_projx1_copy__63->SetMarkerStyle(8);
   data_obs_fail_postfit_projx1_copy__63->GetXaxis()->SetTitle("G_{i}^{Strips}");
   data_obs_fail_postfit_projx1_copy__63->GetXaxis()->SetLabelFont(42);
   data_obs_fail_postfit_projx1_copy__63->GetXaxis()->SetLabelOffset(0.05);
   data_obs_fail_postfit_projx1_copy__63->GetXaxis()->SetLabelSize(0.07);
   data_obs_fail_postfit_projx1_copy__63->GetXaxis()->SetTitleSize(0.09);
   data_obs_fail_postfit_projx1_copy__63->GetXaxis()->SetTitleOffset(1.15);
   data_obs_fail_postfit_projx1_copy__63->GetXaxis()->SetTitleFont(42);
   data_obs_fail_postfit_projx1_copy__63->GetYaxis()->SetTitle("Events / bin");
   data_obs_fail_postfit_projx1_copy__63->GetYaxis()->SetNdivisions(508);
   data_obs_fail_postfit_projx1_copy__63->GetYaxis()->SetLabelFont(42);
   data_obs_fail_postfit_projx1_copy__63->GetYaxis()->SetLabelSize(0.07);
   data_obs_fail_postfit_projx1_copy__63->GetYaxis()->SetTitleSize(0.09);
   data_obs_fail_postfit_projx1_copy__63->GetYaxis()->SetTitleOffset(0.8);
   data_obs_fail_postfit_projx1_copy__63->GetYaxis()->SetTitleFont(42);
   data_obs_fail_postfit_projx1_copy__63->GetZaxis()->SetLabelFont(42);
   data_obs_fail_postfit_projx1_copy__63->GetZaxis()->SetLabelSize(0.035);
   data_obs_fail_postfit_projx1_copy__63->GetZaxis()->SetTitleSize(0.035);
   data_obs_fail_postfit_projx1_copy__63->GetZaxis()->SetTitleFont(42);
   data_obs_fail_postfit_projx1_copy__63->Draw("sameaxis");
   TLatex *   tex = new TLatex(0.21,0.83,"200 < p_{T} < 200 , F^{Pixels}_{i} < 0.9");
tex->SetNDC();
   tex->SetTextAlign(12);
   tex->SetTextFont(42);
   tex->SetTextSize(0.06);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.17,0.92,"CMS");
tex->SetNDC();
   tex->SetTextFont(61);
   tex->SetTextSize(0.0675);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.25,0.92,"Preliminary");
tex->SetNDC();
   tex->SetTextFont(52);
   tex->SetTextSize(0.0485);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.95,0.92,"101 fb^{-1} (13 TeV)");
tex->SetNDC();
   tex->SetTextAlign(31);
   tex->SetTextFont(42);
   tex->SetTextSize(0.07);
   tex->SetLineWidth(2);
   tex->Draw();
   data_obs_fail_postfit_projx1_main->Modified();
   plots_fit_b/base_figs/postfit_projx1_fail_logy->cd();
  
// ------------>Primitives in pad: data_obs_fail_postfit_projx1_sub
   TPad *data_obs_fail_postfit_projx1_sub = new TPad("data_obs_fail_postfit_projx1_sub", "data_obs_fail_postfit_projx1_sub",0,0,1,0.35);
   data_obs_fail_postfit_projx1_sub->Draw();
   data_obs_fail_postfit_projx1_sub->cd();
   data_obs_fail_postfit_projx1_sub->Range(-0.2179487,-6.023077,1.064103,2.9);
   data_obs_fail_postfit_projx1_sub->SetFillColor(0);
   data_obs_fail_postfit_projx1_sub->SetBorderMode(0);
   data_obs_fail_postfit_projx1_sub->SetBorderSize(2);
   data_obs_fail_postfit_projx1_sub->SetTickx(1);
   data_obs_fail_postfit_projx1_sub->SetTicky(1);
   data_obs_fail_postfit_projx1_sub->SetLeftMargin(0.17);
   data_obs_fail_postfit_projx1_sub->SetRightMargin(0.05);
   data_obs_fail_postfit_projx1_sub->SetTopMargin(0);
   data_obs_fail_postfit_projx1_sub->SetBottomMargin(0.35);
   data_obs_fail_postfit_projx1_sub->SetFrameFillStyle(0);
   data_obs_fail_postfit_projx1_sub->SetFrameBorderMode(0);
   data_obs_fail_postfit_projx1_sub->SetFrameFillStyle(0);
   data_obs_fail_postfit_projx1_sub->SetFrameBorderMode(0);
   Double_t xAxis96[10] = {0, 0.05, 0.1, 0.15, 0.2, 0.25, 0.3, 0.35, 0.4, 1}; 
   
   TH1D *data_obs_fail_postfit_projx1_pull__64 = new TH1D("data_obs_fail_postfit_projx1_pull__64","",9, xAxis96);
   data_obs_fail_postfit_projx1_pull__64->SetMinimum(-2.9);
   data_obs_fail_postfit_projx1_pull__64->SetMaximum(2.9);
   data_obs_fail_postfit_projx1_pull__64->SetEntries(18);
   data_obs_fail_postfit_projx1_pull__64->SetStats(0);

   ci = TColor::GetColor("#0000ff");
   data_obs_fail_postfit_projx1_pull__64->SetFillColor(ci);

   ci = TColor::GetColor("#000000");
   data_obs_fail_postfit_projx1_pull__64->SetLineColor(ci);

   ci = TColor::GetColor("#000000");
   data_obs_fail_postfit_projx1_pull__64->SetMarkerColor(ci);
   data_obs_fail_postfit_projx1_pull__64->SetMarkerStyle(8);
   data_obs_fail_postfit_projx1_pull__64->GetXaxis()->SetTitle("G_{i}^{Strips}");
   data_obs_fail_postfit_projx1_pull__64->GetXaxis()->SetLabelFont(42);
   data_obs_fail_postfit_projx1_pull__64->GetXaxis()->SetLabelOffset(0.05);
   data_obs_fail_postfit_projx1_pull__64->GetXaxis()->SetLabelSize(0.13);
   data_obs_fail_postfit_projx1_pull__64->GetXaxis()->SetTitleSize(0.15);
   data_obs_fail_postfit_projx1_pull__64->GetXaxis()->SetTitleOffset(1.15);
   data_obs_fail_postfit_projx1_pull__64->GetXaxis()->SetTitleFont(42);
   data_obs_fail_postfit_projx1_pull__64->GetYaxis()->SetTitle("(Data-Bkg)/#sigma");
   data_obs_fail_postfit_projx1_pull__64->GetYaxis()->SetNdivisions(306);
   data_obs_fail_postfit_projx1_pull__64->GetYaxis()->SetLabelFont(42);
   data_obs_fail_postfit_projx1_pull__64->GetYaxis()->SetLabelSize(0.13);
   data_obs_fail_postfit_projx1_pull__64->GetYaxis()->SetTitleSize(0.12);
   data_obs_fail_postfit_projx1_pull__64->GetYaxis()->SetTitleOffset(0.4);
   data_obs_fail_postfit_projx1_pull__64->GetYaxis()->SetTitleFont(42);
   data_obs_fail_postfit_projx1_pull__64->GetZaxis()->SetLabelFont(42);
   data_obs_fail_postfit_projx1_pull__64->GetZaxis()->SetLabelSize(0.035);
   data_obs_fail_postfit_projx1_pull__64->GetZaxis()->SetTitleSize(0.035);
   data_obs_fail_postfit_projx1_pull__64->GetZaxis()->SetTitleFont(42);
   data_obs_fail_postfit_projx1_pull__64->Draw("hist");
   data_obs_fail_postfit_projx1_sub->Modified();
   plots_fit_b/base_figs/postfit_projx1_fail_logy->cd();
   plots_fit_b/base_figs/postfit_projx1_fail_logy->Modified();
   plots_fit_b/base_figs/postfit_projx1_fail_logy->cd();
   plots_fit_b/base_figs/postfit_projx1_fail_logy->SetSelected(plots_fit_b/base_figs/postfit_projx1_fail_logy);
}
