void postfit_projx0_pass_logy()
{
//=========Macro generated from canvas: plots_fit_b/base_figs/postfit_projx0_pass_logy/plots_fit_b/base_figs/postfit_projx0_pass_logy
//=========  (Fri Jan 12 20:33:16 2024) by ROOT version 6.14/09
   TCanvas *plots_fit_b/base_figs/postfit_projx0_pass_logy = new TCanvas("plots_fit_b/base_figs/postfit_projx0_pass_logy", "plots_fit_b/base_figs/postfit_projx0_pass_logy",0,0,800,700);
   gStyle->SetOptFit(1);
   gStyle->SetOptStat(0);
   plots_fit_b/base_figs/postfit_projx0_pass_logy->SetHighLightColor(2);
   plots_fit_b/base_figs/postfit_projx0_pass_logy->Range(0,0,1,1);
   plots_fit_b/base_figs/postfit_projx0_pass_logy->SetFillColor(0);
   plots_fit_b/base_figs/postfit_projx0_pass_logy->SetBorderMode(0);
   plots_fit_b/base_figs/postfit_projx0_pass_logy->SetBorderSize(2);
   plots_fit_b/base_figs/postfit_projx0_pass_logy->SetTickx(1);
   plots_fit_b/base_figs/postfit_projx0_pass_logy->SetTicky(1);
   plots_fit_b/base_figs/postfit_projx0_pass_logy->SetLeftMargin(0.16);
   plots_fit_b/base_figs/postfit_projx0_pass_logy->SetRightMargin(0);
   plots_fit_b/base_figs/postfit_projx0_pass_logy->SetTopMargin(0);
   plots_fit_b/base_figs/postfit_projx0_pass_logy->SetBottomMargin(0);
   plots_fit_b/base_figs/postfit_projx0_pass_logy->SetFrameFillStyle(0);
   plots_fit_b/base_figs/postfit_projx0_pass_logy->SetFrameBorderMode(0);
  
// ------------>Primitives in pad: data_obs_pass_postfit_projx0_main
   TPad *data_obs_pass_postfit_projx0_main = new TPad("data_obs_pass_postfit_projx0_main", "data_obs_pass_postfit_projx0_main",0,0.35,1,1);
   data_obs_pass_postfit_projx0_main->Draw();
   data_obs_pass_postfit_projx0_main->cd();
   data_obs_pass_postfit_projx0_main->Range(-0.2179487,-2.139535,1.064103,1.348837);
   data_obs_pass_postfit_projx0_main->SetFillColor(0);
   data_obs_pass_postfit_projx0_main->SetBorderMode(0);
   data_obs_pass_postfit_projx0_main->SetBorderSize(2);
   data_obs_pass_postfit_projx0_main->SetLogy();
   data_obs_pass_postfit_projx0_main->SetTickx(1);
   data_obs_pass_postfit_projx0_main->SetTicky(1);
   data_obs_pass_postfit_projx0_main->SetLeftMargin(0.17);
   data_obs_pass_postfit_projx0_main->SetRightMargin(0.05);
   data_obs_pass_postfit_projx0_main->SetBottomMargin(0.04);
   data_obs_pass_postfit_projx0_main->SetFrameFillStyle(0);
   data_obs_pass_postfit_projx0_main->SetFrameBorderMode(0);
   data_obs_pass_postfit_projx0_main->SetFrameFillStyle(0);
   data_obs_pass_postfit_projx0_main->SetFrameBorderMode(0);
   Double_t xAxis217[10] = {0, 0.05, 0.1, 0.15, 0.2, 0.25, 0.3, 0.35, 0.4, 1}; 
   
   TH1D *data_obs_pass_postfit_projx0__145 = new TH1D("data_obs_pass_postfit_projx0__145","",9, xAxis217);
   data_obs_pass_postfit_projx0__145->SetMinimum(0.001);
   data_obs_pass_postfit_projx0__145->SetMaximum(0);
   data_obs_pass_postfit_projx0__145->SetStats(0);

   Int_t ci;      // for color index setting
   TColor *color; // for color definition with alpha
   ci = TColor::GetColor("#000000");
   data_obs_pass_postfit_projx0__145->SetLineColor(ci);

   ci = TColor::GetColor("#000000");
   data_obs_pass_postfit_projx0__145->SetMarkerColor(ci);
   data_obs_pass_postfit_projx0__145->SetMarkerStyle(8);
   data_obs_pass_postfit_projx0__145->GetXaxis()->SetTitle("G_{i}^{Strips}");
   data_obs_pass_postfit_projx0__145->GetXaxis()->SetLabelFont(42);
   data_obs_pass_postfit_projx0__145->GetXaxis()->SetLabelOffset(0.05);
   data_obs_pass_postfit_projx0__145->GetXaxis()->SetLabelSize(0.07);
   data_obs_pass_postfit_projx0__145->GetXaxis()->SetTitleSize(0.09);
   data_obs_pass_postfit_projx0__145->GetXaxis()->SetTitleOffset(1.15);
   data_obs_pass_postfit_projx0__145->GetXaxis()->SetTitleFont(42);
   data_obs_pass_postfit_projx0__145->GetYaxis()->SetTitle("Events / bin");
   data_obs_pass_postfit_projx0__145->GetYaxis()->SetNdivisions(508);
   data_obs_pass_postfit_projx0__145->GetYaxis()->SetLabelFont(42);
   data_obs_pass_postfit_projx0__145->GetYaxis()->SetLabelSize(0.07);
   data_obs_pass_postfit_projx0__145->GetYaxis()->SetTitleSize(0.09);
   data_obs_pass_postfit_projx0__145->GetYaxis()->SetTitleOffset(0.8);
   data_obs_pass_postfit_projx0__145->GetYaxis()->SetTitleFont(42);
   data_obs_pass_postfit_projx0__145->GetZaxis()->SetLabelFont(42);
   data_obs_pass_postfit_projx0__145->GetZaxis()->SetLabelSize(0.035);
   data_obs_pass_postfit_projx0__145->GetZaxis()->SetTitleSize(0.035);
   data_obs_pass_postfit_projx0__145->GetZaxis()->SetTitleFont(42);
   data_obs_pass_postfit_projx0__145->Draw("pe X0");
   
   THStack *postfit_projx0_pass_logy_stack = new THStack();
   postfit_projx0_pass_logy_stack->SetName("postfit_projx0_pass_logy_stack");
   postfit_projx0_pass_logy_stack->SetTitle("postfit_projx0_pass_logy_stack");
   postfit_projx0_pass_logy_stack->SetMinimum(0.001);
   Double_t xAxis218[10] = {0, 0.05, 0.1, 0.15, 0.2, 0.25, 0.3, 0.35, 0.4, 1}; 
   
   TH1F *postfit_projx0_pass_logy_stack_stack_37 = new TH1F("postfit_projx0_pass_logy_stack_stack_37","postfit_projx0_pass_logy_stack",9, xAxis218);
   postfit_projx0_pass_logy_stack_stack_37->SetMinimum(-0);
   postfit_projx0_pass_logy_stack_stack_37->SetMaximum(-nan);
   postfit_projx0_pass_logy_stack_stack_37->SetDirectory(0);
   postfit_projx0_pass_logy_stack_stack_37->SetStats(0);
   postfit_projx0_pass_logy_stack_stack_37->SetLineStyle(0);
   postfit_projx0_pass_logy_stack_stack_37->GetXaxis()->SetLabelFont(42);
   postfit_projx0_pass_logy_stack_stack_37->GetXaxis()->SetLabelOffset(0.007);
   postfit_projx0_pass_logy_stack_stack_37->GetXaxis()->SetLabelSize(0.05);
   postfit_projx0_pass_logy_stack_stack_37->GetXaxis()->SetTitleSize(0.08);
   postfit_projx0_pass_logy_stack_stack_37->GetXaxis()->SetTitleOffset(0.9);
   postfit_projx0_pass_logy_stack_stack_37->GetXaxis()->SetTitleFont(42);
   postfit_projx0_pass_logy_stack_stack_37->GetYaxis()->SetNdivisions(508);
   postfit_projx0_pass_logy_stack_stack_37->GetYaxis()->SetLabelFont(42);
   postfit_projx0_pass_logy_stack_stack_37->GetYaxis()->SetLabelOffset(0.007);
   postfit_projx0_pass_logy_stack_stack_37->GetYaxis()->SetLabelSize(0.05);
   postfit_projx0_pass_logy_stack_stack_37->GetYaxis()->SetTitleSize(0.08);
   postfit_projx0_pass_logy_stack_stack_37->GetYaxis()->SetTitleOffset(1.25);
   postfit_projx0_pass_logy_stack_stack_37->GetYaxis()->SetTitleFont(42);
   postfit_projx0_pass_logy_stack_stack_37->GetZaxis()->SetLabelFont(42);
   postfit_projx0_pass_logy_stack_stack_37->GetZaxis()->SetLabelOffset(0.007);
   postfit_projx0_pass_logy_stack_stack_37->GetZaxis()->SetLabelSize(0.05);
   postfit_projx0_pass_logy_stack_stack_37->GetZaxis()->SetTitleSize(0.08);
   postfit_projx0_pass_logy_stack_stack_37->GetZaxis()->SetTitleFont(42);
   postfit_projx0_pass_logy_stack->SetHistogram(postfit_projx0_pass_logy_stack_stack_37);
   
   Double_t xAxis219[10] = {0, 0.05, 0.1, 0.15, 0.2, 0.25, 0.3, 0.35, 0.4, 1}; 
   
   TH1D *Background_0x0_pass_postfit_projx0_stack_1 = new TH1D("Background_0x0_pass_postfit_projx0_stack_1","Background, pass, postfit, 200-200",9, xAxis219);
   Background_0x0_pass_postfit_projx0_stack_1->SetMinimum(0.001);
   Background_0x0_pass_postfit_projx0_stack_1->SetStats(0);

   ci = TColor::GetColor("#ffff00");
   Background_0x0_pass_postfit_projx0_stack_1->SetFillColor(ci);

   ci = 1197;
   color = new TColor(ci, 1, 1, 1, " ", 0);
   Background_0x0_pass_postfit_projx0_stack_1->SetLineColor(ci);
   Background_0x0_pass_postfit_projx0_stack_1->GetXaxis()->SetTitle("G_{i}^{Strips}");
   Background_0x0_pass_postfit_projx0_stack_1->GetXaxis()->SetLabelFont(42);
   Background_0x0_pass_postfit_projx0_stack_1->GetXaxis()->SetLabelSize(0.035);
   Background_0x0_pass_postfit_projx0_stack_1->GetXaxis()->SetTitleSize(0.035);
   Background_0x0_pass_postfit_projx0_stack_1->GetXaxis()->SetTitleFont(42);
   Background_0x0_pass_postfit_projx0_stack_1->GetYaxis()->SetTitle("Events / bin");
   Background_0x0_pass_postfit_projx0_stack_1->GetYaxis()->SetLabelFont(42);
   Background_0x0_pass_postfit_projx0_stack_1->GetYaxis()->SetLabelSize(0.035);
   Background_0x0_pass_postfit_projx0_stack_1->GetYaxis()->SetTitleSize(0.035);
   Background_0x0_pass_postfit_projx0_stack_1->GetYaxis()->SetTitleOffset(0);
   Background_0x0_pass_postfit_projx0_stack_1->GetYaxis()->SetTitleFont(42);
   Background_0x0_pass_postfit_projx0_stack_1->GetZaxis()->SetLabelFont(42);
   Background_0x0_pass_postfit_projx0_stack_1->GetZaxis()->SetLabelSize(0.035);
   Background_0x0_pass_postfit_projx0_stack_1->GetZaxis()->SetTitleSize(0.035);
   Background_0x0_pass_postfit_projx0_stack_1->GetZaxis()->SetTitleFont(42);
   postfit_projx0_pass_logy_stack->Add(Background_0x0_pass_postfit_projx0_stack_1,"");
   postfit_projx0_pass_logy_stack->Draw("hist same");
   
   postfit_projx0_pass_logy_stack = new THStack();
   postfit_projx0_pass_logy_stack->SetName("postfit_projx0_pass_logy_stack");
   postfit_projx0_pass_logy_stack->SetTitle("postfit_projx0_pass_logy_stack");
   postfit_projx0_pass_logy_stack->SetMinimum(0.001);
   Double_t xAxis220[10] = {0, 0.05, 0.1, 0.15, 0.2, 0.25, 0.3, 0.35, 0.4, 1}; 
   
   TH1F *postfit_projx0_pass_logy_stack_stack_37_stack_38 = new TH1F("postfit_projx0_pass_logy_stack_stack_37_stack_38","postfit_projx0_pass_logy_stack",9, xAxis220);
   postfit_projx0_pass_logy_stack_stack_37_stack_38->SetMinimum(-0);
   postfit_projx0_pass_logy_stack_stack_37_stack_38->SetMaximum(-nan);
   postfit_projx0_pass_logy_stack_stack_37_stack_38->SetDirectory(0);
   postfit_projx0_pass_logy_stack_stack_37_stack_38->SetStats(0);
   postfit_projx0_pass_logy_stack_stack_37_stack_38->SetLineStyle(0);
   postfit_projx0_pass_logy_stack_stack_37_stack_38->GetXaxis()->SetLabelFont(42);
   postfit_projx0_pass_logy_stack_stack_37_stack_38->GetXaxis()->SetLabelOffset(0.007);
   postfit_projx0_pass_logy_stack_stack_37_stack_38->GetXaxis()->SetLabelSize(0.05);
   postfit_projx0_pass_logy_stack_stack_37_stack_38->GetXaxis()->SetTitleSize(0.08);
   postfit_projx0_pass_logy_stack_stack_37_stack_38->GetXaxis()->SetTitleOffset(0.9);
   postfit_projx0_pass_logy_stack_stack_37_stack_38->GetXaxis()->SetTitleFont(42);
   postfit_projx0_pass_logy_stack_stack_37_stack_38->GetYaxis()->SetNdivisions(508);
   postfit_projx0_pass_logy_stack_stack_37_stack_38->GetYaxis()->SetLabelFont(42);
   postfit_projx0_pass_logy_stack_stack_37_stack_38->GetYaxis()->SetLabelOffset(0.007);
   postfit_projx0_pass_logy_stack_stack_37_stack_38->GetYaxis()->SetLabelSize(0.05);
   postfit_projx0_pass_logy_stack_stack_37_stack_38->GetYaxis()->SetTitleSize(0.08);
   postfit_projx0_pass_logy_stack_stack_37_stack_38->GetYaxis()->SetTitleOffset(1.25);
   postfit_projx0_pass_logy_stack_stack_37_stack_38->GetYaxis()->SetTitleFont(42);
   postfit_projx0_pass_logy_stack_stack_37_stack_38->GetZaxis()->SetLabelFont(42);
   postfit_projx0_pass_logy_stack_stack_37_stack_38->GetZaxis()->SetLabelOffset(0.007);
   postfit_projx0_pass_logy_stack_stack_37_stack_38->GetZaxis()->SetLabelSize(0.05);
   postfit_projx0_pass_logy_stack_stack_37_stack_38->GetZaxis()->SetTitleSize(0.08);
   postfit_projx0_pass_logy_stack_stack_37_stack_38->GetZaxis()->SetTitleFont(42);
   postfit_projx0_pass_logy_stack->SetHistogram(postfit_projx0_pass_logy_stack_stack_37_stack_38);
   
   Double_t xAxis221[10] = {0, 0.05, 0.1, 0.15, 0.2, 0.25, 0.3, 0.35, 0.4, 1}; 
   
   TH1D *Background_0x0_pass_postfit_projx0_stack_1_stack_1 = new TH1D("Background_0x0_pass_postfit_projx0_stack_1_stack_1","Background, pass, postfit, 200-200",9, xAxis221);
   Background_0x0_pass_postfit_projx0_stack_1_stack_1->SetMinimum(0.001);
   Background_0x0_pass_postfit_projx0_stack_1_stack_1->SetStats(0);

   ci = TColor::GetColor("#ffff00");
   Background_0x0_pass_postfit_projx0_stack_1_stack_1->SetFillColor(ci);

   ci = 1197;
   color = new TColor(ci, 1, 1, 1, " ", 0);
   Background_0x0_pass_postfit_projx0_stack_1_stack_1->SetLineColor(ci);
   Background_0x0_pass_postfit_projx0_stack_1_stack_1->GetXaxis()->SetTitle("G_{i}^{Strips}");
   Background_0x0_pass_postfit_projx0_stack_1_stack_1->GetXaxis()->SetLabelFont(42);
   Background_0x0_pass_postfit_projx0_stack_1_stack_1->GetXaxis()->SetLabelSize(0.035);
   Background_0x0_pass_postfit_projx0_stack_1_stack_1->GetXaxis()->SetTitleSize(0.035);
   Background_0x0_pass_postfit_projx0_stack_1_stack_1->GetXaxis()->SetTitleFont(42);
   Background_0x0_pass_postfit_projx0_stack_1_stack_1->GetYaxis()->SetTitle("Events / bin");
   Background_0x0_pass_postfit_projx0_stack_1_stack_1->GetYaxis()->SetLabelFont(42);
   Background_0x0_pass_postfit_projx0_stack_1_stack_1->GetYaxis()->SetLabelSize(0.035);
   Background_0x0_pass_postfit_projx0_stack_1_stack_1->GetYaxis()->SetTitleSize(0.035);
   Background_0x0_pass_postfit_projx0_stack_1_stack_1->GetYaxis()->SetTitleOffset(0);
   Background_0x0_pass_postfit_projx0_stack_1_stack_1->GetYaxis()->SetTitleFont(42);
   Background_0x0_pass_postfit_projx0_stack_1_stack_1->GetZaxis()->SetLabelFont(42);
   Background_0x0_pass_postfit_projx0_stack_1_stack_1->GetZaxis()->SetLabelSize(0.035);
   Background_0x0_pass_postfit_projx0_stack_1_stack_1->GetZaxis()->SetTitleSize(0.035);
   Background_0x0_pass_postfit_projx0_stack_1_stack_1->GetZaxis()->SetTitleFont(42);
   postfit_projx0_pass_logy_stack->Add(Background_0x0_pass_postfit_projx0_stack_1_stack_1,"");
   postfit_projx0_pass_logy_stack->Draw("hist same");
   Double_t xAxis222[10] = {0, 0.05, 0.1, 0.15, 0.2, 0.25, 0.3, 0.35, 0.4, 1}; 
   
   TH1D *Signal_gluinomI1800_pass_postfit_projx0__146 = new TH1D("Signal_gluinomI1800_pass_postfit_projx0__146","HSCP gluino 1800 GeV, pass, postfit, 200-200",9, xAxis222);
   Signal_gluinomI1800_pass_postfit_projx0__146->SetMinimum(0.001);
   Signal_gluinomI1800_pass_postfit_projx0__146->SetStats(0);
   Signal_gluinomI1800_pass_postfit_projx0__146->SetLineColor(4);
   Signal_gluinomI1800_pass_postfit_projx0__146->SetLineWidth(2);
   Signal_gluinomI1800_pass_postfit_projx0__146->GetXaxis()->SetTitle("G_{i}^{Strips}");
   Signal_gluinomI1800_pass_postfit_projx0__146->GetXaxis()->SetLabelFont(42);
   Signal_gluinomI1800_pass_postfit_projx0__146->GetXaxis()->SetLabelSize(0.035);
   Signal_gluinomI1800_pass_postfit_projx0__146->GetXaxis()->SetTitleSize(0.035);
   Signal_gluinomI1800_pass_postfit_projx0__146->GetXaxis()->SetTitleFont(42);
   Signal_gluinomI1800_pass_postfit_projx0__146->GetYaxis()->SetTitle("Events / bin");
   Signal_gluinomI1800_pass_postfit_projx0__146->GetYaxis()->SetLabelFont(42);
   Signal_gluinomI1800_pass_postfit_projx0__146->GetYaxis()->SetLabelSize(0.035);
   Signal_gluinomI1800_pass_postfit_projx0__146->GetYaxis()->SetTitleSize(0.035);
   Signal_gluinomI1800_pass_postfit_projx0__146->GetYaxis()->SetTitleOffset(0);
   Signal_gluinomI1800_pass_postfit_projx0__146->GetYaxis()->SetTitleFont(42);
   Signal_gluinomI1800_pass_postfit_projx0__146->GetZaxis()->SetLabelFont(42);
   Signal_gluinomI1800_pass_postfit_projx0__146->GetZaxis()->SetLabelSize(0.035);
   Signal_gluinomI1800_pass_postfit_projx0__146->GetZaxis()->SetTitleSize(0.035);
   Signal_gluinomI1800_pass_postfit_projx0__146->GetZaxis()->SetTitleFont(42);
   Signal_gluinomI1800_pass_postfit_projx0__146->Draw("hist same");
   Double_t xAxis223[10] = {0, 0.05, 0.1, 0.15, 0.2, 0.25, 0.3, 0.35, 0.4, 1}; 
   
   TH1D *Signal_ppStaumI557_pass_postfit_projx0__147 = new TH1D("Signal_ppStaumI557_pass_postfit_projx0__147","HSCP stau 557 GeV, pass, postfit, 200-200",9, xAxis223);
   Signal_ppStaumI557_pass_postfit_projx0__147->SetMinimum(0.001);
   Signal_ppStaumI557_pass_postfit_projx0__147->SetStats(0);
   Signal_ppStaumI557_pass_postfit_projx0__147->SetLineColor(2);
   Signal_ppStaumI557_pass_postfit_projx0__147->SetLineWidth(2);
   Signal_ppStaumI557_pass_postfit_projx0__147->GetXaxis()->SetTitle("G_{i}^{Strips}");
   Signal_ppStaumI557_pass_postfit_projx0__147->GetXaxis()->SetLabelFont(42);
   Signal_ppStaumI557_pass_postfit_projx0__147->GetXaxis()->SetLabelSize(0.035);
   Signal_ppStaumI557_pass_postfit_projx0__147->GetXaxis()->SetTitleSize(0.035);
   Signal_ppStaumI557_pass_postfit_projx0__147->GetXaxis()->SetTitleFont(42);
   Signal_ppStaumI557_pass_postfit_projx0__147->GetYaxis()->SetTitle("Events / bin");
   Signal_ppStaumI557_pass_postfit_projx0__147->GetYaxis()->SetLabelFont(42);
   Signal_ppStaumI557_pass_postfit_projx0__147->GetYaxis()->SetLabelSize(0.035);
   Signal_ppStaumI557_pass_postfit_projx0__147->GetYaxis()->SetTitleSize(0.035);
   Signal_ppStaumI557_pass_postfit_projx0__147->GetYaxis()->SetTitleOffset(0);
   Signal_ppStaumI557_pass_postfit_projx0__147->GetYaxis()->SetTitleFont(42);
   Signal_ppStaumI557_pass_postfit_projx0__147->GetZaxis()->SetLabelFont(42);
   Signal_ppStaumI557_pass_postfit_projx0__147->GetZaxis()->SetLabelSize(0.035);
   Signal_ppStaumI557_pass_postfit_projx0__147->GetZaxis()->SetTitleSize(0.035);
   Signal_ppStaumI557_pass_postfit_projx0__147->GetZaxis()->SetTitleFont(42);
   Signal_ppStaumI557_pass_postfit_projx0__147->Draw("hist same");
   Double_t xAxis224[10] = {0, 0.05, 0.1, 0.15, 0.2, 0.25, 0.3, 0.35, 0.4, 1}; 
   
   TH1D *TotalBkg_pass_postfit_projx0__148 = new TH1D("TotalBkg_pass_postfit_projx0__148","TotalBkg, pass, postfit, 200-200",9, xAxis224);
   TotalBkg_pass_postfit_projx0__148->SetMinimum(0.001);
   TotalBkg_pass_postfit_projx0__148->SetStats(0);
   TotalBkg_pass_postfit_projx0__148->SetMarkerStyle(0);
   TotalBkg_pass_postfit_projx0__148->GetXaxis()->SetTitle("G_{i}^{Strips}");
   TotalBkg_pass_postfit_projx0__148->GetXaxis()->SetLabelFont(42);
   TotalBkg_pass_postfit_projx0__148->GetXaxis()->SetLabelSize(0.035);
   TotalBkg_pass_postfit_projx0__148->GetXaxis()->SetTitleSize(0.035);
   TotalBkg_pass_postfit_projx0__148->GetXaxis()->SetTitleFont(42);
   TotalBkg_pass_postfit_projx0__148->GetYaxis()->SetTitle("Events / bin");
   TotalBkg_pass_postfit_projx0__148->GetYaxis()->SetLabelFont(42);
   TotalBkg_pass_postfit_projx0__148->GetYaxis()->SetLabelSize(0.035);
   TotalBkg_pass_postfit_projx0__148->GetYaxis()->SetTitleSize(0.035);
   TotalBkg_pass_postfit_projx0__148->GetYaxis()->SetTitleOffset(0);
   TotalBkg_pass_postfit_projx0__148->GetYaxis()->SetTitleFont(42);
   TotalBkg_pass_postfit_projx0__148->GetZaxis()->SetLabelFont(42);
   TotalBkg_pass_postfit_projx0__148->GetZaxis()->SetLabelSize(0.035);
   TotalBkg_pass_postfit_projx0__148->GetZaxis()->SetTitleSize(0.035);
   TotalBkg_pass_postfit_projx0__148->GetZaxis()->SetTitleFont(42);
   TotalBkg_pass_postfit_projx0__148->Draw("hist same");
   Double_t xAxis225[10] = {0, 0.05, 0.1, 0.15, 0.2, 0.25, 0.3, 0.35, 0.4, 1}; 
   
   TH1D *TotalBkg_pass_postfit_projx0__149 = new TH1D("TotalBkg_pass_postfit_projx0__149","TotalBkg, pass, postfit, 200-200",9, xAxis225);
   TotalBkg_pass_postfit_projx0__149->SetMinimum(0.001);
   TotalBkg_pass_postfit_projx0__149->SetStats(0);
   TotalBkg_pass_postfit_projx0__149->SetFillColor(1);
   TotalBkg_pass_postfit_projx0__149->SetFillStyle(3354);
   TotalBkg_pass_postfit_projx0__149->SetLineWidth(0);
   TotalBkg_pass_postfit_projx0__149->SetMarkerStyle(0);
   TotalBkg_pass_postfit_projx0__149->GetXaxis()->SetTitle("G_{i}^{Strips}");
   TotalBkg_pass_postfit_projx0__149->GetXaxis()->SetLabelFont(42);
   TotalBkg_pass_postfit_projx0__149->GetXaxis()->SetLabelSize(0.035);
   TotalBkg_pass_postfit_projx0__149->GetXaxis()->SetTitleSize(0.035);
   TotalBkg_pass_postfit_projx0__149->GetXaxis()->SetTitleFont(42);
   TotalBkg_pass_postfit_projx0__149->GetYaxis()->SetTitle("Events / bin");
   TotalBkg_pass_postfit_projx0__149->GetYaxis()->SetLabelFont(42);
   TotalBkg_pass_postfit_projx0__149->GetYaxis()->SetLabelSize(0.035);
   TotalBkg_pass_postfit_projx0__149->GetYaxis()->SetTitleSize(0.035);
   TotalBkg_pass_postfit_projx0__149->GetYaxis()->SetTitleOffset(0);
   TotalBkg_pass_postfit_projx0__149->GetYaxis()->SetTitleFont(42);
   TotalBkg_pass_postfit_projx0__149->GetZaxis()->SetLabelFont(42);
   TotalBkg_pass_postfit_projx0__149->GetZaxis()->SetLabelSize(0.035);
   TotalBkg_pass_postfit_projx0__149->GetZaxis()->SetTitleSize(0.035);
   TotalBkg_pass_postfit_projx0__149->GetZaxis()->SetTitleFont(42);
   TotalBkg_pass_postfit_projx0__149->Draw("e2 same");
   Double_t xAxis226[10] = {0, 0.05, 0.1, 0.15, 0.2, 0.25, 0.3, 0.35, 0.4, 1}; 
   
   TH1D *data_obs_pass_postfit_projx0__150 = new TH1D("data_obs_pass_postfit_projx0__150","",9, xAxis226);
   data_obs_pass_postfit_projx0__150->SetMinimum(0.001);
   data_obs_pass_postfit_projx0__150->SetMaximum(0);
   data_obs_pass_postfit_projx0__150->SetStats(0);

   ci = TColor::GetColor("#000000");
   data_obs_pass_postfit_projx0__150->SetLineColor(ci);

   ci = TColor::GetColor("#000000");
   data_obs_pass_postfit_projx0__150->SetMarkerColor(ci);
   data_obs_pass_postfit_projx0__150->SetMarkerStyle(8);
   data_obs_pass_postfit_projx0__150->GetXaxis()->SetTitle("G_{i}^{Strips}");
   data_obs_pass_postfit_projx0__150->GetXaxis()->SetLabelFont(42);
   data_obs_pass_postfit_projx0__150->GetXaxis()->SetLabelOffset(0.05);
   data_obs_pass_postfit_projx0__150->GetXaxis()->SetLabelSize(0.07);
   data_obs_pass_postfit_projx0__150->GetXaxis()->SetTitleSize(0.09);
   data_obs_pass_postfit_projx0__150->GetXaxis()->SetTitleOffset(1.15);
   data_obs_pass_postfit_projx0__150->GetXaxis()->SetTitleFont(42);
   data_obs_pass_postfit_projx0__150->GetYaxis()->SetTitle("Events / bin");
   data_obs_pass_postfit_projx0__150->GetYaxis()->SetNdivisions(508);
   data_obs_pass_postfit_projx0__150->GetYaxis()->SetLabelFont(42);
   data_obs_pass_postfit_projx0__150->GetYaxis()->SetLabelSize(0.07);
   data_obs_pass_postfit_projx0__150->GetYaxis()->SetTitleSize(0.09);
   data_obs_pass_postfit_projx0__150->GetYaxis()->SetTitleOffset(0.8);
   data_obs_pass_postfit_projx0__150->GetYaxis()->SetTitleFont(42);
   data_obs_pass_postfit_projx0__150->GetZaxis()->SetLabelFont(42);
   data_obs_pass_postfit_projx0__150->GetZaxis()->SetLabelSize(0.035);
   data_obs_pass_postfit_projx0__150->GetZaxis()->SetTitleSize(0.035);
   data_obs_pass_postfit_projx0__150->GetZaxis()->SetTitleFont(42);
   data_obs_pass_postfit_projx0__150->Draw("pe X0 same");
   
   TLegend *leg = new TLegend(0.65,0.61,0.9,0.88,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(1001);
   TLegendEntry *entry=leg->AddEntry("data_obs_pass_postfit_projx0","Data","pe X0");

   ci = TColor::GetColor("#000000");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);

   ci = TColor::GetColor("#000000");
   entry->SetMarkerColor(ci);
   entry->SetMarkerStyle(8);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("TotalBkg_pass_postfit_projx0","Total bkg unc.","F");
   entry->SetFillColor(1);
   entry->SetFillStyle(3354);
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("Signal_gluino-1800_pass_postfit_projx0","HSCP gluino 1800 GeV","L");
   entry->SetLineColor(4);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("Signal_ppStau-557_pass_postfit_projx0","HSCP stau 557 GeV","L");
   entry->SetLineColor(2);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("Background_0x0_pass_postfit_projx0_stack_1_stack_1","Background","f");

   ci = TColor::GetColor("#ffff00");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = 1197;
   color = new TColor(ci, 1, 1, 1, " ", 0);
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   leg->Draw();
   Double_t xAxis227[10] = {0, 0.05, 0.1, 0.15, 0.2, 0.25, 0.3, 0.35, 0.4, 1}; 
   
   TH1D *data_obs_pass_postfit_projx0_copy__151 = new TH1D("data_obs_pass_postfit_projx0_copy__151","",9, xAxis227);
   data_obs_pass_postfit_projx0_copy__151->SetMinimum(0.001);
   data_obs_pass_postfit_projx0_copy__151->SetMaximum(0);
   data_obs_pass_postfit_projx0_copy__151->SetDirectory(0);
   data_obs_pass_postfit_projx0_copy__151->SetStats(0);

   ci = TColor::GetColor("#000000");
   data_obs_pass_postfit_projx0_copy__151->SetLineColor(ci);

   ci = TColor::GetColor("#000000");
   data_obs_pass_postfit_projx0_copy__151->SetMarkerColor(ci);
   data_obs_pass_postfit_projx0_copy__151->SetMarkerStyle(8);
   data_obs_pass_postfit_projx0_copy__151->GetXaxis()->SetTitle("G_{i}^{Strips}");
   data_obs_pass_postfit_projx0_copy__151->GetXaxis()->SetLabelFont(42);
   data_obs_pass_postfit_projx0_copy__151->GetXaxis()->SetLabelOffset(0.05);
   data_obs_pass_postfit_projx0_copy__151->GetXaxis()->SetLabelSize(0.07);
   data_obs_pass_postfit_projx0_copy__151->GetXaxis()->SetTitleSize(0.09);
   data_obs_pass_postfit_projx0_copy__151->GetXaxis()->SetTitleOffset(1.15);
   data_obs_pass_postfit_projx0_copy__151->GetXaxis()->SetTitleFont(42);
   data_obs_pass_postfit_projx0_copy__151->GetYaxis()->SetTitle("Events / bin");
   data_obs_pass_postfit_projx0_copy__151->GetYaxis()->SetNdivisions(508);
   data_obs_pass_postfit_projx0_copy__151->GetYaxis()->SetLabelFont(42);
   data_obs_pass_postfit_projx0_copy__151->GetYaxis()->SetLabelSize(0.07);
   data_obs_pass_postfit_projx0_copy__151->GetYaxis()->SetTitleSize(0.09);
   data_obs_pass_postfit_projx0_copy__151->GetYaxis()->SetTitleOffset(0.8);
   data_obs_pass_postfit_projx0_copy__151->GetYaxis()->SetTitleFont(42);
   data_obs_pass_postfit_projx0_copy__151->GetZaxis()->SetLabelFont(42);
   data_obs_pass_postfit_projx0_copy__151->GetZaxis()->SetLabelSize(0.035);
   data_obs_pass_postfit_projx0_copy__151->GetZaxis()->SetTitleSize(0.035);
   data_obs_pass_postfit_projx0_copy__151->GetZaxis()->SetTitleFont(42);
   data_obs_pass_postfit_projx0_copy__151->Draw("sameaxis");
   TLatex *   tex = new TLatex(0.21,0.83,"200 < p_{T} < 200 , F^{Pixels}_{i} > 0.9");
tex->SetNDC();
   tex->SetTextAlign(12);
   tex->SetTextFont(42);
   tex->SetTextSize(0.06);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.17,0.92,"CMS");
tex->SetNDC();
   tex->SetTextFont(61);
   tex->SetTextSize(0.0675);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.25,0.92,"Preliminary");
tex->SetNDC();
   tex->SetTextFont(52);
   tex->SetTextSize(0.0485);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.95,0.92,"101 fb^{-1} (13 TeV)");
tex->SetNDC();
   tex->SetTextAlign(31);
   tex->SetTextFont(42);
   tex->SetTextSize(0.07);
   tex->SetLineWidth(2);
   tex->Draw();
   data_obs_pass_postfit_projx0_main->Modified();
   plots_fit_b/base_figs/postfit_projx0_pass_logy->cd();
  
// ------------>Primitives in pad: data_obs_pass_postfit_projx0_sub
   TPad *data_obs_pass_postfit_projx0_sub = new TPad("data_obs_pass_postfit_projx0_sub", "data_obs_pass_postfit_projx0_sub",0,0,1,0.35);
   data_obs_pass_postfit_projx0_sub->Draw();
   data_obs_pass_postfit_projx0_sub->cd();
   data_obs_pass_postfit_projx0_sub->Range(-0.2179487,-6.023077,1.064103,2.9);
   data_obs_pass_postfit_projx0_sub->SetFillColor(0);
   data_obs_pass_postfit_projx0_sub->SetBorderMode(0);
   data_obs_pass_postfit_projx0_sub->SetBorderSize(2);
   data_obs_pass_postfit_projx0_sub->SetTickx(1);
   data_obs_pass_postfit_projx0_sub->SetTicky(1);
   data_obs_pass_postfit_projx0_sub->SetLeftMargin(0.17);
   data_obs_pass_postfit_projx0_sub->SetRightMargin(0.05);
   data_obs_pass_postfit_projx0_sub->SetTopMargin(0);
   data_obs_pass_postfit_projx0_sub->SetBottomMargin(0.35);
   data_obs_pass_postfit_projx0_sub->SetFrameFillStyle(0);
   data_obs_pass_postfit_projx0_sub->SetFrameBorderMode(0);
   data_obs_pass_postfit_projx0_sub->SetFrameFillStyle(0);
   data_obs_pass_postfit_projx0_sub->SetFrameBorderMode(0);
   Double_t xAxis228[10] = {0, 0.05, 0.1, 0.15, 0.2, 0.25, 0.3, 0.35, 0.4, 1}; 
   
   TH1D *data_obs_pass_postfit_projx0_pull__152 = new TH1D("data_obs_pass_postfit_projx0_pull__152","",9, xAxis228);
   data_obs_pass_postfit_projx0_pull__152->SetMinimum(-2.9);
   data_obs_pass_postfit_projx0_pull__152->SetMaximum(2.9);
   data_obs_pass_postfit_projx0_pull__152->SetEntries(18);
   data_obs_pass_postfit_projx0_pull__152->SetStats(0);

   ci = TColor::GetColor("#0000ff");
   data_obs_pass_postfit_projx0_pull__152->SetFillColor(ci);

   ci = TColor::GetColor("#000000");
   data_obs_pass_postfit_projx0_pull__152->SetLineColor(ci);

   ci = TColor::GetColor("#000000");
   data_obs_pass_postfit_projx0_pull__152->SetMarkerColor(ci);
   data_obs_pass_postfit_projx0_pull__152->SetMarkerStyle(8);
   data_obs_pass_postfit_projx0_pull__152->GetXaxis()->SetTitle("G_{i}^{Strips}");
   data_obs_pass_postfit_projx0_pull__152->GetXaxis()->SetLabelFont(42);
   data_obs_pass_postfit_projx0_pull__152->GetXaxis()->SetLabelOffset(0.05);
   data_obs_pass_postfit_projx0_pull__152->GetXaxis()->SetLabelSize(0.13);
   data_obs_pass_postfit_projx0_pull__152->GetXaxis()->SetTitleSize(0.15);
   data_obs_pass_postfit_projx0_pull__152->GetXaxis()->SetTitleOffset(1.15);
   data_obs_pass_postfit_projx0_pull__152->GetXaxis()->SetTitleFont(42);
   data_obs_pass_postfit_projx0_pull__152->GetYaxis()->SetTitle("(Data-Bkg)/#sigma");
   data_obs_pass_postfit_projx0_pull__152->GetYaxis()->SetNdivisions(306);
   data_obs_pass_postfit_projx0_pull__152->GetYaxis()->SetLabelFont(42);
   data_obs_pass_postfit_projx0_pull__152->GetYaxis()->SetLabelSize(0.13);
   data_obs_pass_postfit_projx0_pull__152->GetYaxis()->SetTitleSize(0.12);
   data_obs_pass_postfit_projx0_pull__152->GetYaxis()->SetTitleOffset(0.4);
   data_obs_pass_postfit_projx0_pull__152->GetYaxis()->SetTitleFont(42);
   data_obs_pass_postfit_projx0_pull__152->GetZaxis()->SetLabelFont(42);
   data_obs_pass_postfit_projx0_pull__152->GetZaxis()->SetLabelSize(0.035);
   data_obs_pass_postfit_projx0_pull__152->GetZaxis()->SetTitleSize(0.035);
   data_obs_pass_postfit_projx0_pull__152->GetZaxis()->SetTitleFont(42);
   data_obs_pass_postfit_projx0_pull__152->Draw("hist");
   data_obs_pass_postfit_projx0_sub->Modified();
   plots_fit_b/base_figs/postfit_projx0_pass_logy->cd();
   plots_fit_b/base_figs/postfit_projx0_pass_logy->Modified();
   plots_fit_b/base_figs/postfit_projx0_pass_logy->cd();
   plots_fit_b/base_figs/postfit_projx0_pass_logy->SetSelected(plots_fit_b/base_figs/postfit_projx0_pass_logy);
}
