void postfit_projx1_pass()
{
//=========Macro generated from canvas: plots_fit_b/base_figs/postfit_projx1_pass/plots_fit_b/base_figs/postfit_projx1_pass
//=========  (Fri Jan 12 20:33:16 2024) by ROOT version 6.14/09
   TCanvas *plots_fit_b/base_figs/postfit_projx1_pass = new TCanvas("plots_fit_b/base_figs/postfit_projx1_pass", "plots_fit_b/base_figs/postfit_projx1_pass",0,0,800,700);
   gStyle->SetOptFit(1);
   gStyle->SetOptStat(0);
   plots_fit_b/base_figs/postfit_projx1_pass->SetHighLightColor(2);
   plots_fit_b/base_figs/postfit_projx1_pass->Range(0,0,1,1);
   plots_fit_b/base_figs/postfit_projx1_pass->SetFillColor(0);
   plots_fit_b/base_figs/postfit_projx1_pass->SetBorderMode(0);
   plots_fit_b/base_figs/postfit_projx1_pass->SetBorderSize(2);
   plots_fit_b/base_figs/postfit_projx1_pass->SetTickx(1);
   plots_fit_b/base_figs/postfit_projx1_pass->SetTicky(1);
   plots_fit_b/base_figs/postfit_projx1_pass->SetLeftMargin(0.16);
   plots_fit_b/base_figs/postfit_projx1_pass->SetRightMargin(0);
   plots_fit_b/base_figs/postfit_projx1_pass->SetTopMargin(0);
   plots_fit_b/base_figs/postfit_projx1_pass->SetBottomMargin(0);
   plots_fit_b/base_figs/postfit_projx1_pass->SetFrameFillStyle(0);
   plots_fit_b/base_figs/postfit_projx1_pass->SetFrameBorderMode(0);
  
// ------------>Primitives in pad: data_obs_pass_postfit_projx1_main
   TPad *data_obs_pass_postfit_projx1_main = new TPad("data_obs_pass_postfit_projx1_main", "data_obs_pass_postfit_projx1_main",0,0.35,1,1);
   data_obs_pass_postfit_projx1_main->Draw();
   data_obs_pass_postfit_projx1_main->cd();
   data_obs_pass_postfit_projx1_main->Range(-0.2179487,-0.04651163,1.064103,1.116279);
   data_obs_pass_postfit_projx1_main->SetFillColor(0);
   data_obs_pass_postfit_projx1_main->SetBorderMode(0);
   data_obs_pass_postfit_projx1_main->SetBorderSize(2);
   data_obs_pass_postfit_projx1_main->SetTickx(1);
   data_obs_pass_postfit_projx1_main->SetTicky(1);
   data_obs_pass_postfit_projx1_main->SetLeftMargin(0.17);
   data_obs_pass_postfit_projx1_main->SetRightMargin(0.05);
   data_obs_pass_postfit_projx1_main->SetBottomMargin(0.04);
   data_obs_pass_postfit_projx1_main->SetFrameFillStyle(0);
   data_obs_pass_postfit_projx1_main->SetFrameBorderMode(0);
   data_obs_pass_postfit_projx1_main->SetFrameFillStyle(0);
   data_obs_pass_postfit_projx1_main->SetFrameBorderMode(0);
   Double_t xAxis157[10] = {0, 0.05, 0.1, 0.15, 0.2, 0.25, 0.3, 0.35, 0.4, 1}; 
   
   TH1D *data_obs_pass_postfit_projx1__105 = new TH1D("data_obs_pass_postfit_projx1__105","",9, xAxis157);
   data_obs_pass_postfit_projx1__105->SetMinimum(0);
   data_obs_pass_postfit_projx1__105->SetMaximum(0);
   data_obs_pass_postfit_projx1__105->SetStats(0);

   Int_t ci;      // for color index setting
   TColor *color; // for color definition with alpha
   ci = TColor::GetColor("#000000");
   data_obs_pass_postfit_projx1__105->SetLineColor(ci);

   ci = TColor::GetColor("#000000");
   data_obs_pass_postfit_projx1__105->SetMarkerColor(ci);
   data_obs_pass_postfit_projx1__105->SetMarkerStyle(8);
   data_obs_pass_postfit_projx1__105->GetXaxis()->SetTitle("G_{i}^{Strips}");
   data_obs_pass_postfit_projx1__105->GetXaxis()->SetLabelFont(42);
   data_obs_pass_postfit_projx1__105->GetXaxis()->SetLabelOffset(0.05);
   data_obs_pass_postfit_projx1__105->GetXaxis()->SetLabelSize(0.07);
   data_obs_pass_postfit_projx1__105->GetXaxis()->SetTitleSize(0.09);
   data_obs_pass_postfit_projx1__105->GetXaxis()->SetTitleOffset(1.15);
   data_obs_pass_postfit_projx1__105->GetXaxis()->SetTitleFont(42);
   data_obs_pass_postfit_projx1__105->GetYaxis()->SetTitle("Events / bin");
   data_obs_pass_postfit_projx1__105->GetYaxis()->SetNdivisions(508);
   data_obs_pass_postfit_projx1__105->GetYaxis()->SetLabelFont(42);
   data_obs_pass_postfit_projx1__105->GetYaxis()->SetLabelSize(0.07);
   data_obs_pass_postfit_projx1__105->GetYaxis()->SetTitleSize(0.09);
   data_obs_pass_postfit_projx1__105->GetYaxis()->SetTitleOffset(0.8);
   data_obs_pass_postfit_projx1__105->GetYaxis()->SetTitleFont(42);
   data_obs_pass_postfit_projx1__105->GetZaxis()->SetLabelFont(42);
   data_obs_pass_postfit_projx1__105->GetZaxis()->SetLabelSize(0.035);
   data_obs_pass_postfit_projx1__105->GetZaxis()->SetTitleSize(0.035);
   data_obs_pass_postfit_projx1__105->GetZaxis()->SetTitleFont(42);
   data_obs_pass_postfit_projx1__105->Draw("pe X0");
   
   THStack *postfit_projx1_pass_stack = new THStack();
   postfit_projx1_pass_stack->SetName("postfit_projx1_pass_stack");
   postfit_projx1_pass_stack->SetTitle("postfit_projx1_pass_stack");
   Double_t xAxis158[10] = {0, 0.05, 0.1, 0.15, 0.2, 0.25, 0.3, 0.35, 0.4, 1}; 
   
   TH1F *postfit_projx1_pass_stack_stack_27 = new TH1F("postfit_projx1_pass_stack_stack_27","postfit_projx1_pass_stack",9, xAxis158);
   postfit_projx1_pass_stack_stack_27->SetMinimum(0);
   postfit_projx1_pass_stack_stack_27->SetMaximum(0);
   postfit_projx1_pass_stack_stack_27->SetDirectory(0);
   postfit_projx1_pass_stack_stack_27->SetStats(0);
   postfit_projx1_pass_stack_stack_27->SetLineStyle(0);
   postfit_projx1_pass_stack_stack_27->GetXaxis()->SetLabelFont(42);
   postfit_projx1_pass_stack_stack_27->GetXaxis()->SetLabelOffset(0.007);
   postfit_projx1_pass_stack_stack_27->GetXaxis()->SetLabelSize(0.05);
   postfit_projx1_pass_stack_stack_27->GetXaxis()->SetTitleSize(0.08);
   postfit_projx1_pass_stack_stack_27->GetXaxis()->SetTitleOffset(0.9);
   postfit_projx1_pass_stack_stack_27->GetXaxis()->SetTitleFont(42);
   postfit_projx1_pass_stack_stack_27->GetYaxis()->SetNdivisions(508);
   postfit_projx1_pass_stack_stack_27->GetYaxis()->SetLabelFont(42);
   postfit_projx1_pass_stack_stack_27->GetYaxis()->SetLabelOffset(0.007);
   postfit_projx1_pass_stack_stack_27->GetYaxis()->SetLabelSize(0.05);
   postfit_projx1_pass_stack_stack_27->GetYaxis()->SetTitleSize(0.08);
   postfit_projx1_pass_stack_stack_27->GetYaxis()->SetTitleOffset(1.25);
   postfit_projx1_pass_stack_stack_27->GetYaxis()->SetTitleFont(42);
   postfit_projx1_pass_stack_stack_27->GetZaxis()->SetLabelFont(42);
   postfit_projx1_pass_stack_stack_27->GetZaxis()->SetLabelOffset(0.007);
   postfit_projx1_pass_stack_stack_27->GetZaxis()->SetLabelSize(0.05);
   postfit_projx1_pass_stack_stack_27->GetZaxis()->SetTitleSize(0.08);
   postfit_projx1_pass_stack_stack_27->GetZaxis()->SetTitleFont(42);
   postfit_projx1_pass_stack->SetHistogram(postfit_projx1_pass_stack_stack_27);
   
   Double_t xAxis159[10] = {0, 0.05, 0.1, 0.15, 0.2, 0.25, 0.3, 0.35, 0.4, 1}; 
   
   TH1D *Background_0x0_pass_postfit_projx1_stack_1 = new TH1D("Background_0x0_pass_postfit_projx1_stack_1","Background, pass, postfit, 200-200",9, xAxis159);
   Background_0x0_pass_postfit_projx1_stack_1->SetMinimum(0);
   Background_0x0_pass_postfit_projx1_stack_1->SetStats(0);

   ci = TColor::GetColor("#ffff00");
   Background_0x0_pass_postfit_projx1_stack_1->SetFillColor(ci);

   ci = 1198;
   color = new TColor(ci, 1, 1, 1, " ", 0);
   Background_0x0_pass_postfit_projx1_stack_1->SetLineColor(ci);
   Background_0x0_pass_postfit_projx1_stack_1->GetXaxis()->SetTitle("G_{i}^{Strips}");
   Background_0x0_pass_postfit_projx1_stack_1->GetXaxis()->SetLabelFont(42);
   Background_0x0_pass_postfit_projx1_stack_1->GetXaxis()->SetLabelSize(0.035);
   Background_0x0_pass_postfit_projx1_stack_1->GetXaxis()->SetTitleSize(0.035);
   Background_0x0_pass_postfit_projx1_stack_1->GetXaxis()->SetTitleFont(42);
   Background_0x0_pass_postfit_projx1_stack_1->GetYaxis()->SetTitle("Events / bin");
   Background_0x0_pass_postfit_projx1_stack_1->GetYaxis()->SetLabelFont(42);
   Background_0x0_pass_postfit_projx1_stack_1->GetYaxis()->SetLabelSize(0.035);
   Background_0x0_pass_postfit_projx1_stack_1->GetYaxis()->SetTitleSize(0.035);
   Background_0x0_pass_postfit_projx1_stack_1->GetYaxis()->SetTitleOffset(0);
   Background_0x0_pass_postfit_projx1_stack_1->GetYaxis()->SetTitleFont(42);
   Background_0x0_pass_postfit_projx1_stack_1->GetZaxis()->SetLabelFont(42);
   Background_0x0_pass_postfit_projx1_stack_1->GetZaxis()->SetLabelSize(0.035);
   Background_0x0_pass_postfit_projx1_stack_1->GetZaxis()->SetTitleSize(0.035);
   Background_0x0_pass_postfit_projx1_stack_1->GetZaxis()->SetTitleFont(42);
   postfit_projx1_pass_stack->Add(Background_0x0_pass_postfit_projx1_stack_1,"");
   postfit_projx1_pass_stack->Draw("hist same");
   
   postfit_projx1_pass_stack = new THStack();
   postfit_projx1_pass_stack->SetName("postfit_projx1_pass_stack");
   postfit_projx1_pass_stack->SetTitle("postfit_projx1_pass_stack");
   Double_t xAxis160[10] = {0, 0.05, 0.1, 0.15, 0.2, 0.25, 0.3, 0.35, 0.4, 1}; 
   
   TH1F *postfit_projx1_pass_stack_stack_27_stack_28 = new TH1F("postfit_projx1_pass_stack_stack_27_stack_28","postfit_projx1_pass_stack",9, xAxis160);
   postfit_projx1_pass_stack_stack_27_stack_28->SetMinimum(0);
   postfit_projx1_pass_stack_stack_27_stack_28->SetMaximum(0);
   postfit_projx1_pass_stack_stack_27_stack_28->SetDirectory(0);
   postfit_projx1_pass_stack_stack_27_stack_28->SetStats(0);
   postfit_projx1_pass_stack_stack_27_stack_28->SetLineStyle(0);
   postfit_projx1_pass_stack_stack_27_stack_28->GetXaxis()->SetLabelFont(42);
   postfit_projx1_pass_stack_stack_27_stack_28->GetXaxis()->SetLabelOffset(0.007);
   postfit_projx1_pass_stack_stack_27_stack_28->GetXaxis()->SetLabelSize(0.05);
   postfit_projx1_pass_stack_stack_27_stack_28->GetXaxis()->SetTitleSize(0.08);
   postfit_projx1_pass_stack_stack_27_stack_28->GetXaxis()->SetTitleOffset(0.9);
   postfit_projx1_pass_stack_stack_27_stack_28->GetXaxis()->SetTitleFont(42);
   postfit_projx1_pass_stack_stack_27_stack_28->GetYaxis()->SetNdivisions(508);
   postfit_projx1_pass_stack_stack_27_stack_28->GetYaxis()->SetLabelFont(42);
   postfit_projx1_pass_stack_stack_27_stack_28->GetYaxis()->SetLabelOffset(0.007);
   postfit_projx1_pass_stack_stack_27_stack_28->GetYaxis()->SetLabelSize(0.05);
   postfit_projx1_pass_stack_stack_27_stack_28->GetYaxis()->SetTitleSize(0.08);
   postfit_projx1_pass_stack_stack_27_stack_28->GetYaxis()->SetTitleOffset(1.25);
   postfit_projx1_pass_stack_stack_27_stack_28->GetYaxis()->SetTitleFont(42);
   postfit_projx1_pass_stack_stack_27_stack_28->GetZaxis()->SetLabelFont(42);
   postfit_projx1_pass_stack_stack_27_stack_28->GetZaxis()->SetLabelOffset(0.007);
   postfit_projx1_pass_stack_stack_27_stack_28->GetZaxis()->SetLabelSize(0.05);
   postfit_projx1_pass_stack_stack_27_stack_28->GetZaxis()->SetTitleSize(0.08);
   postfit_projx1_pass_stack_stack_27_stack_28->GetZaxis()->SetTitleFont(42);
   postfit_projx1_pass_stack->SetHistogram(postfit_projx1_pass_stack_stack_27_stack_28);
   
   Double_t xAxis161[10] = {0, 0.05, 0.1, 0.15, 0.2, 0.25, 0.3, 0.35, 0.4, 1}; 
   
   TH1D *Background_0x0_pass_postfit_projx1_stack_1_stack_1 = new TH1D("Background_0x0_pass_postfit_projx1_stack_1_stack_1","Background, pass, postfit, 200-200",9, xAxis161);
   Background_0x0_pass_postfit_projx1_stack_1_stack_1->SetMinimum(0);
   Background_0x0_pass_postfit_projx1_stack_1_stack_1->SetStats(0);

   ci = TColor::GetColor("#ffff00");
   Background_0x0_pass_postfit_projx1_stack_1_stack_1->SetFillColor(ci);

   ci = 1198;
   color = new TColor(ci, 1, 1, 1, " ", 0);
   Background_0x0_pass_postfit_projx1_stack_1_stack_1->SetLineColor(ci);
   Background_0x0_pass_postfit_projx1_stack_1_stack_1->GetXaxis()->SetTitle("G_{i}^{Strips}");
   Background_0x0_pass_postfit_projx1_stack_1_stack_1->GetXaxis()->SetLabelFont(42);
   Background_0x0_pass_postfit_projx1_stack_1_stack_1->GetXaxis()->SetLabelSize(0.035);
   Background_0x0_pass_postfit_projx1_stack_1_stack_1->GetXaxis()->SetTitleSize(0.035);
   Background_0x0_pass_postfit_projx1_stack_1_stack_1->GetXaxis()->SetTitleFont(42);
   Background_0x0_pass_postfit_projx1_stack_1_stack_1->GetYaxis()->SetTitle("Events / bin");
   Background_0x0_pass_postfit_projx1_stack_1_stack_1->GetYaxis()->SetLabelFont(42);
   Background_0x0_pass_postfit_projx1_stack_1_stack_1->GetYaxis()->SetLabelSize(0.035);
   Background_0x0_pass_postfit_projx1_stack_1_stack_1->GetYaxis()->SetTitleSize(0.035);
   Background_0x0_pass_postfit_projx1_stack_1_stack_1->GetYaxis()->SetTitleOffset(0);
   Background_0x0_pass_postfit_projx1_stack_1_stack_1->GetYaxis()->SetTitleFont(42);
   Background_0x0_pass_postfit_projx1_stack_1_stack_1->GetZaxis()->SetLabelFont(42);
   Background_0x0_pass_postfit_projx1_stack_1_stack_1->GetZaxis()->SetLabelSize(0.035);
   Background_0x0_pass_postfit_projx1_stack_1_stack_1->GetZaxis()->SetTitleSize(0.035);
   Background_0x0_pass_postfit_projx1_stack_1_stack_1->GetZaxis()->SetTitleFont(42);
   postfit_projx1_pass_stack->Add(Background_0x0_pass_postfit_projx1_stack_1_stack_1,"");
   postfit_projx1_pass_stack->Draw("hist same");
   Double_t xAxis162[10] = {0, 0.05, 0.1, 0.15, 0.2, 0.25, 0.3, 0.35, 0.4, 1}; 
   
   TH1D *Signal_gluinomI1800_pass_postfit_projx1__106 = new TH1D("Signal_gluinomI1800_pass_postfit_projx1__106","HSCP gluino 1800 GeV, pass, postfit, 200-200",9, xAxis162);
   Signal_gluinomI1800_pass_postfit_projx1__106->SetMinimum(0);
   Signal_gluinomI1800_pass_postfit_projx1__106->SetStats(0);
   Signal_gluinomI1800_pass_postfit_projx1__106->SetLineColor(4);
   Signal_gluinomI1800_pass_postfit_projx1__106->SetLineWidth(2);
   Signal_gluinomI1800_pass_postfit_projx1__106->GetXaxis()->SetTitle("G_{i}^{Strips}");
   Signal_gluinomI1800_pass_postfit_projx1__106->GetXaxis()->SetLabelFont(42);
   Signal_gluinomI1800_pass_postfit_projx1__106->GetXaxis()->SetLabelSize(0.035);
   Signal_gluinomI1800_pass_postfit_projx1__106->GetXaxis()->SetTitleSize(0.035);
   Signal_gluinomI1800_pass_postfit_projx1__106->GetXaxis()->SetTitleFont(42);
   Signal_gluinomI1800_pass_postfit_projx1__106->GetYaxis()->SetTitle("Events / bin");
   Signal_gluinomI1800_pass_postfit_projx1__106->GetYaxis()->SetLabelFont(42);
   Signal_gluinomI1800_pass_postfit_projx1__106->GetYaxis()->SetLabelSize(0.035);
   Signal_gluinomI1800_pass_postfit_projx1__106->GetYaxis()->SetTitleSize(0.035);
   Signal_gluinomI1800_pass_postfit_projx1__106->GetYaxis()->SetTitleOffset(0);
   Signal_gluinomI1800_pass_postfit_projx1__106->GetYaxis()->SetTitleFont(42);
   Signal_gluinomI1800_pass_postfit_projx1__106->GetZaxis()->SetLabelFont(42);
   Signal_gluinomI1800_pass_postfit_projx1__106->GetZaxis()->SetLabelSize(0.035);
   Signal_gluinomI1800_pass_postfit_projx1__106->GetZaxis()->SetTitleSize(0.035);
   Signal_gluinomI1800_pass_postfit_projx1__106->GetZaxis()->SetTitleFont(42);
   Signal_gluinomI1800_pass_postfit_projx1__106->Draw("hist same");
   Double_t xAxis163[10] = {0, 0.05, 0.1, 0.15, 0.2, 0.25, 0.3, 0.35, 0.4, 1}; 
   
   TH1D *Signal_ppStaumI557_pass_postfit_projx1__107 = new TH1D("Signal_ppStaumI557_pass_postfit_projx1__107","HSCP stau 557 GeV, pass, postfit, 200-200",9, xAxis163);
   Signal_ppStaumI557_pass_postfit_projx1__107->SetMinimum(0);
   Signal_ppStaumI557_pass_postfit_projx1__107->SetStats(0);
   Signal_ppStaumI557_pass_postfit_projx1__107->SetLineColor(2);
   Signal_ppStaumI557_pass_postfit_projx1__107->SetLineWidth(2);
   Signal_ppStaumI557_pass_postfit_projx1__107->GetXaxis()->SetTitle("G_{i}^{Strips}");
   Signal_ppStaumI557_pass_postfit_projx1__107->GetXaxis()->SetLabelFont(42);
   Signal_ppStaumI557_pass_postfit_projx1__107->GetXaxis()->SetLabelSize(0.035);
   Signal_ppStaumI557_pass_postfit_projx1__107->GetXaxis()->SetTitleSize(0.035);
   Signal_ppStaumI557_pass_postfit_projx1__107->GetXaxis()->SetTitleFont(42);
   Signal_ppStaumI557_pass_postfit_projx1__107->GetYaxis()->SetTitle("Events / bin");
   Signal_ppStaumI557_pass_postfit_projx1__107->GetYaxis()->SetLabelFont(42);
   Signal_ppStaumI557_pass_postfit_projx1__107->GetYaxis()->SetLabelSize(0.035);
   Signal_ppStaumI557_pass_postfit_projx1__107->GetYaxis()->SetTitleSize(0.035);
   Signal_ppStaumI557_pass_postfit_projx1__107->GetYaxis()->SetTitleOffset(0);
   Signal_ppStaumI557_pass_postfit_projx1__107->GetYaxis()->SetTitleFont(42);
   Signal_ppStaumI557_pass_postfit_projx1__107->GetZaxis()->SetLabelFont(42);
   Signal_ppStaumI557_pass_postfit_projx1__107->GetZaxis()->SetLabelSize(0.035);
   Signal_ppStaumI557_pass_postfit_projx1__107->GetZaxis()->SetTitleSize(0.035);
   Signal_ppStaumI557_pass_postfit_projx1__107->GetZaxis()->SetTitleFont(42);
   Signal_ppStaumI557_pass_postfit_projx1__107->Draw("hist same");
   Double_t xAxis164[10] = {0, 0.05, 0.1, 0.15, 0.2, 0.25, 0.3, 0.35, 0.4, 1}; 
   
   TH1D *TotalBkg_pass_postfit_projx1__108 = new TH1D("TotalBkg_pass_postfit_projx1__108","TotalBkg, pass, postfit, 200-200",9, xAxis164);
   TotalBkg_pass_postfit_projx1__108->SetMinimum(0);
   TotalBkg_pass_postfit_projx1__108->SetStats(0);
   TotalBkg_pass_postfit_projx1__108->SetMarkerStyle(0);
   TotalBkg_pass_postfit_projx1__108->GetXaxis()->SetTitle("G_{i}^{Strips}");
   TotalBkg_pass_postfit_projx1__108->GetXaxis()->SetLabelFont(42);
   TotalBkg_pass_postfit_projx1__108->GetXaxis()->SetLabelSize(0.035);
   TotalBkg_pass_postfit_projx1__108->GetXaxis()->SetTitleSize(0.035);
   TotalBkg_pass_postfit_projx1__108->GetXaxis()->SetTitleFont(42);
   TotalBkg_pass_postfit_projx1__108->GetYaxis()->SetTitle("Events / bin");
   TotalBkg_pass_postfit_projx1__108->GetYaxis()->SetLabelFont(42);
   TotalBkg_pass_postfit_projx1__108->GetYaxis()->SetLabelSize(0.035);
   TotalBkg_pass_postfit_projx1__108->GetYaxis()->SetTitleSize(0.035);
   TotalBkg_pass_postfit_projx1__108->GetYaxis()->SetTitleOffset(0);
   TotalBkg_pass_postfit_projx1__108->GetYaxis()->SetTitleFont(42);
   TotalBkg_pass_postfit_projx1__108->GetZaxis()->SetLabelFont(42);
   TotalBkg_pass_postfit_projx1__108->GetZaxis()->SetLabelSize(0.035);
   TotalBkg_pass_postfit_projx1__108->GetZaxis()->SetTitleSize(0.035);
   TotalBkg_pass_postfit_projx1__108->GetZaxis()->SetTitleFont(42);
   TotalBkg_pass_postfit_projx1__108->Draw("hist same");
   Double_t xAxis165[10] = {0, 0.05, 0.1, 0.15, 0.2, 0.25, 0.3, 0.35, 0.4, 1}; 
   
   TH1D *TotalBkg_pass_postfit_projx1__109 = new TH1D("TotalBkg_pass_postfit_projx1__109","TotalBkg, pass, postfit, 200-200",9, xAxis165);
   TotalBkg_pass_postfit_projx1__109->SetMinimum(0);
   TotalBkg_pass_postfit_projx1__109->SetStats(0);
   TotalBkg_pass_postfit_projx1__109->SetFillColor(1);
   TotalBkg_pass_postfit_projx1__109->SetFillStyle(3354);
   TotalBkg_pass_postfit_projx1__109->SetLineWidth(0);
   TotalBkg_pass_postfit_projx1__109->SetMarkerStyle(0);
   TotalBkg_pass_postfit_projx1__109->GetXaxis()->SetTitle("G_{i}^{Strips}");
   TotalBkg_pass_postfit_projx1__109->GetXaxis()->SetLabelFont(42);
   TotalBkg_pass_postfit_projx1__109->GetXaxis()->SetLabelSize(0.035);
   TotalBkg_pass_postfit_projx1__109->GetXaxis()->SetTitleSize(0.035);
   TotalBkg_pass_postfit_projx1__109->GetXaxis()->SetTitleFont(42);
   TotalBkg_pass_postfit_projx1__109->GetYaxis()->SetTitle("Events / bin");
   TotalBkg_pass_postfit_projx1__109->GetYaxis()->SetLabelFont(42);
   TotalBkg_pass_postfit_projx1__109->GetYaxis()->SetLabelSize(0.035);
   TotalBkg_pass_postfit_projx1__109->GetYaxis()->SetTitleSize(0.035);
   TotalBkg_pass_postfit_projx1__109->GetYaxis()->SetTitleOffset(0);
   TotalBkg_pass_postfit_projx1__109->GetYaxis()->SetTitleFont(42);
   TotalBkg_pass_postfit_projx1__109->GetZaxis()->SetLabelFont(42);
   TotalBkg_pass_postfit_projx1__109->GetZaxis()->SetLabelSize(0.035);
   TotalBkg_pass_postfit_projx1__109->GetZaxis()->SetTitleSize(0.035);
   TotalBkg_pass_postfit_projx1__109->GetZaxis()->SetTitleFont(42);
   TotalBkg_pass_postfit_projx1__109->Draw("e2 same");
   Double_t xAxis166[10] = {0, 0.05, 0.1, 0.15, 0.2, 0.25, 0.3, 0.35, 0.4, 1}; 
   
   TH1D *data_obs_pass_postfit_projx1__110 = new TH1D("data_obs_pass_postfit_projx1__110","",9, xAxis166);
   data_obs_pass_postfit_projx1__110->SetMinimum(0);
   data_obs_pass_postfit_projx1__110->SetMaximum(0);
   data_obs_pass_postfit_projx1__110->SetStats(0);

   ci = TColor::GetColor("#000000");
   data_obs_pass_postfit_projx1__110->SetLineColor(ci);

   ci = TColor::GetColor("#000000");
   data_obs_pass_postfit_projx1__110->SetMarkerColor(ci);
   data_obs_pass_postfit_projx1__110->SetMarkerStyle(8);
   data_obs_pass_postfit_projx1__110->GetXaxis()->SetTitle("G_{i}^{Strips}");
   data_obs_pass_postfit_projx1__110->GetXaxis()->SetLabelFont(42);
   data_obs_pass_postfit_projx1__110->GetXaxis()->SetLabelOffset(0.05);
   data_obs_pass_postfit_projx1__110->GetXaxis()->SetLabelSize(0.07);
   data_obs_pass_postfit_projx1__110->GetXaxis()->SetTitleSize(0.09);
   data_obs_pass_postfit_projx1__110->GetXaxis()->SetTitleOffset(1.15);
   data_obs_pass_postfit_projx1__110->GetXaxis()->SetTitleFont(42);
   data_obs_pass_postfit_projx1__110->GetYaxis()->SetTitle("Events / bin");
   data_obs_pass_postfit_projx1__110->GetYaxis()->SetNdivisions(508);
   data_obs_pass_postfit_projx1__110->GetYaxis()->SetLabelFont(42);
   data_obs_pass_postfit_projx1__110->GetYaxis()->SetLabelSize(0.07);
   data_obs_pass_postfit_projx1__110->GetYaxis()->SetTitleSize(0.09);
   data_obs_pass_postfit_projx1__110->GetYaxis()->SetTitleOffset(0.8);
   data_obs_pass_postfit_projx1__110->GetYaxis()->SetTitleFont(42);
   data_obs_pass_postfit_projx1__110->GetZaxis()->SetLabelFont(42);
   data_obs_pass_postfit_projx1__110->GetZaxis()->SetLabelSize(0.035);
   data_obs_pass_postfit_projx1__110->GetZaxis()->SetTitleSize(0.035);
   data_obs_pass_postfit_projx1__110->GetZaxis()->SetTitleFont(42);
   data_obs_pass_postfit_projx1__110->Draw("pe X0 same");
   
   TLegend *leg = new TLegend(0.65,0.61,0.9,0.88,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(1001);
   TLegendEntry *entry=leg->AddEntry("data_obs_pass_postfit_projx1","Data","pe X0");

   ci = TColor::GetColor("#000000");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);

   ci = TColor::GetColor("#000000");
   entry->SetMarkerColor(ci);
   entry->SetMarkerStyle(8);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("TotalBkg_pass_postfit_projx1","Total bkg unc.","F");
   entry->SetFillColor(1);
   entry->SetFillStyle(3354);
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("Signal_gluino-1800_pass_postfit_projx1","HSCP gluino 1800 GeV","L");
   entry->SetLineColor(4);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("Signal_ppStau-557_pass_postfit_projx1","HSCP stau 557 GeV","L");
   entry->SetLineColor(2);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("Background_0x0_pass_postfit_projx1_stack_1_stack_1","Background","f");

   ci = TColor::GetColor("#ffff00");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = 1198;
   color = new TColor(ci, 1, 1, 1, " ", 0);
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   leg->Draw();
   Double_t xAxis167[10] = {0, 0.05, 0.1, 0.15, 0.2, 0.25, 0.3, 0.35, 0.4, 1}; 
   
   TH1D *data_obs_pass_postfit_projx1_copy__111 = new TH1D("data_obs_pass_postfit_projx1_copy__111","",9, xAxis167);
   data_obs_pass_postfit_projx1_copy__111->SetMinimum(0);
   data_obs_pass_postfit_projx1_copy__111->SetMaximum(0);
   data_obs_pass_postfit_projx1_copy__111->SetDirectory(0);
   data_obs_pass_postfit_projx1_copy__111->SetStats(0);

   ci = TColor::GetColor("#000000");
   data_obs_pass_postfit_projx1_copy__111->SetLineColor(ci);

   ci = TColor::GetColor("#000000");
   data_obs_pass_postfit_projx1_copy__111->SetMarkerColor(ci);
   data_obs_pass_postfit_projx1_copy__111->SetMarkerStyle(8);
   data_obs_pass_postfit_projx1_copy__111->GetXaxis()->SetTitle("G_{i}^{Strips}");
   data_obs_pass_postfit_projx1_copy__111->GetXaxis()->SetLabelFont(42);
   data_obs_pass_postfit_projx1_copy__111->GetXaxis()->SetLabelOffset(0.05);
   data_obs_pass_postfit_projx1_copy__111->GetXaxis()->SetLabelSize(0.07);
   data_obs_pass_postfit_projx1_copy__111->GetXaxis()->SetTitleSize(0.09);
   data_obs_pass_postfit_projx1_copy__111->GetXaxis()->SetTitleOffset(1.15);
   data_obs_pass_postfit_projx1_copy__111->GetXaxis()->SetTitleFont(42);
   data_obs_pass_postfit_projx1_copy__111->GetYaxis()->SetTitle("Events / bin");
   data_obs_pass_postfit_projx1_copy__111->GetYaxis()->SetNdivisions(508);
   data_obs_pass_postfit_projx1_copy__111->GetYaxis()->SetLabelFont(42);
   data_obs_pass_postfit_projx1_copy__111->GetYaxis()->SetLabelSize(0.07);
   data_obs_pass_postfit_projx1_copy__111->GetYaxis()->SetTitleSize(0.09);
   data_obs_pass_postfit_projx1_copy__111->GetYaxis()->SetTitleOffset(0.8);
   data_obs_pass_postfit_projx1_copy__111->GetYaxis()->SetTitleFont(42);
   data_obs_pass_postfit_projx1_copy__111->GetZaxis()->SetLabelFont(42);
   data_obs_pass_postfit_projx1_copy__111->GetZaxis()->SetLabelSize(0.035);
   data_obs_pass_postfit_projx1_copy__111->GetZaxis()->SetTitleSize(0.035);
   data_obs_pass_postfit_projx1_copy__111->GetZaxis()->SetTitleFont(42);
   data_obs_pass_postfit_projx1_copy__111->Draw("sameaxis");
   TLatex *   tex = new TLatex(0.21,0.83,"200 < p_{T} < 200 , F^{Pixels}_{i} > 0.9");
tex->SetNDC();
   tex->SetTextAlign(12);
   tex->SetTextFont(42);
   tex->SetTextSize(0.06);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.17,0.92,"CMS");
tex->SetNDC();
   tex->SetTextFont(61);
   tex->SetTextSize(0.0675);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.25,0.92,"Preliminary");
tex->SetNDC();
   tex->SetTextFont(52);
   tex->SetTextSize(0.0485);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.95,0.92,"101 fb^{-1} (13 TeV)");
tex->SetNDC();
   tex->SetTextAlign(31);
   tex->SetTextFont(42);
   tex->SetTextSize(0.07);
   tex->SetLineWidth(2);
   tex->Draw();
   data_obs_pass_postfit_projx1_main->Modified();
   plots_fit_b/base_figs/postfit_projx1_pass->cd();
  
// ------------>Primitives in pad: data_obs_pass_postfit_projx1_sub
   TPad *data_obs_pass_postfit_projx1_sub = new TPad("data_obs_pass_postfit_projx1_sub", "data_obs_pass_postfit_projx1_sub",0,0,1,0.35);
   data_obs_pass_postfit_projx1_sub->Draw();
   data_obs_pass_postfit_projx1_sub->cd();
   data_obs_pass_postfit_projx1_sub->Range(-0.2179487,-6.023077,1.064103,2.9);
   data_obs_pass_postfit_projx1_sub->SetFillColor(0);
   data_obs_pass_postfit_projx1_sub->SetBorderMode(0);
   data_obs_pass_postfit_projx1_sub->SetBorderSize(2);
   data_obs_pass_postfit_projx1_sub->SetTickx(1);
   data_obs_pass_postfit_projx1_sub->SetTicky(1);
   data_obs_pass_postfit_projx1_sub->SetLeftMargin(0.17);
   data_obs_pass_postfit_projx1_sub->SetRightMargin(0.05);
   data_obs_pass_postfit_projx1_sub->SetTopMargin(0);
   data_obs_pass_postfit_projx1_sub->SetBottomMargin(0.35);
   data_obs_pass_postfit_projx1_sub->SetFrameFillStyle(0);
   data_obs_pass_postfit_projx1_sub->SetFrameBorderMode(0);
   data_obs_pass_postfit_projx1_sub->SetFrameFillStyle(0);
   data_obs_pass_postfit_projx1_sub->SetFrameBorderMode(0);
   Double_t xAxis168[10] = {0, 0.05, 0.1, 0.15, 0.2, 0.25, 0.3, 0.35, 0.4, 1}; 
   
   TH1D *data_obs_pass_postfit_projx1_pull__112 = new TH1D("data_obs_pass_postfit_projx1_pull__112","",9, xAxis168);
   data_obs_pass_postfit_projx1_pull__112->SetMinimum(-2.9);
   data_obs_pass_postfit_projx1_pull__112->SetMaximum(2.9);
   data_obs_pass_postfit_projx1_pull__112->SetEntries(18);
   data_obs_pass_postfit_projx1_pull__112->SetStats(0);

   ci = TColor::GetColor("#0000ff");
   data_obs_pass_postfit_projx1_pull__112->SetFillColor(ci);

   ci = TColor::GetColor("#000000");
   data_obs_pass_postfit_projx1_pull__112->SetLineColor(ci);

   ci = TColor::GetColor("#000000");
   data_obs_pass_postfit_projx1_pull__112->SetMarkerColor(ci);
   data_obs_pass_postfit_projx1_pull__112->SetMarkerStyle(8);
   data_obs_pass_postfit_projx1_pull__112->GetXaxis()->SetTitle("G_{i}^{Strips}");
   data_obs_pass_postfit_projx1_pull__112->GetXaxis()->SetLabelFont(42);
   data_obs_pass_postfit_projx1_pull__112->GetXaxis()->SetLabelOffset(0.05);
   data_obs_pass_postfit_projx1_pull__112->GetXaxis()->SetLabelSize(0.13);
   data_obs_pass_postfit_projx1_pull__112->GetXaxis()->SetTitleSize(0.15);
   data_obs_pass_postfit_projx1_pull__112->GetXaxis()->SetTitleOffset(1.15);
   data_obs_pass_postfit_projx1_pull__112->GetXaxis()->SetTitleFont(42);
   data_obs_pass_postfit_projx1_pull__112->GetYaxis()->SetTitle("(Data-Bkg)/#sigma");
   data_obs_pass_postfit_projx1_pull__112->GetYaxis()->SetNdivisions(306);
   data_obs_pass_postfit_projx1_pull__112->GetYaxis()->SetLabelFont(42);
   data_obs_pass_postfit_projx1_pull__112->GetYaxis()->SetLabelSize(0.13);
   data_obs_pass_postfit_projx1_pull__112->GetYaxis()->SetTitleSize(0.12);
   data_obs_pass_postfit_projx1_pull__112->GetYaxis()->SetTitleOffset(0.4);
   data_obs_pass_postfit_projx1_pull__112->GetYaxis()->SetTitleFont(42);
   data_obs_pass_postfit_projx1_pull__112->GetZaxis()->SetLabelFont(42);
   data_obs_pass_postfit_projx1_pull__112->GetZaxis()->SetLabelSize(0.035);
   data_obs_pass_postfit_projx1_pull__112->GetZaxis()->SetTitleSize(0.035);
   data_obs_pass_postfit_projx1_pull__112->GetZaxis()->SetTitleFont(42);
   data_obs_pass_postfit_projx1_pull__112->Draw("hist");
   data_obs_pass_postfit_projx1_sub->Modified();
   plots_fit_b/base_figs/postfit_projx1_pass->cd();
   plots_fit_b/base_figs/postfit_projx1_pass->Modified();
   plots_fit_b/base_figs/postfit_projx1_pass->cd();
   plots_fit_b/base_figs/postfit_projx1_pass->SetSelected(plots_fit_b/base_figs/postfit_projx1_pass);
}
