void postfit_projy1_fail()
{
//=========Macro generated from canvas: plots_fit_b/base_figs/postfit_projy1_fail/plots_fit_b/base_figs/postfit_projy1_fail
//=========  (Fri Jan 12 20:33:15 2024) by ROOT version 6.14/09
   TCanvas *plots_fit_b/base_figs/postfit_projy1_fail = new TCanvas("plots_fit_b/base_figs/postfit_projy1_fail", "plots_fit_b/base_figs/postfit_projy1_fail",0,0,800,700);
   gStyle->SetOptFit(1);
   gStyle->SetOptStat(0);
   plots_fit_b/base_figs/postfit_projy1_fail->SetHighLightColor(2);
   plots_fit_b/base_figs/postfit_projy1_fail->Range(0,0,1,1);
   plots_fit_b/base_figs/postfit_projy1_fail->SetFillColor(0);
   plots_fit_b/base_figs/postfit_projy1_fail->SetBorderMode(0);
   plots_fit_b/base_figs/postfit_projy1_fail->SetBorderSize(2);
   plots_fit_b/base_figs/postfit_projy1_fail->SetTickx(1);
   plots_fit_b/base_figs/postfit_projy1_fail->SetTicky(1);
   plots_fit_b/base_figs/postfit_projy1_fail->SetLeftMargin(0.16);
   plots_fit_b/base_figs/postfit_projy1_fail->SetRightMargin(0);
   plots_fit_b/base_figs/postfit_projy1_fail->SetTopMargin(0);
   plots_fit_b/base_figs/postfit_projy1_fail->SetBottomMargin(0);
   plots_fit_b/base_figs/postfit_projy1_fail->SetFrameFillStyle(0);
   plots_fit_b/base_figs/postfit_projy1_fail->SetFrameBorderMode(0);
  
// ------------>Primitives in pad: data_obs_fail_postfit_projy1_main
   TPad *data_obs_fail_postfit_projy1_main = new TPad("data_obs_fail_postfit_projy1_main", "data_obs_fail_postfit_projy1_main",0,0.35,1,1);
   data_obs_fail_postfit_projy1_main->Draw();
   data_obs_fail_postfit_projy1_main->cd();
   data_obs_fail_postfit_projy1_main->Range(-633.6539,-6.906977,4270.192,165.7674);
   data_obs_fail_postfit_projy1_main->SetFillColor(0);
   data_obs_fail_postfit_projy1_main->SetBorderMode(0);
   data_obs_fail_postfit_projy1_main->SetBorderSize(2);
   data_obs_fail_postfit_projy1_main->SetTickx(1);
   data_obs_fail_postfit_projy1_main->SetTicky(1);
   data_obs_fail_postfit_projy1_main->SetLeftMargin(0.17);
   data_obs_fail_postfit_projy1_main->SetRightMargin(0.05);
   data_obs_fail_postfit_projy1_main->SetBottomMargin(0.04);
   data_obs_fail_postfit_projy1_main->SetFrameFillStyle(0);
   data_obs_fail_postfit_projy1_main->SetFrameBorderMode(0);
   data_obs_fail_postfit_projy1_main->SetFrameFillStyle(0);
   data_obs_fail_postfit_projy1_main->SetFrameBorderMode(0);
   Double_t xAxis49[2] = {200, 4025}; 
   
   TH1D *data_obs_fail_postfit_projy1__33 = new TH1D("data_obs_fail_postfit_projy1__33","",1, xAxis49);
   data_obs_fail_postfit_projy1__33->SetBinContent(1,110);
   data_obs_fail_postfit_projy1__33->SetBinError(1,10.48809);
   data_obs_fail_postfit_projy1__33->SetMinimum(0);
   data_obs_fail_postfit_projy1__33->SetMaximum(148.5);
   data_obs_fail_postfit_projy1__33->SetEntries(110);
   data_obs_fail_postfit_projy1__33->SetStats(0);

   Int_t ci;      // for color index setting
   TColor *color; // for color definition with alpha
   ci = TColor::GetColor("#000000");
   data_obs_fail_postfit_projy1__33->SetLineColor(ci);

   ci = TColor::GetColor("#000000");
   data_obs_fail_postfit_projy1__33->SetMarkerColor(ci);
   data_obs_fail_postfit_projy1__33->SetMarkerStyle(8);
   data_obs_fail_postfit_projy1__33->GetXaxis()->SetTitle("p_{T}");
   data_obs_fail_postfit_projy1__33->GetXaxis()->SetLabelFont(42);
   data_obs_fail_postfit_projy1__33->GetXaxis()->SetLabelOffset(0.05);
   data_obs_fail_postfit_projy1__33->GetXaxis()->SetLabelSize(0.07);
   data_obs_fail_postfit_projy1__33->GetXaxis()->SetTitleSize(0.09);
   data_obs_fail_postfit_projy1__33->GetXaxis()->SetTitleOffset(1.15);
   data_obs_fail_postfit_projy1__33->GetXaxis()->SetTitleFont(42);
   data_obs_fail_postfit_projy1__33->GetYaxis()->SetTitle("Events / bin");
   data_obs_fail_postfit_projy1__33->GetYaxis()->SetNdivisions(508);
   data_obs_fail_postfit_projy1__33->GetYaxis()->SetLabelFont(42);
   data_obs_fail_postfit_projy1__33->GetYaxis()->SetLabelSize(0.07);
   data_obs_fail_postfit_projy1__33->GetYaxis()->SetTitleSize(0.09);
   data_obs_fail_postfit_projy1__33->GetYaxis()->SetTitleOffset(0.8);
   data_obs_fail_postfit_projy1__33->GetYaxis()->SetTitleFont(42);
   data_obs_fail_postfit_projy1__33->GetZaxis()->SetLabelFont(42);
   data_obs_fail_postfit_projy1__33->GetZaxis()->SetLabelSize(0.035);
   data_obs_fail_postfit_projy1__33->GetZaxis()->SetTitleSize(0.035);
   data_obs_fail_postfit_projy1__33->GetZaxis()->SetTitleFont(42);
   data_obs_fail_postfit_projy1__33->Draw("pe X0");
   
   THStack *postfit_projy1_fail_stack = new THStack();
   postfit_projy1_fail_stack->SetName("postfit_projy1_fail_stack");
   postfit_projy1_fail_stack->SetTitle("postfit_projy1_fail_stack");
   Double_t xAxis50[2] = {200, 4025}; 
   
   TH1F *postfit_projy1_fail_stack_stack_9 = new TH1F("postfit_projy1_fail_stack_stack_9","postfit_projy1_fail_stack",1, xAxis50);
   postfit_projy1_fail_stack_stack_9->SetMinimum(0);
   postfit_projy1_fail_stack_stack_9->SetMaximum(118.9292);
   postfit_projy1_fail_stack_stack_9->SetDirectory(0);
   postfit_projy1_fail_stack_stack_9->SetStats(0);
   postfit_projy1_fail_stack_stack_9->SetLineStyle(0);
   postfit_projy1_fail_stack_stack_9->GetXaxis()->SetLabelFont(42);
   postfit_projy1_fail_stack_stack_9->GetXaxis()->SetLabelOffset(0.007);
   postfit_projy1_fail_stack_stack_9->GetXaxis()->SetLabelSize(0.05);
   postfit_projy1_fail_stack_stack_9->GetXaxis()->SetTitleSize(0.08);
   postfit_projy1_fail_stack_stack_9->GetXaxis()->SetTitleOffset(0.9);
   postfit_projy1_fail_stack_stack_9->GetXaxis()->SetTitleFont(42);
   postfit_projy1_fail_stack_stack_9->GetYaxis()->SetNdivisions(508);
   postfit_projy1_fail_stack_stack_9->GetYaxis()->SetLabelFont(42);
   postfit_projy1_fail_stack_stack_9->GetYaxis()->SetLabelOffset(0.007);
   postfit_projy1_fail_stack_stack_9->GetYaxis()->SetLabelSize(0.05);
   postfit_projy1_fail_stack_stack_9->GetYaxis()->SetTitleSize(0.08);
   postfit_projy1_fail_stack_stack_9->GetYaxis()->SetTitleOffset(1.25);
   postfit_projy1_fail_stack_stack_9->GetYaxis()->SetTitleFont(42);
   postfit_projy1_fail_stack_stack_9->GetZaxis()->SetLabelFont(42);
   postfit_projy1_fail_stack_stack_9->GetZaxis()->SetLabelOffset(0.007);
   postfit_projy1_fail_stack_stack_9->GetZaxis()->SetLabelSize(0.05);
   postfit_projy1_fail_stack_stack_9->GetZaxis()->SetTitleSize(0.08);
   postfit_projy1_fail_stack_stack_9->GetZaxis()->SetTitleFont(42);
   postfit_projy1_fail_stack->SetHistogram(postfit_projy1_fail_stack_stack_9);
   
   Double_t xAxis51[2] = {200, 4025}; 
   
   TH1D *Background_fail_postfit_projy1_stack_1 = new TH1D("Background_fail_postfit_projy1_stack_1","Background, fail, postfit, 0.25-1.0",1, xAxis51);
   Background_fail_postfit_projy1_stack_1->SetBinContent(1,104.5562);
   Background_fail_postfit_projy1_stack_1->SetBinError(1,8.709684);
   Background_fail_postfit_projy1_stack_1->SetMinimum(0);
   Background_fail_postfit_projy1_stack_1->SetEntries(144.1103);
   Background_fail_postfit_projy1_stack_1->SetStats(0);

   ci = TColor::GetColor("#ffff00");
   Background_fail_postfit_projy1_stack_1->SetFillColor(ci);

   ci = 1189;
   color = new TColor(ci, 1, 1, 1, " ", 0);
   Background_fail_postfit_projy1_stack_1->SetLineColor(ci);
   Background_fail_postfit_projy1_stack_1->GetXaxis()->SetTitle("p_{T}");
   Background_fail_postfit_projy1_stack_1->GetXaxis()->SetLabelFont(42);
   Background_fail_postfit_projy1_stack_1->GetXaxis()->SetLabelSize(0.035);
   Background_fail_postfit_projy1_stack_1->GetXaxis()->SetTitleSize(0.035);
   Background_fail_postfit_projy1_stack_1->GetXaxis()->SetTitleOffset(0);
   Background_fail_postfit_projy1_stack_1->GetXaxis()->SetTitleFont(42);
   Background_fail_postfit_projy1_stack_1->GetYaxis()->SetTitle("Events / bin");
   Background_fail_postfit_projy1_stack_1->GetYaxis()->SetLabelFont(42);
   Background_fail_postfit_projy1_stack_1->GetYaxis()->SetLabelSize(0.035);
   Background_fail_postfit_projy1_stack_1->GetYaxis()->SetTitleSize(0.035);
   Background_fail_postfit_projy1_stack_1->GetYaxis()->SetTitleOffset(0);
   Background_fail_postfit_projy1_stack_1->GetYaxis()->SetTitleFont(42);
   Background_fail_postfit_projy1_stack_1->GetZaxis()->SetLabelFont(42);
   Background_fail_postfit_projy1_stack_1->GetZaxis()->SetLabelSize(0.035);
   Background_fail_postfit_projy1_stack_1->GetZaxis()->SetTitleSize(0.035);
   Background_fail_postfit_projy1_stack_1->GetZaxis()->SetTitleFont(42);
   postfit_projy1_fail_stack->Add(Background_fail_postfit_projy1_stack_1,"");
   postfit_projy1_fail_stack->Draw("hist same");
   
   postfit_projy1_fail_stack = new THStack();
   postfit_projy1_fail_stack->SetName("postfit_projy1_fail_stack");
   postfit_projy1_fail_stack->SetTitle("postfit_projy1_fail_stack");
   Double_t xAxis52[2] = {200, 4025}; 
   
   TH1F *postfit_projy1_fail_stack_stack_9_stack_10 = new TH1F("postfit_projy1_fail_stack_stack_9_stack_10","postfit_projy1_fail_stack",1, xAxis52);
   postfit_projy1_fail_stack_stack_9_stack_10->SetMinimum(0);
   postfit_projy1_fail_stack_stack_9_stack_10->SetMaximum(118.9292);
   postfit_projy1_fail_stack_stack_9_stack_10->SetDirectory(0);
   postfit_projy1_fail_stack_stack_9_stack_10->SetStats(0);
   postfit_projy1_fail_stack_stack_9_stack_10->SetLineStyle(0);
   postfit_projy1_fail_stack_stack_9_stack_10->GetXaxis()->SetLabelFont(42);
   postfit_projy1_fail_stack_stack_9_stack_10->GetXaxis()->SetLabelOffset(0.007);
   postfit_projy1_fail_stack_stack_9_stack_10->GetXaxis()->SetLabelSize(0.05);
   postfit_projy1_fail_stack_stack_9_stack_10->GetXaxis()->SetTitleSize(0.08);
   postfit_projy1_fail_stack_stack_9_stack_10->GetXaxis()->SetTitleOffset(0.9);
   postfit_projy1_fail_stack_stack_9_stack_10->GetXaxis()->SetTitleFont(42);
   postfit_projy1_fail_stack_stack_9_stack_10->GetYaxis()->SetNdivisions(508);
   postfit_projy1_fail_stack_stack_9_stack_10->GetYaxis()->SetLabelFont(42);
   postfit_projy1_fail_stack_stack_9_stack_10->GetYaxis()->SetLabelOffset(0.007);
   postfit_projy1_fail_stack_stack_9_stack_10->GetYaxis()->SetLabelSize(0.05);
   postfit_projy1_fail_stack_stack_9_stack_10->GetYaxis()->SetTitleSize(0.08);
   postfit_projy1_fail_stack_stack_9_stack_10->GetYaxis()->SetTitleOffset(1.25);
   postfit_projy1_fail_stack_stack_9_stack_10->GetYaxis()->SetTitleFont(42);
   postfit_projy1_fail_stack_stack_9_stack_10->GetZaxis()->SetLabelFont(42);
   postfit_projy1_fail_stack_stack_9_stack_10->GetZaxis()->SetLabelOffset(0.007);
   postfit_projy1_fail_stack_stack_9_stack_10->GetZaxis()->SetLabelSize(0.05);
   postfit_projy1_fail_stack_stack_9_stack_10->GetZaxis()->SetTitleSize(0.08);
   postfit_projy1_fail_stack_stack_9_stack_10->GetZaxis()->SetTitleFont(42);
   postfit_projy1_fail_stack->SetHistogram(postfit_projy1_fail_stack_stack_9_stack_10);
   
   Double_t xAxis53[2] = {200, 4025}; 
   
   TH1D *Background_fail_postfit_projy1_stack_1_stack_1 = new TH1D("Background_fail_postfit_projy1_stack_1_stack_1","Background, fail, postfit, 0.25-1.0",1, xAxis53);
   Background_fail_postfit_projy1_stack_1_stack_1->SetBinContent(1,104.5562);
   Background_fail_postfit_projy1_stack_1_stack_1->SetBinError(1,8.709684);
   Background_fail_postfit_projy1_stack_1_stack_1->SetMinimum(0);
   Background_fail_postfit_projy1_stack_1_stack_1->SetEntries(144.1103);
   Background_fail_postfit_projy1_stack_1_stack_1->SetStats(0);

   ci = TColor::GetColor("#ffff00");
   Background_fail_postfit_projy1_stack_1_stack_1->SetFillColor(ci);

   ci = 1189;
   color = new TColor(ci, 1, 1, 1, " ", 0);
   Background_fail_postfit_projy1_stack_1_stack_1->SetLineColor(ci);
   Background_fail_postfit_projy1_stack_1_stack_1->GetXaxis()->SetTitle("p_{T}");
   Background_fail_postfit_projy1_stack_1_stack_1->GetXaxis()->SetLabelFont(42);
   Background_fail_postfit_projy1_stack_1_stack_1->GetXaxis()->SetLabelSize(0.035);
   Background_fail_postfit_projy1_stack_1_stack_1->GetXaxis()->SetTitleSize(0.035);
   Background_fail_postfit_projy1_stack_1_stack_1->GetXaxis()->SetTitleOffset(0);
   Background_fail_postfit_projy1_stack_1_stack_1->GetXaxis()->SetTitleFont(42);
   Background_fail_postfit_projy1_stack_1_stack_1->GetYaxis()->SetTitle("Events / bin");
   Background_fail_postfit_projy1_stack_1_stack_1->GetYaxis()->SetLabelFont(42);
   Background_fail_postfit_projy1_stack_1_stack_1->GetYaxis()->SetLabelSize(0.035);
   Background_fail_postfit_projy1_stack_1_stack_1->GetYaxis()->SetTitleSize(0.035);
   Background_fail_postfit_projy1_stack_1_stack_1->GetYaxis()->SetTitleOffset(0);
   Background_fail_postfit_projy1_stack_1_stack_1->GetYaxis()->SetTitleFont(42);
   Background_fail_postfit_projy1_stack_1_stack_1->GetZaxis()->SetLabelFont(42);
   Background_fail_postfit_projy1_stack_1_stack_1->GetZaxis()->SetLabelSize(0.035);
   Background_fail_postfit_projy1_stack_1_stack_1->GetZaxis()->SetTitleSize(0.035);
   Background_fail_postfit_projy1_stack_1_stack_1->GetZaxis()->SetTitleFont(42);
   postfit_projy1_fail_stack->Add(Background_fail_postfit_projy1_stack_1_stack_1,"");
   postfit_projy1_fail_stack->Draw("hist same");
   Double_t xAxis54[2] = {200, 4025}; 
   
   TH1D *Signal_gluinomI1800_fail_postfit_projy1__34 = new TH1D("Signal_gluinomI1800_fail_postfit_projy1__34","HSCP gluino 1800 GeV, fail, postfit, 0.25-1.0",1, xAxis54);
   Signal_gluinomI1800_fail_postfit_projy1__34->SetBinContent(1,1.820256);
   Signal_gluinomI1800_fail_postfit_projy1__34->SetBinError(1,0.1791396);
   Signal_gluinomI1800_fail_postfit_projy1__34->SetMinimum(0);
   Signal_gluinomI1800_fail_postfit_projy1__34->SetEntries(103.2479);
   Signal_gluinomI1800_fail_postfit_projy1__34->SetStats(0);
   Signal_gluinomI1800_fail_postfit_projy1__34->SetLineColor(4);
   Signal_gluinomI1800_fail_postfit_projy1__34->SetLineWidth(2);
   Signal_gluinomI1800_fail_postfit_projy1__34->GetXaxis()->SetTitle("p_{T}");
   Signal_gluinomI1800_fail_postfit_projy1__34->GetXaxis()->SetLabelFont(42);
   Signal_gluinomI1800_fail_postfit_projy1__34->GetXaxis()->SetLabelSize(0.035);
   Signal_gluinomI1800_fail_postfit_projy1__34->GetXaxis()->SetTitleSize(0.035);
   Signal_gluinomI1800_fail_postfit_projy1__34->GetXaxis()->SetTitleOffset(0);
   Signal_gluinomI1800_fail_postfit_projy1__34->GetXaxis()->SetTitleFont(42);
   Signal_gluinomI1800_fail_postfit_projy1__34->GetYaxis()->SetTitle("Events / bin");
   Signal_gluinomI1800_fail_postfit_projy1__34->GetYaxis()->SetLabelFont(42);
   Signal_gluinomI1800_fail_postfit_projy1__34->GetYaxis()->SetLabelSize(0.035);
   Signal_gluinomI1800_fail_postfit_projy1__34->GetYaxis()->SetTitleSize(0.035);
   Signal_gluinomI1800_fail_postfit_projy1__34->GetYaxis()->SetTitleOffset(0);
   Signal_gluinomI1800_fail_postfit_projy1__34->GetYaxis()->SetTitleFont(42);
   Signal_gluinomI1800_fail_postfit_projy1__34->GetZaxis()->SetLabelFont(42);
   Signal_gluinomI1800_fail_postfit_projy1__34->GetZaxis()->SetLabelSize(0.035);
   Signal_gluinomI1800_fail_postfit_projy1__34->GetZaxis()->SetTitleSize(0.035);
   Signal_gluinomI1800_fail_postfit_projy1__34->GetZaxis()->SetTitleFont(42);
   Signal_gluinomI1800_fail_postfit_projy1__34->Draw("hist same");
   Double_t xAxis55[2] = {200, 4025}; 
   
   TH1D *Signal_ppStaumI557_fail_postfit_projy1__35 = new TH1D("Signal_ppStaumI557_fail_postfit_projy1__35","HSCP stau 557 GeV, fail, postfit, 0.25-1.0",1, xAxis55);
   Signal_ppStaumI557_fail_postfit_projy1__35->SetBinContent(1,3.461965);
   Signal_ppStaumI557_fail_postfit_projy1__35->SetBinError(1,0.1678412);
   Signal_ppStaumI557_fail_postfit_projy1__35->SetMinimum(0);
   Signal_ppStaumI557_fail_postfit_projy1__35->SetEntries(425.4494);
   Signal_ppStaumI557_fail_postfit_projy1__35->SetStats(0);
   Signal_ppStaumI557_fail_postfit_projy1__35->SetLineColor(2);
   Signal_ppStaumI557_fail_postfit_projy1__35->SetLineWidth(2);
   Signal_ppStaumI557_fail_postfit_projy1__35->GetXaxis()->SetTitle("p_{T}");
   Signal_ppStaumI557_fail_postfit_projy1__35->GetXaxis()->SetLabelFont(42);
   Signal_ppStaumI557_fail_postfit_projy1__35->GetXaxis()->SetLabelSize(0.035);
   Signal_ppStaumI557_fail_postfit_projy1__35->GetXaxis()->SetTitleSize(0.035);
   Signal_ppStaumI557_fail_postfit_projy1__35->GetXaxis()->SetTitleOffset(0);
   Signal_ppStaumI557_fail_postfit_projy1__35->GetXaxis()->SetTitleFont(42);
   Signal_ppStaumI557_fail_postfit_projy1__35->GetYaxis()->SetTitle("Events / bin");
   Signal_ppStaumI557_fail_postfit_projy1__35->GetYaxis()->SetLabelFont(42);
   Signal_ppStaumI557_fail_postfit_projy1__35->GetYaxis()->SetLabelSize(0.035);
   Signal_ppStaumI557_fail_postfit_projy1__35->GetYaxis()->SetTitleSize(0.035);
   Signal_ppStaumI557_fail_postfit_projy1__35->GetYaxis()->SetTitleOffset(0);
   Signal_ppStaumI557_fail_postfit_projy1__35->GetYaxis()->SetTitleFont(42);
   Signal_ppStaumI557_fail_postfit_projy1__35->GetZaxis()->SetLabelFont(42);
   Signal_ppStaumI557_fail_postfit_projy1__35->GetZaxis()->SetLabelSize(0.035);
   Signal_ppStaumI557_fail_postfit_projy1__35->GetZaxis()->SetTitleSize(0.035);
   Signal_ppStaumI557_fail_postfit_projy1__35->GetZaxis()->SetTitleFont(42);
   Signal_ppStaumI557_fail_postfit_projy1__35->Draw("hist same");
   Double_t xAxis56[2] = {200, 4025}; 
   
   TH1D *TotalBkg_fail_postfit_projy1__36 = new TH1D("TotalBkg_fail_postfit_projy1__36","TotalBkg, fail, postfit, 0.25-1.0",1, xAxis56);
   TotalBkg_fail_postfit_projy1__36->SetBinContent(1,104.5562);
   TotalBkg_fail_postfit_projy1__36->SetBinError(1,10.0192);
   TotalBkg_fail_postfit_projy1__36->SetMinimum(0);
   TotalBkg_fail_postfit_projy1__36->SetEntries(108.9014);
   TotalBkg_fail_postfit_projy1__36->SetStats(0);
   TotalBkg_fail_postfit_projy1__36->SetMarkerStyle(0);
   TotalBkg_fail_postfit_projy1__36->GetXaxis()->SetTitle("p_{T}");
   TotalBkg_fail_postfit_projy1__36->GetXaxis()->SetLabelFont(42);
   TotalBkg_fail_postfit_projy1__36->GetXaxis()->SetLabelSize(0.035);
   TotalBkg_fail_postfit_projy1__36->GetXaxis()->SetTitleSize(0.035);
   TotalBkg_fail_postfit_projy1__36->GetXaxis()->SetTitleOffset(0);
   TotalBkg_fail_postfit_projy1__36->GetXaxis()->SetTitleFont(42);
   TotalBkg_fail_postfit_projy1__36->GetYaxis()->SetTitle("Events / bin");
   TotalBkg_fail_postfit_projy1__36->GetYaxis()->SetLabelFont(42);
   TotalBkg_fail_postfit_projy1__36->GetYaxis()->SetLabelSize(0.035);
   TotalBkg_fail_postfit_projy1__36->GetYaxis()->SetTitleSize(0.035);
   TotalBkg_fail_postfit_projy1__36->GetYaxis()->SetTitleOffset(0);
   TotalBkg_fail_postfit_projy1__36->GetYaxis()->SetTitleFont(42);
   TotalBkg_fail_postfit_projy1__36->GetZaxis()->SetLabelFont(42);
   TotalBkg_fail_postfit_projy1__36->GetZaxis()->SetLabelSize(0.035);
   TotalBkg_fail_postfit_projy1__36->GetZaxis()->SetTitleSize(0.035);
   TotalBkg_fail_postfit_projy1__36->GetZaxis()->SetTitleFont(42);
   TotalBkg_fail_postfit_projy1__36->Draw("hist same");
   Double_t xAxis57[2] = {200, 4025}; 
   
   TH1D *TotalBkg_fail_postfit_projy1__37 = new TH1D("TotalBkg_fail_postfit_projy1__37","TotalBkg, fail, postfit, 0.25-1.0",1, xAxis57);
   TotalBkg_fail_postfit_projy1__37->SetBinContent(1,104.5562);
   TotalBkg_fail_postfit_projy1__37->SetBinError(1,10.0192);
   TotalBkg_fail_postfit_projy1__37->SetMinimum(0);
   TotalBkg_fail_postfit_projy1__37->SetEntries(108.9014);
   TotalBkg_fail_postfit_projy1__37->SetStats(0);
   TotalBkg_fail_postfit_projy1__37->SetFillColor(1);
   TotalBkg_fail_postfit_projy1__37->SetFillStyle(3354);
   TotalBkg_fail_postfit_projy1__37->SetLineWidth(0);
   TotalBkg_fail_postfit_projy1__37->SetMarkerStyle(0);
   TotalBkg_fail_postfit_projy1__37->GetXaxis()->SetTitle("p_{T}");
   TotalBkg_fail_postfit_projy1__37->GetXaxis()->SetLabelFont(42);
   TotalBkg_fail_postfit_projy1__37->GetXaxis()->SetLabelSize(0.035);
   TotalBkg_fail_postfit_projy1__37->GetXaxis()->SetTitleSize(0.035);
   TotalBkg_fail_postfit_projy1__37->GetXaxis()->SetTitleOffset(0);
   TotalBkg_fail_postfit_projy1__37->GetXaxis()->SetTitleFont(42);
   TotalBkg_fail_postfit_projy1__37->GetYaxis()->SetTitle("Events / bin");
   TotalBkg_fail_postfit_projy1__37->GetYaxis()->SetLabelFont(42);
   TotalBkg_fail_postfit_projy1__37->GetYaxis()->SetLabelSize(0.035);
   TotalBkg_fail_postfit_projy1__37->GetYaxis()->SetTitleSize(0.035);
   TotalBkg_fail_postfit_projy1__37->GetYaxis()->SetTitleOffset(0);
   TotalBkg_fail_postfit_projy1__37->GetYaxis()->SetTitleFont(42);
   TotalBkg_fail_postfit_projy1__37->GetZaxis()->SetLabelFont(42);
   TotalBkg_fail_postfit_projy1__37->GetZaxis()->SetLabelSize(0.035);
   TotalBkg_fail_postfit_projy1__37->GetZaxis()->SetTitleSize(0.035);
   TotalBkg_fail_postfit_projy1__37->GetZaxis()->SetTitleFont(42);
   TotalBkg_fail_postfit_projy1__37->Draw("e2 same");
   Double_t xAxis58[2] = {200, 4025}; 
   
   TH1D *data_obs_fail_postfit_projy1__38 = new TH1D("data_obs_fail_postfit_projy1__38","",1, xAxis58);
   data_obs_fail_postfit_projy1__38->SetBinContent(1,110);
   data_obs_fail_postfit_projy1__38->SetBinError(1,10.48809);
   data_obs_fail_postfit_projy1__38->SetMinimum(0);
   data_obs_fail_postfit_projy1__38->SetMaximum(148.5);
   data_obs_fail_postfit_projy1__38->SetEntries(110);
   data_obs_fail_postfit_projy1__38->SetStats(0);

   ci = TColor::GetColor("#000000");
   data_obs_fail_postfit_projy1__38->SetLineColor(ci);

   ci = TColor::GetColor("#000000");
   data_obs_fail_postfit_projy1__38->SetMarkerColor(ci);
   data_obs_fail_postfit_projy1__38->SetMarkerStyle(8);
   data_obs_fail_postfit_projy1__38->GetXaxis()->SetTitle("p_{T}");
   data_obs_fail_postfit_projy1__38->GetXaxis()->SetLabelFont(42);
   data_obs_fail_postfit_projy1__38->GetXaxis()->SetLabelOffset(0.05);
   data_obs_fail_postfit_projy1__38->GetXaxis()->SetLabelSize(0.07);
   data_obs_fail_postfit_projy1__38->GetXaxis()->SetTitleSize(0.09);
   data_obs_fail_postfit_projy1__38->GetXaxis()->SetTitleOffset(1.15);
   data_obs_fail_postfit_projy1__38->GetXaxis()->SetTitleFont(42);
   data_obs_fail_postfit_projy1__38->GetYaxis()->SetTitle("Events / bin");
   data_obs_fail_postfit_projy1__38->GetYaxis()->SetNdivisions(508);
   data_obs_fail_postfit_projy1__38->GetYaxis()->SetLabelFont(42);
   data_obs_fail_postfit_projy1__38->GetYaxis()->SetLabelSize(0.07);
   data_obs_fail_postfit_projy1__38->GetYaxis()->SetTitleSize(0.09);
   data_obs_fail_postfit_projy1__38->GetYaxis()->SetTitleOffset(0.8);
   data_obs_fail_postfit_projy1__38->GetYaxis()->SetTitleFont(42);
   data_obs_fail_postfit_projy1__38->GetZaxis()->SetLabelFont(42);
   data_obs_fail_postfit_projy1__38->GetZaxis()->SetLabelSize(0.035);
   data_obs_fail_postfit_projy1__38->GetZaxis()->SetTitleSize(0.035);
   data_obs_fail_postfit_projy1__38->GetZaxis()->SetTitleFont(42);
   data_obs_fail_postfit_projy1__38->Draw("pe X0 same");
   
   TLegend *leg = new TLegend(0.65,0.61,0.9,0.88,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(1001);
   TLegendEntry *entry=leg->AddEntry("data_obs_fail_postfit_projy1","Data","pe X0");

   ci = TColor::GetColor("#000000");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);

   ci = TColor::GetColor("#000000");
   entry->SetMarkerColor(ci);
   entry->SetMarkerStyle(8);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("TotalBkg_fail_postfit_projy1","Total bkg unc.","F");
   entry->SetFillColor(1);
   entry->SetFillStyle(3354);
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("Signal_gluino-1800_fail_postfit_projy1","HSCP gluino 1800 GeV","L");
   entry->SetLineColor(4);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("Signal_ppStau-557_fail_postfit_projy1","HSCP stau 557 GeV","L");
   entry->SetLineColor(2);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("Background_fail_postfit_projy1_stack_1_stack_1","Background","f");

   ci = TColor::GetColor("#ffff00");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = 1189;
   color = new TColor(ci, 1, 1, 1, " ", 0);
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   leg->Draw();
   Double_t xAxis59[2] = {200, 4025}; 
   
   TH1D *data_obs_fail_postfit_projy1_copy__39 = new TH1D("data_obs_fail_postfit_projy1_copy__39","",1, xAxis59);
   data_obs_fail_postfit_projy1_copy__39->SetBinContent(1,110);
   data_obs_fail_postfit_projy1_copy__39->SetBinError(1,10.48809);
   data_obs_fail_postfit_projy1_copy__39->SetMinimum(0);
   data_obs_fail_postfit_projy1_copy__39->SetMaximum(148.5);
   data_obs_fail_postfit_projy1_copy__39->SetEntries(110);
   data_obs_fail_postfit_projy1_copy__39->SetDirectory(0);
   data_obs_fail_postfit_projy1_copy__39->SetStats(0);

   ci = TColor::GetColor("#000000");
   data_obs_fail_postfit_projy1_copy__39->SetLineColor(ci);

   ci = TColor::GetColor("#000000");
   data_obs_fail_postfit_projy1_copy__39->SetMarkerColor(ci);
   data_obs_fail_postfit_projy1_copy__39->SetMarkerStyle(8);
   data_obs_fail_postfit_projy1_copy__39->GetXaxis()->SetTitle("p_{T}");
   data_obs_fail_postfit_projy1_copy__39->GetXaxis()->SetLabelFont(42);
   data_obs_fail_postfit_projy1_copy__39->GetXaxis()->SetLabelOffset(0.05);
   data_obs_fail_postfit_projy1_copy__39->GetXaxis()->SetLabelSize(0.07);
   data_obs_fail_postfit_projy1_copy__39->GetXaxis()->SetTitleSize(0.09);
   data_obs_fail_postfit_projy1_copy__39->GetXaxis()->SetTitleOffset(1.15);
   data_obs_fail_postfit_projy1_copy__39->GetXaxis()->SetTitleFont(42);
   data_obs_fail_postfit_projy1_copy__39->GetYaxis()->SetTitle("Events / bin");
   data_obs_fail_postfit_projy1_copy__39->GetYaxis()->SetNdivisions(508);
   data_obs_fail_postfit_projy1_copy__39->GetYaxis()->SetLabelFont(42);
   data_obs_fail_postfit_projy1_copy__39->GetYaxis()->SetLabelSize(0.07);
   data_obs_fail_postfit_projy1_copy__39->GetYaxis()->SetTitleSize(0.09);
   data_obs_fail_postfit_projy1_copy__39->GetYaxis()->SetTitleOffset(0.8);
   data_obs_fail_postfit_projy1_copy__39->GetYaxis()->SetTitleFont(42);
   data_obs_fail_postfit_projy1_copy__39->GetZaxis()->SetLabelFont(42);
   data_obs_fail_postfit_projy1_copy__39->GetZaxis()->SetLabelSize(0.035);
   data_obs_fail_postfit_projy1_copy__39->GetZaxis()->SetTitleSize(0.035);
   data_obs_fail_postfit_projy1_copy__39->GetZaxis()->SetTitleFont(42);
   data_obs_fail_postfit_projy1_copy__39->Draw("sameaxis");
   TLatex *   tex = new TLatex(0.21,0.83,"0.25 < G_{i}^{Strips} < 1.0 , F^{Pixels}_{i} < 0.9");
tex->SetNDC();
   tex->SetTextAlign(12);
   tex->SetTextFont(42);
   tex->SetTextSize(0.06);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.17,0.92,"CMS");
tex->SetNDC();
   tex->SetTextFont(61);
   tex->SetTextSize(0.0675);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.25,0.92,"Preliminary");
tex->SetNDC();
   tex->SetTextFont(52);
   tex->SetTextSize(0.0485);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.95,0.92,"101 fb^{-1} (13 TeV)");
tex->SetNDC();
   tex->SetTextAlign(31);
   tex->SetTextFont(42);
   tex->SetTextSize(0.07);
   tex->SetLineWidth(2);
   tex->Draw();
   data_obs_fail_postfit_projy1_main->Modified();
   plots_fit_b/base_figs/postfit_projy1_fail->cd();
  
// ------------>Primitives in pad: data_obs_fail_postfit_projy1_sub
   TPad *data_obs_fail_postfit_projy1_sub = new TPad("data_obs_fail_postfit_projy1_sub", "data_obs_fail_postfit_projy1_sub",0,0,1,0.35);
   data_obs_fail_postfit_projy1_sub->Draw();
   data_obs_fail_postfit_projy1_sub->cd();
   data_obs_fail_postfit_projy1_sub->Range(-633.6539,-6.023077,4270.192,2.9);
   data_obs_fail_postfit_projy1_sub->SetFillColor(0);
   data_obs_fail_postfit_projy1_sub->SetBorderMode(0);
   data_obs_fail_postfit_projy1_sub->SetBorderSize(2);
   data_obs_fail_postfit_projy1_sub->SetTickx(1);
   data_obs_fail_postfit_projy1_sub->SetTicky(1);
   data_obs_fail_postfit_projy1_sub->SetLeftMargin(0.17);
   data_obs_fail_postfit_projy1_sub->SetRightMargin(0.05);
   data_obs_fail_postfit_projy1_sub->SetTopMargin(0);
   data_obs_fail_postfit_projy1_sub->SetBottomMargin(0.35);
   data_obs_fail_postfit_projy1_sub->SetFrameFillStyle(0);
   data_obs_fail_postfit_projy1_sub->SetFrameBorderMode(0);
   data_obs_fail_postfit_projy1_sub->SetFrameFillStyle(0);
   data_obs_fail_postfit_projy1_sub->SetFrameBorderMode(0);
   Double_t xAxis60[2] = {200, 4025}; 
   
   TH1D *data_obs_fail_postfit_projy1_pull__40 = new TH1D("data_obs_fail_postfit_projy1_pull__40","",1, xAxis60);
   data_obs_fail_postfit_projy1_pull__40->SetBinContent(1,0.3582529);
   data_obs_fail_postfit_projy1_pull__40->SetBinError(1,14.50464);
   data_obs_fail_postfit_projy1_pull__40->SetMinimum(-2.9);
   data_obs_fail_postfit_projy1_pull__40->SetMaximum(2.9);
   data_obs_fail_postfit_projy1_pull__40->SetEntries(1.14086);
   data_obs_fail_postfit_projy1_pull__40->SetStats(0);

   ci = TColor::GetColor("#0000ff");
   data_obs_fail_postfit_projy1_pull__40->SetFillColor(ci);

   ci = TColor::GetColor("#000000");
   data_obs_fail_postfit_projy1_pull__40->SetLineColor(ci);

   ci = TColor::GetColor("#000000");
   data_obs_fail_postfit_projy1_pull__40->SetMarkerColor(ci);
   data_obs_fail_postfit_projy1_pull__40->SetMarkerStyle(8);
   data_obs_fail_postfit_projy1_pull__40->GetXaxis()->SetTitle("p_{T}");
   data_obs_fail_postfit_projy1_pull__40->GetXaxis()->SetLabelFont(42);
   data_obs_fail_postfit_projy1_pull__40->GetXaxis()->SetLabelOffset(0.05);
   data_obs_fail_postfit_projy1_pull__40->GetXaxis()->SetLabelSize(0.13);
   data_obs_fail_postfit_projy1_pull__40->GetXaxis()->SetTitleSize(0.15);
   data_obs_fail_postfit_projy1_pull__40->GetXaxis()->SetTitleOffset(1.15);
   data_obs_fail_postfit_projy1_pull__40->GetXaxis()->SetTitleFont(42);
   data_obs_fail_postfit_projy1_pull__40->GetYaxis()->SetTitle("(Data-Bkg)/#sigma");
   data_obs_fail_postfit_projy1_pull__40->GetYaxis()->SetNdivisions(306);
   data_obs_fail_postfit_projy1_pull__40->GetYaxis()->SetLabelFont(42);
   data_obs_fail_postfit_projy1_pull__40->GetYaxis()->SetLabelSize(0.13);
   data_obs_fail_postfit_projy1_pull__40->GetYaxis()->SetTitleSize(0.12);
   data_obs_fail_postfit_projy1_pull__40->GetYaxis()->SetTitleOffset(0.4);
   data_obs_fail_postfit_projy1_pull__40->GetYaxis()->SetTitleFont(42);
   data_obs_fail_postfit_projy1_pull__40->GetZaxis()->SetLabelFont(42);
   data_obs_fail_postfit_projy1_pull__40->GetZaxis()->SetLabelSize(0.035);
   data_obs_fail_postfit_projy1_pull__40->GetZaxis()->SetTitleSize(0.035);
   data_obs_fail_postfit_projy1_pull__40->GetZaxis()->SetTitleFont(42);
   data_obs_fail_postfit_projy1_pull__40->Draw("hist");
   data_obs_fail_postfit_projy1_sub->Modified();
   plots_fit_b/base_figs/postfit_projy1_fail->cd();
   plots_fit_b/base_figs/postfit_projy1_fail->Modified();
   plots_fit_b/base_figs/postfit_projy1_fail->cd();
   plots_fit_b/base_figs/postfit_projy1_fail->SetSelected(plots_fit_b/base_figs/postfit_projy1_fail);
}
