void postfit_projy0_pass_logy()
{
//=========Macro generated from canvas: plots_fit_b/base_figs/postfit_projy0_pass_logy/plots_fit_b/base_figs/postfit_projy0_pass_logy
//=========  (Fri Jan 12 20:33:16 2024) by ROOT version 6.14/09
   TCanvas *plots_fit_b/base_figs/postfit_projy0_pass_logy = new TCanvas("plots_fit_b/base_figs/postfit_projy0_pass_logy", "plots_fit_b/base_figs/postfit_projy0_pass_logy",0,0,800,700);
   gStyle->SetOptFit(1);
   gStyle->SetOptStat(0);
   plots_fit_b/base_figs/postfit_projy0_pass_logy->SetHighLightColor(2);
   plots_fit_b/base_figs/postfit_projy0_pass_logy->Range(0,0,1,1);
   plots_fit_b/base_figs/postfit_projy0_pass_logy->SetFillColor(0);
   plots_fit_b/base_figs/postfit_projy0_pass_logy->SetBorderMode(0);
   plots_fit_b/base_figs/postfit_projy0_pass_logy->SetBorderSize(2);
   plots_fit_b/base_figs/postfit_projy0_pass_logy->SetTickx(1);
   plots_fit_b/base_figs/postfit_projy0_pass_logy->SetTicky(1);
   plots_fit_b/base_figs/postfit_projy0_pass_logy->SetLeftMargin(0.16);
   plots_fit_b/base_figs/postfit_projy0_pass_logy->SetRightMargin(0);
   plots_fit_b/base_figs/postfit_projy0_pass_logy->SetTopMargin(0);
   plots_fit_b/base_figs/postfit_projy0_pass_logy->SetBottomMargin(0);
   plots_fit_b/base_figs/postfit_projy0_pass_logy->SetFrameFillStyle(0);
   plots_fit_b/base_figs/postfit_projy0_pass_logy->SetFrameBorderMode(0);
  
// ------------>Primitives in pad: data_obs_pass_postfit_projy0_main
   TPad *data_obs_pass_postfit_projy0_main = new TPad("data_obs_pass_postfit_projy0_main", "data_obs_pass_postfit_projy0_main",0,0.35,1,1);
   data_obs_pass_postfit_projy0_main->Draw();
   data_obs_pass_postfit_projy0_main->cd();
   data_obs_pass_postfit_projy0_main->Range(-633.6539,-3.445121,4270.192,7.682909);
   data_obs_pass_postfit_projy0_main->SetFillColor(0);
   data_obs_pass_postfit_projy0_main->SetBorderMode(0);
   data_obs_pass_postfit_projy0_main->SetBorderSize(2);
   data_obs_pass_postfit_projy0_main->SetLogy();
   data_obs_pass_postfit_projy0_main->SetTickx(1);
   data_obs_pass_postfit_projy0_main->SetTicky(1);
   data_obs_pass_postfit_projy0_main->SetLeftMargin(0.17);
   data_obs_pass_postfit_projy0_main->SetRightMargin(0.05);
   data_obs_pass_postfit_projy0_main->SetBottomMargin(0.04);
   data_obs_pass_postfit_projy0_main->SetFrameFillStyle(0);
   data_obs_pass_postfit_projy0_main->SetFrameBorderMode(0);
   data_obs_pass_postfit_projy0_main->SetFrameFillStyle(0);
   data_obs_pass_postfit_projy0_main->SetFrameBorderMode(0);
   Double_t xAxis253[2] = {200, 4025}; 
   
   TH1D *data_obs_pass_postfit_projy0__169 = new TH1D("data_obs_pass_postfit_projy0__169","",1, xAxis253);
   data_obs_pass_postfit_projy0__169->SetBinContent(1,40782);
   data_obs_pass_postfit_projy0__169->SetBinError(1,201.9455);
   data_obs_pass_postfit_projy0__169->SetMinimum(0.001);
   data_obs_pass_postfit_projy0__169->SetMaximum(3716260);
   data_obs_pass_postfit_projy0__169->SetEntries(40782);
   data_obs_pass_postfit_projy0__169->SetStats(0);

   Int_t ci;      // for color index setting
   TColor *color; // for color definition with alpha
   ci = TColor::GetColor("#000000");
   data_obs_pass_postfit_projy0__169->SetLineColor(ci);

   ci = TColor::GetColor("#000000");
   data_obs_pass_postfit_projy0__169->SetMarkerColor(ci);
   data_obs_pass_postfit_projy0__169->SetMarkerStyle(8);
   data_obs_pass_postfit_projy0__169->GetXaxis()->SetTitle("p_{T}");
   data_obs_pass_postfit_projy0__169->GetXaxis()->SetLabelFont(42);
   data_obs_pass_postfit_projy0__169->GetXaxis()->SetLabelOffset(0.05);
   data_obs_pass_postfit_projy0__169->GetXaxis()->SetLabelSize(0.07);
   data_obs_pass_postfit_projy0__169->GetXaxis()->SetTitleSize(0.09);
   data_obs_pass_postfit_projy0__169->GetXaxis()->SetTitleOffset(1.15);
   data_obs_pass_postfit_projy0__169->GetXaxis()->SetTitleFont(42);
   data_obs_pass_postfit_projy0__169->GetYaxis()->SetTitle("Events / bin");
   data_obs_pass_postfit_projy0__169->GetYaxis()->SetNdivisions(508);
   data_obs_pass_postfit_projy0__169->GetYaxis()->SetLabelFont(42);
   data_obs_pass_postfit_projy0__169->GetYaxis()->SetLabelSize(0.07);
   data_obs_pass_postfit_projy0__169->GetYaxis()->SetTitleSize(0.09);
   data_obs_pass_postfit_projy0__169->GetYaxis()->SetTitleOffset(0.8);
   data_obs_pass_postfit_projy0__169->GetYaxis()->SetTitleFont(42);
   data_obs_pass_postfit_projy0__169->GetZaxis()->SetLabelFont(42);
   data_obs_pass_postfit_projy0__169->GetZaxis()->SetLabelSize(0.035);
   data_obs_pass_postfit_projy0__169->GetZaxis()->SetTitleSize(0.035);
   data_obs_pass_postfit_projy0__169->GetZaxis()->SetTitleFont(42);
   data_obs_pass_postfit_projy0__169->Draw("pe X0");
   
   THStack *postfit_projy0_pass_logy_stack = new THStack();
   postfit_projy0_pass_logy_stack->SetName("postfit_projy0_pass_logy_stack");
   postfit_projy0_pass_logy_stack->SetTitle("postfit_projy0_pass_logy_stack");
   postfit_projy0_pass_logy_stack->SetMinimum(0.001);
   Double_t xAxis254[2] = {200, 4025}; 
   
   TH1F *postfit_projy0_pass_logy_stack_stack_43 = new TH1F("postfit_projy0_pass_logy_stack_stack_43","postfit_projy0_pass_logy_stack",1, xAxis254);
   postfit_projy0_pass_logy_stack_stack_43->SetMinimum(0.0002080643);
   postfit_projy0_pass_logy_stack_stack_43->SetMaximum(103333.5);
   postfit_projy0_pass_logy_stack_stack_43->SetDirectory(0);
   postfit_projy0_pass_logy_stack_stack_43->SetStats(0);
   postfit_projy0_pass_logy_stack_stack_43->SetLineStyle(0);
   postfit_projy0_pass_logy_stack_stack_43->GetXaxis()->SetLabelFont(42);
   postfit_projy0_pass_logy_stack_stack_43->GetXaxis()->SetLabelOffset(0.007);
   postfit_projy0_pass_logy_stack_stack_43->GetXaxis()->SetLabelSize(0.05);
   postfit_projy0_pass_logy_stack_stack_43->GetXaxis()->SetTitleSize(0.08);
   postfit_projy0_pass_logy_stack_stack_43->GetXaxis()->SetTitleOffset(0.9);
   postfit_projy0_pass_logy_stack_stack_43->GetXaxis()->SetTitleFont(42);
   postfit_projy0_pass_logy_stack_stack_43->GetYaxis()->SetNdivisions(508);
   postfit_projy0_pass_logy_stack_stack_43->GetYaxis()->SetLabelFont(42);
   postfit_projy0_pass_logy_stack_stack_43->GetYaxis()->SetLabelOffset(0.007);
   postfit_projy0_pass_logy_stack_stack_43->GetYaxis()->SetLabelSize(0.05);
   postfit_projy0_pass_logy_stack_stack_43->GetYaxis()->SetTitleSize(0.08);
   postfit_projy0_pass_logy_stack_stack_43->GetYaxis()->SetTitleOffset(1.25);
   postfit_projy0_pass_logy_stack_stack_43->GetYaxis()->SetTitleFont(42);
   postfit_projy0_pass_logy_stack_stack_43->GetZaxis()->SetLabelFont(42);
   postfit_projy0_pass_logy_stack_stack_43->GetZaxis()->SetLabelOffset(0.007);
   postfit_projy0_pass_logy_stack_stack_43->GetZaxis()->SetLabelSize(0.05);
   postfit_projy0_pass_logy_stack_stack_43->GetZaxis()->SetTitleSize(0.08);
   postfit_projy0_pass_logy_stack_stack_43->GetZaxis()->SetTitleFont(42);
   postfit_projy0_pass_logy_stack->SetHistogram(postfit_projy0_pass_logy_stack_stack_43);
   
   Double_t xAxis255[2] = {200, 4025}; 
   
   TH1D *Background_0x0_pass_postfit_projy0_stack_1 = new TH1D("Background_0x0_pass_postfit_projy0_stack_1","Background, pass, postfit, 0.0-0.25",1, xAxis255);
   Background_0x0_pass_postfit_projy0_stack_1->SetBinContent(1,40776.9);
   Background_0x0_pass_postfit_projy0_stack_1->SetBinError(1,188.0987);
   Background_0x0_pass_postfit_projy0_stack_1->SetMinimum(0.001);
   Background_0x0_pass_postfit_projy0_stack_1->SetEntries(46995.59);
   Background_0x0_pass_postfit_projy0_stack_1->SetStats(0);

   ci = TColor::GetColor("#ffff00");
   Background_0x0_pass_postfit_projy0_stack_1->SetFillColor(ci);

   ci = 1200;
   color = new TColor(ci, 1, 1, 1, " ", 0);
   Background_0x0_pass_postfit_projy0_stack_1->SetLineColor(ci);
   Background_0x0_pass_postfit_projy0_stack_1->GetXaxis()->SetTitle("p_{T}");
   Background_0x0_pass_postfit_projy0_stack_1->GetXaxis()->SetLabelFont(42);
   Background_0x0_pass_postfit_projy0_stack_1->GetXaxis()->SetLabelSize(0.035);
   Background_0x0_pass_postfit_projy0_stack_1->GetXaxis()->SetTitleSize(0.035);
   Background_0x0_pass_postfit_projy0_stack_1->GetXaxis()->SetTitleOffset(0);
   Background_0x0_pass_postfit_projy0_stack_1->GetXaxis()->SetTitleFont(42);
   Background_0x0_pass_postfit_projy0_stack_1->GetYaxis()->SetTitle("Events / bin");
   Background_0x0_pass_postfit_projy0_stack_1->GetYaxis()->SetLabelFont(42);
   Background_0x0_pass_postfit_projy0_stack_1->GetYaxis()->SetLabelSize(0.035);
   Background_0x0_pass_postfit_projy0_stack_1->GetYaxis()->SetTitleSize(0.035);
   Background_0x0_pass_postfit_projy0_stack_1->GetYaxis()->SetTitleOffset(0);
   Background_0x0_pass_postfit_projy0_stack_1->GetYaxis()->SetTitleFont(42);
   Background_0x0_pass_postfit_projy0_stack_1->GetZaxis()->SetLabelFont(42);
   Background_0x0_pass_postfit_projy0_stack_1->GetZaxis()->SetLabelSize(0.035);
   Background_0x0_pass_postfit_projy0_stack_1->GetZaxis()->SetTitleSize(0.035);
   Background_0x0_pass_postfit_projy0_stack_1->GetZaxis()->SetTitleFont(42);
   postfit_projy0_pass_logy_stack->Add(Background_0x0_pass_postfit_projy0_stack_1,"");
   postfit_projy0_pass_logy_stack->Draw("hist same");
   
   postfit_projy0_pass_logy_stack = new THStack();
   postfit_projy0_pass_logy_stack->SetName("postfit_projy0_pass_logy_stack");
   postfit_projy0_pass_logy_stack->SetTitle("postfit_projy0_pass_logy_stack");
   postfit_projy0_pass_logy_stack->SetMinimum(0.001);
   Double_t xAxis256[2] = {200, 4025}; 
   
   TH1F *postfit_projy0_pass_logy_stack_stack_43_stack_44 = new TH1F("postfit_projy0_pass_logy_stack_stack_43_stack_44","postfit_projy0_pass_logy_stack",1, xAxis256);
   postfit_projy0_pass_logy_stack_stack_43_stack_44->SetMinimum(0.0002080643);
   postfit_projy0_pass_logy_stack_stack_43_stack_44->SetMaximum(103333.5);
   postfit_projy0_pass_logy_stack_stack_43_stack_44->SetDirectory(0);
   postfit_projy0_pass_logy_stack_stack_43_stack_44->SetStats(0);
   postfit_projy0_pass_logy_stack_stack_43_stack_44->SetLineStyle(0);
   postfit_projy0_pass_logy_stack_stack_43_stack_44->GetXaxis()->SetLabelFont(42);
   postfit_projy0_pass_logy_stack_stack_43_stack_44->GetXaxis()->SetLabelOffset(0.007);
   postfit_projy0_pass_logy_stack_stack_43_stack_44->GetXaxis()->SetLabelSize(0.05);
   postfit_projy0_pass_logy_stack_stack_43_stack_44->GetXaxis()->SetTitleSize(0.08);
   postfit_projy0_pass_logy_stack_stack_43_stack_44->GetXaxis()->SetTitleOffset(0.9);
   postfit_projy0_pass_logy_stack_stack_43_stack_44->GetXaxis()->SetTitleFont(42);
   postfit_projy0_pass_logy_stack_stack_43_stack_44->GetYaxis()->SetNdivisions(508);
   postfit_projy0_pass_logy_stack_stack_43_stack_44->GetYaxis()->SetLabelFont(42);
   postfit_projy0_pass_logy_stack_stack_43_stack_44->GetYaxis()->SetLabelOffset(0.007);
   postfit_projy0_pass_logy_stack_stack_43_stack_44->GetYaxis()->SetLabelSize(0.05);
   postfit_projy0_pass_logy_stack_stack_43_stack_44->GetYaxis()->SetTitleSize(0.08);
   postfit_projy0_pass_logy_stack_stack_43_stack_44->GetYaxis()->SetTitleOffset(1.25);
   postfit_projy0_pass_logy_stack_stack_43_stack_44->GetYaxis()->SetTitleFont(42);
   postfit_projy0_pass_logy_stack_stack_43_stack_44->GetZaxis()->SetLabelFont(42);
   postfit_projy0_pass_logy_stack_stack_43_stack_44->GetZaxis()->SetLabelOffset(0.007);
   postfit_projy0_pass_logy_stack_stack_43_stack_44->GetZaxis()->SetLabelSize(0.05);
   postfit_projy0_pass_logy_stack_stack_43_stack_44->GetZaxis()->SetTitleSize(0.08);
   postfit_projy0_pass_logy_stack_stack_43_stack_44->GetZaxis()->SetTitleFont(42);
   postfit_projy0_pass_logy_stack->SetHistogram(postfit_projy0_pass_logy_stack_stack_43_stack_44);
   
   Double_t xAxis257[2] = {200, 4025}; 
   
   TH1D *Background_0x0_pass_postfit_projy0_stack_1_stack_1 = new TH1D("Background_0x0_pass_postfit_projy0_stack_1_stack_1","Background, pass, postfit, 0.0-0.25",1, xAxis257);
   Background_0x0_pass_postfit_projy0_stack_1_stack_1->SetBinContent(1,40776.9);
   Background_0x0_pass_postfit_projy0_stack_1_stack_1->SetBinError(1,188.0987);
   Background_0x0_pass_postfit_projy0_stack_1_stack_1->SetMinimum(0.001);
   Background_0x0_pass_postfit_projy0_stack_1_stack_1->SetEntries(46995.59);
   Background_0x0_pass_postfit_projy0_stack_1_stack_1->SetStats(0);

   ci = TColor::GetColor("#ffff00");
   Background_0x0_pass_postfit_projy0_stack_1_stack_1->SetFillColor(ci);

   ci = 1200;
   color = new TColor(ci, 1, 1, 1, " ", 0);
   Background_0x0_pass_postfit_projy0_stack_1_stack_1->SetLineColor(ci);
   Background_0x0_pass_postfit_projy0_stack_1_stack_1->GetXaxis()->SetTitle("p_{T}");
   Background_0x0_pass_postfit_projy0_stack_1_stack_1->GetXaxis()->SetLabelFont(42);
   Background_0x0_pass_postfit_projy0_stack_1_stack_1->GetXaxis()->SetLabelSize(0.035);
   Background_0x0_pass_postfit_projy0_stack_1_stack_1->GetXaxis()->SetTitleSize(0.035);
   Background_0x0_pass_postfit_projy0_stack_1_stack_1->GetXaxis()->SetTitleOffset(0);
   Background_0x0_pass_postfit_projy0_stack_1_stack_1->GetXaxis()->SetTitleFont(42);
   Background_0x0_pass_postfit_projy0_stack_1_stack_1->GetYaxis()->SetTitle("Events / bin");
   Background_0x0_pass_postfit_projy0_stack_1_stack_1->GetYaxis()->SetLabelFont(42);
   Background_0x0_pass_postfit_projy0_stack_1_stack_1->GetYaxis()->SetLabelSize(0.035);
   Background_0x0_pass_postfit_projy0_stack_1_stack_1->GetYaxis()->SetTitleSize(0.035);
   Background_0x0_pass_postfit_projy0_stack_1_stack_1->GetYaxis()->SetTitleOffset(0);
   Background_0x0_pass_postfit_projy0_stack_1_stack_1->GetYaxis()->SetTitleFont(42);
   Background_0x0_pass_postfit_projy0_stack_1_stack_1->GetZaxis()->SetLabelFont(42);
   Background_0x0_pass_postfit_projy0_stack_1_stack_1->GetZaxis()->SetLabelSize(0.035);
   Background_0x0_pass_postfit_projy0_stack_1_stack_1->GetZaxis()->SetTitleSize(0.035);
   Background_0x0_pass_postfit_projy0_stack_1_stack_1->GetZaxis()->SetTitleFont(42);
   postfit_projy0_pass_logy_stack->Add(Background_0x0_pass_postfit_projy0_stack_1_stack_1,"");
   postfit_projy0_pass_logy_stack->Draw("hist same");
   Double_t xAxis258[2] = {200, 4025}; 
   
   TH1D *Signal_gluinomI1800_pass_postfit_projy0__170 = new TH1D("Signal_gluinomI1800_pass_postfit_projy0__170","HSCP gluino 1800 GeV, pass, postfit, 0.0-0.25",1, xAxis258);
   Signal_gluinomI1800_pass_postfit_projy0__170->SetBinContent(1,0.2719239);
   Signal_gluinomI1800_pass_postfit_projy0__170->SetBinError(1,0.01880066);
   Signal_gluinomI1800_pass_postfit_projy0__170->SetMinimum(0.001);
   Signal_gluinomI1800_pass_postfit_projy0__170->SetEntries(209.1937);
   Signal_gluinomI1800_pass_postfit_projy0__170->SetStats(0);
   Signal_gluinomI1800_pass_postfit_projy0__170->SetLineColor(4);
   Signal_gluinomI1800_pass_postfit_projy0__170->SetLineWidth(2);
   Signal_gluinomI1800_pass_postfit_projy0__170->GetXaxis()->SetTitle("p_{T}");
   Signal_gluinomI1800_pass_postfit_projy0__170->GetXaxis()->SetLabelFont(42);
   Signal_gluinomI1800_pass_postfit_projy0__170->GetXaxis()->SetLabelSize(0.035);
   Signal_gluinomI1800_pass_postfit_projy0__170->GetXaxis()->SetTitleSize(0.035);
   Signal_gluinomI1800_pass_postfit_projy0__170->GetXaxis()->SetTitleOffset(0);
   Signal_gluinomI1800_pass_postfit_projy0__170->GetXaxis()->SetTitleFont(42);
   Signal_gluinomI1800_pass_postfit_projy0__170->GetYaxis()->SetTitle("Events / bin");
   Signal_gluinomI1800_pass_postfit_projy0__170->GetYaxis()->SetLabelFont(42);
   Signal_gluinomI1800_pass_postfit_projy0__170->GetYaxis()->SetLabelSize(0.035);
   Signal_gluinomI1800_pass_postfit_projy0__170->GetYaxis()->SetTitleSize(0.035);
   Signal_gluinomI1800_pass_postfit_projy0__170->GetYaxis()->SetTitleOffset(0);
   Signal_gluinomI1800_pass_postfit_projy0__170->GetYaxis()->SetTitleFont(42);
   Signal_gluinomI1800_pass_postfit_projy0__170->GetZaxis()->SetLabelFont(42);
   Signal_gluinomI1800_pass_postfit_projy0__170->GetZaxis()->SetLabelSize(0.035);
   Signal_gluinomI1800_pass_postfit_projy0__170->GetZaxis()->SetTitleSize(0.035);
   Signal_gluinomI1800_pass_postfit_projy0__170->GetZaxis()->SetTitleFont(42);
   Signal_gluinomI1800_pass_postfit_projy0__170->Draw("hist same");
   Double_t xAxis259[2] = {200, 4025}; 
   
   TH1D *Signal_ppStaumI557_pass_postfit_projy0__171 = new TH1D("Signal_ppStaumI557_pass_postfit_projy0__171","HSCP stau 557 GeV, pass, postfit, 0.0-0.25",1, xAxis259);
   Signal_ppStaumI557_pass_postfit_projy0__171->SetBinContent(1,1.933126);
   Signal_ppStaumI557_pass_postfit_projy0__171->SetBinError(1,0.03011569);
   Signal_ppStaumI557_pass_postfit_projy0__171->SetMinimum(0.001);
   Signal_ppStaumI557_pass_postfit_projy0__171->SetEntries(4120.358);
   Signal_ppStaumI557_pass_postfit_projy0__171->SetStats(0);
   Signal_ppStaumI557_pass_postfit_projy0__171->SetLineColor(2);
   Signal_ppStaumI557_pass_postfit_projy0__171->SetLineWidth(2);
   Signal_ppStaumI557_pass_postfit_projy0__171->GetXaxis()->SetTitle("p_{T}");
   Signal_ppStaumI557_pass_postfit_projy0__171->GetXaxis()->SetLabelFont(42);
   Signal_ppStaumI557_pass_postfit_projy0__171->GetXaxis()->SetLabelSize(0.035);
   Signal_ppStaumI557_pass_postfit_projy0__171->GetXaxis()->SetTitleSize(0.035);
   Signal_ppStaumI557_pass_postfit_projy0__171->GetXaxis()->SetTitleOffset(0);
   Signal_ppStaumI557_pass_postfit_projy0__171->GetXaxis()->SetTitleFont(42);
   Signal_ppStaumI557_pass_postfit_projy0__171->GetYaxis()->SetTitle("Events / bin");
   Signal_ppStaumI557_pass_postfit_projy0__171->GetYaxis()->SetLabelFont(42);
   Signal_ppStaumI557_pass_postfit_projy0__171->GetYaxis()->SetLabelSize(0.035);
   Signal_ppStaumI557_pass_postfit_projy0__171->GetYaxis()->SetTitleSize(0.035);
   Signal_ppStaumI557_pass_postfit_projy0__171->GetYaxis()->SetTitleOffset(0);
   Signal_ppStaumI557_pass_postfit_projy0__171->GetYaxis()->SetTitleFont(42);
   Signal_ppStaumI557_pass_postfit_projy0__171->GetZaxis()->SetLabelFont(42);
   Signal_ppStaumI557_pass_postfit_projy0__171->GetZaxis()->SetLabelSize(0.035);
   Signal_ppStaumI557_pass_postfit_projy0__171->GetZaxis()->SetTitleSize(0.035);
   Signal_ppStaumI557_pass_postfit_projy0__171->GetZaxis()->SetTitleFont(42);
   Signal_ppStaumI557_pass_postfit_projy0__171->Draw("hist same");
   Double_t xAxis260[2] = {200, 4025}; 
   
   TH1D *TotalBkg_pass_postfit_projy0__172 = new TH1D("TotalBkg_pass_postfit_projy0__172","TotalBkg, pass, postfit, 0.0-0.25",1, xAxis260);
   TotalBkg_pass_postfit_projy0__172->SetBinContent(1,40776.9);
   TotalBkg_pass_postfit_projy0__172->SetBinError(1,184.617);
   TotalBkg_pass_postfit_projy0__172->SetMinimum(0.001);
   TotalBkg_pass_postfit_projy0__172->SetEntries(48784.86);
   TotalBkg_pass_postfit_projy0__172->SetStats(0);
   TotalBkg_pass_postfit_projy0__172->SetMarkerStyle(0);
   TotalBkg_pass_postfit_projy0__172->GetXaxis()->SetTitle("p_{T}");
   TotalBkg_pass_postfit_projy0__172->GetXaxis()->SetLabelFont(42);
   TotalBkg_pass_postfit_projy0__172->GetXaxis()->SetLabelSize(0.035);
   TotalBkg_pass_postfit_projy0__172->GetXaxis()->SetTitleSize(0.035);
   TotalBkg_pass_postfit_projy0__172->GetXaxis()->SetTitleOffset(0);
   TotalBkg_pass_postfit_projy0__172->GetXaxis()->SetTitleFont(42);
   TotalBkg_pass_postfit_projy0__172->GetYaxis()->SetTitle("Events / bin");
   TotalBkg_pass_postfit_projy0__172->GetYaxis()->SetLabelFont(42);
   TotalBkg_pass_postfit_projy0__172->GetYaxis()->SetLabelSize(0.035);
   TotalBkg_pass_postfit_projy0__172->GetYaxis()->SetTitleSize(0.035);
   TotalBkg_pass_postfit_projy0__172->GetYaxis()->SetTitleOffset(0);
   TotalBkg_pass_postfit_projy0__172->GetYaxis()->SetTitleFont(42);
   TotalBkg_pass_postfit_projy0__172->GetZaxis()->SetLabelFont(42);
   TotalBkg_pass_postfit_projy0__172->GetZaxis()->SetLabelSize(0.035);
   TotalBkg_pass_postfit_projy0__172->GetZaxis()->SetTitleSize(0.035);
   TotalBkg_pass_postfit_projy0__172->GetZaxis()->SetTitleFont(42);
   TotalBkg_pass_postfit_projy0__172->Draw("hist same");
   Double_t xAxis261[2] = {200, 4025}; 
   
   TH1D *TotalBkg_pass_postfit_projy0__173 = new TH1D("TotalBkg_pass_postfit_projy0__173","TotalBkg, pass, postfit, 0.0-0.25",1, xAxis261);
   TotalBkg_pass_postfit_projy0__173->SetBinContent(1,40776.9);
   TotalBkg_pass_postfit_projy0__173->SetBinError(1,184.617);
   TotalBkg_pass_postfit_projy0__173->SetMinimum(0.001);
   TotalBkg_pass_postfit_projy0__173->SetEntries(48784.86);
   TotalBkg_pass_postfit_projy0__173->SetStats(0);
   TotalBkg_pass_postfit_projy0__173->SetFillColor(1);
   TotalBkg_pass_postfit_projy0__173->SetFillStyle(3354);
   TotalBkg_pass_postfit_projy0__173->SetLineWidth(0);
   TotalBkg_pass_postfit_projy0__173->SetMarkerStyle(0);
   TotalBkg_pass_postfit_projy0__173->GetXaxis()->SetTitle("p_{T}");
   TotalBkg_pass_postfit_projy0__173->GetXaxis()->SetLabelFont(42);
   TotalBkg_pass_postfit_projy0__173->GetXaxis()->SetLabelSize(0.035);
   TotalBkg_pass_postfit_projy0__173->GetXaxis()->SetTitleSize(0.035);
   TotalBkg_pass_postfit_projy0__173->GetXaxis()->SetTitleOffset(0);
   TotalBkg_pass_postfit_projy0__173->GetXaxis()->SetTitleFont(42);
   TotalBkg_pass_postfit_projy0__173->GetYaxis()->SetTitle("Events / bin");
   TotalBkg_pass_postfit_projy0__173->GetYaxis()->SetLabelFont(42);
   TotalBkg_pass_postfit_projy0__173->GetYaxis()->SetLabelSize(0.035);
   TotalBkg_pass_postfit_projy0__173->GetYaxis()->SetTitleSize(0.035);
   TotalBkg_pass_postfit_projy0__173->GetYaxis()->SetTitleOffset(0);
   TotalBkg_pass_postfit_projy0__173->GetYaxis()->SetTitleFont(42);
   TotalBkg_pass_postfit_projy0__173->GetZaxis()->SetLabelFont(42);
   TotalBkg_pass_postfit_projy0__173->GetZaxis()->SetLabelSize(0.035);
   TotalBkg_pass_postfit_projy0__173->GetZaxis()->SetTitleSize(0.035);
   TotalBkg_pass_postfit_projy0__173->GetZaxis()->SetTitleFont(42);
   TotalBkg_pass_postfit_projy0__173->Draw("e2 same");
   Double_t xAxis262[2] = {200, 4025}; 
   
   TH1D *data_obs_pass_postfit_projy0__174 = new TH1D("data_obs_pass_postfit_projy0__174","",1, xAxis262);
   data_obs_pass_postfit_projy0__174->SetBinContent(1,40782);
   data_obs_pass_postfit_projy0__174->SetBinError(1,201.9455);
   data_obs_pass_postfit_projy0__174->SetMinimum(0.001);
   data_obs_pass_postfit_projy0__174->SetMaximum(3716260);
   data_obs_pass_postfit_projy0__174->SetEntries(40782);
   data_obs_pass_postfit_projy0__174->SetStats(0);

   ci = TColor::GetColor("#000000");
   data_obs_pass_postfit_projy0__174->SetLineColor(ci);

   ci = TColor::GetColor("#000000");
   data_obs_pass_postfit_projy0__174->SetMarkerColor(ci);
   data_obs_pass_postfit_projy0__174->SetMarkerStyle(8);
   data_obs_pass_postfit_projy0__174->GetXaxis()->SetTitle("p_{T}");
   data_obs_pass_postfit_projy0__174->GetXaxis()->SetLabelFont(42);
   data_obs_pass_postfit_projy0__174->GetXaxis()->SetLabelOffset(0.05);
   data_obs_pass_postfit_projy0__174->GetXaxis()->SetLabelSize(0.07);
   data_obs_pass_postfit_projy0__174->GetXaxis()->SetTitleSize(0.09);
   data_obs_pass_postfit_projy0__174->GetXaxis()->SetTitleOffset(1.15);
   data_obs_pass_postfit_projy0__174->GetXaxis()->SetTitleFont(42);
   data_obs_pass_postfit_projy0__174->GetYaxis()->SetTitle("Events / bin");
   data_obs_pass_postfit_projy0__174->GetYaxis()->SetNdivisions(508);
   data_obs_pass_postfit_projy0__174->GetYaxis()->SetLabelFont(42);
   data_obs_pass_postfit_projy0__174->GetYaxis()->SetLabelSize(0.07);
   data_obs_pass_postfit_projy0__174->GetYaxis()->SetTitleSize(0.09);
   data_obs_pass_postfit_projy0__174->GetYaxis()->SetTitleOffset(0.8);
   data_obs_pass_postfit_projy0__174->GetYaxis()->SetTitleFont(42);
   data_obs_pass_postfit_projy0__174->GetZaxis()->SetLabelFont(42);
   data_obs_pass_postfit_projy0__174->GetZaxis()->SetLabelSize(0.035);
   data_obs_pass_postfit_projy0__174->GetZaxis()->SetTitleSize(0.035);
   data_obs_pass_postfit_projy0__174->GetZaxis()->SetTitleFont(42);
   data_obs_pass_postfit_projy0__174->Draw("pe X0 same");
   
   TLegend *leg = new TLegend(0.65,0.61,0.9,0.88,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(1001);
   TLegendEntry *entry=leg->AddEntry("data_obs_pass_postfit_projy0","Data","pe X0");

   ci = TColor::GetColor("#000000");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);

   ci = TColor::GetColor("#000000");
   entry->SetMarkerColor(ci);
   entry->SetMarkerStyle(8);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("TotalBkg_pass_postfit_projy0","Total bkg unc.","F");
   entry->SetFillColor(1);
   entry->SetFillStyle(3354);
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("Signal_gluino-1800_pass_postfit_projy0","HSCP gluino 1800 GeV","L");
   entry->SetLineColor(4);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("Signal_ppStau-557_pass_postfit_projy0","HSCP stau 557 GeV","L");
   entry->SetLineColor(2);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("Background_0x0_pass_postfit_projy0_stack_1_stack_1","Background","f");

   ci = TColor::GetColor("#ffff00");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = 1200;
   color = new TColor(ci, 1, 1, 1, " ", 0);
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   leg->Draw();
   Double_t xAxis263[2] = {200, 4025}; 
   
   TH1D *data_obs_pass_postfit_projy0_copy__175 = new TH1D("data_obs_pass_postfit_projy0_copy__175","",1, xAxis263);
   data_obs_pass_postfit_projy0_copy__175->SetBinContent(1,40782);
   data_obs_pass_postfit_projy0_copy__175->SetBinError(1,201.9455);
   data_obs_pass_postfit_projy0_copy__175->SetMinimum(0.001);
   data_obs_pass_postfit_projy0_copy__175->SetMaximum(3716260);
   data_obs_pass_postfit_projy0_copy__175->SetEntries(40782);
   data_obs_pass_postfit_projy0_copy__175->SetDirectory(0);
   data_obs_pass_postfit_projy0_copy__175->SetStats(0);

   ci = TColor::GetColor("#000000");
   data_obs_pass_postfit_projy0_copy__175->SetLineColor(ci);

   ci = TColor::GetColor("#000000");
   data_obs_pass_postfit_projy0_copy__175->SetMarkerColor(ci);
   data_obs_pass_postfit_projy0_copy__175->SetMarkerStyle(8);
   data_obs_pass_postfit_projy0_copy__175->GetXaxis()->SetTitle("p_{T}");
   data_obs_pass_postfit_projy0_copy__175->GetXaxis()->SetLabelFont(42);
   data_obs_pass_postfit_projy0_copy__175->GetXaxis()->SetLabelOffset(0.05);
   data_obs_pass_postfit_projy0_copy__175->GetXaxis()->SetLabelSize(0.07);
   data_obs_pass_postfit_projy0_copy__175->GetXaxis()->SetTitleSize(0.09);
   data_obs_pass_postfit_projy0_copy__175->GetXaxis()->SetTitleOffset(1.15);
   data_obs_pass_postfit_projy0_copy__175->GetXaxis()->SetTitleFont(42);
   data_obs_pass_postfit_projy0_copy__175->GetYaxis()->SetTitle("Events / bin");
   data_obs_pass_postfit_projy0_copy__175->GetYaxis()->SetNdivisions(508);
   data_obs_pass_postfit_projy0_copy__175->GetYaxis()->SetLabelFont(42);
   data_obs_pass_postfit_projy0_copy__175->GetYaxis()->SetLabelSize(0.07);
   data_obs_pass_postfit_projy0_copy__175->GetYaxis()->SetTitleSize(0.09);
   data_obs_pass_postfit_projy0_copy__175->GetYaxis()->SetTitleOffset(0.8);
   data_obs_pass_postfit_projy0_copy__175->GetYaxis()->SetTitleFont(42);
   data_obs_pass_postfit_projy0_copy__175->GetZaxis()->SetLabelFont(42);
   data_obs_pass_postfit_projy0_copy__175->GetZaxis()->SetLabelSize(0.035);
   data_obs_pass_postfit_projy0_copy__175->GetZaxis()->SetTitleSize(0.035);
   data_obs_pass_postfit_projy0_copy__175->GetZaxis()->SetTitleFont(42);
   data_obs_pass_postfit_projy0_copy__175->Draw("sameaxis");
   TLatex *   tex = new TLatex(0.21,0.83,"0.0 < G_{i}^{Strips} < 0.25 , F^{Pixels}_{i} > 0.9");
tex->SetNDC();
   tex->SetTextAlign(12);
   tex->SetTextFont(42);
   tex->SetTextSize(0.06);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.17,0.92,"CMS");
tex->SetNDC();
   tex->SetTextFont(61);
   tex->SetTextSize(0.0675);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.25,0.92,"Preliminary");
tex->SetNDC();
   tex->SetTextFont(52);
   tex->SetTextSize(0.0485);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.95,0.92,"101 fb^{-1} (13 TeV)");
tex->SetNDC();
   tex->SetTextAlign(31);
   tex->SetTextFont(42);
   tex->SetTextSize(0.07);
   tex->SetLineWidth(2);
   tex->Draw();
   data_obs_pass_postfit_projy0_main->Modified();
   plots_fit_b/base_figs/postfit_projy0_pass_logy->cd();
  
// ------------>Primitives in pad: data_obs_pass_postfit_projy0_sub
   TPad *data_obs_pass_postfit_projy0_sub = new TPad("data_obs_pass_postfit_projy0_sub", "data_obs_pass_postfit_projy0_sub",0,0,1,0.35);
   data_obs_pass_postfit_projy0_sub->Draw();
   data_obs_pass_postfit_projy0_sub->cd();
   data_obs_pass_postfit_projy0_sub->Range(-633.6539,-6.023077,4270.192,2.9);
   data_obs_pass_postfit_projy0_sub->SetFillColor(0);
   data_obs_pass_postfit_projy0_sub->SetBorderMode(0);
   data_obs_pass_postfit_projy0_sub->SetBorderSize(2);
   data_obs_pass_postfit_projy0_sub->SetTickx(1);
   data_obs_pass_postfit_projy0_sub->SetTicky(1);
   data_obs_pass_postfit_projy0_sub->SetLeftMargin(0.17);
   data_obs_pass_postfit_projy0_sub->SetRightMargin(0.05);
   data_obs_pass_postfit_projy0_sub->SetTopMargin(0);
   data_obs_pass_postfit_projy0_sub->SetBottomMargin(0.35);
   data_obs_pass_postfit_projy0_sub->SetFrameFillStyle(0);
   data_obs_pass_postfit_projy0_sub->SetFrameBorderMode(0);
   data_obs_pass_postfit_projy0_sub->SetFrameFillStyle(0);
   data_obs_pass_postfit_projy0_sub->SetFrameBorderMode(0);
   Double_t xAxis264[2] = {200, 4025}; 
   
   TH1D *data_obs_pass_postfit_projy0_pull__176 = new TH1D("data_obs_pass_postfit_projy0_pull__176","",1, xAxis264);
   data_obs_pass_postfit_projy0_pull__176->SetBinContent(1,0.0186283);
   data_obs_pass_postfit_projy0_pull__176->SetBinError(1,273.6155);
   data_obs_pass_postfit_projy0_pull__176->SetMinimum(-2.9);
   data_obs_pass_postfit_projy0_pull__176->SetMaximum(2.9);
   data_obs_pass_postfit_projy0_pull__176->SetEntries(1.000347);
   data_obs_pass_postfit_projy0_pull__176->SetStats(0);

   ci = TColor::GetColor("#0000ff");
   data_obs_pass_postfit_projy0_pull__176->SetFillColor(ci);

   ci = TColor::GetColor("#000000");
   data_obs_pass_postfit_projy0_pull__176->SetLineColor(ci);

   ci = TColor::GetColor("#000000");
   data_obs_pass_postfit_projy0_pull__176->SetMarkerColor(ci);
   data_obs_pass_postfit_projy0_pull__176->SetMarkerStyle(8);
   data_obs_pass_postfit_projy0_pull__176->GetXaxis()->SetTitle("p_{T}");
   data_obs_pass_postfit_projy0_pull__176->GetXaxis()->SetLabelFont(42);
   data_obs_pass_postfit_projy0_pull__176->GetXaxis()->SetLabelOffset(0.05);
   data_obs_pass_postfit_projy0_pull__176->GetXaxis()->SetLabelSize(0.13);
   data_obs_pass_postfit_projy0_pull__176->GetXaxis()->SetTitleSize(0.15);
   data_obs_pass_postfit_projy0_pull__176->GetXaxis()->SetTitleOffset(1.15);
   data_obs_pass_postfit_projy0_pull__176->GetXaxis()->SetTitleFont(42);
   data_obs_pass_postfit_projy0_pull__176->GetYaxis()->SetTitle("(Data-Bkg)/#sigma");
   data_obs_pass_postfit_projy0_pull__176->GetYaxis()->SetNdivisions(306);
   data_obs_pass_postfit_projy0_pull__176->GetYaxis()->SetLabelFont(42);
   data_obs_pass_postfit_projy0_pull__176->GetYaxis()->SetLabelSize(0.13);
   data_obs_pass_postfit_projy0_pull__176->GetYaxis()->SetTitleSize(0.12);
   data_obs_pass_postfit_projy0_pull__176->GetYaxis()->SetTitleOffset(0.4);
   data_obs_pass_postfit_projy0_pull__176->GetYaxis()->SetTitleFont(42);
   data_obs_pass_postfit_projy0_pull__176->GetZaxis()->SetLabelFont(42);
   data_obs_pass_postfit_projy0_pull__176->GetZaxis()->SetLabelSize(0.035);
   data_obs_pass_postfit_projy0_pull__176->GetZaxis()->SetTitleSize(0.035);
   data_obs_pass_postfit_projy0_pull__176->GetZaxis()->SetTitleFont(42);
   data_obs_pass_postfit_projy0_pull__176->Draw("hist");
   data_obs_pass_postfit_projy0_sub->Modified();
   plots_fit_b/base_figs/postfit_projy0_pass_logy->cd();
   plots_fit_b/base_figs/postfit_projy0_pass_logy->Modified();
   plots_fit_b/base_figs/postfit_projy0_pass_logy->cd();
   plots_fit_b/base_figs/postfit_projy0_pass_logy->SetSelected(plots_fit_b/base_figs/postfit_projy0_pass_logy);
}
