void postfit_projy2_pass_logy()
{
//=========Macro generated from canvas: plots_fit_b/base_figs/postfit_projy2_pass_logy/plots_fit_b/base_figs/postfit_projy2_pass_logy
//=========  (Fri Jan 12 20:33:17 2024) by ROOT version 6.14/09
   TCanvas *plots_fit_b/base_figs/postfit_projy2_pass_logy = new TCanvas("plots_fit_b/base_figs/postfit_projy2_pass_logy", "plots_fit_b/base_figs/postfit_projy2_pass_logy",0,0,800,700);
   gStyle->SetOptFit(1);
   gStyle->SetOptStat(0);
   plots_fit_b/base_figs/postfit_projy2_pass_logy->SetHighLightColor(2);
   plots_fit_b/base_figs/postfit_projy2_pass_logy->Range(0,0,1,1);
   plots_fit_b/base_figs/postfit_projy2_pass_logy->SetFillColor(0);
   plots_fit_b/base_figs/postfit_projy2_pass_logy->SetBorderMode(0);
   plots_fit_b/base_figs/postfit_projy2_pass_logy->SetBorderSize(2);
   plots_fit_b/base_figs/postfit_projy2_pass_logy->SetTickx(1);
   plots_fit_b/base_figs/postfit_projy2_pass_logy->SetTicky(1);
   plots_fit_b/base_figs/postfit_projy2_pass_logy->SetLeftMargin(0.16);
   plots_fit_b/base_figs/postfit_projy2_pass_logy->SetRightMargin(0);
   plots_fit_b/base_figs/postfit_projy2_pass_logy->SetTopMargin(0);
   plots_fit_b/base_figs/postfit_projy2_pass_logy->SetBottomMargin(0);
   plots_fit_b/base_figs/postfit_projy2_pass_logy->SetFrameFillStyle(0);
   plots_fit_b/base_figs/postfit_projy2_pass_logy->SetFrameBorderMode(0);
  
// ------------>Primitives in pad: data_obs_pass_postfit_projy2_main
   TPad *data_obs_pass_postfit_projy2_main = new TPad("data_obs_pass_postfit_projy2_main", "data_obs_pass_postfit_projy2_main",0,0.35,1,1);
   data_obs_pass_postfit_projy2_main->Draw();
   data_obs_pass_postfit_projy2_main->cd();
   data_obs_pass_postfit_projy2_main->Range(-633.6539,-2.139535,4270.192,1.348837);
   data_obs_pass_postfit_projy2_main->SetFillColor(0);
   data_obs_pass_postfit_projy2_main->SetBorderMode(0);
   data_obs_pass_postfit_projy2_main->SetBorderSize(2);
   data_obs_pass_postfit_projy2_main->SetLogy();
   data_obs_pass_postfit_projy2_main->SetTickx(1);
   data_obs_pass_postfit_projy2_main->SetTicky(1);
   data_obs_pass_postfit_projy2_main->SetLeftMargin(0.17);
   data_obs_pass_postfit_projy2_main->SetRightMargin(0.05);
   data_obs_pass_postfit_projy2_main->SetBottomMargin(0.04);
   data_obs_pass_postfit_projy2_main->SetFrameFillStyle(0);
   data_obs_pass_postfit_projy2_main->SetFrameBorderMode(0);
   data_obs_pass_postfit_projy2_main->SetFrameFillStyle(0);
   data_obs_pass_postfit_projy2_main->SetFrameBorderMode(0);
   Double_t xAxis277[2] = {200, 4025}; 
   
   TH1D *data_obs_pass_postfit_projy2__185 = new TH1D("data_obs_pass_postfit_projy2__185","",1, xAxis277);
   data_obs_pass_postfit_projy2__185->SetMinimum(0.001);
   data_obs_pass_postfit_projy2__185->SetMaximum(0);
   data_obs_pass_postfit_projy2__185->SetStats(0);

   Int_t ci;      // for color index setting
   TColor *color; // for color definition with alpha
   ci = TColor::GetColor("#000000");
   data_obs_pass_postfit_projy2__185->SetLineColor(ci);

   ci = TColor::GetColor("#000000");
   data_obs_pass_postfit_projy2__185->SetMarkerColor(ci);
   data_obs_pass_postfit_projy2__185->SetMarkerStyle(8);
   data_obs_pass_postfit_projy2__185->GetXaxis()->SetTitle("p_{T}");
   data_obs_pass_postfit_projy2__185->GetXaxis()->SetLabelFont(42);
   data_obs_pass_postfit_projy2__185->GetXaxis()->SetLabelOffset(0.05);
   data_obs_pass_postfit_projy2__185->GetXaxis()->SetLabelSize(0.07);
   data_obs_pass_postfit_projy2__185->GetXaxis()->SetTitleSize(0.09);
   data_obs_pass_postfit_projy2__185->GetXaxis()->SetTitleOffset(1.15);
   data_obs_pass_postfit_projy2__185->GetXaxis()->SetTitleFont(42);
   data_obs_pass_postfit_projy2__185->GetYaxis()->SetTitle("Events / bin");
   data_obs_pass_postfit_projy2__185->GetYaxis()->SetNdivisions(508);
   data_obs_pass_postfit_projy2__185->GetYaxis()->SetLabelFont(42);
   data_obs_pass_postfit_projy2__185->GetYaxis()->SetLabelSize(0.07);
   data_obs_pass_postfit_projy2__185->GetYaxis()->SetTitleSize(0.09);
   data_obs_pass_postfit_projy2__185->GetYaxis()->SetTitleOffset(0.8);
   data_obs_pass_postfit_projy2__185->GetYaxis()->SetTitleFont(42);
   data_obs_pass_postfit_projy2__185->GetZaxis()->SetLabelFont(42);
   data_obs_pass_postfit_projy2__185->GetZaxis()->SetLabelSize(0.035);
   data_obs_pass_postfit_projy2__185->GetZaxis()->SetTitleSize(0.035);
   data_obs_pass_postfit_projy2__185->GetZaxis()->SetTitleFont(42);
   data_obs_pass_postfit_projy2__185->Draw("pe X0");
   
   THStack *postfit_projy2_pass_logy_stack = new THStack();
   postfit_projy2_pass_logy_stack->SetName("postfit_projy2_pass_logy_stack");
   postfit_projy2_pass_logy_stack->SetTitle("postfit_projy2_pass_logy_stack");
   postfit_projy2_pass_logy_stack->SetMinimum(0.001);
   Double_t xAxis278[2] = {200, 4025}; 
   
   TH1F *postfit_projy2_pass_logy_stack_stack_47 = new TH1F("postfit_projy2_pass_logy_stack_stack_47","postfit_projy2_pass_logy_stack",1, xAxis278);
   postfit_projy2_pass_logy_stack_stack_47->SetMinimum(-0);
   postfit_projy2_pass_logy_stack_stack_47->SetMaximum(-nan);
   postfit_projy2_pass_logy_stack_stack_47->SetDirectory(0);
   postfit_projy2_pass_logy_stack_stack_47->SetStats(0);
   postfit_projy2_pass_logy_stack_stack_47->SetLineStyle(0);
   postfit_projy2_pass_logy_stack_stack_47->GetXaxis()->SetLabelFont(42);
   postfit_projy2_pass_logy_stack_stack_47->GetXaxis()->SetLabelOffset(0.007);
   postfit_projy2_pass_logy_stack_stack_47->GetXaxis()->SetLabelSize(0.05);
   postfit_projy2_pass_logy_stack_stack_47->GetXaxis()->SetTitleSize(0.08);
   postfit_projy2_pass_logy_stack_stack_47->GetXaxis()->SetTitleOffset(0.9);
   postfit_projy2_pass_logy_stack_stack_47->GetXaxis()->SetTitleFont(42);
   postfit_projy2_pass_logy_stack_stack_47->GetYaxis()->SetNdivisions(508);
   postfit_projy2_pass_logy_stack_stack_47->GetYaxis()->SetLabelFont(42);
   postfit_projy2_pass_logy_stack_stack_47->GetYaxis()->SetLabelOffset(0.007);
   postfit_projy2_pass_logy_stack_stack_47->GetYaxis()->SetLabelSize(0.05);
   postfit_projy2_pass_logy_stack_stack_47->GetYaxis()->SetTitleSize(0.08);
   postfit_projy2_pass_logy_stack_stack_47->GetYaxis()->SetTitleOffset(1.25);
   postfit_projy2_pass_logy_stack_stack_47->GetYaxis()->SetTitleFont(42);
   postfit_projy2_pass_logy_stack_stack_47->GetZaxis()->SetLabelFont(42);
   postfit_projy2_pass_logy_stack_stack_47->GetZaxis()->SetLabelOffset(0.007);
   postfit_projy2_pass_logy_stack_stack_47->GetZaxis()->SetLabelSize(0.05);
   postfit_projy2_pass_logy_stack_stack_47->GetZaxis()->SetTitleSize(0.08);
   postfit_projy2_pass_logy_stack_stack_47->GetZaxis()->SetTitleFont(42);
   postfit_projy2_pass_logy_stack->SetHistogram(postfit_projy2_pass_logy_stack_stack_47);
   
   Double_t xAxis279[2] = {200, 4025}; 
   
   TH1D *Background_0x0_pass_postfit_projy2_stack_1 = new TH1D("Background_0x0_pass_postfit_projy2_stack_1","Background, pass, postfit, 1.0-1.0",1, xAxis279);
   Background_0x0_pass_postfit_projy2_stack_1->SetMinimum(0.001);
   Background_0x0_pass_postfit_projy2_stack_1->SetStats(0);

   ci = TColor::GetColor("#ffff00");
   Background_0x0_pass_postfit_projy2_stack_1->SetFillColor(ci);

   ci = 1202;
   color = new TColor(ci, 1, 1, 1, " ", 0);
   Background_0x0_pass_postfit_projy2_stack_1->SetLineColor(ci);
   Background_0x0_pass_postfit_projy2_stack_1->GetXaxis()->SetTitle("p_{T}");
   Background_0x0_pass_postfit_projy2_stack_1->GetXaxis()->SetLabelFont(42);
   Background_0x0_pass_postfit_projy2_stack_1->GetXaxis()->SetLabelSize(0.035);
   Background_0x0_pass_postfit_projy2_stack_1->GetXaxis()->SetTitleSize(0.035);
   Background_0x0_pass_postfit_projy2_stack_1->GetXaxis()->SetTitleOffset(0);
   Background_0x0_pass_postfit_projy2_stack_1->GetXaxis()->SetTitleFont(42);
   Background_0x0_pass_postfit_projy2_stack_1->GetYaxis()->SetTitle("Events / bin");
   Background_0x0_pass_postfit_projy2_stack_1->GetYaxis()->SetLabelFont(42);
   Background_0x0_pass_postfit_projy2_stack_1->GetYaxis()->SetLabelSize(0.035);
   Background_0x0_pass_postfit_projy2_stack_1->GetYaxis()->SetTitleSize(0.035);
   Background_0x0_pass_postfit_projy2_stack_1->GetYaxis()->SetTitleOffset(0);
   Background_0x0_pass_postfit_projy2_stack_1->GetYaxis()->SetTitleFont(42);
   Background_0x0_pass_postfit_projy2_stack_1->GetZaxis()->SetLabelFont(42);
   Background_0x0_pass_postfit_projy2_stack_1->GetZaxis()->SetLabelSize(0.035);
   Background_0x0_pass_postfit_projy2_stack_1->GetZaxis()->SetTitleSize(0.035);
   Background_0x0_pass_postfit_projy2_stack_1->GetZaxis()->SetTitleFont(42);
   postfit_projy2_pass_logy_stack->Add(Background_0x0_pass_postfit_projy2_stack_1,"");
   postfit_projy2_pass_logy_stack->Draw("hist same");
   
   postfit_projy2_pass_logy_stack = new THStack();
   postfit_projy2_pass_logy_stack->SetName("postfit_projy2_pass_logy_stack");
   postfit_projy2_pass_logy_stack->SetTitle("postfit_projy2_pass_logy_stack");
   postfit_projy2_pass_logy_stack->SetMinimum(0.001);
   Double_t xAxis280[2] = {200, 4025}; 
   
   TH1F *postfit_projy2_pass_logy_stack_stack_47_stack_48 = new TH1F("postfit_projy2_pass_logy_stack_stack_47_stack_48","postfit_projy2_pass_logy_stack",1, xAxis280);
   postfit_projy2_pass_logy_stack_stack_47_stack_48->SetMinimum(-0);
   postfit_projy2_pass_logy_stack_stack_47_stack_48->SetMaximum(-nan);
   postfit_projy2_pass_logy_stack_stack_47_stack_48->SetDirectory(0);
   postfit_projy2_pass_logy_stack_stack_47_stack_48->SetStats(0);
   postfit_projy2_pass_logy_stack_stack_47_stack_48->SetLineStyle(0);
   postfit_projy2_pass_logy_stack_stack_47_stack_48->GetXaxis()->SetLabelFont(42);
   postfit_projy2_pass_logy_stack_stack_47_stack_48->GetXaxis()->SetLabelOffset(0.007);
   postfit_projy2_pass_logy_stack_stack_47_stack_48->GetXaxis()->SetLabelSize(0.05);
   postfit_projy2_pass_logy_stack_stack_47_stack_48->GetXaxis()->SetTitleSize(0.08);
   postfit_projy2_pass_logy_stack_stack_47_stack_48->GetXaxis()->SetTitleOffset(0.9);
   postfit_projy2_pass_logy_stack_stack_47_stack_48->GetXaxis()->SetTitleFont(42);
   postfit_projy2_pass_logy_stack_stack_47_stack_48->GetYaxis()->SetNdivisions(508);
   postfit_projy2_pass_logy_stack_stack_47_stack_48->GetYaxis()->SetLabelFont(42);
   postfit_projy2_pass_logy_stack_stack_47_stack_48->GetYaxis()->SetLabelOffset(0.007);
   postfit_projy2_pass_logy_stack_stack_47_stack_48->GetYaxis()->SetLabelSize(0.05);
   postfit_projy2_pass_logy_stack_stack_47_stack_48->GetYaxis()->SetTitleSize(0.08);
   postfit_projy2_pass_logy_stack_stack_47_stack_48->GetYaxis()->SetTitleOffset(1.25);
   postfit_projy2_pass_logy_stack_stack_47_stack_48->GetYaxis()->SetTitleFont(42);
   postfit_projy2_pass_logy_stack_stack_47_stack_48->GetZaxis()->SetLabelFont(42);
   postfit_projy2_pass_logy_stack_stack_47_stack_48->GetZaxis()->SetLabelOffset(0.007);
   postfit_projy2_pass_logy_stack_stack_47_stack_48->GetZaxis()->SetLabelSize(0.05);
   postfit_projy2_pass_logy_stack_stack_47_stack_48->GetZaxis()->SetTitleSize(0.08);
   postfit_projy2_pass_logy_stack_stack_47_stack_48->GetZaxis()->SetTitleFont(42);
   postfit_projy2_pass_logy_stack->SetHistogram(postfit_projy2_pass_logy_stack_stack_47_stack_48);
   
   Double_t xAxis281[2] = {200, 4025}; 
   
   TH1D *Background_0x0_pass_postfit_projy2_stack_1_stack_1 = new TH1D("Background_0x0_pass_postfit_projy2_stack_1_stack_1","Background, pass, postfit, 1.0-1.0",1, xAxis281);
   Background_0x0_pass_postfit_projy2_stack_1_stack_1->SetMinimum(0.001);
   Background_0x0_pass_postfit_projy2_stack_1_stack_1->SetStats(0);

   ci = TColor::GetColor("#ffff00");
   Background_0x0_pass_postfit_projy2_stack_1_stack_1->SetFillColor(ci);

   ci = 1202;
   color = new TColor(ci, 1, 1, 1, " ", 0);
   Background_0x0_pass_postfit_projy2_stack_1_stack_1->SetLineColor(ci);
   Background_0x0_pass_postfit_projy2_stack_1_stack_1->GetXaxis()->SetTitle("p_{T}");
   Background_0x0_pass_postfit_projy2_stack_1_stack_1->GetXaxis()->SetLabelFont(42);
   Background_0x0_pass_postfit_projy2_stack_1_stack_1->GetXaxis()->SetLabelSize(0.035);
   Background_0x0_pass_postfit_projy2_stack_1_stack_1->GetXaxis()->SetTitleSize(0.035);
   Background_0x0_pass_postfit_projy2_stack_1_stack_1->GetXaxis()->SetTitleOffset(0);
   Background_0x0_pass_postfit_projy2_stack_1_stack_1->GetXaxis()->SetTitleFont(42);
   Background_0x0_pass_postfit_projy2_stack_1_stack_1->GetYaxis()->SetTitle("Events / bin");
   Background_0x0_pass_postfit_projy2_stack_1_stack_1->GetYaxis()->SetLabelFont(42);
   Background_0x0_pass_postfit_projy2_stack_1_stack_1->GetYaxis()->SetLabelSize(0.035);
   Background_0x0_pass_postfit_projy2_stack_1_stack_1->GetYaxis()->SetTitleSize(0.035);
   Background_0x0_pass_postfit_projy2_stack_1_stack_1->GetYaxis()->SetTitleOffset(0);
   Background_0x0_pass_postfit_projy2_stack_1_stack_1->GetYaxis()->SetTitleFont(42);
   Background_0x0_pass_postfit_projy2_stack_1_stack_1->GetZaxis()->SetLabelFont(42);
   Background_0x0_pass_postfit_projy2_stack_1_stack_1->GetZaxis()->SetLabelSize(0.035);
   Background_0x0_pass_postfit_projy2_stack_1_stack_1->GetZaxis()->SetTitleSize(0.035);
   Background_0x0_pass_postfit_projy2_stack_1_stack_1->GetZaxis()->SetTitleFont(42);
   postfit_projy2_pass_logy_stack->Add(Background_0x0_pass_postfit_projy2_stack_1_stack_1,"");
   postfit_projy2_pass_logy_stack->Draw("hist same");
   Double_t xAxis282[2] = {200, 4025}; 
   
   TH1D *Signal_gluinomI1800_pass_postfit_projy2__186 = new TH1D("Signal_gluinomI1800_pass_postfit_projy2__186","HSCP gluino 1800 GeV, pass, postfit, 1.0-1.0",1, xAxis282);
   Signal_gluinomI1800_pass_postfit_projy2__186->SetMinimum(0.001);
   Signal_gluinomI1800_pass_postfit_projy2__186->SetStats(0);
   Signal_gluinomI1800_pass_postfit_projy2__186->SetLineColor(4);
   Signal_gluinomI1800_pass_postfit_projy2__186->SetLineWidth(2);
   Signal_gluinomI1800_pass_postfit_projy2__186->GetXaxis()->SetTitle("p_{T}");
   Signal_gluinomI1800_pass_postfit_projy2__186->GetXaxis()->SetLabelFont(42);
   Signal_gluinomI1800_pass_postfit_projy2__186->GetXaxis()->SetLabelSize(0.035);
   Signal_gluinomI1800_pass_postfit_projy2__186->GetXaxis()->SetTitleSize(0.035);
   Signal_gluinomI1800_pass_postfit_projy2__186->GetXaxis()->SetTitleOffset(0);
   Signal_gluinomI1800_pass_postfit_projy2__186->GetXaxis()->SetTitleFont(42);
   Signal_gluinomI1800_pass_postfit_projy2__186->GetYaxis()->SetTitle("Events / bin");
   Signal_gluinomI1800_pass_postfit_projy2__186->GetYaxis()->SetLabelFont(42);
   Signal_gluinomI1800_pass_postfit_projy2__186->GetYaxis()->SetLabelSize(0.035);
   Signal_gluinomI1800_pass_postfit_projy2__186->GetYaxis()->SetTitleSize(0.035);
   Signal_gluinomI1800_pass_postfit_projy2__186->GetYaxis()->SetTitleOffset(0);
   Signal_gluinomI1800_pass_postfit_projy2__186->GetYaxis()->SetTitleFont(42);
   Signal_gluinomI1800_pass_postfit_projy2__186->GetZaxis()->SetLabelFont(42);
   Signal_gluinomI1800_pass_postfit_projy2__186->GetZaxis()->SetLabelSize(0.035);
   Signal_gluinomI1800_pass_postfit_projy2__186->GetZaxis()->SetTitleSize(0.035);
   Signal_gluinomI1800_pass_postfit_projy2__186->GetZaxis()->SetTitleFont(42);
   Signal_gluinomI1800_pass_postfit_projy2__186->Draw("hist same");
   Double_t xAxis283[2] = {200, 4025}; 
   
   TH1D *Signal_ppStaumI557_pass_postfit_projy2__187 = new TH1D("Signal_ppStaumI557_pass_postfit_projy2__187","HSCP stau 557 GeV, pass, postfit, 1.0-1.0",1, xAxis283);
   Signal_ppStaumI557_pass_postfit_projy2__187->SetMinimum(0.001);
   Signal_ppStaumI557_pass_postfit_projy2__187->SetStats(0);
   Signal_ppStaumI557_pass_postfit_projy2__187->SetLineColor(2);
   Signal_ppStaumI557_pass_postfit_projy2__187->SetLineWidth(2);
   Signal_ppStaumI557_pass_postfit_projy2__187->GetXaxis()->SetTitle("p_{T}");
   Signal_ppStaumI557_pass_postfit_projy2__187->GetXaxis()->SetLabelFont(42);
   Signal_ppStaumI557_pass_postfit_projy2__187->GetXaxis()->SetLabelSize(0.035);
   Signal_ppStaumI557_pass_postfit_projy2__187->GetXaxis()->SetTitleSize(0.035);
   Signal_ppStaumI557_pass_postfit_projy2__187->GetXaxis()->SetTitleOffset(0);
   Signal_ppStaumI557_pass_postfit_projy2__187->GetXaxis()->SetTitleFont(42);
   Signal_ppStaumI557_pass_postfit_projy2__187->GetYaxis()->SetTitle("Events / bin");
   Signal_ppStaumI557_pass_postfit_projy2__187->GetYaxis()->SetLabelFont(42);
   Signal_ppStaumI557_pass_postfit_projy2__187->GetYaxis()->SetLabelSize(0.035);
   Signal_ppStaumI557_pass_postfit_projy2__187->GetYaxis()->SetTitleSize(0.035);
   Signal_ppStaumI557_pass_postfit_projy2__187->GetYaxis()->SetTitleOffset(0);
   Signal_ppStaumI557_pass_postfit_projy2__187->GetYaxis()->SetTitleFont(42);
   Signal_ppStaumI557_pass_postfit_projy2__187->GetZaxis()->SetLabelFont(42);
   Signal_ppStaumI557_pass_postfit_projy2__187->GetZaxis()->SetLabelSize(0.035);
   Signal_ppStaumI557_pass_postfit_projy2__187->GetZaxis()->SetTitleSize(0.035);
   Signal_ppStaumI557_pass_postfit_projy2__187->GetZaxis()->SetTitleFont(42);
   Signal_ppStaumI557_pass_postfit_projy2__187->Draw("hist same");
   Double_t xAxis284[2] = {200, 4025}; 
   
   TH1D *TotalBkg_pass_postfit_projy2__188 = new TH1D("TotalBkg_pass_postfit_projy2__188","TotalBkg, pass, postfit, 1.0-1.0",1, xAxis284);
   TotalBkg_pass_postfit_projy2__188->SetMinimum(0.001);
   TotalBkg_pass_postfit_projy2__188->SetStats(0);
   TotalBkg_pass_postfit_projy2__188->SetMarkerStyle(0);
   TotalBkg_pass_postfit_projy2__188->GetXaxis()->SetTitle("p_{T}");
   TotalBkg_pass_postfit_projy2__188->GetXaxis()->SetLabelFont(42);
   TotalBkg_pass_postfit_projy2__188->GetXaxis()->SetLabelSize(0.035);
   TotalBkg_pass_postfit_projy2__188->GetXaxis()->SetTitleSize(0.035);
   TotalBkg_pass_postfit_projy2__188->GetXaxis()->SetTitleOffset(0);
   TotalBkg_pass_postfit_projy2__188->GetXaxis()->SetTitleFont(42);
   TotalBkg_pass_postfit_projy2__188->GetYaxis()->SetTitle("Events / bin");
   TotalBkg_pass_postfit_projy2__188->GetYaxis()->SetLabelFont(42);
   TotalBkg_pass_postfit_projy2__188->GetYaxis()->SetLabelSize(0.035);
   TotalBkg_pass_postfit_projy2__188->GetYaxis()->SetTitleSize(0.035);
   TotalBkg_pass_postfit_projy2__188->GetYaxis()->SetTitleOffset(0);
   TotalBkg_pass_postfit_projy2__188->GetYaxis()->SetTitleFont(42);
   TotalBkg_pass_postfit_projy2__188->GetZaxis()->SetLabelFont(42);
   TotalBkg_pass_postfit_projy2__188->GetZaxis()->SetLabelSize(0.035);
   TotalBkg_pass_postfit_projy2__188->GetZaxis()->SetTitleSize(0.035);
   TotalBkg_pass_postfit_projy2__188->GetZaxis()->SetTitleFont(42);
   TotalBkg_pass_postfit_projy2__188->Draw("hist same");
   Double_t xAxis285[2] = {200, 4025}; 
   
   TH1D *TotalBkg_pass_postfit_projy2__189 = new TH1D("TotalBkg_pass_postfit_projy2__189","TotalBkg, pass, postfit, 1.0-1.0",1, xAxis285);
   TotalBkg_pass_postfit_projy2__189->SetMinimum(0.001);
   TotalBkg_pass_postfit_projy2__189->SetStats(0);
   TotalBkg_pass_postfit_projy2__189->SetFillColor(1);
   TotalBkg_pass_postfit_projy2__189->SetFillStyle(3354);
   TotalBkg_pass_postfit_projy2__189->SetLineWidth(0);
   TotalBkg_pass_postfit_projy2__189->SetMarkerStyle(0);
   TotalBkg_pass_postfit_projy2__189->GetXaxis()->SetTitle("p_{T}");
   TotalBkg_pass_postfit_projy2__189->GetXaxis()->SetLabelFont(42);
   TotalBkg_pass_postfit_projy2__189->GetXaxis()->SetLabelSize(0.035);
   TotalBkg_pass_postfit_projy2__189->GetXaxis()->SetTitleSize(0.035);
   TotalBkg_pass_postfit_projy2__189->GetXaxis()->SetTitleOffset(0);
   TotalBkg_pass_postfit_projy2__189->GetXaxis()->SetTitleFont(42);
   TotalBkg_pass_postfit_projy2__189->GetYaxis()->SetTitle("Events / bin");
   TotalBkg_pass_postfit_projy2__189->GetYaxis()->SetLabelFont(42);
   TotalBkg_pass_postfit_projy2__189->GetYaxis()->SetLabelSize(0.035);
   TotalBkg_pass_postfit_projy2__189->GetYaxis()->SetTitleSize(0.035);
   TotalBkg_pass_postfit_projy2__189->GetYaxis()->SetTitleOffset(0);
   TotalBkg_pass_postfit_projy2__189->GetYaxis()->SetTitleFont(42);
   TotalBkg_pass_postfit_projy2__189->GetZaxis()->SetLabelFont(42);
   TotalBkg_pass_postfit_projy2__189->GetZaxis()->SetLabelSize(0.035);
   TotalBkg_pass_postfit_projy2__189->GetZaxis()->SetTitleSize(0.035);
   TotalBkg_pass_postfit_projy2__189->GetZaxis()->SetTitleFont(42);
   TotalBkg_pass_postfit_projy2__189->Draw("e2 same");
   Double_t xAxis286[2] = {200, 4025}; 
   
   TH1D *data_obs_pass_postfit_projy2__190 = new TH1D("data_obs_pass_postfit_projy2__190","",1, xAxis286);
   data_obs_pass_postfit_projy2__190->SetMinimum(0.001);
   data_obs_pass_postfit_projy2__190->SetMaximum(0);
   data_obs_pass_postfit_projy2__190->SetStats(0);

   ci = TColor::GetColor("#000000");
   data_obs_pass_postfit_projy2__190->SetLineColor(ci);

   ci = TColor::GetColor("#000000");
   data_obs_pass_postfit_projy2__190->SetMarkerColor(ci);
   data_obs_pass_postfit_projy2__190->SetMarkerStyle(8);
   data_obs_pass_postfit_projy2__190->GetXaxis()->SetTitle("p_{T}");
   data_obs_pass_postfit_projy2__190->GetXaxis()->SetLabelFont(42);
   data_obs_pass_postfit_projy2__190->GetXaxis()->SetLabelOffset(0.05);
   data_obs_pass_postfit_projy2__190->GetXaxis()->SetLabelSize(0.07);
   data_obs_pass_postfit_projy2__190->GetXaxis()->SetTitleSize(0.09);
   data_obs_pass_postfit_projy2__190->GetXaxis()->SetTitleOffset(1.15);
   data_obs_pass_postfit_projy2__190->GetXaxis()->SetTitleFont(42);
   data_obs_pass_postfit_projy2__190->GetYaxis()->SetTitle("Events / bin");
   data_obs_pass_postfit_projy2__190->GetYaxis()->SetNdivisions(508);
   data_obs_pass_postfit_projy2__190->GetYaxis()->SetLabelFont(42);
   data_obs_pass_postfit_projy2__190->GetYaxis()->SetLabelSize(0.07);
   data_obs_pass_postfit_projy2__190->GetYaxis()->SetTitleSize(0.09);
   data_obs_pass_postfit_projy2__190->GetYaxis()->SetTitleOffset(0.8);
   data_obs_pass_postfit_projy2__190->GetYaxis()->SetTitleFont(42);
   data_obs_pass_postfit_projy2__190->GetZaxis()->SetLabelFont(42);
   data_obs_pass_postfit_projy2__190->GetZaxis()->SetLabelSize(0.035);
   data_obs_pass_postfit_projy2__190->GetZaxis()->SetTitleSize(0.035);
   data_obs_pass_postfit_projy2__190->GetZaxis()->SetTitleFont(42);
   data_obs_pass_postfit_projy2__190->Draw("pe X0 same");
   
   TLegend *leg = new TLegend(0.65,0.61,0.9,0.88,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(1001);
   TLegendEntry *entry=leg->AddEntry("data_obs_pass_postfit_projy2","Data","pe X0");

   ci = TColor::GetColor("#000000");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);

   ci = TColor::GetColor("#000000");
   entry->SetMarkerColor(ci);
   entry->SetMarkerStyle(8);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("TotalBkg_pass_postfit_projy2","Total bkg unc.","F");
   entry->SetFillColor(1);
   entry->SetFillStyle(3354);
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("Signal_gluino-1800_pass_postfit_projy2","HSCP gluino 1800 GeV","L");
   entry->SetLineColor(4);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("Signal_ppStau-557_pass_postfit_projy2","HSCP stau 557 GeV","L");
   entry->SetLineColor(2);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("Background_0x0_pass_postfit_projy2_stack_1_stack_1","Background","f");

   ci = TColor::GetColor("#ffff00");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = 1202;
   color = new TColor(ci, 1, 1, 1, " ", 0);
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   leg->Draw();
   Double_t xAxis287[2] = {200, 4025}; 
   
   TH1D *data_obs_pass_postfit_projy2_copy__191 = new TH1D("data_obs_pass_postfit_projy2_copy__191","",1, xAxis287);
   data_obs_pass_postfit_projy2_copy__191->SetMinimum(0.001);
   data_obs_pass_postfit_projy2_copy__191->SetMaximum(0);
   data_obs_pass_postfit_projy2_copy__191->SetDirectory(0);
   data_obs_pass_postfit_projy2_copy__191->SetStats(0);

   ci = TColor::GetColor("#000000");
   data_obs_pass_postfit_projy2_copy__191->SetLineColor(ci);

   ci = TColor::GetColor("#000000");
   data_obs_pass_postfit_projy2_copy__191->SetMarkerColor(ci);
   data_obs_pass_postfit_projy2_copy__191->SetMarkerStyle(8);
   data_obs_pass_postfit_projy2_copy__191->GetXaxis()->SetTitle("p_{T}");
   data_obs_pass_postfit_projy2_copy__191->GetXaxis()->SetLabelFont(42);
   data_obs_pass_postfit_projy2_copy__191->GetXaxis()->SetLabelOffset(0.05);
   data_obs_pass_postfit_projy2_copy__191->GetXaxis()->SetLabelSize(0.07);
   data_obs_pass_postfit_projy2_copy__191->GetXaxis()->SetTitleSize(0.09);
   data_obs_pass_postfit_projy2_copy__191->GetXaxis()->SetTitleOffset(1.15);
   data_obs_pass_postfit_projy2_copy__191->GetXaxis()->SetTitleFont(42);
   data_obs_pass_postfit_projy2_copy__191->GetYaxis()->SetTitle("Events / bin");
   data_obs_pass_postfit_projy2_copy__191->GetYaxis()->SetNdivisions(508);
   data_obs_pass_postfit_projy2_copy__191->GetYaxis()->SetLabelFont(42);
   data_obs_pass_postfit_projy2_copy__191->GetYaxis()->SetLabelSize(0.07);
   data_obs_pass_postfit_projy2_copy__191->GetYaxis()->SetTitleSize(0.09);
   data_obs_pass_postfit_projy2_copy__191->GetYaxis()->SetTitleOffset(0.8);
   data_obs_pass_postfit_projy2_copy__191->GetYaxis()->SetTitleFont(42);
   data_obs_pass_postfit_projy2_copy__191->GetZaxis()->SetLabelFont(42);
   data_obs_pass_postfit_projy2_copy__191->GetZaxis()->SetLabelSize(0.035);
   data_obs_pass_postfit_projy2_copy__191->GetZaxis()->SetTitleSize(0.035);
   data_obs_pass_postfit_projy2_copy__191->GetZaxis()->SetTitleFont(42);
   data_obs_pass_postfit_projy2_copy__191->Draw("sameaxis");
   TLatex *   tex = new TLatex(0.21,0.83,"1.0 < G_{i}^{Strips} < 1.0 , F^{Pixels}_{i} > 0.9");
tex->SetNDC();
   tex->SetTextAlign(12);
   tex->SetTextFont(42);
   tex->SetTextSize(0.06);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.17,0.92,"CMS");
tex->SetNDC();
   tex->SetTextFont(61);
   tex->SetTextSize(0.0675);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.25,0.92,"Preliminary");
tex->SetNDC();
   tex->SetTextFont(52);
   tex->SetTextSize(0.0485);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.95,0.92,"101 fb^{-1} (13 TeV)");
tex->SetNDC();
   tex->SetTextAlign(31);
   tex->SetTextFont(42);
   tex->SetTextSize(0.07);
   tex->SetLineWidth(2);
   tex->Draw();
   data_obs_pass_postfit_projy2_main->Modified();
   plots_fit_b/base_figs/postfit_projy2_pass_logy->cd();
  
// ------------>Primitives in pad: data_obs_pass_postfit_projy2_sub
   TPad *data_obs_pass_postfit_projy2_sub = new TPad("data_obs_pass_postfit_projy2_sub", "data_obs_pass_postfit_projy2_sub",0,0,1,0.35);
   data_obs_pass_postfit_projy2_sub->Draw();
   data_obs_pass_postfit_projy2_sub->cd();
   data_obs_pass_postfit_projy2_sub->Range(-633.6539,-6.023077,4270.192,2.9);
   data_obs_pass_postfit_projy2_sub->SetFillColor(0);
   data_obs_pass_postfit_projy2_sub->SetBorderMode(0);
   data_obs_pass_postfit_projy2_sub->SetBorderSize(2);
   data_obs_pass_postfit_projy2_sub->SetTickx(1);
   data_obs_pass_postfit_projy2_sub->SetTicky(1);
   data_obs_pass_postfit_projy2_sub->SetLeftMargin(0.17);
   data_obs_pass_postfit_projy2_sub->SetRightMargin(0.05);
   data_obs_pass_postfit_projy2_sub->SetTopMargin(0);
   data_obs_pass_postfit_projy2_sub->SetBottomMargin(0.35);
   data_obs_pass_postfit_projy2_sub->SetFrameFillStyle(0);
   data_obs_pass_postfit_projy2_sub->SetFrameBorderMode(0);
   data_obs_pass_postfit_projy2_sub->SetFrameFillStyle(0);
   data_obs_pass_postfit_projy2_sub->SetFrameBorderMode(0);
   Double_t xAxis288[2] = {200, 4025}; 
   
   TH1D *data_obs_pass_postfit_projy2_pull__192 = new TH1D("data_obs_pass_postfit_projy2_pull__192","",1, xAxis288);
   data_obs_pass_postfit_projy2_pull__192->SetMinimum(-2.9);
   data_obs_pass_postfit_projy2_pull__192->SetMaximum(2.9);
   data_obs_pass_postfit_projy2_pull__192->SetEntries(2);
   data_obs_pass_postfit_projy2_pull__192->SetStats(0);

   ci = TColor::GetColor("#0000ff");
   data_obs_pass_postfit_projy2_pull__192->SetFillColor(ci);

   ci = TColor::GetColor("#000000");
   data_obs_pass_postfit_projy2_pull__192->SetLineColor(ci);

   ci = TColor::GetColor("#000000");
   data_obs_pass_postfit_projy2_pull__192->SetMarkerColor(ci);
   data_obs_pass_postfit_projy2_pull__192->SetMarkerStyle(8);
   data_obs_pass_postfit_projy2_pull__192->GetXaxis()->SetTitle("p_{T}");
   data_obs_pass_postfit_projy2_pull__192->GetXaxis()->SetLabelFont(42);
   data_obs_pass_postfit_projy2_pull__192->GetXaxis()->SetLabelOffset(0.05);
   data_obs_pass_postfit_projy2_pull__192->GetXaxis()->SetLabelSize(0.13);
   data_obs_pass_postfit_projy2_pull__192->GetXaxis()->SetTitleSize(0.15);
   data_obs_pass_postfit_projy2_pull__192->GetXaxis()->SetTitleOffset(1.15);
   data_obs_pass_postfit_projy2_pull__192->GetXaxis()->SetTitleFont(42);
   data_obs_pass_postfit_projy2_pull__192->GetYaxis()->SetTitle("(Data-Bkg)/#sigma");
   data_obs_pass_postfit_projy2_pull__192->GetYaxis()->SetNdivisions(306);
   data_obs_pass_postfit_projy2_pull__192->GetYaxis()->SetLabelFont(42);
   data_obs_pass_postfit_projy2_pull__192->GetYaxis()->SetLabelSize(0.13);
   data_obs_pass_postfit_projy2_pull__192->GetYaxis()->SetTitleSize(0.12);
   data_obs_pass_postfit_projy2_pull__192->GetYaxis()->SetTitleOffset(0.4);
   data_obs_pass_postfit_projy2_pull__192->GetYaxis()->SetTitleFont(42);
   data_obs_pass_postfit_projy2_pull__192->GetZaxis()->SetLabelFont(42);
   data_obs_pass_postfit_projy2_pull__192->GetZaxis()->SetLabelSize(0.035);
   data_obs_pass_postfit_projy2_pull__192->GetZaxis()->SetTitleSize(0.035);
   data_obs_pass_postfit_projy2_pull__192->GetZaxis()->SetTitleFont(42);
   data_obs_pass_postfit_projy2_pull__192->Draw("hist");
   data_obs_pass_postfit_projy2_sub->Modified();
   plots_fit_b/base_figs/postfit_projy2_pass_logy->cd();
   plots_fit_b/base_figs/postfit_projy2_pass_logy->Modified();
   plots_fit_b/base_figs/postfit_projy2_pass_logy->cd();
   plots_fit_b/base_figs/postfit_projy2_pass_logy->SetSelected(plots_fit_b/base_figs/postfit_projy2_pass_logy);
}
