void postfit_projy2_fail_logy()
{
//=========Macro generated from canvas: plots_fit_b/base_figs/postfit_projy2_fail_logy/plots_fit_b/base_figs/postfit_projy2_fail_logy
//=========  (Fri Jan 12 20:33:16 2024) by ROOT version 6.14/09
   TCanvas *plots_fit_b/base_figs/postfit_projy2_fail_logy = new TCanvas("plots_fit_b/base_figs/postfit_projy2_fail_logy", "plots_fit_b/base_figs/postfit_projy2_fail_logy",0,0,800,700);
   gStyle->SetOptFit(1);
   gStyle->SetOptStat(0);
   plots_fit_b/base_figs/postfit_projy2_fail_logy->SetHighLightColor(2);
   plots_fit_b/base_figs/postfit_projy2_fail_logy->Range(0,0,1,1);
   plots_fit_b/base_figs/postfit_projy2_fail_logy->SetFillColor(0);
   plots_fit_b/base_figs/postfit_projy2_fail_logy->SetBorderMode(0);
   plots_fit_b/base_figs/postfit_projy2_fail_logy->SetBorderSize(2);
   plots_fit_b/base_figs/postfit_projy2_fail_logy->SetTickx(1);
   plots_fit_b/base_figs/postfit_projy2_fail_logy->SetTicky(1);
   plots_fit_b/base_figs/postfit_projy2_fail_logy->SetLeftMargin(0.16);
   plots_fit_b/base_figs/postfit_projy2_fail_logy->SetRightMargin(0);
   plots_fit_b/base_figs/postfit_projy2_fail_logy->SetTopMargin(0);
   plots_fit_b/base_figs/postfit_projy2_fail_logy->SetBottomMargin(0);
   plots_fit_b/base_figs/postfit_projy2_fail_logy->SetFrameFillStyle(0);
   plots_fit_b/base_figs/postfit_projy2_fail_logy->SetFrameBorderMode(0);
  
// ------------>Primitives in pad: data_obs_fail_postfit_projy2_main
   TPad *data_obs_fail_postfit_projy2_main = new TPad("data_obs_fail_postfit_projy2_main", "data_obs_fail_postfit_projy2_main",0,0.35,1,1);
   data_obs_fail_postfit_projy2_main->Draw();
   data_obs_fail_postfit_projy2_main->cd();
   data_obs_fail_postfit_projy2_main->Range(-633.6539,-2.139535,4270.192,1.348837);
   data_obs_fail_postfit_projy2_main->SetFillColor(0);
   data_obs_fail_postfit_projy2_main->SetBorderMode(0);
   data_obs_fail_postfit_projy2_main->SetBorderSize(2);
   data_obs_fail_postfit_projy2_main->SetLogy();
   data_obs_fail_postfit_projy2_main->SetTickx(1);
   data_obs_fail_postfit_projy2_main->SetTicky(1);
   data_obs_fail_postfit_projy2_main->SetLeftMargin(0.17);
   data_obs_fail_postfit_projy2_main->SetRightMargin(0.05);
   data_obs_fail_postfit_projy2_main->SetBottomMargin(0.04);
   data_obs_fail_postfit_projy2_main->SetFrameFillStyle(0);
   data_obs_fail_postfit_projy2_main->SetFrameBorderMode(0);
   data_obs_fail_postfit_projy2_main->SetFrameFillStyle(0);
   data_obs_fail_postfit_projy2_main->SetFrameBorderMode(0);
   Double_t xAxis133[2] = {200, 4025}; 
   
   TH1D *data_obs_fail_postfit_projy2__89 = new TH1D("data_obs_fail_postfit_projy2__89","",1, xAxis133);
   data_obs_fail_postfit_projy2__89->SetMinimum(0.001);
   data_obs_fail_postfit_projy2__89->SetMaximum(0);
   data_obs_fail_postfit_projy2__89->SetStats(0);

   Int_t ci;      // for color index setting
   TColor *color; // for color definition with alpha
   ci = TColor::GetColor("#000000");
   data_obs_fail_postfit_projy2__89->SetLineColor(ci);

   ci = TColor::GetColor("#000000");
   data_obs_fail_postfit_projy2__89->SetMarkerColor(ci);
   data_obs_fail_postfit_projy2__89->SetMarkerStyle(8);
   data_obs_fail_postfit_projy2__89->GetXaxis()->SetTitle("p_{T}");
   data_obs_fail_postfit_projy2__89->GetXaxis()->SetLabelFont(42);
   data_obs_fail_postfit_projy2__89->GetXaxis()->SetLabelOffset(0.05);
   data_obs_fail_postfit_projy2__89->GetXaxis()->SetLabelSize(0.07);
   data_obs_fail_postfit_projy2__89->GetXaxis()->SetTitleSize(0.09);
   data_obs_fail_postfit_projy2__89->GetXaxis()->SetTitleOffset(1.15);
   data_obs_fail_postfit_projy2__89->GetXaxis()->SetTitleFont(42);
   data_obs_fail_postfit_projy2__89->GetYaxis()->SetTitle("Events / bin");
   data_obs_fail_postfit_projy2__89->GetYaxis()->SetNdivisions(508);
   data_obs_fail_postfit_projy2__89->GetYaxis()->SetLabelFont(42);
   data_obs_fail_postfit_projy2__89->GetYaxis()->SetLabelSize(0.07);
   data_obs_fail_postfit_projy2__89->GetYaxis()->SetTitleSize(0.09);
   data_obs_fail_postfit_projy2__89->GetYaxis()->SetTitleOffset(0.8);
   data_obs_fail_postfit_projy2__89->GetYaxis()->SetTitleFont(42);
   data_obs_fail_postfit_projy2__89->GetZaxis()->SetLabelFont(42);
   data_obs_fail_postfit_projy2__89->GetZaxis()->SetLabelSize(0.035);
   data_obs_fail_postfit_projy2__89->GetZaxis()->SetTitleSize(0.035);
   data_obs_fail_postfit_projy2__89->GetZaxis()->SetTitleFont(42);
   data_obs_fail_postfit_projy2__89->Draw("pe X0");
   
   THStack *postfit_projy2_fail_logy_stack = new THStack();
   postfit_projy2_fail_logy_stack->SetName("postfit_projy2_fail_logy_stack");
   postfit_projy2_fail_logy_stack->SetTitle("postfit_projy2_fail_logy_stack");
   postfit_projy2_fail_logy_stack->SetMinimum(0.001);
   Double_t xAxis134[2] = {200, 4025}; 
   
   TH1F *postfit_projy2_fail_logy_stack_stack_23 = new TH1F("postfit_projy2_fail_logy_stack_stack_23","postfit_projy2_fail_logy_stack",1, xAxis134);
   postfit_projy2_fail_logy_stack_stack_23->SetMinimum(-0);
   postfit_projy2_fail_logy_stack_stack_23->SetMaximum(-nan);
   postfit_projy2_fail_logy_stack_stack_23->SetDirectory(0);
   postfit_projy2_fail_logy_stack_stack_23->SetStats(0);
   postfit_projy2_fail_logy_stack_stack_23->SetLineStyle(0);
   postfit_projy2_fail_logy_stack_stack_23->GetXaxis()->SetLabelFont(42);
   postfit_projy2_fail_logy_stack_stack_23->GetXaxis()->SetLabelOffset(0.007);
   postfit_projy2_fail_logy_stack_stack_23->GetXaxis()->SetLabelSize(0.05);
   postfit_projy2_fail_logy_stack_stack_23->GetXaxis()->SetTitleSize(0.08);
   postfit_projy2_fail_logy_stack_stack_23->GetXaxis()->SetTitleOffset(0.9);
   postfit_projy2_fail_logy_stack_stack_23->GetXaxis()->SetTitleFont(42);
   postfit_projy2_fail_logy_stack_stack_23->GetYaxis()->SetNdivisions(508);
   postfit_projy2_fail_logy_stack_stack_23->GetYaxis()->SetLabelFont(42);
   postfit_projy2_fail_logy_stack_stack_23->GetYaxis()->SetLabelOffset(0.007);
   postfit_projy2_fail_logy_stack_stack_23->GetYaxis()->SetLabelSize(0.05);
   postfit_projy2_fail_logy_stack_stack_23->GetYaxis()->SetTitleSize(0.08);
   postfit_projy2_fail_logy_stack_stack_23->GetYaxis()->SetTitleOffset(1.25);
   postfit_projy2_fail_logy_stack_stack_23->GetYaxis()->SetTitleFont(42);
   postfit_projy2_fail_logy_stack_stack_23->GetZaxis()->SetLabelFont(42);
   postfit_projy2_fail_logy_stack_stack_23->GetZaxis()->SetLabelOffset(0.007);
   postfit_projy2_fail_logy_stack_stack_23->GetZaxis()->SetLabelSize(0.05);
   postfit_projy2_fail_logy_stack_stack_23->GetZaxis()->SetTitleSize(0.08);
   postfit_projy2_fail_logy_stack_stack_23->GetZaxis()->SetTitleFont(42);
   postfit_projy2_fail_logy_stack->SetHistogram(postfit_projy2_fail_logy_stack_stack_23);
   
   Double_t xAxis135[2] = {200, 4025}; 
   
   TH1D *Background_fail_postfit_projy2_stack_1 = new TH1D("Background_fail_postfit_projy2_stack_1","Background, fail, postfit, 1.0-1.0",1, xAxis135);
   Background_fail_postfit_projy2_stack_1->SetMinimum(0.001);
   Background_fail_postfit_projy2_stack_1->SetStats(0);

   ci = TColor::GetColor("#ffff00");
   Background_fail_postfit_projy2_stack_1->SetFillColor(ci);

   ci = 1190;
   color = new TColor(ci, 1, 1, 1, " ", 0);
   Background_fail_postfit_projy2_stack_1->SetLineColor(ci);
   Background_fail_postfit_projy2_stack_1->GetXaxis()->SetTitle("p_{T}");
   Background_fail_postfit_projy2_stack_1->GetXaxis()->SetLabelFont(42);
   Background_fail_postfit_projy2_stack_1->GetXaxis()->SetLabelSize(0.035);
   Background_fail_postfit_projy2_stack_1->GetXaxis()->SetTitleSize(0.035);
   Background_fail_postfit_projy2_stack_1->GetXaxis()->SetTitleOffset(0);
   Background_fail_postfit_projy2_stack_1->GetXaxis()->SetTitleFont(42);
   Background_fail_postfit_projy2_stack_1->GetYaxis()->SetTitle("Events / bin");
   Background_fail_postfit_projy2_stack_1->GetYaxis()->SetLabelFont(42);
   Background_fail_postfit_projy2_stack_1->GetYaxis()->SetLabelSize(0.035);
   Background_fail_postfit_projy2_stack_1->GetYaxis()->SetTitleSize(0.035);
   Background_fail_postfit_projy2_stack_1->GetYaxis()->SetTitleOffset(0);
   Background_fail_postfit_projy2_stack_1->GetYaxis()->SetTitleFont(42);
   Background_fail_postfit_projy2_stack_1->GetZaxis()->SetLabelFont(42);
   Background_fail_postfit_projy2_stack_1->GetZaxis()->SetLabelSize(0.035);
   Background_fail_postfit_projy2_stack_1->GetZaxis()->SetTitleSize(0.035);
   Background_fail_postfit_projy2_stack_1->GetZaxis()->SetTitleFont(42);
   postfit_projy2_fail_logy_stack->Add(Background_fail_postfit_projy2_stack_1,"");
   postfit_projy2_fail_logy_stack->Draw("hist same");
   
   postfit_projy2_fail_logy_stack = new THStack();
   postfit_projy2_fail_logy_stack->SetName("postfit_projy2_fail_logy_stack");
   postfit_projy2_fail_logy_stack->SetTitle("postfit_projy2_fail_logy_stack");
   postfit_projy2_fail_logy_stack->SetMinimum(0.001);
   Double_t xAxis136[2] = {200, 4025}; 
   
   TH1F *postfit_projy2_fail_logy_stack_stack_23_stack_24 = new TH1F("postfit_projy2_fail_logy_stack_stack_23_stack_24","postfit_projy2_fail_logy_stack",1, xAxis136);
   postfit_projy2_fail_logy_stack_stack_23_stack_24->SetMinimum(-0);
   postfit_projy2_fail_logy_stack_stack_23_stack_24->SetMaximum(-nan);
   postfit_projy2_fail_logy_stack_stack_23_stack_24->SetDirectory(0);
   postfit_projy2_fail_logy_stack_stack_23_stack_24->SetStats(0);
   postfit_projy2_fail_logy_stack_stack_23_stack_24->SetLineStyle(0);
   postfit_projy2_fail_logy_stack_stack_23_stack_24->GetXaxis()->SetLabelFont(42);
   postfit_projy2_fail_logy_stack_stack_23_stack_24->GetXaxis()->SetLabelOffset(0.007);
   postfit_projy2_fail_logy_stack_stack_23_stack_24->GetXaxis()->SetLabelSize(0.05);
   postfit_projy2_fail_logy_stack_stack_23_stack_24->GetXaxis()->SetTitleSize(0.08);
   postfit_projy2_fail_logy_stack_stack_23_stack_24->GetXaxis()->SetTitleOffset(0.9);
   postfit_projy2_fail_logy_stack_stack_23_stack_24->GetXaxis()->SetTitleFont(42);
   postfit_projy2_fail_logy_stack_stack_23_stack_24->GetYaxis()->SetNdivisions(508);
   postfit_projy2_fail_logy_stack_stack_23_stack_24->GetYaxis()->SetLabelFont(42);
   postfit_projy2_fail_logy_stack_stack_23_stack_24->GetYaxis()->SetLabelOffset(0.007);
   postfit_projy2_fail_logy_stack_stack_23_stack_24->GetYaxis()->SetLabelSize(0.05);
   postfit_projy2_fail_logy_stack_stack_23_stack_24->GetYaxis()->SetTitleSize(0.08);
   postfit_projy2_fail_logy_stack_stack_23_stack_24->GetYaxis()->SetTitleOffset(1.25);
   postfit_projy2_fail_logy_stack_stack_23_stack_24->GetYaxis()->SetTitleFont(42);
   postfit_projy2_fail_logy_stack_stack_23_stack_24->GetZaxis()->SetLabelFont(42);
   postfit_projy2_fail_logy_stack_stack_23_stack_24->GetZaxis()->SetLabelOffset(0.007);
   postfit_projy2_fail_logy_stack_stack_23_stack_24->GetZaxis()->SetLabelSize(0.05);
   postfit_projy2_fail_logy_stack_stack_23_stack_24->GetZaxis()->SetTitleSize(0.08);
   postfit_projy2_fail_logy_stack_stack_23_stack_24->GetZaxis()->SetTitleFont(42);
   postfit_projy2_fail_logy_stack->SetHistogram(postfit_projy2_fail_logy_stack_stack_23_stack_24);
   
   Double_t xAxis137[2] = {200, 4025}; 
   
   TH1D *Background_fail_postfit_projy2_stack_1_stack_1 = new TH1D("Background_fail_postfit_projy2_stack_1_stack_1","Background, fail, postfit, 1.0-1.0",1, xAxis137);
   Background_fail_postfit_projy2_stack_1_stack_1->SetMinimum(0.001);
   Background_fail_postfit_projy2_stack_1_stack_1->SetStats(0);

   ci = TColor::GetColor("#ffff00");
   Background_fail_postfit_projy2_stack_1_stack_1->SetFillColor(ci);

   ci = 1190;
   color = new TColor(ci, 1, 1, 1, " ", 0);
   Background_fail_postfit_projy2_stack_1_stack_1->SetLineColor(ci);
   Background_fail_postfit_projy2_stack_1_stack_1->GetXaxis()->SetTitle("p_{T}");
   Background_fail_postfit_projy2_stack_1_stack_1->GetXaxis()->SetLabelFont(42);
   Background_fail_postfit_projy2_stack_1_stack_1->GetXaxis()->SetLabelSize(0.035);
   Background_fail_postfit_projy2_stack_1_stack_1->GetXaxis()->SetTitleSize(0.035);
   Background_fail_postfit_projy2_stack_1_stack_1->GetXaxis()->SetTitleOffset(0);
   Background_fail_postfit_projy2_stack_1_stack_1->GetXaxis()->SetTitleFont(42);
   Background_fail_postfit_projy2_stack_1_stack_1->GetYaxis()->SetTitle("Events / bin");
   Background_fail_postfit_projy2_stack_1_stack_1->GetYaxis()->SetLabelFont(42);
   Background_fail_postfit_projy2_stack_1_stack_1->GetYaxis()->SetLabelSize(0.035);
   Background_fail_postfit_projy2_stack_1_stack_1->GetYaxis()->SetTitleSize(0.035);
   Background_fail_postfit_projy2_stack_1_stack_1->GetYaxis()->SetTitleOffset(0);
   Background_fail_postfit_projy2_stack_1_stack_1->GetYaxis()->SetTitleFont(42);
   Background_fail_postfit_projy2_stack_1_stack_1->GetZaxis()->SetLabelFont(42);
   Background_fail_postfit_projy2_stack_1_stack_1->GetZaxis()->SetLabelSize(0.035);
   Background_fail_postfit_projy2_stack_1_stack_1->GetZaxis()->SetTitleSize(0.035);
   Background_fail_postfit_projy2_stack_1_stack_1->GetZaxis()->SetTitleFont(42);
   postfit_projy2_fail_logy_stack->Add(Background_fail_postfit_projy2_stack_1_stack_1,"");
   postfit_projy2_fail_logy_stack->Draw("hist same");
   Double_t xAxis138[2] = {200, 4025}; 
   
   TH1D *Signal_gluinomI1800_fail_postfit_projy2__90 = new TH1D("Signal_gluinomI1800_fail_postfit_projy2__90","HSCP gluino 1800 GeV, fail, postfit, 1.0-1.0",1, xAxis138);
   Signal_gluinomI1800_fail_postfit_projy2__90->SetMinimum(0.001);
   Signal_gluinomI1800_fail_postfit_projy2__90->SetStats(0);
   Signal_gluinomI1800_fail_postfit_projy2__90->SetLineColor(4);
   Signal_gluinomI1800_fail_postfit_projy2__90->SetLineWidth(2);
   Signal_gluinomI1800_fail_postfit_projy2__90->GetXaxis()->SetTitle("p_{T}");
   Signal_gluinomI1800_fail_postfit_projy2__90->GetXaxis()->SetLabelFont(42);
   Signal_gluinomI1800_fail_postfit_projy2__90->GetXaxis()->SetLabelSize(0.035);
   Signal_gluinomI1800_fail_postfit_projy2__90->GetXaxis()->SetTitleSize(0.035);
   Signal_gluinomI1800_fail_postfit_projy2__90->GetXaxis()->SetTitleOffset(0);
   Signal_gluinomI1800_fail_postfit_projy2__90->GetXaxis()->SetTitleFont(42);
   Signal_gluinomI1800_fail_postfit_projy2__90->GetYaxis()->SetTitle("Events / bin");
   Signal_gluinomI1800_fail_postfit_projy2__90->GetYaxis()->SetLabelFont(42);
   Signal_gluinomI1800_fail_postfit_projy2__90->GetYaxis()->SetLabelSize(0.035);
   Signal_gluinomI1800_fail_postfit_projy2__90->GetYaxis()->SetTitleSize(0.035);
   Signal_gluinomI1800_fail_postfit_projy2__90->GetYaxis()->SetTitleOffset(0);
   Signal_gluinomI1800_fail_postfit_projy2__90->GetYaxis()->SetTitleFont(42);
   Signal_gluinomI1800_fail_postfit_projy2__90->GetZaxis()->SetLabelFont(42);
   Signal_gluinomI1800_fail_postfit_projy2__90->GetZaxis()->SetLabelSize(0.035);
   Signal_gluinomI1800_fail_postfit_projy2__90->GetZaxis()->SetTitleSize(0.035);
   Signal_gluinomI1800_fail_postfit_projy2__90->GetZaxis()->SetTitleFont(42);
   Signal_gluinomI1800_fail_postfit_projy2__90->Draw("hist same");
   Double_t xAxis139[2] = {200, 4025}; 
   
   TH1D *Signal_ppStaumI557_fail_postfit_projy2__91 = new TH1D("Signal_ppStaumI557_fail_postfit_projy2__91","HSCP stau 557 GeV, fail, postfit, 1.0-1.0",1, xAxis139);
   Signal_ppStaumI557_fail_postfit_projy2__91->SetMinimum(0.001);
   Signal_ppStaumI557_fail_postfit_projy2__91->SetStats(0);
   Signal_ppStaumI557_fail_postfit_projy2__91->SetLineColor(2);
   Signal_ppStaumI557_fail_postfit_projy2__91->SetLineWidth(2);
   Signal_ppStaumI557_fail_postfit_projy2__91->GetXaxis()->SetTitle("p_{T}");
   Signal_ppStaumI557_fail_postfit_projy2__91->GetXaxis()->SetLabelFont(42);
   Signal_ppStaumI557_fail_postfit_projy2__91->GetXaxis()->SetLabelSize(0.035);
   Signal_ppStaumI557_fail_postfit_projy2__91->GetXaxis()->SetTitleSize(0.035);
   Signal_ppStaumI557_fail_postfit_projy2__91->GetXaxis()->SetTitleOffset(0);
   Signal_ppStaumI557_fail_postfit_projy2__91->GetXaxis()->SetTitleFont(42);
   Signal_ppStaumI557_fail_postfit_projy2__91->GetYaxis()->SetTitle("Events / bin");
   Signal_ppStaumI557_fail_postfit_projy2__91->GetYaxis()->SetLabelFont(42);
   Signal_ppStaumI557_fail_postfit_projy2__91->GetYaxis()->SetLabelSize(0.035);
   Signal_ppStaumI557_fail_postfit_projy2__91->GetYaxis()->SetTitleSize(0.035);
   Signal_ppStaumI557_fail_postfit_projy2__91->GetYaxis()->SetTitleOffset(0);
   Signal_ppStaumI557_fail_postfit_projy2__91->GetYaxis()->SetTitleFont(42);
   Signal_ppStaumI557_fail_postfit_projy2__91->GetZaxis()->SetLabelFont(42);
   Signal_ppStaumI557_fail_postfit_projy2__91->GetZaxis()->SetLabelSize(0.035);
   Signal_ppStaumI557_fail_postfit_projy2__91->GetZaxis()->SetTitleSize(0.035);
   Signal_ppStaumI557_fail_postfit_projy2__91->GetZaxis()->SetTitleFont(42);
   Signal_ppStaumI557_fail_postfit_projy2__91->Draw("hist same");
   Double_t xAxis140[2] = {200, 4025}; 
   
   TH1D *TotalBkg_fail_postfit_projy2__92 = new TH1D("TotalBkg_fail_postfit_projy2__92","TotalBkg, fail, postfit, 1.0-1.0",1, xAxis140);
   TotalBkg_fail_postfit_projy2__92->SetMinimum(0.001);
   TotalBkg_fail_postfit_projy2__92->SetStats(0);
   TotalBkg_fail_postfit_projy2__92->SetMarkerStyle(0);
   TotalBkg_fail_postfit_projy2__92->GetXaxis()->SetTitle("p_{T}");
   TotalBkg_fail_postfit_projy2__92->GetXaxis()->SetLabelFont(42);
   TotalBkg_fail_postfit_projy2__92->GetXaxis()->SetLabelSize(0.035);
   TotalBkg_fail_postfit_projy2__92->GetXaxis()->SetTitleSize(0.035);
   TotalBkg_fail_postfit_projy2__92->GetXaxis()->SetTitleOffset(0);
   TotalBkg_fail_postfit_projy2__92->GetXaxis()->SetTitleFont(42);
   TotalBkg_fail_postfit_projy2__92->GetYaxis()->SetTitle("Events / bin");
   TotalBkg_fail_postfit_projy2__92->GetYaxis()->SetLabelFont(42);
   TotalBkg_fail_postfit_projy2__92->GetYaxis()->SetLabelSize(0.035);
   TotalBkg_fail_postfit_projy2__92->GetYaxis()->SetTitleSize(0.035);
   TotalBkg_fail_postfit_projy2__92->GetYaxis()->SetTitleOffset(0);
   TotalBkg_fail_postfit_projy2__92->GetYaxis()->SetTitleFont(42);
   TotalBkg_fail_postfit_projy2__92->GetZaxis()->SetLabelFont(42);
   TotalBkg_fail_postfit_projy2__92->GetZaxis()->SetLabelSize(0.035);
   TotalBkg_fail_postfit_projy2__92->GetZaxis()->SetTitleSize(0.035);
   TotalBkg_fail_postfit_projy2__92->GetZaxis()->SetTitleFont(42);
   TotalBkg_fail_postfit_projy2__92->Draw("hist same");
   Double_t xAxis141[2] = {200, 4025}; 
   
   TH1D *TotalBkg_fail_postfit_projy2__93 = new TH1D("TotalBkg_fail_postfit_projy2__93","TotalBkg, fail, postfit, 1.0-1.0",1, xAxis141);
   TotalBkg_fail_postfit_projy2__93->SetMinimum(0.001);
   TotalBkg_fail_postfit_projy2__93->SetStats(0);
   TotalBkg_fail_postfit_projy2__93->SetFillColor(1);
   TotalBkg_fail_postfit_projy2__93->SetFillStyle(3354);
   TotalBkg_fail_postfit_projy2__93->SetLineWidth(0);
   TotalBkg_fail_postfit_projy2__93->SetMarkerStyle(0);
   TotalBkg_fail_postfit_projy2__93->GetXaxis()->SetTitle("p_{T}");
   TotalBkg_fail_postfit_projy2__93->GetXaxis()->SetLabelFont(42);
   TotalBkg_fail_postfit_projy2__93->GetXaxis()->SetLabelSize(0.035);
   TotalBkg_fail_postfit_projy2__93->GetXaxis()->SetTitleSize(0.035);
   TotalBkg_fail_postfit_projy2__93->GetXaxis()->SetTitleOffset(0);
   TotalBkg_fail_postfit_projy2__93->GetXaxis()->SetTitleFont(42);
   TotalBkg_fail_postfit_projy2__93->GetYaxis()->SetTitle("Events / bin");
   TotalBkg_fail_postfit_projy2__93->GetYaxis()->SetLabelFont(42);
   TotalBkg_fail_postfit_projy2__93->GetYaxis()->SetLabelSize(0.035);
   TotalBkg_fail_postfit_projy2__93->GetYaxis()->SetTitleSize(0.035);
   TotalBkg_fail_postfit_projy2__93->GetYaxis()->SetTitleOffset(0);
   TotalBkg_fail_postfit_projy2__93->GetYaxis()->SetTitleFont(42);
   TotalBkg_fail_postfit_projy2__93->GetZaxis()->SetLabelFont(42);
   TotalBkg_fail_postfit_projy2__93->GetZaxis()->SetLabelSize(0.035);
   TotalBkg_fail_postfit_projy2__93->GetZaxis()->SetTitleSize(0.035);
   TotalBkg_fail_postfit_projy2__93->GetZaxis()->SetTitleFont(42);
   TotalBkg_fail_postfit_projy2__93->Draw("e2 same");
   Double_t xAxis142[2] = {200, 4025}; 
   
   TH1D *data_obs_fail_postfit_projy2__94 = new TH1D("data_obs_fail_postfit_projy2__94","",1, xAxis142);
   data_obs_fail_postfit_projy2__94->SetMinimum(0.001);
   data_obs_fail_postfit_projy2__94->SetMaximum(0);
   data_obs_fail_postfit_projy2__94->SetStats(0);

   ci = TColor::GetColor("#000000");
   data_obs_fail_postfit_projy2__94->SetLineColor(ci);

   ci = TColor::GetColor("#000000");
   data_obs_fail_postfit_projy2__94->SetMarkerColor(ci);
   data_obs_fail_postfit_projy2__94->SetMarkerStyle(8);
   data_obs_fail_postfit_projy2__94->GetXaxis()->SetTitle("p_{T}");
   data_obs_fail_postfit_projy2__94->GetXaxis()->SetLabelFont(42);
   data_obs_fail_postfit_projy2__94->GetXaxis()->SetLabelOffset(0.05);
   data_obs_fail_postfit_projy2__94->GetXaxis()->SetLabelSize(0.07);
   data_obs_fail_postfit_projy2__94->GetXaxis()->SetTitleSize(0.09);
   data_obs_fail_postfit_projy2__94->GetXaxis()->SetTitleOffset(1.15);
   data_obs_fail_postfit_projy2__94->GetXaxis()->SetTitleFont(42);
   data_obs_fail_postfit_projy2__94->GetYaxis()->SetTitle("Events / bin");
   data_obs_fail_postfit_projy2__94->GetYaxis()->SetNdivisions(508);
   data_obs_fail_postfit_projy2__94->GetYaxis()->SetLabelFont(42);
   data_obs_fail_postfit_projy2__94->GetYaxis()->SetLabelSize(0.07);
   data_obs_fail_postfit_projy2__94->GetYaxis()->SetTitleSize(0.09);
   data_obs_fail_postfit_projy2__94->GetYaxis()->SetTitleOffset(0.8);
   data_obs_fail_postfit_projy2__94->GetYaxis()->SetTitleFont(42);
   data_obs_fail_postfit_projy2__94->GetZaxis()->SetLabelFont(42);
   data_obs_fail_postfit_projy2__94->GetZaxis()->SetLabelSize(0.035);
   data_obs_fail_postfit_projy2__94->GetZaxis()->SetTitleSize(0.035);
   data_obs_fail_postfit_projy2__94->GetZaxis()->SetTitleFont(42);
   data_obs_fail_postfit_projy2__94->Draw("pe X0 same");
   
   TLegend *leg = new TLegend(0.65,0.61,0.9,0.88,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(1001);
   TLegendEntry *entry=leg->AddEntry("data_obs_fail_postfit_projy2","Data","pe X0");

   ci = TColor::GetColor("#000000");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);

   ci = TColor::GetColor("#000000");
   entry->SetMarkerColor(ci);
   entry->SetMarkerStyle(8);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("TotalBkg_fail_postfit_projy2","Total bkg unc.","F");
   entry->SetFillColor(1);
   entry->SetFillStyle(3354);
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("Signal_gluino-1800_fail_postfit_projy2","HSCP gluino 1800 GeV","L");
   entry->SetLineColor(4);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("Signal_ppStau-557_fail_postfit_projy2","HSCP stau 557 GeV","L");
   entry->SetLineColor(2);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("Background_fail_postfit_projy2_stack_1_stack_1","Background","f");

   ci = TColor::GetColor("#ffff00");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = 1190;
   color = new TColor(ci, 1, 1, 1, " ", 0);
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   leg->Draw();
   Double_t xAxis143[2] = {200, 4025}; 
   
   TH1D *data_obs_fail_postfit_projy2_copy__95 = new TH1D("data_obs_fail_postfit_projy2_copy__95","",1, xAxis143);
   data_obs_fail_postfit_projy2_copy__95->SetMinimum(0.001);
   data_obs_fail_postfit_projy2_copy__95->SetMaximum(0);
   data_obs_fail_postfit_projy2_copy__95->SetDirectory(0);
   data_obs_fail_postfit_projy2_copy__95->SetStats(0);

   ci = TColor::GetColor("#000000");
   data_obs_fail_postfit_projy2_copy__95->SetLineColor(ci);

   ci = TColor::GetColor("#000000");
   data_obs_fail_postfit_projy2_copy__95->SetMarkerColor(ci);
   data_obs_fail_postfit_projy2_copy__95->SetMarkerStyle(8);
   data_obs_fail_postfit_projy2_copy__95->GetXaxis()->SetTitle("p_{T}");
   data_obs_fail_postfit_projy2_copy__95->GetXaxis()->SetLabelFont(42);
   data_obs_fail_postfit_projy2_copy__95->GetXaxis()->SetLabelOffset(0.05);
   data_obs_fail_postfit_projy2_copy__95->GetXaxis()->SetLabelSize(0.07);
   data_obs_fail_postfit_projy2_copy__95->GetXaxis()->SetTitleSize(0.09);
   data_obs_fail_postfit_projy2_copy__95->GetXaxis()->SetTitleOffset(1.15);
   data_obs_fail_postfit_projy2_copy__95->GetXaxis()->SetTitleFont(42);
   data_obs_fail_postfit_projy2_copy__95->GetYaxis()->SetTitle("Events / bin");
   data_obs_fail_postfit_projy2_copy__95->GetYaxis()->SetNdivisions(508);
   data_obs_fail_postfit_projy2_copy__95->GetYaxis()->SetLabelFont(42);
   data_obs_fail_postfit_projy2_copy__95->GetYaxis()->SetLabelSize(0.07);
   data_obs_fail_postfit_projy2_copy__95->GetYaxis()->SetTitleSize(0.09);
   data_obs_fail_postfit_projy2_copy__95->GetYaxis()->SetTitleOffset(0.8);
   data_obs_fail_postfit_projy2_copy__95->GetYaxis()->SetTitleFont(42);
   data_obs_fail_postfit_projy2_copy__95->GetZaxis()->SetLabelFont(42);
   data_obs_fail_postfit_projy2_copy__95->GetZaxis()->SetLabelSize(0.035);
   data_obs_fail_postfit_projy2_copy__95->GetZaxis()->SetTitleSize(0.035);
   data_obs_fail_postfit_projy2_copy__95->GetZaxis()->SetTitleFont(42);
   data_obs_fail_postfit_projy2_copy__95->Draw("sameaxis");
   TLatex *   tex = new TLatex(0.21,0.83,"1.0 < G_{i}^{Strips} < 1.0 , F^{Pixels}_{i} < 0.9");
tex->SetNDC();
   tex->SetTextAlign(12);
   tex->SetTextFont(42);
   tex->SetTextSize(0.06);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.17,0.92,"CMS");
tex->SetNDC();
   tex->SetTextFont(61);
   tex->SetTextSize(0.0675);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.25,0.92,"Preliminary");
tex->SetNDC();
   tex->SetTextFont(52);
   tex->SetTextSize(0.0485);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.95,0.92,"101 fb^{-1} (13 TeV)");
tex->SetNDC();
   tex->SetTextAlign(31);
   tex->SetTextFont(42);
   tex->SetTextSize(0.07);
   tex->SetLineWidth(2);
   tex->Draw();
   data_obs_fail_postfit_projy2_main->Modified();
   plots_fit_b/base_figs/postfit_projy2_fail_logy->cd();
  
// ------------>Primitives in pad: data_obs_fail_postfit_projy2_sub
   TPad *data_obs_fail_postfit_projy2_sub = new TPad("data_obs_fail_postfit_projy2_sub", "data_obs_fail_postfit_projy2_sub",0,0,1,0.35);
   data_obs_fail_postfit_projy2_sub->Draw();
   data_obs_fail_postfit_projy2_sub->cd();
   data_obs_fail_postfit_projy2_sub->Range(-633.6539,-6.023077,4270.192,2.9);
   data_obs_fail_postfit_projy2_sub->SetFillColor(0);
   data_obs_fail_postfit_projy2_sub->SetBorderMode(0);
   data_obs_fail_postfit_projy2_sub->SetBorderSize(2);
   data_obs_fail_postfit_projy2_sub->SetTickx(1);
   data_obs_fail_postfit_projy2_sub->SetTicky(1);
   data_obs_fail_postfit_projy2_sub->SetLeftMargin(0.17);
   data_obs_fail_postfit_projy2_sub->SetRightMargin(0.05);
   data_obs_fail_postfit_projy2_sub->SetTopMargin(0);
   data_obs_fail_postfit_projy2_sub->SetBottomMargin(0.35);
   data_obs_fail_postfit_projy2_sub->SetFrameFillStyle(0);
   data_obs_fail_postfit_projy2_sub->SetFrameBorderMode(0);
   data_obs_fail_postfit_projy2_sub->SetFrameFillStyle(0);
   data_obs_fail_postfit_projy2_sub->SetFrameBorderMode(0);
   Double_t xAxis144[2] = {200, 4025}; 
   
   TH1D *data_obs_fail_postfit_projy2_pull__96 = new TH1D("data_obs_fail_postfit_projy2_pull__96","",1, xAxis144);
   data_obs_fail_postfit_projy2_pull__96->SetMinimum(-2.9);
   data_obs_fail_postfit_projy2_pull__96->SetMaximum(2.9);
   data_obs_fail_postfit_projy2_pull__96->SetEntries(2);
   data_obs_fail_postfit_projy2_pull__96->SetStats(0);

   ci = TColor::GetColor("#0000ff");
   data_obs_fail_postfit_projy2_pull__96->SetFillColor(ci);

   ci = TColor::GetColor("#000000");
   data_obs_fail_postfit_projy2_pull__96->SetLineColor(ci);

   ci = TColor::GetColor("#000000");
   data_obs_fail_postfit_projy2_pull__96->SetMarkerColor(ci);
   data_obs_fail_postfit_projy2_pull__96->SetMarkerStyle(8);
   data_obs_fail_postfit_projy2_pull__96->GetXaxis()->SetTitle("p_{T}");
   data_obs_fail_postfit_projy2_pull__96->GetXaxis()->SetLabelFont(42);
   data_obs_fail_postfit_projy2_pull__96->GetXaxis()->SetLabelOffset(0.05);
   data_obs_fail_postfit_projy2_pull__96->GetXaxis()->SetLabelSize(0.13);
   data_obs_fail_postfit_projy2_pull__96->GetXaxis()->SetTitleSize(0.15);
   data_obs_fail_postfit_projy2_pull__96->GetXaxis()->SetTitleOffset(1.15);
   data_obs_fail_postfit_projy2_pull__96->GetXaxis()->SetTitleFont(42);
   data_obs_fail_postfit_projy2_pull__96->GetYaxis()->SetTitle("(Data-Bkg)/#sigma");
   data_obs_fail_postfit_projy2_pull__96->GetYaxis()->SetNdivisions(306);
   data_obs_fail_postfit_projy2_pull__96->GetYaxis()->SetLabelFont(42);
   data_obs_fail_postfit_projy2_pull__96->GetYaxis()->SetLabelSize(0.13);
   data_obs_fail_postfit_projy2_pull__96->GetYaxis()->SetTitleSize(0.12);
   data_obs_fail_postfit_projy2_pull__96->GetYaxis()->SetTitleOffset(0.4);
   data_obs_fail_postfit_projy2_pull__96->GetYaxis()->SetTitleFont(42);
   data_obs_fail_postfit_projy2_pull__96->GetZaxis()->SetLabelFont(42);
   data_obs_fail_postfit_projy2_pull__96->GetZaxis()->SetLabelSize(0.035);
   data_obs_fail_postfit_projy2_pull__96->GetZaxis()->SetTitleSize(0.035);
   data_obs_fail_postfit_projy2_pull__96->GetZaxis()->SetTitleFont(42);
   data_obs_fail_postfit_projy2_pull__96->Draw("hist");
   data_obs_fail_postfit_projy2_sub->Modified();
   plots_fit_b/base_figs/postfit_projy2_fail_logy->cd();
   plots_fit_b/base_figs/postfit_projy2_fail_logy->Modified();
   plots_fit_b/base_figs/postfit_projy2_fail_logy->cd();
   plots_fit_b/base_figs/postfit_projy2_fail_logy->SetSelected(plots_fit_b/base_figs/postfit_projy2_fail_logy);
}
