void postfit_projy1_pass_logy()
{
//=========Macro generated from canvas: plots_fit_b/base_figs/postfit_projy1_pass_logy/plots_fit_b/base_figs/postfit_projy1_pass_logy
//=========  (Fri Jan 12 20:33:16 2024) by ROOT version 6.14/09
   TCanvas *plots_fit_b/base_figs/postfit_projy1_pass_logy = new TCanvas("plots_fit_b/base_figs/postfit_projy1_pass_logy", "plots_fit_b/base_figs/postfit_projy1_pass_logy",0,0,800,700);
   gStyle->SetOptFit(1);
   gStyle->SetOptStat(0);
   plots_fit_b/base_figs/postfit_projy1_pass_logy->SetHighLightColor(2);
   plots_fit_b/base_figs/postfit_projy1_pass_logy->Range(0,0,1,1);
   plots_fit_b/base_figs/postfit_projy1_pass_logy->SetFillColor(0);
   plots_fit_b/base_figs/postfit_projy1_pass_logy->SetBorderMode(0);
   plots_fit_b/base_figs/postfit_projy1_pass_logy->SetBorderSize(2);
   plots_fit_b/base_figs/postfit_projy1_pass_logy->SetTickx(1);
   plots_fit_b/base_figs/postfit_projy1_pass_logy->SetTicky(1);
   plots_fit_b/base_figs/postfit_projy1_pass_logy->SetLeftMargin(0.16);
   plots_fit_b/base_figs/postfit_projy1_pass_logy->SetRightMargin(0);
   plots_fit_b/base_figs/postfit_projy1_pass_logy->SetTopMargin(0);
   plots_fit_b/base_figs/postfit_projy1_pass_logy->SetBottomMargin(0);
   plots_fit_b/base_figs/postfit_projy1_pass_logy->SetFrameFillStyle(0);
   plots_fit_b/base_figs/postfit_projy1_pass_logy->SetFrameBorderMode(0);
  
// ------------>Primitives in pad: data_obs_pass_postfit_projy1_main
   TPad *data_obs_pass_postfit_projy1_main = new TPad("data_obs_pass_postfit_projy1_main", "data_obs_pass_postfit_projy1_main",0,0.35,1,1);
   data_obs_pass_postfit_projy1_main->Draw();
   data_obs_pass_postfit_projy1_main->cd();
   data_obs_pass_postfit_projy1_main->Range(-633.6539,-3.280875,4270.192,3.741007);
   data_obs_pass_postfit_projy1_main->SetFillColor(0);
   data_obs_pass_postfit_projy1_main->SetBorderMode(0);
   data_obs_pass_postfit_projy1_main->SetBorderSize(2);
   data_obs_pass_postfit_projy1_main->SetLogy();
   data_obs_pass_postfit_projy1_main->SetTickx(1);
   data_obs_pass_postfit_projy1_main->SetTicky(1);
   data_obs_pass_postfit_projy1_main->SetLeftMargin(0.17);
   data_obs_pass_postfit_projy1_main->SetRightMargin(0.05);
   data_obs_pass_postfit_projy1_main->SetBottomMargin(0.04);
   data_obs_pass_postfit_projy1_main->SetFrameFillStyle(0);
   data_obs_pass_postfit_projy1_main->SetFrameBorderMode(0);
   data_obs_pass_postfit_projy1_main->SetFrameFillStyle(0);
   data_obs_pass_postfit_projy1_main->SetFrameBorderMode(0);
   Double_t xAxis265[2] = {200, 4025}; 
   
   TH1D *data_obs_pass_postfit_projy1__177 = new TH1D("data_obs_pass_postfit_projy1__177","",1, xAxis265);
   data_obs_pass_postfit_projy1__177->SetBinContent(1,12);
   data_obs_pass_postfit_projy1__177->SetBinError(1,3.464102);
   data_obs_pass_postfit_projy1__177->SetMinimum(0.001);
   data_obs_pass_postfit_projy1__177->SetMaximum(1093.5);
   data_obs_pass_postfit_projy1__177->SetEntries(12);
   data_obs_pass_postfit_projy1__177->SetStats(0);

   Int_t ci;      // for color index setting
   TColor *color; // for color definition with alpha
   ci = TColor::GetColor("#000000");
   data_obs_pass_postfit_projy1__177->SetLineColor(ci);

   ci = TColor::GetColor("#000000");
   data_obs_pass_postfit_projy1__177->SetMarkerColor(ci);
   data_obs_pass_postfit_projy1__177->SetMarkerStyle(8);
   data_obs_pass_postfit_projy1__177->GetXaxis()->SetTitle("p_{T}");
   data_obs_pass_postfit_projy1__177->GetXaxis()->SetLabelFont(42);
   data_obs_pass_postfit_projy1__177->GetXaxis()->SetLabelOffset(0.05);
   data_obs_pass_postfit_projy1__177->GetXaxis()->SetLabelSize(0.07);
   data_obs_pass_postfit_projy1__177->GetXaxis()->SetTitleSize(0.09);
   data_obs_pass_postfit_projy1__177->GetXaxis()->SetTitleOffset(1.15);
   data_obs_pass_postfit_projy1__177->GetXaxis()->SetTitleFont(42);
   data_obs_pass_postfit_projy1__177->GetYaxis()->SetTitle("Events / bin");
   data_obs_pass_postfit_projy1__177->GetYaxis()->SetNdivisions(508);
   data_obs_pass_postfit_projy1__177->GetYaxis()->SetLabelFont(42);
   data_obs_pass_postfit_projy1__177->GetYaxis()->SetLabelSize(0.07);
   data_obs_pass_postfit_projy1__177->GetYaxis()->SetTitleSize(0.09);
   data_obs_pass_postfit_projy1__177->GetYaxis()->SetTitleOffset(0.8);
   data_obs_pass_postfit_projy1__177->GetYaxis()->SetTitleFont(42);
   data_obs_pass_postfit_projy1__177->GetZaxis()->SetLabelFont(42);
   data_obs_pass_postfit_projy1__177->GetZaxis()->SetLabelSize(0.035);
   data_obs_pass_postfit_projy1__177->GetZaxis()->SetTitleSize(0.035);
   data_obs_pass_postfit_projy1__177->GetZaxis()->SetTitleFont(42);
   data_obs_pass_postfit_projy1__177->Draw("pe X0");
   
   THStack *postfit_projy1_pass_logy_stack = new THStack();
   postfit_projy1_pass_logy_stack->SetName("postfit_projy1_pass_logy_stack");
   postfit_projy1_pass_logy_stack->SetTitle("postfit_projy1_pass_logy_stack");
   postfit_projy1_pass_logy_stack->SetMinimum(0.001);
   Double_t xAxis266[2] = {200, 4025}; 
   
   TH1F *postfit_projy1_pass_logy_stack_stack_45 = new TH1F("postfit_projy1_pass_logy_stack_stack_45","postfit_projy1_pass_logy_stack",1, xAxis266);
   postfit_projy1_pass_logy_stack_stack_45->SetMinimum(0.0003183431);
   postfit_projy1_pass_logy_stack_stack_45->SetMaximum(35.58167);
   postfit_projy1_pass_logy_stack_stack_45->SetDirectory(0);
   postfit_projy1_pass_logy_stack_stack_45->SetStats(0);
   postfit_projy1_pass_logy_stack_stack_45->SetLineStyle(0);
   postfit_projy1_pass_logy_stack_stack_45->GetXaxis()->SetLabelFont(42);
   postfit_projy1_pass_logy_stack_stack_45->GetXaxis()->SetLabelOffset(0.007);
   postfit_projy1_pass_logy_stack_stack_45->GetXaxis()->SetLabelSize(0.05);
   postfit_projy1_pass_logy_stack_stack_45->GetXaxis()->SetTitleSize(0.08);
   postfit_projy1_pass_logy_stack_stack_45->GetXaxis()->SetTitleOffset(0.9);
   postfit_projy1_pass_logy_stack_stack_45->GetXaxis()->SetTitleFont(42);
   postfit_projy1_pass_logy_stack_stack_45->GetYaxis()->SetNdivisions(508);
   postfit_projy1_pass_logy_stack_stack_45->GetYaxis()->SetLabelFont(42);
   postfit_projy1_pass_logy_stack_stack_45->GetYaxis()->SetLabelOffset(0.007);
   postfit_projy1_pass_logy_stack_stack_45->GetYaxis()->SetLabelSize(0.05);
   postfit_projy1_pass_logy_stack_stack_45->GetYaxis()->SetTitleSize(0.08);
   postfit_projy1_pass_logy_stack_stack_45->GetYaxis()->SetTitleOffset(1.25);
   postfit_projy1_pass_logy_stack_stack_45->GetYaxis()->SetTitleFont(42);
   postfit_projy1_pass_logy_stack_stack_45->GetZaxis()->SetLabelFont(42);
   postfit_projy1_pass_logy_stack_stack_45->GetZaxis()->SetLabelOffset(0.007);
   postfit_projy1_pass_logy_stack_stack_45->GetZaxis()->SetLabelSize(0.05);
   postfit_projy1_pass_logy_stack_stack_45->GetZaxis()->SetTitleSize(0.08);
   postfit_projy1_pass_logy_stack_stack_45->GetZaxis()->SetTitleFont(42);
   postfit_projy1_pass_logy_stack->SetHistogram(postfit_projy1_pass_logy_stack_stack_45);
   
   Double_t xAxis267[2] = {200, 4025}; 
   
   TH1D *Background_0x0_pass_postfit_projy1_stack_1 = new TH1D("Background_0x0_pass_postfit_projy1_stack_1","Background, pass, postfit, 0.25-1.0",1, xAxis267);
   Background_0x0_pass_postfit_projy1_stack_1->SetBinContent(1,17.44506);
   Background_0x0_pass_postfit_projy1_stack_1->SetBinError(1,1.720871);
   Background_0x0_pass_postfit_projy1_stack_1->SetMinimum(0.001);
   Background_0x0_pass_postfit_projy1_stack_1->SetEntries(102.7657);
   Background_0x0_pass_postfit_projy1_stack_1->SetStats(0);

   ci = TColor::GetColor("#ffff00");
   Background_0x0_pass_postfit_projy1_stack_1->SetFillColor(ci);

   ci = 1201;
   color = new TColor(ci, 1, 1, 1, " ", 0);
   Background_0x0_pass_postfit_projy1_stack_1->SetLineColor(ci);
   Background_0x0_pass_postfit_projy1_stack_1->GetXaxis()->SetTitle("p_{T}");
   Background_0x0_pass_postfit_projy1_stack_1->GetXaxis()->SetLabelFont(42);
   Background_0x0_pass_postfit_projy1_stack_1->GetXaxis()->SetLabelSize(0.035);
   Background_0x0_pass_postfit_projy1_stack_1->GetXaxis()->SetTitleSize(0.035);
   Background_0x0_pass_postfit_projy1_stack_1->GetXaxis()->SetTitleOffset(0);
   Background_0x0_pass_postfit_projy1_stack_1->GetXaxis()->SetTitleFont(42);
   Background_0x0_pass_postfit_projy1_stack_1->GetYaxis()->SetTitle("Events / bin");
   Background_0x0_pass_postfit_projy1_stack_1->GetYaxis()->SetLabelFont(42);
   Background_0x0_pass_postfit_projy1_stack_1->GetYaxis()->SetLabelSize(0.035);
   Background_0x0_pass_postfit_projy1_stack_1->GetYaxis()->SetTitleSize(0.035);
   Background_0x0_pass_postfit_projy1_stack_1->GetYaxis()->SetTitleOffset(0);
   Background_0x0_pass_postfit_projy1_stack_1->GetYaxis()->SetTitleFont(42);
   Background_0x0_pass_postfit_projy1_stack_1->GetZaxis()->SetLabelFont(42);
   Background_0x0_pass_postfit_projy1_stack_1->GetZaxis()->SetLabelSize(0.035);
   Background_0x0_pass_postfit_projy1_stack_1->GetZaxis()->SetTitleSize(0.035);
   Background_0x0_pass_postfit_projy1_stack_1->GetZaxis()->SetTitleFont(42);
   postfit_projy1_pass_logy_stack->Add(Background_0x0_pass_postfit_projy1_stack_1,"");
   postfit_projy1_pass_logy_stack->Draw("hist same");
   
   postfit_projy1_pass_logy_stack = new THStack();
   postfit_projy1_pass_logy_stack->SetName("postfit_projy1_pass_logy_stack");
   postfit_projy1_pass_logy_stack->SetTitle("postfit_projy1_pass_logy_stack");
   postfit_projy1_pass_logy_stack->SetMinimum(0.001);
   Double_t xAxis268[2] = {200, 4025}; 
   
   TH1F *postfit_projy1_pass_logy_stack_stack_45_stack_46 = new TH1F("postfit_projy1_pass_logy_stack_stack_45_stack_46","postfit_projy1_pass_logy_stack",1, xAxis268);
   postfit_projy1_pass_logy_stack_stack_45_stack_46->SetMinimum(0.0003183431);
   postfit_projy1_pass_logy_stack_stack_45_stack_46->SetMaximum(35.58167);
   postfit_projy1_pass_logy_stack_stack_45_stack_46->SetDirectory(0);
   postfit_projy1_pass_logy_stack_stack_45_stack_46->SetStats(0);
   postfit_projy1_pass_logy_stack_stack_45_stack_46->SetLineStyle(0);
   postfit_projy1_pass_logy_stack_stack_45_stack_46->GetXaxis()->SetLabelFont(42);
   postfit_projy1_pass_logy_stack_stack_45_stack_46->GetXaxis()->SetLabelOffset(0.007);
   postfit_projy1_pass_logy_stack_stack_45_stack_46->GetXaxis()->SetLabelSize(0.05);
   postfit_projy1_pass_logy_stack_stack_45_stack_46->GetXaxis()->SetTitleSize(0.08);
   postfit_projy1_pass_logy_stack_stack_45_stack_46->GetXaxis()->SetTitleOffset(0.9);
   postfit_projy1_pass_logy_stack_stack_45_stack_46->GetXaxis()->SetTitleFont(42);
   postfit_projy1_pass_logy_stack_stack_45_stack_46->GetYaxis()->SetNdivisions(508);
   postfit_projy1_pass_logy_stack_stack_45_stack_46->GetYaxis()->SetLabelFont(42);
   postfit_projy1_pass_logy_stack_stack_45_stack_46->GetYaxis()->SetLabelOffset(0.007);
   postfit_projy1_pass_logy_stack_stack_45_stack_46->GetYaxis()->SetLabelSize(0.05);
   postfit_projy1_pass_logy_stack_stack_45_stack_46->GetYaxis()->SetTitleSize(0.08);
   postfit_projy1_pass_logy_stack_stack_45_stack_46->GetYaxis()->SetTitleOffset(1.25);
   postfit_projy1_pass_logy_stack_stack_45_stack_46->GetYaxis()->SetTitleFont(42);
   postfit_projy1_pass_logy_stack_stack_45_stack_46->GetZaxis()->SetLabelFont(42);
   postfit_projy1_pass_logy_stack_stack_45_stack_46->GetZaxis()->SetLabelOffset(0.007);
   postfit_projy1_pass_logy_stack_stack_45_stack_46->GetZaxis()->SetLabelSize(0.05);
   postfit_projy1_pass_logy_stack_stack_45_stack_46->GetZaxis()->SetTitleSize(0.08);
   postfit_projy1_pass_logy_stack_stack_45_stack_46->GetZaxis()->SetTitleFont(42);
   postfit_projy1_pass_logy_stack->SetHistogram(postfit_projy1_pass_logy_stack_stack_45_stack_46);
   
   Double_t xAxis269[2] = {200, 4025}; 
   
   TH1D *Background_0x0_pass_postfit_projy1_stack_1_stack_1 = new TH1D("Background_0x0_pass_postfit_projy1_stack_1_stack_1","Background, pass, postfit, 0.25-1.0",1, xAxis269);
   Background_0x0_pass_postfit_projy1_stack_1_stack_1->SetBinContent(1,17.44506);
   Background_0x0_pass_postfit_projy1_stack_1_stack_1->SetBinError(1,1.720871);
   Background_0x0_pass_postfit_projy1_stack_1_stack_1->SetMinimum(0.001);
   Background_0x0_pass_postfit_projy1_stack_1_stack_1->SetEntries(102.7657);
   Background_0x0_pass_postfit_projy1_stack_1_stack_1->SetStats(0);

   ci = TColor::GetColor("#ffff00");
   Background_0x0_pass_postfit_projy1_stack_1_stack_1->SetFillColor(ci);

   ci = 1201;
   color = new TColor(ci, 1, 1, 1, " ", 0);
   Background_0x0_pass_postfit_projy1_stack_1_stack_1->SetLineColor(ci);
   Background_0x0_pass_postfit_projy1_stack_1_stack_1->GetXaxis()->SetTitle("p_{T}");
   Background_0x0_pass_postfit_projy1_stack_1_stack_1->GetXaxis()->SetLabelFont(42);
   Background_0x0_pass_postfit_projy1_stack_1_stack_1->GetXaxis()->SetLabelSize(0.035);
   Background_0x0_pass_postfit_projy1_stack_1_stack_1->GetXaxis()->SetTitleSize(0.035);
   Background_0x0_pass_postfit_projy1_stack_1_stack_1->GetXaxis()->SetTitleOffset(0);
   Background_0x0_pass_postfit_projy1_stack_1_stack_1->GetXaxis()->SetTitleFont(42);
   Background_0x0_pass_postfit_projy1_stack_1_stack_1->GetYaxis()->SetTitle("Events / bin");
   Background_0x0_pass_postfit_projy1_stack_1_stack_1->GetYaxis()->SetLabelFont(42);
   Background_0x0_pass_postfit_projy1_stack_1_stack_1->GetYaxis()->SetLabelSize(0.035);
   Background_0x0_pass_postfit_projy1_stack_1_stack_1->GetYaxis()->SetTitleSize(0.035);
   Background_0x0_pass_postfit_projy1_stack_1_stack_1->GetYaxis()->SetTitleOffset(0);
   Background_0x0_pass_postfit_projy1_stack_1_stack_1->GetYaxis()->SetTitleFont(42);
   Background_0x0_pass_postfit_projy1_stack_1_stack_1->GetZaxis()->SetLabelFont(42);
   Background_0x0_pass_postfit_projy1_stack_1_stack_1->GetZaxis()->SetLabelSize(0.035);
   Background_0x0_pass_postfit_projy1_stack_1_stack_1->GetZaxis()->SetTitleSize(0.035);
   Background_0x0_pass_postfit_projy1_stack_1_stack_1->GetZaxis()->SetTitleFont(42);
   postfit_projy1_pass_logy_stack->Add(Background_0x0_pass_postfit_projy1_stack_1_stack_1,"");
   postfit_projy1_pass_logy_stack->Draw("hist same");
   Double_t xAxis270[2] = {200, 4025}; 
   
   TH1D *Signal_gluinomI1800_pass_postfit_projy1__178 = new TH1D("Signal_gluinomI1800_pass_postfit_projy1__178","HSCP gluino 1800 GeV, pass, postfit, 0.25-1.0",1, xAxis270);
   Signal_gluinomI1800_pass_postfit_projy1__178->SetBinContent(1,15.91694);
   Signal_gluinomI1800_pass_postfit_projy1__178->SetBinError(1,4.976973);
   Signal_gluinomI1800_pass_postfit_projy1__178->SetMinimum(0.001);
   Signal_gluinomI1800_pass_postfit_projy1__178->SetEntries(10.22795);
   Signal_gluinomI1800_pass_postfit_projy1__178->SetStats(0);
   Signal_gluinomI1800_pass_postfit_projy1__178->SetLineColor(4);
   Signal_gluinomI1800_pass_postfit_projy1__178->SetLineWidth(2);
   Signal_gluinomI1800_pass_postfit_projy1__178->GetXaxis()->SetTitle("p_{T}");
   Signal_gluinomI1800_pass_postfit_projy1__178->GetXaxis()->SetLabelFont(42);
   Signal_gluinomI1800_pass_postfit_projy1__178->GetXaxis()->SetLabelSize(0.035);
   Signal_gluinomI1800_pass_postfit_projy1__178->GetXaxis()->SetTitleSize(0.035);
   Signal_gluinomI1800_pass_postfit_projy1__178->GetXaxis()->SetTitleOffset(0);
   Signal_gluinomI1800_pass_postfit_projy1__178->GetXaxis()->SetTitleFont(42);
   Signal_gluinomI1800_pass_postfit_projy1__178->GetYaxis()->SetTitle("Events / bin");
   Signal_gluinomI1800_pass_postfit_projy1__178->GetYaxis()->SetLabelFont(42);
   Signal_gluinomI1800_pass_postfit_projy1__178->GetYaxis()->SetLabelSize(0.035);
   Signal_gluinomI1800_pass_postfit_projy1__178->GetYaxis()->SetTitleSize(0.035);
   Signal_gluinomI1800_pass_postfit_projy1__178->GetYaxis()->SetTitleOffset(0);
   Signal_gluinomI1800_pass_postfit_projy1__178->GetYaxis()->SetTitleFont(42);
   Signal_gluinomI1800_pass_postfit_projy1__178->GetZaxis()->SetLabelFont(42);
   Signal_gluinomI1800_pass_postfit_projy1__178->GetZaxis()->SetLabelSize(0.035);
   Signal_gluinomI1800_pass_postfit_projy1__178->GetZaxis()->SetTitleSize(0.035);
   Signal_gluinomI1800_pass_postfit_projy1__178->GetZaxis()->SetTitleFont(42);
   Signal_gluinomI1800_pass_postfit_projy1__178->Draw("hist same");
   Double_t xAxis271[2] = {200, 4025}; 
   
   TH1D *Signal_ppStaumI557_pass_postfit_projy1__179 = new TH1D("Signal_ppStaumI557_pass_postfit_projy1__179","HSCP stau 557 GeV, pass, postfit, 0.25-1.0",1, xAxis271);
   Signal_ppStaumI557_pass_postfit_projy1__179->SetBinContent(1,11.2774);
   Signal_ppStaumI557_pass_postfit_projy1__179->SetBinError(1,1.329373);
   Signal_ppStaumI557_pass_postfit_projy1__179->SetMinimum(0.001);
   Signal_ppStaumI557_pass_postfit_projy1__179->SetEntries(71.96547);
   Signal_ppStaumI557_pass_postfit_projy1__179->SetStats(0);
   Signal_ppStaumI557_pass_postfit_projy1__179->SetLineColor(2);
   Signal_ppStaumI557_pass_postfit_projy1__179->SetLineWidth(2);
   Signal_ppStaumI557_pass_postfit_projy1__179->GetXaxis()->SetTitle("p_{T}");
   Signal_ppStaumI557_pass_postfit_projy1__179->GetXaxis()->SetLabelFont(42);
   Signal_ppStaumI557_pass_postfit_projy1__179->GetXaxis()->SetLabelSize(0.035);
   Signal_ppStaumI557_pass_postfit_projy1__179->GetXaxis()->SetTitleSize(0.035);
   Signal_ppStaumI557_pass_postfit_projy1__179->GetXaxis()->SetTitleOffset(0);
   Signal_ppStaumI557_pass_postfit_projy1__179->GetXaxis()->SetTitleFont(42);
   Signal_ppStaumI557_pass_postfit_projy1__179->GetYaxis()->SetTitle("Events / bin");
   Signal_ppStaumI557_pass_postfit_projy1__179->GetYaxis()->SetLabelFont(42);
   Signal_ppStaumI557_pass_postfit_projy1__179->GetYaxis()->SetLabelSize(0.035);
   Signal_ppStaumI557_pass_postfit_projy1__179->GetYaxis()->SetTitleSize(0.035);
   Signal_ppStaumI557_pass_postfit_projy1__179->GetYaxis()->SetTitleOffset(0);
   Signal_ppStaumI557_pass_postfit_projy1__179->GetYaxis()->SetTitleFont(42);
   Signal_ppStaumI557_pass_postfit_projy1__179->GetZaxis()->SetLabelFont(42);
   Signal_ppStaumI557_pass_postfit_projy1__179->GetZaxis()->SetLabelSize(0.035);
   Signal_ppStaumI557_pass_postfit_projy1__179->GetZaxis()->SetTitleSize(0.035);
   Signal_ppStaumI557_pass_postfit_projy1__179->GetZaxis()->SetTitleFont(42);
   Signal_ppStaumI557_pass_postfit_projy1__179->Draw("hist same");
   Double_t xAxis272[2] = {200, 4025}; 
   
   TH1D *TotalBkg_pass_postfit_projy1__180 = new TH1D("TotalBkg_pass_postfit_projy1__180","TotalBkg, pass, postfit, 0.25-1.0",1, xAxis272);
   TotalBkg_pass_postfit_projy1__180->SetBinContent(1,17.44506);
   TotalBkg_pass_postfit_projy1__180->SetBinError(1,1.538981);
   TotalBkg_pass_postfit_projy1__180->SetMinimum(0.001);
   TotalBkg_pass_postfit_projy1__180->SetEntries(128.4927);
   TotalBkg_pass_postfit_projy1__180->SetStats(0);
   TotalBkg_pass_postfit_projy1__180->SetMarkerStyle(0);
   TotalBkg_pass_postfit_projy1__180->GetXaxis()->SetTitle("p_{T}");
   TotalBkg_pass_postfit_projy1__180->GetXaxis()->SetLabelFont(42);
   TotalBkg_pass_postfit_projy1__180->GetXaxis()->SetLabelSize(0.035);
   TotalBkg_pass_postfit_projy1__180->GetXaxis()->SetTitleSize(0.035);
   TotalBkg_pass_postfit_projy1__180->GetXaxis()->SetTitleOffset(0);
   TotalBkg_pass_postfit_projy1__180->GetXaxis()->SetTitleFont(42);
   TotalBkg_pass_postfit_projy1__180->GetYaxis()->SetTitle("Events / bin");
   TotalBkg_pass_postfit_projy1__180->GetYaxis()->SetLabelFont(42);
   TotalBkg_pass_postfit_projy1__180->GetYaxis()->SetLabelSize(0.035);
   TotalBkg_pass_postfit_projy1__180->GetYaxis()->SetTitleSize(0.035);
   TotalBkg_pass_postfit_projy1__180->GetYaxis()->SetTitleOffset(0);
   TotalBkg_pass_postfit_projy1__180->GetYaxis()->SetTitleFont(42);
   TotalBkg_pass_postfit_projy1__180->GetZaxis()->SetLabelFont(42);
   TotalBkg_pass_postfit_projy1__180->GetZaxis()->SetLabelSize(0.035);
   TotalBkg_pass_postfit_projy1__180->GetZaxis()->SetTitleSize(0.035);
   TotalBkg_pass_postfit_projy1__180->GetZaxis()->SetTitleFont(42);
   TotalBkg_pass_postfit_projy1__180->Draw("hist same");
   Double_t xAxis273[2] = {200, 4025}; 
   
   TH1D *TotalBkg_pass_postfit_projy1__181 = new TH1D("TotalBkg_pass_postfit_projy1__181","TotalBkg, pass, postfit, 0.25-1.0",1, xAxis273);
   TotalBkg_pass_postfit_projy1__181->SetBinContent(1,17.44506);
   TotalBkg_pass_postfit_projy1__181->SetBinError(1,1.538981);
   TotalBkg_pass_postfit_projy1__181->SetMinimum(0.001);
   TotalBkg_pass_postfit_projy1__181->SetEntries(128.4927);
   TotalBkg_pass_postfit_projy1__181->SetStats(0);
   TotalBkg_pass_postfit_projy1__181->SetFillColor(1);
   TotalBkg_pass_postfit_projy1__181->SetFillStyle(3354);
   TotalBkg_pass_postfit_projy1__181->SetLineWidth(0);
   TotalBkg_pass_postfit_projy1__181->SetMarkerStyle(0);
   TotalBkg_pass_postfit_projy1__181->GetXaxis()->SetTitle("p_{T}");
   TotalBkg_pass_postfit_projy1__181->GetXaxis()->SetLabelFont(42);
   TotalBkg_pass_postfit_projy1__181->GetXaxis()->SetLabelSize(0.035);
   TotalBkg_pass_postfit_projy1__181->GetXaxis()->SetTitleSize(0.035);
   TotalBkg_pass_postfit_projy1__181->GetXaxis()->SetTitleOffset(0);
   TotalBkg_pass_postfit_projy1__181->GetXaxis()->SetTitleFont(42);
   TotalBkg_pass_postfit_projy1__181->GetYaxis()->SetTitle("Events / bin");
   TotalBkg_pass_postfit_projy1__181->GetYaxis()->SetLabelFont(42);
   TotalBkg_pass_postfit_projy1__181->GetYaxis()->SetLabelSize(0.035);
   TotalBkg_pass_postfit_projy1__181->GetYaxis()->SetTitleSize(0.035);
   TotalBkg_pass_postfit_projy1__181->GetYaxis()->SetTitleOffset(0);
   TotalBkg_pass_postfit_projy1__181->GetYaxis()->SetTitleFont(42);
   TotalBkg_pass_postfit_projy1__181->GetZaxis()->SetLabelFont(42);
   TotalBkg_pass_postfit_projy1__181->GetZaxis()->SetLabelSize(0.035);
   TotalBkg_pass_postfit_projy1__181->GetZaxis()->SetTitleSize(0.035);
   TotalBkg_pass_postfit_projy1__181->GetZaxis()->SetTitleFont(42);
   TotalBkg_pass_postfit_projy1__181->Draw("e2 same");
   Double_t xAxis274[2] = {200, 4025}; 
   
   TH1D *data_obs_pass_postfit_projy1__182 = new TH1D("data_obs_pass_postfit_projy1__182","",1, xAxis274);
   data_obs_pass_postfit_projy1__182->SetBinContent(1,12);
   data_obs_pass_postfit_projy1__182->SetBinError(1,3.464102);
   data_obs_pass_postfit_projy1__182->SetMinimum(0.001);
   data_obs_pass_postfit_projy1__182->SetMaximum(1093.5);
   data_obs_pass_postfit_projy1__182->SetEntries(12);
   data_obs_pass_postfit_projy1__182->SetStats(0);

   ci = TColor::GetColor("#000000");
   data_obs_pass_postfit_projy1__182->SetLineColor(ci);

   ci = TColor::GetColor("#000000");
   data_obs_pass_postfit_projy1__182->SetMarkerColor(ci);
   data_obs_pass_postfit_projy1__182->SetMarkerStyle(8);
   data_obs_pass_postfit_projy1__182->GetXaxis()->SetTitle("p_{T}");
   data_obs_pass_postfit_projy1__182->GetXaxis()->SetLabelFont(42);
   data_obs_pass_postfit_projy1__182->GetXaxis()->SetLabelOffset(0.05);
   data_obs_pass_postfit_projy1__182->GetXaxis()->SetLabelSize(0.07);
   data_obs_pass_postfit_projy1__182->GetXaxis()->SetTitleSize(0.09);
   data_obs_pass_postfit_projy1__182->GetXaxis()->SetTitleOffset(1.15);
   data_obs_pass_postfit_projy1__182->GetXaxis()->SetTitleFont(42);
   data_obs_pass_postfit_projy1__182->GetYaxis()->SetTitle("Events / bin");
   data_obs_pass_postfit_projy1__182->GetYaxis()->SetNdivisions(508);
   data_obs_pass_postfit_projy1__182->GetYaxis()->SetLabelFont(42);
   data_obs_pass_postfit_projy1__182->GetYaxis()->SetLabelSize(0.07);
   data_obs_pass_postfit_projy1__182->GetYaxis()->SetTitleSize(0.09);
   data_obs_pass_postfit_projy1__182->GetYaxis()->SetTitleOffset(0.8);
   data_obs_pass_postfit_projy1__182->GetYaxis()->SetTitleFont(42);
   data_obs_pass_postfit_projy1__182->GetZaxis()->SetLabelFont(42);
   data_obs_pass_postfit_projy1__182->GetZaxis()->SetLabelSize(0.035);
   data_obs_pass_postfit_projy1__182->GetZaxis()->SetTitleSize(0.035);
   data_obs_pass_postfit_projy1__182->GetZaxis()->SetTitleFont(42);
   data_obs_pass_postfit_projy1__182->Draw("pe X0 same");
   
   TLegend *leg = new TLegend(0.65,0.61,0.9,0.88,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(1001);
   TLegendEntry *entry=leg->AddEntry("data_obs_pass_postfit_projy1","Data","pe X0");

   ci = TColor::GetColor("#000000");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);

   ci = TColor::GetColor("#000000");
   entry->SetMarkerColor(ci);
   entry->SetMarkerStyle(8);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("TotalBkg_pass_postfit_projy1","Total bkg unc.","F");
   entry->SetFillColor(1);
   entry->SetFillStyle(3354);
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("Signal_gluino-1800_pass_postfit_projy1","HSCP gluino 1800 GeV","L");
   entry->SetLineColor(4);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("Signal_ppStau-557_pass_postfit_projy1","HSCP stau 557 GeV","L");
   entry->SetLineColor(2);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("Background_0x0_pass_postfit_projy1_stack_1_stack_1","Background","f");

   ci = TColor::GetColor("#ffff00");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = 1201;
   color = new TColor(ci, 1, 1, 1, " ", 0);
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   leg->Draw();
   Double_t xAxis275[2] = {200, 4025}; 
   
   TH1D *data_obs_pass_postfit_projy1_copy__183 = new TH1D("data_obs_pass_postfit_projy1_copy__183","",1, xAxis275);
   data_obs_pass_postfit_projy1_copy__183->SetBinContent(1,12);
   data_obs_pass_postfit_projy1_copy__183->SetBinError(1,3.464102);
   data_obs_pass_postfit_projy1_copy__183->SetMinimum(0.001);
   data_obs_pass_postfit_projy1_copy__183->SetMaximum(1093.5);
   data_obs_pass_postfit_projy1_copy__183->SetEntries(12);
   data_obs_pass_postfit_projy1_copy__183->SetDirectory(0);
   data_obs_pass_postfit_projy1_copy__183->SetStats(0);

   ci = TColor::GetColor("#000000");
   data_obs_pass_postfit_projy1_copy__183->SetLineColor(ci);

   ci = TColor::GetColor("#000000");
   data_obs_pass_postfit_projy1_copy__183->SetMarkerColor(ci);
   data_obs_pass_postfit_projy1_copy__183->SetMarkerStyle(8);
   data_obs_pass_postfit_projy1_copy__183->GetXaxis()->SetTitle("p_{T}");
   data_obs_pass_postfit_projy1_copy__183->GetXaxis()->SetLabelFont(42);
   data_obs_pass_postfit_projy1_copy__183->GetXaxis()->SetLabelOffset(0.05);
   data_obs_pass_postfit_projy1_copy__183->GetXaxis()->SetLabelSize(0.07);
   data_obs_pass_postfit_projy1_copy__183->GetXaxis()->SetTitleSize(0.09);
   data_obs_pass_postfit_projy1_copy__183->GetXaxis()->SetTitleOffset(1.15);
   data_obs_pass_postfit_projy1_copy__183->GetXaxis()->SetTitleFont(42);
   data_obs_pass_postfit_projy1_copy__183->GetYaxis()->SetTitle("Events / bin");
   data_obs_pass_postfit_projy1_copy__183->GetYaxis()->SetNdivisions(508);
   data_obs_pass_postfit_projy1_copy__183->GetYaxis()->SetLabelFont(42);
   data_obs_pass_postfit_projy1_copy__183->GetYaxis()->SetLabelSize(0.07);
   data_obs_pass_postfit_projy1_copy__183->GetYaxis()->SetTitleSize(0.09);
   data_obs_pass_postfit_projy1_copy__183->GetYaxis()->SetTitleOffset(0.8);
   data_obs_pass_postfit_projy1_copy__183->GetYaxis()->SetTitleFont(42);
   data_obs_pass_postfit_projy1_copy__183->GetZaxis()->SetLabelFont(42);
   data_obs_pass_postfit_projy1_copy__183->GetZaxis()->SetLabelSize(0.035);
   data_obs_pass_postfit_projy1_copy__183->GetZaxis()->SetTitleSize(0.035);
   data_obs_pass_postfit_projy1_copy__183->GetZaxis()->SetTitleFont(42);
   data_obs_pass_postfit_projy1_copy__183->Draw("sameaxis");
   TLatex *   tex = new TLatex(0.21,0.83,"0.25 < G_{i}^{Strips} < 1.0 , F^{Pixels}_{i} > 0.9");
tex->SetNDC();
   tex->SetTextAlign(12);
   tex->SetTextFont(42);
   tex->SetTextSize(0.06);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.17,0.92,"CMS");
tex->SetNDC();
   tex->SetTextFont(61);
   tex->SetTextSize(0.0675);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.25,0.92,"Preliminary");
tex->SetNDC();
   tex->SetTextFont(52);
   tex->SetTextSize(0.0485);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.95,0.92,"101 fb^{-1} (13 TeV)");
tex->SetNDC();
   tex->SetTextAlign(31);
   tex->SetTextFont(42);
   tex->SetTextSize(0.07);
   tex->SetLineWidth(2);
   tex->Draw();
   data_obs_pass_postfit_projy1_main->Modified();
   plots_fit_b/base_figs/postfit_projy1_pass_logy->cd();
  
// ------------>Primitives in pad: data_obs_pass_postfit_projy1_sub
   TPad *data_obs_pass_postfit_projy1_sub = new TPad("data_obs_pass_postfit_projy1_sub", "data_obs_pass_postfit_projy1_sub",0,0,1,0.35);
   data_obs_pass_postfit_projy1_sub->Draw();
   data_obs_pass_postfit_projy1_sub->cd();
   data_obs_pass_postfit_projy1_sub->Range(-633.6539,-6.023077,4270.192,2.9);
   data_obs_pass_postfit_projy1_sub->SetFillColor(0);
   data_obs_pass_postfit_projy1_sub->SetBorderMode(0);
   data_obs_pass_postfit_projy1_sub->SetBorderSize(2);
   data_obs_pass_postfit_projy1_sub->SetTickx(1);
   data_obs_pass_postfit_projy1_sub->SetTicky(1);
   data_obs_pass_postfit_projy1_sub->SetLeftMargin(0.17);
   data_obs_pass_postfit_projy1_sub->SetRightMargin(0.05);
   data_obs_pass_postfit_projy1_sub->SetTopMargin(0);
   data_obs_pass_postfit_projy1_sub->SetBottomMargin(0.35);
   data_obs_pass_postfit_projy1_sub->SetFrameFillStyle(0);
   data_obs_pass_postfit_projy1_sub->SetFrameBorderMode(0);
   data_obs_pass_postfit_projy1_sub->SetFrameFillStyle(0);
   data_obs_pass_postfit_projy1_sub->SetFrameBorderMode(0);
   Double_t xAxis276[2] = {200, 4025}; 
   
   TH1D *data_obs_pass_postfit_projy1_pull__184 = new TH1D("data_obs_pass_postfit_projy1_pull__184","",1, xAxis276);
   data_obs_pass_postfit_projy1_pull__184->SetBinContent(1,-1.131435);
   data_obs_pass_postfit_projy1_pull__184->SetBinError(1,3.790576);
   data_obs_pass_postfit_projy1_pull__184->SetMinimum(-2.9);
   data_obs_pass_postfit_projy1_pull__184->SetMaximum(2.9);
   data_obs_pass_postfit_projy1_pull__184->SetEntries(6.445062);
   data_obs_pass_postfit_projy1_pull__184->SetStats(0);

   ci = TColor::GetColor("#0000ff");
   data_obs_pass_postfit_projy1_pull__184->SetFillColor(ci);

   ci = TColor::GetColor("#000000");
   data_obs_pass_postfit_projy1_pull__184->SetLineColor(ci);

   ci = TColor::GetColor("#000000");
   data_obs_pass_postfit_projy1_pull__184->SetMarkerColor(ci);
   data_obs_pass_postfit_projy1_pull__184->SetMarkerStyle(8);
   data_obs_pass_postfit_projy1_pull__184->GetXaxis()->SetTitle("p_{T}");
   data_obs_pass_postfit_projy1_pull__184->GetXaxis()->SetLabelFont(42);
   data_obs_pass_postfit_projy1_pull__184->GetXaxis()->SetLabelOffset(0.05);
   data_obs_pass_postfit_projy1_pull__184->GetXaxis()->SetLabelSize(0.13);
   data_obs_pass_postfit_projy1_pull__184->GetXaxis()->SetTitleSize(0.15);
   data_obs_pass_postfit_projy1_pull__184->GetXaxis()->SetTitleOffset(1.15);
   data_obs_pass_postfit_projy1_pull__184->GetXaxis()->SetTitleFont(42);
   data_obs_pass_postfit_projy1_pull__184->GetYaxis()->SetTitle("(Data-Bkg)/#sigma");
   data_obs_pass_postfit_projy1_pull__184->GetYaxis()->SetNdivisions(306);
   data_obs_pass_postfit_projy1_pull__184->GetYaxis()->SetLabelFont(42);
   data_obs_pass_postfit_projy1_pull__184->GetYaxis()->SetLabelSize(0.13);
   data_obs_pass_postfit_projy1_pull__184->GetYaxis()->SetTitleSize(0.12);
   data_obs_pass_postfit_projy1_pull__184->GetYaxis()->SetTitleOffset(0.4);
   data_obs_pass_postfit_projy1_pull__184->GetYaxis()->SetTitleFont(42);
   data_obs_pass_postfit_projy1_pull__184->GetZaxis()->SetLabelFont(42);
   data_obs_pass_postfit_projy1_pull__184->GetZaxis()->SetLabelSize(0.035);
   data_obs_pass_postfit_projy1_pull__184->GetZaxis()->SetTitleSize(0.035);
   data_obs_pass_postfit_projy1_pull__184->GetZaxis()->SetTitleFont(42);
   data_obs_pass_postfit_projy1_pull__184->Draw("hist");
   data_obs_pass_postfit_projy1_sub->Modified();
   plots_fit_b/base_figs/postfit_projy1_pass_logy->cd();
   plots_fit_b/base_figs/postfit_projy1_pass_logy->Modified();
   plots_fit_b/base_figs/postfit_projy1_pass_logy->cd();
   plots_fit_b/base_figs/postfit_projy1_pass_logy->SetSelected(plots_fit_b/base_figs/postfit_projy1_pass_logy);
}
