void postfit_projy2_pass()
{
//=========Macro generated from canvas: plots_fit_s/base_figs/postfit_projy2_pass/plots_fit_s/base_figs/postfit_projy2_pass
//=========  (Fri Jan 12 21:00:09 2024) by ROOT version 6.14/09
   TCanvas *plots_fit_s/base_figs/postfit_projy2_pass = new TCanvas("plots_fit_s/base_figs/postfit_projy2_pass", "plots_fit_s/base_figs/postfit_projy2_pass",0,0,800,700);
   gStyle->SetOptFit(1);
   gStyle->SetOptStat(0);
   plots_fit_s/base_figs/postfit_projy2_pass->SetHighLightColor(2);
   plots_fit_s/base_figs/postfit_projy2_pass->Range(0,0,1,1);
   plots_fit_s/base_figs/postfit_projy2_pass->SetFillColor(0);
   plots_fit_s/base_figs/postfit_projy2_pass->SetBorderMode(0);
   plots_fit_s/base_figs/postfit_projy2_pass->SetBorderSize(2);
   plots_fit_s/base_figs/postfit_projy2_pass->SetTickx(1);
   plots_fit_s/base_figs/postfit_projy2_pass->SetTicky(1);
   plots_fit_s/base_figs/postfit_projy2_pass->SetLeftMargin(0.16);
   plots_fit_s/base_figs/postfit_projy2_pass->SetRightMargin(0);
   plots_fit_s/base_figs/postfit_projy2_pass->SetTopMargin(0);
   plots_fit_s/base_figs/postfit_projy2_pass->SetBottomMargin(0);
   plots_fit_s/base_figs/postfit_projy2_pass->SetFrameFillStyle(0);
   plots_fit_s/base_figs/postfit_projy2_pass->SetFrameBorderMode(0);
  
// ------------>Primitives in pad: data_obs_pass_postfit_projy2_main
   TPad *data_obs_pass_postfit_projy2_main = new TPad("data_obs_pass_postfit_projy2_main", "data_obs_pass_postfit_projy2_main",0,0.35,1,1);
   data_obs_pass_postfit_projy2_main->Draw();
   data_obs_pass_postfit_projy2_main->cd();
   data_obs_pass_postfit_projy2_main->Range(17.30769,-0.04651163,209.6154,1.116279);
   data_obs_pass_postfit_projy2_main->SetFillColor(0);
   data_obs_pass_postfit_projy2_main->SetBorderMode(0);
   data_obs_pass_postfit_projy2_main->SetBorderSize(2);
   data_obs_pass_postfit_projy2_main->SetTickx(1);
   data_obs_pass_postfit_projy2_main->SetTicky(1);
   data_obs_pass_postfit_projy2_main->SetLeftMargin(0.17);
   data_obs_pass_postfit_projy2_main->SetRightMargin(0.05);
   data_obs_pass_postfit_projy2_main->SetBottomMargin(0.04);
   data_obs_pass_postfit_projy2_main->SetFrameFillStyle(0);
   data_obs_pass_postfit_projy2_main->SetFrameBorderMode(0);
   data_obs_pass_postfit_projy2_main->SetFrameFillStyle(0);
   data_obs_pass_postfit_projy2_main->SetFrameBorderMode(0);
   Double_t xAxis452[2] = {50, 200}; 
   
   TH1D *data_obs_pass_postfit_projy2__288 = new TH1D("data_obs_pass_postfit_projy2__288","",1, xAxis452);
   data_obs_pass_postfit_projy2__288->SetMinimum(0);
   data_obs_pass_postfit_projy2__288->SetMaximum(0);

   Int_t ci;      // for color index setting
   TColor *color; // for color definition with alpha
   ci = TColor::GetColor("#000000");
   data_obs_pass_postfit_projy2__288->SetLineColor(ci);
   data_obs_pass_postfit_projy2__288->SetLineStyle(0);

   ci = TColor::GetColor("#000000");
   data_obs_pass_postfit_projy2__288->SetMarkerColor(ci);
   data_obs_pass_postfit_projy2__288->SetMarkerStyle(8);
   data_obs_pass_postfit_projy2__288->GetXaxis()->SetTitle("p_{T}");
   data_obs_pass_postfit_projy2__288->GetXaxis()->SetLabelFont(42);
   data_obs_pass_postfit_projy2__288->GetXaxis()->SetLabelOffset(0.05);
   data_obs_pass_postfit_projy2__288->GetXaxis()->SetLabelSize(0.07);
   data_obs_pass_postfit_projy2__288->GetXaxis()->SetTitleSize(0.09);
   data_obs_pass_postfit_projy2__288->GetXaxis()->SetTitleOffset(1.15);
   data_obs_pass_postfit_projy2__288->GetXaxis()->SetTitleFont(42);
   data_obs_pass_postfit_projy2__288->GetYaxis()->SetTitle("Events / bin");
   data_obs_pass_postfit_projy2__288->GetYaxis()->SetNdivisions(508);
   data_obs_pass_postfit_projy2__288->GetYaxis()->SetLabelFont(42);
   data_obs_pass_postfit_projy2__288->GetYaxis()->SetLabelOffset(0.007);
   data_obs_pass_postfit_projy2__288->GetYaxis()->SetLabelSize(0.07);
   data_obs_pass_postfit_projy2__288->GetYaxis()->SetTitleSize(0.09);
   data_obs_pass_postfit_projy2__288->GetYaxis()->SetTitleOffset(0.8);
   data_obs_pass_postfit_projy2__288->GetYaxis()->SetTitleFont(42);
   data_obs_pass_postfit_projy2__288->GetZaxis()->SetLabelFont(42);
   data_obs_pass_postfit_projy2__288->GetZaxis()->SetLabelOffset(0.007);
   data_obs_pass_postfit_projy2__288->GetZaxis()->SetLabelSize(0.05);
   data_obs_pass_postfit_projy2__288->GetZaxis()->SetTitleSize(0.08);
   data_obs_pass_postfit_projy2__288->GetZaxis()->SetTitleFont(42);
   data_obs_pass_postfit_projy2__288->Draw("pe X0");
   
   THStack *postfit_projy2_pass_stack = new THStack();
   postfit_projy2_pass_stack->SetName("postfit_projy2_pass_stack");
   postfit_projy2_pass_stack->SetTitle("postfit_projy2_pass_stack");
   Double_t xAxis453[2] = {50, 200}; 
   
   TH1F *postfit_projy2_pass_stack_stack_83 = new TH1F("postfit_projy2_pass_stack_stack_83","postfit_projy2_pass_stack",1, xAxis453);
   postfit_projy2_pass_stack_stack_83->SetMinimum(0);
   postfit_projy2_pass_stack_stack_83->SetMaximum(0);
   postfit_projy2_pass_stack_stack_83->SetDirectory(0);
   postfit_projy2_pass_stack_stack_83->SetStats(0);
   postfit_projy2_pass_stack_stack_83->SetLineStyle(0);
   postfit_projy2_pass_stack_stack_83->GetXaxis()->SetLabelFont(42);
   postfit_projy2_pass_stack_stack_83->GetXaxis()->SetLabelOffset(0.007);
   postfit_projy2_pass_stack_stack_83->GetXaxis()->SetLabelSize(0.05);
   postfit_projy2_pass_stack_stack_83->GetXaxis()->SetTitleSize(0.08);
   postfit_projy2_pass_stack_stack_83->GetXaxis()->SetTitleOffset(0.9);
   postfit_projy2_pass_stack_stack_83->GetXaxis()->SetTitleFont(42);
   postfit_projy2_pass_stack_stack_83->GetYaxis()->SetNdivisions(508);
   postfit_projy2_pass_stack_stack_83->GetYaxis()->SetLabelFont(42);
   postfit_projy2_pass_stack_stack_83->GetYaxis()->SetLabelOffset(0.007);
   postfit_projy2_pass_stack_stack_83->GetYaxis()->SetLabelSize(0.05);
   postfit_projy2_pass_stack_stack_83->GetYaxis()->SetTitleSize(0.08);
   postfit_projy2_pass_stack_stack_83->GetYaxis()->SetTitleOffset(1.25);
   postfit_projy2_pass_stack_stack_83->GetYaxis()->SetTitleFont(42);
   postfit_projy2_pass_stack_stack_83->GetZaxis()->SetLabelFont(42);
   postfit_projy2_pass_stack_stack_83->GetZaxis()->SetLabelOffset(0.007);
   postfit_projy2_pass_stack_stack_83->GetZaxis()->SetLabelSize(0.05);
   postfit_projy2_pass_stack_stack_83->GetZaxis()->SetTitleSize(0.08);
   postfit_projy2_pass_stack_stack_83->GetZaxis()->SetTitleFont(42);
   postfit_projy2_pass_stack->SetHistogram(postfit_projy2_pass_stack_stack_83);
   
   Double_t xAxis454[2] = {50, 200}; 
   
   TH1D *Background_0x0_pass_postfit_projy2_stack_1 = new TH1D("Background_0x0_pass_postfit_projy2_stack_1","Background, pass, postfit, 1.0-1.0",1, xAxis454);
   Background_0x0_pass_postfit_projy2_stack_1->SetMinimum(0);

   ci = TColor::GetColor("#ffff00");
   Background_0x0_pass_postfit_projy2_stack_1->SetFillColor(ci);

   ci = 1322;
   color = new TColor(ci, 1, 1, 1, " ", 0);
   Background_0x0_pass_postfit_projy2_stack_1->SetLineColor(ci);
   Background_0x0_pass_postfit_projy2_stack_1->SetLineStyle(0);
   Background_0x0_pass_postfit_projy2_stack_1->GetXaxis()->SetTitle("p_{T}");
   Background_0x0_pass_postfit_projy2_stack_1->GetXaxis()->SetLabelFont(42);
   Background_0x0_pass_postfit_projy2_stack_1->GetXaxis()->SetLabelOffset(0.007);
   Background_0x0_pass_postfit_projy2_stack_1->GetXaxis()->SetLabelSize(0.05);
   Background_0x0_pass_postfit_projy2_stack_1->GetXaxis()->SetTitleSize(0.08);
   Background_0x0_pass_postfit_projy2_stack_1->GetXaxis()->SetTitleOffset(1.25);
   Background_0x0_pass_postfit_projy2_stack_1->GetXaxis()->SetTitleFont(42);
   Background_0x0_pass_postfit_projy2_stack_1->GetYaxis()->SetTitle("Events / bin");
   Background_0x0_pass_postfit_projy2_stack_1->GetYaxis()->SetLabelFont(42);
   Background_0x0_pass_postfit_projy2_stack_1->GetYaxis()->SetLabelOffset(0.007);
   Background_0x0_pass_postfit_projy2_stack_1->GetYaxis()->SetLabelSize(0.05);
   Background_0x0_pass_postfit_projy2_stack_1->GetYaxis()->SetTitleSize(0.08);
   Background_0x0_pass_postfit_projy2_stack_1->GetYaxis()->SetTitleOffset(1.25);
   Background_0x0_pass_postfit_projy2_stack_1->GetYaxis()->SetTitleFont(42);
   Background_0x0_pass_postfit_projy2_stack_1->GetZaxis()->SetLabelFont(42);
   Background_0x0_pass_postfit_projy2_stack_1->GetZaxis()->SetLabelOffset(0.007);
   Background_0x0_pass_postfit_projy2_stack_1->GetZaxis()->SetLabelSize(0.05);
   Background_0x0_pass_postfit_projy2_stack_1->GetZaxis()->SetTitleSize(0.08);
   Background_0x0_pass_postfit_projy2_stack_1->GetZaxis()->SetTitleFont(42);
   postfit_projy2_pass_stack->Add(Background_0x0_pass_postfit_projy2_stack_1,"");
   postfit_projy2_pass_stack->Draw("hist same");
   
   postfit_projy2_pass_stack = new THStack();
   postfit_projy2_pass_stack->SetName("postfit_projy2_pass_stack");
   postfit_projy2_pass_stack->SetTitle("postfit_projy2_pass_stack");
   Double_t xAxis455[2] = {50, 200}; 
   
   TH1F *postfit_projy2_pass_stack_stack_83_stack_84 = new TH1F("postfit_projy2_pass_stack_stack_83_stack_84","postfit_projy2_pass_stack",1, xAxis455);
   postfit_projy2_pass_stack_stack_83_stack_84->SetMinimum(0);
   postfit_projy2_pass_stack_stack_83_stack_84->SetMaximum(0);
   postfit_projy2_pass_stack_stack_83_stack_84->SetDirectory(0);
   postfit_projy2_pass_stack_stack_83_stack_84->SetStats(0);
   postfit_projy2_pass_stack_stack_83_stack_84->SetLineStyle(0);
   postfit_projy2_pass_stack_stack_83_stack_84->GetXaxis()->SetLabelFont(42);
   postfit_projy2_pass_stack_stack_83_stack_84->GetXaxis()->SetLabelOffset(0.007);
   postfit_projy2_pass_stack_stack_83_stack_84->GetXaxis()->SetLabelSize(0.05);
   postfit_projy2_pass_stack_stack_83_stack_84->GetXaxis()->SetTitleSize(0.08);
   postfit_projy2_pass_stack_stack_83_stack_84->GetXaxis()->SetTitleOffset(0.9);
   postfit_projy2_pass_stack_stack_83_stack_84->GetXaxis()->SetTitleFont(42);
   postfit_projy2_pass_stack_stack_83_stack_84->GetYaxis()->SetNdivisions(508);
   postfit_projy2_pass_stack_stack_83_stack_84->GetYaxis()->SetLabelFont(42);
   postfit_projy2_pass_stack_stack_83_stack_84->GetYaxis()->SetLabelOffset(0.007);
   postfit_projy2_pass_stack_stack_83_stack_84->GetYaxis()->SetLabelSize(0.05);
   postfit_projy2_pass_stack_stack_83_stack_84->GetYaxis()->SetTitleSize(0.08);
   postfit_projy2_pass_stack_stack_83_stack_84->GetYaxis()->SetTitleOffset(1.25);
   postfit_projy2_pass_stack_stack_83_stack_84->GetYaxis()->SetTitleFont(42);
   postfit_projy2_pass_stack_stack_83_stack_84->GetZaxis()->SetLabelFont(42);
   postfit_projy2_pass_stack_stack_83_stack_84->GetZaxis()->SetLabelOffset(0.007);
   postfit_projy2_pass_stack_stack_83_stack_84->GetZaxis()->SetLabelSize(0.05);
   postfit_projy2_pass_stack_stack_83_stack_84->GetZaxis()->SetTitleSize(0.08);
   postfit_projy2_pass_stack_stack_83_stack_84->GetZaxis()->SetTitleFont(42);
   postfit_projy2_pass_stack->SetHistogram(postfit_projy2_pass_stack_stack_83_stack_84);
   
   Double_t xAxis456[2] = {50, 200}; 
   
   TH1D *Background_0x0_pass_postfit_projy2_stack_1_stack_1 = new TH1D("Background_0x0_pass_postfit_projy2_stack_1_stack_1","Background, pass, postfit, 1.0-1.0",1, xAxis456);
   Background_0x0_pass_postfit_projy2_stack_1_stack_1->SetMinimum(0);

   ci = TColor::GetColor("#ffff00");
   Background_0x0_pass_postfit_projy2_stack_1_stack_1->SetFillColor(ci);

   ci = 1322;
   color = new TColor(ci, 1, 1, 1, " ", 0);
   Background_0x0_pass_postfit_projy2_stack_1_stack_1->SetLineColor(ci);
   Background_0x0_pass_postfit_projy2_stack_1_stack_1->SetLineStyle(0);
   Background_0x0_pass_postfit_projy2_stack_1_stack_1->GetXaxis()->SetTitle("p_{T}");
   Background_0x0_pass_postfit_projy2_stack_1_stack_1->GetXaxis()->SetLabelFont(42);
   Background_0x0_pass_postfit_projy2_stack_1_stack_1->GetXaxis()->SetLabelOffset(0.007);
   Background_0x0_pass_postfit_projy2_stack_1_stack_1->GetXaxis()->SetLabelSize(0.05);
   Background_0x0_pass_postfit_projy2_stack_1_stack_1->GetXaxis()->SetTitleSize(0.08);
   Background_0x0_pass_postfit_projy2_stack_1_stack_1->GetXaxis()->SetTitleOffset(1.25);
   Background_0x0_pass_postfit_projy2_stack_1_stack_1->GetXaxis()->SetTitleFont(42);
   Background_0x0_pass_postfit_projy2_stack_1_stack_1->GetYaxis()->SetTitle("Events / bin");
   Background_0x0_pass_postfit_projy2_stack_1_stack_1->GetYaxis()->SetLabelFont(42);
   Background_0x0_pass_postfit_projy2_stack_1_stack_1->GetYaxis()->SetLabelOffset(0.007);
   Background_0x0_pass_postfit_projy2_stack_1_stack_1->GetYaxis()->SetLabelSize(0.05);
   Background_0x0_pass_postfit_projy2_stack_1_stack_1->GetYaxis()->SetTitleSize(0.08);
   Background_0x0_pass_postfit_projy2_stack_1_stack_1->GetYaxis()->SetTitleOffset(1.25);
   Background_0x0_pass_postfit_projy2_stack_1_stack_1->GetYaxis()->SetTitleFont(42);
   Background_0x0_pass_postfit_projy2_stack_1_stack_1->GetZaxis()->SetLabelFont(42);
   Background_0x0_pass_postfit_projy2_stack_1_stack_1->GetZaxis()->SetLabelOffset(0.007);
   Background_0x0_pass_postfit_projy2_stack_1_stack_1->GetZaxis()->SetLabelSize(0.05);
   Background_0x0_pass_postfit_projy2_stack_1_stack_1->GetZaxis()->SetTitleSize(0.08);
   Background_0x0_pass_postfit_projy2_stack_1_stack_1->GetZaxis()->SetTitleFont(42);
   postfit_projy2_pass_stack->Add(Background_0x0_pass_postfit_projy2_stack_1_stack_1,"");
   postfit_projy2_pass_stack->Draw("hist same");
   Double_t xAxis457[2] = {50, 200}; 
   
   TH1D *Signal_ppStaumI557_pass_postfit_projy2__289 = new TH1D("Signal_ppStaumI557_pass_postfit_projy2__289","HSCP signal, pass, postfit, 1.0-1.0",1, xAxis457);
   Signal_ppStaumI557_pass_postfit_projy2__289->SetMinimum(0);
   Signal_ppStaumI557_pass_postfit_projy2__289->SetLineColor(2);
   Signal_ppStaumI557_pass_postfit_projy2__289->SetLineStyle(0);
   Signal_ppStaumI557_pass_postfit_projy2__289->GetXaxis()->SetTitle("p_{T}");
   Signal_ppStaumI557_pass_postfit_projy2__289->GetXaxis()->SetLabelFont(42);
   Signal_ppStaumI557_pass_postfit_projy2__289->GetXaxis()->SetLabelOffset(0.007);
   Signal_ppStaumI557_pass_postfit_projy2__289->GetXaxis()->SetLabelSize(0.05);
   Signal_ppStaumI557_pass_postfit_projy2__289->GetXaxis()->SetTitleSize(0.08);
   Signal_ppStaumI557_pass_postfit_projy2__289->GetXaxis()->SetTitleOffset(1.25);
   Signal_ppStaumI557_pass_postfit_projy2__289->GetXaxis()->SetTitleFont(42);
   Signal_ppStaumI557_pass_postfit_projy2__289->GetYaxis()->SetTitle("Events / bin");
   Signal_ppStaumI557_pass_postfit_projy2__289->GetYaxis()->SetLabelFont(42);
   Signal_ppStaumI557_pass_postfit_projy2__289->GetYaxis()->SetLabelOffset(0.007);
   Signal_ppStaumI557_pass_postfit_projy2__289->GetYaxis()->SetLabelSize(0.05);
   Signal_ppStaumI557_pass_postfit_projy2__289->GetYaxis()->SetTitleSize(0.08);
   Signal_ppStaumI557_pass_postfit_projy2__289->GetYaxis()->SetTitleOffset(1.25);
   Signal_ppStaumI557_pass_postfit_projy2__289->GetYaxis()->SetTitleFont(42);
   Signal_ppStaumI557_pass_postfit_projy2__289->GetZaxis()->SetLabelFont(42);
   Signal_ppStaumI557_pass_postfit_projy2__289->GetZaxis()->SetLabelOffset(0.007);
   Signal_ppStaumI557_pass_postfit_projy2__289->GetZaxis()->SetLabelSize(0.05);
   Signal_ppStaumI557_pass_postfit_projy2__289->GetZaxis()->SetTitleSize(0.08);
   Signal_ppStaumI557_pass_postfit_projy2__289->GetZaxis()->SetTitleFont(42);
   Signal_ppStaumI557_pass_postfit_projy2__289->Draw("hist same");
   Double_t xAxis458[2] = {50, 200}; 
   
   TH1D *TotalBkg_pass_postfit_projy2__290 = new TH1D("TotalBkg_pass_postfit_projy2__290","TotalBkg, pass, postfit, 1.0-1.0",1, xAxis458);
   TotalBkg_pass_postfit_projy2__290->SetMinimum(0);
   TotalBkg_pass_postfit_projy2__290->SetLineStyle(0);
   TotalBkg_pass_postfit_projy2__290->SetMarkerStyle(0);
   TotalBkg_pass_postfit_projy2__290->GetXaxis()->SetTitle("p_{T}");
   TotalBkg_pass_postfit_projy2__290->GetXaxis()->SetLabelFont(42);
   TotalBkg_pass_postfit_projy2__290->GetXaxis()->SetLabelOffset(0.007);
   TotalBkg_pass_postfit_projy2__290->GetXaxis()->SetLabelSize(0.05);
   TotalBkg_pass_postfit_projy2__290->GetXaxis()->SetTitleSize(0.08);
   TotalBkg_pass_postfit_projy2__290->GetXaxis()->SetTitleOffset(1.25);
   TotalBkg_pass_postfit_projy2__290->GetXaxis()->SetTitleFont(42);
   TotalBkg_pass_postfit_projy2__290->GetYaxis()->SetTitle("Events / bin");
   TotalBkg_pass_postfit_projy2__290->GetYaxis()->SetLabelFont(42);
   TotalBkg_pass_postfit_projy2__290->GetYaxis()->SetLabelOffset(0.007);
   TotalBkg_pass_postfit_projy2__290->GetYaxis()->SetLabelSize(0.05);
   TotalBkg_pass_postfit_projy2__290->GetYaxis()->SetTitleSize(0.08);
   TotalBkg_pass_postfit_projy2__290->GetYaxis()->SetTitleOffset(1.25);
   TotalBkg_pass_postfit_projy2__290->GetYaxis()->SetTitleFont(42);
   TotalBkg_pass_postfit_projy2__290->GetZaxis()->SetLabelFont(42);
   TotalBkg_pass_postfit_projy2__290->GetZaxis()->SetLabelOffset(0.007);
   TotalBkg_pass_postfit_projy2__290->GetZaxis()->SetLabelSize(0.05);
   TotalBkg_pass_postfit_projy2__290->GetZaxis()->SetTitleSize(0.08);
   TotalBkg_pass_postfit_projy2__290->GetZaxis()->SetTitleFont(42);
   TotalBkg_pass_postfit_projy2__290->Draw("hist same");
   Double_t xAxis459[2] = {50, 200}; 
   
   TH1D *TotalBkg_pass_postfit_projy2__291 = new TH1D("TotalBkg_pass_postfit_projy2__291","TotalBkg, pass, postfit, 1.0-1.0",1, xAxis459);
   TotalBkg_pass_postfit_projy2__291->SetMinimum(0);
   TotalBkg_pass_postfit_projy2__291->SetFillColor(1);
   TotalBkg_pass_postfit_projy2__291->SetFillStyle(3354);
   TotalBkg_pass_postfit_projy2__291->SetLineStyle(0);
   TotalBkg_pass_postfit_projy2__291->SetLineWidth(0);
   TotalBkg_pass_postfit_projy2__291->SetMarkerStyle(0);
   TotalBkg_pass_postfit_projy2__291->GetXaxis()->SetTitle("p_{T}");
   TotalBkg_pass_postfit_projy2__291->GetXaxis()->SetLabelFont(42);
   TotalBkg_pass_postfit_projy2__291->GetXaxis()->SetLabelOffset(0.007);
   TotalBkg_pass_postfit_projy2__291->GetXaxis()->SetLabelSize(0.05);
   TotalBkg_pass_postfit_projy2__291->GetXaxis()->SetTitleSize(0.08);
   TotalBkg_pass_postfit_projy2__291->GetXaxis()->SetTitleOffset(1.25);
   TotalBkg_pass_postfit_projy2__291->GetXaxis()->SetTitleFont(42);
   TotalBkg_pass_postfit_projy2__291->GetYaxis()->SetTitle("Events / bin");
   TotalBkg_pass_postfit_projy2__291->GetYaxis()->SetLabelFont(42);
   TotalBkg_pass_postfit_projy2__291->GetYaxis()->SetLabelOffset(0.007);
   TotalBkg_pass_postfit_projy2__291->GetYaxis()->SetLabelSize(0.05);
   TotalBkg_pass_postfit_projy2__291->GetYaxis()->SetTitleSize(0.08);
   TotalBkg_pass_postfit_projy2__291->GetYaxis()->SetTitleOffset(1.25);
   TotalBkg_pass_postfit_projy2__291->GetYaxis()->SetTitleFont(42);
   TotalBkg_pass_postfit_projy2__291->GetZaxis()->SetLabelFont(42);
   TotalBkg_pass_postfit_projy2__291->GetZaxis()->SetLabelOffset(0.007);
   TotalBkg_pass_postfit_projy2__291->GetZaxis()->SetLabelSize(0.05);
   TotalBkg_pass_postfit_projy2__291->GetZaxis()->SetTitleSize(0.08);
   TotalBkg_pass_postfit_projy2__291->GetZaxis()->SetTitleFont(42);
   TotalBkg_pass_postfit_projy2__291->Draw("e2 same");
   Double_t xAxis460[2] = {50, 200}; 
   
   TH1D *data_obs_pass_postfit_projy2__292 = new TH1D("data_obs_pass_postfit_projy2__292","",1, xAxis460);
   data_obs_pass_postfit_projy2__292->SetMinimum(0);
   data_obs_pass_postfit_projy2__292->SetMaximum(0);

   ci = TColor::GetColor("#000000");
   data_obs_pass_postfit_projy2__292->SetLineColor(ci);
   data_obs_pass_postfit_projy2__292->SetLineStyle(0);

   ci = TColor::GetColor("#000000");
   data_obs_pass_postfit_projy2__292->SetMarkerColor(ci);
   data_obs_pass_postfit_projy2__292->SetMarkerStyle(8);
   data_obs_pass_postfit_projy2__292->GetXaxis()->SetTitle("p_{T}");
   data_obs_pass_postfit_projy2__292->GetXaxis()->SetLabelFont(42);
   data_obs_pass_postfit_projy2__292->GetXaxis()->SetLabelOffset(0.05);
   data_obs_pass_postfit_projy2__292->GetXaxis()->SetLabelSize(0.07);
   data_obs_pass_postfit_projy2__292->GetXaxis()->SetTitleSize(0.09);
   data_obs_pass_postfit_projy2__292->GetXaxis()->SetTitleOffset(1.15);
   data_obs_pass_postfit_projy2__292->GetXaxis()->SetTitleFont(42);
   data_obs_pass_postfit_projy2__292->GetYaxis()->SetTitle("Events / bin");
   data_obs_pass_postfit_projy2__292->GetYaxis()->SetNdivisions(508);
   data_obs_pass_postfit_projy2__292->GetYaxis()->SetLabelFont(42);
   data_obs_pass_postfit_projy2__292->GetYaxis()->SetLabelOffset(0.007);
   data_obs_pass_postfit_projy2__292->GetYaxis()->SetLabelSize(0.07);
   data_obs_pass_postfit_projy2__292->GetYaxis()->SetTitleSize(0.09);
   data_obs_pass_postfit_projy2__292->GetYaxis()->SetTitleOffset(0.8);
   data_obs_pass_postfit_projy2__292->GetYaxis()->SetTitleFont(42);
   data_obs_pass_postfit_projy2__292->GetZaxis()->SetLabelFont(42);
   data_obs_pass_postfit_projy2__292->GetZaxis()->SetLabelOffset(0.007);
   data_obs_pass_postfit_projy2__292->GetZaxis()->SetLabelSize(0.05);
   data_obs_pass_postfit_projy2__292->GetZaxis()->SetTitleSize(0.08);
   data_obs_pass_postfit_projy2__292->GetZaxis()->SetTitleFont(42);
   data_obs_pass_postfit_projy2__292->Draw("pe X0 same");
   
   TLegend *leg = new TLegend(0.65,0.64,0.9,0.88,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(1001);
   TLegendEntry *entry=leg->AddEntry("data_obs_pass_postfit_projy2","Data","pe X0");

   ci = TColor::GetColor("#000000");
   entry->SetLineColor(ci);
   entry->SetLineWidth(1);

   ci = TColor::GetColor("#000000");
   entry->SetMarkerColor(ci);
   entry->SetMarkerStyle(8);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("TotalBkg_pass_postfit_projy2","Total bkg unc.","F");
   entry->SetFillColor(1);
   entry->SetFillStyle(3354);
   entry->SetLineColor(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("Signal_ppStau-557_pass_postfit_projy2","HSCP signal","L");
   entry->SetLineColor(2);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("Background_0x0_pass_postfit_projy2_stack_1_stack_1","Background","f");

   ci = TColor::GetColor("#ffff00");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = 1322;
   color = new TColor(ci, 1, 1, 1, " ", 0);
   entry->SetLineColor(ci);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   leg->Draw();
   Double_t xAxis461[2] = {50, 200}; 
   
   TH1D *data_obs_pass_postfit_projy2_copy__293 = new TH1D("data_obs_pass_postfit_projy2_copy__293","",1, xAxis461);
   data_obs_pass_postfit_projy2_copy__293->SetMinimum(0);
   data_obs_pass_postfit_projy2_copy__293->SetMaximum(0);
   data_obs_pass_postfit_projy2_copy__293->SetDirectory(0);

   ci = TColor::GetColor("#000000");
   data_obs_pass_postfit_projy2_copy__293->SetLineColor(ci);
   data_obs_pass_postfit_projy2_copy__293->SetLineStyle(0);

   ci = TColor::GetColor("#000000");
   data_obs_pass_postfit_projy2_copy__293->SetMarkerColor(ci);
   data_obs_pass_postfit_projy2_copy__293->SetMarkerStyle(8);
   data_obs_pass_postfit_projy2_copy__293->GetXaxis()->SetTitle("p_{T}");
   data_obs_pass_postfit_projy2_copy__293->GetXaxis()->SetLabelFont(42);
   data_obs_pass_postfit_projy2_copy__293->GetXaxis()->SetLabelOffset(0.05);
   data_obs_pass_postfit_projy2_copy__293->GetXaxis()->SetLabelSize(0.07);
   data_obs_pass_postfit_projy2_copy__293->GetXaxis()->SetTitleSize(0.09);
   data_obs_pass_postfit_projy2_copy__293->GetXaxis()->SetTitleOffset(1.15);
   data_obs_pass_postfit_projy2_copy__293->GetXaxis()->SetTitleFont(42);
   data_obs_pass_postfit_projy2_copy__293->GetYaxis()->SetTitle("Events / bin");
   data_obs_pass_postfit_projy2_copy__293->GetYaxis()->SetNdivisions(508);
   data_obs_pass_postfit_projy2_copy__293->GetYaxis()->SetLabelFont(42);
   data_obs_pass_postfit_projy2_copy__293->GetYaxis()->SetLabelOffset(0.007);
   data_obs_pass_postfit_projy2_copy__293->GetYaxis()->SetLabelSize(0.07);
   data_obs_pass_postfit_projy2_copy__293->GetYaxis()->SetTitleSize(0.09);
   data_obs_pass_postfit_projy2_copy__293->GetYaxis()->SetTitleOffset(0.8);
   data_obs_pass_postfit_projy2_copy__293->GetYaxis()->SetTitleFont(42);
   data_obs_pass_postfit_projy2_copy__293->GetZaxis()->SetLabelFont(42);
   data_obs_pass_postfit_projy2_copy__293->GetZaxis()->SetLabelOffset(0.007);
   data_obs_pass_postfit_projy2_copy__293->GetZaxis()->SetLabelSize(0.05);
   data_obs_pass_postfit_projy2_copy__293->GetZaxis()->SetTitleSize(0.08);
   data_obs_pass_postfit_projy2_copy__293->GetZaxis()->SetTitleFont(42);
   data_obs_pass_postfit_projy2_copy__293->Draw("sameaxis");
   TLatex *   tex = new TLatex(0.21,0.83,"55 < p_{T} < 200 GeV, F^{Pixels}_{i} > 0.9");
tex->SetNDC();
   tex->SetTextAlign(12);
   tex->SetTextFont(42);
   tex->SetTextSize(0.06);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.17,0.92,"CMS");
tex->SetNDC();
   tex->SetTextFont(61);
   tex->SetTextSize(0.0675);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.25,0.92,"Preliminary");
tex->SetNDC();
   tex->SetTextFont(52);
   tex->SetTextSize(0.0485);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.95,0.92,"101 fb^{-1} (13 TeV)");
tex->SetNDC();
   tex->SetTextAlign(31);
   tex->SetTextFont(42);
   tex->SetTextSize(0.07);
   tex->SetLineWidth(2);
   tex->Draw();
   data_obs_pass_postfit_projy2_main->Modified();
   plots_fit_s/base_figs/postfit_projy2_pass->cd();
  
// ------------>Primitives in pad: data_obs_pass_postfit_projy2_sub
   TPad *data_obs_pass_postfit_projy2_sub = new TPad("data_obs_pass_postfit_projy2_sub", "data_obs_pass_postfit_projy2_sub",0,0,1,0.35);
   data_obs_pass_postfit_projy2_sub->Draw();
   data_obs_pass_postfit_projy2_sub->cd();
   data_obs_pass_postfit_projy2_sub->Range(17.30769,-6.023077,209.6154,2.9);
   data_obs_pass_postfit_projy2_sub->SetFillColor(0);
   data_obs_pass_postfit_projy2_sub->SetBorderMode(0);
   data_obs_pass_postfit_projy2_sub->SetBorderSize(2);
   data_obs_pass_postfit_projy2_sub->SetTickx(1);
   data_obs_pass_postfit_projy2_sub->SetTicky(1);
   data_obs_pass_postfit_projy2_sub->SetLeftMargin(0.17);
   data_obs_pass_postfit_projy2_sub->SetRightMargin(0.05);
   data_obs_pass_postfit_projy2_sub->SetTopMargin(0);
   data_obs_pass_postfit_projy2_sub->SetBottomMargin(0.35);
   data_obs_pass_postfit_projy2_sub->SetFrameFillStyle(0);
   data_obs_pass_postfit_projy2_sub->SetFrameBorderMode(0);
   data_obs_pass_postfit_projy2_sub->SetFrameFillStyle(0);
   data_obs_pass_postfit_projy2_sub->SetFrameBorderMode(0);
   Double_t xAxis462[2] = {50, 200}; 
   
   TH1D *data_obs_pass_postfit_projy2_pull__294 = new TH1D("data_obs_pass_postfit_projy2_pull__294","",1, xAxis462);
   data_obs_pass_postfit_projy2_pull__294->SetMinimum(-2.9);
   data_obs_pass_postfit_projy2_pull__294->SetMaximum(2.9);
   data_obs_pass_postfit_projy2_pull__294->SetEntries(2);
   data_obs_pass_postfit_projy2_pull__294->SetStats(0);

   ci = TColor::GetColor("#0000ff");
   data_obs_pass_postfit_projy2_pull__294->SetFillColor(ci);

   ci = TColor::GetColor("#000000");
   data_obs_pass_postfit_projy2_pull__294->SetLineColor(ci);
   data_obs_pass_postfit_projy2_pull__294->SetLineStyle(0);

   ci = TColor::GetColor("#000000");
   data_obs_pass_postfit_projy2_pull__294->SetMarkerColor(ci);
   data_obs_pass_postfit_projy2_pull__294->SetMarkerStyle(8);
   data_obs_pass_postfit_projy2_pull__294->GetXaxis()->SetTitle("p_{T}");
   data_obs_pass_postfit_projy2_pull__294->GetXaxis()->SetLabelFont(42);
   data_obs_pass_postfit_projy2_pull__294->GetXaxis()->SetLabelOffset(0.05);
   data_obs_pass_postfit_projy2_pull__294->GetXaxis()->SetLabelSize(0.13);
   data_obs_pass_postfit_projy2_pull__294->GetXaxis()->SetTitleSize(0.15);
   data_obs_pass_postfit_projy2_pull__294->GetXaxis()->SetTitleOffset(1.15);
   data_obs_pass_postfit_projy2_pull__294->GetXaxis()->SetTitleFont(42);
   data_obs_pass_postfit_projy2_pull__294->GetYaxis()->SetTitle("(Data-Bkg)/#sigma");
   data_obs_pass_postfit_projy2_pull__294->GetYaxis()->SetNdivisions(306);
   data_obs_pass_postfit_projy2_pull__294->GetYaxis()->SetLabelFont(42);
   data_obs_pass_postfit_projy2_pull__294->GetYaxis()->SetLabelOffset(0.007);
   data_obs_pass_postfit_projy2_pull__294->GetYaxis()->SetLabelSize(0.13);
   data_obs_pass_postfit_projy2_pull__294->GetYaxis()->SetTitleSize(0.12);
   data_obs_pass_postfit_projy2_pull__294->GetYaxis()->SetTitleOffset(0.4);
   data_obs_pass_postfit_projy2_pull__294->GetYaxis()->SetTitleFont(42);
   data_obs_pass_postfit_projy2_pull__294->GetZaxis()->SetLabelFont(42);
   data_obs_pass_postfit_projy2_pull__294->GetZaxis()->SetLabelOffset(0.007);
   data_obs_pass_postfit_projy2_pull__294->GetZaxis()->SetLabelSize(0.05);
   data_obs_pass_postfit_projy2_pull__294->GetZaxis()->SetTitleSize(0.08);
   data_obs_pass_postfit_projy2_pull__294->GetZaxis()->SetTitleFont(42);
   data_obs_pass_postfit_projy2_pull__294->Draw("hist");
   data_obs_pass_postfit_projy2_sub->Modified();
   plots_fit_s/base_figs/postfit_projy2_pass->cd();
   plots_fit_s/base_figs/postfit_projy2_pass->Modified();
   plots_fit_s/base_figs/postfit_projy2_pass->cd();
   plots_fit_s/base_figs/postfit_projy2_pass->SetSelected(plots_fit_s/base_figs/postfit_projy2_pass);
}
