void postfit_projx1_fail()
{
//=========Macro generated from canvas: plots_fit_s/base_figs/postfit_projx1_fail/plots_fit_s/base_figs/postfit_projx1_fail
//=========  (Fri Jan 12 21:00:08 2024) by ROOT version 6.14/09
   TCanvas *plots_fit_s/base_figs/postfit_projx1_fail = new TCanvas("plots_fit_s/base_figs/postfit_projx1_fail", "plots_fit_s/base_figs/postfit_projx1_fail",0,0,800,700);
   gStyle->SetOptFit(1);
   gStyle->SetOptStat(0);
   plots_fit_s/base_figs/postfit_projx1_fail->SetHighLightColor(2);
   plots_fit_s/base_figs/postfit_projx1_fail->Range(0,0,1,1);
   plots_fit_s/base_figs/postfit_projx1_fail->SetFillColor(0);
   plots_fit_s/base_figs/postfit_projx1_fail->SetBorderMode(0);
   plots_fit_s/base_figs/postfit_projx1_fail->SetBorderSize(2);
   plots_fit_s/base_figs/postfit_projx1_fail->SetTickx(1);
   plots_fit_s/base_figs/postfit_projx1_fail->SetTicky(1);
   plots_fit_s/base_figs/postfit_projx1_fail->SetLeftMargin(0.16);
   plots_fit_s/base_figs/postfit_projx1_fail->SetRightMargin(0);
   plots_fit_s/base_figs/postfit_projx1_fail->SetTopMargin(0);
   plots_fit_s/base_figs/postfit_projx1_fail->SetBottomMargin(0);
   plots_fit_s/base_figs/postfit_projx1_fail->SetFrameFillStyle(0);
   plots_fit_s/base_figs/postfit_projx1_fail->SetFrameBorderMode(0);
  
// ------------>Primitives in pad: data_obs_fail_postfit_projx1_main
   TPad *data_obs_fail_postfit_projx1_main = new TPad("data_obs_fail_postfit_projx1_main", "data_obs_fail_postfit_projx1_main",0,0.35,1,1);
   data_obs_fail_postfit_projx1_main->Draw();
   data_obs_fail_postfit_projx1_main->cd();
   data_obs_fail_postfit_projx1_main->Range(-0.2179487,-0.04651163,1.064103,1.116279);
   data_obs_fail_postfit_projx1_main->SetFillColor(0);
   data_obs_fail_postfit_projx1_main->SetBorderMode(0);
   data_obs_fail_postfit_projx1_main->SetBorderSize(2);
   data_obs_fail_postfit_projx1_main->SetTickx(1);
   data_obs_fail_postfit_projx1_main->SetTicky(1);
   data_obs_fail_postfit_projx1_main->SetLeftMargin(0.17);
   data_obs_fail_postfit_projx1_main->SetRightMargin(0.05);
   data_obs_fail_postfit_projx1_main->SetBottomMargin(0.04);
   data_obs_fail_postfit_projx1_main->SetFrameFillStyle(0);
   data_obs_fail_postfit_projx1_main->SetFrameBorderMode(0);
   data_obs_fail_postfit_projx1_main->SetFrameFillStyle(0);
   data_obs_fail_postfit_projx1_main->SetFrameBorderMode(0);
   Double_t xAxis276[10] = {0, 0.04, 0.08, 0.12, 0.16, 0.2, 0.24, 0.28, 0.32, 1}; 
   
   TH1D *data_obs_fail_postfit_projx1__176 = new TH1D("data_obs_fail_postfit_projx1__176","",9, xAxis276);
   data_obs_fail_postfit_projx1__176->SetMinimum(0);
   data_obs_fail_postfit_projx1__176->SetMaximum(0);

   Int_t ci;      // for color index setting
   TColor *color; // for color definition with alpha
   ci = TColor::GetColor("#000000");
   data_obs_fail_postfit_projx1__176->SetLineColor(ci);
   data_obs_fail_postfit_projx1__176->SetLineStyle(0);

   ci = TColor::GetColor("#000000");
   data_obs_fail_postfit_projx1__176->SetMarkerColor(ci);
   data_obs_fail_postfit_projx1__176->SetMarkerStyle(8);
   data_obs_fail_postfit_projx1__176->GetXaxis()->SetTitle("G_{i}^{Strips}");
   data_obs_fail_postfit_projx1__176->GetXaxis()->SetLabelFont(42);
   data_obs_fail_postfit_projx1__176->GetXaxis()->SetLabelOffset(0.05);
   data_obs_fail_postfit_projx1__176->GetXaxis()->SetLabelSize(0.07);
   data_obs_fail_postfit_projx1__176->GetXaxis()->SetTitleSize(0.09);
   data_obs_fail_postfit_projx1__176->GetXaxis()->SetTitleOffset(1.15);
   data_obs_fail_postfit_projx1__176->GetXaxis()->SetTitleFont(42);
   data_obs_fail_postfit_projx1__176->GetYaxis()->SetTitle("Events / bin");
   data_obs_fail_postfit_projx1__176->GetYaxis()->SetNdivisions(508);
   data_obs_fail_postfit_projx1__176->GetYaxis()->SetLabelFont(42);
   data_obs_fail_postfit_projx1__176->GetYaxis()->SetLabelOffset(0.007);
   data_obs_fail_postfit_projx1__176->GetYaxis()->SetLabelSize(0.07);
   data_obs_fail_postfit_projx1__176->GetYaxis()->SetTitleSize(0.09);
   data_obs_fail_postfit_projx1__176->GetYaxis()->SetTitleOffset(0.8);
   data_obs_fail_postfit_projx1__176->GetYaxis()->SetTitleFont(42);
   data_obs_fail_postfit_projx1__176->GetZaxis()->SetLabelFont(42);
   data_obs_fail_postfit_projx1__176->GetZaxis()->SetLabelOffset(0.007);
   data_obs_fail_postfit_projx1__176->GetZaxis()->SetLabelSize(0.05);
   data_obs_fail_postfit_projx1__176->GetZaxis()->SetTitleSize(0.08);
   data_obs_fail_postfit_projx1__176->GetZaxis()->SetTitleFont(42);
   data_obs_fail_postfit_projx1__176->Draw("pe X0");
   
   THStack *postfit_projx1_fail_stack = new THStack();
   postfit_projx1_fail_stack->SetName("postfit_projx1_fail_stack");
   postfit_projx1_fail_stack->SetTitle("postfit_projx1_fail_stack");
   Double_t xAxis277[10] = {0, 0.04, 0.08, 0.12, 0.16, 0.2, 0.24, 0.28, 0.32, 1}; 
   
   TH1F *postfit_projx1_fail_stack_stack_51 = new TH1F("postfit_projx1_fail_stack_stack_51","postfit_projx1_fail_stack",9, xAxis277);
   postfit_projx1_fail_stack_stack_51->SetMinimum(0);
   postfit_projx1_fail_stack_stack_51->SetMaximum(0);
   postfit_projx1_fail_stack_stack_51->SetDirectory(0);
   postfit_projx1_fail_stack_stack_51->SetStats(0);
   postfit_projx1_fail_stack_stack_51->SetLineStyle(0);
   postfit_projx1_fail_stack_stack_51->GetXaxis()->SetLabelFont(42);
   postfit_projx1_fail_stack_stack_51->GetXaxis()->SetLabelOffset(0.007);
   postfit_projx1_fail_stack_stack_51->GetXaxis()->SetLabelSize(0.05);
   postfit_projx1_fail_stack_stack_51->GetXaxis()->SetTitleSize(0.08);
   postfit_projx1_fail_stack_stack_51->GetXaxis()->SetTitleOffset(0.9);
   postfit_projx1_fail_stack_stack_51->GetXaxis()->SetTitleFont(42);
   postfit_projx1_fail_stack_stack_51->GetYaxis()->SetNdivisions(508);
   postfit_projx1_fail_stack_stack_51->GetYaxis()->SetLabelFont(42);
   postfit_projx1_fail_stack_stack_51->GetYaxis()->SetLabelOffset(0.007);
   postfit_projx1_fail_stack_stack_51->GetYaxis()->SetLabelSize(0.05);
   postfit_projx1_fail_stack_stack_51->GetYaxis()->SetTitleSize(0.08);
   postfit_projx1_fail_stack_stack_51->GetYaxis()->SetTitleOffset(1.25);
   postfit_projx1_fail_stack_stack_51->GetYaxis()->SetTitleFont(42);
   postfit_projx1_fail_stack_stack_51->GetZaxis()->SetLabelFont(42);
   postfit_projx1_fail_stack_stack_51->GetZaxis()->SetLabelOffset(0.007);
   postfit_projx1_fail_stack_stack_51->GetZaxis()->SetLabelSize(0.05);
   postfit_projx1_fail_stack_stack_51->GetZaxis()->SetTitleSize(0.08);
   postfit_projx1_fail_stack_stack_51->GetZaxis()->SetTitleFont(42);
   postfit_projx1_fail_stack->SetHistogram(postfit_projx1_fail_stack_stack_51);
   
   Double_t xAxis278[10] = {0, 0.04, 0.08, 0.12, 0.16, 0.2, 0.24, 0.28, 0.32, 1}; 
   
   TH1D *Background_fail_postfit_projx1_stack_1 = new TH1D("Background_fail_postfit_projx1_stack_1","Background, fail, postfit, 50-50",9, xAxis278);
   Background_fail_postfit_projx1_stack_1->SetMinimum(0);

   ci = TColor::GetColor("#ffff00");
   Background_fail_postfit_projx1_stack_1->SetFillColor(ci);

   ci = 1306;
   color = new TColor(ci, 1, 1, 1, " ", 0);
   Background_fail_postfit_projx1_stack_1->SetLineColor(ci);
   Background_fail_postfit_projx1_stack_1->SetLineStyle(0);
   Background_fail_postfit_projx1_stack_1->GetXaxis()->SetTitle("G_{i}^{Strips}");
   Background_fail_postfit_projx1_stack_1->GetXaxis()->SetLabelFont(42);
   Background_fail_postfit_projx1_stack_1->GetXaxis()->SetLabelOffset(0.007);
   Background_fail_postfit_projx1_stack_1->GetXaxis()->SetLabelSize(0.05);
   Background_fail_postfit_projx1_stack_1->GetXaxis()->SetTitleSize(0.08);
   Background_fail_postfit_projx1_stack_1->GetXaxis()->SetTitleOffset(0.9);
   Background_fail_postfit_projx1_stack_1->GetXaxis()->SetTitleFont(42);
   Background_fail_postfit_projx1_stack_1->GetYaxis()->SetTitle("Events / bin");
   Background_fail_postfit_projx1_stack_1->GetYaxis()->SetLabelFont(42);
   Background_fail_postfit_projx1_stack_1->GetYaxis()->SetLabelOffset(0.007);
   Background_fail_postfit_projx1_stack_1->GetYaxis()->SetLabelSize(0.05);
   Background_fail_postfit_projx1_stack_1->GetYaxis()->SetTitleSize(0.08);
   Background_fail_postfit_projx1_stack_1->GetYaxis()->SetTitleOffset(1.25);
   Background_fail_postfit_projx1_stack_1->GetYaxis()->SetTitleFont(42);
   Background_fail_postfit_projx1_stack_1->GetZaxis()->SetLabelFont(42);
   Background_fail_postfit_projx1_stack_1->GetZaxis()->SetLabelOffset(0.007);
   Background_fail_postfit_projx1_stack_1->GetZaxis()->SetLabelSize(0.05);
   Background_fail_postfit_projx1_stack_1->GetZaxis()->SetTitleSize(0.08);
   Background_fail_postfit_projx1_stack_1->GetZaxis()->SetTitleFont(42);
   postfit_projx1_fail_stack->Add(Background_fail_postfit_projx1_stack_1,"");
   postfit_projx1_fail_stack->Draw("hist same");
   
   postfit_projx1_fail_stack = new THStack();
   postfit_projx1_fail_stack->SetName("postfit_projx1_fail_stack");
   postfit_projx1_fail_stack->SetTitle("postfit_projx1_fail_stack");
   Double_t xAxis279[10] = {0, 0.04, 0.08, 0.12, 0.16, 0.2, 0.24, 0.28, 0.32, 1}; 
   
   TH1F *postfit_projx1_fail_stack_stack_51_stack_52 = new TH1F("postfit_projx1_fail_stack_stack_51_stack_52","postfit_projx1_fail_stack",9, xAxis279);
   postfit_projx1_fail_stack_stack_51_stack_52->SetMinimum(0);
   postfit_projx1_fail_stack_stack_51_stack_52->SetMaximum(0);
   postfit_projx1_fail_stack_stack_51_stack_52->SetDirectory(0);
   postfit_projx1_fail_stack_stack_51_stack_52->SetStats(0);
   postfit_projx1_fail_stack_stack_51_stack_52->SetLineStyle(0);
   postfit_projx1_fail_stack_stack_51_stack_52->GetXaxis()->SetLabelFont(42);
   postfit_projx1_fail_stack_stack_51_stack_52->GetXaxis()->SetLabelOffset(0.007);
   postfit_projx1_fail_stack_stack_51_stack_52->GetXaxis()->SetLabelSize(0.05);
   postfit_projx1_fail_stack_stack_51_stack_52->GetXaxis()->SetTitleSize(0.08);
   postfit_projx1_fail_stack_stack_51_stack_52->GetXaxis()->SetTitleOffset(0.9);
   postfit_projx1_fail_stack_stack_51_stack_52->GetXaxis()->SetTitleFont(42);
   postfit_projx1_fail_stack_stack_51_stack_52->GetYaxis()->SetNdivisions(508);
   postfit_projx1_fail_stack_stack_51_stack_52->GetYaxis()->SetLabelFont(42);
   postfit_projx1_fail_stack_stack_51_stack_52->GetYaxis()->SetLabelOffset(0.007);
   postfit_projx1_fail_stack_stack_51_stack_52->GetYaxis()->SetLabelSize(0.05);
   postfit_projx1_fail_stack_stack_51_stack_52->GetYaxis()->SetTitleSize(0.08);
   postfit_projx1_fail_stack_stack_51_stack_52->GetYaxis()->SetTitleOffset(1.25);
   postfit_projx1_fail_stack_stack_51_stack_52->GetYaxis()->SetTitleFont(42);
   postfit_projx1_fail_stack_stack_51_stack_52->GetZaxis()->SetLabelFont(42);
   postfit_projx1_fail_stack_stack_51_stack_52->GetZaxis()->SetLabelOffset(0.007);
   postfit_projx1_fail_stack_stack_51_stack_52->GetZaxis()->SetLabelSize(0.05);
   postfit_projx1_fail_stack_stack_51_stack_52->GetZaxis()->SetTitleSize(0.08);
   postfit_projx1_fail_stack_stack_51_stack_52->GetZaxis()->SetTitleFont(42);
   postfit_projx1_fail_stack->SetHistogram(postfit_projx1_fail_stack_stack_51_stack_52);
   
   Double_t xAxis280[10] = {0, 0.04, 0.08, 0.12, 0.16, 0.2, 0.24, 0.28, 0.32, 1}; 
   
   TH1D *Background_fail_postfit_projx1_stack_1_stack_1 = new TH1D("Background_fail_postfit_projx1_stack_1_stack_1","Background, fail, postfit, 50-50",9, xAxis280);
   Background_fail_postfit_projx1_stack_1_stack_1->SetMinimum(0);

   ci = TColor::GetColor("#ffff00");
   Background_fail_postfit_projx1_stack_1_stack_1->SetFillColor(ci);

   ci = 1306;
   color = new TColor(ci, 1, 1, 1, " ", 0);
   Background_fail_postfit_projx1_stack_1_stack_1->SetLineColor(ci);
   Background_fail_postfit_projx1_stack_1_stack_1->SetLineStyle(0);
   Background_fail_postfit_projx1_stack_1_stack_1->GetXaxis()->SetTitle("G_{i}^{Strips}");
   Background_fail_postfit_projx1_stack_1_stack_1->GetXaxis()->SetLabelFont(42);
   Background_fail_postfit_projx1_stack_1_stack_1->GetXaxis()->SetLabelOffset(0.007);
   Background_fail_postfit_projx1_stack_1_stack_1->GetXaxis()->SetLabelSize(0.05);
   Background_fail_postfit_projx1_stack_1_stack_1->GetXaxis()->SetTitleSize(0.08);
   Background_fail_postfit_projx1_stack_1_stack_1->GetXaxis()->SetTitleOffset(0.9);
   Background_fail_postfit_projx1_stack_1_stack_1->GetXaxis()->SetTitleFont(42);
   Background_fail_postfit_projx1_stack_1_stack_1->GetYaxis()->SetTitle("Events / bin");
   Background_fail_postfit_projx1_stack_1_stack_1->GetYaxis()->SetLabelFont(42);
   Background_fail_postfit_projx1_stack_1_stack_1->GetYaxis()->SetLabelOffset(0.007);
   Background_fail_postfit_projx1_stack_1_stack_1->GetYaxis()->SetLabelSize(0.05);
   Background_fail_postfit_projx1_stack_1_stack_1->GetYaxis()->SetTitleSize(0.08);
   Background_fail_postfit_projx1_stack_1_stack_1->GetYaxis()->SetTitleOffset(1.25);
   Background_fail_postfit_projx1_stack_1_stack_1->GetYaxis()->SetTitleFont(42);
   Background_fail_postfit_projx1_stack_1_stack_1->GetZaxis()->SetLabelFont(42);
   Background_fail_postfit_projx1_stack_1_stack_1->GetZaxis()->SetLabelOffset(0.007);
   Background_fail_postfit_projx1_stack_1_stack_1->GetZaxis()->SetLabelSize(0.05);
   Background_fail_postfit_projx1_stack_1_stack_1->GetZaxis()->SetTitleSize(0.08);
   Background_fail_postfit_projx1_stack_1_stack_1->GetZaxis()->SetTitleFont(42);
   postfit_projx1_fail_stack->Add(Background_fail_postfit_projx1_stack_1_stack_1,"");
   postfit_projx1_fail_stack->Draw("hist same");
   Double_t xAxis281[10] = {0, 0.04, 0.08, 0.12, 0.16, 0.2, 0.24, 0.28, 0.32, 1}; 
   
   TH1D *Signal_ppStaumI557_fail_postfit_projx1__177 = new TH1D("Signal_ppStaumI557_fail_postfit_projx1__177","HSCP signal, fail, postfit, 50-50",9, xAxis281);
   Signal_ppStaumI557_fail_postfit_projx1__177->SetMinimum(0);
   Signal_ppStaumI557_fail_postfit_projx1__177->SetLineColor(2);
   Signal_ppStaumI557_fail_postfit_projx1__177->SetLineStyle(0);
   Signal_ppStaumI557_fail_postfit_projx1__177->GetXaxis()->SetTitle("G_{i}^{Strips}");
   Signal_ppStaumI557_fail_postfit_projx1__177->GetXaxis()->SetLabelFont(42);
   Signal_ppStaumI557_fail_postfit_projx1__177->GetXaxis()->SetLabelOffset(0.007);
   Signal_ppStaumI557_fail_postfit_projx1__177->GetXaxis()->SetLabelSize(0.05);
   Signal_ppStaumI557_fail_postfit_projx1__177->GetXaxis()->SetTitleSize(0.08);
   Signal_ppStaumI557_fail_postfit_projx1__177->GetXaxis()->SetTitleOffset(0.9);
   Signal_ppStaumI557_fail_postfit_projx1__177->GetXaxis()->SetTitleFont(42);
   Signal_ppStaumI557_fail_postfit_projx1__177->GetYaxis()->SetTitle("Events / bin");
   Signal_ppStaumI557_fail_postfit_projx1__177->GetYaxis()->SetLabelFont(42);
   Signal_ppStaumI557_fail_postfit_projx1__177->GetYaxis()->SetLabelOffset(0.007);
   Signal_ppStaumI557_fail_postfit_projx1__177->GetYaxis()->SetLabelSize(0.05);
   Signal_ppStaumI557_fail_postfit_projx1__177->GetYaxis()->SetTitleSize(0.08);
   Signal_ppStaumI557_fail_postfit_projx1__177->GetYaxis()->SetTitleOffset(1.25);
   Signal_ppStaumI557_fail_postfit_projx1__177->GetYaxis()->SetTitleFont(42);
   Signal_ppStaumI557_fail_postfit_projx1__177->GetZaxis()->SetLabelFont(42);
   Signal_ppStaumI557_fail_postfit_projx1__177->GetZaxis()->SetLabelOffset(0.007);
   Signal_ppStaumI557_fail_postfit_projx1__177->GetZaxis()->SetLabelSize(0.05);
   Signal_ppStaumI557_fail_postfit_projx1__177->GetZaxis()->SetTitleSize(0.08);
   Signal_ppStaumI557_fail_postfit_projx1__177->GetZaxis()->SetTitleFont(42);
   Signal_ppStaumI557_fail_postfit_projx1__177->Draw("hist same");
   Double_t xAxis282[10] = {0, 0.04, 0.08, 0.12, 0.16, 0.2, 0.24, 0.28, 0.32, 1}; 
   
   TH1D *TotalBkg_fail_postfit_projx1__178 = new TH1D("TotalBkg_fail_postfit_projx1__178","TotalBkg, fail, postfit, 50-50",9, xAxis282);
   TotalBkg_fail_postfit_projx1__178->SetMinimum(0);
   TotalBkg_fail_postfit_projx1__178->SetLineStyle(0);
   TotalBkg_fail_postfit_projx1__178->SetMarkerStyle(0);
   TotalBkg_fail_postfit_projx1__178->GetXaxis()->SetTitle("G_{i}^{Strips}");
   TotalBkg_fail_postfit_projx1__178->GetXaxis()->SetLabelFont(42);
   TotalBkg_fail_postfit_projx1__178->GetXaxis()->SetLabelOffset(0.007);
   TotalBkg_fail_postfit_projx1__178->GetXaxis()->SetLabelSize(0.05);
   TotalBkg_fail_postfit_projx1__178->GetXaxis()->SetTitleSize(0.08);
   TotalBkg_fail_postfit_projx1__178->GetXaxis()->SetTitleOffset(0.9);
   TotalBkg_fail_postfit_projx1__178->GetXaxis()->SetTitleFont(42);
   TotalBkg_fail_postfit_projx1__178->GetYaxis()->SetTitle("Events / bin");
   TotalBkg_fail_postfit_projx1__178->GetYaxis()->SetLabelFont(42);
   TotalBkg_fail_postfit_projx1__178->GetYaxis()->SetLabelOffset(0.007);
   TotalBkg_fail_postfit_projx1__178->GetYaxis()->SetLabelSize(0.05);
   TotalBkg_fail_postfit_projx1__178->GetYaxis()->SetTitleSize(0.08);
   TotalBkg_fail_postfit_projx1__178->GetYaxis()->SetTitleOffset(1.25);
   TotalBkg_fail_postfit_projx1__178->GetYaxis()->SetTitleFont(42);
   TotalBkg_fail_postfit_projx1__178->GetZaxis()->SetLabelFont(42);
   TotalBkg_fail_postfit_projx1__178->GetZaxis()->SetLabelOffset(0.007);
   TotalBkg_fail_postfit_projx1__178->GetZaxis()->SetLabelSize(0.05);
   TotalBkg_fail_postfit_projx1__178->GetZaxis()->SetTitleSize(0.08);
   TotalBkg_fail_postfit_projx1__178->GetZaxis()->SetTitleFont(42);
   TotalBkg_fail_postfit_projx1__178->Draw("hist same");
   Double_t xAxis283[10] = {0, 0.04, 0.08, 0.12, 0.16, 0.2, 0.24, 0.28, 0.32, 1}; 
   
   TH1D *TotalBkg_fail_postfit_projx1__179 = new TH1D("TotalBkg_fail_postfit_projx1__179","TotalBkg, fail, postfit, 50-50",9, xAxis283);
   TotalBkg_fail_postfit_projx1__179->SetMinimum(0);
   TotalBkg_fail_postfit_projx1__179->SetFillColor(1);
   TotalBkg_fail_postfit_projx1__179->SetFillStyle(3354);
   TotalBkg_fail_postfit_projx1__179->SetLineStyle(0);
   TotalBkg_fail_postfit_projx1__179->SetLineWidth(0);
   TotalBkg_fail_postfit_projx1__179->SetMarkerStyle(0);
   TotalBkg_fail_postfit_projx1__179->GetXaxis()->SetTitle("G_{i}^{Strips}");
   TotalBkg_fail_postfit_projx1__179->GetXaxis()->SetLabelFont(42);
   TotalBkg_fail_postfit_projx1__179->GetXaxis()->SetLabelOffset(0.007);
   TotalBkg_fail_postfit_projx1__179->GetXaxis()->SetLabelSize(0.05);
   TotalBkg_fail_postfit_projx1__179->GetXaxis()->SetTitleSize(0.08);
   TotalBkg_fail_postfit_projx1__179->GetXaxis()->SetTitleOffset(0.9);
   TotalBkg_fail_postfit_projx1__179->GetXaxis()->SetTitleFont(42);
   TotalBkg_fail_postfit_projx1__179->GetYaxis()->SetTitle("Events / bin");
   TotalBkg_fail_postfit_projx1__179->GetYaxis()->SetLabelFont(42);
   TotalBkg_fail_postfit_projx1__179->GetYaxis()->SetLabelOffset(0.007);
   TotalBkg_fail_postfit_projx1__179->GetYaxis()->SetLabelSize(0.05);
   TotalBkg_fail_postfit_projx1__179->GetYaxis()->SetTitleSize(0.08);
   TotalBkg_fail_postfit_projx1__179->GetYaxis()->SetTitleOffset(1.25);
   TotalBkg_fail_postfit_projx1__179->GetYaxis()->SetTitleFont(42);
   TotalBkg_fail_postfit_projx1__179->GetZaxis()->SetLabelFont(42);
   TotalBkg_fail_postfit_projx1__179->GetZaxis()->SetLabelOffset(0.007);
   TotalBkg_fail_postfit_projx1__179->GetZaxis()->SetLabelSize(0.05);
   TotalBkg_fail_postfit_projx1__179->GetZaxis()->SetTitleSize(0.08);
   TotalBkg_fail_postfit_projx1__179->GetZaxis()->SetTitleFont(42);
   TotalBkg_fail_postfit_projx1__179->Draw("e2 same");
   Double_t xAxis284[10] = {0, 0.04, 0.08, 0.12, 0.16, 0.2, 0.24, 0.28, 0.32, 1}; 
   
   TH1D *data_obs_fail_postfit_projx1__180 = new TH1D("data_obs_fail_postfit_projx1__180","",9, xAxis284);
   data_obs_fail_postfit_projx1__180->SetMinimum(0);
   data_obs_fail_postfit_projx1__180->SetMaximum(0);

   ci = TColor::GetColor("#000000");
   data_obs_fail_postfit_projx1__180->SetLineColor(ci);
   data_obs_fail_postfit_projx1__180->SetLineStyle(0);

   ci = TColor::GetColor("#000000");
   data_obs_fail_postfit_projx1__180->SetMarkerColor(ci);
   data_obs_fail_postfit_projx1__180->SetMarkerStyle(8);
   data_obs_fail_postfit_projx1__180->GetXaxis()->SetTitle("G_{i}^{Strips}");
   data_obs_fail_postfit_projx1__180->GetXaxis()->SetLabelFont(42);
   data_obs_fail_postfit_projx1__180->GetXaxis()->SetLabelOffset(0.05);
   data_obs_fail_postfit_projx1__180->GetXaxis()->SetLabelSize(0.07);
   data_obs_fail_postfit_projx1__180->GetXaxis()->SetTitleSize(0.09);
   data_obs_fail_postfit_projx1__180->GetXaxis()->SetTitleOffset(1.15);
   data_obs_fail_postfit_projx1__180->GetXaxis()->SetTitleFont(42);
   data_obs_fail_postfit_projx1__180->GetYaxis()->SetTitle("Events / bin");
   data_obs_fail_postfit_projx1__180->GetYaxis()->SetNdivisions(508);
   data_obs_fail_postfit_projx1__180->GetYaxis()->SetLabelFont(42);
   data_obs_fail_postfit_projx1__180->GetYaxis()->SetLabelOffset(0.007);
   data_obs_fail_postfit_projx1__180->GetYaxis()->SetLabelSize(0.07);
   data_obs_fail_postfit_projx1__180->GetYaxis()->SetTitleSize(0.09);
   data_obs_fail_postfit_projx1__180->GetYaxis()->SetTitleOffset(0.8);
   data_obs_fail_postfit_projx1__180->GetYaxis()->SetTitleFont(42);
   data_obs_fail_postfit_projx1__180->GetZaxis()->SetLabelFont(42);
   data_obs_fail_postfit_projx1__180->GetZaxis()->SetLabelOffset(0.007);
   data_obs_fail_postfit_projx1__180->GetZaxis()->SetLabelSize(0.05);
   data_obs_fail_postfit_projx1__180->GetZaxis()->SetTitleSize(0.08);
   data_obs_fail_postfit_projx1__180->GetZaxis()->SetTitleFont(42);
   data_obs_fail_postfit_projx1__180->Draw("pe X0 same");
   
   TLegend *leg = new TLegend(0.65,0.64,0.9,0.88,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(1001);
   TLegendEntry *entry=leg->AddEntry("data_obs_fail_postfit_projx1","Data","pe X0");

   ci = TColor::GetColor("#000000");
   entry->SetLineColor(ci);
   entry->SetLineWidth(1);

   ci = TColor::GetColor("#000000");
   entry->SetMarkerColor(ci);
   entry->SetMarkerStyle(8);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("TotalBkg_fail_postfit_projx1","Total bkg unc.","F");
   entry->SetFillColor(1);
   entry->SetFillStyle(3354);
   entry->SetLineColor(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("Signal_ppStau-557_fail_postfit_projx1","HSCP signal","L");
   entry->SetLineColor(2);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("Background_fail_postfit_projx1_stack_1_stack_1","Background","f");

   ci = TColor::GetColor("#ffff00");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = 1306;
   color = new TColor(ci, 1, 1, 1, " ", 0);
   entry->SetLineColor(ci);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   leg->Draw();
   Double_t xAxis285[10] = {0, 0.04, 0.08, 0.12, 0.16, 0.2, 0.24, 0.28, 0.32, 1}; 
   
   TH1D *data_obs_fail_postfit_projx1_copy__181 = new TH1D("data_obs_fail_postfit_projx1_copy__181","",9, xAxis285);
   data_obs_fail_postfit_projx1_copy__181->SetMinimum(0);
   data_obs_fail_postfit_projx1_copy__181->SetMaximum(0);
   data_obs_fail_postfit_projx1_copy__181->SetDirectory(0);

   ci = TColor::GetColor("#000000");
   data_obs_fail_postfit_projx1_copy__181->SetLineColor(ci);
   data_obs_fail_postfit_projx1_copy__181->SetLineStyle(0);

   ci = TColor::GetColor("#000000");
   data_obs_fail_postfit_projx1_copy__181->SetMarkerColor(ci);
   data_obs_fail_postfit_projx1_copy__181->SetMarkerStyle(8);
   data_obs_fail_postfit_projx1_copy__181->GetXaxis()->SetTitle("G_{i}^{Strips}");
   data_obs_fail_postfit_projx1_copy__181->GetXaxis()->SetLabelFont(42);
   data_obs_fail_postfit_projx1_copy__181->GetXaxis()->SetLabelOffset(0.05);
   data_obs_fail_postfit_projx1_copy__181->GetXaxis()->SetLabelSize(0.07);
   data_obs_fail_postfit_projx1_copy__181->GetXaxis()->SetTitleSize(0.09);
   data_obs_fail_postfit_projx1_copy__181->GetXaxis()->SetTitleOffset(1.15);
   data_obs_fail_postfit_projx1_copy__181->GetXaxis()->SetTitleFont(42);
   data_obs_fail_postfit_projx1_copy__181->GetYaxis()->SetTitle("Events / bin");
   data_obs_fail_postfit_projx1_copy__181->GetYaxis()->SetNdivisions(508);
   data_obs_fail_postfit_projx1_copy__181->GetYaxis()->SetLabelFont(42);
   data_obs_fail_postfit_projx1_copy__181->GetYaxis()->SetLabelOffset(0.007);
   data_obs_fail_postfit_projx1_copy__181->GetYaxis()->SetLabelSize(0.07);
   data_obs_fail_postfit_projx1_copy__181->GetYaxis()->SetTitleSize(0.09);
   data_obs_fail_postfit_projx1_copy__181->GetYaxis()->SetTitleOffset(0.8);
   data_obs_fail_postfit_projx1_copy__181->GetYaxis()->SetTitleFont(42);
   data_obs_fail_postfit_projx1_copy__181->GetZaxis()->SetLabelFont(42);
   data_obs_fail_postfit_projx1_copy__181->GetZaxis()->SetLabelOffset(0.007);
   data_obs_fail_postfit_projx1_copy__181->GetZaxis()->SetLabelSize(0.05);
   data_obs_fail_postfit_projx1_copy__181->GetZaxis()->SetTitleSize(0.08);
   data_obs_fail_postfit_projx1_copy__181->GetZaxis()->SetTitleFont(42);
   data_obs_fail_postfit_projx1_copy__181->Draw("sameaxis");
   TLatex *   tex = new TLatex(0.21,0.83,"55 < p_{T} < 200 GeV, F^{Pixels}_{i} < 0.9");
tex->SetNDC();
   tex->SetTextAlign(12);
   tex->SetTextFont(42);
   tex->SetTextSize(0.06);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.17,0.92,"CMS");
tex->SetNDC();
   tex->SetTextFont(61);
   tex->SetTextSize(0.0675);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.25,0.92,"Preliminary");
tex->SetNDC();
   tex->SetTextFont(52);
   tex->SetTextSize(0.0485);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.95,0.92,"101 fb^{-1} (13 TeV)");
tex->SetNDC();
   tex->SetTextAlign(31);
   tex->SetTextFont(42);
   tex->SetTextSize(0.07);
   tex->SetLineWidth(2);
   tex->Draw();
   data_obs_fail_postfit_projx1_main->Modified();
   plots_fit_s/base_figs/postfit_projx1_fail->cd();
  
// ------------>Primitives in pad: data_obs_fail_postfit_projx1_sub
   TPad *data_obs_fail_postfit_projx1_sub = new TPad("data_obs_fail_postfit_projx1_sub", "data_obs_fail_postfit_projx1_sub",0,0,1,0.35);
   data_obs_fail_postfit_projx1_sub->Draw();
   data_obs_fail_postfit_projx1_sub->cd();
   data_obs_fail_postfit_projx1_sub->Range(-0.2179487,-6.023077,1.064103,2.9);
   data_obs_fail_postfit_projx1_sub->SetFillColor(0);
   data_obs_fail_postfit_projx1_sub->SetBorderMode(0);
   data_obs_fail_postfit_projx1_sub->SetBorderSize(2);
   data_obs_fail_postfit_projx1_sub->SetTickx(1);
   data_obs_fail_postfit_projx1_sub->SetTicky(1);
   data_obs_fail_postfit_projx1_sub->SetLeftMargin(0.17);
   data_obs_fail_postfit_projx1_sub->SetRightMargin(0.05);
   data_obs_fail_postfit_projx1_sub->SetTopMargin(0);
   data_obs_fail_postfit_projx1_sub->SetBottomMargin(0.35);
   data_obs_fail_postfit_projx1_sub->SetFrameFillStyle(0);
   data_obs_fail_postfit_projx1_sub->SetFrameBorderMode(0);
   data_obs_fail_postfit_projx1_sub->SetFrameFillStyle(0);
   data_obs_fail_postfit_projx1_sub->SetFrameBorderMode(0);
   Double_t xAxis286[10] = {0, 0.04, 0.08, 0.12, 0.16, 0.2, 0.24, 0.28, 0.32, 1}; 
   
   TH1D *data_obs_fail_postfit_projx1_pull__182 = new TH1D("data_obs_fail_postfit_projx1_pull__182","",9, xAxis286);
   data_obs_fail_postfit_projx1_pull__182->SetMinimum(-2.9);
   data_obs_fail_postfit_projx1_pull__182->SetMaximum(2.9);
   data_obs_fail_postfit_projx1_pull__182->SetEntries(18);
   data_obs_fail_postfit_projx1_pull__182->SetStats(0);

   ci = TColor::GetColor("#0000ff");
   data_obs_fail_postfit_projx1_pull__182->SetFillColor(ci);

   ci = TColor::GetColor("#000000");
   data_obs_fail_postfit_projx1_pull__182->SetLineColor(ci);
   data_obs_fail_postfit_projx1_pull__182->SetLineStyle(0);

   ci = TColor::GetColor("#000000");
   data_obs_fail_postfit_projx1_pull__182->SetMarkerColor(ci);
   data_obs_fail_postfit_projx1_pull__182->SetMarkerStyle(8);
   data_obs_fail_postfit_projx1_pull__182->GetXaxis()->SetTitle("G_{i}^{Strips}");
   data_obs_fail_postfit_projx1_pull__182->GetXaxis()->SetLabelFont(42);
   data_obs_fail_postfit_projx1_pull__182->GetXaxis()->SetLabelOffset(0.05);
   data_obs_fail_postfit_projx1_pull__182->GetXaxis()->SetLabelSize(0.13);
   data_obs_fail_postfit_projx1_pull__182->GetXaxis()->SetTitleSize(0.15);
   data_obs_fail_postfit_projx1_pull__182->GetXaxis()->SetTitleOffset(1.15);
   data_obs_fail_postfit_projx1_pull__182->GetXaxis()->SetTitleFont(42);
   data_obs_fail_postfit_projx1_pull__182->GetYaxis()->SetTitle("(Data-Bkg)/#sigma");
   data_obs_fail_postfit_projx1_pull__182->GetYaxis()->SetNdivisions(306);
   data_obs_fail_postfit_projx1_pull__182->GetYaxis()->SetLabelFont(42);
   data_obs_fail_postfit_projx1_pull__182->GetYaxis()->SetLabelOffset(0.007);
   data_obs_fail_postfit_projx1_pull__182->GetYaxis()->SetLabelSize(0.13);
   data_obs_fail_postfit_projx1_pull__182->GetYaxis()->SetTitleSize(0.12);
   data_obs_fail_postfit_projx1_pull__182->GetYaxis()->SetTitleOffset(0.4);
   data_obs_fail_postfit_projx1_pull__182->GetYaxis()->SetTitleFont(42);
   data_obs_fail_postfit_projx1_pull__182->GetZaxis()->SetLabelFont(42);
   data_obs_fail_postfit_projx1_pull__182->GetZaxis()->SetLabelOffset(0.007);
   data_obs_fail_postfit_projx1_pull__182->GetZaxis()->SetLabelSize(0.05);
   data_obs_fail_postfit_projx1_pull__182->GetZaxis()->SetTitleSize(0.08);
   data_obs_fail_postfit_projx1_pull__182->GetZaxis()->SetTitleFont(42);
   data_obs_fail_postfit_projx1_pull__182->Draw("hist");
   data_obs_fail_postfit_projx1_sub->Modified();
   plots_fit_s/base_figs/postfit_projx1_fail->cd();
   plots_fit_s/base_figs/postfit_projx1_fail->Modified();
   plots_fit_s/base_figs/postfit_projx1_fail->cd();
   plots_fit_s/base_figs/postfit_projx1_fail->SetSelected(plots_fit_s/base_figs/postfit_projx1_fail);
}
