void postfit_projx0_fail_logy()
{
//=========Macro generated from canvas: plots_fit_s/base_figs/postfit_projx0_fail_logy/plots_fit_s/base_figs/postfit_projx0_fail_logy
//=========  (Fri Jan 12 21:00:08 2024) by ROOT version 6.14/09
   TCanvas *plots_fit_s/base_figs/postfit_projx0_fail_logy = new TCanvas("plots_fit_s/base_figs/postfit_projx0_fail_logy", "plots_fit_s/base_figs/postfit_projx0_fail_logy",0,0,800,700);
   gStyle->SetOptFit(1);
   gStyle->SetOptStat(0);
   plots_fit_s/base_figs/postfit_projx0_fail_logy->SetHighLightColor(2);
   plots_fit_s/base_figs/postfit_projx0_fail_logy->Range(0,0,1,1);
   plots_fit_s/base_figs/postfit_projx0_fail_logy->SetFillColor(0);
   plots_fit_s/base_figs/postfit_projx0_fail_logy->SetBorderMode(0);
   plots_fit_s/base_figs/postfit_projx0_fail_logy->SetBorderSize(2);
   plots_fit_s/base_figs/postfit_projx0_fail_logy->SetTickx(1);
   plots_fit_s/base_figs/postfit_projx0_fail_logy->SetTicky(1);
   plots_fit_s/base_figs/postfit_projx0_fail_logy->SetLeftMargin(0.16);
   plots_fit_s/base_figs/postfit_projx0_fail_logy->SetRightMargin(0);
   plots_fit_s/base_figs/postfit_projx0_fail_logy->SetTopMargin(0);
   plots_fit_s/base_figs/postfit_projx0_fail_logy->SetBottomMargin(0);
   plots_fit_s/base_figs/postfit_projx0_fail_logy->SetFrameFillStyle(0);
   plots_fit_s/base_figs/postfit_projx0_fail_logy->SetFrameBorderMode(0);
  
// ------------>Primitives in pad: data_obs_fail_postfit_projx0_main
   TPad *data_obs_fail_postfit_projx0_main = new TPad("data_obs_fail_postfit_projx0_main", "data_obs_fail_postfit_projx0_main",0,0.35,1,1);
   data_obs_fail_postfit_projx0_main->Draw();
   data_obs_fail_postfit_projx0_main->cd();
   data_obs_fail_postfit_projx0_main->Range(-0.2179487,-2.139535,1.064103,1.348837);
   data_obs_fail_postfit_projx0_main->SetFillColor(0);
   data_obs_fail_postfit_projx0_main->SetBorderMode(0);
   data_obs_fail_postfit_projx0_main->SetBorderSize(2);
   data_obs_fail_postfit_projx0_main->SetLogy();
   data_obs_fail_postfit_projx0_main->SetTickx(1);
   data_obs_fail_postfit_projx0_main->SetTicky(1);
   data_obs_fail_postfit_projx0_main->SetLeftMargin(0.17);
   data_obs_fail_postfit_projx0_main->SetRightMargin(0.05);
   data_obs_fail_postfit_projx0_main->SetBottomMargin(0.04);
   data_obs_fail_postfit_projx0_main->SetFrameFillStyle(0);
   data_obs_fail_postfit_projx0_main->SetFrameBorderMode(0);
   data_obs_fail_postfit_projx0_main->SetFrameFillStyle(0);
   data_obs_fail_postfit_projx0_main->SetFrameBorderMode(0);
   Double_t xAxis331[10] = {0, 0.04, 0.08, 0.12, 0.16, 0.2, 0.24, 0.28, 0.32, 1}; 
   
   TH1D *data_obs_fail_postfit_projx0__211 = new TH1D("data_obs_fail_postfit_projx0__211","",9, xAxis331);
   data_obs_fail_postfit_projx0__211->SetMinimum(0.001);
   data_obs_fail_postfit_projx0__211->SetMaximum(0);

   Int_t ci;      // for color index setting
   TColor *color; // for color definition with alpha
   ci = TColor::GetColor("#000000");
   data_obs_fail_postfit_projx0__211->SetLineColor(ci);
   data_obs_fail_postfit_projx0__211->SetLineStyle(0);

   ci = TColor::GetColor("#000000");
   data_obs_fail_postfit_projx0__211->SetMarkerColor(ci);
   data_obs_fail_postfit_projx0__211->SetMarkerStyle(8);
   data_obs_fail_postfit_projx0__211->GetXaxis()->SetTitle("G_{i}^{Strips}");
   data_obs_fail_postfit_projx0__211->GetXaxis()->SetLabelFont(42);
   data_obs_fail_postfit_projx0__211->GetXaxis()->SetLabelOffset(0.05);
   data_obs_fail_postfit_projx0__211->GetXaxis()->SetLabelSize(0.07);
   data_obs_fail_postfit_projx0__211->GetXaxis()->SetTitleSize(0.09);
   data_obs_fail_postfit_projx0__211->GetXaxis()->SetTitleOffset(1.15);
   data_obs_fail_postfit_projx0__211->GetXaxis()->SetTitleFont(42);
   data_obs_fail_postfit_projx0__211->GetYaxis()->SetTitle("Events / bin");
   data_obs_fail_postfit_projx0__211->GetYaxis()->SetNdivisions(508);
   data_obs_fail_postfit_projx0__211->GetYaxis()->SetLabelFont(42);
   data_obs_fail_postfit_projx0__211->GetYaxis()->SetLabelOffset(0.007);
   data_obs_fail_postfit_projx0__211->GetYaxis()->SetLabelSize(0.07);
   data_obs_fail_postfit_projx0__211->GetYaxis()->SetTitleSize(0.09);
   data_obs_fail_postfit_projx0__211->GetYaxis()->SetTitleOffset(0.8);
   data_obs_fail_postfit_projx0__211->GetYaxis()->SetTitleFont(42);
   data_obs_fail_postfit_projx0__211->GetZaxis()->SetLabelFont(42);
   data_obs_fail_postfit_projx0__211->GetZaxis()->SetLabelOffset(0.007);
   data_obs_fail_postfit_projx0__211->GetZaxis()->SetLabelSize(0.05);
   data_obs_fail_postfit_projx0__211->GetZaxis()->SetTitleSize(0.08);
   data_obs_fail_postfit_projx0__211->GetZaxis()->SetTitleFont(42);
   data_obs_fail_postfit_projx0__211->Draw("pe X0");
   
   THStack *postfit_projx0_fail_logy_stack = new THStack();
   postfit_projx0_fail_logy_stack->SetName("postfit_projx0_fail_logy_stack");
   postfit_projx0_fail_logy_stack->SetTitle("postfit_projx0_fail_logy_stack");
   postfit_projx0_fail_logy_stack->SetMinimum(0.001);
   Double_t xAxis332[10] = {0, 0.04, 0.08, 0.12, 0.16, 0.2, 0.24, 0.28, 0.32, 1}; 
   
   TH1F *postfit_projx0_fail_logy_stack_stack_61 = new TH1F("postfit_projx0_fail_logy_stack_stack_61","postfit_projx0_fail_logy_stack",9, xAxis332);
   postfit_projx0_fail_logy_stack_stack_61->SetMinimum(-0);
   postfit_projx0_fail_logy_stack_stack_61->SetMaximum(-nan);
   postfit_projx0_fail_logy_stack_stack_61->SetDirectory(0);
   postfit_projx0_fail_logy_stack_stack_61->SetStats(0);
   postfit_projx0_fail_logy_stack_stack_61->SetLineStyle(0);
   postfit_projx0_fail_logy_stack_stack_61->GetXaxis()->SetLabelFont(42);
   postfit_projx0_fail_logy_stack_stack_61->GetXaxis()->SetLabelOffset(0.007);
   postfit_projx0_fail_logy_stack_stack_61->GetXaxis()->SetLabelSize(0.05);
   postfit_projx0_fail_logy_stack_stack_61->GetXaxis()->SetTitleSize(0.08);
   postfit_projx0_fail_logy_stack_stack_61->GetXaxis()->SetTitleOffset(0.9);
   postfit_projx0_fail_logy_stack_stack_61->GetXaxis()->SetTitleFont(42);
   postfit_projx0_fail_logy_stack_stack_61->GetYaxis()->SetNdivisions(508);
   postfit_projx0_fail_logy_stack_stack_61->GetYaxis()->SetLabelFont(42);
   postfit_projx0_fail_logy_stack_stack_61->GetYaxis()->SetLabelOffset(0.007);
   postfit_projx0_fail_logy_stack_stack_61->GetYaxis()->SetLabelSize(0.05);
   postfit_projx0_fail_logy_stack_stack_61->GetYaxis()->SetTitleSize(0.08);
   postfit_projx0_fail_logy_stack_stack_61->GetYaxis()->SetTitleOffset(1.25);
   postfit_projx0_fail_logy_stack_stack_61->GetYaxis()->SetTitleFont(42);
   postfit_projx0_fail_logy_stack_stack_61->GetZaxis()->SetLabelFont(42);
   postfit_projx0_fail_logy_stack_stack_61->GetZaxis()->SetLabelOffset(0.007);
   postfit_projx0_fail_logy_stack_stack_61->GetZaxis()->SetLabelSize(0.05);
   postfit_projx0_fail_logy_stack_stack_61->GetZaxis()->SetTitleSize(0.08);
   postfit_projx0_fail_logy_stack_stack_61->GetZaxis()->SetTitleFont(42);
   postfit_projx0_fail_logy_stack->SetHistogram(postfit_projx0_fail_logy_stack_stack_61);
   
   Double_t xAxis333[10] = {0, 0.04, 0.08, 0.12, 0.16, 0.2, 0.24, 0.28, 0.32, 1}; 
   
   TH1D *Background_fail_postfit_projx0_stack_1 = new TH1D("Background_fail_postfit_projx0_stack_1","Background, fail, postfit, 50-50",9, xAxis333);
   Background_fail_postfit_projx0_stack_1->SetMinimum(0.001);

   ci = TColor::GetColor("#ffff00");
   Background_fail_postfit_projx0_stack_1->SetFillColor(ci);

   ci = 1305;
   color = new TColor(ci, 1, 1, 1, " ", 0);
   Background_fail_postfit_projx0_stack_1->SetLineColor(ci);
   Background_fail_postfit_projx0_stack_1->SetLineStyle(0);
   Background_fail_postfit_projx0_stack_1->GetXaxis()->SetTitle("G_{i}^{Strips}");
   Background_fail_postfit_projx0_stack_1->GetXaxis()->SetLabelFont(42);
   Background_fail_postfit_projx0_stack_1->GetXaxis()->SetLabelOffset(0.007);
   Background_fail_postfit_projx0_stack_1->GetXaxis()->SetLabelSize(0.05);
   Background_fail_postfit_projx0_stack_1->GetXaxis()->SetTitleSize(0.08);
   Background_fail_postfit_projx0_stack_1->GetXaxis()->SetTitleOffset(0.9);
   Background_fail_postfit_projx0_stack_1->GetXaxis()->SetTitleFont(42);
   Background_fail_postfit_projx0_stack_1->GetYaxis()->SetTitle("Events / bin");
   Background_fail_postfit_projx0_stack_1->GetYaxis()->SetLabelFont(42);
   Background_fail_postfit_projx0_stack_1->GetYaxis()->SetLabelOffset(0.007);
   Background_fail_postfit_projx0_stack_1->GetYaxis()->SetLabelSize(0.05);
   Background_fail_postfit_projx0_stack_1->GetYaxis()->SetTitleSize(0.08);
   Background_fail_postfit_projx0_stack_1->GetYaxis()->SetTitleOffset(1.25);
   Background_fail_postfit_projx0_stack_1->GetYaxis()->SetTitleFont(42);
   Background_fail_postfit_projx0_stack_1->GetZaxis()->SetLabelFont(42);
   Background_fail_postfit_projx0_stack_1->GetZaxis()->SetLabelOffset(0.007);
   Background_fail_postfit_projx0_stack_1->GetZaxis()->SetLabelSize(0.05);
   Background_fail_postfit_projx0_stack_1->GetZaxis()->SetTitleSize(0.08);
   Background_fail_postfit_projx0_stack_1->GetZaxis()->SetTitleFont(42);
   postfit_projx0_fail_logy_stack->Add(Background_fail_postfit_projx0_stack_1,"");
   postfit_projx0_fail_logy_stack->Draw("hist same");
   
   postfit_projx0_fail_logy_stack = new THStack();
   postfit_projx0_fail_logy_stack->SetName("postfit_projx0_fail_logy_stack");
   postfit_projx0_fail_logy_stack->SetTitle("postfit_projx0_fail_logy_stack");
   postfit_projx0_fail_logy_stack->SetMinimum(0.001);
   Double_t xAxis334[10] = {0, 0.04, 0.08, 0.12, 0.16, 0.2, 0.24, 0.28, 0.32, 1}; 
   
   TH1F *postfit_projx0_fail_logy_stack_stack_61_stack_62 = new TH1F("postfit_projx0_fail_logy_stack_stack_61_stack_62","postfit_projx0_fail_logy_stack",9, xAxis334);
   postfit_projx0_fail_logy_stack_stack_61_stack_62->SetMinimum(-0);
   postfit_projx0_fail_logy_stack_stack_61_stack_62->SetMaximum(-nan);
   postfit_projx0_fail_logy_stack_stack_61_stack_62->SetDirectory(0);
   postfit_projx0_fail_logy_stack_stack_61_stack_62->SetStats(0);
   postfit_projx0_fail_logy_stack_stack_61_stack_62->SetLineStyle(0);
   postfit_projx0_fail_logy_stack_stack_61_stack_62->GetXaxis()->SetLabelFont(42);
   postfit_projx0_fail_logy_stack_stack_61_stack_62->GetXaxis()->SetLabelOffset(0.007);
   postfit_projx0_fail_logy_stack_stack_61_stack_62->GetXaxis()->SetLabelSize(0.05);
   postfit_projx0_fail_logy_stack_stack_61_stack_62->GetXaxis()->SetTitleSize(0.08);
   postfit_projx0_fail_logy_stack_stack_61_stack_62->GetXaxis()->SetTitleOffset(0.9);
   postfit_projx0_fail_logy_stack_stack_61_stack_62->GetXaxis()->SetTitleFont(42);
   postfit_projx0_fail_logy_stack_stack_61_stack_62->GetYaxis()->SetNdivisions(508);
   postfit_projx0_fail_logy_stack_stack_61_stack_62->GetYaxis()->SetLabelFont(42);
   postfit_projx0_fail_logy_stack_stack_61_stack_62->GetYaxis()->SetLabelOffset(0.007);
   postfit_projx0_fail_logy_stack_stack_61_stack_62->GetYaxis()->SetLabelSize(0.05);
   postfit_projx0_fail_logy_stack_stack_61_stack_62->GetYaxis()->SetTitleSize(0.08);
   postfit_projx0_fail_logy_stack_stack_61_stack_62->GetYaxis()->SetTitleOffset(1.25);
   postfit_projx0_fail_logy_stack_stack_61_stack_62->GetYaxis()->SetTitleFont(42);
   postfit_projx0_fail_logy_stack_stack_61_stack_62->GetZaxis()->SetLabelFont(42);
   postfit_projx0_fail_logy_stack_stack_61_stack_62->GetZaxis()->SetLabelOffset(0.007);
   postfit_projx0_fail_logy_stack_stack_61_stack_62->GetZaxis()->SetLabelSize(0.05);
   postfit_projx0_fail_logy_stack_stack_61_stack_62->GetZaxis()->SetTitleSize(0.08);
   postfit_projx0_fail_logy_stack_stack_61_stack_62->GetZaxis()->SetTitleFont(42);
   postfit_projx0_fail_logy_stack->SetHistogram(postfit_projx0_fail_logy_stack_stack_61_stack_62);
   
   Double_t xAxis335[10] = {0, 0.04, 0.08, 0.12, 0.16, 0.2, 0.24, 0.28, 0.32, 1}; 
   
   TH1D *Background_fail_postfit_projx0_stack_1_stack_1 = new TH1D("Background_fail_postfit_projx0_stack_1_stack_1","Background, fail, postfit, 50-50",9, xAxis335);
   Background_fail_postfit_projx0_stack_1_stack_1->SetMinimum(0.001);

   ci = TColor::GetColor("#ffff00");
   Background_fail_postfit_projx0_stack_1_stack_1->SetFillColor(ci);

   ci = 1305;
   color = new TColor(ci, 1, 1, 1, " ", 0);
   Background_fail_postfit_projx0_stack_1_stack_1->SetLineColor(ci);
   Background_fail_postfit_projx0_stack_1_stack_1->SetLineStyle(0);
   Background_fail_postfit_projx0_stack_1_stack_1->GetXaxis()->SetTitle("G_{i}^{Strips}");
   Background_fail_postfit_projx0_stack_1_stack_1->GetXaxis()->SetLabelFont(42);
   Background_fail_postfit_projx0_stack_1_stack_1->GetXaxis()->SetLabelOffset(0.007);
   Background_fail_postfit_projx0_stack_1_stack_1->GetXaxis()->SetLabelSize(0.05);
   Background_fail_postfit_projx0_stack_1_stack_1->GetXaxis()->SetTitleSize(0.08);
   Background_fail_postfit_projx0_stack_1_stack_1->GetXaxis()->SetTitleOffset(0.9);
   Background_fail_postfit_projx0_stack_1_stack_1->GetXaxis()->SetTitleFont(42);
   Background_fail_postfit_projx0_stack_1_stack_1->GetYaxis()->SetTitle("Events / bin");
   Background_fail_postfit_projx0_stack_1_stack_1->GetYaxis()->SetLabelFont(42);
   Background_fail_postfit_projx0_stack_1_stack_1->GetYaxis()->SetLabelOffset(0.007);
   Background_fail_postfit_projx0_stack_1_stack_1->GetYaxis()->SetLabelSize(0.05);
   Background_fail_postfit_projx0_stack_1_stack_1->GetYaxis()->SetTitleSize(0.08);
   Background_fail_postfit_projx0_stack_1_stack_1->GetYaxis()->SetTitleOffset(1.25);
   Background_fail_postfit_projx0_stack_1_stack_1->GetYaxis()->SetTitleFont(42);
   Background_fail_postfit_projx0_stack_1_stack_1->GetZaxis()->SetLabelFont(42);
   Background_fail_postfit_projx0_stack_1_stack_1->GetZaxis()->SetLabelOffset(0.007);
   Background_fail_postfit_projx0_stack_1_stack_1->GetZaxis()->SetLabelSize(0.05);
   Background_fail_postfit_projx0_stack_1_stack_1->GetZaxis()->SetTitleSize(0.08);
   Background_fail_postfit_projx0_stack_1_stack_1->GetZaxis()->SetTitleFont(42);
   postfit_projx0_fail_logy_stack->Add(Background_fail_postfit_projx0_stack_1_stack_1,"");
   postfit_projx0_fail_logy_stack->Draw("hist same");
   Double_t xAxis336[10] = {0, 0.04, 0.08, 0.12, 0.16, 0.2, 0.24, 0.28, 0.32, 1}; 
   
   TH1D *Signal_ppStaumI557_fail_postfit_projx0__212 = new TH1D("Signal_ppStaumI557_fail_postfit_projx0__212","HSCP signal, fail, postfit, 50-50",9, xAxis336);
   Signal_ppStaumI557_fail_postfit_projx0__212->SetMinimum(0.001);
   Signal_ppStaumI557_fail_postfit_projx0__212->SetLineColor(2);
   Signal_ppStaumI557_fail_postfit_projx0__212->SetLineStyle(0);
   Signal_ppStaumI557_fail_postfit_projx0__212->GetXaxis()->SetTitle("G_{i}^{Strips}");
   Signal_ppStaumI557_fail_postfit_projx0__212->GetXaxis()->SetLabelFont(42);
   Signal_ppStaumI557_fail_postfit_projx0__212->GetXaxis()->SetLabelOffset(0.007);
   Signal_ppStaumI557_fail_postfit_projx0__212->GetXaxis()->SetLabelSize(0.05);
   Signal_ppStaumI557_fail_postfit_projx0__212->GetXaxis()->SetTitleSize(0.08);
   Signal_ppStaumI557_fail_postfit_projx0__212->GetXaxis()->SetTitleOffset(0.9);
   Signal_ppStaumI557_fail_postfit_projx0__212->GetXaxis()->SetTitleFont(42);
   Signal_ppStaumI557_fail_postfit_projx0__212->GetYaxis()->SetTitle("Events / bin");
   Signal_ppStaumI557_fail_postfit_projx0__212->GetYaxis()->SetLabelFont(42);
   Signal_ppStaumI557_fail_postfit_projx0__212->GetYaxis()->SetLabelOffset(0.007);
   Signal_ppStaumI557_fail_postfit_projx0__212->GetYaxis()->SetLabelSize(0.05);
   Signal_ppStaumI557_fail_postfit_projx0__212->GetYaxis()->SetTitleSize(0.08);
   Signal_ppStaumI557_fail_postfit_projx0__212->GetYaxis()->SetTitleOffset(1.25);
   Signal_ppStaumI557_fail_postfit_projx0__212->GetYaxis()->SetTitleFont(42);
   Signal_ppStaumI557_fail_postfit_projx0__212->GetZaxis()->SetLabelFont(42);
   Signal_ppStaumI557_fail_postfit_projx0__212->GetZaxis()->SetLabelOffset(0.007);
   Signal_ppStaumI557_fail_postfit_projx0__212->GetZaxis()->SetLabelSize(0.05);
   Signal_ppStaumI557_fail_postfit_projx0__212->GetZaxis()->SetTitleSize(0.08);
   Signal_ppStaumI557_fail_postfit_projx0__212->GetZaxis()->SetTitleFont(42);
   Signal_ppStaumI557_fail_postfit_projx0__212->Draw("hist same");
   Double_t xAxis337[10] = {0, 0.04, 0.08, 0.12, 0.16, 0.2, 0.24, 0.28, 0.32, 1}; 
   
   TH1D *TotalBkg_fail_postfit_projx0__213 = new TH1D("TotalBkg_fail_postfit_projx0__213","TotalBkg, fail, postfit, 50-50",9, xAxis337);
   TotalBkg_fail_postfit_projx0__213->SetMinimum(0.001);
   TotalBkg_fail_postfit_projx0__213->SetLineStyle(0);
   TotalBkg_fail_postfit_projx0__213->SetMarkerStyle(0);
   TotalBkg_fail_postfit_projx0__213->GetXaxis()->SetTitle("G_{i}^{Strips}");
   TotalBkg_fail_postfit_projx0__213->GetXaxis()->SetLabelFont(42);
   TotalBkg_fail_postfit_projx0__213->GetXaxis()->SetLabelOffset(0.007);
   TotalBkg_fail_postfit_projx0__213->GetXaxis()->SetLabelSize(0.05);
   TotalBkg_fail_postfit_projx0__213->GetXaxis()->SetTitleSize(0.08);
   TotalBkg_fail_postfit_projx0__213->GetXaxis()->SetTitleOffset(0.9);
   TotalBkg_fail_postfit_projx0__213->GetXaxis()->SetTitleFont(42);
   TotalBkg_fail_postfit_projx0__213->GetYaxis()->SetTitle("Events / bin");
   TotalBkg_fail_postfit_projx0__213->GetYaxis()->SetLabelFont(42);
   TotalBkg_fail_postfit_projx0__213->GetYaxis()->SetLabelOffset(0.007);
   TotalBkg_fail_postfit_projx0__213->GetYaxis()->SetLabelSize(0.05);
   TotalBkg_fail_postfit_projx0__213->GetYaxis()->SetTitleSize(0.08);
   TotalBkg_fail_postfit_projx0__213->GetYaxis()->SetTitleOffset(1.25);
   TotalBkg_fail_postfit_projx0__213->GetYaxis()->SetTitleFont(42);
   TotalBkg_fail_postfit_projx0__213->GetZaxis()->SetLabelFont(42);
   TotalBkg_fail_postfit_projx0__213->GetZaxis()->SetLabelOffset(0.007);
   TotalBkg_fail_postfit_projx0__213->GetZaxis()->SetLabelSize(0.05);
   TotalBkg_fail_postfit_projx0__213->GetZaxis()->SetTitleSize(0.08);
   TotalBkg_fail_postfit_projx0__213->GetZaxis()->SetTitleFont(42);
   TotalBkg_fail_postfit_projx0__213->Draw("hist same");
   Double_t xAxis338[10] = {0, 0.04, 0.08, 0.12, 0.16, 0.2, 0.24, 0.28, 0.32, 1}; 
   
   TH1D *TotalBkg_fail_postfit_projx0__214 = new TH1D("TotalBkg_fail_postfit_projx0__214","TotalBkg, fail, postfit, 50-50",9, xAxis338);
   TotalBkg_fail_postfit_projx0__214->SetMinimum(0.001);
   TotalBkg_fail_postfit_projx0__214->SetFillColor(1);
   TotalBkg_fail_postfit_projx0__214->SetFillStyle(3354);
   TotalBkg_fail_postfit_projx0__214->SetLineStyle(0);
   TotalBkg_fail_postfit_projx0__214->SetLineWidth(0);
   TotalBkg_fail_postfit_projx0__214->SetMarkerStyle(0);
   TotalBkg_fail_postfit_projx0__214->GetXaxis()->SetTitle("G_{i}^{Strips}");
   TotalBkg_fail_postfit_projx0__214->GetXaxis()->SetLabelFont(42);
   TotalBkg_fail_postfit_projx0__214->GetXaxis()->SetLabelOffset(0.007);
   TotalBkg_fail_postfit_projx0__214->GetXaxis()->SetLabelSize(0.05);
   TotalBkg_fail_postfit_projx0__214->GetXaxis()->SetTitleSize(0.08);
   TotalBkg_fail_postfit_projx0__214->GetXaxis()->SetTitleOffset(0.9);
   TotalBkg_fail_postfit_projx0__214->GetXaxis()->SetTitleFont(42);
   TotalBkg_fail_postfit_projx0__214->GetYaxis()->SetTitle("Events / bin");
   TotalBkg_fail_postfit_projx0__214->GetYaxis()->SetLabelFont(42);
   TotalBkg_fail_postfit_projx0__214->GetYaxis()->SetLabelOffset(0.007);
   TotalBkg_fail_postfit_projx0__214->GetYaxis()->SetLabelSize(0.05);
   TotalBkg_fail_postfit_projx0__214->GetYaxis()->SetTitleSize(0.08);
   TotalBkg_fail_postfit_projx0__214->GetYaxis()->SetTitleOffset(1.25);
   TotalBkg_fail_postfit_projx0__214->GetYaxis()->SetTitleFont(42);
   TotalBkg_fail_postfit_projx0__214->GetZaxis()->SetLabelFont(42);
   TotalBkg_fail_postfit_projx0__214->GetZaxis()->SetLabelOffset(0.007);
   TotalBkg_fail_postfit_projx0__214->GetZaxis()->SetLabelSize(0.05);
   TotalBkg_fail_postfit_projx0__214->GetZaxis()->SetTitleSize(0.08);
   TotalBkg_fail_postfit_projx0__214->GetZaxis()->SetTitleFont(42);
   TotalBkg_fail_postfit_projx0__214->Draw("e2 same");
   Double_t xAxis339[10] = {0, 0.04, 0.08, 0.12, 0.16, 0.2, 0.24, 0.28, 0.32, 1}; 
   
   TH1D *data_obs_fail_postfit_projx0__215 = new TH1D("data_obs_fail_postfit_projx0__215","",9, xAxis339);
   data_obs_fail_postfit_projx0__215->SetMinimum(0.001);
   data_obs_fail_postfit_projx0__215->SetMaximum(0);

   ci = TColor::GetColor("#000000");
   data_obs_fail_postfit_projx0__215->SetLineColor(ci);
   data_obs_fail_postfit_projx0__215->SetLineStyle(0);

   ci = TColor::GetColor("#000000");
   data_obs_fail_postfit_projx0__215->SetMarkerColor(ci);
   data_obs_fail_postfit_projx0__215->SetMarkerStyle(8);
   data_obs_fail_postfit_projx0__215->GetXaxis()->SetTitle("G_{i}^{Strips}");
   data_obs_fail_postfit_projx0__215->GetXaxis()->SetLabelFont(42);
   data_obs_fail_postfit_projx0__215->GetXaxis()->SetLabelOffset(0.05);
   data_obs_fail_postfit_projx0__215->GetXaxis()->SetLabelSize(0.07);
   data_obs_fail_postfit_projx0__215->GetXaxis()->SetTitleSize(0.09);
   data_obs_fail_postfit_projx0__215->GetXaxis()->SetTitleOffset(1.15);
   data_obs_fail_postfit_projx0__215->GetXaxis()->SetTitleFont(42);
   data_obs_fail_postfit_projx0__215->GetYaxis()->SetTitle("Events / bin");
   data_obs_fail_postfit_projx0__215->GetYaxis()->SetNdivisions(508);
   data_obs_fail_postfit_projx0__215->GetYaxis()->SetLabelFont(42);
   data_obs_fail_postfit_projx0__215->GetYaxis()->SetLabelOffset(0.007);
   data_obs_fail_postfit_projx0__215->GetYaxis()->SetLabelSize(0.07);
   data_obs_fail_postfit_projx0__215->GetYaxis()->SetTitleSize(0.09);
   data_obs_fail_postfit_projx0__215->GetYaxis()->SetTitleOffset(0.8);
   data_obs_fail_postfit_projx0__215->GetYaxis()->SetTitleFont(42);
   data_obs_fail_postfit_projx0__215->GetZaxis()->SetLabelFont(42);
   data_obs_fail_postfit_projx0__215->GetZaxis()->SetLabelOffset(0.007);
   data_obs_fail_postfit_projx0__215->GetZaxis()->SetLabelSize(0.05);
   data_obs_fail_postfit_projx0__215->GetZaxis()->SetTitleSize(0.08);
   data_obs_fail_postfit_projx0__215->GetZaxis()->SetTitleFont(42);
   data_obs_fail_postfit_projx0__215->Draw("pe X0 same");
   
   TLegend *leg = new TLegend(0.65,0.64,0.9,0.88,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(1001);
   TLegendEntry *entry=leg->AddEntry("data_obs_fail_postfit_projx0","Data","pe X0");

   ci = TColor::GetColor("#000000");
   entry->SetLineColor(ci);
   entry->SetLineWidth(1);

   ci = TColor::GetColor("#000000");
   entry->SetMarkerColor(ci);
   entry->SetMarkerStyle(8);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("TotalBkg_fail_postfit_projx0","Total bkg unc.","F");
   entry->SetFillColor(1);
   entry->SetFillStyle(3354);
   entry->SetLineColor(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("Signal_ppStau-557_fail_postfit_projx0","HSCP signal","L");
   entry->SetLineColor(2);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("Background_fail_postfit_projx0_stack_1_stack_1","Background","f");

   ci = TColor::GetColor("#ffff00");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = 1305;
   color = new TColor(ci, 1, 1, 1, " ", 0);
   entry->SetLineColor(ci);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   leg->Draw();
   Double_t xAxis340[10] = {0, 0.04, 0.08, 0.12, 0.16, 0.2, 0.24, 0.28, 0.32, 1}; 
   
   TH1D *data_obs_fail_postfit_projx0_copy__216 = new TH1D("data_obs_fail_postfit_projx0_copy__216","",9, xAxis340);
   data_obs_fail_postfit_projx0_copy__216->SetMinimum(0.001);
   data_obs_fail_postfit_projx0_copy__216->SetMaximum(0);
   data_obs_fail_postfit_projx0_copy__216->SetDirectory(0);

   ci = TColor::GetColor("#000000");
   data_obs_fail_postfit_projx0_copy__216->SetLineColor(ci);
   data_obs_fail_postfit_projx0_copy__216->SetLineStyle(0);

   ci = TColor::GetColor("#000000");
   data_obs_fail_postfit_projx0_copy__216->SetMarkerColor(ci);
   data_obs_fail_postfit_projx0_copy__216->SetMarkerStyle(8);
   data_obs_fail_postfit_projx0_copy__216->GetXaxis()->SetTitle("G_{i}^{Strips}");
   data_obs_fail_postfit_projx0_copy__216->GetXaxis()->SetLabelFont(42);
   data_obs_fail_postfit_projx0_copy__216->GetXaxis()->SetLabelOffset(0.05);
   data_obs_fail_postfit_projx0_copy__216->GetXaxis()->SetLabelSize(0.07);
   data_obs_fail_postfit_projx0_copy__216->GetXaxis()->SetTitleSize(0.09);
   data_obs_fail_postfit_projx0_copy__216->GetXaxis()->SetTitleOffset(1.15);
   data_obs_fail_postfit_projx0_copy__216->GetXaxis()->SetTitleFont(42);
   data_obs_fail_postfit_projx0_copy__216->GetYaxis()->SetTitle("Events / bin");
   data_obs_fail_postfit_projx0_copy__216->GetYaxis()->SetNdivisions(508);
   data_obs_fail_postfit_projx0_copy__216->GetYaxis()->SetLabelFont(42);
   data_obs_fail_postfit_projx0_copy__216->GetYaxis()->SetLabelOffset(0.007);
   data_obs_fail_postfit_projx0_copy__216->GetYaxis()->SetLabelSize(0.07);
   data_obs_fail_postfit_projx0_copy__216->GetYaxis()->SetTitleSize(0.09);
   data_obs_fail_postfit_projx0_copy__216->GetYaxis()->SetTitleOffset(0.8);
   data_obs_fail_postfit_projx0_copy__216->GetYaxis()->SetTitleFont(42);
   data_obs_fail_postfit_projx0_copy__216->GetZaxis()->SetLabelFont(42);
   data_obs_fail_postfit_projx0_copy__216->GetZaxis()->SetLabelOffset(0.007);
   data_obs_fail_postfit_projx0_copy__216->GetZaxis()->SetLabelSize(0.05);
   data_obs_fail_postfit_projx0_copy__216->GetZaxis()->SetTitleSize(0.08);
   data_obs_fail_postfit_projx0_copy__216->GetZaxis()->SetTitleFont(42);
   data_obs_fail_postfit_projx0_copy__216->Draw("sameaxis");
   TLatex *   tex = new TLatex(0.21,0.83,"55 < p_{T} < 200 GeV, F^{Pixels}_{i} < 0.9");
tex->SetNDC();
   tex->SetTextAlign(12);
   tex->SetTextFont(42);
   tex->SetTextSize(0.06);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.17,0.92,"CMS");
tex->SetNDC();
   tex->SetTextFont(61);
   tex->SetTextSize(0.0675);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.25,0.92,"Preliminary");
tex->SetNDC();
   tex->SetTextFont(52);
   tex->SetTextSize(0.0485);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.95,0.92,"101 fb^{-1} (13 TeV)");
tex->SetNDC();
   tex->SetTextAlign(31);
   tex->SetTextFont(42);
   tex->SetTextSize(0.07);
   tex->SetLineWidth(2);
   tex->Draw();
   data_obs_fail_postfit_projx0_main->Modified();
   plots_fit_s/base_figs/postfit_projx0_fail_logy->cd();
  
// ------------>Primitives in pad: data_obs_fail_postfit_projx0_sub
   TPad *data_obs_fail_postfit_projx0_sub = new TPad("data_obs_fail_postfit_projx0_sub", "data_obs_fail_postfit_projx0_sub",0,0,1,0.35);
   data_obs_fail_postfit_projx0_sub->Draw();
   data_obs_fail_postfit_projx0_sub->cd();
   data_obs_fail_postfit_projx0_sub->Range(-0.2179487,-6.023077,1.064103,2.9);
   data_obs_fail_postfit_projx0_sub->SetFillColor(0);
   data_obs_fail_postfit_projx0_sub->SetBorderMode(0);
   data_obs_fail_postfit_projx0_sub->SetBorderSize(2);
   data_obs_fail_postfit_projx0_sub->SetTickx(1);
   data_obs_fail_postfit_projx0_sub->SetTicky(1);
   data_obs_fail_postfit_projx0_sub->SetLeftMargin(0.17);
   data_obs_fail_postfit_projx0_sub->SetRightMargin(0.05);
   data_obs_fail_postfit_projx0_sub->SetTopMargin(0);
   data_obs_fail_postfit_projx0_sub->SetBottomMargin(0.35);
   data_obs_fail_postfit_projx0_sub->SetFrameFillStyle(0);
   data_obs_fail_postfit_projx0_sub->SetFrameBorderMode(0);
   data_obs_fail_postfit_projx0_sub->SetFrameFillStyle(0);
   data_obs_fail_postfit_projx0_sub->SetFrameBorderMode(0);
   Double_t xAxis341[10] = {0, 0.04, 0.08, 0.12, 0.16, 0.2, 0.24, 0.28, 0.32, 1}; 
   
   TH1D *data_obs_fail_postfit_projx0_pull__217 = new TH1D("data_obs_fail_postfit_projx0_pull__217","",9, xAxis341);
   data_obs_fail_postfit_projx0_pull__217->SetMinimum(-2.9);
   data_obs_fail_postfit_projx0_pull__217->SetMaximum(2.9);
   data_obs_fail_postfit_projx0_pull__217->SetEntries(18);
   data_obs_fail_postfit_projx0_pull__217->SetStats(0);

   ci = TColor::GetColor("#0000ff");
   data_obs_fail_postfit_projx0_pull__217->SetFillColor(ci);

   ci = TColor::GetColor("#000000");
   data_obs_fail_postfit_projx0_pull__217->SetLineColor(ci);
   data_obs_fail_postfit_projx0_pull__217->SetLineStyle(0);

   ci = TColor::GetColor("#000000");
   data_obs_fail_postfit_projx0_pull__217->SetMarkerColor(ci);
   data_obs_fail_postfit_projx0_pull__217->SetMarkerStyle(8);
   data_obs_fail_postfit_projx0_pull__217->GetXaxis()->SetTitle("G_{i}^{Strips}");
   data_obs_fail_postfit_projx0_pull__217->GetXaxis()->SetLabelFont(42);
   data_obs_fail_postfit_projx0_pull__217->GetXaxis()->SetLabelOffset(0.05);
   data_obs_fail_postfit_projx0_pull__217->GetXaxis()->SetLabelSize(0.13);
   data_obs_fail_postfit_projx0_pull__217->GetXaxis()->SetTitleSize(0.15);
   data_obs_fail_postfit_projx0_pull__217->GetXaxis()->SetTitleOffset(1.15);
   data_obs_fail_postfit_projx0_pull__217->GetXaxis()->SetTitleFont(42);
   data_obs_fail_postfit_projx0_pull__217->GetYaxis()->SetTitle("(Data-Bkg)/#sigma");
   data_obs_fail_postfit_projx0_pull__217->GetYaxis()->SetNdivisions(306);
   data_obs_fail_postfit_projx0_pull__217->GetYaxis()->SetLabelFont(42);
   data_obs_fail_postfit_projx0_pull__217->GetYaxis()->SetLabelOffset(0.007);
   data_obs_fail_postfit_projx0_pull__217->GetYaxis()->SetLabelSize(0.13);
   data_obs_fail_postfit_projx0_pull__217->GetYaxis()->SetTitleSize(0.12);
   data_obs_fail_postfit_projx0_pull__217->GetYaxis()->SetTitleOffset(0.4);
   data_obs_fail_postfit_projx0_pull__217->GetYaxis()->SetTitleFont(42);
   data_obs_fail_postfit_projx0_pull__217->GetZaxis()->SetLabelFont(42);
   data_obs_fail_postfit_projx0_pull__217->GetZaxis()->SetLabelOffset(0.007);
   data_obs_fail_postfit_projx0_pull__217->GetZaxis()->SetLabelSize(0.05);
   data_obs_fail_postfit_projx0_pull__217->GetZaxis()->SetTitleSize(0.08);
   data_obs_fail_postfit_projx0_pull__217->GetZaxis()->SetTitleFont(42);
   data_obs_fail_postfit_projx0_pull__217->Draw("hist");
   data_obs_fail_postfit_projx0_sub->Modified();
   plots_fit_s/base_figs/postfit_projx0_fail_logy->cd();
   plots_fit_s/base_figs/postfit_projx0_fail_logy->Modified();
   plots_fit_s/base_figs/postfit_projx0_fail_logy->cd();
   plots_fit_s/base_figs/postfit_projx0_fail_logy->SetSelected(plots_fit_s/base_figs/postfit_projx0_fail_logy);
}
