void postfit_projy1_pass_logy()
{
//=========Macro generated from canvas: plots_fit_s/base_figs/postfit_projy1_pass_logy/plots_fit_s/base_figs/postfit_projy1_pass_logy
//=========  (Fri Jan 12 21:00:10 2024) by ROOT version 6.14/09
   TCanvas *plots_fit_s/base_figs/postfit_projy1_pass_logy = new TCanvas("plots_fit_s/base_figs/postfit_projy1_pass_logy", "plots_fit_s/base_figs/postfit_projy1_pass_logy",0,0,800,700);
   gStyle->SetOptFit(1);
   gStyle->SetOptStat(0);
   plots_fit_s/base_figs/postfit_projy1_pass_logy->SetHighLightColor(2);
   plots_fit_s/base_figs/postfit_projy1_pass_logy->Range(0,0,1,1);
   plots_fit_s/base_figs/postfit_projy1_pass_logy->SetFillColor(0);
   plots_fit_s/base_figs/postfit_projy1_pass_logy->SetBorderMode(0);
   plots_fit_s/base_figs/postfit_projy1_pass_logy->SetBorderSize(2);
   plots_fit_s/base_figs/postfit_projy1_pass_logy->SetTickx(1);
   plots_fit_s/base_figs/postfit_projy1_pass_logy->SetTicky(1);
   plots_fit_s/base_figs/postfit_projy1_pass_logy->SetLeftMargin(0.16);
   plots_fit_s/base_figs/postfit_projy1_pass_logy->SetRightMargin(0);
   plots_fit_s/base_figs/postfit_projy1_pass_logy->SetTopMargin(0);
   plots_fit_s/base_figs/postfit_projy1_pass_logy->SetBottomMargin(0);
   plots_fit_s/base_figs/postfit_projy1_pass_logy->SetFrameFillStyle(0);
   plots_fit_s/base_figs/postfit_projy1_pass_logy->SetFrameBorderMode(0);
  
// ------------>Primitives in pad: data_obs_pass_postfit_projy1_main
   TPad *data_obs_pass_postfit_projy1_main = new TPad("data_obs_pass_postfit_projy1_main", "data_obs_pass_postfit_projy1_main",0,0.35,1,1);
   data_obs_pass_postfit_projy1_main->Draw();
   data_obs_pass_postfit_projy1_main->cd();
   data_obs_pass_postfit_projy1_main->Range(17.30769,-3.370013,209.6154,5.880305);
   data_obs_pass_postfit_projy1_main->SetFillColor(0);
   data_obs_pass_postfit_projy1_main->SetBorderMode(0);
   data_obs_pass_postfit_projy1_main->SetBorderSize(2);
   data_obs_pass_postfit_projy1_main->SetLogy();
   data_obs_pass_postfit_projy1_main->SetTickx(1);
   data_obs_pass_postfit_projy1_main->SetTicky(1);
   data_obs_pass_postfit_projy1_main->SetLeftMargin(0.17);
   data_obs_pass_postfit_projy1_main->SetRightMargin(0.05);
   data_obs_pass_postfit_projy1_main->SetBottomMargin(0.04);
   data_obs_pass_postfit_projy1_main->SetFrameFillStyle(0);
   data_obs_pass_postfit_projy1_main->SetFrameBorderMode(0);
   data_obs_pass_postfit_projy1_main->SetFrameFillStyle(0);
   data_obs_pass_postfit_projy1_main->SetFrameBorderMode(0);
   Double_t xAxis507[2] = {50, 200}; 
   
   TH1D *data_obs_pass_postfit_projy1__323 = new TH1D("data_obs_pass_postfit_projy1__323","",1, xAxis507);
   data_obs_pass_postfit_projy1__323->SetBinContent(1,990);
   data_obs_pass_postfit_projy1__323->SetBinError(1,31.46427);
   data_obs_pass_postfit_projy1__323->SetMinimum(0.001);
   data_obs_pass_postfit_projy1__323->SetMaximum(90213.75);
   data_obs_pass_postfit_projy1__323->SetEntries(990);

   Int_t ci;      // for color index setting
   TColor *color; // for color definition with alpha
   ci = TColor::GetColor("#000000");
   data_obs_pass_postfit_projy1__323->SetLineColor(ci);
   data_obs_pass_postfit_projy1__323->SetLineStyle(0);

   ci = TColor::GetColor("#000000");
   data_obs_pass_postfit_projy1__323->SetMarkerColor(ci);
   data_obs_pass_postfit_projy1__323->SetMarkerStyle(8);
   data_obs_pass_postfit_projy1__323->GetXaxis()->SetTitle("p_{T}");
   data_obs_pass_postfit_projy1__323->GetXaxis()->SetLabelFont(42);
   data_obs_pass_postfit_projy1__323->GetXaxis()->SetLabelOffset(0.05);
   data_obs_pass_postfit_projy1__323->GetXaxis()->SetLabelSize(0.07);
   data_obs_pass_postfit_projy1__323->GetXaxis()->SetTitleSize(0.09);
   data_obs_pass_postfit_projy1__323->GetXaxis()->SetTitleOffset(1.15);
   data_obs_pass_postfit_projy1__323->GetXaxis()->SetTitleFont(42);
   data_obs_pass_postfit_projy1__323->GetYaxis()->SetTitle("Events / bin");
   data_obs_pass_postfit_projy1__323->GetYaxis()->SetNdivisions(508);
   data_obs_pass_postfit_projy1__323->GetYaxis()->SetLabelFont(42);
   data_obs_pass_postfit_projy1__323->GetYaxis()->SetLabelOffset(0.007);
   data_obs_pass_postfit_projy1__323->GetYaxis()->SetLabelSize(0.07);
   data_obs_pass_postfit_projy1__323->GetYaxis()->SetTitleSize(0.09);
   data_obs_pass_postfit_projy1__323->GetYaxis()->SetTitleOffset(0.8);
   data_obs_pass_postfit_projy1__323->GetYaxis()->SetTitleFont(42);
   data_obs_pass_postfit_projy1__323->GetZaxis()->SetLabelFont(42);
   data_obs_pass_postfit_projy1__323->GetZaxis()->SetLabelOffset(0.007);
   data_obs_pass_postfit_projy1__323->GetZaxis()->SetLabelSize(0.05);
   data_obs_pass_postfit_projy1__323->GetZaxis()->SetTitleSize(0.08);
   data_obs_pass_postfit_projy1__323->GetZaxis()->SetTitleFont(42);
   data_obs_pass_postfit_projy1__323->Draw("pe X0");
   
   THStack *postfit_projy1_pass_logy_stack = new THStack();
   postfit_projy1_pass_logy_stack->SetName("postfit_projy1_pass_logy_stack");
   postfit_projy1_pass_logy_stack->SetTitle("postfit_projy1_pass_logy_stack");
   postfit_projy1_pass_logy_stack->SetMinimum(0.001);
   Double_t xAxis508[2] = {50, 200}; 
   
   TH1F *postfit_projy1_pass_logy_stack_stack_93 = new TH1F("postfit_projy1_pass_logy_stack_stack_93","postfit_projy1_pass_logy_stack",1, xAxis508);
   postfit_projy1_pass_logy_stack_stack_93->SetMinimum(0.0002495095);
   postfit_projy1_pass_logy_stack_stack_93->SetMaximum(2284.386);
   postfit_projy1_pass_logy_stack_stack_93->SetDirectory(0);
   postfit_projy1_pass_logy_stack_stack_93->SetStats(0);
   postfit_projy1_pass_logy_stack_stack_93->SetLineStyle(0);
   postfit_projy1_pass_logy_stack_stack_93->GetXaxis()->SetLabelFont(42);
   postfit_projy1_pass_logy_stack_stack_93->GetXaxis()->SetLabelOffset(0.007);
   postfit_projy1_pass_logy_stack_stack_93->GetXaxis()->SetLabelSize(0.05);
   postfit_projy1_pass_logy_stack_stack_93->GetXaxis()->SetTitleSize(0.08);
   postfit_projy1_pass_logy_stack_stack_93->GetXaxis()->SetTitleOffset(0.9);
   postfit_projy1_pass_logy_stack_stack_93->GetXaxis()->SetTitleFont(42);
   postfit_projy1_pass_logy_stack_stack_93->GetYaxis()->SetNdivisions(508);
   postfit_projy1_pass_logy_stack_stack_93->GetYaxis()->SetLabelFont(42);
   postfit_projy1_pass_logy_stack_stack_93->GetYaxis()->SetLabelOffset(0.007);
   postfit_projy1_pass_logy_stack_stack_93->GetYaxis()->SetLabelSize(0.05);
   postfit_projy1_pass_logy_stack_stack_93->GetYaxis()->SetTitleSize(0.08);
   postfit_projy1_pass_logy_stack_stack_93->GetYaxis()->SetTitleOffset(1.25);
   postfit_projy1_pass_logy_stack_stack_93->GetYaxis()->SetTitleFont(42);
   postfit_projy1_pass_logy_stack_stack_93->GetZaxis()->SetLabelFont(42);
   postfit_projy1_pass_logy_stack_stack_93->GetZaxis()->SetLabelOffset(0.007);
   postfit_projy1_pass_logy_stack_stack_93->GetZaxis()->SetLabelSize(0.05);
   postfit_projy1_pass_logy_stack_stack_93->GetZaxis()->SetTitleSize(0.08);
   postfit_projy1_pass_logy_stack_stack_93->GetZaxis()->SetTitleFont(42);
   postfit_projy1_pass_logy_stack->SetHistogram(postfit_projy1_pass_logy_stack_stack_93);
   
   Double_t xAxis509[2] = {50, 200}; 
   
   TH1D *Background_0x0_pass_postfit_projy1_stack_1 = new TH1D("Background_0x0_pass_postfit_projy1_stack_1","Background, pass, postfit, 0.24-1.0",1, xAxis509);
   Background_0x0_pass_postfit_projy1_stack_1->SetBinContent(1,1025.185);
   Background_0x0_pass_postfit_projy1_stack_1->SetBinError(1,11.69012);
   Background_0x0_pass_postfit_projy1_stack_1->SetMinimum(0.001);
   Background_0x0_pass_postfit_projy1_stack_1->SetEntries(7690.714);

   ci = TColor::GetColor("#ffff00");
   Background_0x0_pass_postfit_projy1_stack_1->SetFillColor(ci);

   ci = 1321;
   color = new TColor(ci, 1, 1, 1, " ", 0);
   Background_0x0_pass_postfit_projy1_stack_1->SetLineColor(ci);
   Background_0x0_pass_postfit_projy1_stack_1->SetLineStyle(0);
   Background_0x0_pass_postfit_projy1_stack_1->GetXaxis()->SetTitle("p_{T}");
   Background_0x0_pass_postfit_projy1_stack_1->GetXaxis()->SetLabelFont(42);
   Background_0x0_pass_postfit_projy1_stack_1->GetXaxis()->SetLabelOffset(0.007);
   Background_0x0_pass_postfit_projy1_stack_1->GetXaxis()->SetLabelSize(0.05);
   Background_0x0_pass_postfit_projy1_stack_1->GetXaxis()->SetTitleSize(0.08);
   Background_0x0_pass_postfit_projy1_stack_1->GetXaxis()->SetTitleOffset(1.25);
   Background_0x0_pass_postfit_projy1_stack_1->GetXaxis()->SetTitleFont(42);
   Background_0x0_pass_postfit_projy1_stack_1->GetYaxis()->SetTitle("Events / bin");
   Background_0x0_pass_postfit_projy1_stack_1->GetYaxis()->SetLabelFont(42);
   Background_0x0_pass_postfit_projy1_stack_1->GetYaxis()->SetLabelOffset(0.007);
   Background_0x0_pass_postfit_projy1_stack_1->GetYaxis()->SetLabelSize(0.05);
   Background_0x0_pass_postfit_projy1_stack_1->GetYaxis()->SetTitleSize(0.08);
   Background_0x0_pass_postfit_projy1_stack_1->GetYaxis()->SetTitleOffset(1.25);
   Background_0x0_pass_postfit_projy1_stack_1->GetYaxis()->SetTitleFont(42);
   Background_0x0_pass_postfit_projy1_stack_1->GetZaxis()->SetLabelFont(42);
   Background_0x0_pass_postfit_projy1_stack_1->GetZaxis()->SetLabelOffset(0.007);
   Background_0x0_pass_postfit_projy1_stack_1->GetZaxis()->SetLabelSize(0.05);
   Background_0x0_pass_postfit_projy1_stack_1->GetZaxis()->SetTitleSize(0.08);
   Background_0x0_pass_postfit_projy1_stack_1->GetZaxis()->SetTitleFont(42);
   postfit_projy1_pass_logy_stack->Add(Background_0x0_pass_postfit_projy1_stack_1,"");
   postfit_projy1_pass_logy_stack->Draw("hist same");
   
   postfit_projy1_pass_logy_stack = new THStack();
   postfit_projy1_pass_logy_stack->SetName("postfit_projy1_pass_logy_stack");
   postfit_projy1_pass_logy_stack->SetTitle("postfit_projy1_pass_logy_stack");
   postfit_projy1_pass_logy_stack->SetMinimum(0.001);
   Double_t xAxis510[2] = {50, 200}; 
   
   TH1F *postfit_projy1_pass_logy_stack_stack_93_stack_94 = new TH1F("postfit_projy1_pass_logy_stack_stack_93_stack_94","postfit_projy1_pass_logy_stack",1, xAxis510);
   postfit_projy1_pass_logy_stack_stack_93_stack_94->SetMinimum(0.0002495095);
   postfit_projy1_pass_logy_stack_stack_93_stack_94->SetMaximum(2284.386);
   postfit_projy1_pass_logy_stack_stack_93_stack_94->SetDirectory(0);
   postfit_projy1_pass_logy_stack_stack_93_stack_94->SetStats(0);
   postfit_projy1_pass_logy_stack_stack_93_stack_94->SetLineStyle(0);
   postfit_projy1_pass_logy_stack_stack_93_stack_94->GetXaxis()->SetLabelFont(42);
   postfit_projy1_pass_logy_stack_stack_93_stack_94->GetXaxis()->SetLabelOffset(0.007);
   postfit_projy1_pass_logy_stack_stack_93_stack_94->GetXaxis()->SetLabelSize(0.05);
   postfit_projy1_pass_logy_stack_stack_93_stack_94->GetXaxis()->SetTitleSize(0.08);
   postfit_projy1_pass_logy_stack_stack_93_stack_94->GetXaxis()->SetTitleOffset(0.9);
   postfit_projy1_pass_logy_stack_stack_93_stack_94->GetXaxis()->SetTitleFont(42);
   postfit_projy1_pass_logy_stack_stack_93_stack_94->GetYaxis()->SetNdivisions(508);
   postfit_projy1_pass_logy_stack_stack_93_stack_94->GetYaxis()->SetLabelFont(42);
   postfit_projy1_pass_logy_stack_stack_93_stack_94->GetYaxis()->SetLabelOffset(0.007);
   postfit_projy1_pass_logy_stack_stack_93_stack_94->GetYaxis()->SetLabelSize(0.05);
   postfit_projy1_pass_logy_stack_stack_93_stack_94->GetYaxis()->SetTitleSize(0.08);
   postfit_projy1_pass_logy_stack_stack_93_stack_94->GetYaxis()->SetTitleOffset(1.25);
   postfit_projy1_pass_logy_stack_stack_93_stack_94->GetYaxis()->SetTitleFont(42);
   postfit_projy1_pass_logy_stack_stack_93_stack_94->GetZaxis()->SetLabelFont(42);
   postfit_projy1_pass_logy_stack_stack_93_stack_94->GetZaxis()->SetLabelOffset(0.007);
   postfit_projy1_pass_logy_stack_stack_93_stack_94->GetZaxis()->SetLabelSize(0.05);
   postfit_projy1_pass_logy_stack_stack_93_stack_94->GetZaxis()->SetTitleSize(0.08);
   postfit_projy1_pass_logy_stack_stack_93_stack_94->GetZaxis()->SetTitleFont(42);
   postfit_projy1_pass_logy_stack->SetHistogram(postfit_projy1_pass_logy_stack_stack_93_stack_94);
   
   Double_t xAxis511[2] = {50, 200}; 
   
   TH1D *Background_0x0_pass_postfit_projy1_stack_1_stack_1 = new TH1D("Background_0x0_pass_postfit_projy1_stack_1_stack_1","Background, pass, postfit, 0.24-1.0",1, xAxis511);
   Background_0x0_pass_postfit_projy1_stack_1_stack_1->SetBinContent(1,1025.185);
   Background_0x0_pass_postfit_projy1_stack_1_stack_1->SetBinError(1,11.69012);
   Background_0x0_pass_postfit_projy1_stack_1_stack_1->SetMinimum(0.001);
   Background_0x0_pass_postfit_projy1_stack_1_stack_1->SetEntries(7690.714);

   ci = TColor::GetColor("#ffff00");
   Background_0x0_pass_postfit_projy1_stack_1_stack_1->SetFillColor(ci);

   ci = 1321;
   color = new TColor(ci, 1, 1, 1, " ", 0);
   Background_0x0_pass_postfit_projy1_stack_1_stack_1->SetLineColor(ci);
   Background_0x0_pass_postfit_projy1_stack_1_stack_1->SetLineStyle(0);
   Background_0x0_pass_postfit_projy1_stack_1_stack_1->GetXaxis()->SetTitle("p_{T}");
   Background_0x0_pass_postfit_projy1_stack_1_stack_1->GetXaxis()->SetLabelFont(42);
   Background_0x0_pass_postfit_projy1_stack_1_stack_1->GetXaxis()->SetLabelOffset(0.007);
   Background_0x0_pass_postfit_projy1_stack_1_stack_1->GetXaxis()->SetLabelSize(0.05);
   Background_0x0_pass_postfit_projy1_stack_1_stack_1->GetXaxis()->SetTitleSize(0.08);
   Background_0x0_pass_postfit_projy1_stack_1_stack_1->GetXaxis()->SetTitleOffset(1.25);
   Background_0x0_pass_postfit_projy1_stack_1_stack_1->GetXaxis()->SetTitleFont(42);
   Background_0x0_pass_postfit_projy1_stack_1_stack_1->GetYaxis()->SetTitle("Events / bin");
   Background_0x0_pass_postfit_projy1_stack_1_stack_1->GetYaxis()->SetLabelFont(42);
   Background_0x0_pass_postfit_projy1_stack_1_stack_1->GetYaxis()->SetLabelOffset(0.007);
   Background_0x0_pass_postfit_projy1_stack_1_stack_1->GetYaxis()->SetLabelSize(0.05);
   Background_0x0_pass_postfit_projy1_stack_1_stack_1->GetYaxis()->SetTitleSize(0.08);
   Background_0x0_pass_postfit_projy1_stack_1_stack_1->GetYaxis()->SetTitleOffset(1.25);
   Background_0x0_pass_postfit_projy1_stack_1_stack_1->GetYaxis()->SetTitleFont(42);
   Background_0x0_pass_postfit_projy1_stack_1_stack_1->GetZaxis()->SetLabelFont(42);
   Background_0x0_pass_postfit_projy1_stack_1_stack_1->GetZaxis()->SetLabelOffset(0.007);
   Background_0x0_pass_postfit_projy1_stack_1_stack_1->GetZaxis()->SetLabelSize(0.05);
   Background_0x0_pass_postfit_projy1_stack_1_stack_1->GetZaxis()->SetTitleSize(0.08);
   Background_0x0_pass_postfit_projy1_stack_1_stack_1->GetZaxis()->SetTitleFont(42);
   postfit_projy1_pass_logy_stack->Add(Background_0x0_pass_postfit_projy1_stack_1_stack_1,"");
   postfit_projy1_pass_logy_stack->Draw("hist same");
   Double_t xAxis512[2] = {50, 200}; 
   
   TH1D *Signal_ppStaumI557_pass_postfit_projy1__324 = new TH1D("Signal_ppStaumI557_pass_postfit_projy1__324","HSCP signal, pass, postfit, 0.24-1.0",1, xAxis512);
   Signal_ppStaumI557_pass_postfit_projy1__324->SetBinContent(1,5.466118);
   Signal_ppStaumI557_pass_postfit_projy1__324->SetBinError(1,3.79449);
   Signal_ppStaumI557_pass_postfit_projy1__324->SetMinimum(0.001);
   Signal_ppStaumI557_pass_postfit_projy1__324->SetEntries(2.075158);
   Signal_ppStaumI557_pass_postfit_projy1__324->SetLineColor(2);
   Signal_ppStaumI557_pass_postfit_projy1__324->SetLineStyle(0);
   Signal_ppStaumI557_pass_postfit_projy1__324->GetXaxis()->SetTitle("p_{T}");
   Signal_ppStaumI557_pass_postfit_projy1__324->GetXaxis()->SetLabelFont(42);
   Signal_ppStaumI557_pass_postfit_projy1__324->GetXaxis()->SetLabelOffset(0.007);
   Signal_ppStaumI557_pass_postfit_projy1__324->GetXaxis()->SetLabelSize(0.05);
   Signal_ppStaumI557_pass_postfit_projy1__324->GetXaxis()->SetTitleSize(0.08);
   Signal_ppStaumI557_pass_postfit_projy1__324->GetXaxis()->SetTitleOffset(1.25);
   Signal_ppStaumI557_pass_postfit_projy1__324->GetXaxis()->SetTitleFont(42);
   Signal_ppStaumI557_pass_postfit_projy1__324->GetYaxis()->SetTitle("Events / bin");
   Signal_ppStaumI557_pass_postfit_projy1__324->GetYaxis()->SetLabelFont(42);
   Signal_ppStaumI557_pass_postfit_projy1__324->GetYaxis()->SetLabelOffset(0.007);
   Signal_ppStaumI557_pass_postfit_projy1__324->GetYaxis()->SetLabelSize(0.05);
   Signal_ppStaumI557_pass_postfit_projy1__324->GetYaxis()->SetTitleSize(0.08);
   Signal_ppStaumI557_pass_postfit_projy1__324->GetYaxis()->SetTitleOffset(1.25);
   Signal_ppStaumI557_pass_postfit_projy1__324->GetYaxis()->SetTitleFont(42);
   Signal_ppStaumI557_pass_postfit_projy1__324->GetZaxis()->SetLabelFont(42);
   Signal_ppStaumI557_pass_postfit_projy1__324->GetZaxis()->SetLabelOffset(0.007);
   Signal_ppStaumI557_pass_postfit_projy1__324->GetZaxis()->SetLabelSize(0.05);
   Signal_ppStaumI557_pass_postfit_projy1__324->GetZaxis()->SetTitleSize(0.08);
   Signal_ppStaumI557_pass_postfit_projy1__324->GetZaxis()->SetTitleFont(42);
   Signal_ppStaumI557_pass_postfit_projy1__324->Draw("hist same");
   Double_t xAxis513[2] = {50, 200}; 
   
   TH1D *TotalBkg_pass_postfit_projy1__325 = new TH1D("TotalBkg_pass_postfit_projy1__325","TotalBkg, pass, postfit, 0.24-1.0",1, xAxis513);
   TotalBkg_pass_postfit_projy1__325->SetBinContent(1,1025.185);
   TotalBkg_pass_postfit_projy1__325->SetBinError(1,12.53427);
   TotalBkg_pass_postfit_projy1__325->SetMinimum(0.001);
   TotalBkg_pass_postfit_projy1__325->SetEntries(6689.697);
   TotalBkg_pass_postfit_projy1__325->SetLineStyle(0);
   TotalBkg_pass_postfit_projy1__325->SetMarkerStyle(0);
   TotalBkg_pass_postfit_projy1__325->GetXaxis()->SetTitle("p_{T}");
   TotalBkg_pass_postfit_projy1__325->GetXaxis()->SetLabelFont(42);
   TotalBkg_pass_postfit_projy1__325->GetXaxis()->SetLabelOffset(0.007);
   TotalBkg_pass_postfit_projy1__325->GetXaxis()->SetLabelSize(0.05);
   TotalBkg_pass_postfit_projy1__325->GetXaxis()->SetTitleSize(0.08);
   TotalBkg_pass_postfit_projy1__325->GetXaxis()->SetTitleOffset(1.25);
   TotalBkg_pass_postfit_projy1__325->GetXaxis()->SetTitleFont(42);
   TotalBkg_pass_postfit_projy1__325->GetYaxis()->SetTitle("Events / bin");
   TotalBkg_pass_postfit_projy1__325->GetYaxis()->SetLabelFont(42);
   TotalBkg_pass_postfit_projy1__325->GetYaxis()->SetLabelOffset(0.007);
   TotalBkg_pass_postfit_projy1__325->GetYaxis()->SetLabelSize(0.05);
   TotalBkg_pass_postfit_projy1__325->GetYaxis()->SetTitleSize(0.08);
   TotalBkg_pass_postfit_projy1__325->GetYaxis()->SetTitleOffset(1.25);
   TotalBkg_pass_postfit_projy1__325->GetYaxis()->SetTitleFont(42);
   TotalBkg_pass_postfit_projy1__325->GetZaxis()->SetLabelFont(42);
   TotalBkg_pass_postfit_projy1__325->GetZaxis()->SetLabelOffset(0.007);
   TotalBkg_pass_postfit_projy1__325->GetZaxis()->SetLabelSize(0.05);
   TotalBkg_pass_postfit_projy1__325->GetZaxis()->SetTitleSize(0.08);
   TotalBkg_pass_postfit_projy1__325->GetZaxis()->SetTitleFont(42);
   TotalBkg_pass_postfit_projy1__325->Draw("hist same");
   Double_t xAxis514[2] = {50, 200}; 
   
   TH1D *TotalBkg_pass_postfit_projy1__326 = new TH1D("TotalBkg_pass_postfit_projy1__326","TotalBkg, pass, postfit, 0.24-1.0",1, xAxis514);
   TotalBkg_pass_postfit_projy1__326->SetBinContent(1,1025.185);
   TotalBkg_pass_postfit_projy1__326->SetBinError(1,12.53427);
   TotalBkg_pass_postfit_projy1__326->SetMinimum(0.001);
   TotalBkg_pass_postfit_projy1__326->SetEntries(6689.697);
   TotalBkg_pass_postfit_projy1__326->SetFillColor(1);
   TotalBkg_pass_postfit_projy1__326->SetFillStyle(3354);
   TotalBkg_pass_postfit_projy1__326->SetLineStyle(0);
   TotalBkg_pass_postfit_projy1__326->SetLineWidth(0);
   TotalBkg_pass_postfit_projy1__326->SetMarkerStyle(0);
   TotalBkg_pass_postfit_projy1__326->GetXaxis()->SetTitle("p_{T}");
   TotalBkg_pass_postfit_projy1__326->GetXaxis()->SetLabelFont(42);
   TotalBkg_pass_postfit_projy1__326->GetXaxis()->SetLabelOffset(0.007);
   TotalBkg_pass_postfit_projy1__326->GetXaxis()->SetLabelSize(0.05);
   TotalBkg_pass_postfit_projy1__326->GetXaxis()->SetTitleSize(0.08);
   TotalBkg_pass_postfit_projy1__326->GetXaxis()->SetTitleOffset(1.25);
   TotalBkg_pass_postfit_projy1__326->GetXaxis()->SetTitleFont(42);
   TotalBkg_pass_postfit_projy1__326->GetYaxis()->SetTitle("Events / bin");
   TotalBkg_pass_postfit_projy1__326->GetYaxis()->SetLabelFont(42);
   TotalBkg_pass_postfit_projy1__326->GetYaxis()->SetLabelOffset(0.007);
   TotalBkg_pass_postfit_projy1__326->GetYaxis()->SetLabelSize(0.05);
   TotalBkg_pass_postfit_projy1__326->GetYaxis()->SetTitleSize(0.08);
   TotalBkg_pass_postfit_projy1__326->GetYaxis()->SetTitleOffset(1.25);
   TotalBkg_pass_postfit_projy1__326->GetYaxis()->SetTitleFont(42);
   TotalBkg_pass_postfit_projy1__326->GetZaxis()->SetLabelFont(42);
   TotalBkg_pass_postfit_projy1__326->GetZaxis()->SetLabelOffset(0.007);
   TotalBkg_pass_postfit_projy1__326->GetZaxis()->SetLabelSize(0.05);
   TotalBkg_pass_postfit_projy1__326->GetZaxis()->SetTitleSize(0.08);
   TotalBkg_pass_postfit_projy1__326->GetZaxis()->SetTitleFont(42);
   TotalBkg_pass_postfit_projy1__326->Draw("e2 same");
   Double_t xAxis515[2] = {50, 200}; 
   
   TH1D *data_obs_pass_postfit_projy1__327 = new TH1D("data_obs_pass_postfit_projy1__327","",1, xAxis515);
   data_obs_pass_postfit_projy1__327->SetBinContent(1,990);
   data_obs_pass_postfit_projy1__327->SetBinError(1,31.46427);
   data_obs_pass_postfit_projy1__327->SetMinimum(0.001);
   data_obs_pass_postfit_projy1__327->SetMaximum(90213.75);
   data_obs_pass_postfit_projy1__327->SetEntries(990);

   ci = TColor::GetColor("#000000");
   data_obs_pass_postfit_projy1__327->SetLineColor(ci);
   data_obs_pass_postfit_projy1__327->SetLineStyle(0);

   ci = TColor::GetColor("#000000");
   data_obs_pass_postfit_projy1__327->SetMarkerColor(ci);
   data_obs_pass_postfit_projy1__327->SetMarkerStyle(8);
   data_obs_pass_postfit_projy1__327->GetXaxis()->SetTitle("p_{T}");
   data_obs_pass_postfit_projy1__327->GetXaxis()->SetLabelFont(42);
   data_obs_pass_postfit_projy1__327->GetXaxis()->SetLabelOffset(0.05);
   data_obs_pass_postfit_projy1__327->GetXaxis()->SetLabelSize(0.07);
   data_obs_pass_postfit_projy1__327->GetXaxis()->SetTitleSize(0.09);
   data_obs_pass_postfit_projy1__327->GetXaxis()->SetTitleOffset(1.15);
   data_obs_pass_postfit_projy1__327->GetXaxis()->SetTitleFont(42);
   data_obs_pass_postfit_projy1__327->GetYaxis()->SetTitle("Events / bin");
   data_obs_pass_postfit_projy1__327->GetYaxis()->SetNdivisions(508);
   data_obs_pass_postfit_projy1__327->GetYaxis()->SetLabelFont(42);
   data_obs_pass_postfit_projy1__327->GetYaxis()->SetLabelOffset(0.007);
   data_obs_pass_postfit_projy1__327->GetYaxis()->SetLabelSize(0.07);
   data_obs_pass_postfit_projy1__327->GetYaxis()->SetTitleSize(0.09);
   data_obs_pass_postfit_projy1__327->GetYaxis()->SetTitleOffset(0.8);
   data_obs_pass_postfit_projy1__327->GetYaxis()->SetTitleFont(42);
   data_obs_pass_postfit_projy1__327->GetZaxis()->SetLabelFont(42);
   data_obs_pass_postfit_projy1__327->GetZaxis()->SetLabelOffset(0.007);
   data_obs_pass_postfit_projy1__327->GetZaxis()->SetLabelSize(0.05);
   data_obs_pass_postfit_projy1__327->GetZaxis()->SetTitleSize(0.08);
   data_obs_pass_postfit_projy1__327->GetZaxis()->SetTitleFont(42);
   data_obs_pass_postfit_projy1__327->Draw("pe X0 same");
   
   TLegend *leg = new TLegend(0.65,0.64,0.9,0.88,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(1001);
   TLegendEntry *entry=leg->AddEntry("data_obs_pass_postfit_projy1","Data","pe X0");

   ci = TColor::GetColor("#000000");
   entry->SetLineColor(ci);
   entry->SetLineWidth(1);

   ci = TColor::GetColor("#000000");
   entry->SetMarkerColor(ci);
   entry->SetMarkerStyle(8);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("TotalBkg_pass_postfit_projy1","Total bkg unc.","F");
   entry->SetFillColor(1);
   entry->SetFillStyle(3354);
   entry->SetLineColor(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("Signal_ppStau-557_pass_postfit_projy1","HSCP signal","L");
   entry->SetLineColor(2);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("Background_0x0_pass_postfit_projy1_stack_1_stack_1","Background","f");

   ci = TColor::GetColor("#ffff00");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = 1321;
   color = new TColor(ci, 1, 1, 1, " ", 0);
   entry->SetLineColor(ci);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   leg->Draw();
   Double_t xAxis516[2] = {50, 200}; 
   
   TH1D *data_obs_pass_postfit_projy1_copy__328 = new TH1D("data_obs_pass_postfit_projy1_copy__328","",1, xAxis516);
   data_obs_pass_postfit_projy1_copy__328->SetBinContent(1,990);
   data_obs_pass_postfit_projy1_copy__328->SetBinError(1,31.46427);
   data_obs_pass_postfit_projy1_copy__328->SetMinimum(0.001);
   data_obs_pass_postfit_projy1_copy__328->SetMaximum(90213.75);
   data_obs_pass_postfit_projy1_copy__328->SetEntries(990);
   data_obs_pass_postfit_projy1_copy__328->SetDirectory(0);

   ci = TColor::GetColor("#000000");
   data_obs_pass_postfit_projy1_copy__328->SetLineColor(ci);
   data_obs_pass_postfit_projy1_copy__328->SetLineStyle(0);

   ci = TColor::GetColor("#000000");
   data_obs_pass_postfit_projy1_copy__328->SetMarkerColor(ci);
   data_obs_pass_postfit_projy1_copy__328->SetMarkerStyle(8);
   data_obs_pass_postfit_projy1_copy__328->GetXaxis()->SetTitle("p_{T}");
   data_obs_pass_postfit_projy1_copy__328->GetXaxis()->SetLabelFont(42);
   data_obs_pass_postfit_projy1_copy__328->GetXaxis()->SetLabelOffset(0.05);
   data_obs_pass_postfit_projy1_copy__328->GetXaxis()->SetLabelSize(0.07);
   data_obs_pass_postfit_projy1_copy__328->GetXaxis()->SetTitleSize(0.09);
   data_obs_pass_postfit_projy1_copy__328->GetXaxis()->SetTitleOffset(1.15);
   data_obs_pass_postfit_projy1_copy__328->GetXaxis()->SetTitleFont(42);
   data_obs_pass_postfit_projy1_copy__328->GetYaxis()->SetTitle("Events / bin");
   data_obs_pass_postfit_projy1_copy__328->GetYaxis()->SetNdivisions(508);
   data_obs_pass_postfit_projy1_copy__328->GetYaxis()->SetLabelFont(42);
   data_obs_pass_postfit_projy1_copy__328->GetYaxis()->SetLabelOffset(0.007);
   data_obs_pass_postfit_projy1_copy__328->GetYaxis()->SetLabelSize(0.07);
   data_obs_pass_postfit_projy1_copy__328->GetYaxis()->SetTitleSize(0.09);
   data_obs_pass_postfit_projy1_copy__328->GetYaxis()->SetTitleOffset(0.8);
   data_obs_pass_postfit_projy1_copy__328->GetYaxis()->SetTitleFont(42);
   data_obs_pass_postfit_projy1_copy__328->GetZaxis()->SetLabelFont(42);
   data_obs_pass_postfit_projy1_copy__328->GetZaxis()->SetLabelOffset(0.007);
   data_obs_pass_postfit_projy1_copy__328->GetZaxis()->SetLabelSize(0.05);
   data_obs_pass_postfit_projy1_copy__328->GetZaxis()->SetTitleSize(0.08);
   data_obs_pass_postfit_projy1_copy__328->GetZaxis()->SetTitleFont(42);
   data_obs_pass_postfit_projy1_copy__328->Draw("sameaxis");
   TLatex *   tex = new TLatex(0.21,0.83,"55 < p_{T} < 200 GeV, F^{Pixels}_{i} > 0.9");
tex->SetNDC();
   tex->SetTextAlign(12);
   tex->SetTextFont(42);
   tex->SetTextSize(0.06);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.17,0.92,"CMS");
tex->SetNDC();
   tex->SetTextFont(61);
   tex->SetTextSize(0.0675);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.25,0.92,"Preliminary");
tex->SetNDC();
   tex->SetTextFont(52);
   tex->SetTextSize(0.0485);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.95,0.92,"101 fb^{-1} (13 TeV)");
tex->SetNDC();
   tex->SetTextAlign(31);
   tex->SetTextFont(42);
   tex->SetTextSize(0.07);
   tex->SetLineWidth(2);
   tex->Draw();
   data_obs_pass_postfit_projy1_main->Modified();
   plots_fit_s/base_figs/postfit_projy1_pass_logy->cd();
  
// ------------>Primitives in pad: data_obs_pass_postfit_projy1_sub
   TPad *data_obs_pass_postfit_projy1_sub = new TPad("data_obs_pass_postfit_projy1_sub", "data_obs_pass_postfit_projy1_sub",0,0,1,0.35);
   data_obs_pass_postfit_projy1_sub->Draw();
   data_obs_pass_postfit_projy1_sub->cd();
   data_obs_pass_postfit_projy1_sub->Range(17.30769,-6.023077,209.6154,2.9);
   data_obs_pass_postfit_projy1_sub->SetFillColor(0);
   data_obs_pass_postfit_projy1_sub->SetBorderMode(0);
   data_obs_pass_postfit_projy1_sub->SetBorderSize(2);
   data_obs_pass_postfit_projy1_sub->SetTickx(1);
   data_obs_pass_postfit_projy1_sub->SetTicky(1);
   data_obs_pass_postfit_projy1_sub->SetLeftMargin(0.17);
   data_obs_pass_postfit_projy1_sub->SetRightMargin(0.05);
   data_obs_pass_postfit_projy1_sub->SetTopMargin(0);
   data_obs_pass_postfit_projy1_sub->SetBottomMargin(0.35);
   data_obs_pass_postfit_projy1_sub->SetFrameFillStyle(0);
   data_obs_pass_postfit_projy1_sub->SetFrameBorderMode(0);
   data_obs_pass_postfit_projy1_sub->SetFrameFillStyle(0);
   data_obs_pass_postfit_projy1_sub->SetFrameBorderMode(0);
   Double_t xAxis517[2] = {50, 200}; 
   
   TH1D *data_obs_pass_postfit_projy1_pull__329 = new TH1D("data_obs_pass_postfit_projy1_pull__329","",1, xAxis517);
   data_obs_pass_postfit_projy1_pull__329->SetBinContent(1,-1.01077);
   data_obs_pass_postfit_projy1_pull__329->SetBinError(1,33.86898);
   data_obs_pass_postfit_projy1_pull__329->SetMinimum(-2.9);
   data_obs_pass_postfit_projy1_pull__329->SetMaximum(2.9);
   data_obs_pass_postfit_projy1_pull__329->SetEntries(36.18474);
   data_obs_pass_postfit_projy1_pull__329->SetStats(0);

   ci = TColor::GetColor("#0000ff");
   data_obs_pass_postfit_projy1_pull__329->SetFillColor(ci);

   ci = TColor::GetColor("#000000");
   data_obs_pass_postfit_projy1_pull__329->SetLineColor(ci);
   data_obs_pass_postfit_projy1_pull__329->SetLineStyle(0);

   ci = TColor::GetColor("#000000");
   data_obs_pass_postfit_projy1_pull__329->SetMarkerColor(ci);
   data_obs_pass_postfit_projy1_pull__329->SetMarkerStyle(8);
   data_obs_pass_postfit_projy1_pull__329->GetXaxis()->SetTitle("p_{T}");
   data_obs_pass_postfit_projy1_pull__329->GetXaxis()->SetLabelFont(42);
   data_obs_pass_postfit_projy1_pull__329->GetXaxis()->SetLabelOffset(0.05);
   data_obs_pass_postfit_projy1_pull__329->GetXaxis()->SetLabelSize(0.13);
   data_obs_pass_postfit_projy1_pull__329->GetXaxis()->SetTitleSize(0.15);
   data_obs_pass_postfit_projy1_pull__329->GetXaxis()->SetTitleOffset(1.15);
   data_obs_pass_postfit_projy1_pull__329->GetXaxis()->SetTitleFont(42);
   data_obs_pass_postfit_projy1_pull__329->GetYaxis()->SetTitle("(Data-Bkg)/#sigma");
   data_obs_pass_postfit_projy1_pull__329->GetYaxis()->SetNdivisions(306);
   data_obs_pass_postfit_projy1_pull__329->GetYaxis()->SetLabelFont(42);
   data_obs_pass_postfit_projy1_pull__329->GetYaxis()->SetLabelOffset(0.007);
   data_obs_pass_postfit_projy1_pull__329->GetYaxis()->SetLabelSize(0.13);
   data_obs_pass_postfit_projy1_pull__329->GetYaxis()->SetTitleSize(0.12);
   data_obs_pass_postfit_projy1_pull__329->GetYaxis()->SetTitleOffset(0.4);
   data_obs_pass_postfit_projy1_pull__329->GetYaxis()->SetTitleFont(42);
   data_obs_pass_postfit_projy1_pull__329->GetZaxis()->SetLabelFont(42);
   data_obs_pass_postfit_projy1_pull__329->GetZaxis()->SetLabelOffset(0.007);
   data_obs_pass_postfit_projy1_pull__329->GetZaxis()->SetLabelSize(0.05);
   data_obs_pass_postfit_projy1_pull__329->GetZaxis()->SetTitleSize(0.08);
   data_obs_pass_postfit_projy1_pull__329->GetZaxis()->SetTitleFont(42);
   data_obs_pass_postfit_projy1_pull__329->Draw("hist");
   data_obs_pass_postfit_projy1_sub->Modified();
   plots_fit_s/base_figs/postfit_projy1_pass_logy->cd();
   plots_fit_s/base_figs/postfit_projy1_pass_logy->Modified();
   plots_fit_s/base_figs/postfit_projy1_pass_logy->cd();
   plots_fit_s/base_figs/postfit_projy1_pass_logy->SetSelected(plots_fit_s/base_figs/postfit_projy1_pass_logy);
}
