void postfit_projy2_fail()
{
//=========Macro generated from canvas: plots_fit_s/base_figs/postfit_projy2_fail/plots_fit_s/base_figs/postfit_projy2_fail
//=========  (Fri Jan 12 21:00:08 2024) by ROOT version 6.14/09
   TCanvas *plots_fit_s/base_figs/postfit_projy2_fail = new TCanvas("plots_fit_s/base_figs/postfit_projy2_fail", "plots_fit_s/base_figs/postfit_projy2_fail",0,0,800,700);
   gStyle->SetOptFit(1);
   gStyle->SetOptStat(0);
   plots_fit_s/base_figs/postfit_projy2_fail->SetHighLightColor(2);
   plots_fit_s/base_figs/postfit_projy2_fail->Range(0,0,1,1);
   plots_fit_s/base_figs/postfit_projy2_fail->SetFillColor(0);
   plots_fit_s/base_figs/postfit_projy2_fail->SetBorderMode(0);
   plots_fit_s/base_figs/postfit_projy2_fail->SetBorderSize(2);
   plots_fit_s/base_figs/postfit_projy2_fail->SetTickx(1);
   plots_fit_s/base_figs/postfit_projy2_fail->SetTicky(1);
   plots_fit_s/base_figs/postfit_projy2_fail->SetLeftMargin(0.16);
   plots_fit_s/base_figs/postfit_projy2_fail->SetRightMargin(0);
   plots_fit_s/base_figs/postfit_projy2_fail->SetTopMargin(0);
   plots_fit_s/base_figs/postfit_projy2_fail->SetBottomMargin(0);
   plots_fit_s/base_figs/postfit_projy2_fail->SetFrameFillStyle(0);
   plots_fit_s/base_figs/postfit_projy2_fail->SetFrameBorderMode(0);
  
// ------------>Primitives in pad: data_obs_fail_postfit_projy2_main
   TPad *data_obs_fail_postfit_projy2_main = new TPad("data_obs_fail_postfit_projy2_main", "data_obs_fail_postfit_projy2_main",0,0.35,1,1);
   data_obs_fail_postfit_projy2_main->Draw();
   data_obs_fail_postfit_projy2_main->cd();
   data_obs_fail_postfit_projy2_main->Range(17.30769,-0.04651163,209.6154,1.116279);
   data_obs_fail_postfit_projy2_main->SetFillColor(0);
   data_obs_fail_postfit_projy2_main->SetBorderMode(0);
   data_obs_fail_postfit_projy2_main->SetBorderSize(2);
   data_obs_fail_postfit_projy2_main->SetTickx(1);
   data_obs_fail_postfit_projy2_main->SetTicky(1);
   data_obs_fail_postfit_projy2_main->SetLeftMargin(0.17);
   data_obs_fail_postfit_projy2_main->SetRightMargin(0.05);
   data_obs_fail_postfit_projy2_main->SetBottomMargin(0.04);
   data_obs_fail_postfit_projy2_main->SetFrameFillStyle(0);
   data_obs_fail_postfit_projy2_main->SetFrameBorderMode(0);
   data_obs_fail_postfit_projy2_main->SetFrameFillStyle(0);
   data_obs_fail_postfit_projy2_main->SetFrameBorderMode(0);
   Double_t xAxis320[2] = {50, 200}; 
   
   TH1D *data_obs_fail_postfit_projy2__204 = new TH1D("data_obs_fail_postfit_projy2__204","",1, xAxis320);
   data_obs_fail_postfit_projy2__204->SetMinimum(0);
   data_obs_fail_postfit_projy2__204->SetMaximum(0);

   Int_t ci;      // for color index setting
   TColor *color; // for color definition with alpha
   ci = TColor::GetColor("#000000");
   data_obs_fail_postfit_projy2__204->SetLineColor(ci);
   data_obs_fail_postfit_projy2__204->SetLineStyle(0);

   ci = TColor::GetColor("#000000");
   data_obs_fail_postfit_projy2__204->SetMarkerColor(ci);
   data_obs_fail_postfit_projy2__204->SetMarkerStyle(8);
   data_obs_fail_postfit_projy2__204->GetXaxis()->SetTitle("p_{T}");
   data_obs_fail_postfit_projy2__204->GetXaxis()->SetLabelFont(42);
   data_obs_fail_postfit_projy2__204->GetXaxis()->SetLabelOffset(0.05);
   data_obs_fail_postfit_projy2__204->GetXaxis()->SetLabelSize(0.07);
   data_obs_fail_postfit_projy2__204->GetXaxis()->SetTitleSize(0.09);
   data_obs_fail_postfit_projy2__204->GetXaxis()->SetTitleOffset(1.15);
   data_obs_fail_postfit_projy2__204->GetXaxis()->SetTitleFont(42);
   data_obs_fail_postfit_projy2__204->GetYaxis()->SetTitle("Events / bin");
   data_obs_fail_postfit_projy2__204->GetYaxis()->SetNdivisions(508);
   data_obs_fail_postfit_projy2__204->GetYaxis()->SetLabelFont(42);
   data_obs_fail_postfit_projy2__204->GetYaxis()->SetLabelOffset(0.007);
   data_obs_fail_postfit_projy2__204->GetYaxis()->SetLabelSize(0.07);
   data_obs_fail_postfit_projy2__204->GetYaxis()->SetTitleSize(0.09);
   data_obs_fail_postfit_projy2__204->GetYaxis()->SetTitleOffset(0.8);
   data_obs_fail_postfit_projy2__204->GetYaxis()->SetTitleFont(42);
   data_obs_fail_postfit_projy2__204->GetZaxis()->SetLabelFont(42);
   data_obs_fail_postfit_projy2__204->GetZaxis()->SetLabelOffset(0.007);
   data_obs_fail_postfit_projy2__204->GetZaxis()->SetLabelSize(0.05);
   data_obs_fail_postfit_projy2__204->GetZaxis()->SetTitleSize(0.08);
   data_obs_fail_postfit_projy2__204->GetZaxis()->SetTitleFont(42);
   data_obs_fail_postfit_projy2__204->Draw("pe X0");
   
   THStack *postfit_projy2_fail_stack = new THStack();
   postfit_projy2_fail_stack->SetName("postfit_projy2_fail_stack");
   postfit_projy2_fail_stack->SetTitle("postfit_projy2_fail_stack");
   Double_t xAxis321[2] = {50, 200}; 
   
   TH1F *postfit_projy2_fail_stack_stack_59 = new TH1F("postfit_projy2_fail_stack_stack_59","postfit_projy2_fail_stack",1, xAxis321);
   postfit_projy2_fail_stack_stack_59->SetMinimum(0);
   postfit_projy2_fail_stack_stack_59->SetMaximum(0);
   postfit_projy2_fail_stack_stack_59->SetDirectory(0);
   postfit_projy2_fail_stack_stack_59->SetStats(0);
   postfit_projy2_fail_stack_stack_59->SetLineStyle(0);
   postfit_projy2_fail_stack_stack_59->GetXaxis()->SetLabelFont(42);
   postfit_projy2_fail_stack_stack_59->GetXaxis()->SetLabelOffset(0.007);
   postfit_projy2_fail_stack_stack_59->GetXaxis()->SetLabelSize(0.05);
   postfit_projy2_fail_stack_stack_59->GetXaxis()->SetTitleSize(0.08);
   postfit_projy2_fail_stack_stack_59->GetXaxis()->SetTitleOffset(0.9);
   postfit_projy2_fail_stack_stack_59->GetXaxis()->SetTitleFont(42);
   postfit_projy2_fail_stack_stack_59->GetYaxis()->SetNdivisions(508);
   postfit_projy2_fail_stack_stack_59->GetYaxis()->SetLabelFont(42);
   postfit_projy2_fail_stack_stack_59->GetYaxis()->SetLabelOffset(0.007);
   postfit_projy2_fail_stack_stack_59->GetYaxis()->SetLabelSize(0.05);
   postfit_projy2_fail_stack_stack_59->GetYaxis()->SetTitleSize(0.08);
   postfit_projy2_fail_stack_stack_59->GetYaxis()->SetTitleOffset(1.25);
   postfit_projy2_fail_stack_stack_59->GetYaxis()->SetTitleFont(42);
   postfit_projy2_fail_stack_stack_59->GetZaxis()->SetLabelFont(42);
   postfit_projy2_fail_stack_stack_59->GetZaxis()->SetLabelOffset(0.007);
   postfit_projy2_fail_stack_stack_59->GetZaxis()->SetLabelSize(0.05);
   postfit_projy2_fail_stack_stack_59->GetZaxis()->SetTitleSize(0.08);
   postfit_projy2_fail_stack_stack_59->GetZaxis()->SetTitleFont(42);
   postfit_projy2_fail_stack->SetHistogram(postfit_projy2_fail_stack_stack_59);
   
   Double_t xAxis322[2] = {50, 200}; 
   
   TH1D *Background_fail_postfit_projy2_stack_1 = new TH1D("Background_fail_postfit_projy2_stack_1","Background, fail, postfit, 1.0-1.0",1, xAxis322);
   Background_fail_postfit_projy2_stack_1->SetMinimum(0);

   ci = TColor::GetColor("#ffff00");
   Background_fail_postfit_projy2_stack_1->SetFillColor(ci);

   ci = 1310;
   color = new TColor(ci, 1, 1, 1, " ", 0);
   Background_fail_postfit_projy2_stack_1->SetLineColor(ci);
   Background_fail_postfit_projy2_stack_1->SetLineStyle(0);
   Background_fail_postfit_projy2_stack_1->GetXaxis()->SetTitle("p_{T}");
   Background_fail_postfit_projy2_stack_1->GetXaxis()->SetLabelFont(42);
   Background_fail_postfit_projy2_stack_1->GetXaxis()->SetLabelOffset(0.007);
   Background_fail_postfit_projy2_stack_1->GetXaxis()->SetLabelSize(0.05);
   Background_fail_postfit_projy2_stack_1->GetXaxis()->SetTitleSize(0.08);
   Background_fail_postfit_projy2_stack_1->GetXaxis()->SetTitleOffset(1.25);
   Background_fail_postfit_projy2_stack_1->GetXaxis()->SetTitleFont(42);
   Background_fail_postfit_projy2_stack_1->GetYaxis()->SetTitle("Events / bin");
   Background_fail_postfit_projy2_stack_1->GetYaxis()->SetLabelFont(42);
   Background_fail_postfit_projy2_stack_1->GetYaxis()->SetLabelOffset(0.007);
   Background_fail_postfit_projy2_stack_1->GetYaxis()->SetLabelSize(0.05);
   Background_fail_postfit_projy2_stack_1->GetYaxis()->SetTitleSize(0.08);
   Background_fail_postfit_projy2_stack_1->GetYaxis()->SetTitleOffset(1.25);
   Background_fail_postfit_projy2_stack_1->GetYaxis()->SetTitleFont(42);
   Background_fail_postfit_projy2_stack_1->GetZaxis()->SetLabelFont(42);
   Background_fail_postfit_projy2_stack_1->GetZaxis()->SetLabelOffset(0.007);
   Background_fail_postfit_projy2_stack_1->GetZaxis()->SetLabelSize(0.05);
   Background_fail_postfit_projy2_stack_1->GetZaxis()->SetTitleSize(0.08);
   Background_fail_postfit_projy2_stack_1->GetZaxis()->SetTitleFont(42);
   postfit_projy2_fail_stack->Add(Background_fail_postfit_projy2_stack_1,"");
   postfit_projy2_fail_stack->Draw("hist same");
   
   postfit_projy2_fail_stack = new THStack();
   postfit_projy2_fail_stack->SetName("postfit_projy2_fail_stack");
   postfit_projy2_fail_stack->SetTitle("postfit_projy2_fail_stack");
   Double_t xAxis323[2] = {50, 200}; 
   
   TH1F *postfit_projy2_fail_stack_stack_59_stack_60 = new TH1F("postfit_projy2_fail_stack_stack_59_stack_60","postfit_projy2_fail_stack",1, xAxis323);
   postfit_projy2_fail_stack_stack_59_stack_60->SetMinimum(0);
   postfit_projy2_fail_stack_stack_59_stack_60->SetMaximum(0);
   postfit_projy2_fail_stack_stack_59_stack_60->SetDirectory(0);
   postfit_projy2_fail_stack_stack_59_stack_60->SetStats(0);
   postfit_projy2_fail_stack_stack_59_stack_60->SetLineStyle(0);
   postfit_projy2_fail_stack_stack_59_stack_60->GetXaxis()->SetLabelFont(42);
   postfit_projy2_fail_stack_stack_59_stack_60->GetXaxis()->SetLabelOffset(0.007);
   postfit_projy2_fail_stack_stack_59_stack_60->GetXaxis()->SetLabelSize(0.05);
   postfit_projy2_fail_stack_stack_59_stack_60->GetXaxis()->SetTitleSize(0.08);
   postfit_projy2_fail_stack_stack_59_stack_60->GetXaxis()->SetTitleOffset(0.9);
   postfit_projy2_fail_stack_stack_59_stack_60->GetXaxis()->SetTitleFont(42);
   postfit_projy2_fail_stack_stack_59_stack_60->GetYaxis()->SetNdivisions(508);
   postfit_projy2_fail_stack_stack_59_stack_60->GetYaxis()->SetLabelFont(42);
   postfit_projy2_fail_stack_stack_59_stack_60->GetYaxis()->SetLabelOffset(0.007);
   postfit_projy2_fail_stack_stack_59_stack_60->GetYaxis()->SetLabelSize(0.05);
   postfit_projy2_fail_stack_stack_59_stack_60->GetYaxis()->SetTitleSize(0.08);
   postfit_projy2_fail_stack_stack_59_stack_60->GetYaxis()->SetTitleOffset(1.25);
   postfit_projy2_fail_stack_stack_59_stack_60->GetYaxis()->SetTitleFont(42);
   postfit_projy2_fail_stack_stack_59_stack_60->GetZaxis()->SetLabelFont(42);
   postfit_projy2_fail_stack_stack_59_stack_60->GetZaxis()->SetLabelOffset(0.007);
   postfit_projy2_fail_stack_stack_59_stack_60->GetZaxis()->SetLabelSize(0.05);
   postfit_projy2_fail_stack_stack_59_stack_60->GetZaxis()->SetTitleSize(0.08);
   postfit_projy2_fail_stack_stack_59_stack_60->GetZaxis()->SetTitleFont(42);
   postfit_projy2_fail_stack->SetHistogram(postfit_projy2_fail_stack_stack_59_stack_60);
   
   Double_t xAxis324[2] = {50, 200}; 
   
   TH1D *Background_fail_postfit_projy2_stack_1_stack_1 = new TH1D("Background_fail_postfit_projy2_stack_1_stack_1","Background, fail, postfit, 1.0-1.0",1, xAxis324);
   Background_fail_postfit_projy2_stack_1_stack_1->SetMinimum(0);

   ci = TColor::GetColor("#ffff00");
   Background_fail_postfit_projy2_stack_1_stack_1->SetFillColor(ci);

   ci = 1310;
   color = new TColor(ci, 1, 1, 1, " ", 0);
   Background_fail_postfit_projy2_stack_1_stack_1->SetLineColor(ci);
   Background_fail_postfit_projy2_stack_1_stack_1->SetLineStyle(0);
   Background_fail_postfit_projy2_stack_1_stack_1->GetXaxis()->SetTitle("p_{T}");
   Background_fail_postfit_projy2_stack_1_stack_1->GetXaxis()->SetLabelFont(42);
   Background_fail_postfit_projy2_stack_1_stack_1->GetXaxis()->SetLabelOffset(0.007);
   Background_fail_postfit_projy2_stack_1_stack_1->GetXaxis()->SetLabelSize(0.05);
   Background_fail_postfit_projy2_stack_1_stack_1->GetXaxis()->SetTitleSize(0.08);
   Background_fail_postfit_projy2_stack_1_stack_1->GetXaxis()->SetTitleOffset(1.25);
   Background_fail_postfit_projy2_stack_1_stack_1->GetXaxis()->SetTitleFont(42);
   Background_fail_postfit_projy2_stack_1_stack_1->GetYaxis()->SetTitle("Events / bin");
   Background_fail_postfit_projy2_stack_1_stack_1->GetYaxis()->SetLabelFont(42);
   Background_fail_postfit_projy2_stack_1_stack_1->GetYaxis()->SetLabelOffset(0.007);
   Background_fail_postfit_projy2_stack_1_stack_1->GetYaxis()->SetLabelSize(0.05);
   Background_fail_postfit_projy2_stack_1_stack_1->GetYaxis()->SetTitleSize(0.08);
   Background_fail_postfit_projy2_stack_1_stack_1->GetYaxis()->SetTitleOffset(1.25);
   Background_fail_postfit_projy2_stack_1_stack_1->GetYaxis()->SetTitleFont(42);
   Background_fail_postfit_projy2_stack_1_stack_1->GetZaxis()->SetLabelFont(42);
   Background_fail_postfit_projy2_stack_1_stack_1->GetZaxis()->SetLabelOffset(0.007);
   Background_fail_postfit_projy2_stack_1_stack_1->GetZaxis()->SetLabelSize(0.05);
   Background_fail_postfit_projy2_stack_1_stack_1->GetZaxis()->SetTitleSize(0.08);
   Background_fail_postfit_projy2_stack_1_stack_1->GetZaxis()->SetTitleFont(42);
   postfit_projy2_fail_stack->Add(Background_fail_postfit_projy2_stack_1_stack_1,"");
   postfit_projy2_fail_stack->Draw("hist same");
   Double_t xAxis325[2] = {50, 200}; 
   
   TH1D *Signal_ppStaumI557_fail_postfit_projy2__205 = new TH1D("Signal_ppStaumI557_fail_postfit_projy2__205","HSCP signal, fail, postfit, 1.0-1.0",1, xAxis325);
   Signal_ppStaumI557_fail_postfit_projy2__205->SetMinimum(0);
   Signal_ppStaumI557_fail_postfit_projy2__205->SetLineColor(2);
   Signal_ppStaumI557_fail_postfit_projy2__205->SetLineStyle(0);
   Signal_ppStaumI557_fail_postfit_projy2__205->GetXaxis()->SetTitle("p_{T}");
   Signal_ppStaumI557_fail_postfit_projy2__205->GetXaxis()->SetLabelFont(42);
   Signal_ppStaumI557_fail_postfit_projy2__205->GetXaxis()->SetLabelOffset(0.007);
   Signal_ppStaumI557_fail_postfit_projy2__205->GetXaxis()->SetLabelSize(0.05);
   Signal_ppStaumI557_fail_postfit_projy2__205->GetXaxis()->SetTitleSize(0.08);
   Signal_ppStaumI557_fail_postfit_projy2__205->GetXaxis()->SetTitleOffset(1.25);
   Signal_ppStaumI557_fail_postfit_projy2__205->GetXaxis()->SetTitleFont(42);
   Signal_ppStaumI557_fail_postfit_projy2__205->GetYaxis()->SetTitle("Events / bin");
   Signal_ppStaumI557_fail_postfit_projy2__205->GetYaxis()->SetLabelFont(42);
   Signal_ppStaumI557_fail_postfit_projy2__205->GetYaxis()->SetLabelOffset(0.007);
   Signal_ppStaumI557_fail_postfit_projy2__205->GetYaxis()->SetLabelSize(0.05);
   Signal_ppStaumI557_fail_postfit_projy2__205->GetYaxis()->SetTitleSize(0.08);
   Signal_ppStaumI557_fail_postfit_projy2__205->GetYaxis()->SetTitleOffset(1.25);
   Signal_ppStaumI557_fail_postfit_projy2__205->GetYaxis()->SetTitleFont(42);
   Signal_ppStaumI557_fail_postfit_projy2__205->GetZaxis()->SetLabelFont(42);
   Signal_ppStaumI557_fail_postfit_projy2__205->GetZaxis()->SetLabelOffset(0.007);
   Signal_ppStaumI557_fail_postfit_projy2__205->GetZaxis()->SetLabelSize(0.05);
   Signal_ppStaumI557_fail_postfit_projy2__205->GetZaxis()->SetTitleSize(0.08);
   Signal_ppStaumI557_fail_postfit_projy2__205->GetZaxis()->SetTitleFont(42);
   Signal_ppStaumI557_fail_postfit_projy2__205->Draw("hist same");
   Double_t xAxis326[2] = {50, 200}; 
   
   TH1D *TotalBkg_fail_postfit_projy2__206 = new TH1D("TotalBkg_fail_postfit_projy2__206","TotalBkg, fail, postfit, 1.0-1.0",1, xAxis326);
   TotalBkg_fail_postfit_projy2__206->SetMinimum(0);
   TotalBkg_fail_postfit_projy2__206->SetLineStyle(0);
   TotalBkg_fail_postfit_projy2__206->SetMarkerStyle(0);
   TotalBkg_fail_postfit_projy2__206->GetXaxis()->SetTitle("p_{T}");
   TotalBkg_fail_postfit_projy2__206->GetXaxis()->SetLabelFont(42);
   TotalBkg_fail_postfit_projy2__206->GetXaxis()->SetLabelOffset(0.007);
   TotalBkg_fail_postfit_projy2__206->GetXaxis()->SetLabelSize(0.05);
   TotalBkg_fail_postfit_projy2__206->GetXaxis()->SetTitleSize(0.08);
   TotalBkg_fail_postfit_projy2__206->GetXaxis()->SetTitleOffset(1.25);
   TotalBkg_fail_postfit_projy2__206->GetXaxis()->SetTitleFont(42);
   TotalBkg_fail_postfit_projy2__206->GetYaxis()->SetTitle("Events / bin");
   TotalBkg_fail_postfit_projy2__206->GetYaxis()->SetLabelFont(42);
   TotalBkg_fail_postfit_projy2__206->GetYaxis()->SetLabelOffset(0.007);
   TotalBkg_fail_postfit_projy2__206->GetYaxis()->SetLabelSize(0.05);
   TotalBkg_fail_postfit_projy2__206->GetYaxis()->SetTitleSize(0.08);
   TotalBkg_fail_postfit_projy2__206->GetYaxis()->SetTitleOffset(1.25);
   TotalBkg_fail_postfit_projy2__206->GetYaxis()->SetTitleFont(42);
   TotalBkg_fail_postfit_projy2__206->GetZaxis()->SetLabelFont(42);
   TotalBkg_fail_postfit_projy2__206->GetZaxis()->SetLabelOffset(0.007);
   TotalBkg_fail_postfit_projy2__206->GetZaxis()->SetLabelSize(0.05);
   TotalBkg_fail_postfit_projy2__206->GetZaxis()->SetTitleSize(0.08);
   TotalBkg_fail_postfit_projy2__206->GetZaxis()->SetTitleFont(42);
   TotalBkg_fail_postfit_projy2__206->Draw("hist same");
   Double_t xAxis327[2] = {50, 200}; 
   
   TH1D *TotalBkg_fail_postfit_projy2__207 = new TH1D("TotalBkg_fail_postfit_projy2__207","TotalBkg, fail, postfit, 1.0-1.0",1, xAxis327);
   TotalBkg_fail_postfit_projy2__207->SetMinimum(0);
   TotalBkg_fail_postfit_projy2__207->SetFillColor(1);
   TotalBkg_fail_postfit_projy2__207->SetFillStyle(3354);
   TotalBkg_fail_postfit_projy2__207->SetLineStyle(0);
   TotalBkg_fail_postfit_projy2__207->SetLineWidth(0);
   TotalBkg_fail_postfit_projy2__207->SetMarkerStyle(0);
   TotalBkg_fail_postfit_projy2__207->GetXaxis()->SetTitle("p_{T}");
   TotalBkg_fail_postfit_projy2__207->GetXaxis()->SetLabelFont(42);
   TotalBkg_fail_postfit_projy2__207->GetXaxis()->SetLabelOffset(0.007);
   TotalBkg_fail_postfit_projy2__207->GetXaxis()->SetLabelSize(0.05);
   TotalBkg_fail_postfit_projy2__207->GetXaxis()->SetTitleSize(0.08);
   TotalBkg_fail_postfit_projy2__207->GetXaxis()->SetTitleOffset(1.25);
   TotalBkg_fail_postfit_projy2__207->GetXaxis()->SetTitleFont(42);
   TotalBkg_fail_postfit_projy2__207->GetYaxis()->SetTitle("Events / bin");
   TotalBkg_fail_postfit_projy2__207->GetYaxis()->SetLabelFont(42);
   TotalBkg_fail_postfit_projy2__207->GetYaxis()->SetLabelOffset(0.007);
   TotalBkg_fail_postfit_projy2__207->GetYaxis()->SetLabelSize(0.05);
   TotalBkg_fail_postfit_projy2__207->GetYaxis()->SetTitleSize(0.08);
   TotalBkg_fail_postfit_projy2__207->GetYaxis()->SetTitleOffset(1.25);
   TotalBkg_fail_postfit_projy2__207->GetYaxis()->SetTitleFont(42);
   TotalBkg_fail_postfit_projy2__207->GetZaxis()->SetLabelFont(42);
   TotalBkg_fail_postfit_projy2__207->GetZaxis()->SetLabelOffset(0.007);
   TotalBkg_fail_postfit_projy2__207->GetZaxis()->SetLabelSize(0.05);
   TotalBkg_fail_postfit_projy2__207->GetZaxis()->SetTitleSize(0.08);
   TotalBkg_fail_postfit_projy2__207->GetZaxis()->SetTitleFont(42);
   TotalBkg_fail_postfit_projy2__207->Draw("e2 same");
   Double_t xAxis328[2] = {50, 200}; 
   
   TH1D *data_obs_fail_postfit_projy2__208 = new TH1D("data_obs_fail_postfit_projy2__208","",1, xAxis328);
   data_obs_fail_postfit_projy2__208->SetMinimum(0);
   data_obs_fail_postfit_projy2__208->SetMaximum(0);

   ci = TColor::GetColor("#000000");
   data_obs_fail_postfit_projy2__208->SetLineColor(ci);
   data_obs_fail_postfit_projy2__208->SetLineStyle(0);

   ci = TColor::GetColor("#000000");
   data_obs_fail_postfit_projy2__208->SetMarkerColor(ci);
   data_obs_fail_postfit_projy2__208->SetMarkerStyle(8);
   data_obs_fail_postfit_projy2__208->GetXaxis()->SetTitle("p_{T}");
   data_obs_fail_postfit_projy2__208->GetXaxis()->SetLabelFont(42);
   data_obs_fail_postfit_projy2__208->GetXaxis()->SetLabelOffset(0.05);
   data_obs_fail_postfit_projy2__208->GetXaxis()->SetLabelSize(0.07);
   data_obs_fail_postfit_projy2__208->GetXaxis()->SetTitleSize(0.09);
   data_obs_fail_postfit_projy2__208->GetXaxis()->SetTitleOffset(1.15);
   data_obs_fail_postfit_projy2__208->GetXaxis()->SetTitleFont(42);
   data_obs_fail_postfit_projy2__208->GetYaxis()->SetTitle("Events / bin");
   data_obs_fail_postfit_projy2__208->GetYaxis()->SetNdivisions(508);
   data_obs_fail_postfit_projy2__208->GetYaxis()->SetLabelFont(42);
   data_obs_fail_postfit_projy2__208->GetYaxis()->SetLabelOffset(0.007);
   data_obs_fail_postfit_projy2__208->GetYaxis()->SetLabelSize(0.07);
   data_obs_fail_postfit_projy2__208->GetYaxis()->SetTitleSize(0.09);
   data_obs_fail_postfit_projy2__208->GetYaxis()->SetTitleOffset(0.8);
   data_obs_fail_postfit_projy2__208->GetYaxis()->SetTitleFont(42);
   data_obs_fail_postfit_projy2__208->GetZaxis()->SetLabelFont(42);
   data_obs_fail_postfit_projy2__208->GetZaxis()->SetLabelOffset(0.007);
   data_obs_fail_postfit_projy2__208->GetZaxis()->SetLabelSize(0.05);
   data_obs_fail_postfit_projy2__208->GetZaxis()->SetTitleSize(0.08);
   data_obs_fail_postfit_projy2__208->GetZaxis()->SetTitleFont(42);
   data_obs_fail_postfit_projy2__208->Draw("pe X0 same");
   
   TLegend *leg = new TLegend(0.65,0.64,0.9,0.88,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(1001);
   TLegendEntry *entry=leg->AddEntry("data_obs_fail_postfit_projy2","Data","pe X0");

   ci = TColor::GetColor("#000000");
   entry->SetLineColor(ci);
   entry->SetLineWidth(1);

   ci = TColor::GetColor("#000000");
   entry->SetMarkerColor(ci);
   entry->SetMarkerStyle(8);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("TotalBkg_fail_postfit_projy2","Total bkg unc.","F");
   entry->SetFillColor(1);
   entry->SetFillStyle(3354);
   entry->SetLineColor(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("Signal_ppStau-557_fail_postfit_projy2","HSCP signal","L");
   entry->SetLineColor(2);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("Background_fail_postfit_projy2_stack_1_stack_1","Background","f");

   ci = TColor::GetColor("#ffff00");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = 1310;
   color = new TColor(ci, 1, 1, 1, " ", 0);
   entry->SetLineColor(ci);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   leg->Draw();
   Double_t xAxis329[2] = {50, 200}; 
   
   TH1D *data_obs_fail_postfit_projy2_copy__209 = new TH1D("data_obs_fail_postfit_projy2_copy__209","",1, xAxis329);
   data_obs_fail_postfit_projy2_copy__209->SetMinimum(0);
   data_obs_fail_postfit_projy2_copy__209->SetMaximum(0);
   data_obs_fail_postfit_projy2_copy__209->SetDirectory(0);

   ci = TColor::GetColor("#000000");
   data_obs_fail_postfit_projy2_copy__209->SetLineColor(ci);
   data_obs_fail_postfit_projy2_copy__209->SetLineStyle(0);

   ci = TColor::GetColor("#000000");
   data_obs_fail_postfit_projy2_copy__209->SetMarkerColor(ci);
   data_obs_fail_postfit_projy2_copy__209->SetMarkerStyle(8);
   data_obs_fail_postfit_projy2_copy__209->GetXaxis()->SetTitle("p_{T}");
   data_obs_fail_postfit_projy2_copy__209->GetXaxis()->SetLabelFont(42);
   data_obs_fail_postfit_projy2_copy__209->GetXaxis()->SetLabelOffset(0.05);
   data_obs_fail_postfit_projy2_copy__209->GetXaxis()->SetLabelSize(0.07);
   data_obs_fail_postfit_projy2_copy__209->GetXaxis()->SetTitleSize(0.09);
   data_obs_fail_postfit_projy2_copy__209->GetXaxis()->SetTitleOffset(1.15);
   data_obs_fail_postfit_projy2_copy__209->GetXaxis()->SetTitleFont(42);
   data_obs_fail_postfit_projy2_copy__209->GetYaxis()->SetTitle("Events / bin");
   data_obs_fail_postfit_projy2_copy__209->GetYaxis()->SetNdivisions(508);
   data_obs_fail_postfit_projy2_copy__209->GetYaxis()->SetLabelFont(42);
   data_obs_fail_postfit_projy2_copy__209->GetYaxis()->SetLabelOffset(0.007);
   data_obs_fail_postfit_projy2_copy__209->GetYaxis()->SetLabelSize(0.07);
   data_obs_fail_postfit_projy2_copy__209->GetYaxis()->SetTitleSize(0.09);
   data_obs_fail_postfit_projy2_copy__209->GetYaxis()->SetTitleOffset(0.8);
   data_obs_fail_postfit_projy2_copy__209->GetYaxis()->SetTitleFont(42);
   data_obs_fail_postfit_projy2_copy__209->GetZaxis()->SetLabelFont(42);
   data_obs_fail_postfit_projy2_copy__209->GetZaxis()->SetLabelOffset(0.007);
   data_obs_fail_postfit_projy2_copy__209->GetZaxis()->SetLabelSize(0.05);
   data_obs_fail_postfit_projy2_copy__209->GetZaxis()->SetTitleSize(0.08);
   data_obs_fail_postfit_projy2_copy__209->GetZaxis()->SetTitleFont(42);
   data_obs_fail_postfit_projy2_copy__209->Draw("sameaxis");
   TLatex *   tex = new TLatex(0.21,0.83,"55 < p_{T} < 200 GeV, F^{Pixels}_{i} < 0.9");
tex->SetNDC();
   tex->SetTextAlign(12);
   tex->SetTextFont(42);
   tex->SetTextSize(0.06);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.17,0.92,"CMS");
tex->SetNDC();
   tex->SetTextFont(61);
   tex->SetTextSize(0.0675);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.25,0.92,"Preliminary");
tex->SetNDC();
   tex->SetTextFont(52);
   tex->SetTextSize(0.0485);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.95,0.92,"101 fb^{-1} (13 TeV)");
tex->SetNDC();
   tex->SetTextAlign(31);
   tex->SetTextFont(42);
   tex->SetTextSize(0.07);
   tex->SetLineWidth(2);
   tex->Draw();
   data_obs_fail_postfit_projy2_main->Modified();
   plots_fit_s/base_figs/postfit_projy2_fail->cd();
  
// ------------>Primitives in pad: data_obs_fail_postfit_projy2_sub
   TPad *data_obs_fail_postfit_projy2_sub = new TPad("data_obs_fail_postfit_projy2_sub", "data_obs_fail_postfit_projy2_sub",0,0,1,0.35);
   data_obs_fail_postfit_projy2_sub->Draw();
   data_obs_fail_postfit_projy2_sub->cd();
   data_obs_fail_postfit_projy2_sub->Range(17.30769,-6.023077,209.6154,2.9);
   data_obs_fail_postfit_projy2_sub->SetFillColor(0);
   data_obs_fail_postfit_projy2_sub->SetBorderMode(0);
   data_obs_fail_postfit_projy2_sub->SetBorderSize(2);
   data_obs_fail_postfit_projy2_sub->SetTickx(1);
   data_obs_fail_postfit_projy2_sub->SetTicky(1);
   data_obs_fail_postfit_projy2_sub->SetLeftMargin(0.17);
   data_obs_fail_postfit_projy2_sub->SetRightMargin(0.05);
   data_obs_fail_postfit_projy2_sub->SetTopMargin(0);
   data_obs_fail_postfit_projy2_sub->SetBottomMargin(0.35);
   data_obs_fail_postfit_projy2_sub->SetFrameFillStyle(0);
   data_obs_fail_postfit_projy2_sub->SetFrameBorderMode(0);
   data_obs_fail_postfit_projy2_sub->SetFrameFillStyle(0);
   data_obs_fail_postfit_projy2_sub->SetFrameBorderMode(0);
   Double_t xAxis330[2] = {50, 200}; 
   
   TH1D *data_obs_fail_postfit_projy2_pull__210 = new TH1D("data_obs_fail_postfit_projy2_pull__210","",1, xAxis330);
   data_obs_fail_postfit_projy2_pull__210->SetMinimum(-2.9);
   data_obs_fail_postfit_projy2_pull__210->SetMaximum(2.9);
   data_obs_fail_postfit_projy2_pull__210->SetEntries(2);
   data_obs_fail_postfit_projy2_pull__210->SetStats(0);

   ci = TColor::GetColor("#0000ff");
   data_obs_fail_postfit_projy2_pull__210->SetFillColor(ci);

   ci = TColor::GetColor("#000000");
   data_obs_fail_postfit_projy2_pull__210->SetLineColor(ci);
   data_obs_fail_postfit_projy2_pull__210->SetLineStyle(0);

   ci = TColor::GetColor("#000000");
   data_obs_fail_postfit_projy2_pull__210->SetMarkerColor(ci);
   data_obs_fail_postfit_projy2_pull__210->SetMarkerStyle(8);
   data_obs_fail_postfit_projy2_pull__210->GetXaxis()->SetTitle("p_{T}");
   data_obs_fail_postfit_projy2_pull__210->GetXaxis()->SetLabelFont(42);
   data_obs_fail_postfit_projy2_pull__210->GetXaxis()->SetLabelOffset(0.05);
   data_obs_fail_postfit_projy2_pull__210->GetXaxis()->SetLabelSize(0.13);
   data_obs_fail_postfit_projy2_pull__210->GetXaxis()->SetTitleSize(0.15);
   data_obs_fail_postfit_projy2_pull__210->GetXaxis()->SetTitleOffset(1.15);
   data_obs_fail_postfit_projy2_pull__210->GetXaxis()->SetTitleFont(42);
   data_obs_fail_postfit_projy2_pull__210->GetYaxis()->SetTitle("(Data-Bkg)/#sigma");
   data_obs_fail_postfit_projy2_pull__210->GetYaxis()->SetNdivisions(306);
   data_obs_fail_postfit_projy2_pull__210->GetYaxis()->SetLabelFont(42);
   data_obs_fail_postfit_projy2_pull__210->GetYaxis()->SetLabelOffset(0.007);
   data_obs_fail_postfit_projy2_pull__210->GetYaxis()->SetLabelSize(0.13);
   data_obs_fail_postfit_projy2_pull__210->GetYaxis()->SetTitleSize(0.12);
   data_obs_fail_postfit_projy2_pull__210->GetYaxis()->SetTitleOffset(0.4);
   data_obs_fail_postfit_projy2_pull__210->GetYaxis()->SetTitleFont(42);
   data_obs_fail_postfit_projy2_pull__210->GetZaxis()->SetLabelFont(42);
   data_obs_fail_postfit_projy2_pull__210->GetZaxis()->SetLabelOffset(0.007);
   data_obs_fail_postfit_projy2_pull__210->GetZaxis()->SetLabelSize(0.05);
   data_obs_fail_postfit_projy2_pull__210->GetZaxis()->SetTitleSize(0.08);
   data_obs_fail_postfit_projy2_pull__210->GetZaxis()->SetTitleFont(42);
   data_obs_fail_postfit_projy2_pull__210->Draw("hist");
   data_obs_fail_postfit_projy2_sub->Modified();
   plots_fit_s/base_figs/postfit_projy2_fail->cd();
   plots_fit_s/base_figs/postfit_projy2_fail->Modified();
   plots_fit_s/base_figs/postfit_projy2_fail->cd();
   plots_fit_s/base_figs/postfit_projy2_fail->SetSelected(plots_fit_s/base_figs/postfit_projy2_fail);
}
