void postfit_projx1_pass_logy()
{
//=========Macro generated from canvas: plots_fit_s/base_figs/postfit_projx1_pass_logy/plots_fit_s/base_figs/postfit_projx1_pass_logy
//=========  (Fri Jan 12 21:00:09 2024) by ROOT version 6.14/09
   TCanvas *plots_fit_s/base_figs/postfit_projx1_pass_logy = new TCanvas("plots_fit_s/base_figs/postfit_projx1_pass_logy", "plots_fit_s/base_figs/postfit_projx1_pass_logy",0,0,800,700);
   gStyle->SetOptFit(1);
   gStyle->SetOptStat(0);
   plots_fit_s/base_figs/postfit_projx1_pass_logy->SetHighLightColor(2);
   plots_fit_s/base_figs/postfit_projx1_pass_logy->Range(0,0,1,1);
   plots_fit_s/base_figs/postfit_projx1_pass_logy->SetFillColor(0);
   plots_fit_s/base_figs/postfit_projx1_pass_logy->SetBorderMode(0);
   plots_fit_s/base_figs/postfit_projx1_pass_logy->SetBorderSize(2);
   plots_fit_s/base_figs/postfit_projx1_pass_logy->SetTickx(1);
   plots_fit_s/base_figs/postfit_projx1_pass_logy->SetTicky(1);
   plots_fit_s/base_figs/postfit_projx1_pass_logy->SetLeftMargin(0.16);
   plots_fit_s/base_figs/postfit_projx1_pass_logy->SetRightMargin(0);
   plots_fit_s/base_figs/postfit_projx1_pass_logy->SetTopMargin(0);
   plots_fit_s/base_figs/postfit_projx1_pass_logy->SetBottomMargin(0);
   plots_fit_s/base_figs/postfit_projx1_pass_logy->SetFrameFillStyle(0);
   plots_fit_s/base_figs/postfit_projx1_pass_logy->SetFrameBorderMode(0);
  
// ------------>Primitives in pad: data_obs_pass_postfit_projx1_main
   TPad *data_obs_pass_postfit_projx1_main = new TPad("data_obs_pass_postfit_projx1_main", "data_obs_pass_postfit_projx1_main",0,0.35,1,1);
   data_obs_pass_postfit_projx1_main->Draw();
   data_obs_pass_postfit_projx1_main->cd();
   data_obs_pass_postfit_projx1_main->Range(-0.2179487,-2.139535,1.064103,1.348837);
   data_obs_pass_postfit_projx1_main->SetFillColor(0);
   data_obs_pass_postfit_projx1_main->SetBorderMode(0);
   data_obs_pass_postfit_projx1_main->SetBorderSize(2);
   data_obs_pass_postfit_projx1_main->SetLogy();
   data_obs_pass_postfit_projx1_main->SetTickx(1);
   data_obs_pass_postfit_projx1_main->SetTicky(1);
   data_obs_pass_postfit_projx1_main->SetLeftMargin(0.17);
   data_obs_pass_postfit_projx1_main->SetRightMargin(0.05);
   data_obs_pass_postfit_projx1_main->SetBottomMargin(0.04);
   data_obs_pass_postfit_projx1_main->SetFrameFillStyle(0);
   data_obs_pass_postfit_projx1_main->SetFrameBorderMode(0);
   data_obs_pass_postfit_projx1_main->SetFrameFillStyle(0);
   data_obs_pass_postfit_projx1_main->SetFrameBorderMode(0);
   Double_t xAxis474[10] = {0, 0.04, 0.08, 0.12, 0.16, 0.2, 0.24, 0.28, 0.32, 1}; 
   
   TH1D *data_obs_pass_postfit_projx1__302 = new TH1D("data_obs_pass_postfit_projx1__302","",9, xAxis474);
   data_obs_pass_postfit_projx1__302->SetMinimum(0.001);
   data_obs_pass_postfit_projx1__302->SetMaximum(0);

   Int_t ci;      // for color index setting
   TColor *color; // for color definition with alpha
   ci = TColor::GetColor("#000000");
   data_obs_pass_postfit_projx1__302->SetLineColor(ci);
   data_obs_pass_postfit_projx1__302->SetLineStyle(0);

   ci = TColor::GetColor("#000000");
   data_obs_pass_postfit_projx1__302->SetMarkerColor(ci);
   data_obs_pass_postfit_projx1__302->SetMarkerStyle(8);
   data_obs_pass_postfit_projx1__302->GetXaxis()->SetTitle("G_{i}^{Strips}");
   data_obs_pass_postfit_projx1__302->GetXaxis()->SetLabelFont(42);
   data_obs_pass_postfit_projx1__302->GetXaxis()->SetLabelOffset(0.05);
   data_obs_pass_postfit_projx1__302->GetXaxis()->SetLabelSize(0.07);
   data_obs_pass_postfit_projx1__302->GetXaxis()->SetTitleSize(0.09);
   data_obs_pass_postfit_projx1__302->GetXaxis()->SetTitleOffset(1.15);
   data_obs_pass_postfit_projx1__302->GetXaxis()->SetTitleFont(42);
   data_obs_pass_postfit_projx1__302->GetYaxis()->SetTitle("Events / bin");
   data_obs_pass_postfit_projx1__302->GetYaxis()->SetNdivisions(508);
   data_obs_pass_postfit_projx1__302->GetYaxis()->SetLabelFont(42);
   data_obs_pass_postfit_projx1__302->GetYaxis()->SetLabelOffset(0.007);
   data_obs_pass_postfit_projx1__302->GetYaxis()->SetLabelSize(0.07);
   data_obs_pass_postfit_projx1__302->GetYaxis()->SetTitleSize(0.09);
   data_obs_pass_postfit_projx1__302->GetYaxis()->SetTitleOffset(0.8);
   data_obs_pass_postfit_projx1__302->GetYaxis()->SetTitleFont(42);
   data_obs_pass_postfit_projx1__302->GetZaxis()->SetLabelFont(42);
   data_obs_pass_postfit_projx1__302->GetZaxis()->SetLabelOffset(0.007);
   data_obs_pass_postfit_projx1__302->GetZaxis()->SetLabelSize(0.05);
   data_obs_pass_postfit_projx1__302->GetZaxis()->SetTitleSize(0.08);
   data_obs_pass_postfit_projx1__302->GetZaxis()->SetTitleFont(42);
   data_obs_pass_postfit_projx1__302->Draw("pe X0");
   
   THStack *postfit_projx1_pass_logy_stack = new THStack();
   postfit_projx1_pass_logy_stack->SetName("postfit_projx1_pass_logy_stack");
   postfit_projx1_pass_logy_stack->SetTitle("postfit_projx1_pass_logy_stack");
   postfit_projx1_pass_logy_stack->SetMinimum(0.001);
   Double_t xAxis475[10] = {0, 0.04, 0.08, 0.12, 0.16, 0.2, 0.24, 0.28, 0.32, 1}; 
   
   TH1F *postfit_projx1_pass_logy_stack_stack_87 = new TH1F("postfit_projx1_pass_logy_stack_stack_87","postfit_projx1_pass_logy_stack",9, xAxis475);
   postfit_projx1_pass_logy_stack_stack_87->SetMinimum(-0);
   postfit_projx1_pass_logy_stack_stack_87->SetMaximum(-nan);
   postfit_projx1_pass_logy_stack_stack_87->SetDirectory(0);
   postfit_projx1_pass_logy_stack_stack_87->SetStats(0);
   postfit_projx1_pass_logy_stack_stack_87->SetLineStyle(0);
   postfit_projx1_pass_logy_stack_stack_87->GetXaxis()->SetLabelFont(42);
   postfit_projx1_pass_logy_stack_stack_87->GetXaxis()->SetLabelOffset(0.007);
   postfit_projx1_pass_logy_stack_stack_87->GetXaxis()->SetLabelSize(0.05);
   postfit_projx1_pass_logy_stack_stack_87->GetXaxis()->SetTitleSize(0.08);
   postfit_projx1_pass_logy_stack_stack_87->GetXaxis()->SetTitleOffset(0.9);
   postfit_projx1_pass_logy_stack_stack_87->GetXaxis()->SetTitleFont(42);
   postfit_projx1_pass_logy_stack_stack_87->GetYaxis()->SetNdivisions(508);
   postfit_projx1_pass_logy_stack_stack_87->GetYaxis()->SetLabelFont(42);
   postfit_projx1_pass_logy_stack_stack_87->GetYaxis()->SetLabelOffset(0.007);
   postfit_projx1_pass_logy_stack_stack_87->GetYaxis()->SetLabelSize(0.05);
   postfit_projx1_pass_logy_stack_stack_87->GetYaxis()->SetTitleSize(0.08);
   postfit_projx1_pass_logy_stack_stack_87->GetYaxis()->SetTitleOffset(1.25);
   postfit_projx1_pass_logy_stack_stack_87->GetYaxis()->SetTitleFont(42);
   postfit_projx1_pass_logy_stack_stack_87->GetZaxis()->SetLabelFont(42);
   postfit_projx1_pass_logy_stack_stack_87->GetZaxis()->SetLabelOffset(0.007);
   postfit_projx1_pass_logy_stack_stack_87->GetZaxis()->SetLabelSize(0.05);
   postfit_projx1_pass_logy_stack_stack_87->GetZaxis()->SetTitleSize(0.08);
   postfit_projx1_pass_logy_stack_stack_87->GetZaxis()->SetTitleFont(42);
   postfit_projx1_pass_logy_stack->SetHistogram(postfit_projx1_pass_logy_stack_stack_87);
   
   Double_t xAxis476[10] = {0, 0.04, 0.08, 0.12, 0.16, 0.2, 0.24, 0.28, 0.32, 1}; 
   
   TH1D *Background_0x0_pass_postfit_projx1_stack_1 = new TH1D("Background_0x0_pass_postfit_projx1_stack_1","Background, pass, postfit, 50-50",9, xAxis476);
   Background_0x0_pass_postfit_projx1_stack_1->SetMinimum(0.001);

   ci = TColor::GetColor("#ffff00");
   Background_0x0_pass_postfit_projx1_stack_1->SetFillColor(ci);

   ci = 1318;
   color = new TColor(ci, 1, 1, 1, " ", 0);
   Background_0x0_pass_postfit_projx1_stack_1->SetLineColor(ci);
   Background_0x0_pass_postfit_projx1_stack_1->SetLineStyle(0);
   Background_0x0_pass_postfit_projx1_stack_1->GetXaxis()->SetTitle("G_{i}^{Strips}");
   Background_0x0_pass_postfit_projx1_stack_1->GetXaxis()->SetLabelFont(42);
   Background_0x0_pass_postfit_projx1_stack_1->GetXaxis()->SetLabelOffset(0.007);
   Background_0x0_pass_postfit_projx1_stack_1->GetXaxis()->SetLabelSize(0.05);
   Background_0x0_pass_postfit_projx1_stack_1->GetXaxis()->SetTitleSize(0.08);
   Background_0x0_pass_postfit_projx1_stack_1->GetXaxis()->SetTitleOffset(0.9);
   Background_0x0_pass_postfit_projx1_stack_1->GetXaxis()->SetTitleFont(42);
   Background_0x0_pass_postfit_projx1_stack_1->GetYaxis()->SetTitle("Events / bin");
   Background_0x0_pass_postfit_projx1_stack_1->GetYaxis()->SetLabelFont(42);
   Background_0x0_pass_postfit_projx1_stack_1->GetYaxis()->SetLabelOffset(0.007);
   Background_0x0_pass_postfit_projx1_stack_1->GetYaxis()->SetLabelSize(0.05);
   Background_0x0_pass_postfit_projx1_stack_1->GetYaxis()->SetTitleSize(0.08);
   Background_0x0_pass_postfit_projx1_stack_1->GetYaxis()->SetTitleOffset(1.25);
   Background_0x0_pass_postfit_projx1_stack_1->GetYaxis()->SetTitleFont(42);
   Background_0x0_pass_postfit_projx1_stack_1->GetZaxis()->SetLabelFont(42);
   Background_0x0_pass_postfit_projx1_stack_1->GetZaxis()->SetLabelOffset(0.007);
   Background_0x0_pass_postfit_projx1_stack_1->GetZaxis()->SetLabelSize(0.05);
   Background_0x0_pass_postfit_projx1_stack_1->GetZaxis()->SetTitleSize(0.08);
   Background_0x0_pass_postfit_projx1_stack_1->GetZaxis()->SetTitleFont(42);
   postfit_projx1_pass_logy_stack->Add(Background_0x0_pass_postfit_projx1_stack_1,"");
   postfit_projx1_pass_logy_stack->Draw("hist same");
   
   postfit_projx1_pass_logy_stack = new THStack();
   postfit_projx1_pass_logy_stack->SetName("postfit_projx1_pass_logy_stack");
   postfit_projx1_pass_logy_stack->SetTitle("postfit_projx1_pass_logy_stack");
   postfit_projx1_pass_logy_stack->SetMinimum(0.001);
   Double_t xAxis477[10] = {0, 0.04, 0.08, 0.12, 0.16, 0.2, 0.24, 0.28, 0.32, 1}; 
   
   TH1F *postfit_projx1_pass_logy_stack_stack_87_stack_88 = new TH1F("postfit_projx1_pass_logy_stack_stack_87_stack_88","postfit_projx1_pass_logy_stack",9, xAxis477);
   postfit_projx1_pass_logy_stack_stack_87_stack_88->SetMinimum(-0);
   postfit_projx1_pass_logy_stack_stack_87_stack_88->SetMaximum(-nan);
   postfit_projx1_pass_logy_stack_stack_87_stack_88->SetDirectory(0);
   postfit_projx1_pass_logy_stack_stack_87_stack_88->SetStats(0);
   postfit_projx1_pass_logy_stack_stack_87_stack_88->SetLineStyle(0);
   postfit_projx1_pass_logy_stack_stack_87_stack_88->GetXaxis()->SetLabelFont(42);
   postfit_projx1_pass_logy_stack_stack_87_stack_88->GetXaxis()->SetLabelOffset(0.007);
   postfit_projx1_pass_logy_stack_stack_87_stack_88->GetXaxis()->SetLabelSize(0.05);
   postfit_projx1_pass_logy_stack_stack_87_stack_88->GetXaxis()->SetTitleSize(0.08);
   postfit_projx1_pass_logy_stack_stack_87_stack_88->GetXaxis()->SetTitleOffset(0.9);
   postfit_projx1_pass_logy_stack_stack_87_stack_88->GetXaxis()->SetTitleFont(42);
   postfit_projx1_pass_logy_stack_stack_87_stack_88->GetYaxis()->SetNdivisions(508);
   postfit_projx1_pass_logy_stack_stack_87_stack_88->GetYaxis()->SetLabelFont(42);
   postfit_projx1_pass_logy_stack_stack_87_stack_88->GetYaxis()->SetLabelOffset(0.007);
   postfit_projx1_pass_logy_stack_stack_87_stack_88->GetYaxis()->SetLabelSize(0.05);
   postfit_projx1_pass_logy_stack_stack_87_stack_88->GetYaxis()->SetTitleSize(0.08);
   postfit_projx1_pass_logy_stack_stack_87_stack_88->GetYaxis()->SetTitleOffset(1.25);
   postfit_projx1_pass_logy_stack_stack_87_stack_88->GetYaxis()->SetTitleFont(42);
   postfit_projx1_pass_logy_stack_stack_87_stack_88->GetZaxis()->SetLabelFont(42);
   postfit_projx1_pass_logy_stack_stack_87_stack_88->GetZaxis()->SetLabelOffset(0.007);
   postfit_projx1_pass_logy_stack_stack_87_stack_88->GetZaxis()->SetLabelSize(0.05);
   postfit_projx1_pass_logy_stack_stack_87_stack_88->GetZaxis()->SetTitleSize(0.08);
   postfit_projx1_pass_logy_stack_stack_87_stack_88->GetZaxis()->SetTitleFont(42);
   postfit_projx1_pass_logy_stack->SetHistogram(postfit_projx1_pass_logy_stack_stack_87_stack_88);
   
   Double_t xAxis478[10] = {0, 0.04, 0.08, 0.12, 0.16, 0.2, 0.24, 0.28, 0.32, 1}; 
   
   TH1D *Background_0x0_pass_postfit_projx1_stack_1_stack_1 = new TH1D("Background_0x0_pass_postfit_projx1_stack_1_stack_1","Background, pass, postfit, 50-50",9, xAxis478);
   Background_0x0_pass_postfit_projx1_stack_1_stack_1->SetMinimum(0.001);

   ci = TColor::GetColor("#ffff00");
   Background_0x0_pass_postfit_projx1_stack_1_stack_1->SetFillColor(ci);

   ci = 1318;
   color = new TColor(ci, 1, 1, 1, " ", 0);
   Background_0x0_pass_postfit_projx1_stack_1_stack_1->SetLineColor(ci);
   Background_0x0_pass_postfit_projx1_stack_1_stack_1->SetLineStyle(0);
   Background_0x0_pass_postfit_projx1_stack_1_stack_1->GetXaxis()->SetTitle("G_{i}^{Strips}");
   Background_0x0_pass_postfit_projx1_stack_1_stack_1->GetXaxis()->SetLabelFont(42);
   Background_0x0_pass_postfit_projx1_stack_1_stack_1->GetXaxis()->SetLabelOffset(0.007);
   Background_0x0_pass_postfit_projx1_stack_1_stack_1->GetXaxis()->SetLabelSize(0.05);
   Background_0x0_pass_postfit_projx1_stack_1_stack_1->GetXaxis()->SetTitleSize(0.08);
   Background_0x0_pass_postfit_projx1_stack_1_stack_1->GetXaxis()->SetTitleOffset(0.9);
   Background_0x0_pass_postfit_projx1_stack_1_stack_1->GetXaxis()->SetTitleFont(42);
   Background_0x0_pass_postfit_projx1_stack_1_stack_1->GetYaxis()->SetTitle("Events / bin");
   Background_0x0_pass_postfit_projx1_stack_1_stack_1->GetYaxis()->SetLabelFont(42);
   Background_0x0_pass_postfit_projx1_stack_1_stack_1->GetYaxis()->SetLabelOffset(0.007);
   Background_0x0_pass_postfit_projx1_stack_1_stack_1->GetYaxis()->SetLabelSize(0.05);
   Background_0x0_pass_postfit_projx1_stack_1_stack_1->GetYaxis()->SetTitleSize(0.08);
   Background_0x0_pass_postfit_projx1_stack_1_stack_1->GetYaxis()->SetTitleOffset(1.25);
   Background_0x0_pass_postfit_projx1_stack_1_stack_1->GetYaxis()->SetTitleFont(42);
   Background_0x0_pass_postfit_projx1_stack_1_stack_1->GetZaxis()->SetLabelFont(42);
   Background_0x0_pass_postfit_projx1_stack_1_stack_1->GetZaxis()->SetLabelOffset(0.007);
   Background_0x0_pass_postfit_projx1_stack_1_stack_1->GetZaxis()->SetLabelSize(0.05);
   Background_0x0_pass_postfit_projx1_stack_1_stack_1->GetZaxis()->SetTitleSize(0.08);
   Background_0x0_pass_postfit_projx1_stack_1_stack_1->GetZaxis()->SetTitleFont(42);
   postfit_projx1_pass_logy_stack->Add(Background_0x0_pass_postfit_projx1_stack_1_stack_1,"");
   postfit_projx1_pass_logy_stack->Draw("hist same");
   Double_t xAxis479[10] = {0, 0.04, 0.08, 0.12, 0.16, 0.2, 0.24, 0.28, 0.32, 1}; 
   
   TH1D *Signal_ppStaumI557_pass_postfit_projx1__303 = new TH1D("Signal_ppStaumI557_pass_postfit_projx1__303","HSCP signal, pass, postfit, 50-50",9, xAxis479);
   Signal_ppStaumI557_pass_postfit_projx1__303->SetMinimum(0.001);
   Signal_ppStaumI557_pass_postfit_projx1__303->SetLineColor(2);
   Signal_ppStaumI557_pass_postfit_projx1__303->SetLineStyle(0);
   Signal_ppStaumI557_pass_postfit_projx1__303->GetXaxis()->SetTitle("G_{i}^{Strips}");
   Signal_ppStaumI557_pass_postfit_projx1__303->GetXaxis()->SetLabelFont(42);
   Signal_ppStaumI557_pass_postfit_projx1__303->GetXaxis()->SetLabelOffset(0.007);
   Signal_ppStaumI557_pass_postfit_projx1__303->GetXaxis()->SetLabelSize(0.05);
   Signal_ppStaumI557_pass_postfit_projx1__303->GetXaxis()->SetTitleSize(0.08);
   Signal_ppStaumI557_pass_postfit_projx1__303->GetXaxis()->SetTitleOffset(0.9);
   Signal_ppStaumI557_pass_postfit_projx1__303->GetXaxis()->SetTitleFont(42);
   Signal_ppStaumI557_pass_postfit_projx1__303->GetYaxis()->SetTitle("Events / bin");
   Signal_ppStaumI557_pass_postfit_projx1__303->GetYaxis()->SetLabelFont(42);
   Signal_ppStaumI557_pass_postfit_projx1__303->GetYaxis()->SetLabelOffset(0.007);
   Signal_ppStaumI557_pass_postfit_projx1__303->GetYaxis()->SetLabelSize(0.05);
   Signal_ppStaumI557_pass_postfit_projx1__303->GetYaxis()->SetTitleSize(0.08);
   Signal_ppStaumI557_pass_postfit_projx1__303->GetYaxis()->SetTitleOffset(1.25);
   Signal_ppStaumI557_pass_postfit_projx1__303->GetYaxis()->SetTitleFont(42);
   Signal_ppStaumI557_pass_postfit_projx1__303->GetZaxis()->SetLabelFont(42);
   Signal_ppStaumI557_pass_postfit_projx1__303->GetZaxis()->SetLabelOffset(0.007);
   Signal_ppStaumI557_pass_postfit_projx1__303->GetZaxis()->SetLabelSize(0.05);
   Signal_ppStaumI557_pass_postfit_projx1__303->GetZaxis()->SetTitleSize(0.08);
   Signal_ppStaumI557_pass_postfit_projx1__303->GetZaxis()->SetTitleFont(42);
   Signal_ppStaumI557_pass_postfit_projx1__303->Draw("hist same");
   Double_t xAxis480[10] = {0, 0.04, 0.08, 0.12, 0.16, 0.2, 0.24, 0.28, 0.32, 1}; 
   
   TH1D *TotalBkg_pass_postfit_projx1__304 = new TH1D("TotalBkg_pass_postfit_projx1__304","TotalBkg, pass, postfit, 50-50",9, xAxis480);
   TotalBkg_pass_postfit_projx1__304->SetMinimum(0.001);
   TotalBkg_pass_postfit_projx1__304->SetLineStyle(0);
   TotalBkg_pass_postfit_projx1__304->SetMarkerStyle(0);
   TotalBkg_pass_postfit_projx1__304->GetXaxis()->SetTitle("G_{i}^{Strips}");
   TotalBkg_pass_postfit_projx1__304->GetXaxis()->SetLabelFont(42);
   TotalBkg_pass_postfit_projx1__304->GetXaxis()->SetLabelOffset(0.007);
   TotalBkg_pass_postfit_projx1__304->GetXaxis()->SetLabelSize(0.05);
   TotalBkg_pass_postfit_projx1__304->GetXaxis()->SetTitleSize(0.08);
   TotalBkg_pass_postfit_projx1__304->GetXaxis()->SetTitleOffset(0.9);
   TotalBkg_pass_postfit_projx1__304->GetXaxis()->SetTitleFont(42);
   TotalBkg_pass_postfit_projx1__304->GetYaxis()->SetTitle("Events / bin");
   TotalBkg_pass_postfit_projx1__304->GetYaxis()->SetLabelFont(42);
   TotalBkg_pass_postfit_projx1__304->GetYaxis()->SetLabelOffset(0.007);
   TotalBkg_pass_postfit_projx1__304->GetYaxis()->SetLabelSize(0.05);
   TotalBkg_pass_postfit_projx1__304->GetYaxis()->SetTitleSize(0.08);
   TotalBkg_pass_postfit_projx1__304->GetYaxis()->SetTitleOffset(1.25);
   TotalBkg_pass_postfit_projx1__304->GetYaxis()->SetTitleFont(42);
   TotalBkg_pass_postfit_projx1__304->GetZaxis()->SetLabelFont(42);
   TotalBkg_pass_postfit_projx1__304->GetZaxis()->SetLabelOffset(0.007);
   TotalBkg_pass_postfit_projx1__304->GetZaxis()->SetLabelSize(0.05);
   TotalBkg_pass_postfit_projx1__304->GetZaxis()->SetTitleSize(0.08);
   TotalBkg_pass_postfit_projx1__304->GetZaxis()->SetTitleFont(42);
   TotalBkg_pass_postfit_projx1__304->Draw("hist same");
   Double_t xAxis481[10] = {0, 0.04, 0.08, 0.12, 0.16, 0.2, 0.24, 0.28, 0.32, 1}; 
   
   TH1D *TotalBkg_pass_postfit_projx1__305 = new TH1D("TotalBkg_pass_postfit_projx1__305","TotalBkg, pass, postfit, 50-50",9, xAxis481);
   TotalBkg_pass_postfit_projx1__305->SetMinimum(0.001);
   TotalBkg_pass_postfit_projx1__305->SetFillColor(1);
   TotalBkg_pass_postfit_projx1__305->SetFillStyle(3354);
   TotalBkg_pass_postfit_projx1__305->SetLineStyle(0);
   TotalBkg_pass_postfit_projx1__305->SetLineWidth(0);
   TotalBkg_pass_postfit_projx1__305->SetMarkerStyle(0);
   TotalBkg_pass_postfit_projx1__305->GetXaxis()->SetTitle("G_{i}^{Strips}");
   TotalBkg_pass_postfit_projx1__305->GetXaxis()->SetLabelFont(42);
   TotalBkg_pass_postfit_projx1__305->GetXaxis()->SetLabelOffset(0.007);
   TotalBkg_pass_postfit_projx1__305->GetXaxis()->SetLabelSize(0.05);
   TotalBkg_pass_postfit_projx1__305->GetXaxis()->SetTitleSize(0.08);
   TotalBkg_pass_postfit_projx1__305->GetXaxis()->SetTitleOffset(0.9);
   TotalBkg_pass_postfit_projx1__305->GetXaxis()->SetTitleFont(42);
   TotalBkg_pass_postfit_projx1__305->GetYaxis()->SetTitle("Events / bin");
   TotalBkg_pass_postfit_projx1__305->GetYaxis()->SetLabelFont(42);
   TotalBkg_pass_postfit_projx1__305->GetYaxis()->SetLabelOffset(0.007);
   TotalBkg_pass_postfit_projx1__305->GetYaxis()->SetLabelSize(0.05);
   TotalBkg_pass_postfit_projx1__305->GetYaxis()->SetTitleSize(0.08);
   TotalBkg_pass_postfit_projx1__305->GetYaxis()->SetTitleOffset(1.25);
   TotalBkg_pass_postfit_projx1__305->GetYaxis()->SetTitleFont(42);
   TotalBkg_pass_postfit_projx1__305->GetZaxis()->SetLabelFont(42);
   TotalBkg_pass_postfit_projx1__305->GetZaxis()->SetLabelOffset(0.007);
   TotalBkg_pass_postfit_projx1__305->GetZaxis()->SetLabelSize(0.05);
   TotalBkg_pass_postfit_projx1__305->GetZaxis()->SetTitleSize(0.08);
   TotalBkg_pass_postfit_projx1__305->GetZaxis()->SetTitleFont(42);
   TotalBkg_pass_postfit_projx1__305->Draw("e2 same");
   Double_t xAxis482[10] = {0, 0.04, 0.08, 0.12, 0.16, 0.2, 0.24, 0.28, 0.32, 1}; 
   
   TH1D *data_obs_pass_postfit_projx1__306 = new TH1D("data_obs_pass_postfit_projx1__306","",9, xAxis482);
   data_obs_pass_postfit_projx1__306->SetMinimum(0.001);
   data_obs_pass_postfit_projx1__306->SetMaximum(0);

   ci = TColor::GetColor("#000000");
   data_obs_pass_postfit_projx1__306->SetLineColor(ci);
   data_obs_pass_postfit_projx1__306->SetLineStyle(0);

   ci = TColor::GetColor("#000000");
   data_obs_pass_postfit_projx1__306->SetMarkerColor(ci);
   data_obs_pass_postfit_projx1__306->SetMarkerStyle(8);
   data_obs_pass_postfit_projx1__306->GetXaxis()->SetTitle("G_{i}^{Strips}");
   data_obs_pass_postfit_projx1__306->GetXaxis()->SetLabelFont(42);
   data_obs_pass_postfit_projx1__306->GetXaxis()->SetLabelOffset(0.05);
   data_obs_pass_postfit_projx1__306->GetXaxis()->SetLabelSize(0.07);
   data_obs_pass_postfit_projx1__306->GetXaxis()->SetTitleSize(0.09);
   data_obs_pass_postfit_projx1__306->GetXaxis()->SetTitleOffset(1.15);
   data_obs_pass_postfit_projx1__306->GetXaxis()->SetTitleFont(42);
   data_obs_pass_postfit_projx1__306->GetYaxis()->SetTitle("Events / bin");
   data_obs_pass_postfit_projx1__306->GetYaxis()->SetNdivisions(508);
   data_obs_pass_postfit_projx1__306->GetYaxis()->SetLabelFont(42);
   data_obs_pass_postfit_projx1__306->GetYaxis()->SetLabelOffset(0.007);
   data_obs_pass_postfit_projx1__306->GetYaxis()->SetLabelSize(0.07);
   data_obs_pass_postfit_projx1__306->GetYaxis()->SetTitleSize(0.09);
   data_obs_pass_postfit_projx1__306->GetYaxis()->SetTitleOffset(0.8);
   data_obs_pass_postfit_projx1__306->GetYaxis()->SetTitleFont(42);
   data_obs_pass_postfit_projx1__306->GetZaxis()->SetLabelFont(42);
   data_obs_pass_postfit_projx1__306->GetZaxis()->SetLabelOffset(0.007);
   data_obs_pass_postfit_projx1__306->GetZaxis()->SetLabelSize(0.05);
   data_obs_pass_postfit_projx1__306->GetZaxis()->SetTitleSize(0.08);
   data_obs_pass_postfit_projx1__306->GetZaxis()->SetTitleFont(42);
   data_obs_pass_postfit_projx1__306->Draw("pe X0 same");
   
   TLegend *leg = new TLegend(0.65,0.64,0.9,0.88,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(1001);
   TLegendEntry *entry=leg->AddEntry("data_obs_pass_postfit_projx1","Data","pe X0");

   ci = TColor::GetColor("#000000");
   entry->SetLineColor(ci);
   entry->SetLineWidth(1);

   ci = TColor::GetColor("#000000");
   entry->SetMarkerColor(ci);
   entry->SetMarkerStyle(8);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("TotalBkg_pass_postfit_projx1","Total bkg unc.","F");
   entry->SetFillColor(1);
   entry->SetFillStyle(3354);
   entry->SetLineColor(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("Signal_ppStau-557_pass_postfit_projx1","HSCP signal","L");
   entry->SetLineColor(2);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("Background_0x0_pass_postfit_projx1_stack_1_stack_1","Background","f");

   ci = TColor::GetColor("#ffff00");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = 1318;
   color = new TColor(ci, 1, 1, 1, " ", 0);
   entry->SetLineColor(ci);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   leg->Draw();
   Double_t xAxis483[10] = {0, 0.04, 0.08, 0.12, 0.16, 0.2, 0.24, 0.28, 0.32, 1}; 
   
   TH1D *data_obs_pass_postfit_projx1_copy__307 = new TH1D("data_obs_pass_postfit_projx1_copy__307","",9, xAxis483);
   data_obs_pass_postfit_projx1_copy__307->SetMinimum(0.001);
   data_obs_pass_postfit_projx1_copy__307->SetMaximum(0);
   data_obs_pass_postfit_projx1_copy__307->SetDirectory(0);

   ci = TColor::GetColor("#000000");
   data_obs_pass_postfit_projx1_copy__307->SetLineColor(ci);
   data_obs_pass_postfit_projx1_copy__307->SetLineStyle(0);

   ci = TColor::GetColor("#000000");
   data_obs_pass_postfit_projx1_copy__307->SetMarkerColor(ci);
   data_obs_pass_postfit_projx1_copy__307->SetMarkerStyle(8);
   data_obs_pass_postfit_projx1_copy__307->GetXaxis()->SetTitle("G_{i}^{Strips}");
   data_obs_pass_postfit_projx1_copy__307->GetXaxis()->SetLabelFont(42);
   data_obs_pass_postfit_projx1_copy__307->GetXaxis()->SetLabelOffset(0.05);
   data_obs_pass_postfit_projx1_copy__307->GetXaxis()->SetLabelSize(0.07);
   data_obs_pass_postfit_projx1_copy__307->GetXaxis()->SetTitleSize(0.09);
   data_obs_pass_postfit_projx1_copy__307->GetXaxis()->SetTitleOffset(1.15);
   data_obs_pass_postfit_projx1_copy__307->GetXaxis()->SetTitleFont(42);
   data_obs_pass_postfit_projx1_copy__307->GetYaxis()->SetTitle("Events / bin");
   data_obs_pass_postfit_projx1_copy__307->GetYaxis()->SetNdivisions(508);
   data_obs_pass_postfit_projx1_copy__307->GetYaxis()->SetLabelFont(42);
   data_obs_pass_postfit_projx1_copy__307->GetYaxis()->SetLabelOffset(0.007);
   data_obs_pass_postfit_projx1_copy__307->GetYaxis()->SetLabelSize(0.07);
   data_obs_pass_postfit_projx1_copy__307->GetYaxis()->SetTitleSize(0.09);
   data_obs_pass_postfit_projx1_copy__307->GetYaxis()->SetTitleOffset(0.8);
   data_obs_pass_postfit_projx1_copy__307->GetYaxis()->SetTitleFont(42);
   data_obs_pass_postfit_projx1_copy__307->GetZaxis()->SetLabelFont(42);
   data_obs_pass_postfit_projx1_copy__307->GetZaxis()->SetLabelOffset(0.007);
   data_obs_pass_postfit_projx1_copy__307->GetZaxis()->SetLabelSize(0.05);
   data_obs_pass_postfit_projx1_copy__307->GetZaxis()->SetTitleSize(0.08);
   data_obs_pass_postfit_projx1_copy__307->GetZaxis()->SetTitleFont(42);
   data_obs_pass_postfit_projx1_copy__307->Draw("sameaxis");
   TLatex *   tex = new TLatex(0.21,0.83,"55 < p_{T} < 200 GeV, F^{Pixels}_{i} > 0.9");
tex->SetNDC();
   tex->SetTextAlign(12);
   tex->SetTextFont(42);
   tex->SetTextSize(0.06);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.17,0.92,"CMS");
tex->SetNDC();
   tex->SetTextFont(61);
   tex->SetTextSize(0.0675);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.25,0.92,"Preliminary");
tex->SetNDC();
   tex->SetTextFont(52);
   tex->SetTextSize(0.0485);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.95,0.92,"101 fb^{-1} (13 TeV)");
tex->SetNDC();
   tex->SetTextAlign(31);
   tex->SetTextFont(42);
   tex->SetTextSize(0.07);
   tex->SetLineWidth(2);
   tex->Draw();
   data_obs_pass_postfit_projx1_main->Modified();
   plots_fit_s/base_figs/postfit_projx1_pass_logy->cd();
  
// ------------>Primitives in pad: data_obs_pass_postfit_projx1_sub
   TPad *data_obs_pass_postfit_projx1_sub = new TPad("data_obs_pass_postfit_projx1_sub", "data_obs_pass_postfit_projx1_sub",0,0,1,0.35);
   data_obs_pass_postfit_projx1_sub->Draw();
   data_obs_pass_postfit_projx1_sub->cd();
   data_obs_pass_postfit_projx1_sub->Range(-0.2179487,-6.023077,1.064103,2.9);
   data_obs_pass_postfit_projx1_sub->SetFillColor(0);
   data_obs_pass_postfit_projx1_sub->SetBorderMode(0);
   data_obs_pass_postfit_projx1_sub->SetBorderSize(2);
   data_obs_pass_postfit_projx1_sub->SetTickx(1);
   data_obs_pass_postfit_projx1_sub->SetTicky(1);
   data_obs_pass_postfit_projx1_sub->SetLeftMargin(0.17);
   data_obs_pass_postfit_projx1_sub->SetRightMargin(0.05);
   data_obs_pass_postfit_projx1_sub->SetTopMargin(0);
   data_obs_pass_postfit_projx1_sub->SetBottomMargin(0.35);
   data_obs_pass_postfit_projx1_sub->SetFrameFillStyle(0);
   data_obs_pass_postfit_projx1_sub->SetFrameBorderMode(0);
   data_obs_pass_postfit_projx1_sub->SetFrameFillStyle(0);
   data_obs_pass_postfit_projx1_sub->SetFrameBorderMode(0);
   Double_t xAxis484[10] = {0, 0.04, 0.08, 0.12, 0.16, 0.2, 0.24, 0.28, 0.32, 1}; 
   
   TH1D *data_obs_pass_postfit_projx1_pull__308 = new TH1D("data_obs_pass_postfit_projx1_pull__308","",9, xAxis484);
   data_obs_pass_postfit_projx1_pull__308->SetMinimum(-2.9);
   data_obs_pass_postfit_projx1_pull__308->SetMaximum(2.9);
   data_obs_pass_postfit_projx1_pull__308->SetEntries(18);
   data_obs_pass_postfit_projx1_pull__308->SetStats(0);

   ci = TColor::GetColor("#0000ff");
   data_obs_pass_postfit_projx1_pull__308->SetFillColor(ci);

   ci = TColor::GetColor("#000000");
   data_obs_pass_postfit_projx1_pull__308->SetLineColor(ci);
   data_obs_pass_postfit_projx1_pull__308->SetLineStyle(0);

   ci = TColor::GetColor("#000000");
   data_obs_pass_postfit_projx1_pull__308->SetMarkerColor(ci);
   data_obs_pass_postfit_projx1_pull__308->SetMarkerStyle(8);
   data_obs_pass_postfit_projx1_pull__308->GetXaxis()->SetTitle("G_{i}^{Strips}");
   data_obs_pass_postfit_projx1_pull__308->GetXaxis()->SetLabelFont(42);
   data_obs_pass_postfit_projx1_pull__308->GetXaxis()->SetLabelOffset(0.05);
   data_obs_pass_postfit_projx1_pull__308->GetXaxis()->SetLabelSize(0.13);
   data_obs_pass_postfit_projx1_pull__308->GetXaxis()->SetTitleSize(0.15);
   data_obs_pass_postfit_projx1_pull__308->GetXaxis()->SetTitleOffset(1.15);
   data_obs_pass_postfit_projx1_pull__308->GetXaxis()->SetTitleFont(42);
   data_obs_pass_postfit_projx1_pull__308->GetYaxis()->SetTitle("(Data-Bkg)/#sigma");
   data_obs_pass_postfit_projx1_pull__308->GetYaxis()->SetNdivisions(306);
   data_obs_pass_postfit_projx1_pull__308->GetYaxis()->SetLabelFont(42);
   data_obs_pass_postfit_projx1_pull__308->GetYaxis()->SetLabelOffset(0.007);
   data_obs_pass_postfit_projx1_pull__308->GetYaxis()->SetLabelSize(0.13);
   data_obs_pass_postfit_projx1_pull__308->GetYaxis()->SetTitleSize(0.12);
   data_obs_pass_postfit_projx1_pull__308->GetYaxis()->SetTitleOffset(0.4);
   data_obs_pass_postfit_projx1_pull__308->GetYaxis()->SetTitleFont(42);
   data_obs_pass_postfit_projx1_pull__308->GetZaxis()->SetLabelFont(42);
   data_obs_pass_postfit_projx1_pull__308->GetZaxis()->SetLabelOffset(0.007);
   data_obs_pass_postfit_projx1_pull__308->GetZaxis()->SetLabelSize(0.05);
   data_obs_pass_postfit_projx1_pull__308->GetZaxis()->SetTitleSize(0.08);
   data_obs_pass_postfit_projx1_pull__308->GetZaxis()->SetTitleFont(42);
   data_obs_pass_postfit_projx1_pull__308->Draw("hist");
   data_obs_pass_postfit_projx1_sub->Modified();
   plots_fit_s/base_figs/postfit_projx1_pass_logy->cd();
   plots_fit_s/base_figs/postfit_projx1_pass_logy->Modified();
   plots_fit_s/base_figs/postfit_projx1_pass_logy->cd();
   plots_fit_s/base_figs/postfit_projx1_pass_logy->SetSelected(plots_fit_s/base_figs/postfit_projx1_pass_logy);
}
