void postfit_projx0_fail()
{
//=========Macro generated from canvas: plots_fit_s/base_figs/postfit_projx0_fail/plots_fit_s/base_figs/postfit_projx0_fail
//=========  (Fri Jan 12 21:00:07 2024) by ROOT version 6.14/09
   TCanvas *plots_fit_s/base_figs/postfit_projx0_fail = new TCanvas("plots_fit_s/base_figs/postfit_projx0_fail", "plots_fit_s/base_figs/postfit_projx0_fail",0,0,800,700);
   gStyle->SetOptFit(1);
   gStyle->SetOptStat(0);
   plots_fit_s/base_figs/postfit_projx0_fail->SetHighLightColor(2);
   plots_fit_s/base_figs/postfit_projx0_fail->Range(0,0,1,1);
   plots_fit_s/base_figs/postfit_projx0_fail->SetFillColor(0);
   plots_fit_s/base_figs/postfit_projx0_fail->SetBorderMode(0);
   plots_fit_s/base_figs/postfit_projx0_fail->SetBorderSize(2);
   plots_fit_s/base_figs/postfit_projx0_fail->SetTickx(1);
   plots_fit_s/base_figs/postfit_projx0_fail->SetTicky(1);
   plots_fit_s/base_figs/postfit_projx0_fail->SetLeftMargin(0.16);
   plots_fit_s/base_figs/postfit_projx0_fail->SetRightMargin(0);
   plots_fit_s/base_figs/postfit_projx0_fail->SetTopMargin(0);
   plots_fit_s/base_figs/postfit_projx0_fail->SetBottomMargin(0);
   plots_fit_s/base_figs/postfit_projx0_fail->SetFrameFillStyle(0);
   plots_fit_s/base_figs/postfit_projx0_fail->SetFrameBorderMode(0);
  
// ------------>Primitives in pad: data_obs_fail_postfit_projx0_main
   TPad *data_obs_fail_postfit_projx0_main = new TPad("data_obs_fail_postfit_projx0_main", "data_obs_fail_postfit_projx0_main",0,0.35,1,1);
   data_obs_fail_postfit_projx0_main->Draw();
   data_obs_fail_postfit_projx0_main->cd();
   data_obs_fail_postfit_projx0_main->Range(-0.2179487,-0.04651163,1.064103,1.116279);
   data_obs_fail_postfit_projx0_main->SetFillColor(0);
   data_obs_fail_postfit_projx0_main->SetBorderMode(0);
   data_obs_fail_postfit_projx0_main->SetBorderSize(2);
   data_obs_fail_postfit_projx0_main->SetTickx(1);
   data_obs_fail_postfit_projx0_main->SetTicky(1);
   data_obs_fail_postfit_projx0_main->SetLeftMargin(0.17);
   data_obs_fail_postfit_projx0_main->SetRightMargin(0.05);
   data_obs_fail_postfit_projx0_main->SetBottomMargin(0.04);
   data_obs_fail_postfit_projx0_main->SetFrameFillStyle(0);
   data_obs_fail_postfit_projx0_main->SetFrameBorderMode(0);
   data_obs_fail_postfit_projx0_main->SetFrameFillStyle(0);
   data_obs_fail_postfit_projx0_main->SetFrameBorderMode(0);
   Double_t xAxis265[10] = {0, 0.04, 0.08, 0.12, 0.16, 0.2, 0.24, 0.28, 0.32, 1}; 
   
   TH1D *data_obs_fail_postfit_projx0__169 = new TH1D("data_obs_fail_postfit_projx0__169","",9, xAxis265);
   data_obs_fail_postfit_projx0__169->SetMinimum(0);
   data_obs_fail_postfit_projx0__169->SetMaximum(0);

   Int_t ci;      // for color index setting
   TColor *color; // for color definition with alpha
   ci = TColor::GetColor("#000000");
   data_obs_fail_postfit_projx0__169->SetLineColor(ci);
   data_obs_fail_postfit_projx0__169->SetLineStyle(0);

   ci = TColor::GetColor("#000000");
   data_obs_fail_postfit_projx0__169->SetMarkerColor(ci);
   data_obs_fail_postfit_projx0__169->SetMarkerStyle(8);
   data_obs_fail_postfit_projx0__169->GetXaxis()->SetTitle("G_{i}^{Strips}");
   data_obs_fail_postfit_projx0__169->GetXaxis()->SetLabelFont(42);
   data_obs_fail_postfit_projx0__169->GetXaxis()->SetLabelOffset(0.05);
   data_obs_fail_postfit_projx0__169->GetXaxis()->SetLabelSize(0.07);
   data_obs_fail_postfit_projx0__169->GetXaxis()->SetTitleSize(0.09);
   data_obs_fail_postfit_projx0__169->GetXaxis()->SetTitleOffset(1.15);
   data_obs_fail_postfit_projx0__169->GetXaxis()->SetTitleFont(42);
   data_obs_fail_postfit_projx0__169->GetYaxis()->SetTitle("Events / bin");
   data_obs_fail_postfit_projx0__169->GetYaxis()->SetNdivisions(508);
   data_obs_fail_postfit_projx0__169->GetYaxis()->SetLabelFont(42);
   data_obs_fail_postfit_projx0__169->GetYaxis()->SetLabelOffset(0.007);
   data_obs_fail_postfit_projx0__169->GetYaxis()->SetLabelSize(0.07);
   data_obs_fail_postfit_projx0__169->GetYaxis()->SetTitleSize(0.09);
   data_obs_fail_postfit_projx0__169->GetYaxis()->SetTitleOffset(0.8);
   data_obs_fail_postfit_projx0__169->GetYaxis()->SetTitleFont(42);
   data_obs_fail_postfit_projx0__169->GetZaxis()->SetLabelFont(42);
   data_obs_fail_postfit_projx0__169->GetZaxis()->SetLabelOffset(0.007);
   data_obs_fail_postfit_projx0__169->GetZaxis()->SetLabelSize(0.05);
   data_obs_fail_postfit_projx0__169->GetZaxis()->SetTitleSize(0.08);
   data_obs_fail_postfit_projx0__169->GetZaxis()->SetTitleFont(42);
   data_obs_fail_postfit_projx0__169->Draw("pe X0");
   
   THStack *postfit_projx0_fail_stack = new THStack();
   postfit_projx0_fail_stack->SetName("postfit_projx0_fail_stack");
   postfit_projx0_fail_stack->SetTitle("postfit_projx0_fail_stack");
   Double_t xAxis266[10] = {0, 0.04, 0.08, 0.12, 0.16, 0.2, 0.24, 0.28, 0.32, 1}; 
   
   TH1F *postfit_projx0_fail_stack_stack_49 = new TH1F("postfit_projx0_fail_stack_stack_49","postfit_projx0_fail_stack",9, xAxis266);
   postfit_projx0_fail_stack_stack_49->SetMinimum(0);
   postfit_projx0_fail_stack_stack_49->SetMaximum(0);
   postfit_projx0_fail_stack_stack_49->SetDirectory(0);
   postfit_projx0_fail_stack_stack_49->SetStats(0);
   postfit_projx0_fail_stack_stack_49->SetLineStyle(0);
   postfit_projx0_fail_stack_stack_49->GetXaxis()->SetLabelFont(42);
   postfit_projx0_fail_stack_stack_49->GetXaxis()->SetLabelOffset(0.007);
   postfit_projx0_fail_stack_stack_49->GetXaxis()->SetLabelSize(0.05);
   postfit_projx0_fail_stack_stack_49->GetXaxis()->SetTitleSize(0.08);
   postfit_projx0_fail_stack_stack_49->GetXaxis()->SetTitleOffset(0.9);
   postfit_projx0_fail_stack_stack_49->GetXaxis()->SetTitleFont(42);
   postfit_projx0_fail_stack_stack_49->GetYaxis()->SetNdivisions(508);
   postfit_projx0_fail_stack_stack_49->GetYaxis()->SetLabelFont(42);
   postfit_projx0_fail_stack_stack_49->GetYaxis()->SetLabelOffset(0.007);
   postfit_projx0_fail_stack_stack_49->GetYaxis()->SetLabelSize(0.05);
   postfit_projx0_fail_stack_stack_49->GetYaxis()->SetTitleSize(0.08);
   postfit_projx0_fail_stack_stack_49->GetYaxis()->SetTitleOffset(1.25);
   postfit_projx0_fail_stack_stack_49->GetYaxis()->SetTitleFont(42);
   postfit_projx0_fail_stack_stack_49->GetZaxis()->SetLabelFont(42);
   postfit_projx0_fail_stack_stack_49->GetZaxis()->SetLabelOffset(0.007);
   postfit_projx0_fail_stack_stack_49->GetZaxis()->SetLabelSize(0.05);
   postfit_projx0_fail_stack_stack_49->GetZaxis()->SetTitleSize(0.08);
   postfit_projx0_fail_stack_stack_49->GetZaxis()->SetTitleFont(42);
   postfit_projx0_fail_stack->SetHistogram(postfit_projx0_fail_stack_stack_49);
   
   Double_t xAxis267[10] = {0, 0.04, 0.08, 0.12, 0.16, 0.2, 0.24, 0.28, 0.32, 1}; 
   
   TH1D *Background_fail_postfit_projx0_stack_1 = new TH1D("Background_fail_postfit_projx0_stack_1","Background, fail, postfit, 50-50",9, xAxis267);
   Background_fail_postfit_projx0_stack_1->SetMinimum(0);

   ci = TColor::GetColor("#ffff00");
   Background_fail_postfit_projx0_stack_1->SetFillColor(ci);

   ci = 1305;
   color = new TColor(ci, 1, 1, 1, " ", 0);
   Background_fail_postfit_projx0_stack_1->SetLineColor(ci);
   Background_fail_postfit_projx0_stack_1->SetLineStyle(0);
   Background_fail_postfit_projx0_stack_1->GetXaxis()->SetTitle("G_{i}^{Strips}");
   Background_fail_postfit_projx0_stack_1->GetXaxis()->SetLabelFont(42);
   Background_fail_postfit_projx0_stack_1->GetXaxis()->SetLabelOffset(0.007);
   Background_fail_postfit_projx0_stack_1->GetXaxis()->SetLabelSize(0.05);
   Background_fail_postfit_projx0_stack_1->GetXaxis()->SetTitleSize(0.08);
   Background_fail_postfit_projx0_stack_1->GetXaxis()->SetTitleOffset(0.9);
   Background_fail_postfit_projx0_stack_1->GetXaxis()->SetTitleFont(42);
   Background_fail_postfit_projx0_stack_1->GetYaxis()->SetTitle("Events / bin");
   Background_fail_postfit_projx0_stack_1->GetYaxis()->SetLabelFont(42);
   Background_fail_postfit_projx0_stack_1->GetYaxis()->SetLabelOffset(0.007);
   Background_fail_postfit_projx0_stack_1->GetYaxis()->SetLabelSize(0.05);
   Background_fail_postfit_projx0_stack_1->GetYaxis()->SetTitleSize(0.08);
   Background_fail_postfit_projx0_stack_1->GetYaxis()->SetTitleOffset(1.25);
   Background_fail_postfit_projx0_stack_1->GetYaxis()->SetTitleFont(42);
   Background_fail_postfit_projx0_stack_1->GetZaxis()->SetLabelFont(42);
   Background_fail_postfit_projx0_stack_1->GetZaxis()->SetLabelOffset(0.007);
   Background_fail_postfit_projx0_stack_1->GetZaxis()->SetLabelSize(0.05);
   Background_fail_postfit_projx0_stack_1->GetZaxis()->SetTitleSize(0.08);
   Background_fail_postfit_projx0_stack_1->GetZaxis()->SetTitleFont(42);
   postfit_projx0_fail_stack->Add(Background_fail_postfit_projx0_stack_1,"");
   postfit_projx0_fail_stack->Draw("hist same");
   
   postfit_projx0_fail_stack = new THStack();
   postfit_projx0_fail_stack->SetName("postfit_projx0_fail_stack");
   postfit_projx0_fail_stack->SetTitle("postfit_projx0_fail_stack");
   Double_t xAxis268[10] = {0, 0.04, 0.08, 0.12, 0.16, 0.2, 0.24, 0.28, 0.32, 1}; 
   
   TH1F *postfit_projx0_fail_stack_stack_49_stack_50 = new TH1F("postfit_projx0_fail_stack_stack_49_stack_50","postfit_projx0_fail_stack",9, xAxis268);
   postfit_projx0_fail_stack_stack_49_stack_50->SetMinimum(0);
   postfit_projx0_fail_stack_stack_49_stack_50->SetMaximum(0);
   postfit_projx0_fail_stack_stack_49_stack_50->SetDirectory(0);
   postfit_projx0_fail_stack_stack_49_stack_50->SetStats(0);
   postfit_projx0_fail_stack_stack_49_stack_50->SetLineStyle(0);
   postfit_projx0_fail_stack_stack_49_stack_50->GetXaxis()->SetLabelFont(42);
   postfit_projx0_fail_stack_stack_49_stack_50->GetXaxis()->SetLabelOffset(0.007);
   postfit_projx0_fail_stack_stack_49_stack_50->GetXaxis()->SetLabelSize(0.05);
   postfit_projx0_fail_stack_stack_49_stack_50->GetXaxis()->SetTitleSize(0.08);
   postfit_projx0_fail_stack_stack_49_stack_50->GetXaxis()->SetTitleOffset(0.9);
   postfit_projx0_fail_stack_stack_49_stack_50->GetXaxis()->SetTitleFont(42);
   postfit_projx0_fail_stack_stack_49_stack_50->GetYaxis()->SetNdivisions(508);
   postfit_projx0_fail_stack_stack_49_stack_50->GetYaxis()->SetLabelFont(42);
   postfit_projx0_fail_stack_stack_49_stack_50->GetYaxis()->SetLabelOffset(0.007);
   postfit_projx0_fail_stack_stack_49_stack_50->GetYaxis()->SetLabelSize(0.05);
   postfit_projx0_fail_stack_stack_49_stack_50->GetYaxis()->SetTitleSize(0.08);
   postfit_projx0_fail_stack_stack_49_stack_50->GetYaxis()->SetTitleOffset(1.25);
   postfit_projx0_fail_stack_stack_49_stack_50->GetYaxis()->SetTitleFont(42);
   postfit_projx0_fail_stack_stack_49_stack_50->GetZaxis()->SetLabelFont(42);
   postfit_projx0_fail_stack_stack_49_stack_50->GetZaxis()->SetLabelOffset(0.007);
   postfit_projx0_fail_stack_stack_49_stack_50->GetZaxis()->SetLabelSize(0.05);
   postfit_projx0_fail_stack_stack_49_stack_50->GetZaxis()->SetTitleSize(0.08);
   postfit_projx0_fail_stack_stack_49_stack_50->GetZaxis()->SetTitleFont(42);
   postfit_projx0_fail_stack->SetHistogram(postfit_projx0_fail_stack_stack_49_stack_50);
   
   Double_t xAxis269[10] = {0, 0.04, 0.08, 0.12, 0.16, 0.2, 0.24, 0.28, 0.32, 1}; 
   
   TH1D *Background_fail_postfit_projx0_stack_1_stack_1 = new TH1D("Background_fail_postfit_projx0_stack_1_stack_1","Background, fail, postfit, 50-50",9, xAxis269);
   Background_fail_postfit_projx0_stack_1_stack_1->SetMinimum(0);

   ci = TColor::GetColor("#ffff00");
   Background_fail_postfit_projx0_stack_1_stack_1->SetFillColor(ci);

   ci = 1305;
   color = new TColor(ci, 1, 1, 1, " ", 0);
   Background_fail_postfit_projx0_stack_1_stack_1->SetLineColor(ci);
   Background_fail_postfit_projx0_stack_1_stack_1->SetLineStyle(0);
   Background_fail_postfit_projx0_stack_1_stack_1->GetXaxis()->SetTitle("G_{i}^{Strips}");
   Background_fail_postfit_projx0_stack_1_stack_1->GetXaxis()->SetLabelFont(42);
   Background_fail_postfit_projx0_stack_1_stack_1->GetXaxis()->SetLabelOffset(0.007);
   Background_fail_postfit_projx0_stack_1_stack_1->GetXaxis()->SetLabelSize(0.05);
   Background_fail_postfit_projx0_stack_1_stack_1->GetXaxis()->SetTitleSize(0.08);
   Background_fail_postfit_projx0_stack_1_stack_1->GetXaxis()->SetTitleOffset(0.9);
   Background_fail_postfit_projx0_stack_1_stack_1->GetXaxis()->SetTitleFont(42);
   Background_fail_postfit_projx0_stack_1_stack_1->GetYaxis()->SetTitle("Events / bin");
   Background_fail_postfit_projx0_stack_1_stack_1->GetYaxis()->SetLabelFont(42);
   Background_fail_postfit_projx0_stack_1_stack_1->GetYaxis()->SetLabelOffset(0.007);
   Background_fail_postfit_projx0_stack_1_stack_1->GetYaxis()->SetLabelSize(0.05);
   Background_fail_postfit_projx0_stack_1_stack_1->GetYaxis()->SetTitleSize(0.08);
   Background_fail_postfit_projx0_stack_1_stack_1->GetYaxis()->SetTitleOffset(1.25);
   Background_fail_postfit_projx0_stack_1_stack_1->GetYaxis()->SetTitleFont(42);
   Background_fail_postfit_projx0_stack_1_stack_1->GetZaxis()->SetLabelFont(42);
   Background_fail_postfit_projx0_stack_1_stack_1->GetZaxis()->SetLabelOffset(0.007);
   Background_fail_postfit_projx0_stack_1_stack_1->GetZaxis()->SetLabelSize(0.05);
   Background_fail_postfit_projx0_stack_1_stack_1->GetZaxis()->SetTitleSize(0.08);
   Background_fail_postfit_projx0_stack_1_stack_1->GetZaxis()->SetTitleFont(42);
   postfit_projx0_fail_stack->Add(Background_fail_postfit_projx0_stack_1_stack_1,"");
   postfit_projx0_fail_stack->Draw("hist same");
   Double_t xAxis270[10] = {0, 0.04, 0.08, 0.12, 0.16, 0.2, 0.24, 0.28, 0.32, 1}; 
   
   TH1D *Signal_ppStaumI557_fail_postfit_projx0__170 = new TH1D("Signal_ppStaumI557_fail_postfit_projx0__170","HSCP signal, fail, postfit, 50-50",9, xAxis270);
   Signal_ppStaumI557_fail_postfit_projx0__170->SetMinimum(0);
   Signal_ppStaumI557_fail_postfit_projx0__170->SetLineColor(2);
   Signal_ppStaumI557_fail_postfit_projx0__170->SetLineStyle(0);
   Signal_ppStaumI557_fail_postfit_projx0__170->GetXaxis()->SetTitle("G_{i}^{Strips}");
   Signal_ppStaumI557_fail_postfit_projx0__170->GetXaxis()->SetLabelFont(42);
   Signal_ppStaumI557_fail_postfit_projx0__170->GetXaxis()->SetLabelOffset(0.007);
   Signal_ppStaumI557_fail_postfit_projx0__170->GetXaxis()->SetLabelSize(0.05);
   Signal_ppStaumI557_fail_postfit_projx0__170->GetXaxis()->SetTitleSize(0.08);
   Signal_ppStaumI557_fail_postfit_projx0__170->GetXaxis()->SetTitleOffset(0.9);
   Signal_ppStaumI557_fail_postfit_projx0__170->GetXaxis()->SetTitleFont(42);
   Signal_ppStaumI557_fail_postfit_projx0__170->GetYaxis()->SetTitle("Events / bin");
   Signal_ppStaumI557_fail_postfit_projx0__170->GetYaxis()->SetLabelFont(42);
   Signal_ppStaumI557_fail_postfit_projx0__170->GetYaxis()->SetLabelOffset(0.007);
   Signal_ppStaumI557_fail_postfit_projx0__170->GetYaxis()->SetLabelSize(0.05);
   Signal_ppStaumI557_fail_postfit_projx0__170->GetYaxis()->SetTitleSize(0.08);
   Signal_ppStaumI557_fail_postfit_projx0__170->GetYaxis()->SetTitleOffset(1.25);
   Signal_ppStaumI557_fail_postfit_projx0__170->GetYaxis()->SetTitleFont(42);
   Signal_ppStaumI557_fail_postfit_projx0__170->GetZaxis()->SetLabelFont(42);
   Signal_ppStaumI557_fail_postfit_projx0__170->GetZaxis()->SetLabelOffset(0.007);
   Signal_ppStaumI557_fail_postfit_projx0__170->GetZaxis()->SetLabelSize(0.05);
   Signal_ppStaumI557_fail_postfit_projx0__170->GetZaxis()->SetTitleSize(0.08);
   Signal_ppStaumI557_fail_postfit_projx0__170->GetZaxis()->SetTitleFont(42);
   Signal_ppStaumI557_fail_postfit_projx0__170->Draw("hist same");
   Double_t xAxis271[10] = {0, 0.04, 0.08, 0.12, 0.16, 0.2, 0.24, 0.28, 0.32, 1}; 
   
   TH1D *TotalBkg_fail_postfit_projx0__171 = new TH1D("TotalBkg_fail_postfit_projx0__171","TotalBkg, fail, postfit, 50-50",9, xAxis271);
   TotalBkg_fail_postfit_projx0__171->SetMinimum(0);
   TotalBkg_fail_postfit_projx0__171->SetLineStyle(0);
   TotalBkg_fail_postfit_projx0__171->SetMarkerStyle(0);
   TotalBkg_fail_postfit_projx0__171->GetXaxis()->SetTitle("G_{i}^{Strips}");
   TotalBkg_fail_postfit_projx0__171->GetXaxis()->SetLabelFont(42);
   TotalBkg_fail_postfit_projx0__171->GetXaxis()->SetLabelOffset(0.007);
   TotalBkg_fail_postfit_projx0__171->GetXaxis()->SetLabelSize(0.05);
   TotalBkg_fail_postfit_projx0__171->GetXaxis()->SetTitleSize(0.08);
   TotalBkg_fail_postfit_projx0__171->GetXaxis()->SetTitleOffset(0.9);
   TotalBkg_fail_postfit_projx0__171->GetXaxis()->SetTitleFont(42);
   TotalBkg_fail_postfit_projx0__171->GetYaxis()->SetTitle("Events / bin");
   TotalBkg_fail_postfit_projx0__171->GetYaxis()->SetLabelFont(42);
   TotalBkg_fail_postfit_projx0__171->GetYaxis()->SetLabelOffset(0.007);
   TotalBkg_fail_postfit_projx0__171->GetYaxis()->SetLabelSize(0.05);
   TotalBkg_fail_postfit_projx0__171->GetYaxis()->SetTitleSize(0.08);
   TotalBkg_fail_postfit_projx0__171->GetYaxis()->SetTitleOffset(1.25);
   TotalBkg_fail_postfit_projx0__171->GetYaxis()->SetTitleFont(42);
   TotalBkg_fail_postfit_projx0__171->GetZaxis()->SetLabelFont(42);
   TotalBkg_fail_postfit_projx0__171->GetZaxis()->SetLabelOffset(0.007);
   TotalBkg_fail_postfit_projx0__171->GetZaxis()->SetLabelSize(0.05);
   TotalBkg_fail_postfit_projx0__171->GetZaxis()->SetTitleSize(0.08);
   TotalBkg_fail_postfit_projx0__171->GetZaxis()->SetTitleFont(42);
   TotalBkg_fail_postfit_projx0__171->Draw("hist same");
   Double_t xAxis272[10] = {0, 0.04, 0.08, 0.12, 0.16, 0.2, 0.24, 0.28, 0.32, 1}; 
   
   TH1D *TotalBkg_fail_postfit_projx0__172 = new TH1D("TotalBkg_fail_postfit_projx0__172","TotalBkg, fail, postfit, 50-50",9, xAxis272);
   TotalBkg_fail_postfit_projx0__172->SetMinimum(0);
   TotalBkg_fail_postfit_projx0__172->SetFillColor(1);
   TotalBkg_fail_postfit_projx0__172->SetFillStyle(3354);
   TotalBkg_fail_postfit_projx0__172->SetLineStyle(0);
   TotalBkg_fail_postfit_projx0__172->SetLineWidth(0);
   TotalBkg_fail_postfit_projx0__172->SetMarkerStyle(0);
   TotalBkg_fail_postfit_projx0__172->GetXaxis()->SetTitle("G_{i}^{Strips}");
   TotalBkg_fail_postfit_projx0__172->GetXaxis()->SetLabelFont(42);
   TotalBkg_fail_postfit_projx0__172->GetXaxis()->SetLabelOffset(0.007);
   TotalBkg_fail_postfit_projx0__172->GetXaxis()->SetLabelSize(0.05);
   TotalBkg_fail_postfit_projx0__172->GetXaxis()->SetTitleSize(0.08);
   TotalBkg_fail_postfit_projx0__172->GetXaxis()->SetTitleOffset(0.9);
   TotalBkg_fail_postfit_projx0__172->GetXaxis()->SetTitleFont(42);
   TotalBkg_fail_postfit_projx0__172->GetYaxis()->SetTitle("Events / bin");
   TotalBkg_fail_postfit_projx0__172->GetYaxis()->SetLabelFont(42);
   TotalBkg_fail_postfit_projx0__172->GetYaxis()->SetLabelOffset(0.007);
   TotalBkg_fail_postfit_projx0__172->GetYaxis()->SetLabelSize(0.05);
   TotalBkg_fail_postfit_projx0__172->GetYaxis()->SetTitleSize(0.08);
   TotalBkg_fail_postfit_projx0__172->GetYaxis()->SetTitleOffset(1.25);
   TotalBkg_fail_postfit_projx0__172->GetYaxis()->SetTitleFont(42);
   TotalBkg_fail_postfit_projx0__172->GetZaxis()->SetLabelFont(42);
   TotalBkg_fail_postfit_projx0__172->GetZaxis()->SetLabelOffset(0.007);
   TotalBkg_fail_postfit_projx0__172->GetZaxis()->SetLabelSize(0.05);
   TotalBkg_fail_postfit_projx0__172->GetZaxis()->SetTitleSize(0.08);
   TotalBkg_fail_postfit_projx0__172->GetZaxis()->SetTitleFont(42);
   TotalBkg_fail_postfit_projx0__172->Draw("e2 same");
   Double_t xAxis273[10] = {0, 0.04, 0.08, 0.12, 0.16, 0.2, 0.24, 0.28, 0.32, 1}; 
   
   TH1D *data_obs_fail_postfit_projx0__173 = new TH1D("data_obs_fail_postfit_projx0__173","",9, xAxis273);
   data_obs_fail_postfit_projx0__173->SetMinimum(0);
   data_obs_fail_postfit_projx0__173->SetMaximum(0);

   ci = TColor::GetColor("#000000");
   data_obs_fail_postfit_projx0__173->SetLineColor(ci);
   data_obs_fail_postfit_projx0__173->SetLineStyle(0);

   ci = TColor::GetColor("#000000");
   data_obs_fail_postfit_projx0__173->SetMarkerColor(ci);
   data_obs_fail_postfit_projx0__173->SetMarkerStyle(8);
   data_obs_fail_postfit_projx0__173->GetXaxis()->SetTitle("G_{i}^{Strips}");
   data_obs_fail_postfit_projx0__173->GetXaxis()->SetLabelFont(42);
   data_obs_fail_postfit_projx0__173->GetXaxis()->SetLabelOffset(0.05);
   data_obs_fail_postfit_projx0__173->GetXaxis()->SetLabelSize(0.07);
   data_obs_fail_postfit_projx0__173->GetXaxis()->SetTitleSize(0.09);
   data_obs_fail_postfit_projx0__173->GetXaxis()->SetTitleOffset(1.15);
   data_obs_fail_postfit_projx0__173->GetXaxis()->SetTitleFont(42);
   data_obs_fail_postfit_projx0__173->GetYaxis()->SetTitle("Events / bin");
   data_obs_fail_postfit_projx0__173->GetYaxis()->SetNdivisions(508);
   data_obs_fail_postfit_projx0__173->GetYaxis()->SetLabelFont(42);
   data_obs_fail_postfit_projx0__173->GetYaxis()->SetLabelOffset(0.007);
   data_obs_fail_postfit_projx0__173->GetYaxis()->SetLabelSize(0.07);
   data_obs_fail_postfit_projx0__173->GetYaxis()->SetTitleSize(0.09);
   data_obs_fail_postfit_projx0__173->GetYaxis()->SetTitleOffset(0.8);
   data_obs_fail_postfit_projx0__173->GetYaxis()->SetTitleFont(42);
   data_obs_fail_postfit_projx0__173->GetZaxis()->SetLabelFont(42);
   data_obs_fail_postfit_projx0__173->GetZaxis()->SetLabelOffset(0.007);
   data_obs_fail_postfit_projx0__173->GetZaxis()->SetLabelSize(0.05);
   data_obs_fail_postfit_projx0__173->GetZaxis()->SetTitleSize(0.08);
   data_obs_fail_postfit_projx0__173->GetZaxis()->SetTitleFont(42);
   data_obs_fail_postfit_projx0__173->Draw("pe X0 same");
   
   TLegend *leg = new TLegend(0.65,0.64,0.9,0.88,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(1001);
   TLegendEntry *entry=leg->AddEntry("data_obs_fail_postfit_projx0","Data","pe X0");

   ci = TColor::GetColor("#000000");
   entry->SetLineColor(ci);
   entry->SetLineWidth(1);

   ci = TColor::GetColor("#000000");
   entry->SetMarkerColor(ci);
   entry->SetMarkerStyle(8);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("TotalBkg_fail_postfit_projx0","Total bkg unc.","F");
   entry->SetFillColor(1);
   entry->SetFillStyle(3354);
   entry->SetLineColor(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("Signal_ppStau-557_fail_postfit_projx0","HSCP signal","L");
   entry->SetLineColor(2);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("Background_fail_postfit_projx0_stack_1_stack_1","Background","f");

   ci = TColor::GetColor("#ffff00");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = 1305;
   color = new TColor(ci, 1, 1, 1, " ", 0);
   entry->SetLineColor(ci);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   leg->Draw();
   Double_t xAxis274[10] = {0, 0.04, 0.08, 0.12, 0.16, 0.2, 0.24, 0.28, 0.32, 1}; 
   
   TH1D *data_obs_fail_postfit_projx0_copy__174 = new TH1D("data_obs_fail_postfit_projx0_copy__174","",9, xAxis274);
   data_obs_fail_postfit_projx0_copy__174->SetMinimum(0);
   data_obs_fail_postfit_projx0_copy__174->SetMaximum(0);
   data_obs_fail_postfit_projx0_copy__174->SetDirectory(0);

   ci = TColor::GetColor("#000000");
   data_obs_fail_postfit_projx0_copy__174->SetLineColor(ci);
   data_obs_fail_postfit_projx0_copy__174->SetLineStyle(0);

   ci = TColor::GetColor("#000000");
   data_obs_fail_postfit_projx0_copy__174->SetMarkerColor(ci);
   data_obs_fail_postfit_projx0_copy__174->SetMarkerStyle(8);
   data_obs_fail_postfit_projx0_copy__174->GetXaxis()->SetTitle("G_{i}^{Strips}");
   data_obs_fail_postfit_projx0_copy__174->GetXaxis()->SetLabelFont(42);
   data_obs_fail_postfit_projx0_copy__174->GetXaxis()->SetLabelOffset(0.05);
   data_obs_fail_postfit_projx0_copy__174->GetXaxis()->SetLabelSize(0.07);
   data_obs_fail_postfit_projx0_copy__174->GetXaxis()->SetTitleSize(0.09);
   data_obs_fail_postfit_projx0_copy__174->GetXaxis()->SetTitleOffset(1.15);
   data_obs_fail_postfit_projx0_copy__174->GetXaxis()->SetTitleFont(42);
   data_obs_fail_postfit_projx0_copy__174->GetYaxis()->SetTitle("Events / bin");
   data_obs_fail_postfit_projx0_copy__174->GetYaxis()->SetNdivisions(508);
   data_obs_fail_postfit_projx0_copy__174->GetYaxis()->SetLabelFont(42);
   data_obs_fail_postfit_projx0_copy__174->GetYaxis()->SetLabelOffset(0.007);
   data_obs_fail_postfit_projx0_copy__174->GetYaxis()->SetLabelSize(0.07);
   data_obs_fail_postfit_projx0_copy__174->GetYaxis()->SetTitleSize(0.09);
   data_obs_fail_postfit_projx0_copy__174->GetYaxis()->SetTitleOffset(0.8);
   data_obs_fail_postfit_projx0_copy__174->GetYaxis()->SetTitleFont(42);
   data_obs_fail_postfit_projx0_copy__174->GetZaxis()->SetLabelFont(42);
   data_obs_fail_postfit_projx0_copy__174->GetZaxis()->SetLabelOffset(0.007);
   data_obs_fail_postfit_projx0_copy__174->GetZaxis()->SetLabelSize(0.05);
   data_obs_fail_postfit_projx0_copy__174->GetZaxis()->SetTitleSize(0.08);
   data_obs_fail_postfit_projx0_copy__174->GetZaxis()->SetTitleFont(42);
   data_obs_fail_postfit_projx0_copy__174->Draw("sameaxis");
   TLatex *   tex = new TLatex(0.21,0.83,"55 < p_{T} < 200 GeV, F^{Pixels}_{i} < 0.9");
tex->SetNDC();
   tex->SetTextAlign(12);
   tex->SetTextFont(42);
   tex->SetTextSize(0.06);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.17,0.92,"CMS");
tex->SetNDC();
   tex->SetTextFont(61);
   tex->SetTextSize(0.0675);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.25,0.92,"Preliminary");
tex->SetNDC();
   tex->SetTextFont(52);
   tex->SetTextSize(0.0485);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.95,0.92,"101 fb^{-1} (13 TeV)");
tex->SetNDC();
   tex->SetTextAlign(31);
   tex->SetTextFont(42);
   tex->SetTextSize(0.07);
   tex->SetLineWidth(2);
   tex->Draw();
   data_obs_fail_postfit_projx0_main->Modified();
   plots_fit_s/base_figs/postfit_projx0_fail->cd();
  
// ------------>Primitives in pad: data_obs_fail_postfit_projx0_sub
   TPad *data_obs_fail_postfit_projx0_sub = new TPad("data_obs_fail_postfit_projx0_sub", "data_obs_fail_postfit_projx0_sub",0,0,1,0.35);
   data_obs_fail_postfit_projx0_sub->Draw();
   data_obs_fail_postfit_projx0_sub->cd();
   data_obs_fail_postfit_projx0_sub->Range(-0.2179487,-6.023077,1.064103,2.9);
   data_obs_fail_postfit_projx0_sub->SetFillColor(0);
   data_obs_fail_postfit_projx0_sub->SetBorderMode(0);
   data_obs_fail_postfit_projx0_sub->SetBorderSize(2);
   data_obs_fail_postfit_projx0_sub->SetTickx(1);
   data_obs_fail_postfit_projx0_sub->SetTicky(1);
   data_obs_fail_postfit_projx0_sub->SetLeftMargin(0.17);
   data_obs_fail_postfit_projx0_sub->SetRightMargin(0.05);
   data_obs_fail_postfit_projx0_sub->SetTopMargin(0);
   data_obs_fail_postfit_projx0_sub->SetBottomMargin(0.35);
   data_obs_fail_postfit_projx0_sub->SetFrameFillStyle(0);
   data_obs_fail_postfit_projx0_sub->SetFrameBorderMode(0);
   data_obs_fail_postfit_projx0_sub->SetFrameFillStyle(0);
   data_obs_fail_postfit_projx0_sub->SetFrameBorderMode(0);
   Double_t xAxis275[10] = {0, 0.04, 0.08, 0.12, 0.16, 0.2, 0.24, 0.28, 0.32, 1}; 
   
   TH1D *data_obs_fail_postfit_projx0_pull__175 = new TH1D("data_obs_fail_postfit_projx0_pull__175","",9, xAxis275);
   data_obs_fail_postfit_projx0_pull__175->SetMinimum(-2.9);
   data_obs_fail_postfit_projx0_pull__175->SetMaximum(2.9);
   data_obs_fail_postfit_projx0_pull__175->SetEntries(18);
   data_obs_fail_postfit_projx0_pull__175->SetStats(0);

   ci = TColor::GetColor("#0000ff");
   data_obs_fail_postfit_projx0_pull__175->SetFillColor(ci);

   ci = TColor::GetColor("#000000");
   data_obs_fail_postfit_projx0_pull__175->SetLineColor(ci);
   data_obs_fail_postfit_projx0_pull__175->SetLineStyle(0);

   ci = TColor::GetColor("#000000");
   data_obs_fail_postfit_projx0_pull__175->SetMarkerColor(ci);
   data_obs_fail_postfit_projx0_pull__175->SetMarkerStyle(8);
   data_obs_fail_postfit_projx0_pull__175->GetXaxis()->SetTitle("G_{i}^{Strips}");
   data_obs_fail_postfit_projx0_pull__175->GetXaxis()->SetLabelFont(42);
   data_obs_fail_postfit_projx0_pull__175->GetXaxis()->SetLabelOffset(0.05);
   data_obs_fail_postfit_projx0_pull__175->GetXaxis()->SetLabelSize(0.13);
   data_obs_fail_postfit_projx0_pull__175->GetXaxis()->SetTitleSize(0.15);
   data_obs_fail_postfit_projx0_pull__175->GetXaxis()->SetTitleOffset(1.15);
   data_obs_fail_postfit_projx0_pull__175->GetXaxis()->SetTitleFont(42);
   data_obs_fail_postfit_projx0_pull__175->GetYaxis()->SetTitle("(Data-Bkg)/#sigma");
   data_obs_fail_postfit_projx0_pull__175->GetYaxis()->SetNdivisions(306);
   data_obs_fail_postfit_projx0_pull__175->GetYaxis()->SetLabelFont(42);
   data_obs_fail_postfit_projx0_pull__175->GetYaxis()->SetLabelOffset(0.007);
   data_obs_fail_postfit_projx0_pull__175->GetYaxis()->SetLabelSize(0.13);
   data_obs_fail_postfit_projx0_pull__175->GetYaxis()->SetTitleSize(0.12);
   data_obs_fail_postfit_projx0_pull__175->GetYaxis()->SetTitleOffset(0.4);
   data_obs_fail_postfit_projx0_pull__175->GetYaxis()->SetTitleFont(42);
   data_obs_fail_postfit_projx0_pull__175->GetZaxis()->SetLabelFont(42);
   data_obs_fail_postfit_projx0_pull__175->GetZaxis()->SetLabelOffset(0.007);
   data_obs_fail_postfit_projx0_pull__175->GetZaxis()->SetLabelSize(0.05);
   data_obs_fail_postfit_projx0_pull__175->GetZaxis()->SetTitleSize(0.08);
   data_obs_fail_postfit_projx0_pull__175->GetZaxis()->SetTitleFont(42);
   data_obs_fail_postfit_projx0_pull__175->Draw("hist");
   data_obs_fail_postfit_projx0_sub->Modified();
   plots_fit_s/base_figs/postfit_projx0_fail->cd();
   plots_fit_s/base_figs/postfit_projx0_fail->Modified();
   plots_fit_s/base_figs/postfit_projx0_fail->cd();
   plots_fit_s/base_figs/postfit_projx0_fail->SetSelected(plots_fit_s/base_figs/postfit_projx0_fail);
}
