void postfit_projy1_fail()
{
//=========Macro generated from canvas: plots_fit_s/base_figs/postfit_projy1_fail/plots_fit_s/base_figs/postfit_projy1_fail
//=========  (Fri Jan 12 21:00:08 2024) by ROOT version 6.14/09
   TCanvas *plots_fit_s/base_figs/postfit_projy1_fail = new TCanvas("plots_fit_s/base_figs/postfit_projy1_fail", "plots_fit_s/base_figs/postfit_projy1_fail",0,0,800,700);
   gStyle->SetOptFit(1);
   gStyle->SetOptStat(0);
   plots_fit_s/base_figs/postfit_projy1_fail->SetHighLightColor(2);
   plots_fit_s/base_figs/postfit_projy1_fail->Range(0,0,1,1);
   plots_fit_s/base_figs/postfit_projy1_fail->SetFillColor(0);
   plots_fit_s/base_figs/postfit_projy1_fail->SetBorderMode(0);
   plots_fit_s/base_figs/postfit_projy1_fail->SetBorderSize(2);
   plots_fit_s/base_figs/postfit_projy1_fail->SetTickx(1);
   plots_fit_s/base_figs/postfit_projy1_fail->SetTicky(1);
   plots_fit_s/base_figs/postfit_projy1_fail->SetLeftMargin(0.16);
   plots_fit_s/base_figs/postfit_projy1_fail->SetRightMargin(0);
   plots_fit_s/base_figs/postfit_projy1_fail->SetTopMargin(0);
   plots_fit_s/base_figs/postfit_projy1_fail->SetBottomMargin(0);
   plots_fit_s/base_figs/postfit_projy1_fail->SetFrameFillStyle(0);
   plots_fit_s/base_figs/postfit_projy1_fail->SetFrameBorderMode(0);
  
// ------------>Primitives in pad: data_obs_fail_postfit_projy1_main
   TPad *data_obs_fail_postfit_projy1_main = new TPad("data_obs_fail_postfit_projy1_main", "data_obs_fail_postfit_projy1_main",0,0.35,1,1);
   data_obs_fail_postfit_projy1_main->Draw();
   data_obs_fail_postfit_projy1_main->cd();
   data_obs_fail_postfit_projy1_main->Range(17.30769,-392.0651,209.6154,9409.562);
   data_obs_fail_postfit_projy1_main->SetFillColor(0);
   data_obs_fail_postfit_projy1_main->SetBorderMode(0);
   data_obs_fail_postfit_projy1_main->SetBorderSize(2);
   data_obs_fail_postfit_projy1_main->SetTickx(1);
   data_obs_fail_postfit_projy1_main->SetTicky(1);
   data_obs_fail_postfit_projy1_main->SetLeftMargin(0.17);
   data_obs_fail_postfit_projy1_main->SetRightMargin(0.05);
   data_obs_fail_postfit_projy1_main->SetBottomMargin(0.04);
   data_obs_fail_postfit_projy1_main->SetFrameFillStyle(0);
   data_obs_fail_postfit_projy1_main->SetFrameBorderMode(0);
   data_obs_fail_postfit_projy1_main->SetFrameFillStyle(0);
   data_obs_fail_postfit_projy1_main->SetFrameBorderMode(0);
   Double_t xAxis309[2] = {50, 200}; 
   
   TH1D *data_obs_fail_postfit_projy1__197 = new TH1D("data_obs_fail_postfit_projy1__197","",1, xAxis309);
   data_obs_fail_postfit_projy1__197->SetBinContent(1,6244);
   data_obs_fail_postfit_projy1__197->SetBinError(1,79.01899);
   data_obs_fail_postfit_projy1__197->SetMinimum(0);
   data_obs_fail_postfit_projy1__197->SetMaximum(8429.4);
   data_obs_fail_postfit_projy1__197->SetEntries(6244);

   Int_t ci;      // for color index setting
   TColor *color; // for color definition with alpha
   ci = TColor::GetColor("#000000");
   data_obs_fail_postfit_projy1__197->SetLineColor(ci);
   data_obs_fail_postfit_projy1__197->SetLineStyle(0);

   ci = TColor::GetColor("#000000");
   data_obs_fail_postfit_projy1__197->SetMarkerColor(ci);
   data_obs_fail_postfit_projy1__197->SetMarkerStyle(8);
   data_obs_fail_postfit_projy1__197->GetXaxis()->SetTitle("p_{T}");
   data_obs_fail_postfit_projy1__197->GetXaxis()->SetLabelFont(42);
   data_obs_fail_postfit_projy1__197->GetXaxis()->SetLabelOffset(0.05);
   data_obs_fail_postfit_projy1__197->GetXaxis()->SetLabelSize(0.07);
   data_obs_fail_postfit_projy1__197->GetXaxis()->SetTitleSize(0.09);
   data_obs_fail_postfit_projy1__197->GetXaxis()->SetTitleOffset(1.15);
   data_obs_fail_postfit_projy1__197->GetXaxis()->SetTitleFont(42);
   data_obs_fail_postfit_projy1__197->GetYaxis()->SetTitle("Events / bin");
   data_obs_fail_postfit_projy1__197->GetYaxis()->SetNdivisions(508);
   data_obs_fail_postfit_projy1__197->GetYaxis()->SetLabelFont(42);
   data_obs_fail_postfit_projy1__197->GetYaxis()->SetLabelOffset(0.007);
   data_obs_fail_postfit_projy1__197->GetYaxis()->SetLabelSize(0.07);
   data_obs_fail_postfit_projy1__197->GetYaxis()->SetTitleSize(0.09);
   data_obs_fail_postfit_projy1__197->GetYaxis()->SetTitleOffset(0.8);
   data_obs_fail_postfit_projy1__197->GetYaxis()->SetTitleFont(42);
   data_obs_fail_postfit_projy1__197->GetZaxis()->SetLabelFont(42);
   data_obs_fail_postfit_projy1__197->GetZaxis()->SetLabelOffset(0.007);
   data_obs_fail_postfit_projy1__197->GetZaxis()->SetLabelSize(0.05);
   data_obs_fail_postfit_projy1__197->GetZaxis()->SetTitleSize(0.08);
   data_obs_fail_postfit_projy1__197->GetZaxis()->SetTitleFont(42);
   data_obs_fail_postfit_projy1__197->Draw("pe X0");
   
   THStack *postfit_projy1_fail_stack = new THStack();
   postfit_projy1_fail_stack->SetName("postfit_projy1_fail_stack");
   postfit_projy1_fail_stack->SetTitle("postfit_projy1_fail_stack");
   Double_t xAxis310[2] = {50, 200}; 
   
   TH1F *postfit_projy1_fail_stack_stack_57 = new TH1F("postfit_projy1_fail_stack_stack_57","postfit_projy1_fail_stack",1, xAxis310);
   postfit_projy1_fail_stack_stack_57->SetMinimum(0);
   postfit_projy1_fail_stack_stack_57->SetMaximum(6592.18);
   postfit_projy1_fail_stack_stack_57->SetDirectory(0);
   postfit_projy1_fail_stack_stack_57->SetStats(0);
   postfit_projy1_fail_stack_stack_57->SetLineStyle(0);
   postfit_projy1_fail_stack_stack_57->GetXaxis()->SetLabelFont(42);
   postfit_projy1_fail_stack_stack_57->GetXaxis()->SetLabelOffset(0.007);
   postfit_projy1_fail_stack_stack_57->GetXaxis()->SetLabelSize(0.05);
   postfit_projy1_fail_stack_stack_57->GetXaxis()->SetTitleSize(0.08);
   postfit_projy1_fail_stack_stack_57->GetXaxis()->SetTitleOffset(0.9);
   postfit_projy1_fail_stack_stack_57->GetXaxis()->SetTitleFont(42);
   postfit_projy1_fail_stack_stack_57->GetYaxis()->SetNdivisions(508);
   postfit_projy1_fail_stack_stack_57->GetYaxis()->SetLabelFont(42);
   postfit_projy1_fail_stack_stack_57->GetYaxis()->SetLabelOffset(0.007);
   postfit_projy1_fail_stack_stack_57->GetYaxis()->SetLabelSize(0.05);
   postfit_projy1_fail_stack_stack_57->GetYaxis()->SetTitleSize(0.08);
   postfit_projy1_fail_stack_stack_57->GetYaxis()->SetTitleOffset(1.25);
   postfit_projy1_fail_stack_stack_57->GetYaxis()->SetTitleFont(42);
   postfit_projy1_fail_stack_stack_57->GetZaxis()->SetLabelFont(42);
   postfit_projy1_fail_stack_stack_57->GetZaxis()->SetLabelOffset(0.007);
   postfit_projy1_fail_stack_stack_57->GetZaxis()->SetLabelSize(0.05);
   postfit_projy1_fail_stack_stack_57->GetZaxis()->SetTitleSize(0.08);
   postfit_projy1_fail_stack_stack_57->GetZaxis()->SetTitleFont(42);
   postfit_projy1_fail_stack->SetHistogram(postfit_projy1_fail_stack_stack_57);
   
   Double_t xAxis311[2] = {50, 200}; 
   
   TH1D *Background_fail_postfit_projy1_stack_1 = new TH1D("Background_fail_postfit_projy1_stack_1","Background, fail, postfit, 0.24-1.0",1, xAxis311);
   Background_fail_postfit_projy1_stack_1->SetBinContent(1,6203.216);
   Background_fail_postfit_projy1_stack_1->SetBinError(1,75.05098);
   Background_fail_postfit_projy1_stack_1->SetMinimum(0);
   Background_fail_postfit_projy1_stack_1->SetEntries(6831.578);

   ci = TColor::GetColor("#ffff00");
   Background_fail_postfit_projy1_stack_1->SetFillColor(ci);

   ci = 1309;
   color = new TColor(ci, 1, 1, 1, " ", 0);
   Background_fail_postfit_projy1_stack_1->SetLineColor(ci);
   Background_fail_postfit_projy1_stack_1->SetLineStyle(0);
   Background_fail_postfit_projy1_stack_1->GetXaxis()->SetTitle("p_{T}");
   Background_fail_postfit_projy1_stack_1->GetXaxis()->SetLabelFont(42);
   Background_fail_postfit_projy1_stack_1->GetXaxis()->SetLabelOffset(0.007);
   Background_fail_postfit_projy1_stack_1->GetXaxis()->SetLabelSize(0.05);
   Background_fail_postfit_projy1_stack_1->GetXaxis()->SetTitleSize(0.08);
   Background_fail_postfit_projy1_stack_1->GetXaxis()->SetTitleOffset(1.25);
   Background_fail_postfit_projy1_stack_1->GetXaxis()->SetTitleFont(42);
   Background_fail_postfit_projy1_stack_1->GetYaxis()->SetTitle("Events / bin");
   Background_fail_postfit_projy1_stack_1->GetYaxis()->SetLabelFont(42);
   Background_fail_postfit_projy1_stack_1->GetYaxis()->SetLabelOffset(0.007);
   Background_fail_postfit_projy1_stack_1->GetYaxis()->SetLabelSize(0.05);
   Background_fail_postfit_projy1_stack_1->GetYaxis()->SetTitleSize(0.08);
   Background_fail_postfit_projy1_stack_1->GetYaxis()->SetTitleOffset(1.25);
   Background_fail_postfit_projy1_stack_1->GetYaxis()->SetTitleFont(42);
   Background_fail_postfit_projy1_stack_1->GetZaxis()->SetLabelFont(42);
   Background_fail_postfit_projy1_stack_1->GetZaxis()->SetLabelOffset(0.007);
   Background_fail_postfit_projy1_stack_1->GetZaxis()->SetLabelSize(0.05);
   Background_fail_postfit_projy1_stack_1->GetZaxis()->SetTitleSize(0.08);
   Background_fail_postfit_projy1_stack_1->GetZaxis()->SetTitleFont(42);
   postfit_projy1_fail_stack->Add(Background_fail_postfit_projy1_stack_1,"");
   postfit_projy1_fail_stack->Draw("hist same");
   
   postfit_projy1_fail_stack = new THStack();
   postfit_projy1_fail_stack->SetName("postfit_projy1_fail_stack");
   postfit_projy1_fail_stack->SetTitle("postfit_projy1_fail_stack");
   Double_t xAxis312[2] = {50, 200}; 
   
   TH1F *postfit_projy1_fail_stack_stack_57_stack_58 = new TH1F("postfit_projy1_fail_stack_stack_57_stack_58","postfit_projy1_fail_stack",1, xAxis312);
   postfit_projy1_fail_stack_stack_57_stack_58->SetMinimum(0);
   postfit_projy1_fail_stack_stack_57_stack_58->SetMaximum(6592.18);
   postfit_projy1_fail_stack_stack_57_stack_58->SetDirectory(0);
   postfit_projy1_fail_stack_stack_57_stack_58->SetStats(0);
   postfit_projy1_fail_stack_stack_57_stack_58->SetLineStyle(0);
   postfit_projy1_fail_stack_stack_57_stack_58->GetXaxis()->SetLabelFont(42);
   postfit_projy1_fail_stack_stack_57_stack_58->GetXaxis()->SetLabelOffset(0.007);
   postfit_projy1_fail_stack_stack_57_stack_58->GetXaxis()->SetLabelSize(0.05);
   postfit_projy1_fail_stack_stack_57_stack_58->GetXaxis()->SetTitleSize(0.08);
   postfit_projy1_fail_stack_stack_57_stack_58->GetXaxis()->SetTitleOffset(0.9);
   postfit_projy1_fail_stack_stack_57_stack_58->GetXaxis()->SetTitleFont(42);
   postfit_projy1_fail_stack_stack_57_stack_58->GetYaxis()->SetNdivisions(508);
   postfit_projy1_fail_stack_stack_57_stack_58->GetYaxis()->SetLabelFont(42);
   postfit_projy1_fail_stack_stack_57_stack_58->GetYaxis()->SetLabelOffset(0.007);
   postfit_projy1_fail_stack_stack_57_stack_58->GetYaxis()->SetLabelSize(0.05);
   postfit_projy1_fail_stack_stack_57_stack_58->GetYaxis()->SetTitleSize(0.08);
   postfit_projy1_fail_stack_stack_57_stack_58->GetYaxis()->SetTitleOffset(1.25);
   postfit_projy1_fail_stack_stack_57_stack_58->GetYaxis()->SetTitleFont(42);
   postfit_projy1_fail_stack_stack_57_stack_58->GetZaxis()->SetLabelFont(42);
   postfit_projy1_fail_stack_stack_57_stack_58->GetZaxis()->SetLabelOffset(0.007);
   postfit_projy1_fail_stack_stack_57_stack_58->GetZaxis()->SetLabelSize(0.05);
   postfit_projy1_fail_stack_stack_57_stack_58->GetZaxis()->SetTitleSize(0.08);
   postfit_projy1_fail_stack_stack_57_stack_58->GetZaxis()->SetTitleFont(42);
   postfit_projy1_fail_stack->SetHistogram(postfit_projy1_fail_stack_stack_57_stack_58);
   
   Double_t xAxis313[2] = {50, 200}; 
   
   TH1D *Background_fail_postfit_projy1_stack_1_stack_1 = new TH1D("Background_fail_postfit_projy1_stack_1_stack_1","Background, fail, postfit, 0.24-1.0",1, xAxis313);
   Background_fail_postfit_projy1_stack_1_stack_1->SetBinContent(1,6203.216);
   Background_fail_postfit_projy1_stack_1_stack_1->SetBinError(1,75.05098);
   Background_fail_postfit_projy1_stack_1_stack_1->SetMinimum(0);
   Background_fail_postfit_projy1_stack_1_stack_1->SetEntries(6831.578);

   ci = TColor::GetColor("#ffff00");
   Background_fail_postfit_projy1_stack_1_stack_1->SetFillColor(ci);

   ci = 1309;
   color = new TColor(ci, 1, 1, 1, " ", 0);
   Background_fail_postfit_projy1_stack_1_stack_1->SetLineColor(ci);
   Background_fail_postfit_projy1_stack_1_stack_1->SetLineStyle(0);
   Background_fail_postfit_projy1_stack_1_stack_1->GetXaxis()->SetTitle("p_{T}");
   Background_fail_postfit_projy1_stack_1_stack_1->GetXaxis()->SetLabelFont(42);
   Background_fail_postfit_projy1_stack_1_stack_1->GetXaxis()->SetLabelOffset(0.007);
   Background_fail_postfit_projy1_stack_1_stack_1->GetXaxis()->SetLabelSize(0.05);
   Background_fail_postfit_projy1_stack_1_stack_1->GetXaxis()->SetTitleSize(0.08);
   Background_fail_postfit_projy1_stack_1_stack_1->GetXaxis()->SetTitleOffset(1.25);
   Background_fail_postfit_projy1_stack_1_stack_1->GetXaxis()->SetTitleFont(42);
   Background_fail_postfit_projy1_stack_1_stack_1->GetYaxis()->SetTitle("Events / bin");
   Background_fail_postfit_projy1_stack_1_stack_1->GetYaxis()->SetLabelFont(42);
   Background_fail_postfit_projy1_stack_1_stack_1->GetYaxis()->SetLabelOffset(0.007);
   Background_fail_postfit_projy1_stack_1_stack_1->GetYaxis()->SetLabelSize(0.05);
   Background_fail_postfit_projy1_stack_1_stack_1->GetYaxis()->SetTitleSize(0.08);
   Background_fail_postfit_projy1_stack_1_stack_1->GetYaxis()->SetTitleOffset(1.25);
   Background_fail_postfit_projy1_stack_1_stack_1->GetYaxis()->SetTitleFont(42);
   Background_fail_postfit_projy1_stack_1_stack_1->GetZaxis()->SetLabelFont(42);
   Background_fail_postfit_projy1_stack_1_stack_1->GetZaxis()->SetLabelOffset(0.007);
   Background_fail_postfit_projy1_stack_1_stack_1->GetZaxis()->SetLabelSize(0.05);
   Background_fail_postfit_projy1_stack_1_stack_1->GetZaxis()->SetTitleSize(0.08);
   Background_fail_postfit_projy1_stack_1_stack_1->GetZaxis()->SetTitleFont(42);
   postfit_projy1_fail_stack->Add(Background_fail_postfit_projy1_stack_1_stack_1,"");
   postfit_projy1_fail_stack->Draw("hist same");
   Double_t xAxis314[2] = {50, 200}; 
   
   TH1D *Signal_ppStaumI557_fail_postfit_projy1__198 = new TH1D("Signal_ppStaumI557_fail_postfit_projy1__198","HSCP signal, fail, postfit, 0.24-1.0",1, xAxis314);
   Signal_ppStaumI557_fail_postfit_projy1__198->SetBinContent(1,0.00107264);
   Signal_ppStaumI557_fail_postfit_projy1__198->SetBinError(1,0.0006307652);
   Signal_ppStaumI557_fail_postfit_projy1__198->SetMinimum(0);
   Signal_ppStaumI557_fail_postfit_projy1__198->SetEntries(2.891831);
   Signal_ppStaumI557_fail_postfit_projy1__198->SetLineColor(2);
   Signal_ppStaumI557_fail_postfit_projy1__198->SetLineStyle(0);
   Signal_ppStaumI557_fail_postfit_projy1__198->GetXaxis()->SetTitle("p_{T}");
   Signal_ppStaumI557_fail_postfit_projy1__198->GetXaxis()->SetLabelFont(42);
   Signal_ppStaumI557_fail_postfit_projy1__198->GetXaxis()->SetLabelOffset(0.007);
   Signal_ppStaumI557_fail_postfit_projy1__198->GetXaxis()->SetLabelSize(0.05);
   Signal_ppStaumI557_fail_postfit_projy1__198->GetXaxis()->SetTitleSize(0.08);
   Signal_ppStaumI557_fail_postfit_projy1__198->GetXaxis()->SetTitleOffset(1.25);
   Signal_ppStaumI557_fail_postfit_projy1__198->GetXaxis()->SetTitleFont(42);
   Signal_ppStaumI557_fail_postfit_projy1__198->GetYaxis()->SetTitle("Events / bin");
   Signal_ppStaumI557_fail_postfit_projy1__198->GetYaxis()->SetLabelFont(42);
   Signal_ppStaumI557_fail_postfit_projy1__198->GetYaxis()->SetLabelOffset(0.007);
   Signal_ppStaumI557_fail_postfit_projy1__198->GetYaxis()->SetLabelSize(0.05);
   Signal_ppStaumI557_fail_postfit_projy1__198->GetYaxis()->SetTitleSize(0.08);
   Signal_ppStaumI557_fail_postfit_projy1__198->GetYaxis()->SetTitleOffset(1.25);
   Signal_ppStaumI557_fail_postfit_projy1__198->GetYaxis()->SetTitleFont(42);
   Signal_ppStaumI557_fail_postfit_projy1__198->GetZaxis()->SetLabelFont(42);
   Signal_ppStaumI557_fail_postfit_projy1__198->GetZaxis()->SetLabelOffset(0.007);
   Signal_ppStaumI557_fail_postfit_projy1__198->GetZaxis()->SetLabelSize(0.05);
   Signal_ppStaumI557_fail_postfit_projy1__198->GetZaxis()->SetTitleSize(0.08);
   Signal_ppStaumI557_fail_postfit_projy1__198->GetZaxis()->SetTitleFont(42);
   Signal_ppStaumI557_fail_postfit_projy1__198->Draw("hist same");
   Double_t xAxis315[2] = {50, 200}; 
   
   TH1D *TotalBkg_fail_postfit_projy1__199 = new TH1D("TotalBkg_fail_postfit_projy1__199","TotalBkg, fail, postfit, 0.24-1.0",1, xAxis315);
   TotalBkg_fail_postfit_projy1__199->SetBinContent(1,6203.216);
   TotalBkg_fail_postfit_projy1__199->SetBinError(1,73.45434);
   TotalBkg_fail_postfit_projy1__199->SetMinimum(0);
   TotalBkg_fail_postfit_projy1__199->SetEntries(7131.795);
   TotalBkg_fail_postfit_projy1__199->SetLineStyle(0);
   TotalBkg_fail_postfit_projy1__199->SetMarkerStyle(0);
   TotalBkg_fail_postfit_projy1__199->GetXaxis()->SetTitle("p_{T}");
   TotalBkg_fail_postfit_projy1__199->GetXaxis()->SetLabelFont(42);
   TotalBkg_fail_postfit_projy1__199->GetXaxis()->SetLabelOffset(0.007);
   TotalBkg_fail_postfit_projy1__199->GetXaxis()->SetLabelSize(0.05);
   TotalBkg_fail_postfit_projy1__199->GetXaxis()->SetTitleSize(0.08);
   TotalBkg_fail_postfit_projy1__199->GetXaxis()->SetTitleOffset(1.25);
   TotalBkg_fail_postfit_projy1__199->GetXaxis()->SetTitleFont(42);
   TotalBkg_fail_postfit_projy1__199->GetYaxis()->SetTitle("Events / bin");
   TotalBkg_fail_postfit_projy1__199->GetYaxis()->SetLabelFont(42);
   TotalBkg_fail_postfit_projy1__199->GetYaxis()->SetLabelOffset(0.007);
   TotalBkg_fail_postfit_projy1__199->GetYaxis()->SetLabelSize(0.05);
   TotalBkg_fail_postfit_projy1__199->GetYaxis()->SetTitleSize(0.08);
   TotalBkg_fail_postfit_projy1__199->GetYaxis()->SetTitleOffset(1.25);
   TotalBkg_fail_postfit_projy1__199->GetYaxis()->SetTitleFont(42);
   TotalBkg_fail_postfit_projy1__199->GetZaxis()->SetLabelFont(42);
   TotalBkg_fail_postfit_projy1__199->GetZaxis()->SetLabelOffset(0.007);
   TotalBkg_fail_postfit_projy1__199->GetZaxis()->SetLabelSize(0.05);
   TotalBkg_fail_postfit_projy1__199->GetZaxis()->SetTitleSize(0.08);
   TotalBkg_fail_postfit_projy1__199->GetZaxis()->SetTitleFont(42);
   TotalBkg_fail_postfit_projy1__199->Draw("hist same");
   Double_t xAxis316[2] = {50, 200}; 
   
   TH1D *TotalBkg_fail_postfit_projy1__200 = new TH1D("TotalBkg_fail_postfit_projy1__200","TotalBkg, fail, postfit, 0.24-1.0",1, xAxis316);
   TotalBkg_fail_postfit_projy1__200->SetBinContent(1,6203.216);
   TotalBkg_fail_postfit_projy1__200->SetBinError(1,73.45434);
   TotalBkg_fail_postfit_projy1__200->SetMinimum(0);
   TotalBkg_fail_postfit_projy1__200->SetEntries(7131.795);
   TotalBkg_fail_postfit_projy1__200->SetFillColor(1);
   TotalBkg_fail_postfit_projy1__200->SetFillStyle(3354);
   TotalBkg_fail_postfit_projy1__200->SetLineStyle(0);
   TotalBkg_fail_postfit_projy1__200->SetLineWidth(0);
   TotalBkg_fail_postfit_projy1__200->SetMarkerStyle(0);
   TotalBkg_fail_postfit_projy1__200->GetXaxis()->SetTitle("p_{T}");
   TotalBkg_fail_postfit_projy1__200->GetXaxis()->SetLabelFont(42);
   TotalBkg_fail_postfit_projy1__200->GetXaxis()->SetLabelOffset(0.007);
   TotalBkg_fail_postfit_projy1__200->GetXaxis()->SetLabelSize(0.05);
   TotalBkg_fail_postfit_projy1__200->GetXaxis()->SetTitleSize(0.08);
   TotalBkg_fail_postfit_projy1__200->GetXaxis()->SetTitleOffset(1.25);
   TotalBkg_fail_postfit_projy1__200->GetXaxis()->SetTitleFont(42);
   TotalBkg_fail_postfit_projy1__200->GetYaxis()->SetTitle("Events / bin");
   TotalBkg_fail_postfit_projy1__200->GetYaxis()->SetLabelFont(42);
   TotalBkg_fail_postfit_projy1__200->GetYaxis()->SetLabelOffset(0.007);
   TotalBkg_fail_postfit_projy1__200->GetYaxis()->SetLabelSize(0.05);
   TotalBkg_fail_postfit_projy1__200->GetYaxis()->SetTitleSize(0.08);
   TotalBkg_fail_postfit_projy1__200->GetYaxis()->SetTitleOffset(1.25);
   TotalBkg_fail_postfit_projy1__200->GetYaxis()->SetTitleFont(42);
   TotalBkg_fail_postfit_projy1__200->GetZaxis()->SetLabelFont(42);
   TotalBkg_fail_postfit_projy1__200->GetZaxis()->SetLabelOffset(0.007);
   TotalBkg_fail_postfit_projy1__200->GetZaxis()->SetLabelSize(0.05);
   TotalBkg_fail_postfit_projy1__200->GetZaxis()->SetTitleSize(0.08);
   TotalBkg_fail_postfit_projy1__200->GetZaxis()->SetTitleFont(42);
   TotalBkg_fail_postfit_projy1__200->Draw("e2 same");
   Double_t xAxis317[2] = {50, 200}; 
   
   TH1D *data_obs_fail_postfit_projy1__201 = new TH1D("data_obs_fail_postfit_projy1__201","",1, xAxis317);
   data_obs_fail_postfit_projy1__201->SetBinContent(1,6244);
   data_obs_fail_postfit_projy1__201->SetBinError(1,79.01899);
   data_obs_fail_postfit_projy1__201->SetMinimum(0);
   data_obs_fail_postfit_projy1__201->SetMaximum(8429.4);
   data_obs_fail_postfit_projy1__201->SetEntries(6244);

   ci = TColor::GetColor("#000000");
   data_obs_fail_postfit_projy1__201->SetLineColor(ci);
   data_obs_fail_postfit_projy1__201->SetLineStyle(0);

   ci = TColor::GetColor("#000000");
   data_obs_fail_postfit_projy1__201->SetMarkerColor(ci);
   data_obs_fail_postfit_projy1__201->SetMarkerStyle(8);
   data_obs_fail_postfit_projy1__201->GetXaxis()->SetTitle("p_{T}");
   data_obs_fail_postfit_projy1__201->GetXaxis()->SetLabelFont(42);
   data_obs_fail_postfit_projy1__201->GetXaxis()->SetLabelOffset(0.05);
   data_obs_fail_postfit_projy1__201->GetXaxis()->SetLabelSize(0.07);
   data_obs_fail_postfit_projy1__201->GetXaxis()->SetTitleSize(0.09);
   data_obs_fail_postfit_projy1__201->GetXaxis()->SetTitleOffset(1.15);
   data_obs_fail_postfit_projy1__201->GetXaxis()->SetTitleFont(42);
   data_obs_fail_postfit_projy1__201->GetYaxis()->SetTitle("Events / bin");
   data_obs_fail_postfit_projy1__201->GetYaxis()->SetNdivisions(508);
   data_obs_fail_postfit_projy1__201->GetYaxis()->SetLabelFont(42);
   data_obs_fail_postfit_projy1__201->GetYaxis()->SetLabelOffset(0.007);
   data_obs_fail_postfit_projy1__201->GetYaxis()->SetLabelSize(0.07);
   data_obs_fail_postfit_projy1__201->GetYaxis()->SetTitleSize(0.09);
   data_obs_fail_postfit_projy1__201->GetYaxis()->SetTitleOffset(0.8);
   data_obs_fail_postfit_projy1__201->GetYaxis()->SetTitleFont(42);
   data_obs_fail_postfit_projy1__201->GetZaxis()->SetLabelFont(42);
   data_obs_fail_postfit_projy1__201->GetZaxis()->SetLabelOffset(0.007);
   data_obs_fail_postfit_projy1__201->GetZaxis()->SetLabelSize(0.05);
   data_obs_fail_postfit_projy1__201->GetZaxis()->SetTitleSize(0.08);
   data_obs_fail_postfit_projy1__201->GetZaxis()->SetTitleFont(42);
   data_obs_fail_postfit_projy1__201->Draw("pe X0 same");
   
   TLegend *leg = new TLegend(0.65,0.64,0.9,0.88,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(1001);
   TLegendEntry *entry=leg->AddEntry("data_obs_fail_postfit_projy1","Data","pe X0");

   ci = TColor::GetColor("#000000");
   entry->SetLineColor(ci);
   entry->SetLineWidth(1);

   ci = TColor::GetColor("#000000");
   entry->SetMarkerColor(ci);
   entry->SetMarkerStyle(8);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("TotalBkg_fail_postfit_projy1","Total bkg unc.","F");
   entry->SetFillColor(1);
   entry->SetFillStyle(3354);
   entry->SetLineColor(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("Signal_ppStau-557_fail_postfit_projy1","HSCP signal","L");
   entry->SetLineColor(2);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("Background_fail_postfit_projy1_stack_1_stack_1","Background","f");

   ci = TColor::GetColor("#ffff00");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = 1309;
   color = new TColor(ci, 1, 1, 1, " ", 0);
   entry->SetLineColor(ci);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   leg->Draw();
   Double_t xAxis318[2] = {50, 200}; 
   
   TH1D *data_obs_fail_postfit_projy1_copy__202 = new TH1D("data_obs_fail_postfit_projy1_copy__202","",1, xAxis318);
   data_obs_fail_postfit_projy1_copy__202->SetBinContent(1,6244);
   data_obs_fail_postfit_projy1_copy__202->SetBinError(1,79.01899);
   data_obs_fail_postfit_projy1_copy__202->SetMinimum(0);
   data_obs_fail_postfit_projy1_copy__202->SetMaximum(8429.4);
   data_obs_fail_postfit_projy1_copy__202->SetEntries(6244);
   data_obs_fail_postfit_projy1_copy__202->SetDirectory(0);

   ci = TColor::GetColor("#000000");
   data_obs_fail_postfit_projy1_copy__202->SetLineColor(ci);
   data_obs_fail_postfit_projy1_copy__202->SetLineStyle(0);

   ci = TColor::GetColor("#000000");
   data_obs_fail_postfit_projy1_copy__202->SetMarkerColor(ci);
   data_obs_fail_postfit_projy1_copy__202->SetMarkerStyle(8);
   data_obs_fail_postfit_projy1_copy__202->GetXaxis()->SetTitle("p_{T}");
   data_obs_fail_postfit_projy1_copy__202->GetXaxis()->SetLabelFont(42);
   data_obs_fail_postfit_projy1_copy__202->GetXaxis()->SetLabelOffset(0.05);
   data_obs_fail_postfit_projy1_copy__202->GetXaxis()->SetLabelSize(0.07);
   data_obs_fail_postfit_projy1_copy__202->GetXaxis()->SetTitleSize(0.09);
   data_obs_fail_postfit_projy1_copy__202->GetXaxis()->SetTitleOffset(1.15);
   data_obs_fail_postfit_projy1_copy__202->GetXaxis()->SetTitleFont(42);
   data_obs_fail_postfit_projy1_copy__202->GetYaxis()->SetTitle("Events / bin");
   data_obs_fail_postfit_projy1_copy__202->GetYaxis()->SetNdivisions(508);
   data_obs_fail_postfit_projy1_copy__202->GetYaxis()->SetLabelFont(42);
   data_obs_fail_postfit_projy1_copy__202->GetYaxis()->SetLabelOffset(0.007);
   data_obs_fail_postfit_projy1_copy__202->GetYaxis()->SetLabelSize(0.07);
   data_obs_fail_postfit_projy1_copy__202->GetYaxis()->SetTitleSize(0.09);
   data_obs_fail_postfit_projy1_copy__202->GetYaxis()->SetTitleOffset(0.8);
   data_obs_fail_postfit_projy1_copy__202->GetYaxis()->SetTitleFont(42);
   data_obs_fail_postfit_projy1_copy__202->GetZaxis()->SetLabelFont(42);
   data_obs_fail_postfit_projy1_copy__202->GetZaxis()->SetLabelOffset(0.007);
   data_obs_fail_postfit_projy1_copy__202->GetZaxis()->SetLabelSize(0.05);
   data_obs_fail_postfit_projy1_copy__202->GetZaxis()->SetTitleSize(0.08);
   data_obs_fail_postfit_projy1_copy__202->GetZaxis()->SetTitleFont(42);
   data_obs_fail_postfit_projy1_copy__202->Draw("sameaxis");
   TLatex *   tex = new TLatex(0.21,0.83,"55 < p_{T} < 200 GeV, F^{Pixels}_{i} < 0.9");
tex->SetNDC();
   tex->SetTextAlign(12);
   tex->SetTextFont(42);
   tex->SetTextSize(0.06);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.17,0.92,"CMS");
tex->SetNDC();
   tex->SetTextFont(61);
   tex->SetTextSize(0.0675);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.25,0.92,"Preliminary");
tex->SetNDC();
   tex->SetTextFont(52);
   tex->SetTextSize(0.0485);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.95,0.92,"101 fb^{-1} (13 TeV)");
tex->SetNDC();
   tex->SetTextAlign(31);
   tex->SetTextFont(42);
   tex->SetTextSize(0.07);
   tex->SetLineWidth(2);
   tex->Draw();
   data_obs_fail_postfit_projy1_main->Modified();
   plots_fit_s/base_figs/postfit_projy1_fail->cd();
  
// ------------>Primitives in pad: data_obs_fail_postfit_projy1_sub
   TPad *data_obs_fail_postfit_projy1_sub = new TPad("data_obs_fail_postfit_projy1_sub", "data_obs_fail_postfit_projy1_sub",0,0,1,0.35);
   data_obs_fail_postfit_projy1_sub->Draw();
   data_obs_fail_postfit_projy1_sub->cd();
   data_obs_fail_postfit_projy1_sub->Range(17.30769,-6.023077,209.6154,2.9);
   data_obs_fail_postfit_projy1_sub->SetFillColor(0);
   data_obs_fail_postfit_projy1_sub->SetBorderMode(0);
   data_obs_fail_postfit_projy1_sub->SetBorderSize(2);
   data_obs_fail_postfit_projy1_sub->SetTickx(1);
   data_obs_fail_postfit_projy1_sub->SetTicky(1);
   data_obs_fail_postfit_projy1_sub->SetLeftMargin(0.17);
   data_obs_fail_postfit_projy1_sub->SetRightMargin(0.05);
   data_obs_fail_postfit_projy1_sub->SetTopMargin(0);
   data_obs_fail_postfit_projy1_sub->SetBottomMargin(0.35);
   data_obs_fail_postfit_projy1_sub->SetFrameFillStyle(0);
   data_obs_fail_postfit_projy1_sub->SetFrameBorderMode(0);
   data_obs_fail_postfit_projy1_sub->SetFrameFillStyle(0);
   data_obs_fail_postfit_projy1_sub->SetFrameBorderMode(0);
   Double_t xAxis319[2] = {50, 200}; 
   
   TH1D *data_obs_fail_postfit_projy1_pull__203 = new TH1D("data_obs_fail_postfit_projy1_pull__203","",1, xAxis319);
   data_obs_fail_postfit_projy1_pull__203->SetBinContent(1,0.3754935);
   data_obs_fail_postfit_projy1_pull__203->SetBinError(1,107.8867);
   data_obs_fail_postfit_projy1_pull__203->SetMinimum(-2.9);
   data_obs_fail_postfit_projy1_pull__203->SetMaximum(2.9);
   data_obs_fail_postfit_projy1_pull__203->SetEntries(1.142905);
   data_obs_fail_postfit_projy1_pull__203->SetStats(0);

   ci = TColor::GetColor("#0000ff");
   data_obs_fail_postfit_projy1_pull__203->SetFillColor(ci);

   ci = TColor::GetColor("#000000");
   data_obs_fail_postfit_projy1_pull__203->SetLineColor(ci);
   data_obs_fail_postfit_projy1_pull__203->SetLineStyle(0);

   ci = TColor::GetColor("#000000");
   data_obs_fail_postfit_projy1_pull__203->SetMarkerColor(ci);
   data_obs_fail_postfit_projy1_pull__203->SetMarkerStyle(8);
   data_obs_fail_postfit_projy1_pull__203->GetXaxis()->SetTitle("p_{T}");
   data_obs_fail_postfit_projy1_pull__203->GetXaxis()->SetLabelFont(42);
   data_obs_fail_postfit_projy1_pull__203->GetXaxis()->SetLabelOffset(0.05);
   data_obs_fail_postfit_projy1_pull__203->GetXaxis()->SetLabelSize(0.13);
   data_obs_fail_postfit_projy1_pull__203->GetXaxis()->SetTitleSize(0.15);
   data_obs_fail_postfit_projy1_pull__203->GetXaxis()->SetTitleOffset(1.15);
   data_obs_fail_postfit_projy1_pull__203->GetXaxis()->SetTitleFont(42);
   data_obs_fail_postfit_projy1_pull__203->GetYaxis()->SetTitle("(Data-Bkg)/#sigma");
   data_obs_fail_postfit_projy1_pull__203->GetYaxis()->SetNdivisions(306);
   data_obs_fail_postfit_projy1_pull__203->GetYaxis()->SetLabelFont(42);
   data_obs_fail_postfit_projy1_pull__203->GetYaxis()->SetLabelOffset(0.007);
   data_obs_fail_postfit_projy1_pull__203->GetYaxis()->SetLabelSize(0.13);
   data_obs_fail_postfit_projy1_pull__203->GetYaxis()->SetTitleSize(0.12);
   data_obs_fail_postfit_projy1_pull__203->GetYaxis()->SetTitleOffset(0.4);
   data_obs_fail_postfit_projy1_pull__203->GetYaxis()->SetTitleFont(42);
   data_obs_fail_postfit_projy1_pull__203->GetZaxis()->SetLabelFont(42);
   data_obs_fail_postfit_projy1_pull__203->GetZaxis()->SetLabelOffset(0.007);
   data_obs_fail_postfit_projy1_pull__203->GetZaxis()->SetLabelSize(0.05);
   data_obs_fail_postfit_projy1_pull__203->GetZaxis()->SetTitleSize(0.08);
   data_obs_fail_postfit_projy1_pull__203->GetZaxis()->SetTitleFont(42);
   data_obs_fail_postfit_projy1_pull__203->Draw("hist");
   data_obs_fail_postfit_projy1_sub->Modified();
   plots_fit_s/base_figs/postfit_projy1_fail->cd();
   plots_fit_s/base_figs/postfit_projy1_fail->Modified();
   plots_fit_s/base_figs/postfit_projy1_fail->cd();
   plots_fit_s/base_figs/postfit_projy1_fail->SetSelected(plots_fit_s/base_figs/postfit_projy1_fail);
}
