void postfit_projy1_pass()
{
//=========Macro generated from canvas: plots_fit_s/base_figs/postfit_projy1_pass/plots_fit_s/base_figs/postfit_projy1_pass
//=========  (Fri Jan 12 21:00:09 2024) by ROOT version 6.14/09
   TCanvas *plots_fit_s/base_figs/postfit_projy1_pass = new TCanvas("plots_fit_s/base_figs/postfit_projy1_pass", "plots_fit_s/base_figs/postfit_projy1_pass",0,0,800,700);
   gStyle->SetOptFit(1);
   gStyle->SetOptStat(0);
   plots_fit_s/base_figs/postfit_projy1_pass->SetHighLightColor(2);
   plots_fit_s/base_figs/postfit_projy1_pass->Range(0,0,1,1);
   plots_fit_s/base_figs/postfit_projy1_pass->SetFillColor(0);
   plots_fit_s/base_figs/postfit_projy1_pass->SetBorderMode(0);
   plots_fit_s/base_figs/postfit_projy1_pass->SetBorderSize(2);
   plots_fit_s/base_figs/postfit_projy1_pass->SetTickx(1);
   plots_fit_s/base_figs/postfit_projy1_pass->SetTicky(1);
   plots_fit_s/base_figs/postfit_projy1_pass->SetLeftMargin(0.16);
   plots_fit_s/base_figs/postfit_projy1_pass->SetRightMargin(0);
   plots_fit_s/base_figs/postfit_projy1_pass->SetTopMargin(0);
   plots_fit_s/base_figs/postfit_projy1_pass->SetBottomMargin(0);
   plots_fit_s/base_figs/postfit_projy1_pass->SetFrameFillStyle(0);
   plots_fit_s/base_figs/postfit_projy1_pass->SetFrameBorderMode(0);
  
// ------------>Primitives in pad: data_obs_pass_postfit_projy1_main
   TPad *data_obs_pass_postfit_projy1_main = new TPad("data_obs_pass_postfit_projy1_main", "data_obs_pass_postfit_projy1_main",0,0.35,1,1);
   data_obs_pass_postfit_projy1_main->Draw();
   data_obs_pass_postfit_projy1_main->cd();
   data_obs_pass_postfit_projy1_main->Range(17.30769,-62.16279,209.6154,1491.907);
   data_obs_pass_postfit_projy1_main->SetFillColor(0);
   data_obs_pass_postfit_projy1_main->SetBorderMode(0);
   data_obs_pass_postfit_projy1_main->SetBorderSize(2);
   data_obs_pass_postfit_projy1_main->SetTickx(1);
   data_obs_pass_postfit_projy1_main->SetTicky(1);
   data_obs_pass_postfit_projy1_main->SetLeftMargin(0.17);
   data_obs_pass_postfit_projy1_main->SetRightMargin(0.05);
   data_obs_pass_postfit_projy1_main->SetBottomMargin(0.04);
   data_obs_pass_postfit_projy1_main->SetFrameFillStyle(0);
   data_obs_pass_postfit_projy1_main->SetFrameBorderMode(0);
   data_obs_pass_postfit_projy1_main->SetFrameFillStyle(0);
   data_obs_pass_postfit_projy1_main->SetFrameBorderMode(0);
   Double_t xAxis441[2] = {50, 200}; 
   
   TH1D *data_obs_pass_postfit_projy1__281 = new TH1D("data_obs_pass_postfit_projy1__281","",1, xAxis441);
   data_obs_pass_postfit_projy1__281->SetBinContent(1,990);
   data_obs_pass_postfit_projy1__281->SetBinError(1,31.46427);
   data_obs_pass_postfit_projy1__281->SetMinimum(0);
   data_obs_pass_postfit_projy1__281->SetMaximum(1336.5);
   data_obs_pass_postfit_projy1__281->SetEntries(990);

   Int_t ci;      // for color index setting
   TColor *color; // for color definition with alpha
   ci = TColor::GetColor("#000000");
   data_obs_pass_postfit_projy1__281->SetLineColor(ci);
   data_obs_pass_postfit_projy1__281->SetLineStyle(0);

   ci = TColor::GetColor("#000000");
   data_obs_pass_postfit_projy1__281->SetMarkerColor(ci);
   data_obs_pass_postfit_projy1__281->SetMarkerStyle(8);
   data_obs_pass_postfit_projy1__281->GetXaxis()->SetTitle("p_{T}");
   data_obs_pass_postfit_projy1__281->GetXaxis()->SetLabelFont(42);
   data_obs_pass_postfit_projy1__281->GetXaxis()->SetLabelOffset(0.05);
   data_obs_pass_postfit_projy1__281->GetXaxis()->SetLabelSize(0.07);
   data_obs_pass_postfit_projy1__281->GetXaxis()->SetTitleSize(0.09);
   data_obs_pass_postfit_projy1__281->GetXaxis()->SetTitleOffset(1.15);
   data_obs_pass_postfit_projy1__281->GetXaxis()->SetTitleFont(42);
   data_obs_pass_postfit_projy1__281->GetYaxis()->SetTitle("Events / bin");
   data_obs_pass_postfit_projy1__281->GetYaxis()->SetNdivisions(508);
   data_obs_pass_postfit_projy1__281->GetYaxis()->SetLabelFont(42);
   data_obs_pass_postfit_projy1__281->GetYaxis()->SetLabelOffset(0.007);
   data_obs_pass_postfit_projy1__281->GetYaxis()->SetLabelSize(0.07);
   data_obs_pass_postfit_projy1__281->GetYaxis()->SetTitleSize(0.09);
   data_obs_pass_postfit_projy1__281->GetYaxis()->SetTitleOffset(0.8);
   data_obs_pass_postfit_projy1__281->GetYaxis()->SetTitleFont(42);
   data_obs_pass_postfit_projy1__281->GetZaxis()->SetLabelFont(42);
   data_obs_pass_postfit_projy1__281->GetZaxis()->SetLabelOffset(0.007);
   data_obs_pass_postfit_projy1__281->GetZaxis()->SetLabelSize(0.05);
   data_obs_pass_postfit_projy1__281->GetZaxis()->SetTitleSize(0.08);
   data_obs_pass_postfit_projy1__281->GetZaxis()->SetTitleFont(42);
   data_obs_pass_postfit_projy1__281->Draw("pe X0");
   
   THStack *postfit_projy1_pass_stack = new THStack();
   postfit_projy1_pass_stack->SetName("postfit_projy1_pass_stack");
   postfit_projy1_pass_stack->SetTitle("postfit_projy1_pass_stack");
   Double_t xAxis442[2] = {50, 200}; 
   
   TH1F *postfit_projy1_pass_stack_stack_81 = new TH1F("postfit_projy1_pass_stack_stack_81","postfit_projy1_pass_stack",1, xAxis442);
   postfit_projy1_pass_stack_stack_81->SetMinimum(0);
   postfit_projy1_pass_stack_stack_81->SetMaximum(1088.719);
   postfit_projy1_pass_stack_stack_81->SetDirectory(0);
   postfit_projy1_pass_stack_stack_81->SetStats(0);
   postfit_projy1_pass_stack_stack_81->SetLineStyle(0);
   postfit_projy1_pass_stack_stack_81->GetXaxis()->SetLabelFont(42);
   postfit_projy1_pass_stack_stack_81->GetXaxis()->SetLabelOffset(0.007);
   postfit_projy1_pass_stack_stack_81->GetXaxis()->SetLabelSize(0.05);
   postfit_projy1_pass_stack_stack_81->GetXaxis()->SetTitleSize(0.08);
   postfit_projy1_pass_stack_stack_81->GetXaxis()->SetTitleOffset(0.9);
   postfit_projy1_pass_stack_stack_81->GetXaxis()->SetTitleFont(42);
   postfit_projy1_pass_stack_stack_81->GetYaxis()->SetNdivisions(508);
   postfit_projy1_pass_stack_stack_81->GetYaxis()->SetLabelFont(42);
   postfit_projy1_pass_stack_stack_81->GetYaxis()->SetLabelOffset(0.007);
   postfit_projy1_pass_stack_stack_81->GetYaxis()->SetLabelSize(0.05);
   postfit_projy1_pass_stack_stack_81->GetYaxis()->SetTitleSize(0.08);
   postfit_projy1_pass_stack_stack_81->GetYaxis()->SetTitleOffset(1.25);
   postfit_projy1_pass_stack_stack_81->GetYaxis()->SetTitleFont(42);
   postfit_projy1_pass_stack_stack_81->GetZaxis()->SetLabelFont(42);
   postfit_projy1_pass_stack_stack_81->GetZaxis()->SetLabelOffset(0.007);
   postfit_projy1_pass_stack_stack_81->GetZaxis()->SetLabelSize(0.05);
   postfit_projy1_pass_stack_stack_81->GetZaxis()->SetTitleSize(0.08);
   postfit_projy1_pass_stack_stack_81->GetZaxis()->SetTitleFont(42);
   postfit_projy1_pass_stack->SetHistogram(postfit_projy1_pass_stack_stack_81);
   
   Double_t xAxis443[2] = {50, 200}; 
   
   TH1D *Background_0x0_pass_postfit_projy1_stack_1 = new TH1D("Background_0x0_pass_postfit_projy1_stack_1","Background, pass, postfit, 0.24-1.0",1, xAxis443);
   Background_0x0_pass_postfit_projy1_stack_1->SetBinContent(1,1025.185);
   Background_0x0_pass_postfit_projy1_stack_1->SetBinError(1,11.69012);
   Background_0x0_pass_postfit_projy1_stack_1->SetMinimum(0);
   Background_0x0_pass_postfit_projy1_stack_1->SetEntries(7690.714);

   ci = TColor::GetColor("#ffff00");
   Background_0x0_pass_postfit_projy1_stack_1->SetFillColor(ci);

   ci = 1321;
   color = new TColor(ci, 1, 1, 1, " ", 0);
   Background_0x0_pass_postfit_projy1_stack_1->SetLineColor(ci);
   Background_0x0_pass_postfit_projy1_stack_1->SetLineStyle(0);
   Background_0x0_pass_postfit_projy1_stack_1->GetXaxis()->SetTitle("p_{T}");
   Background_0x0_pass_postfit_projy1_stack_1->GetXaxis()->SetLabelFont(42);
   Background_0x0_pass_postfit_projy1_stack_1->GetXaxis()->SetLabelOffset(0.007);
   Background_0x0_pass_postfit_projy1_stack_1->GetXaxis()->SetLabelSize(0.05);
   Background_0x0_pass_postfit_projy1_stack_1->GetXaxis()->SetTitleSize(0.08);
   Background_0x0_pass_postfit_projy1_stack_1->GetXaxis()->SetTitleOffset(1.25);
   Background_0x0_pass_postfit_projy1_stack_1->GetXaxis()->SetTitleFont(42);
   Background_0x0_pass_postfit_projy1_stack_1->GetYaxis()->SetTitle("Events / bin");
   Background_0x0_pass_postfit_projy1_stack_1->GetYaxis()->SetLabelFont(42);
   Background_0x0_pass_postfit_projy1_stack_1->GetYaxis()->SetLabelOffset(0.007);
   Background_0x0_pass_postfit_projy1_stack_1->GetYaxis()->SetLabelSize(0.05);
   Background_0x0_pass_postfit_projy1_stack_1->GetYaxis()->SetTitleSize(0.08);
   Background_0x0_pass_postfit_projy1_stack_1->GetYaxis()->SetTitleOffset(1.25);
   Background_0x0_pass_postfit_projy1_stack_1->GetYaxis()->SetTitleFont(42);
   Background_0x0_pass_postfit_projy1_stack_1->GetZaxis()->SetLabelFont(42);
   Background_0x0_pass_postfit_projy1_stack_1->GetZaxis()->SetLabelOffset(0.007);
   Background_0x0_pass_postfit_projy1_stack_1->GetZaxis()->SetLabelSize(0.05);
   Background_0x0_pass_postfit_projy1_stack_1->GetZaxis()->SetTitleSize(0.08);
   Background_0x0_pass_postfit_projy1_stack_1->GetZaxis()->SetTitleFont(42);
   postfit_projy1_pass_stack->Add(Background_0x0_pass_postfit_projy1_stack_1,"");
   postfit_projy1_pass_stack->Draw("hist same");
   
   postfit_projy1_pass_stack = new THStack();
   postfit_projy1_pass_stack->SetName("postfit_projy1_pass_stack");
   postfit_projy1_pass_stack->SetTitle("postfit_projy1_pass_stack");
   Double_t xAxis444[2] = {50, 200}; 
   
   TH1F *postfit_projy1_pass_stack_stack_81_stack_82 = new TH1F("postfit_projy1_pass_stack_stack_81_stack_82","postfit_projy1_pass_stack",1, xAxis444);
   postfit_projy1_pass_stack_stack_81_stack_82->SetMinimum(0);
   postfit_projy1_pass_stack_stack_81_stack_82->SetMaximum(1088.719);
   postfit_projy1_pass_stack_stack_81_stack_82->SetDirectory(0);
   postfit_projy1_pass_stack_stack_81_stack_82->SetStats(0);
   postfit_projy1_pass_stack_stack_81_stack_82->SetLineStyle(0);
   postfit_projy1_pass_stack_stack_81_stack_82->GetXaxis()->SetLabelFont(42);
   postfit_projy1_pass_stack_stack_81_stack_82->GetXaxis()->SetLabelOffset(0.007);
   postfit_projy1_pass_stack_stack_81_stack_82->GetXaxis()->SetLabelSize(0.05);
   postfit_projy1_pass_stack_stack_81_stack_82->GetXaxis()->SetTitleSize(0.08);
   postfit_projy1_pass_stack_stack_81_stack_82->GetXaxis()->SetTitleOffset(0.9);
   postfit_projy1_pass_stack_stack_81_stack_82->GetXaxis()->SetTitleFont(42);
   postfit_projy1_pass_stack_stack_81_stack_82->GetYaxis()->SetNdivisions(508);
   postfit_projy1_pass_stack_stack_81_stack_82->GetYaxis()->SetLabelFont(42);
   postfit_projy1_pass_stack_stack_81_stack_82->GetYaxis()->SetLabelOffset(0.007);
   postfit_projy1_pass_stack_stack_81_stack_82->GetYaxis()->SetLabelSize(0.05);
   postfit_projy1_pass_stack_stack_81_stack_82->GetYaxis()->SetTitleSize(0.08);
   postfit_projy1_pass_stack_stack_81_stack_82->GetYaxis()->SetTitleOffset(1.25);
   postfit_projy1_pass_stack_stack_81_stack_82->GetYaxis()->SetTitleFont(42);
   postfit_projy1_pass_stack_stack_81_stack_82->GetZaxis()->SetLabelFont(42);
   postfit_projy1_pass_stack_stack_81_stack_82->GetZaxis()->SetLabelOffset(0.007);
   postfit_projy1_pass_stack_stack_81_stack_82->GetZaxis()->SetLabelSize(0.05);
   postfit_projy1_pass_stack_stack_81_stack_82->GetZaxis()->SetTitleSize(0.08);
   postfit_projy1_pass_stack_stack_81_stack_82->GetZaxis()->SetTitleFont(42);
   postfit_projy1_pass_stack->SetHistogram(postfit_projy1_pass_stack_stack_81_stack_82);
   
   Double_t xAxis445[2] = {50, 200}; 
   
   TH1D *Background_0x0_pass_postfit_projy1_stack_1_stack_1 = new TH1D("Background_0x0_pass_postfit_projy1_stack_1_stack_1","Background, pass, postfit, 0.24-1.0",1, xAxis445);
   Background_0x0_pass_postfit_projy1_stack_1_stack_1->SetBinContent(1,1025.185);
   Background_0x0_pass_postfit_projy1_stack_1_stack_1->SetBinError(1,11.69012);
   Background_0x0_pass_postfit_projy1_stack_1_stack_1->SetMinimum(0);
   Background_0x0_pass_postfit_projy1_stack_1_stack_1->SetEntries(7690.714);

   ci = TColor::GetColor("#ffff00");
   Background_0x0_pass_postfit_projy1_stack_1_stack_1->SetFillColor(ci);

   ci = 1321;
   color = new TColor(ci, 1, 1, 1, " ", 0);
   Background_0x0_pass_postfit_projy1_stack_1_stack_1->SetLineColor(ci);
   Background_0x0_pass_postfit_projy1_stack_1_stack_1->SetLineStyle(0);
   Background_0x0_pass_postfit_projy1_stack_1_stack_1->GetXaxis()->SetTitle("p_{T}");
   Background_0x0_pass_postfit_projy1_stack_1_stack_1->GetXaxis()->SetLabelFont(42);
   Background_0x0_pass_postfit_projy1_stack_1_stack_1->GetXaxis()->SetLabelOffset(0.007);
   Background_0x0_pass_postfit_projy1_stack_1_stack_1->GetXaxis()->SetLabelSize(0.05);
   Background_0x0_pass_postfit_projy1_stack_1_stack_1->GetXaxis()->SetTitleSize(0.08);
   Background_0x0_pass_postfit_projy1_stack_1_stack_1->GetXaxis()->SetTitleOffset(1.25);
   Background_0x0_pass_postfit_projy1_stack_1_stack_1->GetXaxis()->SetTitleFont(42);
   Background_0x0_pass_postfit_projy1_stack_1_stack_1->GetYaxis()->SetTitle("Events / bin");
   Background_0x0_pass_postfit_projy1_stack_1_stack_1->GetYaxis()->SetLabelFont(42);
   Background_0x0_pass_postfit_projy1_stack_1_stack_1->GetYaxis()->SetLabelOffset(0.007);
   Background_0x0_pass_postfit_projy1_stack_1_stack_1->GetYaxis()->SetLabelSize(0.05);
   Background_0x0_pass_postfit_projy1_stack_1_stack_1->GetYaxis()->SetTitleSize(0.08);
   Background_0x0_pass_postfit_projy1_stack_1_stack_1->GetYaxis()->SetTitleOffset(1.25);
   Background_0x0_pass_postfit_projy1_stack_1_stack_1->GetYaxis()->SetTitleFont(42);
   Background_0x0_pass_postfit_projy1_stack_1_stack_1->GetZaxis()->SetLabelFont(42);
   Background_0x0_pass_postfit_projy1_stack_1_stack_1->GetZaxis()->SetLabelOffset(0.007);
   Background_0x0_pass_postfit_projy1_stack_1_stack_1->GetZaxis()->SetLabelSize(0.05);
   Background_0x0_pass_postfit_projy1_stack_1_stack_1->GetZaxis()->SetTitleSize(0.08);
   Background_0x0_pass_postfit_projy1_stack_1_stack_1->GetZaxis()->SetTitleFont(42);
   postfit_projy1_pass_stack->Add(Background_0x0_pass_postfit_projy1_stack_1_stack_1,"");
   postfit_projy1_pass_stack->Draw("hist same");
   Double_t xAxis446[2] = {50, 200}; 
   
   TH1D *Signal_ppStaumI557_pass_postfit_projy1__282 = new TH1D("Signal_ppStaumI557_pass_postfit_projy1__282","HSCP signal, pass, postfit, 0.24-1.0",1, xAxis446);
   Signal_ppStaumI557_pass_postfit_projy1__282->SetBinContent(1,5.466118);
   Signal_ppStaumI557_pass_postfit_projy1__282->SetBinError(1,3.79449);
   Signal_ppStaumI557_pass_postfit_projy1__282->SetMinimum(0);
   Signal_ppStaumI557_pass_postfit_projy1__282->SetEntries(2.075158);
   Signal_ppStaumI557_pass_postfit_projy1__282->SetLineColor(2);
   Signal_ppStaumI557_pass_postfit_projy1__282->SetLineStyle(0);
   Signal_ppStaumI557_pass_postfit_projy1__282->GetXaxis()->SetTitle("p_{T}");
   Signal_ppStaumI557_pass_postfit_projy1__282->GetXaxis()->SetLabelFont(42);
   Signal_ppStaumI557_pass_postfit_projy1__282->GetXaxis()->SetLabelOffset(0.007);
   Signal_ppStaumI557_pass_postfit_projy1__282->GetXaxis()->SetLabelSize(0.05);
   Signal_ppStaumI557_pass_postfit_projy1__282->GetXaxis()->SetTitleSize(0.08);
   Signal_ppStaumI557_pass_postfit_projy1__282->GetXaxis()->SetTitleOffset(1.25);
   Signal_ppStaumI557_pass_postfit_projy1__282->GetXaxis()->SetTitleFont(42);
   Signal_ppStaumI557_pass_postfit_projy1__282->GetYaxis()->SetTitle("Events / bin");
   Signal_ppStaumI557_pass_postfit_projy1__282->GetYaxis()->SetLabelFont(42);
   Signal_ppStaumI557_pass_postfit_projy1__282->GetYaxis()->SetLabelOffset(0.007);
   Signal_ppStaumI557_pass_postfit_projy1__282->GetYaxis()->SetLabelSize(0.05);
   Signal_ppStaumI557_pass_postfit_projy1__282->GetYaxis()->SetTitleSize(0.08);
   Signal_ppStaumI557_pass_postfit_projy1__282->GetYaxis()->SetTitleOffset(1.25);
   Signal_ppStaumI557_pass_postfit_projy1__282->GetYaxis()->SetTitleFont(42);
   Signal_ppStaumI557_pass_postfit_projy1__282->GetZaxis()->SetLabelFont(42);
   Signal_ppStaumI557_pass_postfit_projy1__282->GetZaxis()->SetLabelOffset(0.007);
   Signal_ppStaumI557_pass_postfit_projy1__282->GetZaxis()->SetLabelSize(0.05);
   Signal_ppStaumI557_pass_postfit_projy1__282->GetZaxis()->SetTitleSize(0.08);
   Signal_ppStaumI557_pass_postfit_projy1__282->GetZaxis()->SetTitleFont(42);
   Signal_ppStaumI557_pass_postfit_projy1__282->Draw("hist same");
   Double_t xAxis447[2] = {50, 200}; 
   
   TH1D *TotalBkg_pass_postfit_projy1__283 = new TH1D("TotalBkg_pass_postfit_projy1__283","TotalBkg, pass, postfit, 0.24-1.0",1, xAxis447);
   TotalBkg_pass_postfit_projy1__283->SetBinContent(1,1025.185);
   TotalBkg_pass_postfit_projy1__283->SetBinError(1,12.53427);
   TotalBkg_pass_postfit_projy1__283->SetMinimum(0);
   TotalBkg_pass_postfit_projy1__283->SetEntries(6689.697);
   TotalBkg_pass_postfit_projy1__283->SetLineStyle(0);
   TotalBkg_pass_postfit_projy1__283->SetMarkerStyle(0);
   TotalBkg_pass_postfit_projy1__283->GetXaxis()->SetTitle("p_{T}");
   TotalBkg_pass_postfit_projy1__283->GetXaxis()->SetLabelFont(42);
   TotalBkg_pass_postfit_projy1__283->GetXaxis()->SetLabelOffset(0.007);
   TotalBkg_pass_postfit_projy1__283->GetXaxis()->SetLabelSize(0.05);
   TotalBkg_pass_postfit_projy1__283->GetXaxis()->SetTitleSize(0.08);
   TotalBkg_pass_postfit_projy1__283->GetXaxis()->SetTitleOffset(1.25);
   TotalBkg_pass_postfit_projy1__283->GetXaxis()->SetTitleFont(42);
   TotalBkg_pass_postfit_projy1__283->GetYaxis()->SetTitle("Events / bin");
   TotalBkg_pass_postfit_projy1__283->GetYaxis()->SetLabelFont(42);
   TotalBkg_pass_postfit_projy1__283->GetYaxis()->SetLabelOffset(0.007);
   TotalBkg_pass_postfit_projy1__283->GetYaxis()->SetLabelSize(0.05);
   TotalBkg_pass_postfit_projy1__283->GetYaxis()->SetTitleSize(0.08);
   TotalBkg_pass_postfit_projy1__283->GetYaxis()->SetTitleOffset(1.25);
   TotalBkg_pass_postfit_projy1__283->GetYaxis()->SetTitleFont(42);
   TotalBkg_pass_postfit_projy1__283->GetZaxis()->SetLabelFont(42);
   TotalBkg_pass_postfit_projy1__283->GetZaxis()->SetLabelOffset(0.007);
   TotalBkg_pass_postfit_projy1__283->GetZaxis()->SetLabelSize(0.05);
   TotalBkg_pass_postfit_projy1__283->GetZaxis()->SetTitleSize(0.08);
   TotalBkg_pass_postfit_projy1__283->GetZaxis()->SetTitleFont(42);
   TotalBkg_pass_postfit_projy1__283->Draw("hist same");
   Double_t xAxis448[2] = {50, 200}; 
   
   TH1D *TotalBkg_pass_postfit_projy1__284 = new TH1D("TotalBkg_pass_postfit_projy1__284","TotalBkg, pass, postfit, 0.24-1.0",1, xAxis448);
   TotalBkg_pass_postfit_projy1__284->SetBinContent(1,1025.185);
   TotalBkg_pass_postfit_projy1__284->SetBinError(1,12.53427);
   TotalBkg_pass_postfit_projy1__284->SetMinimum(0);
   TotalBkg_pass_postfit_projy1__284->SetEntries(6689.697);
   TotalBkg_pass_postfit_projy1__284->SetFillColor(1);
   TotalBkg_pass_postfit_projy1__284->SetFillStyle(3354);
   TotalBkg_pass_postfit_projy1__284->SetLineStyle(0);
   TotalBkg_pass_postfit_projy1__284->SetLineWidth(0);
   TotalBkg_pass_postfit_projy1__284->SetMarkerStyle(0);
   TotalBkg_pass_postfit_projy1__284->GetXaxis()->SetTitle("p_{T}");
   TotalBkg_pass_postfit_projy1__284->GetXaxis()->SetLabelFont(42);
   TotalBkg_pass_postfit_projy1__284->GetXaxis()->SetLabelOffset(0.007);
   TotalBkg_pass_postfit_projy1__284->GetXaxis()->SetLabelSize(0.05);
   TotalBkg_pass_postfit_projy1__284->GetXaxis()->SetTitleSize(0.08);
   TotalBkg_pass_postfit_projy1__284->GetXaxis()->SetTitleOffset(1.25);
   TotalBkg_pass_postfit_projy1__284->GetXaxis()->SetTitleFont(42);
   TotalBkg_pass_postfit_projy1__284->GetYaxis()->SetTitle("Events / bin");
   TotalBkg_pass_postfit_projy1__284->GetYaxis()->SetLabelFont(42);
   TotalBkg_pass_postfit_projy1__284->GetYaxis()->SetLabelOffset(0.007);
   TotalBkg_pass_postfit_projy1__284->GetYaxis()->SetLabelSize(0.05);
   TotalBkg_pass_postfit_projy1__284->GetYaxis()->SetTitleSize(0.08);
   TotalBkg_pass_postfit_projy1__284->GetYaxis()->SetTitleOffset(1.25);
   TotalBkg_pass_postfit_projy1__284->GetYaxis()->SetTitleFont(42);
   TotalBkg_pass_postfit_projy1__284->GetZaxis()->SetLabelFont(42);
   TotalBkg_pass_postfit_projy1__284->GetZaxis()->SetLabelOffset(0.007);
   TotalBkg_pass_postfit_projy1__284->GetZaxis()->SetLabelSize(0.05);
   TotalBkg_pass_postfit_projy1__284->GetZaxis()->SetTitleSize(0.08);
   TotalBkg_pass_postfit_projy1__284->GetZaxis()->SetTitleFont(42);
   TotalBkg_pass_postfit_projy1__284->Draw("e2 same");
   Double_t xAxis449[2] = {50, 200}; 
   
   TH1D *data_obs_pass_postfit_projy1__285 = new TH1D("data_obs_pass_postfit_projy1__285","",1, xAxis449);
   data_obs_pass_postfit_projy1__285->SetBinContent(1,990);
   data_obs_pass_postfit_projy1__285->SetBinError(1,31.46427);
   data_obs_pass_postfit_projy1__285->SetMinimum(0);
   data_obs_pass_postfit_projy1__285->SetMaximum(1336.5);
   data_obs_pass_postfit_projy1__285->SetEntries(990);

   ci = TColor::GetColor("#000000");
   data_obs_pass_postfit_projy1__285->SetLineColor(ci);
   data_obs_pass_postfit_projy1__285->SetLineStyle(0);

   ci = TColor::GetColor("#000000");
   data_obs_pass_postfit_projy1__285->SetMarkerColor(ci);
   data_obs_pass_postfit_projy1__285->SetMarkerStyle(8);
   data_obs_pass_postfit_projy1__285->GetXaxis()->SetTitle("p_{T}");
   data_obs_pass_postfit_projy1__285->GetXaxis()->SetLabelFont(42);
   data_obs_pass_postfit_projy1__285->GetXaxis()->SetLabelOffset(0.05);
   data_obs_pass_postfit_projy1__285->GetXaxis()->SetLabelSize(0.07);
   data_obs_pass_postfit_projy1__285->GetXaxis()->SetTitleSize(0.09);
   data_obs_pass_postfit_projy1__285->GetXaxis()->SetTitleOffset(1.15);
   data_obs_pass_postfit_projy1__285->GetXaxis()->SetTitleFont(42);
   data_obs_pass_postfit_projy1__285->GetYaxis()->SetTitle("Events / bin");
   data_obs_pass_postfit_projy1__285->GetYaxis()->SetNdivisions(508);
   data_obs_pass_postfit_projy1__285->GetYaxis()->SetLabelFont(42);
   data_obs_pass_postfit_projy1__285->GetYaxis()->SetLabelOffset(0.007);
   data_obs_pass_postfit_projy1__285->GetYaxis()->SetLabelSize(0.07);
   data_obs_pass_postfit_projy1__285->GetYaxis()->SetTitleSize(0.09);
   data_obs_pass_postfit_projy1__285->GetYaxis()->SetTitleOffset(0.8);
   data_obs_pass_postfit_projy1__285->GetYaxis()->SetTitleFont(42);
   data_obs_pass_postfit_projy1__285->GetZaxis()->SetLabelFont(42);
   data_obs_pass_postfit_projy1__285->GetZaxis()->SetLabelOffset(0.007);
   data_obs_pass_postfit_projy1__285->GetZaxis()->SetLabelSize(0.05);
   data_obs_pass_postfit_projy1__285->GetZaxis()->SetTitleSize(0.08);
   data_obs_pass_postfit_projy1__285->GetZaxis()->SetTitleFont(42);
   data_obs_pass_postfit_projy1__285->Draw("pe X0 same");
   
   TLegend *leg = new TLegend(0.65,0.64,0.9,0.88,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(1001);
   TLegendEntry *entry=leg->AddEntry("data_obs_pass_postfit_projy1","Data","pe X0");

   ci = TColor::GetColor("#000000");
   entry->SetLineColor(ci);
   entry->SetLineWidth(1);

   ci = TColor::GetColor("#000000");
   entry->SetMarkerColor(ci);
   entry->SetMarkerStyle(8);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("TotalBkg_pass_postfit_projy1","Total bkg unc.","F");
   entry->SetFillColor(1);
   entry->SetFillStyle(3354);
   entry->SetLineColor(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("Signal_ppStau-557_pass_postfit_projy1","HSCP signal","L");
   entry->SetLineColor(2);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("Background_0x0_pass_postfit_projy1_stack_1_stack_1","Background","f");

   ci = TColor::GetColor("#ffff00");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = 1321;
   color = new TColor(ci, 1, 1, 1, " ", 0);
   entry->SetLineColor(ci);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   leg->Draw();
   Double_t xAxis450[2] = {50, 200}; 
   
   TH1D *data_obs_pass_postfit_projy1_copy__286 = new TH1D("data_obs_pass_postfit_projy1_copy__286","",1, xAxis450);
   data_obs_pass_postfit_projy1_copy__286->SetBinContent(1,990);
   data_obs_pass_postfit_projy1_copy__286->SetBinError(1,31.46427);
   data_obs_pass_postfit_projy1_copy__286->SetMinimum(0);
   data_obs_pass_postfit_projy1_copy__286->SetMaximum(1336.5);
   data_obs_pass_postfit_projy1_copy__286->SetEntries(990);
   data_obs_pass_postfit_projy1_copy__286->SetDirectory(0);

   ci = TColor::GetColor("#000000");
   data_obs_pass_postfit_projy1_copy__286->SetLineColor(ci);
   data_obs_pass_postfit_projy1_copy__286->SetLineStyle(0);

   ci = TColor::GetColor("#000000");
   data_obs_pass_postfit_projy1_copy__286->SetMarkerColor(ci);
   data_obs_pass_postfit_projy1_copy__286->SetMarkerStyle(8);
   data_obs_pass_postfit_projy1_copy__286->GetXaxis()->SetTitle("p_{T}");
   data_obs_pass_postfit_projy1_copy__286->GetXaxis()->SetLabelFont(42);
   data_obs_pass_postfit_projy1_copy__286->GetXaxis()->SetLabelOffset(0.05);
   data_obs_pass_postfit_projy1_copy__286->GetXaxis()->SetLabelSize(0.07);
   data_obs_pass_postfit_projy1_copy__286->GetXaxis()->SetTitleSize(0.09);
   data_obs_pass_postfit_projy1_copy__286->GetXaxis()->SetTitleOffset(1.15);
   data_obs_pass_postfit_projy1_copy__286->GetXaxis()->SetTitleFont(42);
   data_obs_pass_postfit_projy1_copy__286->GetYaxis()->SetTitle("Events / bin");
   data_obs_pass_postfit_projy1_copy__286->GetYaxis()->SetNdivisions(508);
   data_obs_pass_postfit_projy1_copy__286->GetYaxis()->SetLabelFont(42);
   data_obs_pass_postfit_projy1_copy__286->GetYaxis()->SetLabelOffset(0.007);
   data_obs_pass_postfit_projy1_copy__286->GetYaxis()->SetLabelSize(0.07);
   data_obs_pass_postfit_projy1_copy__286->GetYaxis()->SetTitleSize(0.09);
   data_obs_pass_postfit_projy1_copy__286->GetYaxis()->SetTitleOffset(0.8);
   data_obs_pass_postfit_projy1_copy__286->GetYaxis()->SetTitleFont(42);
   data_obs_pass_postfit_projy1_copy__286->GetZaxis()->SetLabelFont(42);
   data_obs_pass_postfit_projy1_copy__286->GetZaxis()->SetLabelOffset(0.007);
   data_obs_pass_postfit_projy1_copy__286->GetZaxis()->SetLabelSize(0.05);
   data_obs_pass_postfit_projy1_copy__286->GetZaxis()->SetTitleSize(0.08);
   data_obs_pass_postfit_projy1_copy__286->GetZaxis()->SetTitleFont(42);
   data_obs_pass_postfit_projy1_copy__286->Draw("sameaxis");
   TLatex *   tex = new TLatex(0.21,0.83,"55 < p_{T} < 200 GeV, F^{Pixels}_{i} > 0.9");
tex->SetNDC();
   tex->SetTextAlign(12);
   tex->SetTextFont(42);
   tex->SetTextSize(0.06);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.17,0.92,"CMS");
tex->SetNDC();
   tex->SetTextFont(61);
   tex->SetTextSize(0.0675);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.25,0.92,"Preliminary");
tex->SetNDC();
   tex->SetTextFont(52);
   tex->SetTextSize(0.0485);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.95,0.92,"101 fb^{-1} (13 TeV)");
tex->SetNDC();
   tex->SetTextAlign(31);
   tex->SetTextFont(42);
   tex->SetTextSize(0.07);
   tex->SetLineWidth(2);
   tex->Draw();
   data_obs_pass_postfit_projy1_main->Modified();
   plots_fit_s/base_figs/postfit_projy1_pass->cd();
  
// ------------>Primitives in pad: data_obs_pass_postfit_projy1_sub
   TPad *data_obs_pass_postfit_projy1_sub = new TPad("data_obs_pass_postfit_projy1_sub", "data_obs_pass_postfit_projy1_sub",0,0,1,0.35);
   data_obs_pass_postfit_projy1_sub->Draw();
   data_obs_pass_postfit_projy1_sub->cd();
   data_obs_pass_postfit_projy1_sub->Range(17.30769,-6.023077,209.6154,2.9);
   data_obs_pass_postfit_projy1_sub->SetFillColor(0);
   data_obs_pass_postfit_projy1_sub->SetBorderMode(0);
   data_obs_pass_postfit_projy1_sub->SetBorderSize(2);
   data_obs_pass_postfit_projy1_sub->SetTickx(1);
   data_obs_pass_postfit_projy1_sub->SetTicky(1);
   data_obs_pass_postfit_projy1_sub->SetLeftMargin(0.17);
   data_obs_pass_postfit_projy1_sub->SetRightMargin(0.05);
   data_obs_pass_postfit_projy1_sub->SetTopMargin(0);
   data_obs_pass_postfit_projy1_sub->SetBottomMargin(0.35);
   data_obs_pass_postfit_projy1_sub->SetFrameFillStyle(0);
   data_obs_pass_postfit_projy1_sub->SetFrameBorderMode(0);
   data_obs_pass_postfit_projy1_sub->SetFrameFillStyle(0);
   data_obs_pass_postfit_projy1_sub->SetFrameBorderMode(0);
   Double_t xAxis451[2] = {50, 200}; 
   
   TH1D *data_obs_pass_postfit_projy1_pull__287 = new TH1D("data_obs_pass_postfit_projy1_pull__287","",1, xAxis451);
   data_obs_pass_postfit_projy1_pull__287->SetBinContent(1,-1.01077);
   data_obs_pass_postfit_projy1_pull__287->SetBinError(1,33.86898);
   data_obs_pass_postfit_projy1_pull__287->SetMinimum(-2.9);
   data_obs_pass_postfit_projy1_pull__287->SetMaximum(2.9);
   data_obs_pass_postfit_projy1_pull__287->SetEntries(36.18474);
   data_obs_pass_postfit_projy1_pull__287->SetStats(0);

   ci = TColor::GetColor("#0000ff");
   data_obs_pass_postfit_projy1_pull__287->SetFillColor(ci);

   ci = TColor::GetColor("#000000");
   data_obs_pass_postfit_projy1_pull__287->SetLineColor(ci);
   data_obs_pass_postfit_projy1_pull__287->SetLineStyle(0);

   ci = TColor::GetColor("#000000");
   data_obs_pass_postfit_projy1_pull__287->SetMarkerColor(ci);
   data_obs_pass_postfit_projy1_pull__287->SetMarkerStyle(8);
   data_obs_pass_postfit_projy1_pull__287->GetXaxis()->SetTitle("p_{T}");
   data_obs_pass_postfit_projy1_pull__287->GetXaxis()->SetLabelFont(42);
   data_obs_pass_postfit_projy1_pull__287->GetXaxis()->SetLabelOffset(0.05);
   data_obs_pass_postfit_projy1_pull__287->GetXaxis()->SetLabelSize(0.13);
   data_obs_pass_postfit_projy1_pull__287->GetXaxis()->SetTitleSize(0.15);
   data_obs_pass_postfit_projy1_pull__287->GetXaxis()->SetTitleOffset(1.15);
   data_obs_pass_postfit_projy1_pull__287->GetXaxis()->SetTitleFont(42);
   data_obs_pass_postfit_projy1_pull__287->GetYaxis()->SetTitle("(Data-Bkg)/#sigma");
   data_obs_pass_postfit_projy1_pull__287->GetYaxis()->SetNdivisions(306);
   data_obs_pass_postfit_projy1_pull__287->GetYaxis()->SetLabelFont(42);
   data_obs_pass_postfit_projy1_pull__287->GetYaxis()->SetLabelOffset(0.007);
   data_obs_pass_postfit_projy1_pull__287->GetYaxis()->SetLabelSize(0.13);
   data_obs_pass_postfit_projy1_pull__287->GetYaxis()->SetTitleSize(0.12);
   data_obs_pass_postfit_projy1_pull__287->GetYaxis()->SetTitleOffset(0.4);
   data_obs_pass_postfit_projy1_pull__287->GetYaxis()->SetTitleFont(42);
   data_obs_pass_postfit_projy1_pull__287->GetZaxis()->SetLabelFont(42);
   data_obs_pass_postfit_projy1_pull__287->GetZaxis()->SetLabelOffset(0.007);
   data_obs_pass_postfit_projy1_pull__287->GetZaxis()->SetLabelSize(0.05);
   data_obs_pass_postfit_projy1_pull__287->GetZaxis()->SetTitleSize(0.08);
   data_obs_pass_postfit_projy1_pull__287->GetZaxis()->SetTitleFont(42);
   data_obs_pass_postfit_projy1_pull__287->Draw("hist");
   data_obs_pass_postfit_projy1_sub->Modified();
   plots_fit_s/base_figs/postfit_projy1_pass->cd();
   plots_fit_s/base_figs/postfit_projy1_pass->Modified();
   plots_fit_s/base_figs/postfit_projy1_pass->cd();
   plots_fit_s/base_figs/postfit_projy1_pass->SetSelected(plots_fit_s/base_figs/postfit_projy1_pass);
}
