void postfit_projy1_fail_logy()
{
//=========Macro generated from canvas: plots_fit_s/base_figs/postfit_projy1_fail_logy/plots_fit_s/base_figs/postfit_projy1_fail_logy
//=========  (Fri Jan 12 21:00:09 2024) by ROOT version 6.14/09
   TCanvas *plots_fit_s/base_figs/postfit_projy1_fail_logy = new TCanvas("plots_fit_s/base_figs/postfit_projy1_fail_logy", "plots_fit_s/base_figs/postfit_projy1_fail_logy",0,0,800,700);
   gStyle->SetOptFit(1);
   gStyle->SetOptStat(0);
   plots_fit_s/base_figs/postfit_projy1_fail_logy->SetHighLightColor(2);
   plots_fit_s/base_figs/postfit_projy1_fail_logy->Range(0,0,1,1);
   plots_fit_s/base_figs/postfit_projy1_fail_logy->SetFillColor(0);
   plots_fit_s/base_figs/postfit_projy1_fail_logy->SetBorderMode(0);
   plots_fit_s/base_figs/postfit_projy1_fail_logy->SetBorderSize(2);
   plots_fit_s/base_figs/postfit_projy1_fail_logy->SetTickx(1);
   plots_fit_s/base_figs/postfit_projy1_fail_logy->SetTicky(1);
   plots_fit_s/base_figs/postfit_projy1_fail_logy->SetLeftMargin(0.16);
   plots_fit_s/base_figs/postfit_projy1_fail_logy->SetRightMargin(0);
   plots_fit_s/base_figs/postfit_projy1_fail_logy->SetTopMargin(0);
   plots_fit_s/base_figs/postfit_projy1_fail_logy->SetBottomMargin(0);
   plots_fit_s/base_figs/postfit_projy1_fail_logy->SetFrameFillStyle(0);
   plots_fit_s/base_figs/postfit_projy1_fail_logy->SetFrameBorderMode(0);
  
// ------------>Primitives in pad: data_obs_fail_postfit_projy1_main
   TPad *data_obs_fail_postfit_projy1_main = new TPad("data_obs_fail_postfit_projy1_main", "data_obs_fail_postfit_projy1_main",0,0.35,1,1);
   data_obs_fail_postfit_projy1_main->Draw();
   data_obs_fail_postfit_projy1_main->cd();
   data_obs_fail_postfit_projy1_main->Range(17.30769,-3.407214,209.6154,6.773135);
   data_obs_fail_postfit_projy1_main->SetFillColor(0);
   data_obs_fail_postfit_projy1_main->SetBorderMode(0);
   data_obs_fail_postfit_projy1_main->SetBorderSize(2);
   data_obs_fail_postfit_projy1_main->SetLogy();
   data_obs_fail_postfit_projy1_main->SetTickx(1);
   data_obs_fail_postfit_projy1_main->SetTicky(1);
   data_obs_fail_postfit_projy1_main->SetLeftMargin(0.17);
   data_obs_fail_postfit_projy1_main->SetRightMargin(0.05);
   data_obs_fail_postfit_projy1_main->SetBottomMargin(0.04);
   data_obs_fail_postfit_projy1_main->SetFrameFillStyle(0);
   data_obs_fail_postfit_projy1_main->SetFrameBorderMode(0);
   data_obs_fail_postfit_projy1_main->SetFrameFillStyle(0);
   data_obs_fail_postfit_projy1_main->SetFrameBorderMode(0);
   Double_t xAxis375[2] = {50, 200}; 
   
   TH1D *data_obs_fail_postfit_projy1__239 = new TH1D("data_obs_fail_postfit_projy1__239","",1, xAxis375);
   data_obs_fail_postfit_projy1__239->SetBinContent(1,6244);
   data_obs_fail_postfit_projy1__239->SetBinError(1,79.01899);
   data_obs_fail_postfit_projy1__239->SetMinimum(0.001);
   data_obs_fail_postfit_projy1__239->SetMaximum(568984.5);
   data_obs_fail_postfit_projy1__239->SetEntries(6244);

   Int_t ci;      // for color index setting
   TColor *color; // for color definition with alpha
   ci = TColor::GetColor("#000000");
   data_obs_fail_postfit_projy1__239->SetLineColor(ci);
   data_obs_fail_postfit_projy1__239->SetLineStyle(0);

   ci = TColor::GetColor("#000000");
   data_obs_fail_postfit_projy1__239->SetMarkerColor(ci);
   data_obs_fail_postfit_projy1__239->SetMarkerStyle(8);
   data_obs_fail_postfit_projy1__239->GetXaxis()->SetTitle("p_{T}");
   data_obs_fail_postfit_projy1__239->GetXaxis()->SetLabelFont(42);
   data_obs_fail_postfit_projy1__239->GetXaxis()->SetLabelOffset(0.05);
   data_obs_fail_postfit_projy1__239->GetXaxis()->SetLabelSize(0.07);
   data_obs_fail_postfit_projy1__239->GetXaxis()->SetTitleSize(0.09);
   data_obs_fail_postfit_projy1__239->GetXaxis()->SetTitleOffset(1.15);
   data_obs_fail_postfit_projy1__239->GetXaxis()->SetTitleFont(42);
   data_obs_fail_postfit_projy1__239->GetYaxis()->SetTitle("Events / bin");
   data_obs_fail_postfit_projy1__239->GetYaxis()->SetNdivisions(508);
   data_obs_fail_postfit_projy1__239->GetYaxis()->SetLabelFont(42);
   data_obs_fail_postfit_projy1__239->GetYaxis()->SetLabelOffset(0.007);
   data_obs_fail_postfit_projy1__239->GetYaxis()->SetLabelSize(0.07);
   data_obs_fail_postfit_projy1__239->GetYaxis()->SetTitleSize(0.09);
   data_obs_fail_postfit_projy1__239->GetYaxis()->SetTitleOffset(0.8);
   data_obs_fail_postfit_projy1__239->GetYaxis()->SetTitleFont(42);
   data_obs_fail_postfit_projy1__239->GetZaxis()->SetLabelFont(42);
   data_obs_fail_postfit_projy1__239->GetZaxis()->SetLabelOffset(0.007);
   data_obs_fail_postfit_projy1__239->GetZaxis()->SetLabelSize(0.05);
   data_obs_fail_postfit_projy1__239->GetZaxis()->SetTitleSize(0.08);
   data_obs_fail_postfit_projy1__239->GetZaxis()->SetTitleFont(42);
   data_obs_fail_postfit_projy1__239->Draw("pe X0");
   
   THStack *postfit_projy1_fail_logy_stack = new THStack();
   postfit_projy1_fail_logy_stack->SetName("postfit_projy1_fail_logy_stack");
   postfit_projy1_fail_logy_stack->SetTitle("postfit_projy1_fail_logy_stack");
   postfit_projy1_fail_logy_stack->SetMinimum(0.001);
   Double_t xAxis376[2] = {50, 200}; 
   
   TH1F *postfit_projy1_fail_logy_stack_stack_69 = new TH1F("postfit_projy1_fail_logy_stack_stack_69","postfit_projy1_fail_logy_stack",1, xAxis376);
   postfit_projy1_fail_logy_stack_stack_69->SetMinimum(0.0002273285);
   postfit_projy1_fail_logy_stack_stack_69->SetMaximum(14814);
   postfit_projy1_fail_logy_stack_stack_69->SetDirectory(0);
   postfit_projy1_fail_logy_stack_stack_69->SetStats(0);
   postfit_projy1_fail_logy_stack_stack_69->SetLineStyle(0);
   postfit_projy1_fail_logy_stack_stack_69->GetXaxis()->SetLabelFont(42);
   postfit_projy1_fail_logy_stack_stack_69->GetXaxis()->SetLabelOffset(0.007);
   postfit_projy1_fail_logy_stack_stack_69->GetXaxis()->SetLabelSize(0.05);
   postfit_projy1_fail_logy_stack_stack_69->GetXaxis()->SetTitleSize(0.08);
   postfit_projy1_fail_logy_stack_stack_69->GetXaxis()->SetTitleOffset(0.9);
   postfit_projy1_fail_logy_stack_stack_69->GetXaxis()->SetTitleFont(42);
   postfit_projy1_fail_logy_stack_stack_69->GetYaxis()->SetNdivisions(508);
   postfit_projy1_fail_logy_stack_stack_69->GetYaxis()->SetLabelFont(42);
   postfit_projy1_fail_logy_stack_stack_69->GetYaxis()->SetLabelOffset(0.007);
   postfit_projy1_fail_logy_stack_stack_69->GetYaxis()->SetLabelSize(0.05);
   postfit_projy1_fail_logy_stack_stack_69->GetYaxis()->SetTitleSize(0.08);
   postfit_projy1_fail_logy_stack_stack_69->GetYaxis()->SetTitleOffset(1.25);
   postfit_projy1_fail_logy_stack_stack_69->GetYaxis()->SetTitleFont(42);
   postfit_projy1_fail_logy_stack_stack_69->GetZaxis()->SetLabelFont(42);
   postfit_projy1_fail_logy_stack_stack_69->GetZaxis()->SetLabelOffset(0.007);
   postfit_projy1_fail_logy_stack_stack_69->GetZaxis()->SetLabelSize(0.05);
   postfit_projy1_fail_logy_stack_stack_69->GetZaxis()->SetTitleSize(0.08);
   postfit_projy1_fail_logy_stack_stack_69->GetZaxis()->SetTitleFont(42);
   postfit_projy1_fail_logy_stack->SetHistogram(postfit_projy1_fail_logy_stack_stack_69);
   
   Double_t xAxis377[2] = {50, 200}; 
   
   TH1D *Background_fail_postfit_projy1_stack_1 = new TH1D("Background_fail_postfit_projy1_stack_1","Background, fail, postfit, 0.24-1.0",1, xAxis377);
   Background_fail_postfit_projy1_stack_1->SetBinContent(1,6203.216);
   Background_fail_postfit_projy1_stack_1->SetBinError(1,75.05098);
   Background_fail_postfit_projy1_stack_1->SetMinimum(0.001);
   Background_fail_postfit_projy1_stack_1->SetEntries(6831.578);

   ci = TColor::GetColor("#ffff00");
   Background_fail_postfit_projy1_stack_1->SetFillColor(ci);

   ci = 1309;
   color = new TColor(ci, 1, 1, 1, " ", 0);
   Background_fail_postfit_projy1_stack_1->SetLineColor(ci);
   Background_fail_postfit_projy1_stack_1->SetLineStyle(0);
   Background_fail_postfit_projy1_stack_1->GetXaxis()->SetTitle("p_{T}");
   Background_fail_postfit_projy1_stack_1->GetXaxis()->SetLabelFont(42);
   Background_fail_postfit_projy1_stack_1->GetXaxis()->SetLabelOffset(0.007);
   Background_fail_postfit_projy1_stack_1->GetXaxis()->SetLabelSize(0.05);
   Background_fail_postfit_projy1_stack_1->GetXaxis()->SetTitleSize(0.08);
   Background_fail_postfit_projy1_stack_1->GetXaxis()->SetTitleOffset(1.25);
   Background_fail_postfit_projy1_stack_1->GetXaxis()->SetTitleFont(42);
   Background_fail_postfit_projy1_stack_1->GetYaxis()->SetTitle("Events / bin");
   Background_fail_postfit_projy1_stack_1->GetYaxis()->SetLabelFont(42);
   Background_fail_postfit_projy1_stack_1->GetYaxis()->SetLabelOffset(0.007);
   Background_fail_postfit_projy1_stack_1->GetYaxis()->SetLabelSize(0.05);
   Background_fail_postfit_projy1_stack_1->GetYaxis()->SetTitleSize(0.08);
   Background_fail_postfit_projy1_stack_1->GetYaxis()->SetTitleOffset(1.25);
   Background_fail_postfit_projy1_stack_1->GetYaxis()->SetTitleFont(42);
   Background_fail_postfit_projy1_stack_1->GetZaxis()->SetLabelFont(42);
   Background_fail_postfit_projy1_stack_1->GetZaxis()->SetLabelOffset(0.007);
   Background_fail_postfit_projy1_stack_1->GetZaxis()->SetLabelSize(0.05);
   Background_fail_postfit_projy1_stack_1->GetZaxis()->SetTitleSize(0.08);
   Background_fail_postfit_projy1_stack_1->GetZaxis()->SetTitleFont(42);
   postfit_projy1_fail_logy_stack->Add(Background_fail_postfit_projy1_stack_1,"");
   postfit_projy1_fail_logy_stack->Draw("hist same");
   
   postfit_projy1_fail_logy_stack = new THStack();
   postfit_projy1_fail_logy_stack->SetName("postfit_projy1_fail_logy_stack");
   postfit_projy1_fail_logy_stack->SetTitle("postfit_projy1_fail_logy_stack");
   postfit_projy1_fail_logy_stack->SetMinimum(0.001);
   Double_t xAxis378[2] = {50, 200}; 
   
   TH1F *postfit_projy1_fail_logy_stack_stack_69_stack_70 = new TH1F("postfit_projy1_fail_logy_stack_stack_69_stack_70","postfit_projy1_fail_logy_stack",1, xAxis378);
   postfit_projy1_fail_logy_stack_stack_69_stack_70->SetMinimum(0.0002273285);
   postfit_projy1_fail_logy_stack_stack_69_stack_70->SetMaximum(14814);
   postfit_projy1_fail_logy_stack_stack_69_stack_70->SetDirectory(0);
   postfit_projy1_fail_logy_stack_stack_69_stack_70->SetStats(0);
   postfit_projy1_fail_logy_stack_stack_69_stack_70->SetLineStyle(0);
   postfit_projy1_fail_logy_stack_stack_69_stack_70->GetXaxis()->SetLabelFont(42);
   postfit_projy1_fail_logy_stack_stack_69_stack_70->GetXaxis()->SetLabelOffset(0.007);
   postfit_projy1_fail_logy_stack_stack_69_stack_70->GetXaxis()->SetLabelSize(0.05);
   postfit_projy1_fail_logy_stack_stack_69_stack_70->GetXaxis()->SetTitleSize(0.08);
   postfit_projy1_fail_logy_stack_stack_69_stack_70->GetXaxis()->SetTitleOffset(0.9);
   postfit_projy1_fail_logy_stack_stack_69_stack_70->GetXaxis()->SetTitleFont(42);
   postfit_projy1_fail_logy_stack_stack_69_stack_70->GetYaxis()->SetNdivisions(508);
   postfit_projy1_fail_logy_stack_stack_69_stack_70->GetYaxis()->SetLabelFont(42);
   postfit_projy1_fail_logy_stack_stack_69_stack_70->GetYaxis()->SetLabelOffset(0.007);
   postfit_projy1_fail_logy_stack_stack_69_stack_70->GetYaxis()->SetLabelSize(0.05);
   postfit_projy1_fail_logy_stack_stack_69_stack_70->GetYaxis()->SetTitleSize(0.08);
   postfit_projy1_fail_logy_stack_stack_69_stack_70->GetYaxis()->SetTitleOffset(1.25);
   postfit_projy1_fail_logy_stack_stack_69_stack_70->GetYaxis()->SetTitleFont(42);
   postfit_projy1_fail_logy_stack_stack_69_stack_70->GetZaxis()->SetLabelFont(42);
   postfit_projy1_fail_logy_stack_stack_69_stack_70->GetZaxis()->SetLabelOffset(0.007);
   postfit_projy1_fail_logy_stack_stack_69_stack_70->GetZaxis()->SetLabelSize(0.05);
   postfit_projy1_fail_logy_stack_stack_69_stack_70->GetZaxis()->SetTitleSize(0.08);
   postfit_projy1_fail_logy_stack_stack_69_stack_70->GetZaxis()->SetTitleFont(42);
   postfit_projy1_fail_logy_stack->SetHistogram(postfit_projy1_fail_logy_stack_stack_69_stack_70);
   
   Double_t xAxis379[2] = {50, 200}; 
   
   TH1D *Background_fail_postfit_projy1_stack_1_stack_1 = new TH1D("Background_fail_postfit_projy1_stack_1_stack_1","Background, fail, postfit, 0.24-1.0",1, xAxis379);
   Background_fail_postfit_projy1_stack_1_stack_1->SetBinContent(1,6203.216);
   Background_fail_postfit_projy1_stack_1_stack_1->SetBinError(1,75.05098);
   Background_fail_postfit_projy1_stack_1_stack_1->SetMinimum(0.001);
   Background_fail_postfit_projy1_stack_1_stack_1->SetEntries(6831.578);

   ci = TColor::GetColor("#ffff00");
   Background_fail_postfit_projy1_stack_1_stack_1->SetFillColor(ci);

   ci = 1309;
   color = new TColor(ci, 1, 1, 1, " ", 0);
   Background_fail_postfit_projy1_stack_1_stack_1->SetLineColor(ci);
   Background_fail_postfit_projy1_stack_1_stack_1->SetLineStyle(0);
   Background_fail_postfit_projy1_stack_1_stack_1->GetXaxis()->SetTitle("p_{T}");
   Background_fail_postfit_projy1_stack_1_stack_1->GetXaxis()->SetLabelFont(42);
   Background_fail_postfit_projy1_stack_1_stack_1->GetXaxis()->SetLabelOffset(0.007);
   Background_fail_postfit_projy1_stack_1_stack_1->GetXaxis()->SetLabelSize(0.05);
   Background_fail_postfit_projy1_stack_1_stack_1->GetXaxis()->SetTitleSize(0.08);
   Background_fail_postfit_projy1_stack_1_stack_1->GetXaxis()->SetTitleOffset(1.25);
   Background_fail_postfit_projy1_stack_1_stack_1->GetXaxis()->SetTitleFont(42);
   Background_fail_postfit_projy1_stack_1_stack_1->GetYaxis()->SetTitle("Events / bin");
   Background_fail_postfit_projy1_stack_1_stack_1->GetYaxis()->SetLabelFont(42);
   Background_fail_postfit_projy1_stack_1_stack_1->GetYaxis()->SetLabelOffset(0.007);
   Background_fail_postfit_projy1_stack_1_stack_1->GetYaxis()->SetLabelSize(0.05);
   Background_fail_postfit_projy1_stack_1_stack_1->GetYaxis()->SetTitleSize(0.08);
   Background_fail_postfit_projy1_stack_1_stack_1->GetYaxis()->SetTitleOffset(1.25);
   Background_fail_postfit_projy1_stack_1_stack_1->GetYaxis()->SetTitleFont(42);
   Background_fail_postfit_projy1_stack_1_stack_1->GetZaxis()->SetLabelFont(42);
   Background_fail_postfit_projy1_stack_1_stack_1->GetZaxis()->SetLabelOffset(0.007);
   Background_fail_postfit_projy1_stack_1_stack_1->GetZaxis()->SetLabelSize(0.05);
   Background_fail_postfit_projy1_stack_1_stack_1->GetZaxis()->SetTitleSize(0.08);
   Background_fail_postfit_projy1_stack_1_stack_1->GetZaxis()->SetTitleFont(42);
   postfit_projy1_fail_logy_stack->Add(Background_fail_postfit_projy1_stack_1_stack_1,"");
   postfit_projy1_fail_logy_stack->Draw("hist same");
   Double_t xAxis380[2] = {50, 200}; 
   
   TH1D *Signal_ppStaumI557_fail_postfit_projy1__240 = new TH1D("Signal_ppStaumI557_fail_postfit_projy1__240","HSCP signal, fail, postfit, 0.24-1.0",1, xAxis380);
   Signal_ppStaumI557_fail_postfit_projy1__240->SetBinContent(1,0.00107264);
   Signal_ppStaumI557_fail_postfit_projy1__240->SetBinError(1,0.0006307652);
   Signal_ppStaumI557_fail_postfit_projy1__240->SetMinimum(0.001);
   Signal_ppStaumI557_fail_postfit_projy1__240->SetEntries(2.891831);
   Signal_ppStaumI557_fail_postfit_projy1__240->SetLineColor(2);
   Signal_ppStaumI557_fail_postfit_projy1__240->SetLineStyle(0);
   Signal_ppStaumI557_fail_postfit_projy1__240->GetXaxis()->SetTitle("p_{T}");
   Signal_ppStaumI557_fail_postfit_projy1__240->GetXaxis()->SetLabelFont(42);
   Signal_ppStaumI557_fail_postfit_projy1__240->GetXaxis()->SetLabelOffset(0.007);
   Signal_ppStaumI557_fail_postfit_projy1__240->GetXaxis()->SetLabelSize(0.05);
   Signal_ppStaumI557_fail_postfit_projy1__240->GetXaxis()->SetTitleSize(0.08);
   Signal_ppStaumI557_fail_postfit_projy1__240->GetXaxis()->SetTitleOffset(1.25);
   Signal_ppStaumI557_fail_postfit_projy1__240->GetXaxis()->SetTitleFont(42);
   Signal_ppStaumI557_fail_postfit_projy1__240->GetYaxis()->SetTitle("Events / bin");
   Signal_ppStaumI557_fail_postfit_projy1__240->GetYaxis()->SetLabelFont(42);
   Signal_ppStaumI557_fail_postfit_projy1__240->GetYaxis()->SetLabelOffset(0.007);
   Signal_ppStaumI557_fail_postfit_projy1__240->GetYaxis()->SetLabelSize(0.05);
   Signal_ppStaumI557_fail_postfit_projy1__240->GetYaxis()->SetTitleSize(0.08);
   Signal_ppStaumI557_fail_postfit_projy1__240->GetYaxis()->SetTitleOffset(1.25);
   Signal_ppStaumI557_fail_postfit_projy1__240->GetYaxis()->SetTitleFont(42);
   Signal_ppStaumI557_fail_postfit_projy1__240->GetZaxis()->SetLabelFont(42);
   Signal_ppStaumI557_fail_postfit_projy1__240->GetZaxis()->SetLabelOffset(0.007);
   Signal_ppStaumI557_fail_postfit_projy1__240->GetZaxis()->SetLabelSize(0.05);
   Signal_ppStaumI557_fail_postfit_projy1__240->GetZaxis()->SetTitleSize(0.08);
   Signal_ppStaumI557_fail_postfit_projy1__240->GetZaxis()->SetTitleFont(42);
   Signal_ppStaumI557_fail_postfit_projy1__240->Draw("hist same");
   Double_t xAxis381[2] = {50, 200}; 
   
   TH1D *TotalBkg_fail_postfit_projy1__241 = new TH1D("TotalBkg_fail_postfit_projy1__241","TotalBkg, fail, postfit, 0.24-1.0",1, xAxis381);
   TotalBkg_fail_postfit_projy1__241->SetBinContent(1,6203.216);
   TotalBkg_fail_postfit_projy1__241->SetBinError(1,73.45434);
   TotalBkg_fail_postfit_projy1__241->SetMinimum(0.001);
   TotalBkg_fail_postfit_projy1__241->SetEntries(7131.795);
   TotalBkg_fail_postfit_projy1__241->SetLineStyle(0);
   TotalBkg_fail_postfit_projy1__241->SetMarkerStyle(0);
   TotalBkg_fail_postfit_projy1__241->GetXaxis()->SetTitle("p_{T}");
   TotalBkg_fail_postfit_projy1__241->GetXaxis()->SetLabelFont(42);
   TotalBkg_fail_postfit_projy1__241->GetXaxis()->SetLabelOffset(0.007);
   TotalBkg_fail_postfit_projy1__241->GetXaxis()->SetLabelSize(0.05);
   TotalBkg_fail_postfit_projy1__241->GetXaxis()->SetTitleSize(0.08);
   TotalBkg_fail_postfit_projy1__241->GetXaxis()->SetTitleOffset(1.25);
   TotalBkg_fail_postfit_projy1__241->GetXaxis()->SetTitleFont(42);
   TotalBkg_fail_postfit_projy1__241->GetYaxis()->SetTitle("Events / bin");
   TotalBkg_fail_postfit_projy1__241->GetYaxis()->SetLabelFont(42);
   TotalBkg_fail_postfit_projy1__241->GetYaxis()->SetLabelOffset(0.007);
   TotalBkg_fail_postfit_projy1__241->GetYaxis()->SetLabelSize(0.05);
   TotalBkg_fail_postfit_projy1__241->GetYaxis()->SetTitleSize(0.08);
   TotalBkg_fail_postfit_projy1__241->GetYaxis()->SetTitleOffset(1.25);
   TotalBkg_fail_postfit_projy1__241->GetYaxis()->SetTitleFont(42);
   TotalBkg_fail_postfit_projy1__241->GetZaxis()->SetLabelFont(42);
   TotalBkg_fail_postfit_projy1__241->GetZaxis()->SetLabelOffset(0.007);
   TotalBkg_fail_postfit_projy1__241->GetZaxis()->SetLabelSize(0.05);
   TotalBkg_fail_postfit_projy1__241->GetZaxis()->SetTitleSize(0.08);
   TotalBkg_fail_postfit_projy1__241->GetZaxis()->SetTitleFont(42);
   TotalBkg_fail_postfit_projy1__241->Draw("hist same");
   Double_t xAxis382[2] = {50, 200}; 
   
   TH1D *TotalBkg_fail_postfit_projy1__242 = new TH1D("TotalBkg_fail_postfit_projy1__242","TotalBkg, fail, postfit, 0.24-1.0",1, xAxis382);
   TotalBkg_fail_postfit_projy1__242->SetBinContent(1,6203.216);
   TotalBkg_fail_postfit_projy1__242->SetBinError(1,73.45434);
   TotalBkg_fail_postfit_projy1__242->SetMinimum(0.001);
   TotalBkg_fail_postfit_projy1__242->SetEntries(7131.795);
   TotalBkg_fail_postfit_projy1__242->SetFillColor(1);
   TotalBkg_fail_postfit_projy1__242->SetFillStyle(3354);
   TotalBkg_fail_postfit_projy1__242->SetLineStyle(0);
   TotalBkg_fail_postfit_projy1__242->SetLineWidth(0);
   TotalBkg_fail_postfit_projy1__242->SetMarkerStyle(0);
   TotalBkg_fail_postfit_projy1__242->GetXaxis()->SetTitle("p_{T}");
   TotalBkg_fail_postfit_projy1__242->GetXaxis()->SetLabelFont(42);
   TotalBkg_fail_postfit_projy1__242->GetXaxis()->SetLabelOffset(0.007);
   TotalBkg_fail_postfit_projy1__242->GetXaxis()->SetLabelSize(0.05);
   TotalBkg_fail_postfit_projy1__242->GetXaxis()->SetTitleSize(0.08);
   TotalBkg_fail_postfit_projy1__242->GetXaxis()->SetTitleOffset(1.25);
   TotalBkg_fail_postfit_projy1__242->GetXaxis()->SetTitleFont(42);
   TotalBkg_fail_postfit_projy1__242->GetYaxis()->SetTitle("Events / bin");
   TotalBkg_fail_postfit_projy1__242->GetYaxis()->SetLabelFont(42);
   TotalBkg_fail_postfit_projy1__242->GetYaxis()->SetLabelOffset(0.007);
   TotalBkg_fail_postfit_projy1__242->GetYaxis()->SetLabelSize(0.05);
   TotalBkg_fail_postfit_projy1__242->GetYaxis()->SetTitleSize(0.08);
   TotalBkg_fail_postfit_projy1__242->GetYaxis()->SetTitleOffset(1.25);
   TotalBkg_fail_postfit_projy1__242->GetYaxis()->SetTitleFont(42);
   TotalBkg_fail_postfit_projy1__242->GetZaxis()->SetLabelFont(42);
   TotalBkg_fail_postfit_projy1__242->GetZaxis()->SetLabelOffset(0.007);
   TotalBkg_fail_postfit_projy1__242->GetZaxis()->SetLabelSize(0.05);
   TotalBkg_fail_postfit_projy1__242->GetZaxis()->SetTitleSize(0.08);
   TotalBkg_fail_postfit_projy1__242->GetZaxis()->SetTitleFont(42);
   TotalBkg_fail_postfit_projy1__242->Draw("e2 same");
   Double_t xAxis383[2] = {50, 200}; 
   
   TH1D *data_obs_fail_postfit_projy1__243 = new TH1D("data_obs_fail_postfit_projy1__243","",1, xAxis383);
   data_obs_fail_postfit_projy1__243->SetBinContent(1,6244);
   data_obs_fail_postfit_projy1__243->SetBinError(1,79.01899);
   data_obs_fail_postfit_projy1__243->SetMinimum(0.001);
   data_obs_fail_postfit_projy1__243->SetMaximum(568984.5);
   data_obs_fail_postfit_projy1__243->SetEntries(6244);

   ci = TColor::GetColor("#000000");
   data_obs_fail_postfit_projy1__243->SetLineColor(ci);
   data_obs_fail_postfit_projy1__243->SetLineStyle(0);

   ci = TColor::GetColor("#000000");
   data_obs_fail_postfit_projy1__243->SetMarkerColor(ci);
   data_obs_fail_postfit_projy1__243->SetMarkerStyle(8);
   data_obs_fail_postfit_projy1__243->GetXaxis()->SetTitle("p_{T}");
   data_obs_fail_postfit_projy1__243->GetXaxis()->SetLabelFont(42);
   data_obs_fail_postfit_projy1__243->GetXaxis()->SetLabelOffset(0.05);
   data_obs_fail_postfit_projy1__243->GetXaxis()->SetLabelSize(0.07);
   data_obs_fail_postfit_projy1__243->GetXaxis()->SetTitleSize(0.09);
   data_obs_fail_postfit_projy1__243->GetXaxis()->SetTitleOffset(1.15);
   data_obs_fail_postfit_projy1__243->GetXaxis()->SetTitleFont(42);
   data_obs_fail_postfit_projy1__243->GetYaxis()->SetTitle("Events / bin");
   data_obs_fail_postfit_projy1__243->GetYaxis()->SetNdivisions(508);
   data_obs_fail_postfit_projy1__243->GetYaxis()->SetLabelFont(42);
   data_obs_fail_postfit_projy1__243->GetYaxis()->SetLabelOffset(0.007);
   data_obs_fail_postfit_projy1__243->GetYaxis()->SetLabelSize(0.07);
   data_obs_fail_postfit_projy1__243->GetYaxis()->SetTitleSize(0.09);
   data_obs_fail_postfit_projy1__243->GetYaxis()->SetTitleOffset(0.8);
   data_obs_fail_postfit_projy1__243->GetYaxis()->SetTitleFont(42);
   data_obs_fail_postfit_projy1__243->GetZaxis()->SetLabelFont(42);
   data_obs_fail_postfit_projy1__243->GetZaxis()->SetLabelOffset(0.007);
   data_obs_fail_postfit_projy1__243->GetZaxis()->SetLabelSize(0.05);
   data_obs_fail_postfit_projy1__243->GetZaxis()->SetTitleSize(0.08);
   data_obs_fail_postfit_projy1__243->GetZaxis()->SetTitleFont(42);
   data_obs_fail_postfit_projy1__243->Draw("pe X0 same");
   
   TLegend *leg = new TLegend(0.65,0.64,0.9,0.88,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(1001);
   TLegendEntry *entry=leg->AddEntry("data_obs_fail_postfit_projy1","Data","pe X0");

   ci = TColor::GetColor("#000000");
   entry->SetLineColor(ci);
   entry->SetLineWidth(1);

   ci = TColor::GetColor("#000000");
   entry->SetMarkerColor(ci);
   entry->SetMarkerStyle(8);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("TotalBkg_fail_postfit_projy1","Total bkg unc.","F");
   entry->SetFillColor(1);
   entry->SetFillStyle(3354);
   entry->SetLineColor(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("Signal_ppStau-557_fail_postfit_projy1","HSCP signal","L");
   entry->SetLineColor(2);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("Background_fail_postfit_projy1_stack_1_stack_1","Background","f");

   ci = TColor::GetColor("#ffff00");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = 1309;
   color = new TColor(ci, 1, 1, 1, " ", 0);
   entry->SetLineColor(ci);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   leg->Draw();
   Double_t xAxis384[2] = {50, 200}; 
   
   TH1D *data_obs_fail_postfit_projy1_copy__244 = new TH1D("data_obs_fail_postfit_projy1_copy__244","",1, xAxis384);
   data_obs_fail_postfit_projy1_copy__244->SetBinContent(1,6244);
   data_obs_fail_postfit_projy1_copy__244->SetBinError(1,79.01899);
   data_obs_fail_postfit_projy1_copy__244->SetMinimum(0.001);
   data_obs_fail_postfit_projy1_copy__244->SetMaximum(568984.5);
   data_obs_fail_postfit_projy1_copy__244->SetEntries(6244);
   data_obs_fail_postfit_projy1_copy__244->SetDirectory(0);

   ci = TColor::GetColor("#000000");
   data_obs_fail_postfit_projy1_copy__244->SetLineColor(ci);
   data_obs_fail_postfit_projy1_copy__244->SetLineStyle(0);

   ci = TColor::GetColor("#000000");
   data_obs_fail_postfit_projy1_copy__244->SetMarkerColor(ci);
   data_obs_fail_postfit_projy1_copy__244->SetMarkerStyle(8);
   data_obs_fail_postfit_projy1_copy__244->GetXaxis()->SetTitle("p_{T}");
   data_obs_fail_postfit_projy1_copy__244->GetXaxis()->SetLabelFont(42);
   data_obs_fail_postfit_projy1_copy__244->GetXaxis()->SetLabelOffset(0.05);
   data_obs_fail_postfit_projy1_copy__244->GetXaxis()->SetLabelSize(0.07);
   data_obs_fail_postfit_projy1_copy__244->GetXaxis()->SetTitleSize(0.09);
   data_obs_fail_postfit_projy1_copy__244->GetXaxis()->SetTitleOffset(1.15);
   data_obs_fail_postfit_projy1_copy__244->GetXaxis()->SetTitleFont(42);
   data_obs_fail_postfit_projy1_copy__244->GetYaxis()->SetTitle("Events / bin");
   data_obs_fail_postfit_projy1_copy__244->GetYaxis()->SetNdivisions(508);
   data_obs_fail_postfit_projy1_copy__244->GetYaxis()->SetLabelFont(42);
   data_obs_fail_postfit_projy1_copy__244->GetYaxis()->SetLabelOffset(0.007);
   data_obs_fail_postfit_projy1_copy__244->GetYaxis()->SetLabelSize(0.07);
   data_obs_fail_postfit_projy1_copy__244->GetYaxis()->SetTitleSize(0.09);
   data_obs_fail_postfit_projy1_copy__244->GetYaxis()->SetTitleOffset(0.8);
   data_obs_fail_postfit_projy1_copy__244->GetYaxis()->SetTitleFont(42);
   data_obs_fail_postfit_projy1_copy__244->GetZaxis()->SetLabelFont(42);
   data_obs_fail_postfit_projy1_copy__244->GetZaxis()->SetLabelOffset(0.007);
   data_obs_fail_postfit_projy1_copy__244->GetZaxis()->SetLabelSize(0.05);
   data_obs_fail_postfit_projy1_copy__244->GetZaxis()->SetTitleSize(0.08);
   data_obs_fail_postfit_projy1_copy__244->GetZaxis()->SetTitleFont(42);
   data_obs_fail_postfit_projy1_copy__244->Draw("sameaxis");
   TLatex *   tex = new TLatex(0.21,0.83,"55 < p_{T} < 200 GeV, F^{Pixels}_{i} < 0.9");
tex->SetNDC();
   tex->SetTextAlign(12);
   tex->SetTextFont(42);
   tex->SetTextSize(0.06);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.17,0.92,"CMS");
tex->SetNDC();
   tex->SetTextFont(61);
   tex->SetTextSize(0.0675);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.25,0.92,"Preliminary");
tex->SetNDC();
   tex->SetTextFont(52);
   tex->SetTextSize(0.0485);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.95,0.92,"101 fb^{-1} (13 TeV)");
tex->SetNDC();
   tex->SetTextAlign(31);
   tex->SetTextFont(42);
   tex->SetTextSize(0.07);
   tex->SetLineWidth(2);
   tex->Draw();
   data_obs_fail_postfit_projy1_main->Modified();
   plots_fit_s/base_figs/postfit_projy1_fail_logy->cd();
  
// ------------>Primitives in pad: data_obs_fail_postfit_projy1_sub
   TPad *data_obs_fail_postfit_projy1_sub = new TPad("data_obs_fail_postfit_projy1_sub", "data_obs_fail_postfit_projy1_sub",0,0,1,0.35);
   data_obs_fail_postfit_projy1_sub->Draw();
   data_obs_fail_postfit_projy1_sub->cd();
   data_obs_fail_postfit_projy1_sub->Range(17.30769,-6.023077,209.6154,2.9);
   data_obs_fail_postfit_projy1_sub->SetFillColor(0);
   data_obs_fail_postfit_projy1_sub->SetBorderMode(0);
   data_obs_fail_postfit_projy1_sub->SetBorderSize(2);
   data_obs_fail_postfit_projy1_sub->SetTickx(1);
   data_obs_fail_postfit_projy1_sub->SetTicky(1);
   data_obs_fail_postfit_projy1_sub->SetLeftMargin(0.17);
   data_obs_fail_postfit_projy1_sub->SetRightMargin(0.05);
   data_obs_fail_postfit_projy1_sub->SetTopMargin(0);
   data_obs_fail_postfit_projy1_sub->SetBottomMargin(0.35);
   data_obs_fail_postfit_projy1_sub->SetFrameFillStyle(0);
   data_obs_fail_postfit_projy1_sub->SetFrameBorderMode(0);
   data_obs_fail_postfit_projy1_sub->SetFrameFillStyle(0);
   data_obs_fail_postfit_projy1_sub->SetFrameBorderMode(0);
   Double_t xAxis385[2] = {50, 200}; 
   
   TH1D *data_obs_fail_postfit_projy1_pull__245 = new TH1D("data_obs_fail_postfit_projy1_pull__245","",1, xAxis385);
   data_obs_fail_postfit_projy1_pull__245->SetBinContent(1,0.3754935);
   data_obs_fail_postfit_projy1_pull__245->SetBinError(1,107.8867);
   data_obs_fail_postfit_projy1_pull__245->SetMinimum(-2.9);
   data_obs_fail_postfit_projy1_pull__245->SetMaximum(2.9);
   data_obs_fail_postfit_projy1_pull__245->SetEntries(1.142905);
   data_obs_fail_postfit_projy1_pull__245->SetStats(0);

   ci = TColor::GetColor("#0000ff");
   data_obs_fail_postfit_projy1_pull__245->SetFillColor(ci);

   ci = TColor::GetColor("#000000");
   data_obs_fail_postfit_projy1_pull__245->SetLineColor(ci);
   data_obs_fail_postfit_projy1_pull__245->SetLineStyle(0);

   ci = TColor::GetColor("#000000");
   data_obs_fail_postfit_projy1_pull__245->SetMarkerColor(ci);
   data_obs_fail_postfit_projy1_pull__245->SetMarkerStyle(8);
   data_obs_fail_postfit_projy1_pull__245->GetXaxis()->SetTitle("p_{T}");
   data_obs_fail_postfit_projy1_pull__245->GetXaxis()->SetLabelFont(42);
   data_obs_fail_postfit_projy1_pull__245->GetXaxis()->SetLabelOffset(0.05);
   data_obs_fail_postfit_projy1_pull__245->GetXaxis()->SetLabelSize(0.13);
   data_obs_fail_postfit_projy1_pull__245->GetXaxis()->SetTitleSize(0.15);
   data_obs_fail_postfit_projy1_pull__245->GetXaxis()->SetTitleOffset(1.15);
   data_obs_fail_postfit_projy1_pull__245->GetXaxis()->SetTitleFont(42);
   data_obs_fail_postfit_projy1_pull__245->GetYaxis()->SetTitle("(Data-Bkg)/#sigma");
   data_obs_fail_postfit_projy1_pull__245->GetYaxis()->SetNdivisions(306);
   data_obs_fail_postfit_projy1_pull__245->GetYaxis()->SetLabelFont(42);
   data_obs_fail_postfit_projy1_pull__245->GetYaxis()->SetLabelOffset(0.007);
   data_obs_fail_postfit_projy1_pull__245->GetYaxis()->SetLabelSize(0.13);
   data_obs_fail_postfit_projy1_pull__245->GetYaxis()->SetTitleSize(0.12);
   data_obs_fail_postfit_projy1_pull__245->GetYaxis()->SetTitleOffset(0.4);
   data_obs_fail_postfit_projy1_pull__245->GetYaxis()->SetTitleFont(42);
   data_obs_fail_postfit_projy1_pull__245->GetZaxis()->SetLabelFont(42);
   data_obs_fail_postfit_projy1_pull__245->GetZaxis()->SetLabelOffset(0.007);
   data_obs_fail_postfit_projy1_pull__245->GetZaxis()->SetLabelSize(0.05);
   data_obs_fail_postfit_projy1_pull__245->GetZaxis()->SetTitleSize(0.08);
   data_obs_fail_postfit_projy1_pull__245->GetZaxis()->SetTitleFont(42);
   data_obs_fail_postfit_projy1_pull__245->Draw("hist");
   data_obs_fail_postfit_projy1_sub->Modified();
   plots_fit_s/base_figs/postfit_projy1_fail_logy->cd();
   plots_fit_s/base_figs/postfit_projy1_fail_logy->Modified();
   plots_fit_s/base_figs/postfit_projy1_fail_logy->cd();
   plots_fit_s/base_figs/postfit_projy1_fail_logy->SetSelected(plots_fit_s/base_figs/postfit_projy1_fail_logy);
}
