void prefit_projy0_pass_logy()
{
//=========Macro generated from canvas: plots_fit_s/base_figs/prefit_projy0_pass_logy/plots_fit_s/base_figs/prefit_projy0_pass_logy
//=========  (Fri Jan 12 21:00:35 2024) by ROOT version 6.14/09
   TCanvas *plots_fit_s/base_figs/prefit_projy0_pass_logy = new TCanvas("plots_fit_s/base_figs/prefit_projy0_pass_logy", "plots_fit_s/base_figs/prefit_projy0_pass_logy",0,0,800,700);
   gStyle->SetOptFit(1);
   gStyle->SetOptStat(0);
   plots_fit_s/base_figs/prefit_projy0_pass_logy->SetHighLightColor(2);
   plots_fit_s/base_figs/prefit_projy0_pass_logy->Range(0,0,1,1);
   plots_fit_s/base_figs/prefit_projy0_pass_logy->SetFillColor(0);
   plots_fit_s/base_figs/prefit_projy0_pass_logy->SetBorderMode(0);
   plots_fit_s/base_figs/prefit_projy0_pass_logy->SetBorderSize(2);
   plots_fit_s/base_figs/prefit_projy0_pass_logy->SetTickx(1);
   plots_fit_s/base_figs/prefit_projy0_pass_logy->SetTicky(1);
   plots_fit_s/base_figs/prefit_projy0_pass_logy->SetLeftMargin(0.16);
   plots_fit_s/base_figs/prefit_projy0_pass_logy->SetRightMargin(0);
   plots_fit_s/base_figs/prefit_projy0_pass_logy->SetTopMargin(0);
   plots_fit_s/base_figs/prefit_projy0_pass_logy->SetBottomMargin(0);
   plots_fit_s/base_figs/prefit_projy0_pass_logy->SetFrameFillStyle(0);
   plots_fit_s/base_figs/prefit_projy0_pass_logy->SetFrameBorderMode(0);
  
// ------------>Primitives in pad: data_obs_pass_prefit_projy0_main
   TPad *data_obs_pass_prefit_projy0_main = new TPad("data_obs_pass_prefit_projy0_main", "data_obs_pass_prefit_projy0_main",0,0.35,1,1);
   data_obs_pass_prefit_projy0_main->Draw();
   data_obs_pass_prefit_projy0_main->cd();
   data_obs_pass_prefit_projy0_main->Range(17.30769,-3.526819,209.6154,9.643647);
   data_obs_pass_prefit_projy0_main->SetFillColor(0);
   data_obs_pass_prefit_projy0_main->SetBorderMode(0);
   data_obs_pass_prefit_projy0_main->SetBorderSize(2);
   data_obs_pass_prefit_projy0_main->SetLogy();
   data_obs_pass_prefit_projy0_main->SetTickx(1);
   data_obs_pass_prefit_projy0_main->SetTicky(1);
   data_obs_pass_prefit_projy0_main->SetLeftMargin(0.17);
   data_obs_pass_prefit_projy0_main->SetRightMargin(0.05);
   data_obs_pass_prefit_projy0_main->SetBottomMargin(0.04);
   data_obs_pass_prefit_projy0_main->SetFrameFillStyle(0);
   data_obs_pass_prefit_projy0_main->SetFrameBorderMode(0);
   data_obs_pass_prefit_projy0_main->SetFrameFillStyle(0);
   data_obs_pass_prefit_projy0_main->SetFrameBorderMode(0);
   Double_t xAxis1024[2] = {50, 200}; 
   
   TH1D *data_obs_pass_prefit_projy0__652 = new TH1D("data_obs_pass_prefit_projy0__652","",1, xAxis1024);
   data_obs_pass_prefit_projy0__652->SetBinContent(1,2327894);
   data_obs_pass_prefit_projy0__652->SetBinError(1,1525.744);
   data_obs_pass_prefit_projy0__652->SetMinimum(0.001);
   data_obs_pass_prefit_projy0__652->SetMaximum(2.121293e+08);
   data_obs_pass_prefit_projy0__652->SetEntries(2327894);

   Int_t ci;      // for color index setting
   TColor *color; // for color definition with alpha
   ci = TColor::GetColor("#000000");
   data_obs_pass_prefit_projy0__652->SetLineColor(ci);
   data_obs_pass_prefit_projy0__652->SetLineStyle(0);

   ci = TColor::GetColor("#000000");
   data_obs_pass_prefit_projy0__652->SetMarkerColor(ci);
   data_obs_pass_prefit_projy0__652->SetMarkerStyle(8);
   data_obs_pass_prefit_projy0__652->GetXaxis()->SetTitle("p_{T}");
   data_obs_pass_prefit_projy0__652->GetXaxis()->SetLabelFont(42);
   data_obs_pass_prefit_projy0__652->GetXaxis()->SetLabelOffset(0.05);
   data_obs_pass_prefit_projy0__652->GetXaxis()->SetLabelSize(0.07);
   data_obs_pass_prefit_projy0__652->GetXaxis()->SetTitleSize(0.09);
   data_obs_pass_prefit_projy0__652->GetXaxis()->SetTitleOffset(1.15);
   data_obs_pass_prefit_projy0__652->GetXaxis()->SetTitleFont(42);
   data_obs_pass_prefit_projy0__652->GetYaxis()->SetTitle("Events / bin");
   data_obs_pass_prefit_projy0__652->GetYaxis()->SetNdivisions(508);
   data_obs_pass_prefit_projy0__652->GetYaxis()->SetLabelFont(42);
   data_obs_pass_prefit_projy0__652->GetYaxis()->SetLabelOffset(0.007);
   data_obs_pass_prefit_projy0__652->GetYaxis()->SetLabelSize(0.07);
   data_obs_pass_prefit_projy0__652->GetYaxis()->SetTitleSize(0.09);
   data_obs_pass_prefit_projy0__652->GetYaxis()->SetTitleOffset(0.8);
   data_obs_pass_prefit_projy0__652->GetYaxis()->SetTitleFont(42);
   data_obs_pass_prefit_projy0__652->GetZaxis()->SetLabelFont(42);
   data_obs_pass_prefit_projy0__652->GetZaxis()->SetLabelOffset(0.007);
   data_obs_pass_prefit_projy0__652->GetZaxis()->SetLabelSize(0.05);
   data_obs_pass_prefit_projy0__652->GetZaxis()->SetTitleSize(0.08);
   data_obs_pass_prefit_projy0__652->GetZaxis()->SetTitleFont(42);
   data_obs_pass_prefit_projy0__652->Draw("pe X0");
   
   THStack *prefit_projy0_pass_logy_stack = new THStack();
   prefit_projy0_pass_logy_stack->SetName("prefit_projy0_pass_logy_stack");
   prefit_projy0_pass_logy_stack->SetTitle("prefit_projy0_pass_logy_stack");
   prefit_projy0_pass_logy_stack->SetMinimum(0.001);
   Double_t xAxis1025[2] = {50, 200}; 
   
   TH1F *prefit_projy0_pass_logy_stack_stack_187 = new TH1F("prefit_projy0_pass_logy_stack_stack_187","prefit_projy0_pass_logy_stack",1, xAxis1025);
   prefit_projy0_pass_logy_stack_stack_187->SetMinimum(0.0001919797);
   prefit_projy0_pass_logy_stack_stack_187->SetMaximum(702230.9);
   prefit_projy0_pass_logy_stack_stack_187->SetDirectory(0);
   prefit_projy0_pass_logy_stack_stack_187->SetStats(0);
   prefit_projy0_pass_logy_stack_stack_187->SetLineStyle(0);
   prefit_projy0_pass_logy_stack_stack_187->GetXaxis()->SetLabelFont(42);
   prefit_projy0_pass_logy_stack_stack_187->GetXaxis()->SetLabelOffset(0.007);
   prefit_projy0_pass_logy_stack_stack_187->GetXaxis()->SetLabelSize(0.05);
   prefit_projy0_pass_logy_stack_stack_187->GetXaxis()->SetTitleSize(0.08);
   prefit_projy0_pass_logy_stack_stack_187->GetXaxis()->SetTitleOffset(0.9);
   prefit_projy0_pass_logy_stack_stack_187->GetXaxis()->SetTitleFont(42);
   prefit_projy0_pass_logy_stack_stack_187->GetYaxis()->SetNdivisions(508);
   prefit_projy0_pass_logy_stack_stack_187->GetYaxis()->SetLabelFont(42);
   prefit_projy0_pass_logy_stack_stack_187->GetYaxis()->SetLabelOffset(0.007);
   prefit_projy0_pass_logy_stack_stack_187->GetYaxis()->SetLabelSize(0.05);
   prefit_projy0_pass_logy_stack_stack_187->GetYaxis()->SetTitleSize(0.08);
   prefit_projy0_pass_logy_stack_stack_187->GetYaxis()->SetTitleOffset(1.25);
   prefit_projy0_pass_logy_stack_stack_187->GetYaxis()->SetTitleFont(42);
   prefit_projy0_pass_logy_stack_stack_187->GetZaxis()->SetLabelFont(42);
   prefit_projy0_pass_logy_stack_stack_187->GetZaxis()->SetLabelOffset(0.007);
   prefit_projy0_pass_logy_stack_stack_187->GetZaxis()->SetLabelSize(0.05);
   prefit_projy0_pass_logy_stack_stack_187->GetZaxis()->SetTitleSize(0.08);
   prefit_projy0_pass_logy_stack_stack_187->GetZaxis()->SetTitleFont(42);
   prefit_projy0_pass_logy_stack->SetHistogram(prefit_projy0_pass_logy_stack_stack_187);
   
   Double_t xAxis1026[2] = {50, 200}; 
   
   TH1D *Background_0x0_pass_prefit_projy0_stack_1 = new TH1D("Background_0x0_pass_prefit_projy0_stack_1","Background, pass, prefit, 0.0-0.24",1, xAxis1026);
   Background_0x0_pass_prefit_projy0_stack_1->SetBinContent(1,140854);
   Background_0x0_pass_prefit_projy0_stack_1->SetBinError(1,120825.5);
   Background_0x0_pass_prefit_projy0_stack_1->SetMinimum(0.001);
   Background_0x0_pass_prefit_projy0_stack_1->SetEntries(1.359005);

   ci = TColor::GetColor("#ffff00");
   Background_0x0_pass_prefit_projy0_stack_1->SetFillColor(ci);

   ci = 1554;
   color = new TColor(ci, 1, 1, 1, " ", 0);
   Background_0x0_pass_prefit_projy0_stack_1->SetLineColor(ci);
   Background_0x0_pass_prefit_projy0_stack_1->SetLineStyle(0);
   Background_0x0_pass_prefit_projy0_stack_1->GetXaxis()->SetTitle("p_{T}");
   Background_0x0_pass_prefit_projy0_stack_1->GetXaxis()->SetLabelFont(42);
   Background_0x0_pass_prefit_projy0_stack_1->GetXaxis()->SetLabelOffset(0.007);
   Background_0x0_pass_prefit_projy0_stack_1->GetXaxis()->SetLabelSize(0.05);
   Background_0x0_pass_prefit_projy0_stack_1->GetXaxis()->SetTitleSize(0.08);
   Background_0x0_pass_prefit_projy0_stack_1->GetXaxis()->SetTitleOffset(1.25);
   Background_0x0_pass_prefit_projy0_stack_1->GetXaxis()->SetTitleFont(42);
   Background_0x0_pass_prefit_projy0_stack_1->GetYaxis()->SetTitle("Events / bin");
   Background_0x0_pass_prefit_projy0_stack_1->GetYaxis()->SetLabelFont(42);
   Background_0x0_pass_prefit_projy0_stack_1->GetYaxis()->SetLabelOffset(0.007);
   Background_0x0_pass_prefit_projy0_stack_1->GetYaxis()->SetLabelSize(0.05);
   Background_0x0_pass_prefit_projy0_stack_1->GetYaxis()->SetTitleSize(0.08);
   Background_0x0_pass_prefit_projy0_stack_1->GetYaxis()->SetTitleOffset(1.25);
   Background_0x0_pass_prefit_projy0_stack_1->GetYaxis()->SetTitleFont(42);
   Background_0x0_pass_prefit_projy0_stack_1->GetZaxis()->SetLabelFont(42);
   Background_0x0_pass_prefit_projy0_stack_1->GetZaxis()->SetLabelOffset(0.007);
   Background_0x0_pass_prefit_projy0_stack_1->GetZaxis()->SetLabelSize(0.05);
   Background_0x0_pass_prefit_projy0_stack_1->GetZaxis()->SetTitleSize(0.08);
   Background_0x0_pass_prefit_projy0_stack_1->GetZaxis()->SetTitleFont(42);
   prefit_projy0_pass_logy_stack->Add(Background_0x0_pass_prefit_projy0_stack_1,"");
   prefit_projy0_pass_logy_stack->Draw("hist same");
   
   prefit_projy0_pass_logy_stack = new THStack();
   prefit_projy0_pass_logy_stack->SetName("prefit_projy0_pass_logy_stack");
   prefit_projy0_pass_logy_stack->SetTitle("prefit_projy0_pass_logy_stack");
   prefit_projy0_pass_logy_stack->SetMinimum(0.001);
   Double_t xAxis1027[2] = {50, 200}; 
   
   TH1F *prefit_projy0_pass_logy_stack_stack_187_stack_188 = new TH1F("prefit_projy0_pass_logy_stack_stack_187_stack_188","prefit_projy0_pass_logy_stack",1, xAxis1027);
   prefit_projy0_pass_logy_stack_stack_187_stack_188->SetMinimum(0.0001919797);
   prefit_projy0_pass_logy_stack_stack_187_stack_188->SetMaximum(702230.9);
   prefit_projy0_pass_logy_stack_stack_187_stack_188->SetDirectory(0);
   prefit_projy0_pass_logy_stack_stack_187_stack_188->SetStats(0);
   prefit_projy0_pass_logy_stack_stack_187_stack_188->SetLineStyle(0);
   prefit_projy0_pass_logy_stack_stack_187_stack_188->GetXaxis()->SetLabelFont(42);
   prefit_projy0_pass_logy_stack_stack_187_stack_188->GetXaxis()->SetLabelOffset(0.007);
   prefit_projy0_pass_logy_stack_stack_187_stack_188->GetXaxis()->SetLabelSize(0.05);
   prefit_projy0_pass_logy_stack_stack_187_stack_188->GetXaxis()->SetTitleSize(0.08);
   prefit_projy0_pass_logy_stack_stack_187_stack_188->GetXaxis()->SetTitleOffset(0.9);
   prefit_projy0_pass_logy_stack_stack_187_stack_188->GetXaxis()->SetTitleFont(42);
   prefit_projy0_pass_logy_stack_stack_187_stack_188->GetYaxis()->SetNdivisions(508);
   prefit_projy0_pass_logy_stack_stack_187_stack_188->GetYaxis()->SetLabelFont(42);
   prefit_projy0_pass_logy_stack_stack_187_stack_188->GetYaxis()->SetLabelOffset(0.007);
   prefit_projy0_pass_logy_stack_stack_187_stack_188->GetYaxis()->SetLabelSize(0.05);
   prefit_projy0_pass_logy_stack_stack_187_stack_188->GetYaxis()->SetTitleSize(0.08);
   prefit_projy0_pass_logy_stack_stack_187_stack_188->GetYaxis()->SetTitleOffset(1.25);
   prefit_projy0_pass_logy_stack_stack_187_stack_188->GetYaxis()->SetTitleFont(42);
   prefit_projy0_pass_logy_stack_stack_187_stack_188->GetZaxis()->SetLabelFont(42);
   prefit_projy0_pass_logy_stack_stack_187_stack_188->GetZaxis()->SetLabelOffset(0.007);
   prefit_projy0_pass_logy_stack_stack_187_stack_188->GetZaxis()->SetLabelSize(0.05);
   prefit_projy0_pass_logy_stack_stack_187_stack_188->GetZaxis()->SetTitleSize(0.08);
   prefit_projy0_pass_logy_stack_stack_187_stack_188->GetZaxis()->SetTitleFont(42);
   prefit_projy0_pass_logy_stack->SetHistogram(prefit_projy0_pass_logy_stack_stack_187_stack_188);
   
   Double_t xAxis1028[2] = {50, 200}; 
   
   TH1D *Background_0x0_pass_prefit_projy0_stack_1_stack_1 = new TH1D("Background_0x0_pass_prefit_projy0_stack_1_stack_1","Background, pass, prefit, 0.0-0.24",1, xAxis1028);
   Background_0x0_pass_prefit_projy0_stack_1_stack_1->SetBinContent(1,140854);
   Background_0x0_pass_prefit_projy0_stack_1_stack_1->SetBinError(1,120825.5);
   Background_0x0_pass_prefit_projy0_stack_1_stack_1->SetMinimum(0.001);
   Background_0x0_pass_prefit_projy0_stack_1_stack_1->SetEntries(1.359005);

   ci = TColor::GetColor("#ffff00");
   Background_0x0_pass_prefit_projy0_stack_1_stack_1->SetFillColor(ci);

   ci = 1554;
   color = new TColor(ci, 1, 1, 1, " ", 0);
   Background_0x0_pass_prefit_projy0_stack_1_stack_1->SetLineColor(ci);
   Background_0x0_pass_prefit_projy0_stack_1_stack_1->SetLineStyle(0);
   Background_0x0_pass_prefit_projy0_stack_1_stack_1->GetXaxis()->SetTitle("p_{T}");
   Background_0x0_pass_prefit_projy0_stack_1_stack_1->GetXaxis()->SetLabelFont(42);
   Background_0x0_pass_prefit_projy0_stack_1_stack_1->GetXaxis()->SetLabelOffset(0.007);
   Background_0x0_pass_prefit_projy0_stack_1_stack_1->GetXaxis()->SetLabelSize(0.05);
   Background_0x0_pass_prefit_projy0_stack_1_stack_1->GetXaxis()->SetTitleSize(0.08);
   Background_0x0_pass_prefit_projy0_stack_1_stack_1->GetXaxis()->SetTitleOffset(1.25);
   Background_0x0_pass_prefit_projy0_stack_1_stack_1->GetXaxis()->SetTitleFont(42);
   Background_0x0_pass_prefit_projy0_stack_1_stack_1->GetYaxis()->SetTitle("Events / bin");
   Background_0x0_pass_prefit_projy0_stack_1_stack_1->GetYaxis()->SetLabelFont(42);
   Background_0x0_pass_prefit_projy0_stack_1_stack_1->GetYaxis()->SetLabelOffset(0.007);
   Background_0x0_pass_prefit_projy0_stack_1_stack_1->GetYaxis()->SetLabelSize(0.05);
   Background_0x0_pass_prefit_projy0_stack_1_stack_1->GetYaxis()->SetTitleSize(0.08);
   Background_0x0_pass_prefit_projy0_stack_1_stack_1->GetYaxis()->SetTitleOffset(1.25);
   Background_0x0_pass_prefit_projy0_stack_1_stack_1->GetYaxis()->SetTitleFont(42);
   Background_0x0_pass_prefit_projy0_stack_1_stack_1->GetZaxis()->SetLabelFont(42);
   Background_0x0_pass_prefit_projy0_stack_1_stack_1->GetZaxis()->SetLabelOffset(0.007);
   Background_0x0_pass_prefit_projy0_stack_1_stack_1->GetZaxis()->SetLabelSize(0.05);
   Background_0x0_pass_prefit_projy0_stack_1_stack_1->GetZaxis()->SetTitleSize(0.08);
   Background_0x0_pass_prefit_projy0_stack_1_stack_1->GetZaxis()->SetTitleFont(42);
   prefit_projy0_pass_logy_stack->Add(Background_0x0_pass_prefit_projy0_stack_1_stack_1,"");
   prefit_projy0_pass_logy_stack->Draw("hist same");
   Double_t xAxis1029[2] = {50, 200}; 
   
   TH1D *Signal_ppStaumI557_pass_prefit_projy0__653 = new TH1D("Signal_ppStaumI557_pass_prefit_projy0__653","HSCP signal, pass, prefit, 0.0-0.24",1, xAxis1029);
   Signal_ppStaumI557_pass_prefit_projy0__653->SetBinContent(1,1.44e-05);
   Signal_ppStaumI557_pass_prefit_projy0__653->SetBinError(1,9.331967e-08);
   Signal_ppStaumI557_pass_prefit_projy0__653->SetMinimum(0.001);
   Signal_ppStaumI557_pass_prefit_projy0__653->SetEntries(23811.05);
   Signal_ppStaumI557_pass_prefit_projy0__653->SetLineColor(2);
   Signal_ppStaumI557_pass_prefit_projy0__653->SetLineStyle(0);
   Signal_ppStaumI557_pass_prefit_projy0__653->GetXaxis()->SetTitle("p_{T}");
   Signal_ppStaumI557_pass_prefit_projy0__653->GetXaxis()->SetLabelFont(42);
   Signal_ppStaumI557_pass_prefit_projy0__653->GetXaxis()->SetLabelOffset(0.007);
   Signal_ppStaumI557_pass_prefit_projy0__653->GetXaxis()->SetLabelSize(0.05);
   Signal_ppStaumI557_pass_prefit_projy0__653->GetXaxis()->SetTitleSize(0.08);
   Signal_ppStaumI557_pass_prefit_projy0__653->GetXaxis()->SetTitleOffset(1.25);
   Signal_ppStaumI557_pass_prefit_projy0__653->GetXaxis()->SetTitleFont(42);
   Signal_ppStaumI557_pass_prefit_projy0__653->GetYaxis()->SetTitle("Events / bin");
   Signal_ppStaumI557_pass_prefit_projy0__653->GetYaxis()->SetLabelFont(42);
   Signal_ppStaumI557_pass_prefit_projy0__653->GetYaxis()->SetLabelOffset(0.007);
   Signal_ppStaumI557_pass_prefit_projy0__653->GetYaxis()->SetLabelSize(0.05);
   Signal_ppStaumI557_pass_prefit_projy0__653->GetYaxis()->SetTitleSize(0.08);
   Signal_ppStaumI557_pass_prefit_projy0__653->GetYaxis()->SetTitleOffset(1.25);
   Signal_ppStaumI557_pass_prefit_projy0__653->GetYaxis()->SetTitleFont(42);
   Signal_ppStaumI557_pass_prefit_projy0__653->GetZaxis()->SetLabelFont(42);
   Signal_ppStaumI557_pass_prefit_projy0__653->GetZaxis()->SetLabelOffset(0.007);
   Signal_ppStaumI557_pass_prefit_projy0__653->GetZaxis()->SetLabelSize(0.05);
   Signal_ppStaumI557_pass_prefit_projy0__653->GetZaxis()->SetTitleSize(0.08);
   Signal_ppStaumI557_pass_prefit_projy0__653->GetZaxis()->SetTitleFont(42);
   Signal_ppStaumI557_pass_prefit_projy0__653->Draw("hist same");
   Double_t xAxis1030[2] = {50, 200}; 
   
   TH1D *TotalBkg_pass_prefit_projy0__654 = new TH1D("TotalBkg_pass_prefit_projy0__654","TotalBkg, pass, prefit, 0.0-0.24",1, xAxis1030);
   TotalBkg_pass_prefit_projy0__654->SetBinContent(1,140854);
   TotalBkg_pass_prefit_projy0__654->SetBinError(1,120825.5);
   TotalBkg_pass_prefit_projy0__654->SetMinimum(0.001);
   TotalBkg_pass_prefit_projy0__654->SetEntries(1.359005);
   TotalBkg_pass_prefit_projy0__654->SetLineStyle(0);
   TotalBkg_pass_prefit_projy0__654->SetMarkerStyle(0);
   TotalBkg_pass_prefit_projy0__654->GetXaxis()->SetTitle("p_{T}");
   TotalBkg_pass_prefit_projy0__654->GetXaxis()->SetLabelFont(42);
   TotalBkg_pass_prefit_projy0__654->GetXaxis()->SetLabelOffset(0.007);
   TotalBkg_pass_prefit_projy0__654->GetXaxis()->SetLabelSize(0.05);
   TotalBkg_pass_prefit_projy0__654->GetXaxis()->SetTitleSize(0.08);
   TotalBkg_pass_prefit_projy0__654->GetXaxis()->SetTitleOffset(1.25);
   TotalBkg_pass_prefit_projy0__654->GetXaxis()->SetTitleFont(42);
   TotalBkg_pass_prefit_projy0__654->GetYaxis()->SetTitle("Events / bin");
   TotalBkg_pass_prefit_projy0__654->GetYaxis()->SetLabelFont(42);
   TotalBkg_pass_prefit_projy0__654->GetYaxis()->SetLabelOffset(0.007);
   TotalBkg_pass_prefit_projy0__654->GetYaxis()->SetLabelSize(0.05);
   TotalBkg_pass_prefit_projy0__654->GetYaxis()->SetTitleSize(0.08);
   TotalBkg_pass_prefit_projy0__654->GetYaxis()->SetTitleOffset(1.25);
   TotalBkg_pass_prefit_projy0__654->GetYaxis()->SetTitleFont(42);
   TotalBkg_pass_prefit_projy0__654->GetZaxis()->SetLabelFont(42);
   TotalBkg_pass_prefit_projy0__654->GetZaxis()->SetLabelOffset(0.007);
   TotalBkg_pass_prefit_projy0__654->GetZaxis()->SetLabelSize(0.05);
   TotalBkg_pass_prefit_projy0__654->GetZaxis()->SetTitleSize(0.08);
   TotalBkg_pass_prefit_projy0__654->GetZaxis()->SetTitleFont(42);
   TotalBkg_pass_prefit_projy0__654->Draw("hist same");
   Double_t xAxis1031[2] = {50, 200}; 
   
   TH1D *TotalBkg_pass_prefit_projy0__655 = new TH1D("TotalBkg_pass_prefit_projy0__655","TotalBkg, pass, prefit, 0.0-0.24",1, xAxis1031);
   TotalBkg_pass_prefit_projy0__655->SetBinContent(1,140854);
   TotalBkg_pass_prefit_projy0__655->SetBinError(1,120825.5);
   TotalBkg_pass_prefit_projy0__655->SetMinimum(0.001);
   TotalBkg_pass_prefit_projy0__655->SetEntries(1.359005);
   TotalBkg_pass_prefit_projy0__655->SetFillColor(1);
   TotalBkg_pass_prefit_projy0__655->SetFillStyle(3354);
   TotalBkg_pass_prefit_projy0__655->SetLineStyle(0);
   TotalBkg_pass_prefit_projy0__655->SetLineWidth(0);
   TotalBkg_pass_prefit_projy0__655->SetMarkerStyle(0);
   TotalBkg_pass_prefit_projy0__655->GetXaxis()->SetTitle("p_{T}");
   TotalBkg_pass_prefit_projy0__655->GetXaxis()->SetLabelFont(42);
   TotalBkg_pass_prefit_projy0__655->GetXaxis()->SetLabelOffset(0.007);
   TotalBkg_pass_prefit_projy0__655->GetXaxis()->SetLabelSize(0.05);
   TotalBkg_pass_prefit_projy0__655->GetXaxis()->SetTitleSize(0.08);
   TotalBkg_pass_prefit_projy0__655->GetXaxis()->SetTitleOffset(1.25);
   TotalBkg_pass_prefit_projy0__655->GetXaxis()->SetTitleFont(42);
   TotalBkg_pass_prefit_projy0__655->GetYaxis()->SetTitle("Events / bin");
   TotalBkg_pass_prefit_projy0__655->GetYaxis()->SetLabelFont(42);
   TotalBkg_pass_prefit_projy0__655->GetYaxis()->SetLabelOffset(0.007);
   TotalBkg_pass_prefit_projy0__655->GetYaxis()->SetLabelSize(0.05);
   TotalBkg_pass_prefit_projy0__655->GetYaxis()->SetTitleSize(0.08);
   TotalBkg_pass_prefit_projy0__655->GetYaxis()->SetTitleOffset(1.25);
   TotalBkg_pass_prefit_projy0__655->GetYaxis()->SetTitleFont(42);
   TotalBkg_pass_prefit_projy0__655->GetZaxis()->SetLabelFont(42);
   TotalBkg_pass_prefit_projy0__655->GetZaxis()->SetLabelOffset(0.007);
   TotalBkg_pass_prefit_projy0__655->GetZaxis()->SetLabelSize(0.05);
   TotalBkg_pass_prefit_projy0__655->GetZaxis()->SetTitleSize(0.08);
   TotalBkg_pass_prefit_projy0__655->GetZaxis()->SetTitleFont(42);
   TotalBkg_pass_prefit_projy0__655->Draw("e2 same");
   Double_t xAxis1032[2] = {50, 200}; 
   
   TH1D *data_obs_pass_prefit_projy0__656 = new TH1D("data_obs_pass_prefit_projy0__656","",1, xAxis1032);
   data_obs_pass_prefit_projy0__656->SetBinContent(1,2327894);
   data_obs_pass_prefit_projy0__656->SetBinError(1,1525.744);
   data_obs_pass_prefit_projy0__656->SetMinimum(0.001);
   data_obs_pass_prefit_projy0__656->SetMaximum(2.121293e+08);
   data_obs_pass_prefit_projy0__656->SetEntries(2327894);

   ci = TColor::GetColor("#000000");
   data_obs_pass_prefit_projy0__656->SetLineColor(ci);
   data_obs_pass_prefit_projy0__656->SetLineStyle(0);

   ci = TColor::GetColor("#000000");
   data_obs_pass_prefit_projy0__656->SetMarkerColor(ci);
   data_obs_pass_prefit_projy0__656->SetMarkerStyle(8);
   data_obs_pass_prefit_projy0__656->GetXaxis()->SetTitle("p_{T}");
   data_obs_pass_prefit_projy0__656->GetXaxis()->SetLabelFont(42);
   data_obs_pass_prefit_projy0__656->GetXaxis()->SetLabelOffset(0.05);
   data_obs_pass_prefit_projy0__656->GetXaxis()->SetLabelSize(0.07);
   data_obs_pass_prefit_projy0__656->GetXaxis()->SetTitleSize(0.09);
   data_obs_pass_prefit_projy0__656->GetXaxis()->SetTitleOffset(1.15);
   data_obs_pass_prefit_projy0__656->GetXaxis()->SetTitleFont(42);
   data_obs_pass_prefit_projy0__656->GetYaxis()->SetTitle("Events / bin");
   data_obs_pass_prefit_projy0__656->GetYaxis()->SetNdivisions(508);
   data_obs_pass_prefit_projy0__656->GetYaxis()->SetLabelFont(42);
   data_obs_pass_prefit_projy0__656->GetYaxis()->SetLabelOffset(0.007);
   data_obs_pass_prefit_projy0__656->GetYaxis()->SetLabelSize(0.07);
   data_obs_pass_prefit_projy0__656->GetYaxis()->SetTitleSize(0.09);
   data_obs_pass_prefit_projy0__656->GetYaxis()->SetTitleOffset(0.8);
   data_obs_pass_prefit_projy0__656->GetYaxis()->SetTitleFont(42);
   data_obs_pass_prefit_projy0__656->GetZaxis()->SetLabelFont(42);
   data_obs_pass_prefit_projy0__656->GetZaxis()->SetLabelOffset(0.007);
   data_obs_pass_prefit_projy0__656->GetZaxis()->SetLabelSize(0.05);
   data_obs_pass_prefit_projy0__656->GetZaxis()->SetTitleSize(0.08);
   data_obs_pass_prefit_projy0__656->GetZaxis()->SetTitleFont(42);
   data_obs_pass_prefit_projy0__656->Draw("pe X0 same");
   
   TLegend *leg = new TLegend(0.65,0.64,0.9,0.88,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(1001);
   TLegendEntry *entry=leg->AddEntry("data_obs_pass_prefit_projy0","Data","pe X0");

   ci = TColor::GetColor("#000000");
   entry->SetLineColor(ci);
   entry->SetLineWidth(1);

   ci = TColor::GetColor("#000000");
   entry->SetMarkerColor(ci);
   entry->SetMarkerStyle(8);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("TotalBkg_pass_prefit_projy0","Total bkg unc.","F");
   entry->SetFillColor(1);
   entry->SetFillStyle(3354);
   entry->SetLineColor(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("Signal_ppStau-557_pass_prefit_projy0","HSCP signal","L");
   entry->SetLineColor(2);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("Background_0x0_pass_prefit_projy0_stack_1_stack_1","Background","f");

   ci = TColor::GetColor("#ffff00");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = 1554;
   color = new TColor(ci, 1, 1, 1, " ", 0);
   entry->SetLineColor(ci);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   leg->Draw();
   Double_t xAxis1033[2] = {50, 200}; 
   
   TH1D *data_obs_pass_prefit_projy0_copy__657 = new TH1D("data_obs_pass_prefit_projy0_copy__657","",1, xAxis1033);
   data_obs_pass_prefit_projy0_copy__657->SetBinContent(1,2327894);
   data_obs_pass_prefit_projy0_copy__657->SetBinError(1,1525.744);
   data_obs_pass_prefit_projy0_copy__657->SetMinimum(0.001);
   data_obs_pass_prefit_projy0_copy__657->SetMaximum(2.121293e+08);
   data_obs_pass_prefit_projy0_copy__657->SetEntries(2327894);
   data_obs_pass_prefit_projy0_copy__657->SetDirectory(0);

   ci = TColor::GetColor("#000000");
   data_obs_pass_prefit_projy0_copy__657->SetLineColor(ci);
   data_obs_pass_prefit_projy0_copy__657->SetLineStyle(0);

   ci = TColor::GetColor("#000000");
   data_obs_pass_prefit_projy0_copy__657->SetMarkerColor(ci);
   data_obs_pass_prefit_projy0_copy__657->SetMarkerStyle(8);
   data_obs_pass_prefit_projy0_copy__657->GetXaxis()->SetTitle("p_{T}");
   data_obs_pass_prefit_projy0_copy__657->GetXaxis()->SetLabelFont(42);
   data_obs_pass_prefit_projy0_copy__657->GetXaxis()->SetLabelOffset(0.05);
   data_obs_pass_prefit_projy0_copy__657->GetXaxis()->SetLabelSize(0.07);
   data_obs_pass_prefit_projy0_copy__657->GetXaxis()->SetTitleSize(0.09);
   data_obs_pass_prefit_projy0_copy__657->GetXaxis()->SetTitleOffset(1.15);
   data_obs_pass_prefit_projy0_copy__657->GetXaxis()->SetTitleFont(42);
   data_obs_pass_prefit_projy0_copy__657->GetYaxis()->SetTitle("Events / bin");
   data_obs_pass_prefit_projy0_copy__657->GetYaxis()->SetNdivisions(508);
   data_obs_pass_prefit_projy0_copy__657->GetYaxis()->SetLabelFont(42);
   data_obs_pass_prefit_projy0_copy__657->GetYaxis()->SetLabelOffset(0.007);
   data_obs_pass_prefit_projy0_copy__657->GetYaxis()->SetLabelSize(0.07);
   data_obs_pass_prefit_projy0_copy__657->GetYaxis()->SetTitleSize(0.09);
   data_obs_pass_prefit_projy0_copy__657->GetYaxis()->SetTitleOffset(0.8);
   data_obs_pass_prefit_projy0_copy__657->GetYaxis()->SetTitleFont(42);
   data_obs_pass_prefit_projy0_copy__657->GetZaxis()->SetLabelFont(42);
   data_obs_pass_prefit_projy0_copy__657->GetZaxis()->SetLabelOffset(0.007);
   data_obs_pass_prefit_projy0_copy__657->GetZaxis()->SetLabelSize(0.05);
   data_obs_pass_prefit_projy0_copy__657->GetZaxis()->SetTitleSize(0.08);
   data_obs_pass_prefit_projy0_copy__657->GetZaxis()->SetTitleFont(42);
   data_obs_pass_prefit_projy0_copy__657->Draw("sameaxis");
   TLatex *   tex = new TLatex(0.21,0.83,"55 < p_{T} < 200 GeV, F^{Pixels}_{i} > 0.9");
tex->SetNDC();
   tex->SetTextAlign(12);
   tex->SetTextFont(42);
   tex->SetTextSize(0.06);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.17,0.92,"CMS");
tex->SetNDC();
   tex->SetTextFont(61);
   tex->SetTextSize(0.0675);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.25,0.92,"Preliminary");
tex->SetNDC();
   tex->SetTextFont(52);
   tex->SetTextSize(0.0485);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.95,0.92,"101 fb^{-1} (13 TeV)");
tex->SetNDC();
   tex->SetTextAlign(31);
   tex->SetTextFont(42);
   tex->SetTextSize(0.07);
   tex->SetLineWidth(2);
   tex->Draw();
   data_obs_pass_prefit_projy0_main->Modified();
   plots_fit_s/base_figs/prefit_projy0_pass_logy->cd();
  
// ------------>Primitives in pad: data_obs_pass_prefit_projy0_sub
   TPad *data_obs_pass_prefit_projy0_sub = new TPad("data_obs_pass_prefit_projy0_sub", "data_obs_pass_prefit_projy0_sub",0,0,1,0.35);
   data_obs_pass_prefit_projy0_sub->Draw();
   data_obs_pass_prefit_projy0_sub->cd();
   data_obs_pass_prefit_projy0_sub->Range(17.30769,-6.023077,209.6154,2.9);
   data_obs_pass_prefit_projy0_sub->SetFillColor(0);
   data_obs_pass_prefit_projy0_sub->SetBorderMode(0);
   data_obs_pass_prefit_projy0_sub->SetBorderSize(2);
   data_obs_pass_prefit_projy0_sub->SetTickx(1);
   data_obs_pass_prefit_projy0_sub->SetTicky(1);
   data_obs_pass_prefit_projy0_sub->SetLeftMargin(0.17);
   data_obs_pass_prefit_projy0_sub->SetRightMargin(0.05);
   data_obs_pass_prefit_projy0_sub->SetTopMargin(0);
   data_obs_pass_prefit_projy0_sub->SetBottomMargin(0.35);
   data_obs_pass_prefit_projy0_sub->SetFrameFillStyle(0);
   data_obs_pass_prefit_projy0_sub->SetFrameBorderMode(0);
   data_obs_pass_prefit_projy0_sub->SetFrameFillStyle(0);
   data_obs_pass_prefit_projy0_sub->SetFrameBorderMode(0);
   Double_t xAxis1034[2] = {50, 200}; 
   
   TH1D *data_obs_pass_prefit_projy0_pull__658 = new TH1D("data_obs_pass_prefit_projy0_pull__658","",1, xAxis1034);
   data_obs_pass_prefit_projy0_pull__658->SetBinContent(1,18.09937);
   data_obs_pass_prefit_projy0_pull__658->SetBinError(1,120835.1);
   data_obs_pass_prefit_projy0_pull__658->SetMinimum(-2.9);
   data_obs_pass_prefit_projy0_pull__658->SetMaximum(2.9);
   data_obs_pass_prefit_projy0_pull__658->SetEntries(328.5873);
   data_obs_pass_prefit_projy0_pull__658->SetStats(0);

   ci = TColor::GetColor("#0000ff");
   data_obs_pass_prefit_projy0_pull__658->SetFillColor(ci);

   ci = TColor::GetColor("#000000");
   data_obs_pass_prefit_projy0_pull__658->SetLineColor(ci);
   data_obs_pass_prefit_projy0_pull__658->SetLineStyle(0);

   ci = TColor::GetColor("#000000");
   data_obs_pass_prefit_projy0_pull__658->SetMarkerColor(ci);
   data_obs_pass_prefit_projy0_pull__658->SetMarkerStyle(8);
   data_obs_pass_prefit_projy0_pull__658->GetXaxis()->SetTitle("p_{T}");
   data_obs_pass_prefit_projy0_pull__658->GetXaxis()->SetLabelFont(42);
   data_obs_pass_prefit_projy0_pull__658->GetXaxis()->SetLabelOffset(0.05);
   data_obs_pass_prefit_projy0_pull__658->GetXaxis()->SetLabelSize(0.13);
   data_obs_pass_prefit_projy0_pull__658->GetXaxis()->SetTitleSize(0.15);
   data_obs_pass_prefit_projy0_pull__658->GetXaxis()->SetTitleOffset(1.15);
   data_obs_pass_prefit_projy0_pull__658->GetXaxis()->SetTitleFont(42);
   data_obs_pass_prefit_projy0_pull__658->GetYaxis()->SetTitle("(Data-Bkg)/#sigma");
   data_obs_pass_prefit_projy0_pull__658->GetYaxis()->SetNdivisions(306);
   data_obs_pass_prefit_projy0_pull__658->GetYaxis()->SetLabelFont(42);
   data_obs_pass_prefit_projy0_pull__658->GetYaxis()->SetLabelOffset(0.007);
   data_obs_pass_prefit_projy0_pull__658->GetYaxis()->SetLabelSize(0.13);
   data_obs_pass_prefit_projy0_pull__658->GetYaxis()->SetTitleSize(0.12);
   data_obs_pass_prefit_projy0_pull__658->GetYaxis()->SetTitleOffset(0.4);
   data_obs_pass_prefit_projy0_pull__658->GetYaxis()->SetTitleFont(42);
   data_obs_pass_prefit_projy0_pull__658->GetZaxis()->SetLabelFont(42);
   data_obs_pass_prefit_projy0_pull__658->GetZaxis()->SetLabelOffset(0.007);
   data_obs_pass_prefit_projy0_pull__658->GetZaxis()->SetLabelSize(0.05);
   data_obs_pass_prefit_projy0_pull__658->GetZaxis()->SetTitleSize(0.08);
   data_obs_pass_prefit_projy0_pull__658->GetZaxis()->SetTitleFont(42);
   data_obs_pass_prefit_projy0_pull__658->Draw("hist");
   data_obs_pass_prefit_projy0_sub->Modified();
   plots_fit_s/base_figs/prefit_projy0_pass_logy->cd();
   plots_fit_s/base_figs/prefit_projy0_pass_logy->Modified();
   plots_fit_s/base_figs/prefit_projy0_pass_logy->cd();
   plots_fit_s/base_figs/prefit_projy0_pass_logy->SetSelected(plots_fit_s/base_figs/prefit_projy0_pass_logy);
}
