void prefit_projy1_fail_logy()
{
//=========Macro generated from canvas: plots_fit_s/base_figs/prefit_projy1_fail_logy/plots_fit_s/base_figs/prefit_projy1_fail_logy
//=========  (Fri Jan 12 21:00:34 2024) by ROOT version 6.14/09
   TCanvas *plots_fit_s/base_figs/prefit_projy1_fail_logy = new TCanvas("plots_fit_s/base_figs/prefit_projy1_fail_logy", "plots_fit_s/base_figs/prefit_projy1_fail_logy",0,0,800,700);
   gStyle->SetOptFit(1);
   gStyle->SetOptStat(0);
   plots_fit_s/base_figs/prefit_projy1_fail_logy->SetHighLightColor(2);
   plots_fit_s/base_figs/prefit_projy1_fail_logy->Range(0,0,1,1);
   plots_fit_s/base_figs/prefit_projy1_fail_logy->SetFillColor(0);
   plots_fit_s/base_figs/prefit_projy1_fail_logy->SetBorderMode(0);
   plots_fit_s/base_figs/prefit_projy1_fail_logy->SetBorderSize(2);
   plots_fit_s/base_figs/prefit_projy1_fail_logy->SetTickx(1);
   plots_fit_s/base_figs/prefit_projy1_fail_logy->SetTicky(1);
   plots_fit_s/base_figs/prefit_projy1_fail_logy->SetLeftMargin(0.16);
   plots_fit_s/base_figs/prefit_projy1_fail_logy->SetRightMargin(0);
   plots_fit_s/base_figs/prefit_projy1_fail_logy->SetTopMargin(0);
   plots_fit_s/base_figs/prefit_projy1_fail_logy->SetBottomMargin(0);
   plots_fit_s/base_figs/prefit_projy1_fail_logy->SetFrameFillStyle(0);
   plots_fit_s/base_figs/prefit_projy1_fail_logy->SetFrameBorderMode(0);
  
// ------------>Primitives in pad: data_obs_fail_prefit_projy1_main
   TPad *data_obs_fail_prefit_projy1_main = new TPad("data_obs_fail_prefit_projy1_main", "data_obs_fail_prefit_projy1_main",0,0.35,1,1);
   data_obs_fail_prefit_projy1_main->Draw();
   data_obs_fail_prefit_projy1_main->cd();
   data_obs_fail_prefit_projy1_main->Range(17.30769,-3.407214,209.6154,6.773135);
   data_obs_fail_prefit_projy1_main->SetFillColor(0);
   data_obs_fail_prefit_projy1_main->SetBorderMode(0);
   data_obs_fail_prefit_projy1_main->SetBorderSize(2);
   data_obs_fail_prefit_projy1_main->SetLogy();
   data_obs_fail_prefit_projy1_main->SetTickx(1);
   data_obs_fail_prefit_projy1_main->SetTicky(1);
   data_obs_fail_prefit_projy1_main->SetLeftMargin(0.17);
   data_obs_fail_prefit_projy1_main->SetRightMargin(0.05);
   data_obs_fail_prefit_projy1_main->SetBottomMargin(0.04);
   data_obs_fail_prefit_projy1_main->SetFrameFillStyle(0);
   data_obs_fail_prefit_projy1_main->SetFrameBorderMode(0);
   data_obs_fail_prefit_projy1_main->SetFrameFillStyle(0);
   data_obs_fail_prefit_projy1_main->SetFrameBorderMode(0);
   Double_t xAxis903[2] = {50, 200}; 
   
   TH1D *data_obs_fail_prefit_projy1__575 = new TH1D("data_obs_fail_prefit_projy1__575","",1, xAxis903);
   data_obs_fail_prefit_projy1__575->SetBinContent(1,6244);
   data_obs_fail_prefit_projy1__575->SetBinError(1,79.01899);
   data_obs_fail_prefit_projy1__575->SetMinimum(0.001);
   data_obs_fail_prefit_projy1__575->SetMaximum(568984.5);
   data_obs_fail_prefit_projy1__575->SetEntries(6244);

   Int_t ci;      // for color index setting
   TColor *color; // for color definition with alpha
   ci = TColor::GetColor("#000000");
   data_obs_fail_prefit_projy1__575->SetLineColor(ci);
   data_obs_fail_prefit_projy1__575->SetLineStyle(0);

   ci = TColor::GetColor("#000000");
   data_obs_fail_prefit_projy1__575->SetMarkerColor(ci);
   data_obs_fail_prefit_projy1__575->SetMarkerStyle(8);
   data_obs_fail_prefit_projy1__575->GetXaxis()->SetTitle("p_{T}");
   data_obs_fail_prefit_projy1__575->GetXaxis()->SetLabelFont(42);
   data_obs_fail_prefit_projy1__575->GetXaxis()->SetLabelOffset(0.05);
   data_obs_fail_prefit_projy1__575->GetXaxis()->SetLabelSize(0.07);
   data_obs_fail_prefit_projy1__575->GetXaxis()->SetTitleSize(0.09);
   data_obs_fail_prefit_projy1__575->GetXaxis()->SetTitleOffset(1.15);
   data_obs_fail_prefit_projy1__575->GetXaxis()->SetTitleFont(42);
   data_obs_fail_prefit_projy1__575->GetYaxis()->SetTitle("Events / bin");
   data_obs_fail_prefit_projy1__575->GetYaxis()->SetNdivisions(508);
   data_obs_fail_prefit_projy1__575->GetYaxis()->SetLabelFont(42);
   data_obs_fail_prefit_projy1__575->GetYaxis()->SetLabelOffset(0.007);
   data_obs_fail_prefit_projy1__575->GetYaxis()->SetLabelSize(0.07);
   data_obs_fail_prefit_projy1__575->GetYaxis()->SetTitleSize(0.09);
   data_obs_fail_prefit_projy1__575->GetYaxis()->SetTitleOffset(0.8);
   data_obs_fail_prefit_projy1__575->GetYaxis()->SetTitleFont(42);
   data_obs_fail_prefit_projy1__575->GetZaxis()->SetLabelFont(42);
   data_obs_fail_prefit_projy1__575->GetZaxis()->SetLabelOffset(0.007);
   data_obs_fail_prefit_projy1__575->GetZaxis()->SetLabelSize(0.05);
   data_obs_fail_prefit_projy1__575->GetZaxis()->SetTitleSize(0.08);
   data_obs_fail_prefit_projy1__575->GetZaxis()->SetTitleFont(42);
   data_obs_fail_prefit_projy1__575->Draw("pe X0");
   
   THStack *prefit_projy1_fail_logy_stack = new THStack();
   prefit_projy1_fail_logy_stack->SetName("prefit_projy1_fail_logy_stack");
   prefit_projy1_fail_logy_stack->SetTitle("prefit_projy1_fail_logy_stack");
   prefit_projy1_fail_logy_stack->SetMinimum(0.001);
   Double_t xAxis904[2] = {50, 200}; 
   
   TH1F *prefit_projy1_fail_logy_stack_stack_165 = new TH1F("prefit_projy1_fail_logy_stack_stack_165","prefit_projy1_fail_logy_stack",1, xAxis904);
   prefit_projy1_fail_logy_stack_stack_165->SetMinimum(0.00022739);
   prefit_projy1_fail_logy_stack_stack_165->SetMaximum(14730.17);
   prefit_projy1_fail_logy_stack_stack_165->SetDirectory(0);
   prefit_projy1_fail_logy_stack_stack_165->SetStats(0);
   prefit_projy1_fail_logy_stack_stack_165->SetLineStyle(0);
   prefit_projy1_fail_logy_stack_stack_165->GetXaxis()->SetLabelFont(42);
   prefit_projy1_fail_logy_stack_stack_165->GetXaxis()->SetLabelOffset(0.007);
   prefit_projy1_fail_logy_stack_stack_165->GetXaxis()->SetLabelSize(0.05);
   prefit_projy1_fail_logy_stack_stack_165->GetXaxis()->SetTitleSize(0.08);
   prefit_projy1_fail_logy_stack_stack_165->GetXaxis()->SetTitleOffset(0.9);
   prefit_projy1_fail_logy_stack_stack_165->GetXaxis()->SetTitleFont(42);
   prefit_projy1_fail_logy_stack_stack_165->GetYaxis()->SetNdivisions(508);
   prefit_projy1_fail_logy_stack_stack_165->GetYaxis()->SetLabelFont(42);
   prefit_projy1_fail_logy_stack_stack_165->GetYaxis()->SetLabelOffset(0.007);
   prefit_projy1_fail_logy_stack_stack_165->GetYaxis()->SetLabelSize(0.05);
   prefit_projy1_fail_logy_stack_stack_165->GetYaxis()->SetTitleSize(0.08);
   prefit_projy1_fail_logy_stack_stack_165->GetYaxis()->SetTitleOffset(1.25);
   prefit_projy1_fail_logy_stack_stack_165->GetYaxis()->SetTitleFont(42);
   prefit_projy1_fail_logy_stack_stack_165->GetZaxis()->SetLabelFont(42);
   prefit_projy1_fail_logy_stack_stack_165->GetZaxis()->SetLabelOffset(0.007);
   prefit_projy1_fail_logy_stack_stack_165->GetZaxis()->SetLabelSize(0.05);
   prefit_projy1_fail_logy_stack_stack_165->GetZaxis()->SetTitleSize(0.08);
   prefit_projy1_fail_logy_stack_stack_165->GetZaxis()->SetTitleFont(42);
   prefit_projy1_fail_logy_stack->SetHistogram(prefit_projy1_fail_logy_stack_stack_165);
   
   Double_t xAxis905[2] = {50, 200}; 
   
   TH1D *Background_fail_prefit_projy1_stack_1 = new TH1D("Background_fail_prefit_projy1_stack_1","Background, fail, prefit, 0.24-1.0",1, xAxis905);
   Background_fail_prefit_projy1_stack_1->SetBinContent(1,6244);
   Background_fail_prefit_projy1_stack_1->SetMinimum(0.001);
   Background_fail_prefit_projy1_stack_1->SetEntries(6244);

   ci = TColor::GetColor("#ffff00");
   Background_fail_prefit_projy1_stack_1->SetFillColor(ci);

   ci = 1543;
   color = new TColor(ci, 1, 1, 1, " ", 0);
   Background_fail_prefit_projy1_stack_1->SetLineColor(ci);
   Background_fail_prefit_projy1_stack_1->SetLineStyle(0);
   Background_fail_prefit_projy1_stack_1->GetXaxis()->SetTitle("p_{T}");
   Background_fail_prefit_projy1_stack_1->GetXaxis()->SetLabelFont(42);
   Background_fail_prefit_projy1_stack_1->GetXaxis()->SetLabelOffset(0.007);
   Background_fail_prefit_projy1_stack_1->GetXaxis()->SetLabelSize(0.05);
   Background_fail_prefit_projy1_stack_1->GetXaxis()->SetTitleSize(0.08);
   Background_fail_prefit_projy1_stack_1->GetXaxis()->SetTitleOffset(1.25);
   Background_fail_prefit_projy1_stack_1->GetXaxis()->SetTitleFont(42);
   Background_fail_prefit_projy1_stack_1->GetYaxis()->SetTitle("Events / bin");
   Background_fail_prefit_projy1_stack_1->GetYaxis()->SetLabelFont(42);
   Background_fail_prefit_projy1_stack_1->GetYaxis()->SetLabelOffset(0.007);
   Background_fail_prefit_projy1_stack_1->GetYaxis()->SetLabelSize(0.05);
   Background_fail_prefit_projy1_stack_1->GetYaxis()->SetTitleSize(0.08);
   Background_fail_prefit_projy1_stack_1->GetYaxis()->SetTitleOffset(1.25);
   Background_fail_prefit_projy1_stack_1->GetYaxis()->SetTitleFont(42);
   Background_fail_prefit_projy1_stack_1->GetZaxis()->SetLabelFont(42);
   Background_fail_prefit_projy1_stack_1->GetZaxis()->SetLabelOffset(0.007);
   Background_fail_prefit_projy1_stack_1->GetZaxis()->SetLabelSize(0.05);
   Background_fail_prefit_projy1_stack_1->GetZaxis()->SetTitleSize(0.08);
   Background_fail_prefit_projy1_stack_1->GetZaxis()->SetTitleFont(42);
   prefit_projy1_fail_logy_stack->Add(Background_fail_prefit_projy1_stack_1,"");
   prefit_projy1_fail_logy_stack->Draw("hist same");
   
   prefit_projy1_fail_logy_stack = new THStack();
   prefit_projy1_fail_logy_stack->SetName("prefit_projy1_fail_logy_stack");
   prefit_projy1_fail_logy_stack->SetTitle("prefit_projy1_fail_logy_stack");
   prefit_projy1_fail_logy_stack->SetMinimum(0.001);
   Double_t xAxis906[2] = {50, 200}; 
   
   TH1F *prefit_projy1_fail_logy_stack_stack_165_stack_166 = new TH1F("prefit_projy1_fail_logy_stack_stack_165_stack_166","prefit_projy1_fail_logy_stack",1, xAxis906);
   prefit_projy1_fail_logy_stack_stack_165_stack_166->SetMinimum(0.00022739);
   prefit_projy1_fail_logy_stack_stack_165_stack_166->SetMaximum(14730.17);
   prefit_projy1_fail_logy_stack_stack_165_stack_166->SetDirectory(0);
   prefit_projy1_fail_logy_stack_stack_165_stack_166->SetStats(0);
   prefit_projy1_fail_logy_stack_stack_165_stack_166->SetLineStyle(0);
   prefit_projy1_fail_logy_stack_stack_165_stack_166->GetXaxis()->SetLabelFont(42);
   prefit_projy1_fail_logy_stack_stack_165_stack_166->GetXaxis()->SetLabelOffset(0.007);
   prefit_projy1_fail_logy_stack_stack_165_stack_166->GetXaxis()->SetLabelSize(0.05);
   prefit_projy1_fail_logy_stack_stack_165_stack_166->GetXaxis()->SetTitleSize(0.08);
   prefit_projy1_fail_logy_stack_stack_165_stack_166->GetXaxis()->SetTitleOffset(0.9);
   prefit_projy1_fail_logy_stack_stack_165_stack_166->GetXaxis()->SetTitleFont(42);
   prefit_projy1_fail_logy_stack_stack_165_stack_166->GetYaxis()->SetNdivisions(508);
   prefit_projy1_fail_logy_stack_stack_165_stack_166->GetYaxis()->SetLabelFont(42);
   prefit_projy1_fail_logy_stack_stack_165_stack_166->GetYaxis()->SetLabelOffset(0.007);
   prefit_projy1_fail_logy_stack_stack_165_stack_166->GetYaxis()->SetLabelSize(0.05);
   prefit_projy1_fail_logy_stack_stack_165_stack_166->GetYaxis()->SetTitleSize(0.08);
   prefit_projy1_fail_logy_stack_stack_165_stack_166->GetYaxis()->SetTitleOffset(1.25);
   prefit_projy1_fail_logy_stack_stack_165_stack_166->GetYaxis()->SetTitleFont(42);
   prefit_projy1_fail_logy_stack_stack_165_stack_166->GetZaxis()->SetLabelFont(42);
   prefit_projy1_fail_logy_stack_stack_165_stack_166->GetZaxis()->SetLabelOffset(0.007);
   prefit_projy1_fail_logy_stack_stack_165_stack_166->GetZaxis()->SetLabelSize(0.05);
   prefit_projy1_fail_logy_stack_stack_165_stack_166->GetZaxis()->SetTitleSize(0.08);
   prefit_projy1_fail_logy_stack_stack_165_stack_166->GetZaxis()->SetTitleFont(42);
   prefit_projy1_fail_logy_stack->SetHistogram(prefit_projy1_fail_logy_stack_stack_165_stack_166);
   
   Double_t xAxis907[2] = {50, 200}; 
   
   TH1D *Background_fail_prefit_projy1_stack_1_stack_1 = new TH1D("Background_fail_prefit_projy1_stack_1_stack_1","Background, fail, prefit, 0.24-1.0",1, xAxis907);
   Background_fail_prefit_projy1_stack_1_stack_1->SetBinContent(1,6244);
   Background_fail_prefit_projy1_stack_1_stack_1->SetMinimum(0.001);
   Background_fail_prefit_projy1_stack_1_stack_1->SetEntries(6244);

   ci = TColor::GetColor("#ffff00");
   Background_fail_prefit_projy1_stack_1_stack_1->SetFillColor(ci);

   ci = 1543;
   color = new TColor(ci, 1, 1, 1, " ", 0);
   Background_fail_prefit_projy1_stack_1_stack_1->SetLineColor(ci);
   Background_fail_prefit_projy1_stack_1_stack_1->SetLineStyle(0);
   Background_fail_prefit_projy1_stack_1_stack_1->GetXaxis()->SetTitle("p_{T}");
   Background_fail_prefit_projy1_stack_1_stack_1->GetXaxis()->SetLabelFont(42);
   Background_fail_prefit_projy1_stack_1_stack_1->GetXaxis()->SetLabelOffset(0.007);
   Background_fail_prefit_projy1_stack_1_stack_1->GetXaxis()->SetLabelSize(0.05);
   Background_fail_prefit_projy1_stack_1_stack_1->GetXaxis()->SetTitleSize(0.08);
   Background_fail_prefit_projy1_stack_1_stack_1->GetXaxis()->SetTitleOffset(1.25);
   Background_fail_prefit_projy1_stack_1_stack_1->GetXaxis()->SetTitleFont(42);
   Background_fail_prefit_projy1_stack_1_stack_1->GetYaxis()->SetTitle("Events / bin");
   Background_fail_prefit_projy1_stack_1_stack_1->GetYaxis()->SetLabelFont(42);
   Background_fail_prefit_projy1_stack_1_stack_1->GetYaxis()->SetLabelOffset(0.007);
   Background_fail_prefit_projy1_stack_1_stack_1->GetYaxis()->SetLabelSize(0.05);
   Background_fail_prefit_projy1_stack_1_stack_1->GetYaxis()->SetTitleSize(0.08);
   Background_fail_prefit_projy1_stack_1_stack_1->GetYaxis()->SetTitleOffset(1.25);
   Background_fail_prefit_projy1_stack_1_stack_1->GetYaxis()->SetTitleFont(42);
   Background_fail_prefit_projy1_stack_1_stack_1->GetZaxis()->SetLabelFont(42);
   Background_fail_prefit_projy1_stack_1_stack_1->GetZaxis()->SetLabelOffset(0.007);
   Background_fail_prefit_projy1_stack_1_stack_1->GetZaxis()->SetLabelSize(0.05);
   Background_fail_prefit_projy1_stack_1_stack_1->GetZaxis()->SetTitleSize(0.08);
   Background_fail_prefit_projy1_stack_1_stack_1->GetZaxis()->SetTitleFont(42);
   prefit_projy1_fail_logy_stack->Add(Background_fail_prefit_projy1_stack_1_stack_1,"");
   prefit_projy1_fail_logy_stack->Draw("hist same");
   Double_t xAxis908[2] = {50, 200}; 
   
   TH1D *Signal_ppStaumI557_fail_prefit_projy1__576 = new TH1D("Signal_ppStaumI557_fail_prefit_projy1__576","HSCP signal, fail, prefit, 0.24-1.0",1, xAxis908);
   Signal_ppStaumI557_fail_prefit_projy1__576->SetBinContent(1,4.56e-05);
   Signal_ppStaumI557_fail_prefit_projy1__576->SetBinError(1,6.498974e-07);
   Signal_ppStaumI557_fail_prefit_projy1__576->SetMinimum(0.001);
   Signal_ppStaumI557_fail_prefit_projy1__576->SetEntries(4923.116);
   Signal_ppStaumI557_fail_prefit_projy1__576->SetLineColor(2);
   Signal_ppStaumI557_fail_prefit_projy1__576->SetLineStyle(0);
   Signal_ppStaumI557_fail_prefit_projy1__576->GetXaxis()->SetTitle("p_{T}");
   Signal_ppStaumI557_fail_prefit_projy1__576->GetXaxis()->SetLabelFont(42);
   Signal_ppStaumI557_fail_prefit_projy1__576->GetXaxis()->SetLabelOffset(0.007);
   Signal_ppStaumI557_fail_prefit_projy1__576->GetXaxis()->SetLabelSize(0.05);
   Signal_ppStaumI557_fail_prefit_projy1__576->GetXaxis()->SetTitleSize(0.08);
   Signal_ppStaumI557_fail_prefit_projy1__576->GetXaxis()->SetTitleOffset(1.25);
   Signal_ppStaumI557_fail_prefit_projy1__576->GetXaxis()->SetTitleFont(42);
   Signal_ppStaumI557_fail_prefit_projy1__576->GetYaxis()->SetTitle("Events / bin");
   Signal_ppStaumI557_fail_prefit_projy1__576->GetYaxis()->SetLabelFont(42);
   Signal_ppStaumI557_fail_prefit_projy1__576->GetYaxis()->SetLabelOffset(0.007);
   Signal_ppStaumI557_fail_prefit_projy1__576->GetYaxis()->SetLabelSize(0.05);
   Signal_ppStaumI557_fail_prefit_projy1__576->GetYaxis()->SetTitleSize(0.08);
   Signal_ppStaumI557_fail_prefit_projy1__576->GetYaxis()->SetTitleOffset(1.25);
   Signal_ppStaumI557_fail_prefit_projy1__576->GetYaxis()->SetTitleFont(42);
   Signal_ppStaumI557_fail_prefit_projy1__576->GetZaxis()->SetLabelFont(42);
   Signal_ppStaumI557_fail_prefit_projy1__576->GetZaxis()->SetLabelOffset(0.007);
   Signal_ppStaumI557_fail_prefit_projy1__576->GetZaxis()->SetLabelSize(0.05);
   Signal_ppStaumI557_fail_prefit_projy1__576->GetZaxis()->SetTitleSize(0.08);
   Signal_ppStaumI557_fail_prefit_projy1__576->GetZaxis()->SetTitleFont(42);
   Signal_ppStaumI557_fail_prefit_projy1__576->Draw("hist same");
   Double_t xAxis909[2] = {50, 200}; 
   
   TH1D *TotalBkg_fail_prefit_projy1__577 = new TH1D("TotalBkg_fail_prefit_projy1__577","TotalBkg, fail, prefit, 0.24-1.0",1, xAxis909);
   TotalBkg_fail_prefit_projy1__577->SetBinContent(1,6244);
   TotalBkg_fail_prefit_projy1__577->SetMinimum(0.001);
   TotalBkg_fail_prefit_projy1__577->SetEntries(6244);
   TotalBkg_fail_prefit_projy1__577->SetLineStyle(0);
   TotalBkg_fail_prefit_projy1__577->SetMarkerStyle(0);
   TotalBkg_fail_prefit_projy1__577->GetXaxis()->SetTitle("p_{T}");
   TotalBkg_fail_prefit_projy1__577->GetXaxis()->SetLabelFont(42);
   TotalBkg_fail_prefit_projy1__577->GetXaxis()->SetLabelOffset(0.007);
   TotalBkg_fail_prefit_projy1__577->GetXaxis()->SetLabelSize(0.05);
   TotalBkg_fail_prefit_projy1__577->GetXaxis()->SetTitleSize(0.08);
   TotalBkg_fail_prefit_projy1__577->GetXaxis()->SetTitleOffset(1.25);
   TotalBkg_fail_prefit_projy1__577->GetXaxis()->SetTitleFont(42);
   TotalBkg_fail_prefit_projy1__577->GetYaxis()->SetTitle("Events / bin");
   TotalBkg_fail_prefit_projy1__577->GetYaxis()->SetLabelFont(42);
   TotalBkg_fail_prefit_projy1__577->GetYaxis()->SetLabelOffset(0.007);
   TotalBkg_fail_prefit_projy1__577->GetYaxis()->SetLabelSize(0.05);
   TotalBkg_fail_prefit_projy1__577->GetYaxis()->SetTitleSize(0.08);
   TotalBkg_fail_prefit_projy1__577->GetYaxis()->SetTitleOffset(1.25);
   TotalBkg_fail_prefit_projy1__577->GetYaxis()->SetTitleFont(42);
   TotalBkg_fail_prefit_projy1__577->GetZaxis()->SetLabelFont(42);
   TotalBkg_fail_prefit_projy1__577->GetZaxis()->SetLabelOffset(0.007);
   TotalBkg_fail_prefit_projy1__577->GetZaxis()->SetLabelSize(0.05);
   TotalBkg_fail_prefit_projy1__577->GetZaxis()->SetTitleSize(0.08);
   TotalBkg_fail_prefit_projy1__577->GetZaxis()->SetTitleFont(42);
   TotalBkg_fail_prefit_projy1__577->Draw("hist same");
   Double_t xAxis910[2] = {50, 200}; 
   
   TH1D *TotalBkg_fail_prefit_projy1__578 = new TH1D("TotalBkg_fail_prefit_projy1__578","TotalBkg, fail, prefit, 0.24-1.0",1, xAxis910);
   TotalBkg_fail_prefit_projy1__578->SetBinContent(1,6244);
   TotalBkg_fail_prefit_projy1__578->SetMinimum(0.001);
   TotalBkg_fail_prefit_projy1__578->SetEntries(6244);
   TotalBkg_fail_prefit_projy1__578->SetFillColor(1);
   TotalBkg_fail_prefit_projy1__578->SetFillStyle(3354);
   TotalBkg_fail_prefit_projy1__578->SetLineStyle(0);
   TotalBkg_fail_prefit_projy1__578->SetLineWidth(0);
   TotalBkg_fail_prefit_projy1__578->SetMarkerStyle(0);
   TotalBkg_fail_prefit_projy1__578->GetXaxis()->SetTitle("p_{T}");
   TotalBkg_fail_prefit_projy1__578->GetXaxis()->SetLabelFont(42);
   TotalBkg_fail_prefit_projy1__578->GetXaxis()->SetLabelOffset(0.007);
   TotalBkg_fail_prefit_projy1__578->GetXaxis()->SetLabelSize(0.05);
   TotalBkg_fail_prefit_projy1__578->GetXaxis()->SetTitleSize(0.08);
   TotalBkg_fail_prefit_projy1__578->GetXaxis()->SetTitleOffset(1.25);
   TotalBkg_fail_prefit_projy1__578->GetXaxis()->SetTitleFont(42);
   TotalBkg_fail_prefit_projy1__578->GetYaxis()->SetTitle("Events / bin");
   TotalBkg_fail_prefit_projy1__578->GetYaxis()->SetLabelFont(42);
   TotalBkg_fail_prefit_projy1__578->GetYaxis()->SetLabelOffset(0.007);
   TotalBkg_fail_prefit_projy1__578->GetYaxis()->SetLabelSize(0.05);
   TotalBkg_fail_prefit_projy1__578->GetYaxis()->SetTitleSize(0.08);
   TotalBkg_fail_prefit_projy1__578->GetYaxis()->SetTitleOffset(1.25);
   TotalBkg_fail_prefit_projy1__578->GetYaxis()->SetTitleFont(42);
   TotalBkg_fail_prefit_projy1__578->GetZaxis()->SetLabelFont(42);
   TotalBkg_fail_prefit_projy1__578->GetZaxis()->SetLabelOffset(0.007);
   TotalBkg_fail_prefit_projy1__578->GetZaxis()->SetLabelSize(0.05);
   TotalBkg_fail_prefit_projy1__578->GetZaxis()->SetTitleSize(0.08);
   TotalBkg_fail_prefit_projy1__578->GetZaxis()->SetTitleFont(42);
   TotalBkg_fail_prefit_projy1__578->Draw("e2 same");
   Double_t xAxis911[2] = {50, 200}; 
   
   TH1D *data_obs_fail_prefit_projy1__579 = new TH1D("data_obs_fail_prefit_projy1__579","",1, xAxis911);
   data_obs_fail_prefit_projy1__579->SetBinContent(1,6244);
   data_obs_fail_prefit_projy1__579->SetBinError(1,79.01899);
   data_obs_fail_prefit_projy1__579->SetMinimum(0.001);
   data_obs_fail_prefit_projy1__579->SetMaximum(568984.5);
   data_obs_fail_prefit_projy1__579->SetEntries(6244);

   ci = TColor::GetColor("#000000");
   data_obs_fail_prefit_projy1__579->SetLineColor(ci);
   data_obs_fail_prefit_projy1__579->SetLineStyle(0);

   ci = TColor::GetColor("#000000");
   data_obs_fail_prefit_projy1__579->SetMarkerColor(ci);
   data_obs_fail_prefit_projy1__579->SetMarkerStyle(8);
   data_obs_fail_prefit_projy1__579->GetXaxis()->SetTitle("p_{T}");
   data_obs_fail_prefit_projy1__579->GetXaxis()->SetLabelFont(42);
   data_obs_fail_prefit_projy1__579->GetXaxis()->SetLabelOffset(0.05);
   data_obs_fail_prefit_projy1__579->GetXaxis()->SetLabelSize(0.07);
   data_obs_fail_prefit_projy1__579->GetXaxis()->SetTitleSize(0.09);
   data_obs_fail_prefit_projy1__579->GetXaxis()->SetTitleOffset(1.15);
   data_obs_fail_prefit_projy1__579->GetXaxis()->SetTitleFont(42);
   data_obs_fail_prefit_projy1__579->GetYaxis()->SetTitle("Events / bin");
   data_obs_fail_prefit_projy1__579->GetYaxis()->SetNdivisions(508);
   data_obs_fail_prefit_projy1__579->GetYaxis()->SetLabelFont(42);
   data_obs_fail_prefit_projy1__579->GetYaxis()->SetLabelOffset(0.007);
   data_obs_fail_prefit_projy1__579->GetYaxis()->SetLabelSize(0.07);
   data_obs_fail_prefit_projy1__579->GetYaxis()->SetTitleSize(0.09);
   data_obs_fail_prefit_projy1__579->GetYaxis()->SetTitleOffset(0.8);
   data_obs_fail_prefit_projy1__579->GetYaxis()->SetTitleFont(42);
   data_obs_fail_prefit_projy1__579->GetZaxis()->SetLabelFont(42);
   data_obs_fail_prefit_projy1__579->GetZaxis()->SetLabelOffset(0.007);
   data_obs_fail_prefit_projy1__579->GetZaxis()->SetLabelSize(0.05);
   data_obs_fail_prefit_projy1__579->GetZaxis()->SetTitleSize(0.08);
   data_obs_fail_prefit_projy1__579->GetZaxis()->SetTitleFont(42);
   data_obs_fail_prefit_projy1__579->Draw("pe X0 same");
   
   TLegend *leg = new TLegend(0.65,0.64,0.9,0.88,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(1001);
   TLegendEntry *entry=leg->AddEntry("data_obs_fail_prefit_projy1","Data","pe X0");

   ci = TColor::GetColor("#000000");
   entry->SetLineColor(ci);
   entry->SetLineWidth(1);

   ci = TColor::GetColor("#000000");
   entry->SetMarkerColor(ci);
   entry->SetMarkerStyle(8);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("TotalBkg_fail_prefit_projy1","Total bkg unc.","F");
   entry->SetFillColor(1);
   entry->SetFillStyle(3354);
   entry->SetLineColor(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("Signal_ppStau-557_fail_prefit_projy1","HSCP signal","L");
   entry->SetLineColor(2);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("Background_fail_prefit_projy1_stack_1_stack_1","Background","f");

   ci = TColor::GetColor("#ffff00");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = 1543;
   color = new TColor(ci, 1, 1, 1, " ", 0);
   entry->SetLineColor(ci);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   leg->Draw();
   Double_t xAxis912[2] = {50, 200}; 
   
   TH1D *data_obs_fail_prefit_projy1_copy__580 = new TH1D("data_obs_fail_prefit_projy1_copy__580","",1, xAxis912);
   data_obs_fail_prefit_projy1_copy__580->SetBinContent(1,6244);
   data_obs_fail_prefit_projy1_copy__580->SetBinError(1,79.01899);
   data_obs_fail_prefit_projy1_copy__580->SetMinimum(0.001);
   data_obs_fail_prefit_projy1_copy__580->SetMaximum(568984.5);
   data_obs_fail_prefit_projy1_copy__580->SetEntries(6244);
   data_obs_fail_prefit_projy1_copy__580->SetDirectory(0);

   ci = TColor::GetColor("#000000");
   data_obs_fail_prefit_projy1_copy__580->SetLineColor(ci);
   data_obs_fail_prefit_projy1_copy__580->SetLineStyle(0);

   ci = TColor::GetColor("#000000");
   data_obs_fail_prefit_projy1_copy__580->SetMarkerColor(ci);
   data_obs_fail_prefit_projy1_copy__580->SetMarkerStyle(8);
   data_obs_fail_prefit_projy1_copy__580->GetXaxis()->SetTitle("p_{T}");
   data_obs_fail_prefit_projy1_copy__580->GetXaxis()->SetLabelFont(42);
   data_obs_fail_prefit_projy1_copy__580->GetXaxis()->SetLabelOffset(0.05);
   data_obs_fail_prefit_projy1_copy__580->GetXaxis()->SetLabelSize(0.07);
   data_obs_fail_prefit_projy1_copy__580->GetXaxis()->SetTitleSize(0.09);
   data_obs_fail_prefit_projy1_copy__580->GetXaxis()->SetTitleOffset(1.15);
   data_obs_fail_prefit_projy1_copy__580->GetXaxis()->SetTitleFont(42);
   data_obs_fail_prefit_projy1_copy__580->GetYaxis()->SetTitle("Events / bin");
   data_obs_fail_prefit_projy1_copy__580->GetYaxis()->SetNdivisions(508);
   data_obs_fail_prefit_projy1_copy__580->GetYaxis()->SetLabelFont(42);
   data_obs_fail_prefit_projy1_copy__580->GetYaxis()->SetLabelOffset(0.007);
   data_obs_fail_prefit_projy1_copy__580->GetYaxis()->SetLabelSize(0.07);
   data_obs_fail_prefit_projy1_copy__580->GetYaxis()->SetTitleSize(0.09);
   data_obs_fail_prefit_projy1_copy__580->GetYaxis()->SetTitleOffset(0.8);
   data_obs_fail_prefit_projy1_copy__580->GetYaxis()->SetTitleFont(42);
   data_obs_fail_prefit_projy1_copy__580->GetZaxis()->SetLabelFont(42);
   data_obs_fail_prefit_projy1_copy__580->GetZaxis()->SetLabelOffset(0.007);
   data_obs_fail_prefit_projy1_copy__580->GetZaxis()->SetLabelSize(0.05);
   data_obs_fail_prefit_projy1_copy__580->GetZaxis()->SetTitleSize(0.08);
   data_obs_fail_prefit_projy1_copy__580->GetZaxis()->SetTitleFont(42);
   data_obs_fail_prefit_projy1_copy__580->Draw("sameaxis");
   TLatex *   tex = new TLatex(0.21,0.83,"55 < p_{T} < 200 GeV, F^{Pixels}_{i} < 0.9");
tex->SetNDC();
   tex->SetTextAlign(12);
   tex->SetTextFont(42);
   tex->SetTextSize(0.06);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.17,0.92,"CMS");
tex->SetNDC();
   tex->SetTextFont(61);
   tex->SetTextSize(0.0675);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.25,0.92,"Preliminary");
tex->SetNDC();
   tex->SetTextFont(52);
   tex->SetTextSize(0.0485);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.95,0.92,"101 fb^{-1} (13 TeV)");
tex->SetNDC();
   tex->SetTextAlign(31);
   tex->SetTextFont(42);
   tex->SetTextSize(0.07);
   tex->SetLineWidth(2);
   tex->Draw();
   data_obs_fail_prefit_projy1_main->Modified();
   plots_fit_s/base_figs/prefit_projy1_fail_logy->cd();
  
// ------------>Primitives in pad: data_obs_fail_prefit_projy1_sub
   TPad *data_obs_fail_prefit_projy1_sub = new TPad("data_obs_fail_prefit_projy1_sub", "data_obs_fail_prefit_projy1_sub",0,0,1,0.35);
   data_obs_fail_prefit_projy1_sub->Draw();
   data_obs_fail_prefit_projy1_sub->cd();
   data_obs_fail_prefit_projy1_sub->Range(17.30769,-6.023077,209.6154,2.9);
   data_obs_fail_prefit_projy1_sub->SetFillColor(0);
   data_obs_fail_prefit_projy1_sub->SetBorderMode(0);
   data_obs_fail_prefit_projy1_sub->SetBorderSize(2);
   data_obs_fail_prefit_projy1_sub->SetTickx(1);
   data_obs_fail_prefit_projy1_sub->SetTicky(1);
   data_obs_fail_prefit_projy1_sub->SetLeftMargin(0.17);
   data_obs_fail_prefit_projy1_sub->SetRightMargin(0.05);
   data_obs_fail_prefit_projy1_sub->SetTopMargin(0);
   data_obs_fail_prefit_projy1_sub->SetBottomMargin(0.35);
   data_obs_fail_prefit_projy1_sub->SetFrameFillStyle(0);
   data_obs_fail_prefit_projy1_sub->SetFrameBorderMode(0);
   data_obs_fail_prefit_projy1_sub->SetFrameFillStyle(0);
   data_obs_fail_prefit_projy1_sub->SetFrameBorderMode(0);
   Double_t xAxis913[2] = {50, 200}; 
   
   TH1D *data_obs_fail_prefit_projy1_pull__581 = new TH1D("data_obs_fail_prefit_projy1_pull__581","",1, xAxis913);
   data_obs_fail_prefit_projy1_pull__581->SetBinContent(1,-1.544859e-06);
   data_obs_fail_prefit_projy1_pull__581->SetBinError(1,79.01899);
   data_obs_fail_prefit_projy1_pull__581->SetMinimum(-2.9);
   data_obs_fail_prefit_projy1_pull__581->SetMaximum(2.9);
   data_obs_fail_prefit_projy1_pull__581->SetEntries(1.000122);
   data_obs_fail_prefit_projy1_pull__581->SetStats(0);

   ci = TColor::GetColor("#0000ff");
   data_obs_fail_prefit_projy1_pull__581->SetFillColor(ci);

   ci = TColor::GetColor("#000000");
   data_obs_fail_prefit_projy1_pull__581->SetLineColor(ci);
   data_obs_fail_prefit_projy1_pull__581->SetLineStyle(0);

   ci = TColor::GetColor("#000000");
   data_obs_fail_prefit_projy1_pull__581->SetMarkerColor(ci);
   data_obs_fail_prefit_projy1_pull__581->SetMarkerStyle(8);
   data_obs_fail_prefit_projy1_pull__581->GetXaxis()->SetTitle("p_{T}");
   data_obs_fail_prefit_projy1_pull__581->GetXaxis()->SetLabelFont(42);
   data_obs_fail_prefit_projy1_pull__581->GetXaxis()->SetLabelOffset(0.05);
   data_obs_fail_prefit_projy1_pull__581->GetXaxis()->SetLabelSize(0.13);
   data_obs_fail_prefit_projy1_pull__581->GetXaxis()->SetTitleSize(0.15);
   data_obs_fail_prefit_projy1_pull__581->GetXaxis()->SetTitleOffset(1.15);
   data_obs_fail_prefit_projy1_pull__581->GetXaxis()->SetTitleFont(42);
   data_obs_fail_prefit_projy1_pull__581->GetYaxis()->SetTitle("(Data-Bkg)/#sigma");
   data_obs_fail_prefit_projy1_pull__581->GetYaxis()->SetNdivisions(306);
   data_obs_fail_prefit_projy1_pull__581->GetYaxis()->SetLabelFont(42);
   data_obs_fail_prefit_projy1_pull__581->GetYaxis()->SetLabelOffset(0.007);
   data_obs_fail_prefit_projy1_pull__581->GetYaxis()->SetLabelSize(0.13);
   data_obs_fail_prefit_projy1_pull__581->GetYaxis()->SetTitleSize(0.12);
   data_obs_fail_prefit_projy1_pull__581->GetYaxis()->SetTitleOffset(0.4);
   data_obs_fail_prefit_projy1_pull__581->GetYaxis()->SetTitleFont(42);
   data_obs_fail_prefit_projy1_pull__581->GetZaxis()->SetLabelFont(42);
   data_obs_fail_prefit_projy1_pull__581->GetZaxis()->SetLabelOffset(0.007);
   data_obs_fail_prefit_projy1_pull__581->GetZaxis()->SetLabelSize(0.05);
   data_obs_fail_prefit_projy1_pull__581->GetZaxis()->SetTitleSize(0.08);
   data_obs_fail_prefit_projy1_pull__581->GetZaxis()->SetTitleFont(42);
   data_obs_fail_prefit_projy1_pull__581->Draw("hist");
   data_obs_fail_prefit_projy1_sub->Modified();
   plots_fit_s/base_figs/prefit_projy1_fail_logy->cd();
   plots_fit_s/base_figs/prefit_projy1_fail_logy->Modified();
   plots_fit_s/base_figs/prefit_projy1_fail_logy->cd();
   plots_fit_s/base_figs/prefit_projy1_fail_logy->SetSelected(plots_fit_s/base_figs/prefit_projy1_fail_logy);
}
