void prefit_projy2_pass_logy()
{
//=========Macro generated from canvas: plots_fit_s/base_figs/prefit_projy2_pass_logy/plots_fit_s/base_figs/prefit_projy2_pass_logy
//=========  (Fri Jan 12 21:00:35 2024) by ROOT version 6.14/09
   TCanvas *plots_fit_s/base_figs/prefit_projy2_pass_logy = new TCanvas("plots_fit_s/base_figs/prefit_projy2_pass_logy", "plots_fit_s/base_figs/prefit_projy2_pass_logy",0,0,800,700);
   gStyle->SetOptFit(1);
   gStyle->SetOptStat(0);
   plots_fit_s/base_figs/prefit_projy2_pass_logy->SetHighLightColor(2);
   plots_fit_s/base_figs/prefit_projy2_pass_logy->Range(0,0,1,1);
   plots_fit_s/base_figs/prefit_projy2_pass_logy->SetFillColor(0);
   plots_fit_s/base_figs/prefit_projy2_pass_logy->SetBorderMode(0);
   plots_fit_s/base_figs/prefit_projy2_pass_logy->SetBorderSize(2);
   plots_fit_s/base_figs/prefit_projy2_pass_logy->SetTickx(1);
   plots_fit_s/base_figs/prefit_projy2_pass_logy->SetTicky(1);
   plots_fit_s/base_figs/prefit_projy2_pass_logy->SetLeftMargin(0.16);
   plots_fit_s/base_figs/prefit_projy2_pass_logy->SetRightMargin(0);
   plots_fit_s/base_figs/prefit_projy2_pass_logy->SetTopMargin(0);
   plots_fit_s/base_figs/prefit_projy2_pass_logy->SetBottomMargin(0);
   plots_fit_s/base_figs/prefit_projy2_pass_logy->SetFrameFillStyle(0);
   plots_fit_s/base_figs/prefit_projy2_pass_logy->SetFrameBorderMode(0);
  
// ------------>Primitives in pad: data_obs_pass_prefit_projy2_main
   TPad *data_obs_pass_prefit_projy2_main = new TPad("data_obs_pass_prefit_projy2_main", "data_obs_pass_prefit_projy2_main",0,0.35,1,1);
   data_obs_pass_prefit_projy2_main->Draw();
   data_obs_pass_prefit_projy2_main->cd();
   data_obs_pass_prefit_projy2_main->Range(17.30769,-2.139535,209.6154,1.348837);
   data_obs_pass_prefit_projy2_main->SetFillColor(0);
   data_obs_pass_prefit_projy2_main->SetBorderMode(0);
   data_obs_pass_prefit_projy2_main->SetBorderSize(2);
   data_obs_pass_prefit_projy2_main->SetLogy();
   data_obs_pass_prefit_projy2_main->SetTickx(1);
   data_obs_pass_prefit_projy2_main->SetTicky(1);
   data_obs_pass_prefit_projy2_main->SetLeftMargin(0.17);
   data_obs_pass_prefit_projy2_main->SetRightMargin(0.05);
   data_obs_pass_prefit_projy2_main->SetBottomMargin(0.04);
   data_obs_pass_prefit_projy2_main->SetFrameFillStyle(0);
   data_obs_pass_prefit_projy2_main->SetFrameBorderMode(0);
   data_obs_pass_prefit_projy2_main->SetFrameFillStyle(0);
   data_obs_pass_prefit_projy2_main->SetFrameBorderMode(0);
   Double_t xAxis1046[2] = {50, 200}; 
   
   TH1D *data_obs_pass_prefit_projy2__666 = new TH1D("data_obs_pass_prefit_projy2__666","",1, xAxis1046);
   data_obs_pass_prefit_projy2__666->SetMinimum(0.001);
   data_obs_pass_prefit_projy2__666->SetMaximum(0);

   Int_t ci;      // for color index setting
   TColor *color; // for color definition with alpha
   ci = TColor::GetColor("#000000");
   data_obs_pass_prefit_projy2__666->SetLineColor(ci);
   data_obs_pass_prefit_projy2__666->SetLineStyle(0);

   ci = TColor::GetColor("#000000");
   data_obs_pass_prefit_projy2__666->SetMarkerColor(ci);
   data_obs_pass_prefit_projy2__666->SetMarkerStyle(8);
   data_obs_pass_prefit_projy2__666->GetXaxis()->SetTitle("p_{T}");
   data_obs_pass_prefit_projy2__666->GetXaxis()->SetLabelFont(42);
   data_obs_pass_prefit_projy2__666->GetXaxis()->SetLabelOffset(0.05);
   data_obs_pass_prefit_projy2__666->GetXaxis()->SetLabelSize(0.07);
   data_obs_pass_prefit_projy2__666->GetXaxis()->SetTitleSize(0.09);
   data_obs_pass_prefit_projy2__666->GetXaxis()->SetTitleOffset(1.15);
   data_obs_pass_prefit_projy2__666->GetXaxis()->SetTitleFont(42);
   data_obs_pass_prefit_projy2__666->GetYaxis()->SetTitle("Events / bin");
   data_obs_pass_prefit_projy2__666->GetYaxis()->SetNdivisions(508);
   data_obs_pass_prefit_projy2__666->GetYaxis()->SetLabelFont(42);
   data_obs_pass_prefit_projy2__666->GetYaxis()->SetLabelOffset(0.007);
   data_obs_pass_prefit_projy2__666->GetYaxis()->SetLabelSize(0.07);
   data_obs_pass_prefit_projy2__666->GetYaxis()->SetTitleSize(0.09);
   data_obs_pass_prefit_projy2__666->GetYaxis()->SetTitleOffset(0.8);
   data_obs_pass_prefit_projy2__666->GetYaxis()->SetTitleFont(42);
   data_obs_pass_prefit_projy2__666->GetZaxis()->SetLabelFont(42);
   data_obs_pass_prefit_projy2__666->GetZaxis()->SetLabelOffset(0.007);
   data_obs_pass_prefit_projy2__666->GetZaxis()->SetLabelSize(0.05);
   data_obs_pass_prefit_projy2__666->GetZaxis()->SetTitleSize(0.08);
   data_obs_pass_prefit_projy2__666->GetZaxis()->SetTitleFont(42);
   data_obs_pass_prefit_projy2__666->Draw("pe X0");
   
   THStack *prefit_projy2_pass_logy_stack = new THStack();
   prefit_projy2_pass_logy_stack->SetName("prefit_projy2_pass_logy_stack");
   prefit_projy2_pass_logy_stack->SetTitle("prefit_projy2_pass_logy_stack");
   prefit_projy2_pass_logy_stack->SetMinimum(0.001);
   Double_t xAxis1047[2] = {50, 200}; 
   
   TH1F *prefit_projy2_pass_logy_stack_stack_191 = new TH1F("prefit_projy2_pass_logy_stack_stack_191","prefit_projy2_pass_logy_stack",1, xAxis1047);
   prefit_projy2_pass_logy_stack_stack_191->SetMinimum(-0);
   prefit_projy2_pass_logy_stack_stack_191->SetMaximum(-nan);
   prefit_projy2_pass_logy_stack_stack_191->SetDirectory(0);
   prefit_projy2_pass_logy_stack_stack_191->SetStats(0);
   prefit_projy2_pass_logy_stack_stack_191->SetLineStyle(0);
   prefit_projy2_pass_logy_stack_stack_191->GetXaxis()->SetLabelFont(42);
   prefit_projy2_pass_logy_stack_stack_191->GetXaxis()->SetLabelOffset(0.007);
   prefit_projy2_pass_logy_stack_stack_191->GetXaxis()->SetLabelSize(0.05);
   prefit_projy2_pass_logy_stack_stack_191->GetXaxis()->SetTitleSize(0.08);
   prefit_projy2_pass_logy_stack_stack_191->GetXaxis()->SetTitleOffset(0.9);
   prefit_projy2_pass_logy_stack_stack_191->GetXaxis()->SetTitleFont(42);
   prefit_projy2_pass_logy_stack_stack_191->GetYaxis()->SetNdivisions(508);
   prefit_projy2_pass_logy_stack_stack_191->GetYaxis()->SetLabelFont(42);
   prefit_projy2_pass_logy_stack_stack_191->GetYaxis()->SetLabelOffset(0.007);
   prefit_projy2_pass_logy_stack_stack_191->GetYaxis()->SetLabelSize(0.05);
   prefit_projy2_pass_logy_stack_stack_191->GetYaxis()->SetTitleSize(0.08);
   prefit_projy2_pass_logy_stack_stack_191->GetYaxis()->SetTitleOffset(1.25);
   prefit_projy2_pass_logy_stack_stack_191->GetYaxis()->SetTitleFont(42);
   prefit_projy2_pass_logy_stack_stack_191->GetZaxis()->SetLabelFont(42);
   prefit_projy2_pass_logy_stack_stack_191->GetZaxis()->SetLabelOffset(0.007);
   prefit_projy2_pass_logy_stack_stack_191->GetZaxis()->SetLabelSize(0.05);
   prefit_projy2_pass_logy_stack_stack_191->GetZaxis()->SetTitleSize(0.08);
   prefit_projy2_pass_logy_stack_stack_191->GetZaxis()->SetTitleFont(42);
   prefit_projy2_pass_logy_stack->SetHistogram(prefit_projy2_pass_logy_stack_stack_191);
   
   Double_t xAxis1048[2] = {50, 200}; 
   
   TH1D *Background_0x0_pass_prefit_projy2_stack_1 = new TH1D("Background_0x0_pass_prefit_projy2_stack_1","Background, pass, prefit, 1.0-1.0",1, xAxis1048);
   Background_0x0_pass_prefit_projy2_stack_1->SetMinimum(0.001);

   ci = TColor::GetColor("#ffff00");
   Background_0x0_pass_prefit_projy2_stack_1->SetFillColor(ci);

   ci = 1556;
   color = new TColor(ci, 1, 1, 1, " ", 0);
   Background_0x0_pass_prefit_projy2_stack_1->SetLineColor(ci);
   Background_0x0_pass_prefit_projy2_stack_1->SetLineStyle(0);
   Background_0x0_pass_prefit_projy2_stack_1->GetXaxis()->SetTitle("p_{T}");
   Background_0x0_pass_prefit_projy2_stack_1->GetXaxis()->SetLabelFont(42);
   Background_0x0_pass_prefit_projy2_stack_1->GetXaxis()->SetLabelOffset(0.007);
   Background_0x0_pass_prefit_projy2_stack_1->GetXaxis()->SetLabelSize(0.05);
   Background_0x0_pass_prefit_projy2_stack_1->GetXaxis()->SetTitleSize(0.08);
   Background_0x0_pass_prefit_projy2_stack_1->GetXaxis()->SetTitleOffset(1.25);
   Background_0x0_pass_prefit_projy2_stack_1->GetXaxis()->SetTitleFont(42);
   Background_0x0_pass_prefit_projy2_stack_1->GetYaxis()->SetTitle("Events / bin");
   Background_0x0_pass_prefit_projy2_stack_1->GetYaxis()->SetLabelFont(42);
   Background_0x0_pass_prefit_projy2_stack_1->GetYaxis()->SetLabelOffset(0.007);
   Background_0x0_pass_prefit_projy2_stack_1->GetYaxis()->SetLabelSize(0.05);
   Background_0x0_pass_prefit_projy2_stack_1->GetYaxis()->SetTitleSize(0.08);
   Background_0x0_pass_prefit_projy2_stack_1->GetYaxis()->SetTitleOffset(1.25);
   Background_0x0_pass_prefit_projy2_stack_1->GetYaxis()->SetTitleFont(42);
   Background_0x0_pass_prefit_projy2_stack_1->GetZaxis()->SetLabelFont(42);
   Background_0x0_pass_prefit_projy2_stack_1->GetZaxis()->SetLabelOffset(0.007);
   Background_0x0_pass_prefit_projy2_stack_1->GetZaxis()->SetLabelSize(0.05);
   Background_0x0_pass_prefit_projy2_stack_1->GetZaxis()->SetTitleSize(0.08);
   Background_0x0_pass_prefit_projy2_stack_1->GetZaxis()->SetTitleFont(42);
   prefit_projy2_pass_logy_stack->Add(Background_0x0_pass_prefit_projy2_stack_1,"");
   prefit_projy2_pass_logy_stack->Draw("hist same");
   
   prefit_projy2_pass_logy_stack = new THStack();
   prefit_projy2_pass_logy_stack->SetName("prefit_projy2_pass_logy_stack");
   prefit_projy2_pass_logy_stack->SetTitle("prefit_projy2_pass_logy_stack");
   prefit_projy2_pass_logy_stack->SetMinimum(0.001);
   Double_t xAxis1049[2] = {50, 200}; 
   
   TH1F *prefit_projy2_pass_logy_stack_stack_191_stack_192 = new TH1F("prefit_projy2_pass_logy_stack_stack_191_stack_192","prefit_projy2_pass_logy_stack",1, xAxis1049);
   prefit_projy2_pass_logy_stack_stack_191_stack_192->SetMinimum(-0);
   prefit_projy2_pass_logy_stack_stack_191_stack_192->SetMaximum(-nan);
   prefit_projy2_pass_logy_stack_stack_191_stack_192->SetDirectory(0);
   prefit_projy2_pass_logy_stack_stack_191_stack_192->SetStats(0);
   prefit_projy2_pass_logy_stack_stack_191_stack_192->SetLineStyle(0);
   prefit_projy2_pass_logy_stack_stack_191_stack_192->GetXaxis()->SetLabelFont(42);
   prefit_projy2_pass_logy_stack_stack_191_stack_192->GetXaxis()->SetLabelOffset(0.007);
   prefit_projy2_pass_logy_stack_stack_191_stack_192->GetXaxis()->SetLabelSize(0.05);
   prefit_projy2_pass_logy_stack_stack_191_stack_192->GetXaxis()->SetTitleSize(0.08);
   prefit_projy2_pass_logy_stack_stack_191_stack_192->GetXaxis()->SetTitleOffset(0.9);
   prefit_projy2_pass_logy_stack_stack_191_stack_192->GetXaxis()->SetTitleFont(42);
   prefit_projy2_pass_logy_stack_stack_191_stack_192->GetYaxis()->SetNdivisions(508);
   prefit_projy2_pass_logy_stack_stack_191_stack_192->GetYaxis()->SetLabelFont(42);
   prefit_projy2_pass_logy_stack_stack_191_stack_192->GetYaxis()->SetLabelOffset(0.007);
   prefit_projy2_pass_logy_stack_stack_191_stack_192->GetYaxis()->SetLabelSize(0.05);
   prefit_projy2_pass_logy_stack_stack_191_stack_192->GetYaxis()->SetTitleSize(0.08);
   prefit_projy2_pass_logy_stack_stack_191_stack_192->GetYaxis()->SetTitleOffset(1.25);
   prefit_projy2_pass_logy_stack_stack_191_stack_192->GetYaxis()->SetTitleFont(42);
   prefit_projy2_pass_logy_stack_stack_191_stack_192->GetZaxis()->SetLabelFont(42);
   prefit_projy2_pass_logy_stack_stack_191_stack_192->GetZaxis()->SetLabelOffset(0.007);
   prefit_projy2_pass_logy_stack_stack_191_stack_192->GetZaxis()->SetLabelSize(0.05);
   prefit_projy2_pass_logy_stack_stack_191_stack_192->GetZaxis()->SetTitleSize(0.08);
   prefit_projy2_pass_logy_stack_stack_191_stack_192->GetZaxis()->SetTitleFont(42);
   prefit_projy2_pass_logy_stack->SetHistogram(prefit_projy2_pass_logy_stack_stack_191_stack_192);
   
   Double_t xAxis1050[2] = {50, 200}; 
   
   TH1D *Background_0x0_pass_prefit_projy2_stack_1_stack_1 = new TH1D("Background_0x0_pass_prefit_projy2_stack_1_stack_1","Background, pass, prefit, 1.0-1.0",1, xAxis1050);
   Background_0x0_pass_prefit_projy2_stack_1_stack_1->SetMinimum(0.001);

   ci = TColor::GetColor("#ffff00");
   Background_0x0_pass_prefit_projy2_stack_1_stack_1->SetFillColor(ci);

   ci = 1556;
   color = new TColor(ci, 1, 1, 1, " ", 0);
   Background_0x0_pass_prefit_projy2_stack_1_stack_1->SetLineColor(ci);
   Background_0x0_pass_prefit_projy2_stack_1_stack_1->SetLineStyle(0);
   Background_0x0_pass_prefit_projy2_stack_1_stack_1->GetXaxis()->SetTitle("p_{T}");
   Background_0x0_pass_prefit_projy2_stack_1_stack_1->GetXaxis()->SetLabelFont(42);
   Background_0x0_pass_prefit_projy2_stack_1_stack_1->GetXaxis()->SetLabelOffset(0.007);
   Background_0x0_pass_prefit_projy2_stack_1_stack_1->GetXaxis()->SetLabelSize(0.05);
   Background_0x0_pass_prefit_projy2_stack_1_stack_1->GetXaxis()->SetTitleSize(0.08);
   Background_0x0_pass_prefit_projy2_stack_1_stack_1->GetXaxis()->SetTitleOffset(1.25);
   Background_0x0_pass_prefit_projy2_stack_1_stack_1->GetXaxis()->SetTitleFont(42);
   Background_0x0_pass_prefit_projy2_stack_1_stack_1->GetYaxis()->SetTitle("Events / bin");
   Background_0x0_pass_prefit_projy2_stack_1_stack_1->GetYaxis()->SetLabelFont(42);
   Background_0x0_pass_prefit_projy2_stack_1_stack_1->GetYaxis()->SetLabelOffset(0.007);
   Background_0x0_pass_prefit_projy2_stack_1_stack_1->GetYaxis()->SetLabelSize(0.05);
   Background_0x0_pass_prefit_projy2_stack_1_stack_1->GetYaxis()->SetTitleSize(0.08);
   Background_0x0_pass_prefit_projy2_stack_1_stack_1->GetYaxis()->SetTitleOffset(1.25);
   Background_0x0_pass_prefit_projy2_stack_1_stack_1->GetYaxis()->SetTitleFont(42);
   Background_0x0_pass_prefit_projy2_stack_1_stack_1->GetZaxis()->SetLabelFont(42);
   Background_0x0_pass_prefit_projy2_stack_1_stack_1->GetZaxis()->SetLabelOffset(0.007);
   Background_0x0_pass_prefit_projy2_stack_1_stack_1->GetZaxis()->SetLabelSize(0.05);
   Background_0x0_pass_prefit_projy2_stack_1_stack_1->GetZaxis()->SetTitleSize(0.08);
   Background_0x0_pass_prefit_projy2_stack_1_stack_1->GetZaxis()->SetTitleFont(42);
   prefit_projy2_pass_logy_stack->Add(Background_0x0_pass_prefit_projy2_stack_1_stack_1,"");
   prefit_projy2_pass_logy_stack->Draw("hist same");
   Double_t xAxis1051[2] = {50, 200}; 
   
   TH1D *Signal_ppStaumI557_pass_prefit_projy2__667 = new TH1D("Signal_ppStaumI557_pass_prefit_projy2__667","HSCP signal, pass, prefit, 1.0-1.0",1, xAxis1051);
   Signal_ppStaumI557_pass_prefit_projy2__667->SetMinimum(0.001);
   Signal_ppStaumI557_pass_prefit_projy2__667->SetLineColor(2);
   Signal_ppStaumI557_pass_prefit_projy2__667->SetLineStyle(0);
   Signal_ppStaumI557_pass_prefit_projy2__667->GetXaxis()->SetTitle("p_{T}");
   Signal_ppStaumI557_pass_prefit_projy2__667->GetXaxis()->SetLabelFont(42);
   Signal_ppStaumI557_pass_prefit_projy2__667->GetXaxis()->SetLabelOffset(0.007);
   Signal_ppStaumI557_pass_prefit_projy2__667->GetXaxis()->SetLabelSize(0.05);
   Signal_ppStaumI557_pass_prefit_projy2__667->GetXaxis()->SetTitleSize(0.08);
   Signal_ppStaumI557_pass_prefit_projy2__667->GetXaxis()->SetTitleOffset(1.25);
   Signal_ppStaumI557_pass_prefit_projy2__667->GetXaxis()->SetTitleFont(42);
   Signal_ppStaumI557_pass_prefit_projy2__667->GetYaxis()->SetTitle("Events / bin");
   Signal_ppStaumI557_pass_prefit_projy2__667->GetYaxis()->SetLabelFont(42);
   Signal_ppStaumI557_pass_prefit_projy2__667->GetYaxis()->SetLabelOffset(0.007);
   Signal_ppStaumI557_pass_prefit_projy2__667->GetYaxis()->SetLabelSize(0.05);
   Signal_ppStaumI557_pass_prefit_projy2__667->GetYaxis()->SetTitleSize(0.08);
   Signal_ppStaumI557_pass_prefit_projy2__667->GetYaxis()->SetTitleOffset(1.25);
   Signal_ppStaumI557_pass_prefit_projy2__667->GetYaxis()->SetTitleFont(42);
   Signal_ppStaumI557_pass_prefit_projy2__667->GetZaxis()->SetLabelFont(42);
   Signal_ppStaumI557_pass_prefit_projy2__667->GetZaxis()->SetLabelOffset(0.007);
   Signal_ppStaumI557_pass_prefit_projy2__667->GetZaxis()->SetLabelSize(0.05);
   Signal_ppStaumI557_pass_prefit_projy2__667->GetZaxis()->SetTitleSize(0.08);
   Signal_ppStaumI557_pass_prefit_projy2__667->GetZaxis()->SetTitleFont(42);
   Signal_ppStaumI557_pass_prefit_projy2__667->Draw("hist same");
   Double_t xAxis1052[2] = {50, 200}; 
   
   TH1D *TotalBkg_pass_prefit_projy2__668 = new TH1D("TotalBkg_pass_prefit_projy2__668","TotalBkg, pass, prefit, 1.0-1.0",1, xAxis1052);
   TotalBkg_pass_prefit_projy2__668->SetMinimum(0.001);
   TotalBkg_pass_prefit_projy2__668->SetLineStyle(0);
   TotalBkg_pass_prefit_projy2__668->SetMarkerStyle(0);
   TotalBkg_pass_prefit_projy2__668->GetXaxis()->SetTitle("p_{T}");
   TotalBkg_pass_prefit_projy2__668->GetXaxis()->SetLabelFont(42);
   TotalBkg_pass_prefit_projy2__668->GetXaxis()->SetLabelOffset(0.007);
   TotalBkg_pass_prefit_projy2__668->GetXaxis()->SetLabelSize(0.05);
   TotalBkg_pass_prefit_projy2__668->GetXaxis()->SetTitleSize(0.08);
   TotalBkg_pass_prefit_projy2__668->GetXaxis()->SetTitleOffset(1.25);
   TotalBkg_pass_prefit_projy2__668->GetXaxis()->SetTitleFont(42);
   TotalBkg_pass_prefit_projy2__668->GetYaxis()->SetTitle("Events / bin");
   TotalBkg_pass_prefit_projy2__668->GetYaxis()->SetLabelFont(42);
   TotalBkg_pass_prefit_projy2__668->GetYaxis()->SetLabelOffset(0.007);
   TotalBkg_pass_prefit_projy2__668->GetYaxis()->SetLabelSize(0.05);
   TotalBkg_pass_prefit_projy2__668->GetYaxis()->SetTitleSize(0.08);
   TotalBkg_pass_prefit_projy2__668->GetYaxis()->SetTitleOffset(1.25);
   TotalBkg_pass_prefit_projy2__668->GetYaxis()->SetTitleFont(42);
   TotalBkg_pass_prefit_projy2__668->GetZaxis()->SetLabelFont(42);
   TotalBkg_pass_prefit_projy2__668->GetZaxis()->SetLabelOffset(0.007);
   TotalBkg_pass_prefit_projy2__668->GetZaxis()->SetLabelSize(0.05);
   TotalBkg_pass_prefit_projy2__668->GetZaxis()->SetTitleSize(0.08);
   TotalBkg_pass_prefit_projy2__668->GetZaxis()->SetTitleFont(42);
   TotalBkg_pass_prefit_projy2__668->Draw("hist same");
   Double_t xAxis1053[2] = {50, 200}; 
   
   TH1D *TotalBkg_pass_prefit_projy2__669 = new TH1D("TotalBkg_pass_prefit_projy2__669","TotalBkg, pass, prefit, 1.0-1.0",1, xAxis1053);
   TotalBkg_pass_prefit_projy2__669->SetMinimum(0.001);
   TotalBkg_pass_prefit_projy2__669->SetFillColor(1);
   TotalBkg_pass_prefit_projy2__669->SetFillStyle(3354);
   TotalBkg_pass_prefit_projy2__669->SetLineStyle(0);
   TotalBkg_pass_prefit_projy2__669->SetLineWidth(0);
   TotalBkg_pass_prefit_projy2__669->SetMarkerStyle(0);
   TotalBkg_pass_prefit_projy2__669->GetXaxis()->SetTitle("p_{T}");
   TotalBkg_pass_prefit_projy2__669->GetXaxis()->SetLabelFont(42);
   TotalBkg_pass_prefit_projy2__669->GetXaxis()->SetLabelOffset(0.007);
   TotalBkg_pass_prefit_projy2__669->GetXaxis()->SetLabelSize(0.05);
   TotalBkg_pass_prefit_projy2__669->GetXaxis()->SetTitleSize(0.08);
   TotalBkg_pass_prefit_projy2__669->GetXaxis()->SetTitleOffset(1.25);
   TotalBkg_pass_prefit_projy2__669->GetXaxis()->SetTitleFont(42);
   TotalBkg_pass_prefit_projy2__669->GetYaxis()->SetTitle("Events / bin");
   TotalBkg_pass_prefit_projy2__669->GetYaxis()->SetLabelFont(42);
   TotalBkg_pass_prefit_projy2__669->GetYaxis()->SetLabelOffset(0.007);
   TotalBkg_pass_prefit_projy2__669->GetYaxis()->SetLabelSize(0.05);
   TotalBkg_pass_prefit_projy2__669->GetYaxis()->SetTitleSize(0.08);
   TotalBkg_pass_prefit_projy2__669->GetYaxis()->SetTitleOffset(1.25);
   TotalBkg_pass_prefit_projy2__669->GetYaxis()->SetTitleFont(42);
   TotalBkg_pass_prefit_projy2__669->GetZaxis()->SetLabelFont(42);
   TotalBkg_pass_prefit_projy2__669->GetZaxis()->SetLabelOffset(0.007);
   TotalBkg_pass_prefit_projy2__669->GetZaxis()->SetLabelSize(0.05);
   TotalBkg_pass_prefit_projy2__669->GetZaxis()->SetTitleSize(0.08);
   TotalBkg_pass_prefit_projy2__669->GetZaxis()->SetTitleFont(42);
   TotalBkg_pass_prefit_projy2__669->Draw("e2 same");
   Double_t xAxis1054[2] = {50, 200}; 
   
   TH1D *data_obs_pass_prefit_projy2__670 = new TH1D("data_obs_pass_prefit_projy2__670","",1, xAxis1054);
   data_obs_pass_prefit_projy2__670->SetMinimum(0.001);
   data_obs_pass_prefit_projy2__670->SetMaximum(0);

   ci = TColor::GetColor("#000000");
   data_obs_pass_prefit_projy2__670->SetLineColor(ci);
   data_obs_pass_prefit_projy2__670->SetLineStyle(0);

   ci = TColor::GetColor("#000000");
   data_obs_pass_prefit_projy2__670->SetMarkerColor(ci);
   data_obs_pass_prefit_projy2__670->SetMarkerStyle(8);
   data_obs_pass_prefit_projy2__670->GetXaxis()->SetTitle("p_{T}");
   data_obs_pass_prefit_projy2__670->GetXaxis()->SetLabelFont(42);
   data_obs_pass_prefit_projy2__670->GetXaxis()->SetLabelOffset(0.05);
   data_obs_pass_prefit_projy2__670->GetXaxis()->SetLabelSize(0.07);
   data_obs_pass_prefit_projy2__670->GetXaxis()->SetTitleSize(0.09);
   data_obs_pass_prefit_projy2__670->GetXaxis()->SetTitleOffset(1.15);
   data_obs_pass_prefit_projy2__670->GetXaxis()->SetTitleFont(42);
   data_obs_pass_prefit_projy2__670->GetYaxis()->SetTitle("Events / bin");
   data_obs_pass_prefit_projy2__670->GetYaxis()->SetNdivisions(508);
   data_obs_pass_prefit_projy2__670->GetYaxis()->SetLabelFont(42);
   data_obs_pass_prefit_projy2__670->GetYaxis()->SetLabelOffset(0.007);
   data_obs_pass_prefit_projy2__670->GetYaxis()->SetLabelSize(0.07);
   data_obs_pass_prefit_projy2__670->GetYaxis()->SetTitleSize(0.09);
   data_obs_pass_prefit_projy2__670->GetYaxis()->SetTitleOffset(0.8);
   data_obs_pass_prefit_projy2__670->GetYaxis()->SetTitleFont(42);
   data_obs_pass_prefit_projy2__670->GetZaxis()->SetLabelFont(42);
   data_obs_pass_prefit_projy2__670->GetZaxis()->SetLabelOffset(0.007);
   data_obs_pass_prefit_projy2__670->GetZaxis()->SetLabelSize(0.05);
   data_obs_pass_prefit_projy2__670->GetZaxis()->SetTitleSize(0.08);
   data_obs_pass_prefit_projy2__670->GetZaxis()->SetTitleFont(42);
   data_obs_pass_prefit_projy2__670->Draw("pe X0 same");
   
   TLegend *leg = new TLegend(0.65,0.64,0.9,0.88,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(1001);
   TLegendEntry *entry=leg->AddEntry("data_obs_pass_prefit_projy2","Data","pe X0");

   ci = TColor::GetColor("#000000");
   entry->SetLineColor(ci);
   entry->SetLineWidth(1);

   ci = TColor::GetColor("#000000");
   entry->SetMarkerColor(ci);
   entry->SetMarkerStyle(8);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("TotalBkg_pass_prefit_projy2","Total bkg unc.","F");
   entry->SetFillColor(1);
   entry->SetFillStyle(3354);
   entry->SetLineColor(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("Signal_ppStau-557_pass_prefit_projy2","HSCP signal","L");
   entry->SetLineColor(2);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("Background_0x0_pass_prefit_projy2_stack_1_stack_1","Background","f");

   ci = TColor::GetColor("#ffff00");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = 1556;
   color = new TColor(ci, 1, 1, 1, " ", 0);
   entry->SetLineColor(ci);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   leg->Draw();
   Double_t xAxis1055[2] = {50, 200}; 
   
   TH1D *data_obs_pass_prefit_projy2_copy__671 = new TH1D("data_obs_pass_prefit_projy2_copy__671","",1, xAxis1055);
   data_obs_pass_prefit_projy2_copy__671->SetMinimum(0.001);
   data_obs_pass_prefit_projy2_copy__671->SetMaximum(0);
   data_obs_pass_prefit_projy2_copy__671->SetDirectory(0);

   ci = TColor::GetColor("#000000");
   data_obs_pass_prefit_projy2_copy__671->SetLineColor(ci);
   data_obs_pass_prefit_projy2_copy__671->SetLineStyle(0);

   ci = TColor::GetColor("#000000");
   data_obs_pass_prefit_projy2_copy__671->SetMarkerColor(ci);
   data_obs_pass_prefit_projy2_copy__671->SetMarkerStyle(8);
   data_obs_pass_prefit_projy2_copy__671->GetXaxis()->SetTitle("p_{T}");
   data_obs_pass_prefit_projy2_copy__671->GetXaxis()->SetLabelFont(42);
   data_obs_pass_prefit_projy2_copy__671->GetXaxis()->SetLabelOffset(0.05);
   data_obs_pass_prefit_projy2_copy__671->GetXaxis()->SetLabelSize(0.07);
   data_obs_pass_prefit_projy2_copy__671->GetXaxis()->SetTitleSize(0.09);
   data_obs_pass_prefit_projy2_copy__671->GetXaxis()->SetTitleOffset(1.15);
   data_obs_pass_prefit_projy2_copy__671->GetXaxis()->SetTitleFont(42);
   data_obs_pass_prefit_projy2_copy__671->GetYaxis()->SetTitle("Events / bin");
   data_obs_pass_prefit_projy2_copy__671->GetYaxis()->SetNdivisions(508);
   data_obs_pass_prefit_projy2_copy__671->GetYaxis()->SetLabelFont(42);
   data_obs_pass_prefit_projy2_copy__671->GetYaxis()->SetLabelOffset(0.007);
   data_obs_pass_prefit_projy2_copy__671->GetYaxis()->SetLabelSize(0.07);
   data_obs_pass_prefit_projy2_copy__671->GetYaxis()->SetTitleSize(0.09);
   data_obs_pass_prefit_projy2_copy__671->GetYaxis()->SetTitleOffset(0.8);
   data_obs_pass_prefit_projy2_copy__671->GetYaxis()->SetTitleFont(42);
   data_obs_pass_prefit_projy2_copy__671->GetZaxis()->SetLabelFont(42);
   data_obs_pass_prefit_projy2_copy__671->GetZaxis()->SetLabelOffset(0.007);
   data_obs_pass_prefit_projy2_copy__671->GetZaxis()->SetLabelSize(0.05);
   data_obs_pass_prefit_projy2_copy__671->GetZaxis()->SetTitleSize(0.08);
   data_obs_pass_prefit_projy2_copy__671->GetZaxis()->SetTitleFont(42);
   data_obs_pass_prefit_projy2_copy__671->Draw("sameaxis");
   TLatex *   tex = new TLatex(0.21,0.83,"55 < p_{T} < 200 GeV, F^{Pixels}_{i} > 0.9");
tex->SetNDC();
   tex->SetTextAlign(12);
   tex->SetTextFont(42);
   tex->SetTextSize(0.06);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.17,0.92,"CMS");
tex->SetNDC();
   tex->SetTextFont(61);
   tex->SetTextSize(0.0675);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.25,0.92,"Preliminary");
tex->SetNDC();
   tex->SetTextFont(52);
   tex->SetTextSize(0.0485);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.95,0.92,"101 fb^{-1} (13 TeV)");
tex->SetNDC();
   tex->SetTextAlign(31);
   tex->SetTextFont(42);
   tex->SetTextSize(0.07);
   tex->SetLineWidth(2);
   tex->Draw();
   data_obs_pass_prefit_projy2_main->Modified();
   plots_fit_s/base_figs/prefit_projy2_pass_logy->cd();
  
// ------------>Primitives in pad: data_obs_pass_prefit_projy2_sub
   TPad *data_obs_pass_prefit_projy2_sub = new TPad("data_obs_pass_prefit_projy2_sub", "data_obs_pass_prefit_projy2_sub",0,0,1,0.35);
   data_obs_pass_prefit_projy2_sub->Draw();
   data_obs_pass_prefit_projy2_sub->cd();
   data_obs_pass_prefit_projy2_sub->Range(17.30769,-6.023077,209.6154,2.9);
   data_obs_pass_prefit_projy2_sub->SetFillColor(0);
   data_obs_pass_prefit_projy2_sub->SetBorderMode(0);
   data_obs_pass_prefit_projy2_sub->SetBorderSize(2);
   data_obs_pass_prefit_projy2_sub->SetTickx(1);
   data_obs_pass_prefit_projy2_sub->SetTicky(1);
   data_obs_pass_prefit_projy2_sub->SetLeftMargin(0.17);
   data_obs_pass_prefit_projy2_sub->SetRightMargin(0.05);
   data_obs_pass_prefit_projy2_sub->SetTopMargin(0);
   data_obs_pass_prefit_projy2_sub->SetBottomMargin(0.35);
   data_obs_pass_prefit_projy2_sub->SetFrameFillStyle(0);
   data_obs_pass_prefit_projy2_sub->SetFrameBorderMode(0);
   data_obs_pass_prefit_projy2_sub->SetFrameFillStyle(0);
   data_obs_pass_prefit_projy2_sub->SetFrameBorderMode(0);
   Double_t xAxis1056[2] = {50, 200}; 
   
   TH1D *data_obs_pass_prefit_projy2_pull__672 = new TH1D("data_obs_pass_prefit_projy2_pull__672","",1, xAxis1056);
   data_obs_pass_prefit_projy2_pull__672->SetMinimum(-2.9);
   data_obs_pass_prefit_projy2_pull__672->SetMaximum(2.9);
   data_obs_pass_prefit_projy2_pull__672->SetEntries(2);
   data_obs_pass_prefit_projy2_pull__672->SetStats(0);

   ci = TColor::GetColor("#0000ff");
   data_obs_pass_prefit_projy2_pull__672->SetFillColor(ci);

   ci = TColor::GetColor("#000000");
   data_obs_pass_prefit_projy2_pull__672->SetLineColor(ci);
   data_obs_pass_prefit_projy2_pull__672->SetLineStyle(0);

   ci = TColor::GetColor("#000000");
   data_obs_pass_prefit_projy2_pull__672->SetMarkerColor(ci);
   data_obs_pass_prefit_projy2_pull__672->SetMarkerStyle(8);
   data_obs_pass_prefit_projy2_pull__672->GetXaxis()->SetTitle("p_{T}");
   data_obs_pass_prefit_projy2_pull__672->GetXaxis()->SetLabelFont(42);
   data_obs_pass_prefit_projy2_pull__672->GetXaxis()->SetLabelOffset(0.05);
   data_obs_pass_prefit_projy2_pull__672->GetXaxis()->SetLabelSize(0.13);
   data_obs_pass_prefit_projy2_pull__672->GetXaxis()->SetTitleSize(0.15);
   data_obs_pass_prefit_projy2_pull__672->GetXaxis()->SetTitleOffset(1.15);
   data_obs_pass_prefit_projy2_pull__672->GetXaxis()->SetTitleFont(42);
   data_obs_pass_prefit_projy2_pull__672->GetYaxis()->SetTitle("(Data-Bkg)/#sigma");
   data_obs_pass_prefit_projy2_pull__672->GetYaxis()->SetNdivisions(306);
   data_obs_pass_prefit_projy2_pull__672->GetYaxis()->SetLabelFont(42);
   data_obs_pass_prefit_projy2_pull__672->GetYaxis()->SetLabelOffset(0.007);
   data_obs_pass_prefit_projy2_pull__672->GetYaxis()->SetLabelSize(0.13);
   data_obs_pass_prefit_projy2_pull__672->GetYaxis()->SetTitleSize(0.12);
   data_obs_pass_prefit_projy2_pull__672->GetYaxis()->SetTitleOffset(0.4);
   data_obs_pass_prefit_projy2_pull__672->GetYaxis()->SetTitleFont(42);
   data_obs_pass_prefit_projy2_pull__672->GetZaxis()->SetLabelFont(42);
   data_obs_pass_prefit_projy2_pull__672->GetZaxis()->SetLabelOffset(0.007);
   data_obs_pass_prefit_projy2_pull__672->GetZaxis()->SetLabelSize(0.05);
   data_obs_pass_prefit_projy2_pull__672->GetZaxis()->SetTitleSize(0.08);
   data_obs_pass_prefit_projy2_pull__672->GetZaxis()->SetTitleFont(42);
   data_obs_pass_prefit_projy2_pull__672->Draw("hist");
   data_obs_pass_prefit_projy2_sub->Modified();
   plots_fit_s/base_figs/prefit_projy2_pass_logy->cd();
   plots_fit_s/base_figs/prefit_projy2_pass_logy->Modified();
   plots_fit_s/base_figs/prefit_projy2_pass_logy->cd();
   plots_fit_s/base_figs/prefit_projy2_pass_logy->SetSelected(plots_fit_s/base_figs/prefit_projy2_pass_logy);
}
