void prefit_projy2_pass()
{
//=========Macro generated from canvas: plots_fit_s/base_figs/prefit_projy2_pass/plots_fit_s/base_figs/prefit_projy2_pass
//=========  (Fri Jan 12 21:00:35 2024) by ROOT version 6.14/09
   TCanvas *plots_fit_s/base_figs/prefit_projy2_pass = new TCanvas("plots_fit_s/base_figs/prefit_projy2_pass", "plots_fit_s/base_figs/prefit_projy2_pass",0,0,800,700);
   gStyle->SetOptFit(1);
   gStyle->SetOptStat(0);
   plots_fit_s/base_figs/prefit_projy2_pass->SetHighLightColor(2);
   plots_fit_s/base_figs/prefit_projy2_pass->Range(0,0,1,1);
   plots_fit_s/base_figs/prefit_projy2_pass->SetFillColor(0);
   plots_fit_s/base_figs/prefit_projy2_pass->SetBorderMode(0);
   plots_fit_s/base_figs/prefit_projy2_pass->SetBorderSize(2);
   plots_fit_s/base_figs/prefit_projy2_pass->SetTickx(1);
   plots_fit_s/base_figs/prefit_projy2_pass->SetTicky(1);
   plots_fit_s/base_figs/prefit_projy2_pass->SetLeftMargin(0.16);
   plots_fit_s/base_figs/prefit_projy2_pass->SetRightMargin(0);
   plots_fit_s/base_figs/prefit_projy2_pass->SetTopMargin(0);
   plots_fit_s/base_figs/prefit_projy2_pass->SetBottomMargin(0);
   plots_fit_s/base_figs/prefit_projy2_pass->SetFrameFillStyle(0);
   plots_fit_s/base_figs/prefit_projy2_pass->SetFrameBorderMode(0);
  
// ------------>Primitives in pad: data_obs_pass_prefit_projy2_main
   TPad *data_obs_pass_prefit_projy2_main = new TPad("data_obs_pass_prefit_projy2_main", "data_obs_pass_prefit_projy2_main",0,0.35,1,1);
   data_obs_pass_prefit_projy2_main->Draw();
   data_obs_pass_prefit_projy2_main->cd();
   data_obs_pass_prefit_projy2_main->Range(17.30769,-0.04651163,209.6154,1.116279);
   data_obs_pass_prefit_projy2_main->SetFillColor(0);
   data_obs_pass_prefit_projy2_main->SetBorderMode(0);
   data_obs_pass_prefit_projy2_main->SetBorderSize(2);
   data_obs_pass_prefit_projy2_main->SetTickx(1);
   data_obs_pass_prefit_projy2_main->SetTicky(1);
   data_obs_pass_prefit_projy2_main->SetLeftMargin(0.17);
   data_obs_pass_prefit_projy2_main->SetRightMargin(0.05);
   data_obs_pass_prefit_projy2_main->SetBottomMargin(0.04);
   data_obs_pass_prefit_projy2_main->SetFrameFillStyle(0);
   data_obs_pass_prefit_projy2_main->SetFrameBorderMode(0);
   data_obs_pass_prefit_projy2_main->SetFrameFillStyle(0);
   data_obs_pass_prefit_projy2_main->SetFrameBorderMode(0);
   Double_t xAxis980[2] = {50, 200}; 
   
   TH1D *data_obs_pass_prefit_projy2__624 = new TH1D("data_obs_pass_prefit_projy2__624","",1, xAxis980);
   data_obs_pass_prefit_projy2__624->SetMinimum(0);
   data_obs_pass_prefit_projy2__624->SetMaximum(0);

   Int_t ci;      // for color index setting
   TColor *color; // for color definition with alpha
   ci = TColor::GetColor("#000000");
   data_obs_pass_prefit_projy2__624->SetLineColor(ci);
   data_obs_pass_prefit_projy2__624->SetLineStyle(0);

   ci = TColor::GetColor("#000000");
   data_obs_pass_prefit_projy2__624->SetMarkerColor(ci);
   data_obs_pass_prefit_projy2__624->SetMarkerStyle(8);
   data_obs_pass_prefit_projy2__624->GetXaxis()->SetTitle("p_{T}");
   data_obs_pass_prefit_projy2__624->GetXaxis()->SetLabelFont(42);
   data_obs_pass_prefit_projy2__624->GetXaxis()->SetLabelOffset(0.05);
   data_obs_pass_prefit_projy2__624->GetXaxis()->SetLabelSize(0.07);
   data_obs_pass_prefit_projy2__624->GetXaxis()->SetTitleSize(0.09);
   data_obs_pass_prefit_projy2__624->GetXaxis()->SetTitleOffset(1.15);
   data_obs_pass_prefit_projy2__624->GetXaxis()->SetTitleFont(42);
   data_obs_pass_prefit_projy2__624->GetYaxis()->SetTitle("Events / bin");
   data_obs_pass_prefit_projy2__624->GetYaxis()->SetNdivisions(508);
   data_obs_pass_prefit_projy2__624->GetYaxis()->SetLabelFont(42);
   data_obs_pass_prefit_projy2__624->GetYaxis()->SetLabelOffset(0.007);
   data_obs_pass_prefit_projy2__624->GetYaxis()->SetLabelSize(0.07);
   data_obs_pass_prefit_projy2__624->GetYaxis()->SetTitleSize(0.09);
   data_obs_pass_prefit_projy2__624->GetYaxis()->SetTitleOffset(0.8);
   data_obs_pass_prefit_projy2__624->GetYaxis()->SetTitleFont(42);
   data_obs_pass_prefit_projy2__624->GetZaxis()->SetLabelFont(42);
   data_obs_pass_prefit_projy2__624->GetZaxis()->SetLabelOffset(0.007);
   data_obs_pass_prefit_projy2__624->GetZaxis()->SetLabelSize(0.05);
   data_obs_pass_prefit_projy2__624->GetZaxis()->SetTitleSize(0.08);
   data_obs_pass_prefit_projy2__624->GetZaxis()->SetTitleFont(42);
   data_obs_pass_prefit_projy2__624->Draw("pe X0");
   
   THStack *prefit_projy2_pass_stack = new THStack();
   prefit_projy2_pass_stack->SetName("prefit_projy2_pass_stack");
   prefit_projy2_pass_stack->SetTitle("prefit_projy2_pass_stack");
   Double_t xAxis981[2] = {50, 200}; 
   
   TH1F *prefit_projy2_pass_stack_stack_179 = new TH1F("prefit_projy2_pass_stack_stack_179","prefit_projy2_pass_stack",1, xAxis981);
   prefit_projy2_pass_stack_stack_179->SetMinimum(0);
   prefit_projy2_pass_stack_stack_179->SetMaximum(0);
   prefit_projy2_pass_stack_stack_179->SetDirectory(0);
   prefit_projy2_pass_stack_stack_179->SetStats(0);
   prefit_projy2_pass_stack_stack_179->SetLineStyle(0);
   prefit_projy2_pass_stack_stack_179->GetXaxis()->SetLabelFont(42);
   prefit_projy2_pass_stack_stack_179->GetXaxis()->SetLabelOffset(0.007);
   prefit_projy2_pass_stack_stack_179->GetXaxis()->SetLabelSize(0.05);
   prefit_projy2_pass_stack_stack_179->GetXaxis()->SetTitleSize(0.08);
   prefit_projy2_pass_stack_stack_179->GetXaxis()->SetTitleOffset(0.9);
   prefit_projy2_pass_stack_stack_179->GetXaxis()->SetTitleFont(42);
   prefit_projy2_pass_stack_stack_179->GetYaxis()->SetNdivisions(508);
   prefit_projy2_pass_stack_stack_179->GetYaxis()->SetLabelFont(42);
   prefit_projy2_pass_stack_stack_179->GetYaxis()->SetLabelOffset(0.007);
   prefit_projy2_pass_stack_stack_179->GetYaxis()->SetLabelSize(0.05);
   prefit_projy2_pass_stack_stack_179->GetYaxis()->SetTitleSize(0.08);
   prefit_projy2_pass_stack_stack_179->GetYaxis()->SetTitleOffset(1.25);
   prefit_projy2_pass_stack_stack_179->GetYaxis()->SetTitleFont(42);
   prefit_projy2_pass_stack_stack_179->GetZaxis()->SetLabelFont(42);
   prefit_projy2_pass_stack_stack_179->GetZaxis()->SetLabelOffset(0.007);
   prefit_projy2_pass_stack_stack_179->GetZaxis()->SetLabelSize(0.05);
   prefit_projy2_pass_stack_stack_179->GetZaxis()->SetTitleSize(0.08);
   prefit_projy2_pass_stack_stack_179->GetZaxis()->SetTitleFont(42);
   prefit_projy2_pass_stack->SetHistogram(prefit_projy2_pass_stack_stack_179);
   
   Double_t xAxis982[2] = {50, 200}; 
   
   TH1D *Background_0x0_pass_prefit_projy2_stack_1 = new TH1D("Background_0x0_pass_prefit_projy2_stack_1","Background, pass, prefit, 1.0-1.0",1, xAxis982);
   Background_0x0_pass_prefit_projy2_stack_1->SetMinimum(0);

   ci = TColor::GetColor("#ffff00");
   Background_0x0_pass_prefit_projy2_stack_1->SetFillColor(ci);

   ci = 1556;
   color = new TColor(ci, 1, 1, 1, " ", 0);
   Background_0x0_pass_prefit_projy2_stack_1->SetLineColor(ci);
   Background_0x0_pass_prefit_projy2_stack_1->SetLineStyle(0);
   Background_0x0_pass_prefit_projy2_stack_1->GetXaxis()->SetTitle("p_{T}");
   Background_0x0_pass_prefit_projy2_stack_1->GetXaxis()->SetLabelFont(42);
   Background_0x0_pass_prefit_projy2_stack_1->GetXaxis()->SetLabelOffset(0.007);
   Background_0x0_pass_prefit_projy2_stack_1->GetXaxis()->SetLabelSize(0.05);
   Background_0x0_pass_prefit_projy2_stack_1->GetXaxis()->SetTitleSize(0.08);
   Background_0x0_pass_prefit_projy2_stack_1->GetXaxis()->SetTitleOffset(1.25);
   Background_0x0_pass_prefit_projy2_stack_1->GetXaxis()->SetTitleFont(42);
   Background_0x0_pass_prefit_projy2_stack_1->GetYaxis()->SetTitle("Events / bin");
   Background_0x0_pass_prefit_projy2_stack_1->GetYaxis()->SetLabelFont(42);
   Background_0x0_pass_prefit_projy2_stack_1->GetYaxis()->SetLabelOffset(0.007);
   Background_0x0_pass_prefit_projy2_stack_1->GetYaxis()->SetLabelSize(0.05);
   Background_0x0_pass_prefit_projy2_stack_1->GetYaxis()->SetTitleSize(0.08);
   Background_0x0_pass_prefit_projy2_stack_1->GetYaxis()->SetTitleOffset(1.25);
   Background_0x0_pass_prefit_projy2_stack_1->GetYaxis()->SetTitleFont(42);
   Background_0x0_pass_prefit_projy2_stack_1->GetZaxis()->SetLabelFont(42);
   Background_0x0_pass_prefit_projy2_stack_1->GetZaxis()->SetLabelOffset(0.007);
   Background_0x0_pass_prefit_projy2_stack_1->GetZaxis()->SetLabelSize(0.05);
   Background_0x0_pass_prefit_projy2_stack_1->GetZaxis()->SetTitleSize(0.08);
   Background_0x0_pass_prefit_projy2_stack_1->GetZaxis()->SetTitleFont(42);
   prefit_projy2_pass_stack->Add(Background_0x0_pass_prefit_projy2_stack_1,"");
   prefit_projy2_pass_stack->Draw("hist same");
   
   prefit_projy2_pass_stack = new THStack();
   prefit_projy2_pass_stack->SetName("prefit_projy2_pass_stack");
   prefit_projy2_pass_stack->SetTitle("prefit_projy2_pass_stack");
   Double_t xAxis983[2] = {50, 200}; 
   
   TH1F *prefit_projy2_pass_stack_stack_179_stack_180 = new TH1F("prefit_projy2_pass_stack_stack_179_stack_180","prefit_projy2_pass_stack",1, xAxis983);
   prefit_projy2_pass_stack_stack_179_stack_180->SetMinimum(0);
   prefit_projy2_pass_stack_stack_179_stack_180->SetMaximum(0);
   prefit_projy2_pass_stack_stack_179_stack_180->SetDirectory(0);
   prefit_projy2_pass_stack_stack_179_stack_180->SetStats(0);
   prefit_projy2_pass_stack_stack_179_stack_180->SetLineStyle(0);
   prefit_projy2_pass_stack_stack_179_stack_180->GetXaxis()->SetLabelFont(42);
   prefit_projy2_pass_stack_stack_179_stack_180->GetXaxis()->SetLabelOffset(0.007);
   prefit_projy2_pass_stack_stack_179_stack_180->GetXaxis()->SetLabelSize(0.05);
   prefit_projy2_pass_stack_stack_179_stack_180->GetXaxis()->SetTitleSize(0.08);
   prefit_projy2_pass_stack_stack_179_stack_180->GetXaxis()->SetTitleOffset(0.9);
   prefit_projy2_pass_stack_stack_179_stack_180->GetXaxis()->SetTitleFont(42);
   prefit_projy2_pass_stack_stack_179_stack_180->GetYaxis()->SetNdivisions(508);
   prefit_projy2_pass_stack_stack_179_stack_180->GetYaxis()->SetLabelFont(42);
   prefit_projy2_pass_stack_stack_179_stack_180->GetYaxis()->SetLabelOffset(0.007);
   prefit_projy2_pass_stack_stack_179_stack_180->GetYaxis()->SetLabelSize(0.05);
   prefit_projy2_pass_stack_stack_179_stack_180->GetYaxis()->SetTitleSize(0.08);
   prefit_projy2_pass_stack_stack_179_stack_180->GetYaxis()->SetTitleOffset(1.25);
   prefit_projy2_pass_stack_stack_179_stack_180->GetYaxis()->SetTitleFont(42);
   prefit_projy2_pass_stack_stack_179_stack_180->GetZaxis()->SetLabelFont(42);
   prefit_projy2_pass_stack_stack_179_stack_180->GetZaxis()->SetLabelOffset(0.007);
   prefit_projy2_pass_stack_stack_179_stack_180->GetZaxis()->SetLabelSize(0.05);
   prefit_projy2_pass_stack_stack_179_stack_180->GetZaxis()->SetTitleSize(0.08);
   prefit_projy2_pass_stack_stack_179_stack_180->GetZaxis()->SetTitleFont(42);
   prefit_projy2_pass_stack->SetHistogram(prefit_projy2_pass_stack_stack_179_stack_180);
   
   Double_t xAxis984[2] = {50, 200}; 
   
   TH1D *Background_0x0_pass_prefit_projy2_stack_1_stack_1 = new TH1D("Background_0x0_pass_prefit_projy2_stack_1_stack_1","Background, pass, prefit, 1.0-1.0",1, xAxis984);
   Background_0x0_pass_prefit_projy2_stack_1_stack_1->SetMinimum(0);

   ci = TColor::GetColor("#ffff00");
   Background_0x0_pass_prefit_projy2_stack_1_stack_1->SetFillColor(ci);

   ci = 1556;
   color = new TColor(ci, 1, 1, 1, " ", 0);
   Background_0x0_pass_prefit_projy2_stack_1_stack_1->SetLineColor(ci);
   Background_0x0_pass_prefit_projy2_stack_1_stack_1->SetLineStyle(0);
   Background_0x0_pass_prefit_projy2_stack_1_stack_1->GetXaxis()->SetTitle("p_{T}");
   Background_0x0_pass_prefit_projy2_stack_1_stack_1->GetXaxis()->SetLabelFont(42);
   Background_0x0_pass_prefit_projy2_stack_1_stack_1->GetXaxis()->SetLabelOffset(0.007);
   Background_0x0_pass_prefit_projy2_stack_1_stack_1->GetXaxis()->SetLabelSize(0.05);
   Background_0x0_pass_prefit_projy2_stack_1_stack_1->GetXaxis()->SetTitleSize(0.08);
   Background_0x0_pass_prefit_projy2_stack_1_stack_1->GetXaxis()->SetTitleOffset(1.25);
   Background_0x0_pass_prefit_projy2_stack_1_stack_1->GetXaxis()->SetTitleFont(42);
   Background_0x0_pass_prefit_projy2_stack_1_stack_1->GetYaxis()->SetTitle("Events / bin");
   Background_0x0_pass_prefit_projy2_stack_1_stack_1->GetYaxis()->SetLabelFont(42);
   Background_0x0_pass_prefit_projy2_stack_1_stack_1->GetYaxis()->SetLabelOffset(0.007);
   Background_0x0_pass_prefit_projy2_stack_1_stack_1->GetYaxis()->SetLabelSize(0.05);
   Background_0x0_pass_prefit_projy2_stack_1_stack_1->GetYaxis()->SetTitleSize(0.08);
   Background_0x0_pass_prefit_projy2_stack_1_stack_1->GetYaxis()->SetTitleOffset(1.25);
   Background_0x0_pass_prefit_projy2_stack_1_stack_1->GetYaxis()->SetTitleFont(42);
   Background_0x0_pass_prefit_projy2_stack_1_stack_1->GetZaxis()->SetLabelFont(42);
   Background_0x0_pass_prefit_projy2_stack_1_stack_1->GetZaxis()->SetLabelOffset(0.007);
   Background_0x0_pass_prefit_projy2_stack_1_stack_1->GetZaxis()->SetLabelSize(0.05);
   Background_0x0_pass_prefit_projy2_stack_1_stack_1->GetZaxis()->SetTitleSize(0.08);
   Background_0x0_pass_prefit_projy2_stack_1_stack_1->GetZaxis()->SetTitleFont(42);
   prefit_projy2_pass_stack->Add(Background_0x0_pass_prefit_projy2_stack_1_stack_1,"");
   prefit_projy2_pass_stack->Draw("hist same");
   Double_t xAxis985[2] = {50, 200}; 
   
   TH1D *Signal_ppStaumI557_pass_prefit_projy2__625 = new TH1D("Signal_ppStaumI557_pass_prefit_projy2__625","HSCP signal, pass, prefit, 1.0-1.0",1, xAxis985);
   Signal_ppStaumI557_pass_prefit_projy2__625->SetMinimum(0);
   Signal_ppStaumI557_pass_prefit_projy2__625->SetLineColor(2);
   Signal_ppStaumI557_pass_prefit_projy2__625->SetLineStyle(0);
   Signal_ppStaumI557_pass_prefit_projy2__625->GetXaxis()->SetTitle("p_{T}");
   Signal_ppStaumI557_pass_prefit_projy2__625->GetXaxis()->SetLabelFont(42);
   Signal_ppStaumI557_pass_prefit_projy2__625->GetXaxis()->SetLabelOffset(0.007);
   Signal_ppStaumI557_pass_prefit_projy2__625->GetXaxis()->SetLabelSize(0.05);
   Signal_ppStaumI557_pass_prefit_projy2__625->GetXaxis()->SetTitleSize(0.08);
   Signal_ppStaumI557_pass_prefit_projy2__625->GetXaxis()->SetTitleOffset(1.25);
   Signal_ppStaumI557_pass_prefit_projy2__625->GetXaxis()->SetTitleFont(42);
   Signal_ppStaumI557_pass_prefit_projy2__625->GetYaxis()->SetTitle("Events / bin");
   Signal_ppStaumI557_pass_prefit_projy2__625->GetYaxis()->SetLabelFont(42);
   Signal_ppStaumI557_pass_prefit_projy2__625->GetYaxis()->SetLabelOffset(0.007);
   Signal_ppStaumI557_pass_prefit_projy2__625->GetYaxis()->SetLabelSize(0.05);
   Signal_ppStaumI557_pass_prefit_projy2__625->GetYaxis()->SetTitleSize(0.08);
   Signal_ppStaumI557_pass_prefit_projy2__625->GetYaxis()->SetTitleOffset(1.25);
   Signal_ppStaumI557_pass_prefit_projy2__625->GetYaxis()->SetTitleFont(42);
   Signal_ppStaumI557_pass_prefit_projy2__625->GetZaxis()->SetLabelFont(42);
   Signal_ppStaumI557_pass_prefit_projy2__625->GetZaxis()->SetLabelOffset(0.007);
   Signal_ppStaumI557_pass_prefit_projy2__625->GetZaxis()->SetLabelSize(0.05);
   Signal_ppStaumI557_pass_prefit_projy2__625->GetZaxis()->SetTitleSize(0.08);
   Signal_ppStaumI557_pass_prefit_projy2__625->GetZaxis()->SetTitleFont(42);
   Signal_ppStaumI557_pass_prefit_projy2__625->Draw("hist same");
   Double_t xAxis986[2] = {50, 200}; 
   
   TH1D *TotalBkg_pass_prefit_projy2__626 = new TH1D("TotalBkg_pass_prefit_projy2__626","TotalBkg, pass, prefit, 1.0-1.0",1, xAxis986);
   TotalBkg_pass_prefit_projy2__626->SetMinimum(0);
   TotalBkg_pass_prefit_projy2__626->SetLineStyle(0);
   TotalBkg_pass_prefit_projy2__626->SetMarkerStyle(0);
   TotalBkg_pass_prefit_projy2__626->GetXaxis()->SetTitle("p_{T}");
   TotalBkg_pass_prefit_projy2__626->GetXaxis()->SetLabelFont(42);
   TotalBkg_pass_prefit_projy2__626->GetXaxis()->SetLabelOffset(0.007);
   TotalBkg_pass_prefit_projy2__626->GetXaxis()->SetLabelSize(0.05);
   TotalBkg_pass_prefit_projy2__626->GetXaxis()->SetTitleSize(0.08);
   TotalBkg_pass_prefit_projy2__626->GetXaxis()->SetTitleOffset(1.25);
   TotalBkg_pass_prefit_projy2__626->GetXaxis()->SetTitleFont(42);
   TotalBkg_pass_prefit_projy2__626->GetYaxis()->SetTitle("Events / bin");
   TotalBkg_pass_prefit_projy2__626->GetYaxis()->SetLabelFont(42);
   TotalBkg_pass_prefit_projy2__626->GetYaxis()->SetLabelOffset(0.007);
   TotalBkg_pass_prefit_projy2__626->GetYaxis()->SetLabelSize(0.05);
   TotalBkg_pass_prefit_projy2__626->GetYaxis()->SetTitleSize(0.08);
   TotalBkg_pass_prefit_projy2__626->GetYaxis()->SetTitleOffset(1.25);
   TotalBkg_pass_prefit_projy2__626->GetYaxis()->SetTitleFont(42);
   TotalBkg_pass_prefit_projy2__626->GetZaxis()->SetLabelFont(42);
   TotalBkg_pass_prefit_projy2__626->GetZaxis()->SetLabelOffset(0.007);
   TotalBkg_pass_prefit_projy2__626->GetZaxis()->SetLabelSize(0.05);
   TotalBkg_pass_prefit_projy2__626->GetZaxis()->SetTitleSize(0.08);
   TotalBkg_pass_prefit_projy2__626->GetZaxis()->SetTitleFont(42);
   TotalBkg_pass_prefit_projy2__626->Draw("hist same");
   Double_t xAxis987[2] = {50, 200}; 
   
   TH1D *TotalBkg_pass_prefit_projy2__627 = new TH1D("TotalBkg_pass_prefit_projy2__627","TotalBkg, pass, prefit, 1.0-1.0",1, xAxis987);
   TotalBkg_pass_prefit_projy2__627->SetMinimum(0);
   TotalBkg_pass_prefit_projy2__627->SetFillColor(1);
   TotalBkg_pass_prefit_projy2__627->SetFillStyle(3354);
   TotalBkg_pass_prefit_projy2__627->SetLineStyle(0);
   TotalBkg_pass_prefit_projy2__627->SetLineWidth(0);
   TotalBkg_pass_prefit_projy2__627->SetMarkerStyle(0);
   TotalBkg_pass_prefit_projy2__627->GetXaxis()->SetTitle("p_{T}");
   TotalBkg_pass_prefit_projy2__627->GetXaxis()->SetLabelFont(42);
   TotalBkg_pass_prefit_projy2__627->GetXaxis()->SetLabelOffset(0.007);
   TotalBkg_pass_prefit_projy2__627->GetXaxis()->SetLabelSize(0.05);
   TotalBkg_pass_prefit_projy2__627->GetXaxis()->SetTitleSize(0.08);
   TotalBkg_pass_prefit_projy2__627->GetXaxis()->SetTitleOffset(1.25);
   TotalBkg_pass_prefit_projy2__627->GetXaxis()->SetTitleFont(42);
   TotalBkg_pass_prefit_projy2__627->GetYaxis()->SetTitle("Events / bin");
   TotalBkg_pass_prefit_projy2__627->GetYaxis()->SetLabelFont(42);
   TotalBkg_pass_prefit_projy2__627->GetYaxis()->SetLabelOffset(0.007);
   TotalBkg_pass_prefit_projy2__627->GetYaxis()->SetLabelSize(0.05);
   TotalBkg_pass_prefit_projy2__627->GetYaxis()->SetTitleSize(0.08);
   TotalBkg_pass_prefit_projy2__627->GetYaxis()->SetTitleOffset(1.25);
   TotalBkg_pass_prefit_projy2__627->GetYaxis()->SetTitleFont(42);
   TotalBkg_pass_prefit_projy2__627->GetZaxis()->SetLabelFont(42);
   TotalBkg_pass_prefit_projy2__627->GetZaxis()->SetLabelOffset(0.007);
   TotalBkg_pass_prefit_projy2__627->GetZaxis()->SetLabelSize(0.05);
   TotalBkg_pass_prefit_projy2__627->GetZaxis()->SetTitleSize(0.08);
   TotalBkg_pass_prefit_projy2__627->GetZaxis()->SetTitleFont(42);
   TotalBkg_pass_prefit_projy2__627->Draw("e2 same");
   Double_t xAxis988[2] = {50, 200}; 
   
   TH1D *data_obs_pass_prefit_projy2__628 = new TH1D("data_obs_pass_prefit_projy2__628","",1, xAxis988);
   data_obs_pass_prefit_projy2__628->SetMinimum(0);
   data_obs_pass_prefit_projy2__628->SetMaximum(0);

   ci = TColor::GetColor("#000000");
   data_obs_pass_prefit_projy2__628->SetLineColor(ci);
   data_obs_pass_prefit_projy2__628->SetLineStyle(0);

   ci = TColor::GetColor("#000000");
   data_obs_pass_prefit_projy2__628->SetMarkerColor(ci);
   data_obs_pass_prefit_projy2__628->SetMarkerStyle(8);
   data_obs_pass_prefit_projy2__628->GetXaxis()->SetTitle("p_{T}");
   data_obs_pass_prefit_projy2__628->GetXaxis()->SetLabelFont(42);
   data_obs_pass_prefit_projy2__628->GetXaxis()->SetLabelOffset(0.05);
   data_obs_pass_prefit_projy2__628->GetXaxis()->SetLabelSize(0.07);
   data_obs_pass_prefit_projy2__628->GetXaxis()->SetTitleSize(0.09);
   data_obs_pass_prefit_projy2__628->GetXaxis()->SetTitleOffset(1.15);
   data_obs_pass_prefit_projy2__628->GetXaxis()->SetTitleFont(42);
   data_obs_pass_prefit_projy2__628->GetYaxis()->SetTitle("Events / bin");
   data_obs_pass_prefit_projy2__628->GetYaxis()->SetNdivisions(508);
   data_obs_pass_prefit_projy2__628->GetYaxis()->SetLabelFont(42);
   data_obs_pass_prefit_projy2__628->GetYaxis()->SetLabelOffset(0.007);
   data_obs_pass_prefit_projy2__628->GetYaxis()->SetLabelSize(0.07);
   data_obs_pass_prefit_projy2__628->GetYaxis()->SetTitleSize(0.09);
   data_obs_pass_prefit_projy2__628->GetYaxis()->SetTitleOffset(0.8);
   data_obs_pass_prefit_projy2__628->GetYaxis()->SetTitleFont(42);
   data_obs_pass_prefit_projy2__628->GetZaxis()->SetLabelFont(42);
   data_obs_pass_prefit_projy2__628->GetZaxis()->SetLabelOffset(0.007);
   data_obs_pass_prefit_projy2__628->GetZaxis()->SetLabelSize(0.05);
   data_obs_pass_prefit_projy2__628->GetZaxis()->SetTitleSize(0.08);
   data_obs_pass_prefit_projy2__628->GetZaxis()->SetTitleFont(42);
   data_obs_pass_prefit_projy2__628->Draw("pe X0 same");
   
   TLegend *leg = new TLegend(0.65,0.64,0.9,0.88,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(1001);
   TLegendEntry *entry=leg->AddEntry("data_obs_pass_prefit_projy2","Data","pe X0");

   ci = TColor::GetColor("#000000");
   entry->SetLineColor(ci);
   entry->SetLineWidth(1);

   ci = TColor::GetColor("#000000");
   entry->SetMarkerColor(ci);
   entry->SetMarkerStyle(8);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("TotalBkg_pass_prefit_projy2","Total bkg unc.","F");
   entry->SetFillColor(1);
   entry->SetFillStyle(3354);
   entry->SetLineColor(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("Signal_ppStau-557_pass_prefit_projy2","HSCP signal","L");
   entry->SetLineColor(2);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("Background_0x0_pass_prefit_projy2_stack_1_stack_1","Background","f");

   ci = TColor::GetColor("#ffff00");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = 1556;
   color = new TColor(ci, 1, 1, 1, " ", 0);
   entry->SetLineColor(ci);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   leg->Draw();
   Double_t xAxis989[2] = {50, 200}; 
   
   TH1D *data_obs_pass_prefit_projy2_copy__629 = new TH1D("data_obs_pass_prefit_projy2_copy__629","",1, xAxis989);
   data_obs_pass_prefit_projy2_copy__629->SetMinimum(0);
   data_obs_pass_prefit_projy2_copy__629->SetMaximum(0);
   data_obs_pass_prefit_projy2_copy__629->SetDirectory(0);

   ci = TColor::GetColor("#000000");
   data_obs_pass_prefit_projy2_copy__629->SetLineColor(ci);
   data_obs_pass_prefit_projy2_copy__629->SetLineStyle(0);

   ci = TColor::GetColor("#000000");
   data_obs_pass_prefit_projy2_copy__629->SetMarkerColor(ci);
   data_obs_pass_prefit_projy2_copy__629->SetMarkerStyle(8);
   data_obs_pass_prefit_projy2_copy__629->GetXaxis()->SetTitle("p_{T}");
   data_obs_pass_prefit_projy2_copy__629->GetXaxis()->SetLabelFont(42);
   data_obs_pass_prefit_projy2_copy__629->GetXaxis()->SetLabelOffset(0.05);
   data_obs_pass_prefit_projy2_copy__629->GetXaxis()->SetLabelSize(0.07);
   data_obs_pass_prefit_projy2_copy__629->GetXaxis()->SetTitleSize(0.09);
   data_obs_pass_prefit_projy2_copy__629->GetXaxis()->SetTitleOffset(1.15);
   data_obs_pass_prefit_projy2_copy__629->GetXaxis()->SetTitleFont(42);
   data_obs_pass_prefit_projy2_copy__629->GetYaxis()->SetTitle("Events / bin");
   data_obs_pass_prefit_projy2_copy__629->GetYaxis()->SetNdivisions(508);
   data_obs_pass_prefit_projy2_copy__629->GetYaxis()->SetLabelFont(42);
   data_obs_pass_prefit_projy2_copy__629->GetYaxis()->SetLabelOffset(0.007);
   data_obs_pass_prefit_projy2_copy__629->GetYaxis()->SetLabelSize(0.07);
   data_obs_pass_prefit_projy2_copy__629->GetYaxis()->SetTitleSize(0.09);
   data_obs_pass_prefit_projy2_copy__629->GetYaxis()->SetTitleOffset(0.8);
   data_obs_pass_prefit_projy2_copy__629->GetYaxis()->SetTitleFont(42);
   data_obs_pass_prefit_projy2_copy__629->GetZaxis()->SetLabelFont(42);
   data_obs_pass_prefit_projy2_copy__629->GetZaxis()->SetLabelOffset(0.007);
   data_obs_pass_prefit_projy2_copy__629->GetZaxis()->SetLabelSize(0.05);
   data_obs_pass_prefit_projy2_copy__629->GetZaxis()->SetTitleSize(0.08);
   data_obs_pass_prefit_projy2_copy__629->GetZaxis()->SetTitleFont(42);
   data_obs_pass_prefit_projy2_copy__629->Draw("sameaxis");
   TLatex *   tex = new TLatex(0.21,0.83,"55 < p_{T} < 200 GeV, F^{Pixels}_{i} > 0.9");
tex->SetNDC();
   tex->SetTextAlign(12);
   tex->SetTextFont(42);
   tex->SetTextSize(0.06);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.17,0.92,"CMS");
tex->SetNDC();
   tex->SetTextFont(61);
   tex->SetTextSize(0.0675);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.25,0.92,"Preliminary");
tex->SetNDC();
   tex->SetTextFont(52);
   tex->SetTextSize(0.0485);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.95,0.92,"101 fb^{-1} (13 TeV)");
tex->SetNDC();
   tex->SetTextAlign(31);
   tex->SetTextFont(42);
   tex->SetTextSize(0.07);
   tex->SetLineWidth(2);
   tex->Draw();
   data_obs_pass_prefit_projy2_main->Modified();
   plots_fit_s/base_figs/prefit_projy2_pass->cd();
  
// ------------>Primitives in pad: data_obs_pass_prefit_projy2_sub
   TPad *data_obs_pass_prefit_projy2_sub = new TPad("data_obs_pass_prefit_projy2_sub", "data_obs_pass_prefit_projy2_sub",0,0,1,0.35);
   data_obs_pass_prefit_projy2_sub->Draw();
   data_obs_pass_prefit_projy2_sub->cd();
   data_obs_pass_prefit_projy2_sub->Range(17.30769,-6.023077,209.6154,2.9);
   data_obs_pass_prefit_projy2_sub->SetFillColor(0);
   data_obs_pass_prefit_projy2_sub->SetBorderMode(0);
   data_obs_pass_prefit_projy2_sub->SetBorderSize(2);
   data_obs_pass_prefit_projy2_sub->SetTickx(1);
   data_obs_pass_prefit_projy2_sub->SetTicky(1);
   data_obs_pass_prefit_projy2_sub->SetLeftMargin(0.17);
   data_obs_pass_prefit_projy2_sub->SetRightMargin(0.05);
   data_obs_pass_prefit_projy2_sub->SetTopMargin(0);
   data_obs_pass_prefit_projy2_sub->SetBottomMargin(0.35);
   data_obs_pass_prefit_projy2_sub->SetFrameFillStyle(0);
   data_obs_pass_prefit_projy2_sub->SetFrameBorderMode(0);
   data_obs_pass_prefit_projy2_sub->SetFrameFillStyle(0);
   data_obs_pass_prefit_projy2_sub->SetFrameBorderMode(0);
   Double_t xAxis990[2] = {50, 200}; 
   
   TH1D *data_obs_pass_prefit_projy2_pull__630 = new TH1D("data_obs_pass_prefit_projy2_pull__630","",1, xAxis990);
   data_obs_pass_prefit_projy2_pull__630->SetMinimum(-2.9);
   data_obs_pass_prefit_projy2_pull__630->SetMaximum(2.9);
   data_obs_pass_prefit_projy2_pull__630->SetEntries(2);
   data_obs_pass_prefit_projy2_pull__630->SetStats(0);

   ci = TColor::GetColor("#0000ff");
   data_obs_pass_prefit_projy2_pull__630->SetFillColor(ci);

   ci = TColor::GetColor("#000000");
   data_obs_pass_prefit_projy2_pull__630->SetLineColor(ci);
   data_obs_pass_prefit_projy2_pull__630->SetLineStyle(0);

   ci = TColor::GetColor("#000000");
   data_obs_pass_prefit_projy2_pull__630->SetMarkerColor(ci);
   data_obs_pass_prefit_projy2_pull__630->SetMarkerStyle(8);
   data_obs_pass_prefit_projy2_pull__630->GetXaxis()->SetTitle("p_{T}");
   data_obs_pass_prefit_projy2_pull__630->GetXaxis()->SetLabelFont(42);
   data_obs_pass_prefit_projy2_pull__630->GetXaxis()->SetLabelOffset(0.05);
   data_obs_pass_prefit_projy2_pull__630->GetXaxis()->SetLabelSize(0.13);
   data_obs_pass_prefit_projy2_pull__630->GetXaxis()->SetTitleSize(0.15);
   data_obs_pass_prefit_projy2_pull__630->GetXaxis()->SetTitleOffset(1.15);
   data_obs_pass_prefit_projy2_pull__630->GetXaxis()->SetTitleFont(42);
   data_obs_pass_prefit_projy2_pull__630->GetYaxis()->SetTitle("(Data-Bkg)/#sigma");
   data_obs_pass_prefit_projy2_pull__630->GetYaxis()->SetNdivisions(306);
   data_obs_pass_prefit_projy2_pull__630->GetYaxis()->SetLabelFont(42);
   data_obs_pass_prefit_projy2_pull__630->GetYaxis()->SetLabelOffset(0.007);
   data_obs_pass_prefit_projy2_pull__630->GetYaxis()->SetLabelSize(0.13);
   data_obs_pass_prefit_projy2_pull__630->GetYaxis()->SetTitleSize(0.12);
   data_obs_pass_prefit_projy2_pull__630->GetYaxis()->SetTitleOffset(0.4);
   data_obs_pass_prefit_projy2_pull__630->GetYaxis()->SetTitleFont(42);
   data_obs_pass_prefit_projy2_pull__630->GetZaxis()->SetLabelFont(42);
   data_obs_pass_prefit_projy2_pull__630->GetZaxis()->SetLabelOffset(0.007);
   data_obs_pass_prefit_projy2_pull__630->GetZaxis()->SetLabelSize(0.05);
   data_obs_pass_prefit_projy2_pull__630->GetZaxis()->SetTitleSize(0.08);
   data_obs_pass_prefit_projy2_pull__630->GetZaxis()->SetTitleFont(42);
   data_obs_pass_prefit_projy2_pull__630->Draw("hist");
   data_obs_pass_prefit_projy2_sub->Modified();
   plots_fit_s/base_figs/prefit_projy2_pass->cd();
   plots_fit_s/base_figs/prefit_projy2_pass->Modified();
   plots_fit_s/base_figs/prefit_projy2_pass->cd();
   plots_fit_s/base_figs/prefit_projy2_pass->SetSelected(plots_fit_s/base_figs/prefit_projy2_pass);
}
