void prefit_projy0_fail()
{
//=========Macro generated from canvas: plots_fit_s/base_figs/prefit_projy0_fail/plots_fit_s/base_figs/prefit_projy0_fail
//=========  (Fri Jan 12 21:00:33 2024) by ROOT version 6.14/09
   TCanvas *plots_fit_s/base_figs/prefit_projy0_fail = new TCanvas("plots_fit_s/base_figs/prefit_projy0_fail", "plots_fit_s/base_figs/prefit_projy0_fail",0,0,800,700);
   gStyle->SetOptFit(1);
   gStyle->SetOptStat(0);
   plots_fit_s/base_figs/prefit_projy0_fail->SetHighLightColor(2);
   plots_fit_s/base_figs/prefit_projy0_fail->Range(0,0,1,1);
   plots_fit_s/base_figs/prefit_projy0_fail->SetFillColor(0);
   plots_fit_s/base_figs/prefit_projy0_fail->SetBorderMode(0);
   plots_fit_s/base_figs/prefit_projy0_fail->SetBorderSize(2);
   plots_fit_s/base_figs/prefit_projy0_fail->SetTickx(1);
   plots_fit_s/base_figs/prefit_projy0_fail->SetTicky(1);
   plots_fit_s/base_figs/prefit_projy0_fail->SetLeftMargin(0.16);
   plots_fit_s/base_figs/prefit_projy0_fail->SetRightMargin(0);
   plots_fit_s/base_figs/prefit_projy0_fail->SetTopMargin(0);
   plots_fit_s/base_figs/prefit_projy0_fail->SetBottomMargin(0);
   plots_fit_s/base_figs/prefit_projy0_fail->SetFrameFillStyle(0);
   plots_fit_s/base_figs/prefit_projy0_fail->SetFrameBorderMode(0);
  
// ------------>Primitives in pad: data_obs_fail_prefit_projy0_main
   TPad *data_obs_fail_prefit_projy0_main = new TPad("data_obs_fail_prefit_projy0_main", "data_obs_fail_prefit_projy0_main",0,0.35,1,1);
   data_obs_fail_prefit_projy0_main->Draw();
   data_obs_fail_prefit_projy0_main->cd();
   data_obs_fail_prefit_projy0_main->Range(17.30769,-884431.9,209.6154,2.122636e+07);
   data_obs_fail_prefit_projy0_main->SetFillColor(0);
   data_obs_fail_prefit_projy0_main->SetBorderMode(0);
   data_obs_fail_prefit_projy0_main->SetBorderSize(2);
   data_obs_fail_prefit_projy0_main->SetTickx(1);
   data_obs_fail_prefit_projy0_main->SetTicky(1);
   data_obs_fail_prefit_projy0_main->SetLeftMargin(0.17);
   data_obs_fail_prefit_projy0_main->SetRightMargin(0.05);
   data_obs_fail_prefit_projy0_main->SetBottomMargin(0.04);
   data_obs_fail_prefit_projy0_main->SetFrameFillStyle(0);
   data_obs_fail_prefit_projy0_main->SetFrameBorderMode(0);
   data_obs_fail_prefit_projy0_main->SetFrameFillStyle(0);
   data_obs_fail_prefit_projy0_main->SetFrameBorderMode(0);
   Double_t xAxis826[2] = {50, 200}; 
   
   TH1D *data_obs_fail_prefit_projy0__526 = new TH1D("data_obs_fail_prefit_projy0__526","",1, xAxis826);
   data_obs_fail_prefit_projy0__526->SetBinContent(1,1.40854e+07);
   data_obs_fail_prefit_projy0__526->SetBinError(1,3753.052);
   data_obs_fail_prefit_projy0__526->SetMinimum(0);
   data_obs_fail_prefit_projy0__526->SetMaximum(1.901528e+07);
   data_obs_fail_prefit_projy0__526->SetEntries(1.40854e+07);

   Int_t ci;      // for color index setting
   TColor *color; // for color definition with alpha
   ci = TColor::GetColor("#000000");
   data_obs_fail_prefit_projy0__526->SetLineColor(ci);
   data_obs_fail_prefit_projy0__526->SetLineStyle(0);

   ci = TColor::GetColor("#000000");
   data_obs_fail_prefit_projy0__526->SetMarkerColor(ci);
   data_obs_fail_prefit_projy0__526->SetMarkerStyle(8);
   data_obs_fail_prefit_projy0__526->GetXaxis()->SetTitle("p_{T}");
   data_obs_fail_prefit_projy0__526->GetXaxis()->SetLabelFont(42);
   data_obs_fail_prefit_projy0__526->GetXaxis()->SetLabelOffset(0.05);
   data_obs_fail_prefit_projy0__526->GetXaxis()->SetLabelSize(0.07);
   data_obs_fail_prefit_projy0__526->GetXaxis()->SetTitleSize(0.09);
   data_obs_fail_prefit_projy0__526->GetXaxis()->SetTitleOffset(1.15);
   data_obs_fail_prefit_projy0__526->GetXaxis()->SetTitleFont(42);
   data_obs_fail_prefit_projy0__526->GetYaxis()->SetTitle("Events / bin");
   data_obs_fail_prefit_projy0__526->GetYaxis()->SetNdivisions(508);
   data_obs_fail_prefit_projy0__526->GetYaxis()->SetLabelFont(42);
   data_obs_fail_prefit_projy0__526->GetYaxis()->SetLabelOffset(0.007);
   data_obs_fail_prefit_projy0__526->GetYaxis()->SetLabelSize(0.07);
   data_obs_fail_prefit_projy0__526->GetYaxis()->SetTitleSize(0.09);
   data_obs_fail_prefit_projy0__526->GetYaxis()->SetTitleOffset(0.8);
   data_obs_fail_prefit_projy0__526->GetYaxis()->SetTitleFont(42);
   data_obs_fail_prefit_projy0__526->GetZaxis()->SetLabelFont(42);
   data_obs_fail_prefit_projy0__526->GetZaxis()->SetLabelOffset(0.007);
   data_obs_fail_prefit_projy0__526->GetZaxis()->SetLabelSize(0.05);
   data_obs_fail_prefit_projy0__526->GetZaxis()->SetTitleSize(0.08);
   data_obs_fail_prefit_projy0__526->GetZaxis()->SetTitleFont(42);
   data_obs_fail_prefit_projy0__526->Draw("pe X0");
   
   THStack *prefit_projy0_fail_stack = new THStack();
   prefit_projy0_fail_stack->SetName("prefit_projy0_fail_stack");
   prefit_projy0_fail_stack->SetTitle("prefit_projy0_fail_stack");
   Double_t xAxis827[2] = {50, 200}; 
   
   TH1F *prefit_projy0_fail_stack_stack_151 = new TH1F("prefit_projy0_fail_stack_stack_151","prefit_projy0_fail_stack",1, xAxis827);
   prefit_projy0_fail_stack_stack_151->SetMinimum(0);
   prefit_projy0_fail_stack_stack_151->SetMaximum(1.478967e+07);
   prefit_projy0_fail_stack_stack_151->SetDirectory(0);
   prefit_projy0_fail_stack_stack_151->SetStats(0);
   prefit_projy0_fail_stack_stack_151->SetLineStyle(0);
   prefit_projy0_fail_stack_stack_151->GetXaxis()->SetLabelFont(42);
   prefit_projy0_fail_stack_stack_151->GetXaxis()->SetLabelOffset(0.007);
   prefit_projy0_fail_stack_stack_151->GetXaxis()->SetLabelSize(0.05);
   prefit_projy0_fail_stack_stack_151->GetXaxis()->SetTitleSize(0.08);
   prefit_projy0_fail_stack_stack_151->GetXaxis()->SetTitleOffset(0.9);
   prefit_projy0_fail_stack_stack_151->GetXaxis()->SetTitleFont(42);
   prefit_projy0_fail_stack_stack_151->GetYaxis()->SetNdivisions(508);
   prefit_projy0_fail_stack_stack_151->GetYaxis()->SetLabelFont(42);
   prefit_projy0_fail_stack_stack_151->GetYaxis()->SetLabelOffset(0.007);
   prefit_projy0_fail_stack_stack_151->GetYaxis()->SetLabelSize(0.05);
   prefit_projy0_fail_stack_stack_151->GetYaxis()->SetTitleSize(0.08);
   prefit_projy0_fail_stack_stack_151->GetYaxis()->SetTitleOffset(1.25);
   prefit_projy0_fail_stack_stack_151->GetYaxis()->SetTitleFont(42);
   prefit_projy0_fail_stack_stack_151->GetZaxis()->SetLabelFont(42);
   prefit_projy0_fail_stack_stack_151->GetZaxis()->SetLabelOffset(0.007);
   prefit_projy0_fail_stack_stack_151->GetZaxis()->SetLabelSize(0.05);
   prefit_projy0_fail_stack_stack_151->GetZaxis()->SetTitleSize(0.08);
   prefit_projy0_fail_stack_stack_151->GetZaxis()->SetTitleFont(42);
   prefit_projy0_fail_stack->SetHistogram(prefit_projy0_fail_stack_stack_151);
   
   Double_t xAxis828[2] = {50, 200}; 
   
   TH1D *Background_fail_prefit_projy0_stack_1 = new TH1D("Background_fail_prefit_projy0_stack_1","Background, fail, prefit, 0.0-0.24",1, xAxis828);
   Background_fail_prefit_projy0_stack_1->SetBinContent(1,1.40854e+07);
   Background_fail_prefit_projy0_stack_1->SetMinimum(0);
   Background_fail_prefit_projy0_stack_1->SetEntries(1.40854e+07);

   ci = TColor::GetColor("#ffff00");
   Background_fail_prefit_projy0_stack_1->SetFillColor(ci);

   ci = 1542;
   color = new TColor(ci, 1, 1, 1, " ", 0);
   Background_fail_prefit_projy0_stack_1->SetLineColor(ci);
   Background_fail_prefit_projy0_stack_1->SetLineStyle(0);
   Background_fail_prefit_projy0_stack_1->GetXaxis()->SetTitle("p_{T}");
   Background_fail_prefit_projy0_stack_1->GetXaxis()->SetLabelFont(42);
   Background_fail_prefit_projy0_stack_1->GetXaxis()->SetLabelOffset(0.007);
   Background_fail_prefit_projy0_stack_1->GetXaxis()->SetLabelSize(0.05);
   Background_fail_prefit_projy0_stack_1->GetXaxis()->SetTitleSize(0.08);
   Background_fail_prefit_projy0_stack_1->GetXaxis()->SetTitleOffset(1.25);
   Background_fail_prefit_projy0_stack_1->GetXaxis()->SetTitleFont(42);
   Background_fail_prefit_projy0_stack_1->GetYaxis()->SetTitle("Events / bin");
   Background_fail_prefit_projy0_stack_1->GetYaxis()->SetLabelFont(42);
   Background_fail_prefit_projy0_stack_1->GetYaxis()->SetLabelOffset(0.007);
   Background_fail_prefit_projy0_stack_1->GetYaxis()->SetLabelSize(0.05);
   Background_fail_prefit_projy0_stack_1->GetYaxis()->SetTitleSize(0.08);
   Background_fail_prefit_projy0_stack_1->GetYaxis()->SetTitleOffset(1.25);
   Background_fail_prefit_projy0_stack_1->GetYaxis()->SetTitleFont(42);
   Background_fail_prefit_projy0_stack_1->GetZaxis()->SetLabelFont(42);
   Background_fail_prefit_projy0_stack_1->GetZaxis()->SetLabelOffset(0.007);
   Background_fail_prefit_projy0_stack_1->GetZaxis()->SetLabelSize(0.05);
   Background_fail_prefit_projy0_stack_1->GetZaxis()->SetTitleSize(0.08);
   Background_fail_prefit_projy0_stack_1->GetZaxis()->SetTitleFont(42);
   prefit_projy0_fail_stack->Add(Background_fail_prefit_projy0_stack_1,"");
   prefit_projy0_fail_stack->Draw("hist same");
   
   prefit_projy0_fail_stack = new THStack();
   prefit_projy0_fail_stack->SetName("prefit_projy0_fail_stack");
   prefit_projy0_fail_stack->SetTitle("prefit_projy0_fail_stack");
   Double_t xAxis829[2] = {50, 200}; 
   
   TH1F *prefit_projy0_fail_stack_stack_151_stack_152 = new TH1F("prefit_projy0_fail_stack_stack_151_stack_152","prefit_projy0_fail_stack",1, xAxis829);
   prefit_projy0_fail_stack_stack_151_stack_152->SetMinimum(0);
   prefit_projy0_fail_stack_stack_151_stack_152->SetMaximum(1.478967e+07);
   prefit_projy0_fail_stack_stack_151_stack_152->SetDirectory(0);
   prefit_projy0_fail_stack_stack_151_stack_152->SetStats(0);
   prefit_projy0_fail_stack_stack_151_stack_152->SetLineStyle(0);
   prefit_projy0_fail_stack_stack_151_stack_152->GetXaxis()->SetLabelFont(42);
   prefit_projy0_fail_stack_stack_151_stack_152->GetXaxis()->SetLabelOffset(0.007);
   prefit_projy0_fail_stack_stack_151_stack_152->GetXaxis()->SetLabelSize(0.05);
   prefit_projy0_fail_stack_stack_151_stack_152->GetXaxis()->SetTitleSize(0.08);
   prefit_projy0_fail_stack_stack_151_stack_152->GetXaxis()->SetTitleOffset(0.9);
   prefit_projy0_fail_stack_stack_151_stack_152->GetXaxis()->SetTitleFont(42);
   prefit_projy0_fail_stack_stack_151_stack_152->GetYaxis()->SetNdivisions(508);
   prefit_projy0_fail_stack_stack_151_stack_152->GetYaxis()->SetLabelFont(42);
   prefit_projy0_fail_stack_stack_151_stack_152->GetYaxis()->SetLabelOffset(0.007);
   prefit_projy0_fail_stack_stack_151_stack_152->GetYaxis()->SetLabelSize(0.05);
   prefit_projy0_fail_stack_stack_151_stack_152->GetYaxis()->SetTitleSize(0.08);
   prefit_projy0_fail_stack_stack_151_stack_152->GetYaxis()->SetTitleOffset(1.25);
   prefit_projy0_fail_stack_stack_151_stack_152->GetYaxis()->SetTitleFont(42);
   prefit_projy0_fail_stack_stack_151_stack_152->GetZaxis()->SetLabelFont(42);
   prefit_projy0_fail_stack_stack_151_stack_152->GetZaxis()->SetLabelOffset(0.007);
   prefit_projy0_fail_stack_stack_151_stack_152->GetZaxis()->SetLabelSize(0.05);
   prefit_projy0_fail_stack_stack_151_stack_152->GetZaxis()->SetTitleSize(0.08);
   prefit_projy0_fail_stack_stack_151_stack_152->GetZaxis()->SetTitleFont(42);
   prefit_projy0_fail_stack->SetHistogram(prefit_projy0_fail_stack_stack_151_stack_152);
   
   Double_t xAxis830[2] = {50, 200}; 
   
   TH1D *Background_fail_prefit_projy0_stack_1_stack_1 = new TH1D("Background_fail_prefit_projy0_stack_1_stack_1","Background, fail, prefit, 0.0-0.24",1, xAxis830);
   Background_fail_prefit_projy0_stack_1_stack_1->SetBinContent(1,1.40854e+07);
   Background_fail_prefit_projy0_stack_1_stack_1->SetMinimum(0);
   Background_fail_prefit_projy0_stack_1_stack_1->SetEntries(1.40854e+07);

   ci = TColor::GetColor("#ffff00");
   Background_fail_prefit_projy0_stack_1_stack_1->SetFillColor(ci);

   ci = 1542;
   color = new TColor(ci, 1, 1, 1, " ", 0);
   Background_fail_prefit_projy0_stack_1_stack_1->SetLineColor(ci);
   Background_fail_prefit_projy0_stack_1_stack_1->SetLineStyle(0);
   Background_fail_prefit_projy0_stack_1_stack_1->GetXaxis()->SetTitle("p_{T}");
   Background_fail_prefit_projy0_stack_1_stack_1->GetXaxis()->SetLabelFont(42);
   Background_fail_prefit_projy0_stack_1_stack_1->GetXaxis()->SetLabelOffset(0.007);
   Background_fail_prefit_projy0_stack_1_stack_1->GetXaxis()->SetLabelSize(0.05);
   Background_fail_prefit_projy0_stack_1_stack_1->GetXaxis()->SetTitleSize(0.08);
   Background_fail_prefit_projy0_stack_1_stack_1->GetXaxis()->SetTitleOffset(1.25);
   Background_fail_prefit_projy0_stack_1_stack_1->GetXaxis()->SetTitleFont(42);
   Background_fail_prefit_projy0_stack_1_stack_1->GetYaxis()->SetTitle("Events / bin");
   Background_fail_prefit_projy0_stack_1_stack_1->GetYaxis()->SetLabelFont(42);
   Background_fail_prefit_projy0_stack_1_stack_1->GetYaxis()->SetLabelOffset(0.007);
   Background_fail_prefit_projy0_stack_1_stack_1->GetYaxis()->SetLabelSize(0.05);
   Background_fail_prefit_projy0_stack_1_stack_1->GetYaxis()->SetTitleSize(0.08);
   Background_fail_prefit_projy0_stack_1_stack_1->GetYaxis()->SetTitleOffset(1.25);
   Background_fail_prefit_projy0_stack_1_stack_1->GetYaxis()->SetTitleFont(42);
   Background_fail_prefit_projy0_stack_1_stack_1->GetZaxis()->SetLabelFont(42);
   Background_fail_prefit_projy0_stack_1_stack_1->GetZaxis()->SetLabelOffset(0.007);
   Background_fail_prefit_projy0_stack_1_stack_1->GetZaxis()->SetLabelSize(0.05);
   Background_fail_prefit_projy0_stack_1_stack_1->GetZaxis()->SetTitleSize(0.08);
   Background_fail_prefit_projy0_stack_1_stack_1->GetZaxis()->SetTitleFont(42);
   prefit_projy0_fail_stack->Add(Background_fail_prefit_projy0_stack_1_stack_1,"");
   prefit_projy0_fail_stack->Draw("hist same");
   Double_t xAxis831[2] = {50, 200}; 
   
   TH1D *Signal_ppStaumI557_fail_prefit_projy0__527 = new TH1D("Signal_ppStaumI557_fail_prefit_projy0__527","HSCP signal, fail, prefit, 0.0-0.24",1, xAxis831);
   Signal_ppStaumI557_fail_prefit_projy0__527->SetBinContent(1,0.000411045);
   Signal_ppStaumI557_fail_prefit_projy0__527->SetBinError(1,3.743176e-05);
   Signal_ppStaumI557_fail_prefit_projy0__527->SetMinimum(0);
   Signal_ppStaumI557_fail_prefit_projy0__527->SetEntries(120.5864);
   Signal_ppStaumI557_fail_prefit_projy0__527->SetLineColor(2);
   Signal_ppStaumI557_fail_prefit_projy0__527->SetLineStyle(0);
   Signal_ppStaumI557_fail_prefit_projy0__527->GetXaxis()->SetTitle("p_{T}");
   Signal_ppStaumI557_fail_prefit_projy0__527->GetXaxis()->SetLabelFont(42);
   Signal_ppStaumI557_fail_prefit_projy0__527->GetXaxis()->SetLabelOffset(0.007);
   Signal_ppStaumI557_fail_prefit_projy0__527->GetXaxis()->SetLabelSize(0.05);
   Signal_ppStaumI557_fail_prefit_projy0__527->GetXaxis()->SetTitleSize(0.08);
   Signal_ppStaumI557_fail_prefit_projy0__527->GetXaxis()->SetTitleOffset(1.25);
   Signal_ppStaumI557_fail_prefit_projy0__527->GetXaxis()->SetTitleFont(42);
   Signal_ppStaumI557_fail_prefit_projy0__527->GetYaxis()->SetTitle("Events / bin");
   Signal_ppStaumI557_fail_prefit_projy0__527->GetYaxis()->SetLabelFont(42);
   Signal_ppStaumI557_fail_prefit_projy0__527->GetYaxis()->SetLabelOffset(0.007);
   Signal_ppStaumI557_fail_prefit_projy0__527->GetYaxis()->SetLabelSize(0.05);
   Signal_ppStaumI557_fail_prefit_projy0__527->GetYaxis()->SetTitleSize(0.08);
   Signal_ppStaumI557_fail_prefit_projy0__527->GetYaxis()->SetTitleOffset(1.25);
   Signal_ppStaumI557_fail_prefit_projy0__527->GetYaxis()->SetTitleFont(42);
   Signal_ppStaumI557_fail_prefit_projy0__527->GetZaxis()->SetLabelFont(42);
   Signal_ppStaumI557_fail_prefit_projy0__527->GetZaxis()->SetLabelOffset(0.007);
   Signal_ppStaumI557_fail_prefit_projy0__527->GetZaxis()->SetLabelSize(0.05);
   Signal_ppStaumI557_fail_prefit_projy0__527->GetZaxis()->SetTitleSize(0.08);
   Signal_ppStaumI557_fail_prefit_projy0__527->GetZaxis()->SetTitleFont(42);
   Signal_ppStaumI557_fail_prefit_projy0__527->Draw("hist same");
   Double_t xAxis832[2] = {50, 200}; 
   
   TH1D *TotalBkg_fail_prefit_projy0__528 = new TH1D("TotalBkg_fail_prefit_projy0__528","TotalBkg, fail, prefit, 0.0-0.24",1, xAxis832);
   TotalBkg_fail_prefit_projy0__528->SetBinContent(1,1.40854e+07);
   TotalBkg_fail_prefit_projy0__528->SetMinimum(0);
   TotalBkg_fail_prefit_projy0__528->SetEntries(1.40854e+07);
   TotalBkg_fail_prefit_projy0__528->SetLineStyle(0);
   TotalBkg_fail_prefit_projy0__528->SetMarkerStyle(0);
   TotalBkg_fail_prefit_projy0__528->GetXaxis()->SetTitle("p_{T}");
   TotalBkg_fail_prefit_projy0__528->GetXaxis()->SetLabelFont(42);
   TotalBkg_fail_prefit_projy0__528->GetXaxis()->SetLabelOffset(0.007);
   TotalBkg_fail_prefit_projy0__528->GetXaxis()->SetLabelSize(0.05);
   TotalBkg_fail_prefit_projy0__528->GetXaxis()->SetTitleSize(0.08);
   TotalBkg_fail_prefit_projy0__528->GetXaxis()->SetTitleOffset(1.25);
   TotalBkg_fail_prefit_projy0__528->GetXaxis()->SetTitleFont(42);
   TotalBkg_fail_prefit_projy0__528->GetYaxis()->SetTitle("Events / bin");
   TotalBkg_fail_prefit_projy0__528->GetYaxis()->SetLabelFont(42);
   TotalBkg_fail_prefit_projy0__528->GetYaxis()->SetLabelOffset(0.007);
   TotalBkg_fail_prefit_projy0__528->GetYaxis()->SetLabelSize(0.05);
   TotalBkg_fail_prefit_projy0__528->GetYaxis()->SetTitleSize(0.08);
   TotalBkg_fail_prefit_projy0__528->GetYaxis()->SetTitleOffset(1.25);
   TotalBkg_fail_prefit_projy0__528->GetYaxis()->SetTitleFont(42);
   TotalBkg_fail_prefit_projy0__528->GetZaxis()->SetLabelFont(42);
   TotalBkg_fail_prefit_projy0__528->GetZaxis()->SetLabelOffset(0.007);
   TotalBkg_fail_prefit_projy0__528->GetZaxis()->SetLabelSize(0.05);
   TotalBkg_fail_prefit_projy0__528->GetZaxis()->SetTitleSize(0.08);
   TotalBkg_fail_prefit_projy0__528->GetZaxis()->SetTitleFont(42);
   TotalBkg_fail_prefit_projy0__528->Draw("hist same");
   Double_t xAxis833[2] = {50, 200}; 
   
   TH1D *TotalBkg_fail_prefit_projy0__529 = new TH1D("TotalBkg_fail_prefit_projy0__529","TotalBkg, fail, prefit, 0.0-0.24",1, xAxis833);
   TotalBkg_fail_prefit_projy0__529->SetBinContent(1,1.40854e+07);
   TotalBkg_fail_prefit_projy0__529->SetMinimum(0);
   TotalBkg_fail_prefit_projy0__529->SetEntries(1.40854e+07);
   TotalBkg_fail_prefit_projy0__529->SetFillColor(1);
   TotalBkg_fail_prefit_projy0__529->SetFillStyle(3354);
   TotalBkg_fail_prefit_projy0__529->SetLineStyle(0);
   TotalBkg_fail_prefit_projy0__529->SetLineWidth(0);
   TotalBkg_fail_prefit_projy0__529->SetMarkerStyle(0);
   TotalBkg_fail_prefit_projy0__529->GetXaxis()->SetTitle("p_{T}");
   TotalBkg_fail_prefit_projy0__529->GetXaxis()->SetLabelFont(42);
   TotalBkg_fail_prefit_projy0__529->GetXaxis()->SetLabelOffset(0.007);
   TotalBkg_fail_prefit_projy0__529->GetXaxis()->SetLabelSize(0.05);
   TotalBkg_fail_prefit_projy0__529->GetXaxis()->SetTitleSize(0.08);
   TotalBkg_fail_prefit_projy0__529->GetXaxis()->SetTitleOffset(1.25);
   TotalBkg_fail_prefit_projy0__529->GetXaxis()->SetTitleFont(42);
   TotalBkg_fail_prefit_projy0__529->GetYaxis()->SetTitle("Events / bin");
   TotalBkg_fail_prefit_projy0__529->GetYaxis()->SetLabelFont(42);
   TotalBkg_fail_prefit_projy0__529->GetYaxis()->SetLabelOffset(0.007);
   TotalBkg_fail_prefit_projy0__529->GetYaxis()->SetLabelSize(0.05);
   TotalBkg_fail_prefit_projy0__529->GetYaxis()->SetTitleSize(0.08);
   TotalBkg_fail_prefit_projy0__529->GetYaxis()->SetTitleOffset(1.25);
   TotalBkg_fail_prefit_projy0__529->GetYaxis()->SetTitleFont(42);
   TotalBkg_fail_prefit_projy0__529->GetZaxis()->SetLabelFont(42);
   TotalBkg_fail_prefit_projy0__529->GetZaxis()->SetLabelOffset(0.007);
   TotalBkg_fail_prefit_projy0__529->GetZaxis()->SetLabelSize(0.05);
   TotalBkg_fail_prefit_projy0__529->GetZaxis()->SetTitleSize(0.08);
   TotalBkg_fail_prefit_projy0__529->GetZaxis()->SetTitleFont(42);
   TotalBkg_fail_prefit_projy0__529->Draw("e2 same");
   Double_t xAxis834[2] = {50, 200}; 
   
   TH1D *data_obs_fail_prefit_projy0__530 = new TH1D("data_obs_fail_prefit_projy0__530","",1, xAxis834);
   data_obs_fail_prefit_projy0__530->SetBinContent(1,1.40854e+07);
   data_obs_fail_prefit_projy0__530->SetBinError(1,3753.052);
   data_obs_fail_prefit_projy0__530->SetMinimum(0);
   data_obs_fail_prefit_projy0__530->SetMaximum(1.901528e+07);
   data_obs_fail_prefit_projy0__530->SetEntries(1.40854e+07);

   ci = TColor::GetColor("#000000");
   data_obs_fail_prefit_projy0__530->SetLineColor(ci);
   data_obs_fail_prefit_projy0__530->SetLineStyle(0);

   ci = TColor::GetColor("#000000");
   data_obs_fail_prefit_projy0__530->SetMarkerColor(ci);
   data_obs_fail_prefit_projy0__530->SetMarkerStyle(8);
   data_obs_fail_prefit_projy0__530->GetXaxis()->SetTitle("p_{T}");
   data_obs_fail_prefit_projy0__530->GetXaxis()->SetLabelFont(42);
   data_obs_fail_prefit_projy0__530->GetXaxis()->SetLabelOffset(0.05);
   data_obs_fail_prefit_projy0__530->GetXaxis()->SetLabelSize(0.07);
   data_obs_fail_prefit_projy0__530->GetXaxis()->SetTitleSize(0.09);
   data_obs_fail_prefit_projy0__530->GetXaxis()->SetTitleOffset(1.15);
   data_obs_fail_prefit_projy0__530->GetXaxis()->SetTitleFont(42);
   data_obs_fail_prefit_projy0__530->GetYaxis()->SetTitle("Events / bin");
   data_obs_fail_prefit_projy0__530->GetYaxis()->SetNdivisions(508);
   data_obs_fail_prefit_projy0__530->GetYaxis()->SetLabelFont(42);
   data_obs_fail_prefit_projy0__530->GetYaxis()->SetLabelOffset(0.007);
   data_obs_fail_prefit_projy0__530->GetYaxis()->SetLabelSize(0.07);
   data_obs_fail_prefit_projy0__530->GetYaxis()->SetTitleSize(0.09);
   data_obs_fail_prefit_projy0__530->GetYaxis()->SetTitleOffset(0.8);
   data_obs_fail_prefit_projy0__530->GetYaxis()->SetTitleFont(42);
   data_obs_fail_prefit_projy0__530->GetZaxis()->SetLabelFont(42);
   data_obs_fail_prefit_projy0__530->GetZaxis()->SetLabelOffset(0.007);
   data_obs_fail_prefit_projy0__530->GetZaxis()->SetLabelSize(0.05);
   data_obs_fail_prefit_projy0__530->GetZaxis()->SetTitleSize(0.08);
   data_obs_fail_prefit_projy0__530->GetZaxis()->SetTitleFont(42);
   data_obs_fail_prefit_projy0__530->Draw("pe X0 same");
   
   TLegend *leg = new TLegend(0.65,0.64,0.9,0.88,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(1001);
   TLegendEntry *entry=leg->AddEntry("data_obs_fail_prefit_projy0","Data","pe X0");

   ci = TColor::GetColor("#000000");
   entry->SetLineColor(ci);
   entry->SetLineWidth(1);

   ci = TColor::GetColor("#000000");
   entry->SetMarkerColor(ci);
   entry->SetMarkerStyle(8);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("TotalBkg_fail_prefit_projy0","Total bkg unc.","F");
   entry->SetFillColor(1);
   entry->SetFillStyle(3354);
   entry->SetLineColor(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("Signal_ppStau-557_fail_prefit_projy0","HSCP signal","L");
   entry->SetLineColor(2);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("Background_fail_prefit_projy0_stack_1_stack_1","Background","f");

   ci = TColor::GetColor("#ffff00");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = 1542;
   color = new TColor(ci, 1, 1, 1, " ", 0);
   entry->SetLineColor(ci);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   leg->Draw();
   Double_t xAxis835[2] = {50, 200}; 
   
   TH1D *data_obs_fail_prefit_projy0_copy__531 = new TH1D("data_obs_fail_prefit_projy0_copy__531","",1, xAxis835);
   data_obs_fail_prefit_projy0_copy__531->SetBinContent(1,1.40854e+07);
   data_obs_fail_prefit_projy0_copy__531->SetBinError(1,3753.052);
   data_obs_fail_prefit_projy0_copy__531->SetMinimum(0);
   data_obs_fail_prefit_projy0_copy__531->SetMaximum(1.901528e+07);
   data_obs_fail_prefit_projy0_copy__531->SetEntries(1.40854e+07);
   data_obs_fail_prefit_projy0_copy__531->SetDirectory(0);

   ci = TColor::GetColor("#000000");
   data_obs_fail_prefit_projy0_copy__531->SetLineColor(ci);
   data_obs_fail_prefit_projy0_copy__531->SetLineStyle(0);

   ci = TColor::GetColor("#000000");
   data_obs_fail_prefit_projy0_copy__531->SetMarkerColor(ci);
   data_obs_fail_prefit_projy0_copy__531->SetMarkerStyle(8);
   data_obs_fail_prefit_projy0_copy__531->GetXaxis()->SetTitle("p_{T}");
   data_obs_fail_prefit_projy0_copy__531->GetXaxis()->SetLabelFont(42);
   data_obs_fail_prefit_projy0_copy__531->GetXaxis()->SetLabelOffset(0.05);
   data_obs_fail_prefit_projy0_copy__531->GetXaxis()->SetLabelSize(0.07);
   data_obs_fail_prefit_projy0_copy__531->GetXaxis()->SetTitleSize(0.09);
   data_obs_fail_prefit_projy0_copy__531->GetXaxis()->SetTitleOffset(1.15);
   data_obs_fail_prefit_projy0_copy__531->GetXaxis()->SetTitleFont(42);
   data_obs_fail_prefit_projy0_copy__531->GetYaxis()->SetTitle("Events / bin");
   data_obs_fail_prefit_projy0_copy__531->GetYaxis()->SetNdivisions(508);
   data_obs_fail_prefit_projy0_copy__531->GetYaxis()->SetLabelFont(42);
   data_obs_fail_prefit_projy0_copy__531->GetYaxis()->SetLabelOffset(0.007);
   data_obs_fail_prefit_projy0_copy__531->GetYaxis()->SetLabelSize(0.07);
   data_obs_fail_prefit_projy0_copy__531->GetYaxis()->SetTitleSize(0.09);
   data_obs_fail_prefit_projy0_copy__531->GetYaxis()->SetTitleOffset(0.8);
   data_obs_fail_prefit_projy0_copy__531->GetYaxis()->SetTitleFont(42);
   data_obs_fail_prefit_projy0_copy__531->GetZaxis()->SetLabelFont(42);
   data_obs_fail_prefit_projy0_copy__531->GetZaxis()->SetLabelOffset(0.007);
   data_obs_fail_prefit_projy0_copy__531->GetZaxis()->SetLabelSize(0.05);
   data_obs_fail_prefit_projy0_copy__531->GetZaxis()->SetTitleSize(0.08);
   data_obs_fail_prefit_projy0_copy__531->GetZaxis()->SetTitleFont(42);
   data_obs_fail_prefit_projy0_copy__531->Draw("sameaxis");
   TLatex *   tex = new TLatex(0.21,0.83,"55 < p_{T} < 200 GeV, F^{Pixels}_{i} < 0.9");
tex->SetNDC();
   tex->SetTextAlign(12);
   tex->SetTextFont(42);
   tex->SetTextSize(0.06);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.17,0.92,"CMS");
tex->SetNDC();
   tex->SetTextFont(61);
   tex->SetTextSize(0.0675);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.25,0.92,"Preliminary");
tex->SetNDC();
   tex->SetTextFont(52);
   tex->SetTextSize(0.0485);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.95,0.92,"101 fb^{-1} (13 TeV)");
tex->SetNDC();
   tex->SetTextAlign(31);
   tex->SetTextFont(42);
   tex->SetTextSize(0.07);
   tex->SetLineWidth(2);
   tex->Draw();
   data_obs_fail_prefit_projy0_main->Modified();
   plots_fit_s/base_figs/prefit_projy0_fail->cd();
  
// ------------>Primitives in pad: data_obs_fail_prefit_projy0_sub
   TPad *data_obs_fail_prefit_projy0_sub = new TPad("data_obs_fail_prefit_projy0_sub", "data_obs_fail_prefit_projy0_sub",0,0,1,0.35);
   data_obs_fail_prefit_projy0_sub->Draw();
   data_obs_fail_prefit_projy0_sub->cd();
   data_obs_fail_prefit_projy0_sub->Range(17.30769,-6.023077,209.6154,2.9);
   data_obs_fail_prefit_projy0_sub->SetFillColor(0);
   data_obs_fail_prefit_projy0_sub->SetBorderMode(0);
   data_obs_fail_prefit_projy0_sub->SetBorderSize(2);
   data_obs_fail_prefit_projy0_sub->SetTickx(1);
   data_obs_fail_prefit_projy0_sub->SetTicky(1);
   data_obs_fail_prefit_projy0_sub->SetLeftMargin(0.17);
   data_obs_fail_prefit_projy0_sub->SetRightMargin(0.05);
   data_obs_fail_prefit_projy0_sub->SetTopMargin(0);
   data_obs_fail_prefit_projy0_sub->SetBottomMargin(0.35);
   data_obs_fail_prefit_projy0_sub->SetFrameFillStyle(0);
   data_obs_fail_prefit_projy0_sub->SetFrameBorderMode(0);
   data_obs_fail_prefit_projy0_sub->SetFrameFillStyle(0);
   data_obs_fail_prefit_projy0_sub->SetFrameBorderMode(0);
   Double_t xAxis836[2] = {50, 200}; 
   
   TH1D *data_obs_fail_prefit_projy0_pull__532 = new TH1D("data_obs_fail_prefit_projy0_pull__532","",1, xAxis836);
   data_obs_fail_prefit_projy0_pull__532->SetBinContent(1,-1.040542e-06);
   data_obs_fail_prefit_projy0_pull__532->SetBinError(1,3753.052);
   data_obs_fail_prefit_projy0_pull__532->SetMinimum(-2.9);
   data_obs_fail_prefit_projy0_pull__532->SetMaximum(2.9);
   data_obs_fail_prefit_projy0_pull__532->SetEntries(1.003906);
   data_obs_fail_prefit_projy0_pull__532->SetStats(0);

   ci = TColor::GetColor("#0000ff");
   data_obs_fail_prefit_projy0_pull__532->SetFillColor(ci);

   ci = TColor::GetColor("#000000");
   data_obs_fail_prefit_projy0_pull__532->SetLineColor(ci);
   data_obs_fail_prefit_projy0_pull__532->SetLineStyle(0);

   ci = TColor::GetColor("#000000");
   data_obs_fail_prefit_projy0_pull__532->SetMarkerColor(ci);
   data_obs_fail_prefit_projy0_pull__532->SetMarkerStyle(8);
   data_obs_fail_prefit_projy0_pull__532->GetXaxis()->SetTitle("p_{T}");
   data_obs_fail_prefit_projy0_pull__532->GetXaxis()->SetLabelFont(42);
   data_obs_fail_prefit_projy0_pull__532->GetXaxis()->SetLabelOffset(0.05);
   data_obs_fail_prefit_projy0_pull__532->GetXaxis()->SetLabelSize(0.13);
   data_obs_fail_prefit_projy0_pull__532->GetXaxis()->SetTitleSize(0.15);
   data_obs_fail_prefit_projy0_pull__532->GetXaxis()->SetTitleOffset(1.15);
   data_obs_fail_prefit_projy0_pull__532->GetXaxis()->SetTitleFont(42);
   data_obs_fail_prefit_projy0_pull__532->GetYaxis()->SetTitle("(Data-Bkg)/#sigma");
   data_obs_fail_prefit_projy0_pull__532->GetYaxis()->SetNdivisions(306);
   data_obs_fail_prefit_projy0_pull__532->GetYaxis()->SetLabelFont(42);
   data_obs_fail_prefit_projy0_pull__532->GetYaxis()->SetLabelOffset(0.007);
   data_obs_fail_prefit_projy0_pull__532->GetYaxis()->SetLabelSize(0.13);
   data_obs_fail_prefit_projy0_pull__532->GetYaxis()->SetTitleSize(0.12);
   data_obs_fail_prefit_projy0_pull__532->GetYaxis()->SetTitleOffset(0.4);
   data_obs_fail_prefit_projy0_pull__532->GetYaxis()->SetTitleFont(42);
   data_obs_fail_prefit_projy0_pull__532->GetZaxis()->SetLabelFont(42);
   data_obs_fail_prefit_projy0_pull__532->GetZaxis()->SetLabelOffset(0.007);
   data_obs_fail_prefit_projy0_pull__532->GetZaxis()->SetLabelSize(0.05);
   data_obs_fail_prefit_projy0_pull__532->GetZaxis()->SetTitleSize(0.08);
   data_obs_fail_prefit_projy0_pull__532->GetZaxis()->SetTitleFont(42);
   data_obs_fail_prefit_projy0_pull__532->Draw("hist");
   data_obs_fail_prefit_projy0_sub->Modified();
   plots_fit_s/base_figs/prefit_projy0_fail->cd();
   plots_fit_s/base_figs/prefit_projy0_fail->Modified();
   plots_fit_s/base_figs/prefit_projy0_fail->cd();
   plots_fit_s/base_figs/prefit_projy0_fail->SetSelected(plots_fit_s/base_figs/prefit_projy0_fail);
}
