void prefit_projy2_fail()
{
//=========Macro generated from canvas: plots_fit_s/base_figs/prefit_projy2_fail/plots_fit_s/base_figs/prefit_projy2_fail
//=========  (Fri Jan 12 21:00:34 2024) by ROOT version 6.14/09
   TCanvas *plots_fit_s/base_figs/prefit_projy2_fail = new TCanvas("plots_fit_s/base_figs/prefit_projy2_fail", "plots_fit_s/base_figs/prefit_projy2_fail",0,0,800,700);
   gStyle->SetOptFit(1);
   gStyle->SetOptStat(0);
   plots_fit_s/base_figs/prefit_projy2_fail->SetHighLightColor(2);
   plots_fit_s/base_figs/prefit_projy2_fail->Range(0,0,1,1);
   plots_fit_s/base_figs/prefit_projy2_fail->SetFillColor(0);
   plots_fit_s/base_figs/prefit_projy2_fail->SetBorderMode(0);
   plots_fit_s/base_figs/prefit_projy2_fail->SetBorderSize(2);
   plots_fit_s/base_figs/prefit_projy2_fail->SetTickx(1);
   plots_fit_s/base_figs/prefit_projy2_fail->SetTicky(1);
   plots_fit_s/base_figs/prefit_projy2_fail->SetLeftMargin(0.16);
   plots_fit_s/base_figs/prefit_projy2_fail->SetRightMargin(0);
   plots_fit_s/base_figs/prefit_projy2_fail->SetTopMargin(0);
   plots_fit_s/base_figs/prefit_projy2_fail->SetBottomMargin(0);
   plots_fit_s/base_figs/prefit_projy2_fail->SetFrameFillStyle(0);
   plots_fit_s/base_figs/prefit_projy2_fail->SetFrameBorderMode(0);
  
// ------------>Primitives in pad: data_obs_fail_prefit_projy2_main
   TPad *data_obs_fail_prefit_projy2_main = new TPad("data_obs_fail_prefit_projy2_main", "data_obs_fail_prefit_projy2_main",0,0.35,1,1);
   data_obs_fail_prefit_projy2_main->Draw();
   data_obs_fail_prefit_projy2_main->cd();
   data_obs_fail_prefit_projy2_main->Range(17.30769,-0.04651163,209.6154,1.116279);
   data_obs_fail_prefit_projy2_main->SetFillColor(0);
   data_obs_fail_prefit_projy2_main->SetBorderMode(0);
   data_obs_fail_prefit_projy2_main->SetBorderSize(2);
   data_obs_fail_prefit_projy2_main->SetTickx(1);
   data_obs_fail_prefit_projy2_main->SetTicky(1);
   data_obs_fail_prefit_projy2_main->SetLeftMargin(0.17);
   data_obs_fail_prefit_projy2_main->SetRightMargin(0.05);
   data_obs_fail_prefit_projy2_main->SetBottomMargin(0.04);
   data_obs_fail_prefit_projy2_main->SetFrameFillStyle(0);
   data_obs_fail_prefit_projy2_main->SetFrameBorderMode(0);
   data_obs_fail_prefit_projy2_main->SetFrameFillStyle(0);
   data_obs_fail_prefit_projy2_main->SetFrameBorderMode(0);
   Double_t xAxis848[2] = {50, 200}; 
   
   TH1D *data_obs_fail_prefit_projy2__540 = new TH1D("data_obs_fail_prefit_projy2__540","",1, xAxis848);
   data_obs_fail_prefit_projy2__540->SetMinimum(0);
   data_obs_fail_prefit_projy2__540->SetMaximum(0);

   Int_t ci;      // for color index setting
   TColor *color; // for color definition with alpha
   ci = TColor::GetColor("#000000");
   data_obs_fail_prefit_projy2__540->SetLineColor(ci);
   data_obs_fail_prefit_projy2__540->SetLineStyle(0);

   ci = TColor::GetColor("#000000");
   data_obs_fail_prefit_projy2__540->SetMarkerColor(ci);
   data_obs_fail_prefit_projy2__540->SetMarkerStyle(8);
   data_obs_fail_prefit_projy2__540->GetXaxis()->SetTitle("p_{T}");
   data_obs_fail_prefit_projy2__540->GetXaxis()->SetLabelFont(42);
   data_obs_fail_prefit_projy2__540->GetXaxis()->SetLabelOffset(0.05);
   data_obs_fail_prefit_projy2__540->GetXaxis()->SetLabelSize(0.07);
   data_obs_fail_prefit_projy2__540->GetXaxis()->SetTitleSize(0.09);
   data_obs_fail_prefit_projy2__540->GetXaxis()->SetTitleOffset(1.15);
   data_obs_fail_prefit_projy2__540->GetXaxis()->SetTitleFont(42);
   data_obs_fail_prefit_projy2__540->GetYaxis()->SetTitle("Events / bin");
   data_obs_fail_prefit_projy2__540->GetYaxis()->SetNdivisions(508);
   data_obs_fail_prefit_projy2__540->GetYaxis()->SetLabelFont(42);
   data_obs_fail_prefit_projy2__540->GetYaxis()->SetLabelOffset(0.007);
   data_obs_fail_prefit_projy2__540->GetYaxis()->SetLabelSize(0.07);
   data_obs_fail_prefit_projy2__540->GetYaxis()->SetTitleSize(0.09);
   data_obs_fail_prefit_projy2__540->GetYaxis()->SetTitleOffset(0.8);
   data_obs_fail_prefit_projy2__540->GetYaxis()->SetTitleFont(42);
   data_obs_fail_prefit_projy2__540->GetZaxis()->SetLabelFont(42);
   data_obs_fail_prefit_projy2__540->GetZaxis()->SetLabelOffset(0.007);
   data_obs_fail_prefit_projy2__540->GetZaxis()->SetLabelSize(0.05);
   data_obs_fail_prefit_projy2__540->GetZaxis()->SetTitleSize(0.08);
   data_obs_fail_prefit_projy2__540->GetZaxis()->SetTitleFont(42);
   data_obs_fail_prefit_projy2__540->Draw("pe X0");
   
   THStack *prefit_projy2_fail_stack = new THStack();
   prefit_projy2_fail_stack->SetName("prefit_projy2_fail_stack");
   prefit_projy2_fail_stack->SetTitle("prefit_projy2_fail_stack");
   Double_t xAxis849[2] = {50, 200}; 
   
   TH1F *prefit_projy2_fail_stack_stack_155 = new TH1F("prefit_projy2_fail_stack_stack_155","prefit_projy2_fail_stack",1, xAxis849);
   prefit_projy2_fail_stack_stack_155->SetMinimum(0);
   prefit_projy2_fail_stack_stack_155->SetMaximum(0);
   prefit_projy2_fail_stack_stack_155->SetDirectory(0);
   prefit_projy2_fail_stack_stack_155->SetStats(0);
   prefit_projy2_fail_stack_stack_155->SetLineStyle(0);
   prefit_projy2_fail_stack_stack_155->GetXaxis()->SetLabelFont(42);
   prefit_projy2_fail_stack_stack_155->GetXaxis()->SetLabelOffset(0.007);
   prefit_projy2_fail_stack_stack_155->GetXaxis()->SetLabelSize(0.05);
   prefit_projy2_fail_stack_stack_155->GetXaxis()->SetTitleSize(0.08);
   prefit_projy2_fail_stack_stack_155->GetXaxis()->SetTitleOffset(0.9);
   prefit_projy2_fail_stack_stack_155->GetXaxis()->SetTitleFont(42);
   prefit_projy2_fail_stack_stack_155->GetYaxis()->SetNdivisions(508);
   prefit_projy2_fail_stack_stack_155->GetYaxis()->SetLabelFont(42);
   prefit_projy2_fail_stack_stack_155->GetYaxis()->SetLabelOffset(0.007);
   prefit_projy2_fail_stack_stack_155->GetYaxis()->SetLabelSize(0.05);
   prefit_projy2_fail_stack_stack_155->GetYaxis()->SetTitleSize(0.08);
   prefit_projy2_fail_stack_stack_155->GetYaxis()->SetTitleOffset(1.25);
   prefit_projy2_fail_stack_stack_155->GetYaxis()->SetTitleFont(42);
   prefit_projy2_fail_stack_stack_155->GetZaxis()->SetLabelFont(42);
   prefit_projy2_fail_stack_stack_155->GetZaxis()->SetLabelOffset(0.007);
   prefit_projy2_fail_stack_stack_155->GetZaxis()->SetLabelSize(0.05);
   prefit_projy2_fail_stack_stack_155->GetZaxis()->SetTitleSize(0.08);
   prefit_projy2_fail_stack_stack_155->GetZaxis()->SetTitleFont(42);
   prefit_projy2_fail_stack->SetHistogram(prefit_projy2_fail_stack_stack_155);
   
   Double_t xAxis850[2] = {50, 200}; 
   
   TH1D *Background_fail_prefit_projy2_stack_1 = new TH1D("Background_fail_prefit_projy2_stack_1","Background, fail, prefit, 1.0-1.0",1, xAxis850);
   Background_fail_prefit_projy2_stack_1->SetMinimum(0);

   ci = TColor::GetColor("#ffff00");
   Background_fail_prefit_projy2_stack_1->SetFillColor(ci);

   ci = 1544;
   color = new TColor(ci, 1, 1, 1, " ", 0);
   Background_fail_prefit_projy2_stack_1->SetLineColor(ci);
   Background_fail_prefit_projy2_stack_1->SetLineStyle(0);
   Background_fail_prefit_projy2_stack_1->GetXaxis()->SetTitle("p_{T}");
   Background_fail_prefit_projy2_stack_1->GetXaxis()->SetLabelFont(42);
   Background_fail_prefit_projy2_stack_1->GetXaxis()->SetLabelOffset(0.007);
   Background_fail_prefit_projy2_stack_1->GetXaxis()->SetLabelSize(0.05);
   Background_fail_prefit_projy2_stack_1->GetXaxis()->SetTitleSize(0.08);
   Background_fail_prefit_projy2_stack_1->GetXaxis()->SetTitleOffset(1.25);
   Background_fail_prefit_projy2_stack_1->GetXaxis()->SetTitleFont(42);
   Background_fail_prefit_projy2_stack_1->GetYaxis()->SetTitle("Events / bin");
   Background_fail_prefit_projy2_stack_1->GetYaxis()->SetLabelFont(42);
   Background_fail_prefit_projy2_stack_1->GetYaxis()->SetLabelOffset(0.007);
   Background_fail_prefit_projy2_stack_1->GetYaxis()->SetLabelSize(0.05);
   Background_fail_prefit_projy2_stack_1->GetYaxis()->SetTitleSize(0.08);
   Background_fail_prefit_projy2_stack_1->GetYaxis()->SetTitleOffset(1.25);
   Background_fail_prefit_projy2_stack_1->GetYaxis()->SetTitleFont(42);
   Background_fail_prefit_projy2_stack_1->GetZaxis()->SetLabelFont(42);
   Background_fail_prefit_projy2_stack_1->GetZaxis()->SetLabelOffset(0.007);
   Background_fail_prefit_projy2_stack_1->GetZaxis()->SetLabelSize(0.05);
   Background_fail_prefit_projy2_stack_1->GetZaxis()->SetTitleSize(0.08);
   Background_fail_prefit_projy2_stack_1->GetZaxis()->SetTitleFont(42);
   prefit_projy2_fail_stack->Add(Background_fail_prefit_projy2_stack_1,"");
   prefit_projy2_fail_stack->Draw("hist same");
   
   prefit_projy2_fail_stack = new THStack();
   prefit_projy2_fail_stack->SetName("prefit_projy2_fail_stack");
   prefit_projy2_fail_stack->SetTitle("prefit_projy2_fail_stack");
   Double_t xAxis851[2] = {50, 200}; 
   
   TH1F *prefit_projy2_fail_stack_stack_155_stack_156 = new TH1F("prefit_projy2_fail_stack_stack_155_stack_156","prefit_projy2_fail_stack",1, xAxis851);
   prefit_projy2_fail_stack_stack_155_stack_156->SetMinimum(0);
   prefit_projy2_fail_stack_stack_155_stack_156->SetMaximum(0);
   prefit_projy2_fail_stack_stack_155_stack_156->SetDirectory(0);
   prefit_projy2_fail_stack_stack_155_stack_156->SetStats(0);
   prefit_projy2_fail_stack_stack_155_stack_156->SetLineStyle(0);
   prefit_projy2_fail_stack_stack_155_stack_156->GetXaxis()->SetLabelFont(42);
   prefit_projy2_fail_stack_stack_155_stack_156->GetXaxis()->SetLabelOffset(0.007);
   prefit_projy2_fail_stack_stack_155_stack_156->GetXaxis()->SetLabelSize(0.05);
   prefit_projy2_fail_stack_stack_155_stack_156->GetXaxis()->SetTitleSize(0.08);
   prefit_projy2_fail_stack_stack_155_stack_156->GetXaxis()->SetTitleOffset(0.9);
   prefit_projy2_fail_stack_stack_155_stack_156->GetXaxis()->SetTitleFont(42);
   prefit_projy2_fail_stack_stack_155_stack_156->GetYaxis()->SetNdivisions(508);
   prefit_projy2_fail_stack_stack_155_stack_156->GetYaxis()->SetLabelFont(42);
   prefit_projy2_fail_stack_stack_155_stack_156->GetYaxis()->SetLabelOffset(0.007);
   prefit_projy2_fail_stack_stack_155_stack_156->GetYaxis()->SetLabelSize(0.05);
   prefit_projy2_fail_stack_stack_155_stack_156->GetYaxis()->SetTitleSize(0.08);
   prefit_projy2_fail_stack_stack_155_stack_156->GetYaxis()->SetTitleOffset(1.25);
   prefit_projy2_fail_stack_stack_155_stack_156->GetYaxis()->SetTitleFont(42);
   prefit_projy2_fail_stack_stack_155_stack_156->GetZaxis()->SetLabelFont(42);
   prefit_projy2_fail_stack_stack_155_stack_156->GetZaxis()->SetLabelOffset(0.007);
   prefit_projy2_fail_stack_stack_155_stack_156->GetZaxis()->SetLabelSize(0.05);
   prefit_projy2_fail_stack_stack_155_stack_156->GetZaxis()->SetTitleSize(0.08);
   prefit_projy2_fail_stack_stack_155_stack_156->GetZaxis()->SetTitleFont(42);
   prefit_projy2_fail_stack->SetHistogram(prefit_projy2_fail_stack_stack_155_stack_156);
   
   Double_t xAxis852[2] = {50, 200}; 
   
   TH1D *Background_fail_prefit_projy2_stack_1_stack_1 = new TH1D("Background_fail_prefit_projy2_stack_1_stack_1","Background, fail, prefit, 1.0-1.0",1, xAxis852);
   Background_fail_prefit_projy2_stack_1_stack_1->SetMinimum(0);

   ci = TColor::GetColor("#ffff00");
   Background_fail_prefit_projy2_stack_1_stack_1->SetFillColor(ci);

   ci = 1544;
   color = new TColor(ci, 1, 1, 1, " ", 0);
   Background_fail_prefit_projy2_stack_1_stack_1->SetLineColor(ci);
   Background_fail_prefit_projy2_stack_1_stack_1->SetLineStyle(0);
   Background_fail_prefit_projy2_stack_1_stack_1->GetXaxis()->SetTitle("p_{T}");
   Background_fail_prefit_projy2_stack_1_stack_1->GetXaxis()->SetLabelFont(42);
   Background_fail_prefit_projy2_stack_1_stack_1->GetXaxis()->SetLabelOffset(0.007);
   Background_fail_prefit_projy2_stack_1_stack_1->GetXaxis()->SetLabelSize(0.05);
   Background_fail_prefit_projy2_stack_1_stack_1->GetXaxis()->SetTitleSize(0.08);
   Background_fail_prefit_projy2_stack_1_stack_1->GetXaxis()->SetTitleOffset(1.25);
   Background_fail_prefit_projy2_stack_1_stack_1->GetXaxis()->SetTitleFont(42);
   Background_fail_prefit_projy2_stack_1_stack_1->GetYaxis()->SetTitle("Events / bin");
   Background_fail_prefit_projy2_stack_1_stack_1->GetYaxis()->SetLabelFont(42);
   Background_fail_prefit_projy2_stack_1_stack_1->GetYaxis()->SetLabelOffset(0.007);
   Background_fail_prefit_projy2_stack_1_stack_1->GetYaxis()->SetLabelSize(0.05);
   Background_fail_prefit_projy2_stack_1_stack_1->GetYaxis()->SetTitleSize(0.08);
   Background_fail_prefit_projy2_stack_1_stack_1->GetYaxis()->SetTitleOffset(1.25);
   Background_fail_prefit_projy2_stack_1_stack_1->GetYaxis()->SetTitleFont(42);
   Background_fail_prefit_projy2_stack_1_stack_1->GetZaxis()->SetLabelFont(42);
   Background_fail_prefit_projy2_stack_1_stack_1->GetZaxis()->SetLabelOffset(0.007);
   Background_fail_prefit_projy2_stack_1_stack_1->GetZaxis()->SetLabelSize(0.05);
   Background_fail_prefit_projy2_stack_1_stack_1->GetZaxis()->SetTitleSize(0.08);
   Background_fail_prefit_projy2_stack_1_stack_1->GetZaxis()->SetTitleFont(42);
   prefit_projy2_fail_stack->Add(Background_fail_prefit_projy2_stack_1_stack_1,"");
   prefit_projy2_fail_stack->Draw("hist same");
   Double_t xAxis853[2] = {50, 200}; 
   
   TH1D *Signal_ppStaumI557_fail_prefit_projy2__541 = new TH1D("Signal_ppStaumI557_fail_prefit_projy2__541","HSCP signal, fail, prefit, 1.0-1.0",1, xAxis853);
   Signal_ppStaumI557_fail_prefit_projy2__541->SetMinimum(0);
   Signal_ppStaumI557_fail_prefit_projy2__541->SetLineColor(2);
   Signal_ppStaumI557_fail_prefit_projy2__541->SetLineStyle(0);
   Signal_ppStaumI557_fail_prefit_projy2__541->GetXaxis()->SetTitle("p_{T}");
   Signal_ppStaumI557_fail_prefit_projy2__541->GetXaxis()->SetLabelFont(42);
   Signal_ppStaumI557_fail_prefit_projy2__541->GetXaxis()->SetLabelOffset(0.007);
   Signal_ppStaumI557_fail_prefit_projy2__541->GetXaxis()->SetLabelSize(0.05);
   Signal_ppStaumI557_fail_prefit_projy2__541->GetXaxis()->SetTitleSize(0.08);
   Signal_ppStaumI557_fail_prefit_projy2__541->GetXaxis()->SetTitleOffset(1.25);
   Signal_ppStaumI557_fail_prefit_projy2__541->GetXaxis()->SetTitleFont(42);
   Signal_ppStaumI557_fail_prefit_projy2__541->GetYaxis()->SetTitle("Events / bin");
   Signal_ppStaumI557_fail_prefit_projy2__541->GetYaxis()->SetLabelFont(42);
   Signal_ppStaumI557_fail_prefit_projy2__541->GetYaxis()->SetLabelOffset(0.007);
   Signal_ppStaumI557_fail_prefit_projy2__541->GetYaxis()->SetLabelSize(0.05);
   Signal_ppStaumI557_fail_prefit_projy2__541->GetYaxis()->SetTitleSize(0.08);
   Signal_ppStaumI557_fail_prefit_projy2__541->GetYaxis()->SetTitleOffset(1.25);
   Signal_ppStaumI557_fail_prefit_projy2__541->GetYaxis()->SetTitleFont(42);
   Signal_ppStaumI557_fail_prefit_projy2__541->GetZaxis()->SetLabelFont(42);
   Signal_ppStaumI557_fail_prefit_projy2__541->GetZaxis()->SetLabelOffset(0.007);
   Signal_ppStaumI557_fail_prefit_projy2__541->GetZaxis()->SetLabelSize(0.05);
   Signal_ppStaumI557_fail_prefit_projy2__541->GetZaxis()->SetTitleSize(0.08);
   Signal_ppStaumI557_fail_prefit_projy2__541->GetZaxis()->SetTitleFont(42);
   Signal_ppStaumI557_fail_prefit_projy2__541->Draw("hist same");
   Double_t xAxis854[2] = {50, 200}; 
   
   TH1D *TotalBkg_fail_prefit_projy2__542 = new TH1D("TotalBkg_fail_prefit_projy2__542","TotalBkg, fail, prefit, 1.0-1.0",1, xAxis854);
   TotalBkg_fail_prefit_projy2__542->SetMinimum(0);
   TotalBkg_fail_prefit_projy2__542->SetLineStyle(0);
   TotalBkg_fail_prefit_projy2__542->SetMarkerStyle(0);
   TotalBkg_fail_prefit_projy2__542->GetXaxis()->SetTitle("p_{T}");
   TotalBkg_fail_prefit_projy2__542->GetXaxis()->SetLabelFont(42);
   TotalBkg_fail_prefit_projy2__542->GetXaxis()->SetLabelOffset(0.007);
   TotalBkg_fail_prefit_projy2__542->GetXaxis()->SetLabelSize(0.05);
   TotalBkg_fail_prefit_projy2__542->GetXaxis()->SetTitleSize(0.08);
   TotalBkg_fail_prefit_projy2__542->GetXaxis()->SetTitleOffset(1.25);
   TotalBkg_fail_prefit_projy2__542->GetXaxis()->SetTitleFont(42);
   TotalBkg_fail_prefit_projy2__542->GetYaxis()->SetTitle("Events / bin");
   TotalBkg_fail_prefit_projy2__542->GetYaxis()->SetLabelFont(42);
   TotalBkg_fail_prefit_projy2__542->GetYaxis()->SetLabelOffset(0.007);
   TotalBkg_fail_prefit_projy2__542->GetYaxis()->SetLabelSize(0.05);
   TotalBkg_fail_prefit_projy2__542->GetYaxis()->SetTitleSize(0.08);
   TotalBkg_fail_prefit_projy2__542->GetYaxis()->SetTitleOffset(1.25);
   TotalBkg_fail_prefit_projy2__542->GetYaxis()->SetTitleFont(42);
   TotalBkg_fail_prefit_projy2__542->GetZaxis()->SetLabelFont(42);
   TotalBkg_fail_prefit_projy2__542->GetZaxis()->SetLabelOffset(0.007);
   TotalBkg_fail_prefit_projy2__542->GetZaxis()->SetLabelSize(0.05);
   TotalBkg_fail_prefit_projy2__542->GetZaxis()->SetTitleSize(0.08);
   TotalBkg_fail_prefit_projy2__542->GetZaxis()->SetTitleFont(42);
   TotalBkg_fail_prefit_projy2__542->Draw("hist same");
   Double_t xAxis855[2] = {50, 200}; 
   
   TH1D *TotalBkg_fail_prefit_projy2__543 = new TH1D("TotalBkg_fail_prefit_projy2__543","TotalBkg, fail, prefit, 1.0-1.0",1, xAxis855);
   TotalBkg_fail_prefit_projy2__543->SetMinimum(0);
   TotalBkg_fail_prefit_projy2__543->SetFillColor(1);
   TotalBkg_fail_prefit_projy2__543->SetFillStyle(3354);
   TotalBkg_fail_prefit_projy2__543->SetLineStyle(0);
   TotalBkg_fail_prefit_projy2__543->SetLineWidth(0);
   TotalBkg_fail_prefit_projy2__543->SetMarkerStyle(0);
   TotalBkg_fail_prefit_projy2__543->GetXaxis()->SetTitle("p_{T}");
   TotalBkg_fail_prefit_projy2__543->GetXaxis()->SetLabelFont(42);
   TotalBkg_fail_prefit_projy2__543->GetXaxis()->SetLabelOffset(0.007);
   TotalBkg_fail_prefit_projy2__543->GetXaxis()->SetLabelSize(0.05);
   TotalBkg_fail_prefit_projy2__543->GetXaxis()->SetTitleSize(0.08);
   TotalBkg_fail_prefit_projy2__543->GetXaxis()->SetTitleOffset(1.25);
   TotalBkg_fail_prefit_projy2__543->GetXaxis()->SetTitleFont(42);
   TotalBkg_fail_prefit_projy2__543->GetYaxis()->SetTitle("Events / bin");
   TotalBkg_fail_prefit_projy2__543->GetYaxis()->SetLabelFont(42);
   TotalBkg_fail_prefit_projy2__543->GetYaxis()->SetLabelOffset(0.007);
   TotalBkg_fail_prefit_projy2__543->GetYaxis()->SetLabelSize(0.05);
   TotalBkg_fail_prefit_projy2__543->GetYaxis()->SetTitleSize(0.08);
   TotalBkg_fail_prefit_projy2__543->GetYaxis()->SetTitleOffset(1.25);
   TotalBkg_fail_prefit_projy2__543->GetYaxis()->SetTitleFont(42);
   TotalBkg_fail_prefit_projy2__543->GetZaxis()->SetLabelFont(42);
   TotalBkg_fail_prefit_projy2__543->GetZaxis()->SetLabelOffset(0.007);
   TotalBkg_fail_prefit_projy2__543->GetZaxis()->SetLabelSize(0.05);
   TotalBkg_fail_prefit_projy2__543->GetZaxis()->SetTitleSize(0.08);
   TotalBkg_fail_prefit_projy2__543->GetZaxis()->SetTitleFont(42);
   TotalBkg_fail_prefit_projy2__543->Draw("e2 same");
   Double_t xAxis856[2] = {50, 200}; 
   
   TH1D *data_obs_fail_prefit_projy2__544 = new TH1D("data_obs_fail_prefit_projy2__544","",1, xAxis856);
   data_obs_fail_prefit_projy2__544->SetMinimum(0);
   data_obs_fail_prefit_projy2__544->SetMaximum(0);

   ci = TColor::GetColor("#000000");
   data_obs_fail_prefit_projy2__544->SetLineColor(ci);
   data_obs_fail_prefit_projy2__544->SetLineStyle(0);

   ci = TColor::GetColor("#000000");
   data_obs_fail_prefit_projy2__544->SetMarkerColor(ci);
   data_obs_fail_prefit_projy2__544->SetMarkerStyle(8);
   data_obs_fail_prefit_projy2__544->GetXaxis()->SetTitle("p_{T}");
   data_obs_fail_prefit_projy2__544->GetXaxis()->SetLabelFont(42);
   data_obs_fail_prefit_projy2__544->GetXaxis()->SetLabelOffset(0.05);
   data_obs_fail_prefit_projy2__544->GetXaxis()->SetLabelSize(0.07);
   data_obs_fail_prefit_projy2__544->GetXaxis()->SetTitleSize(0.09);
   data_obs_fail_prefit_projy2__544->GetXaxis()->SetTitleOffset(1.15);
   data_obs_fail_prefit_projy2__544->GetXaxis()->SetTitleFont(42);
   data_obs_fail_prefit_projy2__544->GetYaxis()->SetTitle("Events / bin");
   data_obs_fail_prefit_projy2__544->GetYaxis()->SetNdivisions(508);
   data_obs_fail_prefit_projy2__544->GetYaxis()->SetLabelFont(42);
   data_obs_fail_prefit_projy2__544->GetYaxis()->SetLabelOffset(0.007);
   data_obs_fail_prefit_projy2__544->GetYaxis()->SetLabelSize(0.07);
   data_obs_fail_prefit_projy2__544->GetYaxis()->SetTitleSize(0.09);
   data_obs_fail_prefit_projy2__544->GetYaxis()->SetTitleOffset(0.8);
   data_obs_fail_prefit_projy2__544->GetYaxis()->SetTitleFont(42);
   data_obs_fail_prefit_projy2__544->GetZaxis()->SetLabelFont(42);
   data_obs_fail_prefit_projy2__544->GetZaxis()->SetLabelOffset(0.007);
   data_obs_fail_prefit_projy2__544->GetZaxis()->SetLabelSize(0.05);
   data_obs_fail_prefit_projy2__544->GetZaxis()->SetTitleSize(0.08);
   data_obs_fail_prefit_projy2__544->GetZaxis()->SetTitleFont(42);
   data_obs_fail_prefit_projy2__544->Draw("pe X0 same");
   
   TLegend *leg = new TLegend(0.65,0.64,0.9,0.88,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(1001);
   TLegendEntry *entry=leg->AddEntry("data_obs_fail_prefit_projy2","Data","pe X0");

   ci = TColor::GetColor("#000000");
   entry->SetLineColor(ci);
   entry->SetLineWidth(1);

   ci = TColor::GetColor("#000000");
   entry->SetMarkerColor(ci);
   entry->SetMarkerStyle(8);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("TotalBkg_fail_prefit_projy2","Total bkg unc.","F");
   entry->SetFillColor(1);
   entry->SetFillStyle(3354);
   entry->SetLineColor(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("Signal_ppStau-557_fail_prefit_projy2","HSCP signal","L");
   entry->SetLineColor(2);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("Background_fail_prefit_projy2_stack_1_stack_1","Background","f");

   ci = TColor::GetColor("#ffff00");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = 1544;
   color = new TColor(ci, 1, 1, 1, " ", 0);
   entry->SetLineColor(ci);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   leg->Draw();
   Double_t xAxis857[2] = {50, 200}; 
   
   TH1D *data_obs_fail_prefit_projy2_copy__545 = new TH1D("data_obs_fail_prefit_projy2_copy__545","",1, xAxis857);
   data_obs_fail_prefit_projy2_copy__545->SetMinimum(0);
   data_obs_fail_prefit_projy2_copy__545->SetMaximum(0);
   data_obs_fail_prefit_projy2_copy__545->SetDirectory(0);

   ci = TColor::GetColor("#000000");
   data_obs_fail_prefit_projy2_copy__545->SetLineColor(ci);
   data_obs_fail_prefit_projy2_copy__545->SetLineStyle(0);

   ci = TColor::GetColor("#000000");
   data_obs_fail_prefit_projy2_copy__545->SetMarkerColor(ci);
   data_obs_fail_prefit_projy2_copy__545->SetMarkerStyle(8);
   data_obs_fail_prefit_projy2_copy__545->GetXaxis()->SetTitle("p_{T}");
   data_obs_fail_prefit_projy2_copy__545->GetXaxis()->SetLabelFont(42);
   data_obs_fail_prefit_projy2_copy__545->GetXaxis()->SetLabelOffset(0.05);
   data_obs_fail_prefit_projy2_copy__545->GetXaxis()->SetLabelSize(0.07);
   data_obs_fail_prefit_projy2_copy__545->GetXaxis()->SetTitleSize(0.09);
   data_obs_fail_prefit_projy2_copy__545->GetXaxis()->SetTitleOffset(1.15);
   data_obs_fail_prefit_projy2_copy__545->GetXaxis()->SetTitleFont(42);
   data_obs_fail_prefit_projy2_copy__545->GetYaxis()->SetTitle("Events / bin");
   data_obs_fail_prefit_projy2_copy__545->GetYaxis()->SetNdivisions(508);
   data_obs_fail_prefit_projy2_copy__545->GetYaxis()->SetLabelFont(42);
   data_obs_fail_prefit_projy2_copy__545->GetYaxis()->SetLabelOffset(0.007);
   data_obs_fail_prefit_projy2_copy__545->GetYaxis()->SetLabelSize(0.07);
   data_obs_fail_prefit_projy2_copy__545->GetYaxis()->SetTitleSize(0.09);
   data_obs_fail_prefit_projy2_copy__545->GetYaxis()->SetTitleOffset(0.8);
   data_obs_fail_prefit_projy2_copy__545->GetYaxis()->SetTitleFont(42);
   data_obs_fail_prefit_projy2_copy__545->GetZaxis()->SetLabelFont(42);
   data_obs_fail_prefit_projy2_copy__545->GetZaxis()->SetLabelOffset(0.007);
   data_obs_fail_prefit_projy2_copy__545->GetZaxis()->SetLabelSize(0.05);
   data_obs_fail_prefit_projy2_copy__545->GetZaxis()->SetTitleSize(0.08);
   data_obs_fail_prefit_projy2_copy__545->GetZaxis()->SetTitleFont(42);
   data_obs_fail_prefit_projy2_copy__545->Draw("sameaxis");
   TLatex *   tex = new TLatex(0.21,0.83,"55 < p_{T} < 200 GeV, F^{Pixels}_{i} < 0.9");
tex->SetNDC();
   tex->SetTextAlign(12);
   tex->SetTextFont(42);
   tex->SetTextSize(0.06);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.17,0.92,"CMS");
tex->SetNDC();
   tex->SetTextFont(61);
   tex->SetTextSize(0.0675);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.25,0.92,"Preliminary");
tex->SetNDC();
   tex->SetTextFont(52);
   tex->SetTextSize(0.0485);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.95,0.92,"101 fb^{-1} (13 TeV)");
tex->SetNDC();
   tex->SetTextAlign(31);
   tex->SetTextFont(42);
   tex->SetTextSize(0.07);
   tex->SetLineWidth(2);
   tex->Draw();
   data_obs_fail_prefit_projy2_main->Modified();
   plots_fit_s/base_figs/prefit_projy2_fail->cd();
  
// ------------>Primitives in pad: data_obs_fail_prefit_projy2_sub
   TPad *data_obs_fail_prefit_projy2_sub = new TPad("data_obs_fail_prefit_projy2_sub", "data_obs_fail_prefit_projy2_sub",0,0,1,0.35);
   data_obs_fail_prefit_projy2_sub->Draw();
   data_obs_fail_prefit_projy2_sub->cd();
   data_obs_fail_prefit_projy2_sub->Range(17.30769,-6.023077,209.6154,2.9);
   data_obs_fail_prefit_projy2_sub->SetFillColor(0);
   data_obs_fail_prefit_projy2_sub->SetBorderMode(0);
   data_obs_fail_prefit_projy2_sub->SetBorderSize(2);
   data_obs_fail_prefit_projy2_sub->SetTickx(1);
   data_obs_fail_prefit_projy2_sub->SetTicky(1);
   data_obs_fail_prefit_projy2_sub->SetLeftMargin(0.17);
   data_obs_fail_prefit_projy2_sub->SetRightMargin(0.05);
   data_obs_fail_prefit_projy2_sub->SetTopMargin(0);
   data_obs_fail_prefit_projy2_sub->SetBottomMargin(0.35);
   data_obs_fail_prefit_projy2_sub->SetFrameFillStyle(0);
   data_obs_fail_prefit_projy2_sub->SetFrameBorderMode(0);
   data_obs_fail_prefit_projy2_sub->SetFrameFillStyle(0);
   data_obs_fail_prefit_projy2_sub->SetFrameBorderMode(0);
   Double_t xAxis858[2] = {50, 200}; 
   
   TH1D *data_obs_fail_prefit_projy2_pull__546 = new TH1D("data_obs_fail_prefit_projy2_pull__546","",1, xAxis858);
   data_obs_fail_prefit_projy2_pull__546->SetMinimum(-2.9);
   data_obs_fail_prefit_projy2_pull__546->SetMaximum(2.9);
   data_obs_fail_prefit_projy2_pull__546->SetEntries(2);
   data_obs_fail_prefit_projy2_pull__546->SetStats(0);

   ci = TColor::GetColor("#0000ff");
   data_obs_fail_prefit_projy2_pull__546->SetFillColor(ci);

   ci = TColor::GetColor("#000000");
   data_obs_fail_prefit_projy2_pull__546->SetLineColor(ci);
   data_obs_fail_prefit_projy2_pull__546->SetLineStyle(0);

   ci = TColor::GetColor("#000000");
   data_obs_fail_prefit_projy2_pull__546->SetMarkerColor(ci);
   data_obs_fail_prefit_projy2_pull__546->SetMarkerStyle(8);
   data_obs_fail_prefit_projy2_pull__546->GetXaxis()->SetTitle("p_{T}");
   data_obs_fail_prefit_projy2_pull__546->GetXaxis()->SetLabelFont(42);
   data_obs_fail_prefit_projy2_pull__546->GetXaxis()->SetLabelOffset(0.05);
   data_obs_fail_prefit_projy2_pull__546->GetXaxis()->SetLabelSize(0.13);
   data_obs_fail_prefit_projy2_pull__546->GetXaxis()->SetTitleSize(0.15);
   data_obs_fail_prefit_projy2_pull__546->GetXaxis()->SetTitleOffset(1.15);
   data_obs_fail_prefit_projy2_pull__546->GetXaxis()->SetTitleFont(42);
   data_obs_fail_prefit_projy2_pull__546->GetYaxis()->SetTitle("(Data-Bkg)/#sigma");
   data_obs_fail_prefit_projy2_pull__546->GetYaxis()->SetNdivisions(306);
   data_obs_fail_prefit_projy2_pull__546->GetYaxis()->SetLabelFont(42);
   data_obs_fail_prefit_projy2_pull__546->GetYaxis()->SetLabelOffset(0.007);
   data_obs_fail_prefit_projy2_pull__546->GetYaxis()->SetLabelSize(0.13);
   data_obs_fail_prefit_projy2_pull__546->GetYaxis()->SetTitleSize(0.12);
   data_obs_fail_prefit_projy2_pull__546->GetYaxis()->SetTitleOffset(0.4);
   data_obs_fail_prefit_projy2_pull__546->GetYaxis()->SetTitleFont(42);
   data_obs_fail_prefit_projy2_pull__546->GetZaxis()->SetLabelFont(42);
   data_obs_fail_prefit_projy2_pull__546->GetZaxis()->SetLabelOffset(0.007);
   data_obs_fail_prefit_projy2_pull__546->GetZaxis()->SetLabelSize(0.05);
   data_obs_fail_prefit_projy2_pull__546->GetZaxis()->SetTitleSize(0.08);
   data_obs_fail_prefit_projy2_pull__546->GetZaxis()->SetTitleFont(42);
   data_obs_fail_prefit_projy2_pull__546->Draw("hist");
   data_obs_fail_prefit_projy2_sub->Modified();
   plots_fit_s/base_figs/prefit_projy2_fail->cd();
   plots_fit_s/base_figs/prefit_projy2_fail->Modified();
   plots_fit_s/base_figs/prefit_projy2_fail->cd();
   plots_fit_s/base_figs/prefit_projy2_fail->SetSelected(plots_fit_s/base_figs/prefit_projy2_fail);
}
