void prefit_projy0_pass()
{
//=========Macro generated from canvas: plots_fit_s/base_figs/prefit_projy0_pass/plots_fit_s/base_figs/prefit_projy0_pass
//=========  (Fri Jan 12 21:00:35 2024) by ROOT version 6.14/09
   TCanvas *plots_fit_s/base_figs/prefit_projy0_pass = new TCanvas("plots_fit_s/base_figs/prefit_projy0_pass", "plots_fit_s/base_figs/prefit_projy0_pass",0,0,800,700);
   gStyle->SetOptFit(1);
   gStyle->SetOptStat(0);
   plots_fit_s/base_figs/prefit_projy0_pass->SetHighLightColor(2);
   plots_fit_s/base_figs/prefit_projy0_pass->Range(0,0,1,1);
   plots_fit_s/base_figs/prefit_projy0_pass->SetFillColor(0);
   plots_fit_s/base_figs/prefit_projy0_pass->SetBorderMode(0);
   plots_fit_s/base_figs/prefit_projy0_pass->SetBorderSize(2);
   plots_fit_s/base_figs/prefit_projy0_pass->SetTickx(1);
   plots_fit_s/base_figs/prefit_projy0_pass->SetTicky(1);
   plots_fit_s/base_figs/prefit_projy0_pass->SetLeftMargin(0.16);
   plots_fit_s/base_figs/prefit_projy0_pass->SetRightMargin(0);
   plots_fit_s/base_figs/prefit_projy0_pass->SetTopMargin(0);
   plots_fit_s/base_figs/prefit_projy0_pass->SetBottomMargin(0);
   plots_fit_s/base_figs/prefit_projy0_pass->SetFrameFillStyle(0);
   plots_fit_s/base_figs/prefit_projy0_pass->SetFrameBorderMode(0);
  
// ------------>Primitives in pad: data_obs_pass_prefit_projy0_main
   TPad *data_obs_pass_prefit_projy0_main = new TPad("data_obs_pass_prefit_projy0_main", "data_obs_pass_prefit_projy0_main",0,0.35,1,1);
   data_obs_pass_prefit_projy0_main->Draw();
   data_obs_pass_prefit_projy0_main->cd();
   data_obs_pass_prefit_projy0_main->Range(17.30769,-146170.1,209.6154,3508082);
   data_obs_pass_prefit_projy0_main->SetFillColor(0);
   data_obs_pass_prefit_projy0_main->SetBorderMode(0);
   data_obs_pass_prefit_projy0_main->SetBorderSize(2);
   data_obs_pass_prefit_projy0_main->SetTickx(1);
   data_obs_pass_prefit_projy0_main->SetTicky(1);
   data_obs_pass_prefit_projy0_main->SetLeftMargin(0.17);
   data_obs_pass_prefit_projy0_main->SetRightMargin(0.05);
   data_obs_pass_prefit_projy0_main->SetBottomMargin(0.04);
   data_obs_pass_prefit_projy0_main->SetFrameFillStyle(0);
   data_obs_pass_prefit_projy0_main->SetFrameBorderMode(0);
   data_obs_pass_prefit_projy0_main->SetFrameFillStyle(0);
   data_obs_pass_prefit_projy0_main->SetFrameBorderMode(0);
   Double_t xAxis958[2] = {50, 200}; 
   
   TH1D *data_obs_pass_prefit_projy0__610 = new TH1D("data_obs_pass_prefit_projy0__610","",1, xAxis958);
   data_obs_pass_prefit_projy0__610->SetBinContent(1,2327894);
   data_obs_pass_prefit_projy0__610->SetBinError(1,1525.744);
   data_obs_pass_prefit_projy0__610->SetMinimum(0);
   data_obs_pass_prefit_projy0__610->SetMaximum(3142657);
   data_obs_pass_prefit_projy0__610->SetEntries(2327894);

   Int_t ci;      // for color index setting
   TColor *color; // for color definition with alpha
   ci = TColor::GetColor("#000000");
   data_obs_pass_prefit_projy0__610->SetLineColor(ci);
   data_obs_pass_prefit_projy0__610->SetLineStyle(0);

   ci = TColor::GetColor("#000000");
   data_obs_pass_prefit_projy0__610->SetMarkerColor(ci);
   data_obs_pass_prefit_projy0__610->SetMarkerStyle(8);
   data_obs_pass_prefit_projy0__610->GetXaxis()->SetTitle("p_{T}");
   data_obs_pass_prefit_projy0__610->GetXaxis()->SetLabelFont(42);
   data_obs_pass_prefit_projy0__610->GetXaxis()->SetLabelOffset(0.05);
   data_obs_pass_prefit_projy0__610->GetXaxis()->SetLabelSize(0.07);
   data_obs_pass_prefit_projy0__610->GetXaxis()->SetTitleSize(0.09);
   data_obs_pass_prefit_projy0__610->GetXaxis()->SetTitleOffset(1.15);
   data_obs_pass_prefit_projy0__610->GetXaxis()->SetTitleFont(42);
   data_obs_pass_prefit_projy0__610->GetYaxis()->SetTitle("Events / bin");
   data_obs_pass_prefit_projy0__610->GetYaxis()->SetNdivisions(508);
   data_obs_pass_prefit_projy0__610->GetYaxis()->SetLabelFont(42);
   data_obs_pass_prefit_projy0__610->GetYaxis()->SetLabelOffset(0.007);
   data_obs_pass_prefit_projy0__610->GetYaxis()->SetLabelSize(0.07);
   data_obs_pass_prefit_projy0__610->GetYaxis()->SetTitleSize(0.09);
   data_obs_pass_prefit_projy0__610->GetYaxis()->SetTitleOffset(0.8);
   data_obs_pass_prefit_projy0__610->GetYaxis()->SetTitleFont(42);
   data_obs_pass_prefit_projy0__610->GetZaxis()->SetLabelFont(42);
   data_obs_pass_prefit_projy0__610->GetZaxis()->SetLabelOffset(0.007);
   data_obs_pass_prefit_projy0__610->GetZaxis()->SetLabelSize(0.05);
   data_obs_pass_prefit_projy0__610->GetZaxis()->SetTitleSize(0.08);
   data_obs_pass_prefit_projy0__610->GetZaxis()->SetTitleFont(42);
   data_obs_pass_prefit_projy0__610->Draw("pe X0");
   
   THStack *prefit_projy0_pass_stack = new THStack();
   prefit_projy0_pass_stack->SetName("prefit_projy0_pass_stack");
   prefit_projy0_pass_stack->SetTitle("prefit_projy0_pass_stack");
   Double_t xAxis959[2] = {50, 200}; 
   
   TH1F *prefit_projy0_pass_stack_stack_175 = new TH1F("prefit_projy0_pass_stack_stack_175","prefit_projy0_pass_stack",1, xAxis959);
   prefit_projy0_pass_stack_stack_175->SetMinimum(0);
   prefit_projy0_pass_stack_stack_175->SetMaximum(274763.4);
   prefit_projy0_pass_stack_stack_175->SetDirectory(0);
   prefit_projy0_pass_stack_stack_175->SetStats(0);
   prefit_projy0_pass_stack_stack_175->SetLineStyle(0);
   prefit_projy0_pass_stack_stack_175->GetXaxis()->SetLabelFont(42);
   prefit_projy0_pass_stack_stack_175->GetXaxis()->SetLabelOffset(0.007);
   prefit_projy0_pass_stack_stack_175->GetXaxis()->SetLabelSize(0.05);
   prefit_projy0_pass_stack_stack_175->GetXaxis()->SetTitleSize(0.08);
   prefit_projy0_pass_stack_stack_175->GetXaxis()->SetTitleOffset(0.9);
   prefit_projy0_pass_stack_stack_175->GetXaxis()->SetTitleFont(42);
   prefit_projy0_pass_stack_stack_175->GetYaxis()->SetNdivisions(508);
   prefit_projy0_pass_stack_stack_175->GetYaxis()->SetLabelFont(42);
   prefit_projy0_pass_stack_stack_175->GetYaxis()->SetLabelOffset(0.007);
   prefit_projy0_pass_stack_stack_175->GetYaxis()->SetLabelSize(0.05);
   prefit_projy0_pass_stack_stack_175->GetYaxis()->SetTitleSize(0.08);
   prefit_projy0_pass_stack_stack_175->GetYaxis()->SetTitleOffset(1.25);
   prefit_projy0_pass_stack_stack_175->GetYaxis()->SetTitleFont(42);
   prefit_projy0_pass_stack_stack_175->GetZaxis()->SetLabelFont(42);
   prefit_projy0_pass_stack_stack_175->GetZaxis()->SetLabelOffset(0.007);
   prefit_projy0_pass_stack_stack_175->GetZaxis()->SetLabelSize(0.05);
   prefit_projy0_pass_stack_stack_175->GetZaxis()->SetTitleSize(0.08);
   prefit_projy0_pass_stack_stack_175->GetZaxis()->SetTitleFont(42);
   prefit_projy0_pass_stack->SetHistogram(prefit_projy0_pass_stack_stack_175);
   
   Double_t xAxis960[2] = {50, 200}; 
   
   TH1D *Background_0x0_pass_prefit_projy0_stack_1 = new TH1D("Background_0x0_pass_prefit_projy0_stack_1","Background, pass, prefit, 0.0-0.24",1, xAxis960);
   Background_0x0_pass_prefit_projy0_stack_1->SetBinContent(1,140854);
   Background_0x0_pass_prefit_projy0_stack_1->SetBinError(1,120825.5);
   Background_0x0_pass_prefit_projy0_stack_1->SetMinimum(0);
   Background_0x0_pass_prefit_projy0_stack_1->SetEntries(1.359005);

   ci = TColor::GetColor("#ffff00");
   Background_0x0_pass_prefit_projy0_stack_1->SetFillColor(ci);

   ci = 1554;
   color = new TColor(ci, 1, 1, 1, " ", 0);
   Background_0x0_pass_prefit_projy0_stack_1->SetLineColor(ci);
   Background_0x0_pass_prefit_projy0_stack_1->SetLineStyle(0);
   Background_0x0_pass_prefit_projy0_stack_1->GetXaxis()->SetTitle("p_{T}");
   Background_0x0_pass_prefit_projy0_stack_1->GetXaxis()->SetLabelFont(42);
   Background_0x0_pass_prefit_projy0_stack_1->GetXaxis()->SetLabelOffset(0.007);
   Background_0x0_pass_prefit_projy0_stack_1->GetXaxis()->SetLabelSize(0.05);
   Background_0x0_pass_prefit_projy0_stack_1->GetXaxis()->SetTitleSize(0.08);
   Background_0x0_pass_prefit_projy0_stack_1->GetXaxis()->SetTitleOffset(1.25);
   Background_0x0_pass_prefit_projy0_stack_1->GetXaxis()->SetTitleFont(42);
   Background_0x0_pass_prefit_projy0_stack_1->GetYaxis()->SetTitle("Events / bin");
   Background_0x0_pass_prefit_projy0_stack_1->GetYaxis()->SetLabelFont(42);
   Background_0x0_pass_prefit_projy0_stack_1->GetYaxis()->SetLabelOffset(0.007);
   Background_0x0_pass_prefit_projy0_stack_1->GetYaxis()->SetLabelSize(0.05);
   Background_0x0_pass_prefit_projy0_stack_1->GetYaxis()->SetTitleSize(0.08);
   Background_0x0_pass_prefit_projy0_stack_1->GetYaxis()->SetTitleOffset(1.25);
   Background_0x0_pass_prefit_projy0_stack_1->GetYaxis()->SetTitleFont(42);
   Background_0x0_pass_prefit_projy0_stack_1->GetZaxis()->SetLabelFont(42);
   Background_0x0_pass_prefit_projy0_stack_1->GetZaxis()->SetLabelOffset(0.007);
   Background_0x0_pass_prefit_projy0_stack_1->GetZaxis()->SetLabelSize(0.05);
   Background_0x0_pass_prefit_projy0_stack_1->GetZaxis()->SetTitleSize(0.08);
   Background_0x0_pass_prefit_projy0_stack_1->GetZaxis()->SetTitleFont(42);
   prefit_projy0_pass_stack->Add(Background_0x0_pass_prefit_projy0_stack_1,"");
   prefit_projy0_pass_stack->Draw("hist same");
   
   prefit_projy0_pass_stack = new THStack();
   prefit_projy0_pass_stack->SetName("prefit_projy0_pass_stack");
   prefit_projy0_pass_stack->SetTitle("prefit_projy0_pass_stack");
   Double_t xAxis961[2] = {50, 200}; 
   
   TH1F *prefit_projy0_pass_stack_stack_175_stack_176 = new TH1F("prefit_projy0_pass_stack_stack_175_stack_176","prefit_projy0_pass_stack",1, xAxis961);
   prefit_projy0_pass_stack_stack_175_stack_176->SetMinimum(0);
   prefit_projy0_pass_stack_stack_175_stack_176->SetMaximum(274763.4);
   prefit_projy0_pass_stack_stack_175_stack_176->SetDirectory(0);
   prefit_projy0_pass_stack_stack_175_stack_176->SetStats(0);
   prefit_projy0_pass_stack_stack_175_stack_176->SetLineStyle(0);
   prefit_projy0_pass_stack_stack_175_stack_176->GetXaxis()->SetLabelFont(42);
   prefit_projy0_pass_stack_stack_175_stack_176->GetXaxis()->SetLabelOffset(0.007);
   prefit_projy0_pass_stack_stack_175_stack_176->GetXaxis()->SetLabelSize(0.05);
   prefit_projy0_pass_stack_stack_175_stack_176->GetXaxis()->SetTitleSize(0.08);
   prefit_projy0_pass_stack_stack_175_stack_176->GetXaxis()->SetTitleOffset(0.9);
   prefit_projy0_pass_stack_stack_175_stack_176->GetXaxis()->SetTitleFont(42);
   prefit_projy0_pass_stack_stack_175_stack_176->GetYaxis()->SetNdivisions(508);
   prefit_projy0_pass_stack_stack_175_stack_176->GetYaxis()->SetLabelFont(42);
   prefit_projy0_pass_stack_stack_175_stack_176->GetYaxis()->SetLabelOffset(0.007);
   prefit_projy0_pass_stack_stack_175_stack_176->GetYaxis()->SetLabelSize(0.05);
   prefit_projy0_pass_stack_stack_175_stack_176->GetYaxis()->SetTitleSize(0.08);
   prefit_projy0_pass_stack_stack_175_stack_176->GetYaxis()->SetTitleOffset(1.25);
   prefit_projy0_pass_stack_stack_175_stack_176->GetYaxis()->SetTitleFont(42);
   prefit_projy0_pass_stack_stack_175_stack_176->GetZaxis()->SetLabelFont(42);
   prefit_projy0_pass_stack_stack_175_stack_176->GetZaxis()->SetLabelOffset(0.007);
   prefit_projy0_pass_stack_stack_175_stack_176->GetZaxis()->SetLabelSize(0.05);
   prefit_projy0_pass_stack_stack_175_stack_176->GetZaxis()->SetTitleSize(0.08);
   prefit_projy0_pass_stack_stack_175_stack_176->GetZaxis()->SetTitleFont(42);
   prefit_projy0_pass_stack->SetHistogram(prefit_projy0_pass_stack_stack_175_stack_176);
   
   Double_t xAxis962[2] = {50, 200}; 
   
   TH1D *Background_0x0_pass_prefit_projy0_stack_1_stack_1 = new TH1D("Background_0x0_pass_prefit_projy0_stack_1_stack_1","Background, pass, prefit, 0.0-0.24",1, xAxis962);
   Background_0x0_pass_prefit_projy0_stack_1_stack_1->SetBinContent(1,140854);
   Background_0x0_pass_prefit_projy0_stack_1_stack_1->SetBinError(1,120825.5);
   Background_0x0_pass_prefit_projy0_stack_1_stack_1->SetMinimum(0);
   Background_0x0_pass_prefit_projy0_stack_1_stack_1->SetEntries(1.359005);

   ci = TColor::GetColor("#ffff00");
   Background_0x0_pass_prefit_projy0_stack_1_stack_1->SetFillColor(ci);

   ci = 1554;
   color = new TColor(ci, 1, 1, 1, " ", 0);
   Background_0x0_pass_prefit_projy0_stack_1_stack_1->SetLineColor(ci);
   Background_0x0_pass_prefit_projy0_stack_1_stack_1->SetLineStyle(0);
   Background_0x0_pass_prefit_projy0_stack_1_stack_1->GetXaxis()->SetTitle("p_{T}");
   Background_0x0_pass_prefit_projy0_stack_1_stack_1->GetXaxis()->SetLabelFont(42);
   Background_0x0_pass_prefit_projy0_stack_1_stack_1->GetXaxis()->SetLabelOffset(0.007);
   Background_0x0_pass_prefit_projy0_stack_1_stack_1->GetXaxis()->SetLabelSize(0.05);
   Background_0x0_pass_prefit_projy0_stack_1_stack_1->GetXaxis()->SetTitleSize(0.08);
   Background_0x0_pass_prefit_projy0_stack_1_stack_1->GetXaxis()->SetTitleOffset(1.25);
   Background_0x0_pass_prefit_projy0_stack_1_stack_1->GetXaxis()->SetTitleFont(42);
   Background_0x0_pass_prefit_projy0_stack_1_stack_1->GetYaxis()->SetTitle("Events / bin");
   Background_0x0_pass_prefit_projy0_stack_1_stack_1->GetYaxis()->SetLabelFont(42);
   Background_0x0_pass_prefit_projy0_stack_1_stack_1->GetYaxis()->SetLabelOffset(0.007);
   Background_0x0_pass_prefit_projy0_stack_1_stack_1->GetYaxis()->SetLabelSize(0.05);
   Background_0x0_pass_prefit_projy0_stack_1_stack_1->GetYaxis()->SetTitleSize(0.08);
   Background_0x0_pass_prefit_projy0_stack_1_stack_1->GetYaxis()->SetTitleOffset(1.25);
   Background_0x0_pass_prefit_projy0_stack_1_stack_1->GetYaxis()->SetTitleFont(42);
   Background_0x0_pass_prefit_projy0_stack_1_stack_1->GetZaxis()->SetLabelFont(42);
   Background_0x0_pass_prefit_projy0_stack_1_stack_1->GetZaxis()->SetLabelOffset(0.007);
   Background_0x0_pass_prefit_projy0_stack_1_stack_1->GetZaxis()->SetLabelSize(0.05);
   Background_0x0_pass_prefit_projy0_stack_1_stack_1->GetZaxis()->SetTitleSize(0.08);
   Background_0x0_pass_prefit_projy0_stack_1_stack_1->GetZaxis()->SetTitleFont(42);
   prefit_projy0_pass_stack->Add(Background_0x0_pass_prefit_projy0_stack_1_stack_1,"");
   prefit_projy0_pass_stack->Draw("hist same");
   Double_t xAxis963[2] = {50, 200}; 
   
   TH1D *Signal_ppStaumI557_pass_prefit_projy0__611 = new TH1D("Signal_ppStaumI557_pass_prefit_projy0__611","HSCP signal, pass, prefit, 0.0-0.24",1, xAxis963);
   Signal_ppStaumI557_pass_prefit_projy0__611->SetBinContent(1,1.44e-05);
   Signal_ppStaumI557_pass_prefit_projy0__611->SetBinError(1,9.331967e-08);
   Signal_ppStaumI557_pass_prefit_projy0__611->SetMinimum(0);
   Signal_ppStaumI557_pass_prefit_projy0__611->SetEntries(23811.05);
   Signal_ppStaumI557_pass_prefit_projy0__611->SetLineColor(2);
   Signal_ppStaumI557_pass_prefit_projy0__611->SetLineStyle(0);
   Signal_ppStaumI557_pass_prefit_projy0__611->GetXaxis()->SetTitle("p_{T}");
   Signal_ppStaumI557_pass_prefit_projy0__611->GetXaxis()->SetLabelFont(42);
   Signal_ppStaumI557_pass_prefit_projy0__611->GetXaxis()->SetLabelOffset(0.007);
   Signal_ppStaumI557_pass_prefit_projy0__611->GetXaxis()->SetLabelSize(0.05);
   Signal_ppStaumI557_pass_prefit_projy0__611->GetXaxis()->SetTitleSize(0.08);
   Signal_ppStaumI557_pass_prefit_projy0__611->GetXaxis()->SetTitleOffset(1.25);
   Signal_ppStaumI557_pass_prefit_projy0__611->GetXaxis()->SetTitleFont(42);
   Signal_ppStaumI557_pass_prefit_projy0__611->GetYaxis()->SetTitle("Events / bin");
   Signal_ppStaumI557_pass_prefit_projy0__611->GetYaxis()->SetLabelFont(42);
   Signal_ppStaumI557_pass_prefit_projy0__611->GetYaxis()->SetLabelOffset(0.007);
   Signal_ppStaumI557_pass_prefit_projy0__611->GetYaxis()->SetLabelSize(0.05);
   Signal_ppStaumI557_pass_prefit_projy0__611->GetYaxis()->SetTitleSize(0.08);
   Signal_ppStaumI557_pass_prefit_projy0__611->GetYaxis()->SetTitleOffset(1.25);
   Signal_ppStaumI557_pass_prefit_projy0__611->GetYaxis()->SetTitleFont(42);
   Signal_ppStaumI557_pass_prefit_projy0__611->GetZaxis()->SetLabelFont(42);
   Signal_ppStaumI557_pass_prefit_projy0__611->GetZaxis()->SetLabelOffset(0.007);
   Signal_ppStaumI557_pass_prefit_projy0__611->GetZaxis()->SetLabelSize(0.05);
   Signal_ppStaumI557_pass_prefit_projy0__611->GetZaxis()->SetTitleSize(0.08);
   Signal_ppStaumI557_pass_prefit_projy0__611->GetZaxis()->SetTitleFont(42);
   Signal_ppStaumI557_pass_prefit_projy0__611->Draw("hist same");
   Double_t xAxis964[2] = {50, 200}; 
   
   TH1D *TotalBkg_pass_prefit_projy0__612 = new TH1D("TotalBkg_pass_prefit_projy0__612","TotalBkg, pass, prefit, 0.0-0.24",1, xAxis964);
   TotalBkg_pass_prefit_projy0__612->SetBinContent(1,140854);
   TotalBkg_pass_prefit_projy0__612->SetBinError(1,120825.5);
   TotalBkg_pass_prefit_projy0__612->SetMinimum(0);
   TotalBkg_pass_prefit_projy0__612->SetEntries(1.359005);
   TotalBkg_pass_prefit_projy0__612->SetLineStyle(0);
   TotalBkg_pass_prefit_projy0__612->SetMarkerStyle(0);
   TotalBkg_pass_prefit_projy0__612->GetXaxis()->SetTitle("p_{T}");
   TotalBkg_pass_prefit_projy0__612->GetXaxis()->SetLabelFont(42);
   TotalBkg_pass_prefit_projy0__612->GetXaxis()->SetLabelOffset(0.007);
   TotalBkg_pass_prefit_projy0__612->GetXaxis()->SetLabelSize(0.05);
   TotalBkg_pass_prefit_projy0__612->GetXaxis()->SetTitleSize(0.08);
   TotalBkg_pass_prefit_projy0__612->GetXaxis()->SetTitleOffset(1.25);
   TotalBkg_pass_prefit_projy0__612->GetXaxis()->SetTitleFont(42);
   TotalBkg_pass_prefit_projy0__612->GetYaxis()->SetTitle("Events / bin");
   TotalBkg_pass_prefit_projy0__612->GetYaxis()->SetLabelFont(42);
   TotalBkg_pass_prefit_projy0__612->GetYaxis()->SetLabelOffset(0.007);
   TotalBkg_pass_prefit_projy0__612->GetYaxis()->SetLabelSize(0.05);
   TotalBkg_pass_prefit_projy0__612->GetYaxis()->SetTitleSize(0.08);
   TotalBkg_pass_prefit_projy0__612->GetYaxis()->SetTitleOffset(1.25);
   TotalBkg_pass_prefit_projy0__612->GetYaxis()->SetTitleFont(42);
   TotalBkg_pass_prefit_projy0__612->GetZaxis()->SetLabelFont(42);
   TotalBkg_pass_prefit_projy0__612->GetZaxis()->SetLabelOffset(0.007);
   TotalBkg_pass_prefit_projy0__612->GetZaxis()->SetLabelSize(0.05);
   TotalBkg_pass_prefit_projy0__612->GetZaxis()->SetTitleSize(0.08);
   TotalBkg_pass_prefit_projy0__612->GetZaxis()->SetTitleFont(42);
   TotalBkg_pass_prefit_projy0__612->Draw("hist same");
   Double_t xAxis965[2] = {50, 200}; 
   
   TH1D *TotalBkg_pass_prefit_projy0__613 = new TH1D("TotalBkg_pass_prefit_projy0__613","TotalBkg, pass, prefit, 0.0-0.24",1, xAxis965);
   TotalBkg_pass_prefit_projy0__613->SetBinContent(1,140854);
   TotalBkg_pass_prefit_projy0__613->SetBinError(1,120825.5);
   TotalBkg_pass_prefit_projy0__613->SetMinimum(0);
   TotalBkg_pass_prefit_projy0__613->SetEntries(1.359005);
   TotalBkg_pass_prefit_projy0__613->SetFillColor(1);
   TotalBkg_pass_prefit_projy0__613->SetFillStyle(3354);
   TotalBkg_pass_prefit_projy0__613->SetLineStyle(0);
   TotalBkg_pass_prefit_projy0__613->SetLineWidth(0);
   TotalBkg_pass_prefit_projy0__613->SetMarkerStyle(0);
   TotalBkg_pass_prefit_projy0__613->GetXaxis()->SetTitle("p_{T}");
   TotalBkg_pass_prefit_projy0__613->GetXaxis()->SetLabelFont(42);
   TotalBkg_pass_prefit_projy0__613->GetXaxis()->SetLabelOffset(0.007);
   TotalBkg_pass_prefit_projy0__613->GetXaxis()->SetLabelSize(0.05);
   TotalBkg_pass_prefit_projy0__613->GetXaxis()->SetTitleSize(0.08);
   TotalBkg_pass_prefit_projy0__613->GetXaxis()->SetTitleOffset(1.25);
   TotalBkg_pass_prefit_projy0__613->GetXaxis()->SetTitleFont(42);
   TotalBkg_pass_prefit_projy0__613->GetYaxis()->SetTitle("Events / bin");
   TotalBkg_pass_prefit_projy0__613->GetYaxis()->SetLabelFont(42);
   TotalBkg_pass_prefit_projy0__613->GetYaxis()->SetLabelOffset(0.007);
   TotalBkg_pass_prefit_projy0__613->GetYaxis()->SetLabelSize(0.05);
   TotalBkg_pass_prefit_projy0__613->GetYaxis()->SetTitleSize(0.08);
   TotalBkg_pass_prefit_projy0__613->GetYaxis()->SetTitleOffset(1.25);
   TotalBkg_pass_prefit_projy0__613->GetYaxis()->SetTitleFont(42);
   TotalBkg_pass_prefit_projy0__613->GetZaxis()->SetLabelFont(42);
   TotalBkg_pass_prefit_projy0__613->GetZaxis()->SetLabelOffset(0.007);
   TotalBkg_pass_prefit_projy0__613->GetZaxis()->SetLabelSize(0.05);
   TotalBkg_pass_prefit_projy0__613->GetZaxis()->SetTitleSize(0.08);
   TotalBkg_pass_prefit_projy0__613->GetZaxis()->SetTitleFont(42);
   TotalBkg_pass_prefit_projy0__613->Draw("e2 same");
   Double_t xAxis966[2] = {50, 200}; 
   
   TH1D *data_obs_pass_prefit_projy0__614 = new TH1D("data_obs_pass_prefit_projy0__614","",1, xAxis966);
   data_obs_pass_prefit_projy0__614->SetBinContent(1,2327894);
   data_obs_pass_prefit_projy0__614->SetBinError(1,1525.744);
   data_obs_pass_prefit_projy0__614->SetMinimum(0);
   data_obs_pass_prefit_projy0__614->SetMaximum(3142657);
   data_obs_pass_prefit_projy0__614->SetEntries(2327894);

   ci = TColor::GetColor("#000000");
   data_obs_pass_prefit_projy0__614->SetLineColor(ci);
   data_obs_pass_prefit_projy0__614->SetLineStyle(0);

   ci = TColor::GetColor("#000000");
   data_obs_pass_prefit_projy0__614->SetMarkerColor(ci);
   data_obs_pass_prefit_projy0__614->SetMarkerStyle(8);
   data_obs_pass_prefit_projy0__614->GetXaxis()->SetTitle("p_{T}");
   data_obs_pass_prefit_projy0__614->GetXaxis()->SetLabelFont(42);
   data_obs_pass_prefit_projy0__614->GetXaxis()->SetLabelOffset(0.05);
   data_obs_pass_prefit_projy0__614->GetXaxis()->SetLabelSize(0.07);
   data_obs_pass_prefit_projy0__614->GetXaxis()->SetTitleSize(0.09);
   data_obs_pass_prefit_projy0__614->GetXaxis()->SetTitleOffset(1.15);
   data_obs_pass_prefit_projy0__614->GetXaxis()->SetTitleFont(42);
   data_obs_pass_prefit_projy0__614->GetYaxis()->SetTitle("Events / bin");
   data_obs_pass_prefit_projy0__614->GetYaxis()->SetNdivisions(508);
   data_obs_pass_prefit_projy0__614->GetYaxis()->SetLabelFont(42);
   data_obs_pass_prefit_projy0__614->GetYaxis()->SetLabelOffset(0.007);
   data_obs_pass_prefit_projy0__614->GetYaxis()->SetLabelSize(0.07);
   data_obs_pass_prefit_projy0__614->GetYaxis()->SetTitleSize(0.09);
   data_obs_pass_prefit_projy0__614->GetYaxis()->SetTitleOffset(0.8);
   data_obs_pass_prefit_projy0__614->GetYaxis()->SetTitleFont(42);
   data_obs_pass_prefit_projy0__614->GetZaxis()->SetLabelFont(42);
   data_obs_pass_prefit_projy0__614->GetZaxis()->SetLabelOffset(0.007);
   data_obs_pass_prefit_projy0__614->GetZaxis()->SetLabelSize(0.05);
   data_obs_pass_prefit_projy0__614->GetZaxis()->SetTitleSize(0.08);
   data_obs_pass_prefit_projy0__614->GetZaxis()->SetTitleFont(42);
   data_obs_pass_prefit_projy0__614->Draw("pe X0 same");
   
   TLegend *leg = new TLegend(0.65,0.64,0.9,0.88,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(1001);
   TLegendEntry *entry=leg->AddEntry("data_obs_pass_prefit_projy0","Data","pe X0");

   ci = TColor::GetColor("#000000");
   entry->SetLineColor(ci);
   entry->SetLineWidth(1);

   ci = TColor::GetColor("#000000");
   entry->SetMarkerColor(ci);
   entry->SetMarkerStyle(8);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("TotalBkg_pass_prefit_projy0","Total bkg unc.","F");
   entry->SetFillColor(1);
   entry->SetFillStyle(3354);
   entry->SetLineColor(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("Signal_ppStau-557_pass_prefit_projy0","HSCP signal","L");
   entry->SetLineColor(2);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("Background_0x0_pass_prefit_projy0_stack_1_stack_1","Background","f");

   ci = TColor::GetColor("#ffff00");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = 1554;
   color = new TColor(ci, 1, 1, 1, " ", 0);
   entry->SetLineColor(ci);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   leg->Draw();
   Double_t xAxis967[2] = {50, 200}; 
   
   TH1D *data_obs_pass_prefit_projy0_copy__615 = new TH1D("data_obs_pass_prefit_projy0_copy__615","",1, xAxis967);
   data_obs_pass_prefit_projy0_copy__615->SetBinContent(1,2327894);
   data_obs_pass_prefit_projy0_copy__615->SetBinError(1,1525.744);
   data_obs_pass_prefit_projy0_copy__615->SetMinimum(0);
   data_obs_pass_prefit_projy0_copy__615->SetMaximum(3142657);
   data_obs_pass_prefit_projy0_copy__615->SetEntries(2327894);
   data_obs_pass_prefit_projy0_copy__615->SetDirectory(0);

   ci = TColor::GetColor("#000000");
   data_obs_pass_prefit_projy0_copy__615->SetLineColor(ci);
   data_obs_pass_prefit_projy0_copy__615->SetLineStyle(0);

   ci = TColor::GetColor("#000000");
   data_obs_pass_prefit_projy0_copy__615->SetMarkerColor(ci);
   data_obs_pass_prefit_projy0_copy__615->SetMarkerStyle(8);
   data_obs_pass_prefit_projy0_copy__615->GetXaxis()->SetTitle("p_{T}");
   data_obs_pass_prefit_projy0_copy__615->GetXaxis()->SetLabelFont(42);
   data_obs_pass_prefit_projy0_copy__615->GetXaxis()->SetLabelOffset(0.05);
   data_obs_pass_prefit_projy0_copy__615->GetXaxis()->SetLabelSize(0.07);
   data_obs_pass_prefit_projy0_copy__615->GetXaxis()->SetTitleSize(0.09);
   data_obs_pass_prefit_projy0_copy__615->GetXaxis()->SetTitleOffset(1.15);
   data_obs_pass_prefit_projy0_copy__615->GetXaxis()->SetTitleFont(42);
   data_obs_pass_prefit_projy0_copy__615->GetYaxis()->SetTitle("Events / bin");
   data_obs_pass_prefit_projy0_copy__615->GetYaxis()->SetNdivisions(508);
   data_obs_pass_prefit_projy0_copy__615->GetYaxis()->SetLabelFont(42);
   data_obs_pass_prefit_projy0_copy__615->GetYaxis()->SetLabelOffset(0.007);
   data_obs_pass_prefit_projy0_copy__615->GetYaxis()->SetLabelSize(0.07);
   data_obs_pass_prefit_projy0_copy__615->GetYaxis()->SetTitleSize(0.09);
   data_obs_pass_prefit_projy0_copy__615->GetYaxis()->SetTitleOffset(0.8);
   data_obs_pass_prefit_projy0_copy__615->GetYaxis()->SetTitleFont(42);
   data_obs_pass_prefit_projy0_copy__615->GetZaxis()->SetLabelFont(42);
   data_obs_pass_prefit_projy0_copy__615->GetZaxis()->SetLabelOffset(0.007);
   data_obs_pass_prefit_projy0_copy__615->GetZaxis()->SetLabelSize(0.05);
   data_obs_pass_prefit_projy0_copy__615->GetZaxis()->SetTitleSize(0.08);
   data_obs_pass_prefit_projy0_copy__615->GetZaxis()->SetTitleFont(42);
   data_obs_pass_prefit_projy0_copy__615->Draw("sameaxis");
   TLatex *   tex = new TLatex(0.21,0.83,"55 < p_{T} < 200 GeV, F^{Pixels}_{i} > 0.9");
tex->SetNDC();
   tex->SetTextAlign(12);
   tex->SetTextFont(42);
   tex->SetTextSize(0.06);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.17,0.92,"CMS");
tex->SetNDC();
   tex->SetTextFont(61);
   tex->SetTextSize(0.0675);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.25,0.92,"Preliminary");
tex->SetNDC();
   tex->SetTextFont(52);
   tex->SetTextSize(0.0485);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.95,0.92,"101 fb^{-1} (13 TeV)");
tex->SetNDC();
   tex->SetTextAlign(31);
   tex->SetTextFont(42);
   tex->SetTextSize(0.07);
   tex->SetLineWidth(2);
   tex->Draw();
   data_obs_pass_prefit_projy0_main->Modified();
   plots_fit_s/base_figs/prefit_projy0_pass->cd();
  
// ------------>Primitives in pad: data_obs_pass_prefit_projy0_sub
   TPad *data_obs_pass_prefit_projy0_sub = new TPad("data_obs_pass_prefit_projy0_sub", "data_obs_pass_prefit_projy0_sub",0,0,1,0.35);
   data_obs_pass_prefit_projy0_sub->Draw();
   data_obs_pass_prefit_projy0_sub->cd();
   data_obs_pass_prefit_projy0_sub->Range(17.30769,-6.023077,209.6154,2.9);
   data_obs_pass_prefit_projy0_sub->SetFillColor(0);
   data_obs_pass_prefit_projy0_sub->SetBorderMode(0);
   data_obs_pass_prefit_projy0_sub->SetBorderSize(2);
   data_obs_pass_prefit_projy0_sub->SetTickx(1);
   data_obs_pass_prefit_projy0_sub->SetTicky(1);
   data_obs_pass_prefit_projy0_sub->SetLeftMargin(0.17);
   data_obs_pass_prefit_projy0_sub->SetRightMargin(0.05);
   data_obs_pass_prefit_projy0_sub->SetTopMargin(0);
   data_obs_pass_prefit_projy0_sub->SetBottomMargin(0.35);
   data_obs_pass_prefit_projy0_sub->SetFrameFillStyle(0);
   data_obs_pass_prefit_projy0_sub->SetFrameBorderMode(0);
   data_obs_pass_prefit_projy0_sub->SetFrameFillStyle(0);
   data_obs_pass_prefit_projy0_sub->SetFrameBorderMode(0);
   Double_t xAxis968[2] = {50, 200}; 
   
   TH1D *data_obs_pass_prefit_projy0_pull__616 = new TH1D("data_obs_pass_prefit_projy0_pull__616","",1, xAxis968);
   data_obs_pass_prefit_projy0_pull__616->SetBinContent(1,18.09937);
   data_obs_pass_prefit_projy0_pull__616->SetBinError(1,120835.1);
   data_obs_pass_prefit_projy0_pull__616->SetMinimum(-2.9);
   data_obs_pass_prefit_projy0_pull__616->SetMaximum(2.9);
   data_obs_pass_prefit_projy0_pull__616->SetEntries(328.5873);
   data_obs_pass_prefit_projy0_pull__616->SetStats(0);

   ci = TColor::GetColor("#0000ff");
   data_obs_pass_prefit_projy0_pull__616->SetFillColor(ci);

   ci = TColor::GetColor("#000000");
   data_obs_pass_prefit_projy0_pull__616->SetLineColor(ci);
   data_obs_pass_prefit_projy0_pull__616->SetLineStyle(0);

   ci = TColor::GetColor("#000000");
   data_obs_pass_prefit_projy0_pull__616->SetMarkerColor(ci);
   data_obs_pass_prefit_projy0_pull__616->SetMarkerStyle(8);
   data_obs_pass_prefit_projy0_pull__616->GetXaxis()->SetTitle("p_{T}");
   data_obs_pass_prefit_projy0_pull__616->GetXaxis()->SetLabelFont(42);
   data_obs_pass_prefit_projy0_pull__616->GetXaxis()->SetLabelOffset(0.05);
   data_obs_pass_prefit_projy0_pull__616->GetXaxis()->SetLabelSize(0.13);
   data_obs_pass_prefit_projy0_pull__616->GetXaxis()->SetTitleSize(0.15);
   data_obs_pass_prefit_projy0_pull__616->GetXaxis()->SetTitleOffset(1.15);
   data_obs_pass_prefit_projy0_pull__616->GetXaxis()->SetTitleFont(42);
   data_obs_pass_prefit_projy0_pull__616->GetYaxis()->SetTitle("(Data-Bkg)/#sigma");
   data_obs_pass_prefit_projy0_pull__616->GetYaxis()->SetNdivisions(306);
   data_obs_pass_prefit_projy0_pull__616->GetYaxis()->SetLabelFont(42);
   data_obs_pass_prefit_projy0_pull__616->GetYaxis()->SetLabelOffset(0.007);
   data_obs_pass_prefit_projy0_pull__616->GetYaxis()->SetLabelSize(0.13);
   data_obs_pass_prefit_projy0_pull__616->GetYaxis()->SetTitleSize(0.12);
   data_obs_pass_prefit_projy0_pull__616->GetYaxis()->SetTitleOffset(0.4);
   data_obs_pass_prefit_projy0_pull__616->GetYaxis()->SetTitleFont(42);
   data_obs_pass_prefit_projy0_pull__616->GetZaxis()->SetLabelFont(42);
   data_obs_pass_prefit_projy0_pull__616->GetZaxis()->SetLabelOffset(0.007);
   data_obs_pass_prefit_projy0_pull__616->GetZaxis()->SetLabelSize(0.05);
   data_obs_pass_prefit_projy0_pull__616->GetZaxis()->SetTitleSize(0.08);
   data_obs_pass_prefit_projy0_pull__616->GetZaxis()->SetTitleFont(42);
   data_obs_pass_prefit_projy0_pull__616->Draw("hist");
   data_obs_pass_prefit_projy0_sub->Modified();
   plots_fit_s/base_figs/prefit_projy0_pass->cd();
   plots_fit_s/base_figs/prefit_projy0_pass->Modified();
   plots_fit_s/base_figs/prefit_projy0_pass->cd();
   plots_fit_s/base_figs/prefit_projy0_pass->SetSelected(plots_fit_s/base_figs/prefit_projy0_pass);
}
