void prefit_projx0_fail()
{
//=========Macro generated from canvas: plots_fit_s/base_figs/prefit_projx0_fail/plots_fit_s/base_figs/prefit_projx0_fail
//=========  (Fri Jan 12 21:00:33 2024) by ROOT version 6.14/09
   TCanvas *plots_fit_s/base_figs/prefit_projx0_fail = new TCanvas("plots_fit_s/base_figs/prefit_projx0_fail", "plots_fit_s/base_figs/prefit_projx0_fail",0,0,800,700);
   gStyle->SetOptFit(1);
   gStyle->SetOptStat(0);
   plots_fit_s/base_figs/prefit_projx0_fail->SetHighLightColor(2);
   plots_fit_s/base_figs/prefit_projx0_fail->Range(0,0,1,1);
   plots_fit_s/base_figs/prefit_projx0_fail->SetFillColor(0);
   plots_fit_s/base_figs/prefit_projx0_fail->SetBorderMode(0);
   plots_fit_s/base_figs/prefit_projx0_fail->SetBorderSize(2);
   plots_fit_s/base_figs/prefit_projx0_fail->SetTickx(1);
   plots_fit_s/base_figs/prefit_projx0_fail->SetTicky(1);
   plots_fit_s/base_figs/prefit_projx0_fail->SetLeftMargin(0.16);
   plots_fit_s/base_figs/prefit_projx0_fail->SetRightMargin(0);
   plots_fit_s/base_figs/prefit_projx0_fail->SetTopMargin(0);
   plots_fit_s/base_figs/prefit_projx0_fail->SetBottomMargin(0);
   plots_fit_s/base_figs/prefit_projx0_fail->SetFrameFillStyle(0);
   plots_fit_s/base_figs/prefit_projx0_fail->SetFrameBorderMode(0);
  
// ------------>Primitives in pad: data_obs_fail_prefit_projx0_main
   TPad *data_obs_fail_prefit_projx0_main = new TPad("data_obs_fail_prefit_projx0_main", "data_obs_fail_prefit_projx0_main",0,0.35,1,1);
   data_obs_fail_prefit_projx0_main->Draw();
   data_obs_fail_prefit_projx0_main->cd();
   data_obs_fail_prefit_projx0_main->Range(-0.2179487,-0.04651163,1.064103,1.116279);
   data_obs_fail_prefit_projx0_main->SetFillColor(0);
   data_obs_fail_prefit_projx0_main->SetBorderMode(0);
   data_obs_fail_prefit_projx0_main->SetBorderSize(2);
   data_obs_fail_prefit_projx0_main->SetTickx(1);
   data_obs_fail_prefit_projx0_main->SetTicky(1);
   data_obs_fail_prefit_projx0_main->SetLeftMargin(0.17);
   data_obs_fail_prefit_projx0_main->SetRightMargin(0.05);
   data_obs_fail_prefit_projx0_main->SetBottomMargin(0.04);
   data_obs_fail_prefit_projx0_main->SetFrameFillStyle(0);
   data_obs_fail_prefit_projx0_main->SetFrameBorderMode(0);
   data_obs_fail_prefit_projx0_main->SetFrameFillStyle(0);
   data_obs_fail_prefit_projx0_main->SetFrameBorderMode(0);
   Double_t xAxis793[10] = {0, 0.04, 0.08, 0.12, 0.16, 0.2, 0.24, 0.28, 0.32, 1}; 
   
   TH1D *data_obs_fail_prefit_projx0__505 = new TH1D("data_obs_fail_prefit_projx0__505","",9, xAxis793);
   data_obs_fail_prefit_projx0__505->SetMinimum(0);
   data_obs_fail_prefit_projx0__505->SetMaximum(0);

   Int_t ci;      // for color index setting
   TColor *color; // for color definition with alpha
   ci = TColor::GetColor("#000000");
   data_obs_fail_prefit_projx0__505->SetLineColor(ci);
   data_obs_fail_prefit_projx0__505->SetLineStyle(0);

   ci = TColor::GetColor("#000000");
   data_obs_fail_prefit_projx0__505->SetMarkerColor(ci);
   data_obs_fail_prefit_projx0__505->SetMarkerStyle(8);
   data_obs_fail_prefit_projx0__505->GetXaxis()->SetTitle("G_{i}^{Strips}");
   data_obs_fail_prefit_projx0__505->GetXaxis()->SetLabelFont(42);
   data_obs_fail_prefit_projx0__505->GetXaxis()->SetLabelOffset(0.05);
   data_obs_fail_prefit_projx0__505->GetXaxis()->SetLabelSize(0.07);
   data_obs_fail_prefit_projx0__505->GetXaxis()->SetTitleSize(0.09);
   data_obs_fail_prefit_projx0__505->GetXaxis()->SetTitleOffset(1.15);
   data_obs_fail_prefit_projx0__505->GetXaxis()->SetTitleFont(42);
   data_obs_fail_prefit_projx0__505->GetYaxis()->SetTitle("Events / bin");
   data_obs_fail_prefit_projx0__505->GetYaxis()->SetNdivisions(508);
   data_obs_fail_prefit_projx0__505->GetYaxis()->SetLabelFont(42);
   data_obs_fail_prefit_projx0__505->GetYaxis()->SetLabelOffset(0.007);
   data_obs_fail_prefit_projx0__505->GetYaxis()->SetLabelSize(0.07);
   data_obs_fail_prefit_projx0__505->GetYaxis()->SetTitleSize(0.09);
   data_obs_fail_prefit_projx0__505->GetYaxis()->SetTitleOffset(0.8);
   data_obs_fail_prefit_projx0__505->GetYaxis()->SetTitleFont(42);
   data_obs_fail_prefit_projx0__505->GetZaxis()->SetLabelFont(42);
   data_obs_fail_prefit_projx0__505->GetZaxis()->SetLabelOffset(0.007);
   data_obs_fail_prefit_projx0__505->GetZaxis()->SetLabelSize(0.05);
   data_obs_fail_prefit_projx0__505->GetZaxis()->SetTitleSize(0.08);
   data_obs_fail_prefit_projx0__505->GetZaxis()->SetTitleFont(42);
   data_obs_fail_prefit_projx0__505->Draw("pe X0");
   
   THStack *prefit_projx0_fail_stack = new THStack();
   prefit_projx0_fail_stack->SetName("prefit_projx0_fail_stack");
   prefit_projx0_fail_stack->SetTitle("prefit_projx0_fail_stack");
   Double_t xAxis794[10] = {0, 0.04, 0.08, 0.12, 0.16, 0.2, 0.24, 0.28, 0.32, 1}; 
   
   TH1F *prefit_projx0_fail_stack_stack_145 = new TH1F("prefit_projx0_fail_stack_stack_145","prefit_projx0_fail_stack",9, xAxis794);
   prefit_projx0_fail_stack_stack_145->SetMinimum(0);
   prefit_projx0_fail_stack_stack_145->SetMaximum(0);
   prefit_projx0_fail_stack_stack_145->SetDirectory(0);
   prefit_projx0_fail_stack_stack_145->SetStats(0);
   prefit_projx0_fail_stack_stack_145->SetLineStyle(0);
   prefit_projx0_fail_stack_stack_145->GetXaxis()->SetLabelFont(42);
   prefit_projx0_fail_stack_stack_145->GetXaxis()->SetLabelOffset(0.007);
   prefit_projx0_fail_stack_stack_145->GetXaxis()->SetLabelSize(0.05);
   prefit_projx0_fail_stack_stack_145->GetXaxis()->SetTitleSize(0.08);
   prefit_projx0_fail_stack_stack_145->GetXaxis()->SetTitleOffset(0.9);
   prefit_projx0_fail_stack_stack_145->GetXaxis()->SetTitleFont(42);
   prefit_projx0_fail_stack_stack_145->GetYaxis()->SetNdivisions(508);
   prefit_projx0_fail_stack_stack_145->GetYaxis()->SetLabelFont(42);
   prefit_projx0_fail_stack_stack_145->GetYaxis()->SetLabelOffset(0.007);
   prefit_projx0_fail_stack_stack_145->GetYaxis()->SetLabelSize(0.05);
   prefit_projx0_fail_stack_stack_145->GetYaxis()->SetTitleSize(0.08);
   prefit_projx0_fail_stack_stack_145->GetYaxis()->SetTitleOffset(1.25);
   prefit_projx0_fail_stack_stack_145->GetYaxis()->SetTitleFont(42);
   prefit_projx0_fail_stack_stack_145->GetZaxis()->SetLabelFont(42);
   prefit_projx0_fail_stack_stack_145->GetZaxis()->SetLabelOffset(0.007);
   prefit_projx0_fail_stack_stack_145->GetZaxis()->SetLabelSize(0.05);
   prefit_projx0_fail_stack_stack_145->GetZaxis()->SetTitleSize(0.08);
   prefit_projx0_fail_stack_stack_145->GetZaxis()->SetTitleFont(42);
   prefit_projx0_fail_stack->SetHistogram(prefit_projx0_fail_stack_stack_145);
   
   Double_t xAxis795[10] = {0, 0.04, 0.08, 0.12, 0.16, 0.2, 0.24, 0.28, 0.32, 1}; 
   
   TH1D *Background_fail_prefit_projx0_stack_1 = new TH1D("Background_fail_prefit_projx0_stack_1","Background, fail, prefit, 50-50",9, xAxis795);
   Background_fail_prefit_projx0_stack_1->SetMinimum(0);

   ci = TColor::GetColor("#ffff00");
   Background_fail_prefit_projx0_stack_1->SetFillColor(ci);

   ci = 1539;
   color = new TColor(ci, 1, 1, 1, " ", 0);
   Background_fail_prefit_projx0_stack_1->SetLineColor(ci);
   Background_fail_prefit_projx0_stack_1->SetLineStyle(0);
   Background_fail_prefit_projx0_stack_1->GetXaxis()->SetTitle("G_{i}^{Strips}");
   Background_fail_prefit_projx0_stack_1->GetXaxis()->SetLabelFont(42);
   Background_fail_prefit_projx0_stack_1->GetXaxis()->SetLabelOffset(0.007);
   Background_fail_prefit_projx0_stack_1->GetXaxis()->SetLabelSize(0.05);
   Background_fail_prefit_projx0_stack_1->GetXaxis()->SetTitleSize(0.08);
   Background_fail_prefit_projx0_stack_1->GetXaxis()->SetTitleOffset(0.9);
   Background_fail_prefit_projx0_stack_1->GetXaxis()->SetTitleFont(42);
   Background_fail_prefit_projx0_stack_1->GetYaxis()->SetTitle("Events / bin");
   Background_fail_prefit_projx0_stack_1->GetYaxis()->SetLabelFont(42);
   Background_fail_prefit_projx0_stack_1->GetYaxis()->SetLabelOffset(0.007);
   Background_fail_prefit_projx0_stack_1->GetYaxis()->SetLabelSize(0.05);
   Background_fail_prefit_projx0_stack_1->GetYaxis()->SetTitleSize(0.08);
   Background_fail_prefit_projx0_stack_1->GetYaxis()->SetTitleOffset(1.25);
   Background_fail_prefit_projx0_stack_1->GetYaxis()->SetTitleFont(42);
   Background_fail_prefit_projx0_stack_1->GetZaxis()->SetLabelFont(42);
   Background_fail_prefit_projx0_stack_1->GetZaxis()->SetLabelOffset(0.007);
   Background_fail_prefit_projx0_stack_1->GetZaxis()->SetLabelSize(0.05);
   Background_fail_prefit_projx0_stack_1->GetZaxis()->SetTitleSize(0.08);
   Background_fail_prefit_projx0_stack_1->GetZaxis()->SetTitleFont(42);
   prefit_projx0_fail_stack->Add(Background_fail_prefit_projx0_stack_1,"");
   prefit_projx0_fail_stack->Draw("hist same");
   
   prefit_projx0_fail_stack = new THStack();
   prefit_projx0_fail_stack->SetName("prefit_projx0_fail_stack");
   prefit_projx0_fail_stack->SetTitle("prefit_projx0_fail_stack");
   Double_t xAxis796[10] = {0, 0.04, 0.08, 0.12, 0.16, 0.2, 0.24, 0.28, 0.32, 1}; 
   
   TH1F *prefit_projx0_fail_stack_stack_145_stack_146 = new TH1F("prefit_projx0_fail_stack_stack_145_stack_146","prefit_projx0_fail_stack",9, xAxis796);
   prefit_projx0_fail_stack_stack_145_stack_146->SetMinimum(0);
   prefit_projx0_fail_stack_stack_145_stack_146->SetMaximum(0);
   prefit_projx0_fail_stack_stack_145_stack_146->SetDirectory(0);
   prefit_projx0_fail_stack_stack_145_stack_146->SetStats(0);
   prefit_projx0_fail_stack_stack_145_stack_146->SetLineStyle(0);
   prefit_projx0_fail_stack_stack_145_stack_146->GetXaxis()->SetLabelFont(42);
   prefit_projx0_fail_stack_stack_145_stack_146->GetXaxis()->SetLabelOffset(0.007);
   prefit_projx0_fail_stack_stack_145_stack_146->GetXaxis()->SetLabelSize(0.05);
   prefit_projx0_fail_stack_stack_145_stack_146->GetXaxis()->SetTitleSize(0.08);
   prefit_projx0_fail_stack_stack_145_stack_146->GetXaxis()->SetTitleOffset(0.9);
   prefit_projx0_fail_stack_stack_145_stack_146->GetXaxis()->SetTitleFont(42);
   prefit_projx0_fail_stack_stack_145_stack_146->GetYaxis()->SetNdivisions(508);
   prefit_projx0_fail_stack_stack_145_stack_146->GetYaxis()->SetLabelFont(42);
   prefit_projx0_fail_stack_stack_145_stack_146->GetYaxis()->SetLabelOffset(0.007);
   prefit_projx0_fail_stack_stack_145_stack_146->GetYaxis()->SetLabelSize(0.05);
   prefit_projx0_fail_stack_stack_145_stack_146->GetYaxis()->SetTitleSize(0.08);
   prefit_projx0_fail_stack_stack_145_stack_146->GetYaxis()->SetTitleOffset(1.25);
   prefit_projx0_fail_stack_stack_145_stack_146->GetYaxis()->SetTitleFont(42);
   prefit_projx0_fail_stack_stack_145_stack_146->GetZaxis()->SetLabelFont(42);
   prefit_projx0_fail_stack_stack_145_stack_146->GetZaxis()->SetLabelOffset(0.007);
   prefit_projx0_fail_stack_stack_145_stack_146->GetZaxis()->SetLabelSize(0.05);
   prefit_projx0_fail_stack_stack_145_stack_146->GetZaxis()->SetTitleSize(0.08);
   prefit_projx0_fail_stack_stack_145_stack_146->GetZaxis()->SetTitleFont(42);
   prefit_projx0_fail_stack->SetHistogram(prefit_projx0_fail_stack_stack_145_stack_146);
   
   Double_t xAxis797[10] = {0, 0.04, 0.08, 0.12, 0.16, 0.2, 0.24, 0.28, 0.32, 1}; 
   
   TH1D *Background_fail_prefit_projx0_stack_1_stack_1 = new TH1D("Background_fail_prefit_projx0_stack_1_stack_1","Background, fail, prefit, 50-50",9, xAxis797);
   Background_fail_prefit_projx0_stack_1_stack_1->SetMinimum(0);

   ci = TColor::GetColor("#ffff00");
   Background_fail_prefit_projx0_stack_1_stack_1->SetFillColor(ci);

   ci = 1539;
   color = new TColor(ci, 1, 1, 1, " ", 0);
   Background_fail_prefit_projx0_stack_1_stack_1->SetLineColor(ci);
   Background_fail_prefit_projx0_stack_1_stack_1->SetLineStyle(0);
   Background_fail_prefit_projx0_stack_1_stack_1->GetXaxis()->SetTitle("G_{i}^{Strips}");
   Background_fail_prefit_projx0_stack_1_stack_1->GetXaxis()->SetLabelFont(42);
   Background_fail_prefit_projx0_stack_1_stack_1->GetXaxis()->SetLabelOffset(0.007);
   Background_fail_prefit_projx0_stack_1_stack_1->GetXaxis()->SetLabelSize(0.05);
   Background_fail_prefit_projx0_stack_1_stack_1->GetXaxis()->SetTitleSize(0.08);
   Background_fail_prefit_projx0_stack_1_stack_1->GetXaxis()->SetTitleOffset(0.9);
   Background_fail_prefit_projx0_stack_1_stack_1->GetXaxis()->SetTitleFont(42);
   Background_fail_prefit_projx0_stack_1_stack_1->GetYaxis()->SetTitle("Events / bin");
   Background_fail_prefit_projx0_stack_1_stack_1->GetYaxis()->SetLabelFont(42);
   Background_fail_prefit_projx0_stack_1_stack_1->GetYaxis()->SetLabelOffset(0.007);
   Background_fail_prefit_projx0_stack_1_stack_1->GetYaxis()->SetLabelSize(0.05);
   Background_fail_prefit_projx0_stack_1_stack_1->GetYaxis()->SetTitleSize(0.08);
   Background_fail_prefit_projx0_stack_1_stack_1->GetYaxis()->SetTitleOffset(1.25);
   Background_fail_prefit_projx0_stack_1_stack_1->GetYaxis()->SetTitleFont(42);
   Background_fail_prefit_projx0_stack_1_stack_1->GetZaxis()->SetLabelFont(42);
   Background_fail_prefit_projx0_stack_1_stack_1->GetZaxis()->SetLabelOffset(0.007);
   Background_fail_prefit_projx0_stack_1_stack_1->GetZaxis()->SetLabelSize(0.05);
   Background_fail_prefit_projx0_stack_1_stack_1->GetZaxis()->SetTitleSize(0.08);
   Background_fail_prefit_projx0_stack_1_stack_1->GetZaxis()->SetTitleFont(42);
   prefit_projx0_fail_stack->Add(Background_fail_prefit_projx0_stack_1_stack_1,"");
   prefit_projx0_fail_stack->Draw("hist same");
   Double_t xAxis798[10] = {0, 0.04, 0.08, 0.12, 0.16, 0.2, 0.24, 0.28, 0.32, 1}; 
   
   TH1D *Signal_ppStaumI557_fail_prefit_projx0__506 = new TH1D("Signal_ppStaumI557_fail_prefit_projx0__506","HSCP signal, fail, prefit, 50-50",9, xAxis798);
   Signal_ppStaumI557_fail_prefit_projx0__506->SetMinimum(0);
   Signal_ppStaumI557_fail_prefit_projx0__506->SetLineColor(2);
   Signal_ppStaumI557_fail_prefit_projx0__506->SetLineStyle(0);
   Signal_ppStaumI557_fail_prefit_projx0__506->GetXaxis()->SetTitle("G_{i}^{Strips}");
   Signal_ppStaumI557_fail_prefit_projx0__506->GetXaxis()->SetLabelFont(42);
   Signal_ppStaumI557_fail_prefit_projx0__506->GetXaxis()->SetLabelOffset(0.007);
   Signal_ppStaumI557_fail_prefit_projx0__506->GetXaxis()->SetLabelSize(0.05);
   Signal_ppStaumI557_fail_prefit_projx0__506->GetXaxis()->SetTitleSize(0.08);
   Signal_ppStaumI557_fail_prefit_projx0__506->GetXaxis()->SetTitleOffset(0.9);
   Signal_ppStaumI557_fail_prefit_projx0__506->GetXaxis()->SetTitleFont(42);
   Signal_ppStaumI557_fail_prefit_projx0__506->GetYaxis()->SetTitle("Events / bin");
   Signal_ppStaumI557_fail_prefit_projx0__506->GetYaxis()->SetLabelFont(42);
   Signal_ppStaumI557_fail_prefit_projx0__506->GetYaxis()->SetLabelOffset(0.007);
   Signal_ppStaumI557_fail_prefit_projx0__506->GetYaxis()->SetLabelSize(0.05);
   Signal_ppStaumI557_fail_prefit_projx0__506->GetYaxis()->SetTitleSize(0.08);
   Signal_ppStaumI557_fail_prefit_projx0__506->GetYaxis()->SetTitleOffset(1.25);
   Signal_ppStaumI557_fail_prefit_projx0__506->GetYaxis()->SetTitleFont(42);
   Signal_ppStaumI557_fail_prefit_projx0__506->GetZaxis()->SetLabelFont(42);
   Signal_ppStaumI557_fail_prefit_projx0__506->GetZaxis()->SetLabelOffset(0.007);
   Signal_ppStaumI557_fail_prefit_projx0__506->GetZaxis()->SetLabelSize(0.05);
   Signal_ppStaumI557_fail_prefit_projx0__506->GetZaxis()->SetTitleSize(0.08);
   Signal_ppStaumI557_fail_prefit_projx0__506->GetZaxis()->SetTitleFont(42);
   Signal_ppStaumI557_fail_prefit_projx0__506->Draw("hist same");
   Double_t xAxis799[10] = {0, 0.04, 0.08, 0.12, 0.16, 0.2, 0.24, 0.28, 0.32, 1}; 
   
   TH1D *TotalBkg_fail_prefit_projx0__507 = new TH1D("TotalBkg_fail_prefit_projx0__507","TotalBkg, fail, prefit, 50-50",9, xAxis799);
   TotalBkg_fail_prefit_projx0__507->SetMinimum(0);
   TotalBkg_fail_prefit_projx0__507->SetLineStyle(0);
   TotalBkg_fail_prefit_projx0__507->SetMarkerStyle(0);
   TotalBkg_fail_prefit_projx0__507->GetXaxis()->SetTitle("G_{i}^{Strips}");
   TotalBkg_fail_prefit_projx0__507->GetXaxis()->SetLabelFont(42);
   TotalBkg_fail_prefit_projx0__507->GetXaxis()->SetLabelOffset(0.007);
   TotalBkg_fail_prefit_projx0__507->GetXaxis()->SetLabelSize(0.05);
   TotalBkg_fail_prefit_projx0__507->GetXaxis()->SetTitleSize(0.08);
   TotalBkg_fail_prefit_projx0__507->GetXaxis()->SetTitleOffset(0.9);
   TotalBkg_fail_prefit_projx0__507->GetXaxis()->SetTitleFont(42);
   TotalBkg_fail_prefit_projx0__507->GetYaxis()->SetTitle("Events / bin");
   TotalBkg_fail_prefit_projx0__507->GetYaxis()->SetLabelFont(42);
   TotalBkg_fail_prefit_projx0__507->GetYaxis()->SetLabelOffset(0.007);
   TotalBkg_fail_prefit_projx0__507->GetYaxis()->SetLabelSize(0.05);
   TotalBkg_fail_prefit_projx0__507->GetYaxis()->SetTitleSize(0.08);
   TotalBkg_fail_prefit_projx0__507->GetYaxis()->SetTitleOffset(1.25);
   TotalBkg_fail_prefit_projx0__507->GetYaxis()->SetTitleFont(42);
   TotalBkg_fail_prefit_projx0__507->GetZaxis()->SetLabelFont(42);
   TotalBkg_fail_prefit_projx0__507->GetZaxis()->SetLabelOffset(0.007);
   TotalBkg_fail_prefit_projx0__507->GetZaxis()->SetLabelSize(0.05);
   TotalBkg_fail_prefit_projx0__507->GetZaxis()->SetTitleSize(0.08);
   TotalBkg_fail_prefit_projx0__507->GetZaxis()->SetTitleFont(42);
   TotalBkg_fail_prefit_projx0__507->Draw("hist same");
   Double_t xAxis800[10] = {0, 0.04, 0.08, 0.12, 0.16, 0.2, 0.24, 0.28, 0.32, 1}; 
   
   TH1D *TotalBkg_fail_prefit_projx0__508 = new TH1D("TotalBkg_fail_prefit_projx0__508","TotalBkg, fail, prefit, 50-50",9, xAxis800);
   TotalBkg_fail_prefit_projx0__508->SetMinimum(0);
   TotalBkg_fail_prefit_projx0__508->SetFillColor(1);
   TotalBkg_fail_prefit_projx0__508->SetFillStyle(3354);
   TotalBkg_fail_prefit_projx0__508->SetLineStyle(0);
   TotalBkg_fail_prefit_projx0__508->SetLineWidth(0);
   TotalBkg_fail_prefit_projx0__508->SetMarkerStyle(0);
   TotalBkg_fail_prefit_projx0__508->GetXaxis()->SetTitle("G_{i}^{Strips}");
   TotalBkg_fail_prefit_projx0__508->GetXaxis()->SetLabelFont(42);
   TotalBkg_fail_prefit_projx0__508->GetXaxis()->SetLabelOffset(0.007);
   TotalBkg_fail_prefit_projx0__508->GetXaxis()->SetLabelSize(0.05);
   TotalBkg_fail_prefit_projx0__508->GetXaxis()->SetTitleSize(0.08);
   TotalBkg_fail_prefit_projx0__508->GetXaxis()->SetTitleOffset(0.9);
   TotalBkg_fail_prefit_projx0__508->GetXaxis()->SetTitleFont(42);
   TotalBkg_fail_prefit_projx0__508->GetYaxis()->SetTitle("Events / bin");
   TotalBkg_fail_prefit_projx0__508->GetYaxis()->SetLabelFont(42);
   TotalBkg_fail_prefit_projx0__508->GetYaxis()->SetLabelOffset(0.007);
   TotalBkg_fail_prefit_projx0__508->GetYaxis()->SetLabelSize(0.05);
   TotalBkg_fail_prefit_projx0__508->GetYaxis()->SetTitleSize(0.08);
   TotalBkg_fail_prefit_projx0__508->GetYaxis()->SetTitleOffset(1.25);
   TotalBkg_fail_prefit_projx0__508->GetYaxis()->SetTitleFont(42);
   TotalBkg_fail_prefit_projx0__508->GetZaxis()->SetLabelFont(42);
   TotalBkg_fail_prefit_projx0__508->GetZaxis()->SetLabelOffset(0.007);
   TotalBkg_fail_prefit_projx0__508->GetZaxis()->SetLabelSize(0.05);
   TotalBkg_fail_prefit_projx0__508->GetZaxis()->SetTitleSize(0.08);
   TotalBkg_fail_prefit_projx0__508->GetZaxis()->SetTitleFont(42);
   TotalBkg_fail_prefit_projx0__508->Draw("e2 same");
   Double_t xAxis801[10] = {0, 0.04, 0.08, 0.12, 0.16, 0.2, 0.24, 0.28, 0.32, 1}; 
   
   TH1D *data_obs_fail_prefit_projx0__509 = new TH1D("data_obs_fail_prefit_projx0__509","",9, xAxis801);
   data_obs_fail_prefit_projx0__509->SetMinimum(0);
   data_obs_fail_prefit_projx0__509->SetMaximum(0);

   ci = TColor::GetColor("#000000");
   data_obs_fail_prefit_projx0__509->SetLineColor(ci);
   data_obs_fail_prefit_projx0__509->SetLineStyle(0);

   ci = TColor::GetColor("#000000");
   data_obs_fail_prefit_projx0__509->SetMarkerColor(ci);
   data_obs_fail_prefit_projx0__509->SetMarkerStyle(8);
   data_obs_fail_prefit_projx0__509->GetXaxis()->SetTitle("G_{i}^{Strips}");
   data_obs_fail_prefit_projx0__509->GetXaxis()->SetLabelFont(42);
   data_obs_fail_prefit_projx0__509->GetXaxis()->SetLabelOffset(0.05);
   data_obs_fail_prefit_projx0__509->GetXaxis()->SetLabelSize(0.07);
   data_obs_fail_prefit_projx0__509->GetXaxis()->SetTitleSize(0.09);
   data_obs_fail_prefit_projx0__509->GetXaxis()->SetTitleOffset(1.15);
   data_obs_fail_prefit_projx0__509->GetXaxis()->SetTitleFont(42);
   data_obs_fail_prefit_projx0__509->GetYaxis()->SetTitle("Events / bin");
   data_obs_fail_prefit_projx0__509->GetYaxis()->SetNdivisions(508);
   data_obs_fail_prefit_projx0__509->GetYaxis()->SetLabelFont(42);
   data_obs_fail_prefit_projx0__509->GetYaxis()->SetLabelOffset(0.007);
   data_obs_fail_prefit_projx0__509->GetYaxis()->SetLabelSize(0.07);
   data_obs_fail_prefit_projx0__509->GetYaxis()->SetTitleSize(0.09);
   data_obs_fail_prefit_projx0__509->GetYaxis()->SetTitleOffset(0.8);
   data_obs_fail_prefit_projx0__509->GetYaxis()->SetTitleFont(42);
   data_obs_fail_prefit_projx0__509->GetZaxis()->SetLabelFont(42);
   data_obs_fail_prefit_projx0__509->GetZaxis()->SetLabelOffset(0.007);
   data_obs_fail_prefit_projx0__509->GetZaxis()->SetLabelSize(0.05);
   data_obs_fail_prefit_projx0__509->GetZaxis()->SetTitleSize(0.08);
   data_obs_fail_prefit_projx0__509->GetZaxis()->SetTitleFont(42);
   data_obs_fail_prefit_projx0__509->Draw("pe X0 same");
   
   TLegend *leg = new TLegend(0.65,0.64,0.9,0.88,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(1001);
   TLegendEntry *entry=leg->AddEntry("data_obs_fail_prefit_projx0","Data","pe X0");

   ci = TColor::GetColor("#000000");
   entry->SetLineColor(ci);
   entry->SetLineWidth(1);

   ci = TColor::GetColor("#000000");
   entry->SetMarkerColor(ci);
   entry->SetMarkerStyle(8);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("TotalBkg_fail_prefit_projx0","Total bkg unc.","F");
   entry->SetFillColor(1);
   entry->SetFillStyle(3354);
   entry->SetLineColor(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("Signal_ppStau-557_fail_prefit_projx0","HSCP signal","L");
   entry->SetLineColor(2);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("Background_fail_prefit_projx0_stack_1_stack_1","Background","f");

   ci = TColor::GetColor("#ffff00");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = 1539;
   color = new TColor(ci, 1, 1, 1, " ", 0);
   entry->SetLineColor(ci);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   leg->Draw();
   Double_t xAxis802[10] = {0, 0.04, 0.08, 0.12, 0.16, 0.2, 0.24, 0.28, 0.32, 1}; 
   
   TH1D *data_obs_fail_prefit_projx0_copy__510 = new TH1D("data_obs_fail_prefit_projx0_copy__510","",9, xAxis802);
   data_obs_fail_prefit_projx0_copy__510->SetMinimum(0);
   data_obs_fail_prefit_projx0_copy__510->SetMaximum(0);
   data_obs_fail_prefit_projx0_copy__510->SetDirectory(0);

   ci = TColor::GetColor("#000000");
   data_obs_fail_prefit_projx0_copy__510->SetLineColor(ci);
   data_obs_fail_prefit_projx0_copy__510->SetLineStyle(0);

   ci = TColor::GetColor("#000000");
   data_obs_fail_prefit_projx0_copy__510->SetMarkerColor(ci);
   data_obs_fail_prefit_projx0_copy__510->SetMarkerStyle(8);
   data_obs_fail_prefit_projx0_copy__510->GetXaxis()->SetTitle("G_{i}^{Strips}");
   data_obs_fail_prefit_projx0_copy__510->GetXaxis()->SetLabelFont(42);
   data_obs_fail_prefit_projx0_copy__510->GetXaxis()->SetLabelOffset(0.05);
   data_obs_fail_prefit_projx0_copy__510->GetXaxis()->SetLabelSize(0.07);
   data_obs_fail_prefit_projx0_copy__510->GetXaxis()->SetTitleSize(0.09);
   data_obs_fail_prefit_projx0_copy__510->GetXaxis()->SetTitleOffset(1.15);
   data_obs_fail_prefit_projx0_copy__510->GetXaxis()->SetTitleFont(42);
   data_obs_fail_prefit_projx0_copy__510->GetYaxis()->SetTitle("Events / bin");
   data_obs_fail_prefit_projx0_copy__510->GetYaxis()->SetNdivisions(508);
   data_obs_fail_prefit_projx0_copy__510->GetYaxis()->SetLabelFont(42);
   data_obs_fail_prefit_projx0_copy__510->GetYaxis()->SetLabelOffset(0.007);
   data_obs_fail_prefit_projx0_copy__510->GetYaxis()->SetLabelSize(0.07);
   data_obs_fail_prefit_projx0_copy__510->GetYaxis()->SetTitleSize(0.09);
   data_obs_fail_prefit_projx0_copy__510->GetYaxis()->SetTitleOffset(0.8);
   data_obs_fail_prefit_projx0_copy__510->GetYaxis()->SetTitleFont(42);
   data_obs_fail_prefit_projx0_copy__510->GetZaxis()->SetLabelFont(42);
   data_obs_fail_prefit_projx0_copy__510->GetZaxis()->SetLabelOffset(0.007);
   data_obs_fail_prefit_projx0_copy__510->GetZaxis()->SetLabelSize(0.05);
   data_obs_fail_prefit_projx0_copy__510->GetZaxis()->SetTitleSize(0.08);
   data_obs_fail_prefit_projx0_copy__510->GetZaxis()->SetTitleFont(42);
   data_obs_fail_prefit_projx0_copy__510->Draw("sameaxis");
   TLatex *   tex = new TLatex(0.21,0.83,"55 < p_{T} < 200 GeV, F^{Pixels}_{i} < 0.9");
tex->SetNDC();
   tex->SetTextAlign(12);
   tex->SetTextFont(42);
   tex->SetTextSize(0.06);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.17,0.92,"CMS");
tex->SetNDC();
   tex->SetTextFont(61);
   tex->SetTextSize(0.0675);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.25,0.92,"Preliminary");
tex->SetNDC();
   tex->SetTextFont(52);
   tex->SetTextSize(0.0485);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.95,0.92,"101 fb^{-1} (13 TeV)");
tex->SetNDC();
   tex->SetTextAlign(31);
   tex->SetTextFont(42);
   tex->SetTextSize(0.07);
   tex->SetLineWidth(2);
   tex->Draw();
   data_obs_fail_prefit_projx0_main->Modified();
   plots_fit_s/base_figs/prefit_projx0_fail->cd();
  
// ------------>Primitives in pad: data_obs_fail_prefit_projx0_sub
   TPad *data_obs_fail_prefit_projx0_sub = new TPad("data_obs_fail_prefit_projx0_sub", "data_obs_fail_prefit_projx0_sub",0,0,1,0.35);
   data_obs_fail_prefit_projx0_sub->Draw();
   data_obs_fail_prefit_projx0_sub->cd();
   data_obs_fail_prefit_projx0_sub->Range(-0.2179487,-6.023077,1.064103,2.9);
   data_obs_fail_prefit_projx0_sub->SetFillColor(0);
   data_obs_fail_prefit_projx0_sub->SetBorderMode(0);
   data_obs_fail_prefit_projx0_sub->SetBorderSize(2);
   data_obs_fail_prefit_projx0_sub->SetTickx(1);
   data_obs_fail_prefit_projx0_sub->SetTicky(1);
   data_obs_fail_prefit_projx0_sub->SetLeftMargin(0.17);
   data_obs_fail_prefit_projx0_sub->SetRightMargin(0.05);
   data_obs_fail_prefit_projx0_sub->SetTopMargin(0);
   data_obs_fail_prefit_projx0_sub->SetBottomMargin(0.35);
   data_obs_fail_prefit_projx0_sub->SetFrameFillStyle(0);
   data_obs_fail_prefit_projx0_sub->SetFrameBorderMode(0);
   data_obs_fail_prefit_projx0_sub->SetFrameFillStyle(0);
   data_obs_fail_prefit_projx0_sub->SetFrameBorderMode(0);
   Double_t xAxis803[10] = {0, 0.04, 0.08, 0.12, 0.16, 0.2, 0.24, 0.28, 0.32, 1}; 
   
   TH1D *data_obs_fail_prefit_projx0_pull__511 = new TH1D("data_obs_fail_prefit_projx0_pull__511","",9, xAxis803);
   data_obs_fail_prefit_projx0_pull__511->SetMinimum(-2.9);
   data_obs_fail_prefit_projx0_pull__511->SetMaximum(2.9);
   data_obs_fail_prefit_projx0_pull__511->SetEntries(18);
   data_obs_fail_prefit_projx0_pull__511->SetStats(0);

   ci = TColor::GetColor("#0000ff");
   data_obs_fail_prefit_projx0_pull__511->SetFillColor(ci);

   ci = TColor::GetColor("#000000");
   data_obs_fail_prefit_projx0_pull__511->SetLineColor(ci);
   data_obs_fail_prefit_projx0_pull__511->SetLineStyle(0);

   ci = TColor::GetColor("#000000");
   data_obs_fail_prefit_projx0_pull__511->SetMarkerColor(ci);
   data_obs_fail_prefit_projx0_pull__511->SetMarkerStyle(8);
   data_obs_fail_prefit_projx0_pull__511->GetXaxis()->SetTitle("G_{i}^{Strips}");
   data_obs_fail_prefit_projx0_pull__511->GetXaxis()->SetLabelFont(42);
   data_obs_fail_prefit_projx0_pull__511->GetXaxis()->SetLabelOffset(0.05);
   data_obs_fail_prefit_projx0_pull__511->GetXaxis()->SetLabelSize(0.13);
   data_obs_fail_prefit_projx0_pull__511->GetXaxis()->SetTitleSize(0.15);
   data_obs_fail_prefit_projx0_pull__511->GetXaxis()->SetTitleOffset(1.15);
   data_obs_fail_prefit_projx0_pull__511->GetXaxis()->SetTitleFont(42);
   data_obs_fail_prefit_projx0_pull__511->GetYaxis()->SetTitle("(Data-Bkg)/#sigma");
   data_obs_fail_prefit_projx0_pull__511->GetYaxis()->SetNdivisions(306);
   data_obs_fail_prefit_projx0_pull__511->GetYaxis()->SetLabelFont(42);
   data_obs_fail_prefit_projx0_pull__511->GetYaxis()->SetLabelOffset(0.007);
   data_obs_fail_prefit_projx0_pull__511->GetYaxis()->SetLabelSize(0.13);
   data_obs_fail_prefit_projx0_pull__511->GetYaxis()->SetTitleSize(0.12);
   data_obs_fail_prefit_projx0_pull__511->GetYaxis()->SetTitleOffset(0.4);
   data_obs_fail_prefit_projx0_pull__511->GetYaxis()->SetTitleFont(42);
   data_obs_fail_prefit_projx0_pull__511->GetZaxis()->SetLabelFont(42);
   data_obs_fail_prefit_projx0_pull__511->GetZaxis()->SetLabelOffset(0.007);
   data_obs_fail_prefit_projx0_pull__511->GetZaxis()->SetLabelSize(0.05);
   data_obs_fail_prefit_projx0_pull__511->GetZaxis()->SetTitleSize(0.08);
   data_obs_fail_prefit_projx0_pull__511->GetZaxis()->SetTitleFont(42);
   data_obs_fail_prefit_projx0_pull__511->Draw("hist");
   data_obs_fail_prefit_projx0_sub->Modified();
   plots_fit_s/base_figs/prefit_projx0_fail->cd();
   plots_fit_s/base_figs/prefit_projx0_fail->Modified();
   plots_fit_s/base_figs/prefit_projx0_fail->cd();
   plots_fit_s/base_figs/prefit_projx0_fail->SetSelected(plots_fit_s/base_figs/prefit_projx0_fail);
}
