void prefit_projx0_pass_logy()
{
//=========Macro generated from canvas: plots_fit_s/base_figs/prefit_projx0_pass_logy/plots_fit_s/base_figs/prefit_projx0_pass_logy
//=========  (Fri Jan 12 21:00:35 2024) by ROOT version 6.14/09
   TCanvas *plots_fit_s/base_figs/prefit_projx0_pass_logy = new TCanvas("plots_fit_s/base_figs/prefit_projx0_pass_logy", "plots_fit_s/base_figs/prefit_projx0_pass_logy",0,0,800,700);
   gStyle->SetOptFit(1);
   gStyle->SetOptStat(0);
   plots_fit_s/base_figs/prefit_projx0_pass_logy->SetHighLightColor(2);
   plots_fit_s/base_figs/prefit_projx0_pass_logy->Range(0,0,1,1);
   plots_fit_s/base_figs/prefit_projx0_pass_logy->SetFillColor(0);
   plots_fit_s/base_figs/prefit_projx0_pass_logy->SetBorderMode(0);
   plots_fit_s/base_figs/prefit_projx0_pass_logy->SetBorderSize(2);
   plots_fit_s/base_figs/prefit_projx0_pass_logy->SetTickx(1);
   plots_fit_s/base_figs/prefit_projx0_pass_logy->SetTicky(1);
   plots_fit_s/base_figs/prefit_projx0_pass_logy->SetLeftMargin(0.16);
   plots_fit_s/base_figs/prefit_projx0_pass_logy->SetRightMargin(0);
   plots_fit_s/base_figs/prefit_projx0_pass_logy->SetTopMargin(0);
   plots_fit_s/base_figs/prefit_projx0_pass_logy->SetBottomMargin(0);
   plots_fit_s/base_figs/prefit_projx0_pass_logy->SetFrameFillStyle(0);
   plots_fit_s/base_figs/prefit_projx0_pass_logy->SetFrameBorderMode(0);
  
// ------------>Primitives in pad: data_obs_pass_prefit_projx0_main
   TPad *data_obs_pass_prefit_projx0_main = new TPad("data_obs_pass_prefit_projx0_main", "data_obs_pass_prefit_projx0_main",0,0.35,1,1);
   data_obs_pass_prefit_projx0_main->Draw();
   data_obs_pass_prefit_projx0_main->cd();
   data_obs_pass_prefit_projx0_main->Range(-0.2179487,-2.139535,1.064103,1.348837);
   data_obs_pass_prefit_projx0_main->SetFillColor(0);
   data_obs_pass_prefit_projx0_main->SetBorderMode(0);
   data_obs_pass_prefit_projx0_main->SetBorderSize(2);
   data_obs_pass_prefit_projx0_main->SetLogy();
   data_obs_pass_prefit_projx0_main->SetTickx(1);
   data_obs_pass_prefit_projx0_main->SetTicky(1);
   data_obs_pass_prefit_projx0_main->SetLeftMargin(0.17);
   data_obs_pass_prefit_projx0_main->SetRightMargin(0.05);
   data_obs_pass_prefit_projx0_main->SetBottomMargin(0.04);
   data_obs_pass_prefit_projx0_main->SetFrameFillStyle(0);
   data_obs_pass_prefit_projx0_main->SetFrameBorderMode(0);
   data_obs_pass_prefit_projx0_main->SetFrameFillStyle(0);
   data_obs_pass_prefit_projx0_main->SetFrameBorderMode(0);
   Double_t xAxis991[10] = {0, 0.04, 0.08, 0.12, 0.16, 0.2, 0.24, 0.28, 0.32, 1}; 
   
   TH1D *data_obs_pass_prefit_projx0__631 = new TH1D("data_obs_pass_prefit_projx0__631","",9, xAxis991);
   data_obs_pass_prefit_projx0__631->SetMinimum(0.001);
   data_obs_pass_prefit_projx0__631->SetMaximum(0);

   Int_t ci;      // for color index setting
   TColor *color; // for color definition with alpha
   ci = TColor::GetColor("#000000");
   data_obs_pass_prefit_projx0__631->SetLineColor(ci);
   data_obs_pass_prefit_projx0__631->SetLineStyle(0);

   ci = TColor::GetColor("#000000");
   data_obs_pass_prefit_projx0__631->SetMarkerColor(ci);
   data_obs_pass_prefit_projx0__631->SetMarkerStyle(8);
   data_obs_pass_prefit_projx0__631->GetXaxis()->SetTitle("G_{i}^{Strips}");
   data_obs_pass_prefit_projx0__631->GetXaxis()->SetLabelFont(42);
   data_obs_pass_prefit_projx0__631->GetXaxis()->SetLabelOffset(0.05);
   data_obs_pass_prefit_projx0__631->GetXaxis()->SetLabelSize(0.07);
   data_obs_pass_prefit_projx0__631->GetXaxis()->SetTitleSize(0.09);
   data_obs_pass_prefit_projx0__631->GetXaxis()->SetTitleOffset(1.15);
   data_obs_pass_prefit_projx0__631->GetXaxis()->SetTitleFont(42);
   data_obs_pass_prefit_projx0__631->GetYaxis()->SetTitle("Events / bin");
   data_obs_pass_prefit_projx0__631->GetYaxis()->SetNdivisions(508);
   data_obs_pass_prefit_projx0__631->GetYaxis()->SetLabelFont(42);
   data_obs_pass_prefit_projx0__631->GetYaxis()->SetLabelOffset(0.007);
   data_obs_pass_prefit_projx0__631->GetYaxis()->SetLabelSize(0.07);
   data_obs_pass_prefit_projx0__631->GetYaxis()->SetTitleSize(0.09);
   data_obs_pass_prefit_projx0__631->GetYaxis()->SetTitleOffset(0.8);
   data_obs_pass_prefit_projx0__631->GetYaxis()->SetTitleFont(42);
   data_obs_pass_prefit_projx0__631->GetZaxis()->SetLabelFont(42);
   data_obs_pass_prefit_projx0__631->GetZaxis()->SetLabelOffset(0.007);
   data_obs_pass_prefit_projx0__631->GetZaxis()->SetLabelSize(0.05);
   data_obs_pass_prefit_projx0__631->GetZaxis()->SetTitleSize(0.08);
   data_obs_pass_prefit_projx0__631->GetZaxis()->SetTitleFont(42);
   data_obs_pass_prefit_projx0__631->Draw("pe X0");
   
   THStack *prefit_projx0_pass_logy_stack = new THStack();
   prefit_projx0_pass_logy_stack->SetName("prefit_projx0_pass_logy_stack");
   prefit_projx0_pass_logy_stack->SetTitle("prefit_projx0_pass_logy_stack");
   prefit_projx0_pass_logy_stack->SetMinimum(0.001);
   Double_t xAxis992[10] = {0, 0.04, 0.08, 0.12, 0.16, 0.2, 0.24, 0.28, 0.32, 1}; 
   
   TH1F *prefit_projx0_pass_logy_stack_stack_181 = new TH1F("prefit_projx0_pass_logy_stack_stack_181","prefit_projx0_pass_logy_stack",9, xAxis992);
   prefit_projx0_pass_logy_stack_stack_181->SetMinimum(-0);
   prefit_projx0_pass_logy_stack_stack_181->SetMaximum(-nan);
   prefit_projx0_pass_logy_stack_stack_181->SetDirectory(0);
   prefit_projx0_pass_logy_stack_stack_181->SetStats(0);
   prefit_projx0_pass_logy_stack_stack_181->SetLineStyle(0);
   prefit_projx0_pass_logy_stack_stack_181->GetXaxis()->SetLabelFont(42);
   prefit_projx0_pass_logy_stack_stack_181->GetXaxis()->SetLabelOffset(0.007);
   prefit_projx0_pass_logy_stack_stack_181->GetXaxis()->SetLabelSize(0.05);
   prefit_projx0_pass_logy_stack_stack_181->GetXaxis()->SetTitleSize(0.08);
   prefit_projx0_pass_logy_stack_stack_181->GetXaxis()->SetTitleOffset(0.9);
   prefit_projx0_pass_logy_stack_stack_181->GetXaxis()->SetTitleFont(42);
   prefit_projx0_pass_logy_stack_stack_181->GetYaxis()->SetNdivisions(508);
   prefit_projx0_pass_logy_stack_stack_181->GetYaxis()->SetLabelFont(42);
   prefit_projx0_pass_logy_stack_stack_181->GetYaxis()->SetLabelOffset(0.007);
   prefit_projx0_pass_logy_stack_stack_181->GetYaxis()->SetLabelSize(0.05);
   prefit_projx0_pass_logy_stack_stack_181->GetYaxis()->SetTitleSize(0.08);
   prefit_projx0_pass_logy_stack_stack_181->GetYaxis()->SetTitleOffset(1.25);
   prefit_projx0_pass_logy_stack_stack_181->GetYaxis()->SetTitleFont(42);
   prefit_projx0_pass_logy_stack_stack_181->GetZaxis()->SetLabelFont(42);
   prefit_projx0_pass_logy_stack_stack_181->GetZaxis()->SetLabelOffset(0.007);
   prefit_projx0_pass_logy_stack_stack_181->GetZaxis()->SetLabelSize(0.05);
   prefit_projx0_pass_logy_stack_stack_181->GetZaxis()->SetTitleSize(0.08);
   prefit_projx0_pass_logy_stack_stack_181->GetZaxis()->SetTitleFont(42);
   prefit_projx0_pass_logy_stack->SetHistogram(prefit_projx0_pass_logy_stack_stack_181);
   
   Double_t xAxis993[10] = {0, 0.04, 0.08, 0.12, 0.16, 0.2, 0.24, 0.28, 0.32, 1}; 
   
   TH1D *Background_0x0_pass_prefit_projx0_stack_1 = new TH1D("Background_0x0_pass_prefit_projx0_stack_1","Background, pass, prefit, 50-50",9, xAxis993);
   Background_0x0_pass_prefit_projx0_stack_1->SetMinimum(0.001);

   ci = TColor::GetColor("#ffff00");
   Background_0x0_pass_prefit_projx0_stack_1->SetFillColor(ci);

   ci = 1551;
   color = new TColor(ci, 1, 1, 1, " ", 0);
   Background_0x0_pass_prefit_projx0_stack_1->SetLineColor(ci);
   Background_0x0_pass_prefit_projx0_stack_1->SetLineStyle(0);
   Background_0x0_pass_prefit_projx0_stack_1->GetXaxis()->SetTitle("G_{i}^{Strips}");
   Background_0x0_pass_prefit_projx0_stack_1->GetXaxis()->SetLabelFont(42);
   Background_0x0_pass_prefit_projx0_stack_1->GetXaxis()->SetLabelOffset(0.007);
   Background_0x0_pass_prefit_projx0_stack_1->GetXaxis()->SetLabelSize(0.05);
   Background_0x0_pass_prefit_projx0_stack_1->GetXaxis()->SetTitleSize(0.08);
   Background_0x0_pass_prefit_projx0_stack_1->GetXaxis()->SetTitleOffset(0.9);
   Background_0x0_pass_prefit_projx0_stack_1->GetXaxis()->SetTitleFont(42);
   Background_0x0_pass_prefit_projx0_stack_1->GetYaxis()->SetTitle("Events / bin");
   Background_0x0_pass_prefit_projx0_stack_1->GetYaxis()->SetLabelFont(42);
   Background_0x0_pass_prefit_projx0_stack_1->GetYaxis()->SetLabelOffset(0.007);
   Background_0x0_pass_prefit_projx0_stack_1->GetYaxis()->SetLabelSize(0.05);
   Background_0x0_pass_prefit_projx0_stack_1->GetYaxis()->SetTitleSize(0.08);
   Background_0x0_pass_prefit_projx0_stack_1->GetYaxis()->SetTitleOffset(1.25);
   Background_0x0_pass_prefit_projx0_stack_1->GetYaxis()->SetTitleFont(42);
   Background_0x0_pass_prefit_projx0_stack_1->GetZaxis()->SetLabelFont(42);
   Background_0x0_pass_prefit_projx0_stack_1->GetZaxis()->SetLabelOffset(0.007);
   Background_0x0_pass_prefit_projx0_stack_1->GetZaxis()->SetLabelSize(0.05);
   Background_0x0_pass_prefit_projx0_stack_1->GetZaxis()->SetTitleSize(0.08);
   Background_0x0_pass_prefit_projx0_stack_1->GetZaxis()->SetTitleFont(42);
   prefit_projx0_pass_logy_stack->Add(Background_0x0_pass_prefit_projx0_stack_1,"");
   prefit_projx0_pass_logy_stack->Draw("hist same");
   
   prefit_projx0_pass_logy_stack = new THStack();
   prefit_projx0_pass_logy_stack->SetName("prefit_projx0_pass_logy_stack");
   prefit_projx0_pass_logy_stack->SetTitle("prefit_projx0_pass_logy_stack");
   prefit_projx0_pass_logy_stack->SetMinimum(0.001);
   Double_t xAxis994[10] = {0, 0.04, 0.08, 0.12, 0.16, 0.2, 0.24, 0.28, 0.32, 1}; 
   
   TH1F *prefit_projx0_pass_logy_stack_stack_181_stack_182 = new TH1F("prefit_projx0_pass_logy_stack_stack_181_stack_182","prefit_projx0_pass_logy_stack",9, xAxis994);
   prefit_projx0_pass_logy_stack_stack_181_stack_182->SetMinimum(-0);
   prefit_projx0_pass_logy_stack_stack_181_stack_182->SetMaximum(-nan);
   prefit_projx0_pass_logy_stack_stack_181_stack_182->SetDirectory(0);
   prefit_projx0_pass_logy_stack_stack_181_stack_182->SetStats(0);
   prefit_projx0_pass_logy_stack_stack_181_stack_182->SetLineStyle(0);
   prefit_projx0_pass_logy_stack_stack_181_stack_182->GetXaxis()->SetLabelFont(42);
   prefit_projx0_pass_logy_stack_stack_181_stack_182->GetXaxis()->SetLabelOffset(0.007);
   prefit_projx0_pass_logy_stack_stack_181_stack_182->GetXaxis()->SetLabelSize(0.05);
   prefit_projx0_pass_logy_stack_stack_181_stack_182->GetXaxis()->SetTitleSize(0.08);
   prefit_projx0_pass_logy_stack_stack_181_stack_182->GetXaxis()->SetTitleOffset(0.9);
   prefit_projx0_pass_logy_stack_stack_181_stack_182->GetXaxis()->SetTitleFont(42);
   prefit_projx0_pass_logy_stack_stack_181_stack_182->GetYaxis()->SetNdivisions(508);
   prefit_projx0_pass_logy_stack_stack_181_stack_182->GetYaxis()->SetLabelFont(42);
   prefit_projx0_pass_logy_stack_stack_181_stack_182->GetYaxis()->SetLabelOffset(0.007);
   prefit_projx0_pass_logy_stack_stack_181_stack_182->GetYaxis()->SetLabelSize(0.05);
   prefit_projx0_pass_logy_stack_stack_181_stack_182->GetYaxis()->SetTitleSize(0.08);
   prefit_projx0_pass_logy_stack_stack_181_stack_182->GetYaxis()->SetTitleOffset(1.25);
   prefit_projx0_pass_logy_stack_stack_181_stack_182->GetYaxis()->SetTitleFont(42);
   prefit_projx0_pass_logy_stack_stack_181_stack_182->GetZaxis()->SetLabelFont(42);
   prefit_projx0_pass_logy_stack_stack_181_stack_182->GetZaxis()->SetLabelOffset(0.007);
   prefit_projx0_pass_logy_stack_stack_181_stack_182->GetZaxis()->SetLabelSize(0.05);
   prefit_projx0_pass_logy_stack_stack_181_stack_182->GetZaxis()->SetTitleSize(0.08);
   prefit_projx0_pass_logy_stack_stack_181_stack_182->GetZaxis()->SetTitleFont(42);
   prefit_projx0_pass_logy_stack->SetHistogram(prefit_projx0_pass_logy_stack_stack_181_stack_182);
   
   Double_t xAxis995[10] = {0, 0.04, 0.08, 0.12, 0.16, 0.2, 0.24, 0.28, 0.32, 1}; 
   
   TH1D *Background_0x0_pass_prefit_projx0_stack_1_stack_1 = new TH1D("Background_0x0_pass_prefit_projx0_stack_1_stack_1","Background, pass, prefit, 50-50",9, xAxis995);
   Background_0x0_pass_prefit_projx0_stack_1_stack_1->SetMinimum(0.001);

   ci = TColor::GetColor("#ffff00");
   Background_0x0_pass_prefit_projx0_stack_1_stack_1->SetFillColor(ci);

   ci = 1551;
   color = new TColor(ci, 1, 1, 1, " ", 0);
   Background_0x0_pass_prefit_projx0_stack_1_stack_1->SetLineColor(ci);
   Background_0x0_pass_prefit_projx0_stack_1_stack_1->SetLineStyle(0);
   Background_0x0_pass_prefit_projx0_stack_1_stack_1->GetXaxis()->SetTitle("G_{i}^{Strips}");
   Background_0x0_pass_prefit_projx0_stack_1_stack_1->GetXaxis()->SetLabelFont(42);
   Background_0x0_pass_prefit_projx0_stack_1_stack_1->GetXaxis()->SetLabelOffset(0.007);
   Background_0x0_pass_prefit_projx0_stack_1_stack_1->GetXaxis()->SetLabelSize(0.05);
   Background_0x0_pass_prefit_projx0_stack_1_stack_1->GetXaxis()->SetTitleSize(0.08);
   Background_0x0_pass_prefit_projx0_stack_1_stack_1->GetXaxis()->SetTitleOffset(0.9);
   Background_0x0_pass_prefit_projx0_stack_1_stack_1->GetXaxis()->SetTitleFont(42);
   Background_0x0_pass_prefit_projx0_stack_1_stack_1->GetYaxis()->SetTitle("Events / bin");
   Background_0x0_pass_prefit_projx0_stack_1_stack_1->GetYaxis()->SetLabelFont(42);
   Background_0x0_pass_prefit_projx0_stack_1_stack_1->GetYaxis()->SetLabelOffset(0.007);
   Background_0x0_pass_prefit_projx0_stack_1_stack_1->GetYaxis()->SetLabelSize(0.05);
   Background_0x0_pass_prefit_projx0_stack_1_stack_1->GetYaxis()->SetTitleSize(0.08);
   Background_0x0_pass_prefit_projx0_stack_1_stack_1->GetYaxis()->SetTitleOffset(1.25);
   Background_0x0_pass_prefit_projx0_stack_1_stack_1->GetYaxis()->SetTitleFont(42);
   Background_0x0_pass_prefit_projx0_stack_1_stack_1->GetZaxis()->SetLabelFont(42);
   Background_0x0_pass_prefit_projx0_stack_1_stack_1->GetZaxis()->SetLabelOffset(0.007);
   Background_0x0_pass_prefit_projx0_stack_1_stack_1->GetZaxis()->SetLabelSize(0.05);
   Background_0x0_pass_prefit_projx0_stack_1_stack_1->GetZaxis()->SetTitleSize(0.08);
   Background_0x0_pass_prefit_projx0_stack_1_stack_1->GetZaxis()->SetTitleFont(42);
   prefit_projx0_pass_logy_stack->Add(Background_0x0_pass_prefit_projx0_stack_1_stack_1,"");
   prefit_projx0_pass_logy_stack->Draw("hist same");
   Double_t xAxis996[10] = {0, 0.04, 0.08, 0.12, 0.16, 0.2, 0.24, 0.28, 0.32, 1}; 
   
   TH1D *Signal_ppStaumI557_pass_prefit_projx0__632 = new TH1D("Signal_ppStaumI557_pass_prefit_projx0__632","HSCP signal, pass, prefit, 50-50",9, xAxis996);
   Signal_ppStaumI557_pass_prefit_projx0__632->SetMinimum(0.001);
   Signal_ppStaumI557_pass_prefit_projx0__632->SetLineColor(2);
   Signal_ppStaumI557_pass_prefit_projx0__632->SetLineStyle(0);
   Signal_ppStaumI557_pass_prefit_projx0__632->GetXaxis()->SetTitle("G_{i}^{Strips}");
   Signal_ppStaumI557_pass_prefit_projx0__632->GetXaxis()->SetLabelFont(42);
   Signal_ppStaumI557_pass_prefit_projx0__632->GetXaxis()->SetLabelOffset(0.007);
   Signal_ppStaumI557_pass_prefit_projx0__632->GetXaxis()->SetLabelSize(0.05);
   Signal_ppStaumI557_pass_prefit_projx0__632->GetXaxis()->SetTitleSize(0.08);
   Signal_ppStaumI557_pass_prefit_projx0__632->GetXaxis()->SetTitleOffset(0.9);
   Signal_ppStaumI557_pass_prefit_projx0__632->GetXaxis()->SetTitleFont(42);
   Signal_ppStaumI557_pass_prefit_projx0__632->GetYaxis()->SetTitle("Events / bin");
   Signal_ppStaumI557_pass_prefit_projx0__632->GetYaxis()->SetLabelFont(42);
   Signal_ppStaumI557_pass_prefit_projx0__632->GetYaxis()->SetLabelOffset(0.007);
   Signal_ppStaumI557_pass_prefit_projx0__632->GetYaxis()->SetLabelSize(0.05);
   Signal_ppStaumI557_pass_prefit_projx0__632->GetYaxis()->SetTitleSize(0.08);
   Signal_ppStaumI557_pass_prefit_projx0__632->GetYaxis()->SetTitleOffset(1.25);
   Signal_ppStaumI557_pass_prefit_projx0__632->GetYaxis()->SetTitleFont(42);
   Signal_ppStaumI557_pass_prefit_projx0__632->GetZaxis()->SetLabelFont(42);
   Signal_ppStaumI557_pass_prefit_projx0__632->GetZaxis()->SetLabelOffset(0.007);
   Signal_ppStaumI557_pass_prefit_projx0__632->GetZaxis()->SetLabelSize(0.05);
   Signal_ppStaumI557_pass_prefit_projx0__632->GetZaxis()->SetTitleSize(0.08);
   Signal_ppStaumI557_pass_prefit_projx0__632->GetZaxis()->SetTitleFont(42);
   Signal_ppStaumI557_pass_prefit_projx0__632->Draw("hist same");
   Double_t xAxis997[10] = {0, 0.04, 0.08, 0.12, 0.16, 0.2, 0.24, 0.28, 0.32, 1}; 
   
   TH1D *TotalBkg_pass_prefit_projx0__633 = new TH1D("TotalBkg_pass_prefit_projx0__633","TotalBkg, pass, prefit, 50-50",9, xAxis997);
   TotalBkg_pass_prefit_projx0__633->SetMinimum(0.001);
   TotalBkg_pass_prefit_projx0__633->SetLineStyle(0);
   TotalBkg_pass_prefit_projx0__633->SetMarkerStyle(0);
   TotalBkg_pass_prefit_projx0__633->GetXaxis()->SetTitle("G_{i}^{Strips}");
   TotalBkg_pass_prefit_projx0__633->GetXaxis()->SetLabelFont(42);
   TotalBkg_pass_prefit_projx0__633->GetXaxis()->SetLabelOffset(0.007);
   TotalBkg_pass_prefit_projx0__633->GetXaxis()->SetLabelSize(0.05);
   TotalBkg_pass_prefit_projx0__633->GetXaxis()->SetTitleSize(0.08);
   TotalBkg_pass_prefit_projx0__633->GetXaxis()->SetTitleOffset(0.9);
   TotalBkg_pass_prefit_projx0__633->GetXaxis()->SetTitleFont(42);
   TotalBkg_pass_prefit_projx0__633->GetYaxis()->SetTitle("Events / bin");
   TotalBkg_pass_prefit_projx0__633->GetYaxis()->SetLabelFont(42);
   TotalBkg_pass_prefit_projx0__633->GetYaxis()->SetLabelOffset(0.007);
   TotalBkg_pass_prefit_projx0__633->GetYaxis()->SetLabelSize(0.05);
   TotalBkg_pass_prefit_projx0__633->GetYaxis()->SetTitleSize(0.08);
   TotalBkg_pass_prefit_projx0__633->GetYaxis()->SetTitleOffset(1.25);
   TotalBkg_pass_prefit_projx0__633->GetYaxis()->SetTitleFont(42);
   TotalBkg_pass_prefit_projx0__633->GetZaxis()->SetLabelFont(42);
   TotalBkg_pass_prefit_projx0__633->GetZaxis()->SetLabelOffset(0.007);
   TotalBkg_pass_prefit_projx0__633->GetZaxis()->SetLabelSize(0.05);
   TotalBkg_pass_prefit_projx0__633->GetZaxis()->SetTitleSize(0.08);
   TotalBkg_pass_prefit_projx0__633->GetZaxis()->SetTitleFont(42);
   TotalBkg_pass_prefit_projx0__633->Draw("hist same");
   Double_t xAxis998[10] = {0, 0.04, 0.08, 0.12, 0.16, 0.2, 0.24, 0.28, 0.32, 1}; 
   
   TH1D *TotalBkg_pass_prefit_projx0__634 = new TH1D("TotalBkg_pass_prefit_projx0__634","TotalBkg, pass, prefit, 50-50",9, xAxis998);
   TotalBkg_pass_prefit_projx0__634->SetMinimum(0.001);
   TotalBkg_pass_prefit_projx0__634->SetFillColor(1);
   TotalBkg_pass_prefit_projx0__634->SetFillStyle(3354);
   TotalBkg_pass_prefit_projx0__634->SetLineStyle(0);
   TotalBkg_pass_prefit_projx0__634->SetLineWidth(0);
   TotalBkg_pass_prefit_projx0__634->SetMarkerStyle(0);
   TotalBkg_pass_prefit_projx0__634->GetXaxis()->SetTitle("G_{i}^{Strips}");
   TotalBkg_pass_prefit_projx0__634->GetXaxis()->SetLabelFont(42);
   TotalBkg_pass_prefit_projx0__634->GetXaxis()->SetLabelOffset(0.007);
   TotalBkg_pass_prefit_projx0__634->GetXaxis()->SetLabelSize(0.05);
   TotalBkg_pass_prefit_projx0__634->GetXaxis()->SetTitleSize(0.08);
   TotalBkg_pass_prefit_projx0__634->GetXaxis()->SetTitleOffset(0.9);
   TotalBkg_pass_prefit_projx0__634->GetXaxis()->SetTitleFont(42);
   TotalBkg_pass_prefit_projx0__634->GetYaxis()->SetTitle("Events / bin");
   TotalBkg_pass_prefit_projx0__634->GetYaxis()->SetLabelFont(42);
   TotalBkg_pass_prefit_projx0__634->GetYaxis()->SetLabelOffset(0.007);
   TotalBkg_pass_prefit_projx0__634->GetYaxis()->SetLabelSize(0.05);
   TotalBkg_pass_prefit_projx0__634->GetYaxis()->SetTitleSize(0.08);
   TotalBkg_pass_prefit_projx0__634->GetYaxis()->SetTitleOffset(1.25);
   TotalBkg_pass_prefit_projx0__634->GetYaxis()->SetTitleFont(42);
   TotalBkg_pass_prefit_projx0__634->GetZaxis()->SetLabelFont(42);
   TotalBkg_pass_prefit_projx0__634->GetZaxis()->SetLabelOffset(0.007);
   TotalBkg_pass_prefit_projx0__634->GetZaxis()->SetLabelSize(0.05);
   TotalBkg_pass_prefit_projx0__634->GetZaxis()->SetTitleSize(0.08);
   TotalBkg_pass_prefit_projx0__634->GetZaxis()->SetTitleFont(42);
   TotalBkg_pass_prefit_projx0__634->Draw("e2 same");
   Double_t xAxis999[10] = {0, 0.04, 0.08, 0.12, 0.16, 0.2, 0.24, 0.28, 0.32, 1}; 
   
   TH1D *data_obs_pass_prefit_projx0__635 = new TH1D("data_obs_pass_prefit_projx0__635","",9, xAxis999);
   data_obs_pass_prefit_projx0__635->SetMinimum(0.001);
   data_obs_pass_prefit_projx0__635->SetMaximum(0);

   ci = TColor::GetColor("#000000");
   data_obs_pass_prefit_projx0__635->SetLineColor(ci);
   data_obs_pass_prefit_projx0__635->SetLineStyle(0);

   ci = TColor::GetColor("#000000");
   data_obs_pass_prefit_projx0__635->SetMarkerColor(ci);
   data_obs_pass_prefit_projx0__635->SetMarkerStyle(8);
   data_obs_pass_prefit_projx0__635->GetXaxis()->SetTitle("G_{i}^{Strips}");
   data_obs_pass_prefit_projx0__635->GetXaxis()->SetLabelFont(42);
   data_obs_pass_prefit_projx0__635->GetXaxis()->SetLabelOffset(0.05);
   data_obs_pass_prefit_projx0__635->GetXaxis()->SetLabelSize(0.07);
   data_obs_pass_prefit_projx0__635->GetXaxis()->SetTitleSize(0.09);
   data_obs_pass_prefit_projx0__635->GetXaxis()->SetTitleOffset(1.15);
   data_obs_pass_prefit_projx0__635->GetXaxis()->SetTitleFont(42);
   data_obs_pass_prefit_projx0__635->GetYaxis()->SetTitle("Events / bin");
   data_obs_pass_prefit_projx0__635->GetYaxis()->SetNdivisions(508);
   data_obs_pass_prefit_projx0__635->GetYaxis()->SetLabelFont(42);
   data_obs_pass_prefit_projx0__635->GetYaxis()->SetLabelOffset(0.007);
   data_obs_pass_prefit_projx0__635->GetYaxis()->SetLabelSize(0.07);
   data_obs_pass_prefit_projx0__635->GetYaxis()->SetTitleSize(0.09);
   data_obs_pass_prefit_projx0__635->GetYaxis()->SetTitleOffset(0.8);
   data_obs_pass_prefit_projx0__635->GetYaxis()->SetTitleFont(42);
   data_obs_pass_prefit_projx0__635->GetZaxis()->SetLabelFont(42);
   data_obs_pass_prefit_projx0__635->GetZaxis()->SetLabelOffset(0.007);
   data_obs_pass_prefit_projx0__635->GetZaxis()->SetLabelSize(0.05);
   data_obs_pass_prefit_projx0__635->GetZaxis()->SetTitleSize(0.08);
   data_obs_pass_prefit_projx0__635->GetZaxis()->SetTitleFont(42);
   data_obs_pass_prefit_projx0__635->Draw("pe X0 same");
   
   TLegend *leg = new TLegend(0.65,0.64,0.9,0.88,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(1001);
   TLegendEntry *entry=leg->AddEntry("data_obs_pass_prefit_projx0","Data","pe X0");

   ci = TColor::GetColor("#000000");
   entry->SetLineColor(ci);
   entry->SetLineWidth(1);

   ci = TColor::GetColor("#000000");
   entry->SetMarkerColor(ci);
   entry->SetMarkerStyle(8);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("TotalBkg_pass_prefit_projx0","Total bkg unc.","F");
   entry->SetFillColor(1);
   entry->SetFillStyle(3354);
   entry->SetLineColor(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("Signal_ppStau-557_pass_prefit_projx0","HSCP signal","L");
   entry->SetLineColor(2);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("Background_0x0_pass_prefit_projx0_stack_1_stack_1","Background","f");

   ci = TColor::GetColor("#ffff00");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = 1551;
   color = new TColor(ci, 1, 1, 1, " ", 0);
   entry->SetLineColor(ci);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   leg->Draw();
   Double_t xAxis1000[10] = {0, 0.04, 0.08, 0.12, 0.16, 0.2, 0.24, 0.28, 0.32, 1}; 
   
   TH1D *data_obs_pass_prefit_projx0_copy__636 = new TH1D("data_obs_pass_prefit_projx0_copy__636","",9, xAxis1000);
   data_obs_pass_prefit_projx0_copy__636->SetMinimum(0.001);
   data_obs_pass_prefit_projx0_copy__636->SetMaximum(0);
   data_obs_pass_prefit_projx0_copy__636->SetDirectory(0);

   ci = TColor::GetColor("#000000");
   data_obs_pass_prefit_projx0_copy__636->SetLineColor(ci);
   data_obs_pass_prefit_projx0_copy__636->SetLineStyle(0);

   ci = TColor::GetColor("#000000");
   data_obs_pass_prefit_projx0_copy__636->SetMarkerColor(ci);
   data_obs_pass_prefit_projx0_copy__636->SetMarkerStyle(8);
   data_obs_pass_prefit_projx0_copy__636->GetXaxis()->SetTitle("G_{i}^{Strips}");
   data_obs_pass_prefit_projx0_copy__636->GetXaxis()->SetLabelFont(42);
   data_obs_pass_prefit_projx0_copy__636->GetXaxis()->SetLabelOffset(0.05);
   data_obs_pass_prefit_projx0_copy__636->GetXaxis()->SetLabelSize(0.07);
   data_obs_pass_prefit_projx0_copy__636->GetXaxis()->SetTitleSize(0.09);
   data_obs_pass_prefit_projx0_copy__636->GetXaxis()->SetTitleOffset(1.15);
   data_obs_pass_prefit_projx0_copy__636->GetXaxis()->SetTitleFont(42);
   data_obs_pass_prefit_projx0_copy__636->GetYaxis()->SetTitle("Events / bin");
   data_obs_pass_prefit_projx0_copy__636->GetYaxis()->SetNdivisions(508);
   data_obs_pass_prefit_projx0_copy__636->GetYaxis()->SetLabelFont(42);
   data_obs_pass_prefit_projx0_copy__636->GetYaxis()->SetLabelOffset(0.007);
   data_obs_pass_prefit_projx0_copy__636->GetYaxis()->SetLabelSize(0.07);
   data_obs_pass_prefit_projx0_copy__636->GetYaxis()->SetTitleSize(0.09);
   data_obs_pass_prefit_projx0_copy__636->GetYaxis()->SetTitleOffset(0.8);
   data_obs_pass_prefit_projx0_copy__636->GetYaxis()->SetTitleFont(42);
   data_obs_pass_prefit_projx0_copy__636->GetZaxis()->SetLabelFont(42);
   data_obs_pass_prefit_projx0_copy__636->GetZaxis()->SetLabelOffset(0.007);
   data_obs_pass_prefit_projx0_copy__636->GetZaxis()->SetLabelSize(0.05);
   data_obs_pass_prefit_projx0_copy__636->GetZaxis()->SetTitleSize(0.08);
   data_obs_pass_prefit_projx0_copy__636->GetZaxis()->SetTitleFont(42);
   data_obs_pass_prefit_projx0_copy__636->Draw("sameaxis");
   TLatex *   tex = new TLatex(0.21,0.83,"55 < p_{T} < 200 GeV, F^{Pixels}_{i} > 0.9");
tex->SetNDC();
   tex->SetTextAlign(12);
   tex->SetTextFont(42);
   tex->SetTextSize(0.06);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.17,0.92,"CMS");
tex->SetNDC();
   tex->SetTextFont(61);
   tex->SetTextSize(0.0675);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.25,0.92,"Preliminary");
tex->SetNDC();
   tex->SetTextFont(52);
   tex->SetTextSize(0.0485);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.95,0.92,"101 fb^{-1} (13 TeV)");
tex->SetNDC();
   tex->SetTextAlign(31);
   tex->SetTextFont(42);
   tex->SetTextSize(0.07);
   tex->SetLineWidth(2);
   tex->Draw();
   data_obs_pass_prefit_projx0_main->Modified();
   plots_fit_s/base_figs/prefit_projx0_pass_logy->cd();
  
// ------------>Primitives in pad: data_obs_pass_prefit_projx0_sub
   TPad *data_obs_pass_prefit_projx0_sub = new TPad("data_obs_pass_prefit_projx0_sub", "data_obs_pass_prefit_projx0_sub",0,0,1,0.35);
   data_obs_pass_prefit_projx0_sub->Draw();
   data_obs_pass_prefit_projx0_sub->cd();
   data_obs_pass_prefit_projx0_sub->Range(-0.2179487,-6.023077,1.064103,2.9);
   data_obs_pass_prefit_projx0_sub->SetFillColor(0);
   data_obs_pass_prefit_projx0_sub->SetBorderMode(0);
   data_obs_pass_prefit_projx0_sub->SetBorderSize(2);
   data_obs_pass_prefit_projx0_sub->SetTickx(1);
   data_obs_pass_prefit_projx0_sub->SetTicky(1);
   data_obs_pass_prefit_projx0_sub->SetLeftMargin(0.17);
   data_obs_pass_prefit_projx0_sub->SetRightMargin(0.05);
   data_obs_pass_prefit_projx0_sub->SetTopMargin(0);
   data_obs_pass_prefit_projx0_sub->SetBottomMargin(0.35);
   data_obs_pass_prefit_projx0_sub->SetFrameFillStyle(0);
   data_obs_pass_prefit_projx0_sub->SetFrameBorderMode(0);
   data_obs_pass_prefit_projx0_sub->SetFrameFillStyle(0);
   data_obs_pass_prefit_projx0_sub->SetFrameBorderMode(0);
   Double_t xAxis1001[10] = {0, 0.04, 0.08, 0.12, 0.16, 0.2, 0.24, 0.28, 0.32, 1}; 
   
   TH1D *data_obs_pass_prefit_projx0_pull__637 = new TH1D("data_obs_pass_prefit_projx0_pull__637","",9, xAxis1001);
   data_obs_pass_prefit_projx0_pull__637->SetMinimum(-2.9);
   data_obs_pass_prefit_projx0_pull__637->SetMaximum(2.9);
   data_obs_pass_prefit_projx0_pull__637->SetEntries(18);
   data_obs_pass_prefit_projx0_pull__637->SetStats(0);

   ci = TColor::GetColor("#0000ff");
   data_obs_pass_prefit_projx0_pull__637->SetFillColor(ci);

   ci = TColor::GetColor("#000000");
   data_obs_pass_prefit_projx0_pull__637->SetLineColor(ci);
   data_obs_pass_prefit_projx0_pull__637->SetLineStyle(0);

   ci = TColor::GetColor("#000000");
   data_obs_pass_prefit_projx0_pull__637->SetMarkerColor(ci);
   data_obs_pass_prefit_projx0_pull__637->SetMarkerStyle(8);
   data_obs_pass_prefit_projx0_pull__637->GetXaxis()->SetTitle("G_{i}^{Strips}");
   data_obs_pass_prefit_projx0_pull__637->GetXaxis()->SetLabelFont(42);
   data_obs_pass_prefit_projx0_pull__637->GetXaxis()->SetLabelOffset(0.05);
   data_obs_pass_prefit_projx0_pull__637->GetXaxis()->SetLabelSize(0.13);
   data_obs_pass_prefit_projx0_pull__637->GetXaxis()->SetTitleSize(0.15);
   data_obs_pass_prefit_projx0_pull__637->GetXaxis()->SetTitleOffset(1.15);
   data_obs_pass_prefit_projx0_pull__637->GetXaxis()->SetTitleFont(42);
   data_obs_pass_prefit_projx0_pull__637->GetYaxis()->SetTitle("(Data-Bkg)/#sigma");
   data_obs_pass_prefit_projx0_pull__637->GetYaxis()->SetNdivisions(306);
   data_obs_pass_prefit_projx0_pull__637->GetYaxis()->SetLabelFont(42);
   data_obs_pass_prefit_projx0_pull__637->GetYaxis()->SetLabelOffset(0.007);
   data_obs_pass_prefit_projx0_pull__637->GetYaxis()->SetLabelSize(0.13);
   data_obs_pass_prefit_projx0_pull__637->GetYaxis()->SetTitleSize(0.12);
   data_obs_pass_prefit_projx0_pull__637->GetYaxis()->SetTitleOffset(0.4);
   data_obs_pass_prefit_projx0_pull__637->GetYaxis()->SetTitleFont(42);
   data_obs_pass_prefit_projx0_pull__637->GetZaxis()->SetLabelFont(42);
   data_obs_pass_prefit_projx0_pull__637->GetZaxis()->SetLabelOffset(0.007);
   data_obs_pass_prefit_projx0_pull__637->GetZaxis()->SetLabelSize(0.05);
   data_obs_pass_prefit_projx0_pull__637->GetZaxis()->SetTitleSize(0.08);
   data_obs_pass_prefit_projx0_pull__637->GetZaxis()->SetTitleFont(42);
   data_obs_pass_prefit_projx0_pull__637->Draw("hist");
   data_obs_pass_prefit_projx0_sub->Modified();
   plots_fit_s/base_figs/prefit_projx0_pass_logy->cd();
   plots_fit_s/base_figs/prefit_projx0_pass_logy->Modified();
   plots_fit_s/base_figs/prefit_projx0_pass_logy->cd();
   plots_fit_s/base_figs/prefit_projx0_pass_logy->SetSelected(plots_fit_s/base_figs/prefit_projx0_pass_logy);
}
