void prefit_projy1_pass()
{
//=========Macro generated from canvas: plots_fit_s/base_figs/prefit_projy1_pass/plots_fit_s/base_figs/prefit_projy1_pass
//=========  (Fri Jan 12 21:00:35 2024) by ROOT version 6.14/09
   TCanvas *plots_fit_s/base_figs/prefit_projy1_pass = new TCanvas("plots_fit_s/base_figs/prefit_projy1_pass", "plots_fit_s/base_figs/prefit_projy1_pass",0,0,800,700);
   gStyle->SetOptFit(1);
   gStyle->SetOptStat(0);
   plots_fit_s/base_figs/prefit_projy1_pass->SetHighLightColor(2);
   plots_fit_s/base_figs/prefit_projy1_pass->Range(0,0,1,1);
   plots_fit_s/base_figs/prefit_projy1_pass->SetFillColor(0);
   plots_fit_s/base_figs/prefit_projy1_pass->SetBorderMode(0);
   plots_fit_s/base_figs/prefit_projy1_pass->SetBorderSize(2);
   plots_fit_s/base_figs/prefit_projy1_pass->SetTickx(1);
   plots_fit_s/base_figs/prefit_projy1_pass->SetTicky(1);
   plots_fit_s/base_figs/prefit_projy1_pass->SetLeftMargin(0.16);
   plots_fit_s/base_figs/prefit_projy1_pass->SetRightMargin(0);
   plots_fit_s/base_figs/prefit_projy1_pass->SetTopMargin(0);
   plots_fit_s/base_figs/prefit_projy1_pass->SetBottomMargin(0);
   plots_fit_s/base_figs/prefit_projy1_pass->SetFrameFillStyle(0);
   plots_fit_s/base_figs/prefit_projy1_pass->SetFrameBorderMode(0);
  
// ------------>Primitives in pad: data_obs_pass_prefit_projy1_main
   TPad *data_obs_pass_prefit_projy1_main = new TPad("data_obs_pass_prefit_projy1_main", "data_obs_pass_prefit_projy1_main",0,0.35,1,1);
   data_obs_pass_prefit_projy1_main->Draw();
   data_obs_pass_prefit_projy1_main->cd();
   data_obs_pass_prefit_projy1_main->Range(17.30769,-62.16279,209.6154,1491.907);
   data_obs_pass_prefit_projy1_main->SetFillColor(0);
   data_obs_pass_prefit_projy1_main->SetBorderMode(0);
   data_obs_pass_prefit_projy1_main->SetBorderSize(2);
   data_obs_pass_prefit_projy1_main->SetTickx(1);
   data_obs_pass_prefit_projy1_main->SetTicky(1);
   data_obs_pass_prefit_projy1_main->SetLeftMargin(0.17);
   data_obs_pass_prefit_projy1_main->SetRightMargin(0.05);
   data_obs_pass_prefit_projy1_main->SetBottomMargin(0.04);
   data_obs_pass_prefit_projy1_main->SetFrameFillStyle(0);
   data_obs_pass_prefit_projy1_main->SetFrameBorderMode(0);
   data_obs_pass_prefit_projy1_main->SetFrameFillStyle(0);
   data_obs_pass_prefit_projy1_main->SetFrameBorderMode(0);
   Double_t xAxis969[2] = {50, 200}; 
   
   TH1D *data_obs_pass_prefit_projy1__617 = new TH1D("data_obs_pass_prefit_projy1__617","",1, xAxis969);
   data_obs_pass_prefit_projy1__617->SetBinContent(1,990);
   data_obs_pass_prefit_projy1__617->SetBinError(1,31.46427);
   data_obs_pass_prefit_projy1__617->SetMinimum(0);
   data_obs_pass_prefit_projy1__617->SetMaximum(1336.5);
   data_obs_pass_prefit_projy1__617->SetEntries(990);

   Int_t ci;      // for color index setting
   TColor *color; // for color definition with alpha
   ci = TColor::GetColor("#000000");
   data_obs_pass_prefit_projy1__617->SetLineColor(ci);
   data_obs_pass_prefit_projy1__617->SetLineStyle(0);

   ci = TColor::GetColor("#000000");
   data_obs_pass_prefit_projy1__617->SetMarkerColor(ci);
   data_obs_pass_prefit_projy1__617->SetMarkerStyle(8);
   data_obs_pass_prefit_projy1__617->GetXaxis()->SetTitle("p_{T}");
   data_obs_pass_prefit_projy1__617->GetXaxis()->SetLabelFont(42);
   data_obs_pass_prefit_projy1__617->GetXaxis()->SetLabelOffset(0.05);
   data_obs_pass_prefit_projy1__617->GetXaxis()->SetLabelSize(0.07);
   data_obs_pass_prefit_projy1__617->GetXaxis()->SetTitleSize(0.09);
   data_obs_pass_prefit_projy1__617->GetXaxis()->SetTitleOffset(1.15);
   data_obs_pass_prefit_projy1__617->GetXaxis()->SetTitleFont(42);
   data_obs_pass_prefit_projy1__617->GetYaxis()->SetTitle("Events / bin");
   data_obs_pass_prefit_projy1__617->GetYaxis()->SetNdivisions(508);
   data_obs_pass_prefit_projy1__617->GetYaxis()->SetLabelFont(42);
   data_obs_pass_prefit_projy1__617->GetYaxis()->SetLabelOffset(0.007);
   data_obs_pass_prefit_projy1__617->GetYaxis()->SetLabelSize(0.07);
   data_obs_pass_prefit_projy1__617->GetYaxis()->SetTitleSize(0.09);
   data_obs_pass_prefit_projy1__617->GetYaxis()->SetTitleOffset(0.8);
   data_obs_pass_prefit_projy1__617->GetYaxis()->SetTitleFont(42);
   data_obs_pass_prefit_projy1__617->GetZaxis()->SetLabelFont(42);
   data_obs_pass_prefit_projy1__617->GetZaxis()->SetLabelOffset(0.007);
   data_obs_pass_prefit_projy1__617->GetZaxis()->SetLabelSize(0.05);
   data_obs_pass_prefit_projy1__617->GetZaxis()->SetTitleSize(0.08);
   data_obs_pass_prefit_projy1__617->GetZaxis()->SetTitleFont(42);
   data_obs_pass_prefit_projy1__617->Draw("pe X0");
   
   THStack *prefit_projy1_pass_stack = new THStack();
   prefit_projy1_pass_stack->SetName("prefit_projy1_pass_stack");
   prefit_projy1_pass_stack->SetTitle("prefit_projy1_pass_stack");
   Double_t xAxis970[2] = {50, 200}; 
   
   TH1F *prefit_projy1_pass_stack_stack_177 = new TH1F("prefit_projy1_pass_stack_stack_177","prefit_projy1_pass_stack",1, xAxis970);
   prefit_projy1_pass_stack_stack_177->SetMinimum(0);
   prefit_projy1_pass_stack_stack_177->SetMaximum(110.3708);
   prefit_projy1_pass_stack_stack_177->SetDirectory(0);
   prefit_projy1_pass_stack_stack_177->SetStats(0);
   prefit_projy1_pass_stack_stack_177->SetLineStyle(0);
   prefit_projy1_pass_stack_stack_177->GetXaxis()->SetLabelFont(42);
   prefit_projy1_pass_stack_stack_177->GetXaxis()->SetLabelOffset(0.007);
   prefit_projy1_pass_stack_stack_177->GetXaxis()->SetLabelSize(0.05);
   prefit_projy1_pass_stack_stack_177->GetXaxis()->SetTitleSize(0.08);
   prefit_projy1_pass_stack_stack_177->GetXaxis()->SetTitleOffset(0.9);
   prefit_projy1_pass_stack_stack_177->GetXaxis()->SetTitleFont(42);
   prefit_projy1_pass_stack_stack_177->GetYaxis()->SetNdivisions(508);
   prefit_projy1_pass_stack_stack_177->GetYaxis()->SetLabelFont(42);
   prefit_projy1_pass_stack_stack_177->GetYaxis()->SetLabelOffset(0.007);
   prefit_projy1_pass_stack_stack_177->GetYaxis()->SetLabelSize(0.05);
   prefit_projy1_pass_stack_stack_177->GetYaxis()->SetTitleSize(0.08);
   prefit_projy1_pass_stack_stack_177->GetYaxis()->SetTitleOffset(1.25);
   prefit_projy1_pass_stack_stack_177->GetYaxis()->SetTitleFont(42);
   prefit_projy1_pass_stack_stack_177->GetZaxis()->SetLabelFont(42);
   prefit_projy1_pass_stack_stack_177->GetZaxis()->SetLabelOffset(0.007);
   prefit_projy1_pass_stack_stack_177->GetZaxis()->SetLabelSize(0.05);
   prefit_projy1_pass_stack_stack_177->GetZaxis()->SetTitleSize(0.08);
   prefit_projy1_pass_stack_stack_177->GetZaxis()->SetTitleFont(42);
   prefit_projy1_pass_stack->SetHistogram(prefit_projy1_pass_stack_stack_177);
   
   Double_t xAxis971[2] = {50, 200}; 
   
   TH1D *Background_0x0_pass_prefit_projy1_stack_1 = new TH1D("Background_0x0_pass_prefit_projy1_stack_1","Background, pass, prefit, 0.24-1.0",1, xAxis971);
   Background_0x0_pass_prefit_projy1_stack_1->SetBinContent(1,62.44);
   Background_0x0_pass_prefit_projy1_stack_1->SetBinError(1,42.67506);
   Background_0x0_pass_prefit_projy1_stack_1->SetMinimum(0);
   Background_0x0_pass_prefit_projy1_stack_1->SetEntries(2.140807);

   ci = TColor::GetColor("#ffff00");
   Background_0x0_pass_prefit_projy1_stack_1->SetFillColor(ci);

   ci = 1555;
   color = new TColor(ci, 1, 1, 1, " ", 0);
   Background_0x0_pass_prefit_projy1_stack_1->SetLineColor(ci);
   Background_0x0_pass_prefit_projy1_stack_1->SetLineStyle(0);
   Background_0x0_pass_prefit_projy1_stack_1->GetXaxis()->SetTitle("p_{T}");
   Background_0x0_pass_prefit_projy1_stack_1->GetXaxis()->SetLabelFont(42);
   Background_0x0_pass_prefit_projy1_stack_1->GetXaxis()->SetLabelOffset(0.007);
   Background_0x0_pass_prefit_projy1_stack_1->GetXaxis()->SetLabelSize(0.05);
   Background_0x0_pass_prefit_projy1_stack_1->GetXaxis()->SetTitleSize(0.08);
   Background_0x0_pass_prefit_projy1_stack_1->GetXaxis()->SetTitleOffset(1.25);
   Background_0x0_pass_prefit_projy1_stack_1->GetXaxis()->SetTitleFont(42);
   Background_0x0_pass_prefit_projy1_stack_1->GetYaxis()->SetTitle("Events / bin");
   Background_0x0_pass_prefit_projy1_stack_1->GetYaxis()->SetLabelFont(42);
   Background_0x0_pass_prefit_projy1_stack_1->GetYaxis()->SetLabelOffset(0.007);
   Background_0x0_pass_prefit_projy1_stack_1->GetYaxis()->SetLabelSize(0.05);
   Background_0x0_pass_prefit_projy1_stack_1->GetYaxis()->SetTitleSize(0.08);
   Background_0x0_pass_prefit_projy1_stack_1->GetYaxis()->SetTitleOffset(1.25);
   Background_0x0_pass_prefit_projy1_stack_1->GetYaxis()->SetTitleFont(42);
   Background_0x0_pass_prefit_projy1_stack_1->GetZaxis()->SetLabelFont(42);
   Background_0x0_pass_prefit_projy1_stack_1->GetZaxis()->SetLabelOffset(0.007);
   Background_0x0_pass_prefit_projy1_stack_1->GetZaxis()->SetLabelSize(0.05);
   Background_0x0_pass_prefit_projy1_stack_1->GetZaxis()->SetTitleSize(0.08);
   Background_0x0_pass_prefit_projy1_stack_1->GetZaxis()->SetTitleFont(42);
   prefit_projy1_pass_stack->Add(Background_0x0_pass_prefit_projy1_stack_1,"");
   prefit_projy1_pass_stack->Draw("hist same");
   
   prefit_projy1_pass_stack = new THStack();
   prefit_projy1_pass_stack->SetName("prefit_projy1_pass_stack");
   prefit_projy1_pass_stack->SetTitle("prefit_projy1_pass_stack");
   Double_t xAxis972[2] = {50, 200}; 
   
   TH1F *prefit_projy1_pass_stack_stack_177_stack_178 = new TH1F("prefit_projy1_pass_stack_stack_177_stack_178","prefit_projy1_pass_stack",1, xAxis972);
   prefit_projy1_pass_stack_stack_177_stack_178->SetMinimum(0);
   prefit_projy1_pass_stack_stack_177_stack_178->SetMaximum(110.3708);
   prefit_projy1_pass_stack_stack_177_stack_178->SetDirectory(0);
   prefit_projy1_pass_stack_stack_177_stack_178->SetStats(0);
   prefit_projy1_pass_stack_stack_177_stack_178->SetLineStyle(0);
   prefit_projy1_pass_stack_stack_177_stack_178->GetXaxis()->SetLabelFont(42);
   prefit_projy1_pass_stack_stack_177_stack_178->GetXaxis()->SetLabelOffset(0.007);
   prefit_projy1_pass_stack_stack_177_stack_178->GetXaxis()->SetLabelSize(0.05);
   prefit_projy1_pass_stack_stack_177_stack_178->GetXaxis()->SetTitleSize(0.08);
   prefit_projy1_pass_stack_stack_177_stack_178->GetXaxis()->SetTitleOffset(0.9);
   prefit_projy1_pass_stack_stack_177_stack_178->GetXaxis()->SetTitleFont(42);
   prefit_projy1_pass_stack_stack_177_stack_178->GetYaxis()->SetNdivisions(508);
   prefit_projy1_pass_stack_stack_177_stack_178->GetYaxis()->SetLabelFont(42);
   prefit_projy1_pass_stack_stack_177_stack_178->GetYaxis()->SetLabelOffset(0.007);
   prefit_projy1_pass_stack_stack_177_stack_178->GetYaxis()->SetLabelSize(0.05);
   prefit_projy1_pass_stack_stack_177_stack_178->GetYaxis()->SetTitleSize(0.08);
   prefit_projy1_pass_stack_stack_177_stack_178->GetYaxis()->SetTitleOffset(1.25);
   prefit_projy1_pass_stack_stack_177_stack_178->GetYaxis()->SetTitleFont(42);
   prefit_projy1_pass_stack_stack_177_stack_178->GetZaxis()->SetLabelFont(42);
   prefit_projy1_pass_stack_stack_177_stack_178->GetZaxis()->SetLabelOffset(0.007);
   prefit_projy1_pass_stack_stack_177_stack_178->GetZaxis()->SetLabelSize(0.05);
   prefit_projy1_pass_stack_stack_177_stack_178->GetZaxis()->SetTitleSize(0.08);
   prefit_projy1_pass_stack_stack_177_stack_178->GetZaxis()->SetTitleFont(42);
   prefit_projy1_pass_stack->SetHistogram(prefit_projy1_pass_stack_stack_177_stack_178);
   
   Double_t xAxis973[2] = {50, 200}; 
   
   TH1D *Background_0x0_pass_prefit_projy1_stack_1_stack_1 = new TH1D("Background_0x0_pass_prefit_projy1_stack_1_stack_1","Background, pass, prefit, 0.24-1.0",1, xAxis973);
   Background_0x0_pass_prefit_projy1_stack_1_stack_1->SetBinContent(1,62.44);
   Background_0x0_pass_prefit_projy1_stack_1_stack_1->SetBinError(1,42.67506);
   Background_0x0_pass_prefit_projy1_stack_1_stack_1->SetMinimum(0);
   Background_0x0_pass_prefit_projy1_stack_1_stack_1->SetEntries(2.140807);

   ci = TColor::GetColor("#ffff00");
   Background_0x0_pass_prefit_projy1_stack_1_stack_1->SetFillColor(ci);

   ci = 1555;
   color = new TColor(ci, 1, 1, 1, " ", 0);
   Background_0x0_pass_prefit_projy1_stack_1_stack_1->SetLineColor(ci);
   Background_0x0_pass_prefit_projy1_stack_1_stack_1->SetLineStyle(0);
   Background_0x0_pass_prefit_projy1_stack_1_stack_1->GetXaxis()->SetTitle("p_{T}");
   Background_0x0_pass_prefit_projy1_stack_1_stack_1->GetXaxis()->SetLabelFont(42);
   Background_0x0_pass_prefit_projy1_stack_1_stack_1->GetXaxis()->SetLabelOffset(0.007);
   Background_0x0_pass_prefit_projy1_stack_1_stack_1->GetXaxis()->SetLabelSize(0.05);
   Background_0x0_pass_prefit_projy1_stack_1_stack_1->GetXaxis()->SetTitleSize(0.08);
   Background_0x0_pass_prefit_projy1_stack_1_stack_1->GetXaxis()->SetTitleOffset(1.25);
   Background_0x0_pass_prefit_projy1_stack_1_stack_1->GetXaxis()->SetTitleFont(42);
   Background_0x0_pass_prefit_projy1_stack_1_stack_1->GetYaxis()->SetTitle("Events / bin");
   Background_0x0_pass_prefit_projy1_stack_1_stack_1->GetYaxis()->SetLabelFont(42);
   Background_0x0_pass_prefit_projy1_stack_1_stack_1->GetYaxis()->SetLabelOffset(0.007);
   Background_0x0_pass_prefit_projy1_stack_1_stack_1->GetYaxis()->SetLabelSize(0.05);
   Background_0x0_pass_prefit_projy1_stack_1_stack_1->GetYaxis()->SetTitleSize(0.08);
   Background_0x0_pass_prefit_projy1_stack_1_stack_1->GetYaxis()->SetTitleOffset(1.25);
   Background_0x0_pass_prefit_projy1_stack_1_stack_1->GetYaxis()->SetTitleFont(42);
   Background_0x0_pass_prefit_projy1_stack_1_stack_1->GetZaxis()->SetLabelFont(42);
   Background_0x0_pass_prefit_projy1_stack_1_stack_1->GetZaxis()->SetLabelOffset(0.007);
   Background_0x0_pass_prefit_projy1_stack_1_stack_1->GetZaxis()->SetLabelSize(0.05);
   Background_0x0_pass_prefit_projy1_stack_1_stack_1->GetZaxis()->SetTitleSize(0.08);
   Background_0x0_pass_prefit_projy1_stack_1_stack_1->GetZaxis()->SetTitleFont(42);
   prefit_projy1_pass_stack->Add(Background_0x0_pass_prefit_projy1_stack_1_stack_1,"");
   prefit_projy1_pass_stack->Draw("hist same");
   Double_t xAxis974[2] = {50, 200}; 
   
   TH1D *Signal_ppStaumI557_pass_prefit_projy1__618 = new TH1D("Signal_ppStaumI557_pass_prefit_projy1__618","HSCP signal, pass, prefit, 0.24-1.0",1, xAxis974);
   Signal_ppStaumI557_pass_prefit_projy1__618->SetBinContent(1,0.232382);
   Signal_ppStaumI557_pass_prefit_projy1__618->SetBinError(1,0.03381868);
   Signal_ppStaumI557_pass_prefit_projy1__618->SetMinimum(0);
   Signal_ppStaumI557_pass_prefit_projy1__618->SetEntries(47.21626);
   Signal_ppStaumI557_pass_prefit_projy1__618->SetLineColor(2);
   Signal_ppStaumI557_pass_prefit_projy1__618->SetLineStyle(0);
   Signal_ppStaumI557_pass_prefit_projy1__618->GetXaxis()->SetTitle("p_{T}");
   Signal_ppStaumI557_pass_prefit_projy1__618->GetXaxis()->SetLabelFont(42);
   Signal_ppStaumI557_pass_prefit_projy1__618->GetXaxis()->SetLabelOffset(0.007);
   Signal_ppStaumI557_pass_prefit_projy1__618->GetXaxis()->SetLabelSize(0.05);
   Signal_ppStaumI557_pass_prefit_projy1__618->GetXaxis()->SetTitleSize(0.08);
   Signal_ppStaumI557_pass_prefit_projy1__618->GetXaxis()->SetTitleOffset(1.25);
   Signal_ppStaumI557_pass_prefit_projy1__618->GetXaxis()->SetTitleFont(42);
   Signal_ppStaumI557_pass_prefit_projy1__618->GetYaxis()->SetTitle("Events / bin");
   Signal_ppStaumI557_pass_prefit_projy1__618->GetYaxis()->SetLabelFont(42);
   Signal_ppStaumI557_pass_prefit_projy1__618->GetYaxis()->SetLabelOffset(0.007);
   Signal_ppStaumI557_pass_prefit_projy1__618->GetYaxis()->SetLabelSize(0.05);
   Signal_ppStaumI557_pass_prefit_projy1__618->GetYaxis()->SetTitleSize(0.08);
   Signal_ppStaumI557_pass_prefit_projy1__618->GetYaxis()->SetTitleOffset(1.25);
   Signal_ppStaumI557_pass_prefit_projy1__618->GetYaxis()->SetTitleFont(42);
   Signal_ppStaumI557_pass_prefit_projy1__618->GetZaxis()->SetLabelFont(42);
   Signal_ppStaumI557_pass_prefit_projy1__618->GetZaxis()->SetLabelOffset(0.007);
   Signal_ppStaumI557_pass_prefit_projy1__618->GetZaxis()->SetLabelSize(0.05);
   Signal_ppStaumI557_pass_prefit_projy1__618->GetZaxis()->SetTitleSize(0.08);
   Signal_ppStaumI557_pass_prefit_projy1__618->GetZaxis()->SetTitleFont(42);
   Signal_ppStaumI557_pass_prefit_projy1__618->Draw("hist same");
   Double_t xAxis975[2] = {50, 200}; 
   
   TH1D *TotalBkg_pass_prefit_projy1__619 = new TH1D("TotalBkg_pass_prefit_projy1__619","TotalBkg, pass, prefit, 0.24-1.0",1, xAxis975);
   TotalBkg_pass_prefit_projy1__619->SetBinContent(1,62.44);
   TotalBkg_pass_prefit_projy1__619->SetBinError(1,42.67506);
   TotalBkg_pass_prefit_projy1__619->SetMinimum(0);
   TotalBkg_pass_prefit_projy1__619->SetEntries(2.140807);
   TotalBkg_pass_prefit_projy1__619->SetLineStyle(0);
   TotalBkg_pass_prefit_projy1__619->SetMarkerStyle(0);
   TotalBkg_pass_prefit_projy1__619->GetXaxis()->SetTitle("p_{T}");
   TotalBkg_pass_prefit_projy1__619->GetXaxis()->SetLabelFont(42);
   TotalBkg_pass_prefit_projy1__619->GetXaxis()->SetLabelOffset(0.007);
   TotalBkg_pass_prefit_projy1__619->GetXaxis()->SetLabelSize(0.05);
   TotalBkg_pass_prefit_projy1__619->GetXaxis()->SetTitleSize(0.08);
   TotalBkg_pass_prefit_projy1__619->GetXaxis()->SetTitleOffset(1.25);
   TotalBkg_pass_prefit_projy1__619->GetXaxis()->SetTitleFont(42);
   TotalBkg_pass_prefit_projy1__619->GetYaxis()->SetTitle("Events / bin");
   TotalBkg_pass_prefit_projy1__619->GetYaxis()->SetLabelFont(42);
   TotalBkg_pass_prefit_projy1__619->GetYaxis()->SetLabelOffset(0.007);
   TotalBkg_pass_prefit_projy1__619->GetYaxis()->SetLabelSize(0.05);
   TotalBkg_pass_prefit_projy1__619->GetYaxis()->SetTitleSize(0.08);
   TotalBkg_pass_prefit_projy1__619->GetYaxis()->SetTitleOffset(1.25);
   TotalBkg_pass_prefit_projy1__619->GetYaxis()->SetTitleFont(42);
   TotalBkg_pass_prefit_projy1__619->GetZaxis()->SetLabelFont(42);
   TotalBkg_pass_prefit_projy1__619->GetZaxis()->SetLabelOffset(0.007);
   TotalBkg_pass_prefit_projy1__619->GetZaxis()->SetLabelSize(0.05);
   TotalBkg_pass_prefit_projy1__619->GetZaxis()->SetTitleSize(0.08);
   TotalBkg_pass_prefit_projy1__619->GetZaxis()->SetTitleFont(42);
   TotalBkg_pass_prefit_projy1__619->Draw("hist same");
   Double_t xAxis976[2] = {50, 200}; 
   
   TH1D *TotalBkg_pass_prefit_projy1__620 = new TH1D("TotalBkg_pass_prefit_projy1__620","TotalBkg, pass, prefit, 0.24-1.0",1, xAxis976);
   TotalBkg_pass_prefit_projy1__620->SetBinContent(1,62.44);
   TotalBkg_pass_prefit_projy1__620->SetBinError(1,42.67506);
   TotalBkg_pass_prefit_projy1__620->SetMinimum(0);
   TotalBkg_pass_prefit_projy1__620->SetEntries(2.140807);
   TotalBkg_pass_prefit_projy1__620->SetFillColor(1);
   TotalBkg_pass_prefit_projy1__620->SetFillStyle(3354);
   TotalBkg_pass_prefit_projy1__620->SetLineStyle(0);
   TotalBkg_pass_prefit_projy1__620->SetLineWidth(0);
   TotalBkg_pass_prefit_projy1__620->SetMarkerStyle(0);
   TotalBkg_pass_prefit_projy1__620->GetXaxis()->SetTitle("p_{T}");
   TotalBkg_pass_prefit_projy1__620->GetXaxis()->SetLabelFont(42);
   TotalBkg_pass_prefit_projy1__620->GetXaxis()->SetLabelOffset(0.007);
   TotalBkg_pass_prefit_projy1__620->GetXaxis()->SetLabelSize(0.05);
   TotalBkg_pass_prefit_projy1__620->GetXaxis()->SetTitleSize(0.08);
   TotalBkg_pass_prefit_projy1__620->GetXaxis()->SetTitleOffset(1.25);
   TotalBkg_pass_prefit_projy1__620->GetXaxis()->SetTitleFont(42);
   TotalBkg_pass_prefit_projy1__620->GetYaxis()->SetTitle("Events / bin");
   TotalBkg_pass_prefit_projy1__620->GetYaxis()->SetLabelFont(42);
   TotalBkg_pass_prefit_projy1__620->GetYaxis()->SetLabelOffset(0.007);
   TotalBkg_pass_prefit_projy1__620->GetYaxis()->SetLabelSize(0.05);
   TotalBkg_pass_prefit_projy1__620->GetYaxis()->SetTitleSize(0.08);
   TotalBkg_pass_prefit_projy1__620->GetYaxis()->SetTitleOffset(1.25);
   TotalBkg_pass_prefit_projy1__620->GetYaxis()->SetTitleFont(42);
   TotalBkg_pass_prefit_projy1__620->GetZaxis()->SetLabelFont(42);
   TotalBkg_pass_prefit_projy1__620->GetZaxis()->SetLabelOffset(0.007);
   TotalBkg_pass_prefit_projy1__620->GetZaxis()->SetLabelSize(0.05);
   TotalBkg_pass_prefit_projy1__620->GetZaxis()->SetTitleSize(0.08);
   TotalBkg_pass_prefit_projy1__620->GetZaxis()->SetTitleFont(42);
   TotalBkg_pass_prefit_projy1__620->Draw("e2 same");
   Double_t xAxis977[2] = {50, 200}; 
   
   TH1D *data_obs_pass_prefit_projy1__621 = new TH1D("data_obs_pass_prefit_projy1__621","",1, xAxis977);
   data_obs_pass_prefit_projy1__621->SetBinContent(1,990);
   data_obs_pass_prefit_projy1__621->SetBinError(1,31.46427);
   data_obs_pass_prefit_projy1__621->SetMinimum(0);
   data_obs_pass_prefit_projy1__621->SetMaximum(1336.5);
   data_obs_pass_prefit_projy1__621->SetEntries(990);

   ci = TColor::GetColor("#000000");
   data_obs_pass_prefit_projy1__621->SetLineColor(ci);
   data_obs_pass_prefit_projy1__621->SetLineStyle(0);

   ci = TColor::GetColor("#000000");
   data_obs_pass_prefit_projy1__621->SetMarkerColor(ci);
   data_obs_pass_prefit_projy1__621->SetMarkerStyle(8);
   data_obs_pass_prefit_projy1__621->GetXaxis()->SetTitle("p_{T}");
   data_obs_pass_prefit_projy1__621->GetXaxis()->SetLabelFont(42);
   data_obs_pass_prefit_projy1__621->GetXaxis()->SetLabelOffset(0.05);
   data_obs_pass_prefit_projy1__621->GetXaxis()->SetLabelSize(0.07);
   data_obs_pass_prefit_projy1__621->GetXaxis()->SetTitleSize(0.09);
   data_obs_pass_prefit_projy1__621->GetXaxis()->SetTitleOffset(1.15);
   data_obs_pass_prefit_projy1__621->GetXaxis()->SetTitleFont(42);
   data_obs_pass_prefit_projy1__621->GetYaxis()->SetTitle("Events / bin");
   data_obs_pass_prefit_projy1__621->GetYaxis()->SetNdivisions(508);
   data_obs_pass_prefit_projy1__621->GetYaxis()->SetLabelFont(42);
   data_obs_pass_prefit_projy1__621->GetYaxis()->SetLabelOffset(0.007);
   data_obs_pass_prefit_projy1__621->GetYaxis()->SetLabelSize(0.07);
   data_obs_pass_prefit_projy1__621->GetYaxis()->SetTitleSize(0.09);
   data_obs_pass_prefit_projy1__621->GetYaxis()->SetTitleOffset(0.8);
   data_obs_pass_prefit_projy1__621->GetYaxis()->SetTitleFont(42);
   data_obs_pass_prefit_projy1__621->GetZaxis()->SetLabelFont(42);
   data_obs_pass_prefit_projy1__621->GetZaxis()->SetLabelOffset(0.007);
   data_obs_pass_prefit_projy1__621->GetZaxis()->SetLabelSize(0.05);
   data_obs_pass_prefit_projy1__621->GetZaxis()->SetTitleSize(0.08);
   data_obs_pass_prefit_projy1__621->GetZaxis()->SetTitleFont(42);
   data_obs_pass_prefit_projy1__621->Draw("pe X0 same");
   
   TLegend *leg = new TLegend(0.65,0.64,0.9,0.88,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(1001);
   TLegendEntry *entry=leg->AddEntry("data_obs_pass_prefit_projy1","Data","pe X0");

   ci = TColor::GetColor("#000000");
   entry->SetLineColor(ci);
   entry->SetLineWidth(1);

   ci = TColor::GetColor("#000000");
   entry->SetMarkerColor(ci);
   entry->SetMarkerStyle(8);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("TotalBkg_pass_prefit_projy1","Total bkg unc.","F");
   entry->SetFillColor(1);
   entry->SetFillStyle(3354);
   entry->SetLineColor(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("Signal_ppStau-557_pass_prefit_projy1","HSCP signal","L");
   entry->SetLineColor(2);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("Background_0x0_pass_prefit_projy1_stack_1_stack_1","Background","f");

   ci = TColor::GetColor("#ffff00");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = 1555;
   color = new TColor(ci, 1, 1, 1, " ", 0);
   entry->SetLineColor(ci);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   leg->Draw();
   Double_t xAxis978[2] = {50, 200}; 
   
   TH1D *data_obs_pass_prefit_projy1_copy__622 = new TH1D("data_obs_pass_prefit_projy1_copy__622","",1, xAxis978);
   data_obs_pass_prefit_projy1_copy__622->SetBinContent(1,990);
   data_obs_pass_prefit_projy1_copy__622->SetBinError(1,31.46427);
   data_obs_pass_prefit_projy1_copy__622->SetMinimum(0);
   data_obs_pass_prefit_projy1_copy__622->SetMaximum(1336.5);
   data_obs_pass_prefit_projy1_copy__622->SetEntries(990);
   data_obs_pass_prefit_projy1_copy__622->SetDirectory(0);

   ci = TColor::GetColor("#000000");
   data_obs_pass_prefit_projy1_copy__622->SetLineColor(ci);
   data_obs_pass_prefit_projy1_copy__622->SetLineStyle(0);

   ci = TColor::GetColor("#000000");
   data_obs_pass_prefit_projy1_copy__622->SetMarkerColor(ci);
   data_obs_pass_prefit_projy1_copy__622->SetMarkerStyle(8);
   data_obs_pass_prefit_projy1_copy__622->GetXaxis()->SetTitle("p_{T}");
   data_obs_pass_prefit_projy1_copy__622->GetXaxis()->SetLabelFont(42);
   data_obs_pass_prefit_projy1_copy__622->GetXaxis()->SetLabelOffset(0.05);
   data_obs_pass_prefit_projy1_copy__622->GetXaxis()->SetLabelSize(0.07);
   data_obs_pass_prefit_projy1_copy__622->GetXaxis()->SetTitleSize(0.09);
   data_obs_pass_prefit_projy1_copy__622->GetXaxis()->SetTitleOffset(1.15);
   data_obs_pass_prefit_projy1_copy__622->GetXaxis()->SetTitleFont(42);
   data_obs_pass_prefit_projy1_copy__622->GetYaxis()->SetTitle("Events / bin");
   data_obs_pass_prefit_projy1_copy__622->GetYaxis()->SetNdivisions(508);
   data_obs_pass_prefit_projy1_copy__622->GetYaxis()->SetLabelFont(42);
   data_obs_pass_prefit_projy1_copy__622->GetYaxis()->SetLabelOffset(0.007);
   data_obs_pass_prefit_projy1_copy__622->GetYaxis()->SetLabelSize(0.07);
   data_obs_pass_prefit_projy1_copy__622->GetYaxis()->SetTitleSize(0.09);
   data_obs_pass_prefit_projy1_copy__622->GetYaxis()->SetTitleOffset(0.8);
   data_obs_pass_prefit_projy1_copy__622->GetYaxis()->SetTitleFont(42);
   data_obs_pass_prefit_projy1_copy__622->GetZaxis()->SetLabelFont(42);
   data_obs_pass_prefit_projy1_copy__622->GetZaxis()->SetLabelOffset(0.007);
   data_obs_pass_prefit_projy1_copy__622->GetZaxis()->SetLabelSize(0.05);
   data_obs_pass_prefit_projy1_copy__622->GetZaxis()->SetTitleSize(0.08);
   data_obs_pass_prefit_projy1_copy__622->GetZaxis()->SetTitleFont(42);
   data_obs_pass_prefit_projy1_copy__622->Draw("sameaxis");
   TLatex *   tex = new TLatex(0.21,0.83,"55 < p_{T} < 200 GeV, F^{Pixels}_{i} > 0.9");
tex->SetNDC();
   tex->SetTextAlign(12);
   tex->SetTextFont(42);
   tex->SetTextSize(0.06);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.17,0.92,"CMS");
tex->SetNDC();
   tex->SetTextFont(61);
   tex->SetTextSize(0.0675);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.25,0.92,"Preliminary");
tex->SetNDC();
   tex->SetTextFont(52);
   tex->SetTextSize(0.0485);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.95,0.92,"101 fb^{-1} (13 TeV)");
tex->SetNDC();
   tex->SetTextAlign(31);
   tex->SetTextFont(42);
   tex->SetTextSize(0.07);
   tex->SetLineWidth(2);
   tex->Draw();
   data_obs_pass_prefit_projy1_main->Modified();
   plots_fit_s/base_figs/prefit_projy1_pass->cd();
  
// ------------>Primitives in pad: data_obs_pass_prefit_projy1_sub
   TPad *data_obs_pass_prefit_projy1_sub = new TPad("data_obs_pass_prefit_projy1_sub", "data_obs_pass_prefit_projy1_sub",0,0,1,0.35);
   data_obs_pass_prefit_projy1_sub->Draw();
   data_obs_pass_prefit_projy1_sub->cd();
   data_obs_pass_prefit_projy1_sub->Range(17.30769,-6.023077,209.6154,2.9);
   data_obs_pass_prefit_projy1_sub->SetFillColor(0);
   data_obs_pass_prefit_projy1_sub->SetBorderMode(0);
   data_obs_pass_prefit_projy1_sub->SetBorderSize(2);
   data_obs_pass_prefit_projy1_sub->SetTickx(1);
   data_obs_pass_prefit_projy1_sub->SetTicky(1);
   data_obs_pass_prefit_projy1_sub->SetLeftMargin(0.17);
   data_obs_pass_prefit_projy1_sub->SetRightMargin(0.05);
   data_obs_pass_prefit_projy1_sub->SetTopMargin(0);
   data_obs_pass_prefit_projy1_sub->SetBottomMargin(0.35);
   data_obs_pass_prefit_projy1_sub->SetFrameFillStyle(0);
   data_obs_pass_prefit_projy1_sub->SetFrameBorderMode(0);
   data_obs_pass_prefit_projy1_sub->SetFrameFillStyle(0);
   data_obs_pass_prefit_projy1_sub->SetFrameBorderMode(0);
   Double_t xAxis979[2] = {50, 200}; 
   
   TH1D *data_obs_pass_prefit_projy1_pull__623 = new TH1D("data_obs_pass_prefit_projy1_pull__623","",1, xAxis979);
   data_obs_pass_prefit_projy1_pull__623->SetBinContent(1,17.49544);
   data_obs_pass_prefit_projy1_pull__623->SetBinError(1,53.02038);
   data_obs_pass_prefit_projy1_pull__623->SetMinimum(-2.9);
   data_obs_pass_prefit_projy1_pull__623->SetMaximum(2.9);
   data_obs_pass_prefit_projy1_pull__623->SetEntries(307.0542);
   data_obs_pass_prefit_projy1_pull__623->SetStats(0);

   ci = TColor::GetColor("#0000ff");
   data_obs_pass_prefit_projy1_pull__623->SetFillColor(ci);

   ci = TColor::GetColor("#000000");
   data_obs_pass_prefit_projy1_pull__623->SetLineColor(ci);
   data_obs_pass_prefit_projy1_pull__623->SetLineStyle(0);

   ci = TColor::GetColor("#000000");
   data_obs_pass_prefit_projy1_pull__623->SetMarkerColor(ci);
   data_obs_pass_prefit_projy1_pull__623->SetMarkerStyle(8);
   data_obs_pass_prefit_projy1_pull__623->GetXaxis()->SetTitle("p_{T}");
   data_obs_pass_prefit_projy1_pull__623->GetXaxis()->SetLabelFont(42);
   data_obs_pass_prefit_projy1_pull__623->GetXaxis()->SetLabelOffset(0.05);
   data_obs_pass_prefit_projy1_pull__623->GetXaxis()->SetLabelSize(0.13);
   data_obs_pass_prefit_projy1_pull__623->GetXaxis()->SetTitleSize(0.15);
   data_obs_pass_prefit_projy1_pull__623->GetXaxis()->SetTitleOffset(1.15);
   data_obs_pass_prefit_projy1_pull__623->GetXaxis()->SetTitleFont(42);
   data_obs_pass_prefit_projy1_pull__623->GetYaxis()->SetTitle("(Data-Bkg)/#sigma");
   data_obs_pass_prefit_projy1_pull__623->GetYaxis()->SetNdivisions(306);
   data_obs_pass_prefit_projy1_pull__623->GetYaxis()->SetLabelFont(42);
   data_obs_pass_prefit_projy1_pull__623->GetYaxis()->SetLabelOffset(0.007);
   data_obs_pass_prefit_projy1_pull__623->GetYaxis()->SetLabelSize(0.13);
   data_obs_pass_prefit_projy1_pull__623->GetYaxis()->SetTitleSize(0.12);
   data_obs_pass_prefit_projy1_pull__623->GetYaxis()->SetTitleOffset(0.4);
   data_obs_pass_prefit_projy1_pull__623->GetYaxis()->SetTitleFont(42);
   data_obs_pass_prefit_projy1_pull__623->GetZaxis()->SetLabelFont(42);
   data_obs_pass_prefit_projy1_pull__623->GetZaxis()->SetLabelOffset(0.007);
   data_obs_pass_prefit_projy1_pull__623->GetZaxis()->SetLabelSize(0.05);
   data_obs_pass_prefit_projy1_pull__623->GetZaxis()->SetTitleSize(0.08);
   data_obs_pass_prefit_projy1_pull__623->GetZaxis()->SetTitleFont(42);
   data_obs_pass_prefit_projy1_pull__623->Draw("hist");
   data_obs_pass_prefit_projy1_sub->Modified();
   plots_fit_s/base_figs/prefit_projy1_pass->cd();
   plots_fit_s/base_figs/prefit_projy1_pass->Modified();
   plots_fit_s/base_figs/prefit_projy1_pass->cd();
   plots_fit_s/base_figs/prefit_projy1_pass->SetSelected(plots_fit_s/base_figs/prefit_projy1_pass);
}
