void prefit_projx1_pass_logy()
{
//=========Macro generated from canvas: plots_fit_s/base_figs/prefit_projx1_pass_logy/plots_fit_s/base_figs/prefit_projx1_pass_logy
//=========  (Fri Jan 12 21:00:35 2024) by ROOT version 6.14/09
   TCanvas *plots_fit_s/base_figs/prefit_projx1_pass_logy = new TCanvas("plots_fit_s/base_figs/prefit_projx1_pass_logy", "plots_fit_s/base_figs/prefit_projx1_pass_logy",0,0,800,700);
   gStyle->SetOptFit(1);
   gStyle->SetOptStat(0);
   plots_fit_s/base_figs/prefit_projx1_pass_logy->SetHighLightColor(2);
   plots_fit_s/base_figs/prefit_projx1_pass_logy->Range(0,0,1,1);
   plots_fit_s/base_figs/prefit_projx1_pass_logy->SetFillColor(0);
   plots_fit_s/base_figs/prefit_projx1_pass_logy->SetBorderMode(0);
   plots_fit_s/base_figs/prefit_projx1_pass_logy->SetBorderSize(2);
   plots_fit_s/base_figs/prefit_projx1_pass_logy->SetTickx(1);
   plots_fit_s/base_figs/prefit_projx1_pass_logy->SetTicky(1);
   plots_fit_s/base_figs/prefit_projx1_pass_logy->SetLeftMargin(0.16);
   plots_fit_s/base_figs/prefit_projx1_pass_logy->SetRightMargin(0);
   plots_fit_s/base_figs/prefit_projx1_pass_logy->SetTopMargin(0);
   plots_fit_s/base_figs/prefit_projx1_pass_logy->SetBottomMargin(0);
   plots_fit_s/base_figs/prefit_projx1_pass_logy->SetFrameFillStyle(0);
   plots_fit_s/base_figs/prefit_projx1_pass_logy->SetFrameBorderMode(0);
  
// ------------>Primitives in pad: data_obs_pass_prefit_projx1_main
   TPad *data_obs_pass_prefit_projx1_main = new TPad("data_obs_pass_prefit_projx1_main", "data_obs_pass_prefit_projx1_main",0,0.35,1,1);
   data_obs_pass_prefit_projx1_main->Draw();
   data_obs_pass_prefit_projx1_main->cd();
   data_obs_pass_prefit_projx1_main->Range(-0.2179487,-2.139535,1.064103,1.348837);
   data_obs_pass_prefit_projx1_main->SetFillColor(0);
   data_obs_pass_prefit_projx1_main->SetBorderMode(0);
   data_obs_pass_prefit_projx1_main->SetBorderSize(2);
   data_obs_pass_prefit_projx1_main->SetLogy();
   data_obs_pass_prefit_projx1_main->SetTickx(1);
   data_obs_pass_prefit_projx1_main->SetTicky(1);
   data_obs_pass_prefit_projx1_main->SetLeftMargin(0.17);
   data_obs_pass_prefit_projx1_main->SetRightMargin(0.05);
   data_obs_pass_prefit_projx1_main->SetBottomMargin(0.04);
   data_obs_pass_prefit_projx1_main->SetFrameFillStyle(0);
   data_obs_pass_prefit_projx1_main->SetFrameBorderMode(0);
   data_obs_pass_prefit_projx1_main->SetFrameFillStyle(0);
   data_obs_pass_prefit_projx1_main->SetFrameBorderMode(0);
   Double_t xAxis1002[10] = {0, 0.04, 0.08, 0.12, 0.16, 0.2, 0.24, 0.28, 0.32, 1}; 
   
   TH1D *data_obs_pass_prefit_projx1__638 = new TH1D("data_obs_pass_prefit_projx1__638","",9, xAxis1002);
   data_obs_pass_prefit_projx1__638->SetMinimum(0.001);
   data_obs_pass_prefit_projx1__638->SetMaximum(0);

   Int_t ci;      // for color index setting
   TColor *color; // for color definition with alpha
   ci = TColor::GetColor("#000000");
   data_obs_pass_prefit_projx1__638->SetLineColor(ci);
   data_obs_pass_prefit_projx1__638->SetLineStyle(0);

   ci = TColor::GetColor("#000000");
   data_obs_pass_prefit_projx1__638->SetMarkerColor(ci);
   data_obs_pass_prefit_projx1__638->SetMarkerStyle(8);
   data_obs_pass_prefit_projx1__638->GetXaxis()->SetTitle("G_{i}^{Strips}");
   data_obs_pass_prefit_projx1__638->GetXaxis()->SetLabelFont(42);
   data_obs_pass_prefit_projx1__638->GetXaxis()->SetLabelOffset(0.05);
   data_obs_pass_prefit_projx1__638->GetXaxis()->SetLabelSize(0.07);
   data_obs_pass_prefit_projx1__638->GetXaxis()->SetTitleSize(0.09);
   data_obs_pass_prefit_projx1__638->GetXaxis()->SetTitleOffset(1.15);
   data_obs_pass_prefit_projx1__638->GetXaxis()->SetTitleFont(42);
   data_obs_pass_prefit_projx1__638->GetYaxis()->SetTitle("Events / bin");
   data_obs_pass_prefit_projx1__638->GetYaxis()->SetNdivisions(508);
   data_obs_pass_prefit_projx1__638->GetYaxis()->SetLabelFont(42);
   data_obs_pass_prefit_projx1__638->GetYaxis()->SetLabelOffset(0.007);
   data_obs_pass_prefit_projx1__638->GetYaxis()->SetLabelSize(0.07);
   data_obs_pass_prefit_projx1__638->GetYaxis()->SetTitleSize(0.09);
   data_obs_pass_prefit_projx1__638->GetYaxis()->SetTitleOffset(0.8);
   data_obs_pass_prefit_projx1__638->GetYaxis()->SetTitleFont(42);
   data_obs_pass_prefit_projx1__638->GetZaxis()->SetLabelFont(42);
   data_obs_pass_prefit_projx1__638->GetZaxis()->SetLabelOffset(0.007);
   data_obs_pass_prefit_projx1__638->GetZaxis()->SetLabelSize(0.05);
   data_obs_pass_prefit_projx1__638->GetZaxis()->SetTitleSize(0.08);
   data_obs_pass_prefit_projx1__638->GetZaxis()->SetTitleFont(42);
   data_obs_pass_prefit_projx1__638->Draw("pe X0");
   
   THStack *prefit_projx1_pass_logy_stack = new THStack();
   prefit_projx1_pass_logy_stack->SetName("prefit_projx1_pass_logy_stack");
   prefit_projx1_pass_logy_stack->SetTitle("prefit_projx1_pass_logy_stack");
   prefit_projx1_pass_logy_stack->SetMinimum(0.001);
   Double_t xAxis1003[10] = {0, 0.04, 0.08, 0.12, 0.16, 0.2, 0.24, 0.28, 0.32, 1}; 
   
   TH1F *prefit_projx1_pass_logy_stack_stack_183 = new TH1F("prefit_projx1_pass_logy_stack_stack_183","prefit_projx1_pass_logy_stack",9, xAxis1003);
   prefit_projx1_pass_logy_stack_stack_183->SetMinimum(-0);
   prefit_projx1_pass_logy_stack_stack_183->SetMaximum(-nan);
   prefit_projx1_pass_logy_stack_stack_183->SetDirectory(0);
   prefit_projx1_pass_logy_stack_stack_183->SetStats(0);
   prefit_projx1_pass_logy_stack_stack_183->SetLineStyle(0);
   prefit_projx1_pass_logy_stack_stack_183->GetXaxis()->SetLabelFont(42);
   prefit_projx1_pass_logy_stack_stack_183->GetXaxis()->SetLabelOffset(0.007);
   prefit_projx1_pass_logy_stack_stack_183->GetXaxis()->SetLabelSize(0.05);
   prefit_projx1_pass_logy_stack_stack_183->GetXaxis()->SetTitleSize(0.08);
   prefit_projx1_pass_logy_stack_stack_183->GetXaxis()->SetTitleOffset(0.9);
   prefit_projx1_pass_logy_stack_stack_183->GetXaxis()->SetTitleFont(42);
   prefit_projx1_pass_logy_stack_stack_183->GetYaxis()->SetNdivisions(508);
   prefit_projx1_pass_logy_stack_stack_183->GetYaxis()->SetLabelFont(42);
   prefit_projx1_pass_logy_stack_stack_183->GetYaxis()->SetLabelOffset(0.007);
   prefit_projx1_pass_logy_stack_stack_183->GetYaxis()->SetLabelSize(0.05);
   prefit_projx1_pass_logy_stack_stack_183->GetYaxis()->SetTitleSize(0.08);
   prefit_projx1_pass_logy_stack_stack_183->GetYaxis()->SetTitleOffset(1.25);
   prefit_projx1_pass_logy_stack_stack_183->GetYaxis()->SetTitleFont(42);
   prefit_projx1_pass_logy_stack_stack_183->GetZaxis()->SetLabelFont(42);
   prefit_projx1_pass_logy_stack_stack_183->GetZaxis()->SetLabelOffset(0.007);
   prefit_projx1_pass_logy_stack_stack_183->GetZaxis()->SetLabelSize(0.05);
   prefit_projx1_pass_logy_stack_stack_183->GetZaxis()->SetTitleSize(0.08);
   prefit_projx1_pass_logy_stack_stack_183->GetZaxis()->SetTitleFont(42);
   prefit_projx1_pass_logy_stack->SetHistogram(prefit_projx1_pass_logy_stack_stack_183);
   
   Double_t xAxis1004[10] = {0, 0.04, 0.08, 0.12, 0.16, 0.2, 0.24, 0.28, 0.32, 1}; 
   
   TH1D *Background_0x0_pass_prefit_projx1_stack_1 = new TH1D("Background_0x0_pass_prefit_projx1_stack_1","Background, pass, prefit, 50-50",9, xAxis1004);
   Background_0x0_pass_prefit_projx1_stack_1->SetMinimum(0.001);

   ci = TColor::GetColor("#ffff00");
   Background_0x0_pass_prefit_projx1_stack_1->SetFillColor(ci);

   ci = 1552;
   color = new TColor(ci, 1, 1, 1, " ", 0);
   Background_0x0_pass_prefit_projx1_stack_1->SetLineColor(ci);
   Background_0x0_pass_prefit_projx1_stack_1->SetLineStyle(0);
   Background_0x0_pass_prefit_projx1_stack_1->GetXaxis()->SetTitle("G_{i}^{Strips}");
   Background_0x0_pass_prefit_projx1_stack_1->GetXaxis()->SetLabelFont(42);
   Background_0x0_pass_prefit_projx1_stack_1->GetXaxis()->SetLabelOffset(0.007);
   Background_0x0_pass_prefit_projx1_stack_1->GetXaxis()->SetLabelSize(0.05);
   Background_0x0_pass_prefit_projx1_stack_1->GetXaxis()->SetTitleSize(0.08);
   Background_0x0_pass_prefit_projx1_stack_1->GetXaxis()->SetTitleOffset(0.9);
   Background_0x0_pass_prefit_projx1_stack_1->GetXaxis()->SetTitleFont(42);
   Background_0x0_pass_prefit_projx1_stack_1->GetYaxis()->SetTitle("Events / bin");
   Background_0x0_pass_prefit_projx1_stack_1->GetYaxis()->SetLabelFont(42);
   Background_0x0_pass_prefit_projx1_stack_1->GetYaxis()->SetLabelOffset(0.007);
   Background_0x0_pass_prefit_projx1_stack_1->GetYaxis()->SetLabelSize(0.05);
   Background_0x0_pass_prefit_projx1_stack_1->GetYaxis()->SetTitleSize(0.08);
   Background_0x0_pass_prefit_projx1_stack_1->GetYaxis()->SetTitleOffset(1.25);
   Background_0x0_pass_prefit_projx1_stack_1->GetYaxis()->SetTitleFont(42);
   Background_0x0_pass_prefit_projx1_stack_1->GetZaxis()->SetLabelFont(42);
   Background_0x0_pass_prefit_projx1_stack_1->GetZaxis()->SetLabelOffset(0.007);
   Background_0x0_pass_prefit_projx1_stack_1->GetZaxis()->SetLabelSize(0.05);
   Background_0x0_pass_prefit_projx1_stack_1->GetZaxis()->SetTitleSize(0.08);
   Background_0x0_pass_prefit_projx1_stack_1->GetZaxis()->SetTitleFont(42);
   prefit_projx1_pass_logy_stack->Add(Background_0x0_pass_prefit_projx1_stack_1,"");
   prefit_projx1_pass_logy_stack->Draw("hist same");
   
   prefit_projx1_pass_logy_stack = new THStack();
   prefit_projx1_pass_logy_stack->SetName("prefit_projx1_pass_logy_stack");
   prefit_projx1_pass_logy_stack->SetTitle("prefit_projx1_pass_logy_stack");
   prefit_projx1_pass_logy_stack->SetMinimum(0.001);
   Double_t xAxis1005[10] = {0, 0.04, 0.08, 0.12, 0.16, 0.2, 0.24, 0.28, 0.32, 1}; 
   
   TH1F *prefit_projx1_pass_logy_stack_stack_183_stack_184 = new TH1F("prefit_projx1_pass_logy_stack_stack_183_stack_184","prefit_projx1_pass_logy_stack",9, xAxis1005);
   prefit_projx1_pass_logy_stack_stack_183_stack_184->SetMinimum(-0);
   prefit_projx1_pass_logy_stack_stack_183_stack_184->SetMaximum(-nan);
   prefit_projx1_pass_logy_stack_stack_183_stack_184->SetDirectory(0);
   prefit_projx1_pass_logy_stack_stack_183_stack_184->SetStats(0);
   prefit_projx1_pass_logy_stack_stack_183_stack_184->SetLineStyle(0);
   prefit_projx1_pass_logy_stack_stack_183_stack_184->GetXaxis()->SetLabelFont(42);
   prefit_projx1_pass_logy_stack_stack_183_stack_184->GetXaxis()->SetLabelOffset(0.007);
   prefit_projx1_pass_logy_stack_stack_183_stack_184->GetXaxis()->SetLabelSize(0.05);
   prefit_projx1_pass_logy_stack_stack_183_stack_184->GetXaxis()->SetTitleSize(0.08);
   prefit_projx1_pass_logy_stack_stack_183_stack_184->GetXaxis()->SetTitleOffset(0.9);
   prefit_projx1_pass_logy_stack_stack_183_stack_184->GetXaxis()->SetTitleFont(42);
   prefit_projx1_pass_logy_stack_stack_183_stack_184->GetYaxis()->SetNdivisions(508);
   prefit_projx1_pass_logy_stack_stack_183_stack_184->GetYaxis()->SetLabelFont(42);
   prefit_projx1_pass_logy_stack_stack_183_stack_184->GetYaxis()->SetLabelOffset(0.007);
   prefit_projx1_pass_logy_stack_stack_183_stack_184->GetYaxis()->SetLabelSize(0.05);
   prefit_projx1_pass_logy_stack_stack_183_stack_184->GetYaxis()->SetTitleSize(0.08);
   prefit_projx1_pass_logy_stack_stack_183_stack_184->GetYaxis()->SetTitleOffset(1.25);
   prefit_projx1_pass_logy_stack_stack_183_stack_184->GetYaxis()->SetTitleFont(42);
   prefit_projx1_pass_logy_stack_stack_183_stack_184->GetZaxis()->SetLabelFont(42);
   prefit_projx1_pass_logy_stack_stack_183_stack_184->GetZaxis()->SetLabelOffset(0.007);
   prefit_projx1_pass_logy_stack_stack_183_stack_184->GetZaxis()->SetLabelSize(0.05);
   prefit_projx1_pass_logy_stack_stack_183_stack_184->GetZaxis()->SetTitleSize(0.08);
   prefit_projx1_pass_logy_stack_stack_183_stack_184->GetZaxis()->SetTitleFont(42);
   prefit_projx1_pass_logy_stack->SetHistogram(prefit_projx1_pass_logy_stack_stack_183_stack_184);
   
   Double_t xAxis1006[10] = {0, 0.04, 0.08, 0.12, 0.16, 0.2, 0.24, 0.28, 0.32, 1}; 
   
   TH1D *Background_0x0_pass_prefit_projx1_stack_1_stack_1 = new TH1D("Background_0x0_pass_prefit_projx1_stack_1_stack_1","Background, pass, prefit, 50-50",9, xAxis1006);
   Background_0x0_pass_prefit_projx1_stack_1_stack_1->SetMinimum(0.001);

   ci = TColor::GetColor("#ffff00");
   Background_0x0_pass_prefit_projx1_stack_1_stack_1->SetFillColor(ci);

   ci = 1552;
   color = new TColor(ci, 1, 1, 1, " ", 0);
   Background_0x0_pass_prefit_projx1_stack_1_stack_1->SetLineColor(ci);
   Background_0x0_pass_prefit_projx1_stack_1_stack_1->SetLineStyle(0);
   Background_0x0_pass_prefit_projx1_stack_1_stack_1->GetXaxis()->SetTitle("G_{i}^{Strips}");
   Background_0x0_pass_prefit_projx1_stack_1_stack_1->GetXaxis()->SetLabelFont(42);
   Background_0x0_pass_prefit_projx1_stack_1_stack_1->GetXaxis()->SetLabelOffset(0.007);
   Background_0x0_pass_prefit_projx1_stack_1_stack_1->GetXaxis()->SetLabelSize(0.05);
   Background_0x0_pass_prefit_projx1_stack_1_stack_1->GetXaxis()->SetTitleSize(0.08);
   Background_0x0_pass_prefit_projx1_stack_1_stack_1->GetXaxis()->SetTitleOffset(0.9);
   Background_0x0_pass_prefit_projx1_stack_1_stack_1->GetXaxis()->SetTitleFont(42);
   Background_0x0_pass_prefit_projx1_stack_1_stack_1->GetYaxis()->SetTitle("Events / bin");
   Background_0x0_pass_prefit_projx1_stack_1_stack_1->GetYaxis()->SetLabelFont(42);
   Background_0x0_pass_prefit_projx1_stack_1_stack_1->GetYaxis()->SetLabelOffset(0.007);
   Background_0x0_pass_prefit_projx1_stack_1_stack_1->GetYaxis()->SetLabelSize(0.05);
   Background_0x0_pass_prefit_projx1_stack_1_stack_1->GetYaxis()->SetTitleSize(0.08);
   Background_0x0_pass_prefit_projx1_stack_1_stack_1->GetYaxis()->SetTitleOffset(1.25);
   Background_0x0_pass_prefit_projx1_stack_1_stack_1->GetYaxis()->SetTitleFont(42);
   Background_0x0_pass_prefit_projx1_stack_1_stack_1->GetZaxis()->SetLabelFont(42);
   Background_0x0_pass_prefit_projx1_stack_1_stack_1->GetZaxis()->SetLabelOffset(0.007);
   Background_0x0_pass_prefit_projx1_stack_1_stack_1->GetZaxis()->SetLabelSize(0.05);
   Background_0x0_pass_prefit_projx1_stack_1_stack_1->GetZaxis()->SetTitleSize(0.08);
   Background_0x0_pass_prefit_projx1_stack_1_stack_1->GetZaxis()->SetTitleFont(42);
   prefit_projx1_pass_logy_stack->Add(Background_0x0_pass_prefit_projx1_stack_1_stack_1,"");
   prefit_projx1_pass_logy_stack->Draw("hist same");
   Double_t xAxis1007[10] = {0, 0.04, 0.08, 0.12, 0.16, 0.2, 0.24, 0.28, 0.32, 1}; 
   
   TH1D *Signal_ppStaumI557_pass_prefit_projx1__639 = new TH1D("Signal_ppStaumI557_pass_prefit_projx1__639","HSCP signal, pass, prefit, 50-50",9, xAxis1007);
   Signal_ppStaumI557_pass_prefit_projx1__639->SetMinimum(0.001);
   Signal_ppStaumI557_pass_prefit_projx1__639->SetLineColor(2);
   Signal_ppStaumI557_pass_prefit_projx1__639->SetLineStyle(0);
   Signal_ppStaumI557_pass_prefit_projx1__639->GetXaxis()->SetTitle("G_{i}^{Strips}");
   Signal_ppStaumI557_pass_prefit_projx1__639->GetXaxis()->SetLabelFont(42);
   Signal_ppStaumI557_pass_prefit_projx1__639->GetXaxis()->SetLabelOffset(0.007);
   Signal_ppStaumI557_pass_prefit_projx1__639->GetXaxis()->SetLabelSize(0.05);
   Signal_ppStaumI557_pass_prefit_projx1__639->GetXaxis()->SetTitleSize(0.08);
   Signal_ppStaumI557_pass_prefit_projx1__639->GetXaxis()->SetTitleOffset(0.9);
   Signal_ppStaumI557_pass_prefit_projx1__639->GetXaxis()->SetTitleFont(42);
   Signal_ppStaumI557_pass_prefit_projx1__639->GetYaxis()->SetTitle("Events / bin");
   Signal_ppStaumI557_pass_prefit_projx1__639->GetYaxis()->SetLabelFont(42);
   Signal_ppStaumI557_pass_prefit_projx1__639->GetYaxis()->SetLabelOffset(0.007);
   Signal_ppStaumI557_pass_prefit_projx1__639->GetYaxis()->SetLabelSize(0.05);
   Signal_ppStaumI557_pass_prefit_projx1__639->GetYaxis()->SetTitleSize(0.08);
   Signal_ppStaumI557_pass_prefit_projx1__639->GetYaxis()->SetTitleOffset(1.25);
   Signal_ppStaumI557_pass_prefit_projx1__639->GetYaxis()->SetTitleFont(42);
   Signal_ppStaumI557_pass_prefit_projx1__639->GetZaxis()->SetLabelFont(42);
   Signal_ppStaumI557_pass_prefit_projx1__639->GetZaxis()->SetLabelOffset(0.007);
   Signal_ppStaumI557_pass_prefit_projx1__639->GetZaxis()->SetLabelSize(0.05);
   Signal_ppStaumI557_pass_prefit_projx1__639->GetZaxis()->SetTitleSize(0.08);
   Signal_ppStaumI557_pass_prefit_projx1__639->GetZaxis()->SetTitleFont(42);
   Signal_ppStaumI557_pass_prefit_projx1__639->Draw("hist same");
   Double_t xAxis1008[10] = {0, 0.04, 0.08, 0.12, 0.16, 0.2, 0.24, 0.28, 0.32, 1}; 
   
   TH1D *TotalBkg_pass_prefit_projx1__640 = new TH1D("TotalBkg_pass_prefit_projx1__640","TotalBkg, pass, prefit, 50-50",9, xAxis1008);
   TotalBkg_pass_prefit_projx1__640->SetMinimum(0.001);
   TotalBkg_pass_prefit_projx1__640->SetLineStyle(0);
   TotalBkg_pass_prefit_projx1__640->SetMarkerStyle(0);
   TotalBkg_pass_prefit_projx1__640->GetXaxis()->SetTitle("G_{i}^{Strips}");
   TotalBkg_pass_prefit_projx1__640->GetXaxis()->SetLabelFont(42);
   TotalBkg_pass_prefit_projx1__640->GetXaxis()->SetLabelOffset(0.007);
   TotalBkg_pass_prefit_projx1__640->GetXaxis()->SetLabelSize(0.05);
   TotalBkg_pass_prefit_projx1__640->GetXaxis()->SetTitleSize(0.08);
   TotalBkg_pass_prefit_projx1__640->GetXaxis()->SetTitleOffset(0.9);
   TotalBkg_pass_prefit_projx1__640->GetXaxis()->SetTitleFont(42);
   TotalBkg_pass_prefit_projx1__640->GetYaxis()->SetTitle("Events / bin");
   TotalBkg_pass_prefit_projx1__640->GetYaxis()->SetLabelFont(42);
   TotalBkg_pass_prefit_projx1__640->GetYaxis()->SetLabelOffset(0.007);
   TotalBkg_pass_prefit_projx1__640->GetYaxis()->SetLabelSize(0.05);
   TotalBkg_pass_prefit_projx1__640->GetYaxis()->SetTitleSize(0.08);
   TotalBkg_pass_prefit_projx1__640->GetYaxis()->SetTitleOffset(1.25);
   TotalBkg_pass_prefit_projx1__640->GetYaxis()->SetTitleFont(42);
   TotalBkg_pass_prefit_projx1__640->GetZaxis()->SetLabelFont(42);
   TotalBkg_pass_prefit_projx1__640->GetZaxis()->SetLabelOffset(0.007);
   TotalBkg_pass_prefit_projx1__640->GetZaxis()->SetLabelSize(0.05);
   TotalBkg_pass_prefit_projx1__640->GetZaxis()->SetTitleSize(0.08);
   TotalBkg_pass_prefit_projx1__640->GetZaxis()->SetTitleFont(42);
   TotalBkg_pass_prefit_projx1__640->Draw("hist same");
   Double_t xAxis1009[10] = {0, 0.04, 0.08, 0.12, 0.16, 0.2, 0.24, 0.28, 0.32, 1}; 
   
   TH1D *TotalBkg_pass_prefit_projx1__641 = new TH1D("TotalBkg_pass_prefit_projx1__641","TotalBkg, pass, prefit, 50-50",9, xAxis1009);
   TotalBkg_pass_prefit_projx1__641->SetMinimum(0.001);
   TotalBkg_pass_prefit_projx1__641->SetFillColor(1);
   TotalBkg_pass_prefit_projx1__641->SetFillStyle(3354);
   TotalBkg_pass_prefit_projx1__641->SetLineStyle(0);
   TotalBkg_pass_prefit_projx1__641->SetLineWidth(0);
   TotalBkg_pass_prefit_projx1__641->SetMarkerStyle(0);
   TotalBkg_pass_prefit_projx1__641->GetXaxis()->SetTitle("G_{i}^{Strips}");
   TotalBkg_pass_prefit_projx1__641->GetXaxis()->SetLabelFont(42);
   TotalBkg_pass_prefit_projx1__641->GetXaxis()->SetLabelOffset(0.007);
   TotalBkg_pass_prefit_projx1__641->GetXaxis()->SetLabelSize(0.05);
   TotalBkg_pass_prefit_projx1__641->GetXaxis()->SetTitleSize(0.08);
   TotalBkg_pass_prefit_projx1__641->GetXaxis()->SetTitleOffset(0.9);
   TotalBkg_pass_prefit_projx1__641->GetXaxis()->SetTitleFont(42);
   TotalBkg_pass_prefit_projx1__641->GetYaxis()->SetTitle("Events / bin");
   TotalBkg_pass_prefit_projx1__641->GetYaxis()->SetLabelFont(42);
   TotalBkg_pass_prefit_projx1__641->GetYaxis()->SetLabelOffset(0.007);
   TotalBkg_pass_prefit_projx1__641->GetYaxis()->SetLabelSize(0.05);
   TotalBkg_pass_prefit_projx1__641->GetYaxis()->SetTitleSize(0.08);
   TotalBkg_pass_prefit_projx1__641->GetYaxis()->SetTitleOffset(1.25);
   TotalBkg_pass_prefit_projx1__641->GetYaxis()->SetTitleFont(42);
   TotalBkg_pass_prefit_projx1__641->GetZaxis()->SetLabelFont(42);
   TotalBkg_pass_prefit_projx1__641->GetZaxis()->SetLabelOffset(0.007);
   TotalBkg_pass_prefit_projx1__641->GetZaxis()->SetLabelSize(0.05);
   TotalBkg_pass_prefit_projx1__641->GetZaxis()->SetTitleSize(0.08);
   TotalBkg_pass_prefit_projx1__641->GetZaxis()->SetTitleFont(42);
   TotalBkg_pass_prefit_projx1__641->Draw("e2 same");
   Double_t xAxis1010[10] = {0, 0.04, 0.08, 0.12, 0.16, 0.2, 0.24, 0.28, 0.32, 1}; 
   
   TH1D *data_obs_pass_prefit_projx1__642 = new TH1D("data_obs_pass_prefit_projx1__642","",9, xAxis1010);
   data_obs_pass_prefit_projx1__642->SetMinimum(0.001);
   data_obs_pass_prefit_projx1__642->SetMaximum(0);

   ci = TColor::GetColor("#000000");
   data_obs_pass_prefit_projx1__642->SetLineColor(ci);
   data_obs_pass_prefit_projx1__642->SetLineStyle(0);

   ci = TColor::GetColor("#000000");
   data_obs_pass_prefit_projx1__642->SetMarkerColor(ci);
   data_obs_pass_prefit_projx1__642->SetMarkerStyle(8);
   data_obs_pass_prefit_projx1__642->GetXaxis()->SetTitle("G_{i}^{Strips}");
   data_obs_pass_prefit_projx1__642->GetXaxis()->SetLabelFont(42);
   data_obs_pass_prefit_projx1__642->GetXaxis()->SetLabelOffset(0.05);
   data_obs_pass_prefit_projx1__642->GetXaxis()->SetLabelSize(0.07);
   data_obs_pass_prefit_projx1__642->GetXaxis()->SetTitleSize(0.09);
   data_obs_pass_prefit_projx1__642->GetXaxis()->SetTitleOffset(1.15);
   data_obs_pass_prefit_projx1__642->GetXaxis()->SetTitleFont(42);
   data_obs_pass_prefit_projx1__642->GetYaxis()->SetTitle("Events / bin");
   data_obs_pass_prefit_projx1__642->GetYaxis()->SetNdivisions(508);
   data_obs_pass_prefit_projx1__642->GetYaxis()->SetLabelFont(42);
   data_obs_pass_prefit_projx1__642->GetYaxis()->SetLabelOffset(0.007);
   data_obs_pass_prefit_projx1__642->GetYaxis()->SetLabelSize(0.07);
   data_obs_pass_prefit_projx1__642->GetYaxis()->SetTitleSize(0.09);
   data_obs_pass_prefit_projx1__642->GetYaxis()->SetTitleOffset(0.8);
   data_obs_pass_prefit_projx1__642->GetYaxis()->SetTitleFont(42);
   data_obs_pass_prefit_projx1__642->GetZaxis()->SetLabelFont(42);
   data_obs_pass_prefit_projx1__642->GetZaxis()->SetLabelOffset(0.007);
   data_obs_pass_prefit_projx1__642->GetZaxis()->SetLabelSize(0.05);
   data_obs_pass_prefit_projx1__642->GetZaxis()->SetTitleSize(0.08);
   data_obs_pass_prefit_projx1__642->GetZaxis()->SetTitleFont(42);
   data_obs_pass_prefit_projx1__642->Draw("pe X0 same");
   
   TLegend *leg = new TLegend(0.65,0.64,0.9,0.88,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(1001);
   TLegendEntry *entry=leg->AddEntry("data_obs_pass_prefit_projx1","Data","pe X0");

   ci = TColor::GetColor("#000000");
   entry->SetLineColor(ci);
   entry->SetLineWidth(1);

   ci = TColor::GetColor("#000000");
   entry->SetMarkerColor(ci);
   entry->SetMarkerStyle(8);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("TotalBkg_pass_prefit_projx1","Total bkg unc.","F");
   entry->SetFillColor(1);
   entry->SetFillStyle(3354);
   entry->SetLineColor(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("Signal_ppStau-557_pass_prefit_projx1","HSCP signal","L");
   entry->SetLineColor(2);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("Background_0x0_pass_prefit_projx1_stack_1_stack_1","Background","f");

   ci = TColor::GetColor("#ffff00");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = 1552;
   color = new TColor(ci, 1, 1, 1, " ", 0);
   entry->SetLineColor(ci);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   leg->Draw();
   Double_t xAxis1011[10] = {0, 0.04, 0.08, 0.12, 0.16, 0.2, 0.24, 0.28, 0.32, 1}; 
   
   TH1D *data_obs_pass_prefit_projx1_copy__643 = new TH1D("data_obs_pass_prefit_projx1_copy__643","",9, xAxis1011);
   data_obs_pass_prefit_projx1_copy__643->SetMinimum(0.001);
   data_obs_pass_prefit_projx1_copy__643->SetMaximum(0);
   data_obs_pass_prefit_projx1_copy__643->SetDirectory(0);

   ci = TColor::GetColor("#000000");
   data_obs_pass_prefit_projx1_copy__643->SetLineColor(ci);
   data_obs_pass_prefit_projx1_copy__643->SetLineStyle(0);

   ci = TColor::GetColor("#000000");
   data_obs_pass_prefit_projx1_copy__643->SetMarkerColor(ci);
   data_obs_pass_prefit_projx1_copy__643->SetMarkerStyle(8);
   data_obs_pass_prefit_projx1_copy__643->GetXaxis()->SetTitle("G_{i}^{Strips}");
   data_obs_pass_prefit_projx1_copy__643->GetXaxis()->SetLabelFont(42);
   data_obs_pass_prefit_projx1_copy__643->GetXaxis()->SetLabelOffset(0.05);
   data_obs_pass_prefit_projx1_copy__643->GetXaxis()->SetLabelSize(0.07);
   data_obs_pass_prefit_projx1_copy__643->GetXaxis()->SetTitleSize(0.09);
   data_obs_pass_prefit_projx1_copy__643->GetXaxis()->SetTitleOffset(1.15);
   data_obs_pass_prefit_projx1_copy__643->GetXaxis()->SetTitleFont(42);
   data_obs_pass_prefit_projx1_copy__643->GetYaxis()->SetTitle("Events / bin");
   data_obs_pass_prefit_projx1_copy__643->GetYaxis()->SetNdivisions(508);
   data_obs_pass_prefit_projx1_copy__643->GetYaxis()->SetLabelFont(42);
   data_obs_pass_prefit_projx1_copy__643->GetYaxis()->SetLabelOffset(0.007);
   data_obs_pass_prefit_projx1_copy__643->GetYaxis()->SetLabelSize(0.07);
   data_obs_pass_prefit_projx1_copy__643->GetYaxis()->SetTitleSize(0.09);
   data_obs_pass_prefit_projx1_copy__643->GetYaxis()->SetTitleOffset(0.8);
   data_obs_pass_prefit_projx1_copy__643->GetYaxis()->SetTitleFont(42);
   data_obs_pass_prefit_projx1_copy__643->GetZaxis()->SetLabelFont(42);
   data_obs_pass_prefit_projx1_copy__643->GetZaxis()->SetLabelOffset(0.007);
   data_obs_pass_prefit_projx1_copy__643->GetZaxis()->SetLabelSize(0.05);
   data_obs_pass_prefit_projx1_copy__643->GetZaxis()->SetTitleSize(0.08);
   data_obs_pass_prefit_projx1_copy__643->GetZaxis()->SetTitleFont(42);
   data_obs_pass_prefit_projx1_copy__643->Draw("sameaxis");
   TLatex *   tex = new TLatex(0.21,0.83,"55 < p_{T} < 200 GeV, F^{Pixels}_{i} > 0.9");
tex->SetNDC();
   tex->SetTextAlign(12);
   tex->SetTextFont(42);
   tex->SetTextSize(0.06);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.17,0.92,"CMS");
tex->SetNDC();
   tex->SetTextFont(61);
   tex->SetTextSize(0.0675);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.25,0.92,"Preliminary");
tex->SetNDC();
   tex->SetTextFont(52);
   tex->SetTextSize(0.0485);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.95,0.92,"101 fb^{-1} (13 TeV)");
tex->SetNDC();
   tex->SetTextAlign(31);
   tex->SetTextFont(42);
   tex->SetTextSize(0.07);
   tex->SetLineWidth(2);
   tex->Draw();
   data_obs_pass_prefit_projx1_main->Modified();
   plots_fit_s/base_figs/prefit_projx1_pass_logy->cd();
  
// ------------>Primitives in pad: data_obs_pass_prefit_projx1_sub
   TPad *data_obs_pass_prefit_projx1_sub = new TPad("data_obs_pass_prefit_projx1_sub", "data_obs_pass_prefit_projx1_sub",0,0,1,0.35);
   data_obs_pass_prefit_projx1_sub->Draw();
   data_obs_pass_prefit_projx1_sub->cd();
   data_obs_pass_prefit_projx1_sub->Range(-0.2179487,-6.023077,1.064103,2.9);
   data_obs_pass_prefit_projx1_sub->SetFillColor(0);
   data_obs_pass_prefit_projx1_sub->SetBorderMode(0);
   data_obs_pass_prefit_projx1_sub->SetBorderSize(2);
   data_obs_pass_prefit_projx1_sub->SetTickx(1);
   data_obs_pass_prefit_projx1_sub->SetTicky(1);
   data_obs_pass_prefit_projx1_sub->SetLeftMargin(0.17);
   data_obs_pass_prefit_projx1_sub->SetRightMargin(0.05);
   data_obs_pass_prefit_projx1_sub->SetTopMargin(0);
   data_obs_pass_prefit_projx1_sub->SetBottomMargin(0.35);
   data_obs_pass_prefit_projx1_sub->SetFrameFillStyle(0);
   data_obs_pass_prefit_projx1_sub->SetFrameBorderMode(0);
   data_obs_pass_prefit_projx1_sub->SetFrameFillStyle(0);
   data_obs_pass_prefit_projx1_sub->SetFrameBorderMode(0);
   Double_t xAxis1012[10] = {0, 0.04, 0.08, 0.12, 0.16, 0.2, 0.24, 0.28, 0.32, 1}; 
   
   TH1D *data_obs_pass_prefit_projx1_pull__644 = new TH1D("data_obs_pass_prefit_projx1_pull__644","",9, xAxis1012);
   data_obs_pass_prefit_projx1_pull__644->SetMinimum(-2.9);
   data_obs_pass_prefit_projx1_pull__644->SetMaximum(2.9);
   data_obs_pass_prefit_projx1_pull__644->SetEntries(18);
   data_obs_pass_prefit_projx1_pull__644->SetStats(0);

   ci = TColor::GetColor("#0000ff");
   data_obs_pass_prefit_projx1_pull__644->SetFillColor(ci);

   ci = TColor::GetColor("#000000");
   data_obs_pass_prefit_projx1_pull__644->SetLineColor(ci);
   data_obs_pass_prefit_projx1_pull__644->SetLineStyle(0);

   ci = TColor::GetColor("#000000");
   data_obs_pass_prefit_projx1_pull__644->SetMarkerColor(ci);
   data_obs_pass_prefit_projx1_pull__644->SetMarkerStyle(8);
   data_obs_pass_prefit_projx1_pull__644->GetXaxis()->SetTitle("G_{i}^{Strips}");
   data_obs_pass_prefit_projx1_pull__644->GetXaxis()->SetLabelFont(42);
   data_obs_pass_prefit_projx1_pull__644->GetXaxis()->SetLabelOffset(0.05);
   data_obs_pass_prefit_projx1_pull__644->GetXaxis()->SetLabelSize(0.13);
   data_obs_pass_prefit_projx1_pull__644->GetXaxis()->SetTitleSize(0.15);
   data_obs_pass_prefit_projx1_pull__644->GetXaxis()->SetTitleOffset(1.15);
   data_obs_pass_prefit_projx1_pull__644->GetXaxis()->SetTitleFont(42);
   data_obs_pass_prefit_projx1_pull__644->GetYaxis()->SetTitle("(Data-Bkg)/#sigma");
   data_obs_pass_prefit_projx1_pull__644->GetYaxis()->SetNdivisions(306);
   data_obs_pass_prefit_projx1_pull__644->GetYaxis()->SetLabelFont(42);
   data_obs_pass_prefit_projx1_pull__644->GetYaxis()->SetLabelOffset(0.007);
   data_obs_pass_prefit_projx1_pull__644->GetYaxis()->SetLabelSize(0.13);
   data_obs_pass_prefit_projx1_pull__644->GetYaxis()->SetTitleSize(0.12);
   data_obs_pass_prefit_projx1_pull__644->GetYaxis()->SetTitleOffset(0.4);
   data_obs_pass_prefit_projx1_pull__644->GetYaxis()->SetTitleFont(42);
   data_obs_pass_prefit_projx1_pull__644->GetZaxis()->SetLabelFont(42);
   data_obs_pass_prefit_projx1_pull__644->GetZaxis()->SetLabelOffset(0.007);
   data_obs_pass_prefit_projx1_pull__644->GetZaxis()->SetLabelSize(0.05);
   data_obs_pass_prefit_projx1_pull__644->GetZaxis()->SetTitleSize(0.08);
   data_obs_pass_prefit_projx1_pull__644->GetZaxis()->SetTitleFont(42);
   data_obs_pass_prefit_projx1_pull__644->Draw("hist");
   data_obs_pass_prefit_projx1_sub->Modified();
   plots_fit_s/base_figs/prefit_projx1_pass_logy->cd();
   plots_fit_s/base_figs/prefit_projx1_pass_logy->Modified();
   plots_fit_s/base_figs/prefit_projx1_pass_logy->cd();
   plots_fit_s/base_figs/prefit_projx1_pass_logy->SetSelected(plots_fit_s/base_figs/prefit_projx1_pass_logy);
}
