void postfit_projy0_fail()
{
//=========Macro generated from canvas: plots_fit_s/base_figs/postfit_projy0_fail/plots_fit_s/base_figs/postfit_projy0_fail
//=========  (Fri Jan 12 20:33:23 2024) by ROOT version 6.14/09
   TCanvas *plots_fit_s/base_figs/postfit_projy0_fail = new TCanvas("plots_fit_s/base_figs/postfit_projy0_fail", "plots_fit_s/base_figs/postfit_projy0_fail",0,0,800,700);
   gStyle->SetOptFit(1);
   gStyle->SetOptStat(0);
   plots_fit_s/base_figs/postfit_projy0_fail->SetHighLightColor(2);
   plots_fit_s/base_figs/postfit_projy0_fail->Range(0,0,1,1);
   plots_fit_s/base_figs/postfit_projy0_fail->SetFillColor(0);
   plots_fit_s/base_figs/postfit_projy0_fail->SetBorderMode(0);
   plots_fit_s/base_figs/postfit_projy0_fail->SetBorderSize(2);
   plots_fit_s/base_figs/postfit_projy0_fail->SetTickx(1);
   plots_fit_s/base_figs/postfit_projy0_fail->SetTicky(1);
   plots_fit_s/base_figs/postfit_projy0_fail->SetLeftMargin(0.16);
   plots_fit_s/base_figs/postfit_projy0_fail->SetRightMargin(0);
   plots_fit_s/base_figs/postfit_projy0_fail->SetTopMargin(0);
   plots_fit_s/base_figs/postfit_projy0_fail->SetBottomMargin(0);
   plots_fit_s/base_figs/postfit_projy0_fail->SetFrameFillStyle(0);
   plots_fit_s/base_figs/postfit_projy0_fail->SetFrameBorderMode(0);
  
// ------------>Primitives in pad: data_obs_fail_postfit_projy0_main
   TPad *data_obs_fail_postfit_projy0_main = new TPad("data_obs_fail_postfit_projy0_main", "data_obs_fail_postfit_projy0_main",0,0.35,1,1);
   data_obs_fail_postfit_projy0_main->Draw();
   data_obs_fail_postfit_projy0_main->cd();
   data_obs_fail_postfit_projy0_main->Range(-633.6539,-15345.36,4270.192,368288.5);
   data_obs_fail_postfit_projy0_main->SetFillColor(0);
   data_obs_fail_postfit_projy0_main->SetBorderMode(0);
   data_obs_fail_postfit_projy0_main->SetBorderSize(2);
   data_obs_fail_postfit_projy0_main->SetTickx(1);
   data_obs_fail_postfit_projy0_main->SetTicky(1);
   data_obs_fail_postfit_projy0_main->SetLeftMargin(0.17);
   data_obs_fail_postfit_projy0_main->SetRightMargin(0.05);
   data_obs_fail_postfit_projy0_main->SetBottomMargin(0.04);
   data_obs_fail_postfit_projy0_main->SetFrameFillStyle(0);
   data_obs_fail_postfit_projy0_main->SetFrameBorderMode(0);
   data_obs_fail_postfit_projy0_main->SetFrameFillStyle(0);
   data_obs_fail_postfit_projy0_main->SetFrameBorderMode(0);
   Double_t xAxis325[2] = {200, 4025}; 
   
   TH1D *data_obs_fail_postfit_projy0__217 = new TH1D("data_obs_fail_postfit_projy0__217","",1, xAxis325);
   data_obs_fail_postfit_projy0__217->SetBinContent(1,244389);
   data_obs_fail_postfit_projy0__217->SetBinError(1,494.3572);
   data_obs_fail_postfit_projy0__217->SetMinimum(0);
   data_obs_fail_postfit_projy0__217->SetMaximum(329925.2);
   data_obs_fail_postfit_projy0__217->SetEntries(244389);

   Int_t ci;      // for color index setting
   TColor *color; // for color definition with alpha
   ci = TColor::GetColor("#000000");
   data_obs_fail_postfit_projy0__217->SetLineColor(ci);
   data_obs_fail_postfit_projy0__217->SetLineStyle(0);

   ci = TColor::GetColor("#000000");
   data_obs_fail_postfit_projy0__217->SetMarkerColor(ci);
   data_obs_fail_postfit_projy0__217->SetMarkerStyle(8);
   data_obs_fail_postfit_projy0__217->GetXaxis()->SetTitle("p_{T}");
   data_obs_fail_postfit_projy0__217->GetXaxis()->SetLabelFont(42);
   data_obs_fail_postfit_projy0__217->GetXaxis()->SetLabelOffset(0.05);
   data_obs_fail_postfit_projy0__217->GetXaxis()->SetLabelSize(0.07);
   data_obs_fail_postfit_projy0__217->GetXaxis()->SetTitleSize(0.09);
   data_obs_fail_postfit_projy0__217->GetXaxis()->SetTitleOffset(1.15);
   data_obs_fail_postfit_projy0__217->GetXaxis()->SetTitleFont(42);
   data_obs_fail_postfit_projy0__217->GetYaxis()->SetTitle("Events / bin");
   data_obs_fail_postfit_projy0__217->GetYaxis()->SetNdivisions(508);
   data_obs_fail_postfit_projy0__217->GetYaxis()->SetLabelFont(42);
   data_obs_fail_postfit_projy0__217->GetYaxis()->SetLabelOffset(0.007);
   data_obs_fail_postfit_projy0__217->GetYaxis()->SetLabelSize(0.07);
   data_obs_fail_postfit_projy0__217->GetYaxis()->SetTitleSize(0.09);
   data_obs_fail_postfit_projy0__217->GetYaxis()->SetTitleOffset(0.8);
   data_obs_fail_postfit_projy0__217->GetYaxis()->SetTitleFont(42);
   data_obs_fail_postfit_projy0__217->GetZaxis()->SetLabelFont(42);
   data_obs_fail_postfit_projy0__217->GetZaxis()->SetLabelOffset(0.007);
   data_obs_fail_postfit_projy0__217->GetZaxis()->SetLabelSize(0.05);
   data_obs_fail_postfit_projy0__217->GetZaxis()->SetTitleSize(0.08);
   data_obs_fail_postfit_projy0__217->GetZaxis()->SetTitleFont(42);
   data_obs_fail_postfit_projy0__217->Draw("pe X0");
   
   THStack *postfit_projy0_fail_stack = new THStack();
   postfit_projy0_fail_stack->SetName("postfit_projy0_fail_stack");
   postfit_projy0_fail_stack->SetTitle("postfit_projy0_fail_stack");
   Double_t xAxis326[2] = {200, 4025}; 
   
   TH1F *postfit_projy0_fail_stack_stack_55 = new TH1F("postfit_projy0_fail_stack_stack_55","postfit_projy0_fail_stack",1, xAxis326);
   postfit_projy0_fail_stack_stack_55->SetMinimum(0);
   postfit_projy0_fail_stack_stack_55->SetMaximum(257141.4);
   postfit_projy0_fail_stack_stack_55->SetDirectory(0);
   postfit_projy0_fail_stack_stack_55->SetStats(0);
   postfit_projy0_fail_stack_stack_55->SetLineStyle(0);
   postfit_projy0_fail_stack_stack_55->GetXaxis()->SetLabelFont(42);
   postfit_projy0_fail_stack_stack_55->GetXaxis()->SetLabelOffset(0.007);
   postfit_projy0_fail_stack_stack_55->GetXaxis()->SetLabelSize(0.05);
   postfit_projy0_fail_stack_stack_55->GetXaxis()->SetTitleSize(0.08);
   postfit_projy0_fail_stack_stack_55->GetXaxis()->SetTitleOffset(0.9);
   postfit_projy0_fail_stack_stack_55->GetXaxis()->SetTitleFont(42);
   postfit_projy0_fail_stack_stack_55->GetYaxis()->SetNdivisions(508);
   postfit_projy0_fail_stack_stack_55->GetYaxis()->SetLabelFont(42);
   postfit_projy0_fail_stack_stack_55->GetYaxis()->SetLabelOffset(0.007);
   postfit_projy0_fail_stack_stack_55->GetYaxis()->SetLabelSize(0.05);
   postfit_projy0_fail_stack_stack_55->GetYaxis()->SetTitleSize(0.08);
   postfit_projy0_fail_stack_stack_55->GetYaxis()->SetTitleOffset(1.25);
   postfit_projy0_fail_stack_stack_55->GetYaxis()->SetTitleFont(42);
   postfit_projy0_fail_stack_stack_55->GetZaxis()->SetLabelFont(42);
   postfit_projy0_fail_stack_stack_55->GetZaxis()->SetLabelOffset(0.007);
   postfit_projy0_fail_stack_stack_55->GetZaxis()->SetLabelSize(0.05);
   postfit_projy0_fail_stack_stack_55->GetZaxis()->SetTitleSize(0.08);
   postfit_projy0_fail_stack_stack_55->GetZaxis()->SetTitleFont(42);
   postfit_projy0_fail_stack->SetHistogram(postfit_projy0_fail_stack_stack_55);
   
   Double_t xAxis327[2] = {200, 4025}; 
   
   TH1D *Background_fail_postfit_projy0_stack_1 = new TH1D("Background_fail_postfit_projy0_stack_1","Background, fail, postfit, 0.0-0.25",1, xAxis327);
   Background_fail_postfit_projy0_stack_1->SetBinContent(1,244394.3);
   Background_fail_postfit_projy0_stack_1->SetBinError(1,502.3257);
   Background_fail_postfit_projy0_stack_1->SetMinimum(0);
   Background_fail_postfit_projy0_stack_1->SetEntries(236707.1);

   ci = TColor::GetColor("#ffff00");
   Background_fail_postfit_projy0_stack_1->SetFillColor(ci);

   ci = 1332;
   color = new TColor(ci, 1, 1, 1, " ", 0);
   Background_fail_postfit_projy0_stack_1->SetLineColor(ci);
   Background_fail_postfit_projy0_stack_1->SetLineStyle(0);
   Background_fail_postfit_projy0_stack_1->GetXaxis()->SetTitle("p_{T}");
   Background_fail_postfit_projy0_stack_1->GetXaxis()->SetLabelFont(42);
   Background_fail_postfit_projy0_stack_1->GetXaxis()->SetLabelOffset(0.007);
   Background_fail_postfit_projy0_stack_1->GetXaxis()->SetLabelSize(0.05);
   Background_fail_postfit_projy0_stack_1->GetXaxis()->SetTitleSize(0.08);
   Background_fail_postfit_projy0_stack_1->GetXaxis()->SetTitleOffset(1.25);
   Background_fail_postfit_projy0_stack_1->GetXaxis()->SetTitleFont(42);
   Background_fail_postfit_projy0_stack_1->GetYaxis()->SetTitle("Events / bin");
   Background_fail_postfit_projy0_stack_1->GetYaxis()->SetLabelFont(42);
   Background_fail_postfit_projy0_stack_1->GetYaxis()->SetLabelOffset(0.007);
   Background_fail_postfit_projy0_stack_1->GetYaxis()->SetLabelSize(0.05);
   Background_fail_postfit_projy0_stack_1->GetYaxis()->SetTitleSize(0.08);
   Background_fail_postfit_projy0_stack_1->GetYaxis()->SetTitleOffset(1.25);
   Background_fail_postfit_projy0_stack_1->GetYaxis()->SetTitleFont(42);
   Background_fail_postfit_projy0_stack_1->GetZaxis()->SetLabelFont(42);
   Background_fail_postfit_projy0_stack_1->GetZaxis()->SetLabelOffset(0.007);
   Background_fail_postfit_projy0_stack_1->GetZaxis()->SetLabelSize(0.05);
   Background_fail_postfit_projy0_stack_1->GetZaxis()->SetTitleSize(0.08);
   Background_fail_postfit_projy0_stack_1->GetZaxis()->SetTitleFont(42);
   postfit_projy0_fail_stack->Add(Background_fail_postfit_projy0_stack_1,"");
   postfit_projy0_fail_stack->Draw("hist same");
   
   postfit_projy0_fail_stack = new THStack();
   postfit_projy0_fail_stack->SetName("postfit_projy0_fail_stack");
   postfit_projy0_fail_stack->SetTitle("postfit_projy0_fail_stack");
   Double_t xAxis328[2] = {200, 4025}; 
   
   TH1F *postfit_projy0_fail_stack_stack_55_stack_56 = new TH1F("postfit_projy0_fail_stack_stack_55_stack_56","postfit_projy0_fail_stack",1, xAxis328);
   postfit_projy0_fail_stack_stack_55_stack_56->SetMinimum(0);
   postfit_projy0_fail_stack_stack_55_stack_56->SetMaximum(257141.4);
   postfit_projy0_fail_stack_stack_55_stack_56->SetDirectory(0);
   postfit_projy0_fail_stack_stack_55_stack_56->SetStats(0);
   postfit_projy0_fail_stack_stack_55_stack_56->SetLineStyle(0);
   postfit_projy0_fail_stack_stack_55_stack_56->GetXaxis()->SetLabelFont(42);
   postfit_projy0_fail_stack_stack_55_stack_56->GetXaxis()->SetLabelOffset(0.007);
   postfit_projy0_fail_stack_stack_55_stack_56->GetXaxis()->SetLabelSize(0.05);
   postfit_projy0_fail_stack_stack_55_stack_56->GetXaxis()->SetTitleSize(0.08);
   postfit_projy0_fail_stack_stack_55_stack_56->GetXaxis()->SetTitleOffset(0.9);
   postfit_projy0_fail_stack_stack_55_stack_56->GetXaxis()->SetTitleFont(42);
   postfit_projy0_fail_stack_stack_55_stack_56->GetYaxis()->SetNdivisions(508);
   postfit_projy0_fail_stack_stack_55_stack_56->GetYaxis()->SetLabelFont(42);
   postfit_projy0_fail_stack_stack_55_stack_56->GetYaxis()->SetLabelOffset(0.007);
   postfit_projy0_fail_stack_stack_55_stack_56->GetYaxis()->SetLabelSize(0.05);
   postfit_projy0_fail_stack_stack_55_stack_56->GetYaxis()->SetTitleSize(0.08);
   postfit_projy0_fail_stack_stack_55_stack_56->GetYaxis()->SetTitleOffset(1.25);
   postfit_projy0_fail_stack_stack_55_stack_56->GetYaxis()->SetTitleFont(42);
   postfit_projy0_fail_stack_stack_55_stack_56->GetZaxis()->SetLabelFont(42);
   postfit_projy0_fail_stack_stack_55_stack_56->GetZaxis()->SetLabelOffset(0.007);
   postfit_projy0_fail_stack_stack_55_stack_56->GetZaxis()->SetLabelSize(0.05);
   postfit_projy0_fail_stack_stack_55_stack_56->GetZaxis()->SetTitleSize(0.08);
   postfit_projy0_fail_stack_stack_55_stack_56->GetZaxis()->SetTitleFont(42);
   postfit_projy0_fail_stack->SetHistogram(postfit_projy0_fail_stack_stack_55_stack_56);
   
   Double_t xAxis329[2] = {200, 4025}; 
   
   TH1D *Background_fail_postfit_projy0_stack_1_stack_1 = new TH1D("Background_fail_postfit_projy0_stack_1_stack_1","Background, fail, postfit, 0.0-0.25",1, xAxis329);
   Background_fail_postfit_projy0_stack_1_stack_1->SetBinContent(1,244394.3);
   Background_fail_postfit_projy0_stack_1_stack_1->SetBinError(1,502.3257);
   Background_fail_postfit_projy0_stack_1_stack_1->SetMinimum(0);
   Background_fail_postfit_projy0_stack_1_stack_1->SetEntries(236707.1);

   ci = TColor::GetColor("#ffff00");
   Background_fail_postfit_projy0_stack_1_stack_1->SetFillColor(ci);

   ci = 1332;
   color = new TColor(ci, 1, 1, 1, " ", 0);
   Background_fail_postfit_projy0_stack_1_stack_1->SetLineColor(ci);
   Background_fail_postfit_projy0_stack_1_stack_1->SetLineStyle(0);
   Background_fail_postfit_projy0_stack_1_stack_1->GetXaxis()->SetTitle("p_{T}");
   Background_fail_postfit_projy0_stack_1_stack_1->GetXaxis()->SetLabelFont(42);
   Background_fail_postfit_projy0_stack_1_stack_1->GetXaxis()->SetLabelOffset(0.007);
   Background_fail_postfit_projy0_stack_1_stack_1->GetXaxis()->SetLabelSize(0.05);
   Background_fail_postfit_projy0_stack_1_stack_1->GetXaxis()->SetTitleSize(0.08);
   Background_fail_postfit_projy0_stack_1_stack_1->GetXaxis()->SetTitleOffset(1.25);
   Background_fail_postfit_projy0_stack_1_stack_1->GetXaxis()->SetTitleFont(42);
   Background_fail_postfit_projy0_stack_1_stack_1->GetYaxis()->SetTitle("Events / bin");
   Background_fail_postfit_projy0_stack_1_stack_1->GetYaxis()->SetLabelFont(42);
   Background_fail_postfit_projy0_stack_1_stack_1->GetYaxis()->SetLabelOffset(0.007);
   Background_fail_postfit_projy0_stack_1_stack_1->GetYaxis()->SetLabelSize(0.05);
   Background_fail_postfit_projy0_stack_1_stack_1->GetYaxis()->SetTitleSize(0.08);
   Background_fail_postfit_projy0_stack_1_stack_1->GetYaxis()->SetTitleOffset(1.25);
   Background_fail_postfit_projy0_stack_1_stack_1->GetYaxis()->SetTitleFont(42);
   Background_fail_postfit_projy0_stack_1_stack_1->GetZaxis()->SetLabelFont(42);
   Background_fail_postfit_projy0_stack_1_stack_1->GetZaxis()->SetLabelOffset(0.007);
   Background_fail_postfit_projy0_stack_1_stack_1->GetZaxis()->SetLabelSize(0.05);
   Background_fail_postfit_projy0_stack_1_stack_1->GetZaxis()->SetTitleSize(0.08);
   Background_fail_postfit_projy0_stack_1_stack_1->GetZaxis()->SetTitleFont(42);
   postfit_projy0_fail_stack->Add(Background_fail_postfit_projy0_stack_1_stack_1,"");
   postfit_projy0_fail_stack->Draw("hist same");
   Double_t xAxis330[2] = {200, 4025}; 
   
   TH1D *Signal_gluinomI1800_fail_postfit_projy0__218 = new TH1D("Signal_gluinomI1800_fail_postfit_projy0__218","HSCP gluino 1800 GeV, fail, postfit, 0.0-0.25",1, xAxis330);
   Signal_gluinomI1800_fail_postfit_projy0__218->SetBinContent(1,0.01564849);
   Signal_gluinomI1800_fail_postfit_projy0__218->SetBinError(1,0.009295667);
   Signal_gluinomI1800_fail_postfit_projy0__218->SetMinimum(0);
   Signal_gluinomI1800_fail_postfit_projy0__218->SetEntries(2.833894);
   Signal_gluinomI1800_fail_postfit_projy0__218->SetLineColor(4);
   Signal_gluinomI1800_fail_postfit_projy0__218->SetLineStyle(0);
   Signal_gluinomI1800_fail_postfit_projy0__218->SetLineWidth(2);
   Signal_gluinomI1800_fail_postfit_projy0__218->GetXaxis()->SetTitle("p_{T}");
   Signal_gluinomI1800_fail_postfit_projy0__218->GetXaxis()->SetLabelFont(42);
   Signal_gluinomI1800_fail_postfit_projy0__218->GetXaxis()->SetLabelOffset(0.007);
   Signal_gluinomI1800_fail_postfit_projy0__218->GetXaxis()->SetLabelSize(0.05);
   Signal_gluinomI1800_fail_postfit_projy0__218->GetXaxis()->SetTitleSize(0.08);
   Signal_gluinomI1800_fail_postfit_projy0__218->GetXaxis()->SetTitleOffset(1.25);
   Signal_gluinomI1800_fail_postfit_projy0__218->GetXaxis()->SetTitleFont(42);
   Signal_gluinomI1800_fail_postfit_projy0__218->GetYaxis()->SetTitle("Events / bin");
   Signal_gluinomI1800_fail_postfit_projy0__218->GetYaxis()->SetLabelFont(42);
   Signal_gluinomI1800_fail_postfit_projy0__218->GetYaxis()->SetLabelOffset(0.007);
   Signal_gluinomI1800_fail_postfit_projy0__218->GetYaxis()->SetLabelSize(0.05);
   Signal_gluinomI1800_fail_postfit_projy0__218->GetYaxis()->SetTitleSize(0.08);
   Signal_gluinomI1800_fail_postfit_projy0__218->GetYaxis()->SetTitleOffset(1.25);
   Signal_gluinomI1800_fail_postfit_projy0__218->GetYaxis()->SetTitleFont(42);
   Signal_gluinomI1800_fail_postfit_projy0__218->GetZaxis()->SetLabelFont(42);
   Signal_gluinomI1800_fail_postfit_projy0__218->GetZaxis()->SetLabelOffset(0.007);
   Signal_gluinomI1800_fail_postfit_projy0__218->GetZaxis()->SetLabelSize(0.05);
   Signal_gluinomI1800_fail_postfit_projy0__218->GetZaxis()->SetTitleSize(0.08);
   Signal_gluinomI1800_fail_postfit_projy0__218->GetZaxis()->SetTitleFont(42);
   Signal_gluinomI1800_fail_postfit_projy0__218->Draw("hist same");
   Double_t xAxis331[2] = {200, 4025}; 
   
   TH1D *Signal_ppStaumI557_fail_postfit_projy0__219 = new TH1D("Signal_ppStaumI557_fail_postfit_projy0__219","HSCP stau 557 GeV, fail, postfit, 0.0-0.25",1, xAxis331);
   Signal_ppStaumI557_fail_postfit_projy0__219->SetBinContent(1,0.177032);
   Signal_ppStaumI557_fail_postfit_projy0__219->SetBinError(1,0.1110457);
   Signal_ppStaumI557_fail_postfit_projy0__219->SetMinimum(0);
   Signal_ppStaumI557_fail_postfit_projy0__219->SetEntries(2.541556);
   Signal_ppStaumI557_fail_postfit_projy0__219->SetLineColor(2);
   Signal_ppStaumI557_fail_postfit_projy0__219->SetLineStyle(0);
   Signal_ppStaumI557_fail_postfit_projy0__219->SetLineWidth(2);
   Signal_ppStaumI557_fail_postfit_projy0__219->GetXaxis()->SetTitle("p_{T}");
   Signal_ppStaumI557_fail_postfit_projy0__219->GetXaxis()->SetLabelFont(42);
   Signal_ppStaumI557_fail_postfit_projy0__219->GetXaxis()->SetLabelOffset(0.007);
   Signal_ppStaumI557_fail_postfit_projy0__219->GetXaxis()->SetLabelSize(0.05);
   Signal_ppStaumI557_fail_postfit_projy0__219->GetXaxis()->SetTitleSize(0.08);
   Signal_ppStaumI557_fail_postfit_projy0__219->GetXaxis()->SetTitleOffset(1.25);
   Signal_ppStaumI557_fail_postfit_projy0__219->GetXaxis()->SetTitleFont(42);
   Signal_ppStaumI557_fail_postfit_projy0__219->GetYaxis()->SetTitle("Events / bin");
   Signal_ppStaumI557_fail_postfit_projy0__219->GetYaxis()->SetLabelFont(42);
   Signal_ppStaumI557_fail_postfit_projy0__219->GetYaxis()->SetLabelOffset(0.007);
   Signal_ppStaumI557_fail_postfit_projy0__219->GetYaxis()->SetLabelSize(0.05);
   Signal_ppStaumI557_fail_postfit_projy0__219->GetYaxis()->SetTitleSize(0.08);
   Signal_ppStaumI557_fail_postfit_projy0__219->GetYaxis()->SetTitleOffset(1.25);
   Signal_ppStaumI557_fail_postfit_projy0__219->GetYaxis()->SetTitleFont(42);
   Signal_ppStaumI557_fail_postfit_projy0__219->GetZaxis()->SetLabelFont(42);
   Signal_ppStaumI557_fail_postfit_projy0__219->GetZaxis()->SetLabelOffset(0.007);
   Signal_ppStaumI557_fail_postfit_projy0__219->GetZaxis()->SetLabelSize(0.05);
   Signal_ppStaumI557_fail_postfit_projy0__219->GetZaxis()->SetTitleSize(0.08);
   Signal_ppStaumI557_fail_postfit_projy0__219->GetZaxis()->SetTitleFont(42);
   Signal_ppStaumI557_fail_postfit_projy0__219->Draw("hist same");
   Double_t xAxis332[2] = {200, 4025}; 
   
   TH1D *TotalBkg_fail_postfit_projy0__220 = new TH1D("TotalBkg_fail_postfit_projy0__220","TotalBkg, fail, postfit, 0.0-0.25",1, xAxis332);
   TotalBkg_fail_postfit_projy0__220->SetBinContent(1,244394.3);
   TotalBkg_fail_postfit_projy0__220->SetBinError(1,473.8674);
   TotalBkg_fail_postfit_projy0__220->SetMinimum(0);
   TotalBkg_fail_postfit_projy0__220->SetEntries(265991.9);
   TotalBkg_fail_postfit_projy0__220->SetLineStyle(0);
   TotalBkg_fail_postfit_projy0__220->SetMarkerStyle(0);
   TotalBkg_fail_postfit_projy0__220->GetXaxis()->SetTitle("p_{T}");
   TotalBkg_fail_postfit_projy0__220->GetXaxis()->SetLabelFont(42);
   TotalBkg_fail_postfit_projy0__220->GetXaxis()->SetLabelOffset(0.007);
   TotalBkg_fail_postfit_projy0__220->GetXaxis()->SetLabelSize(0.05);
   TotalBkg_fail_postfit_projy0__220->GetXaxis()->SetTitleSize(0.08);
   TotalBkg_fail_postfit_projy0__220->GetXaxis()->SetTitleOffset(1.25);
   TotalBkg_fail_postfit_projy0__220->GetXaxis()->SetTitleFont(42);
   TotalBkg_fail_postfit_projy0__220->GetYaxis()->SetTitle("Events / bin");
   TotalBkg_fail_postfit_projy0__220->GetYaxis()->SetLabelFont(42);
   TotalBkg_fail_postfit_projy0__220->GetYaxis()->SetLabelOffset(0.007);
   TotalBkg_fail_postfit_projy0__220->GetYaxis()->SetLabelSize(0.05);
   TotalBkg_fail_postfit_projy0__220->GetYaxis()->SetTitleSize(0.08);
   TotalBkg_fail_postfit_projy0__220->GetYaxis()->SetTitleOffset(1.25);
   TotalBkg_fail_postfit_projy0__220->GetYaxis()->SetTitleFont(42);
   TotalBkg_fail_postfit_projy0__220->GetZaxis()->SetLabelFont(42);
   TotalBkg_fail_postfit_projy0__220->GetZaxis()->SetLabelOffset(0.007);
   TotalBkg_fail_postfit_projy0__220->GetZaxis()->SetLabelSize(0.05);
   TotalBkg_fail_postfit_projy0__220->GetZaxis()->SetTitleSize(0.08);
   TotalBkg_fail_postfit_projy0__220->GetZaxis()->SetTitleFont(42);
   TotalBkg_fail_postfit_projy0__220->Draw("hist same");
   Double_t xAxis333[2] = {200, 4025}; 
   
   TH1D *TotalBkg_fail_postfit_projy0__221 = new TH1D("TotalBkg_fail_postfit_projy0__221","TotalBkg, fail, postfit, 0.0-0.25",1, xAxis333);
   TotalBkg_fail_postfit_projy0__221->SetBinContent(1,244394.3);
   TotalBkg_fail_postfit_projy0__221->SetBinError(1,473.8674);
   TotalBkg_fail_postfit_projy0__221->SetMinimum(0);
   TotalBkg_fail_postfit_projy0__221->SetEntries(265991.9);
   TotalBkg_fail_postfit_projy0__221->SetFillColor(1);
   TotalBkg_fail_postfit_projy0__221->SetFillStyle(3354);
   TotalBkg_fail_postfit_projy0__221->SetLineStyle(0);
   TotalBkg_fail_postfit_projy0__221->SetLineWidth(0);
   TotalBkg_fail_postfit_projy0__221->SetMarkerStyle(0);
   TotalBkg_fail_postfit_projy0__221->GetXaxis()->SetTitle("p_{T}");
   TotalBkg_fail_postfit_projy0__221->GetXaxis()->SetLabelFont(42);
   TotalBkg_fail_postfit_projy0__221->GetXaxis()->SetLabelOffset(0.007);
   TotalBkg_fail_postfit_projy0__221->GetXaxis()->SetLabelSize(0.05);
   TotalBkg_fail_postfit_projy0__221->GetXaxis()->SetTitleSize(0.08);
   TotalBkg_fail_postfit_projy0__221->GetXaxis()->SetTitleOffset(1.25);
   TotalBkg_fail_postfit_projy0__221->GetXaxis()->SetTitleFont(42);
   TotalBkg_fail_postfit_projy0__221->GetYaxis()->SetTitle("Events / bin");
   TotalBkg_fail_postfit_projy0__221->GetYaxis()->SetLabelFont(42);
   TotalBkg_fail_postfit_projy0__221->GetYaxis()->SetLabelOffset(0.007);
   TotalBkg_fail_postfit_projy0__221->GetYaxis()->SetLabelSize(0.05);
   TotalBkg_fail_postfit_projy0__221->GetYaxis()->SetTitleSize(0.08);
   TotalBkg_fail_postfit_projy0__221->GetYaxis()->SetTitleOffset(1.25);
   TotalBkg_fail_postfit_projy0__221->GetYaxis()->SetTitleFont(42);
   TotalBkg_fail_postfit_projy0__221->GetZaxis()->SetLabelFont(42);
   TotalBkg_fail_postfit_projy0__221->GetZaxis()->SetLabelOffset(0.007);
   TotalBkg_fail_postfit_projy0__221->GetZaxis()->SetLabelSize(0.05);
   TotalBkg_fail_postfit_projy0__221->GetZaxis()->SetTitleSize(0.08);
   TotalBkg_fail_postfit_projy0__221->GetZaxis()->SetTitleFont(42);
   TotalBkg_fail_postfit_projy0__221->Draw("e2 same");
   Double_t xAxis334[2] = {200, 4025}; 
   
   TH1D *data_obs_fail_postfit_projy0__222 = new TH1D("data_obs_fail_postfit_projy0__222","",1, xAxis334);
   data_obs_fail_postfit_projy0__222->SetBinContent(1,244389);
   data_obs_fail_postfit_projy0__222->SetBinError(1,494.3572);
   data_obs_fail_postfit_projy0__222->SetMinimum(0);
   data_obs_fail_postfit_projy0__222->SetMaximum(329925.2);
   data_obs_fail_postfit_projy0__222->SetEntries(244389);

   ci = TColor::GetColor("#000000");
   data_obs_fail_postfit_projy0__222->SetLineColor(ci);
   data_obs_fail_postfit_projy0__222->SetLineStyle(0);

   ci = TColor::GetColor("#000000");
   data_obs_fail_postfit_projy0__222->SetMarkerColor(ci);
   data_obs_fail_postfit_projy0__222->SetMarkerStyle(8);
   data_obs_fail_postfit_projy0__222->GetXaxis()->SetTitle("p_{T}");
   data_obs_fail_postfit_projy0__222->GetXaxis()->SetLabelFont(42);
   data_obs_fail_postfit_projy0__222->GetXaxis()->SetLabelOffset(0.05);
   data_obs_fail_postfit_projy0__222->GetXaxis()->SetLabelSize(0.07);
   data_obs_fail_postfit_projy0__222->GetXaxis()->SetTitleSize(0.09);
   data_obs_fail_postfit_projy0__222->GetXaxis()->SetTitleOffset(1.15);
   data_obs_fail_postfit_projy0__222->GetXaxis()->SetTitleFont(42);
   data_obs_fail_postfit_projy0__222->GetYaxis()->SetTitle("Events / bin");
   data_obs_fail_postfit_projy0__222->GetYaxis()->SetNdivisions(508);
   data_obs_fail_postfit_projy0__222->GetYaxis()->SetLabelFont(42);
   data_obs_fail_postfit_projy0__222->GetYaxis()->SetLabelOffset(0.007);
   data_obs_fail_postfit_projy0__222->GetYaxis()->SetLabelSize(0.07);
   data_obs_fail_postfit_projy0__222->GetYaxis()->SetTitleSize(0.09);
   data_obs_fail_postfit_projy0__222->GetYaxis()->SetTitleOffset(0.8);
   data_obs_fail_postfit_projy0__222->GetYaxis()->SetTitleFont(42);
   data_obs_fail_postfit_projy0__222->GetZaxis()->SetLabelFont(42);
   data_obs_fail_postfit_projy0__222->GetZaxis()->SetLabelOffset(0.007);
   data_obs_fail_postfit_projy0__222->GetZaxis()->SetLabelSize(0.05);
   data_obs_fail_postfit_projy0__222->GetZaxis()->SetTitleSize(0.08);
   data_obs_fail_postfit_projy0__222->GetZaxis()->SetTitleFont(42);
   data_obs_fail_postfit_projy0__222->Draw("pe X0 same");
   
   TLegend *leg = new TLegend(0.65,0.61,0.9,0.88,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(1001);
   TLegendEntry *entry=leg->AddEntry("data_obs_fail_postfit_projy0","Data","pe X0");

   ci = TColor::GetColor("#000000");
   entry->SetLineColor(ci);
   entry->SetLineWidth(1);

   ci = TColor::GetColor("#000000");
   entry->SetMarkerColor(ci);
   entry->SetMarkerStyle(8);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("TotalBkg_fail_postfit_projy0","Total bkg unc.","F");
   entry->SetFillColor(1);
   entry->SetFillStyle(3354);
   entry->SetLineColor(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("Signal_gluino-1800_fail_postfit_projy0","HSCP gluino 1800 GeV","L");
   entry->SetLineColor(4);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("Signal_ppStau-557_fail_postfit_projy0","HSCP stau 557 GeV","L");
   entry->SetLineColor(2);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("Background_fail_postfit_projy0_stack_1_stack_1","Background","f");

   ci = TColor::GetColor("#ffff00");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = 1332;
   color = new TColor(ci, 1, 1, 1, " ", 0);
   entry->SetLineColor(ci);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   leg->Draw();
   Double_t xAxis335[2] = {200, 4025}; 
   
   TH1D *data_obs_fail_postfit_projy0_copy__223 = new TH1D("data_obs_fail_postfit_projy0_copy__223","",1, xAxis335);
   data_obs_fail_postfit_projy0_copy__223->SetBinContent(1,244389);
   data_obs_fail_postfit_projy0_copy__223->SetBinError(1,494.3572);
   data_obs_fail_postfit_projy0_copy__223->SetMinimum(0);
   data_obs_fail_postfit_projy0_copy__223->SetMaximum(329925.2);
   data_obs_fail_postfit_projy0_copy__223->SetEntries(244389);
   data_obs_fail_postfit_projy0_copy__223->SetDirectory(0);

   ci = TColor::GetColor("#000000");
   data_obs_fail_postfit_projy0_copy__223->SetLineColor(ci);
   data_obs_fail_postfit_projy0_copy__223->SetLineStyle(0);

   ci = TColor::GetColor("#000000");
   data_obs_fail_postfit_projy0_copy__223->SetMarkerColor(ci);
   data_obs_fail_postfit_projy0_copy__223->SetMarkerStyle(8);
   data_obs_fail_postfit_projy0_copy__223->GetXaxis()->SetTitle("p_{T}");
   data_obs_fail_postfit_projy0_copy__223->GetXaxis()->SetLabelFont(42);
   data_obs_fail_postfit_projy0_copy__223->GetXaxis()->SetLabelOffset(0.05);
   data_obs_fail_postfit_projy0_copy__223->GetXaxis()->SetLabelSize(0.07);
   data_obs_fail_postfit_projy0_copy__223->GetXaxis()->SetTitleSize(0.09);
   data_obs_fail_postfit_projy0_copy__223->GetXaxis()->SetTitleOffset(1.15);
   data_obs_fail_postfit_projy0_copy__223->GetXaxis()->SetTitleFont(42);
   data_obs_fail_postfit_projy0_copy__223->GetYaxis()->SetTitle("Events / bin");
   data_obs_fail_postfit_projy0_copy__223->GetYaxis()->SetNdivisions(508);
   data_obs_fail_postfit_projy0_copy__223->GetYaxis()->SetLabelFont(42);
   data_obs_fail_postfit_projy0_copy__223->GetYaxis()->SetLabelOffset(0.007);
   data_obs_fail_postfit_projy0_copy__223->GetYaxis()->SetLabelSize(0.07);
   data_obs_fail_postfit_projy0_copy__223->GetYaxis()->SetTitleSize(0.09);
   data_obs_fail_postfit_projy0_copy__223->GetYaxis()->SetTitleOffset(0.8);
   data_obs_fail_postfit_projy0_copy__223->GetYaxis()->SetTitleFont(42);
   data_obs_fail_postfit_projy0_copy__223->GetZaxis()->SetLabelFont(42);
   data_obs_fail_postfit_projy0_copy__223->GetZaxis()->SetLabelOffset(0.007);
   data_obs_fail_postfit_projy0_copy__223->GetZaxis()->SetLabelSize(0.05);
   data_obs_fail_postfit_projy0_copy__223->GetZaxis()->SetTitleSize(0.08);
   data_obs_fail_postfit_projy0_copy__223->GetZaxis()->SetTitleFont(42);
   data_obs_fail_postfit_projy0_copy__223->Draw("sameaxis");
   TLatex *   tex = new TLatex(0.21,0.83,"0.0 < G_{i}^{Strips} < 0.25 , F^{Pixels}_{i} < 0.9");
tex->SetNDC();
   tex->SetTextAlign(12);
   tex->SetTextFont(42);
   tex->SetTextSize(0.06);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.17,0.92,"CMS");
tex->SetNDC();
   tex->SetTextFont(61);
   tex->SetTextSize(0.0675);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.25,0.92,"Preliminary");
tex->SetNDC();
   tex->SetTextFont(52);
   tex->SetTextSize(0.0485);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.95,0.92,"101 fb^{-1} (13 TeV)");
tex->SetNDC();
   tex->SetTextAlign(31);
   tex->SetTextFont(42);
   tex->SetTextSize(0.07);
   tex->SetLineWidth(2);
   tex->Draw();
   data_obs_fail_postfit_projy0_main->Modified();
   plots_fit_s/base_figs/postfit_projy0_fail->cd();
  
// ------------>Primitives in pad: data_obs_fail_postfit_projy0_sub
   TPad *data_obs_fail_postfit_projy0_sub = new TPad("data_obs_fail_postfit_projy0_sub", "data_obs_fail_postfit_projy0_sub",0,0,1,0.35);
   data_obs_fail_postfit_projy0_sub->Draw();
   data_obs_fail_postfit_projy0_sub->cd();
   data_obs_fail_postfit_projy0_sub->Range(-633.6539,-6.023077,4270.192,2.9);
   data_obs_fail_postfit_projy0_sub->SetFillColor(0);
   data_obs_fail_postfit_projy0_sub->SetBorderMode(0);
   data_obs_fail_postfit_projy0_sub->SetBorderSize(2);
   data_obs_fail_postfit_projy0_sub->SetTickx(1);
   data_obs_fail_postfit_projy0_sub->SetTicky(1);
   data_obs_fail_postfit_projy0_sub->SetLeftMargin(0.17);
   data_obs_fail_postfit_projy0_sub->SetRightMargin(0.05);
   data_obs_fail_postfit_projy0_sub->SetTopMargin(0);
   data_obs_fail_postfit_projy0_sub->SetBottomMargin(0.35);
   data_obs_fail_postfit_projy0_sub->SetFrameFillStyle(0);
   data_obs_fail_postfit_projy0_sub->SetFrameBorderMode(0);
   data_obs_fail_postfit_projy0_sub->SetFrameFillStyle(0);
   data_obs_fail_postfit_projy0_sub->SetFrameBorderMode(0);
   Double_t xAxis336[2] = {200, 4025}; 
   
   TH1D *data_obs_fail_postfit_projy0_pull__224 = new TH1D("data_obs_fail_postfit_projy0_pull__224","",1, xAxis336);
   data_obs_fail_postfit_projy0_pull__224->SetBinContent(1,-0.007692051);
   data_obs_fail_postfit_projy0_pull__224->SetBinError(1,684.7914);
   data_obs_fail_postfit_projy0_pull__224->SetMinimum(-2.9);
   data_obs_fail_postfit_projy0_pull__224->SetMaximum(2.9);
   data_obs_fail_postfit_projy0_pull__224->SetEntries(6.27301);
   data_obs_fail_postfit_projy0_pull__224->SetStats(0);

   ci = TColor::GetColor("#0000ff");
   data_obs_fail_postfit_projy0_pull__224->SetFillColor(ci);

   ci = TColor::GetColor("#000000");
   data_obs_fail_postfit_projy0_pull__224->SetLineColor(ci);
   data_obs_fail_postfit_projy0_pull__224->SetLineStyle(0);

   ci = TColor::GetColor("#000000");
   data_obs_fail_postfit_projy0_pull__224->SetMarkerColor(ci);
   data_obs_fail_postfit_projy0_pull__224->SetMarkerStyle(8);
   data_obs_fail_postfit_projy0_pull__224->GetXaxis()->SetTitle("p_{T}");
   data_obs_fail_postfit_projy0_pull__224->GetXaxis()->SetLabelFont(42);
   data_obs_fail_postfit_projy0_pull__224->GetXaxis()->SetLabelOffset(0.05);
   data_obs_fail_postfit_projy0_pull__224->GetXaxis()->SetLabelSize(0.13);
   data_obs_fail_postfit_projy0_pull__224->GetXaxis()->SetTitleSize(0.15);
   data_obs_fail_postfit_projy0_pull__224->GetXaxis()->SetTitleOffset(1.15);
   data_obs_fail_postfit_projy0_pull__224->GetXaxis()->SetTitleFont(42);
   data_obs_fail_postfit_projy0_pull__224->GetYaxis()->SetTitle("(Data-Bkg)/#sigma");
   data_obs_fail_postfit_projy0_pull__224->GetYaxis()->SetNdivisions(306);
   data_obs_fail_postfit_projy0_pull__224->GetYaxis()->SetLabelFont(42);
   data_obs_fail_postfit_projy0_pull__224->GetYaxis()->SetLabelOffset(0.007);
   data_obs_fail_postfit_projy0_pull__224->GetYaxis()->SetLabelSize(0.13);
   data_obs_fail_postfit_projy0_pull__224->GetYaxis()->SetTitleSize(0.12);
   data_obs_fail_postfit_projy0_pull__224->GetYaxis()->SetTitleOffset(0.4);
   data_obs_fail_postfit_projy0_pull__224->GetYaxis()->SetTitleFont(42);
   data_obs_fail_postfit_projy0_pull__224->GetZaxis()->SetLabelFont(42);
   data_obs_fail_postfit_projy0_pull__224->GetZaxis()->SetLabelOffset(0.007);
   data_obs_fail_postfit_projy0_pull__224->GetZaxis()->SetLabelSize(0.05);
   data_obs_fail_postfit_projy0_pull__224->GetZaxis()->SetTitleSize(0.08);
   data_obs_fail_postfit_projy0_pull__224->GetZaxis()->SetTitleFont(42);
   data_obs_fail_postfit_projy0_pull__224->Draw("hist");
   data_obs_fail_postfit_projy0_sub->Modified();
   plots_fit_s/base_figs/postfit_projy0_fail->cd();
   plots_fit_s/base_figs/postfit_projy0_fail->Modified();
   plots_fit_s/base_figs/postfit_projy0_fail->cd();
   plots_fit_s/base_figs/postfit_projy0_fail->SetSelected(plots_fit_s/base_figs/postfit_projy0_fail);
}
