void postfit_projx0_pass()
{
//=========Macro generated from canvas: plots_fit_s/base_figs/postfit_projx0_pass/plots_fit_s/base_figs/postfit_projx0_pass
//=========  (Fri Jan 12 20:33:23 2024) by ROOT version 6.14/09
   TCanvas *plots_fit_s/base_figs/postfit_projx0_pass = new TCanvas("plots_fit_s/base_figs/postfit_projx0_pass", "plots_fit_s/base_figs/postfit_projx0_pass",0,0,800,700);
   gStyle->SetOptFit(1);
   gStyle->SetOptStat(0);
   plots_fit_s/base_figs/postfit_projx0_pass->SetHighLightColor(2);
   plots_fit_s/base_figs/postfit_projx0_pass->Range(0,0,1,1);
   plots_fit_s/base_figs/postfit_projx0_pass->SetFillColor(0);
   plots_fit_s/base_figs/postfit_projx0_pass->SetBorderMode(0);
   plots_fit_s/base_figs/postfit_projx0_pass->SetBorderSize(2);
   plots_fit_s/base_figs/postfit_projx0_pass->SetTickx(1);
   plots_fit_s/base_figs/postfit_projx0_pass->SetTicky(1);
   plots_fit_s/base_figs/postfit_projx0_pass->SetLeftMargin(0.16);
   plots_fit_s/base_figs/postfit_projx0_pass->SetRightMargin(0);
   plots_fit_s/base_figs/postfit_projx0_pass->SetTopMargin(0);
   plots_fit_s/base_figs/postfit_projx0_pass->SetBottomMargin(0);
   plots_fit_s/base_figs/postfit_projx0_pass->SetFrameFillStyle(0);
   plots_fit_s/base_figs/postfit_projx0_pass->SetFrameBorderMode(0);
  
// ------------>Primitives in pad: data_obs_pass_postfit_projx0_main
   TPad *data_obs_pass_postfit_projx0_main = new TPad("data_obs_pass_postfit_projx0_main", "data_obs_pass_postfit_projx0_main",0,0.35,1,1);
   data_obs_pass_postfit_projx0_main->Draw();
   data_obs_pass_postfit_projx0_main->cd();
   data_obs_pass_postfit_projx0_main->Range(-0.2179487,-0.04651163,1.064103,1.116279);
   data_obs_pass_postfit_projx0_main->SetFillColor(0);
   data_obs_pass_postfit_projx0_main->SetBorderMode(0);
   data_obs_pass_postfit_projx0_main->SetBorderSize(2);
   data_obs_pass_postfit_projx0_main->SetTickx(1);
   data_obs_pass_postfit_projx0_main->SetTicky(1);
   data_obs_pass_postfit_projx0_main->SetLeftMargin(0.17);
   data_obs_pass_postfit_projx0_main->SetRightMargin(0.05);
   data_obs_pass_postfit_projx0_main->SetBottomMargin(0.04);
   data_obs_pass_postfit_projx0_main->SetFrameFillStyle(0);
   data_obs_pass_postfit_projx0_main->SetFrameBorderMode(0);
   data_obs_pass_postfit_projx0_main->SetFrameFillStyle(0);
   data_obs_pass_postfit_projx0_main->SetFrameBorderMode(0);
   Double_t xAxis433[10] = {0, 0.05, 0.1, 0.15, 0.2, 0.25, 0.3, 0.35, 0.4, 1}; 
   
   TH1D *data_obs_pass_postfit_projx0__289 = new TH1D("data_obs_pass_postfit_projx0__289","",9, xAxis433);
   data_obs_pass_postfit_projx0__289->SetMinimum(0);
   data_obs_pass_postfit_projx0__289->SetMaximum(0);

   Int_t ci;      // for color index setting
   TColor *color; // for color definition with alpha
   ci = TColor::GetColor("#000000");
   data_obs_pass_postfit_projx0__289->SetLineColor(ci);
   data_obs_pass_postfit_projx0__289->SetLineStyle(0);

   ci = TColor::GetColor("#000000");
   data_obs_pass_postfit_projx0__289->SetMarkerColor(ci);
   data_obs_pass_postfit_projx0__289->SetMarkerStyle(8);
   data_obs_pass_postfit_projx0__289->GetXaxis()->SetTitle("G_{i}^{Strips}");
   data_obs_pass_postfit_projx0__289->GetXaxis()->SetLabelFont(42);
   data_obs_pass_postfit_projx0__289->GetXaxis()->SetLabelOffset(0.05);
   data_obs_pass_postfit_projx0__289->GetXaxis()->SetLabelSize(0.07);
   data_obs_pass_postfit_projx0__289->GetXaxis()->SetTitleSize(0.09);
   data_obs_pass_postfit_projx0__289->GetXaxis()->SetTitleOffset(1.15);
   data_obs_pass_postfit_projx0__289->GetXaxis()->SetTitleFont(42);
   data_obs_pass_postfit_projx0__289->GetYaxis()->SetTitle("Events / bin");
   data_obs_pass_postfit_projx0__289->GetYaxis()->SetNdivisions(508);
   data_obs_pass_postfit_projx0__289->GetYaxis()->SetLabelFont(42);
   data_obs_pass_postfit_projx0__289->GetYaxis()->SetLabelOffset(0.007);
   data_obs_pass_postfit_projx0__289->GetYaxis()->SetLabelSize(0.07);
   data_obs_pass_postfit_projx0__289->GetYaxis()->SetTitleSize(0.09);
   data_obs_pass_postfit_projx0__289->GetYaxis()->SetTitleOffset(0.8);
   data_obs_pass_postfit_projx0__289->GetYaxis()->SetTitleFont(42);
   data_obs_pass_postfit_projx0__289->GetZaxis()->SetLabelFont(42);
   data_obs_pass_postfit_projx0__289->GetZaxis()->SetLabelOffset(0.007);
   data_obs_pass_postfit_projx0__289->GetZaxis()->SetLabelSize(0.05);
   data_obs_pass_postfit_projx0__289->GetZaxis()->SetTitleSize(0.08);
   data_obs_pass_postfit_projx0__289->GetZaxis()->SetTitleFont(42);
   data_obs_pass_postfit_projx0__289->Draw("pe X0");
   
   THStack *postfit_projx0_pass_stack = new THStack();
   postfit_projx0_pass_stack->SetName("postfit_projx0_pass_stack");
   postfit_projx0_pass_stack->SetTitle("postfit_projx0_pass_stack");
   Double_t xAxis434[10] = {0, 0.05, 0.1, 0.15, 0.2, 0.25, 0.3, 0.35, 0.4, 1}; 
   
   TH1F *postfit_projx0_pass_stack_stack_73 = new TH1F("postfit_projx0_pass_stack_stack_73","postfit_projx0_pass_stack",9, xAxis434);
   postfit_projx0_pass_stack_stack_73->SetMinimum(0);
   postfit_projx0_pass_stack_stack_73->SetMaximum(0);
   postfit_projx0_pass_stack_stack_73->SetDirectory(0);
   postfit_projx0_pass_stack_stack_73->SetStats(0);
   postfit_projx0_pass_stack_stack_73->SetLineStyle(0);
   postfit_projx0_pass_stack_stack_73->GetXaxis()->SetLabelFont(42);
   postfit_projx0_pass_stack_stack_73->GetXaxis()->SetLabelOffset(0.007);
   postfit_projx0_pass_stack_stack_73->GetXaxis()->SetLabelSize(0.05);
   postfit_projx0_pass_stack_stack_73->GetXaxis()->SetTitleSize(0.08);
   postfit_projx0_pass_stack_stack_73->GetXaxis()->SetTitleOffset(0.9);
   postfit_projx0_pass_stack_stack_73->GetXaxis()->SetTitleFont(42);
   postfit_projx0_pass_stack_stack_73->GetYaxis()->SetNdivisions(508);
   postfit_projx0_pass_stack_stack_73->GetYaxis()->SetLabelFont(42);
   postfit_projx0_pass_stack_stack_73->GetYaxis()->SetLabelOffset(0.007);
   postfit_projx0_pass_stack_stack_73->GetYaxis()->SetLabelSize(0.05);
   postfit_projx0_pass_stack_stack_73->GetYaxis()->SetTitleSize(0.08);
   postfit_projx0_pass_stack_stack_73->GetYaxis()->SetTitleOffset(1.25);
   postfit_projx0_pass_stack_stack_73->GetYaxis()->SetTitleFont(42);
   postfit_projx0_pass_stack_stack_73->GetZaxis()->SetLabelFont(42);
   postfit_projx0_pass_stack_stack_73->GetZaxis()->SetLabelOffset(0.007);
   postfit_projx0_pass_stack_stack_73->GetZaxis()->SetLabelSize(0.05);
   postfit_projx0_pass_stack_stack_73->GetZaxis()->SetTitleSize(0.08);
   postfit_projx0_pass_stack_stack_73->GetZaxis()->SetTitleFont(42);
   postfit_projx0_pass_stack->SetHistogram(postfit_projx0_pass_stack_stack_73);
   
   Double_t xAxis435[10] = {0, 0.05, 0.1, 0.15, 0.2, 0.25, 0.3, 0.35, 0.4, 1}; 
   
   TH1D *Background_0x0_pass_postfit_projx0_stack_1 = new TH1D("Background_0x0_pass_postfit_projx0_stack_1","Background, pass, postfit, 200-200",9, xAxis435);
   Background_0x0_pass_postfit_projx0_stack_1->SetMinimum(0);

   ci = TColor::GetColor("#ffff00");
   Background_0x0_pass_postfit_projx0_stack_1->SetFillColor(ci);

   ci = 1341;
   color = new TColor(ci, 1, 1, 1, " ", 0);
   Background_0x0_pass_postfit_projx0_stack_1->SetLineColor(ci);
   Background_0x0_pass_postfit_projx0_stack_1->SetLineStyle(0);
   Background_0x0_pass_postfit_projx0_stack_1->GetXaxis()->SetTitle("G_{i}^{Strips}");
   Background_0x0_pass_postfit_projx0_stack_1->GetXaxis()->SetLabelFont(42);
   Background_0x0_pass_postfit_projx0_stack_1->GetXaxis()->SetLabelOffset(0.007);
   Background_0x0_pass_postfit_projx0_stack_1->GetXaxis()->SetLabelSize(0.05);
   Background_0x0_pass_postfit_projx0_stack_1->GetXaxis()->SetTitleSize(0.08);
   Background_0x0_pass_postfit_projx0_stack_1->GetXaxis()->SetTitleOffset(0.9);
   Background_0x0_pass_postfit_projx0_stack_1->GetXaxis()->SetTitleFont(42);
   Background_0x0_pass_postfit_projx0_stack_1->GetYaxis()->SetTitle("Events / bin");
   Background_0x0_pass_postfit_projx0_stack_1->GetYaxis()->SetLabelFont(42);
   Background_0x0_pass_postfit_projx0_stack_1->GetYaxis()->SetLabelOffset(0.007);
   Background_0x0_pass_postfit_projx0_stack_1->GetYaxis()->SetLabelSize(0.05);
   Background_0x0_pass_postfit_projx0_stack_1->GetYaxis()->SetTitleSize(0.08);
   Background_0x0_pass_postfit_projx0_stack_1->GetYaxis()->SetTitleOffset(1.25);
   Background_0x0_pass_postfit_projx0_stack_1->GetYaxis()->SetTitleFont(42);
   Background_0x0_pass_postfit_projx0_stack_1->GetZaxis()->SetLabelFont(42);
   Background_0x0_pass_postfit_projx0_stack_1->GetZaxis()->SetLabelOffset(0.007);
   Background_0x0_pass_postfit_projx0_stack_1->GetZaxis()->SetLabelSize(0.05);
   Background_0x0_pass_postfit_projx0_stack_1->GetZaxis()->SetTitleSize(0.08);
   Background_0x0_pass_postfit_projx0_stack_1->GetZaxis()->SetTitleFont(42);
   postfit_projx0_pass_stack->Add(Background_0x0_pass_postfit_projx0_stack_1,"");
   postfit_projx0_pass_stack->Draw("hist same");
   
   postfit_projx0_pass_stack = new THStack();
   postfit_projx0_pass_stack->SetName("postfit_projx0_pass_stack");
   postfit_projx0_pass_stack->SetTitle("postfit_projx0_pass_stack");
   Double_t xAxis436[10] = {0, 0.05, 0.1, 0.15, 0.2, 0.25, 0.3, 0.35, 0.4, 1}; 
   
   TH1F *postfit_projx0_pass_stack_stack_73_stack_74 = new TH1F("postfit_projx0_pass_stack_stack_73_stack_74","postfit_projx0_pass_stack",9, xAxis436);
   postfit_projx0_pass_stack_stack_73_stack_74->SetMinimum(0);
   postfit_projx0_pass_stack_stack_73_stack_74->SetMaximum(0);
   postfit_projx0_pass_stack_stack_73_stack_74->SetDirectory(0);
   postfit_projx0_pass_stack_stack_73_stack_74->SetStats(0);
   postfit_projx0_pass_stack_stack_73_stack_74->SetLineStyle(0);
   postfit_projx0_pass_stack_stack_73_stack_74->GetXaxis()->SetLabelFont(42);
   postfit_projx0_pass_stack_stack_73_stack_74->GetXaxis()->SetLabelOffset(0.007);
   postfit_projx0_pass_stack_stack_73_stack_74->GetXaxis()->SetLabelSize(0.05);
   postfit_projx0_pass_stack_stack_73_stack_74->GetXaxis()->SetTitleSize(0.08);
   postfit_projx0_pass_stack_stack_73_stack_74->GetXaxis()->SetTitleOffset(0.9);
   postfit_projx0_pass_stack_stack_73_stack_74->GetXaxis()->SetTitleFont(42);
   postfit_projx0_pass_stack_stack_73_stack_74->GetYaxis()->SetNdivisions(508);
   postfit_projx0_pass_stack_stack_73_stack_74->GetYaxis()->SetLabelFont(42);
   postfit_projx0_pass_stack_stack_73_stack_74->GetYaxis()->SetLabelOffset(0.007);
   postfit_projx0_pass_stack_stack_73_stack_74->GetYaxis()->SetLabelSize(0.05);
   postfit_projx0_pass_stack_stack_73_stack_74->GetYaxis()->SetTitleSize(0.08);
   postfit_projx0_pass_stack_stack_73_stack_74->GetYaxis()->SetTitleOffset(1.25);
   postfit_projx0_pass_stack_stack_73_stack_74->GetYaxis()->SetTitleFont(42);
   postfit_projx0_pass_stack_stack_73_stack_74->GetZaxis()->SetLabelFont(42);
   postfit_projx0_pass_stack_stack_73_stack_74->GetZaxis()->SetLabelOffset(0.007);
   postfit_projx0_pass_stack_stack_73_stack_74->GetZaxis()->SetLabelSize(0.05);
   postfit_projx0_pass_stack_stack_73_stack_74->GetZaxis()->SetTitleSize(0.08);
   postfit_projx0_pass_stack_stack_73_stack_74->GetZaxis()->SetTitleFont(42);
   postfit_projx0_pass_stack->SetHistogram(postfit_projx0_pass_stack_stack_73_stack_74);
   
   Double_t xAxis437[10] = {0, 0.05, 0.1, 0.15, 0.2, 0.25, 0.3, 0.35, 0.4, 1}; 
   
   TH1D *Background_0x0_pass_postfit_projx0_stack_1_stack_1 = new TH1D("Background_0x0_pass_postfit_projx0_stack_1_stack_1","Background, pass, postfit, 200-200",9, xAxis437);
   Background_0x0_pass_postfit_projx0_stack_1_stack_1->SetMinimum(0);

   ci = TColor::GetColor("#ffff00");
   Background_0x0_pass_postfit_projx0_stack_1_stack_1->SetFillColor(ci);

   ci = 1341;
   color = new TColor(ci, 1, 1, 1, " ", 0);
   Background_0x0_pass_postfit_projx0_stack_1_stack_1->SetLineColor(ci);
   Background_0x0_pass_postfit_projx0_stack_1_stack_1->SetLineStyle(0);
   Background_0x0_pass_postfit_projx0_stack_1_stack_1->GetXaxis()->SetTitle("G_{i}^{Strips}");
   Background_0x0_pass_postfit_projx0_stack_1_stack_1->GetXaxis()->SetLabelFont(42);
   Background_0x0_pass_postfit_projx0_stack_1_stack_1->GetXaxis()->SetLabelOffset(0.007);
   Background_0x0_pass_postfit_projx0_stack_1_stack_1->GetXaxis()->SetLabelSize(0.05);
   Background_0x0_pass_postfit_projx0_stack_1_stack_1->GetXaxis()->SetTitleSize(0.08);
   Background_0x0_pass_postfit_projx0_stack_1_stack_1->GetXaxis()->SetTitleOffset(0.9);
   Background_0x0_pass_postfit_projx0_stack_1_stack_1->GetXaxis()->SetTitleFont(42);
   Background_0x0_pass_postfit_projx0_stack_1_stack_1->GetYaxis()->SetTitle("Events / bin");
   Background_0x0_pass_postfit_projx0_stack_1_stack_1->GetYaxis()->SetLabelFont(42);
   Background_0x0_pass_postfit_projx0_stack_1_stack_1->GetYaxis()->SetLabelOffset(0.007);
   Background_0x0_pass_postfit_projx0_stack_1_stack_1->GetYaxis()->SetLabelSize(0.05);
   Background_0x0_pass_postfit_projx0_stack_1_stack_1->GetYaxis()->SetTitleSize(0.08);
   Background_0x0_pass_postfit_projx0_stack_1_stack_1->GetYaxis()->SetTitleOffset(1.25);
   Background_0x0_pass_postfit_projx0_stack_1_stack_1->GetYaxis()->SetTitleFont(42);
   Background_0x0_pass_postfit_projx0_stack_1_stack_1->GetZaxis()->SetLabelFont(42);
   Background_0x0_pass_postfit_projx0_stack_1_stack_1->GetZaxis()->SetLabelOffset(0.007);
   Background_0x0_pass_postfit_projx0_stack_1_stack_1->GetZaxis()->SetLabelSize(0.05);
   Background_0x0_pass_postfit_projx0_stack_1_stack_1->GetZaxis()->SetTitleSize(0.08);
   Background_0x0_pass_postfit_projx0_stack_1_stack_1->GetZaxis()->SetTitleFont(42);
   postfit_projx0_pass_stack->Add(Background_0x0_pass_postfit_projx0_stack_1_stack_1,"");
   postfit_projx0_pass_stack->Draw("hist same");
   Double_t xAxis438[10] = {0, 0.05, 0.1, 0.15, 0.2, 0.25, 0.3, 0.35, 0.4, 1}; 
   
   TH1D *Signal_gluinomI1800_pass_postfit_projx0__290 = new TH1D("Signal_gluinomI1800_pass_postfit_projx0__290","HSCP gluino 1800 GeV, pass, postfit, 200-200",9, xAxis438);
   Signal_gluinomI1800_pass_postfit_projx0__290->SetMinimum(0);
   Signal_gluinomI1800_pass_postfit_projx0__290->SetLineColor(4);
   Signal_gluinomI1800_pass_postfit_projx0__290->SetLineStyle(0);
   Signal_gluinomI1800_pass_postfit_projx0__290->SetLineWidth(2);
   Signal_gluinomI1800_pass_postfit_projx0__290->GetXaxis()->SetTitle("G_{i}^{Strips}");
   Signal_gluinomI1800_pass_postfit_projx0__290->GetXaxis()->SetLabelFont(42);
   Signal_gluinomI1800_pass_postfit_projx0__290->GetXaxis()->SetLabelOffset(0.007);
   Signal_gluinomI1800_pass_postfit_projx0__290->GetXaxis()->SetLabelSize(0.05);
   Signal_gluinomI1800_pass_postfit_projx0__290->GetXaxis()->SetTitleSize(0.08);
   Signal_gluinomI1800_pass_postfit_projx0__290->GetXaxis()->SetTitleOffset(0.9);
   Signal_gluinomI1800_pass_postfit_projx0__290->GetXaxis()->SetTitleFont(42);
   Signal_gluinomI1800_pass_postfit_projx0__290->GetYaxis()->SetTitle("Events / bin");
   Signal_gluinomI1800_pass_postfit_projx0__290->GetYaxis()->SetLabelFont(42);
   Signal_gluinomI1800_pass_postfit_projx0__290->GetYaxis()->SetLabelOffset(0.007);
   Signal_gluinomI1800_pass_postfit_projx0__290->GetYaxis()->SetLabelSize(0.05);
   Signal_gluinomI1800_pass_postfit_projx0__290->GetYaxis()->SetTitleSize(0.08);
   Signal_gluinomI1800_pass_postfit_projx0__290->GetYaxis()->SetTitleOffset(1.25);
   Signal_gluinomI1800_pass_postfit_projx0__290->GetYaxis()->SetTitleFont(42);
   Signal_gluinomI1800_pass_postfit_projx0__290->GetZaxis()->SetLabelFont(42);
   Signal_gluinomI1800_pass_postfit_projx0__290->GetZaxis()->SetLabelOffset(0.007);
   Signal_gluinomI1800_pass_postfit_projx0__290->GetZaxis()->SetLabelSize(0.05);
   Signal_gluinomI1800_pass_postfit_projx0__290->GetZaxis()->SetTitleSize(0.08);
   Signal_gluinomI1800_pass_postfit_projx0__290->GetZaxis()->SetTitleFont(42);
   Signal_gluinomI1800_pass_postfit_projx0__290->Draw("hist same");
   Double_t xAxis439[10] = {0, 0.05, 0.1, 0.15, 0.2, 0.25, 0.3, 0.35, 0.4, 1}; 
   
   TH1D *Signal_ppStaumI557_pass_postfit_projx0__291 = new TH1D("Signal_ppStaumI557_pass_postfit_projx0__291","HSCP stau 557 GeV, pass, postfit, 200-200",9, xAxis439);
   Signal_ppStaumI557_pass_postfit_projx0__291->SetMinimum(0);
   Signal_ppStaumI557_pass_postfit_projx0__291->SetLineColor(2);
   Signal_ppStaumI557_pass_postfit_projx0__291->SetLineStyle(0);
   Signal_ppStaumI557_pass_postfit_projx0__291->SetLineWidth(2);
   Signal_ppStaumI557_pass_postfit_projx0__291->GetXaxis()->SetTitle("G_{i}^{Strips}");
   Signal_ppStaumI557_pass_postfit_projx0__291->GetXaxis()->SetLabelFont(42);
   Signal_ppStaumI557_pass_postfit_projx0__291->GetXaxis()->SetLabelOffset(0.007);
   Signal_ppStaumI557_pass_postfit_projx0__291->GetXaxis()->SetLabelSize(0.05);
   Signal_ppStaumI557_pass_postfit_projx0__291->GetXaxis()->SetTitleSize(0.08);
   Signal_ppStaumI557_pass_postfit_projx0__291->GetXaxis()->SetTitleOffset(0.9);
   Signal_ppStaumI557_pass_postfit_projx0__291->GetXaxis()->SetTitleFont(42);
   Signal_ppStaumI557_pass_postfit_projx0__291->GetYaxis()->SetTitle("Events / bin");
   Signal_ppStaumI557_pass_postfit_projx0__291->GetYaxis()->SetLabelFont(42);
   Signal_ppStaumI557_pass_postfit_projx0__291->GetYaxis()->SetLabelOffset(0.007);
   Signal_ppStaumI557_pass_postfit_projx0__291->GetYaxis()->SetLabelSize(0.05);
   Signal_ppStaumI557_pass_postfit_projx0__291->GetYaxis()->SetTitleSize(0.08);
   Signal_ppStaumI557_pass_postfit_projx0__291->GetYaxis()->SetTitleOffset(1.25);
   Signal_ppStaumI557_pass_postfit_projx0__291->GetYaxis()->SetTitleFont(42);
   Signal_ppStaumI557_pass_postfit_projx0__291->GetZaxis()->SetLabelFont(42);
   Signal_ppStaumI557_pass_postfit_projx0__291->GetZaxis()->SetLabelOffset(0.007);
   Signal_ppStaumI557_pass_postfit_projx0__291->GetZaxis()->SetLabelSize(0.05);
   Signal_ppStaumI557_pass_postfit_projx0__291->GetZaxis()->SetTitleSize(0.08);
   Signal_ppStaumI557_pass_postfit_projx0__291->GetZaxis()->SetTitleFont(42);
   Signal_ppStaumI557_pass_postfit_projx0__291->Draw("hist same");
   Double_t xAxis440[10] = {0, 0.05, 0.1, 0.15, 0.2, 0.25, 0.3, 0.35, 0.4, 1}; 
   
   TH1D *TotalBkg_pass_postfit_projx0__292 = new TH1D("TotalBkg_pass_postfit_projx0__292","TotalBkg, pass, postfit, 200-200",9, xAxis440);
   TotalBkg_pass_postfit_projx0__292->SetMinimum(0);
   TotalBkg_pass_postfit_projx0__292->SetLineStyle(0);
   TotalBkg_pass_postfit_projx0__292->SetMarkerStyle(0);
   TotalBkg_pass_postfit_projx0__292->GetXaxis()->SetTitle("G_{i}^{Strips}");
   TotalBkg_pass_postfit_projx0__292->GetXaxis()->SetLabelFont(42);
   TotalBkg_pass_postfit_projx0__292->GetXaxis()->SetLabelOffset(0.007);
   TotalBkg_pass_postfit_projx0__292->GetXaxis()->SetLabelSize(0.05);
   TotalBkg_pass_postfit_projx0__292->GetXaxis()->SetTitleSize(0.08);
   TotalBkg_pass_postfit_projx0__292->GetXaxis()->SetTitleOffset(0.9);
   TotalBkg_pass_postfit_projx0__292->GetXaxis()->SetTitleFont(42);
   TotalBkg_pass_postfit_projx0__292->GetYaxis()->SetTitle("Events / bin");
   TotalBkg_pass_postfit_projx0__292->GetYaxis()->SetLabelFont(42);
   TotalBkg_pass_postfit_projx0__292->GetYaxis()->SetLabelOffset(0.007);
   TotalBkg_pass_postfit_projx0__292->GetYaxis()->SetLabelSize(0.05);
   TotalBkg_pass_postfit_projx0__292->GetYaxis()->SetTitleSize(0.08);
   TotalBkg_pass_postfit_projx0__292->GetYaxis()->SetTitleOffset(1.25);
   TotalBkg_pass_postfit_projx0__292->GetYaxis()->SetTitleFont(42);
   TotalBkg_pass_postfit_projx0__292->GetZaxis()->SetLabelFont(42);
   TotalBkg_pass_postfit_projx0__292->GetZaxis()->SetLabelOffset(0.007);
   TotalBkg_pass_postfit_projx0__292->GetZaxis()->SetLabelSize(0.05);
   TotalBkg_pass_postfit_projx0__292->GetZaxis()->SetTitleSize(0.08);
   TotalBkg_pass_postfit_projx0__292->GetZaxis()->SetTitleFont(42);
   TotalBkg_pass_postfit_projx0__292->Draw("hist same");
   Double_t xAxis441[10] = {0, 0.05, 0.1, 0.15, 0.2, 0.25, 0.3, 0.35, 0.4, 1}; 
   
   TH1D *TotalBkg_pass_postfit_projx0__293 = new TH1D("TotalBkg_pass_postfit_projx0__293","TotalBkg, pass, postfit, 200-200",9, xAxis441);
   TotalBkg_pass_postfit_projx0__293->SetMinimum(0);
   TotalBkg_pass_postfit_projx0__293->SetFillColor(1);
   TotalBkg_pass_postfit_projx0__293->SetFillStyle(3354);
   TotalBkg_pass_postfit_projx0__293->SetLineStyle(0);
   TotalBkg_pass_postfit_projx0__293->SetLineWidth(0);
   TotalBkg_pass_postfit_projx0__293->SetMarkerStyle(0);
   TotalBkg_pass_postfit_projx0__293->GetXaxis()->SetTitle("G_{i}^{Strips}");
   TotalBkg_pass_postfit_projx0__293->GetXaxis()->SetLabelFont(42);
   TotalBkg_pass_postfit_projx0__293->GetXaxis()->SetLabelOffset(0.007);
   TotalBkg_pass_postfit_projx0__293->GetXaxis()->SetLabelSize(0.05);
   TotalBkg_pass_postfit_projx0__293->GetXaxis()->SetTitleSize(0.08);
   TotalBkg_pass_postfit_projx0__293->GetXaxis()->SetTitleOffset(0.9);
   TotalBkg_pass_postfit_projx0__293->GetXaxis()->SetTitleFont(42);
   TotalBkg_pass_postfit_projx0__293->GetYaxis()->SetTitle("Events / bin");
   TotalBkg_pass_postfit_projx0__293->GetYaxis()->SetLabelFont(42);
   TotalBkg_pass_postfit_projx0__293->GetYaxis()->SetLabelOffset(0.007);
   TotalBkg_pass_postfit_projx0__293->GetYaxis()->SetLabelSize(0.05);
   TotalBkg_pass_postfit_projx0__293->GetYaxis()->SetTitleSize(0.08);
   TotalBkg_pass_postfit_projx0__293->GetYaxis()->SetTitleOffset(1.25);
   TotalBkg_pass_postfit_projx0__293->GetYaxis()->SetTitleFont(42);
   TotalBkg_pass_postfit_projx0__293->GetZaxis()->SetLabelFont(42);
   TotalBkg_pass_postfit_projx0__293->GetZaxis()->SetLabelOffset(0.007);
   TotalBkg_pass_postfit_projx0__293->GetZaxis()->SetLabelSize(0.05);
   TotalBkg_pass_postfit_projx0__293->GetZaxis()->SetTitleSize(0.08);
   TotalBkg_pass_postfit_projx0__293->GetZaxis()->SetTitleFont(42);
   TotalBkg_pass_postfit_projx0__293->Draw("e2 same");
   Double_t xAxis442[10] = {0, 0.05, 0.1, 0.15, 0.2, 0.25, 0.3, 0.35, 0.4, 1}; 
   
   TH1D *data_obs_pass_postfit_projx0__294 = new TH1D("data_obs_pass_postfit_projx0__294","",9, xAxis442);
   data_obs_pass_postfit_projx0__294->SetMinimum(0);
   data_obs_pass_postfit_projx0__294->SetMaximum(0);

   ci = TColor::GetColor("#000000");
   data_obs_pass_postfit_projx0__294->SetLineColor(ci);
   data_obs_pass_postfit_projx0__294->SetLineStyle(0);

   ci = TColor::GetColor("#000000");
   data_obs_pass_postfit_projx0__294->SetMarkerColor(ci);
   data_obs_pass_postfit_projx0__294->SetMarkerStyle(8);
   data_obs_pass_postfit_projx0__294->GetXaxis()->SetTitle("G_{i}^{Strips}");
   data_obs_pass_postfit_projx0__294->GetXaxis()->SetLabelFont(42);
   data_obs_pass_postfit_projx0__294->GetXaxis()->SetLabelOffset(0.05);
   data_obs_pass_postfit_projx0__294->GetXaxis()->SetLabelSize(0.07);
   data_obs_pass_postfit_projx0__294->GetXaxis()->SetTitleSize(0.09);
   data_obs_pass_postfit_projx0__294->GetXaxis()->SetTitleOffset(1.15);
   data_obs_pass_postfit_projx0__294->GetXaxis()->SetTitleFont(42);
   data_obs_pass_postfit_projx0__294->GetYaxis()->SetTitle("Events / bin");
   data_obs_pass_postfit_projx0__294->GetYaxis()->SetNdivisions(508);
   data_obs_pass_postfit_projx0__294->GetYaxis()->SetLabelFont(42);
   data_obs_pass_postfit_projx0__294->GetYaxis()->SetLabelOffset(0.007);
   data_obs_pass_postfit_projx0__294->GetYaxis()->SetLabelSize(0.07);
   data_obs_pass_postfit_projx0__294->GetYaxis()->SetTitleSize(0.09);
   data_obs_pass_postfit_projx0__294->GetYaxis()->SetTitleOffset(0.8);
   data_obs_pass_postfit_projx0__294->GetYaxis()->SetTitleFont(42);
   data_obs_pass_postfit_projx0__294->GetZaxis()->SetLabelFont(42);
   data_obs_pass_postfit_projx0__294->GetZaxis()->SetLabelOffset(0.007);
   data_obs_pass_postfit_projx0__294->GetZaxis()->SetLabelSize(0.05);
   data_obs_pass_postfit_projx0__294->GetZaxis()->SetTitleSize(0.08);
   data_obs_pass_postfit_projx0__294->GetZaxis()->SetTitleFont(42);
   data_obs_pass_postfit_projx0__294->Draw("pe X0 same");
   
   TLegend *leg = new TLegend(0.65,0.61,0.9,0.88,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(1001);
   TLegendEntry *entry=leg->AddEntry("data_obs_pass_postfit_projx0","Data","pe X0");

   ci = TColor::GetColor("#000000");
   entry->SetLineColor(ci);
   entry->SetLineWidth(1);

   ci = TColor::GetColor("#000000");
   entry->SetMarkerColor(ci);
   entry->SetMarkerStyle(8);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("TotalBkg_pass_postfit_projx0","Total bkg unc.","F");
   entry->SetFillColor(1);
   entry->SetFillStyle(3354);
   entry->SetLineColor(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("Signal_gluino-1800_pass_postfit_projx0","HSCP gluino 1800 GeV","L");
   entry->SetLineColor(4);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("Signal_ppStau-557_pass_postfit_projx0","HSCP stau 557 GeV","L");
   entry->SetLineColor(2);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("Background_0x0_pass_postfit_projx0_stack_1_stack_1","Background","f");

   ci = TColor::GetColor("#ffff00");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = 1341;
   color = new TColor(ci, 1, 1, 1, " ", 0);
   entry->SetLineColor(ci);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   leg->Draw();
   Double_t xAxis443[10] = {0, 0.05, 0.1, 0.15, 0.2, 0.25, 0.3, 0.35, 0.4, 1}; 
   
   TH1D *data_obs_pass_postfit_projx0_copy__295 = new TH1D("data_obs_pass_postfit_projx0_copy__295","",9, xAxis443);
   data_obs_pass_postfit_projx0_copy__295->SetMinimum(0);
   data_obs_pass_postfit_projx0_copy__295->SetMaximum(0);
   data_obs_pass_postfit_projx0_copy__295->SetDirectory(0);

   ci = TColor::GetColor("#000000");
   data_obs_pass_postfit_projx0_copy__295->SetLineColor(ci);
   data_obs_pass_postfit_projx0_copy__295->SetLineStyle(0);

   ci = TColor::GetColor("#000000");
   data_obs_pass_postfit_projx0_copy__295->SetMarkerColor(ci);
   data_obs_pass_postfit_projx0_copy__295->SetMarkerStyle(8);
   data_obs_pass_postfit_projx0_copy__295->GetXaxis()->SetTitle("G_{i}^{Strips}");
   data_obs_pass_postfit_projx0_copy__295->GetXaxis()->SetLabelFont(42);
   data_obs_pass_postfit_projx0_copy__295->GetXaxis()->SetLabelOffset(0.05);
   data_obs_pass_postfit_projx0_copy__295->GetXaxis()->SetLabelSize(0.07);
   data_obs_pass_postfit_projx0_copy__295->GetXaxis()->SetTitleSize(0.09);
   data_obs_pass_postfit_projx0_copy__295->GetXaxis()->SetTitleOffset(1.15);
   data_obs_pass_postfit_projx0_copy__295->GetXaxis()->SetTitleFont(42);
   data_obs_pass_postfit_projx0_copy__295->GetYaxis()->SetTitle("Events / bin");
   data_obs_pass_postfit_projx0_copy__295->GetYaxis()->SetNdivisions(508);
   data_obs_pass_postfit_projx0_copy__295->GetYaxis()->SetLabelFont(42);
   data_obs_pass_postfit_projx0_copy__295->GetYaxis()->SetLabelOffset(0.007);
   data_obs_pass_postfit_projx0_copy__295->GetYaxis()->SetLabelSize(0.07);
   data_obs_pass_postfit_projx0_copy__295->GetYaxis()->SetTitleSize(0.09);
   data_obs_pass_postfit_projx0_copy__295->GetYaxis()->SetTitleOffset(0.8);
   data_obs_pass_postfit_projx0_copy__295->GetYaxis()->SetTitleFont(42);
   data_obs_pass_postfit_projx0_copy__295->GetZaxis()->SetLabelFont(42);
   data_obs_pass_postfit_projx0_copy__295->GetZaxis()->SetLabelOffset(0.007);
   data_obs_pass_postfit_projx0_copy__295->GetZaxis()->SetLabelSize(0.05);
   data_obs_pass_postfit_projx0_copy__295->GetZaxis()->SetTitleSize(0.08);
   data_obs_pass_postfit_projx0_copy__295->GetZaxis()->SetTitleFont(42);
   data_obs_pass_postfit_projx0_copy__295->Draw("sameaxis");
   TLatex *   tex = new TLatex(0.21,0.83,"200 < p_{T} < 200 , F^{Pixels}_{i} > 0.9");
tex->SetNDC();
   tex->SetTextAlign(12);
   tex->SetTextFont(42);
   tex->SetTextSize(0.06);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.17,0.92,"CMS");
tex->SetNDC();
   tex->SetTextFont(61);
   tex->SetTextSize(0.0675);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.25,0.92,"Preliminary");
tex->SetNDC();
   tex->SetTextFont(52);
   tex->SetTextSize(0.0485);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.95,0.92,"101 fb^{-1} (13 TeV)");
tex->SetNDC();
   tex->SetTextAlign(31);
   tex->SetTextFont(42);
   tex->SetTextSize(0.07);
   tex->SetLineWidth(2);
   tex->Draw();
   data_obs_pass_postfit_projx0_main->Modified();
   plots_fit_s/base_figs/postfit_projx0_pass->cd();
  
// ------------>Primitives in pad: data_obs_pass_postfit_projx0_sub
   TPad *data_obs_pass_postfit_projx0_sub = new TPad("data_obs_pass_postfit_projx0_sub", "data_obs_pass_postfit_projx0_sub",0,0,1,0.35);
   data_obs_pass_postfit_projx0_sub->Draw();
   data_obs_pass_postfit_projx0_sub->cd();
   data_obs_pass_postfit_projx0_sub->Range(-0.2179487,-6.023077,1.064103,2.9);
   data_obs_pass_postfit_projx0_sub->SetFillColor(0);
   data_obs_pass_postfit_projx0_sub->SetBorderMode(0);
   data_obs_pass_postfit_projx0_sub->SetBorderSize(2);
   data_obs_pass_postfit_projx0_sub->SetTickx(1);
   data_obs_pass_postfit_projx0_sub->SetTicky(1);
   data_obs_pass_postfit_projx0_sub->SetLeftMargin(0.17);
   data_obs_pass_postfit_projx0_sub->SetRightMargin(0.05);
   data_obs_pass_postfit_projx0_sub->SetTopMargin(0);
   data_obs_pass_postfit_projx0_sub->SetBottomMargin(0.35);
   data_obs_pass_postfit_projx0_sub->SetFrameFillStyle(0);
   data_obs_pass_postfit_projx0_sub->SetFrameBorderMode(0);
   data_obs_pass_postfit_projx0_sub->SetFrameFillStyle(0);
   data_obs_pass_postfit_projx0_sub->SetFrameBorderMode(0);
   Double_t xAxis444[10] = {0, 0.05, 0.1, 0.15, 0.2, 0.25, 0.3, 0.35, 0.4, 1}; 
   
   TH1D *data_obs_pass_postfit_projx0_pull__296 = new TH1D("data_obs_pass_postfit_projx0_pull__296","",9, xAxis444);
   data_obs_pass_postfit_projx0_pull__296->SetMinimum(-2.9);
   data_obs_pass_postfit_projx0_pull__296->SetMaximum(2.9);
   data_obs_pass_postfit_projx0_pull__296->SetEntries(18);
   data_obs_pass_postfit_projx0_pull__296->SetStats(0);

   ci = TColor::GetColor("#0000ff");
   data_obs_pass_postfit_projx0_pull__296->SetFillColor(ci);

   ci = TColor::GetColor("#000000");
   data_obs_pass_postfit_projx0_pull__296->SetLineColor(ci);
   data_obs_pass_postfit_projx0_pull__296->SetLineStyle(0);

   ci = TColor::GetColor("#000000");
   data_obs_pass_postfit_projx0_pull__296->SetMarkerColor(ci);
   data_obs_pass_postfit_projx0_pull__296->SetMarkerStyle(8);
   data_obs_pass_postfit_projx0_pull__296->GetXaxis()->SetTitle("G_{i}^{Strips}");
   data_obs_pass_postfit_projx0_pull__296->GetXaxis()->SetLabelFont(42);
   data_obs_pass_postfit_projx0_pull__296->GetXaxis()->SetLabelOffset(0.05);
   data_obs_pass_postfit_projx0_pull__296->GetXaxis()->SetLabelSize(0.13);
   data_obs_pass_postfit_projx0_pull__296->GetXaxis()->SetTitleSize(0.15);
   data_obs_pass_postfit_projx0_pull__296->GetXaxis()->SetTitleOffset(1.15);
   data_obs_pass_postfit_projx0_pull__296->GetXaxis()->SetTitleFont(42);
   data_obs_pass_postfit_projx0_pull__296->GetYaxis()->SetTitle("(Data-Bkg)/#sigma");
   data_obs_pass_postfit_projx0_pull__296->GetYaxis()->SetNdivisions(306);
   data_obs_pass_postfit_projx0_pull__296->GetYaxis()->SetLabelFont(42);
   data_obs_pass_postfit_projx0_pull__296->GetYaxis()->SetLabelOffset(0.007);
   data_obs_pass_postfit_projx0_pull__296->GetYaxis()->SetLabelSize(0.13);
   data_obs_pass_postfit_projx0_pull__296->GetYaxis()->SetTitleSize(0.12);
   data_obs_pass_postfit_projx0_pull__296->GetYaxis()->SetTitleOffset(0.4);
   data_obs_pass_postfit_projx0_pull__296->GetYaxis()->SetTitleFont(42);
   data_obs_pass_postfit_projx0_pull__296->GetZaxis()->SetLabelFont(42);
   data_obs_pass_postfit_projx0_pull__296->GetZaxis()->SetLabelOffset(0.007);
   data_obs_pass_postfit_projx0_pull__296->GetZaxis()->SetLabelSize(0.05);
   data_obs_pass_postfit_projx0_pull__296->GetZaxis()->SetTitleSize(0.08);
   data_obs_pass_postfit_projx0_pull__296->GetZaxis()->SetTitleFont(42);
   data_obs_pass_postfit_projx0_pull__296->Draw("hist");
   data_obs_pass_postfit_projx0_sub->Modified();
   plots_fit_s/base_figs/postfit_projx0_pass->cd();
   plots_fit_s/base_figs/postfit_projx0_pass->Modified();
   plots_fit_s/base_figs/postfit_projx0_pass->cd();
   plots_fit_s/base_figs/postfit_projx0_pass->SetSelected(plots_fit_s/base_figs/postfit_projx0_pass);
}
