void postfit_projx1_fail_logy()
{
//=========Macro generated from canvas: plots_fit_s/base_figs/postfit_projx1_fail_logy/plots_fit_s/base_figs/postfit_projx1_fail_logy
//=========  (Fri Jan 12 20:33:23 2024) by ROOT version 6.14/09
   TCanvas *plots_fit_s/base_figs/postfit_projx1_fail_logy = new TCanvas("plots_fit_s/base_figs/postfit_projx1_fail_logy", "plots_fit_s/base_figs/postfit_projx1_fail_logy",0,0,800,700);
   gStyle->SetOptFit(1);
   gStyle->SetOptStat(0);
   plots_fit_s/base_figs/postfit_projx1_fail_logy->SetHighLightColor(2);
   plots_fit_s/base_figs/postfit_projx1_fail_logy->Range(0,0,1,1);
   plots_fit_s/base_figs/postfit_projx1_fail_logy->SetFillColor(0);
   plots_fit_s/base_figs/postfit_projx1_fail_logy->SetBorderMode(0);
   plots_fit_s/base_figs/postfit_projx1_fail_logy->SetBorderSize(2);
   plots_fit_s/base_figs/postfit_projx1_fail_logy->SetTickx(1);
   plots_fit_s/base_figs/postfit_projx1_fail_logy->SetTicky(1);
   plots_fit_s/base_figs/postfit_projx1_fail_logy->SetLeftMargin(0.16);
   plots_fit_s/base_figs/postfit_projx1_fail_logy->SetRightMargin(0);
   plots_fit_s/base_figs/postfit_projx1_fail_logy->SetTopMargin(0);
   plots_fit_s/base_figs/postfit_projx1_fail_logy->SetBottomMargin(0);
   plots_fit_s/base_figs/postfit_projx1_fail_logy->SetFrameFillStyle(0);
   plots_fit_s/base_figs/postfit_projx1_fail_logy->SetFrameBorderMode(0);
  
// ------------>Primitives in pad: data_obs_fail_postfit_projx1_main
   TPad *data_obs_fail_postfit_projx1_main = new TPad("data_obs_fail_postfit_projx1_main", "data_obs_fail_postfit_projx1_main",0,0.35,1,1);
   data_obs_fail_postfit_projx1_main->Draw();
   data_obs_fail_postfit_projx1_main->cd();
   data_obs_fail_postfit_projx1_main->Range(-0.2179487,-2.139535,1.064103,1.348837);
   data_obs_fail_postfit_projx1_main->SetFillColor(0);
   data_obs_fail_postfit_projx1_main->SetBorderMode(0);
   data_obs_fail_postfit_projx1_main->SetBorderSize(2);
   data_obs_fail_postfit_projx1_main->SetLogy();
   data_obs_fail_postfit_projx1_main->SetTickx(1);
   data_obs_fail_postfit_projx1_main->SetTicky(1);
   data_obs_fail_postfit_projx1_main->SetLeftMargin(0.17);
   data_obs_fail_postfit_projx1_main->SetRightMargin(0.05);
   data_obs_fail_postfit_projx1_main->SetBottomMargin(0.04);
   data_obs_fail_postfit_projx1_main->SetFrameFillStyle(0);
   data_obs_fail_postfit_projx1_main->SetFrameBorderMode(0);
   data_obs_fail_postfit_projx1_main->SetFrameFillStyle(0);
   data_obs_fail_postfit_projx1_main->SetFrameBorderMode(0);
   Double_t xAxis373[10] = {0, 0.05, 0.1, 0.15, 0.2, 0.25, 0.3, 0.35, 0.4, 1}; 
   
   TH1D *data_obs_fail_postfit_projx1__249 = new TH1D("data_obs_fail_postfit_projx1__249","",9, xAxis373);
   data_obs_fail_postfit_projx1__249->SetMinimum(0.001);
   data_obs_fail_postfit_projx1__249->SetMaximum(0);

   Int_t ci;      // for color index setting
   TColor *color; // for color definition with alpha
   ci = TColor::GetColor("#000000");
   data_obs_fail_postfit_projx1__249->SetLineColor(ci);
   data_obs_fail_postfit_projx1__249->SetLineStyle(0);

   ci = TColor::GetColor("#000000");
   data_obs_fail_postfit_projx1__249->SetMarkerColor(ci);
   data_obs_fail_postfit_projx1__249->SetMarkerStyle(8);
   data_obs_fail_postfit_projx1__249->GetXaxis()->SetTitle("G_{i}^{Strips}");
   data_obs_fail_postfit_projx1__249->GetXaxis()->SetLabelFont(42);
   data_obs_fail_postfit_projx1__249->GetXaxis()->SetLabelOffset(0.05);
   data_obs_fail_postfit_projx1__249->GetXaxis()->SetLabelSize(0.07);
   data_obs_fail_postfit_projx1__249->GetXaxis()->SetTitleSize(0.09);
   data_obs_fail_postfit_projx1__249->GetXaxis()->SetTitleOffset(1.15);
   data_obs_fail_postfit_projx1__249->GetXaxis()->SetTitleFont(42);
   data_obs_fail_postfit_projx1__249->GetYaxis()->SetTitle("Events / bin");
   data_obs_fail_postfit_projx1__249->GetYaxis()->SetNdivisions(508);
   data_obs_fail_postfit_projx1__249->GetYaxis()->SetLabelFont(42);
   data_obs_fail_postfit_projx1__249->GetYaxis()->SetLabelOffset(0.007);
   data_obs_fail_postfit_projx1__249->GetYaxis()->SetLabelSize(0.07);
   data_obs_fail_postfit_projx1__249->GetYaxis()->SetTitleSize(0.09);
   data_obs_fail_postfit_projx1__249->GetYaxis()->SetTitleOffset(0.8);
   data_obs_fail_postfit_projx1__249->GetYaxis()->SetTitleFont(42);
   data_obs_fail_postfit_projx1__249->GetZaxis()->SetLabelFont(42);
   data_obs_fail_postfit_projx1__249->GetZaxis()->SetLabelOffset(0.007);
   data_obs_fail_postfit_projx1__249->GetZaxis()->SetLabelSize(0.05);
   data_obs_fail_postfit_projx1__249->GetZaxis()->SetTitleSize(0.08);
   data_obs_fail_postfit_projx1__249->GetZaxis()->SetTitleFont(42);
   data_obs_fail_postfit_projx1__249->Draw("pe X0");
   
   THStack *postfit_projx1_fail_logy_stack = new THStack();
   postfit_projx1_fail_logy_stack->SetName("postfit_projx1_fail_logy_stack");
   postfit_projx1_fail_logy_stack->SetTitle("postfit_projx1_fail_logy_stack");
   postfit_projx1_fail_logy_stack->SetMinimum(0.001);
   Double_t xAxis374[10] = {0, 0.05, 0.1, 0.15, 0.2, 0.25, 0.3, 0.35, 0.4, 1}; 
   
   TH1F *postfit_projx1_fail_logy_stack_stack_63 = new TH1F("postfit_projx1_fail_logy_stack_stack_63","postfit_projx1_fail_logy_stack",9, xAxis374);
   postfit_projx1_fail_logy_stack_stack_63->SetMinimum(-0);
   postfit_projx1_fail_logy_stack_stack_63->SetMaximum(-nan);
   postfit_projx1_fail_logy_stack_stack_63->SetDirectory(0);
   postfit_projx1_fail_logy_stack_stack_63->SetStats(0);
   postfit_projx1_fail_logy_stack_stack_63->SetLineStyle(0);
   postfit_projx1_fail_logy_stack_stack_63->GetXaxis()->SetLabelFont(42);
   postfit_projx1_fail_logy_stack_stack_63->GetXaxis()->SetLabelOffset(0.007);
   postfit_projx1_fail_logy_stack_stack_63->GetXaxis()->SetLabelSize(0.05);
   postfit_projx1_fail_logy_stack_stack_63->GetXaxis()->SetTitleSize(0.08);
   postfit_projx1_fail_logy_stack_stack_63->GetXaxis()->SetTitleOffset(0.9);
   postfit_projx1_fail_logy_stack_stack_63->GetXaxis()->SetTitleFont(42);
   postfit_projx1_fail_logy_stack_stack_63->GetYaxis()->SetNdivisions(508);
   postfit_projx1_fail_logy_stack_stack_63->GetYaxis()->SetLabelFont(42);
   postfit_projx1_fail_logy_stack_stack_63->GetYaxis()->SetLabelOffset(0.007);
   postfit_projx1_fail_logy_stack_stack_63->GetYaxis()->SetLabelSize(0.05);
   postfit_projx1_fail_logy_stack_stack_63->GetYaxis()->SetTitleSize(0.08);
   postfit_projx1_fail_logy_stack_stack_63->GetYaxis()->SetTitleOffset(1.25);
   postfit_projx1_fail_logy_stack_stack_63->GetYaxis()->SetTitleFont(42);
   postfit_projx1_fail_logy_stack_stack_63->GetZaxis()->SetLabelFont(42);
   postfit_projx1_fail_logy_stack_stack_63->GetZaxis()->SetLabelOffset(0.007);
   postfit_projx1_fail_logy_stack_stack_63->GetZaxis()->SetLabelSize(0.05);
   postfit_projx1_fail_logy_stack_stack_63->GetZaxis()->SetTitleSize(0.08);
   postfit_projx1_fail_logy_stack_stack_63->GetZaxis()->SetTitleFont(42);
   postfit_projx1_fail_logy_stack->SetHistogram(postfit_projx1_fail_logy_stack_stack_63);
   
   Double_t xAxis375[10] = {0, 0.05, 0.1, 0.15, 0.2, 0.25, 0.3, 0.35, 0.4, 1}; 
   
   TH1D *Background_fail_postfit_projx1_stack_1 = new TH1D("Background_fail_postfit_projx1_stack_1","Background, fail, postfit, 200-200",9, xAxis375);
   Background_fail_postfit_projx1_stack_1->SetMinimum(0.001);

   ci = TColor::GetColor("#ffff00");
   Background_fail_postfit_projx1_stack_1->SetFillColor(ci);

   ci = 1330;
   color = new TColor(ci, 1, 1, 1, " ", 0);
   Background_fail_postfit_projx1_stack_1->SetLineColor(ci);
   Background_fail_postfit_projx1_stack_1->SetLineStyle(0);
   Background_fail_postfit_projx1_stack_1->GetXaxis()->SetTitle("G_{i}^{Strips}");
   Background_fail_postfit_projx1_stack_1->GetXaxis()->SetLabelFont(42);
   Background_fail_postfit_projx1_stack_1->GetXaxis()->SetLabelOffset(0.007);
   Background_fail_postfit_projx1_stack_1->GetXaxis()->SetLabelSize(0.05);
   Background_fail_postfit_projx1_stack_1->GetXaxis()->SetTitleSize(0.08);
   Background_fail_postfit_projx1_stack_1->GetXaxis()->SetTitleOffset(0.9);
   Background_fail_postfit_projx1_stack_1->GetXaxis()->SetTitleFont(42);
   Background_fail_postfit_projx1_stack_1->GetYaxis()->SetTitle("Events / bin");
   Background_fail_postfit_projx1_stack_1->GetYaxis()->SetLabelFont(42);
   Background_fail_postfit_projx1_stack_1->GetYaxis()->SetLabelOffset(0.007);
   Background_fail_postfit_projx1_stack_1->GetYaxis()->SetLabelSize(0.05);
   Background_fail_postfit_projx1_stack_1->GetYaxis()->SetTitleSize(0.08);
   Background_fail_postfit_projx1_stack_1->GetYaxis()->SetTitleOffset(1.25);
   Background_fail_postfit_projx1_stack_1->GetYaxis()->SetTitleFont(42);
   Background_fail_postfit_projx1_stack_1->GetZaxis()->SetLabelFont(42);
   Background_fail_postfit_projx1_stack_1->GetZaxis()->SetLabelOffset(0.007);
   Background_fail_postfit_projx1_stack_1->GetZaxis()->SetLabelSize(0.05);
   Background_fail_postfit_projx1_stack_1->GetZaxis()->SetTitleSize(0.08);
   Background_fail_postfit_projx1_stack_1->GetZaxis()->SetTitleFont(42);
   postfit_projx1_fail_logy_stack->Add(Background_fail_postfit_projx1_stack_1,"");
   postfit_projx1_fail_logy_stack->Draw("hist same");
   
   postfit_projx1_fail_logy_stack = new THStack();
   postfit_projx1_fail_logy_stack->SetName("postfit_projx1_fail_logy_stack");
   postfit_projx1_fail_logy_stack->SetTitle("postfit_projx1_fail_logy_stack");
   postfit_projx1_fail_logy_stack->SetMinimum(0.001);
   Double_t xAxis376[10] = {0, 0.05, 0.1, 0.15, 0.2, 0.25, 0.3, 0.35, 0.4, 1}; 
   
   TH1F *postfit_projx1_fail_logy_stack_stack_63_stack_64 = new TH1F("postfit_projx1_fail_logy_stack_stack_63_stack_64","postfit_projx1_fail_logy_stack",9, xAxis376);
   postfit_projx1_fail_logy_stack_stack_63_stack_64->SetMinimum(-0);
   postfit_projx1_fail_logy_stack_stack_63_stack_64->SetMaximum(-nan);
   postfit_projx1_fail_logy_stack_stack_63_stack_64->SetDirectory(0);
   postfit_projx1_fail_logy_stack_stack_63_stack_64->SetStats(0);
   postfit_projx1_fail_logy_stack_stack_63_stack_64->SetLineStyle(0);
   postfit_projx1_fail_logy_stack_stack_63_stack_64->GetXaxis()->SetLabelFont(42);
   postfit_projx1_fail_logy_stack_stack_63_stack_64->GetXaxis()->SetLabelOffset(0.007);
   postfit_projx1_fail_logy_stack_stack_63_stack_64->GetXaxis()->SetLabelSize(0.05);
   postfit_projx1_fail_logy_stack_stack_63_stack_64->GetXaxis()->SetTitleSize(0.08);
   postfit_projx1_fail_logy_stack_stack_63_stack_64->GetXaxis()->SetTitleOffset(0.9);
   postfit_projx1_fail_logy_stack_stack_63_stack_64->GetXaxis()->SetTitleFont(42);
   postfit_projx1_fail_logy_stack_stack_63_stack_64->GetYaxis()->SetNdivisions(508);
   postfit_projx1_fail_logy_stack_stack_63_stack_64->GetYaxis()->SetLabelFont(42);
   postfit_projx1_fail_logy_stack_stack_63_stack_64->GetYaxis()->SetLabelOffset(0.007);
   postfit_projx1_fail_logy_stack_stack_63_stack_64->GetYaxis()->SetLabelSize(0.05);
   postfit_projx1_fail_logy_stack_stack_63_stack_64->GetYaxis()->SetTitleSize(0.08);
   postfit_projx1_fail_logy_stack_stack_63_stack_64->GetYaxis()->SetTitleOffset(1.25);
   postfit_projx1_fail_logy_stack_stack_63_stack_64->GetYaxis()->SetTitleFont(42);
   postfit_projx1_fail_logy_stack_stack_63_stack_64->GetZaxis()->SetLabelFont(42);
   postfit_projx1_fail_logy_stack_stack_63_stack_64->GetZaxis()->SetLabelOffset(0.007);
   postfit_projx1_fail_logy_stack_stack_63_stack_64->GetZaxis()->SetLabelSize(0.05);
   postfit_projx1_fail_logy_stack_stack_63_stack_64->GetZaxis()->SetTitleSize(0.08);
   postfit_projx1_fail_logy_stack_stack_63_stack_64->GetZaxis()->SetTitleFont(42);
   postfit_projx1_fail_logy_stack->SetHistogram(postfit_projx1_fail_logy_stack_stack_63_stack_64);
   
   Double_t xAxis377[10] = {0, 0.05, 0.1, 0.15, 0.2, 0.25, 0.3, 0.35, 0.4, 1}; 
   
   TH1D *Background_fail_postfit_projx1_stack_1_stack_1 = new TH1D("Background_fail_postfit_projx1_stack_1_stack_1","Background, fail, postfit, 200-200",9, xAxis377);
   Background_fail_postfit_projx1_stack_1_stack_1->SetMinimum(0.001);

   ci = TColor::GetColor("#ffff00");
   Background_fail_postfit_projx1_stack_1_stack_1->SetFillColor(ci);

   ci = 1330;
   color = new TColor(ci, 1, 1, 1, " ", 0);
   Background_fail_postfit_projx1_stack_1_stack_1->SetLineColor(ci);
   Background_fail_postfit_projx1_stack_1_stack_1->SetLineStyle(0);
   Background_fail_postfit_projx1_stack_1_stack_1->GetXaxis()->SetTitle("G_{i}^{Strips}");
   Background_fail_postfit_projx1_stack_1_stack_1->GetXaxis()->SetLabelFont(42);
   Background_fail_postfit_projx1_stack_1_stack_1->GetXaxis()->SetLabelOffset(0.007);
   Background_fail_postfit_projx1_stack_1_stack_1->GetXaxis()->SetLabelSize(0.05);
   Background_fail_postfit_projx1_stack_1_stack_1->GetXaxis()->SetTitleSize(0.08);
   Background_fail_postfit_projx1_stack_1_stack_1->GetXaxis()->SetTitleOffset(0.9);
   Background_fail_postfit_projx1_stack_1_stack_1->GetXaxis()->SetTitleFont(42);
   Background_fail_postfit_projx1_stack_1_stack_1->GetYaxis()->SetTitle("Events / bin");
   Background_fail_postfit_projx1_stack_1_stack_1->GetYaxis()->SetLabelFont(42);
   Background_fail_postfit_projx1_stack_1_stack_1->GetYaxis()->SetLabelOffset(0.007);
   Background_fail_postfit_projx1_stack_1_stack_1->GetYaxis()->SetLabelSize(0.05);
   Background_fail_postfit_projx1_stack_1_stack_1->GetYaxis()->SetTitleSize(0.08);
   Background_fail_postfit_projx1_stack_1_stack_1->GetYaxis()->SetTitleOffset(1.25);
   Background_fail_postfit_projx1_stack_1_stack_1->GetYaxis()->SetTitleFont(42);
   Background_fail_postfit_projx1_stack_1_stack_1->GetZaxis()->SetLabelFont(42);
   Background_fail_postfit_projx1_stack_1_stack_1->GetZaxis()->SetLabelOffset(0.007);
   Background_fail_postfit_projx1_stack_1_stack_1->GetZaxis()->SetLabelSize(0.05);
   Background_fail_postfit_projx1_stack_1_stack_1->GetZaxis()->SetTitleSize(0.08);
   Background_fail_postfit_projx1_stack_1_stack_1->GetZaxis()->SetTitleFont(42);
   postfit_projx1_fail_logy_stack->Add(Background_fail_postfit_projx1_stack_1_stack_1,"");
   postfit_projx1_fail_logy_stack->Draw("hist same");
   Double_t xAxis378[10] = {0, 0.05, 0.1, 0.15, 0.2, 0.25, 0.3, 0.35, 0.4, 1}; 
   
   TH1D *Signal_gluinomI1800_fail_postfit_projx1__250 = new TH1D("Signal_gluinomI1800_fail_postfit_projx1__250","HSCP gluino 1800 GeV, fail, postfit, 200-200",9, xAxis378);
   Signal_gluinomI1800_fail_postfit_projx1__250->SetMinimum(0.001);
   Signal_gluinomI1800_fail_postfit_projx1__250->SetLineColor(4);
   Signal_gluinomI1800_fail_postfit_projx1__250->SetLineStyle(0);
   Signal_gluinomI1800_fail_postfit_projx1__250->SetLineWidth(2);
   Signal_gluinomI1800_fail_postfit_projx1__250->GetXaxis()->SetTitle("G_{i}^{Strips}");
   Signal_gluinomI1800_fail_postfit_projx1__250->GetXaxis()->SetLabelFont(42);
   Signal_gluinomI1800_fail_postfit_projx1__250->GetXaxis()->SetLabelOffset(0.007);
   Signal_gluinomI1800_fail_postfit_projx1__250->GetXaxis()->SetLabelSize(0.05);
   Signal_gluinomI1800_fail_postfit_projx1__250->GetXaxis()->SetTitleSize(0.08);
   Signal_gluinomI1800_fail_postfit_projx1__250->GetXaxis()->SetTitleOffset(0.9);
   Signal_gluinomI1800_fail_postfit_projx1__250->GetXaxis()->SetTitleFont(42);
   Signal_gluinomI1800_fail_postfit_projx1__250->GetYaxis()->SetTitle("Events / bin");
   Signal_gluinomI1800_fail_postfit_projx1__250->GetYaxis()->SetLabelFont(42);
   Signal_gluinomI1800_fail_postfit_projx1__250->GetYaxis()->SetLabelOffset(0.007);
   Signal_gluinomI1800_fail_postfit_projx1__250->GetYaxis()->SetLabelSize(0.05);
   Signal_gluinomI1800_fail_postfit_projx1__250->GetYaxis()->SetTitleSize(0.08);
   Signal_gluinomI1800_fail_postfit_projx1__250->GetYaxis()->SetTitleOffset(1.25);
   Signal_gluinomI1800_fail_postfit_projx1__250->GetYaxis()->SetTitleFont(42);
   Signal_gluinomI1800_fail_postfit_projx1__250->GetZaxis()->SetLabelFont(42);
   Signal_gluinomI1800_fail_postfit_projx1__250->GetZaxis()->SetLabelOffset(0.007);
   Signal_gluinomI1800_fail_postfit_projx1__250->GetZaxis()->SetLabelSize(0.05);
   Signal_gluinomI1800_fail_postfit_projx1__250->GetZaxis()->SetTitleSize(0.08);
   Signal_gluinomI1800_fail_postfit_projx1__250->GetZaxis()->SetTitleFont(42);
   Signal_gluinomI1800_fail_postfit_projx1__250->Draw("hist same");
   Double_t xAxis379[10] = {0, 0.05, 0.1, 0.15, 0.2, 0.25, 0.3, 0.35, 0.4, 1}; 
   
   TH1D *Signal_ppStaumI557_fail_postfit_projx1__251 = new TH1D("Signal_ppStaumI557_fail_postfit_projx1__251","HSCP stau 557 GeV, fail, postfit, 200-200",9, xAxis379);
   Signal_ppStaumI557_fail_postfit_projx1__251->SetMinimum(0.001);
   Signal_ppStaumI557_fail_postfit_projx1__251->SetLineColor(2);
   Signal_ppStaumI557_fail_postfit_projx1__251->SetLineStyle(0);
   Signal_ppStaumI557_fail_postfit_projx1__251->SetLineWidth(2);
   Signal_ppStaumI557_fail_postfit_projx1__251->GetXaxis()->SetTitle("G_{i}^{Strips}");
   Signal_ppStaumI557_fail_postfit_projx1__251->GetXaxis()->SetLabelFont(42);
   Signal_ppStaumI557_fail_postfit_projx1__251->GetXaxis()->SetLabelOffset(0.007);
   Signal_ppStaumI557_fail_postfit_projx1__251->GetXaxis()->SetLabelSize(0.05);
   Signal_ppStaumI557_fail_postfit_projx1__251->GetXaxis()->SetTitleSize(0.08);
   Signal_ppStaumI557_fail_postfit_projx1__251->GetXaxis()->SetTitleOffset(0.9);
   Signal_ppStaumI557_fail_postfit_projx1__251->GetXaxis()->SetTitleFont(42);
   Signal_ppStaumI557_fail_postfit_projx1__251->GetYaxis()->SetTitle("Events / bin");
   Signal_ppStaumI557_fail_postfit_projx1__251->GetYaxis()->SetLabelFont(42);
   Signal_ppStaumI557_fail_postfit_projx1__251->GetYaxis()->SetLabelOffset(0.007);
   Signal_ppStaumI557_fail_postfit_projx1__251->GetYaxis()->SetLabelSize(0.05);
   Signal_ppStaumI557_fail_postfit_projx1__251->GetYaxis()->SetTitleSize(0.08);
   Signal_ppStaumI557_fail_postfit_projx1__251->GetYaxis()->SetTitleOffset(1.25);
   Signal_ppStaumI557_fail_postfit_projx1__251->GetYaxis()->SetTitleFont(42);
   Signal_ppStaumI557_fail_postfit_projx1__251->GetZaxis()->SetLabelFont(42);
   Signal_ppStaumI557_fail_postfit_projx1__251->GetZaxis()->SetLabelOffset(0.007);
   Signal_ppStaumI557_fail_postfit_projx1__251->GetZaxis()->SetLabelSize(0.05);
   Signal_ppStaumI557_fail_postfit_projx1__251->GetZaxis()->SetTitleSize(0.08);
   Signal_ppStaumI557_fail_postfit_projx1__251->GetZaxis()->SetTitleFont(42);
   Signal_ppStaumI557_fail_postfit_projx1__251->Draw("hist same");
   Double_t xAxis380[10] = {0, 0.05, 0.1, 0.15, 0.2, 0.25, 0.3, 0.35, 0.4, 1}; 
   
   TH1D *TotalBkg_fail_postfit_projx1__252 = new TH1D("TotalBkg_fail_postfit_projx1__252","TotalBkg, fail, postfit, 200-200",9, xAxis380);
   TotalBkg_fail_postfit_projx1__252->SetMinimum(0.001);
   TotalBkg_fail_postfit_projx1__252->SetLineStyle(0);
   TotalBkg_fail_postfit_projx1__252->SetMarkerStyle(0);
   TotalBkg_fail_postfit_projx1__252->GetXaxis()->SetTitle("G_{i}^{Strips}");
   TotalBkg_fail_postfit_projx1__252->GetXaxis()->SetLabelFont(42);
   TotalBkg_fail_postfit_projx1__252->GetXaxis()->SetLabelOffset(0.007);
   TotalBkg_fail_postfit_projx1__252->GetXaxis()->SetLabelSize(0.05);
   TotalBkg_fail_postfit_projx1__252->GetXaxis()->SetTitleSize(0.08);
   TotalBkg_fail_postfit_projx1__252->GetXaxis()->SetTitleOffset(0.9);
   TotalBkg_fail_postfit_projx1__252->GetXaxis()->SetTitleFont(42);
   TotalBkg_fail_postfit_projx1__252->GetYaxis()->SetTitle("Events / bin");
   TotalBkg_fail_postfit_projx1__252->GetYaxis()->SetLabelFont(42);
   TotalBkg_fail_postfit_projx1__252->GetYaxis()->SetLabelOffset(0.007);
   TotalBkg_fail_postfit_projx1__252->GetYaxis()->SetLabelSize(0.05);
   TotalBkg_fail_postfit_projx1__252->GetYaxis()->SetTitleSize(0.08);
   TotalBkg_fail_postfit_projx1__252->GetYaxis()->SetTitleOffset(1.25);
   TotalBkg_fail_postfit_projx1__252->GetYaxis()->SetTitleFont(42);
   TotalBkg_fail_postfit_projx1__252->GetZaxis()->SetLabelFont(42);
   TotalBkg_fail_postfit_projx1__252->GetZaxis()->SetLabelOffset(0.007);
   TotalBkg_fail_postfit_projx1__252->GetZaxis()->SetLabelSize(0.05);
   TotalBkg_fail_postfit_projx1__252->GetZaxis()->SetTitleSize(0.08);
   TotalBkg_fail_postfit_projx1__252->GetZaxis()->SetTitleFont(42);
   TotalBkg_fail_postfit_projx1__252->Draw("hist same");
   Double_t xAxis381[10] = {0, 0.05, 0.1, 0.15, 0.2, 0.25, 0.3, 0.35, 0.4, 1}; 
   
   TH1D *TotalBkg_fail_postfit_projx1__253 = new TH1D("TotalBkg_fail_postfit_projx1__253","TotalBkg, fail, postfit, 200-200",9, xAxis381);
   TotalBkg_fail_postfit_projx1__253->SetMinimum(0.001);
   TotalBkg_fail_postfit_projx1__253->SetFillColor(1);
   TotalBkg_fail_postfit_projx1__253->SetFillStyle(3354);
   TotalBkg_fail_postfit_projx1__253->SetLineStyle(0);
   TotalBkg_fail_postfit_projx1__253->SetLineWidth(0);
   TotalBkg_fail_postfit_projx1__253->SetMarkerStyle(0);
   TotalBkg_fail_postfit_projx1__253->GetXaxis()->SetTitle("G_{i}^{Strips}");
   TotalBkg_fail_postfit_projx1__253->GetXaxis()->SetLabelFont(42);
   TotalBkg_fail_postfit_projx1__253->GetXaxis()->SetLabelOffset(0.007);
   TotalBkg_fail_postfit_projx1__253->GetXaxis()->SetLabelSize(0.05);
   TotalBkg_fail_postfit_projx1__253->GetXaxis()->SetTitleSize(0.08);
   TotalBkg_fail_postfit_projx1__253->GetXaxis()->SetTitleOffset(0.9);
   TotalBkg_fail_postfit_projx1__253->GetXaxis()->SetTitleFont(42);
   TotalBkg_fail_postfit_projx1__253->GetYaxis()->SetTitle("Events / bin");
   TotalBkg_fail_postfit_projx1__253->GetYaxis()->SetLabelFont(42);
   TotalBkg_fail_postfit_projx1__253->GetYaxis()->SetLabelOffset(0.007);
   TotalBkg_fail_postfit_projx1__253->GetYaxis()->SetLabelSize(0.05);
   TotalBkg_fail_postfit_projx1__253->GetYaxis()->SetTitleSize(0.08);
   TotalBkg_fail_postfit_projx1__253->GetYaxis()->SetTitleOffset(1.25);
   TotalBkg_fail_postfit_projx1__253->GetYaxis()->SetTitleFont(42);
   TotalBkg_fail_postfit_projx1__253->GetZaxis()->SetLabelFont(42);
   TotalBkg_fail_postfit_projx1__253->GetZaxis()->SetLabelOffset(0.007);
   TotalBkg_fail_postfit_projx1__253->GetZaxis()->SetLabelSize(0.05);
   TotalBkg_fail_postfit_projx1__253->GetZaxis()->SetTitleSize(0.08);
   TotalBkg_fail_postfit_projx1__253->GetZaxis()->SetTitleFont(42);
   TotalBkg_fail_postfit_projx1__253->Draw("e2 same");
   Double_t xAxis382[10] = {0, 0.05, 0.1, 0.15, 0.2, 0.25, 0.3, 0.35, 0.4, 1}; 
   
   TH1D *data_obs_fail_postfit_projx1__254 = new TH1D("data_obs_fail_postfit_projx1__254","",9, xAxis382);
   data_obs_fail_postfit_projx1__254->SetMinimum(0.001);
   data_obs_fail_postfit_projx1__254->SetMaximum(0);

   ci = TColor::GetColor("#000000");
   data_obs_fail_postfit_projx1__254->SetLineColor(ci);
   data_obs_fail_postfit_projx1__254->SetLineStyle(0);

   ci = TColor::GetColor("#000000");
   data_obs_fail_postfit_projx1__254->SetMarkerColor(ci);
   data_obs_fail_postfit_projx1__254->SetMarkerStyle(8);
   data_obs_fail_postfit_projx1__254->GetXaxis()->SetTitle("G_{i}^{Strips}");
   data_obs_fail_postfit_projx1__254->GetXaxis()->SetLabelFont(42);
   data_obs_fail_postfit_projx1__254->GetXaxis()->SetLabelOffset(0.05);
   data_obs_fail_postfit_projx1__254->GetXaxis()->SetLabelSize(0.07);
   data_obs_fail_postfit_projx1__254->GetXaxis()->SetTitleSize(0.09);
   data_obs_fail_postfit_projx1__254->GetXaxis()->SetTitleOffset(1.15);
   data_obs_fail_postfit_projx1__254->GetXaxis()->SetTitleFont(42);
   data_obs_fail_postfit_projx1__254->GetYaxis()->SetTitle("Events / bin");
   data_obs_fail_postfit_projx1__254->GetYaxis()->SetNdivisions(508);
   data_obs_fail_postfit_projx1__254->GetYaxis()->SetLabelFont(42);
   data_obs_fail_postfit_projx1__254->GetYaxis()->SetLabelOffset(0.007);
   data_obs_fail_postfit_projx1__254->GetYaxis()->SetLabelSize(0.07);
   data_obs_fail_postfit_projx1__254->GetYaxis()->SetTitleSize(0.09);
   data_obs_fail_postfit_projx1__254->GetYaxis()->SetTitleOffset(0.8);
   data_obs_fail_postfit_projx1__254->GetYaxis()->SetTitleFont(42);
   data_obs_fail_postfit_projx1__254->GetZaxis()->SetLabelFont(42);
   data_obs_fail_postfit_projx1__254->GetZaxis()->SetLabelOffset(0.007);
   data_obs_fail_postfit_projx1__254->GetZaxis()->SetLabelSize(0.05);
   data_obs_fail_postfit_projx1__254->GetZaxis()->SetTitleSize(0.08);
   data_obs_fail_postfit_projx1__254->GetZaxis()->SetTitleFont(42);
   data_obs_fail_postfit_projx1__254->Draw("pe X0 same");
   
   TLegend *leg = new TLegend(0.65,0.61,0.9,0.88,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(1001);
   TLegendEntry *entry=leg->AddEntry("data_obs_fail_postfit_projx1","Data","pe X0");

   ci = TColor::GetColor("#000000");
   entry->SetLineColor(ci);
   entry->SetLineWidth(1);

   ci = TColor::GetColor("#000000");
   entry->SetMarkerColor(ci);
   entry->SetMarkerStyle(8);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("TotalBkg_fail_postfit_projx1","Total bkg unc.","F");
   entry->SetFillColor(1);
   entry->SetFillStyle(3354);
   entry->SetLineColor(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("Signal_gluino-1800_fail_postfit_projx1","HSCP gluino 1800 GeV","L");
   entry->SetLineColor(4);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("Signal_ppStau-557_fail_postfit_projx1","HSCP stau 557 GeV","L");
   entry->SetLineColor(2);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("Background_fail_postfit_projx1_stack_1_stack_1","Background","f");

   ci = TColor::GetColor("#ffff00");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = 1330;
   color = new TColor(ci, 1, 1, 1, " ", 0);
   entry->SetLineColor(ci);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   leg->Draw();
   Double_t xAxis383[10] = {0, 0.05, 0.1, 0.15, 0.2, 0.25, 0.3, 0.35, 0.4, 1}; 
   
   TH1D *data_obs_fail_postfit_projx1_copy__255 = new TH1D("data_obs_fail_postfit_projx1_copy__255","",9, xAxis383);
   data_obs_fail_postfit_projx1_copy__255->SetMinimum(0.001);
   data_obs_fail_postfit_projx1_copy__255->SetMaximum(0);
   data_obs_fail_postfit_projx1_copy__255->SetDirectory(0);

   ci = TColor::GetColor("#000000");
   data_obs_fail_postfit_projx1_copy__255->SetLineColor(ci);
   data_obs_fail_postfit_projx1_copy__255->SetLineStyle(0);

   ci = TColor::GetColor("#000000");
   data_obs_fail_postfit_projx1_copy__255->SetMarkerColor(ci);
   data_obs_fail_postfit_projx1_copy__255->SetMarkerStyle(8);
   data_obs_fail_postfit_projx1_copy__255->GetXaxis()->SetTitle("G_{i}^{Strips}");
   data_obs_fail_postfit_projx1_copy__255->GetXaxis()->SetLabelFont(42);
   data_obs_fail_postfit_projx1_copy__255->GetXaxis()->SetLabelOffset(0.05);
   data_obs_fail_postfit_projx1_copy__255->GetXaxis()->SetLabelSize(0.07);
   data_obs_fail_postfit_projx1_copy__255->GetXaxis()->SetTitleSize(0.09);
   data_obs_fail_postfit_projx1_copy__255->GetXaxis()->SetTitleOffset(1.15);
   data_obs_fail_postfit_projx1_copy__255->GetXaxis()->SetTitleFont(42);
   data_obs_fail_postfit_projx1_copy__255->GetYaxis()->SetTitle("Events / bin");
   data_obs_fail_postfit_projx1_copy__255->GetYaxis()->SetNdivisions(508);
   data_obs_fail_postfit_projx1_copy__255->GetYaxis()->SetLabelFont(42);
   data_obs_fail_postfit_projx1_copy__255->GetYaxis()->SetLabelOffset(0.007);
   data_obs_fail_postfit_projx1_copy__255->GetYaxis()->SetLabelSize(0.07);
   data_obs_fail_postfit_projx1_copy__255->GetYaxis()->SetTitleSize(0.09);
   data_obs_fail_postfit_projx1_copy__255->GetYaxis()->SetTitleOffset(0.8);
   data_obs_fail_postfit_projx1_copy__255->GetYaxis()->SetTitleFont(42);
   data_obs_fail_postfit_projx1_copy__255->GetZaxis()->SetLabelFont(42);
   data_obs_fail_postfit_projx1_copy__255->GetZaxis()->SetLabelOffset(0.007);
   data_obs_fail_postfit_projx1_copy__255->GetZaxis()->SetLabelSize(0.05);
   data_obs_fail_postfit_projx1_copy__255->GetZaxis()->SetTitleSize(0.08);
   data_obs_fail_postfit_projx1_copy__255->GetZaxis()->SetTitleFont(42);
   data_obs_fail_postfit_projx1_copy__255->Draw("sameaxis");
   TLatex *   tex = new TLatex(0.21,0.83,"200 < p_{T} < 200 , F^{Pixels}_{i} < 0.9");
tex->SetNDC();
   tex->SetTextAlign(12);
   tex->SetTextFont(42);
   tex->SetTextSize(0.06);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.17,0.92,"CMS");
tex->SetNDC();
   tex->SetTextFont(61);
   tex->SetTextSize(0.0675);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.25,0.92,"Preliminary");
tex->SetNDC();
   tex->SetTextFont(52);
   tex->SetTextSize(0.0485);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.95,0.92,"101 fb^{-1} (13 TeV)");
tex->SetNDC();
   tex->SetTextAlign(31);
   tex->SetTextFont(42);
   tex->SetTextSize(0.07);
   tex->SetLineWidth(2);
   tex->Draw();
   data_obs_fail_postfit_projx1_main->Modified();
   plots_fit_s/base_figs/postfit_projx1_fail_logy->cd();
  
// ------------>Primitives in pad: data_obs_fail_postfit_projx1_sub
   TPad *data_obs_fail_postfit_projx1_sub = new TPad("data_obs_fail_postfit_projx1_sub", "data_obs_fail_postfit_projx1_sub",0,0,1,0.35);
   data_obs_fail_postfit_projx1_sub->Draw();
   data_obs_fail_postfit_projx1_sub->cd();
   data_obs_fail_postfit_projx1_sub->Range(-0.2179487,-6.023077,1.064103,2.9);
   data_obs_fail_postfit_projx1_sub->SetFillColor(0);
   data_obs_fail_postfit_projx1_sub->SetBorderMode(0);
   data_obs_fail_postfit_projx1_sub->SetBorderSize(2);
   data_obs_fail_postfit_projx1_sub->SetTickx(1);
   data_obs_fail_postfit_projx1_sub->SetTicky(1);
   data_obs_fail_postfit_projx1_sub->SetLeftMargin(0.17);
   data_obs_fail_postfit_projx1_sub->SetRightMargin(0.05);
   data_obs_fail_postfit_projx1_sub->SetTopMargin(0);
   data_obs_fail_postfit_projx1_sub->SetBottomMargin(0.35);
   data_obs_fail_postfit_projx1_sub->SetFrameFillStyle(0);
   data_obs_fail_postfit_projx1_sub->SetFrameBorderMode(0);
   data_obs_fail_postfit_projx1_sub->SetFrameFillStyle(0);
   data_obs_fail_postfit_projx1_sub->SetFrameBorderMode(0);
   Double_t xAxis384[10] = {0, 0.05, 0.1, 0.15, 0.2, 0.25, 0.3, 0.35, 0.4, 1}; 
   
   TH1D *data_obs_fail_postfit_projx1_pull__256 = new TH1D("data_obs_fail_postfit_projx1_pull__256","",9, xAxis384);
   data_obs_fail_postfit_projx1_pull__256->SetMinimum(-2.9);
   data_obs_fail_postfit_projx1_pull__256->SetMaximum(2.9);
   data_obs_fail_postfit_projx1_pull__256->SetEntries(18);
   data_obs_fail_postfit_projx1_pull__256->SetStats(0);

   ci = TColor::GetColor("#0000ff");
   data_obs_fail_postfit_projx1_pull__256->SetFillColor(ci);

   ci = TColor::GetColor("#000000");
   data_obs_fail_postfit_projx1_pull__256->SetLineColor(ci);
   data_obs_fail_postfit_projx1_pull__256->SetLineStyle(0);

   ci = TColor::GetColor("#000000");
   data_obs_fail_postfit_projx1_pull__256->SetMarkerColor(ci);
   data_obs_fail_postfit_projx1_pull__256->SetMarkerStyle(8);
   data_obs_fail_postfit_projx1_pull__256->GetXaxis()->SetTitle("G_{i}^{Strips}");
   data_obs_fail_postfit_projx1_pull__256->GetXaxis()->SetLabelFont(42);
   data_obs_fail_postfit_projx1_pull__256->GetXaxis()->SetLabelOffset(0.05);
   data_obs_fail_postfit_projx1_pull__256->GetXaxis()->SetLabelSize(0.13);
   data_obs_fail_postfit_projx1_pull__256->GetXaxis()->SetTitleSize(0.15);
   data_obs_fail_postfit_projx1_pull__256->GetXaxis()->SetTitleOffset(1.15);
   data_obs_fail_postfit_projx1_pull__256->GetXaxis()->SetTitleFont(42);
   data_obs_fail_postfit_projx1_pull__256->GetYaxis()->SetTitle("(Data-Bkg)/#sigma");
   data_obs_fail_postfit_projx1_pull__256->GetYaxis()->SetNdivisions(306);
   data_obs_fail_postfit_projx1_pull__256->GetYaxis()->SetLabelFont(42);
   data_obs_fail_postfit_projx1_pull__256->GetYaxis()->SetLabelOffset(0.007);
   data_obs_fail_postfit_projx1_pull__256->GetYaxis()->SetLabelSize(0.13);
   data_obs_fail_postfit_projx1_pull__256->GetYaxis()->SetTitleSize(0.12);
   data_obs_fail_postfit_projx1_pull__256->GetYaxis()->SetTitleOffset(0.4);
   data_obs_fail_postfit_projx1_pull__256->GetYaxis()->SetTitleFont(42);
   data_obs_fail_postfit_projx1_pull__256->GetZaxis()->SetLabelFont(42);
   data_obs_fail_postfit_projx1_pull__256->GetZaxis()->SetLabelOffset(0.007);
   data_obs_fail_postfit_projx1_pull__256->GetZaxis()->SetLabelSize(0.05);
   data_obs_fail_postfit_projx1_pull__256->GetZaxis()->SetTitleSize(0.08);
   data_obs_fail_postfit_projx1_pull__256->GetZaxis()->SetTitleFont(42);
   data_obs_fail_postfit_projx1_pull__256->Draw("hist");
   data_obs_fail_postfit_projx1_sub->Modified();
   plots_fit_s/base_figs/postfit_projx1_fail_logy->cd();
   plots_fit_s/base_figs/postfit_projx1_fail_logy->Modified();
   plots_fit_s/base_figs/postfit_projx1_fail_logy->cd();
   plots_fit_s/base_figs/postfit_projx1_fail_logy->SetSelected(plots_fit_s/base_figs/postfit_projx1_fail_logy);
}
