void postfit_projy0_pass()
{
//=========Macro generated from canvas: plots_fit_s/base_figs/postfit_projy0_pass/plots_fit_s/base_figs/postfit_projy0_pass
//=========  (Fri Jan 12 20:33:24 2024) by ROOT version 6.14/09
   TCanvas *plots_fit_s/base_figs/postfit_projy0_pass = new TCanvas("plots_fit_s/base_figs/postfit_projy0_pass", "plots_fit_s/base_figs/postfit_projy0_pass",0,0,800,700);
   gStyle->SetOptFit(1);
   gStyle->SetOptStat(0);
   plots_fit_s/base_figs/postfit_projy0_pass->SetHighLightColor(2);
   plots_fit_s/base_figs/postfit_projy0_pass->Range(0,0,1,1);
   plots_fit_s/base_figs/postfit_projy0_pass->SetFillColor(0);
   plots_fit_s/base_figs/postfit_projy0_pass->SetBorderMode(0);
   plots_fit_s/base_figs/postfit_projy0_pass->SetBorderSize(2);
   plots_fit_s/base_figs/postfit_projy0_pass->SetTickx(1);
   plots_fit_s/base_figs/postfit_projy0_pass->SetTicky(1);
   plots_fit_s/base_figs/postfit_projy0_pass->SetLeftMargin(0.16);
   plots_fit_s/base_figs/postfit_projy0_pass->SetRightMargin(0);
   plots_fit_s/base_figs/postfit_projy0_pass->SetTopMargin(0);
   plots_fit_s/base_figs/postfit_projy0_pass->SetBottomMargin(0);
   plots_fit_s/base_figs/postfit_projy0_pass->SetFrameFillStyle(0);
   plots_fit_s/base_figs/postfit_projy0_pass->SetFrameBorderMode(0);
  
// ------------>Primitives in pad: data_obs_pass_postfit_projy0_main
   TPad *data_obs_pass_postfit_projy0_main = new TPad("data_obs_pass_postfit_projy0_main", "data_obs_pass_postfit_projy0_main",0,0.35,1,1);
   data_obs_pass_postfit_projy0_main->Draw();
   data_obs_pass_postfit_projy0_main->cd();
   data_obs_pass_postfit_projy0_main->Range(-633.6539,-2560.73,4270.192,61457.53);
   data_obs_pass_postfit_projy0_main->SetFillColor(0);
   data_obs_pass_postfit_projy0_main->SetBorderMode(0);
   data_obs_pass_postfit_projy0_main->SetBorderSize(2);
   data_obs_pass_postfit_projy0_main->SetTickx(1);
   data_obs_pass_postfit_projy0_main->SetTicky(1);
   data_obs_pass_postfit_projy0_main->SetLeftMargin(0.17);
   data_obs_pass_postfit_projy0_main->SetRightMargin(0.05);
   data_obs_pass_postfit_projy0_main->SetBottomMargin(0.04);
   data_obs_pass_postfit_projy0_main->SetFrameFillStyle(0);
   data_obs_pass_postfit_projy0_main->SetFrameBorderMode(0);
   data_obs_pass_postfit_projy0_main->SetFrameFillStyle(0);
   data_obs_pass_postfit_projy0_main->SetFrameBorderMode(0);
   Double_t xAxis469[2] = {200, 4025}; 
   
   TH1D *data_obs_pass_postfit_projy0__313 = new TH1D("data_obs_pass_postfit_projy0__313","",1, xAxis469);
   data_obs_pass_postfit_projy0__313->SetBinContent(1,40782);
   data_obs_pass_postfit_projy0__313->SetBinError(1,201.9455);
   data_obs_pass_postfit_projy0__313->SetMinimum(0);
   data_obs_pass_postfit_projy0__313->SetMaximum(55055.7);
   data_obs_pass_postfit_projy0__313->SetEntries(40782);

   Int_t ci;      // for color index setting
   TColor *color; // for color definition with alpha
   ci = TColor::GetColor("#000000");
   data_obs_pass_postfit_projy0__313->SetLineColor(ci);
   data_obs_pass_postfit_projy0__313->SetLineStyle(0);

   ci = TColor::GetColor("#000000");
   data_obs_pass_postfit_projy0__313->SetMarkerColor(ci);
   data_obs_pass_postfit_projy0__313->SetMarkerStyle(8);
   data_obs_pass_postfit_projy0__313->GetXaxis()->SetTitle("p_{T}");
   data_obs_pass_postfit_projy0__313->GetXaxis()->SetLabelFont(42);
   data_obs_pass_postfit_projy0__313->GetXaxis()->SetLabelOffset(0.05);
   data_obs_pass_postfit_projy0__313->GetXaxis()->SetLabelSize(0.07);
   data_obs_pass_postfit_projy0__313->GetXaxis()->SetTitleSize(0.09);
   data_obs_pass_postfit_projy0__313->GetXaxis()->SetTitleOffset(1.15);
   data_obs_pass_postfit_projy0__313->GetXaxis()->SetTitleFont(42);
   data_obs_pass_postfit_projy0__313->GetYaxis()->SetTitle("Events / bin");
   data_obs_pass_postfit_projy0__313->GetYaxis()->SetNdivisions(508);
   data_obs_pass_postfit_projy0__313->GetYaxis()->SetLabelFont(42);
   data_obs_pass_postfit_projy0__313->GetYaxis()->SetLabelOffset(0.007);
   data_obs_pass_postfit_projy0__313->GetYaxis()->SetLabelSize(0.07);
   data_obs_pass_postfit_projy0__313->GetYaxis()->SetTitleSize(0.09);
   data_obs_pass_postfit_projy0__313->GetYaxis()->SetTitleOffset(0.8);
   data_obs_pass_postfit_projy0__313->GetYaxis()->SetTitleFont(42);
   data_obs_pass_postfit_projy0__313->GetZaxis()->SetLabelFont(42);
   data_obs_pass_postfit_projy0__313->GetZaxis()->SetLabelOffset(0.007);
   data_obs_pass_postfit_projy0__313->GetZaxis()->SetLabelSize(0.05);
   data_obs_pass_postfit_projy0__313->GetZaxis()->SetTitleSize(0.08);
   data_obs_pass_postfit_projy0__313->GetZaxis()->SetTitleFont(42);
   data_obs_pass_postfit_projy0__313->Draw("pe X0");
   
   THStack *postfit_projy0_pass_stack = new THStack();
   postfit_projy0_pass_stack->SetName("postfit_projy0_pass_stack");
   postfit_projy0_pass_stack->SetTitle("postfit_projy0_pass_stack");
   Double_t xAxis470[2] = {200, 4025}; 
   
   TH1F *postfit_projy0_pass_stack_stack_79 = new TH1F("postfit_projy0_pass_stack_stack_79","postfit_projy0_pass_stack",1, xAxis470);
   postfit_projy0_pass_stack_stack_79->SetMinimum(0);
   postfit_projy0_pass_stack_stack_79->SetMaximum(42985.6);
   postfit_projy0_pass_stack_stack_79->SetDirectory(0);
   postfit_projy0_pass_stack_stack_79->SetStats(0);
   postfit_projy0_pass_stack_stack_79->SetLineStyle(0);
   postfit_projy0_pass_stack_stack_79->GetXaxis()->SetLabelFont(42);
   postfit_projy0_pass_stack_stack_79->GetXaxis()->SetLabelOffset(0.007);
   postfit_projy0_pass_stack_stack_79->GetXaxis()->SetLabelSize(0.05);
   postfit_projy0_pass_stack_stack_79->GetXaxis()->SetTitleSize(0.08);
   postfit_projy0_pass_stack_stack_79->GetXaxis()->SetTitleOffset(0.9);
   postfit_projy0_pass_stack_stack_79->GetXaxis()->SetTitleFont(42);
   postfit_projy0_pass_stack_stack_79->GetYaxis()->SetNdivisions(508);
   postfit_projy0_pass_stack_stack_79->GetYaxis()->SetLabelFont(42);
   postfit_projy0_pass_stack_stack_79->GetYaxis()->SetLabelOffset(0.007);
   postfit_projy0_pass_stack_stack_79->GetYaxis()->SetLabelSize(0.05);
   postfit_projy0_pass_stack_stack_79->GetYaxis()->SetTitleSize(0.08);
   postfit_projy0_pass_stack_stack_79->GetYaxis()->SetTitleOffset(1.25);
   postfit_projy0_pass_stack_stack_79->GetYaxis()->SetTitleFont(42);
   postfit_projy0_pass_stack_stack_79->GetZaxis()->SetLabelFont(42);
   postfit_projy0_pass_stack_stack_79->GetZaxis()->SetLabelOffset(0.007);
   postfit_projy0_pass_stack_stack_79->GetZaxis()->SetLabelSize(0.05);
   postfit_projy0_pass_stack_stack_79->GetZaxis()->SetTitleSize(0.08);
   postfit_projy0_pass_stack_stack_79->GetZaxis()->SetTitleFont(42);
   postfit_projy0_pass_stack->SetHistogram(postfit_projy0_pass_stack_stack_79);
   
   Double_t xAxis471[2] = {200, 4025}; 
   
   TH1D *Background_0x0_pass_postfit_projy0_stack_1 = new TH1D("Background_0x0_pass_postfit_projy0_stack_1","Background, pass, postfit, 0.0-0.25",1, xAxis471);
   Background_0x0_pass_postfit_projy0_stack_1->SetBinContent(1,40775.21);
   Background_0x0_pass_postfit_projy0_stack_1->SetBinError(1,163.4513);
   Background_0x0_pass_postfit_projy0_stack_1->SetMinimum(0);
   Background_0x0_pass_postfit_projy0_stack_1->SetEntries(62232.25);

   ci = TColor::GetColor("#ffff00");
   Background_0x0_pass_postfit_projy0_stack_1->SetFillColor(ci);

   ci = 1344;
   color = new TColor(ci, 1, 1, 1, " ", 0);
   Background_0x0_pass_postfit_projy0_stack_1->SetLineColor(ci);
   Background_0x0_pass_postfit_projy0_stack_1->SetLineStyle(0);
   Background_0x0_pass_postfit_projy0_stack_1->GetXaxis()->SetTitle("p_{T}");
   Background_0x0_pass_postfit_projy0_stack_1->GetXaxis()->SetLabelFont(42);
   Background_0x0_pass_postfit_projy0_stack_1->GetXaxis()->SetLabelOffset(0.007);
   Background_0x0_pass_postfit_projy0_stack_1->GetXaxis()->SetLabelSize(0.05);
   Background_0x0_pass_postfit_projy0_stack_1->GetXaxis()->SetTitleSize(0.08);
   Background_0x0_pass_postfit_projy0_stack_1->GetXaxis()->SetTitleOffset(1.25);
   Background_0x0_pass_postfit_projy0_stack_1->GetXaxis()->SetTitleFont(42);
   Background_0x0_pass_postfit_projy0_stack_1->GetYaxis()->SetTitle("Events / bin");
   Background_0x0_pass_postfit_projy0_stack_1->GetYaxis()->SetLabelFont(42);
   Background_0x0_pass_postfit_projy0_stack_1->GetYaxis()->SetLabelOffset(0.007);
   Background_0x0_pass_postfit_projy0_stack_1->GetYaxis()->SetLabelSize(0.05);
   Background_0x0_pass_postfit_projy0_stack_1->GetYaxis()->SetTitleSize(0.08);
   Background_0x0_pass_postfit_projy0_stack_1->GetYaxis()->SetTitleOffset(1.25);
   Background_0x0_pass_postfit_projy0_stack_1->GetYaxis()->SetTitleFont(42);
   Background_0x0_pass_postfit_projy0_stack_1->GetZaxis()->SetLabelFont(42);
   Background_0x0_pass_postfit_projy0_stack_1->GetZaxis()->SetLabelOffset(0.007);
   Background_0x0_pass_postfit_projy0_stack_1->GetZaxis()->SetLabelSize(0.05);
   Background_0x0_pass_postfit_projy0_stack_1->GetZaxis()->SetTitleSize(0.08);
   Background_0x0_pass_postfit_projy0_stack_1->GetZaxis()->SetTitleFont(42);
   postfit_projy0_pass_stack->Add(Background_0x0_pass_postfit_projy0_stack_1,"");
   postfit_projy0_pass_stack->Draw("hist same");
   
   postfit_projy0_pass_stack = new THStack();
   postfit_projy0_pass_stack->SetName("postfit_projy0_pass_stack");
   postfit_projy0_pass_stack->SetTitle("postfit_projy0_pass_stack");
   Double_t xAxis472[2] = {200, 4025}; 
   
   TH1F *postfit_projy0_pass_stack_stack_79_stack_80 = new TH1F("postfit_projy0_pass_stack_stack_79_stack_80","postfit_projy0_pass_stack",1, xAxis472);
   postfit_projy0_pass_stack_stack_79_stack_80->SetMinimum(0);
   postfit_projy0_pass_stack_stack_79_stack_80->SetMaximum(42985.6);
   postfit_projy0_pass_stack_stack_79_stack_80->SetDirectory(0);
   postfit_projy0_pass_stack_stack_79_stack_80->SetStats(0);
   postfit_projy0_pass_stack_stack_79_stack_80->SetLineStyle(0);
   postfit_projy0_pass_stack_stack_79_stack_80->GetXaxis()->SetLabelFont(42);
   postfit_projy0_pass_stack_stack_79_stack_80->GetXaxis()->SetLabelOffset(0.007);
   postfit_projy0_pass_stack_stack_79_stack_80->GetXaxis()->SetLabelSize(0.05);
   postfit_projy0_pass_stack_stack_79_stack_80->GetXaxis()->SetTitleSize(0.08);
   postfit_projy0_pass_stack_stack_79_stack_80->GetXaxis()->SetTitleOffset(0.9);
   postfit_projy0_pass_stack_stack_79_stack_80->GetXaxis()->SetTitleFont(42);
   postfit_projy0_pass_stack_stack_79_stack_80->GetYaxis()->SetNdivisions(508);
   postfit_projy0_pass_stack_stack_79_stack_80->GetYaxis()->SetLabelFont(42);
   postfit_projy0_pass_stack_stack_79_stack_80->GetYaxis()->SetLabelOffset(0.007);
   postfit_projy0_pass_stack_stack_79_stack_80->GetYaxis()->SetLabelSize(0.05);
   postfit_projy0_pass_stack_stack_79_stack_80->GetYaxis()->SetTitleSize(0.08);
   postfit_projy0_pass_stack_stack_79_stack_80->GetYaxis()->SetTitleOffset(1.25);
   postfit_projy0_pass_stack_stack_79_stack_80->GetYaxis()->SetTitleFont(42);
   postfit_projy0_pass_stack_stack_79_stack_80->GetZaxis()->SetLabelFont(42);
   postfit_projy0_pass_stack_stack_79_stack_80->GetZaxis()->SetLabelOffset(0.007);
   postfit_projy0_pass_stack_stack_79_stack_80->GetZaxis()->SetLabelSize(0.05);
   postfit_projy0_pass_stack_stack_79_stack_80->GetZaxis()->SetTitleSize(0.08);
   postfit_projy0_pass_stack_stack_79_stack_80->GetZaxis()->SetTitleFont(42);
   postfit_projy0_pass_stack->SetHistogram(postfit_projy0_pass_stack_stack_79_stack_80);
   
   Double_t xAxis473[2] = {200, 4025}; 
   
   TH1D *Background_0x0_pass_postfit_projy0_stack_1_stack_1 = new TH1D("Background_0x0_pass_postfit_projy0_stack_1_stack_1","Background, pass, postfit, 0.0-0.25",1, xAxis473);
   Background_0x0_pass_postfit_projy0_stack_1_stack_1->SetBinContent(1,40775.21);
   Background_0x0_pass_postfit_projy0_stack_1_stack_1->SetBinError(1,163.4513);
   Background_0x0_pass_postfit_projy0_stack_1_stack_1->SetMinimum(0);
   Background_0x0_pass_postfit_projy0_stack_1_stack_1->SetEntries(62232.25);

   ci = TColor::GetColor("#ffff00");
   Background_0x0_pass_postfit_projy0_stack_1_stack_1->SetFillColor(ci);

   ci = 1344;
   color = new TColor(ci, 1, 1, 1, " ", 0);
   Background_0x0_pass_postfit_projy0_stack_1_stack_1->SetLineColor(ci);
   Background_0x0_pass_postfit_projy0_stack_1_stack_1->SetLineStyle(0);
   Background_0x0_pass_postfit_projy0_stack_1_stack_1->GetXaxis()->SetTitle("p_{T}");
   Background_0x0_pass_postfit_projy0_stack_1_stack_1->GetXaxis()->SetLabelFont(42);
   Background_0x0_pass_postfit_projy0_stack_1_stack_1->GetXaxis()->SetLabelOffset(0.007);
   Background_0x0_pass_postfit_projy0_stack_1_stack_1->GetXaxis()->SetLabelSize(0.05);
   Background_0x0_pass_postfit_projy0_stack_1_stack_1->GetXaxis()->SetTitleSize(0.08);
   Background_0x0_pass_postfit_projy0_stack_1_stack_1->GetXaxis()->SetTitleOffset(1.25);
   Background_0x0_pass_postfit_projy0_stack_1_stack_1->GetXaxis()->SetTitleFont(42);
   Background_0x0_pass_postfit_projy0_stack_1_stack_1->GetYaxis()->SetTitle("Events / bin");
   Background_0x0_pass_postfit_projy0_stack_1_stack_1->GetYaxis()->SetLabelFont(42);
   Background_0x0_pass_postfit_projy0_stack_1_stack_1->GetYaxis()->SetLabelOffset(0.007);
   Background_0x0_pass_postfit_projy0_stack_1_stack_1->GetYaxis()->SetLabelSize(0.05);
   Background_0x0_pass_postfit_projy0_stack_1_stack_1->GetYaxis()->SetTitleSize(0.08);
   Background_0x0_pass_postfit_projy0_stack_1_stack_1->GetYaxis()->SetTitleOffset(1.25);
   Background_0x0_pass_postfit_projy0_stack_1_stack_1->GetYaxis()->SetTitleFont(42);
   Background_0x0_pass_postfit_projy0_stack_1_stack_1->GetZaxis()->SetLabelFont(42);
   Background_0x0_pass_postfit_projy0_stack_1_stack_1->GetZaxis()->SetLabelOffset(0.007);
   Background_0x0_pass_postfit_projy0_stack_1_stack_1->GetZaxis()->SetLabelSize(0.05);
   Background_0x0_pass_postfit_projy0_stack_1_stack_1->GetZaxis()->SetTitleSize(0.08);
   Background_0x0_pass_postfit_projy0_stack_1_stack_1->GetZaxis()->SetTitleFont(42);
   postfit_projy0_pass_stack->Add(Background_0x0_pass_postfit_projy0_stack_1_stack_1,"");
   postfit_projy0_pass_stack->Draw("hist same");
   Double_t xAxis474[2] = {200, 4025}; 
   
   TH1D *Signal_gluinomI1800_pass_postfit_projy0__314 = new TH1D("Signal_gluinomI1800_pass_postfit_projy0__314","HSCP gluino 1800 GeV, pass, postfit, 0.0-0.25",1, xAxis474);
   Signal_gluinomI1800_pass_postfit_projy0__314->SetBinContent(1,0.00696533);
   Signal_gluinomI1800_pass_postfit_projy0__314->SetBinError(1,0.005319221);
   Signal_gluinomI1800_pass_postfit_projy0__314->SetMinimum(0);
   Signal_gluinomI1800_pass_postfit_projy0__314->SetEntries(1.714697);
   Signal_gluinomI1800_pass_postfit_projy0__314->SetLineColor(4);
   Signal_gluinomI1800_pass_postfit_projy0__314->SetLineStyle(0);
   Signal_gluinomI1800_pass_postfit_projy0__314->SetLineWidth(2);
   Signal_gluinomI1800_pass_postfit_projy0__314->GetXaxis()->SetTitle("p_{T}");
   Signal_gluinomI1800_pass_postfit_projy0__314->GetXaxis()->SetLabelFont(42);
   Signal_gluinomI1800_pass_postfit_projy0__314->GetXaxis()->SetLabelOffset(0.007);
   Signal_gluinomI1800_pass_postfit_projy0__314->GetXaxis()->SetLabelSize(0.05);
   Signal_gluinomI1800_pass_postfit_projy0__314->GetXaxis()->SetTitleSize(0.08);
   Signal_gluinomI1800_pass_postfit_projy0__314->GetXaxis()->SetTitleOffset(1.25);
   Signal_gluinomI1800_pass_postfit_projy0__314->GetXaxis()->SetTitleFont(42);
   Signal_gluinomI1800_pass_postfit_projy0__314->GetYaxis()->SetTitle("Events / bin");
   Signal_gluinomI1800_pass_postfit_projy0__314->GetYaxis()->SetLabelFont(42);
   Signal_gluinomI1800_pass_postfit_projy0__314->GetYaxis()->SetLabelOffset(0.007);
   Signal_gluinomI1800_pass_postfit_projy0__314->GetYaxis()->SetLabelSize(0.05);
   Signal_gluinomI1800_pass_postfit_projy0__314->GetYaxis()->SetTitleSize(0.08);
   Signal_gluinomI1800_pass_postfit_projy0__314->GetYaxis()->SetTitleOffset(1.25);
   Signal_gluinomI1800_pass_postfit_projy0__314->GetYaxis()->SetTitleFont(42);
   Signal_gluinomI1800_pass_postfit_projy0__314->GetZaxis()->SetLabelFont(42);
   Signal_gluinomI1800_pass_postfit_projy0__314->GetZaxis()->SetLabelOffset(0.007);
   Signal_gluinomI1800_pass_postfit_projy0__314->GetZaxis()->SetLabelSize(0.05);
   Signal_gluinomI1800_pass_postfit_projy0__314->GetZaxis()->SetTitleSize(0.08);
   Signal_gluinomI1800_pass_postfit_projy0__314->GetZaxis()->SetTitleFont(42);
   Signal_gluinomI1800_pass_postfit_projy0__314->Draw("hist same");
   Double_t xAxis475[2] = {200, 4025}; 
   
   TH1D *Signal_ppStaumI557_pass_postfit_projy0__315 = new TH1D("Signal_ppStaumI557_pass_postfit_projy0__315","HSCP stau 557 GeV, pass, postfit, 0.0-0.25",1, xAxis475);
   Signal_ppStaumI557_pass_postfit_projy0__315->SetBinContent(1,0.04950573);
   Signal_ppStaumI557_pass_postfit_projy0__315->SetBinError(1,0.02597917);
   Signal_ppStaumI557_pass_postfit_projy0__315->SetMinimum(0);
   Signal_ppStaumI557_pass_postfit_projy0__315->SetEntries(3.631285);
   Signal_ppStaumI557_pass_postfit_projy0__315->SetLineColor(2);
   Signal_ppStaumI557_pass_postfit_projy0__315->SetLineStyle(0);
   Signal_ppStaumI557_pass_postfit_projy0__315->SetLineWidth(2);
   Signal_ppStaumI557_pass_postfit_projy0__315->GetXaxis()->SetTitle("p_{T}");
   Signal_ppStaumI557_pass_postfit_projy0__315->GetXaxis()->SetLabelFont(42);
   Signal_ppStaumI557_pass_postfit_projy0__315->GetXaxis()->SetLabelOffset(0.007);
   Signal_ppStaumI557_pass_postfit_projy0__315->GetXaxis()->SetLabelSize(0.05);
   Signal_ppStaumI557_pass_postfit_projy0__315->GetXaxis()->SetTitleSize(0.08);
   Signal_ppStaumI557_pass_postfit_projy0__315->GetXaxis()->SetTitleOffset(1.25);
   Signal_ppStaumI557_pass_postfit_projy0__315->GetXaxis()->SetTitleFont(42);
   Signal_ppStaumI557_pass_postfit_projy0__315->GetYaxis()->SetTitle("Events / bin");
   Signal_ppStaumI557_pass_postfit_projy0__315->GetYaxis()->SetLabelFont(42);
   Signal_ppStaumI557_pass_postfit_projy0__315->GetYaxis()->SetLabelOffset(0.007);
   Signal_ppStaumI557_pass_postfit_projy0__315->GetYaxis()->SetLabelSize(0.05);
   Signal_ppStaumI557_pass_postfit_projy0__315->GetYaxis()->SetTitleSize(0.08);
   Signal_ppStaumI557_pass_postfit_projy0__315->GetYaxis()->SetTitleOffset(1.25);
   Signal_ppStaumI557_pass_postfit_projy0__315->GetYaxis()->SetTitleFont(42);
   Signal_ppStaumI557_pass_postfit_projy0__315->GetZaxis()->SetLabelFont(42);
   Signal_ppStaumI557_pass_postfit_projy0__315->GetZaxis()->SetLabelOffset(0.007);
   Signal_ppStaumI557_pass_postfit_projy0__315->GetZaxis()->SetLabelSize(0.05);
   Signal_ppStaumI557_pass_postfit_projy0__315->GetZaxis()->SetTitleSize(0.08);
   Signal_ppStaumI557_pass_postfit_projy0__315->GetZaxis()->SetTitleFont(42);
   Signal_ppStaumI557_pass_postfit_projy0__315->Draw("hist same");
   Double_t xAxis476[2] = {200, 4025}; 
   
   TH1D *TotalBkg_pass_postfit_projy0__316 = new TH1D("TotalBkg_pass_postfit_projy0__316","TotalBkg, pass, postfit, 0.0-0.25",1, xAxis476);
   TotalBkg_pass_postfit_projy0__316->SetBinContent(1,40775.21);
   TotalBkg_pass_postfit_projy0__316->SetBinError(1,187.7497);
   TotalBkg_pass_postfit_projy0__316->SetMinimum(0);
   TotalBkg_pass_postfit_projy0__316->SetEntries(47166.54);
   TotalBkg_pass_postfit_projy0__316->SetLineStyle(0);
   TotalBkg_pass_postfit_projy0__316->SetMarkerStyle(0);
   TotalBkg_pass_postfit_projy0__316->GetXaxis()->SetTitle("p_{T}");
   TotalBkg_pass_postfit_projy0__316->GetXaxis()->SetLabelFont(42);
   TotalBkg_pass_postfit_projy0__316->GetXaxis()->SetLabelOffset(0.007);
   TotalBkg_pass_postfit_projy0__316->GetXaxis()->SetLabelSize(0.05);
   TotalBkg_pass_postfit_projy0__316->GetXaxis()->SetTitleSize(0.08);
   TotalBkg_pass_postfit_projy0__316->GetXaxis()->SetTitleOffset(1.25);
   TotalBkg_pass_postfit_projy0__316->GetXaxis()->SetTitleFont(42);
   TotalBkg_pass_postfit_projy0__316->GetYaxis()->SetTitle("Events / bin");
   TotalBkg_pass_postfit_projy0__316->GetYaxis()->SetLabelFont(42);
   TotalBkg_pass_postfit_projy0__316->GetYaxis()->SetLabelOffset(0.007);
   TotalBkg_pass_postfit_projy0__316->GetYaxis()->SetLabelSize(0.05);
   TotalBkg_pass_postfit_projy0__316->GetYaxis()->SetTitleSize(0.08);
   TotalBkg_pass_postfit_projy0__316->GetYaxis()->SetTitleOffset(1.25);
   TotalBkg_pass_postfit_projy0__316->GetYaxis()->SetTitleFont(42);
   TotalBkg_pass_postfit_projy0__316->GetZaxis()->SetLabelFont(42);
   TotalBkg_pass_postfit_projy0__316->GetZaxis()->SetLabelOffset(0.007);
   TotalBkg_pass_postfit_projy0__316->GetZaxis()->SetLabelSize(0.05);
   TotalBkg_pass_postfit_projy0__316->GetZaxis()->SetTitleSize(0.08);
   TotalBkg_pass_postfit_projy0__316->GetZaxis()->SetTitleFont(42);
   TotalBkg_pass_postfit_projy0__316->Draw("hist same");
   Double_t xAxis477[2] = {200, 4025}; 
   
   TH1D *TotalBkg_pass_postfit_projy0__317 = new TH1D("TotalBkg_pass_postfit_projy0__317","TotalBkg, pass, postfit, 0.0-0.25",1, xAxis477);
   TotalBkg_pass_postfit_projy0__317->SetBinContent(1,40775.21);
   TotalBkg_pass_postfit_projy0__317->SetBinError(1,187.7497);
   TotalBkg_pass_postfit_projy0__317->SetMinimum(0);
   TotalBkg_pass_postfit_projy0__317->SetEntries(47166.54);
   TotalBkg_pass_postfit_projy0__317->SetFillColor(1);
   TotalBkg_pass_postfit_projy0__317->SetFillStyle(3354);
   TotalBkg_pass_postfit_projy0__317->SetLineStyle(0);
   TotalBkg_pass_postfit_projy0__317->SetLineWidth(0);
   TotalBkg_pass_postfit_projy0__317->SetMarkerStyle(0);
   TotalBkg_pass_postfit_projy0__317->GetXaxis()->SetTitle("p_{T}");
   TotalBkg_pass_postfit_projy0__317->GetXaxis()->SetLabelFont(42);
   TotalBkg_pass_postfit_projy0__317->GetXaxis()->SetLabelOffset(0.007);
   TotalBkg_pass_postfit_projy0__317->GetXaxis()->SetLabelSize(0.05);
   TotalBkg_pass_postfit_projy0__317->GetXaxis()->SetTitleSize(0.08);
   TotalBkg_pass_postfit_projy0__317->GetXaxis()->SetTitleOffset(1.25);
   TotalBkg_pass_postfit_projy0__317->GetXaxis()->SetTitleFont(42);
   TotalBkg_pass_postfit_projy0__317->GetYaxis()->SetTitle("Events / bin");
   TotalBkg_pass_postfit_projy0__317->GetYaxis()->SetLabelFont(42);
   TotalBkg_pass_postfit_projy0__317->GetYaxis()->SetLabelOffset(0.007);
   TotalBkg_pass_postfit_projy0__317->GetYaxis()->SetLabelSize(0.05);
   TotalBkg_pass_postfit_projy0__317->GetYaxis()->SetTitleSize(0.08);
   TotalBkg_pass_postfit_projy0__317->GetYaxis()->SetTitleOffset(1.25);
   TotalBkg_pass_postfit_projy0__317->GetYaxis()->SetTitleFont(42);
   TotalBkg_pass_postfit_projy0__317->GetZaxis()->SetLabelFont(42);
   TotalBkg_pass_postfit_projy0__317->GetZaxis()->SetLabelOffset(0.007);
   TotalBkg_pass_postfit_projy0__317->GetZaxis()->SetLabelSize(0.05);
   TotalBkg_pass_postfit_projy0__317->GetZaxis()->SetTitleSize(0.08);
   TotalBkg_pass_postfit_projy0__317->GetZaxis()->SetTitleFont(42);
   TotalBkg_pass_postfit_projy0__317->Draw("e2 same");
   Double_t xAxis478[2] = {200, 4025}; 
   
   TH1D *data_obs_pass_postfit_projy0__318 = new TH1D("data_obs_pass_postfit_projy0__318","",1, xAxis478);
   data_obs_pass_postfit_projy0__318->SetBinContent(1,40782);
   data_obs_pass_postfit_projy0__318->SetBinError(1,201.9455);
   data_obs_pass_postfit_projy0__318->SetMinimum(0);
   data_obs_pass_postfit_projy0__318->SetMaximum(55055.7);
   data_obs_pass_postfit_projy0__318->SetEntries(40782);

   ci = TColor::GetColor("#000000");
   data_obs_pass_postfit_projy0__318->SetLineColor(ci);
   data_obs_pass_postfit_projy0__318->SetLineStyle(0);

   ci = TColor::GetColor("#000000");
   data_obs_pass_postfit_projy0__318->SetMarkerColor(ci);
   data_obs_pass_postfit_projy0__318->SetMarkerStyle(8);
   data_obs_pass_postfit_projy0__318->GetXaxis()->SetTitle("p_{T}");
   data_obs_pass_postfit_projy0__318->GetXaxis()->SetLabelFont(42);
   data_obs_pass_postfit_projy0__318->GetXaxis()->SetLabelOffset(0.05);
   data_obs_pass_postfit_projy0__318->GetXaxis()->SetLabelSize(0.07);
   data_obs_pass_postfit_projy0__318->GetXaxis()->SetTitleSize(0.09);
   data_obs_pass_postfit_projy0__318->GetXaxis()->SetTitleOffset(1.15);
   data_obs_pass_postfit_projy0__318->GetXaxis()->SetTitleFont(42);
   data_obs_pass_postfit_projy0__318->GetYaxis()->SetTitle("Events / bin");
   data_obs_pass_postfit_projy0__318->GetYaxis()->SetNdivisions(508);
   data_obs_pass_postfit_projy0__318->GetYaxis()->SetLabelFont(42);
   data_obs_pass_postfit_projy0__318->GetYaxis()->SetLabelOffset(0.007);
   data_obs_pass_postfit_projy0__318->GetYaxis()->SetLabelSize(0.07);
   data_obs_pass_postfit_projy0__318->GetYaxis()->SetTitleSize(0.09);
   data_obs_pass_postfit_projy0__318->GetYaxis()->SetTitleOffset(0.8);
   data_obs_pass_postfit_projy0__318->GetYaxis()->SetTitleFont(42);
   data_obs_pass_postfit_projy0__318->GetZaxis()->SetLabelFont(42);
   data_obs_pass_postfit_projy0__318->GetZaxis()->SetLabelOffset(0.007);
   data_obs_pass_postfit_projy0__318->GetZaxis()->SetLabelSize(0.05);
   data_obs_pass_postfit_projy0__318->GetZaxis()->SetTitleSize(0.08);
   data_obs_pass_postfit_projy0__318->GetZaxis()->SetTitleFont(42);
   data_obs_pass_postfit_projy0__318->Draw("pe X0 same");
   
   TLegend *leg = new TLegend(0.65,0.61,0.9,0.88,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(1001);
   TLegendEntry *entry=leg->AddEntry("data_obs_pass_postfit_projy0","Data","pe X0");

   ci = TColor::GetColor("#000000");
   entry->SetLineColor(ci);
   entry->SetLineWidth(1);

   ci = TColor::GetColor("#000000");
   entry->SetMarkerColor(ci);
   entry->SetMarkerStyle(8);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("TotalBkg_pass_postfit_projy0","Total bkg unc.","F");
   entry->SetFillColor(1);
   entry->SetFillStyle(3354);
   entry->SetLineColor(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("Signal_gluino-1800_pass_postfit_projy0","HSCP gluino 1800 GeV","L");
   entry->SetLineColor(4);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("Signal_ppStau-557_pass_postfit_projy0","HSCP stau 557 GeV","L");
   entry->SetLineColor(2);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("Background_0x0_pass_postfit_projy0_stack_1_stack_1","Background","f");

   ci = TColor::GetColor("#ffff00");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = 1344;
   color = new TColor(ci, 1, 1, 1, " ", 0);
   entry->SetLineColor(ci);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   leg->Draw();
   Double_t xAxis479[2] = {200, 4025}; 
   
   TH1D *data_obs_pass_postfit_projy0_copy__319 = new TH1D("data_obs_pass_postfit_projy0_copy__319","",1, xAxis479);
   data_obs_pass_postfit_projy0_copy__319->SetBinContent(1,40782);
   data_obs_pass_postfit_projy0_copy__319->SetBinError(1,201.9455);
   data_obs_pass_postfit_projy0_copy__319->SetMinimum(0);
   data_obs_pass_postfit_projy0_copy__319->SetMaximum(55055.7);
   data_obs_pass_postfit_projy0_copy__319->SetEntries(40782);
   data_obs_pass_postfit_projy0_copy__319->SetDirectory(0);

   ci = TColor::GetColor("#000000");
   data_obs_pass_postfit_projy0_copy__319->SetLineColor(ci);
   data_obs_pass_postfit_projy0_copy__319->SetLineStyle(0);

   ci = TColor::GetColor("#000000");
   data_obs_pass_postfit_projy0_copy__319->SetMarkerColor(ci);
   data_obs_pass_postfit_projy0_copy__319->SetMarkerStyle(8);
   data_obs_pass_postfit_projy0_copy__319->GetXaxis()->SetTitle("p_{T}");
   data_obs_pass_postfit_projy0_copy__319->GetXaxis()->SetLabelFont(42);
   data_obs_pass_postfit_projy0_copy__319->GetXaxis()->SetLabelOffset(0.05);
   data_obs_pass_postfit_projy0_copy__319->GetXaxis()->SetLabelSize(0.07);
   data_obs_pass_postfit_projy0_copy__319->GetXaxis()->SetTitleSize(0.09);
   data_obs_pass_postfit_projy0_copy__319->GetXaxis()->SetTitleOffset(1.15);
   data_obs_pass_postfit_projy0_copy__319->GetXaxis()->SetTitleFont(42);
   data_obs_pass_postfit_projy0_copy__319->GetYaxis()->SetTitle("Events / bin");
   data_obs_pass_postfit_projy0_copy__319->GetYaxis()->SetNdivisions(508);
   data_obs_pass_postfit_projy0_copy__319->GetYaxis()->SetLabelFont(42);
   data_obs_pass_postfit_projy0_copy__319->GetYaxis()->SetLabelOffset(0.007);
   data_obs_pass_postfit_projy0_copy__319->GetYaxis()->SetLabelSize(0.07);
   data_obs_pass_postfit_projy0_copy__319->GetYaxis()->SetTitleSize(0.09);
   data_obs_pass_postfit_projy0_copy__319->GetYaxis()->SetTitleOffset(0.8);
   data_obs_pass_postfit_projy0_copy__319->GetYaxis()->SetTitleFont(42);
   data_obs_pass_postfit_projy0_copy__319->GetZaxis()->SetLabelFont(42);
   data_obs_pass_postfit_projy0_copy__319->GetZaxis()->SetLabelOffset(0.007);
   data_obs_pass_postfit_projy0_copy__319->GetZaxis()->SetLabelSize(0.05);
   data_obs_pass_postfit_projy0_copy__319->GetZaxis()->SetTitleSize(0.08);
   data_obs_pass_postfit_projy0_copy__319->GetZaxis()->SetTitleFont(42);
   data_obs_pass_postfit_projy0_copy__319->Draw("sameaxis");
   TLatex *   tex = new TLatex(0.21,0.83,"0.0 < G_{i}^{Strips} < 0.25 , F^{Pixels}_{i} > 0.9");
tex->SetNDC();
   tex->SetTextAlign(12);
   tex->SetTextFont(42);
   tex->SetTextSize(0.06);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.17,0.92,"CMS");
tex->SetNDC();
   tex->SetTextFont(61);
   tex->SetTextSize(0.0675);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.25,0.92,"Preliminary");
tex->SetNDC();
   tex->SetTextFont(52);
   tex->SetTextSize(0.0485);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.95,0.92,"101 fb^{-1} (13 TeV)");
tex->SetNDC();
   tex->SetTextAlign(31);
   tex->SetTextFont(42);
   tex->SetTextSize(0.07);
   tex->SetLineWidth(2);
   tex->Draw();
   data_obs_pass_postfit_projy0_main->Modified();
   plots_fit_s/base_figs/postfit_projy0_pass->cd();
  
// ------------>Primitives in pad: data_obs_pass_postfit_projy0_sub
   TPad *data_obs_pass_postfit_projy0_sub = new TPad("data_obs_pass_postfit_projy0_sub", "data_obs_pass_postfit_projy0_sub",0,0,1,0.35);
   data_obs_pass_postfit_projy0_sub->Draw();
   data_obs_pass_postfit_projy0_sub->cd();
   data_obs_pass_postfit_projy0_sub->Range(-633.6539,-6.023077,4270.192,2.9);
   data_obs_pass_postfit_projy0_sub->SetFillColor(0);
   data_obs_pass_postfit_projy0_sub->SetBorderMode(0);
   data_obs_pass_postfit_projy0_sub->SetBorderSize(2);
   data_obs_pass_postfit_projy0_sub->SetTickx(1);
   data_obs_pass_postfit_projy0_sub->SetTicky(1);
   data_obs_pass_postfit_projy0_sub->SetLeftMargin(0.17);
   data_obs_pass_postfit_projy0_sub->SetRightMargin(0.05);
   data_obs_pass_postfit_projy0_sub->SetTopMargin(0);
   data_obs_pass_postfit_projy0_sub->SetBottomMargin(0.35);
   data_obs_pass_postfit_projy0_sub->SetFrameFillStyle(0);
   data_obs_pass_postfit_projy0_sub->SetFrameBorderMode(0);
   data_obs_pass_postfit_projy0_sub->SetFrameFillStyle(0);
   data_obs_pass_postfit_projy0_sub->SetFrameBorderMode(0);
   Double_t xAxis480[2] = {200, 4025}; 
   
   TH1D *data_obs_pass_postfit_projy0_pull__320 = new TH1D("data_obs_pass_postfit_projy0_pull__320","",1, xAxis480);
   data_obs_pass_postfit_projy0_pull__320->SetBinContent(1,0.02461263);
   data_obs_pass_postfit_projy0_pull__320->SetBinError(1,275.7389);
   data_obs_pass_postfit_projy0_pull__320->SetMinimum(-2.9);
   data_obs_pass_postfit_projy0_pull__320->SetMaximum(2.9);
   data_obs_pass_postfit_projy0_pull__320->SetEntries(1.000606);
   data_obs_pass_postfit_projy0_pull__320->SetStats(0);

   ci = TColor::GetColor("#0000ff");
   data_obs_pass_postfit_projy0_pull__320->SetFillColor(ci);

   ci = TColor::GetColor("#000000");
   data_obs_pass_postfit_projy0_pull__320->SetLineColor(ci);
   data_obs_pass_postfit_projy0_pull__320->SetLineStyle(0);

   ci = TColor::GetColor("#000000");
   data_obs_pass_postfit_projy0_pull__320->SetMarkerColor(ci);
   data_obs_pass_postfit_projy0_pull__320->SetMarkerStyle(8);
   data_obs_pass_postfit_projy0_pull__320->GetXaxis()->SetTitle("p_{T}");
   data_obs_pass_postfit_projy0_pull__320->GetXaxis()->SetLabelFont(42);
   data_obs_pass_postfit_projy0_pull__320->GetXaxis()->SetLabelOffset(0.05);
   data_obs_pass_postfit_projy0_pull__320->GetXaxis()->SetLabelSize(0.13);
   data_obs_pass_postfit_projy0_pull__320->GetXaxis()->SetTitleSize(0.15);
   data_obs_pass_postfit_projy0_pull__320->GetXaxis()->SetTitleOffset(1.15);
   data_obs_pass_postfit_projy0_pull__320->GetXaxis()->SetTitleFont(42);
   data_obs_pass_postfit_projy0_pull__320->GetYaxis()->SetTitle("(Data-Bkg)/#sigma");
   data_obs_pass_postfit_projy0_pull__320->GetYaxis()->SetNdivisions(306);
   data_obs_pass_postfit_projy0_pull__320->GetYaxis()->SetLabelFont(42);
   data_obs_pass_postfit_projy0_pull__320->GetYaxis()->SetLabelOffset(0.007);
   data_obs_pass_postfit_projy0_pull__320->GetYaxis()->SetLabelSize(0.13);
   data_obs_pass_postfit_projy0_pull__320->GetYaxis()->SetTitleSize(0.12);
   data_obs_pass_postfit_projy0_pull__320->GetYaxis()->SetTitleOffset(0.4);
   data_obs_pass_postfit_projy0_pull__320->GetYaxis()->SetTitleFont(42);
   data_obs_pass_postfit_projy0_pull__320->GetZaxis()->SetLabelFont(42);
   data_obs_pass_postfit_projy0_pull__320->GetZaxis()->SetLabelOffset(0.007);
   data_obs_pass_postfit_projy0_pull__320->GetZaxis()->SetLabelSize(0.05);
   data_obs_pass_postfit_projy0_pull__320->GetZaxis()->SetTitleSize(0.08);
   data_obs_pass_postfit_projy0_pull__320->GetZaxis()->SetTitleFont(42);
   data_obs_pass_postfit_projy0_pull__320->Draw("hist");
   data_obs_pass_postfit_projy0_sub->Modified();
   plots_fit_s/base_figs/postfit_projy0_pass->cd();
   plots_fit_s/base_figs/postfit_projy0_pass->Modified();
   plots_fit_s/base_figs/postfit_projy0_pass->cd();
   plots_fit_s/base_figs/postfit_projy0_pass->SetSelected(plots_fit_s/base_figs/postfit_projy0_pass);
}
