void postfit_projy2_pass()
{
//=========Macro generated from canvas: plots_fit_s/base_figs/postfit_projy2_pass/plots_fit_s/base_figs/postfit_projy2_pass
//=========  (Fri Jan 12 20:33:24 2024) by ROOT version 6.14/09
   TCanvas *plots_fit_s/base_figs/postfit_projy2_pass = new TCanvas("plots_fit_s/base_figs/postfit_projy2_pass", "plots_fit_s/base_figs/postfit_projy2_pass",0,0,800,700);
   gStyle->SetOptFit(1);
   gStyle->SetOptStat(0);
   plots_fit_s/base_figs/postfit_projy2_pass->SetHighLightColor(2);
   plots_fit_s/base_figs/postfit_projy2_pass->Range(0,0,1,1);
   plots_fit_s/base_figs/postfit_projy2_pass->SetFillColor(0);
   plots_fit_s/base_figs/postfit_projy2_pass->SetBorderMode(0);
   plots_fit_s/base_figs/postfit_projy2_pass->SetBorderSize(2);
   plots_fit_s/base_figs/postfit_projy2_pass->SetTickx(1);
   plots_fit_s/base_figs/postfit_projy2_pass->SetTicky(1);
   plots_fit_s/base_figs/postfit_projy2_pass->SetLeftMargin(0.16);
   plots_fit_s/base_figs/postfit_projy2_pass->SetRightMargin(0);
   plots_fit_s/base_figs/postfit_projy2_pass->SetTopMargin(0);
   plots_fit_s/base_figs/postfit_projy2_pass->SetBottomMargin(0);
   plots_fit_s/base_figs/postfit_projy2_pass->SetFrameFillStyle(0);
   plots_fit_s/base_figs/postfit_projy2_pass->SetFrameBorderMode(0);
  
// ------------>Primitives in pad: data_obs_pass_postfit_projy2_main
   TPad *data_obs_pass_postfit_projy2_main = new TPad("data_obs_pass_postfit_projy2_main", "data_obs_pass_postfit_projy2_main",0,0.35,1,1);
   data_obs_pass_postfit_projy2_main->Draw();
   data_obs_pass_postfit_projy2_main->cd();
   data_obs_pass_postfit_projy2_main->Range(-633.6539,-0.04651163,4270.192,1.116279);
   data_obs_pass_postfit_projy2_main->SetFillColor(0);
   data_obs_pass_postfit_projy2_main->SetBorderMode(0);
   data_obs_pass_postfit_projy2_main->SetBorderSize(2);
   data_obs_pass_postfit_projy2_main->SetTickx(1);
   data_obs_pass_postfit_projy2_main->SetTicky(1);
   data_obs_pass_postfit_projy2_main->SetLeftMargin(0.17);
   data_obs_pass_postfit_projy2_main->SetRightMargin(0.05);
   data_obs_pass_postfit_projy2_main->SetBottomMargin(0.04);
   data_obs_pass_postfit_projy2_main->SetFrameFillStyle(0);
   data_obs_pass_postfit_projy2_main->SetFrameBorderMode(0);
   data_obs_pass_postfit_projy2_main->SetFrameFillStyle(0);
   data_obs_pass_postfit_projy2_main->SetFrameBorderMode(0);
   Double_t xAxis493[2] = {200, 4025}; 
   
   TH1D *data_obs_pass_postfit_projy2__329 = new TH1D("data_obs_pass_postfit_projy2__329","",1, xAxis493);
   data_obs_pass_postfit_projy2__329->SetMinimum(0);
   data_obs_pass_postfit_projy2__329->SetMaximum(0);

   Int_t ci;      // for color index setting
   TColor *color; // for color definition with alpha
   ci = TColor::GetColor("#000000");
   data_obs_pass_postfit_projy2__329->SetLineColor(ci);
   data_obs_pass_postfit_projy2__329->SetLineStyle(0);

   ci = TColor::GetColor("#000000");
   data_obs_pass_postfit_projy2__329->SetMarkerColor(ci);
   data_obs_pass_postfit_projy2__329->SetMarkerStyle(8);
   data_obs_pass_postfit_projy2__329->GetXaxis()->SetTitle("p_{T}");
   data_obs_pass_postfit_projy2__329->GetXaxis()->SetLabelFont(42);
   data_obs_pass_postfit_projy2__329->GetXaxis()->SetLabelOffset(0.05);
   data_obs_pass_postfit_projy2__329->GetXaxis()->SetLabelSize(0.07);
   data_obs_pass_postfit_projy2__329->GetXaxis()->SetTitleSize(0.09);
   data_obs_pass_postfit_projy2__329->GetXaxis()->SetTitleOffset(1.15);
   data_obs_pass_postfit_projy2__329->GetXaxis()->SetTitleFont(42);
   data_obs_pass_postfit_projy2__329->GetYaxis()->SetTitle("Events / bin");
   data_obs_pass_postfit_projy2__329->GetYaxis()->SetNdivisions(508);
   data_obs_pass_postfit_projy2__329->GetYaxis()->SetLabelFont(42);
   data_obs_pass_postfit_projy2__329->GetYaxis()->SetLabelOffset(0.007);
   data_obs_pass_postfit_projy2__329->GetYaxis()->SetLabelSize(0.07);
   data_obs_pass_postfit_projy2__329->GetYaxis()->SetTitleSize(0.09);
   data_obs_pass_postfit_projy2__329->GetYaxis()->SetTitleOffset(0.8);
   data_obs_pass_postfit_projy2__329->GetYaxis()->SetTitleFont(42);
   data_obs_pass_postfit_projy2__329->GetZaxis()->SetLabelFont(42);
   data_obs_pass_postfit_projy2__329->GetZaxis()->SetLabelOffset(0.007);
   data_obs_pass_postfit_projy2__329->GetZaxis()->SetLabelSize(0.05);
   data_obs_pass_postfit_projy2__329->GetZaxis()->SetTitleSize(0.08);
   data_obs_pass_postfit_projy2__329->GetZaxis()->SetTitleFont(42);
   data_obs_pass_postfit_projy2__329->Draw("pe X0");
   
   THStack *postfit_projy2_pass_stack = new THStack();
   postfit_projy2_pass_stack->SetName("postfit_projy2_pass_stack");
   postfit_projy2_pass_stack->SetTitle("postfit_projy2_pass_stack");
   Double_t xAxis494[2] = {200, 4025}; 
   
   TH1F *postfit_projy2_pass_stack_stack_83 = new TH1F("postfit_projy2_pass_stack_stack_83","postfit_projy2_pass_stack",1, xAxis494);
   postfit_projy2_pass_stack_stack_83->SetMinimum(0);
   postfit_projy2_pass_stack_stack_83->SetMaximum(0);
   postfit_projy2_pass_stack_stack_83->SetDirectory(0);
   postfit_projy2_pass_stack_stack_83->SetStats(0);
   postfit_projy2_pass_stack_stack_83->SetLineStyle(0);
   postfit_projy2_pass_stack_stack_83->GetXaxis()->SetLabelFont(42);
   postfit_projy2_pass_stack_stack_83->GetXaxis()->SetLabelOffset(0.007);
   postfit_projy2_pass_stack_stack_83->GetXaxis()->SetLabelSize(0.05);
   postfit_projy2_pass_stack_stack_83->GetXaxis()->SetTitleSize(0.08);
   postfit_projy2_pass_stack_stack_83->GetXaxis()->SetTitleOffset(0.9);
   postfit_projy2_pass_stack_stack_83->GetXaxis()->SetTitleFont(42);
   postfit_projy2_pass_stack_stack_83->GetYaxis()->SetNdivisions(508);
   postfit_projy2_pass_stack_stack_83->GetYaxis()->SetLabelFont(42);
   postfit_projy2_pass_stack_stack_83->GetYaxis()->SetLabelOffset(0.007);
   postfit_projy2_pass_stack_stack_83->GetYaxis()->SetLabelSize(0.05);
   postfit_projy2_pass_stack_stack_83->GetYaxis()->SetTitleSize(0.08);
   postfit_projy2_pass_stack_stack_83->GetYaxis()->SetTitleOffset(1.25);
   postfit_projy2_pass_stack_stack_83->GetYaxis()->SetTitleFont(42);
   postfit_projy2_pass_stack_stack_83->GetZaxis()->SetLabelFont(42);
   postfit_projy2_pass_stack_stack_83->GetZaxis()->SetLabelOffset(0.007);
   postfit_projy2_pass_stack_stack_83->GetZaxis()->SetLabelSize(0.05);
   postfit_projy2_pass_stack_stack_83->GetZaxis()->SetTitleSize(0.08);
   postfit_projy2_pass_stack_stack_83->GetZaxis()->SetTitleFont(42);
   postfit_projy2_pass_stack->SetHistogram(postfit_projy2_pass_stack_stack_83);
   
   Double_t xAxis495[2] = {200, 4025}; 
   
   TH1D *Background_0x0_pass_postfit_projy2_stack_1 = new TH1D("Background_0x0_pass_postfit_projy2_stack_1","Background, pass, postfit, 1.0-1.0",1, xAxis495);
   Background_0x0_pass_postfit_projy2_stack_1->SetMinimum(0);

   ci = TColor::GetColor("#ffff00");
   Background_0x0_pass_postfit_projy2_stack_1->SetFillColor(ci);

   ci = 1346;
   color = new TColor(ci, 1, 1, 1, " ", 0);
   Background_0x0_pass_postfit_projy2_stack_1->SetLineColor(ci);
   Background_0x0_pass_postfit_projy2_stack_1->SetLineStyle(0);
   Background_0x0_pass_postfit_projy2_stack_1->GetXaxis()->SetTitle("p_{T}");
   Background_0x0_pass_postfit_projy2_stack_1->GetXaxis()->SetLabelFont(42);
   Background_0x0_pass_postfit_projy2_stack_1->GetXaxis()->SetLabelOffset(0.007);
   Background_0x0_pass_postfit_projy2_stack_1->GetXaxis()->SetLabelSize(0.05);
   Background_0x0_pass_postfit_projy2_stack_1->GetXaxis()->SetTitleSize(0.08);
   Background_0x0_pass_postfit_projy2_stack_1->GetXaxis()->SetTitleOffset(1.25);
   Background_0x0_pass_postfit_projy2_stack_1->GetXaxis()->SetTitleFont(42);
   Background_0x0_pass_postfit_projy2_stack_1->GetYaxis()->SetTitle("Events / bin");
   Background_0x0_pass_postfit_projy2_stack_1->GetYaxis()->SetLabelFont(42);
   Background_0x0_pass_postfit_projy2_stack_1->GetYaxis()->SetLabelOffset(0.007);
   Background_0x0_pass_postfit_projy2_stack_1->GetYaxis()->SetLabelSize(0.05);
   Background_0x0_pass_postfit_projy2_stack_1->GetYaxis()->SetTitleSize(0.08);
   Background_0x0_pass_postfit_projy2_stack_1->GetYaxis()->SetTitleOffset(1.25);
   Background_0x0_pass_postfit_projy2_stack_1->GetYaxis()->SetTitleFont(42);
   Background_0x0_pass_postfit_projy2_stack_1->GetZaxis()->SetLabelFont(42);
   Background_0x0_pass_postfit_projy2_stack_1->GetZaxis()->SetLabelOffset(0.007);
   Background_0x0_pass_postfit_projy2_stack_1->GetZaxis()->SetLabelSize(0.05);
   Background_0x0_pass_postfit_projy2_stack_1->GetZaxis()->SetTitleSize(0.08);
   Background_0x0_pass_postfit_projy2_stack_1->GetZaxis()->SetTitleFont(42);
   postfit_projy2_pass_stack->Add(Background_0x0_pass_postfit_projy2_stack_1,"");
   postfit_projy2_pass_stack->Draw("hist same");
   
   postfit_projy2_pass_stack = new THStack();
   postfit_projy2_pass_stack->SetName("postfit_projy2_pass_stack");
   postfit_projy2_pass_stack->SetTitle("postfit_projy2_pass_stack");
   Double_t xAxis496[2] = {200, 4025}; 
   
   TH1F *postfit_projy2_pass_stack_stack_83_stack_84 = new TH1F("postfit_projy2_pass_stack_stack_83_stack_84","postfit_projy2_pass_stack",1, xAxis496);
   postfit_projy2_pass_stack_stack_83_stack_84->SetMinimum(0);
   postfit_projy2_pass_stack_stack_83_stack_84->SetMaximum(0);
   postfit_projy2_pass_stack_stack_83_stack_84->SetDirectory(0);
   postfit_projy2_pass_stack_stack_83_stack_84->SetStats(0);
   postfit_projy2_pass_stack_stack_83_stack_84->SetLineStyle(0);
   postfit_projy2_pass_stack_stack_83_stack_84->GetXaxis()->SetLabelFont(42);
   postfit_projy2_pass_stack_stack_83_stack_84->GetXaxis()->SetLabelOffset(0.007);
   postfit_projy2_pass_stack_stack_83_stack_84->GetXaxis()->SetLabelSize(0.05);
   postfit_projy2_pass_stack_stack_83_stack_84->GetXaxis()->SetTitleSize(0.08);
   postfit_projy2_pass_stack_stack_83_stack_84->GetXaxis()->SetTitleOffset(0.9);
   postfit_projy2_pass_stack_stack_83_stack_84->GetXaxis()->SetTitleFont(42);
   postfit_projy2_pass_stack_stack_83_stack_84->GetYaxis()->SetNdivisions(508);
   postfit_projy2_pass_stack_stack_83_stack_84->GetYaxis()->SetLabelFont(42);
   postfit_projy2_pass_stack_stack_83_stack_84->GetYaxis()->SetLabelOffset(0.007);
   postfit_projy2_pass_stack_stack_83_stack_84->GetYaxis()->SetLabelSize(0.05);
   postfit_projy2_pass_stack_stack_83_stack_84->GetYaxis()->SetTitleSize(0.08);
   postfit_projy2_pass_stack_stack_83_stack_84->GetYaxis()->SetTitleOffset(1.25);
   postfit_projy2_pass_stack_stack_83_stack_84->GetYaxis()->SetTitleFont(42);
   postfit_projy2_pass_stack_stack_83_stack_84->GetZaxis()->SetLabelFont(42);
   postfit_projy2_pass_stack_stack_83_stack_84->GetZaxis()->SetLabelOffset(0.007);
   postfit_projy2_pass_stack_stack_83_stack_84->GetZaxis()->SetLabelSize(0.05);
   postfit_projy2_pass_stack_stack_83_stack_84->GetZaxis()->SetTitleSize(0.08);
   postfit_projy2_pass_stack_stack_83_stack_84->GetZaxis()->SetTitleFont(42);
   postfit_projy2_pass_stack->SetHistogram(postfit_projy2_pass_stack_stack_83_stack_84);
   
   Double_t xAxis497[2] = {200, 4025}; 
   
   TH1D *Background_0x0_pass_postfit_projy2_stack_1_stack_1 = new TH1D("Background_0x0_pass_postfit_projy2_stack_1_stack_1","Background, pass, postfit, 1.0-1.0",1, xAxis497);
   Background_0x0_pass_postfit_projy2_stack_1_stack_1->SetMinimum(0);

   ci = TColor::GetColor("#ffff00");
   Background_0x0_pass_postfit_projy2_stack_1_stack_1->SetFillColor(ci);

   ci = 1346;
   color = new TColor(ci, 1, 1, 1, " ", 0);
   Background_0x0_pass_postfit_projy2_stack_1_stack_1->SetLineColor(ci);
   Background_0x0_pass_postfit_projy2_stack_1_stack_1->SetLineStyle(0);
   Background_0x0_pass_postfit_projy2_stack_1_stack_1->GetXaxis()->SetTitle("p_{T}");
   Background_0x0_pass_postfit_projy2_stack_1_stack_1->GetXaxis()->SetLabelFont(42);
   Background_0x0_pass_postfit_projy2_stack_1_stack_1->GetXaxis()->SetLabelOffset(0.007);
   Background_0x0_pass_postfit_projy2_stack_1_stack_1->GetXaxis()->SetLabelSize(0.05);
   Background_0x0_pass_postfit_projy2_stack_1_stack_1->GetXaxis()->SetTitleSize(0.08);
   Background_0x0_pass_postfit_projy2_stack_1_stack_1->GetXaxis()->SetTitleOffset(1.25);
   Background_0x0_pass_postfit_projy2_stack_1_stack_1->GetXaxis()->SetTitleFont(42);
   Background_0x0_pass_postfit_projy2_stack_1_stack_1->GetYaxis()->SetTitle("Events / bin");
   Background_0x0_pass_postfit_projy2_stack_1_stack_1->GetYaxis()->SetLabelFont(42);
   Background_0x0_pass_postfit_projy2_stack_1_stack_1->GetYaxis()->SetLabelOffset(0.007);
   Background_0x0_pass_postfit_projy2_stack_1_stack_1->GetYaxis()->SetLabelSize(0.05);
   Background_0x0_pass_postfit_projy2_stack_1_stack_1->GetYaxis()->SetTitleSize(0.08);
   Background_0x0_pass_postfit_projy2_stack_1_stack_1->GetYaxis()->SetTitleOffset(1.25);
   Background_0x0_pass_postfit_projy2_stack_1_stack_1->GetYaxis()->SetTitleFont(42);
   Background_0x0_pass_postfit_projy2_stack_1_stack_1->GetZaxis()->SetLabelFont(42);
   Background_0x0_pass_postfit_projy2_stack_1_stack_1->GetZaxis()->SetLabelOffset(0.007);
   Background_0x0_pass_postfit_projy2_stack_1_stack_1->GetZaxis()->SetLabelSize(0.05);
   Background_0x0_pass_postfit_projy2_stack_1_stack_1->GetZaxis()->SetTitleSize(0.08);
   Background_0x0_pass_postfit_projy2_stack_1_stack_1->GetZaxis()->SetTitleFont(42);
   postfit_projy2_pass_stack->Add(Background_0x0_pass_postfit_projy2_stack_1_stack_1,"");
   postfit_projy2_pass_stack->Draw("hist same");
   Double_t xAxis498[2] = {200, 4025}; 
   
   TH1D *Signal_gluinomI1800_pass_postfit_projy2__330 = new TH1D("Signal_gluinomI1800_pass_postfit_projy2__330","HSCP gluino 1800 GeV, pass, postfit, 1.0-1.0",1, xAxis498);
   Signal_gluinomI1800_pass_postfit_projy2__330->SetMinimum(0);
   Signal_gluinomI1800_pass_postfit_projy2__330->SetLineColor(4);
   Signal_gluinomI1800_pass_postfit_projy2__330->SetLineStyle(0);
   Signal_gluinomI1800_pass_postfit_projy2__330->SetLineWidth(2);
   Signal_gluinomI1800_pass_postfit_projy2__330->GetXaxis()->SetTitle("p_{T}");
   Signal_gluinomI1800_pass_postfit_projy2__330->GetXaxis()->SetLabelFont(42);
   Signal_gluinomI1800_pass_postfit_projy2__330->GetXaxis()->SetLabelOffset(0.007);
   Signal_gluinomI1800_pass_postfit_projy2__330->GetXaxis()->SetLabelSize(0.05);
   Signal_gluinomI1800_pass_postfit_projy2__330->GetXaxis()->SetTitleSize(0.08);
   Signal_gluinomI1800_pass_postfit_projy2__330->GetXaxis()->SetTitleOffset(1.25);
   Signal_gluinomI1800_pass_postfit_projy2__330->GetXaxis()->SetTitleFont(42);
   Signal_gluinomI1800_pass_postfit_projy2__330->GetYaxis()->SetTitle("Events / bin");
   Signal_gluinomI1800_pass_postfit_projy2__330->GetYaxis()->SetLabelFont(42);
   Signal_gluinomI1800_pass_postfit_projy2__330->GetYaxis()->SetLabelOffset(0.007);
   Signal_gluinomI1800_pass_postfit_projy2__330->GetYaxis()->SetLabelSize(0.05);
   Signal_gluinomI1800_pass_postfit_projy2__330->GetYaxis()->SetTitleSize(0.08);
   Signal_gluinomI1800_pass_postfit_projy2__330->GetYaxis()->SetTitleOffset(1.25);
   Signal_gluinomI1800_pass_postfit_projy2__330->GetYaxis()->SetTitleFont(42);
   Signal_gluinomI1800_pass_postfit_projy2__330->GetZaxis()->SetLabelFont(42);
   Signal_gluinomI1800_pass_postfit_projy2__330->GetZaxis()->SetLabelOffset(0.007);
   Signal_gluinomI1800_pass_postfit_projy2__330->GetZaxis()->SetLabelSize(0.05);
   Signal_gluinomI1800_pass_postfit_projy2__330->GetZaxis()->SetTitleSize(0.08);
   Signal_gluinomI1800_pass_postfit_projy2__330->GetZaxis()->SetTitleFont(42);
   Signal_gluinomI1800_pass_postfit_projy2__330->Draw("hist same");
   Double_t xAxis499[2] = {200, 4025}; 
   
   TH1D *Signal_ppStaumI557_pass_postfit_projy2__331 = new TH1D("Signal_ppStaumI557_pass_postfit_projy2__331","HSCP stau 557 GeV, pass, postfit, 1.0-1.0",1, xAxis499);
   Signal_ppStaumI557_pass_postfit_projy2__331->SetMinimum(0);
   Signal_ppStaumI557_pass_postfit_projy2__331->SetLineColor(2);
   Signal_ppStaumI557_pass_postfit_projy2__331->SetLineStyle(0);
   Signal_ppStaumI557_pass_postfit_projy2__331->SetLineWidth(2);
   Signal_ppStaumI557_pass_postfit_projy2__331->GetXaxis()->SetTitle("p_{T}");
   Signal_ppStaumI557_pass_postfit_projy2__331->GetXaxis()->SetLabelFont(42);
   Signal_ppStaumI557_pass_postfit_projy2__331->GetXaxis()->SetLabelOffset(0.007);
   Signal_ppStaumI557_pass_postfit_projy2__331->GetXaxis()->SetLabelSize(0.05);
   Signal_ppStaumI557_pass_postfit_projy2__331->GetXaxis()->SetTitleSize(0.08);
   Signal_ppStaumI557_pass_postfit_projy2__331->GetXaxis()->SetTitleOffset(1.25);
   Signal_ppStaumI557_pass_postfit_projy2__331->GetXaxis()->SetTitleFont(42);
   Signal_ppStaumI557_pass_postfit_projy2__331->GetYaxis()->SetTitle("Events / bin");
   Signal_ppStaumI557_pass_postfit_projy2__331->GetYaxis()->SetLabelFont(42);
   Signal_ppStaumI557_pass_postfit_projy2__331->GetYaxis()->SetLabelOffset(0.007);
   Signal_ppStaumI557_pass_postfit_projy2__331->GetYaxis()->SetLabelSize(0.05);
   Signal_ppStaumI557_pass_postfit_projy2__331->GetYaxis()->SetTitleSize(0.08);
   Signal_ppStaumI557_pass_postfit_projy2__331->GetYaxis()->SetTitleOffset(1.25);
   Signal_ppStaumI557_pass_postfit_projy2__331->GetYaxis()->SetTitleFont(42);
   Signal_ppStaumI557_pass_postfit_projy2__331->GetZaxis()->SetLabelFont(42);
   Signal_ppStaumI557_pass_postfit_projy2__331->GetZaxis()->SetLabelOffset(0.007);
   Signal_ppStaumI557_pass_postfit_projy2__331->GetZaxis()->SetLabelSize(0.05);
   Signal_ppStaumI557_pass_postfit_projy2__331->GetZaxis()->SetTitleSize(0.08);
   Signal_ppStaumI557_pass_postfit_projy2__331->GetZaxis()->SetTitleFont(42);
   Signal_ppStaumI557_pass_postfit_projy2__331->Draw("hist same");
   Double_t xAxis500[2] = {200, 4025}; 
   
   TH1D *TotalBkg_pass_postfit_projy2__332 = new TH1D("TotalBkg_pass_postfit_projy2__332","TotalBkg, pass, postfit, 1.0-1.0",1, xAxis500);
   TotalBkg_pass_postfit_projy2__332->SetMinimum(0);
   TotalBkg_pass_postfit_projy2__332->SetLineStyle(0);
   TotalBkg_pass_postfit_projy2__332->SetMarkerStyle(0);
   TotalBkg_pass_postfit_projy2__332->GetXaxis()->SetTitle("p_{T}");
   TotalBkg_pass_postfit_projy2__332->GetXaxis()->SetLabelFont(42);
   TotalBkg_pass_postfit_projy2__332->GetXaxis()->SetLabelOffset(0.007);
   TotalBkg_pass_postfit_projy2__332->GetXaxis()->SetLabelSize(0.05);
   TotalBkg_pass_postfit_projy2__332->GetXaxis()->SetTitleSize(0.08);
   TotalBkg_pass_postfit_projy2__332->GetXaxis()->SetTitleOffset(1.25);
   TotalBkg_pass_postfit_projy2__332->GetXaxis()->SetTitleFont(42);
   TotalBkg_pass_postfit_projy2__332->GetYaxis()->SetTitle("Events / bin");
   TotalBkg_pass_postfit_projy2__332->GetYaxis()->SetLabelFont(42);
   TotalBkg_pass_postfit_projy2__332->GetYaxis()->SetLabelOffset(0.007);
   TotalBkg_pass_postfit_projy2__332->GetYaxis()->SetLabelSize(0.05);
   TotalBkg_pass_postfit_projy2__332->GetYaxis()->SetTitleSize(0.08);
   TotalBkg_pass_postfit_projy2__332->GetYaxis()->SetTitleOffset(1.25);
   TotalBkg_pass_postfit_projy2__332->GetYaxis()->SetTitleFont(42);
   TotalBkg_pass_postfit_projy2__332->GetZaxis()->SetLabelFont(42);
   TotalBkg_pass_postfit_projy2__332->GetZaxis()->SetLabelOffset(0.007);
   TotalBkg_pass_postfit_projy2__332->GetZaxis()->SetLabelSize(0.05);
   TotalBkg_pass_postfit_projy2__332->GetZaxis()->SetTitleSize(0.08);
   TotalBkg_pass_postfit_projy2__332->GetZaxis()->SetTitleFont(42);
   TotalBkg_pass_postfit_projy2__332->Draw("hist same");
   Double_t xAxis501[2] = {200, 4025}; 
   
   TH1D *TotalBkg_pass_postfit_projy2__333 = new TH1D("TotalBkg_pass_postfit_projy2__333","TotalBkg, pass, postfit, 1.0-1.0",1, xAxis501);
   TotalBkg_pass_postfit_projy2__333->SetMinimum(0);
   TotalBkg_pass_postfit_projy2__333->SetFillColor(1);
   TotalBkg_pass_postfit_projy2__333->SetFillStyle(3354);
   TotalBkg_pass_postfit_projy2__333->SetLineStyle(0);
   TotalBkg_pass_postfit_projy2__333->SetLineWidth(0);
   TotalBkg_pass_postfit_projy2__333->SetMarkerStyle(0);
   TotalBkg_pass_postfit_projy2__333->GetXaxis()->SetTitle("p_{T}");
   TotalBkg_pass_postfit_projy2__333->GetXaxis()->SetLabelFont(42);
   TotalBkg_pass_postfit_projy2__333->GetXaxis()->SetLabelOffset(0.007);
   TotalBkg_pass_postfit_projy2__333->GetXaxis()->SetLabelSize(0.05);
   TotalBkg_pass_postfit_projy2__333->GetXaxis()->SetTitleSize(0.08);
   TotalBkg_pass_postfit_projy2__333->GetXaxis()->SetTitleOffset(1.25);
   TotalBkg_pass_postfit_projy2__333->GetXaxis()->SetTitleFont(42);
   TotalBkg_pass_postfit_projy2__333->GetYaxis()->SetTitle("Events / bin");
   TotalBkg_pass_postfit_projy2__333->GetYaxis()->SetLabelFont(42);
   TotalBkg_pass_postfit_projy2__333->GetYaxis()->SetLabelOffset(0.007);
   TotalBkg_pass_postfit_projy2__333->GetYaxis()->SetLabelSize(0.05);
   TotalBkg_pass_postfit_projy2__333->GetYaxis()->SetTitleSize(0.08);
   TotalBkg_pass_postfit_projy2__333->GetYaxis()->SetTitleOffset(1.25);
   TotalBkg_pass_postfit_projy2__333->GetYaxis()->SetTitleFont(42);
   TotalBkg_pass_postfit_projy2__333->GetZaxis()->SetLabelFont(42);
   TotalBkg_pass_postfit_projy2__333->GetZaxis()->SetLabelOffset(0.007);
   TotalBkg_pass_postfit_projy2__333->GetZaxis()->SetLabelSize(0.05);
   TotalBkg_pass_postfit_projy2__333->GetZaxis()->SetTitleSize(0.08);
   TotalBkg_pass_postfit_projy2__333->GetZaxis()->SetTitleFont(42);
   TotalBkg_pass_postfit_projy2__333->Draw("e2 same");
   Double_t xAxis502[2] = {200, 4025}; 
   
   TH1D *data_obs_pass_postfit_projy2__334 = new TH1D("data_obs_pass_postfit_projy2__334","",1, xAxis502);
   data_obs_pass_postfit_projy2__334->SetMinimum(0);
   data_obs_pass_postfit_projy2__334->SetMaximum(0);

   ci = TColor::GetColor("#000000");
   data_obs_pass_postfit_projy2__334->SetLineColor(ci);
   data_obs_pass_postfit_projy2__334->SetLineStyle(0);

   ci = TColor::GetColor("#000000");
   data_obs_pass_postfit_projy2__334->SetMarkerColor(ci);
   data_obs_pass_postfit_projy2__334->SetMarkerStyle(8);
   data_obs_pass_postfit_projy2__334->GetXaxis()->SetTitle("p_{T}");
   data_obs_pass_postfit_projy2__334->GetXaxis()->SetLabelFont(42);
   data_obs_pass_postfit_projy2__334->GetXaxis()->SetLabelOffset(0.05);
   data_obs_pass_postfit_projy2__334->GetXaxis()->SetLabelSize(0.07);
   data_obs_pass_postfit_projy2__334->GetXaxis()->SetTitleSize(0.09);
   data_obs_pass_postfit_projy2__334->GetXaxis()->SetTitleOffset(1.15);
   data_obs_pass_postfit_projy2__334->GetXaxis()->SetTitleFont(42);
   data_obs_pass_postfit_projy2__334->GetYaxis()->SetTitle("Events / bin");
   data_obs_pass_postfit_projy2__334->GetYaxis()->SetNdivisions(508);
   data_obs_pass_postfit_projy2__334->GetYaxis()->SetLabelFont(42);
   data_obs_pass_postfit_projy2__334->GetYaxis()->SetLabelOffset(0.007);
   data_obs_pass_postfit_projy2__334->GetYaxis()->SetLabelSize(0.07);
   data_obs_pass_postfit_projy2__334->GetYaxis()->SetTitleSize(0.09);
   data_obs_pass_postfit_projy2__334->GetYaxis()->SetTitleOffset(0.8);
   data_obs_pass_postfit_projy2__334->GetYaxis()->SetTitleFont(42);
   data_obs_pass_postfit_projy2__334->GetZaxis()->SetLabelFont(42);
   data_obs_pass_postfit_projy2__334->GetZaxis()->SetLabelOffset(0.007);
   data_obs_pass_postfit_projy2__334->GetZaxis()->SetLabelSize(0.05);
   data_obs_pass_postfit_projy2__334->GetZaxis()->SetTitleSize(0.08);
   data_obs_pass_postfit_projy2__334->GetZaxis()->SetTitleFont(42);
   data_obs_pass_postfit_projy2__334->Draw("pe X0 same");
   
   TLegend *leg = new TLegend(0.65,0.61,0.9,0.88,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(1001);
   TLegendEntry *entry=leg->AddEntry("data_obs_pass_postfit_projy2","Data","pe X0");

   ci = TColor::GetColor("#000000");
   entry->SetLineColor(ci);
   entry->SetLineWidth(1);

   ci = TColor::GetColor("#000000");
   entry->SetMarkerColor(ci);
   entry->SetMarkerStyle(8);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("TotalBkg_pass_postfit_projy2","Total bkg unc.","F");
   entry->SetFillColor(1);
   entry->SetFillStyle(3354);
   entry->SetLineColor(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("Signal_gluino-1800_pass_postfit_projy2","HSCP gluino 1800 GeV","L");
   entry->SetLineColor(4);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("Signal_ppStau-557_pass_postfit_projy2","HSCP stau 557 GeV","L");
   entry->SetLineColor(2);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("Background_0x0_pass_postfit_projy2_stack_1_stack_1","Background","f");

   ci = TColor::GetColor("#ffff00");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = 1346;
   color = new TColor(ci, 1, 1, 1, " ", 0);
   entry->SetLineColor(ci);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   leg->Draw();
   Double_t xAxis503[2] = {200, 4025}; 
   
   TH1D *data_obs_pass_postfit_projy2_copy__335 = new TH1D("data_obs_pass_postfit_projy2_copy__335","",1, xAxis503);
   data_obs_pass_postfit_projy2_copy__335->SetMinimum(0);
   data_obs_pass_postfit_projy2_copy__335->SetMaximum(0);
   data_obs_pass_postfit_projy2_copy__335->SetDirectory(0);

   ci = TColor::GetColor("#000000");
   data_obs_pass_postfit_projy2_copy__335->SetLineColor(ci);
   data_obs_pass_postfit_projy2_copy__335->SetLineStyle(0);

   ci = TColor::GetColor("#000000");
   data_obs_pass_postfit_projy2_copy__335->SetMarkerColor(ci);
   data_obs_pass_postfit_projy2_copy__335->SetMarkerStyle(8);
   data_obs_pass_postfit_projy2_copy__335->GetXaxis()->SetTitle("p_{T}");
   data_obs_pass_postfit_projy2_copy__335->GetXaxis()->SetLabelFont(42);
   data_obs_pass_postfit_projy2_copy__335->GetXaxis()->SetLabelOffset(0.05);
   data_obs_pass_postfit_projy2_copy__335->GetXaxis()->SetLabelSize(0.07);
   data_obs_pass_postfit_projy2_copy__335->GetXaxis()->SetTitleSize(0.09);
   data_obs_pass_postfit_projy2_copy__335->GetXaxis()->SetTitleOffset(1.15);
   data_obs_pass_postfit_projy2_copy__335->GetXaxis()->SetTitleFont(42);
   data_obs_pass_postfit_projy2_copy__335->GetYaxis()->SetTitle("Events / bin");
   data_obs_pass_postfit_projy2_copy__335->GetYaxis()->SetNdivisions(508);
   data_obs_pass_postfit_projy2_copy__335->GetYaxis()->SetLabelFont(42);
   data_obs_pass_postfit_projy2_copy__335->GetYaxis()->SetLabelOffset(0.007);
   data_obs_pass_postfit_projy2_copy__335->GetYaxis()->SetLabelSize(0.07);
   data_obs_pass_postfit_projy2_copy__335->GetYaxis()->SetTitleSize(0.09);
   data_obs_pass_postfit_projy2_copy__335->GetYaxis()->SetTitleOffset(0.8);
   data_obs_pass_postfit_projy2_copy__335->GetYaxis()->SetTitleFont(42);
   data_obs_pass_postfit_projy2_copy__335->GetZaxis()->SetLabelFont(42);
   data_obs_pass_postfit_projy2_copy__335->GetZaxis()->SetLabelOffset(0.007);
   data_obs_pass_postfit_projy2_copy__335->GetZaxis()->SetLabelSize(0.05);
   data_obs_pass_postfit_projy2_copy__335->GetZaxis()->SetTitleSize(0.08);
   data_obs_pass_postfit_projy2_copy__335->GetZaxis()->SetTitleFont(42);
   data_obs_pass_postfit_projy2_copy__335->Draw("sameaxis");
   TLatex *   tex = new TLatex(0.21,0.83,"1.0 < G_{i}^{Strips} < 1.0 , F^{Pixels}_{i} > 0.9");
tex->SetNDC();
   tex->SetTextAlign(12);
   tex->SetTextFont(42);
   tex->SetTextSize(0.06);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.17,0.92,"CMS");
tex->SetNDC();
   tex->SetTextFont(61);
   tex->SetTextSize(0.0675);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.25,0.92,"Preliminary");
tex->SetNDC();
   tex->SetTextFont(52);
   tex->SetTextSize(0.0485);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.95,0.92,"101 fb^{-1} (13 TeV)");
tex->SetNDC();
   tex->SetTextAlign(31);
   tex->SetTextFont(42);
   tex->SetTextSize(0.07);
   tex->SetLineWidth(2);
   tex->Draw();
   data_obs_pass_postfit_projy2_main->Modified();
   plots_fit_s/base_figs/postfit_projy2_pass->cd();
  
// ------------>Primitives in pad: data_obs_pass_postfit_projy2_sub
   TPad *data_obs_pass_postfit_projy2_sub = new TPad("data_obs_pass_postfit_projy2_sub", "data_obs_pass_postfit_projy2_sub",0,0,1,0.35);
   data_obs_pass_postfit_projy2_sub->Draw();
   data_obs_pass_postfit_projy2_sub->cd();
   data_obs_pass_postfit_projy2_sub->Range(-633.6539,-6.023077,4270.192,2.9);
   data_obs_pass_postfit_projy2_sub->SetFillColor(0);
   data_obs_pass_postfit_projy2_sub->SetBorderMode(0);
   data_obs_pass_postfit_projy2_sub->SetBorderSize(2);
   data_obs_pass_postfit_projy2_sub->SetTickx(1);
   data_obs_pass_postfit_projy2_sub->SetTicky(1);
   data_obs_pass_postfit_projy2_sub->SetLeftMargin(0.17);
   data_obs_pass_postfit_projy2_sub->SetRightMargin(0.05);
   data_obs_pass_postfit_projy2_sub->SetTopMargin(0);
   data_obs_pass_postfit_projy2_sub->SetBottomMargin(0.35);
   data_obs_pass_postfit_projy2_sub->SetFrameFillStyle(0);
   data_obs_pass_postfit_projy2_sub->SetFrameBorderMode(0);
   data_obs_pass_postfit_projy2_sub->SetFrameFillStyle(0);
   data_obs_pass_postfit_projy2_sub->SetFrameBorderMode(0);
   Double_t xAxis504[2] = {200, 4025}; 
   
   TH1D *data_obs_pass_postfit_projy2_pull__336 = new TH1D("data_obs_pass_postfit_projy2_pull__336","",1, xAxis504);
   data_obs_pass_postfit_projy2_pull__336->SetMinimum(-2.9);
   data_obs_pass_postfit_projy2_pull__336->SetMaximum(2.9);
   data_obs_pass_postfit_projy2_pull__336->SetEntries(2);
   data_obs_pass_postfit_projy2_pull__336->SetStats(0);

   ci = TColor::GetColor("#0000ff");
   data_obs_pass_postfit_projy2_pull__336->SetFillColor(ci);

   ci = TColor::GetColor("#000000");
   data_obs_pass_postfit_projy2_pull__336->SetLineColor(ci);
   data_obs_pass_postfit_projy2_pull__336->SetLineStyle(0);

   ci = TColor::GetColor("#000000");
   data_obs_pass_postfit_projy2_pull__336->SetMarkerColor(ci);
   data_obs_pass_postfit_projy2_pull__336->SetMarkerStyle(8);
   data_obs_pass_postfit_projy2_pull__336->GetXaxis()->SetTitle("p_{T}");
   data_obs_pass_postfit_projy2_pull__336->GetXaxis()->SetLabelFont(42);
   data_obs_pass_postfit_projy2_pull__336->GetXaxis()->SetLabelOffset(0.05);
   data_obs_pass_postfit_projy2_pull__336->GetXaxis()->SetLabelSize(0.13);
   data_obs_pass_postfit_projy2_pull__336->GetXaxis()->SetTitleSize(0.15);
   data_obs_pass_postfit_projy2_pull__336->GetXaxis()->SetTitleOffset(1.15);
   data_obs_pass_postfit_projy2_pull__336->GetXaxis()->SetTitleFont(42);
   data_obs_pass_postfit_projy2_pull__336->GetYaxis()->SetTitle("(Data-Bkg)/#sigma");
   data_obs_pass_postfit_projy2_pull__336->GetYaxis()->SetNdivisions(306);
   data_obs_pass_postfit_projy2_pull__336->GetYaxis()->SetLabelFont(42);
   data_obs_pass_postfit_projy2_pull__336->GetYaxis()->SetLabelOffset(0.007);
   data_obs_pass_postfit_projy2_pull__336->GetYaxis()->SetLabelSize(0.13);
   data_obs_pass_postfit_projy2_pull__336->GetYaxis()->SetTitleSize(0.12);
   data_obs_pass_postfit_projy2_pull__336->GetYaxis()->SetTitleOffset(0.4);
   data_obs_pass_postfit_projy2_pull__336->GetYaxis()->SetTitleFont(42);
   data_obs_pass_postfit_projy2_pull__336->GetZaxis()->SetLabelFont(42);
   data_obs_pass_postfit_projy2_pull__336->GetZaxis()->SetLabelOffset(0.007);
   data_obs_pass_postfit_projy2_pull__336->GetZaxis()->SetLabelSize(0.05);
   data_obs_pass_postfit_projy2_pull__336->GetZaxis()->SetTitleSize(0.08);
   data_obs_pass_postfit_projy2_pull__336->GetZaxis()->SetTitleFont(42);
   data_obs_pass_postfit_projy2_pull__336->Draw("hist");
   data_obs_pass_postfit_projy2_sub->Modified();
   plots_fit_s/base_figs/postfit_projy2_pass->cd();
   plots_fit_s/base_figs/postfit_projy2_pass->Modified();
   plots_fit_s/base_figs/postfit_projy2_pass->cd();
   plots_fit_s/base_figs/postfit_projy2_pass->SetSelected(plots_fit_s/base_figs/postfit_projy2_pass);
}
