void postfit_projy2_fail_logy()
{
//=========Macro generated from canvas: plots_fit_s/base_figs/postfit_projy2_fail_logy/plots_fit_s/base_figs/postfit_projy2_fail_logy
//=========  (Fri Jan 12 20:33:23 2024) by ROOT version 6.14/09
   TCanvas *plots_fit_s/base_figs/postfit_projy2_fail_logy = new TCanvas("plots_fit_s/base_figs/postfit_projy2_fail_logy", "plots_fit_s/base_figs/postfit_projy2_fail_logy",0,0,800,700);
   gStyle->SetOptFit(1);
   gStyle->SetOptStat(0);
   plots_fit_s/base_figs/postfit_projy2_fail_logy->SetHighLightColor(2);
   plots_fit_s/base_figs/postfit_projy2_fail_logy->Range(0,0,1,1);
   plots_fit_s/base_figs/postfit_projy2_fail_logy->SetFillColor(0);
   plots_fit_s/base_figs/postfit_projy2_fail_logy->SetBorderMode(0);
   plots_fit_s/base_figs/postfit_projy2_fail_logy->SetBorderSize(2);
   plots_fit_s/base_figs/postfit_projy2_fail_logy->SetTickx(1);
   plots_fit_s/base_figs/postfit_projy2_fail_logy->SetTicky(1);
   plots_fit_s/base_figs/postfit_projy2_fail_logy->SetLeftMargin(0.16);
   plots_fit_s/base_figs/postfit_projy2_fail_logy->SetRightMargin(0);
   plots_fit_s/base_figs/postfit_projy2_fail_logy->SetTopMargin(0);
   plots_fit_s/base_figs/postfit_projy2_fail_logy->SetBottomMargin(0);
   plots_fit_s/base_figs/postfit_projy2_fail_logy->SetFrameFillStyle(0);
   plots_fit_s/base_figs/postfit_projy2_fail_logy->SetFrameBorderMode(0);
  
// ------------>Primitives in pad: data_obs_fail_postfit_projy2_main
   TPad *data_obs_fail_postfit_projy2_main = new TPad("data_obs_fail_postfit_projy2_main", "data_obs_fail_postfit_projy2_main",0,0.35,1,1);
   data_obs_fail_postfit_projy2_main->Draw();
   data_obs_fail_postfit_projy2_main->cd();
   data_obs_fail_postfit_projy2_main->Range(-633.6539,-2.139535,4270.192,1.348837);
   data_obs_fail_postfit_projy2_main->SetFillColor(0);
   data_obs_fail_postfit_projy2_main->SetBorderMode(0);
   data_obs_fail_postfit_projy2_main->SetBorderSize(2);
   data_obs_fail_postfit_projy2_main->SetLogy();
   data_obs_fail_postfit_projy2_main->SetTickx(1);
   data_obs_fail_postfit_projy2_main->SetTicky(1);
   data_obs_fail_postfit_projy2_main->SetLeftMargin(0.17);
   data_obs_fail_postfit_projy2_main->SetRightMargin(0.05);
   data_obs_fail_postfit_projy2_main->SetBottomMargin(0.04);
   data_obs_fail_postfit_projy2_main->SetFrameFillStyle(0);
   data_obs_fail_postfit_projy2_main->SetFrameBorderMode(0);
   data_obs_fail_postfit_projy2_main->SetFrameFillStyle(0);
   data_obs_fail_postfit_projy2_main->SetFrameBorderMode(0);
   Double_t xAxis421[2] = {200, 4025}; 
   
   TH1D *data_obs_fail_postfit_projy2__281 = new TH1D("data_obs_fail_postfit_projy2__281","",1, xAxis421);
   data_obs_fail_postfit_projy2__281->SetMinimum(0.001);
   data_obs_fail_postfit_projy2__281->SetMaximum(0);

   Int_t ci;      // for color index setting
   TColor *color; // for color definition with alpha
   ci = TColor::GetColor("#000000");
   data_obs_fail_postfit_projy2__281->SetLineColor(ci);
   data_obs_fail_postfit_projy2__281->SetLineStyle(0);

   ci = TColor::GetColor("#000000");
   data_obs_fail_postfit_projy2__281->SetMarkerColor(ci);
   data_obs_fail_postfit_projy2__281->SetMarkerStyle(8);
   data_obs_fail_postfit_projy2__281->GetXaxis()->SetTitle("p_{T}");
   data_obs_fail_postfit_projy2__281->GetXaxis()->SetLabelFont(42);
   data_obs_fail_postfit_projy2__281->GetXaxis()->SetLabelOffset(0.05);
   data_obs_fail_postfit_projy2__281->GetXaxis()->SetLabelSize(0.07);
   data_obs_fail_postfit_projy2__281->GetXaxis()->SetTitleSize(0.09);
   data_obs_fail_postfit_projy2__281->GetXaxis()->SetTitleOffset(1.15);
   data_obs_fail_postfit_projy2__281->GetXaxis()->SetTitleFont(42);
   data_obs_fail_postfit_projy2__281->GetYaxis()->SetTitle("Events / bin");
   data_obs_fail_postfit_projy2__281->GetYaxis()->SetNdivisions(508);
   data_obs_fail_postfit_projy2__281->GetYaxis()->SetLabelFont(42);
   data_obs_fail_postfit_projy2__281->GetYaxis()->SetLabelOffset(0.007);
   data_obs_fail_postfit_projy2__281->GetYaxis()->SetLabelSize(0.07);
   data_obs_fail_postfit_projy2__281->GetYaxis()->SetTitleSize(0.09);
   data_obs_fail_postfit_projy2__281->GetYaxis()->SetTitleOffset(0.8);
   data_obs_fail_postfit_projy2__281->GetYaxis()->SetTitleFont(42);
   data_obs_fail_postfit_projy2__281->GetZaxis()->SetLabelFont(42);
   data_obs_fail_postfit_projy2__281->GetZaxis()->SetLabelOffset(0.007);
   data_obs_fail_postfit_projy2__281->GetZaxis()->SetLabelSize(0.05);
   data_obs_fail_postfit_projy2__281->GetZaxis()->SetTitleSize(0.08);
   data_obs_fail_postfit_projy2__281->GetZaxis()->SetTitleFont(42);
   data_obs_fail_postfit_projy2__281->Draw("pe X0");
   
   THStack *postfit_projy2_fail_logy_stack = new THStack();
   postfit_projy2_fail_logy_stack->SetName("postfit_projy2_fail_logy_stack");
   postfit_projy2_fail_logy_stack->SetTitle("postfit_projy2_fail_logy_stack");
   postfit_projy2_fail_logy_stack->SetMinimum(0.001);
   Double_t xAxis422[2] = {200, 4025}; 
   
   TH1F *postfit_projy2_fail_logy_stack_stack_71 = new TH1F("postfit_projy2_fail_logy_stack_stack_71","postfit_projy2_fail_logy_stack",1, xAxis422);
   postfit_projy2_fail_logy_stack_stack_71->SetMinimum(-0);
   postfit_projy2_fail_logy_stack_stack_71->SetMaximum(-nan);
   postfit_projy2_fail_logy_stack_stack_71->SetDirectory(0);
   postfit_projy2_fail_logy_stack_stack_71->SetStats(0);
   postfit_projy2_fail_logy_stack_stack_71->SetLineStyle(0);
   postfit_projy2_fail_logy_stack_stack_71->GetXaxis()->SetLabelFont(42);
   postfit_projy2_fail_logy_stack_stack_71->GetXaxis()->SetLabelOffset(0.007);
   postfit_projy2_fail_logy_stack_stack_71->GetXaxis()->SetLabelSize(0.05);
   postfit_projy2_fail_logy_stack_stack_71->GetXaxis()->SetTitleSize(0.08);
   postfit_projy2_fail_logy_stack_stack_71->GetXaxis()->SetTitleOffset(0.9);
   postfit_projy2_fail_logy_stack_stack_71->GetXaxis()->SetTitleFont(42);
   postfit_projy2_fail_logy_stack_stack_71->GetYaxis()->SetNdivisions(508);
   postfit_projy2_fail_logy_stack_stack_71->GetYaxis()->SetLabelFont(42);
   postfit_projy2_fail_logy_stack_stack_71->GetYaxis()->SetLabelOffset(0.007);
   postfit_projy2_fail_logy_stack_stack_71->GetYaxis()->SetLabelSize(0.05);
   postfit_projy2_fail_logy_stack_stack_71->GetYaxis()->SetTitleSize(0.08);
   postfit_projy2_fail_logy_stack_stack_71->GetYaxis()->SetTitleOffset(1.25);
   postfit_projy2_fail_logy_stack_stack_71->GetYaxis()->SetTitleFont(42);
   postfit_projy2_fail_logy_stack_stack_71->GetZaxis()->SetLabelFont(42);
   postfit_projy2_fail_logy_stack_stack_71->GetZaxis()->SetLabelOffset(0.007);
   postfit_projy2_fail_logy_stack_stack_71->GetZaxis()->SetLabelSize(0.05);
   postfit_projy2_fail_logy_stack_stack_71->GetZaxis()->SetTitleSize(0.08);
   postfit_projy2_fail_logy_stack_stack_71->GetZaxis()->SetTitleFont(42);
   postfit_projy2_fail_logy_stack->SetHistogram(postfit_projy2_fail_logy_stack_stack_71);
   
   Double_t xAxis423[2] = {200, 4025}; 
   
   TH1D *Background_fail_postfit_projy2_stack_1 = new TH1D("Background_fail_postfit_projy2_stack_1","Background, fail, postfit, 1.0-1.0",1, xAxis423);
   Background_fail_postfit_projy2_stack_1->SetMinimum(0.001);

   ci = TColor::GetColor("#ffff00");
   Background_fail_postfit_projy2_stack_1->SetFillColor(ci);

   ci = 1334;
   color = new TColor(ci, 1, 1, 1, " ", 0);
   Background_fail_postfit_projy2_stack_1->SetLineColor(ci);
   Background_fail_postfit_projy2_stack_1->SetLineStyle(0);
   Background_fail_postfit_projy2_stack_1->GetXaxis()->SetTitle("p_{T}");
   Background_fail_postfit_projy2_stack_1->GetXaxis()->SetLabelFont(42);
   Background_fail_postfit_projy2_stack_1->GetXaxis()->SetLabelOffset(0.007);
   Background_fail_postfit_projy2_stack_1->GetXaxis()->SetLabelSize(0.05);
   Background_fail_postfit_projy2_stack_1->GetXaxis()->SetTitleSize(0.08);
   Background_fail_postfit_projy2_stack_1->GetXaxis()->SetTitleOffset(1.25);
   Background_fail_postfit_projy2_stack_1->GetXaxis()->SetTitleFont(42);
   Background_fail_postfit_projy2_stack_1->GetYaxis()->SetTitle("Events / bin");
   Background_fail_postfit_projy2_stack_1->GetYaxis()->SetLabelFont(42);
   Background_fail_postfit_projy2_stack_1->GetYaxis()->SetLabelOffset(0.007);
   Background_fail_postfit_projy2_stack_1->GetYaxis()->SetLabelSize(0.05);
   Background_fail_postfit_projy2_stack_1->GetYaxis()->SetTitleSize(0.08);
   Background_fail_postfit_projy2_stack_1->GetYaxis()->SetTitleOffset(1.25);
   Background_fail_postfit_projy2_stack_1->GetYaxis()->SetTitleFont(42);
   Background_fail_postfit_projy2_stack_1->GetZaxis()->SetLabelFont(42);
   Background_fail_postfit_projy2_stack_1->GetZaxis()->SetLabelOffset(0.007);
   Background_fail_postfit_projy2_stack_1->GetZaxis()->SetLabelSize(0.05);
   Background_fail_postfit_projy2_stack_1->GetZaxis()->SetTitleSize(0.08);
   Background_fail_postfit_projy2_stack_1->GetZaxis()->SetTitleFont(42);
   postfit_projy2_fail_logy_stack->Add(Background_fail_postfit_projy2_stack_1,"");
   postfit_projy2_fail_logy_stack->Draw("hist same");
   
   postfit_projy2_fail_logy_stack = new THStack();
   postfit_projy2_fail_logy_stack->SetName("postfit_projy2_fail_logy_stack");
   postfit_projy2_fail_logy_stack->SetTitle("postfit_projy2_fail_logy_stack");
   postfit_projy2_fail_logy_stack->SetMinimum(0.001);
   Double_t xAxis424[2] = {200, 4025}; 
   
   TH1F *postfit_projy2_fail_logy_stack_stack_71_stack_72 = new TH1F("postfit_projy2_fail_logy_stack_stack_71_stack_72","postfit_projy2_fail_logy_stack",1, xAxis424);
   postfit_projy2_fail_logy_stack_stack_71_stack_72->SetMinimum(-0);
   postfit_projy2_fail_logy_stack_stack_71_stack_72->SetMaximum(-nan);
   postfit_projy2_fail_logy_stack_stack_71_stack_72->SetDirectory(0);
   postfit_projy2_fail_logy_stack_stack_71_stack_72->SetStats(0);
   postfit_projy2_fail_logy_stack_stack_71_stack_72->SetLineStyle(0);
   postfit_projy2_fail_logy_stack_stack_71_stack_72->GetXaxis()->SetLabelFont(42);
   postfit_projy2_fail_logy_stack_stack_71_stack_72->GetXaxis()->SetLabelOffset(0.007);
   postfit_projy2_fail_logy_stack_stack_71_stack_72->GetXaxis()->SetLabelSize(0.05);
   postfit_projy2_fail_logy_stack_stack_71_stack_72->GetXaxis()->SetTitleSize(0.08);
   postfit_projy2_fail_logy_stack_stack_71_stack_72->GetXaxis()->SetTitleOffset(0.9);
   postfit_projy2_fail_logy_stack_stack_71_stack_72->GetXaxis()->SetTitleFont(42);
   postfit_projy2_fail_logy_stack_stack_71_stack_72->GetYaxis()->SetNdivisions(508);
   postfit_projy2_fail_logy_stack_stack_71_stack_72->GetYaxis()->SetLabelFont(42);
   postfit_projy2_fail_logy_stack_stack_71_stack_72->GetYaxis()->SetLabelOffset(0.007);
   postfit_projy2_fail_logy_stack_stack_71_stack_72->GetYaxis()->SetLabelSize(0.05);
   postfit_projy2_fail_logy_stack_stack_71_stack_72->GetYaxis()->SetTitleSize(0.08);
   postfit_projy2_fail_logy_stack_stack_71_stack_72->GetYaxis()->SetTitleOffset(1.25);
   postfit_projy2_fail_logy_stack_stack_71_stack_72->GetYaxis()->SetTitleFont(42);
   postfit_projy2_fail_logy_stack_stack_71_stack_72->GetZaxis()->SetLabelFont(42);
   postfit_projy2_fail_logy_stack_stack_71_stack_72->GetZaxis()->SetLabelOffset(0.007);
   postfit_projy2_fail_logy_stack_stack_71_stack_72->GetZaxis()->SetLabelSize(0.05);
   postfit_projy2_fail_logy_stack_stack_71_stack_72->GetZaxis()->SetTitleSize(0.08);
   postfit_projy2_fail_logy_stack_stack_71_stack_72->GetZaxis()->SetTitleFont(42);
   postfit_projy2_fail_logy_stack->SetHistogram(postfit_projy2_fail_logy_stack_stack_71_stack_72);
   
   Double_t xAxis425[2] = {200, 4025}; 
   
   TH1D *Background_fail_postfit_projy2_stack_1_stack_1 = new TH1D("Background_fail_postfit_projy2_stack_1_stack_1","Background, fail, postfit, 1.0-1.0",1, xAxis425);
   Background_fail_postfit_projy2_stack_1_stack_1->SetMinimum(0.001);

   ci = TColor::GetColor("#ffff00");
   Background_fail_postfit_projy2_stack_1_stack_1->SetFillColor(ci);

   ci = 1334;
   color = new TColor(ci, 1, 1, 1, " ", 0);
   Background_fail_postfit_projy2_stack_1_stack_1->SetLineColor(ci);
   Background_fail_postfit_projy2_stack_1_stack_1->SetLineStyle(0);
   Background_fail_postfit_projy2_stack_1_stack_1->GetXaxis()->SetTitle("p_{T}");
   Background_fail_postfit_projy2_stack_1_stack_1->GetXaxis()->SetLabelFont(42);
   Background_fail_postfit_projy2_stack_1_stack_1->GetXaxis()->SetLabelOffset(0.007);
   Background_fail_postfit_projy2_stack_1_stack_1->GetXaxis()->SetLabelSize(0.05);
   Background_fail_postfit_projy2_stack_1_stack_1->GetXaxis()->SetTitleSize(0.08);
   Background_fail_postfit_projy2_stack_1_stack_1->GetXaxis()->SetTitleOffset(1.25);
   Background_fail_postfit_projy2_stack_1_stack_1->GetXaxis()->SetTitleFont(42);
   Background_fail_postfit_projy2_stack_1_stack_1->GetYaxis()->SetTitle("Events / bin");
   Background_fail_postfit_projy2_stack_1_stack_1->GetYaxis()->SetLabelFont(42);
   Background_fail_postfit_projy2_stack_1_stack_1->GetYaxis()->SetLabelOffset(0.007);
   Background_fail_postfit_projy2_stack_1_stack_1->GetYaxis()->SetLabelSize(0.05);
   Background_fail_postfit_projy2_stack_1_stack_1->GetYaxis()->SetTitleSize(0.08);
   Background_fail_postfit_projy2_stack_1_stack_1->GetYaxis()->SetTitleOffset(1.25);
   Background_fail_postfit_projy2_stack_1_stack_1->GetYaxis()->SetTitleFont(42);
   Background_fail_postfit_projy2_stack_1_stack_1->GetZaxis()->SetLabelFont(42);
   Background_fail_postfit_projy2_stack_1_stack_1->GetZaxis()->SetLabelOffset(0.007);
   Background_fail_postfit_projy2_stack_1_stack_1->GetZaxis()->SetLabelSize(0.05);
   Background_fail_postfit_projy2_stack_1_stack_1->GetZaxis()->SetTitleSize(0.08);
   Background_fail_postfit_projy2_stack_1_stack_1->GetZaxis()->SetTitleFont(42);
   postfit_projy2_fail_logy_stack->Add(Background_fail_postfit_projy2_stack_1_stack_1,"");
   postfit_projy2_fail_logy_stack->Draw("hist same");
   Double_t xAxis426[2] = {200, 4025}; 
   
   TH1D *Signal_gluinomI1800_fail_postfit_projy2__282 = new TH1D("Signal_gluinomI1800_fail_postfit_projy2__282","HSCP gluino 1800 GeV, fail, postfit, 1.0-1.0",1, xAxis426);
   Signal_gluinomI1800_fail_postfit_projy2__282->SetMinimum(0.001);
   Signal_gluinomI1800_fail_postfit_projy2__282->SetLineColor(4);
   Signal_gluinomI1800_fail_postfit_projy2__282->SetLineStyle(0);
   Signal_gluinomI1800_fail_postfit_projy2__282->SetLineWidth(2);
   Signal_gluinomI1800_fail_postfit_projy2__282->GetXaxis()->SetTitle("p_{T}");
   Signal_gluinomI1800_fail_postfit_projy2__282->GetXaxis()->SetLabelFont(42);
   Signal_gluinomI1800_fail_postfit_projy2__282->GetXaxis()->SetLabelOffset(0.007);
   Signal_gluinomI1800_fail_postfit_projy2__282->GetXaxis()->SetLabelSize(0.05);
   Signal_gluinomI1800_fail_postfit_projy2__282->GetXaxis()->SetTitleSize(0.08);
   Signal_gluinomI1800_fail_postfit_projy2__282->GetXaxis()->SetTitleOffset(1.25);
   Signal_gluinomI1800_fail_postfit_projy2__282->GetXaxis()->SetTitleFont(42);
   Signal_gluinomI1800_fail_postfit_projy2__282->GetYaxis()->SetTitle("Events / bin");
   Signal_gluinomI1800_fail_postfit_projy2__282->GetYaxis()->SetLabelFont(42);
   Signal_gluinomI1800_fail_postfit_projy2__282->GetYaxis()->SetLabelOffset(0.007);
   Signal_gluinomI1800_fail_postfit_projy2__282->GetYaxis()->SetLabelSize(0.05);
   Signal_gluinomI1800_fail_postfit_projy2__282->GetYaxis()->SetTitleSize(0.08);
   Signal_gluinomI1800_fail_postfit_projy2__282->GetYaxis()->SetTitleOffset(1.25);
   Signal_gluinomI1800_fail_postfit_projy2__282->GetYaxis()->SetTitleFont(42);
   Signal_gluinomI1800_fail_postfit_projy2__282->GetZaxis()->SetLabelFont(42);
   Signal_gluinomI1800_fail_postfit_projy2__282->GetZaxis()->SetLabelOffset(0.007);
   Signal_gluinomI1800_fail_postfit_projy2__282->GetZaxis()->SetLabelSize(0.05);
   Signal_gluinomI1800_fail_postfit_projy2__282->GetZaxis()->SetTitleSize(0.08);
   Signal_gluinomI1800_fail_postfit_projy2__282->GetZaxis()->SetTitleFont(42);
   Signal_gluinomI1800_fail_postfit_projy2__282->Draw("hist same");
   Double_t xAxis427[2] = {200, 4025}; 
   
   TH1D *Signal_ppStaumI557_fail_postfit_projy2__283 = new TH1D("Signal_ppStaumI557_fail_postfit_projy2__283","HSCP stau 557 GeV, fail, postfit, 1.0-1.0",1, xAxis427);
   Signal_ppStaumI557_fail_postfit_projy2__283->SetMinimum(0.001);
   Signal_ppStaumI557_fail_postfit_projy2__283->SetLineColor(2);
   Signal_ppStaumI557_fail_postfit_projy2__283->SetLineStyle(0);
   Signal_ppStaumI557_fail_postfit_projy2__283->SetLineWidth(2);
   Signal_ppStaumI557_fail_postfit_projy2__283->GetXaxis()->SetTitle("p_{T}");
   Signal_ppStaumI557_fail_postfit_projy2__283->GetXaxis()->SetLabelFont(42);
   Signal_ppStaumI557_fail_postfit_projy2__283->GetXaxis()->SetLabelOffset(0.007);
   Signal_ppStaumI557_fail_postfit_projy2__283->GetXaxis()->SetLabelSize(0.05);
   Signal_ppStaumI557_fail_postfit_projy2__283->GetXaxis()->SetTitleSize(0.08);
   Signal_ppStaumI557_fail_postfit_projy2__283->GetXaxis()->SetTitleOffset(1.25);
   Signal_ppStaumI557_fail_postfit_projy2__283->GetXaxis()->SetTitleFont(42);
   Signal_ppStaumI557_fail_postfit_projy2__283->GetYaxis()->SetTitle("Events / bin");
   Signal_ppStaumI557_fail_postfit_projy2__283->GetYaxis()->SetLabelFont(42);
   Signal_ppStaumI557_fail_postfit_projy2__283->GetYaxis()->SetLabelOffset(0.007);
   Signal_ppStaumI557_fail_postfit_projy2__283->GetYaxis()->SetLabelSize(0.05);
   Signal_ppStaumI557_fail_postfit_projy2__283->GetYaxis()->SetTitleSize(0.08);
   Signal_ppStaumI557_fail_postfit_projy2__283->GetYaxis()->SetTitleOffset(1.25);
   Signal_ppStaumI557_fail_postfit_projy2__283->GetYaxis()->SetTitleFont(42);
   Signal_ppStaumI557_fail_postfit_projy2__283->GetZaxis()->SetLabelFont(42);
   Signal_ppStaumI557_fail_postfit_projy2__283->GetZaxis()->SetLabelOffset(0.007);
   Signal_ppStaumI557_fail_postfit_projy2__283->GetZaxis()->SetLabelSize(0.05);
   Signal_ppStaumI557_fail_postfit_projy2__283->GetZaxis()->SetTitleSize(0.08);
   Signal_ppStaumI557_fail_postfit_projy2__283->GetZaxis()->SetTitleFont(42);
   Signal_ppStaumI557_fail_postfit_projy2__283->Draw("hist same");
   Double_t xAxis428[2] = {200, 4025}; 
   
   TH1D *TotalBkg_fail_postfit_projy2__284 = new TH1D("TotalBkg_fail_postfit_projy2__284","TotalBkg, fail, postfit, 1.0-1.0",1, xAxis428);
   TotalBkg_fail_postfit_projy2__284->SetMinimum(0.001);
   TotalBkg_fail_postfit_projy2__284->SetLineStyle(0);
   TotalBkg_fail_postfit_projy2__284->SetMarkerStyle(0);
   TotalBkg_fail_postfit_projy2__284->GetXaxis()->SetTitle("p_{T}");
   TotalBkg_fail_postfit_projy2__284->GetXaxis()->SetLabelFont(42);
   TotalBkg_fail_postfit_projy2__284->GetXaxis()->SetLabelOffset(0.007);
   TotalBkg_fail_postfit_projy2__284->GetXaxis()->SetLabelSize(0.05);
   TotalBkg_fail_postfit_projy2__284->GetXaxis()->SetTitleSize(0.08);
   TotalBkg_fail_postfit_projy2__284->GetXaxis()->SetTitleOffset(1.25);
   TotalBkg_fail_postfit_projy2__284->GetXaxis()->SetTitleFont(42);
   TotalBkg_fail_postfit_projy2__284->GetYaxis()->SetTitle("Events / bin");
   TotalBkg_fail_postfit_projy2__284->GetYaxis()->SetLabelFont(42);
   TotalBkg_fail_postfit_projy2__284->GetYaxis()->SetLabelOffset(0.007);
   TotalBkg_fail_postfit_projy2__284->GetYaxis()->SetLabelSize(0.05);
   TotalBkg_fail_postfit_projy2__284->GetYaxis()->SetTitleSize(0.08);
   TotalBkg_fail_postfit_projy2__284->GetYaxis()->SetTitleOffset(1.25);
   TotalBkg_fail_postfit_projy2__284->GetYaxis()->SetTitleFont(42);
   TotalBkg_fail_postfit_projy2__284->GetZaxis()->SetLabelFont(42);
   TotalBkg_fail_postfit_projy2__284->GetZaxis()->SetLabelOffset(0.007);
   TotalBkg_fail_postfit_projy2__284->GetZaxis()->SetLabelSize(0.05);
   TotalBkg_fail_postfit_projy2__284->GetZaxis()->SetTitleSize(0.08);
   TotalBkg_fail_postfit_projy2__284->GetZaxis()->SetTitleFont(42);
   TotalBkg_fail_postfit_projy2__284->Draw("hist same");
   Double_t xAxis429[2] = {200, 4025}; 
   
   TH1D *TotalBkg_fail_postfit_projy2__285 = new TH1D("TotalBkg_fail_postfit_projy2__285","TotalBkg, fail, postfit, 1.0-1.0",1, xAxis429);
   TotalBkg_fail_postfit_projy2__285->SetMinimum(0.001);
   TotalBkg_fail_postfit_projy2__285->SetFillColor(1);
   TotalBkg_fail_postfit_projy2__285->SetFillStyle(3354);
   TotalBkg_fail_postfit_projy2__285->SetLineStyle(0);
   TotalBkg_fail_postfit_projy2__285->SetLineWidth(0);
   TotalBkg_fail_postfit_projy2__285->SetMarkerStyle(0);
   TotalBkg_fail_postfit_projy2__285->GetXaxis()->SetTitle("p_{T}");
   TotalBkg_fail_postfit_projy2__285->GetXaxis()->SetLabelFont(42);
   TotalBkg_fail_postfit_projy2__285->GetXaxis()->SetLabelOffset(0.007);
   TotalBkg_fail_postfit_projy2__285->GetXaxis()->SetLabelSize(0.05);
   TotalBkg_fail_postfit_projy2__285->GetXaxis()->SetTitleSize(0.08);
   TotalBkg_fail_postfit_projy2__285->GetXaxis()->SetTitleOffset(1.25);
   TotalBkg_fail_postfit_projy2__285->GetXaxis()->SetTitleFont(42);
   TotalBkg_fail_postfit_projy2__285->GetYaxis()->SetTitle("Events / bin");
   TotalBkg_fail_postfit_projy2__285->GetYaxis()->SetLabelFont(42);
   TotalBkg_fail_postfit_projy2__285->GetYaxis()->SetLabelOffset(0.007);
   TotalBkg_fail_postfit_projy2__285->GetYaxis()->SetLabelSize(0.05);
   TotalBkg_fail_postfit_projy2__285->GetYaxis()->SetTitleSize(0.08);
   TotalBkg_fail_postfit_projy2__285->GetYaxis()->SetTitleOffset(1.25);
   TotalBkg_fail_postfit_projy2__285->GetYaxis()->SetTitleFont(42);
   TotalBkg_fail_postfit_projy2__285->GetZaxis()->SetLabelFont(42);
   TotalBkg_fail_postfit_projy2__285->GetZaxis()->SetLabelOffset(0.007);
   TotalBkg_fail_postfit_projy2__285->GetZaxis()->SetLabelSize(0.05);
   TotalBkg_fail_postfit_projy2__285->GetZaxis()->SetTitleSize(0.08);
   TotalBkg_fail_postfit_projy2__285->GetZaxis()->SetTitleFont(42);
   TotalBkg_fail_postfit_projy2__285->Draw("e2 same");
   Double_t xAxis430[2] = {200, 4025}; 
   
   TH1D *data_obs_fail_postfit_projy2__286 = new TH1D("data_obs_fail_postfit_projy2__286","",1, xAxis430);
   data_obs_fail_postfit_projy2__286->SetMinimum(0.001);
   data_obs_fail_postfit_projy2__286->SetMaximum(0);

   ci = TColor::GetColor("#000000");
   data_obs_fail_postfit_projy2__286->SetLineColor(ci);
   data_obs_fail_postfit_projy2__286->SetLineStyle(0);

   ci = TColor::GetColor("#000000");
   data_obs_fail_postfit_projy2__286->SetMarkerColor(ci);
   data_obs_fail_postfit_projy2__286->SetMarkerStyle(8);
   data_obs_fail_postfit_projy2__286->GetXaxis()->SetTitle("p_{T}");
   data_obs_fail_postfit_projy2__286->GetXaxis()->SetLabelFont(42);
   data_obs_fail_postfit_projy2__286->GetXaxis()->SetLabelOffset(0.05);
   data_obs_fail_postfit_projy2__286->GetXaxis()->SetLabelSize(0.07);
   data_obs_fail_postfit_projy2__286->GetXaxis()->SetTitleSize(0.09);
   data_obs_fail_postfit_projy2__286->GetXaxis()->SetTitleOffset(1.15);
   data_obs_fail_postfit_projy2__286->GetXaxis()->SetTitleFont(42);
   data_obs_fail_postfit_projy2__286->GetYaxis()->SetTitle("Events / bin");
   data_obs_fail_postfit_projy2__286->GetYaxis()->SetNdivisions(508);
   data_obs_fail_postfit_projy2__286->GetYaxis()->SetLabelFont(42);
   data_obs_fail_postfit_projy2__286->GetYaxis()->SetLabelOffset(0.007);
   data_obs_fail_postfit_projy2__286->GetYaxis()->SetLabelSize(0.07);
   data_obs_fail_postfit_projy2__286->GetYaxis()->SetTitleSize(0.09);
   data_obs_fail_postfit_projy2__286->GetYaxis()->SetTitleOffset(0.8);
   data_obs_fail_postfit_projy2__286->GetYaxis()->SetTitleFont(42);
   data_obs_fail_postfit_projy2__286->GetZaxis()->SetLabelFont(42);
   data_obs_fail_postfit_projy2__286->GetZaxis()->SetLabelOffset(0.007);
   data_obs_fail_postfit_projy2__286->GetZaxis()->SetLabelSize(0.05);
   data_obs_fail_postfit_projy2__286->GetZaxis()->SetTitleSize(0.08);
   data_obs_fail_postfit_projy2__286->GetZaxis()->SetTitleFont(42);
   data_obs_fail_postfit_projy2__286->Draw("pe X0 same");
   
   TLegend *leg = new TLegend(0.65,0.61,0.9,0.88,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(1001);
   TLegendEntry *entry=leg->AddEntry("data_obs_fail_postfit_projy2","Data","pe X0");

   ci = TColor::GetColor("#000000");
   entry->SetLineColor(ci);
   entry->SetLineWidth(1);

   ci = TColor::GetColor("#000000");
   entry->SetMarkerColor(ci);
   entry->SetMarkerStyle(8);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("TotalBkg_fail_postfit_projy2","Total bkg unc.","F");
   entry->SetFillColor(1);
   entry->SetFillStyle(3354);
   entry->SetLineColor(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("Signal_gluino-1800_fail_postfit_projy2","HSCP gluino 1800 GeV","L");
   entry->SetLineColor(4);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("Signal_ppStau-557_fail_postfit_projy2","HSCP stau 557 GeV","L");
   entry->SetLineColor(2);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("Background_fail_postfit_projy2_stack_1_stack_1","Background","f");

   ci = TColor::GetColor("#ffff00");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = 1334;
   color = new TColor(ci, 1, 1, 1, " ", 0);
   entry->SetLineColor(ci);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   leg->Draw();
   Double_t xAxis431[2] = {200, 4025}; 
   
   TH1D *data_obs_fail_postfit_projy2_copy__287 = new TH1D("data_obs_fail_postfit_projy2_copy__287","",1, xAxis431);
   data_obs_fail_postfit_projy2_copy__287->SetMinimum(0.001);
   data_obs_fail_postfit_projy2_copy__287->SetMaximum(0);
   data_obs_fail_postfit_projy2_copy__287->SetDirectory(0);

   ci = TColor::GetColor("#000000");
   data_obs_fail_postfit_projy2_copy__287->SetLineColor(ci);
   data_obs_fail_postfit_projy2_copy__287->SetLineStyle(0);

   ci = TColor::GetColor("#000000");
   data_obs_fail_postfit_projy2_copy__287->SetMarkerColor(ci);
   data_obs_fail_postfit_projy2_copy__287->SetMarkerStyle(8);
   data_obs_fail_postfit_projy2_copy__287->GetXaxis()->SetTitle("p_{T}");
   data_obs_fail_postfit_projy2_copy__287->GetXaxis()->SetLabelFont(42);
   data_obs_fail_postfit_projy2_copy__287->GetXaxis()->SetLabelOffset(0.05);
   data_obs_fail_postfit_projy2_copy__287->GetXaxis()->SetLabelSize(0.07);
   data_obs_fail_postfit_projy2_copy__287->GetXaxis()->SetTitleSize(0.09);
   data_obs_fail_postfit_projy2_copy__287->GetXaxis()->SetTitleOffset(1.15);
   data_obs_fail_postfit_projy2_copy__287->GetXaxis()->SetTitleFont(42);
   data_obs_fail_postfit_projy2_copy__287->GetYaxis()->SetTitle("Events / bin");
   data_obs_fail_postfit_projy2_copy__287->GetYaxis()->SetNdivisions(508);
   data_obs_fail_postfit_projy2_copy__287->GetYaxis()->SetLabelFont(42);
   data_obs_fail_postfit_projy2_copy__287->GetYaxis()->SetLabelOffset(0.007);
   data_obs_fail_postfit_projy2_copy__287->GetYaxis()->SetLabelSize(0.07);
   data_obs_fail_postfit_projy2_copy__287->GetYaxis()->SetTitleSize(0.09);
   data_obs_fail_postfit_projy2_copy__287->GetYaxis()->SetTitleOffset(0.8);
   data_obs_fail_postfit_projy2_copy__287->GetYaxis()->SetTitleFont(42);
   data_obs_fail_postfit_projy2_copy__287->GetZaxis()->SetLabelFont(42);
   data_obs_fail_postfit_projy2_copy__287->GetZaxis()->SetLabelOffset(0.007);
   data_obs_fail_postfit_projy2_copy__287->GetZaxis()->SetLabelSize(0.05);
   data_obs_fail_postfit_projy2_copy__287->GetZaxis()->SetTitleSize(0.08);
   data_obs_fail_postfit_projy2_copy__287->GetZaxis()->SetTitleFont(42);
   data_obs_fail_postfit_projy2_copy__287->Draw("sameaxis");
   TLatex *   tex = new TLatex(0.21,0.83,"1.0 < G_{i}^{Strips} < 1.0 , F^{Pixels}_{i} < 0.9");
tex->SetNDC();
   tex->SetTextAlign(12);
   tex->SetTextFont(42);
   tex->SetTextSize(0.06);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.17,0.92,"CMS");
tex->SetNDC();
   tex->SetTextFont(61);
   tex->SetTextSize(0.0675);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.25,0.92,"Preliminary");
tex->SetNDC();
   tex->SetTextFont(52);
   tex->SetTextSize(0.0485);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.95,0.92,"101 fb^{-1} (13 TeV)");
tex->SetNDC();
   tex->SetTextAlign(31);
   tex->SetTextFont(42);
   tex->SetTextSize(0.07);
   tex->SetLineWidth(2);
   tex->Draw();
   data_obs_fail_postfit_projy2_main->Modified();
   plots_fit_s/base_figs/postfit_projy2_fail_logy->cd();
  
// ------------>Primitives in pad: data_obs_fail_postfit_projy2_sub
   TPad *data_obs_fail_postfit_projy2_sub = new TPad("data_obs_fail_postfit_projy2_sub", "data_obs_fail_postfit_projy2_sub",0,0,1,0.35);
   data_obs_fail_postfit_projy2_sub->Draw();
   data_obs_fail_postfit_projy2_sub->cd();
   data_obs_fail_postfit_projy2_sub->Range(-633.6539,-6.023077,4270.192,2.9);
   data_obs_fail_postfit_projy2_sub->SetFillColor(0);
   data_obs_fail_postfit_projy2_sub->SetBorderMode(0);
   data_obs_fail_postfit_projy2_sub->SetBorderSize(2);
   data_obs_fail_postfit_projy2_sub->SetTickx(1);
   data_obs_fail_postfit_projy2_sub->SetTicky(1);
   data_obs_fail_postfit_projy2_sub->SetLeftMargin(0.17);
   data_obs_fail_postfit_projy2_sub->SetRightMargin(0.05);
   data_obs_fail_postfit_projy2_sub->SetTopMargin(0);
   data_obs_fail_postfit_projy2_sub->SetBottomMargin(0.35);
   data_obs_fail_postfit_projy2_sub->SetFrameFillStyle(0);
   data_obs_fail_postfit_projy2_sub->SetFrameBorderMode(0);
   data_obs_fail_postfit_projy2_sub->SetFrameFillStyle(0);
   data_obs_fail_postfit_projy2_sub->SetFrameBorderMode(0);
   Double_t xAxis432[2] = {200, 4025}; 
   
   TH1D *data_obs_fail_postfit_projy2_pull__288 = new TH1D("data_obs_fail_postfit_projy2_pull__288","",1, xAxis432);
   data_obs_fail_postfit_projy2_pull__288->SetMinimum(-2.9);
   data_obs_fail_postfit_projy2_pull__288->SetMaximum(2.9);
   data_obs_fail_postfit_projy2_pull__288->SetEntries(2);
   data_obs_fail_postfit_projy2_pull__288->SetStats(0);

   ci = TColor::GetColor("#0000ff");
   data_obs_fail_postfit_projy2_pull__288->SetFillColor(ci);

   ci = TColor::GetColor("#000000");
   data_obs_fail_postfit_projy2_pull__288->SetLineColor(ci);
   data_obs_fail_postfit_projy2_pull__288->SetLineStyle(0);

   ci = TColor::GetColor("#000000");
   data_obs_fail_postfit_projy2_pull__288->SetMarkerColor(ci);
   data_obs_fail_postfit_projy2_pull__288->SetMarkerStyle(8);
   data_obs_fail_postfit_projy2_pull__288->GetXaxis()->SetTitle("p_{T}");
   data_obs_fail_postfit_projy2_pull__288->GetXaxis()->SetLabelFont(42);
   data_obs_fail_postfit_projy2_pull__288->GetXaxis()->SetLabelOffset(0.05);
   data_obs_fail_postfit_projy2_pull__288->GetXaxis()->SetLabelSize(0.13);
   data_obs_fail_postfit_projy2_pull__288->GetXaxis()->SetTitleSize(0.15);
   data_obs_fail_postfit_projy2_pull__288->GetXaxis()->SetTitleOffset(1.15);
   data_obs_fail_postfit_projy2_pull__288->GetXaxis()->SetTitleFont(42);
   data_obs_fail_postfit_projy2_pull__288->GetYaxis()->SetTitle("(Data-Bkg)/#sigma");
   data_obs_fail_postfit_projy2_pull__288->GetYaxis()->SetNdivisions(306);
   data_obs_fail_postfit_projy2_pull__288->GetYaxis()->SetLabelFont(42);
   data_obs_fail_postfit_projy2_pull__288->GetYaxis()->SetLabelOffset(0.007);
   data_obs_fail_postfit_projy2_pull__288->GetYaxis()->SetLabelSize(0.13);
   data_obs_fail_postfit_projy2_pull__288->GetYaxis()->SetTitleSize(0.12);
   data_obs_fail_postfit_projy2_pull__288->GetYaxis()->SetTitleOffset(0.4);
   data_obs_fail_postfit_projy2_pull__288->GetYaxis()->SetTitleFont(42);
   data_obs_fail_postfit_projy2_pull__288->GetZaxis()->SetLabelFont(42);
   data_obs_fail_postfit_projy2_pull__288->GetZaxis()->SetLabelOffset(0.007);
   data_obs_fail_postfit_projy2_pull__288->GetZaxis()->SetLabelSize(0.05);
   data_obs_fail_postfit_projy2_pull__288->GetZaxis()->SetTitleSize(0.08);
   data_obs_fail_postfit_projy2_pull__288->GetZaxis()->SetTitleFont(42);
   data_obs_fail_postfit_projy2_pull__288->Draw("hist");
   data_obs_fail_postfit_projy2_sub->Modified();
   plots_fit_s/base_figs/postfit_projy2_fail_logy->cd();
   plots_fit_s/base_figs/postfit_projy2_fail_logy->Modified();
   plots_fit_s/base_figs/postfit_projy2_fail_logy->cd();
   plots_fit_s/base_figs/postfit_projy2_fail_logy->SetSelected(plots_fit_s/base_figs/postfit_projy2_fail_logy);
}
