void postfit_projx1_fail()
{
//=========Macro generated from canvas: plots_fit_s/base_figs/postfit_projx1_fail/plots_fit_s/base_figs/postfit_projx1_fail
//=========  (Fri Jan 12 20:33:22 2024) by ROOT version 6.14/09
   TCanvas *plots_fit_s/base_figs/postfit_projx1_fail = new TCanvas("plots_fit_s/base_figs/postfit_projx1_fail", "plots_fit_s/base_figs/postfit_projx1_fail",0,0,800,700);
   gStyle->SetOptFit(1);
   gStyle->SetOptStat(0);
   plots_fit_s/base_figs/postfit_projx1_fail->SetHighLightColor(2);
   plots_fit_s/base_figs/postfit_projx1_fail->Range(0,0,1,1);
   plots_fit_s/base_figs/postfit_projx1_fail->SetFillColor(0);
   plots_fit_s/base_figs/postfit_projx1_fail->SetBorderMode(0);
   plots_fit_s/base_figs/postfit_projx1_fail->SetBorderSize(2);
   plots_fit_s/base_figs/postfit_projx1_fail->SetTickx(1);
   plots_fit_s/base_figs/postfit_projx1_fail->SetTicky(1);
   plots_fit_s/base_figs/postfit_projx1_fail->SetLeftMargin(0.16);
   plots_fit_s/base_figs/postfit_projx1_fail->SetRightMargin(0);
   plots_fit_s/base_figs/postfit_projx1_fail->SetTopMargin(0);
   plots_fit_s/base_figs/postfit_projx1_fail->SetBottomMargin(0);
   plots_fit_s/base_figs/postfit_projx1_fail->SetFrameFillStyle(0);
   plots_fit_s/base_figs/postfit_projx1_fail->SetFrameBorderMode(0);
  
// ------------>Primitives in pad: data_obs_fail_postfit_projx1_main
   TPad *data_obs_fail_postfit_projx1_main = new TPad("data_obs_fail_postfit_projx1_main", "data_obs_fail_postfit_projx1_main",0,0.35,1,1);
   data_obs_fail_postfit_projx1_main->Draw();
   data_obs_fail_postfit_projx1_main->cd();
   data_obs_fail_postfit_projx1_main->Range(-0.2179487,-0.04651163,1.064103,1.116279);
   data_obs_fail_postfit_projx1_main->SetFillColor(0);
   data_obs_fail_postfit_projx1_main->SetBorderMode(0);
   data_obs_fail_postfit_projx1_main->SetBorderSize(2);
   data_obs_fail_postfit_projx1_main->SetTickx(1);
   data_obs_fail_postfit_projx1_main->SetTicky(1);
   data_obs_fail_postfit_projx1_main->SetLeftMargin(0.17);
   data_obs_fail_postfit_projx1_main->SetRightMargin(0.05);
   data_obs_fail_postfit_projx1_main->SetBottomMargin(0.04);
   data_obs_fail_postfit_projx1_main->SetFrameFillStyle(0);
   data_obs_fail_postfit_projx1_main->SetFrameBorderMode(0);
   data_obs_fail_postfit_projx1_main->SetFrameFillStyle(0);
   data_obs_fail_postfit_projx1_main->SetFrameBorderMode(0);
   Double_t xAxis301[10] = {0, 0.05, 0.1, 0.15, 0.2, 0.25, 0.3, 0.35, 0.4, 1}; 
   
   TH1D *data_obs_fail_postfit_projx1__201 = new TH1D("data_obs_fail_postfit_projx1__201","",9, xAxis301);
   data_obs_fail_postfit_projx1__201->SetMinimum(0);
   data_obs_fail_postfit_projx1__201->SetMaximum(0);

   Int_t ci;      // for color index setting
   TColor *color; // for color definition with alpha
   ci = TColor::GetColor("#000000");
   data_obs_fail_postfit_projx1__201->SetLineColor(ci);
   data_obs_fail_postfit_projx1__201->SetLineStyle(0);

   ci = TColor::GetColor("#000000");
   data_obs_fail_postfit_projx1__201->SetMarkerColor(ci);
   data_obs_fail_postfit_projx1__201->SetMarkerStyle(8);
   data_obs_fail_postfit_projx1__201->GetXaxis()->SetTitle("G_{i}^{Strips}");
   data_obs_fail_postfit_projx1__201->GetXaxis()->SetLabelFont(42);
   data_obs_fail_postfit_projx1__201->GetXaxis()->SetLabelOffset(0.05);
   data_obs_fail_postfit_projx1__201->GetXaxis()->SetLabelSize(0.07);
   data_obs_fail_postfit_projx1__201->GetXaxis()->SetTitleSize(0.09);
   data_obs_fail_postfit_projx1__201->GetXaxis()->SetTitleOffset(1.15);
   data_obs_fail_postfit_projx1__201->GetXaxis()->SetTitleFont(42);
   data_obs_fail_postfit_projx1__201->GetYaxis()->SetTitle("Events / bin");
   data_obs_fail_postfit_projx1__201->GetYaxis()->SetNdivisions(508);
   data_obs_fail_postfit_projx1__201->GetYaxis()->SetLabelFont(42);
   data_obs_fail_postfit_projx1__201->GetYaxis()->SetLabelOffset(0.007);
   data_obs_fail_postfit_projx1__201->GetYaxis()->SetLabelSize(0.07);
   data_obs_fail_postfit_projx1__201->GetYaxis()->SetTitleSize(0.09);
   data_obs_fail_postfit_projx1__201->GetYaxis()->SetTitleOffset(0.8);
   data_obs_fail_postfit_projx1__201->GetYaxis()->SetTitleFont(42);
   data_obs_fail_postfit_projx1__201->GetZaxis()->SetLabelFont(42);
   data_obs_fail_postfit_projx1__201->GetZaxis()->SetLabelOffset(0.007);
   data_obs_fail_postfit_projx1__201->GetZaxis()->SetLabelSize(0.05);
   data_obs_fail_postfit_projx1__201->GetZaxis()->SetTitleSize(0.08);
   data_obs_fail_postfit_projx1__201->GetZaxis()->SetTitleFont(42);
   data_obs_fail_postfit_projx1__201->Draw("pe X0");
   
   THStack *postfit_projx1_fail_stack = new THStack();
   postfit_projx1_fail_stack->SetName("postfit_projx1_fail_stack");
   postfit_projx1_fail_stack->SetTitle("postfit_projx1_fail_stack");
   Double_t xAxis302[10] = {0, 0.05, 0.1, 0.15, 0.2, 0.25, 0.3, 0.35, 0.4, 1}; 
   
   TH1F *postfit_projx1_fail_stack_stack_51 = new TH1F("postfit_projx1_fail_stack_stack_51","postfit_projx1_fail_stack",9, xAxis302);
   postfit_projx1_fail_stack_stack_51->SetMinimum(0);
   postfit_projx1_fail_stack_stack_51->SetMaximum(0);
   postfit_projx1_fail_stack_stack_51->SetDirectory(0);
   postfit_projx1_fail_stack_stack_51->SetStats(0);
   postfit_projx1_fail_stack_stack_51->SetLineStyle(0);
   postfit_projx1_fail_stack_stack_51->GetXaxis()->SetLabelFont(42);
   postfit_projx1_fail_stack_stack_51->GetXaxis()->SetLabelOffset(0.007);
   postfit_projx1_fail_stack_stack_51->GetXaxis()->SetLabelSize(0.05);
   postfit_projx1_fail_stack_stack_51->GetXaxis()->SetTitleSize(0.08);
   postfit_projx1_fail_stack_stack_51->GetXaxis()->SetTitleOffset(0.9);
   postfit_projx1_fail_stack_stack_51->GetXaxis()->SetTitleFont(42);
   postfit_projx1_fail_stack_stack_51->GetYaxis()->SetNdivisions(508);
   postfit_projx1_fail_stack_stack_51->GetYaxis()->SetLabelFont(42);
   postfit_projx1_fail_stack_stack_51->GetYaxis()->SetLabelOffset(0.007);
   postfit_projx1_fail_stack_stack_51->GetYaxis()->SetLabelSize(0.05);
   postfit_projx1_fail_stack_stack_51->GetYaxis()->SetTitleSize(0.08);
   postfit_projx1_fail_stack_stack_51->GetYaxis()->SetTitleOffset(1.25);
   postfit_projx1_fail_stack_stack_51->GetYaxis()->SetTitleFont(42);
   postfit_projx1_fail_stack_stack_51->GetZaxis()->SetLabelFont(42);
   postfit_projx1_fail_stack_stack_51->GetZaxis()->SetLabelOffset(0.007);
   postfit_projx1_fail_stack_stack_51->GetZaxis()->SetLabelSize(0.05);
   postfit_projx1_fail_stack_stack_51->GetZaxis()->SetTitleSize(0.08);
   postfit_projx1_fail_stack_stack_51->GetZaxis()->SetTitleFont(42);
   postfit_projx1_fail_stack->SetHistogram(postfit_projx1_fail_stack_stack_51);
   
   Double_t xAxis303[10] = {0, 0.05, 0.1, 0.15, 0.2, 0.25, 0.3, 0.35, 0.4, 1}; 
   
   TH1D *Background_fail_postfit_projx1_stack_1 = new TH1D("Background_fail_postfit_projx1_stack_1","Background, fail, postfit, 200-200",9, xAxis303);
   Background_fail_postfit_projx1_stack_1->SetMinimum(0);

   ci = TColor::GetColor("#ffff00");
   Background_fail_postfit_projx1_stack_1->SetFillColor(ci);

   ci = 1330;
   color = new TColor(ci, 1, 1, 1, " ", 0);
   Background_fail_postfit_projx1_stack_1->SetLineColor(ci);
   Background_fail_postfit_projx1_stack_1->SetLineStyle(0);
   Background_fail_postfit_projx1_stack_1->GetXaxis()->SetTitle("G_{i}^{Strips}");
   Background_fail_postfit_projx1_stack_1->GetXaxis()->SetLabelFont(42);
   Background_fail_postfit_projx1_stack_1->GetXaxis()->SetLabelOffset(0.007);
   Background_fail_postfit_projx1_stack_1->GetXaxis()->SetLabelSize(0.05);
   Background_fail_postfit_projx1_stack_1->GetXaxis()->SetTitleSize(0.08);
   Background_fail_postfit_projx1_stack_1->GetXaxis()->SetTitleOffset(0.9);
   Background_fail_postfit_projx1_stack_1->GetXaxis()->SetTitleFont(42);
   Background_fail_postfit_projx1_stack_1->GetYaxis()->SetTitle("Events / bin");
   Background_fail_postfit_projx1_stack_1->GetYaxis()->SetLabelFont(42);
   Background_fail_postfit_projx1_stack_1->GetYaxis()->SetLabelOffset(0.007);
   Background_fail_postfit_projx1_stack_1->GetYaxis()->SetLabelSize(0.05);
   Background_fail_postfit_projx1_stack_1->GetYaxis()->SetTitleSize(0.08);
   Background_fail_postfit_projx1_stack_1->GetYaxis()->SetTitleOffset(1.25);
   Background_fail_postfit_projx1_stack_1->GetYaxis()->SetTitleFont(42);
   Background_fail_postfit_projx1_stack_1->GetZaxis()->SetLabelFont(42);
   Background_fail_postfit_projx1_stack_1->GetZaxis()->SetLabelOffset(0.007);
   Background_fail_postfit_projx1_stack_1->GetZaxis()->SetLabelSize(0.05);
   Background_fail_postfit_projx1_stack_1->GetZaxis()->SetTitleSize(0.08);
   Background_fail_postfit_projx1_stack_1->GetZaxis()->SetTitleFont(42);
   postfit_projx1_fail_stack->Add(Background_fail_postfit_projx1_stack_1,"");
   postfit_projx1_fail_stack->Draw("hist same");
   
   postfit_projx1_fail_stack = new THStack();
   postfit_projx1_fail_stack->SetName("postfit_projx1_fail_stack");
   postfit_projx1_fail_stack->SetTitle("postfit_projx1_fail_stack");
   Double_t xAxis304[10] = {0, 0.05, 0.1, 0.15, 0.2, 0.25, 0.3, 0.35, 0.4, 1}; 
   
   TH1F *postfit_projx1_fail_stack_stack_51_stack_52 = new TH1F("postfit_projx1_fail_stack_stack_51_stack_52","postfit_projx1_fail_stack",9, xAxis304);
   postfit_projx1_fail_stack_stack_51_stack_52->SetMinimum(0);
   postfit_projx1_fail_stack_stack_51_stack_52->SetMaximum(0);
   postfit_projx1_fail_stack_stack_51_stack_52->SetDirectory(0);
   postfit_projx1_fail_stack_stack_51_stack_52->SetStats(0);
   postfit_projx1_fail_stack_stack_51_stack_52->SetLineStyle(0);
   postfit_projx1_fail_stack_stack_51_stack_52->GetXaxis()->SetLabelFont(42);
   postfit_projx1_fail_stack_stack_51_stack_52->GetXaxis()->SetLabelOffset(0.007);
   postfit_projx1_fail_stack_stack_51_stack_52->GetXaxis()->SetLabelSize(0.05);
   postfit_projx1_fail_stack_stack_51_stack_52->GetXaxis()->SetTitleSize(0.08);
   postfit_projx1_fail_stack_stack_51_stack_52->GetXaxis()->SetTitleOffset(0.9);
   postfit_projx1_fail_stack_stack_51_stack_52->GetXaxis()->SetTitleFont(42);
   postfit_projx1_fail_stack_stack_51_stack_52->GetYaxis()->SetNdivisions(508);
   postfit_projx1_fail_stack_stack_51_stack_52->GetYaxis()->SetLabelFont(42);
   postfit_projx1_fail_stack_stack_51_stack_52->GetYaxis()->SetLabelOffset(0.007);
   postfit_projx1_fail_stack_stack_51_stack_52->GetYaxis()->SetLabelSize(0.05);
   postfit_projx1_fail_stack_stack_51_stack_52->GetYaxis()->SetTitleSize(0.08);
   postfit_projx1_fail_stack_stack_51_stack_52->GetYaxis()->SetTitleOffset(1.25);
   postfit_projx1_fail_stack_stack_51_stack_52->GetYaxis()->SetTitleFont(42);
   postfit_projx1_fail_stack_stack_51_stack_52->GetZaxis()->SetLabelFont(42);
   postfit_projx1_fail_stack_stack_51_stack_52->GetZaxis()->SetLabelOffset(0.007);
   postfit_projx1_fail_stack_stack_51_stack_52->GetZaxis()->SetLabelSize(0.05);
   postfit_projx1_fail_stack_stack_51_stack_52->GetZaxis()->SetTitleSize(0.08);
   postfit_projx1_fail_stack_stack_51_stack_52->GetZaxis()->SetTitleFont(42);
   postfit_projx1_fail_stack->SetHistogram(postfit_projx1_fail_stack_stack_51_stack_52);
   
   Double_t xAxis305[10] = {0, 0.05, 0.1, 0.15, 0.2, 0.25, 0.3, 0.35, 0.4, 1}; 
   
   TH1D *Background_fail_postfit_projx1_stack_1_stack_1 = new TH1D("Background_fail_postfit_projx1_stack_1_stack_1","Background, fail, postfit, 200-200",9, xAxis305);
   Background_fail_postfit_projx1_stack_1_stack_1->SetMinimum(0);

   ci = TColor::GetColor("#ffff00");
   Background_fail_postfit_projx1_stack_1_stack_1->SetFillColor(ci);

   ci = 1330;
   color = new TColor(ci, 1, 1, 1, " ", 0);
   Background_fail_postfit_projx1_stack_1_stack_1->SetLineColor(ci);
   Background_fail_postfit_projx1_stack_1_stack_1->SetLineStyle(0);
   Background_fail_postfit_projx1_stack_1_stack_1->GetXaxis()->SetTitle("G_{i}^{Strips}");
   Background_fail_postfit_projx1_stack_1_stack_1->GetXaxis()->SetLabelFont(42);
   Background_fail_postfit_projx1_stack_1_stack_1->GetXaxis()->SetLabelOffset(0.007);
   Background_fail_postfit_projx1_stack_1_stack_1->GetXaxis()->SetLabelSize(0.05);
   Background_fail_postfit_projx1_stack_1_stack_1->GetXaxis()->SetTitleSize(0.08);
   Background_fail_postfit_projx1_stack_1_stack_1->GetXaxis()->SetTitleOffset(0.9);
   Background_fail_postfit_projx1_stack_1_stack_1->GetXaxis()->SetTitleFont(42);
   Background_fail_postfit_projx1_stack_1_stack_1->GetYaxis()->SetTitle("Events / bin");
   Background_fail_postfit_projx1_stack_1_stack_1->GetYaxis()->SetLabelFont(42);
   Background_fail_postfit_projx1_stack_1_stack_1->GetYaxis()->SetLabelOffset(0.007);
   Background_fail_postfit_projx1_stack_1_stack_1->GetYaxis()->SetLabelSize(0.05);
   Background_fail_postfit_projx1_stack_1_stack_1->GetYaxis()->SetTitleSize(0.08);
   Background_fail_postfit_projx1_stack_1_stack_1->GetYaxis()->SetTitleOffset(1.25);
   Background_fail_postfit_projx1_stack_1_stack_1->GetYaxis()->SetTitleFont(42);
   Background_fail_postfit_projx1_stack_1_stack_1->GetZaxis()->SetLabelFont(42);
   Background_fail_postfit_projx1_stack_1_stack_1->GetZaxis()->SetLabelOffset(0.007);
   Background_fail_postfit_projx1_stack_1_stack_1->GetZaxis()->SetLabelSize(0.05);
   Background_fail_postfit_projx1_stack_1_stack_1->GetZaxis()->SetTitleSize(0.08);
   Background_fail_postfit_projx1_stack_1_stack_1->GetZaxis()->SetTitleFont(42);
   postfit_projx1_fail_stack->Add(Background_fail_postfit_projx1_stack_1_stack_1,"");
   postfit_projx1_fail_stack->Draw("hist same");
   Double_t xAxis306[10] = {0, 0.05, 0.1, 0.15, 0.2, 0.25, 0.3, 0.35, 0.4, 1}; 
   
   TH1D *Signal_gluinomI1800_fail_postfit_projx1__202 = new TH1D("Signal_gluinomI1800_fail_postfit_projx1__202","HSCP gluino 1800 GeV, fail, postfit, 200-200",9, xAxis306);
   Signal_gluinomI1800_fail_postfit_projx1__202->SetMinimum(0);
   Signal_gluinomI1800_fail_postfit_projx1__202->SetLineColor(4);
   Signal_gluinomI1800_fail_postfit_projx1__202->SetLineStyle(0);
   Signal_gluinomI1800_fail_postfit_projx1__202->SetLineWidth(2);
   Signal_gluinomI1800_fail_postfit_projx1__202->GetXaxis()->SetTitle("G_{i}^{Strips}");
   Signal_gluinomI1800_fail_postfit_projx1__202->GetXaxis()->SetLabelFont(42);
   Signal_gluinomI1800_fail_postfit_projx1__202->GetXaxis()->SetLabelOffset(0.007);
   Signal_gluinomI1800_fail_postfit_projx1__202->GetXaxis()->SetLabelSize(0.05);
   Signal_gluinomI1800_fail_postfit_projx1__202->GetXaxis()->SetTitleSize(0.08);
   Signal_gluinomI1800_fail_postfit_projx1__202->GetXaxis()->SetTitleOffset(0.9);
   Signal_gluinomI1800_fail_postfit_projx1__202->GetXaxis()->SetTitleFont(42);
   Signal_gluinomI1800_fail_postfit_projx1__202->GetYaxis()->SetTitle("Events / bin");
   Signal_gluinomI1800_fail_postfit_projx1__202->GetYaxis()->SetLabelFont(42);
   Signal_gluinomI1800_fail_postfit_projx1__202->GetYaxis()->SetLabelOffset(0.007);
   Signal_gluinomI1800_fail_postfit_projx1__202->GetYaxis()->SetLabelSize(0.05);
   Signal_gluinomI1800_fail_postfit_projx1__202->GetYaxis()->SetTitleSize(0.08);
   Signal_gluinomI1800_fail_postfit_projx1__202->GetYaxis()->SetTitleOffset(1.25);
   Signal_gluinomI1800_fail_postfit_projx1__202->GetYaxis()->SetTitleFont(42);
   Signal_gluinomI1800_fail_postfit_projx1__202->GetZaxis()->SetLabelFont(42);
   Signal_gluinomI1800_fail_postfit_projx1__202->GetZaxis()->SetLabelOffset(0.007);
   Signal_gluinomI1800_fail_postfit_projx1__202->GetZaxis()->SetLabelSize(0.05);
   Signal_gluinomI1800_fail_postfit_projx1__202->GetZaxis()->SetTitleSize(0.08);
   Signal_gluinomI1800_fail_postfit_projx1__202->GetZaxis()->SetTitleFont(42);
   Signal_gluinomI1800_fail_postfit_projx1__202->Draw("hist same");
   Double_t xAxis307[10] = {0, 0.05, 0.1, 0.15, 0.2, 0.25, 0.3, 0.35, 0.4, 1}; 
   
   TH1D *Signal_ppStaumI557_fail_postfit_projx1__203 = new TH1D("Signal_ppStaumI557_fail_postfit_projx1__203","HSCP stau 557 GeV, fail, postfit, 200-200",9, xAxis307);
   Signal_ppStaumI557_fail_postfit_projx1__203->SetMinimum(0);
   Signal_ppStaumI557_fail_postfit_projx1__203->SetLineColor(2);
   Signal_ppStaumI557_fail_postfit_projx1__203->SetLineStyle(0);
   Signal_ppStaumI557_fail_postfit_projx1__203->SetLineWidth(2);
   Signal_ppStaumI557_fail_postfit_projx1__203->GetXaxis()->SetTitle("G_{i}^{Strips}");
   Signal_ppStaumI557_fail_postfit_projx1__203->GetXaxis()->SetLabelFont(42);
   Signal_ppStaumI557_fail_postfit_projx1__203->GetXaxis()->SetLabelOffset(0.007);
   Signal_ppStaumI557_fail_postfit_projx1__203->GetXaxis()->SetLabelSize(0.05);
   Signal_ppStaumI557_fail_postfit_projx1__203->GetXaxis()->SetTitleSize(0.08);
   Signal_ppStaumI557_fail_postfit_projx1__203->GetXaxis()->SetTitleOffset(0.9);
   Signal_ppStaumI557_fail_postfit_projx1__203->GetXaxis()->SetTitleFont(42);
   Signal_ppStaumI557_fail_postfit_projx1__203->GetYaxis()->SetTitle("Events / bin");
   Signal_ppStaumI557_fail_postfit_projx1__203->GetYaxis()->SetLabelFont(42);
   Signal_ppStaumI557_fail_postfit_projx1__203->GetYaxis()->SetLabelOffset(0.007);
   Signal_ppStaumI557_fail_postfit_projx1__203->GetYaxis()->SetLabelSize(0.05);
   Signal_ppStaumI557_fail_postfit_projx1__203->GetYaxis()->SetTitleSize(0.08);
   Signal_ppStaumI557_fail_postfit_projx1__203->GetYaxis()->SetTitleOffset(1.25);
   Signal_ppStaumI557_fail_postfit_projx1__203->GetYaxis()->SetTitleFont(42);
   Signal_ppStaumI557_fail_postfit_projx1__203->GetZaxis()->SetLabelFont(42);
   Signal_ppStaumI557_fail_postfit_projx1__203->GetZaxis()->SetLabelOffset(0.007);
   Signal_ppStaumI557_fail_postfit_projx1__203->GetZaxis()->SetLabelSize(0.05);
   Signal_ppStaumI557_fail_postfit_projx1__203->GetZaxis()->SetTitleSize(0.08);
   Signal_ppStaumI557_fail_postfit_projx1__203->GetZaxis()->SetTitleFont(42);
   Signal_ppStaumI557_fail_postfit_projx1__203->Draw("hist same");
   Double_t xAxis308[10] = {0, 0.05, 0.1, 0.15, 0.2, 0.25, 0.3, 0.35, 0.4, 1}; 
   
   TH1D *TotalBkg_fail_postfit_projx1__204 = new TH1D("TotalBkg_fail_postfit_projx1__204","TotalBkg, fail, postfit, 200-200",9, xAxis308);
   TotalBkg_fail_postfit_projx1__204->SetMinimum(0);
   TotalBkg_fail_postfit_projx1__204->SetLineStyle(0);
   TotalBkg_fail_postfit_projx1__204->SetMarkerStyle(0);
   TotalBkg_fail_postfit_projx1__204->GetXaxis()->SetTitle("G_{i}^{Strips}");
   TotalBkg_fail_postfit_projx1__204->GetXaxis()->SetLabelFont(42);
   TotalBkg_fail_postfit_projx1__204->GetXaxis()->SetLabelOffset(0.007);
   TotalBkg_fail_postfit_projx1__204->GetXaxis()->SetLabelSize(0.05);
   TotalBkg_fail_postfit_projx1__204->GetXaxis()->SetTitleSize(0.08);
   TotalBkg_fail_postfit_projx1__204->GetXaxis()->SetTitleOffset(0.9);
   TotalBkg_fail_postfit_projx1__204->GetXaxis()->SetTitleFont(42);
   TotalBkg_fail_postfit_projx1__204->GetYaxis()->SetTitle("Events / bin");
   TotalBkg_fail_postfit_projx1__204->GetYaxis()->SetLabelFont(42);
   TotalBkg_fail_postfit_projx1__204->GetYaxis()->SetLabelOffset(0.007);
   TotalBkg_fail_postfit_projx1__204->GetYaxis()->SetLabelSize(0.05);
   TotalBkg_fail_postfit_projx1__204->GetYaxis()->SetTitleSize(0.08);
   TotalBkg_fail_postfit_projx1__204->GetYaxis()->SetTitleOffset(1.25);
   TotalBkg_fail_postfit_projx1__204->GetYaxis()->SetTitleFont(42);
   TotalBkg_fail_postfit_projx1__204->GetZaxis()->SetLabelFont(42);
   TotalBkg_fail_postfit_projx1__204->GetZaxis()->SetLabelOffset(0.007);
   TotalBkg_fail_postfit_projx1__204->GetZaxis()->SetLabelSize(0.05);
   TotalBkg_fail_postfit_projx1__204->GetZaxis()->SetTitleSize(0.08);
   TotalBkg_fail_postfit_projx1__204->GetZaxis()->SetTitleFont(42);
   TotalBkg_fail_postfit_projx1__204->Draw("hist same");
   Double_t xAxis309[10] = {0, 0.05, 0.1, 0.15, 0.2, 0.25, 0.3, 0.35, 0.4, 1}; 
   
   TH1D *TotalBkg_fail_postfit_projx1__205 = new TH1D("TotalBkg_fail_postfit_projx1__205","TotalBkg, fail, postfit, 200-200",9, xAxis309);
   TotalBkg_fail_postfit_projx1__205->SetMinimum(0);
   TotalBkg_fail_postfit_projx1__205->SetFillColor(1);
   TotalBkg_fail_postfit_projx1__205->SetFillStyle(3354);
   TotalBkg_fail_postfit_projx1__205->SetLineStyle(0);
   TotalBkg_fail_postfit_projx1__205->SetLineWidth(0);
   TotalBkg_fail_postfit_projx1__205->SetMarkerStyle(0);
   TotalBkg_fail_postfit_projx1__205->GetXaxis()->SetTitle("G_{i}^{Strips}");
   TotalBkg_fail_postfit_projx1__205->GetXaxis()->SetLabelFont(42);
   TotalBkg_fail_postfit_projx1__205->GetXaxis()->SetLabelOffset(0.007);
   TotalBkg_fail_postfit_projx1__205->GetXaxis()->SetLabelSize(0.05);
   TotalBkg_fail_postfit_projx1__205->GetXaxis()->SetTitleSize(0.08);
   TotalBkg_fail_postfit_projx1__205->GetXaxis()->SetTitleOffset(0.9);
   TotalBkg_fail_postfit_projx1__205->GetXaxis()->SetTitleFont(42);
   TotalBkg_fail_postfit_projx1__205->GetYaxis()->SetTitle("Events / bin");
   TotalBkg_fail_postfit_projx1__205->GetYaxis()->SetLabelFont(42);
   TotalBkg_fail_postfit_projx1__205->GetYaxis()->SetLabelOffset(0.007);
   TotalBkg_fail_postfit_projx1__205->GetYaxis()->SetLabelSize(0.05);
   TotalBkg_fail_postfit_projx1__205->GetYaxis()->SetTitleSize(0.08);
   TotalBkg_fail_postfit_projx1__205->GetYaxis()->SetTitleOffset(1.25);
   TotalBkg_fail_postfit_projx1__205->GetYaxis()->SetTitleFont(42);
   TotalBkg_fail_postfit_projx1__205->GetZaxis()->SetLabelFont(42);
   TotalBkg_fail_postfit_projx1__205->GetZaxis()->SetLabelOffset(0.007);
   TotalBkg_fail_postfit_projx1__205->GetZaxis()->SetLabelSize(0.05);
   TotalBkg_fail_postfit_projx1__205->GetZaxis()->SetTitleSize(0.08);
   TotalBkg_fail_postfit_projx1__205->GetZaxis()->SetTitleFont(42);
   TotalBkg_fail_postfit_projx1__205->Draw("e2 same");
   Double_t xAxis310[10] = {0, 0.05, 0.1, 0.15, 0.2, 0.25, 0.3, 0.35, 0.4, 1}; 
   
   TH1D *data_obs_fail_postfit_projx1__206 = new TH1D("data_obs_fail_postfit_projx1__206","",9, xAxis310);
   data_obs_fail_postfit_projx1__206->SetMinimum(0);
   data_obs_fail_postfit_projx1__206->SetMaximum(0);

   ci = TColor::GetColor("#000000");
   data_obs_fail_postfit_projx1__206->SetLineColor(ci);
   data_obs_fail_postfit_projx1__206->SetLineStyle(0);

   ci = TColor::GetColor("#000000");
   data_obs_fail_postfit_projx1__206->SetMarkerColor(ci);
   data_obs_fail_postfit_projx1__206->SetMarkerStyle(8);
   data_obs_fail_postfit_projx1__206->GetXaxis()->SetTitle("G_{i}^{Strips}");
   data_obs_fail_postfit_projx1__206->GetXaxis()->SetLabelFont(42);
   data_obs_fail_postfit_projx1__206->GetXaxis()->SetLabelOffset(0.05);
   data_obs_fail_postfit_projx1__206->GetXaxis()->SetLabelSize(0.07);
   data_obs_fail_postfit_projx1__206->GetXaxis()->SetTitleSize(0.09);
   data_obs_fail_postfit_projx1__206->GetXaxis()->SetTitleOffset(1.15);
   data_obs_fail_postfit_projx1__206->GetXaxis()->SetTitleFont(42);
   data_obs_fail_postfit_projx1__206->GetYaxis()->SetTitle("Events / bin");
   data_obs_fail_postfit_projx1__206->GetYaxis()->SetNdivisions(508);
   data_obs_fail_postfit_projx1__206->GetYaxis()->SetLabelFont(42);
   data_obs_fail_postfit_projx1__206->GetYaxis()->SetLabelOffset(0.007);
   data_obs_fail_postfit_projx1__206->GetYaxis()->SetLabelSize(0.07);
   data_obs_fail_postfit_projx1__206->GetYaxis()->SetTitleSize(0.09);
   data_obs_fail_postfit_projx1__206->GetYaxis()->SetTitleOffset(0.8);
   data_obs_fail_postfit_projx1__206->GetYaxis()->SetTitleFont(42);
   data_obs_fail_postfit_projx1__206->GetZaxis()->SetLabelFont(42);
   data_obs_fail_postfit_projx1__206->GetZaxis()->SetLabelOffset(0.007);
   data_obs_fail_postfit_projx1__206->GetZaxis()->SetLabelSize(0.05);
   data_obs_fail_postfit_projx1__206->GetZaxis()->SetTitleSize(0.08);
   data_obs_fail_postfit_projx1__206->GetZaxis()->SetTitleFont(42);
   data_obs_fail_postfit_projx1__206->Draw("pe X0 same");
   
   TLegend *leg = new TLegend(0.65,0.61,0.9,0.88,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(1001);
   TLegendEntry *entry=leg->AddEntry("data_obs_fail_postfit_projx1","Data","pe X0");

   ci = TColor::GetColor("#000000");
   entry->SetLineColor(ci);
   entry->SetLineWidth(1);

   ci = TColor::GetColor("#000000");
   entry->SetMarkerColor(ci);
   entry->SetMarkerStyle(8);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("TotalBkg_fail_postfit_projx1","Total bkg unc.","F");
   entry->SetFillColor(1);
   entry->SetFillStyle(3354);
   entry->SetLineColor(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("Signal_gluino-1800_fail_postfit_projx1","HSCP gluino 1800 GeV","L");
   entry->SetLineColor(4);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("Signal_ppStau-557_fail_postfit_projx1","HSCP stau 557 GeV","L");
   entry->SetLineColor(2);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("Background_fail_postfit_projx1_stack_1_stack_1","Background","f");

   ci = TColor::GetColor("#ffff00");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = 1330;
   color = new TColor(ci, 1, 1, 1, " ", 0);
   entry->SetLineColor(ci);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   leg->Draw();
   Double_t xAxis311[10] = {0, 0.05, 0.1, 0.15, 0.2, 0.25, 0.3, 0.35, 0.4, 1}; 
   
   TH1D *data_obs_fail_postfit_projx1_copy__207 = new TH1D("data_obs_fail_postfit_projx1_copy__207","",9, xAxis311);
   data_obs_fail_postfit_projx1_copy__207->SetMinimum(0);
   data_obs_fail_postfit_projx1_copy__207->SetMaximum(0);
   data_obs_fail_postfit_projx1_copy__207->SetDirectory(0);

   ci = TColor::GetColor("#000000");
   data_obs_fail_postfit_projx1_copy__207->SetLineColor(ci);
   data_obs_fail_postfit_projx1_copy__207->SetLineStyle(0);

   ci = TColor::GetColor("#000000");
   data_obs_fail_postfit_projx1_copy__207->SetMarkerColor(ci);
   data_obs_fail_postfit_projx1_copy__207->SetMarkerStyle(8);
   data_obs_fail_postfit_projx1_copy__207->GetXaxis()->SetTitle("G_{i}^{Strips}");
   data_obs_fail_postfit_projx1_copy__207->GetXaxis()->SetLabelFont(42);
   data_obs_fail_postfit_projx1_copy__207->GetXaxis()->SetLabelOffset(0.05);
   data_obs_fail_postfit_projx1_copy__207->GetXaxis()->SetLabelSize(0.07);
   data_obs_fail_postfit_projx1_copy__207->GetXaxis()->SetTitleSize(0.09);
   data_obs_fail_postfit_projx1_copy__207->GetXaxis()->SetTitleOffset(1.15);
   data_obs_fail_postfit_projx1_copy__207->GetXaxis()->SetTitleFont(42);
   data_obs_fail_postfit_projx1_copy__207->GetYaxis()->SetTitle("Events / bin");
   data_obs_fail_postfit_projx1_copy__207->GetYaxis()->SetNdivisions(508);
   data_obs_fail_postfit_projx1_copy__207->GetYaxis()->SetLabelFont(42);
   data_obs_fail_postfit_projx1_copy__207->GetYaxis()->SetLabelOffset(0.007);
   data_obs_fail_postfit_projx1_copy__207->GetYaxis()->SetLabelSize(0.07);
   data_obs_fail_postfit_projx1_copy__207->GetYaxis()->SetTitleSize(0.09);
   data_obs_fail_postfit_projx1_copy__207->GetYaxis()->SetTitleOffset(0.8);
   data_obs_fail_postfit_projx1_copy__207->GetYaxis()->SetTitleFont(42);
   data_obs_fail_postfit_projx1_copy__207->GetZaxis()->SetLabelFont(42);
   data_obs_fail_postfit_projx1_copy__207->GetZaxis()->SetLabelOffset(0.007);
   data_obs_fail_postfit_projx1_copy__207->GetZaxis()->SetLabelSize(0.05);
   data_obs_fail_postfit_projx1_copy__207->GetZaxis()->SetTitleSize(0.08);
   data_obs_fail_postfit_projx1_copy__207->GetZaxis()->SetTitleFont(42);
   data_obs_fail_postfit_projx1_copy__207->Draw("sameaxis");
   TLatex *   tex = new TLatex(0.21,0.83,"200 < p_{T} < 200 , F^{Pixels}_{i} < 0.9");
tex->SetNDC();
   tex->SetTextAlign(12);
   tex->SetTextFont(42);
   tex->SetTextSize(0.06);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.17,0.92,"CMS");
tex->SetNDC();
   tex->SetTextFont(61);
   tex->SetTextSize(0.0675);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.25,0.92,"Preliminary");
tex->SetNDC();
   tex->SetTextFont(52);
   tex->SetTextSize(0.0485);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.95,0.92,"101 fb^{-1} (13 TeV)");
tex->SetNDC();
   tex->SetTextAlign(31);
   tex->SetTextFont(42);
   tex->SetTextSize(0.07);
   tex->SetLineWidth(2);
   tex->Draw();
   data_obs_fail_postfit_projx1_main->Modified();
   plots_fit_s/base_figs/postfit_projx1_fail->cd();
  
// ------------>Primitives in pad: data_obs_fail_postfit_projx1_sub
   TPad *data_obs_fail_postfit_projx1_sub = new TPad("data_obs_fail_postfit_projx1_sub", "data_obs_fail_postfit_projx1_sub",0,0,1,0.35);
   data_obs_fail_postfit_projx1_sub->Draw();
   data_obs_fail_postfit_projx1_sub->cd();
   data_obs_fail_postfit_projx1_sub->Range(-0.2179487,-6.023077,1.064103,2.9);
   data_obs_fail_postfit_projx1_sub->SetFillColor(0);
   data_obs_fail_postfit_projx1_sub->SetBorderMode(0);
   data_obs_fail_postfit_projx1_sub->SetBorderSize(2);
   data_obs_fail_postfit_projx1_sub->SetTickx(1);
   data_obs_fail_postfit_projx1_sub->SetTicky(1);
   data_obs_fail_postfit_projx1_sub->SetLeftMargin(0.17);
   data_obs_fail_postfit_projx1_sub->SetRightMargin(0.05);
   data_obs_fail_postfit_projx1_sub->SetTopMargin(0);
   data_obs_fail_postfit_projx1_sub->SetBottomMargin(0.35);
   data_obs_fail_postfit_projx1_sub->SetFrameFillStyle(0);
   data_obs_fail_postfit_projx1_sub->SetFrameBorderMode(0);
   data_obs_fail_postfit_projx1_sub->SetFrameFillStyle(0);
   data_obs_fail_postfit_projx1_sub->SetFrameBorderMode(0);
   Double_t xAxis312[10] = {0, 0.05, 0.1, 0.15, 0.2, 0.25, 0.3, 0.35, 0.4, 1}; 
   
   TH1D *data_obs_fail_postfit_projx1_pull__208 = new TH1D("data_obs_fail_postfit_projx1_pull__208","",9, xAxis312);
   data_obs_fail_postfit_projx1_pull__208->SetMinimum(-2.9);
   data_obs_fail_postfit_projx1_pull__208->SetMaximum(2.9);
   data_obs_fail_postfit_projx1_pull__208->SetEntries(18);
   data_obs_fail_postfit_projx1_pull__208->SetStats(0);

   ci = TColor::GetColor("#0000ff");
   data_obs_fail_postfit_projx1_pull__208->SetFillColor(ci);

   ci = TColor::GetColor("#000000");
   data_obs_fail_postfit_projx1_pull__208->SetLineColor(ci);
   data_obs_fail_postfit_projx1_pull__208->SetLineStyle(0);

   ci = TColor::GetColor("#000000");
   data_obs_fail_postfit_projx1_pull__208->SetMarkerColor(ci);
   data_obs_fail_postfit_projx1_pull__208->SetMarkerStyle(8);
   data_obs_fail_postfit_projx1_pull__208->GetXaxis()->SetTitle("G_{i}^{Strips}");
   data_obs_fail_postfit_projx1_pull__208->GetXaxis()->SetLabelFont(42);
   data_obs_fail_postfit_projx1_pull__208->GetXaxis()->SetLabelOffset(0.05);
   data_obs_fail_postfit_projx1_pull__208->GetXaxis()->SetLabelSize(0.13);
   data_obs_fail_postfit_projx1_pull__208->GetXaxis()->SetTitleSize(0.15);
   data_obs_fail_postfit_projx1_pull__208->GetXaxis()->SetTitleOffset(1.15);
   data_obs_fail_postfit_projx1_pull__208->GetXaxis()->SetTitleFont(42);
   data_obs_fail_postfit_projx1_pull__208->GetYaxis()->SetTitle("(Data-Bkg)/#sigma");
   data_obs_fail_postfit_projx1_pull__208->GetYaxis()->SetNdivisions(306);
   data_obs_fail_postfit_projx1_pull__208->GetYaxis()->SetLabelFont(42);
   data_obs_fail_postfit_projx1_pull__208->GetYaxis()->SetLabelOffset(0.007);
   data_obs_fail_postfit_projx1_pull__208->GetYaxis()->SetLabelSize(0.13);
   data_obs_fail_postfit_projx1_pull__208->GetYaxis()->SetTitleSize(0.12);
   data_obs_fail_postfit_projx1_pull__208->GetYaxis()->SetTitleOffset(0.4);
   data_obs_fail_postfit_projx1_pull__208->GetYaxis()->SetTitleFont(42);
   data_obs_fail_postfit_projx1_pull__208->GetZaxis()->SetLabelFont(42);
   data_obs_fail_postfit_projx1_pull__208->GetZaxis()->SetLabelOffset(0.007);
   data_obs_fail_postfit_projx1_pull__208->GetZaxis()->SetLabelSize(0.05);
   data_obs_fail_postfit_projx1_pull__208->GetZaxis()->SetTitleSize(0.08);
   data_obs_fail_postfit_projx1_pull__208->GetZaxis()->SetTitleFont(42);
   data_obs_fail_postfit_projx1_pull__208->Draw("hist");
   data_obs_fail_postfit_projx1_sub->Modified();
   plots_fit_s/base_figs/postfit_projx1_fail->cd();
   plots_fit_s/base_figs/postfit_projx1_fail->Modified();
   plots_fit_s/base_figs/postfit_projx1_fail->cd();
   plots_fit_s/base_figs/postfit_projx1_fail->SetSelected(plots_fit_s/base_figs/postfit_projx1_fail);
}
