void postfit_projx0_pass_logy()
{
//=========Macro generated from canvas: plots_fit_s/base_figs/postfit_projx0_pass_logy/plots_fit_s/base_figs/postfit_projx0_pass_logy
//=========  (Fri Jan 12 20:33:24 2024) by ROOT version 6.14/09
   TCanvas *plots_fit_s/base_figs/postfit_projx0_pass_logy = new TCanvas("plots_fit_s/base_figs/postfit_projx0_pass_logy", "plots_fit_s/base_figs/postfit_projx0_pass_logy",0,0,800,700);
   gStyle->SetOptFit(1);
   gStyle->SetOptStat(0);
   plots_fit_s/base_figs/postfit_projx0_pass_logy->SetHighLightColor(2);
   plots_fit_s/base_figs/postfit_projx0_pass_logy->Range(0,0,1,1);
   plots_fit_s/base_figs/postfit_projx0_pass_logy->SetFillColor(0);
   plots_fit_s/base_figs/postfit_projx0_pass_logy->SetBorderMode(0);
   plots_fit_s/base_figs/postfit_projx0_pass_logy->SetBorderSize(2);
   plots_fit_s/base_figs/postfit_projx0_pass_logy->SetTickx(1);
   plots_fit_s/base_figs/postfit_projx0_pass_logy->SetTicky(1);
   plots_fit_s/base_figs/postfit_projx0_pass_logy->SetLeftMargin(0.16);
   plots_fit_s/base_figs/postfit_projx0_pass_logy->SetRightMargin(0);
   plots_fit_s/base_figs/postfit_projx0_pass_logy->SetTopMargin(0);
   plots_fit_s/base_figs/postfit_projx0_pass_logy->SetBottomMargin(0);
   plots_fit_s/base_figs/postfit_projx0_pass_logy->SetFrameFillStyle(0);
   plots_fit_s/base_figs/postfit_projx0_pass_logy->SetFrameBorderMode(0);
  
// ------------>Primitives in pad: data_obs_pass_postfit_projx0_main
   TPad *data_obs_pass_postfit_projx0_main = new TPad("data_obs_pass_postfit_projx0_main", "data_obs_pass_postfit_projx0_main",0,0.35,1,1);
   data_obs_pass_postfit_projx0_main->Draw();
   data_obs_pass_postfit_projx0_main->cd();
   data_obs_pass_postfit_projx0_main->Range(-0.2179487,-2.139535,1.064103,1.348837);
   data_obs_pass_postfit_projx0_main->SetFillColor(0);
   data_obs_pass_postfit_projx0_main->SetBorderMode(0);
   data_obs_pass_postfit_projx0_main->SetBorderSize(2);
   data_obs_pass_postfit_projx0_main->SetLogy();
   data_obs_pass_postfit_projx0_main->SetTickx(1);
   data_obs_pass_postfit_projx0_main->SetTicky(1);
   data_obs_pass_postfit_projx0_main->SetLeftMargin(0.17);
   data_obs_pass_postfit_projx0_main->SetRightMargin(0.05);
   data_obs_pass_postfit_projx0_main->SetBottomMargin(0.04);
   data_obs_pass_postfit_projx0_main->SetFrameFillStyle(0);
   data_obs_pass_postfit_projx0_main->SetFrameBorderMode(0);
   data_obs_pass_postfit_projx0_main->SetFrameFillStyle(0);
   data_obs_pass_postfit_projx0_main->SetFrameBorderMode(0);
   Double_t xAxis505[10] = {0, 0.05, 0.1, 0.15, 0.2, 0.25, 0.3, 0.35, 0.4, 1}; 
   
   TH1D *data_obs_pass_postfit_projx0__337 = new TH1D("data_obs_pass_postfit_projx0__337","",9, xAxis505);
   data_obs_pass_postfit_projx0__337->SetMinimum(0.001);
   data_obs_pass_postfit_projx0__337->SetMaximum(0);

   Int_t ci;      // for color index setting
   TColor *color; // for color definition with alpha
   ci = TColor::GetColor("#000000");
   data_obs_pass_postfit_projx0__337->SetLineColor(ci);
   data_obs_pass_postfit_projx0__337->SetLineStyle(0);

   ci = TColor::GetColor("#000000");
   data_obs_pass_postfit_projx0__337->SetMarkerColor(ci);
   data_obs_pass_postfit_projx0__337->SetMarkerStyle(8);
   data_obs_pass_postfit_projx0__337->GetXaxis()->SetTitle("G_{i}^{Strips}");
   data_obs_pass_postfit_projx0__337->GetXaxis()->SetLabelFont(42);
   data_obs_pass_postfit_projx0__337->GetXaxis()->SetLabelOffset(0.05);
   data_obs_pass_postfit_projx0__337->GetXaxis()->SetLabelSize(0.07);
   data_obs_pass_postfit_projx0__337->GetXaxis()->SetTitleSize(0.09);
   data_obs_pass_postfit_projx0__337->GetXaxis()->SetTitleOffset(1.15);
   data_obs_pass_postfit_projx0__337->GetXaxis()->SetTitleFont(42);
   data_obs_pass_postfit_projx0__337->GetYaxis()->SetTitle("Events / bin");
   data_obs_pass_postfit_projx0__337->GetYaxis()->SetNdivisions(508);
   data_obs_pass_postfit_projx0__337->GetYaxis()->SetLabelFont(42);
   data_obs_pass_postfit_projx0__337->GetYaxis()->SetLabelOffset(0.007);
   data_obs_pass_postfit_projx0__337->GetYaxis()->SetLabelSize(0.07);
   data_obs_pass_postfit_projx0__337->GetYaxis()->SetTitleSize(0.09);
   data_obs_pass_postfit_projx0__337->GetYaxis()->SetTitleOffset(0.8);
   data_obs_pass_postfit_projx0__337->GetYaxis()->SetTitleFont(42);
   data_obs_pass_postfit_projx0__337->GetZaxis()->SetLabelFont(42);
   data_obs_pass_postfit_projx0__337->GetZaxis()->SetLabelOffset(0.007);
   data_obs_pass_postfit_projx0__337->GetZaxis()->SetLabelSize(0.05);
   data_obs_pass_postfit_projx0__337->GetZaxis()->SetTitleSize(0.08);
   data_obs_pass_postfit_projx0__337->GetZaxis()->SetTitleFont(42);
   data_obs_pass_postfit_projx0__337->Draw("pe X0");
   
   THStack *postfit_projx0_pass_logy_stack = new THStack();
   postfit_projx0_pass_logy_stack->SetName("postfit_projx0_pass_logy_stack");
   postfit_projx0_pass_logy_stack->SetTitle("postfit_projx0_pass_logy_stack");
   postfit_projx0_pass_logy_stack->SetMinimum(0.001);
   Double_t xAxis506[10] = {0, 0.05, 0.1, 0.15, 0.2, 0.25, 0.3, 0.35, 0.4, 1}; 
   
   TH1F *postfit_projx0_pass_logy_stack_stack_85 = new TH1F("postfit_projx0_pass_logy_stack_stack_85","postfit_projx0_pass_logy_stack",9, xAxis506);
   postfit_projx0_pass_logy_stack_stack_85->SetMinimum(-0);
   postfit_projx0_pass_logy_stack_stack_85->SetMaximum(-nan);
   postfit_projx0_pass_logy_stack_stack_85->SetDirectory(0);
   postfit_projx0_pass_logy_stack_stack_85->SetStats(0);
   postfit_projx0_pass_logy_stack_stack_85->SetLineStyle(0);
   postfit_projx0_pass_logy_stack_stack_85->GetXaxis()->SetLabelFont(42);
   postfit_projx0_pass_logy_stack_stack_85->GetXaxis()->SetLabelOffset(0.007);
   postfit_projx0_pass_logy_stack_stack_85->GetXaxis()->SetLabelSize(0.05);
   postfit_projx0_pass_logy_stack_stack_85->GetXaxis()->SetTitleSize(0.08);
   postfit_projx0_pass_logy_stack_stack_85->GetXaxis()->SetTitleOffset(0.9);
   postfit_projx0_pass_logy_stack_stack_85->GetXaxis()->SetTitleFont(42);
   postfit_projx0_pass_logy_stack_stack_85->GetYaxis()->SetNdivisions(508);
   postfit_projx0_pass_logy_stack_stack_85->GetYaxis()->SetLabelFont(42);
   postfit_projx0_pass_logy_stack_stack_85->GetYaxis()->SetLabelOffset(0.007);
   postfit_projx0_pass_logy_stack_stack_85->GetYaxis()->SetLabelSize(0.05);
   postfit_projx0_pass_logy_stack_stack_85->GetYaxis()->SetTitleSize(0.08);
   postfit_projx0_pass_logy_stack_stack_85->GetYaxis()->SetTitleOffset(1.25);
   postfit_projx0_pass_logy_stack_stack_85->GetYaxis()->SetTitleFont(42);
   postfit_projx0_pass_logy_stack_stack_85->GetZaxis()->SetLabelFont(42);
   postfit_projx0_pass_logy_stack_stack_85->GetZaxis()->SetLabelOffset(0.007);
   postfit_projx0_pass_logy_stack_stack_85->GetZaxis()->SetLabelSize(0.05);
   postfit_projx0_pass_logy_stack_stack_85->GetZaxis()->SetTitleSize(0.08);
   postfit_projx0_pass_logy_stack_stack_85->GetZaxis()->SetTitleFont(42);
   postfit_projx0_pass_logy_stack->SetHistogram(postfit_projx0_pass_logy_stack_stack_85);
   
   Double_t xAxis507[10] = {0, 0.05, 0.1, 0.15, 0.2, 0.25, 0.3, 0.35, 0.4, 1}; 
   
   TH1D *Background_0x0_pass_postfit_projx0_stack_1 = new TH1D("Background_0x0_pass_postfit_projx0_stack_1","Background, pass, postfit, 200-200",9, xAxis507);
   Background_0x0_pass_postfit_projx0_stack_1->SetMinimum(0.001);

   ci = TColor::GetColor("#ffff00");
   Background_0x0_pass_postfit_projx0_stack_1->SetFillColor(ci);

   ci = 1341;
   color = new TColor(ci, 1, 1, 1, " ", 0);
   Background_0x0_pass_postfit_projx0_stack_1->SetLineColor(ci);
   Background_0x0_pass_postfit_projx0_stack_1->SetLineStyle(0);
   Background_0x0_pass_postfit_projx0_stack_1->GetXaxis()->SetTitle("G_{i}^{Strips}");
   Background_0x0_pass_postfit_projx0_stack_1->GetXaxis()->SetLabelFont(42);
   Background_0x0_pass_postfit_projx0_stack_1->GetXaxis()->SetLabelOffset(0.007);
   Background_0x0_pass_postfit_projx0_stack_1->GetXaxis()->SetLabelSize(0.05);
   Background_0x0_pass_postfit_projx0_stack_1->GetXaxis()->SetTitleSize(0.08);
   Background_0x0_pass_postfit_projx0_stack_1->GetXaxis()->SetTitleOffset(0.9);
   Background_0x0_pass_postfit_projx0_stack_1->GetXaxis()->SetTitleFont(42);
   Background_0x0_pass_postfit_projx0_stack_1->GetYaxis()->SetTitle("Events / bin");
   Background_0x0_pass_postfit_projx0_stack_1->GetYaxis()->SetLabelFont(42);
   Background_0x0_pass_postfit_projx0_stack_1->GetYaxis()->SetLabelOffset(0.007);
   Background_0x0_pass_postfit_projx0_stack_1->GetYaxis()->SetLabelSize(0.05);
   Background_0x0_pass_postfit_projx0_stack_1->GetYaxis()->SetTitleSize(0.08);
   Background_0x0_pass_postfit_projx0_stack_1->GetYaxis()->SetTitleOffset(1.25);
   Background_0x0_pass_postfit_projx0_stack_1->GetYaxis()->SetTitleFont(42);
   Background_0x0_pass_postfit_projx0_stack_1->GetZaxis()->SetLabelFont(42);
   Background_0x0_pass_postfit_projx0_stack_1->GetZaxis()->SetLabelOffset(0.007);
   Background_0x0_pass_postfit_projx0_stack_1->GetZaxis()->SetLabelSize(0.05);
   Background_0x0_pass_postfit_projx0_stack_1->GetZaxis()->SetTitleSize(0.08);
   Background_0x0_pass_postfit_projx0_stack_1->GetZaxis()->SetTitleFont(42);
   postfit_projx0_pass_logy_stack->Add(Background_0x0_pass_postfit_projx0_stack_1,"");
   postfit_projx0_pass_logy_stack->Draw("hist same");
   
   postfit_projx0_pass_logy_stack = new THStack();
   postfit_projx0_pass_logy_stack->SetName("postfit_projx0_pass_logy_stack");
   postfit_projx0_pass_logy_stack->SetTitle("postfit_projx0_pass_logy_stack");
   postfit_projx0_pass_logy_stack->SetMinimum(0.001);
   Double_t xAxis508[10] = {0, 0.05, 0.1, 0.15, 0.2, 0.25, 0.3, 0.35, 0.4, 1}; 
   
   TH1F *postfit_projx0_pass_logy_stack_stack_85_stack_86 = new TH1F("postfit_projx0_pass_logy_stack_stack_85_stack_86","postfit_projx0_pass_logy_stack",9, xAxis508);
   postfit_projx0_pass_logy_stack_stack_85_stack_86->SetMinimum(-0);
   postfit_projx0_pass_logy_stack_stack_85_stack_86->SetMaximum(-nan);
   postfit_projx0_pass_logy_stack_stack_85_stack_86->SetDirectory(0);
   postfit_projx0_pass_logy_stack_stack_85_stack_86->SetStats(0);
   postfit_projx0_pass_logy_stack_stack_85_stack_86->SetLineStyle(0);
   postfit_projx0_pass_logy_stack_stack_85_stack_86->GetXaxis()->SetLabelFont(42);
   postfit_projx0_pass_logy_stack_stack_85_stack_86->GetXaxis()->SetLabelOffset(0.007);
   postfit_projx0_pass_logy_stack_stack_85_stack_86->GetXaxis()->SetLabelSize(0.05);
   postfit_projx0_pass_logy_stack_stack_85_stack_86->GetXaxis()->SetTitleSize(0.08);
   postfit_projx0_pass_logy_stack_stack_85_stack_86->GetXaxis()->SetTitleOffset(0.9);
   postfit_projx0_pass_logy_stack_stack_85_stack_86->GetXaxis()->SetTitleFont(42);
   postfit_projx0_pass_logy_stack_stack_85_stack_86->GetYaxis()->SetNdivisions(508);
   postfit_projx0_pass_logy_stack_stack_85_stack_86->GetYaxis()->SetLabelFont(42);
   postfit_projx0_pass_logy_stack_stack_85_stack_86->GetYaxis()->SetLabelOffset(0.007);
   postfit_projx0_pass_logy_stack_stack_85_stack_86->GetYaxis()->SetLabelSize(0.05);
   postfit_projx0_pass_logy_stack_stack_85_stack_86->GetYaxis()->SetTitleSize(0.08);
   postfit_projx0_pass_logy_stack_stack_85_stack_86->GetYaxis()->SetTitleOffset(1.25);
   postfit_projx0_pass_logy_stack_stack_85_stack_86->GetYaxis()->SetTitleFont(42);
   postfit_projx0_pass_logy_stack_stack_85_stack_86->GetZaxis()->SetLabelFont(42);
   postfit_projx0_pass_logy_stack_stack_85_stack_86->GetZaxis()->SetLabelOffset(0.007);
   postfit_projx0_pass_logy_stack_stack_85_stack_86->GetZaxis()->SetLabelSize(0.05);
   postfit_projx0_pass_logy_stack_stack_85_stack_86->GetZaxis()->SetTitleSize(0.08);
   postfit_projx0_pass_logy_stack_stack_85_stack_86->GetZaxis()->SetTitleFont(42);
   postfit_projx0_pass_logy_stack->SetHistogram(postfit_projx0_pass_logy_stack_stack_85_stack_86);
   
   Double_t xAxis509[10] = {0, 0.05, 0.1, 0.15, 0.2, 0.25, 0.3, 0.35, 0.4, 1}; 
   
   TH1D *Background_0x0_pass_postfit_projx0_stack_1_stack_1 = new TH1D("Background_0x0_pass_postfit_projx0_stack_1_stack_1","Background, pass, postfit, 200-200",9, xAxis509);
   Background_0x0_pass_postfit_projx0_stack_1_stack_1->SetMinimum(0.001);

   ci = TColor::GetColor("#ffff00");
   Background_0x0_pass_postfit_projx0_stack_1_stack_1->SetFillColor(ci);

   ci = 1341;
   color = new TColor(ci, 1, 1, 1, " ", 0);
   Background_0x0_pass_postfit_projx0_stack_1_stack_1->SetLineColor(ci);
   Background_0x0_pass_postfit_projx0_stack_1_stack_1->SetLineStyle(0);
   Background_0x0_pass_postfit_projx0_stack_1_stack_1->GetXaxis()->SetTitle("G_{i}^{Strips}");
   Background_0x0_pass_postfit_projx0_stack_1_stack_1->GetXaxis()->SetLabelFont(42);
   Background_0x0_pass_postfit_projx0_stack_1_stack_1->GetXaxis()->SetLabelOffset(0.007);
   Background_0x0_pass_postfit_projx0_stack_1_stack_1->GetXaxis()->SetLabelSize(0.05);
   Background_0x0_pass_postfit_projx0_stack_1_stack_1->GetXaxis()->SetTitleSize(0.08);
   Background_0x0_pass_postfit_projx0_stack_1_stack_1->GetXaxis()->SetTitleOffset(0.9);
   Background_0x0_pass_postfit_projx0_stack_1_stack_1->GetXaxis()->SetTitleFont(42);
   Background_0x0_pass_postfit_projx0_stack_1_stack_1->GetYaxis()->SetTitle("Events / bin");
   Background_0x0_pass_postfit_projx0_stack_1_stack_1->GetYaxis()->SetLabelFont(42);
   Background_0x0_pass_postfit_projx0_stack_1_stack_1->GetYaxis()->SetLabelOffset(0.007);
   Background_0x0_pass_postfit_projx0_stack_1_stack_1->GetYaxis()->SetLabelSize(0.05);
   Background_0x0_pass_postfit_projx0_stack_1_stack_1->GetYaxis()->SetTitleSize(0.08);
   Background_0x0_pass_postfit_projx0_stack_1_stack_1->GetYaxis()->SetTitleOffset(1.25);
   Background_0x0_pass_postfit_projx0_stack_1_stack_1->GetYaxis()->SetTitleFont(42);
   Background_0x0_pass_postfit_projx0_stack_1_stack_1->GetZaxis()->SetLabelFont(42);
   Background_0x0_pass_postfit_projx0_stack_1_stack_1->GetZaxis()->SetLabelOffset(0.007);
   Background_0x0_pass_postfit_projx0_stack_1_stack_1->GetZaxis()->SetLabelSize(0.05);
   Background_0x0_pass_postfit_projx0_stack_1_stack_1->GetZaxis()->SetTitleSize(0.08);
   Background_0x0_pass_postfit_projx0_stack_1_stack_1->GetZaxis()->SetTitleFont(42);
   postfit_projx0_pass_logy_stack->Add(Background_0x0_pass_postfit_projx0_stack_1_stack_1,"");
   postfit_projx0_pass_logy_stack->Draw("hist same");
   Double_t xAxis510[10] = {0, 0.05, 0.1, 0.15, 0.2, 0.25, 0.3, 0.35, 0.4, 1}; 
   
   TH1D *Signal_gluinomI1800_pass_postfit_projx0__338 = new TH1D("Signal_gluinomI1800_pass_postfit_projx0__338","HSCP gluino 1800 GeV, pass, postfit, 200-200",9, xAxis510);
   Signal_gluinomI1800_pass_postfit_projx0__338->SetMinimum(0.001);
   Signal_gluinomI1800_pass_postfit_projx0__338->SetLineColor(4);
   Signal_gluinomI1800_pass_postfit_projx0__338->SetLineStyle(0);
   Signal_gluinomI1800_pass_postfit_projx0__338->SetLineWidth(2);
   Signal_gluinomI1800_pass_postfit_projx0__338->GetXaxis()->SetTitle("G_{i}^{Strips}");
   Signal_gluinomI1800_pass_postfit_projx0__338->GetXaxis()->SetLabelFont(42);
   Signal_gluinomI1800_pass_postfit_projx0__338->GetXaxis()->SetLabelOffset(0.007);
   Signal_gluinomI1800_pass_postfit_projx0__338->GetXaxis()->SetLabelSize(0.05);
   Signal_gluinomI1800_pass_postfit_projx0__338->GetXaxis()->SetTitleSize(0.08);
   Signal_gluinomI1800_pass_postfit_projx0__338->GetXaxis()->SetTitleOffset(0.9);
   Signal_gluinomI1800_pass_postfit_projx0__338->GetXaxis()->SetTitleFont(42);
   Signal_gluinomI1800_pass_postfit_projx0__338->GetYaxis()->SetTitle("Events / bin");
   Signal_gluinomI1800_pass_postfit_projx0__338->GetYaxis()->SetLabelFont(42);
   Signal_gluinomI1800_pass_postfit_projx0__338->GetYaxis()->SetLabelOffset(0.007);
   Signal_gluinomI1800_pass_postfit_projx0__338->GetYaxis()->SetLabelSize(0.05);
   Signal_gluinomI1800_pass_postfit_projx0__338->GetYaxis()->SetTitleSize(0.08);
   Signal_gluinomI1800_pass_postfit_projx0__338->GetYaxis()->SetTitleOffset(1.25);
   Signal_gluinomI1800_pass_postfit_projx0__338->GetYaxis()->SetTitleFont(42);
   Signal_gluinomI1800_pass_postfit_projx0__338->GetZaxis()->SetLabelFont(42);
   Signal_gluinomI1800_pass_postfit_projx0__338->GetZaxis()->SetLabelOffset(0.007);
   Signal_gluinomI1800_pass_postfit_projx0__338->GetZaxis()->SetLabelSize(0.05);
   Signal_gluinomI1800_pass_postfit_projx0__338->GetZaxis()->SetTitleSize(0.08);
   Signal_gluinomI1800_pass_postfit_projx0__338->GetZaxis()->SetTitleFont(42);
   Signal_gluinomI1800_pass_postfit_projx0__338->Draw("hist same");
   Double_t xAxis511[10] = {0, 0.05, 0.1, 0.15, 0.2, 0.25, 0.3, 0.35, 0.4, 1}; 
   
   TH1D *Signal_ppStaumI557_pass_postfit_projx0__339 = new TH1D("Signal_ppStaumI557_pass_postfit_projx0__339","HSCP stau 557 GeV, pass, postfit, 200-200",9, xAxis511);
   Signal_ppStaumI557_pass_postfit_projx0__339->SetMinimum(0.001);
   Signal_ppStaumI557_pass_postfit_projx0__339->SetLineColor(2);
   Signal_ppStaumI557_pass_postfit_projx0__339->SetLineStyle(0);
   Signal_ppStaumI557_pass_postfit_projx0__339->SetLineWidth(2);
   Signal_ppStaumI557_pass_postfit_projx0__339->GetXaxis()->SetTitle("G_{i}^{Strips}");
   Signal_ppStaumI557_pass_postfit_projx0__339->GetXaxis()->SetLabelFont(42);
   Signal_ppStaumI557_pass_postfit_projx0__339->GetXaxis()->SetLabelOffset(0.007);
   Signal_ppStaumI557_pass_postfit_projx0__339->GetXaxis()->SetLabelSize(0.05);
   Signal_ppStaumI557_pass_postfit_projx0__339->GetXaxis()->SetTitleSize(0.08);
   Signal_ppStaumI557_pass_postfit_projx0__339->GetXaxis()->SetTitleOffset(0.9);
   Signal_ppStaumI557_pass_postfit_projx0__339->GetXaxis()->SetTitleFont(42);
   Signal_ppStaumI557_pass_postfit_projx0__339->GetYaxis()->SetTitle("Events / bin");
   Signal_ppStaumI557_pass_postfit_projx0__339->GetYaxis()->SetLabelFont(42);
   Signal_ppStaumI557_pass_postfit_projx0__339->GetYaxis()->SetLabelOffset(0.007);
   Signal_ppStaumI557_pass_postfit_projx0__339->GetYaxis()->SetLabelSize(0.05);
   Signal_ppStaumI557_pass_postfit_projx0__339->GetYaxis()->SetTitleSize(0.08);
   Signal_ppStaumI557_pass_postfit_projx0__339->GetYaxis()->SetTitleOffset(1.25);
   Signal_ppStaumI557_pass_postfit_projx0__339->GetYaxis()->SetTitleFont(42);
   Signal_ppStaumI557_pass_postfit_projx0__339->GetZaxis()->SetLabelFont(42);
   Signal_ppStaumI557_pass_postfit_projx0__339->GetZaxis()->SetLabelOffset(0.007);
   Signal_ppStaumI557_pass_postfit_projx0__339->GetZaxis()->SetLabelSize(0.05);
   Signal_ppStaumI557_pass_postfit_projx0__339->GetZaxis()->SetTitleSize(0.08);
   Signal_ppStaumI557_pass_postfit_projx0__339->GetZaxis()->SetTitleFont(42);
   Signal_ppStaumI557_pass_postfit_projx0__339->Draw("hist same");
   Double_t xAxis512[10] = {0, 0.05, 0.1, 0.15, 0.2, 0.25, 0.3, 0.35, 0.4, 1}; 
   
   TH1D *TotalBkg_pass_postfit_projx0__340 = new TH1D("TotalBkg_pass_postfit_projx0__340","TotalBkg, pass, postfit, 200-200",9, xAxis512);
   TotalBkg_pass_postfit_projx0__340->SetMinimum(0.001);
   TotalBkg_pass_postfit_projx0__340->SetLineStyle(0);
   TotalBkg_pass_postfit_projx0__340->SetMarkerStyle(0);
   TotalBkg_pass_postfit_projx0__340->GetXaxis()->SetTitle("G_{i}^{Strips}");
   TotalBkg_pass_postfit_projx0__340->GetXaxis()->SetLabelFont(42);
   TotalBkg_pass_postfit_projx0__340->GetXaxis()->SetLabelOffset(0.007);
   TotalBkg_pass_postfit_projx0__340->GetXaxis()->SetLabelSize(0.05);
   TotalBkg_pass_postfit_projx0__340->GetXaxis()->SetTitleSize(0.08);
   TotalBkg_pass_postfit_projx0__340->GetXaxis()->SetTitleOffset(0.9);
   TotalBkg_pass_postfit_projx0__340->GetXaxis()->SetTitleFont(42);
   TotalBkg_pass_postfit_projx0__340->GetYaxis()->SetTitle("Events / bin");
   TotalBkg_pass_postfit_projx0__340->GetYaxis()->SetLabelFont(42);
   TotalBkg_pass_postfit_projx0__340->GetYaxis()->SetLabelOffset(0.007);
   TotalBkg_pass_postfit_projx0__340->GetYaxis()->SetLabelSize(0.05);
   TotalBkg_pass_postfit_projx0__340->GetYaxis()->SetTitleSize(0.08);
   TotalBkg_pass_postfit_projx0__340->GetYaxis()->SetTitleOffset(1.25);
   TotalBkg_pass_postfit_projx0__340->GetYaxis()->SetTitleFont(42);
   TotalBkg_pass_postfit_projx0__340->GetZaxis()->SetLabelFont(42);
   TotalBkg_pass_postfit_projx0__340->GetZaxis()->SetLabelOffset(0.007);
   TotalBkg_pass_postfit_projx0__340->GetZaxis()->SetLabelSize(0.05);
   TotalBkg_pass_postfit_projx0__340->GetZaxis()->SetTitleSize(0.08);
   TotalBkg_pass_postfit_projx0__340->GetZaxis()->SetTitleFont(42);
   TotalBkg_pass_postfit_projx0__340->Draw("hist same");
   Double_t xAxis513[10] = {0, 0.05, 0.1, 0.15, 0.2, 0.25, 0.3, 0.35, 0.4, 1}; 
   
   TH1D *TotalBkg_pass_postfit_projx0__341 = new TH1D("TotalBkg_pass_postfit_projx0__341","TotalBkg, pass, postfit, 200-200",9, xAxis513);
   TotalBkg_pass_postfit_projx0__341->SetMinimum(0.001);
   TotalBkg_pass_postfit_projx0__341->SetFillColor(1);
   TotalBkg_pass_postfit_projx0__341->SetFillStyle(3354);
   TotalBkg_pass_postfit_projx0__341->SetLineStyle(0);
   TotalBkg_pass_postfit_projx0__341->SetLineWidth(0);
   TotalBkg_pass_postfit_projx0__341->SetMarkerStyle(0);
   TotalBkg_pass_postfit_projx0__341->GetXaxis()->SetTitle("G_{i}^{Strips}");
   TotalBkg_pass_postfit_projx0__341->GetXaxis()->SetLabelFont(42);
   TotalBkg_pass_postfit_projx0__341->GetXaxis()->SetLabelOffset(0.007);
   TotalBkg_pass_postfit_projx0__341->GetXaxis()->SetLabelSize(0.05);
   TotalBkg_pass_postfit_projx0__341->GetXaxis()->SetTitleSize(0.08);
   TotalBkg_pass_postfit_projx0__341->GetXaxis()->SetTitleOffset(0.9);
   TotalBkg_pass_postfit_projx0__341->GetXaxis()->SetTitleFont(42);
   TotalBkg_pass_postfit_projx0__341->GetYaxis()->SetTitle("Events / bin");
   TotalBkg_pass_postfit_projx0__341->GetYaxis()->SetLabelFont(42);
   TotalBkg_pass_postfit_projx0__341->GetYaxis()->SetLabelOffset(0.007);
   TotalBkg_pass_postfit_projx0__341->GetYaxis()->SetLabelSize(0.05);
   TotalBkg_pass_postfit_projx0__341->GetYaxis()->SetTitleSize(0.08);
   TotalBkg_pass_postfit_projx0__341->GetYaxis()->SetTitleOffset(1.25);
   TotalBkg_pass_postfit_projx0__341->GetYaxis()->SetTitleFont(42);
   TotalBkg_pass_postfit_projx0__341->GetZaxis()->SetLabelFont(42);
   TotalBkg_pass_postfit_projx0__341->GetZaxis()->SetLabelOffset(0.007);
   TotalBkg_pass_postfit_projx0__341->GetZaxis()->SetLabelSize(0.05);
   TotalBkg_pass_postfit_projx0__341->GetZaxis()->SetTitleSize(0.08);
   TotalBkg_pass_postfit_projx0__341->GetZaxis()->SetTitleFont(42);
   TotalBkg_pass_postfit_projx0__341->Draw("e2 same");
   Double_t xAxis514[10] = {0, 0.05, 0.1, 0.15, 0.2, 0.25, 0.3, 0.35, 0.4, 1}; 
   
   TH1D *data_obs_pass_postfit_projx0__342 = new TH1D("data_obs_pass_postfit_projx0__342","",9, xAxis514);
   data_obs_pass_postfit_projx0__342->SetMinimum(0.001);
   data_obs_pass_postfit_projx0__342->SetMaximum(0);

   ci = TColor::GetColor("#000000");
   data_obs_pass_postfit_projx0__342->SetLineColor(ci);
   data_obs_pass_postfit_projx0__342->SetLineStyle(0);

   ci = TColor::GetColor("#000000");
   data_obs_pass_postfit_projx0__342->SetMarkerColor(ci);
   data_obs_pass_postfit_projx0__342->SetMarkerStyle(8);
   data_obs_pass_postfit_projx0__342->GetXaxis()->SetTitle("G_{i}^{Strips}");
   data_obs_pass_postfit_projx0__342->GetXaxis()->SetLabelFont(42);
   data_obs_pass_postfit_projx0__342->GetXaxis()->SetLabelOffset(0.05);
   data_obs_pass_postfit_projx0__342->GetXaxis()->SetLabelSize(0.07);
   data_obs_pass_postfit_projx0__342->GetXaxis()->SetTitleSize(0.09);
   data_obs_pass_postfit_projx0__342->GetXaxis()->SetTitleOffset(1.15);
   data_obs_pass_postfit_projx0__342->GetXaxis()->SetTitleFont(42);
   data_obs_pass_postfit_projx0__342->GetYaxis()->SetTitle("Events / bin");
   data_obs_pass_postfit_projx0__342->GetYaxis()->SetNdivisions(508);
   data_obs_pass_postfit_projx0__342->GetYaxis()->SetLabelFont(42);
   data_obs_pass_postfit_projx0__342->GetYaxis()->SetLabelOffset(0.007);
   data_obs_pass_postfit_projx0__342->GetYaxis()->SetLabelSize(0.07);
   data_obs_pass_postfit_projx0__342->GetYaxis()->SetTitleSize(0.09);
   data_obs_pass_postfit_projx0__342->GetYaxis()->SetTitleOffset(0.8);
   data_obs_pass_postfit_projx0__342->GetYaxis()->SetTitleFont(42);
   data_obs_pass_postfit_projx0__342->GetZaxis()->SetLabelFont(42);
   data_obs_pass_postfit_projx0__342->GetZaxis()->SetLabelOffset(0.007);
   data_obs_pass_postfit_projx0__342->GetZaxis()->SetLabelSize(0.05);
   data_obs_pass_postfit_projx0__342->GetZaxis()->SetTitleSize(0.08);
   data_obs_pass_postfit_projx0__342->GetZaxis()->SetTitleFont(42);
   data_obs_pass_postfit_projx0__342->Draw("pe X0 same");
   
   TLegend *leg = new TLegend(0.65,0.61,0.9,0.88,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(1001);
   TLegendEntry *entry=leg->AddEntry("data_obs_pass_postfit_projx0","Data","pe X0");

   ci = TColor::GetColor("#000000");
   entry->SetLineColor(ci);
   entry->SetLineWidth(1);

   ci = TColor::GetColor("#000000");
   entry->SetMarkerColor(ci);
   entry->SetMarkerStyle(8);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("TotalBkg_pass_postfit_projx0","Total bkg unc.","F");
   entry->SetFillColor(1);
   entry->SetFillStyle(3354);
   entry->SetLineColor(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("Signal_gluino-1800_pass_postfit_projx0","HSCP gluino 1800 GeV","L");
   entry->SetLineColor(4);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("Signal_ppStau-557_pass_postfit_projx0","HSCP stau 557 GeV","L");
   entry->SetLineColor(2);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("Background_0x0_pass_postfit_projx0_stack_1_stack_1","Background","f");

   ci = TColor::GetColor("#ffff00");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = 1341;
   color = new TColor(ci, 1, 1, 1, " ", 0);
   entry->SetLineColor(ci);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   leg->Draw();
   Double_t xAxis515[10] = {0, 0.05, 0.1, 0.15, 0.2, 0.25, 0.3, 0.35, 0.4, 1}; 
   
   TH1D *data_obs_pass_postfit_projx0_copy__343 = new TH1D("data_obs_pass_postfit_projx0_copy__343","",9, xAxis515);
   data_obs_pass_postfit_projx0_copy__343->SetMinimum(0.001);
   data_obs_pass_postfit_projx0_copy__343->SetMaximum(0);
   data_obs_pass_postfit_projx0_copy__343->SetDirectory(0);

   ci = TColor::GetColor("#000000");
   data_obs_pass_postfit_projx0_copy__343->SetLineColor(ci);
   data_obs_pass_postfit_projx0_copy__343->SetLineStyle(0);

   ci = TColor::GetColor("#000000");
   data_obs_pass_postfit_projx0_copy__343->SetMarkerColor(ci);
   data_obs_pass_postfit_projx0_copy__343->SetMarkerStyle(8);
   data_obs_pass_postfit_projx0_copy__343->GetXaxis()->SetTitle("G_{i}^{Strips}");
   data_obs_pass_postfit_projx0_copy__343->GetXaxis()->SetLabelFont(42);
   data_obs_pass_postfit_projx0_copy__343->GetXaxis()->SetLabelOffset(0.05);
   data_obs_pass_postfit_projx0_copy__343->GetXaxis()->SetLabelSize(0.07);
   data_obs_pass_postfit_projx0_copy__343->GetXaxis()->SetTitleSize(0.09);
   data_obs_pass_postfit_projx0_copy__343->GetXaxis()->SetTitleOffset(1.15);
   data_obs_pass_postfit_projx0_copy__343->GetXaxis()->SetTitleFont(42);
   data_obs_pass_postfit_projx0_copy__343->GetYaxis()->SetTitle("Events / bin");
   data_obs_pass_postfit_projx0_copy__343->GetYaxis()->SetNdivisions(508);
   data_obs_pass_postfit_projx0_copy__343->GetYaxis()->SetLabelFont(42);
   data_obs_pass_postfit_projx0_copy__343->GetYaxis()->SetLabelOffset(0.007);
   data_obs_pass_postfit_projx0_copy__343->GetYaxis()->SetLabelSize(0.07);
   data_obs_pass_postfit_projx0_copy__343->GetYaxis()->SetTitleSize(0.09);
   data_obs_pass_postfit_projx0_copy__343->GetYaxis()->SetTitleOffset(0.8);
   data_obs_pass_postfit_projx0_copy__343->GetYaxis()->SetTitleFont(42);
   data_obs_pass_postfit_projx0_copy__343->GetZaxis()->SetLabelFont(42);
   data_obs_pass_postfit_projx0_copy__343->GetZaxis()->SetLabelOffset(0.007);
   data_obs_pass_postfit_projx0_copy__343->GetZaxis()->SetLabelSize(0.05);
   data_obs_pass_postfit_projx0_copy__343->GetZaxis()->SetTitleSize(0.08);
   data_obs_pass_postfit_projx0_copy__343->GetZaxis()->SetTitleFont(42);
   data_obs_pass_postfit_projx0_copy__343->Draw("sameaxis");
   TLatex *   tex = new TLatex(0.21,0.83,"200 < p_{T} < 200 , F^{Pixels}_{i} > 0.9");
tex->SetNDC();
   tex->SetTextAlign(12);
   tex->SetTextFont(42);
   tex->SetTextSize(0.06);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.17,0.92,"CMS");
tex->SetNDC();
   tex->SetTextFont(61);
   tex->SetTextSize(0.0675);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.25,0.92,"Preliminary");
tex->SetNDC();
   tex->SetTextFont(52);
   tex->SetTextSize(0.0485);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.95,0.92,"101 fb^{-1} (13 TeV)");
tex->SetNDC();
   tex->SetTextAlign(31);
   tex->SetTextFont(42);
   tex->SetTextSize(0.07);
   tex->SetLineWidth(2);
   tex->Draw();
   data_obs_pass_postfit_projx0_main->Modified();
   plots_fit_s/base_figs/postfit_projx0_pass_logy->cd();
  
// ------------>Primitives in pad: data_obs_pass_postfit_projx0_sub
   TPad *data_obs_pass_postfit_projx0_sub = new TPad("data_obs_pass_postfit_projx0_sub", "data_obs_pass_postfit_projx0_sub",0,0,1,0.35);
   data_obs_pass_postfit_projx0_sub->Draw();
   data_obs_pass_postfit_projx0_sub->cd();
   data_obs_pass_postfit_projx0_sub->Range(-0.2179487,-6.023077,1.064103,2.9);
   data_obs_pass_postfit_projx0_sub->SetFillColor(0);
   data_obs_pass_postfit_projx0_sub->SetBorderMode(0);
   data_obs_pass_postfit_projx0_sub->SetBorderSize(2);
   data_obs_pass_postfit_projx0_sub->SetTickx(1);
   data_obs_pass_postfit_projx0_sub->SetTicky(1);
   data_obs_pass_postfit_projx0_sub->SetLeftMargin(0.17);
   data_obs_pass_postfit_projx0_sub->SetRightMargin(0.05);
   data_obs_pass_postfit_projx0_sub->SetTopMargin(0);
   data_obs_pass_postfit_projx0_sub->SetBottomMargin(0.35);
   data_obs_pass_postfit_projx0_sub->SetFrameFillStyle(0);
   data_obs_pass_postfit_projx0_sub->SetFrameBorderMode(0);
   data_obs_pass_postfit_projx0_sub->SetFrameFillStyle(0);
   data_obs_pass_postfit_projx0_sub->SetFrameBorderMode(0);
   Double_t xAxis516[10] = {0, 0.05, 0.1, 0.15, 0.2, 0.25, 0.3, 0.35, 0.4, 1}; 
   
   TH1D *data_obs_pass_postfit_projx0_pull__344 = new TH1D("data_obs_pass_postfit_projx0_pull__344","",9, xAxis516);
   data_obs_pass_postfit_projx0_pull__344->SetMinimum(-2.9);
   data_obs_pass_postfit_projx0_pull__344->SetMaximum(2.9);
   data_obs_pass_postfit_projx0_pull__344->SetEntries(18);
   data_obs_pass_postfit_projx0_pull__344->SetStats(0);

   ci = TColor::GetColor("#0000ff");
   data_obs_pass_postfit_projx0_pull__344->SetFillColor(ci);

   ci = TColor::GetColor("#000000");
   data_obs_pass_postfit_projx0_pull__344->SetLineColor(ci);
   data_obs_pass_postfit_projx0_pull__344->SetLineStyle(0);

   ci = TColor::GetColor("#000000");
   data_obs_pass_postfit_projx0_pull__344->SetMarkerColor(ci);
   data_obs_pass_postfit_projx0_pull__344->SetMarkerStyle(8);
   data_obs_pass_postfit_projx0_pull__344->GetXaxis()->SetTitle("G_{i}^{Strips}");
   data_obs_pass_postfit_projx0_pull__344->GetXaxis()->SetLabelFont(42);
   data_obs_pass_postfit_projx0_pull__344->GetXaxis()->SetLabelOffset(0.05);
   data_obs_pass_postfit_projx0_pull__344->GetXaxis()->SetLabelSize(0.13);
   data_obs_pass_postfit_projx0_pull__344->GetXaxis()->SetTitleSize(0.15);
   data_obs_pass_postfit_projx0_pull__344->GetXaxis()->SetTitleOffset(1.15);
   data_obs_pass_postfit_projx0_pull__344->GetXaxis()->SetTitleFont(42);
   data_obs_pass_postfit_projx0_pull__344->GetYaxis()->SetTitle("(Data-Bkg)/#sigma");
   data_obs_pass_postfit_projx0_pull__344->GetYaxis()->SetNdivisions(306);
   data_obs_pass_postfit_projx0_pull__344->GetYaxis()->SetLabelFont(42);
   data_obs_pass_postfit_projx0_pull__344->GetYaxis()->SetLabelOffset(0.007);
   data_obs_pass_postfit_projx0_pull__344->GetYaxis()->SetLabelSize(0.13);
   data_obs_pass_postfit_projx0_pull__344->GetYaxis()->SetTitleSize(0.12);
   data_obs_pass_postfit_projx0_pull__344->GetYaxis()->SetTitleOffset(0.4);
   data_obs_pass_postfit_projx0_pull__344->GetYaxis()->SetTitleFont(42);
   data_obs_pass_postfit_projx0_pull__344->GetZaxis()->SetLabelFont(42);
   data_obs_pass_postfit_projx0_pull__344->GetZaxis()->SetLabelOffset(0.007);
   data_obs_pass_postfit_projx0_pull__344->GetZaxis()->SetLabelSize(0.05);
   data_obs_pass_postfit_projx0_pull__344->GetZaxis()->SetTitleSize(0.08);
   data_obs_pass_postfit_projx0_pull__344->GetZaxis()->SetTitleFont(42);
   data_obs_pass_postfit_projx0_pull__344->Draw("hist");
   data_obs_pass_postfit_projx0_sub->Modified();
   plots_fit_s/base_figs/postfit_projx0_pass_logy->cd();
   plots_fit_s/base_figs/postfit_projx0_pass_logy->Modified();
   plots_fit_s/base_figs/postfit_projx0_pass_logy->cd();
   plots_fit_s/base_figs/postfit_projx0_pass_logy->SetSelected(plots_fit_s/base_figs/postfit_projx0_pass_logy);
}
