void postfit_projy1_pass()
{
//=========Macro generated from canvas: plots_fit_b/base_figs/postfit_projy1_pass/plots_fit_b/base_figs/postfit_projy1_pass
//=========  (Fri Jan 12 21:00:02 2024) by ROOT version 6.14/09
   TCanvas *plots_fit_b/base_figs/postfit_projy1_pass = new TCanvas("plots_fit_b/base_figs/postfit_projy1_pass", "plots_fit_b/base_figs/postfit_projy1_pass",0,0,800,700);
   gStyle->SetOptFit(1);
   gStyle->SetOptStat(0);
   plots_fit_b/base_figs/postfit_projy1_pass->SetHighLightColor(2);
   plots_fit_b/base_figs/postfit_projy1_pass->Range(0,0,1,1);
   plots_fit_b/base_figs/postfit_projy1_pass->SetFillColor(0);
   plots_fit_b/base_figs/postfit_projy1_pass->SetBorderMode(0);
   plots_fit_b/base_figs/postfit_projy1_pass->SetBorderSize(2);
   plots_fit_b/base_figs/postfit_projy1_pass->SetTickx(1);
   plots_fit_b/base_figs/postfit_projy1_pass->SetTicky(1);
   plots_fit_b/base_figs/postfit_projy1_pass->SetLeftMargin(0.16);
   plots_fit_b/base_figs/postfit_projy1_pass->SetRightMargin(0);
   plots_fit_b/base_figs/postfit_projy1_pass->SetTopMargin(0);
   plots_fit_b/base_figs/postfit_projy1_pass->SetBottomMargin(0);
   plots_fit_b/base_figs/postfit_projy1_pass->SetFrameFillStyle(0);
   plots_fit_b/base_figs/postfit_projy1_pass->SetFrameBorderMode(0);
  
// ------------>Primitives in pad: data_obs_pass_postfit_projy1_main
   TPad *data_obs_pass_postfit_projy1_main = new TPad("data_obs_pass_postfit_projy1_main", "data_obs_pass_postfit_projy1_main",0,0.35,1,1);
   data_obs_pass_postfit_projy1_main->Draw();
   data_obs_pass_postfit_projy1_main->cd();
   data_obs_pass_postfit_projy1_main->Range(17.30769,-62.16279,209.6154,1491.907);
   data_obs_pass_postfit_projy1_main->SetFillColor(0);
   data_obs_pass_postfit_projy1_main->SetBorderMode(0);
   data_obs_pass_postfit_projy1_main->SetBorderSize(2);
   data_obs_pass_postfit_projy1_main->SetTickx(1);
   data_obs_pass_postfit_projy1_main->SetTicky(1);
   data_obs_pass_postfit_projy1_main->SetLeftMargin(0.17);
   data_obs_pass_postfit_projy1_main->SetRightMargin(0.05);
   data_obs_pass_postfit_projy1_main->SetBottomMargin(0.04);
   data_obs_pass_postfit_projy1_main->SetFrameFillStyle(0);
   data_obs_pass_postfit_projy1_main->SetFrameBorderMode(0);
   data_obs_pass_postfit_projy1_main->SetFrameFillStyle(0);
   data_obs_pass_postfit_projy1_main->SetFrameBorderMode(0);
   Double_t xAxis177[2] = {50, 200}; 
   
   TH1D *data_obs_pass_postfit_projy1__113 = new TH1D("data_obs_pass_postfit_projy1__113","",1, xAxis177);
   data_obs_pass_postfit_projy1__113->SetBinContent(1,990);
   data_obs_pass_postfit_projy1__113->SetBinError(1,31.46427);
   data_obs_pass_postfit_projy1__113->SetMinimum(0);
   data_obs_pass_postfit_projy1__113->SetMaximum(1336.5);
   data_obs_pass_postfit_projy1__113->SetEntries(990);
   data_obs_pass_postfit_projy1__113->SetStats(0);

   Int_t ci;      // for color index setting
   TColor *color; // for color definition with alpha
   ci = TColor::GetColor("#000000");
   data_obs_pass_postfit_projy1__113->SetLineColor(ci);

   ci = TColor::GetColor("#000000");
   data_obs_pass_postfit_projy1__113->SetMarkerColor(ci);
   data_obs_pass_postfit_projy1__113->SetMarkerStyle(8);
   data_obs_pass_postfit_projy1__113->GetXaxis()->SetTitle("p_{T}");
   data_obs_pass_postfit_projy1__113->GetXaxis()->SetLabelFont(42);
   data_obs_pass_postfit_projy1__113->GetXaxis()->SetLabelOffset(0.05);
   data_obs_pass_postfit_projy1__113->GetXaxis()->SetLabelSize(0.07);
   data_obs_pass_postfit_projy1__113->GetXaxis()->SetTitleSize(0.09);
   data_obs_pass_postfit_projy1__113->GetXaxis()->SetTitleOffset(1.15);
   data_obs_pass_postfit_projy1__113->GetXaxis()->SetTitleFont(42);
   data_obs_pass_postfit_projy1__113->GetYaxis()->SetTitle("Events / bin");
   data_obs_pass_postfit_projy1__113->GetYaxis()->SetNdivisions(508);
   data_obs_pass_postfit_projy1__113->GetYaxis()->SetLabelFont(42);
   data_obs_pass_postfit_projy1__113->GetYaxis()->SetLabelSize(0.07);
   data_obs_pass_postfit_projy1__113->GetYaxis()->SetTitleSize(0.09);
   data_obs_pass_postfit_projy1__113->GetYaxis()->SetTitleOffset(0.8);
   data_obs_pass_postfit_projy1__113->GetYaxis()->SetTitleFont(42);
   data_obs_pass_postfit_projy1__113->GetZaxis()->SetLabelFont(42);
   data_obs_pass_postfit_projy1__113->GetZaxis()->SetLabelSize(0.035);
   data_obs_pass_postfit_projy1__113->GetZaxis()->SetTitleSize(0.035);
   data_obs_pass_postfit_projy1__113->GetZaxis()->SetTitleFont(42);
   data_obs_pass_postfit_projy1__113->Draw("pe X0");
   
   THStack *postfit_projy1_pass_stack = new THStack();
   postfit_projy1_pass_stack->SetName("postfit_projy1_pass_stack");
   postfit_projy1_pass_stack->SetTitle("postfit_projy1_pass_stack");
   Double_t xAxis178[2] = {50, 200}; 
   
   TH1F *postfit_projy1_pass_stack_stack_33 = new TH1F("postfit_projy1_pass_stack_stack_33","postfit_projy1_pass_stack",1, xAxis178);
   postfit_projy1_pass_stack_stack_33->SetMinimum(0);
   postfit_projy1_pass_stack_stack_33->SetMaximum(1090.878);
   postfit_projy1_pass_stack_stack_33->SetDirectory(0);
   postfit_projy1_pass_stack_stack_33->SetStats(0);
   postfit_projy1_pass_stack_stack_33->SetLineStyle(0);
   postfit_projy1_pass_stack_stack_33->GetXaxis()->SetLabelFont(42);
   postfit_projy1_pass_stack_stack_33->GetXaxis()->SetLabelOffset(0.007);
   postfit_projy1_pass_stack_stack_33->GetXaxis()->SetLabelSize(0.05);
   postfit_projy1_pass_stack_stack_33->GetXaxis()->SetTitleSize(0.08);
   postfit_projy1_pass_stack_stack_33->GetXaxis()->SetTitleOffset(0.9);
   postfit_projy1_pass_stack_stack_33->GetXaxis()->SetTitleFont(42);
   postfit_projy1_pass_stack_stack_33->GetYaxis()->SetNdivisions(508);
   postfit_projy1_pass_stack_stack_33->GetYaxis()->SetLabelFont(42);
   postfit_projy1_pass_stack_stack_33->GetYaxis()->SetLabelOffset(0.007);
   postfit_projy1_pass_stack_stack_33->GetYaxis()->SetLabelSize(0.05);
   postfit_projy1_pass_stack_stack_33->GetYaxis()->SetTitleSize(0.08);
   postfit_projy1_pass_stack_stack_33->GetYaxis()->SetTitleOffset(1.25);
   postfit_projy1_pass_stack_stack_33->GetYaxis()->SetTitleFont(42);
   postfit_projy1_pass_stack_stack_33->GetZaxis()->SetLabelFont(42);
   postfit_projy1_pass_stack_stack_33->GetZaxis()->SetLabelOffset(0.007);
   postfit_projy1_pass_stack_stack_33->GetZaxis()->SetLabelSize(0.05);
   postfit_projy1_pass_stack_stack_33->GetZaxis()->SetTitleSize(0.08);
   postfit_projy1_pass_stack_stack_33->GetZaxis()->SetTitleFont(42);
   postfit_projy1_pass_stack->SetHistogram(postfit_projy1_pass_stack_stack_33);
   
   Double_t xAxis179[2] = {50, 200}; 
   
   TH1D *Background_0x0_pass_postfit_projy1_stack_1 = new TH1D("Background_0x0_pass_postfit_projy1_stack_1","Background, pass, postfit, 0.24-1.0",1, xAxis179);
   Background_0x0_pass_postfit_projy1_stack_1->SetBinContent(1,1025.981);
   Background_0x0_pass_postfit_projy1_stack_1->SetBinError(1,12.9502);
   Background_0x0_pass_postfit_projy1_stack_1->SetMinimum(0);
   Background_0x0_pass_postfit_projy1_stack_1->SetEntries(6276.616);
   Background_0x0_pass_postfit_projy1_stack_1->SetStats(0);

   ci = TColor::GetColor("#ffff00");
   Background_0x0_pass_postfit_projy1_stack_1->SetFillColor(ci);

   ci = 1201;
   color = new TColor(ci, 1, 1, 1, " ", 0);
   Background_0x0_pass_postfit_projy1_stack_1->SetLineColor(ci);
   Background_0x0_pass_postfit_projy1_stack_1->GetXaxis()->SetTitle("p_{T}");
   Background_0x0_pass_postfit_projy1_stack_1->GetXaxis()->SetLabelFont(42);
   Background_0x0_pass_postfit_projy1_stack_1->GetXaxis()->SetLabelSize(0.035);
   Background_0x0_pass_postfit_projy1_stack_1->GetXaxis()->SetTitleSize(0.035);
   Background_0x0_pass_postfit_projy1_stack_1->GetXaxis()->SetTitleOffset(0);
   Background_0x0_pass_postfit_projy1_stack_1->GetXaxis()->SetTitleFont(42);
   Background_0x0_pass_postfit_projy1_stack_1->GetYaxis()->SetTitle("Events / bin");
   Background_0x0_pass_postfit_projy1_stack_1->GetYaxis()->SetLabelFont(42);
   Background_0x0_pass_postfit_projy1_stack_1->GetYaxis()->SetLabelSize(0.035);
   Background_0x0_pass_postfit_projy1_stack_1->GetYaxis()->SetTitleSize(0.035);
   Background_0x0_pass_postfit_projy1_stack_1->GetYaxis()->SetTitleOffset(0);
   Background_0x0_pass_postfit_projy1_stack_1->GetYaxis()->SetTitleFont(42);
   Background_0x0_pass_postfit_projy1_stack_1->GetZaxis()->SetLabelFont(42);
   Background_0x0_pass_postfit_projy1_stack_1->GetZaxis()->SetLabelSize(0.035);
   Background_0x0_pass_postfit_projy1_stack_1->GetZaxis()->SetTitleSize(0.035);
   Background_0x0_pass_postfit_projy1_stack_1->GetZaxis()->SetTitleFont(42);
   postfit_projy1_pass_stack->Add(Background_0x0_pass_postfit_projy1_stack_1,"");
   postfit_projy1_pass_stack->Draw("hist same");
   
   postfit_projy1_pass_stack = new THStack();
   postfit_projy1_pass_stack->SetName("postfit_projy1_pass_stack");
   postfit_projy1_pass_stack->SetTitle("postfit_projy1_pass_stack");
   Double_t xAxis180[2] = {50, 200}; 
   
   TH1F *postfit_projy1_pass_stack_stack_33_stack_34 = new TH1F("postfit_projy1_pass_stack_stack_33_stack_34","postfit_projy1_pass_stack",1, xAxis180);
   postfit_projy1_pass_stack_stack_33_stack_34->SetMinimum(0);
   postfit_projy1_pass_stack_stack_33_stack_34->SetMaximum(1090.878);
   postfit_projy1_pass_stack_stack_33_stack_34->SetDirectory(0);
   postfit_projy1_pass_stack_stack_33_stack_34->SetStats(0);
   postfit_projy1_pass_stack_stack_33_stack_34->SetLineStyle(0);
   postfit_projy1_pass_stack_stack_33_stack_34->GetXaxis()->SetLabelFont(42);
   postfit_projy1_pass_stack_stack_33_stack_34->GetXaxis()->SetLabelOffset(0.007);
   postfit_projy1_pass_stack_stack_33_stack_34->GetXaxis()->SetLabelSize(0.05);
   postfit_projy1_pass_stack_stack_33_stack_34->GetXaxis()->SetTitleSize(0.08);
   postfit_projy1_pass_stack_stack_33_stack_34->GetXaxis()->SetTitleOffset(0.9);
   postfit_projy1_pass_stack_stack_33_stack_34->GetXaxis()->SetTitleFont(42);
   postfit_projy1_pass_stack_stack_33_stack_34->GetYaxis()->SetNdivisions(508);
   postfit_projy1_pass_stack_stack_33_stack_34->GetYaxis()->SetLabelFont(42);
   postfit_projy1_pass_stack_stack_33_stack_34->GetYaxis()->SetLabelOffset(0.007);
   postfit_projy1_pass_stack_stack_33_stack_34->GetYaxis()->SetLabelSize(0.05);
   postfit_projy1_pass_stack_stack_33_stack_34->GetYaxis()->SetTitleSize(0.08);
   postfit_projy1_pass_stack_stack_33_stack_34->GetYaxis()->SetTitleOffset(1.25);
   postfit_projy1_pass_stack_stack_33_stack_34->GetYaxis()->SetTitleFont(42);
   postfit_projy1_pass_stack_stack_33_stack_34->GetZaxis()->SetLabelFont(42);
   postfit_projy1_pass_stack_stack_33_stack_34->GetZaxis()->SetLabelOffset(0.007);
   postfit_projy1_pass_stack_stack_33_stack_34->GetZaxis()->SetLabelSize(0.05);
   postfit_projy1_pass_stack_stack_33_stack_34->GetZaxis()->SetTitleSize(0.08);
   postfit_projy1_pass_stack_stack_33_stack_34->GetZaxis()->SetTitleFont(42);
   postfit_projy1_pass_stack->SetHistogram(postfit_projy1_pass_stack_stack_33_stack_34);
   
   Double_t xAxis181[2] = {50, 200}; 
   
   TH1D *Background_0x0_pass_postfit_projy1_stack_1_stack_1 = new TH1D("Background_0x0_pass_postfit_projy1_stack_1_stack_1","Background, pass, postfit, 0.24-1.0",1, xAxis181);
   Background_0x0_pass_postfit_projy1_stack_1_stack_1->SetBinContent(1,1025.981);
   Background_0x0_pass_postfit_projy1_stack_1_stack_1->SetBinError(1,12.9502);
   Background_0x0_pass_postfit_projy1_stack_1_stack_1->SetMinimum(0);
   Background_0x0_pass_postfit_projy1_stack_1_stack_1->SetEntries(6276.616);
   Background_0x0_pass_postfit_projy1_stack_1_stack_1->SetStats(0);

   ci = TColor::GetColor("#ffff00");
   Background_0x0_pass_postfit_projy1_stack_1_stack_1->SetFillColor(ci);

   ci = 1201;
   color = new TColor(ci, 1, 1, 1, " ", 0);
   Background_0x0_pass_postfit_projy1_stack_1_stack_1->SetLineColor(ci);
   Background_0x0_pass_postfit_projy1_stack_1_stack_1->GetXaxis()->SetTitle("p_{T}");
   Background_0x0_pass_postfit_projy1_stack_1_stack_1->GetXaxis()->SetLabelFont(42);
   Background_0x0_pass_postfit_projy1_stack_1_stack_1->GetXaxis()->SetLabelSize(0.035);
   Background_0x0_pass_postfit_projy1_stack_1_stack_1->GetXaxis()->SetTitleSize(0.035);
   Background_0x0_pass_postfit_projy1_stack_1_stack_1->GetXaxis()->SetTitleOffset(0);
   Background_0x0_pass_postfit_projy1_stack_1_stack_1->GetXaxis()->SetTitleFont(42);
   Background_0x0_pass_postfit_projy1_stack_1_stack_1->GetYaxis()->SetTitle("Events / bin");
   Background_0x0_pass_postfit_projy1_stack_1_stack_1->GetYaxis()->SetLabelFont(42);
   Background_0x0_pass_postfit_projy1_stack_1_stack_1->GetYaxis()->SetLabelSize(0.035);
   Background_0x0_pass_postfit_projy1_stack_1_stack_1->GetYaxis()->SetTitleSize(0.035);
   Background_0x0_pass_postfit_projy1_stack_1_stack_1->GetYaxis()->SetTitleOffset(0);
   Background_0x0_pass_postfit_projy1_stack_1_stack_1->GetYaxis()->SetTitleFont(42);
   Background_0x0_pass_postfit_projy1_stack_1_stack_1->GetZaxis()->SetLabelFont(42);
   Background_0x0_pass_postfit_projy1_stack_1_stack_1->GetZaxis()->SetLabelSize(0.035);
   Background_0x0_pass_postfit_projy1_stack_1_stack_1->GetZaxis()->SetTitleSize(0.035);
   Background_0x0_pass_postfit_projy1_stack_1_stack_1->GetZaxis()->SetTitleFont(42);
   postfit_projy1_pass_stack->Add(Background_0x0_pass_postfit_projy1_stack_1_stack_1,"");
   postfit_projy1_pass_stack->Draw("hist same");
   Double_t xAxis182[2] = {50, 200}; 
   
   TH1D *Signal_ppStaumI557_pass_postfit_projy1__114 = new TH1D("Signal_ppStaumI557_pass_postfit_projy1__114","HSCP signal, pass, postfit, 0.24-1.0",1, xAxis182);
   Signal_ppStaumI557_pass_postfit_projy1__114->SetBinContent(1,0.232382);
   Signal_ppStaumI557_pass_postfit_projy1__114->SetBinError(1,0.04518739);
   Signal_ppStaumI557_pass_postfit_projy1__114->SetMinimum(0);
   Signal_ppStaumI557_pass_postfit_projy1__114->SetEntries(26.44664);
   Signal_ppStaumI557_pass_postfit_projy1__114->SetStats(0);
   Signal_ppStaumI557_pass_postfit_projy1__114->SetLineColor(2);
   Signal_ppStaumI557_pass_postfit_projy1__114->GetXaxis()->SetTitle("p_{T}");
   Signal_ppStaumI557_pass_postfit_projy1__114->GetXaxis()->SetLabelFont(42);
   Signal_ppStaumI557_pass_postfit_projy1__114->GetXaxis()->SetLabelSize(0.035);
   Signal_ppStaumI557_pass_postfit_projy1__114->GetXaxis()->SetTitleSize(0.035);
   Signal_ppStaumI557_pass_postfit_projy1__114->GetXaxis()->SetTitleOffset(0);
   Signal_ppStaumI557_pass_postfit_projy1__114->GetXaxis()->SetTitleFont(42);
   Signal_ppStaumI557_pass_postfit_projy1__114->GetYaxis()->SetTitle("Events / bin");
   Signal_ppStaumI557_pass_postfit_projy1__114->GetYaxis()->SetLabelFont(42);
   Signal_ppStaumI557_pass_postfit_projy1__114->GetYaxis()->SetLabelSize(0.035);
   Signal_ppStaumI557_pass_postfit_projy1__114->GetYaxis()->SetTitleSize(0.035);
   Signal_ppStaumI557_pass_postfit_projy1__114->GetYaxis()->SetTitleOffset(0);
   Signal_ppStaumI557_pass_postfit_projy1__114->GetYaxis()->SetTitleFont(42);
   Signal_ppStaumI557_pass_postfit_projy1__114->GetZaxis()->SetLabelFont(42);
   Signal_ppStaumI557_pass_postfit_projy1__114->GetZaxis()->SetLabelSize(0.035);
   Signal_ppStaumI557_pass_postfit_projy1__114->GetZaxis()->SetTitleSize(0.035);
   Signal_ppStaumI557_pass_postfit_projy1__114->GetZaxis()->SetTitleFont(42);
   Signal_ppStaumI557_pass_postfit_projy1__114->Draw("hist same");
   Double_t xAxis183[2] = {50, 200}; 
   
   TH1D *TotalBkg_pass_postfit_projy1__115 = new TH1D("TotalBkg_pass_postfit_projy1__115","TotalBkg, pass, postfit, 0.24-1.0",1, xAxis183);
   TotalBkg_pass_postfit_projy1__115->SetBinContent(1,1025.981);
   TotalBkg_pass_postfit_projy1__115->SetBinError(1,12.80391);
   TotalBkg_pass_postfit_projy1__115->SetMinimum(0);
   TotalBkg_pass_postfit_projy1__115->SetEntries(6420.868);
   TotalBkg_pass_postfit_projy1__115->SetStats(0);
   TotalBkg_pass_postfit_projy1__115->SetMarkerStyle(0);
   TotalBkg_pass_postfit_projy1__115->GetXaxis()->SetTitle("p_{T}");
   TotalBkg_pass_postfit_projy1__115->GetXaxis()->SetLabelFont(42);
   TotalBkg_pass_postfit_projy1__115->GetXaxis()->SetLabelSize(0.035);
   TotalBkg_pass_postfit_projy1__115->GetXaxis()->SetTitleSize(0.035);
   TotalBkg_pass_postfit_projy1__115->GetXaxis()->SetTitleOffset(0);
   TotalBkg_pass_postfit_projy1__115->GetXaxis()->SetTitleFont(42);
   TotalBkg_pass_postfit_projy1__115->GetYaxis()->SetTitle("Events / bin");
   TotalBkg_pass_postfit_projy1__115->GetYaxis()->SetLabelFont(42);
   TotalBkg_pass_postfit_projy1__115->GetYaxis()->SetLabelSize(0.035);
   TotalBkg_pass_postfit_projy1__115->GetYaxis()->SetTitleSize(0.035);
   TotalBkg_pass_postfit_projy1__115->GetYaxis()->SetTitleOffset(0);
   TotalBkg_pass_postfit_projy1__115->GetYaxis()->SetTitleFont(42);
   TotalBkg_pass_postfit_projy1__115->GetZaxis()->SetLabelFont(42);
   TotalBkg_pass_postfit_projy1__115->GetZaxis()->SetLabelSize(0.035);
   TotalBkg_pass_postfit_projy1__115->GetZaxis()->SetTitleSize(0.035);
   TotalBkg_pass_postfit_projy1__115->GetZaxis()->SetTitleFont(42);
   TotalBkg_pass_postfit_projy1__115->Draw("hist same");
   Double_t xAxis184[2] = {50, 200}; 
   
   TH1D *TotalBkg_pass_postfit_projy1__116 = new TH1D("TotalBkg_pass_postfit_projy1__116","TotalBkg, pass, postfit, 0.24-1.0",1, xAxis184);
   TotalBkg_pass_postfit_projy1__116->SetBinContent(1,1025.981);
   TotalBkg_pass_postfit_projy1__116->SetBinError(1,12.80391);
   TotalBkg_pass_postfit_projy1__116->SetMinimum(0);
   TotalBkg_pass_postfit_projy1__116->SetEntries(6420.868);
   TotalBkg_pass_postfit_projy1__116->SetStats(0);
   TotalBkg_pass_postfit_projy1__116->SetFillColor(1);
   TotalBkg_pass_postfit_projy1__116->SetFillStyle(3354);
   TotalBkg_pass_postfit_projy1__116->SetLineWidth(0);
   TotalBkg_pass_postfit_projy1__116->SetMarkerStyle(0);
   TotalBkg_pass_postfit_projy1__116->GetXaxis()->SetTitle("p_{T}");
   TotalBkg_pass_postfit_projy1__116->GetXaxis()->SetLabelFont(42);
   TotalBkg_pass_postfit_projy1__116->GetXaxis()->SetLabelSize(0.035);
   TotalBkg_pass_postfit_projy1__116->GetXaxis()->SetTitleSize(0.035);
   TotalBkg_pass_postfit_projy1__116->GetXaxis()->SetTitleOffset(0);
   TotalBkg_pass_postfit_projy1__116->GetXaxis()->SetTitleFont(42);
   TotalBkg_pass_postfit_projy1__116->GetYaxis()->SetTitle("Events / bin");
   TotalBkg_pass_postfit_projy1__116->GetYaxis()->SetLabelFont(42);
   TotalBkg_pass_postfit_projy1__116->GetYaxis()->SetLabelSize(0.035);
   TotalBkg_pass_postfit_projy1__116->GetYaxis()->SetTitleSize(0.035);
   TotalBkg_pass_postfit_projy1__116->GetYaxis()->SetTitleOffset(0);
   TotalBkg_pass_postfit_projy1__116->GetYaxis()->SetTitleFont(42);
   TotalBkg_pass_postfit_projy1__116->GetZaxis()->SetLabelFont(42);
   TotalBkg_pass_postfit_projy1__116->GetZaxis()->SetLabelSize(0.035);
   TotalBkg_pass_postfit_projy1__116->GetZaxis()->SetTitleSize(0.035);
   TotalBkg_pass_postfit_projy1__116->GetZaxis()->SetTitleFont(42);
   TotalBkg_pass_postfit_projy1__116->Draw("e2 same");
   Double_t xAxis185[2] = {50, 200}; 
   
   TH1D *data_obs_pass_postfit_projy1__117 = new TH1D("data_obs_pass_postfit_projy1__117","",1, xAxis185);
   data_obs_pass_postfit_projy1__117->SetBinContent(1,990);
   data_obs_pass_postfit_projy1__117->SetBinError(1,31.46427);
   data_obs_pass_postfit_projy1__117->SetMinimum(0);
   data_obs_pass_postfit_projy1__117->SetMaximum(1336.5);
   data_obs_pass_postfit_projy1__117->SetEntries(990);
   data_obs_pass_postfit_projy1__117->SetStats(0);

   ci = TColor::GetColor("#000000");
   data_obs_pass_postfit_projy1__117->SetLineColor(ci);

   ci = TColor::GetColor("#000000");
   data_obs_pass_postfit_projy1__117->SetMarkerColor(ci);
   data_obs_pass_postfit_projy1__117->SetMarkerStyle(8);
   data_obs_pass_postfit_projy1__117->GetXaxis()->SetTitle("p_{T}");
   data_obs_pass_postfit_projy1__117->GetXaxis()->SetLabelFont(42);
   data_obs_pass_postfit_projy1__117->GetXaxis()->SetLabelOffset(0.05);
   data_obs_pass_postfit_projy1__117->GetXaxis()->SetLabelSize(0.07);
   data_obs_pass_postfit_projy1__117->GetXaxis()->SetTitleSize(0.09);
   data_obs_pass_postfit_projy1__117->GetXaxis()->SetTitleOffset(1.15);
   data_obs_pass_postfit_projy1__117->GetXaxis()->SetTitleFont(42);
   data_obs_pass_postfit_projy1__117->GetYaxis()->SetTitle("Events / bin");
   data_obs_pass_postfit_projy1__117->GetYaxis()->SetNdivisions(508);
   data_obs_pass_postfit_projy1__117->GetYaxis()->SetLabelFont(42);
   data_obs_pass_postfit_projy1__117->GetYaxis()->SetLabelSize(0.07);
   data_obs_pass_postfit_projy1__117->GetYaxis()->SetTitleSize(0.09);
   data_obs_pass_postfit_projy1__117->GetYaxis()->SetTitleOffset(0.8);
   data_obs_pass_postfit_projy1__117->GetYaxis()->SetTitleFont(42);
   data_obs_pass_postfit_projy1__117->GetZaxis()->SetLabelFont(42);
   data_obs_pass_postfit_projy1__117->GetZaxis()->SetLabelSize(0.035);
   data_obs_pass_postfit_projy1__117->GetZaxis()->SetTitleSize(0.035);
   data_obs_pass_postfit_projy1__117->GetZaxis()->SetTitleFont(42);
   data_obs_pass_postfit_projy1__117->Draw("pe X0 same");
   
   TLegend *leg = new TLegend(0.65,0.64,0.9,0.88,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(1001);
   TLegendEntry *entry=leg->AddEntry("data_obs_pass_postfit_projy1","Data","pe X0");

   ci = TColor::GetColor("#000000");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);

   ci = TColor::GetColor("#000000");
   entry->SetMarkerColor(ci);
   entry->SetMarkerStyle(8);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("TotalBkg_pass_postfit_projy1","Total bkg unc.","F");
   entry->SetFillColor(1);
   entry->SetFillStyle(3354);
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("Signal_ppStau-557_pass_postfit_projy1","HSCP signal","L");
   entry->SetLineColor(2);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("Background_0x0_pass_postfit_projy1_stack_1_stack_1","Background","f");

   ci = TColor::GetColor("#ffff00");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = 1201;
   color = new TColor(ci, 1, 1, 1, " ", 0);
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   leg->Draw();
   Double_t xAxis186[2] = {50, 200}; 
   
   TH1D *data_obs_pass_postfit_projy1_copy__118 = new TH1D("data_obs_pass_postfit_projy1_copy__118","",1, xAxis186);
   data_obs_pass_postfit_projy1_copy__118->SetBinContent(1,990);
   data_obs_pass_postfit_projy1_copy__118->SetBinError(1,31.46427);
   data_obs_pass_postfit_projy1_copy__118->SetMinimum(0);
   data_obs_pass_postfit_projy1_copy__118->SetMaximum(1336.5);
   data_obs_pass_postfit_projy1_copy__118->SetEntries(990);
   data_obs_pass_postfit_projy1_copy__118->SetDirectory(0);
   data_obs_pass_postfit_projy1_copy__118->SetStats(0);

   ci = TColor::GetColor("#000000");
   data_obs_pass_postfit_projy1_copy__118->SetLineColor(ci);

   ci = TColor::GetColor("#000000");
   data_obs_pass_postfit_projy1_copy__118->SetMarkerColor(ci);
   data_obs_pass_postfit_projy1_copy__118->SetMarkerStyle(8);
   data_obs_pass_postfit_projy1_copy__118->GetXaxis()->SetTitle("p_{T}");
   data_obs_pass_postfit_projy1_copy__118->GetXaxis()->SetLabelFont(42);
   data_obs_pass_postfit_projy1_copy__118->GetXaxis()->SetLabelOffset(0.05);
   data_obs_pass_postfit_projy1_copy__118->GetXaxis()->SetLabelSize(0.07);
   data_obs_pass_postfit_projy1_copy__118->GetXaxis()->SetTitleSize(0.09);
   data_obs_pass_postfit_projy1_copy__118->GetXaxis()->SetTitleOffset(1.15);
   data_obs_pass_postfit_projy1_copy__118->GetXaxis()->SetTitleFont(42);
   data_obs_pass_postfit_projy1_copy__118->GetYaxis()->SetTitle("Events / bin");
   data_obs_pass_postfit_projy1_copy__118->GetYaxis()->SetNdivisions(508);
   data_obs_pass_postfit_projy1_copy__118->GetYaxis()->SetLabelFont(42);
   data_obs_pass_postfit_projy1_copy__118->GetYaxis()->SetLabelSize(0.07);
   data_obs_pass_postfit_projy1_copy__118->GetYaxis()->SetTitleSize(0.09);
   data_obs_pass_postfit_projy1_copy__118->GetYaxis()->SetTitleOffset(0.8);
   data_obs_pass_postfit_projy1_copy__118->GetYaxis()->SetTitleFont(42);
   data_obs_pass_postfit_projy1_copy__118->GetZaxis()->SetLabelFont(42);
   data_obs_pass_postfit_projy1_copy__118->GetZaxis()->SetLabelSize(0.035);
   data_obs_pass_postfit_projy1_copy__118->GetZaxis()->SetTitleSize(0.035);
   data_obs_pass_postfit_projy1_copy__118->GetZaxis()->SetTitleFont(42);
   data_obs_pass_postfit_projy1_copy__118->Draw("sameaxis");
   TLatex *   tex = new TLatex(0.21,0.83,"55 < p_{T} < 200 GeV, F^{Pixels}_{i} > 0.9");
tex->SetNDC();
   tex->SetTextAlign(12);
   tex->SetTextFont(42);
   tex->SetTextSize(0.06);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.17,0.92,"CMS");
tex->SetNDC();
   tex->SetTextFont(61);
   tex->SetTextSize(0.0675);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.25,0.92,"Preliminary");
tex->SetNDC();
   tex->SetTextFont(52);
   tex->SetTextSize(0.0485);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.95,0.92,"101 fb^{-1} (13 TeV)");
tex->SetNDC();
   tex->SetTextAlign(31);
   tex->SetTextFont(42);
   tex->SetTextSize(0.07);
   tex->SetLineWidth(2);
   tex->Draw();
   data_obs_pass_postfit_projy1_main->Modified();
   plots_fit_b/base_figs/postfit_projy1_pass->cd();
  
// ------------>Primitives in pad: data_obs_pass_postfit_projy1_sub
   TPad *data_obs_pass_postfit_projy1_sub = new TPad("data_obs_pass_postfit_projy1_sub", "data_obs_pass_postfit_projy1_sub",0,0,1,0.35);
   data_obs_pass_postfit_projy1_sub->Draw();
   data_obs_pass_postfit_projy1_sub->cd();
   data_obs_pass_postfit_projy1_sub->Range(17.30769,-6.023077,209.6154,2.9);
   data_obs_pass_postfit_projy1_sub->SetFillColor(0);
   data_obs_pass_postfit_projy1_sub->SetBorderMode(0);
   data_obs_pass_postfit_projy1_sub->SetBorderSize(2);
   data_obs_pass_postfit_projy1_sub->SetTickx(1);
   data_obs_pass_postfit_projy1_sub->SetTicky(1);
   data_obs_pass_postfit_projy1_sub->SetLeftMargin(0.17);
   data_obs_pass_postfit_projy1_sub->SetRightMargin(0.05);
   data_obs_pass_postfit_projy1_sub->SetTopMargin(0);
   data_obs_pass_postfit_projy1_sub->SetBottomMargin(0.35);
   data_obs_pass_postfit_projy1_sub->SetFrameFillStyle(0);
   data_obs_pass_postfit_projy1_sub->SetFrameBorderMode(0);
   data_obs_pass_postfit_projy1_sub->SetFrameFillStyle(0);
   data_obs_pass_postfit_projy1_sub->SetFrameBorderMode(0);
   Double_t xAxis187[2] = {50, 200}; 
   
   TH1D *data_obs_pass_postfit_projy1_pull__119 = new TH1D("data_obs_pass_postfit_projy1_pull__119","",1, xAxis187);
   data_obs_pass_postfit_projy1_pull__119->SetBinContent(1,-1.030742);
   data_obs_pass_postfit_projy1_pull__119->SetBinError(1,33.96969);
   data_obs_pass_postfit_projy1_pull__119->SetMinimum(-2.9);
   data_obs_pass_postfit_projy1_pull__119->SetMaximum(2.9);
   data_obs_pass_postfit_projy1_pull__119->SetEntries(36.98099);
   data_obs_pass_postfit_projy1_pull__119->SetStats(0);

   ci = TColor::GetColor("#0000ff");
   data_obs_pass_postfit_projy1_pull__119->SetFillColor(ci);

   ci = TColor::GetColor("#000000");
   data_obs_pass_postfit_projy1_pull__119->SetLineColor(ci);

   ci = TColor::GetColor("#000000");
   data_obs_pass_postfit_projy1_pull__119->SetMarkerColor(ci);
   data_obs_pass_postfit_projy1_pull__119->SetMarkerStyle(8);
   data_obs_pass_postfit_projy1_pull__119->GetXaxis()->SetTitle("p_{T}");
   data_obs_pass_postfit_projy1_pull__119->GetXaxis()->SetLabelFont(42);
   data_obs_pass_postfit_projy1_pull__119->GetXaxis()->SetLabelOffset(0.05);
   data_obs_pass_postfit_projy1_pull__119->GetXaxis()->SetLabelSize(0.13);
   data_obs_pass_postfit_projy1_pull__119->GetXaxis()->SetTitleSize(0.15);
   data_obs_pass_postfit_projy1_pull__119->GetXaxis()->SetTitleOffset(1.15);
   data_obs_pass_postfit_projy1_pull__119->GetXaxis()->SetTitleFont(42);
   data_obs_pass_postfit_projy1_pull__119->GetYaxis()->SetTitle("(Data-Bkg)/#sigma");
   data_obs_pass_postfit_projy1_pull__119->GetYaxis()->SetNdivisions(306);
   data_obs_pass_postfit_projy1_pull__119->GetYaxis()->SetLabelFont(42);
   data_obs_pass_postfit_projy1_pull__119->GetYaxis()->SetLabelSize(0.13);
   data_obs_pass_postfit_projy1_pull__119->GetYaxis()->SetTitleSize(0.12);
   data_obs_pass_postfit_projy1_pull__119->GetYaxis()->SetTitleOffset(0.4);
   data_obs_pass_postfit_projy1_pull__119->GetYaxis()->SetTitleFont(42);
   data_obs_pass_postfit_projy1_pull__119->GetZaxis()->SetLabelFont(42);
   data_obs_pass_postfit_projy1_pull__119->GetZaxis()->SetLabelSize(0.035);
   data_obs_pass_postfit_projy1_pull__119->GetZaxis()->SetTitleSize(0.035);
   data_obs_pass_postfit_projy1_pull__119->GetZaxis()->SetTitleFont(42);
   data_obs_pass_postfit_projy1_pull__119->Draw("hist");
   data_obs_pass_postfit_projy1_sub->Modified();
   plots_fit_b/base_figs/postfit_projy1_pass->cd();
   plots_fit_b/base_figs/postfit_projy1_pass->Modified();
   plots_fit_b/base_figs/postfit_projy1_pass->cd();
   plots_fit_b/base_figs/postfit_projy1_pass->SetSelected(plots_fit_b/base_figs/postfit_projy1_pass);
}
