void postfit_projy1_fail()
{
//=========Macro generated from canvas: plots_fit_b/base_figs/postfit_projy1_fail/plots_fit_b/base_figs/postfit_projy1_fail
//=========  (Fri Jan 12 21:00:01 2024) by ROOT version 6.14/09
   TCanvas *plots_fit_b/base_figs/postfit_projy1_fail = new TCanvas("plots_fit_b/base_figs/postfit_projy1_fail", "plots_fit_b/base_figs/postfit_projy1_fail",0,0,800,700);
   gStyle->SetOptFit(1);
   gStyle->SetOptStat(0);
   plots_fit_b/base_figs/postfit_projy1_fail->SetHighLightColor(2);
   plots_fit_b/base_figs/postfit_projy1_fail->Range(0,0,1,1);
   plots_fit_b/base_figs/postfit_projy1_fail->SetFillColor(0);
   plots_fit_b/base_figs/postfit_projy1_fail->SetBorderMode(0);
   plots_fit_b/base_figs/postfit_projy1_fail->SetBorderSize(2);
   plots_fit_b/base_figs/postfit_projy1_fail->SetTickx(1);
   plots_fit_b/base_figs/postfit_projy1_fail->SetTicky(1);
   plots_fit_b/base_figs/postfit_projy1_fail->SetLeftMargin(0.16);
   plots_fit_b/base_figs/postfit_projy1_fail->SetRightMargin(0);
   plots_fit_b/base_figs/postfit_projy1_fail->SetTopMargin(0);
   plots_fit_b/base_figs/postfit_projy1_fail->SetBottomMargin(0);
   plots_fit_b/base_figs/postfit_projy1_fail->SetFrameFillStyle(0);
   plots_fit_b/base_figs/postfit_projy1_fail->SetFrameBorderMode(0);
  
// ------------>Primitives in pad: data_obs_fail_postfit_projy1_main
   TPad *data_obs_fail_postfit_projy1_main = new TPad("data_obs_fail_postfit_projy1_main", "data_obs_fail_postfit_projy1_main",0,0.35,1,1);
   data_obs_fail_postfit_projy1_main->Draw();
   data_obs_fail_postfit_projy1_main->cd();
   data_obs_fail_postfit_projy1_main->Range(17.30769,-392.0651,209.6154,9409.562);
   data_obs_fail_postfit_projy1_main->SetFillColor(0);
   data_obs_fail_postfit_projy1_main->SetBorderMode(0);
   data_obs_fail_postfit_projy1_main->SetBorderSize(2);
   data_obs_fail_postfit_projy1_main->SetTickx(1);
   data_obs_fail_postfit_projy1_main->SetTicky(1);
   data_obs_fail_postfit_projy1_main->SetLeftMargin(0.17);
   data_obs_fail_postfit_projy1_main->SetRightMargin(0.05);
   data_obs_fail_postfit_projy1_main->SetBottomMargin(0.04);
   data_obs_fail_postfit_projy1_main->SetFrameFillStyle(0);
   data_obs_fail_postfit_projy1_main->SetFrameBorderMode(0);
   data_obs_fail_postfit_projy1_main->SetFrameFillStyle(0);
   data_obs_fail_postfit_projy1_main->SetFrameBorderMode(0);
   Double_t xAxis45[2] = {50, 200}; 
   
   TH1D *data_obs_fail_postfit_projy1__29 = new TH1D("data_obs_fail_postfit_projy1__29","",1, xAxis45);
   data_obs_fail_postfit_projy1__29->SetBinContent(1,6244);
   data_obs_fail_postfit_projy1__29->SetBinError(1,79.01899);
   data_obs_fail_postfit_projy1__29->SetMinimum(0);
   data_obs_fail_postfit_projy1__29->SetMaximum(8429.4);
   data_obs_fail_postfit_projy1__29->SetEntries(6244);
   data_obs_fail_postfit_projy1__29->SetStats(0);

   Int_t ci;      // for color index setting
   TColor *color; // for color definition with alpha
   ci = TColor::GetColor("#000000");
   data_obs_fail_postfit_projy1__29->SetLineColor(ci);

   ci = TColor::GetColor("#000000");
   data_obs_fail_postfit_projy1__29->SetMarkerColor(ci);
   data_obs_fail_postfit_projy1__29->SetMarkerStyle(8);
   data_obs_fail_postfit_projy1__29->GetXaxis()->SetTitle("p_{T}");
   data_obs_fail_postfit_projy1__29->GetXaxis()->SetLabelFont(42);
   data_obs_fail_postfit_projy1__29->GetXaxis()->SetLabelOffset(0.05);
   data_obs_fail_postfit_projy1__29->GetXaxis()->SetLabelSize(0.07);
   data_obs_fail_postfit_projy1__29->GetXaxis()->SetTitleSize(0.09);
   data_obs_fail_postfit_projy1__29->GetXaxis()->SetTitleOffset(1.15);
   data_obs_fail_postfit_projy1__29->GetXaxis()->SetTitleFont(42);
   data_obs_fail_postfit_projy1__29->GetYaxis()->SetTitle("Events / bin");
   data_obs_fail_postfit_projy1__29->GetYaxis()->SetNdivisions(508);
   data_obs_fail_postfit_projy1__29->GetYaxis()->SetLabelFont(42);
   data_obs_fail_postfit_projy1__29->GetYaxis()->SetLabelSize(0.07);
   data_obs_fail_postfit_projy1__29->GetYaxis()->SetTitleSize(0.09);
   data_obs_fail_postfit_projy1__29->GetYaxis()->SetTitleOffset(0.8);
   data_obs_fail_postfit_projy1__29->GetYaxis()->SetTitleFont(42);
   data_obs_fail_postfit_projy1__29->GetZaxis()->SetLabelFont(42);
   data_obs_fail_postfit_projy1__29->GetZaxis()->SetLabelSize(0.035);
   data_obs_fail_postfit_projy1__29->GetZaxis()->SetTitleSize(0.035);
   data_obs_fail_postfit_projy1__29->GetZaxis()->SetTitleFont(42);
   data_obs_fail_postfit_projy1__29->Draw("pe X0");
   
   THStack *postfit_projy1_fail_stack = new THStack();
   postfit_projy1_fail_stack->SetName("postfit_projy1_fail_stack");
   postfit_projy1_fail_stack->SetTitle("postfit_projy1_fail_stack");
   Double_t xAxis46[2] = {50, 200}; 
   
   TH1F *postfit_projy1_fail_stack_stack_9 = new TH1F("postfit_projy1_fail_stack_stack_9","postfit_projy1_fail_stack",1, xAxis46);
   postfit_projy1_fail_stack_stack_9->SetMinimum(0);
   postfit_projy1_fail_stack_stack_9->SetMaximum(6590.552);
   postfit_projy1_fail_stack_stack_9->SetDirectory(0);
   postfit_projy1_fail_stack_stack_9->SetStats(0);
   postfit_projy1_fail_stack_stack_9->SetLineStyle(0);
   postfit_projy1_fail_stack_stack_9->GetXaxis()->SetLabelFont(42);
   postfit_projy1_fail_stack_stack_9->GetXaxis()->SetLabelOffset(0.007);
   postfit_projy1_fail_stack_stack_9->GetXaxis()->SetLabelSize(0.05);
   postfit_projy1_fail_stack_stack_9->GetXaxis()->SetTitleSize(0.08);
   postfit_projy1_fail_stack_stack_9->GetXaxis()->SetTitleOffset(0.9);
   postfit_projy1_fail_stack_stack_9->GetXaxis()->SetTitleFont(42);
   postfit_projy1_fail_stack_stack_9->GetYaxis()->SetNdivisions(508);
   postfit_projy1_fail_stack_stack_9->GetYaxis()->SetLabelFont(42);
   postfit_projy1_fail_stack_stack_9->GetYaxis()->SetLabelOffset(0.007);
   postfit_projy1_fail_stack_stack_9->GetYaxis()->SetLabelSize(0.05);
   postfit_projy1_fail_stack_stack_9->GetYaxis()->SetTitleSize(0.08);
   postfit_projy1_fail_stack_stack_9->GetYaxis()->SetTitleOffset(1.25);
   postfit_projy1_fail_stack_stack_9->GetYaxis()->SetTitleFont(42);
   postfit_projy1_fail_stack_stack_9->GetZaxis()->SetLabelFont(42);
   postfit_projy1_fail_stack_stack_9->GetZaxis()->SetLabelOffset(0.007);
   postfit_projy1_fail_stack_stack_9->GetZaxis()->SetLabelSize(0.05);
   postfit_projy1_fail_stack_stack_9->GetZaxis()->SetTitleSize(0.08);
   postfit_projy1_fail_stack_stack_9->GetZaxis()->SetTitleFont(42);
   postfit_projy1_fail_stack->SetHistogram(postfit_projy1_fail_stack_stack_9);
   
   Double_t xAxis47[2] = {50, 200}; 
   
   TH1D *Background_fail_postfit_projy1_stack_1 = new TH1D("Background_fail_postfit_projy1_stack_1","Background, fail, postfit, 0.24-1.0",1, xAxis47);
   Background_fail_postfit_projy1_stack_1->SetBinContent(1,6208.019);
   Background_fail_postfit_projy1_stack_1->SetBinError(1,68.6972);
   Background_fail_postfit_projy1_stack_1->SetMinimum(0);
   Background_fail_postfit_projy1_stack_1->SetEntries(8166.349);
   Background_fail_postfit_projy1_stack_1->SetStats(0);

   ci = TColor::GetColor("#ffff00");
   Background_fail_postfit_projy1_stack_1->SetFillColor(ci);

   ci = 1189;
   color = new TColor(ci, 1, 1, 1, " ", 0);
   Background_fail_postfit_projy1_stack_1->SetLineColor(ci);
   Background_fail_postfit_projy1_stack_1->GetXaxis()->SetTitle("p_{T}");
   Background_fail_postfit_projy1_stack_1->GetXaxis()->SetLabelFont(42);
   Background_fail_postfit_projy1_stack_1->GetXaxis()->SetLabelSize(0.035);
   Background_fail_postfit_projy1_stack_1->GetXaxis()->SetTitleSize(0.035);
   Background_fail_postfit_projy1_stack_1->GetXaxis()->SetTitleOffset(0);
   Background_fail_postfit_projy1_stack_1->GetXaxis()->SetTitleFont(42);
   Background_fail_postfit_projy1_stack_1->GetYaxis()->SetTitle("Events / bin");
   Background_fail_postfit_projy1_stack_1->GetYaxis()->SetLabelFont(42);
   Background_fail_postfit_projy1_stack_1->GetYaxis()->SetLabelSize(0.035);
   Background_fail_postfit_projy1_stack_1->GetYaxis()->SetTitleSize(0.035);
   Background_fail_postfit_projy1_stack_1->GetYaxis()->SetTitleOffset(0);
   Background_fail_postfit_projy1_stack_1->GetYaxis()->SetTitleFont(42);
   Background_fail_postfit_projy1_stack_1->GetZaxis()->SetLabelFont(42);
   Background_fail_postfit_projy1_stack_1->GetZaxis()->SetLabelSize(0.035);
   Background_fail_postfit_projy1_stack_1->GetZaxis()->SetTitleSize(0.035);
   Background_fail_postfit_projy1_stack_1->GetZaxis()->SetTitleFont(42);
   postfit_projy1_fail_stack->Add(Background_fail_postfit_projy1_stack_1,"");
   postfit_projy1_fail_stack->Draw("hist same");
   
   postfit_projy1_fail_stack = new THStack();
   postfit_projy1_fail_stack->SetName("postfit_projy1_fail_stack");
   postfit_projy1_fail_stack->SetTitle("postfit_projy1_fail_stack");
   Double_t xAxis48[2] = {50, 200}; 
   
   TH1F *postfit_projy1_fail_stack_stack_9_stack_10 = new TH1F("postfit_projy1_fail_stack_stack_9_stack_10","postfit_projy1_fail_stack",1, xAxis48);
   postfit_projy1_fail_stack_stack_9_stack_10->SetMinimum(0);
   postfit_projy1_fail_stack_stack_9_stack_10->SetMaximum(6590.552);
   postfit_projy1_fail_stack_stack_9_stack_10->SetDirectory(0);
   postfit_projy1_fail_stack_stack_9_stack_10->SetStats(0);
   postfit_projy1_fail_stack_stack_9_stack_10->SetLineStyle(0);
   postfit_projy1_fail_stack_stack_9_stack_10->GetXaxis()->SetLabelFont(42);
   postfit_projy1_fail_stack_stack_9_stack_10->GetXaxis()->SetLabelOffset(0.007);
   postfit_projy1_fail_stack_stack_9_stack_10->GetXaxis()->SetLabelSize(0.05);
   postfit_projy1_fail_stack_stack_9_stack_10->GetXaxis()->SetTitleSize(0.08);
   postfit_projy1_fail_stack_stack_9_stack_10->GetXaxis()->SetTitleOffset(0.9);
   postfit_projy1_fail_stack_stack_9_stack_10->GetXaxis()->SetTitleFont(42);
   postfit_projy1_fail_stack_stack_9_stack_10->GetYaxis()->SetNdivisions(508);
   postfit_projy1_fail_stack_stack_9_stack_10->GetYaxis()->SetLabelFont(42);
   postfit_projy1_fail_stack_stack_9_stack_10->GetYaxis()->SetLabelOffset(0.007);
   postfit_projy1_fail_stack_stack_9_stack_10->GetYaxis()->SetLabelSize(0.05);
   postfit_projy1_fail_stack_stack_9_stack_10->GetYaxis()->SetTitleSize(0.08);
   postfit_projy1_fail_stack_stack_9_stack_10->GetYaxis()->SetTitleOffset(1.25);
   postfit_projy1_fail_stack_stack_9_stack_10->GetYaxis()->SetTitleFont(42);
   postfit_projy1_fail_stack_stack_9_stack_10->GetZaxis()->SetLabelFont(42);
   postfit_projy1_fail_stack_stack_9_stack_10->GetZaxis()->SetLabelOffset(0.007);
   postfit_projy1_fail_stack_stack_9_stack_10->GetZaxis()->SetLabelSize(0.05);
   postfit_projy1_fail_stack_stack_9_stack_10->GetZaxis()->SetTitleSize(0.08);
   postfit_projy1_fail_stack_stack_9_stack_10->GetZaxis()->SetTitleFont(42);
   postfit_projy1_fail_stack->SetHistogram(postfit_projy1_fail_stack_stack_9_stack_10);
   
   Double_t xAxis49[2] = {50, 200}; 
   
   TH1D *Background_fail_postfit_projy1_stack_1_stack_1 = new TH1D("Background_fail_postfit_projy1_stack_1_stack_1","Background, fail, postfit, 0.24-1.0",1, xAxis49);
   Background_fail_postfit_projy1_stack_1_stack_1->SetBinContent(1,6208.019);
   Background_fail_postfit_projy1_stack_1_stack_1->SetBinError(1,68.6972);
   Background_fail_postfit_projy1_stack_1_stack_1->SetMinimum(0);
   Background_fail_postfit_projy1_stack_1_stack_1->SetEntries(8166.349);
   Background_fail_postfit_projy1_stack_1_stack_1->SetStats(0);

   ci = TColor::GetColor("#ffff00");
   Background_fail_postfit_projy1_stack_1_stack_1->SetFillColor(ci);

   ci = 1189;
   color = new TColor(ci, 1, 1, 1, " ", 0);
   Background_fail_postfit_projy1_stack_1_stack_1->SetLineColor(ci);
   Background_fail_postfit_projy1_stack_1_stack_1->GetXaxis()->SetTitle("p_{T}");
   Background_fail_postfit_projy1_stack_1_stack_1->GetXaxis()->SetLabelFont(42);
   Background_fail_postfit_projy1_stack_1_stack_1->GetXaxis()->SetLabelSize(0.035);
   Background_fail_postfit_projy1_stack_1_stack_1->GetXaxis()->SetTitleSize(0.035);
   Background_fail_postfit_projy1_stack_1_stack_1->GetXaxis()->SetTitleOffset(0);
   Background_fail_postfit_projy1_stack_1_stack_1->GetXaxis()->SetTitleFont(42);
   Background_fail_postfit_projy1_stack_1_stack_1->GetYaxis()->SetTitle("Events / bin");
   Background_fail_postfit_projy1_stack_1_stack_1->GetYaxis()->SetLabelFont(42);
   Background_fail_postfit_projy1_stack_1_stack_1->GetYaxis()->SetLabelSize(0.035);
   Background_fail_postfit_projy1_stack_1_stack_1->GetYaxis()->SetTitleSize(0.035);
   Background_fail_postfit_projy1_stack_1_stack_1->GetYaxis()->SetTitleOffset(0);
   Background_fail_postfit_projy1_stack_1_stack_1->GetYaxis()->SetTitleFont(42);
   Background_fail_postfit_projy1_stack_1_stack_1->GetZaxis()->SetLabelFont(42);
   Background_fail_postfit_projy1_stack_1_stack_1->GetZaxis()->SetLabelSize(0.035);
   Background_fail_postfit_projy1_stack_1_stack_1->GetZaxis()->SetTitleSize(0.035);
   Background_fail_postfit_projy1_stack_1_stack_1->GetZaxis()->SetTitleFont(42);
   postfit_projy1_fail_stack->Add(Background_fail_postfit_projy1_stack_1_stack_1,"");
   postfit_projy1_fail_stack->Draw("hist same");
   Double_t xAxis50[2] = {50, 200}; 
   
   TH1D *Signal_ppStaumI557_fail_postfit_projy1__30 = new TH1D("Signal_ppStaumI557_fail_postfit_projy1__30","HSCP signal, fail, postfit, 0.24-1.0",1, xAxis50);
   Signal_ppStaumI557_fail_postfit_projy1__30->SetBinContent(1,4.56e-05);
   Signal_ppStaumI557_fail_postfit_projy1__30->SetBinError(1,6.71163e-07);
   Signal_ppStaumI557_fail_postfit_projy1__30->SetMinimum(0);
   Signal_ppStaumI557_fail_postfit_projy1__30->SetEntries(4616.084);
   Signal_ppStaumI557_fail_postfit_projy1__30->SetStats(0);
   Signal_ppStaumI557_fail_postfit_projy1__30->SetLineColor(2);
   Signal_ppStaumI557_fail_postfit_projy1__30->GetXaxis()->SetTitle("p_{T}");
   Signal_ppStaumI557_fail_postfit_projy1__30->GetXaxis()->SetLabelFont(42);
   Signal_ppStaumI557_fail_postfit_projy1__30->GetXaxis()->SetLabelSize(0.035);
   Signal_ppStaumI557_fail_postfit_projy1__30->GetXaxis()->SetTitleSize(0.035);
   Signal_ppStaumI557_fail_postfit_projy1__30->GetXaxis()->SetTitleOffset(0);
   Signal_ppStaumI557_fail_postfit_projy1__30->GetXaxis()->SetTitleFont(42);
   Signal_ppStaumI557_fail_postfit_projy1__30->GetYaxis()->SetTitle("Events / bin");
   Signal_ppStaumI557_fail_postfit_projy1__30->GetYaxis()->SetLabelFont(42);
   Signal_ppStaumI557_fail_postfit_projy1__30->GetYaxis()->SetLabelSize(0.035);
   Signal_ppStaumI557_fail_postfit_projy1__30->GetYaxis()->SetTitleSize(0.035);
   Signal_ppStaumI557_fail_postfit_projy1__30->GetYaxis()->SetTitleOffset(0);
   Signal_ppStaumI557_fail_postfit_projy1__30->GetYaxis()->SetTitleFont(42);
   Signal_ppStaumI557_fail_postfit_projy1__30->GetZaxis()->SetLabelFont(42);
   Signal_ppStaumI557_fail_postfit_projy1__30->GetZaxis()->SetLabelSize(0.035);
   Signal_ppStaumI557_fail_postfit_projy1__30->GetZaxis()->SetTitleSize(0.035);
   Signal_ppStaumI557_fail_postfit_projy1__30->GetZaxis()->SetTitleFont(42);
   Signal_ppStaumI557_fail_postfit_projy1__30->Draw("hist same");
   Double_t xAxis51[2] = {50, 200}; 
   
   TH1D *TotalBkg_fail_postfit_projy1__31 = new TH1D("TotalBkg_fail_postfit_projy1__31","TotalBkg, fail, postfit, 0.24-1.0",1, xAxis51);
   TotalBkg_fail_postfit_projy1__31->SetBinContent(1,6208.019);
   TotalBkg_fail_postfit_projy1__31->SetBinError(1,75.02896);
   TotalBkg_fail_postfit_projy1__31->SetMinimum(0);
   TotalBkg_fail_postfit_projy1__31->SetEntries(6846.179);
   TotalBkg_fail_postfit_projy1__31->SetStats(0);
   TotalBkg_fail_postfit_projy1__31->SetMarkerStyle(0);
   TotalBkg_fail_postfit_projy1__31->GetXaxis()->SetTitle("p_{T}");
   TotalBkg_fail_postfit_projy1__31->GetXaxis()->SetLabelFont(42);
   TotalBkg_fail_postfit_projy1__31->GetXaxis()->SetLabelSize(0.035);
   TotalBkg_fail_postfit_projy1__31->GetXaxis()->SetTitleSize(0.035);
   TotalBkg_fail_postfit_projy1__31->GetXaxis()->SetTitleOffset(0);
   TotalBkg_fail_postfit_projy1__31->GetXaxis()->SetTitleFont(42);
   TotalBkg_fail_postfit_projy1__31->GetYaxis()->SetTitle("Events / bin");
   TotalBkg_fail_postfit_projy1__31->GetYaxis()->SetLabelFont(42);
   TotalBkg_fail_postfit_projy1__31->GetYaxis()->SetLabelSize(0.035);
   TotalBkg_fail_postfit_projy1__31->GetYaxis()->SetTitleSize(0.035);
   TotalBkg_fail_postfit_projy1__31->GetYaxis()->SetTitleOffset(0);
   TotalBkg_fail_postfit_projy1__31->GetYaxis()->SetTitleFont(42);
   TotalBkg_fail_postfit_projy1__31->GetZaxis()->SetLabelFont(42);
   TotalBkg_fail_postfit_projy1__31->GetZaxis()->SetLabelSize(0.035);
   TotalBkg_fail_postfit_projy1__31->GetZaxis()->SetTitleSize(0.035);
   TotalBkg_fail_postfit_projy1__31->GetZaxis()->SetTitleFont(42);
   TotalBkg_fail_postfit_projy1__31->Draw("hist same");
   Double_t xAxis52[2] = {50, 200}; 
   
   TH1D *TotalBkg_fail_postfit_projy1__32 = new TH1D("TotalBkg_fail_postfit_projy1__32","TotalBkg, fail, postfit, 0.24-1.0",1, xAxis52);
   TotalBkg_fail_postfit_projy1__32->SetBinContent(1,6208.019);
   TotalBkg_fail_postfit_projy1__32->SetBinError(1,75.02896);
   TotalBkg_fail_postfit_projy1__32->SetMinimum(0);
   TotalBkg_fail_postfit_projy1__32->SetEntries(6846.179);
   TotalBkg_fail_postfit_projy1__32->SetStats(0);
   TotalBkg_fail_postfit_projy1__32->SetFillColor(1);
   TotalBkg_fail_postfit_projy1__32->SetFillStyle(3354);
   TotalBkg_fail_postfit_projy1__32->SetLineWidth(0);
   TotalBkg_fail_postfit_projy1__32->SetMarkerStyle(0);
   TotalBkg_fail_postfit_projy1__32->GetXaxis()->SetTitle("p_{T}");
   TotalBkg_fail_postfit_projy1__32->GetXaxis()->SetLabelFont(42);
   TotalBkg_fail_postfit_projy1__32->GetXaxis()->SetLabelSize(0.035);
   TotalBkg_fail_postfit_projy1__32->GetXaxis()->SetTitleSize(0.035);
   TotalBkg_fail_postfit_projy1__32->GetXaxis()->SetTitleOffset(0);
   TotalBkg_fail_postfit_projy1__32->GetXaxis()->SetTitleFont(42);
   TotalBkg_fail_postfit_projy1__32->GetYaxis()->SetTitle("Events / bin");
   TotalBkg_fail_postfit_projy1__32->GetYaxis()->SetLabelFont(42);
   TotalBkg_fail_postfit_projy1__32->GetYaxis()->SetLabelSize(0.035);
   TotalBkg_fail_postfit_projy1__32->GetYaxis()->SetTitleSize(0.035);
   TotalBkg_fail_postfit_projy1__32->GetYaxis()->SetTitleOffset(0);
   TotalBkg_fail_postfit_projy1__32->GetYaxis()->SetTitleFont(42);
   TotalBkg_fail_postfit_projy1__32->GetZaxis()->SetLabelFont(42);
   TotalBkg_fail_postfit_projy1__32->GetZaxis()->SetLabelSize(0.035);
   TotalBkg_fail_postfit_projy1__32->GetZaxis()->SetTitleSize(0.035);
   TotalBkg_fail_postfit_projy1__32->GetZaxis()->SetTitleFont(42);
   TotalBkg_fail_postfit_projy1__32->Draw("e2 same");
   Double_t xAxis53[2] = {50, 200}; 
   
   TH1D *data_obs_fail_postfit_projy1__33 = new TH1D("data_obs_fail_postfit_projy1__33","",1, xAxis53);
   data_obs_fail_postfit_projy1__33->SetBinContent(1,6244);
   data_obs_fail_postfit_projy1__33->SetBinError(1,79.01899);
   data_obs_fail_postfit_projy1__33->SetMinimum(0);
   data_obs_fail_postfit_projy1__33->SetMaximum(8429.4);
   data_obs_fail_postfit_projy1__33->SetEntries(6244);
   data_obs_fail_postfit_projy1__33->SetStats(0);

   ci = TColor::GetColor("#000000");
   data_obs_fail_postfit_projy1__33->SetLineColor(ci);

   ci = TColor::GetColor("#000000");
   data_obs_fail_postfit_projy1__33->SetMarkerColor(ci);
   data_obs_fail_postfit_projy1__33->SetMarkerStyle(8);
   data_obs_fail_postfit_projy1__33->GetXaxis()->SetTitle("p_{T}");
   data_obs_fail_postfit_projy1__33->GetXaxis()->SetLabelFont(42);
   data_obs_fail_postfit_projy1__33->GetXaxis()->SetLabelOffset(0.05);
   data_obs_fail_postfit_projy1__33->GetXaxis()->SetLabelSize(0.07);
   data_obs_fail_postfit_projy1__33->GetXaxis()->SetTitleSize(0.09);
   data_obs_fail_postfit_projy1__33->GetXaxis()->SetTitleOffset(1.15);
   data_obs_fail_postfit_projy1__33->GetXaxis()->SetTitleFont(42);
   data_obs_fail_postfit_projy1__33->GetYaxis()->SetTitle("Events / bin");
   data_obs_fail_postfit_projy1__33->GetYaxis()->SetNdivisions(508);
   data_obs_fail_postfit_projy1__33->GetYaxis()->SetLabelFont(42);
   data_obs_fail_postfit_projy1__33->GetYaxis()->SetLabelSize(0.07);
   data_obs_fail_postfit_projy1__33->GetYaxis()->SetTitleSize(0.09);
   data_obs_fail_postfit_projy1__33->GetYaxis()->SetTitleOffset(0.8);
   data_obs_fail_postfit_projy1__33->GetYaxis()->SetTitleFont(42);
   data_obs_fail_postfit_projy1__33->GetZaxis()->SetLabelFont(42);
   data_obs_fail_postfit_projy1__33->GetZaxis()->SetLabelSize(0.035);
   data_obs_fail_postfit_projy1__33->GetZaxis()->SetTitleSize(0.035);
   data_obs_fail_postfit_projy1__33->GetZaxis()->SetTitleFont(42);
   data_obs_fail_postfit_projy1__33->Draw("pe X0 same");
   
   TLegend *leg = new TLegend(0.65,0.64,0.9,0.88,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(1001);
   TLegendEntry *entry=leg->AddEntry("data_obs_fail_postfit_projy1","Data","pe X0");

   ci = TColor::GetColor("#000000");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);

   ci = TColor::GetColor("#000000");
   entry->SetMarkerColor(ci);
   entry->SetMarkerStyle(8);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("TotalBkg_fail_postfit_projy1","Total bkg unc.","F");
   entry->SetFillColor(1);
   entry->SetFillStyle(3354);
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("Signal_ppStau-557_fail_postfit_projy1","HSCP signal","L");
   entry->SetLineColor(2);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("Background_fail_postfit_projy1_stack_1_stack_1","Background","f");

   ci = TColor::GetColor("#ffff00");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = 1189;
   color = new TColor(ci, 1, 1, 1, " ", 0);
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   leg->Draw();
   Double_t xAxis54[2] = {50, 200}; 
   
   TH1D *data_obs_fail_postfit_projy1_copy__34 = new TH1D("data_obs_fail_postfit_projy1_copy__34","",1, xAxis54);
   data_obs_fail_postfit_projy1_copy__34->SetBinContent(1,6244);
   data_obs_fail_postfit_projy1_copy__34->SetBinError(1,79.01899);
   data_obs_fail_postfit_projy1_copy__34->SetMinimum(0);
   data_obs_fail_postfit_projy1_copy__34->SetMaximum(8429.4);
   data_obs_fail_postfit_projy1_copy__34->SetEntries(6244);
   data_obs_fail_postfit_projy1_copy__34->SetDirectory(0);
   data_obs_fail_postfit_projy1_copy__34->SetStats(0);

   ci = TColor::GetColor("#000000");
   data_obs_fail_postfit_projy1_copy__34->SetLineColor(ci);

   ci = TColor::GetColor("#000000");
   data_obs_fail_postfit_projy1_copy__34->SetMarkerColor(ci);
   data_obs_fail_postfit_projy1_copy__34->SetMarkerStyle(8);
   data_obs_fail_postfit_projy1_copy__34->GetXaxis()->SetTitle("p_{T}");
   data_obs_fail_postfit_projy1_copy__34->GetXaxis()->SetLabelFont(42);
   data_obs_fail_postfit_projy1_copy__34->GetXaxis()->SetLabelOffset(0.05);
   data_obs_fail_postfit_projy1_copy__34->GetXaxis()->SetLabelSize(0.07);
   data_obs_fail_postfit_projy1_copy__34->GetXaxis()->SetTitleSize(0.09);
   data_obs_fail_postfit_projy1_copy__34->GetXaxis()->SetTitleOffset(1.15);
   data_obs_fail_postfit_projy1_copy__34->GetXaxis()->SetTitleFont(42);
   data_obs_fail_postfit_projy1_copy__34->GetYaxis()->SetTitle("Events / bin");
   data_obs_fail_postfit_projy1_copy__34->GetYaxis()->SetNdivisions(508);
   data_obs_fail_postfit_projy1_copy__34->GetYaxis()->SetLabelFont(42);
   data_obs_fail_postfit_projy1_copy__34->GetYaxis()->SetLabelSize(0.07);
   data_obs_fail_postfit_projy1_copy__34->GetYaxis()->SetTitleSize(0.09);
   data_obs_fail_postfit_projy1_copy__34->GetYaxis()->SetTitleOffset(0.8);
   data_obs_fail_postfit_projy1_copy__34->GetYaxis()->SetTitleFont(42);
   data_obs_fail_postfit_projy1_copy__34->GetZaxis()->SetLabelFont(42);
   data_obs_fail_postfit_projy1_copy__34->GetZaxis()->SetLabelSize(0.035);
   data_obs_fail_postfit_projy1_copy__34->GetZaxis()->SetTitleSize(0.035);
   data_obs_fail_postfit_projy1_copy__34->GetZaxis()->SetTitleFont(42);
   data_obs_fail_postfit_projy1_copy__34->Draw("sameaxis");
   TLatex *   tex = new TLatex(0.21,0.83,"55 < p_{T} < 200 GeV, F^{Pixels}_{i} < 0.9");
tex->SetNDC();
   tex->SetTextAlign(12);
   tex->SetTextFont(42);
   tex->SetTextSize(0.06);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.17,0.92,"CMS");
tex->SetNDC();
   tex->SetTextFont(61);
   tex->SetTextSize(0.0675);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.25,0.92,"Preliminary");
tex->SetNDC();
   tex->SetTextFont(52);
   tex->SetTextSize(0.0485);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.95,0.92,"101 fb^{-1} (13 TeV)");
tex->SetNDC();
   tex->SetTextAlign(31);
   tex->SetTextFont(42);
   tex->SetTextSize(0.07);
   tex->SetLineWidth(2);
   tex->Draw();
   data_obs_fail_postfit_projy1_main->Modified();
   plots_fit_b/base_figs/postfit_projy1_fail->cd();
  
// ------------>Primitives in pad: data_obs_fail_postfit_projy1_sub
   TPad *data_obs_fail_postfit_projy1_sub = new TPad("data_obs_fail_postfit_projy1_sub", "data_obs_fail_postfit_projy1_sub",0,0,1,0.35);
   data_obs_fail_postfit_projy1_sub->Draw();
   data_obs_fail_postfit_projy1_sub->cd();
   data_obs_fail_postfit_projy1_sub->Range(17.30769,-6.023077,209.6154,2.9);
   data_obs_fail_postfit_projy1_sub->SetFillColor(0);
   data_obs_fail_postfit_projy1_sub->SetBorderMode(0);
   data_obs_fail_postfit_projy1_sub->SetBorderSize(2);
   data_obs_fail_postfit_projy1_sub->SetTickx(1);
   data_obs_fail_postfit_projy1_sub->SetTicky(1);
   data_obs_fail_postfit_projy1_sub->SetLeftMargin(0.17);
   data_obs_fail_postfit_projy1_sub->SetRightMargin(0.05);
   data_obs_fail_postfit_projy1_sub->SetTopMargin(0);
   data_obs_fail_postfit_projy1_sub->SetBottomMargin(0.35);
   data_obs_fail_postfit_projy1_sub->SetFrameFillStyle(0);
   data_obs_fail_postfit_projy1_sub->SetFrameBorderMode(0);
   data_obs_fail_postfit_projy1_sub->SetFrameFillStyle(0);
   data_obs_fail_postfit_projy1_sub->SetFrameBorderMode(0);
   Double_t xAxis55[2] = {50, 200}; 
   
   TH1D *data_obs_fail_postfit_projy1_pull__35 = new TH1D("data_obs_fail_postfit_projy1_pull__35","",1, xAxis55);
   data_obs_fail_postfit_projy1_pull__35->SetBinContent(1,0.3280369);
   data_obs_fail_postfit_projy1_pull__35->SetBinError(1,108.9649);
   data_obs_fail_postfit_projy1_pull__35->SetMinimum(-2.9);
   data_obs_fail_postfit_projy1_pull__35->SetMaximum(2.9);
   data_obs_fail_postfit_projy1_pull__35->SetEntries(1.109037);
   data_obs_fail_postfit_projy1_pull__35->SetStats(0);

   ci = TColor::GetColor("#0000ff");
   data_obs_fail_postfit_projy1_pull__35->SetFillColor(ci);

   ci = TColor::GetColor("#000000");
   data_obs_fail_postfit_projy1_pull__35->SetLineColor(ci);

   ci = TColor::GetColor("#000000");
   data_obs_fail_postfit_projy1_pull__35->SetMarkerColor(ci);
   data_obs_fail_postfit_projy1_pull__35->SetMarkerStyle(8);
   data_obs_fail_postfit_projy1_pull__35->GetXaxis()->SetTitle("p_{T}");
   data_obs_fail_postfit_projy1_pull__35->GetXaxis()->SetLabelFont(42);
   data_obs_fail_postfit_projy1_pull__35->GetXaxis()->SetLabelOffset(0.05);
   data_obs_fail_postfit_projy1_pull__35->GetXaxis()->SetLabelSize(0.13);
   data_obs_fail_postfit_projy1_pull__35->GetXaxis()->SetTitleSize(0.15);
   data_obs_fail_postfit_projy1_pull__35->GetXaxis()->SetTitleOffset(1.15);
   data_obs_fail_postfit_projy1_pull__35->GetXaxis()->SetTitleFont(42);
   data_obs_fail_postfit_projy1_pull__35->GetYaxis()->SetTitle("(Data-Bkg)/#sigma");
   data_obs_fail_postfit_projy1_pull__35->GetYaxis()->SetNdivisions(306);
   data_obs_fail_postfit_projy1_pull__35->GetYaxis()->SetLabelFont(42);
   data_obs_fail_postfit_projy1_pull__35->GetYaxis()->SetLabelSize(0.13);
   data_obs_fail_postfit_projy1_pull__35->GetYaxis()->SetTitleSize(0.12);
   data_obs_fail_postfit_projy1_pull__35->GetYaxis()->SetTitleOffset(0.4);
   data_obs_fail_postfit_projy1_pull__35->GetYaxis()->SetTitleFont(42);
   data_obs_fail_postfit_projy1_pull__35->GetZaxis()->SetLabelFont(42);
   data_obs_fail_postfit_projy1_pull__35->GetZaxis()->SetLabelSize(0.035);
   data_obs_fail_postfit_projy1_pull__35->GetZaxis()->SetTitleSize(0.035);
   data_obs_fail_postfit_projy1_pull__35->GetZaxis()->SetTitleFont(42);
   data_obs_fail_postfit_projy1_pull__35->Draw("hist");
   data_obs_fail_postfit_projy1_sub->Modified();
   plots_fit_b/base_figs/postfit_projy1_fail->cd();
   plots_fit_b/base_figs/postfit_projy1_fail->Modified();
   plots_fit_b/base_figs/postfit_projy1_fail->cd();
   plots_fit_b/base_figs/postfit_projy1_fail->SetSelected(plots_fit_b/base_figs/postfit_projy1_fail);
}
