void postfit_projy0_fail()
{
//=========Macro generated from canvas: plots_fit_b/base_figs/postfit_projy0_fail/plots_fit_b/base_figs/postfit_projy0_fail
//=========  (Fri Jan 12 21:00:01 2024) by ROOT version 6.14/09
   TCanvas *plots_fit_b/base_figs/postfit_projy0_fail = new TCanvas("plots_fit_b/base_figs/postfit_projy0_fail", "plots_fit_b/base_figs/postfit_projy0_fail",0,0,800,700);
   gStyle->SetOptFit(1);
   gStyle->SetOptStat(0);
   plots_fit_b/base_figs/postfit_projy0_fail->SetHighLightColor(2);
   plots_fit_b/base_figs/postfit_projy0_fail->Range(0,0,1,1);
   plots_fit_b/base_figs/postfit_projy0_fail->SetFillColor(0);
   plots_fit_b/base_figs/postfit_projy0_fail->SetBorderMode(0);
   plots_fit_b/base_figs/postfit_projy0_fail->SetBorderSize(2);
   plots_fit_b/base_figs/postfit_projy0_fail->SetTickx(1);
   plots_fit_b/base_figs/postfit_projy0_fail->SetTicky(1);
   plots_fit_b/base_figs/postfit_projy0_fail->SetLeftMargin(0.16);
   plots_fit_b/base_figs/postfit_projy0_fail->SetRightMargin(0);
   plots_fit_b/base_figs/postfit_projy0_fail->SetTopMargin(0);
   plots_fit_b/base_figs/postfit_projy0_fail->SetBottomMargin(0);
   plots_fit_b/base_figs/postfit_projy0_fail->SetFrameFillStyle(0);
   plots_fit_b/base_figs/postfit_projy0_fail->SetFrameBorderMode(0);
  
// ------------>Primitives in pad: data_obs_fail_postfit_projy0_main
   TPad *data_obs_fail_postfit_projy0_main = new TPad("data_obs_fail_postfit_projy0_main", "data_obs_fail_postfit_projy0_main",0,0.35,1,1);
   data_obs_fail_postfit_projy0_main->Draw();
   data_obs_fail_postfit_projy0_main->cd();
   data_obs_fail_postfit_projy0_main->Range(17.30769,-884431.9,209.6154,2.122636e+07);
   data_obs_fail_postfit_projy0_main->SetFillColor(0);
   data_obs_fail_postfit_projy0_main->SetBorderMode(0);
   data_obs_fail_postfit_projy0_main->SetBorderSize(2);
   data_obs_fail_postfit_projy0_main->SetTickx(1);
   data_obs_fail_postfit_projy0_main->SetTicky(1);
   data_obs_fail_postfit_projy0_main->SetLeftMargin(0.17);
   data_obs_fail_postfit_projy0_main->SetRightMargin(0.05);
   data_obs_fail_postfit_projy0_main->SetBottomMargin(0.04);
   data_obs_fail_postfit_projy0_main->SetFrameFillStyle(0);
   data_obs_fail_postfit_projy0_main->SetFrameBorderMode(0);
   data_obs_fail_postfit_projy0_main->SetFrameFillStyle(0);
   data_obs_fail_postfit_projy0_main->SetFrameBorderMode(0);
   Double_t xAxis34[2] = {50, 200}; 
   
   TH1D *data_obs_fail_postfit_projy0__22 = new TH1D("data_obs_fail_postfit_projy0__22","",1, xAxis34);
   data_obs_fail_postfit_projy0__22->SetBinContent(1,1.40854e+07);
   data_obs_fail_postfit_projy0__22->SetBinError(1,3753.052);
   data_obs_fail_postfit_projy0__22->SetMinimum(0);
   data_obs_fail_postfit_projy0__22->SetMaximum(1.901528e+07);
   data_obs_fail_postfit_projy0__22->SetEntries(1.40854e+07);
   data_obs_fail_postfit_projy0__22->SetStats(0);

   Int_t ci;      // for color index setting
   TColor *color; // for color definition with alpha
   ci = TColor::GetColor("#000000");
   data_obs_fail_postfit_projy0__22->SetLineColor(ci);

   ci = TColor::GetColor("#000000");
   data_obs_fail_postfit_projy0__22->SetMarkerColor(ci);
   data_obs_fail_postfit_projy0__22->SetMarkerStyle(8);
   data_obs_fail_postfit_projy0__22->GetXaxis()->SetTitle("p_{T}");
   data_obs_fail_postfit_projy0__22->GetXaxis()->SetLabelFont(42);
   data_obs_fail_postfit_projy0__22->GetXaxis()->SetLabelOffset(0.05);
   data_obs_fail_postfit_projy0__22->GetXaxis()->SetLabelSize(0.07);
   data_obs_fail_postfit_projy0__22->GetXaxis()->SetTitleSize(0.09);
   data_obs_fail_postfit_projy0__22->GetXaxis()->SetTitleOffset(1.15);
   data_obs_fail_postfit_projy0__22->GetXaxis()->SetTitleFont(42);
   data_obs_fail_postfit_projy0__22->GetYaxis()->SetTitle("Events / bin");
   data_obs_fail_postfit_projy0__22->GetYaxis()->SetNdivisions(508);
   data_obs_fail_postfit_projy0__22->GetYaxis()->SetLabelFont(42);
   data_obs_fail_postfit_projy0__22->GetYaxis()->SetLabelSize(0.07);
   data_obs_fail_postfit_projy0__22->GetYaxis()->SetTitleSize(0.09);
   data_obs_fail_postfit_projy0__22->GetYaxis()->SetTitleOffset(0.8);
   data_obs_fail_postfit_projy0__22->GetYaxis()->SetTitleFont(42);
   data_obs_fail_postfit_projy0__22->GetZaxis()->SetLabelFont(42);
   data_obs_fail_postfit_projy0__22->GetZaxis()->SetLabelSize(0.035);
   data_obs_fail_postfit_projy0__22->GetZaxis()->SetTitleSize(0.035);
   data_obs_fail_postfit_projy0__22->GetZaxis()->SetTitleFont(42);
   data_obs_fail_postfit_projy0__22->Draw("pe X0");
   
   THStack *postfit_projy0_fail_stack = new THStack();
   postfit_projy0_fail_stack->SetName("postfit_projy0_fail_stack");
   postfit_projy0_fail_stack->SetTitle("postfit_projy0_fail_stack");
   Double_t xAxis35[2] = {50, 200}; 
   
   TH1F *postfit_projy0_fail_stack_stack_7 = new TH1F("postfit_projy0_fail_stack_stack_7","postfit_projy0_fail_stack",1, xAxis35);
   postfit_projy0_fail_stack_stack_7->SetMinimum(0);
   postfit_projy0_fail_stack_stack_7->SetMaximum(1.479374e+07);
   postfit_projy0_fail_stack_stack_7->SetDirectory(0);
   postfit_projy0_fail_stack_stack_7->SetStats(0);
   postfit_projy0_fail_stack_stack_7->SetLineStyle(0);
   postfit_projy0_fail_stack_stack_7->GetXaxis()->SetLabelFont(42);
   postfit_projy0_fail_stack_stack_7->GetXaxis()->SetLabelOffset(0.007);
   postfit_projy0_fail_stack_stack_7->GetXaxis()->SetLabelSize(0.05);
   postfit_projy0_fail_stack_stack_7->GetXaxis()->SetTitleSize(0.08);
   postfit_projy0_fail_stack_stack_7->GetXaxis()->SetTitleOffset(0.9);
   postfit_projy0_fail_stack_stack_7->GetXaxis()->SetTitleFont(42);
   postfit_projy0_fail_stack_stack_7->GetYaxis()->SetNdivisions(508);
   postfit_projy0_fail_stack_stack_7->GetYaxis()->SetLabelFont(42);
   postfit_projy0_fail_stack_stack_7->GetYaxis()->SetLabelOffset(0.007);
   postfit_projy0_fail_stack_stack_7->GetYaxis()->SetLabelSize(0.05);
   postfit_projy0_fail_stack_stack_7->GetYaxis()->SetTitleSize(0.08);
   postfit_projy0_fail_stack_stack_7->GetYaxis()->SetTitleOffset(1.25);
   postfit_projy0_fail_stack_stack_7->GetYaxis()->SetTitleFont(42);
   postfit_projy0_fail_stack_stack_7->GetZaxis()->SetLabelFont(42);
   postfit_projy0_fail_stack_stack_7->GetZaxis()->SetLabelOffset(0.007);
   postfit_projy0_fail_stack_stack_7->GetZaxis()->SetLabelSize(0.05);
   postfit_projy0_fail_stack_stack_7->GetZaxis()->SetTitleSize(0.08);
   postfit_projy0_fail_stack_stack_7->GetZaxis()->SetTitleFont(42);
   postfit_projy0_fail_stack->SetHistogram(postfit_projy0_fail_stack_stack_7);
   
   Double_t xAxis36[2] = {50, 200}; 
   
   TH1D *Background_fail_postfit_projy0_stack_1 = new TH1D("Background_fail_postfit_projy0_stack_1","Background, fail, postfit, 0.0-0.24",1, xAxis36);
   Background_fail_postfit_projy0_stack_1->SetBinContent(1,1.408543e+07);
   Background_fail_postfit_projy0_stack_1->SetBinError(1,3844.732);
   Background_fail_postfit_projy0_stack_1->SetMinimum(0);
   Background_fail_postfit_projy0_stack_1->SetEntries(1.342172e+07);
   Background_fail_postfit_projy0_stack_1->SetStats(0);

   ci = TColor::GetColor("#ffff00");
   Background_fail_postfit_projy0_stack_1->SetFillColor(ci);

   ci = 1188;
   color = new TColor(ci, 1, 1, 1, " ", 0);
   Background_fail_postfit_projy0_stack_1->SetLineColor(ci);
   Background_fail_postfit_projy0_stack_1->GetXaxis()->SetTitle("p_{T}");
   Background_fail_postfit_projy0_stack_1->GetXaxis()->SetLabelFont(42);
   Background_fail_postfit_projy0_stack_1->GetXaxis()->SetLabelSize(0.035);
   Background_fail_postfit_projy0_stack_1->GetXaxis()->SetTitleSize(0.035);
   Background_fail_postfit_projy0_stack_1->GetXaxis()->SetTitleOffset(0);
   Background_fail_postfit_projy0_stack_1->GetXaxis()->SetTitleFont(42);
   Background_fail_postfit_projy0_stack_1->GetYaxis()->SetTitle("Events / bin");
   Background_fail_postfit_projy0_stack_1->GetYaxis()->SetLabelFont(42);
   Background_fail_postfit_projy0_stack_1->GetYaxis()->SetLabelSize(0.035);
   Background_fail_postfit_projy0_stack_1->GetYaxis()->SetTitleSize(0.035);
   Background_fail_postfit_projy0_stack_1->GetYaxis()->SetTitleOffset(0);
   Background_fail_postfit_projy0_stack_1->GetYaxis()->SetTitleFont(42);
   Background_fail_postfit_projy0_stack_1->GetZaxis()->SetLabelFont(42);
   Background_fail_postfit_projy0_stack_1->GetZaxis()->SetLabelSize(0.035);
   Background_fail_postfit_projy0_stack_1->GetZaxis()->SetTitleSize(0.035);
   Background_fail_postfit_projy0_stack_1->GetZaxis()->SetTitleFont(42);
   postfit_projy0_fail_stack->Add(Background_fail_postfit_projy0_stack_1,"");
   postfit_projy0_fail_stack->Draw("hist same");
   
   postfit_projy0_fail_stack = new THStack();
   postfit_projy0_fail_stack->SetName("postfit_projy0_fail_stack");
   postfit_projy0_fail_stack->SetTitle("postfit_projy0_fail_stack");
   Double_t xAxis37[2] = {50, 200}; 
   
   TH1F *postfit_projy0_fail_stack_stack_7_stack_8 = new TH1F("postfit_projy0_fail_stack_stack_7_stack_8","postfit_projy0_fail_stack",1, xAxis37);
   postfit_projy0_fail_stack_stack_7_stack_8->SetMinimum(0);
   postfit_projy0_fail_stack_stack_7_stack_8->SetMaximum(1.479374e+07);
   postfit_projy0_fail_stack_stack_7_stack_8->SetDirectory(0);
   postfit_projy0_fail_stack_stack_7_stack_8->SetStats(0);
   postfit_projy0_fail_stack_stack_7_stack_8->SetLineStyle(0);
   postfit_projy0_fail_stack_stack_7_stack_8->GetXaxis()->SetLabelFont(42);
   postfit_projy0_fail_stack_stack_7_stack_8->GetXaxis()->SetLabelOffset(0.007);
   postfit_projy0_fail_stack_stack_7_stack_8->GetXaxis()->SetLabelSize(0.05);
   postfit_projy0_fail_stack_stack_7_stack_8->GetXaxis()->SetTitleSize(0.08);
   postfit_projy0_fail_stack_stack_7_stack_8->GetXaxis()->SetTitleOffset(0.9);
   postfit_projy0_fail_stack_stack_7_stack_8->GetXaxis()->SetTitleFont(42);
   postfit_projy0_fail_stack_stack_7_stack_8->GetYaxis()->SetNdivisions(508);
   postfit_projy0_fail_stack_stack_7_stack_8->GetYaxis()->SetLabelFont(42);
   postfit_projy0_fail_stack_stack_7_stack_8->GetYaxis()->SetLabelOffset(0.007);
   postfit_projy0_fail_stack_stack_7_stack_8->GetYaxis()->SetLabelSize(0.05);
   postfit_projy0_fail_stack_stack_7_stack_8->GetYaxis()->SetTitleSize(0.08);
   postfit_projy0_fail_stack_stack_7_stack_8->GetYaxis()->SetTitleOffset(1.25);
   postfit_projy0_fail_stack_stack_7_stack_8->GetYaxis()->SetTitleFont(42);
   postfit_projy0_fail_stack_stack_7_stack_8->GetZaxis()->SetLabelFont(42);
   postfit_projy0_fail_stack_stack_7_stack_8->GetZaxis()->SetLabelOffset(0.007);
   postfit_projy0_fail_stack_stack_7_stack_8->GetZaxis()->SetLabelSize(0.05);
   postfit_projy0_fail_stack_stack_7_stack_8->GetZaxis()->SetTitleSize(0.08);
   postfit_projy0_fail_stack_stack_7_stack_8->GetZaxis()->SetTitleFont(42);
   postfit_projy0_fail_stack->SetHistogram(postfit_projy0_fail_stack_stack_7_stack_8);
   
   Double_t xAxis38[2] = {50, 200}; 
   
   TH1D *Background_fail_postfit_projy0_stack_1_stack_1 = new TH1D("Background_fail_postfit_projy0_stack_1_stack_1","Background, fail, postfit, 0.0-0.24",1, xAxis38);
   Background_fail_postfit_projy0_stack_1_stack_1->SetBinContent(1,1.408543e+07);
   Background_fail_postfit_projy0_stack_1_stack_1->SetBinError(1,3844.732);
   Background_fail_postfit_projy0_stack_1_stack_1->SetMinimum(0);
   Background_fail_postfit_projy0_stack_1_stack_1->SetEntries(1.342172e+07);
   Background_fail_postfit_projy0_stack_1_stack_1->SetStats(0);

   ci = TColor::GetColor("#ffff00");
   Background_fail_postfit_projy0_stack_1_stack_1->SetFillColor(ci);

   ci = 1188;
   color = new TColor(ci, 1, 1, 1, " ", 0);
   Background_fail_postfit_projy0_stack_1_stack_1->SetLineColor(ci);
   Background_fail_postfit_projy0_stack_1_stack_1->GetXaxis()->SetTitle("p_{T}");
   Background_fail_postfit_projy0_stack_1_stack_1->GetXaxis()->SetLabelFont(42);
   Background_fail_postfit_projy0_stack_1_stack_1->GetXaxis()->SetLabelSize(0.035);
   Background_fail_postfit_projy0_stack_1_stack_1->GetXaxis()->SetTitleSize(0.035);
   Background_fail_postfit_projy0_stack_1_stack_1->GetXaxis()->SetTitleOffset(0);
   Background_fail_postfit_projy0_stack_1_stack_1->GetXaxis()->SetTitleFont(42);
   Background_fail_postfit_projy0_stack_1_stack_1->GetYaxis()->SetTitle("Events / bin");
   Background_fail_postfit_projy0_stack_1_stack_1->GetYaxis()->SetLabelFont(42);
   Background_fail_postfit_projy0_stack_1_stack_1->GetYaxis()->SetLabelSize(0.035);
   Background_fail_postfit_projy0_stack_1_stack_1->GetYaxis()->SetTitleSize(0.035);
   Background_fail_postfit_projy0_stack_1_stack_1->GetYaxis()->SetTitleOffset(0);
   Background_fail_postfit_projy0_stack_1_stack_1->GetYaxis()->SetTitleFont(42);
   Background_fail_postfit_projy0_stack_1_stack_1->GetZaxis()->SetLabelFont(42);
   Background_fail_postfit_projy0_stack_1_stack_1->GetZaxis()->SetLabelSize(0.035);
   Background_fail_postfit_projy0_stack_1_stack_1->GetZaxis()->SetTitleSize(0.035);
   Background_fail_postfit_projy0_stack_1_stack_1->GetZaxis()->SetTitleFont(42);
   postfit_projy0_fail_stack->Add(Background_fail_postfit_projy0_stack_1_stack_1,"");
   postfit_projy0_fail_stack->Draw("hist same");
   Double_t xAxis39[2] = {50, 200}; 
   
   TH1D *Signal_ppStaumI557_fail_postfit_projy0__23 = new TH1D("Signal_ppStaumI557_fail_postfit_projy0__23","HSCP signal, fail, postfit, 0.0-0.24",1, xAxis39);
   Signal_ppStaumI557_fail_postfit_projy0__23->SetBinContent(1,0.000411045);
   Signal_ppStaumI557_fail_postfit_projy0__23->SetBinError(1,4.119792e-05);
   Signal_ppStaumI557_fail_postfit_projy0__23->SetMinimum(0);
   Signal_ppStaumI557_fail_postfit_projy0__23->SetEntries(99.54697);
   Signal_ppStaumI557_fail_postfit_projy0__23->SetStats(0);
   Signal_ppStaumI557_fail_postfit_projy0__23->SetLineColor(2);
   Signal_ppStaumI557_fail_postfit_projy0__23->GetXaxis()->SetTitle("p_{T}");
   Signal_ppStaumI557_fail_postfit_projy0__23->GetXaxis()->SetLabelFont(42);
   Signal_ppStaumI557_fail_postfit_projy0__23->GetXaxis()->SetLabelSize(0.035);
   Signal_ppStaumI557_fail_postfit_projy0__23->GetXaxis()->SetTitleSize(0.035);
   Signal_ppStaumI557_fail_postfit_projy0__23->GetXaxis()->SetTitleOffset(0);
   Signal_ppStaumI557_fail_postfit_projy0__23->GetXaxis()->SetTitleFont(42);
   Signal_ppStaumI557_fail_postfit_projy0__23->GetYaxis()->SetTitle("Events / bin");
   Signal_ppStaumI557_fail_postfit_projy0__23->GetYaxis()->SetLabelFont(42);
   Signal_ppStaumI557_fail_postfit_projy0__23->GetYaxis()->SetLabelSize(0.035);
   Signal_ppStaumI557_fail_postfit_projy0__23->GetYaxis()->SetTitleSize(0.035);
   Signal_ppStaumI557_fail_postfit_projy0__23->GetYaxis()->SetTitleOffset(0);
   Signal_ppStaumI557_fail_postfit_projy0__23->GetYaxis()->SetTitleFont(42);
   Signal_ppStaumI557_fail_postfit_projy0__23->GetZaxis()->SetLabelFont(42);
   Signal_ppStaumI557_fail_postfit_projy0__23->GetZaxis()->SetLabelSize(0.035);
   Signal_ppStaumI557_fail_postfit_projy0__23->GetZaxis()->SetTitleSize(0.035);
   Signal_ppStaumI557_fail_postfit_projy0__23->GetZaxis()->SetTitleFont(42);
   Signal_ppStaumI557_fail_postfit_projy0__23->Draw("hist same");
   Double_t xAxis40[2] = {50, 200}; 
   
   TH1D *TotalBkg_fail_postfit_projy0__24 = new TH1D("TotalBkg_fail_postfit_projy0__24","TotalBkg, fail, postfit, 0.0-0.24",1, xAxis40);
   TotalBkg_fail_postfit_projy0__24->SetBinContent(1,1.408543e+07);
   TotalBkg_fail_postfit_projy0__24->SetBinError(1,3467.333);
   TotalBkg_fail_postfit_projy0__24->SetMinimum(0);
   TotalBkg_fail_postfit_projy0__24->SetEntries(1.650248e+07);
   TotalBkg_fail_postfit_projy0__24->SetStats(0);
   TotalBkg_fail_postfit_projy0__24->SetMarkerStyle(0);
   TotalBkg_fail_postfit_projy0__24->GetXaxis()->SetTitle("p_{T}");
   TotalBkg_fail_postfit_projy0__24->GetXaxis()->SetLabelFont(42);
   TotalBkg_fail_postfit_projy0__24->GetXaxis()->SetLabelSize(0.035);
   TotalBkg_fail_postfit_projy0__24->GetXaxis()->SetTitleSize(0.035);
   TotalBkg_fail_postfit_projy0__24->GetXaxis()->SetTitleOffset(0);
   TotalBkg_fail_postfit_projy0__24->GetXaxis()->SetTitleFont(42);
   TotalBkg_fail_postfit_projy0__24->GetYaxis()->SetTitle("Events / bin");
   TotalBkg_fail_postfit_projy0__24->GetYaxis()->SetLabelFont(42);
   TotalBkg_fail_postfit_projy0__24->GetYaxis()->SetLabelSize(0.035);
   TotalBkg_fail_postfit_projy0__24->GetYaxis()->SetTitleSize(0.035);
   TotalBkg_fail_postfit_projy0__24->GetYaxis()->SetTitleOffset(0);
   TotalBkg_fail_postfit_projy0__24->GetYaxis()->SetTitleFont(42);
   TotalBkg_fail_postfit_projy0__24->GetZaxis()->SetLabelFont(42);
   TotalBkg_fail_postfit_projy0__24->GetZaxis()->SetLabelSize(0.035);
   TotalBkg_fail_postfit_projy0__24->GetZaxis()->SetTitleSize(0.035);
   TotalBkg_fail_postfit_projy0__24->GetZaxis()->SetTitleFont(42);
   TotalBkg_fail_postfit_projy0__24->Draw("hist same");
   Double_t xAxis41[2] = {50, 200}; 
   
   TH1D *TotalBkg_fail_postfit_projy0__25 = new TH1D("TotalBkg_fail_postfit_projy0__25","TotalBkg, fail, postfit, 0.0-0.24",1, xAxis41);
   TotalBkg_fail_postfit_projy0__25->SetBinContent(1,1.408543e+07);
   TotalBkg_fail_postfit_projy0__25->SetBinError(1,3467.333);
   TotalBkg_fail_postfit_projy0__25->SetMinimum(0);
   TotalBkg_fail_postfit_projy0__25->SetEntries(1.650248e+07);
   TotalBkg_fail_postfit_projy0__25->SetStats(0);
   TotalBkg_fail_postfit_projy0__25->SetFillColor(1);
   TotalBkg_fail_postfit_projy0__25->SetFillStyle(3354);
   TotalBkg_fail_postfit_projy0__25->SetLineWidth(0);
   TotalBkg_fail_postfit_projy0__25->SetMarkerStyle(0);
   TotalBkg_fail_postfit_projy0__25->GetXaxis()->SetTitle("p_{T}");
   TotalBkg_fail_postfit_projy0__25->GetXaxis()->SetLabelFont(42);
   TotalBkg_fail_postfit_projy0__25->GetXaxis()->SetLabelSize(0.035);
   TotalBkg_fail_postfit_projy0__25->GetXaxis()->SetTitleSize(0.035);
   TotalBkg_fail_postfit_projy0__25->GetXaxis()->SetTitleOffset(0);
   TotalBkg_fail_postfit_projy0__25->GetXaxis()->SetTitleFont(42);
   TotalBkg_fail_postfit_projy0__25->GetYaxis()->SetTitle("Events / bin");
   TotalBkg_fail_postfit_projy0__25->GetYaxis()->SetLabelFont(42);
   TotalBkg_fail_postfit_projy0__25->GetYaxis()->SetLabelSize(0.035);
   TotalBkg_fail_postfit_projy0__25->GetYaxis()->SetTitleSize(0.035);
   TotalBkg_fail_postfit_projy0__25->GetYaxis()->SetTitleOffset(0);
   TotalBkg_fail_postfit_projy0__25->GetYaxis()->SetTitleFont(42);
   TotalBkg_fail_postfit_projy0__25->GetZaxis()->SetLabelFont(42);
   TotalBkg_fail_postfit_projy0__25->GetZaxis()->SetLabelSize(0.035);
   TotalBkg_fail_postfit_projy0__25->GetZaxis()->SetTitleSize(0.035);
   TotalBkg_fail_postfit_projy0__25->GetZaxis()->SetTitleFont(42);
   TotalBkg_fail_postfit_projy0__25->Draw("e2 same");
   Double_t xAxis42[2] = {50, 200}; 
   
   TH1D *data_obs_fail_postfit_projy0__26 = new TH1D("data_obs_fail_postfit_projy0__26","",1, xAxis42);
   data_obs_fail_postfit_projy0__26->SetBinContent(1,1.40854e+07);
   data_obs_fail_postfit_projy0__26->SetBinError(1,3753.052);
   data_obs_fail_postfit_projy0__26->SetMinimum(0);
   data_obs_fail_postfit_projy0__26->SetMaximum(1.901528e+07);
   data_obs_fail_postfit_projy0__26->SetEntries(1.40854e+07);
   data_obs_fail_postfit_projy0__26->SetStats(0);

   ci = TColor::GetColor("#000000");
   data_obs_fail_postfit_projy0__26->SetLineColor(ci);

   ci = TColor::GetColor("#000000");
   data_obs_fail_postfit_projy0__26->SetMarkerColor(ci);
   data_obs_fail_postfit_projy0__26->SetMarkerStyle(8);
   data_obs_fail_postfit_projy0__26->GetXaxis()->SetTitle("p_{T}");
   data_obs_fail_postfit_projy0__26->GetXaxis()->SetLabelFont(42);
   data_obs_fail_postfit_projy0__26->GetXaxis()->SetLabelOffset(0.05);
   data_obs_fail_postfit_projy0__26->GetXaxis()->SetLabelSize(0.07);
   data_obs_fail_postfit_projy0__26->GetXaxis()->SetTitleSize(0.09);
   data_obs_fail_postfit_projy0__26->GetXaxis()->SetTitleOffset(1.15);
   data_obs_fail_postfit_projy0__26->GetXaxis()->SetTitleFont(42);
   data_obs_fail_postfit_projy0__26->GetYaxis()->SetTitle("Events / bin");
   data_obs_fail_postfit_projy0__26->GetYaxis()->SetNdivisions(508);
   data_obs_fail_postfit_projy0__26->GetYaxis()->SetLabelFont(42);
   data_obs_fail_postfit_projy0__26->GetYaxis()->SetLabelSize(0.07);
   data_obs_fail_postfit_projy0__26->GetYaxis()->SetTitleSize(0.09);
   data_obs_fail_postfit_projy0__26->GetYaxis()->SetTitleOffset(0.8);
   data_obs_fail_postfit_projy0__26->GetYaxis()->SetTitleFont(42);
   data_obs_fail_postfit_projy0__26->GetZaxis()->SetLabelFont(42);
   data_obs_fail_postfit_projy0__26->GetZaxis()->SetLabelSize(0.035);
   data_obs_fail_postfit_projy0__26->GetZaxis()->SetTitleSize(0.035);
   data_obs_fail_postfit_projy0__26->GetZaxis()->SetTitleFont(42);
   data_obs_fail_postfit_projy0__26->Draw("pe X0 same");
   
   TLegend *leg = new TLegend(0.65,0.64,0.9,0.88,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(1001);
   TLegendEntry *entry=leg->AddEntry("data_obs_fail_postfit_projy0","Data","pe X0");

   ci = TColor::GetColor("#000000");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);

   ci = TColor::GetColor("#000000");
   entry->SetMarkerColor(ci);
   entry->SetMarkerStyle(8);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("TotalBkg_fail_postfit_projy0","Total bkg unc.","F");
   entry->SetFillColor(1);
   entry->SetFillStyle(3354);
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("Signal_ppStau-557_fail_postfit_projy0","HSCP signal","L");
   entry->SetLineColor(2);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("Background_fail_postfit_projy0_stack_1_stack_1","Background","f");

   ci = TColor::GetColor("#ffff00");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = 1188;
   color = new TColor(ci, 1, 1, 1, " ", 0);
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   leg->Draw();
   Double_t xAxis43[2] = {50, 200}; 
   
   TH1D *data_obs_fail_postfit_projy0_copy__27 = new TH1D("data_obs_fail_postfit_projy0_copy__27","",1, xAxis43);
   data_obs_fail_postfit_projy0_copy__27->SetBinContent(1,1.40854e+07);
   data_obs_fail_postfit_projy0_copy__27->SetBinError(1,3753.052);
   data_obs_fail_postfit_projy0_copy__27->SetMinimum(0);
   data_obs_fail_postfit_projy0_copy__27->SetMaximum(1.901528e+07);
   data_obs_fail_postfit_projy0_copy__27->SetEntries(1.40854e+07);
   data_obs_fail_postfit_projy0_copy__27->SetDirectory(0);
   data_obs_fail_postfit_projy0_copy__27->SetStats(0);

   ci = TColor::GetColor("#000000");
   data_obs_fail_postfit_projy0_copy__27->SetLineColor(ci);

   ci = TColor::GetColor("#000000");
   data_obs_fail_postfit_projy0_copy__27->SetMarkerColor(ci);
   data_obs_fail_postfit_projy0_copy__27->SetMarkerStyle(8);
   data_obs_fail_postfit_projy0_copy__27->GetXaxis()->SetTitle("p_{T}");
   data_obs_fail_postfit_projy0_copy__27->GetXaxis()->SetLabelFont(42);
   data_obs_fail_postfit_projy0_copy__27->GetXaxis()->SetLabelOffset(0.05);
   data_obs_fail_postfit_projy0_copy__27->GetXaxis()->SetLabelSize(0.07);
   data_obs_fail_postfit_projy0_copy__27->GetXaxis()->SetTitleSize(0.09);
   data_obs_fail_postfit_projy0_copy__27->GetXaxis()->SetTitleOffset(1.15);
   data_obs_fail_postfit_projy0_copy__27->GetXaxis()->SetTitleFont(42);
   data_obs_fail_postfit_projy0_copy__27->GetYaxis()->SetTitle("Events / bin");
   data_obs_fail_postfit_projy0_copy__27->GetYaxis()->SetNdivisions(508);
   data_obs_fail_postfit_projy0_copy__27->GetYaxis()->SetLabelFont(42);
   data_obs_fail_postfit_projy0_copy__27->GetYaxis()->SetLabelSize(0.07);
   data_obs_fail_postfit_projy0_copy__27->GetYaxis()->SetTitleSize(0.09);
   data_obs_fail_postfit_projy0_copy__27->GetYaxis()->SetTitleOffset(0.8);
   data_obs_fail_postfit_projy0_copy__27->GetYaxis()->SetTitleFont(42);
   data_obs_fail_postfit_projy0_copy__27->GetZaxis()->SetLabelFont(42);
   data_obs_fail_postfit_projy0_copy__27->GetZaxis()->SetLabelSize(0.035);
   data_obs_fail_postfit_projy0_copy__27->GetZaxis()->SetTitleSize(0.035);
   data_obs_fail_postfit_projy0_copy__27->GetZaxis()->SetTitleFont(42);
   data_obs_fail_postfit_projy0_copy__27->Draw("sameaxis");
   TLatex *   tex = new TLatex(0.21,0.83,"55 < p_{T} < 200 GeV, F^{Pixels}_{i} < 0.9");
tex->SetNDC();
   tex->SetTextAlign(12);
   tex->SetTextFont(42);
   tex->SetTextSize(0.06);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.17,0.92,"CMS");
tex->SetNDC();
   tex->SetTextFont(61);
   tex->SetTextSize(0.0675);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.25,0.92,"Preliminary");
tex->SetNDC();
   tex->SetTextFont(52);
   tex->SetTextSize(0.0485);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.95,0.92,"101 fb^{-1} (13 TeV)");
tex->SetNDC();
   tex->SetTextAlign(31);
   tex->SetTextFont(42);
   tex->SetTextSize(0.07);
   tex->SetLineWidth(2);
   tex->Draw();
   data_obs_fail_postfit_projy0_main->Modified();
   plots_fit_b/base_figs/postfit_projy0_fail->cd();
  
// ------------>Primitives in pad: data_obs_fail_postfit_projy0_sub
   TPad *data_obs_fail_postfit_projy0_sub = new TPad("data_obs_fail_postfit_projy0_sub", "data_obs_fail_postfit_projy0_sub",0,0,1,0.35);
   data_obs_fail_postfit_projy0_sub->Draw();
   data_obs_fail_postfit_projy0_sub->cd();
   data_obs_fail_postfit_projy0_sub->Range(17.30769,-6.023077,209.6154,2.9);
   data_obs_fail_postfit_projy0_sub->SetFillColor(0);
   data_obs_fail_postfit_projy0_sub->SetBorderMode(0);
   data_obs_fail_postfit_projy0_sub->SetBorderSize(2);
   data_obs_fail_postfit_projy0_sub->SetTickx(1);
   data_obs_fail_postfit_projy0_sub->SetTicky(1);
   data_obs_fail_postfit_projy0_sub->SetLeftMargin(0.17);
   data_obs_fail_postfit_projy0_sub->SetRightMargin(0.05);
   data_obs_fail_postfit_projy0_sub->SetTopMargin(0);
   data_obs_fail_postfit_projy0_sub->SetBottomMargin(0.35);
   data_obs_fail_postfit_projy0_sub->SetFrameFillStyle(0);
   data_obs_fail_postfit_projy0_sub->SetFrameBorderMode(0);
   data_obs_fail_postfit_projy0_sub->SetFrameFillStyle(0);
   data_obs_fail_postfit_projy0_sub->SetFrameBorderMode(0);
   Double_t xAxis44[2] = {50, 200}; 
   
   TH1D *data_obs_fail_postfit_projy0_pull__28 = new TH1D("data_obs_fail_postfit_projy0_pull__28","",1, xAxis44);
   data_obs_fail_postfit_projy0_pull__28->SetBinContent(1,-0.006877177);
   data_obs_fail_postfit_projy0_pull__28->SetBinError(1,5109.579);
   data_obs_fail_postfit_projy0_pull__28->SetMinimum(-2.9);
   data_obs_fail_postfit_projy0_pull__28->SetMaximum(2.9);
   data_obs_fail_postfit_projy0_pull__28->SetEntries(36.14453);
   data_obs_fail_postfit_projy0_pull__28->SetStats(0);

   ci = TColor::GetColor("#0000ff");
   data_obs_fail_postfit_projy0_pull__28->SetFillColor(ci);

   ci = TColor::GetColor("#000000");
   data_obs_fail_postfit_projy0_pull__28->SetLineColor(ci);

   ci = TColor::GetColor("#000000");
   data_obs_fail_postfit_projy0_pull__28->SetMarkerColor(ci);
   data_obs_fail_postfit_projy0_pull__28->SetMarkerStyle(8);
   data_obs_fail_postfit_projy0_pull__28->GetXaxis()->SetTitle("p_{T}");
   data_obs_fail_postfit_projy0_pull__28->GetXaxis()->SetLabelFont(42);
   data_obs_fail_postfit_projy0_pull__28->GetXaxis()->SetLabelOffset(0.05);
   data_obs_fail_postfit_projy0_pull__28->GetXaxis()->SetLabelSize(0.13);
   data_obs_fail_postfit_projy0_pull__28->GetXaxis()->SetTitleSize(0.15);
   data_obs_fail_postfit_projy0_pull__28->GetXaxis()->SetTitleOffset(1.15);
   data_obs_fail_postfit_projy0_pull__28->GetXaxis()->SetTitleFont(42);
   data_obs_fail_postfit_projy0_pull__28->GetYaxis()->SetTitle("(Data-Bkg)/#sigma");
   data_obs_fail_postfit_projy0_pull__28->GetYaxis()->SetNdivisions(306);
   data_obs_fail_postfit_projy0_pull__28->GetYaxis()->SetLabelFont(42);
   data_obs_fail_postfit_projy0_pull__28->GetYaxis()->SetLabelSize(0.13);
   data_obs_fail_postfit_projy0_pull__28->GetYaxis()->SetTitleSize(0.12);
   data_obs_fail_postfit_projy0_pull__28->GetYaxis()->SetTitleOffset(0.4);
   data_obs_fail_postfit_projy0_pull__28->GetYaxis()->SetTitleFont(42);
   data_obs_fail_postfit_projy0_pull__28->GetZaxis()->SetLabelFont(42);
   data_obs_fail_postfit_projy0_pull__28->GetZaxis()->SetLabelSize(0.035);
   data_obs_fail_postfit_projy0_pull__28->GetZaxis()->SetTitleSize(0.035);
   data_obs_fail_postfit_projy0_pull__28->GetZaxis()->SetTitleFont(42);
   data_obs_fail_postfit_projy0_pull__28->Draw("hist");
   data_obs_fail_postfit_projy0_sub->Modified();
   plots_fit_b/base_figs/postfit_projy0_fail->cd();
   plots_fit_b/base_figs/postfit_projy0_fail->Modified();
   plots_fit_b/base_figs/postfit_projy0_fail->cd();
   plots_fit_b/base_figs/postfit_projy0_fail->SetSelected(plots_fit_b/base_figs/postfit_projy0_fail);
}
