void postfit_projy0_pass()
{
//=========Macro generated from canvas: plots_fit_b/base_figs/postfit_projy0_pass/plots_fit_b/base_figs/postfit_projy0_pass
//=========  (Fri Jan 12 21:00:02 2024) by ROOT version 6.14/09
   TCanvas *plots_fit_b/base_figs/postfit_projy0_pass = new TCanvas("plots_fit_b/base_figs/postfit_projy0_pass", "plots_fit_b/base_figs/postfit_projy0_pass",0,0,800,700);
   gStyle->SetOptFit(1);
   gStyle->SetOptStat(0);
   plots_fit_b/base_figs/postfit_projy0_pass->SetHighLightColor(2);
   plots_fit_b/base_figs/postfit_projy0_pass->Range(0,0,1,1);
   plots_fit_b/base_figs/postfit_projy0_pass->SetFillColor(0);
   plots_fit_b/base_figs/postfit_projy0_pass->SetBorderMode(0);
   plots_fit_b/base_figs/postfit_projy0_pass->SetBorderSize(2);
   plots_fit_b/base_figs/postfit_projy0_pass->SetTickx(1);
   plots_fit_b/base_figs/postfit_projy0_pass->SetTicky(1);
   plots_fit_b/base_figs/postfit_projy0_pass->SetLeftMargin(0.16);
   plots_fit_b/base_figs/postfit_projy0_pass->SetRightMargin(0);
   plots_fit_b/base_figs/postfit_projy0_pass->SetTopMargin(0);
   plots_fit_b/base_figs/postfit_projy0_pass->SetBottomMargin(0);
   plots_fit_b/base_figs/postfit_projy0_pass->SetFrameFillStyle(0);
   plots_fit_b/base_figs/postfit_projy0_pass->SetFrameBorderMode(0);
  
// ------------>Primitives in pad: data_obs_pass_postfit_projy0_main
   TPad *data_obs_pass_postfit_projy0_main = new TPad("data_obs_pass_postfit_projy0_main", "data_obs_pass_postfit_projy0_main",0,0.35,1,1);
   data_obs_pass_postfit_projy0_main->Draw();
   data_obs_pass_postfit_projy0_main->cd();
   data_obs_pass_postfit_projy0_main->Range(17.30769,-146170.1,209.6154,3508082);
   data_obs_pass_postfit_projy0_main->SetFillColor(0);
   data_obs_pass_postfit_projy0_main->SetBorderMode(0);
   data_obs_pass_postfit_projy0_main->SetBorderSize(2);
   data_obs_pass_postfit_projy0_main->SetTickx(1);
   data_obs_pass_postfit_projy0_main->SetTicky(1);
   data_obs_pass_postfit_projy0_main->SetLeftMargin(0.17);
   data_obs_pass_postfit_projy0_main->SetRightMargin(0.05);
   data_obs_pass_postfit_projy0_main->SetBottomMargin(0.04);
   data_obs_pass_postfit_projy0_main->SetFrameFillStyle(0);
   data_obs_pass_postfit_projy0_main->SetFrameBorderMode(0);
   data_obs_pass_postfit_projy0_main->SetFrameFillStyle(0);
   data_obs_pass_postfit_projy0_main->SetFrameBorderMode(0);
   Double_t xAxis166[2] = {50, 200}; 
   
   TH1D *data_obs_pass_postfit_projy0__106 = new TH1D("data_obs_pass_postfit_projy0__106","",1, xAxis166);
   data_obs_pass_postfit_projy0__106->SetBinContent(1,2327894);
   data_obs_pass_postfit_projy0__106->SetBinError(1,1525.744);
   data_obs_pass_postfit_projy0__106->SetMinimum(0);
   data_obs_pass_postfit_projy0__106->SetMaximum(3142657);
   data_obs_pass_postfit_projy0__106->SetEntries(2327894);
   data_obs_pass_postfit_projy0__106->SetStats(0);

   Int_t ci;      // for color index setting
   TColor *color; // for color definition with alpha
   ci = TColor::GetColor("#000000");
   data_obs_pass_postfit_projy0__106->SetLineColor(ci);

   ci = TColor::GetColor("#000000");
   data_obs_pass_postfit_projy0__106->SetMarkerColor(ci);
   data_obs_pass_postfit_projy0__106->SetMarkerStyle(8);
   data_obs_pass_postfit_projy0__106->GetXaxis()->SetTitle("p_{T}");
   data_obs_pass_postfit_projy0__106->GetXaxis()->SetLabelFont(42);
   data_obs_pass_postfit_projy0__106->GetXaxis()->SetLabelOffset(0.05);
   data_obs_pass_postfit_projy0__106->GetXaxis()->SetLabelSize(0.07);
   data_obs_pass_postfit_projy0__106->GetXaxis()->SetTitleSize(0.09);
   data_obs_pass_postfit_projy0__106->GetXaxis()->SetTitleOffset(1.15);
   data_obs_pass_postfit_projy0__106->GetXaxis()->SetTitleFont(42);
   data_obs_pass_postfit_projy0__106->GetYaxis()->SetTitle("Events / bin");
   data_obs_pass_postfit_projy0__106->GetYaxis()->SetNdivisions(508);
   data_obs_pass_postfit_projy0__106->GetYaxis()->SetLabelFont(42);
   data_obs_pass_postfit_projy0__106->GetYaxis()->SetLabelSize(0.07);
   data_obs_pass_postfit_projy0__106->GetYaxis()->SetTitleSize(0.09);
   data_obs_pass_postfit_projy0__106->GetYaxis()->SetTitleOffset(0.8);
   data_obs_pass_postfit_projy0__106->GetYaxis()->SetTitleFont(42);
   data_obs_pass_postfit_projy0__106->GetZaxis()->SetLabelFont(42);
   data_obs_pass_postfit_projy0__106->GetZaxis()->SetLabelSize(0.035);
   data_obs_pass_postfit_projy0__106->GetZaxis()->SetTitleSize(0.035);
   data_obs_pass_postfit_projy0__106->GetZaxis()->SetTitleFont(42);
   data_obs_pass_postfit_projy0__106->Draw("pe X0");
   
   THStack *postfit_projy0_pass_stack = new THStack();
   postfit_projy0_pass_stack->SetName("postfit_projy0_pass_stack");
   postfit_projy0_pass_stack->SetTitle("postfit_projy0_pass_stack");
   Double_t xAxis167[2] = {50, 200}; 
   
   TH1F *postfit_projy0_pass_stack_stack_31 = new TH1F("postfit_projy0_pass_stack_stack_31","postfit_projy0_pass_stack",1, xAxis167);
   postfit_projy0_pass_stack_stack_31->SetMinimum(0);
   postfit_projy0_pass_stack_stack_31->SetMaximum(2445475);
   postfit_projy0_pass_stack_stack_31->SetDirectory(0);
   postfit_projy0_pass_stack_stack_31->SetStats(0);
   postfit_projy0_pass_stack_stack_31->SetLineStyle(0);
   postfit_projy0_pass_stack_stack_31->GetXaxis()->SetLabelFont(42);
   postfit_projy0_pass_stack_stack_31->GetXaxis()->SetLabelOffset(0.007);
   postfit_projy0_pass_stack_stack_31->GetXaxis()->SetLabelSize(0.05);
   postfit_projy0_pass_stack_stack_31->GetXaxis()->SetTitleSize(0.08);
   postfit_projy0_pass_stack_stack_31->GetXaxis()->SetTitleOffset(0.9);
   postfit_projy0_pass_stack_stack_31->GetXaxis()->SetTitleFont(42);
   postfit_projy0_pass_stack_stack_31->GetYaxis()->SetNdivisions(508);
   postfit_projy0_pass_stack_stack_31->GetYaxis()->SetLabelFont(42);
   postfit_projy0_pass_stack_stack_31->GetYaxis()->SetLabelOffset(0.007);
   postfit_projy0_pass_stack_stack_31->GetYaxis()->SetLabelSize(0.05);
   postfit_projy0_pass_stack_stack_31->GetYaxis()->SetTitleSize(0.08);
   postfit_projy0_pass_stack_stack_31->GetYaxis()->SetTitleOffset(1.25);
   postfit_projy0_pass_stack_stack_31->GetYaxis()->SetTitleFont(42);
   postfit_projy0_pass_stack_stack_31->GetZaxis()->SetLabelFont(42);
   postfit_projy0_pass_stack_stack_31->GetZaxis()->SetLabelOffset(0.007);
   postfit_projy0_pass_stack_stack_31->GetZaxis()->SetLabelSize(0.05);
   postfit_projy0_pass_stack_stack_31->GetZaxis()->SetTitleSize(0.08);
   postfit_projy0_pass_stack_stack_31->GetZaxis()->SetTitleFont(42);
   postfit_projy0_pass_stack->SetHistogram(postfit_projy0_pass_stack_stack_31);
   
   Double_t xAxis168[2] = {50, 200}; 
   
   TH1D *Background_0x0_pass_postfit_projy0_stack_1 = new TH1D("Background_0x0_pass_postfit_projy0_stack_1","Background, pass, postfit, 0.0-0.24",1, xAxis168);
   Background_0x0_pass_postfit_projy0_stack_1->SetBinContent(1,2327858);
   Background_0x0_pass_postfit_projy0_stack_1->SetBinError(1,1165.91);
   Background_0x0_pass_postfit_projy0_stack_1->SetMinimum(0);
   Background_0x0_pass_postfit_projy0_stack_1->SetEntries(3986418);
   Background_0x0_pass_postfit_projy0_stack_1->SetStats(0);

   ci = TColor::GetColor("#ffff00");
   Background_0x0_pass_postfit_projy0_stack_1->SetFillColor(ci);

   ci = 1200;
   color = new TColor(ci, 1, 1, 1, " ", 0);
   Background_0x0_pass_postfit_projy0_stack_1->SetLineColor(ci);
   Background_0x0_pass_postfit_projy0_stack_1->GetXaxis()->SetTitle("p_{T}");
   Background_0x0_pass_postfit_projy0_stack_1->GetXaxis()->SetLabelFont(42);
   Background_0x0_pass_postfit_projy0_stack_1->GetXaxis()->SetLabelSize(0.035);
   Background_0x0_pass_postfit_projy0_stack_1->GetXaxis()->SetTitleSize(0.035);
   Background_0x0_pass_postfit_projy0_stack_1->GetXaxis()->SetTitleOffset(0);
   Background_0x0_pass_postfit_projy0_stack_1->GetXaxis()->SetTitleFont(42);
   Background_0x0_pass_postfit_projy0_stack_1->GetYaxis()->SetTitle("Events / bin");
   Background_0x0_pass_postfit_projy0_stack_1->GetYaxis()->SetLabelFont(42);
   Background_0x0_pass_postfit_projy0_stack_1->GetYaxis()->SetLabelSize(0.035);
   Background_0x0_pass_postfit_projy0_stack_1->GetYaxis()->SetTitleSize(0.035);
   Background_0x0_pass_postfit_projy0_stack_1->GetYaxis()->SetTitleOffset(0);
   Background_0x0_pass_postfit_projy0_stack_1->GetYaxis()->SetTitleFont(42);
   Background_0x0_pass_postfit_projy0_stack_1->GetZaxis()->SetLabelFont(42);
   Background_0x0_pass_postfit_projy0_stack_1->GetZaxis()->SetLabelSize(0.035);
   Background_0x0_pass_postfit_projy0_stack_1->GetZaxis()->SetTitleSize(0.035);
   Background_0x0_pass_postfit_projy0_stack_1->GetZaxis()->SetTitleFont(42);
   postfit_projy0_pass_stack->Add(Background_0x0_pass_postfit_projy0_stack_1,"");
   postfit_projy0_pass_stack->Draw("hist same");
   
   postfit_projy0_pass_stack = new THStack();
   postfit_projy0_pass_stack->SetName("postfit_projy0_pass_stack");
   postfit_projy0_pass_stack->SetTitle("postfit_projy0_pass_stack");
   Double_t xAxis169[2] = {50, 200}; 
   
   TH1F *postfit_projy0_pass_stack_stack_31_stack_32 = new TH1F("postfit_projy0_pass_stack_stack_31_stack_32","postfit_projy0_pass_stack",1, xAxis169);
   postfit_projy0_pass_stack_stack_31_stack_32->SetMinimum(0);
   postfit_projy0_pass_stack_stack_31_stack_32->SetMaximum(2445475);
   postfit_projy0_pass_stack_stack_31_stack_32->SetDirectory(0);
   postfit_projy0_pass_stack_stack_31_stack_32->SetStats(0);
   postfit_projy0_pass_stack_stack_31_stack_32->SetLineStyle(0);
   postfit_projy0_pass_stack_stack_31_stack_32->GetXaxis()->SetLabelFont(42);
   postfit_projy0_pass_stack_stack_31_stack_32->GetXaxis()->SetLabelOffset(0.007);
   postfit_projy0_pass_stack_stack_31_stack_32->GetXaxis()->SetLabelSize(0.05);
   postfit_projy0_pass_stack_stack_31_stack_32->GetXaxis()->SetTitleSize(0.08);
   postfit_projy0_pass_stack_stack_31_stack_32->GetXaxis()->SetTitleOffset(0.9);
   postfit_projy0_pass_stack_stack_31_stack_32->GetXaxis()->SetTitleFont(42);
   postfit_projy0_pass_stack_stack_31_stack_32->GetYaxis()->SetNdivisions(508);
   postfit_projy0_pass_stack_stack_31_stack_32->GetYaxis()->SetLabelFont(42);
   postfit_projy0_pass_stack_stack_31_stack_32->GetYaxis()->SetLabelOffset(0.007);
   postfit_projy0_pass_stack_stack_31_stack_32->GetYaxis()->SetLabelSize(0.05);
   postfit_projy0_pass_stack_stack_31_stack_32->GetYaxis()->SetTitleSize(0.08);
   postfit_projy0_pass_stack_stack_31_stack_32->GetYaxis()->SetTitleOffset(1.25);
   postfit_projy0_pass_stack_stack_31_stack_32->GetYaxis()->SetTitleFont(42);
   postfit_projy0_pass_stack_stack_31_stack_32->GetZaxis()->SetLabelFont(42);
   postfit_projy0_pass_stack_stack_31_stack_32->GetZaxis()->SetLabelOffset(0.007);
   postfit_projy0_pass_stack_stack_31_stack_32->GetZaxis()->SetLabelSize(0.05);
   postfit_projy0_pass_stack_stack_31_stack_32->GetZaxis()->SetTitleSize(0.08);
   postfit_projy0_pass_stack_stack_31_stack_32->GetZaxis()->SetTitleFont(42);
   postfit_projy0_pass_stack->SetHistogram(postfit_projy0_pass_stack_stack_31_stack_32);
   
   Double_t xAxis170[2] = {50, 200}; 
   
   TH1D *Background_0x0_pass_postfit_projy0_stack_1_stack_1 = new TH1D("Background_0x0_pass_postfit_projy0_stack_1_stack_1","Background, pass, postfit, 0.0-0.24",1, xAxis170);
   Background_0x0_pass_postfit_projy0_stack_1_stack_1->SetBinContent(1,2327858);
   Background_0x0_pass_postfit_projy0_stack_1_stack_1->SetBinError(1,1165.91);
   Background_0x0_pass_postfit_projy0_stack_1_stack_1->SetMinimum(0);
   Background_0x0_pass_postfit_projy0_stack_1_stack_1->SetEntries(3986418);
   Background_0x0_pass_postfit_projy0_stack_1_stack_1->SetStats(0);

   ci = TColor::GetColor("#ffff00");
   Background_0x0_pass_postfit_projy0_stack_1_stack_1->SetFillColor(ci);

   ci = 1200;
   color = new TColor(ci, 1, 1, 1, " ", 0);
   Background_0x0_pass_postfit_projy0_stack_1_stack_1->SetLineColor(ci);
   Background_0x0_pass_postfit_projy0_stack_1_stack_1->GetXaxis()->SetTitle("p_{T}");
   Background_0x0_pass_postfit_projy0_stack_1_stack_1->GetXaxis()->SetLabelFont(42);
   Background_0x0_pass_postfit_projy0_stack_1_stack_1->GetXaxis()->SetLabelSize(0.035);
   Background_0x0_pass_postfit_projy0_stack_1_stack_1->GetXaxis()->SetTitleSize(0.035);
   Background_0x0_pass_postfit_projy0_stack_1_stack_1->GetXaxis()->SetTitleOffset(0);
   Background_0x0_pass_postfit_projy0_stack_1_stack_1->GetXaxis()->SetTitleFont(42);
   Background_0x0_pass_postfit_projy0_stack_1_stack_1->GetYaxis()->SetTitle("Events / bin");
   Background_0x0_pass_postfit_projy0_stack_1_stack_1->GetYaxis()->SetLabelFont(42);
   Background_0x0_pass_postfit_projy0_stack_1_stack_1->GetYaxis()->SetLabelSize(0.035);
   Background_0x0_pass_postfit_projy0_stack_1_stack_1->GetYaxis()->SetTitleSize(0.035);
   Background_0x0_pass_postfit_projy0_stack_1_stack_1->GetYaxis()->SetTitleOffset(0);
   Background_0x0_pass_postfit_projy0_stack_1_stack_1->GetYaxis()->SetTitleFont(42);
   Background_0x0_pass_postfit_projy0_stack_1_stack_1->GetZaxis()->SetLabelFont(42);
   Background_0x0_pass_postfit_projy0_stack_1_stack_1->GetZaxis()->SetLabelSize(0.035);
   Background_0x0_pass_postfit_projy0_stack_1_stack_1->GetZaxis()->SetTitleSize(0.035);
   Background_0x0_pass_postfit_projy0_stack_1_stack_1->GetZaxis()->SetTitleFont(42);
   postfit_projy0_pass_stack->Add(Background_0x0_pass_postfit_projy0_stack_1_stack_1,"");
   postfit_projy0_pass_stack->Draw("hist same");
   Double_t xAxis171[2] = {50, 200}; 
   
   TH1D *Signal_ppStaumI557_pass_postfit_projy0__107 = new TH1D("Signal_ppStaumI557_pass_postfit_projy0__107","HSCP signal, pass, postfit, 0.0-0.24",1, xAxis171);
   Signal_ppStaumI557_pass_postfit_projy0__107->SetBinContent(1,1.44e-05);
   Signal_ppStaumI557_pass_postfit_projy0__107->SetBinError(1,8.844606e-08);
   Signal_ppStaumI557_pass_postfit_projy0__107->SetMinimum(0);
   Signal_ppStaumI557_pass_postfit_projy0__107->SetEntries(26507.45);
   Signal_ppStaumI557_pass_postfit_projy0__107->SetStats(0);
   Signal_ppStaumI557_pass_postfit_projy0__107->SetLineColor(2);
   Signal_ppStaumI557_pass_postfit_projy0__107->GetXaxis()->SetTitle("p_{T}");
   Signal_ppStaumI557_pass_postfit_projy0__107->GetXaxis()->SetLabelFont(42);
   Signal_ppStaumI557_pass_postfit_projy0__107->GetXaxis()->SetLabelSize(0.035);
   Signal_ppStaumI557_pass_postfit_projy0__107->GetXaxis()->SetTitleSize(0.035);
   Signal_ppStaumI557_pass_postfit_projy0__107->GetXaxis()->SetTitleOffset(0);
   Signal_ppStaumI557_pass_postfit_projy0__107->GetXaxis()->SetTitleFont(42);
   Signal_ppStaumI557_pass_postfit_projy0__107->GetYaxis()->SetTitle("Events / bin");
   Signal_ppStaumI557_pass_postfit_projy0__107->GetYaxis()->SetLabelFont(42);
   Signal_ppStaumI557_pass_postfit_projy0__107->GetYaxis()->SetLabelSize(0.035);
   Signal_ppStaumI557_pass_postfit_projy0__107->GetYaxis()->SetTitleSize(0.035);
   Signal_ppStaumI557_pass_postfit_projy0__107->GetYaxis()->SetTitleOffset(0);
   Signal_ppStaumI557_pass_postfit_projy0__107->GetYaxis()->SetTitleFont(42);
   Signal_ppStaumI557_pass_postfit_projy0__107->GetZaxis()->SetLabelFont(42);
   Signal_ppStaumI557_pass_postfit_projy0__107->GetZaxis()->SetLabelSize(0.035);
   Signal_ppStaumI557_pass_postfit_projy0__107->GetZaxis()->SetTitleSize(0.035);
   Signal_ppStaumI557_pass_postfit_projy0__107->GetZaxis()->SetTitleFont(42);
   Signal_ppStaumI557_pass_postfit_projy0__107->Draw("hist same");
   Double_t xAxis172[2] = {50, 200}; 
   
   TH1D *TotalBkg_pass_postfit_projy0__108 = new TH1D("TotalBkg_pass_postfit_projy0__108","TotalBkg, pass, postfit, 0.0-0.24",1, xAxis172);
   TotalBkg_pass_postfit_projy0__108->SetBinContent(1,2327858);
   TotalBkg_pass_postfit_projy0__108->SetBinError(1,1368.309);
   TotalBkg_pass_postfit_projy0__108->SetMinimum(0);
   TotalBkg_pass_postfit_projy0__108->SetEntries(2894307);
   TotalBkg_pass_postfit_projy0__108->SetStats(0);
   TotalBkg_pass_postfit_projy0__108->SetMarkerStyle(0);
   TotalBkg_pass_postfit_projy0__108->GetXaxis()->SetTitle("p_{T}");
   TotalBkg_pass_postfit_projy0__108->GetXaxis()->SetLabelFont(42);
   TotalBkg_pass_postfit_projy0__108->GetXaxis()->SetLabelSize(0.035);
   TotalBkg_pass_postfit_projy0__108->GetXaxis()->SetTitleSize(0.035);
   TotalBkg_pass_postfit_projy0__108->GetXaxis()->SetTitleOffset(0);
   TotalBkg_pass_postfit_projy0__108->GetXaxis()->SetTitleFont(42);
   TotalBkg_pass_postfit_projy0__108->GetYaxis()->SetTitle("Events / bin");
   TotalBkg_pass_postfit_projy0__108->GetYaxis()->SetLabelFont(42);
   TotalBkg_pass_postfit_projy0__108->GetYaxis()->SetLabelSize(0.035);
   TotalBkg_pass_postfit_projy0__108->GetYaxis()->SetTitleSize(0.035);
   TotalBkg_pass_postfit_projy0__108->GetYaxis()->SetTitleOffset(0);
   TotalBkg_pass_postfit_projy0__108->GetYaxis()->SetTitleFont(42);
   TotalBkg_pass_postfit_projy0__108->GetZaxis()->SetLabelFont(42);
   TotalBkg_pass_postfit_projy0__108->GetZaxis()->SetLabelSize(0.035);
   TotalBkg_pass_postfit_projy0__108->GetZaxis()->SetTitleSize(0.035);
   TotalBkg_pass_postfit_projy0__108->GetZaxis()->SetTitleFont(42);
   TotalBkg_pass_postfit_projy0__108->Draw("hist same");
   Double_t xAxis173[2] = {50, 200}; 
   
   TH1D *TotalBkg_pass_postfit_projy0__109 = new TH1D("TotalBkg_pass_postfit_projy0__109","TotalBkg, pass, postfit, 0.0-0.24",1, xAxis173);
   TotalBkg_pass_postfit_projy0__109->SetBinContent(1,2327858);
   TotalBkg_pass_postfit_projy0__109->SetBinError(1,1368.309);
   TotalBkg_pass_postfit_projy0__109->SetMinimum(0);
   TotalBkg_pass_postfit_projy0__109->SetEntries(2894307);
   TotalBkg_pass_postfit_projy0__109->SetStats(0);
   TotalBkg_pass_postfit_projy0__109->SetFillColor(1);
   TotalBkg_pass_postfit_projy0__109->SetFillStyle(3354);
   TotalBkg_pass_postfit_projy0__109->SetLineWidth(0);
   TotalBkg_pass_postfit_projy0__109->SetMarkerStyle(0);
   TotalBkg_pass_postfit_projy0__109->GetXaxis()->SetTitle("p_{T}");
   TotalBkg_pass_postfit_projy0__109->GetXaxis()->SetLabelFont(42);
   TotalBkg_pass_postfit_projy0__109->GetXaxis()->SetLabelSize(0.035);
   TotalBkg_pass_postfit_projy0__109->GetXaxis()->SetTitleSize(0.035);
   TotalBkg_pass_postfit_projy0__109->GetXaxis()->SetTitleOffset(0);
   TotalBkg_pass_postfit_projy0__109->GetXaxis()->SetTitleFont(42);
   TotalBkg_pass_postfit_projy0__109->GetYaxis()->SetTitle("Events / bin");
   TotalBkg_pass_postfit_projy0__109->GetYaxis()->SetLabelFont(42);
   TotalBkg_pass_postfit_projy0__109->GetYaxis()->SetLabelSize(0.035);
   TotalBkg_pass_postfit_projy0__109->GetYaxis()->SetTitleSize(0.035);
   TotalBkg_pass_postfit_projy0__109->GetYaxis()->SetTitleOffset(0);
   TotalBkg_pass_postfit_projy0__109->GetYaxis()->SetTitleFont(42);
   TotalBkg_pass_postfit_projy0__109->GetZaxis()->SetLabelFont(42);
   TotalBkg_pass_postfit_projy0__109->GetZaxis()->SetLabelSize(0.035);
   TotalBkg_pass_postfit_projy0__109->GetZaxis()->SetTitleSize(0.035);
   TotalBkg_pass_postfit_projy0__109->GetZaxis()->SetTitleFont(42);
   TotalBkg_pass_postfit_projy0__109->Draw("e2 same");
   Double_t xAxis174[2] = {50, 200}; 
   
   TH1D *data_obs_pass_postfit_projy0__110 = new TH1D("data_obs_pass_postfit_projy0__110","",1, xAxis174);
   data_obs_pass_postfit_projy0__110->SetBinContent(1,2327894);
   data_obs_pass_postfit_projy0__110->SetBinError(1,1525.744);
   data_obs_pass_postfit_projy0__110->SetMinimum(0);
   data_obs_pass_postfit_projy0__110->SetMaximum(3142657);
   data_obs_pass_postfit_projy0__110->SetEntries(2327894);
   data_obs_pass_postfit_projy0__110->SetStats(0);

   ci = TColor::GetColor("#000000");
   data_obs_pass_postfit_projy0__110->SetLineColor(ci);

   ci = TColor::GetColor("#000000");
   data_obs_pass_postfit_projy0__110->SetMarkerColor(ci);
   data_obs_pass_postfit_projy0__110->SetMarkerStyle(8);
   data_obs_pass_postfit_projy0__110->GetXaxis()->SetTitle("p_{T}");
   data_obs_pass_postfit_projy0__110->GetXaxis()->SetLabelFont(42);
   data_obs_pass_postfit_projy0__110->GetXaxis()->SetLabelOffset(0.05);
   data_obs_pass_postfit_projy0__110->GetXaxis()->SetLabelSize(0.07);
   data_obs_pass_postfit_projy0__110->GetXaxis()->SetTitleSize(0.09);
   data_obs_pass_postfit_projy0__110->GetXaxis()->SetTitleOffset(1.15);
   data_obs_pass_postfit_projy0__110->GetXaxis()->SetTitleFont(42);
   data_obs_pass_postfit_projy0__110->GetYaxis()->SetTitle("Events / bin");
   data_obs_pass_postfit_projy0__110->GetYaxis()->SetNdivisions(508);
   data_obs_pass_postfit_projy0__110->GetYaxis()->SetLabelFont(42);
   data_obs_pass_postfit_projy0__110->GetYaxis()->SetLabelSize(0.07);
   data_obs_pass_postfit_projy0__110->GetYaxis()->SetTitleSize(0.09);
   data_obs_pass_postfit_projy0__110->GetYaxis()->SetTitleOffset(0.8);
   data_obs_pass_postfit_projy0__110->GetYaxis()->SetTitleFont(42);
   data_obs_pass_postfit_projy0__110->GetZaxis()->SetLabelFont(42);
   data_obs_pass_postfit_projy0__110->GetZaxis()->SetLabelSize(0.035);
   data_obs_pass_postfit_projy0__110->GetZaxis()->SetTitleSize(0.035);
   data_obs_pass_postfit_projy0__110->GetZaxis()->SetTitleFont(42);
   data_obs_pass_postfit_projy0__110->Draw("pe X0 same");
   
   TLegend *leg = new TLegend(0.65,0.64,0.9,0.88,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(1001);
   TLegendEntry *entry=leg->AddEntry("data_obs_pass_postfit_projy0","Data","pe X0");

   ci = TColor::GetColor("#000000");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);

   ci = TColor::GetColor("#000000");
   entry->SetMarkerColor(ci);
   entry->SetMarkerStyle(8);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("TotalBkg_pass_postfit_projy0","Total bkg unc.","F");
   entry->SetFillColor(1);
   entry->SetFillStyle(3354);
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("Signal_ppStau-557_pass_postfit_projy0","HSCP signal","L");
   entry->SetLineColor(2);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("Background_0x0_pass_postfit_projy0_stack_1_stack_1","Background","f");

   ci = TColor::GetColor("#ffff00");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = 1200;
   color = new TColor(ci, 1, 1, 1, " ", 0);
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   leg->Draw();
   Double_t xAxis175[2] = {50, 200}; 
   
   TH1D *data_obs_pass_postfit_projy0_copy__111 = new TH1D("data_obs_pass_postfit_projy0_copy__111","",1, xAxis175);
   data_obs_pass_postfit_projy0_copy__111->SetBinContent(1,2327894);
   data_obs_pass_postfit_projy0_copy__111->SetBinError(1,1525.744);
   data_obs_pass_postfit_projy0_copy__111->SetMinimum(0);
   data_obs_pass_postfit_projy0_copy__111->SetMaximum(3142657);
   data_obs_pass_postfit_projy0_copy__111->SetEntries(2327894);
   data_obs_pass_postfit_projy0_copy__111->SetDirectory(0);
   data_obs_pass_postfit_projy0_copy__111->SetStats(0);

   ci = TColor::GetColor("#000000");
   data_obs_pass_postfit_projy0_copy__111->SetLineColor(ci);

   ci = TColor::GetColor("#000000");
   data_obs_pass_postfit_projy0_copy__111->SetMarkerColor(ci);
   data_obs_pass_postfit_projy0_copy__111->SetMarkerStyle(8);
   data_obs_pass_postfit_projy0_copy__111->GetXaxis()->SetTitle("p_{T}");
   data_obs_pass_postfit_projy0_copy__111->GetXaxis()->SetLabelFont(42);
   data_obs_pass_postfit_projy0_copy__111->GetXaxis()->SetLabelOffset(0.05);
   data_obs_pass_postfit_projy0_copy__111->GetXaxis()->SetLabelSize(0.07);
   data_obs_pass_postfit_projy0_copy__111->GetXaxis()->SetTitleSize(0.09);
   data_obs_pass_postfit_projy0_copy__111->GetXaxis()->SetTitleOffset(1.15);
   data_obs_pass_postfit_projy0_copy__111->GetXaxis()->SetTitleFont(42);
   data_obs_pass_postfit_projy0_copy__111->GetYaxis()->SetTitle("Events / bin");
   data_obs_pass_postfit_projy0_copy__111->GetYaxis()->SetNdivisions(508);
   data_obs_pass_postfit_projy0_copy__111->GetYaxis()->SetLabelFont(42);
   data_obs_pass_postfit_projy0_copy__111->GetYaxis()->SetLabelSize(0.07);
   data_obs_pass_postfit_projy0_copy__111->GetYaxis()->SetTitleSize(0.09);
   data_obs_pass_postfit_projy0_copy__111->GetYaxis()->SetTitleOffset(0.8);
   data_obs_pass_postfit_projy0_copy__111->GetYaxis()->SetTitleFont(42);
   data_obs_pass_postfit_projy0_copy__111->GetZaxis()->SetLabelFont(42);
   data_obs_pass_postfit_projy0_copy__111->GetZaxis()->SetLabelSize(0.035);
   data_obs_pass_postfit_projy0_copy__111->GetZaxis()->SetTitleSize(0.035);
   data_obs_pass_postfit_projy0_copy__111->GetZaxis()->SetTitleFont(42);
   data_obs_pass_postfit_projy0_copy__111->Draw("sameaxis");
   TLatex *   tex = new TLatex(0.21,0.83,"55 < p_{T} < 200 GeV, F^{Pixels}_{i} > 0.9");
tex->SetNDC();
   tex->SetTextAlign(12);
   tex->SetTextFont(42);
   tex->SetTextSize(0.06);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.17,0.92,"CMS");
tex->SetNDC();
   tex->SetTextFont(61);
   tex->SetTextSize(0.0675);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.25,0.92,"Preliminary");
tex->SetNDC();
   tex->SetTextFont(52);
   tex->SetTextSize(0.0485);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.95,0.92,"101 fb^{-1} (13 TeV)");
tex->SetNDC();
   tex->SetTextAlign(31);
   tex->SetTextFont(42);
   tex->SetTextSize(0.07);
   tex->SetLineWidth(2);
   tex->Draw();
   data_obs_pass_postfit_projy0_main->Modified();
   plots_fit_b/base_figs/postfit_projy0_pass->cd();
  
// ------------>Primitives in pad: data_obs_pass_postfit_projy0_sub
   TPad *data_obs_pass_postfit_projy0_sub = new TPad("data_obs_pass_postfit_projy0_sub", "data_obs_pass_postfit_projy0_sub",0,0,1,0.35);
   data_obs_pass_postfit_projy0_sub->Draw();
   data_obs_pass_postfit_projy0_sub->cd();
   data_obs_pass_postfit_projy0_sub->Range(17.30769,-6.023077,209.6154,2.9);
   data_obs_pass_postfit_projy0_sub->SetFillColor(0);
   data_obs_pass_postfit_projy0_sub->SetBorderMode(0);
   data_obs_pass_postfit_projy0_sub->SetBorderSize(2);
   data_obs_pass_postfit_projy0_sub->SetTickx(1);
   data_obs_pass_postfit_projy0_sub->SetTicky(1);
   data_obs_pass_postfit_projy0_sub->SetLeftMargin(0.17);
   data_obs_pass_postfit_projy0_sub->SetRightMargin(0.05);
   data_obs_pass_postfit_projy0_sub->SetTopMargin(0);
   data_obs_pass_postfit_projy0_sub->SetBottomMargin(0.35);
   data_obs_pass_postfit_projy0_sub->SetFrameFillStyle(0);
   data_obs_pass_postfit_projy0_sub->SetFrameBorderMode(0);
   data_obs_pass_postfit_projy0_sub->SetFrameFillStyle(0);
   data_obs_pass_postfit_projy0_sub->SetFrameBorderMode(0);
   Double_t xAxis176[2] = {50, 200}; 
   
   TH1D *data_obs_pass_postfit_projy0_pull__112 = new TH1D("data_obs_pass_postfit_projy0_pull__112","",1, xAxis176);
   data_obs_pass_postfit_projy0_pull__112->SetBinContent(1,0.01766789);
   data_obs_pass_postfit_projy0_pull__112->SetBinError(1,2049.43);
   data_obs_pass_postfit_projy0_pull__112->SetMinimum(-2.9);
   data_obs_pass_postfit_projy0_pull__112->SetMaximum(2.9);
   data_obs_pass_postfit_projy0_pull__112->SetEntries(1.000312);
   data_obs_pass_postfit_projy0_pull__112->SetStats(0);

   ci = TColor::GetColor("#0000ff");
   data_obs_pass_postfit_projy0_pull__112->SetFillColor(ci);

   ci = TColor::GetColor("#000000");
   data_obs_pass_postfit_projy0_pull__112->SetLineColor(ci);

   ci = TColor::GetColor("#000000");
   data_obs_pass_postfit_projy0_pull__112->SetMarkerColor(ci);
   data_obs_pass_postfit_projy0_pull__112->SetMarkerStyle(8);
   data_obs_pass_postfit_projy0_pull__112->GetXaxis()->SetTitle("p_{T}");
   data_obs_pass_postfit_projy0_pull__112->GetXaxis()->SetLabelFont(42);
   data_obs_pass_postfit_projy0_pull__112->GetXaxis()->SetLabelOffset(0.05);
   data_obs_pass_postfit_projy0_pull__112->GetXaxis()->SetLabelSize(0.13);
   data_obs_pass_postfit_projy0_pull__112->GetXaxis()->SetTitleSize(0.15);
   data_obs_pass_postfit_projy0_pull__112->GetXaxis()->SetTitleOffset(1.15);
   data_obs_pass_postfit_projy0_pull__112->GetXaxis()->SetTitleFont(42);
   data_obs_pass_postfit_projy0_pull__112->GetYaxis()->SetTitle("(Data-Bkg)/#sigma");
   data_obs_pass_postfit_projy0_pull__112->GetYaxis()->SetNdivisions(306);
   data_obs_pass_postfit_projy0_pull__112->GetYaxis()->SetLabelFont(42);
   data_obs_pass_postfit_projy0_pull__112->GetYaxis()->SetLabelSize(0.13);
   data_obs_pass_postfit_projy0_pull__112->GetYaxis()->SetTitleSize(0.12);
   data_obs_pass_postfit_projy0_pull__112->GetYaxis()->SetTitleOffset(0.4);
   data_obs_pass_postfit_projy0_pull__112->GetYaxis()->SetTitleFont(42);
   data_obs_pass_postfit_projy0_pull__112->GetZaxis()->SetLabelFont(42);
   data_obs_pass_postfit_projy0_pull__112->GetZaxis()->SetLabelSize(0.035);
   data_obs_pass_postfit_projy0_pull__112->GetZaxis()->SetTitleSize(0.035);
   data_obs_pass_postfit_projy0_pull__112->GetZaxis()->SetTitleFont(42);
   data_obs_pass_postfit_projy0_pull__112->Draw("hist");
   data_obs_pass_postfit_projy0_sub->Modified();
   plots_fit_b/base_figs/postfit_projy0_pass->cd();
   plots_fit_b/base_figs/postfit_projy0_pass->Modified();
   plots_fit_b/base_figs/postfit_projy0_pass->cd();
   plots_fit_b/base_figs/postfit_projy0_pass->SetSelected(plots_fit_b/base_figs/postfit_projy0_pass);
}
