void postfit_projy2_fail()
{
//=========Macro generated from canvas: plots_fit_b/base_figs/postfit_projy2_fail/plots_fit_b/base_figs/postfit_projy2_fail
//=========  (Fri Jan 12 21:00:01 2024) by ROOT version 6.14/09
   TCanvas *plots_fit_b/base_figs/postfit_projy2_fail = new TCanvas("plots_fit_b/base_figs/postfit_projy2_fail", "plots_fit_b/base_figs/postfit_projy2_fail",0,0,800,700);
   gStyle->SetOptFit(1);
   gStyle->SetOptStat(0);
   plots_fit_b/base_figs/postfit_projy2_fail->SetHighLightColor(2);
   plots_fit_b/base_figs/postfit_projy2_fail->Range(0,0,1,1);
   plots_fit_b/base_figs/postfit_projy2_fail->SetFillColor(0);
   plots_fit_b/base_figs/postfit_projy2_fail->SetBorderMode(0);
   plots_fit_b/base_figs/postfit_projy2_fail->SetBorderSize(2);
   plots_fit_b/base_figs/postfit_projy2_fail->SetTickx(1);
   plots_fit_b/base_figs/postfit_projy2_fail->SetTicky(1);
   plots_fit_b/base_figs/postfit_projy2_fail->SetLeftMargin(0.16);
   plots_fit_b/base_figs/postfit_projy2_fail->SetRightMargin(0);
   plots_fit_b/base_figs/postfit_projy2_fail->SetTopMargin(0);
   plots_fit_b/base_figs/postfit_projy2_fail->SetBottomMargin(0);
   plots_fit_b/base_figs/postfit_projy2_fail->SetFrameFillStyle(0);
   plots_fit_b/base_figs/postfit_projy2_fail->SetFrameBorderMode(0);
  
// ------------>Primitives in pad: data_obs_fail_postfit_projy2_main
   TPad *data_obs_fail_postfit_projy2_main = new TPad("data_obs_fail_postfit_projy2_main", "data_obs_fail_postfit_projy2_main",0,0.35,1,1);
   data_obs_fail_postfit_projy2_main->Draw();
   data_obs_fail_postfit_projy2_main->cd();
   data_obs_fail_postfit_projy2_main->Range(17.30769,-0.04651163,209.6154,1.116279);
   data_obs_fail_postfit_projy2_main->SetFillColor(0);
   data_obs_fail_postfit_projy2_main->SetBorderMode(0);
   data_obs_fail_postfit_projy2_main->SetBorderSize(2);
   data_obs_fail_postfit_projy2_main->SetTickx(1);
   data_obs_fail_postfit_projy2_main->SetTicky(1);
   data_obs_fail_postfit_projy2_main->SetLeftMargin(0.17);
   data_obs_fail_postfit_projy2_main->SetRightMargin(0.05);
   data_obs_fail_postfit_projy2_main->SetBottomMargin(0.04);
   data_obs_fail_postfit_projy2_main->SetFrameFillStyle(0);
   data_obs_fail_postfit_projy2_main->SetFrameBorderMode(0);
   data_obs_fail_postfit_projy2_main->SetFrameFillStyle(0);
   data_obs_fail_postfit_projy2_main->SetFrameBorderMode(0);
   Double_t xAxis56[2] = {50, 200}; 
   
   TH1D *data_obs_fail_postfit_projy2__36 = new TH1D("data_obs_fail_postfit_projy2__36","",1, xAxis56);
   data_obs_fail_postfit_projy2__36->SetMinimum(0);
   data_obs_fail_postfit_projy2__36->SetMaximum(0);
   data_obs_fail_postfit_projy2__36->SetStats(0);

   Int_t ci;      // for color index setting
   TColor *color; // for color definition with alpha
   ci = TColor::GetColor("#000000");
   data_obs_fail_postfit_projy2__36->SetLineColor(ci);

   ci = TColor::GetColor("#000000");
   data_obs_fail_postfit_projy2__36->SetMarkerColor(ci);
   data_obs_fail_postfit_projy2__36->SetMarkerStyle(8);
   data_obs_fail_postfit_projy2__36->GetXaxis()->SetTitle("p_{T}");
   data_obs_fail_postfit_projy2__36->GetXaxis()->SetLabelFont(42);
   data_obs_fail_postfit_projy2__36->GetXaxis()->SetLabelOffset(0.05);
   data_obs_fail_postfit_projy2__36->GetXaxis()->SetLabelSize(0.07);
   data_obs_fail_postfit_projy2__36->GetXaxis()->SetTitleSize(0.09);
   data_obs_fail_postfit_projy2__36->GetXaxis()->SetTitleOffset(1.15);
   data_obs_fail_postfit_projy2__36->GetXaxis()->SetTitleFont(42);
   data_obs_fail_postfit_projy2__36->GetYaxis()->SetTitle("Events / bin");
   data_obs_fail_postfit_projy2__36->GetYaxis()->SetNdivisions(508);
   data_obs_fail_postfit_projy2__36->GetYaxis()->SetLabelFont(42);
   data_obs_fail_postfit_projy2__36->GetYaxis()->SetLabelSize(0.07);
   data_obs_fail_postfit_projy2__36->GetYaxis()->SetTitleSize(0.09);
   data_obs_fail_postfit_projy2__36->GetYaxis()->SetTitleOffset(0.8);
   data_obs_fail_postfit_projy2__36->GetYaxis()->SetTitleFont(42);
   data_obs_fail_postfit_projy2__36->GetZaxis()->SetLabelFont(42);
   data_obs_fail_postfit_projy2__36->GetZaxis()->SetLabelSize(0.035);
   data_obs_fail_postfit_projy2__36->GetZaxis()->SetTitleSize(0.035);
   data_obs_fail_postfit_projy2__36->GetZaxis()->SetTitleFont(42);
   data_obs_fail_postfit_projy2__36->Draw("pe X0");
   
   THStack *postfit_projy2_fail_stack = new THStack();
   postfit_projy2_fail_stack->SetName("postfit_projy2_fail_stack");
   postfit_projy2_fail_stack->SetTitle("postfit_projy2_fail_stack");
   Double_t xAxis57[2] = {50, 200}; 
   
   TH1F *postfit_projy2_fail_stack_stack_11 = new TH1F("postfit_projy2_fail_stack_stack_11","postfit_projy2_fail_stack",1, xAxis57);
   postfit_projy2_fail_stack_stack_11->SetMinimum(0);
   postfit_projy2_fail_stack_stack_11->SetMaximum(0);
   postfit_projy2_fail_stack_stack_11->SetDirectory(0);
   postfit_projy2_fail_stack_stack_11->SetStats(0);
   postfit_projy2_fail_stack_stack_11->SetLineStyle(0);
   postfit_projy2_fail_stack_stack_11->GetXaxis()->SetLabelFont(42);
   postfit_projy2_fail_stack_stack_11->GetXaxis()->SetLabelOffset(0.007);
   postfit_projy2_fail_stack_stack_11->GetXaxis()->SetLabelSize(0.05);
   postfit_projy2_fail_stack_stack_11->GetXaxis()->SetTitleSize(0.08);
   postfit_projy2_fail_stack_stack_11->GetXaxis()->SetTitleOffset(0.9);
   postfit_projy2_fail_stack_stack_11->GetXaxis()->SetTitleFont(42);
   postfit_projy2_fail_stack_stack_11->GetYaxis()->SetNdivisions(508);
   postfit_projy2_fail_stack_stack_11->GetYaxis()->SetLabelFont(42);
   postfit_projy2_fail_stack_stack_11->GetYaxis()->SetLabelOffset(0.007);
   postfit_projy2_fail_stack_stack_11->GetYaxis()->SetLabelSize(0.05);
   postfit_projy2_fail_stack_stack_11->GetYaxis()->SetTitleSize(0.08);
   postfit_projy2_fail_stack_stack_11->GetYaxis()->SetTitleOffset(1.25);
   postfit_projy2_fail_stack_stack_11->GetYaxis()->SetTitleFont(42);
   postfit_projy2_fail_stack_stack_11->GetZaxis()->SetLabelFont(42);
   postfit_projy2_fail_stack_stack_11->GetZaxis()->SetLabelOffset(0.007);
   postfit_projy2_fail_stack_stack_11->GetZaxis()->SetLabelSize(0.05);
   postfit_projy2_fail_stack_stack_11->GetZaxis()->SetTitleSize(0.08);
   postfit_projy2_fail_stack_stack_11->GetZaxis()->SetTitleFont(42);
   postfit_projy2_fail_stack->SetHistogram(postfit_projy2_fail_stack_stack_11);
   
   Double_t xAxis58[2] = {50, 200}; 
   
   TH1D *Background_fail_postfit_projy2_stack_1 = new TH1D("Background_fail_postfit_projy2_stack_1","Background, fail, postfit, 1.0-1.0",1, xAxis58);
   Background_fail_postfit_projy2_stack_1->SetMinimum(0);
   Background_fail_postfit_projy2_stack_1->SetStats(0);

   ci = TColor::GetColor("#ffff00");
   Background_fail_postfit_projy2_stack_1->SetFillColor(ci);

   ci = 1190;
   color = new TColor(ci, 1, 1, 1, " ", 0);
   Background_fail_postfit_projy2_stack_1->SetLineColor(ci);
   Background_fail_postfit_projy2_stack_1->GetXaxis()->SetTitle("p_{T}");
   Background_fail_postfit_projy2_stack_1->GetXaxis()->SetLabelFont(42);
   Background_fail_postfit_projy2_stack_1->GetXaxis()->SetLabelSize(0.035);
   Background_fail_postfit_projy2_stack_1->GetXaxis()->SetTitleSize(0.035);
   Background_fail_postfit_projy2_stack_1->GetXaxis()->SetTitleOffset(0);
   Background_fail_postfit_projy2_stack_1->GetXaxis()->SetTitleFont(42);
   Background_fail_postfit_projy2_stack_1->GetYaxis()->SetTitle("Events / bin");
   Background_fail_postfit_projy2_stack_1->GetYaxis()->SetLabelFont(42);
   Background_fail_postfit_projy2_stack_1->GetYaxis()->SetLabelSize(0.035);
   Background_fail_postfit_projy2_stack_1->GetYaxis()->SetTitleSize(0.035);
   Background_fail_postfit_projy2_stack_1->GetYaxis()->SetTitleOffset(0);
   Background_fail_postfit_projy2_stack_1->GetYaxis()->SetTitleFont(42);
   Background_fail_postfit_projy2_stack_1->GetZaxis()->SetLabelFont(42);
   Background_fail_postfit_projy2_stack_1->GetZaxis()->SetLabelSize(0.035);
   Background_fail_postfit_projy2_stack_1->GetZaxis()->SetTitleSize(0.035);
   Background_fail_postfit_projy2_stack_1->GetZaxis()->SetTitleFont(42);
   postfit_projy2_fail_stack->Add(Background_fail_postfit_projy2_stack_1,"");
   postfit_projy2_fail_stack->Draw("hist same");
   
   postfit_projy2_fail_stack = new THStack();
   postfit_projy2_fail_stack->SetName("postfit_projy2_fail_stack");
   postfit_projy2_fail_stack->SetTitle("postfit_projy2_fail_stack");
   Double_t xAxis59[2] = {50, 200}; 
   
   TH1F *postfit_projy2_fail_stack_stack_11_stack_12 = new TH1F("postfit_projy2_fail_stack_stack_11_stack_12","postfit_projy2_fail_stack",1, xAxis59);
   postfit_projy2_fail_stack_stack_11_stack_12->SetMinimum(0);
   postfit_projy2_fail_stack_stack_11_stack_12->SetMaximum(0);
   postfit_projy2_fail_stack_stack_11_stack_12->SetDirectory(0);
   postfit_projy2_fail_stack_stack_11_stack_12->SetStats(0);
   postfit_projy2_fail_stack_stack_11_stack_12->SetLineStyle(0);
   postfit_projy2_fail_stack_stack_11_stack_12->GetXaxis()->SetLabelFont(42);
   postfit_projy2_fail_stack_stack_11_stack_12->GetXaxis()->SetLabelOffset(0.007);
   postfit_projy2_fail_stack_stack_11_stack_12->GetXaxis()->SetLabelSize(0.05);
   postfit_projy2_fail_stack_stack_11_stack_12->GetXaxis()->SetTitleSize(0.08);
   postfit_projy2_fail_stack_stack_11_stack_12->GetXaxis()->SetTitleOffset(0.9);
   postfit_projy2_fail_stack_stack_11_stack_12->GetXaxis()->SetTitleFont(42);
   postfit_projy2_fail_stack_stack_11_stack_12->GetYaxis()->SetNdivisions(508);
   postfit_projy2_fail_stack_stack_11_stack_12->GetYaxis()->SetLabelFont(42);
   postfit_projy2_fail_stack_stack_11_stack_12->GetYaxis()->SetLabelOffset(0.007);
   postfit_projy2_fail_stack_stack_11_stack_12->GetYaxis()->SetLabelSize(0.05);
   postfit_projy2_fail_stack_stack_11_stack_12->GetYaxis()->SetTitleSize(0.08);
   postfit_projy2_fail_stack_stack_11_stack_12->GetYaxis()->SetTitleOffset(1.25);
   postfit_projy2_fail_stack_stack_11_stack_12->GetYaxis()->SetTitleFont(42);
   postfit_projy2_fail_stack_stack_11_stack_12->GetZaxis()->SetLabelFont(42);
   postfit_projy2_fail_stack_stack_11_stack_12->GetZaxis()->SetLabelOffset(0.007);
   postfit_projy2_fail_stack_stack_11_stack_12->GetZaxis()->SetLabelSize(0.05);
   postfit_projy2_fail_stack_stack_11_stack_12->GetZaxis()->SetTitleSize(0.08);
   postfit_projy2_fail_stack_stack_11_stack_12->GetZaxis()->SetTitleFont(42);
   postfit_projy2_fail_stack->SetHistogram(postfit_projy2_fail_stack_stack_11_stack_12);
   
   Double_t xAxis60[2] = {50, 200}; 
   
   TH1D *Background_fail_postfit_projy2_stack_1_stack_1 = new TH1D("Background_fail_postfit_projy2_stack_1_stack_1","Background, fail, postfit, 1.0-1.0",1, xAxis60);
   Background_fail_postfit_projy2_stack_1_stack_1->SetMinimum(0);
   Background_fail_postfit_projy2_stack_1_stack_1->SetStats(0);

   ci = TColor::GetColor("#ffff00");
   Background_fail_postfit_projy2_stack_1_stack_1->SetFillColor(ci);

   ci = 1190;
   color = new TColor(ci, 1, 1, 1, " ", 0);
   Background_fail_postfit_projy2_stack_1_stack_1->SetLineColor(ci);
   Background_fail_postfit_projy2_stack_1_stack_1->GetXaxis()->SetTitle("p_{T}");
   Background_fail_postfit_projy2_stack_1_stack_1->GetXaxis()->SetLabelFont(42);
   Background_fail_postfit_projy2_stack_1_stack_1->GetXaxis()->SetLabelSize(0.035);
   Background_fail_postfit_projy2_stack_1_stack_1->GetXaxis()->SetTitleSize(0.035);
   Background_fail_postfit_projy2_stack_1_stack_1->GetXaxis()->SetTitleOffset(0);
   Background_fail_postfit_projy2_stack_1_stack_1->GetXaxis()->SetTitleFont(42);
   Background_fail_postfit_projy2_stack_1_stack_1->GetYaxis()->SetTitle("Events / bin");
   Background_fail_postfit_projy2_stack_1_stack_1->GetYaxis()->SetLabelFont(42);
   Background_fail_postfit_projy2_stack_1_stack_1->GetYaxis()->SetLabelSize(0.035);
   Background_fail_postfit_projy2_stack_1_stack_1->GetYaxis()->SetTitleSize(0.035);
   Background_fail_postfit_projy2_stack_1_stack_1->GetYaxis()->SetTitleOffset(0);
   Background_fail_postfit_projy2_stack_1_stack_1->GetYaxis()->SetTitleFont(42);
   Background_fail_postfit_projy2_stack_1_stack_1->GetZaxis()->SetLabelFont(42);
   Background_fail_postfit_projy2_stack_1_stack_1->GetZaxis()->SetLabelSize(0.035);
   Background_fail_postfit_projy2_stack_1_stack_1->GetZaxis()->SetTitleSize(0.035);
   Background_fail_postfit_projy2_stack_1_stack_1->GetZaxis()->SetTitleFont(42);
   postfit_projy2_fail_stack->Add(Background_fail_postfit_projy2_stack_1_stack_1,"");
   postfit_projy2_fail_stack->Draw("hist same");
   Double_t xAxis61[2] = {50, 200}; 
   
   TH1D *Signal_ppStaumI557_fail_postfit_projy2__37 = new TH1D("Signal_ppStaumI557_fail_postfit_projy2__37","HSCP signal, fail, postfit, 1.0-1.0",1, xAxis61);
   Signal_ppStaumI557_fail_postfit_projy2__37->SetMinimum(0);
   Signal_ppStaumI557_fail_postfit_projy2__37->SetStats(0);
   Signal_ppStaumI557_fail_postfit_projy2__37->SetLineColor(2);
   Signal_ppStaumI557_fail_postfit_projy2__37->GetXaxis()->SetTitle("p_{T}");
   Signal_ppStaumI557_fail_postfit_projy2__37->GetXaxis()->SetLabelFont(42);
   Signal_ppStaumI557_fail_postfit_projy2__37->GetXaxis()->SetLabelSize(0.035);
   Signal_ppStaumI557_fail_postfit_projy2__37->GetXaxis()->SetTitleSize(0.035);
   Signal_ppStaumI557_fail_postfit_projy2__37->GetXaxis()->SetTitleOffset(0);
   Signal_ppStaumI557_fail_postfit_projy2__37->GetXaxis()->SetTitleFont(42);
   Signal_ppStaumI557_fail_postfit_projy2__37->GetYaxis()->SetTitle("Events / bin");
   Signal_ppStaumI557_fail_postfit_projy2__37->GetYaxis()->SetLabelFont(42);
   Signal_ppStaumI557_fail_postfit_projy2__37->GetYaxis()->SetLabelSize(0.035);
   Signal_ppStaumI557_fail_postfit_projy2__37->GetYaxis()->SetTitleSize(0.035);
   Signal_ppStaumI557_fail_postfit_projy2__37->GetYaxis()->SetTitleOffset(0);
   Signal_ppStaumI557_fail_postfit_projy2__37->GetYaxis()->SetTitleFont(42);
   Signal_ppStaumI557_fail_postfit_projy2__37->GetZaxis()->SetLabelFont(42);
   Signal_ppStaumI557_fail_postfit_projy2__37->GetZaxis()->SetLabelSize(0.035);
   Signal_ppStaumI557_fail_postfit_projy2__37->GetZaxis()->SetTitleSize(0.035);
   Signal_ppStaumI557_fail_postfit_projy2__37->GetZaxis()->SetTitleFont(42);
   Signal_ppStaumI557_fail_postfit_projy2__37->Draw("hist same");
   Double_t xAxis62[2] = {50, 200}; 
   
   TH1D *TotalBkg_fail_postfit_projy2__38 = new TH1D("TotalBkg_fail_postfit_projy2__38","TotalBkg, fail, postfit, 1.0-1.0",1, xAxis62);
   TotalBkg_fail_postfit_projy2__38->SetMinimum(0);
   TotalBkg_fail_postfit_projy2__38->SetStats(0);
   TotalBkg_fail_postfit_projy2__38->SetMarkerStyle(0);
   TotalBkg_fail_postfit_projy2__38->GetXaxis()->SetTitle("p_{T}");
   TotalBkg_fail_postfit_projy2__38->GetXaxis()->SetLabelFont(42);
   TotalBkg_fail_postfit_projy2__38->GetXaxis()->SetLabelSize(0.035);
   TotalBkg_fail_postfit_projy2__38->GetXaxis()->SetTitleSize(0.035);
   TotalBkg_fail_postfit_projy2__38->GetXaxis()->SetTitleOffset(0);
   TotalBkg_fail_postfit_projy2__38->GetXaxis()->SetTitleFont(42);
   TotalBkg_fail_postfit_projy2__38->GetYaxis()->SetTitle("Events / bin");
   TotalBkg_fail_postfit_projy2__38->GetYaxis()->SetLabelFont(42);
   TotalBkg_fail_postfit_projy2__38->GetYaxis()->SetLabelSize(0.035);
   TotalBkg_fail_postfit_projy2__38->GetYaxis()->SetTitleSize(0.035);
   TotalBkg_fail_postfit_projy2__38->GetYaxis()->SetTitleOffset(0);
   TotalBkg_fail_postfit_projy2__38->GetYaxis()->SetTitleFont(42);
   TotalBkg_fail_postfit_projy2__38->GetZaxis()->SetLabelFont(42);
   TotalBkg_fail_postfit_projy2__38->GetZaxis()->SetLabelSize(0.035);
   TotalBkg_fail_postfit_projy2__38->GetZaxis()->SetTitleSize(0.035);
   TotalBkg_fail_postfit_projy2__38->GetZaxis()->SetTitleFont(42);
   TotalBkg_fail_postfit_projy2__38->Draw("hist same");
   Double_t xAxis63[2] = {50, 200}; 
   
   TH1D *TotalBkg_fail_postfit_projy2__39 = new TH1D("TotalBkg_fail_postfit_projy2__39","TotalBkg, fail, postfit, 1.0-1.0",1, xAxis63);
   TotalBkg_fail_postfit_projy2__39->SetMinimum(0);
   TotalBkg_fail_postfit_projy2__39->SetStats(0);
   TotalBkg_fail_postfit_projy2__39->SetFillColor(1);
   TotalBkg_fail_postfit_projy2__39->SetFillStyle(3354);
   TotalBkg_fail_postfit_projy2__39->SetLineWidth(0);
   TotalBkg_fail_postfit_projy2__39->SetMarkerStyle(0);
   TotalBkg_fail_postfit_projy2__39->GetXaxis()->SetTitle("p_{T}");
   TotalBkg_fail_postfit_projy2__39->GetXaxis()->SetLabelFont(42);
   TotalBkg_fail_postfit_projy2__39->GetXaxis()->SetLabelSize(0.035);
   TotalBkg_fail_postfit_projy2__39->GetXaxis()->SetTitleSize(0.035);
   TotalBkg_fail_postfit_projy2__39->GetXaxis()->SetTitleOffset(0);
   TotalBkg_fail_postfit_projy2__39->GetXaxis()->SetTitleFont(42);
   TotalBkg_fail_postfit_projy2__39->GetYaxis()->SetTitle("Events / bin");
   TotalBkg_fail_postfit_projy2__39->GetYaxis()->SetLabelFont(42);
   TotalBkg_fail_postfit_projy2__39->GetYaxis()->SetLabelSize(0.035);
   TotalBkg_fail_postfit_projy2__39->GetYaxis()->SetTitleSize(0.035);
   TotalBkg_fail_postfit_projy2__39->GetYaxis()->SetTitleOffset(0);
   TotalBkg_fail_postfit_projy2__39->GetYaxis()->SetTitleFont(42);
   TotalBkg_fail_postfit_projy2__39->GetZaxis()->SetLabelFont(42);
   TotalBkg_fail_postfit_projy2__39->GetZaxis()->SetLabelSize(0.035);
   TotalBkg_fail_postfit_projy2__39->GetZaxis()->SetTitleSize(0.035);
   TotalBkg_fail_postfit_projy2__39->GetZaxis()->SetTitleFont(42);
   TotalBkg_fail_postfit_projy2__39->Draw("e2 same");
   Double_t xAxis64[2] = {50, 200}; 
   
   TH1D *data_obs_fail_postfit_projy2__40 = new TH1D("data_obs_fail_postfit_projy2__40","",1, xAxis64);
   data_obs_fail_postfit_projy2__40->SetMinimum(0);
   data_obs_fail_postfit_projy2__40->SetMaximum(0);
   data_obs_fail_postfit_projy2__40->SetStats(0);

   ci = TColor::GetColor("#000000");
   data_obs_fail_postfit_projy2__40->SetLineColor(ci);

   ci = TColor::GetColor("#000000");
   data_obs_fail_postfit_projy2__40->SetMarkerColor(ci);
   data_obs_fail_postfit_projy2__40->SetMarkerStyle(8);
   data_obs_fail_postfit_projy2__40->GetXaxis()->SetTitle("p_{T}");
   data_obs_fail_postfit_projy2__40->GetXaxis()->SetLabelFont(42);
   data_obs_fail_postfit_projy2__40->GetXaxis()->SetLabelOffset(0.05);
   data_obs_fail_postfit_projy2__40->GetXaxis()->SetLabelSize(0.07);
   data_obs_fail_postfit_projy2__40->GetXaxis()->SetTitleSize(0.09);
   data_obs_fail_postfit_projy2__40->GetXaxis()->SetTitleOffset(1.15);
   data_obs_fail_postfit_projy2__40->GetXaxis()->SetTitleFont(42);
   data_obs_fail_postfit_projy2__40->GetYaxis()->SetTitle("Events / bin");
   data_obs_fail_postfit_projy2__40->GetYaxis()->SetNdivisions(508);
   data_obs_fail_postfit_projy2__40->GetYaxis()->SetLabelFont(42);
   data_obs_fail_postfit_projy2__40->GetYaxis()->SetLabelSize(0.07);
   data_obs_fail_postfit_projy2__40->GetYaxis()->SetTitleSize(0.09);
   data_obs_fail_postfit_projy2__40->GetYaxis()->SetTitleOffset(0.8);
   data_obs_fail_postfit_projy2__40->GetYaxis()->SetTitleFont(42);
   data_obs_fail_postfit_projy2__40->GetZaxis()->SetLabelFont(42);
   data_obs_fail_postfit_projy2__40->GetZaxis()->SetLabelSize(0.035);
   data_obs_fail_postfit_projy2__40->GetZaxis()->SetTitleSize(0.035);
   data_obs_fail_postfit_projy2__40->GetZaxis()->SetTitleFont(42);
   data_obs_fail_postfit_projy2__40->Draw("pe X0 same");
   
   TLegend *leg = new TLegend(0.65,0.64,0.9,0.88,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(1001);
   TLegendEntry *entry=leg->AddEntry("data_obs_fail_postfit_projy2","Data","pe X0");

   ci = TColor::GetColor("#000000");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);

   ci = TColor::GetColor("#000000");
   entry->SetMarkerColor(ci);
   entry->SetMarkerStyle(8);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("TotalBkg_fail_postfit_projy2","Total bkg unc.","F");
   entry->SetFillColor(1);
   entry->SetFillStyle(3354);
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("Signal_ppStau-557_fail_postfit_projy2","HSCP signal","L");
   entry->SetLineColor(2);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("Background_fail_postfit_projy2_stack_1_stack_1","Background","f");

   ci = TColor::GetColor("#ffff00");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = 1190;
   color = new TColor(ci, 1, 1, 1, " ", 0);
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   leg->Draw();
   Double_t xAxis65[2] = {50, 200}; 
   
   TH1D *data_obs_fail_postfit_projy2_copy__41 = new TH1D("data_obs_fail_postfit_projy2_copy__41","",1, xAxis65);
   data_obs_fail_postfit_projy2_copy__41->SetMinimum(0);
   data_obs_fail_postfit_projy2_copy__41->SetMaximum(0);
   data_obs_fail_postfit_projy2_copy__41->SetDirectory(0);
   data_obs_fail_postfit_projy2_copy__41->SetStats(0);

   ci = TColor::GetColor("#000000");
   data_obs_fail_postfit_projy2_copy__41->SetLineColor(ci);

   ci = TColor::GetColor("#000000");
   data_obs_fail_postfit_projy2_copy__41->SetMarkerColor(ci);
   data_obs_fail_postfit_projy2_copy__41->SetMarkerStyle(8);
   data_obs_fail_postfit_projy2_copy__41->GetXaxis()->SetTitle("p_{T}");
   data_obs_fail_postfit_projy2_copy__41->GetXaxis()->SetLabelFont(42);
   data_obs_fail_postfit_projy2_copy__41->GetXaxis()->SetLabelOffset(0.05);
   data_obs_fail_postfit_projy2_copy__41->GetXaxis()->SetLabelSize(0.07);
   data_obs_fail_postfit_projy2_copy__41->GetXaxis()->SetTitleSize(0.09);
   data_obs_fail_postfit_projy2_copy__41->GetXaxis()->SetTitleOffset(1.15);
   data_obs_fail_postfit_projy2_copy__41->GetXaxis()->SetTitleFont(42);
   data_obs_fail_postfit_projy2_copy__41->GetYaxis()->SetTitle("Events / bin");
   data_obs_fail_postfit_projy2_copy__41->GetYaxis()->SetNdivisions(508);
   data_obs_fail_postfit_projy2_copy__41->GetYaxis()->SetLabelFont(42);
   data_obs_fail_postfit_projy2_copy__41->GetYaxis()->SetLabelSize(0.07);
   data_obs_fail_postfit_projy2_copy__41->GetYaxis()->SetTitleSize(0.09);
   data_obs_fail_postfit_projy2_copy__41->GetYaxis()->SetTitleOffset(0.8);
   data_obs_fail_postfit_projy2_copy__41->GetYaxis()->SetTitleFont(42);
   data_obs_fail_postfit_projy2_copy__41->GetZaxis()->SetLabelFont(42);
   data_obs_fail_postfit_projy2_copy__41->GetZaxis()->SetLabelSize(0.035);
   data_obs_fail_postfit_projy2_copy__41->GetZaxis()->SetTitleSize(0.035);
   data_obs_fail_postfit_projy2_copy__41->GetZaxis()->SetTitleFont(42);
   data_obs_fail_postfit_projy2_copy__41->Draw("sameaxis");
   TLatex *   tex = new TLatex(0.21,0.83,"55 < p_{T} < 200 GeV, F^{Pixels}_{i} < 0.9");
tex->SetNDC();
   tex->SetTextAlign(12);
   tex->SetTextFont(42);
   tex->SetTextSize(0.06);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.17,0.92,"CMS");
tex->SetNDC();
   tex->SetTextFont(61);
   tex->SetTextSize(0.0675);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.25,0.92,"Preliminary");
tex->SetNDC();
   tex->SetTextFont(52);
   tex->SetTextSize(0.0485);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.95,0.92,"101 fb^{-1} (13 TeV)");
tex->SetNDC();
   tex->SetTextAlign(31);
   tex->SetTextFont(42);
   tex->SetTextSize(0.07);
   tex->SetLineWidth(2);
   tex->Draw();
   data_obs_fail_postfit_projy2_main->Modified();
   plots_fit_b/base_figs/postfit_projy2_fail->cd();
  
// ------------>Primitives in pad: data_obs_fail_postfit_projy2_sub
   TPad *data_obs_fail_postfit_projy2_sub = new TPad("data_obs_fail_postfit_projy2_sub", "data_obs_fail_postfit_projy2_sub",0,0,1,0.35);
   data_obs_fail_postfit_projy2_sub->Draw();
   data_obs_fail_postfit_projy2_sub->cd();
   data_obs_fail_postfit_projy2_sub->Range(17.30769,-6.023077,209.6154,2.9);
   data_obs_fail_postfit_projy2_sub->SetFillColor(0);
   data_obs_fail_postfit_projy2_sub->SetBorderMode(0);
   data_obs_fail_postfit_projy2_sub->SetBorderSize(2);
   data_obs_fail_postfit_projy2_sub->SetTickx(1);
   data_obs_fail_postfit_projy2_sub->SetTicky(1);
   data_obs_fail_postfit_projy2_sub->SetLeftMargin(0.17);
   data_obs_fail_postfit_projy2_sub->SetRightMargin(0.05);
   data_obs_fail_postfit_projy2_sub->SetTopMargin(0);
   data_obs_fail_postfit_projy2_sub->SetBottomMargin(0.35);
   data_obs_fail_postfit_projy2_sub->SetFrameFillStyle(0);
   data_obs_fail_postfit_projy2_sub->SetFrameBorderMode(0);
   data_obs_fail_postfit_projy2_sub->SetFrameFillStyle(0);
   data_obs_fail_postfit_projy2_sub->SetFrameBorderMode(0);
   Double_t xAxis66[2] = {50, 200}; 
   
   TH1D *data_obs_fail_postfit_projy2_pull__42 = new TH1D("data_obs_fail_postfit_projy2_pull__42","",1, xAxis66);
   data_obs_fail_postfit_projy2_pull__42->SetMinimum(-2.9);
   data_obs_fail_postfit_projy2_pull__42->SetMaximum(2.9);
   data_obs_fail_postfit_projy2_pull__42->SetEntries(2);
   data_obs_fail_postfit_projy2_pull__42->SetStats(0);

   ci = TColor::GetColor("#0000ff");
   data_obs_fail_postfit_projy2_pull__42->SetFillColor(ci);

   ci = TColor::GetColor("#000000");
   data_obs_fail_postfit_projy2_pull__42->SetLineColor(ci);

   ci = TColor::GetColor("#000000");
   data_obs_fail_postfit_projy2_pull__42->SetMarkerColor(ci);
   data_obs_fail_postfit_projy2_pull__42->SetMarkerStyle(8);
   data_obs_fail_postfit_projy2_pull__42->GetXaxis()->SetTitle("p_{T}");
   data_obs_fail_postfit_projy2_pull__42->GetXaxis()->SetLabelFont(42);
   data_obs_fail_postfit_projy2_pull__42->GetXaxis()->SetLabelOffset(0.05);
   data_obs_fail_postfit_projy2_pull__42->GetXaxis()->SetLabelSize(0.13);
   data_obs_fail_postfit_projy2_pull__42->GetXaxis()->SetTitleSize(0.15);
   data_obs_fail_postfit_projy2_pull__42->GetXaxis()->SetTitleOffset(1.15);
   data_obs_fail_postfit_projy2_pull__42->GetXaxis()->SetTitleFont(42);
   data_obs_fail_postfit_projy2_pull__42->GetYaxis()->SetTitle("(Data-Bkg)/#sigma");
   data_obs_fail_postfit_projy2_pull__42->GetYaxis()->SetNdivisions(306);
   data_obs_fail_postfit_projy2_pull__42->GetYaxis()->SetLabelFont(42);
   data_obs_fail_postfit_projy2_pull__42->GetYaxis()->SetLabelSize(0.13);
   data_obs_fail_postfit_projy2_pull__42->GetYaxis()->SetTitleSize(0.12);
   data_obs_fail_postfit_projy2_pull__42->GetYaxis()->SetTitleOffset(0.4);
   data_obs_fail_postfit_projy2_pull__42->GetYaxis()->SetTitleFont(42);
   data_obs_fail_postfit_projy2_pull__42->GetZaxis()->SetLabelFont(42);
   data_obs_fail_postfit_projy2_pull__42->GetZaxis()->SetLabelSize(0.035);
   data_obs_fail_postfit_projy2_pull__42->GetZaxis()->SetTitleSize(0.035);
   data_obs_fail_postfit_projy2_pull__42->GetZaxis()->SetTitleFont(42);
   data_obs_fail_postfit_projy2_pull__42->Draw("hist");
   data_obs_fail_postfit_projy2_sub->Modified();
   plots_fit_b/base_figs/postfit_projy2_fail->cd();
   plots_fit_b/base_figs/postfit_projy2_fail->Modified();
   plots_fit_b/base_figs/postfit_projy2_fail->cd();
   plots_fit_b/base_figs/postfit_projy2_fail->SetSelected(plots_fit_b/base_figs/postfit_projy2_fail);
}
