void postfit_projy2_fail_logy()
{
//=========Macro generated from canvas: plots_fit_b/base_figs/postfit_projy2_fail_logy/plots_fit_b/base_figs/postfit_projy2_fail_logy
//=========  (Fri Jan 12 21:00:02 2024) by ROOT version 6.14/09
   TCanvas *plots_fit_b/base_figs/postfit_projy2_fail_logy = new TCanvas("plots_fit_b/base_figs/postfit_projy2_fail_logy", "plots_fit_b/base_figs/postfit_projy2_fail_logy",0,0,800,700);
   gStyle->SetOptFit(1);
   gStyle->SetOptStat(0);
   plots_fit_b/base_figs/postfit_projy2_fail_logy->SetHighLightColor(2);
   plots_fit_b/base_figs/postfit_projy2_fail_logy->Range(0,0,1,1);
   plots_fit_b/base_figs/postfit_projy2_fail_logy->SetFillColor(0);
   plots_fit_b/base_figs/postfit_projy2_fail_logy->SetBorderMode(0);
   plots_fit_b/base_figs/postfit_projy2_fail_logy->SetBorderSize(2);
   plots_fit_b/base_figs/postfit_projy2_fail_logy->SetTickx(1);
   plots_fit_b/base_figs/postfit_projy2_fail_logy->SetTicky(1);
   plots_fit_b/base_figs/postfit_projy2_fail_logy->SetLeftMargin(0.16);
   plots_fit_b/base_figs/postfit_projy2_fail_logy->SetRightMargin(0);
   plots_fit_b/base_figs/postfit_projy2_fail_logy->SetTopMargin(0);
   plots_fit_b/base_figs/postfit_projy2_fail_logy->SetBottomMargin(0);
   plots_fit_b/base_figs/postfit_projy2_fail_logy->SetFrameFillStyle(0);
   plots_fit_b/base_figs/postfit_projy2_fail_logy->SetFrameBorderMode(0);
  
// ------------>Primitives in pad: data_obs_fail_postfit_projy2_main
   TPad *data_obs_fail_postfit_projy2_main = new TPad("data_obs_fail_postfit_projy2_main", "data_obs_fail_postfit_projy2_main",0,0.35,1,1);
   data_obs_fail_postfit_projy2_main->Draw();
   data_obs_fail_postfit_projy2_main->cd();
   data_obs_fail_postfit_projy2_main->Range(17.30769,-2.139535,209.6154,1.348837);
   data_obs_fail_postfit_projy2_main->SetFillColor(0);
   data_obs_fail_postfit_projy2_main->SetBorderMode(0);
   data_obs_fail_postfit_projy2_main->SetBorderSize(2);
   data_obs_fail_postfit_projy2_main->SetLogy();
   data_obs_fail_postfit_projy2_main->SetTickx(1);
   data_obs_fail_postfit_projy2_main->SetTicky(1);
   data_obs_fail_postfit_projy2_main->SetLeftMargin(0.17);
   data_obs_fail_postfit_projy2_main->SetRightMargin(0.05);
   data_obs_fail_postfit_projy2_main->SetBottomMargin(0.04);
   data_obs_fail_postfit_projy2_main->SetFrameFillStyle(0);
   data_obs_fail_postfit_projy2_main->SetFrameBorderMode(0);
   data_obs_fail_postfit_projy2_main->SetFrameFillStyle(0);
   data_obs_fail_postfit_projy2_main->SetFrameBorderMode(0);
   Double_t xAxis122[2] = {50, 200}; 
   
   TH1D *data_obs_fail_postfit_projy2__78 = new TH1D("data_obs_fail_postfit_projy2__78","",1, xAxis122);
   data_obs_fail_postfit_projy2__78->SetMinimum(0.001);
   data_obs_fail_postfit_projy2__78->SetMaximum(0);
   data_obs_fail_postfit_projy2__78->SetStats(0);

   Int_t ci;      // for color index setting
   TColor *color; // for color definition with alpha
   ci = TColor::GetColor("#000000");
   data_obs_fail_postfit_projy2__78->SetLineColor(ci);

   ci = TColor::GetColor("#000000");
   data_obs_fail_postfit_projy2__78->SetMarkerColor(ci);
   data_obs_fail_postfit_projy2__78->SetMarkerStyle(8);
   data_obs_fail_postfit_projy2__78->GetXaxis()->SetTitle("p_{T}");
   data_obs_fail_postfit_projy2__78->GetXaxis()->SetLabelFont(42);
   data_obs_fail_postfit_projy2__78->GetXaxis()->SetLabelOffset(0.05);
   data_obs_fail_postfit_projy2__78->GetXaxis()->SetLabelSize(0.07);
   data_obs_fail_postfit_projy2__78->GetXaxis()->SetTitleSize(0.09);
   data_obs_fail_postfit_projy2__78->GetXaxis()->SetTitleOffset(1.15);
   data_obs_fail_postfit_projy2__78->GetXaxis()->SetTitleFont(42);
   data_obs_fail_postfit_projy2__78->GetYaxis()->SetTitle("Events / bin");
   data_obs_fail_postfit_projy2__78->GetYaxis()->SetNdivisions(508);
   data_obs_fail_postfit_projy2__78->GetYaxis()->SetLabelFont(42);
   data_obs_fail_postfit_projy2__78->GetYaxis()->SetLabelSize(0.07);
   data_obs_fail_postfit_projy2__78->GetYaxis()->SetTitleSize(0.09);
   data_obs_fail_postfit_projy2__78->GetYaxis()->SetTitleOffset(0.8);
   data_obs_fail_postfit_projy2__78->GetYaxis()->SetTitleFont(42);
   data_obs_fail_postfit_projy2__78->GetZaxis()->SetLabelFont(42);
   data_obs_fail_postfit_projy2__78->GetZaxis()->SetLabelSize(0.035);
   data_obs_fail_postfit_projy2__78->GetZaxis()->SetTitleSize(0.035);
   data_obs_fail_postfit_projy2__78->GetZaxis()->SetTitleFont(42);
   data_obs_fail_postfit_projy2__78->Draw("pe X0");
   
   THStack *postfit_projy2_fail_logy_stack = new THStack();
   postfit_projy2_fail_logy_stack->SetName("postfit_projy2_fail_logy_stack");
   postfit_projy2_fail_logy_stack->SetTitle("postfit_projy2_fail_logy_stack");
   postfit_projy2_fail_logy_stack->SetMinimum(0.001);
   Double_t xAxis123[2] = {50, 200}; 
   
   TH1F *postfit_projy2_fail_logy_stack_stack_23 = new TH1F("postfit_projy2_fail_logy_stack_stack_23","postfit_projy2_fail_logy_stack",1, xAxis123);
   postfit_projy2_fail_logy_stack_stack_23->SetMinimum(-0);
   postfit_projy2_fail_logy_stack_stack_23->SetMaximum(-nan);
   postfit_projy2_fail_logy_stack_stack_23->SetDirectory(0);
   postfit_projy2_fail_logy_stack_stack_23->SetStats(0);
   postfit_projy2_fail_logy_stack_stack_23->SetLineStyle(0);
   postfit_projy2_fail_logy_stack_stack_23->GetXaxis()->SetLabelFont(42);
   postfit_projy2_fail_logy_stack_stack_23->GetXaxis()->SetLabelOffset(0.007);
   postfit_projy2_fail_logy_stack_stack_23->GetXaxis()->SetLabelSize(0.05);
   postfit_projy2_fail_logy_stack_stack_23->GetXaxis()->SetTitleSize(0.08);
   postfit_projy2_fail_logy_stack_stack_23->GetXaxis()->SetTitleOffset(0.9);
   postfit_projy2_fail_logy_stack_stack_23->GetXaxis()->SetTitleFont(42);
   postfit_projy2_fail_logy_stack_stack_23->GetYaxis()->SetNdivisions(508);
   postfit_projy2_fail_logy_stack_stack_23->GetYaxis()->SetLabelFont(42);
   postfit_projy2_fail_logy_stack_stack_23->GetYaxis()->SetLabelOffset(0.007);
   postfit_projy2_fail_logy_stack_stack_23->GetYaxis()->SetLabelSize(0.05);
   postfit_projy2_fail_logy_stack_stack_23->GetYaxis()->SetTitleSize(0.08);
   postfit_projy2_fail_logy_stack_stack_23->GetYaxis()->SetTitleOffset(1.25);
   postfit_projy2_fail_logy_stack_stack_23->GetYaxis()->SetTitleFont(42);
   postfit_projy2_fail_logy_stack_stack_23->GetZaxis()->SetLabelFont(42);
   postfit_projy2_fail_logy_stack_stack_23->GetZaxis()->SetLabelOffset(0.007);
   postfit_projy2_fail_logy_stack_stack_23->GetZaxis()->SetLabelSize(0.05);
   postfit_projy2_fail_logy_stack_stack_23->GetZaxis()->SetTitleSize(0.08);
   postfit_projy2_fail_logy_stack_stack_23->GetZaxis()->SetTitleFont(42);
   postfit_projy2_fail_logy_stack->SetHistogram(postfit_projy2_fail_logy_stack_stack_23);
   
   Double_t xAxis124[2] = {50, 200}; 
   
   TH1D *Background_fail_postfit_projy2_stack_1 = new TH1D("Background_fail_postfit_projy2_stack_1","Background, fail, postfit, 1.0-1.0",1, xAxis124);
   Background_fail_postfit_projy2_stack_1->SetMinimum(0.001);
   Background_fail_postfit_projy2_stack_1->SetStats(0);

   ci = TColor::GetColor("#ffff00");
   Background_fail_postfit_projy2_stack_1->SetFillColor(ci);

   ci = 1190;
   color = new TColor(ci, 1, 1, 1, " ", 0);
   Background_fail_postfit_projy2_stack_1->SetLineColor(ci);
   Background_fail_postfit_projy2_stack_1->GetXaxis()->SetTitle("p_{T}");
   Background_fail_postfit_projy2_stack_1->GetXaxis()->SetLabelFont(42);
   Background_fail_postfit_projy2_stack_1->GetXaxis()->SetLabelSize(0.035);
   Background_fail_postfit_projy2_stack_1->GetXaxis()->SetTitleSize(0.035);
   Background_fail_postfit_projy2_stack_1->GetXaxis()->SetTitleOffset(0);
   Background_fail_postfit_projy2_stack_1->GetXaxis()->SetTitleFont(42);
   Background_fail_postfit_projy2_stack_1->GetYaxis()->SetTitle("Events / bin");
   Background_fail_postfit_projy2_stack_1->GetYaxis()->SetLabelFont(42);
   Background_fail_postfit_projy2_stack_1->GetYaxis()->SetLabelSize(0.035);
   Background_fail_postfit_projy2_stack_1->GetYaxis()->SetTitleSize(0.035);
   Background_fail_postfit_projy2_stack_1->GetYaxis()->SetTitleOffset(0);
   Background_fail_postfit_projy2_stack_1->GetYaxis()->SetTitleFont(42);
   Background_fail_postfit_projy2_stack_1->GetZaxis()->SetLabelFont(42);
   Background_fail_postfit_projy2_stack_1->GetZaxis()->SetLabelSize(0.035);
   Background_fail_postfit_projy2_stack_1->GetZaxis()->SetTitleSize(0.035);
   Background_fail_postfit_projy2_stack_1->GetZaxis()->SetTitleFont(42);
   postfit_projy2_fail_logy_stack->Add(Background_fail_postfit_projy2_stack_1,"");
   postfit_projy2_fail_logy_stack->Draw("hist same");
   
   postfit_projy2_fail_logy_stack = new THStack();
   postfit_projy2_fail_logy_stack->SetName("postfit_projy2_fail_logy_stack");
   postfit_projy2_fail_logy_stack->SetTitle("postfit_projy2_fail_logy_stack");
   postfit_projy2_fail_logy_stack->SetMinimum(0.001);
   Double_t xAxis125[2] = {50, 200}; 
   
   TH1F *postfit_projy2_fail_logy_stack_stack_23_stack_24 = new TH1F("postfit_projy2_fail_logy_stack_stack_23_stack_24","postfit_projy2_fail_logy_stack",1, xAxis125);
   postfit_projy2_fail_logy_stack_stack_23_stack_24->SetMinimum(-0);
   postfit_projy2_fail_logy_stack_stack_23_stack_24->SetMaximum(-nan);
   postfit_projy2_fail_logy_stack_stack_23_stack_24->SetDirectory(0);
   postfit_projy2_fail_logy_stack_stack_23_stack_24->SetStats(0);
   postfit_projy2_fail_logy_stack_stack_23_stack_24->SetLineStyle(0);
   postfit_projy2_fail_logy_stack_stack_23_stack_24->GetXaxis()->SetLabelFont(42);
   postfit_projy2_fail_logy_stack_stack_23_stack_24->GetXaxis()->SetLabelOffset(0.007);
   postfit_projy2_fail_logy_stack_stack_23_stack_24->GetXaxis()->SetLabelSize(0.05);
   postfit_projy2_fail_logy_stack_stack_23_stack_24->GetXaxis()->SetTitleSize(0.08);
   postfit_projy2_fail_logy_stack_stack_23_stack_24->GetXaxis()->SetTitleOffset(0.9);
   postfit_projy2_fail_logy_stack_stack_23_stack_24->GetXaxis()->SetTitleFont(42);
   postfit_projy2_fail_logy_stack_stack_23_stack_24->GetYaxis()->SetNdivisions(508);
   postfit_projy2_fail_logy_stack_stack_23_stack_24->GetYaxis()->SetLabelFont(42);
   postfit_projy2_fail_logy_stack_stack_23_stack_24->GetYaxis()->SetLabelOffset(0.007);
   postfit_projy2_fail_logy_stack_stack_23_stack_24->GetYaxis()->SetLabelSize(0.05);
   postfit_projy2_fail_logy_stack_stack_23_stack_24->GetYaxis()->SetTitleSize(0.08);
   postfit_projy2_fail_logy_stack_stack_23_stack_24->GetYaxis()->SetTitleOffset(1.25);
   postfit_projy2_fail_logy_stack_stack_23_stack_24->GetYaxis()->SetTitleFont(42);
   postfit_projy2_fail_logy_stack_stack_23_stack_24->GetZaxis()->SetLabelFont(42);
   postfit_projy2_fail_logy_stack_stack_23_stack_24->GetZaxis()->SetLabelOffset(0.007);
   postfit_projy2_fail_logy_stack_stack_23_stack_24->GetZaxis()->SetLabelSize(0.05);
   postfit_projy2_fail_logy_stack_stack_23_stack_24->GetZaxis()->SetTitleSize(0.08);
   postfit_projy2_fail_logy_stack_stack_23_stack_24->GetZaxis()->SetTitleFont(42);
   postfit_projy2_fail_logy_stack->SetHistogram(postfit_projy2_fail_logy_stack_stack_23_stack_24);
   
   Double_t xAxis126[2] = {50, 200}; 
   
   TH1D *Background_fail_postfit_projy2_stack_1_stack_1 = new TH1D("Background_fail_postfit_projy2_stack_1_stack_1","Background, fail, postfit, 1.0-1.0",1, xAxis126);
   Background_fail_postfit_projy2_stack_1_stack_1->SetMinimum(0.001);
   Background_fail_postfit_projy2_stack_1_stack_1->SetStats(0);

   ci = TColor::GetColor("#ffff00");
   Background_fail_postfit_projy2_stack_1_stack_1->SetFillColor(ci);

   ci = 1190;
   color = new TColor(ci, 1, 1, 1, " ", 0);
   Background_fail_postfit_projy2_stack_1_stack_1->SetLineColor(ci);
   Background_fail_postfit_projy2_stack_1_stack_1->GetXaxis()->SetTitle("p_{T}");
   Background_fail_postfit_projy2_stack_1_stack_1->GetXaxis()->SetLabelFont(42);
   Background_fail_postfit_projy2_stack_1_stack_1->GetXaxis()->SetLabelSize(0.035);
   Background_fail_postfit_projy2_stack_1_stack_1->GetXaxis()->SetTitleSize(0.035);
   Background_fail_postfit_projy2_stack_1_stack_1->GetXaxis()->SetTitleOffset(0);
   Background_fail_postfit_projy2_stack_1_stack_1->GetXaxis()->SetTitleFont(42);
   Background_fail_postfit_projy2_stack_1_stack_1->GetYaxis()->SetTitle("Events / bin");
   Background_fail_postfit_projy2_stack_1_stack_1->GetYaxis()->SetLabelFont(42);
   Background_fail_postfit_projy2_stack_1_stack_1->GetYaxis()->SetLabelSize(0.035);
   Background_fail_postfit_projy2_stack_1_stack_1->GetYaxis()->SetTitleSize(0.035);
   Background_fail_postfit_projy2_stack_1_stack_1->GetYaxis()->SetTitleOffset(0);
   Background_fail_postfit_projy2_stack_1_stack_1->GetYaxis()->SetTitleFont(42);
   Background_fail_postfit_projy2_stack_1_stack_1->GetZaxis()->SetLabelFont(42);
   Background_fail_postfit_projy2_stack_1_stack_1->GetZaxis()->SetLabelSize(0.035);
   Background_fail_postfit_projy2_stack_1_stack_1->GetZaxis()->SetTitleSize(0.035);
   Background_fail_postfit_projy2_stack_1_stack_1->GetZaxis()->SetTitleFont(42);
   postfit_projy2_fail_logy_stack->Add(Background_fail_postfit_projy2_stack_1_stack_1,"");
   postfit_projy2_fail_logy_stack->Draw("hist same");
   Double_t xAxis127[2] = {50, 200}; 
   
   TH1D *Signal_ppStaumI557_fail_postfit_projy2__79 = new TH1D("Signal_ppStaumI557_fail_postfit_projy2__79","HSCP signal, fail, postfit, 1.0-1.0",1, xAxis127);
   Signal_ppStaumI557_fail_postfit_projy2__79->SetMinimum(0.001);
   Signal_ppStaumI557_fail_postfit_projy2__79->SetStats(0);
   Signal_ppStaumI557_fail_postfit_projy2__79->SetLineColor(2);
   Signal_ppStaumI557_fail_postfit_projy2__79->GetXaxis()->SetTitle("p_{T}");
   Signal_ppStaumI557_fail_postfit_projy2__79->GetXaxis()->SetLabelFont(42);
   Signal_ppStaumI557_fail_postfit_projy2__79->GetXaxis()->SetLabelSize(0.035);
   Signal_ppStaumI557_fail_postfit_projy2__79->GetXaxis()->SetTitleSize(0.035);
   Signal_ppStaumI557_fail_postfit_projy2__79->GetXaxis()->SetTitleOffset(0);
   Signal_ppStaumI557_fail_postfit_projy2__79->GetXaxis()->SetTitleFont(42);
   Signal_ppStaumI557_fail_postfit_projy2__79->GetYaxis()->SetTitle("Events / bin");
   Signal_ppStaumI557_fail_postfit_projy2__79->GetYaxis()->SetLabelFont(42);
   Signal_ppStaumI557_fail_postfit_projy2__79->GetYaxis()->SetLabelSize(0.035);
   Signal_ppStaumI557_fail_postfit_projy2__79->GetYaxis()->SetTitleSize(0.035);
   Signal_ppStaumI557_fail_postfit_projy2__79->GetYaxis()->SetTitleOffset(0);
   Signal_ppStaumI557_fail_postfit_projy2__79->GetYaxis()->SetTitleFont(42);
   Signal_ppStaumI557_fail_postfit_projy2__79->GetZaxis()->SetLabelFont(42);
   Signal_ppStaumI557_fail_postfit_projy2__79->GetZaxis()->SetLabelSize(0.035);
   Signal_ppStaumI557_fail_postfit_projy2__79->GetZaxis()->SetTitleSize(0.035);
   Signal_ppStaumI557_fail_postfit_projy2__79->GetZaxis()->SetTitleFont(42);
   Signal_ppStaumI557_fail_postfit_projy2__79->Draw("hist same");
   Double_t xAxis128[2] = {50, 200}; 
   
   TH1D *TotalBkg_fail_postfit_projy2__80 = new TH1D("TotalBkg_fail_postfit_projy2__80","TotalBkg, fail, postfit, 1.0-1.0",1, xAxis128);
   TotalBkg_fail_postfit_projy2__80->SetMinimum(0.001);
   TotalBkg_fail_postfit_projy2__80->SetStats(0);
   TotalBkg_fail_postfit_projy2__80->SetMarkerStyle(0);
   TotalBkg_fail_postfit_projy2__80->GetXaxis()->SetTitle("p_{T}");
   TotalBkg_fail_postfit_projy2__80->GetXaxis()->SetLabelFont(42);
   TotalBkg_fail_postfit_projy2__80->GetXaxis()->SetLabelSize(0.035);
   TotalBkg_fail_postfit_projy2__80->GetXaxis()->SetTitleSize(0.035);
   TotalBkg_fail_postfit_projy2__80->GetXaxis()->SetTitleOffset(0);
   TotalBkg_fail_postfit_projy2__80->GetXaxis()->SetTitleFont(42);
   TotalBkg_fail_postfit_projy2__80->GetYaxis()->SetTitle("Events / bin");
   TotalBkg_fail_postfit_projy2__80->GetYaxis()->SetLabelFont(42);
   TotalBkg_fail_postfit_projy2__80->GetYaxis()->SetLabelSize(0.035);
   TotalBkg_fail_postfit_projy2__80->GetYaxis()->SetTitleSize(0.035);
   TotalBkg_fail_postfit_projy2__80->GetYaxis()->SetTitleOffset(0);
   TotalBkg_fail_postfit_projy2__80->GetYaxis()->SetTitleFont(42);
   TotalBkg_fail_postfit_projy2__80->GetZaxis()->SetLabelFont(42);
   TotalBkg_fail_postfit_projy2__80->GetZaxis()->SetLabelSize(0.035);
   TotalBkg_fail_postfit_projy2__80->GetZaxis()->SetTitleSize(0.035);
   TotalBkg_fail_postfit_projy2__80->GetZaxis()->SetTitleFont(42);
   TotalBkg_fail_postfit_projy2__80->Draw("hist same");
   Double_t xAxis129[2] = {50, 200}; 
   
   TH1D *TotalBkg_fail_postfit_projy2__81 = new TH1D("TotalBkg_fail_postfit_projy2__81","TotalBkg, fail, postfit, 1.0-1.0",1, xAxis129);
   TotalBkg_fail_postfit_projy2__81->SetMinimum(0.001);
   TotalBkg_fail_postfit_projy2__81->SetStats(0);
   TotalBkg_fail_postfit_projy2__81->SetFillColor(1);
   TotalBkg_fail_postfit_projy2__81->SetFillStyle(3354);
   TotalBkg_fail_postfit_projy2__81->SetLineWidth(0);
   TotalBkg_fail_postfit_projy2__81->SetMarkerStyle(0);
   TotalBkg_fail_postfit_projy2__81->GetXaxis()->SetTitle("p_{T}");
   TotalBkg_fail_postfit_projy2__81->GetXaxis()->SetLabelFont(42);
   TotalBkg_fail_postfit_projy2__81->GetXaxis()->SetLabelSize(0.035);
   TotalBkg_fail_postfit_projy2__81->GetXaxis()->SetTitleSize(0.035);
   TotalBkg_fail_postfit_projy2__81->GetXaxis()->SetTitleOffset(0);
   TotalBkg_fail_postfit_projy2__81->GetXaxis()->SetTitleFont(42);
   TotalBkg_fail_postfit_projy2__81->GetYaxis()->SetTitle("Events / bin");
   TotalBkg_fail_postfit_projy2__81->GetYaxis()->SetLabelFont(42);
   TotalBkg_fail_postfit_projy2__81->GetYaxis()->SetLabelSize(0.035);
   TotalBkg_fail_postfit_projy2__81->GetYaxis()->SetTitleSize(0.035);
   TotalBkg_fail_postfit_projy2__81->GetYaxis()->SetTitleOffset(0);
   TotalBkg_fail_postfit_projy2__81->GetYaxis()->SetTitleFont(42);
   TotalBkg_fail_postfit_projy2__81->GetZaxis()->SetLabelFont(42);
   TotalBkg_fail_postfit_projy2__81->GetZaxis()->SetLabelSize(0.035);
   TotalBkg_fail_postfit_projy2__81->GetZaxis()->SetTitleSize(0.035);
   TotalBkg_fail_postfit_projy2__81->GetZaxis()->SetTitleFont(42);
   TotalBkg_fail_postfit_projy2__81->Draw("e2 same");
   Double_t xAxis130[2] = {50, 200}; 
   
   TH1D *data_obs_fail_postfit_projy2__82 = new TH1D("data_obs_fail_postfit_projy2__82","",1, xAxis130);
   data_obs_fail_postfit_projy2__82->SetMinimum(0.001);
   data_obs_fail_postfit_projy2__82->SetMaximum(0);
   data_obs_fail_postfit_projy2__82->SetStats(0);

   ci = TColor::GetColor("#000000");
   data_obs_fail_postfit_projy2__82->SetLineColor(ci);

   ci = TColor::GetColor("#000000");
   data_obs_fail_postfit_projy2__82->SetMarkerColor(ci);
   data_obs_fail_postfit_projy2__82->SetMarkerStyle(8);
   data_obs_fail_postfit_projy2__82->GetXaxis()->SetTitle("p_{T}");
   data_obs_fail_postfit_projy2__82->GetXaxis()->SetLabelFont(42);
   data_obs_fail_postfit_projy2__82->GetXaxis()->SetLabelOffset(0.05);
   data_obs_fail_postfit_projy2__82->GetXaxis()->SetLabelSize(0.07);
   data_obs_fail_postfit_projy2__82->GetXaxis()->SetTitleSize(0.09);
   data_obs_fail_postfit_projy2__82->GetXaxis()->SetTitleOffset(1.15);
   data_obs_fail_postfit_projy2__82->GetXaxis()->SetTitleFont(42);
   data_obs_fail_postfit_projy2__82->GetYaxis()->SetTitle("Events / bin");
   data_obs_fail_postfit_projy2__82->GetYaxis()->SetNdivisions(508);
   data_obs_fail_postfit_projy2__82->GetYaxis()->SetLabelFont(42);
   data_obs_fail_postfit_projy2__82->GetYaxis()->SetLabelSize(0.07);
   data_obs_fail_postfit_projy2__82->GetYaxis()->SetTitleSize(0.09);
   data_obs_fail_postfit_projy2__82->GetYaxis()->SetTitleOffset(0.8);
   data_obs_fail_postfit_projy2__82->GetYaxis()->SetTitleFont(42);
   data_obs_fail_postfit_projy2__82->GetZaxis()->SetLabelFont(42);
   data_obs_fail_postfit_projy2__82->GetZaxis()->SetLabelSize(0.035);
   data_obs_fail_postfit_projy2__82->GetZaxis()->SetTitleSize(0.035);
   data_obs_fail_postfit_projy2__82->GetZaxis()->SetTitleFont(42);
   data_obs_fail_postfit_projy2__82->Draw("pe X0 same");
   
   TLegend *leg = new TLegend(0.65,0.64,0.9,0.88,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(1001);
   TLegendEntry *entry=leg->AddEntry("data_obs_fail_postfit_projy2","Data","pe X0");

   ci = TColor::GetColor("#000000");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);

   ci = TColor::GetColor("#000000");
   entry->SetMarkerColor(ci);
   entry->SetMarkerStyle(8);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("TotalBkg_fail_postfit_projy2","Total bkg unc.","F");
   entry->SetFillColor(1);
   entry->SetFillStyle(3354);
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("Signal_ppStau-557_fail_postfit_projy2","HSCP signal","L");
   entry->SetLineColor(2);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("Background_fail_postfit_projy2_stack_1_stack_1","Background","f");

   ci = TColor::GetColor("#ffff00");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = 1190;
   color = new TColor(ci, 1, 1, 1, " ", 0);
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   leg->Draw();
   Double_t xAxis131[2] = {50, 200}; 
   
   TH1D *data_obs_fail_postfit_projy2_copy__83 = new TH1D("data_obs_fail_postfit_projy2_copy__83","",1, xAxis131);
   data_obs_fail_postfit_projy2_copy__83->SetMinimum(0.001);
   data_obs_fail_postfit_projy2_copy__83->SetMaximum(0);
   data_obs_fail_postfit_projy2_copy__83->SetDirectory(0);
   data_obs_fail_postfit_projy2_copy__83->SetStats(0);

   ci = TColor::GetColor("#000000");
   data_obs_fail_postfit_projy2_copy__83->SetLineColor(ci);

   ci = TColor::GetColor("#000000");
   data_obs_fail_postfit_projy2_copy__83->SetMarkerColor(ci);
   data_obs_fail_postfit_projy2_copy__83->SetMarkerStyle(8);
   data_obs_fail_postfit_projy2_copy__83->GetXaxis()->SetTitle("p_{T}");
   data_obs_fail_postfit_projy2_copy__83->GetXaxis()->SetLabelFont(42);
   data_obs_fail_postfit_projy2_copy__83->GetXaxis()->SetLabelOffset(0.05);
   data_obs_fail_postfit_projy2_copy__83->GetXaxis()->SetLabelSize(0.07);
   data_obs_fail_postfit_projy2_copy__83->GetXaxis()->SetTitleSize(0.09);
   data_obs_fail_postfit_projy2_copy__83->GetXaxis()->SetTitleOffset(1.15);
   data_obs_fail_postfit_projy2_copy__83->GetXaxis()->SetTitleFont(42);
   data_obs_fail_postfit_projy2_copy__83->GetYaxis()->SetTitle("Events / bin");
   data_obs_fail_postfit_projy2_copy__83->GetYaxis()->SetNdivisions(508);
   data_obs_fail_postfit_projy2_copy__83->GetYaxis()->SetLabelFont(42);
   data_obs_fail_postfit_projy2_copy__83->GetYaxis()->SetLabelSize(0.07);
   data_obs_fail_postfit_projy2_copy__83->GetYaxis()->SetTitleSize(0.09);
   data_obs_fail_postfit_projy2_copy__83->GetYaxis()->SetTitleOffset(0.8);
   data_obs_fail_postfit_projy2_copy__83->GetYaxis()->SetTitleFont(42);
   data_obs_fail_postfit_projy2_copy__83->GetZaxis()->SetLabelFont(42);
   data_obs_fail_postfit_projy2_copy__83->GetZaxis()->SetLabelSize(0.035);
   data_obs_fail_postfit_projy2_copy__83->GetZaxis()->SetTitleSize(0.035);
   data_obs_fail_postfit_projy2_copy__83->GetZaxis()->SetTitleFont(42);
   data_obs_fail_postfit_projy2_copy__83->Draw("sameaxis");
   TLatex *   tex = new TLatex(0.21,0.83,"55 < p_{T} < 200 GeV, F^{Pixels}_{i} < 0.9");
tex->SetNDC();
   tex->SetTextAlign(12);
   tex->SetTextFont(42);
   tex->SetTextSize(0.06);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.17,0.92,"CMS");
tex->SetNDC();
   tex->SetTextFont(61);
   tex->SetTextSize(0.0675);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.25,0.92,"Preliminary");
tex->SetNDC();
   tex->SetTextFont(52);
   tex->SetTextSize(0.0485);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.95,0.92,"101 fb^{-1} (13 TeV)");
tex->SetNDC();
   tex->SetTextAlign(31);
   tex->SetTextFont(42);
   tex->SetTextSize(0.07);
   tex->SetLineWidth(2);
   tex->Draw();
   data_obs_fail_postfit_projy2_main->Modified();
   plots_fit_b/base_figs/postfit_projy2_fail_logy->cd();
  
// ------------>Primitives in pad: data_obs_fail_postfit_projy2_sub
   TPad *data_obs_fail_postfit_projy2_sub = new TPad("data_obs_fail_postfit_projy2_sub", "data_obs_fail_postfit_projy2_sub",0,0,1,0.35);
   data_obs_fail_postfit_projy2_sub->Draw();
   data_obs_fail_postfit_projy2_sub->cd();
   data_obs_fail_postfit_projy2_sub->Range(17.30769,-6.023077,209.6154,2.9);
   data_obs_fail_postfit_projy2_sub->SetFillColor(0);
   data_obs_fail_postfit_projy2_sub->SetBorderMode(0);
   data_obs_fail_postfit_projy2_sub->SetBorderSize(2);
   data_obs_fail_postfit_projy2_sub->SetTickx(1);
   data_obs_fail_postfit_projy2_sub->SetTicky(1);
   data_obs_fail_postfit_projy2_sub->SetLeftMargin(0.17);
   data_obs_fail_postfit_projy2_sub->SetRightMargin(0.05);
   data_obs_fail_postfit_projy2_sub->SetTopMargin(0);
   data_obs_fail_postfit_projy2_sub->SetBottomMargin(0.35);
   data_obs_fail_postfit_projy2_sub->SetFrameFillStyle(0);
   data_obs_fail_postfit_projy2_sub->SetFrameBorderMode(0);
   data_obs_fail_postfit_projy2_sub->SetFrameFillStyle(0);
   data_obs_fail_postfit_projy2_sub->SetFrameBorderMode(0);
   Double_t xAxis132[2] = {50, 200}; 
   
   TH1D *data_obs_fail_postfit_projy2_pull__84 = new TH1D("data_obs_fail_postfit_projy2_pull__84","",1, xAxis132);
   data_obs_fail_postfit_projy2_pull__84->SetMinimum(-2.9);
   data_obs_fail_postfit_projy2_pull__84->SetMaximum(2.9);
   data_obs_fail_postfit_projy2_pull__84->SetEntries(2);
   data_obs_fail_postfit_projy2_pull__84->SetStats(0);

   ci = TColor::GetColor("#0000ff");
   data_obs_fail_postfit_projy2_pull__84->SetFillColor(ci);

   ci = TColor::GetColor("#000000");
   data_obs_fail_postfit_projy2_pull__84->SetLineColor(ci);

   ci = TColor::GetColor("#000000");
   data_obs_fail_postfit_projy2_pull__84->SetMarkerColor(ci);
   data_obs_fail_postfit_projy2_pull__84->SetMarkerStyle(8);
   data_obs_fail_postfit_projy2_pull__84->GetXaxis()->SetTitle("p_{T}");
   data_obs_fail_postfit_projy2_pull__84->GetXaxis()->SetLabelFont(42);
   data_obs_fail_postfit_projy2_pull__84->GetXaxis()->SetLabelOffset(0.05);
   data_obs_fail_postfit_projy2_pull__84->GetXaxis()->SetLabelSize(0.13);
   data_obs_fail_postfit_projy2_pull__84->GetXaxis()->SetTitleSize(0.15);
   data_obs_fail_postfit_projy2_pull__84->GetXaxis()->SetTitleOffset(1.15);
   data_obs_fail_postfit_projy2_pull__84->GetXaxis()->SetTitleFont(42);
   data_obs_fail_postfit_projy2_pull__84->GetYaxis()->SetTitle("(Data-Bkg)/#sigma");
   data_obs_fail_postfit_projy2_pull__84->GetYaxis()->SetNdivisions(306);
   data_obs_fail_postfit_projy2_pull__84->GetYaxis()->SetLabelFont(42);
   data_obs_fail_postfit_projy2_pull__84->GetYaxis()->SetLabelSize(0.13);
   data_obs_fail_postfit_projy2_pull__84->GetYaxis()->SetTitleSize(0.12);
   data_obs_fail_postfit_projy2_pull__84->GetYaxis()->SetTitleOffset(0.4);
   data_obs_fail_postfit_projy2_pull__84->GetYaxis()->SetTitleFont(42);
   data_obs_fail_postfit_projy2_pull__84->GetZaxis()->SetLabelFont(42);
   data_obs_fail_postfit_projy2_pull__84->GetZaxis()->SetLabelSize(0.035);
   data_obs_fail_postfit_projy2_pull__84->GetZaxis()->SetTitleSize(0.035);
   data_obs_fail_postfit_projy2_pull__84->GetZaxis()->SetTitleFont(42);
   data_obs_fail_postfit_projy2_pull__84->Draw("hist");
   data_obs_fail_postfit_projy2_sub->Modified();
   plots_fit_b/base_figs/postfit_projy2_fail_logy->cd();
   plots_fit_b/base_figs/postfit_projy2_fail_logy->Modified();
   plots_fit_b/base_figs/postfit_projy2_fail_logy->cd();
   plots_fit_b/base_figs/postfit_projy2_fail_logy->SetSelected(plots_fit_b/base_figs/postfit_projy2_fail_logy);
}
