void postfit_projy1_pass_logy()
{
//=========Macro generated from canvas: plots_fit_b/base_figs/postfit_projy1_pass_logy/plots_fit_b/base_figs/postfit_projy1_pass_logy
//=========  (Fri Jan 12 21:00:03 2024) by ROOT version 6.14/09
   TCanvas *plots_fit_b/base_figs/postfit_projy1_pass_logy = new TCanvas("plots_fit_b/base_figs/postfit_projy1_pass_logy", "plots_fit_b/base_figs/postfit_projy1_pass_logy",0,0,800,700);
   gStyle->SetOptFit(1);
   gStyle->SetOptStat(0);
   plots_fit_b/base_figs/postfit_projy1_pass_logy->SetHighLightColor(2);
   plots_fit_b/base_figs/postfit_projy1_pass_logy->Range(0,0,1,1);
   plots_fit_b/base_figs/postfit_projy1_pass_logy->SetFillColor(0);
   plots_fit_b/base_figs/postfit_projy1_pass_logy->SetBorderMode(0);
   plots_fit_b/base_figs/postfit_projy1_pass_logy->SetBorderSize(2);
   plots_fit_b/base_figs/postfit_projy1_pass_logy->SetTickx(1);
   plots_fit_b/base_figs/postfit_projy1_pass_logy->SetTicky(1);
   plots_fit_b/base_figs/postfit_projy1_pass_logy->SetLeftMargin(0.16);
   plots_fit_b/base_figs/postfit_projy1_pass_logy->SetRightMargin(0);
   plots_fit_b/base_figs/postfit_projy1_pass_logy->SetTopMargin(0);
   plots_fit_b/base_figs/postfit_projy1_pass_logy->SetBottomMargin(0);
   plots_fit_b/base_figs/postfit_projy1_pass_logy->SetFrameFillStyle(0);
   plots_fit_b/base_figs/postfit_projy1_pass_logy->SetFrameBorderMode(0);
  
// ------------>Primitives in pad: data_obs_pass_postfit_projy1_main
   TPad *data_obs_pass_postfit_projy1_main = new TPad("data_obs_pass_postfit_projy1_main", "data_obs_pass_postfit_projy1_main",0,0.35,1,1);
   data_obs_pass_postfit_projy1_main->Draw();
   data_obs_pass_postfit_projy1_main->cd();
   data_obs_pass_postfit_projy1_main->Range(17.30769,-3.370013,209.6154,5.880305);
   data_obs_pass_postfit_projy1_main->SetFillColor(0);
   data_obs_pass_postfit_projy1_main->SetBorderMode(0);
   data_obs_pass_postfit_projy1_main->SetBorderSize(2);
   data_obs_pass_postfit_projy1_main->SetLogy();
   data_obs_pass_postfit_projy1_main->SetTickx(1);
   data_obs_pass_postfit_projy1_main->SetTicky(1);
   data_obs_pass_postfit_projy1_main->SetLeftMargin(0.17);
   data_obs_pass_postfit_projy1_main->SetRightMargin(0.05);
   data_obs_pass_postfit_projy1_main->SetBottomMargin(0.04);
   data_obs_pass_postfit_projy1_main->SetFrameFillStyle(0);
   data_obs_pass_postfit_projy1_main->SetFrameBorderMode(0);
   data_obs_pass_postfit_projy1_main->SetFrameFillStyle(0);
   data_obs_pass_postfit_projy1_main->SetFrameBorderMode(0);
   Double_t xAxis243[2] = {50, 200}; 
   
   TH1D *data_obs_pass_postfit_projy1__155 = new TH1D("data_obs_pass_postfit_projy1__155","",1, xAxis243);
   data_obs_pass_postfit_projy1__155->SetBinContent(1,990);
   data_obs_pass_postfit_projy1__155->SetBinError(1,31.46427);
   data_obs_pass_postfit_projy1__155->SetMinimum(0.001);
   data_obs_pass_postfit_projy1__155->SetMaximum(90213.75);
   data_obs_pass_postfit_projy1__155->SetEntries(990);
   data_obs_pass_postfit_projy1__155->SetStats(0);

   Int_t ci;      // for color index setting
   TColor *color; // for color definition with alpha
   ci = TColor::GetColor("#000000");
   data_obs_pass_postfit_projy1__155->SetLineColor(ci);

   ci = TColor::GetColor("#000000");
   data_obs_pass_postfit_projy1__155->SetMarkerColor(ci);
   data_obs_pass_postfit_projy1__155->SetMarkerStyle(8);
   data_obs_pass_postfit_projy1__155->GetXaxis()->SetTitle("p_{T}");
   data_obs_pass_postfit_projy1__155->GetXaxis()->SetLabelFont(42);
   data_obs_pass_postfit_projy1__155->GetXaxis()->SetLabelOffset(0.05);
   data_obs_pass_postfit_projy1__155->GetXaxis()->SetLabelSize(0.07);
   data_obs_pass_postfit_projy1__155->GetXaxis()->SetTitleSize(0.09);
   data_obs_pass_postfit_projy1__155->GetXaxis()->SetTitleOffset(1.15);
   data_obs_pass_postfit_projy1__155->GetXaxis()->SetTitleFont(42);
   data_obs_pass_postfit_projy1__155->GetYaxis()->SetTitle("Events / bin");
   data_obs_pass_postfit_projy1__155->GetYaxis()->SetNdivisions(508);
   data_obs_pass_postfit_projy1__155->GetYaxis()->SetLabelFont(42);
   data_obs_pass_postfit_projy1__155->GetYaxis()->SetLabelSize(0.07);
   data_obs_pass_postfit_projy1__155->GetYaxis()->SetTitleSize(0.09);
   data_obs_pass_postfit_projy1__155->GetYaxis()->SetTitleOffset(0.8);
   data_obs_pass_postfit_projy1__155->GetYaxis()->SetTitleFont(42);
   data_obs_pass_postfit_projy1__155->GetZaxis()->SetLabelFont(42);
   data_obs_pass_postfit_projy1__155->GetZaxis()->SetLabelSize(0.035);
   data_obs_pass_postfit_projy1__155->GetZaxis()->SetTitleSize(0.035);
   data_obs_pass_postfit_projy1__155->GetZaxis()->SetTitleFont(42);
   data_obs_pass_postfit_projy1__155->Draw("pe X0");
   
   THStack *postfit_projy1_pass_logy_stack = new THStack();
   postfit_projy1_pass_logy_stack->SetName("postfit_projy1_pass_logy_stack");
   postfit_projy1_pass_logy_stack->SetTitle("postfit_projy1_pass_logy_stack");
   postfit_projy1_pass_logy_stack->SetMinimum(0.001);
   Double_t xAxis244[2] = {50, 200}; 
   
   TH1F *postfit_projy1_pass_logy_stack_stack_45 = new TH1F("postfit_projy1_pass_logy_stack_stack_45","postfit_projy1_pass_logy_stack",1, xAxis244);
   postfit_projy1_pass_logy_stack_stack_45->SetMinimum(0.0002494827);
   postfit_projy1_pass_logy_stack_stack_45->SetMaximum(2289.095);
   postfit_projy1_pass_logy_stack_stack_45->SetDirectory(0);
   postfit_projy1_pass_logy_stack_stack_45->SetStats(0);
   postfit_projy1_pass_logy_stack_stack_45->SetLineStyle(0);
   postfit_projy1_pass_logy_stack_stack_45->GetXaxis()->SetLabelFont(42);
   postfit_projy1_pass_logy_stack_stack_45->GetXaxis()->SetLabelOffset(0.007);
   postfit_projy1_pass_logy_stack_stack_45->GetXaxis()->SetLabelSize(0.05);
   postfit_projy1_pass_logy_stack_stack_45->GetXaxis()->SetTitleSize(0.08);
   postfit_projy1_pass_logy_stack_stack_45->GetXaxis()->SetTitleOffset(0.9);
   postfit_projy1_pass_logy_stack_stack_45->GetXaxis()->SetTitleFont(42);
   postfit_projy1_pass_logy_stack_stack_45->GetYaxis()->SetNdivisions(508);
   postfit_projy1_pass_logy_stack_stack_45->GetYaxis()->SetLabelFont(42);
   postfit_projy1_pass_logy_stack_stack_45->GetYaxis()->SetLabelOffset(0.007);
   postfit_projy1_pass_logy_stack_stack_45->GetYaxis()->SetLabelSize(0.05);
   postfit_projy1_pass_logy_stack_stack_45->GetYaxis()->SetTitleSize(0.08);
   postfit_projy1_pass_logy_stack_stack_45->GetYaxis()->SetTitleOffset(1.25);
   postfit_projy1_pass_logy_stack_stack_45->GetYaxis()->SetTitleFont(42);
   postfit_projy1_pass_logy_stack_stack_45->GetZaxis()->SetLabelFont(42);
   postfit_projy1_pass_logy_stack_stack_45->GetZaxis()->SetLabelOffset(0.007);
   postfit_projy1_pass_logy_stack_stack_45->GetZaxis()->SetLabelSize(0.05);
   postfit_projy1_pass_logy_stack_stack_45->GetZaxis()->SetTitleSize(0.08);
   postfit_projy1_pass_logy_stack_stack_45->GetZaxis()->SetTitleFont(42);
   postfit_projy1_pass_logy_stack->SetHistogram(postfit_projy1_pass_logy_stack_stack_45);
   
   Double_t xAxis245[2] = {50, 200}; 
   
   TH1D *Background_0x0_pass_postfit_projy1_stack_1 = new TH1D("Background_0x0_pass_postfit_projy1_stack_1","Background, pass, postfit, 0.24-1.0",1, xAxis245);
   Background_0x0_pass_postfit_projy1_stack_1->SetBinContent(1,1025.981);
   Background_0x0_pass_postfit_projy1_stack_1->SetBinError(1,12.9502);
   Background_0x0_pass_postfit_projy1_stack_1->SetMinimum(0.001);
   Background_0x0_pass_postfit_projy1_stack_1->SetEntries(6276.616);
   Background_0x0_pass_postfit_projy1_stack_1->SetStats(0);

   ci = TColor::GetColor("#ffff00");
   Background_0x0_pass_postfit_projy1_stack_1->SetFillColor(ci);

   ci = 1201;
   color = new TColor(ci, 1, 1, 1, " ", 0);
   Background_0x0_pass_postfit_projy1_stack_1->SetLineColor(ci);
   Background_0x0_pass_postfit_projy1_stack_1->GetXaxis()->SetTitle("p_{T}");
   Background_0x0_pass_postfit_projy1_stack_1->GetXaxis()->SetLabelFont(42);
   Background_0x0_pass_postfit_projy1_stack_1->GetXaxis()->SetLabelSize(0.035);
   Background_0x0_pass_postfit_projy1_stack_1->GetXaxis()->SetTitleSize(0.035);
   Background_0x0_pass_postfit_projy1_stack_1->GetXaxis()->SetTitleOffset(0);
   Background_0x0_pass_postfit_projy1_stack_1->GetXaxis()->SetTitleFont(42);
   Background_0x0_pass_postfit_projy1_stack_1->GetYaxis()->SetTitle("Events / bin");
   Background_0x0_pass_postfit_projy1_stack_1->GetYaxis()->SetLabelFont(42);
   Background_0x0_pass_postfit_projy1_stack_1->GetYaxis()->SetLabelSize(0.035);
   Background_0x0_pass_postfit_projy1_stack_1->GetYaxis()->SetTitleSize(0.035);
   Background_0x0_pass_postfit_projy1_stack_1->GetYaxis()->SetTitleOffset(0);
   Background_0x0_pass_postfit_projy1_stack_1->GetYaxis()->SetTitleFont(42);
   Background_0x0_pass_postfit_projy1_stack_1->GetZaxis()->SetLabelFont(42);
   Background_0x0_pass_postfit_projy1_stack_1->GetZaxis()->SetLabelSize(0.035);
   Background_0x0_pass_postfit_projy1_stack_1->GetZaxis()->SetTitleSize(0.035);
   Background_0x0_pass_postfit_projy1_stack_1->GetZaxis()->SetTitleFont(42);
   postfit_projy1_pass_logy_stack->Add(Background_0x0_pass_postfit_projy1_stack_1,"");
   postfit_projy1_pass_logy_stack->Draw("hist same");
   
   postfit_projy1_pass_logy_stack = new THStack();
   postfit_projy1_pass_logy_stack->SetName("postfit_projy1_pass_logy_stack");
   postfit_projy1_pass_logy_stack->SetTitle("postfit_projy1_pass_logy_stack");
   postfit_projy1_pass_logy_stack->SetMinimum(0.001);
   Double_t xAxis246[2] = {50, 200}; 
   
   TH1F *postfit_projy1_pass_logy_stack_stack_45_stack_46 = new TH1F("postfit_projy1_pass_logy_stack_stack_45_stack_46","postfit_projy1_pass_logy_stack",1, xAxis246);
   postfit_projy1_pass_logy_stack_stack_45_stack_46->SetMinimum(0.0002494827);
   postfit_projy1_pass_logy_stack_stack_45_stack_46->SetMaximum(2289.095);
   postfit_projy1_pass_logy_stack_stack_45_stack_46->SetDirectory(0);
   postfit_projy1_pass_logy_stack_stack_45_stack_46->SetStats(0);
   postfit_projy1_pass_logy_stack_stack_45_stack_46->SetLineStyle(0);
   postfit_projy1_pass_logy_stack_stack_45_stack_46->GetXaxis()->SetLabelFont(42);
   postfit_projy1_pass_logy_stack_stack_45_stack_46->GetXaxis()->SetLabelOffset(0.007);
   postfit_projy1_pass_logy_stack_stack_45_stack_46->GetXaxis()->SetLabelSize(0.05);
   postfit_projy1_pass_logy_stack_stack_45_stack_46->GetXaxis()->SetTitleSize(0.08);
   postfit_projy1_pass_logy_stack_stack_45_stack_46->GetXaxis()->SetTitleOffset(0.9);
   postfit_projy1_pass_logy_stack_stack_45_stack_46->GetXaxis()->SetTitleFont(42);
   postfit_projy1_pass_logy_stack_stack_45_stack_46->GetYaxis()->SetNdivisions(508);
   postfit_projy1_pass_logy_stack_stack_45_stack_46->GetYaxis()->SetLabelFont(42);
   postfit_projy1_pass_logy_stack_stack_45_stack_46->GetYaxis()->SetLabelOffset(0.007);
   postfit_projy1_pass_logy_stack_stack_45_stack_46->GetYaxis()->SetLabelSize(0.05);
   postfit_projy1_pass_logy_stack_stack_45_stack_46->GetYaxis()->SetTitleSize(0.08);
   postfit_projy1_pass_logy_stack_stack_45_stack_46->GetYaxis()->SetTitleOffset(1.25);
   postfit_projy1_pass_logy_stack_stack_45_stack_46->GetYaxis()->SetTitleFont(42);
   postfit_projy1_pass_logy_stack_stack_45_stack_46->GetZaxis()->SetLabelFont(42);
   postfit_projy1_pass_logy_stack_stack_45_stack_46->GetZaxis()->SetLabelOffset(0.007);
   postfit_projy1_pass_logy_stack_stack_45_stack_46->GetZaxis()->SetLabelSize(0.05);
   postfit_projy1_pass_logy_stack_stack_45_stack_46->GetZaxis()->SetTitleSize(0.08);
   postfit_projy1_pass_logy_stack_stack_45_stack_46->GetZaxis()->SetTitleFont(42);
   postfit_projy1_pass_logy_stack->SetHistogram(postfit_projy1_pass_logy_stack_stack_45_stack_46);
   
   Double_t xAxis247[2] = {50, 200}; 
   
   TH1D *Background_0x0_pass_postfit_projy1_stack_1_stack_1 = new TH1D("Background_0x0_pass_postfit_projy1_stack_1_stack_1","Background, pass, postfit, 0.24-1.0",1, xAxis247);
   Background_0x0_pass_postfit_projy1_stack_1_stack_1->SetBinContent(1,1025.981);
   Background_0x0_pass_postfit_projy1_stack_1_stack_1->SetBinError(1,12.9502);
   Background_0x0_pass_postfit_projy1_stack_1_stack_1->SetMinimum(0.001);
   Background_0x0_pass_postfit_projy1_stack_1_stack_1->SetEntries(6276.616);
   Background_0x0_pass_postfit_projy1_stack_1_stack_1->SetStats(0);

   ci = TColor::GetColor("#ffff00");
   Background_0x0_pass_postfit_projy1_stack_1_stack_1->SetFillColor(ci);

   ci = 1201;
   color = new TColor(ci, 1, 1, 1, " ", 0);
   Background_0x0_pass_postfit_projy1_stack_1_stack_1->SetLineColor(ci);
   Background_0x0_pass_postfit_projy1_stack_1_stack_1->GetXaxis()->SetTitle("p_{T}");
   Background_0x0_pass_postfit_projy1_stack_1_stack_1->GetXaxis()->SetLabelFont(42);
   Background_0x0_pass_postfit_projy1_stack_1_stack_1->GetXaxis()->SetLabelSize(0.035);
   Background_0x0_pass_postfit_projy1_stack_1_stack_1->GetXaxis()->SetTitleSize(0.035);
   Background_0x0_pass_postfit_projy1_stack_1_stack_1->GetXaxis()->SetTitleOffset(0);
   Background_0x0_pass_postfit_projy1_stack_1_stack_1->GetXaxis()->SetTitleFont(42);
   Background_0x0_pass_postfit_projy1_stack_1_stack_1->GetYaxis()->SetTitle("Events / bin");
   Background_0x0_pass_postfit_projy1_stack_1_stack_1->GetYaxis()->SetLabelFont(42);
   Background_0x0_pass_postfit_projy1_stack_1_stack_1->GetYaxis()->SetLabelSize(0.035);
   Background_0x0_pass_postfit_projy1_stack_1_stack_1->GetYaxis()->SetTitleSize(0.035);
   Background_0x0_pass_postfit_projy1_stack_1_stack_1->GetYaxis()->SetTitleOffset(0);
   Background_0x0_pass_postfit_projy1_stack_1_stack_1->GetYaxis()->SetTitleFont(42);
   Background_0x0_pass_postfit_projy1_stack_1_stack_1->GetZaxis()->SetLabelFont(42);
   Background_0x0_pass_postfit_projy1_stack_1_stack_1->GetZaxis()->SetLabelSize(0.035);
   Background_0x0_pass_postfit_projy1_stack_1_stack_1->GetZaxis()->SetTitleSize(0.035);
   Background_0x0_pass_postfit_projy1_stack_1_stack_1->GetZaxis()->SetTitleFont(42);
   postfit_projy1_pass_logy_stack->Add(Background_0x0_pass_postfit_projy1_stack_1_stack_1,"");
   postfit_projy1_pass_logy_stack->Draw("hist same");
   Double_t xAxis248[2] = {50, 200}; 
   
   TH1D *Signal_ppStaumI557_pass_postfit_projy1__156 = new TH1D("Signal_ppStaumI557_pass_postfit_projy1__156","HSCP signal, pass, postfit, 0.24-1.0",1, xAxis248);
   Signal_ppStaumI557_pass_postfit_projy1__156->SetBinContent(1,0.232382);
   Signal_ppStaumI557_pass_postfit_projy1__156->SetBinError(1,0.04518739);
   Signal_ppStaumI557_pass_postfit_projy1__156->SetMinimum(0.001);
   Signal_ppStaumI557_pass_postfit_projy1__156->SetEntries(26.44664);
   Signal_ppStaumI557_pass_postfit_projy1__156->SetStats(0);
   Signal_ppStaumI557_pass_postfit_projy1__156->SetLineColor(2);
   Signal_ppStaumI557_pass_postfit_projy1__156->GetXaxis()->SetTitle("p_{T}");
   Signal_ppStaumI557_pass_postfit_projy1__156->GetXaxis()->SetLabelFont(42);
   Signal_ppStaumI557_pass_postfit_projy1__156->GetXaxis()->SetLabelSize(0.035);
   Signal_ppStaumI557_pass_postfit_projy1__156->GetXaxis()->SetTitleSize(0.035);
   Signal_ppStaumI557_pass_postfit_projy1__156->GetXaxis()->SetTitleOffset(0);
   Signal_ppStaumI557_pass_postfit_projy1__156->GetXaxis()->SetTitleFont(42);
   Signal_ppStaumI557_pass_postfit_projy1__156->GetYaxis()->SetTitle("Events / bin");
   Signal_ppStaumI557_pass_postfit_projy1__156->GetYaxis()->SetLabelFont(42);
   Signal_ppStaumI557_pass_postfit_projy1__156->GetYaxis()->SetLabelSize(0.035);
   Signal_ppStaumI557_pass_postfit_projy1__156->GetYaxis()->SetTitleSize(0.035);
   Signal_ppStaumI557_pass_postfit_projy1__156->GetYaxis()->SetTitleOffset(0);
   Signal_ppStaumI557_pass_postfit_projy1__156->GetYaxis()->SetTitleFont(42);
   Signal_ppStaumI557_pass_postfit_projy1__156->GetZaxis()->SetLabelFont(42);
   Signal_ppStaumI557_pass_postfit_projy1__156->GetZaxis()->SetLabelSize(0.035);
   Signal_ppStaumI557_pass_postfit_projy1__156->GetZaxis()->SetTitleSize(0.035);
   Signal_ppStaumI557_pass_postfit_projy1__156->GetZaxis()->SetTitleFont(42);
   Signal_ppStaumI557_pass_postfit_projy1__156->Draw("hist same");
   Double_t xAxis249[2] = {50, 200}; 
   
   TH1D *TotalBkg_pass_postfit_projy1__157 = new TH1D("TotalBkg_pass_postfit_projy1__157","TotalBkg, pass, postfit, 0.24-1.0",1, xAxis249);
   TotalBkg_pass_postfit_projy1__157->SetBinContent(1,1025.981);
   TotalBkg_pass_postfit_projy1__157->SetBinError(1,12.80391);
   TotalBkg_pass_postfit_projy1__157->SetMinimum(0.001);
   TotalBkg_pass_postfit_projy1__157->SetEntries(6420.868);
   TotalBkg_pass_postfit_projy1__157->SetStats(0);
   TotalBkg_pass_postfit_projy1__157->SetMarkerStyle(0);
   TotalBkg_pass_postfit_projy1__157->GetXaxis()->SetTitle("p_{T}");
   TotalBkg_pass_postfit_projy1__157->GetXaxis()->SetLabelFont(42);
   TotalBkg_pass_postfit_projy1__157->GetXaxis()->SetLabelSize(0.035);
   TotalBkg_pass_postfit_projy1__157->GetXaxis()->SetTitleSize(0.035);
   TotalBkg_pass_postfit_projy1__157->GetXaxis()->SetTitleOffset(0);
   TotalBkg_pass_postfit_projy1__157->GetXaxis()->SetTitleFont(42);
   TotalBkg_pass_postfit_projy1__157->GetYaxis()->SetTitle("Events / bin");
   TotalBkg_pass_postfit_projy1__157->GetYaxis()->SetLabelFont(42);
   TotalBkg_pass_postfit_projy1__157->GetYaxis()->SetLabelSize(0.035);
   TotalBkg_pass_postfit_projy1__157->GetYaxis()->SetTitleSize(0.035);
   TotalBkg_pass_postfit_projy1__157->GetYaxis()->SetTitleOffset(0);
   TotalBkg_pass_postfit_projy1__157->GetYaxis()->SetTitleFont(42);
   TotalBkg_pass_postfit_projy1__157->GetZaxis()->SetLabelFont(42);
   TotalBkg_pass_postfit_projy1__157->GetZaxis()->SetLabelSize(0.035);
   TotalBkg_pass_postfit_projy1__157->GetZaxis()->SetTitleSize(0.035);
   TotalBkg_pass_postfit_projy1__157->GetZaxis()->SetTitleFont(42);
   TotalBkg_pass_postfit_projy1__157->Draw("hist same");
   Double_t xAxis250[2] = {50, 200}; 
   
   TH1D *TotalBkg_pass_postfit_projy1__158 = new TH1D("TotalBkg_pass_postfit_projy1__158","TotalBkg, pass, postfit, 0.24-1.0",1, xAxis250);
   TotalBkg_pass_postfit_projy1__158->SetBinContent(1,1025.981);
   TotalBkg_pass_postfit_projy1__158->SetBinError(1,12.80391);
   TotalBkg_pass_postfit_projy1__158->SetMinimum(0.001);
   TotalBkg_pass_postfit_projy1__158->SetEntries(6420.868);
   TotalBkg_pass_postfit_projy1__158->SetStats(0);
   TotalBkg_pass_postfit_projy1__158->SetFillColor(1);
   TotalBkg_pass_postfit_projy1__158->SetFillStyle(3354);
   TotalBkg_pass_postfit_projy1__158->SetLineWidth(0);
   TotalBkg_pass_postfit_projy1__158->SetMarkerStyle(0);
   TotalBkg_pass_postfit_projy1__158->GetXaxis()->SetTitle("p_{T}");
   TotalBkg_pass_postfit_projy1__158->GetXaxis()->SetLabelFont(42);
   TotalBkg_pass_postfit_projy1__158->GetXaxis()->SetLabelSize(0.035);
   TotalBkg_pass_postfit_projy1__158->GetXaxis()->SetTitleSize(0.035);
   TotalBkg_pass_postfit_projy1__158->GetXaxis()->SetTitleOffset(0);
   TotalBkg_pass_postfit_projy1__158->GetXaxis()->SetTitleFont(42);
   TotalBkg_pass_postfit_projy1__158->GetYaxis()->SetTitle("Events / bin");
   TotalBkg_pass_postfit_projy1__158->GetYaxis()->SetLabelFont(42);
   TotalBkg_pass_postfit_projy1__158->GetYaxis()->SetLabelSize(0.035);
   TotalBkg_pass_postfit_projy1__158->GetYaxis()->SetTitleSize(0.035);
   TotalBkg_pass_postfit_projy1__158->GetYaxis()->SetTitleOffset(0);
   TotalBkg_pass_postfit_projy1__158->GetYaxis()->SetTitleFont(42);
   TotalBkg_pass_postfit_projy1__158->GetZaxis()->SetLabelFont(42);
   TotalBkg_pass_postfit_projy1__158->GetZaxis()->SetLabelSize(0.035);
   TotalBkg_pass_postfit_projy1__158->GetZaxis()->SetTitleSize(0.035);
   TotalBkg_pass_postfit_projy1__158->GetZaxis()->SetTitleFont(42);
   TotalBkg_pass_postfit_projy1__158->Draw("e2 same");
   Double_t xAxis251[2] = {50, 200}; 
   
   TH1D *data_obs_pass_postfit_projy1__159 = new TH1D("data_obs_pass_postfit_projy1__159","",1, xAxis251);
   data_obs_pass_postfit_projy1__159->SetBinContent(1,990);
   data_obs_pass_postfit_projy1__159->SetBinError(1,31.46427);
   data_obs_pass_postfit_projy1__159->SetMinimum(0.001);
   data_obs_pass_postfit_projy1__159->SetMaximum(90213.75);
   data_obs_pass_postfit_projy1__159->SetEntries(990);
   data_obs_pass_postfit_projy1__159->SetStats(0);

   ci = TColor::GetColor("#000000");
   data_obs_pass_postfit_projy1__159->SetLineColor(ci);

   ci = TColor::GetColor("#000000");
   data_obs_pass_postfit_projy1__159->SetMarkerColor(ci);
   data_obs_pass_postfit_projy1__159->SetMarkerStyle(8);
   data_obs_pass_postfit_projy1__159->GetXaxis()->SetTitle("p_{T}");
   data_obs_pass_postfit_projy1__159->GetXaxis()->SetLabelFont(42);
   data_obs_pass_postfit_projy1__159->GetXaxis()->SetLabelOffset(0.05);
   data_obs_pass_postfit_projy1__159->GetXaxis()->SetLabelSize(0.07);
   data_obs_pass_postfit_projy1__159->GetXaxis()->SetTitleSize(0.09);
   data_obs_pass_postfit_projy1__159->GetXaxis()->SetTitleOffset(1.15);
   data_obs_pass_postfit_projy1__159->GetXaxis()->SetTitleFont(42);
   data_obs_pass_postfit_projy1__159->GetYaxis()->SetTitle("Events / bin");
   data_obs_pass_postfit_projy1__159->GetYaxis()->SetNdivisions(508);
   data_obs_pass_postfit_projy1__159->GetYaxis()->SetLabelFont(42);
   data_obs_pass_postfit_projy1__159->GetYaxis()->SetLabelSize(0.07);
   data_obs_pass_postfit_projy1__159->GetYaxis()->SetTitleSize(0.09);
   data_obs_pass_postfit_projy1__159->GetYaxis()->SetTitleOffset(0.8);
   data_obs_pass_postfit_projy1__159->GetYaxis()->SetTitleFont(42);
   data_obs_pass_postfit_projy1__159->GetZaxis()->SetLabelFont(42);
   data_obs_pass_postfit_projy1__159->GetZaxis()->SetLabelSize(0.035);
   data_obs_pass_postfit_projy1__159->GetZaxis()->SetTitleSize(0.035);
   data_obs_pass_postfit_projy1__159->GetZaxis()->SetTitleFont(42);
   data_obs_pass_postfit_projy1__159->Draw("pe X0 same");
   
   TLegend *leg = new TLegend(0.65,0.64,0.9,0.88,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(1001);
   TLegendEntry *entry=leg->AddEntry("data_obs_pass_postfit_projy1","Data","pe X0");

   ci = TColor::GetColor("#000000");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);

   ci = TColor::GetColor("#000000");
   entry->SetMarkerColor(ci);
   entry->SetMarkerStyle(8);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("TotalBkg_pass_postfit_projy1","Total bkg unc.","F");
   entry->SetFillColor(1);
   entry->SetFillStyle(3354);
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("Signal_ppStau-557_pass_postfit_projy1","HSCP signal","L");
   entry->SetLineColor(2);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("Background_0x0_pass_postfit_projy1_stack_1_stack_1","Background","f");

   ci = TColor::GetColor("#ffff00");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = 1201;
   color = new TColor(ci, 1, 1, 1, " ", 0);
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   leg->Draw();
   Double_t xAxis252[2] = {50, 200}; 
   
   TH1D *data_obs_pass_postfit_projy1_copy__160 = new TH1D("data_obs_pass_postfit_projy1_copy__160","",1, xAxis252);
   data_obs_pass_postfit_projy1_copy__160->SetBinContent(1,990);
   data_obs_pass_postfit_projy1_copy__160->SetBinError(1,31.46427);
   data_obs_pass_postfit_projy1_copy__160->SetMinimum(0.001);
   data_obs_pass_postfit_projy1_copy__160->SetMaximum(90213.75);
   data_obs_pass_postfit_projy1_copy__160->SetEntries(990);
   data_obs_pass_postfit_projy1_copy__160->SetDirectory(0);
   data_obs_pass_postfit_projy1_copy__160->SetStats(0);

   ci = TColor::GetColor("#000000");
   data_obs_pass_postfit_projy1_copy__160->SetLineColor(ci);

   ci = TColor::GetColor("#000000");
   data_obs_pass_postfit_projy1_copy__160->SetMarkerColor(ci);
   data_obs_pass_postfit_projy1_copy__160->SetMarkerStyle(8);
   data_obs_pass_postfit_projy1_copy__160->GetXaxis()->SetTitle("p_{T}");
   data_obs_pass_postfit_projy1_copy__160->GetXaxis()->SetLabelFont(42);
   data_obs_pass_postfit_projy1_copy__160->GetXaxis()->SetLabelOffset(0.05);
   data_obs_pass_postfit_projy1_copy__160->GetXaxis()->SetLabelSize(0.07);
   data_obs_pass_postfit_projy1_copy__160->GetXaxis()->SetTitleSize(0.09);
   data_obs_pass_postfit_projy1_copy__160->GetXaxis()->SetTitleOffset(1.15);
   data_obs_pass_postfit_projy1_copy__160->GetXaxis()->SetTitleFont(42);
   data_obs_pass_postfit_projy1_copy__160->GetYaxis()->SetTitle("Events / bin");
   data_obs_pass_postfit_projy1_copy__160->GetYaxis()->SetNdivisions(508);
   data_obs_pass_postfit_projy1_copy__160->GetYaxis()->SetLabelFont(42);
   data_obs_pass_postfit_projy1_copy__160->GetYaxis()->SetLabelSize(0.07);
   data_obs_pass_postfit_projy1_copy__160->GetYaxis()->SetTitleSize(0.09);
   data_obs_pass_postfit_projy1_copy__160->GetYaxis()->SetTitleOffset(0.8);
   data_obs_pass_postfit_projy1_copy__160->GetYaxis()->SetTitleFont(42);
   data_obs_pass_postfit_projy1_copy__160->GetZaxis()->SetLabelFont(42);
   data_obs_pass_postfit_projy1_copy__160->GetZaxis()->SetLabelSize(0.035);
   data_obs_pass_postfit_projy1_copy__160->GetZaxis()->SetTitleSize(0.035);
   data_obs_pass_postfit_projy1_copy__160->GetZaxis()->SetTitleFont(42);
   data_obs_pass_postfit_projy1_copy__160->Draw("sameaxis");
   TLatex *   tex = new TLatex(0.21,0.83,"55 < p_{T} < 200 GeV, F^{Pixels}_{i} > 0.9");
tex->SetNDC();
   tex->SetTextAlign(12);
   tex->SetTextFont(42);
   tex->SetTextSize(0.06);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.17,0.92,"CMS");
tex->SetNDC();
   tex->SetTextFont(61);
   tex->SetTextSize(0.0675);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.25,0.92,"Preliminary");
tex->SetNDC();
   tex->SetTextFont(52);
   tex->SetTextSize(0.0485);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.95,0.92,"101 fb^{-1} (13 TeV)");
tex->SetNDC();
   tex->SetTextAlign(31);
   tex->SetTextFont(42);
   tex->SetTextSize(0.07);
   tex->SetLineWidth(2);
   tex->Draw();
   data_obs_pass_postfit_projy1_main->Modified();
   plots_fit_b/base_figs/postfit_projy1_pass_logy->cd();
  
// ------------>Primitives in pad: data_obs_pass_postfit_projy1_sub
   TPad *data_obs_pass_postfit_projy1_sub = new TPad("data_obs_pass_postfit_projy1_sub", "data_obs_pass_postfit_projy1_sub",0,0,1,0.35);
   data_obs_pass_postfit_projy1_sub->Draw();
   data_obs_pass_postfit_projy1_sub->cd();
   data_obs_pass_postfit_projy1_sub->Range(17.30769,-6.023077,209.6154,2.9);
   data_obs_pass_postfit_projy1_sub->SetFillColor(0);
   data_obs_pass_postfit_projy1_sub->SetBorderMode(0);
   data_obs_pass_postfit_projy1_sub->SetBorderSize(2);
   data_obs_pass_postfit_projy1_sub->SetTickx(1);
   data_obs_pass_postfit_projy1_sub->SetTicky(1);
   data_obs_pass_postfit_projy1_sub->SetLeftMargin(0.17);
   data_obs_pass_postfit_projy1_sub->SetRightMargin(0.05);
   data_obs_pass_postfit_projy1_sub->SetTopMargin(0);
   data_obs_pass_postfit_projy1_sub->SetBottomMargin(0.35);
   data_obs_pass_postfit_projy1_sub->SetFrameFillStyle(0);
   data_obs_pass_postfit_projy1_sub->SetFrameBorderMode(0);
   data_obs_pass_postfit_projy1_sub->SetFrameFillStyle(0);
   data_obs_pass_postfit_projy1_sub->SetFrameBorderMode(0);
   Double_t xAxis253[2] = {50, 200}; 
   
   TH1D *data_obs_pass_postfit_projy1_pull__161 = new TH1D("data_obs_pass_postfit_projy1_pull__161","",1, xAxis253);
   data_obs_pass_postfit_projy1_pull__161->SetBinContent(1,-1.030742);
   data_obs_pass_postfit_projy1_pull__161->SetBinError(1,33.96969);
   data_obs_pass_postfit_projy1_pull__161->SetMinimum(-2.9);
   data_obs_pass_postfit_projy1_pull__161->SetMaximum(2.9);
   data_obs_pass_postfit_projy1_pull__161->SetEntries(36.98099);
   data_obs_pass_postfit_projy1_pull__161->SetStats(0);

   ci = TColor::GetColor("#0000ff");
   data_obs_pass_postfit_projy1_pull__161->SetFillColor(ci);

   ci = TColor::GetColor("#000000");
   data_obs_pass_postfit_projy1_pull__161->SetLineColor(ci);

   ci = TColor::GetColor("#000000");
   data_obs_pass_postfit_projy1_pull__161->SetMarkerColor(ci);
   data_obs_pass_postfit_projy1_pull__161->SetMarkerStyle(8);
   data_obs_pass_postfit_projy1_pull__161->GetXaxis()->SetTitle("p_{T}");
   data_obs_pass_postfit_projy1_pull__161->GetXaxis()->SetLabelFont(42);
   data_obs_pass_postfit_projy1_pull__161->GetXaxis()->SetLabelOffset(0.05);
   data_obs_pass_postfit_projy1_pull__161->GetXaxis()->SetLabelSize(0.13);
   data_obs_pass_postfit_projy1_pull__161->GetXaxis()->SetTitleSize(0.15);
   data_obs_pass_postfit_projy1_pull__161->GetXaxis()->SetTitleOffset(1.15);
   data_obs_pass_postfit_projy1_pull__161->GetXaxis()->SetTitleFont(42);
   data_obs_pass_postfit_projy1_pull__161->GetYaxis()->SetTitle("(Data-Bkg)/#sigma");
   data_obs_pass_postfit_projy1_pull__161->GetYaxis()->SetNdivisions(306);
   data_obs_pass_postfit_projy1_pull__161->GetYaxis()->SetLabelFont(42);
   data_obs_pass_postfit_projy1_pull__161->GetYaxis()->SetLabelSize(0.13);
   data_obs_pass_postfit_projy1_pull__161->GetYaxis()->SetTitleSize(0.12);
   data_obs_pass_postfit_projy1_pull__161->GetYaxis()->SetTitleOffset(0.4);
   data_obs_pass_postfit_projy1_pull__161->GetYaxis()->SetTitleFont(42);
   data_obs_pass_postfit_projy1_pull__161->GetZaxis()->SetLabelFont(42);
   data_obs_pass_postfit_projy1_pull__161->GetZaxis()->SetLabelSize(0.035);
   data_obs_pass_postfit_projy1_pull__161->GetZaxis()->SetTitleSize(0.035);
   data_obs_pass_postfit_projy1_pull__161->GetZaxis()->SetTitleFont(42);
   data_obs_pass_postfit_projy1_pull__161->Draw("hist");
   data_obs_pass_postfit_projy1_sub->Modified();
   plots_fit_b/base_figs/postfit_projy1_pass_logy->cd();
   plots_fit_b/base_figs/postfit_projy1_pass_logy->Modified();
   plots_fit_b/base_figs/postfit_projy1_pass_logy->cd();
   plots_fit_b/base_figs/postfit_projy1_pass_logy->SetSelected(plots_fit_b/base_figs/postfit_projy1_pass_logy);
}
