void prefit_projy1_pass()
{
//=========Macro generated from canvas: plots_fit_b/base_figs/prefit_projy1_pass/plots_fit_b/base_figs/prefit_projy1_pass
//=========  (Fri Jan 12 21:00:28 2024) by ROOT version 6.14/09
   TCanvas *plots_fit_b/base_figs/prefit_projy1_pass = new TCanvas("plots_fit_b/base_figs/prefit_projy1_pass", "plots_fit_b/base_figs/prefit_projy1_pass",0,0,800,700);
   gStyle->SetOptFit(1);
   gStyle->SetOptStat(0);
   plots_fit_b/base_figs/prefit_projy1_pass->SetHighLightColor(2);
   plots_fit_b/base_figs/prefit_projy1_pass->Range(0,0,1,1);
   plots_fit_b/base_figs/prefit_projy1_pass->SetFillColor(0);
   plots_fit_b/base_figs/prefit_projy1_pass->SetBorderMode(0);
   plots_fit_b/base_figs/prefit_projy1_pass->SetBorderSize(2);
   plots_fit_b/base_figs/prefit_projy1_pass->SetTickx(1);
   plots_fit_b/base_figs/prefit_projy1_pass->SetTicky(1);
   plots_fit_b/base_figs/prefit_projy1_pass->SetLeftMargin(0.16);
   plots_fit_b/base_figs/prefit_projy1_pass->SetRightMargin(0);
   plots_fit_b/base_figs/prefit_projy1_pass->SetTopMargin(0);
   plots_fit_b/base_figs/prefit_projy1_pass->SetBottomMargin(0);
   plots_fit_b/base_figs/prefit_projy1_pass->SetFrameFillStyle(0);
   plots_fit_b/base_figs/prefit_projy1_pass->SetFrameBorderMode(0);
  
// ------------>Primitives in pad: data_obs_pass_prefit_projy1_main
   TPad *data_obs_pass_prefit_projy1_main = new TPad("data_obs_pass_prefit_projy1_main", "data_obs_pass_prefit_projy1_main",0,0.35,1,1);
   data_obs_pass_prefit_projy1_main->Draw();
   data_obs_pass_prefit_projy1_main->cd();
   data_obs_pass_prefit_projy1_main->Range(17.30769,-62.16279,209.6154,1491.907);
   data_obs_pass_prefit_projy1_main->SetFillColor(0);
   data_obs_pass_prefit_projy1_main->SetBorderMode(0);
   data_obs_pass_prefit_projy1_main->SetBorderSize(2);
   data_obs_pass_prefit_projy1_main->SetTickx(1);
   data_obs_pass_prefit_projy1_main->SetTicky(1);
   data_obs_pass_prefit_projy1_main->SetLeftMargin(0.17);
   data_obs_pass_prefit_projy1_main->SetRightMargin(0.05);
   data_obs_pass_prefit_projy1_main->SetBottomMargin(0.04);
   data_obs_pass_prefit_projy1_main->SetFrameFillStyle(0);
   data_obs_pass_prefit_projy1_main->SetFrameBorderMode(0);
   data_obs_pass_prefit_projy1_main->SetFrameFillStyle(0);
   data_obs_pass_prefit_projy1_main->SetFrameBorderMode(0);
   Double_t xAxis705[2] = {50, 200}; 
   
   TH1D *data_obs_pass_prefit_projy1__449 = new TH1D("data_obs_pass_prefit_projy1__449","",1, xAxis705);
   data_obs_pass_prefit_projy1__449->SetBinContent(1,990);
   data_obs_pass_prefit_projy1__449->SetBinError(1,31.46427);
   data_obs_pass_prefit_projy1__449->SetMinimum(0);
   data_obs_pass_prefit_projy1__449->SetMaximum(1336.5);
   data_obs_pass_prefit_projy1__449->SetEntries(990);

   Int_t ci;      // for color index setting
   TColor *color; // for color definition with alpha
   ci = TColor::GetColor("#000000");
   data_obs_pass_prefit_projy1__449->SetLineColor(ci);
   data_obs_pass_prefit_projy1__449->SetLineStyle(0);

   ci = TColor::GetColor("#000000");
   data_obs_pass_prefit_projy1__449->SetMarkerColor(ci);
   data_obs_pass_prefit_projy1__449->SetMarkerStyle(8);
   data_obs_pass_prefit_projy1__449->GetXaxis()->SetTitle("p_{T}");
   data_obs_pass_prefit_projy1__449->GetXaxis()->SetLabelFont(42);
   data_obs_pass_prefit_projy1__449->GetXaxis()->SetLabelOffset(0.05);
   data_obs_pass_prefit_projy1__449->GetXaxis()->SetLabelSize(0.07);
   data_obs_pass_prefit_projy1__449->GetXaxis()->SetTitleSize(0.09);
   data_obs_pass_prefit_projy1__449->GetXaxis()->SetTitleOffset(1.15);
   data_obs_pass_prefit_projy1__449->GetXaxis()->SetTitleFont(42);
   data_obs_pass_prefit_projy1__449->GetYaxis()->SetTitle("Events / bin");
   data_obs_pass_prefit_projy1__449->GetYaxis()->SetNdivisions(508);
   data_obs_pass_prefit_projy1__449->GetYaxis()->SetLabelFont(42);
   data_obs_pass_prefit_projy1__449->GetYaxis()->SetLabelOffset(0.007);
   data_obs_pass_prefit_projy1__449->GetYaxis()->SetLabelSize(0.07);
   data_obs_pass_prefit_projy1__449->GetYaxis()->SetTitleSize(0.09);
   data_obs_pass_prefit_projy1__449->GetYaxis()->SetTitleOffset(0.8);
   data_obs_pass_prefit_projy1__449->GetYaxis()->SetTitleFont(42);
   data_obs_pass_prefit_projy1__449->GetZaxis()->SetLabelFont(42);
   data_obs_pass_prefit_projy1__449->GetZaxis()->SetLabelOffset(0.007);
   data_obs_pass_prefit_projy1__449->GetZaxis()->SetLabelSize(0.05);
   data_obs_pass_prefit_projy1__449->GetZaxis()->SetTitleSize(0.08);
   data_obs_pass_prefit_projy1__449->GetZaxis()->SetTitleFont(42);
   data_obs_pass_prefit_projy1__449->Draw("pe X0");
   
   THStack *prefit_projy1_pass_stack = new THStack();
   prefit_projy1_pass_stack->SetName("prefit_projy1_pass_stack");
   prefit_projy1_pass_stack->SetTitle("prefit_projy1_pass_stack");
   Double_t xAxis706[2] = {50, 200}; 
   
   TH1F *prefit_projy1_pass_stack_stack_129 = new TH1F("prefit_projy1_pass_stack_stack_129","prefit_projy1_pass_stack",1, xAxis706);
   prefit_projy1_pass_stack_stack_129->SetMinimum(0);
   prefit_projy1_pass_stack_stack_129->SetMaximum(110.3708);
   prefit_projy1_pass_stack_stack_129->SetDirectory(0);
   prefit_projy1_pass_stack_stack_129->SetStats(0);
   prefit_projy1_pass_stack_stack_129->SetLineStyle(0);
   prefit_projy1_pass_stack_stack_129->GetXaxis()->SetLabelFont(42);
   prefit_projy1_pass_stack_stack_129->GetXaxis()->SetLabelOffset(0.007);
   prefit_projy1_pass_stack_stack_129->GetXaxis()->SetLabelSize(0.05);
   prefit_projy1_pass_stack_stack_129->GetXaxis()->SetTitleSize(0.08);
   prefit_projy1_pass_stack_stack_129->GetXaxis()->SetTitleOffset(0.9);
   prefit_projy1_pass_stack_stack_129->GetXaxis()->SetTitleFont(42);
   prefit_projy1_pass_stack_stack_129->GetYaxis()->SetNdivisions(508);
   prefit_projy1_pass_stack_stack_129->GetYaxis()->SetLabelFont(42);
   prefit_projy1_pass_stack_stack_129->GetYaxis()->SetLabelOffset(0.007);
   prefit_projy1_pass_stack_stack_129->GetYaxis()->SetLabelSize(0.05);
   prefit_projy1_pass_stack_stack_129->GetYaxis()->SetTitleSize(0.08);
   prefit_projy1_pass_stack_stack_129->GetYaxis()->SetTitleOffset(1.25);
   prefit_projy1_pass_stack_stack_129->GetYaxis()->SetTitleFont(42);
   prefit_projy1_pass_stack_stack_129->GetZaxis()->SetLabelFont(42);
   prefit_projy1_pass_stack_stack_129->GetZaxis()->SetLabelOffset(0.007);
   prefit_projy1_pass_stack_stack_129->GetZaxis()->SetLabelSize(0.05);
   prefit_projy1_pass_stack_stack_129->GetZaxis()->SetTitleSize(0.08);
   prefit_projy1_pass_stack_stack_129->GetZaxis()->SetTitleFont(42);
   prefit_projy1_pass_stack->SetHistogram(prefit_projy1_pass_stack_stack_129);
   
   Double_t xAxis707[2] = {50, 200}; 
   
   TH1D *Background_0x0_pass_prefit_projy1_stack_1 = new TH1D("Background_0x0_pass_prefit_projy1_stack_1","Background, pass, prefit, 0.24-1.0",1, xAxis707);
   Background_0x0_pass_prefit_projy1_stack_1->SetBinContent(1,62.44);
   Background_0x0_pass_prefit_projy1_stack_1->SetBinError(1,42.67506);
   Background_0x0_pass_prefit_projy1_stack_1->SetMinimum(0);
   Background_0x0_pass_prefit_projy1_stack_1->SetEntries(2.140807);

   ci = TColor::GetColor("#ffff00");
   Background_0x0_pass_prefit_projy1_stack_1->SetFillColor(ci);

   ci = 1435;
   color = new TColor(ci, 1, 1, 1, " ", 0);
   Background_0x0_pass_prefit_projy1_stack_1->SetLineColor(ci);
   Background_0x0_pass_prefit_projy1_stack_1->SetLineStyle(0);
   Background_0x0_pass_prefit_projy1_stack_1->GetXaxis()->SetTitle("p_{T}");
   Background_0x0_pass_prefit_projy1_stack_1->GetXaxis()->SetLabelFont(42);
   Background_0x0_pass_prefit_projy1_stack_1->GetXaxis()->SetLabelOffset(0.007);
   Background_0x0_pass_prefit_projy1_stack_1->GetXaxis()->SetLabelSize(0.05);
   Background_0x0_pass_prefit_projy1_stack_1->GetXaxis()->SetTitleSize(0.08);
   Background_0x0_pass_prefit_projy1_stack_1->GetXaxis()->SetTitleOffset(1.25);
   Background_0x0_pass_prefit_projy1_stack_1->GetXaxis()->SetTitleFont(42);
   Background_0x0_pass_prefit_projy1_stack_1->GetYaxis()->SetTitle("Events / bin");
   Background_0x0_pass_prefit_projy1_stack_1->GetYaxis()->SetLabelFont(42);
   Background_0x0_pass_prefit_projy1_stack_1->GetYaxis()->SetLabelOffset(0.007);
   Background_0x0_pass_prefit_projy1_stack_1->GetYaxis()->SetLabelSize(0.05);
   Background_0x0_pass_prefit_projy1_stack_1->GetYaxis()->SetTitleSize(0.08);
   Background_0x0_pass_prefit_projy1_stack_1->GetYaxis()->SetTitleOffset(1.25);
   Background_0x0_pass_prefit_projy1_stack_1->GetYaxis()->SetTitleFont(42);
   Background_0x0_pass_prefit_projy1_stack_1->GetZaxis()->SetLabelFont(42);
   Background_0x0_pass_prefit_projy1_stack_1->GetZaxis()->SetLabelOffset(0.007);
   Background_0x0_pass_prefit_projy1_stack_1->GetZaxis()->SetLabelSize(0.05);
   Background_0x0_pass_prefit_projy1_stack_1->GetZaxis()->SetTitleSize(0.08);
   Background_0x0_pass_prefit_projy1_stack_1->GetZaxis()->SetTitleFont(42);
   prefit_projy1_pass_stack->Add(Background_0x0_pass_prefit_projy1_stack_1,"");
   prefit_projy1_pass_stack->Draw("hist same");
   
   prefit_projy1_pass_stack = new THStack();
   prefit_projy1_pass_stack->SetName("prefit_projy1_pass_stack");
   prefit_projy1_pass_stack->SetTitle("prefit_projy1_pass_stack");
   Double_t xAxis708[2] = {50, 200}; 
   
   TH1F *prefit_projy1_pass_stack_stack_129_stack_130 = new TH1F("prefit_projy1_pass_stack_stack_129_stack_130","prefit_projy1_pass_stack",1, xAxis708);
   prefit_projy1_pass_stack_stack_129_stack_130->SetMinimum(0);
   prefit_projy1_pass_stack_stack_129_stack_130->SetMaximum(110.3708);
   prefit_projy1_pass_stack_stack_129_stack_130->SetDirectory(0);
   prefit_projy1_pass_stack_stack_129_stack_130->SetStats(0);
   prefit_projy1_pass_stack_stack_129_stack_130->SetLineStyle(0);
   prefit_projy1_pass_stack_stack_129_stack_130->GetXaxis()->SetLabelFont(42);
   prefit_projy1_pass_stack_stack_129_stack_130->GetXaxis()->SetLabelOffset(0.007);
   prefit_projy1_pass_stack_stack_129_stack_130->GetXaxis()->SetLabelSize(0.05);
   prefit_projy1_pass_stack_stack_129_stack_130->GetXaxis()->SetTitleSize(0.08);
   prefit_projy1_pass_stack_stack_129_stack_130->GetXaxis()->SetTitleOffset(0.9);
   prefit_projy1_pass_stack_stack_129_stack_130->GetXaxis()->SetTitleFont(42);
   prefit_projy1_pass_stack_stack_129_stack_130->GetYaxis()->SetNdivisions(508);
   prefit_projy1_pass_stack_stack_129_stack_130->GetYaxis()->SetLabelFont(42);
   prefit_projy1_pass_stack_stack_129_stack_130->GetYaxis()->SetLabelOffset(0.007);
   prefit_projy1_pass_stack_stack_129_stack_130->GetYaxis()->SetLabelSize(0.05);
   prefit_projy1_pass_stack_stack_129_stack_130->GetYaxis()->SetTitleSize(0.08);
   prefit_projy1_pass_stack_stack_129_stack_130->GetYaxis()->SetTitleOffset(1.25);
   prefit_projy1_pass_stack_stack_129_stack_130->GetYaxis()->SetTitleFont(42);
   prefit_projy1_pass_stack_stack_129_stack_130->GetZaxis()->SetLabelFont(42);
   prefit_projy1_pass_stack_stack_129_stack_130->GetZaxis()->SetLabelOffset(0.007);
   prefit_projy1_pass_stack_stack_129_stack_130->GetZaxis()->SetLabelSize(0.05);
   prefit_projy1_pass_stack_stack_129_stack_130->GetZaxis()->SetTitleSize(0.08);
   prefit_projy1_pass_stack_stack_129_stack_130->GetZaxis()->SetTitleFont(42);
   prefit_projy1_pass_stack->SetHistogram(prefit_projy1_pass_stack_stack_129_stack_130);
   
   Double_t xAxis709[2] = {50, 200}; 
   
   TH1D *Background_0x0_pass_prefit_projy1_stack_1_stack_1 = new TH1D("Background_0x0_pass_prefit_projy1_stack_1_stack_1","Background, pass, prefit, 0.24-1.0",1, xAxis709);
   Background_0x0_pass_prefit_projy1_stack_1_stack_1->SetBinContent(1,62.44);
   Background_0x0_pass_prefit_projy1_stack_1_stack_1->SetBinError(1,42.67506);
   Background_0x0_pass_prefit_projy1_stack_1_stack_1->SetMinimum(0);
   Background_0x0_pass_prefit_projy1_stack_1_stack_1->SetEntries(2.140807);

   ci = TColor::GetColor("#ffff00");
   Background_0x0_pass_prefit_projy1_stack_1_stack_1->SetFillColor(ci);

   ci = 1435;
   color = new TColor(ci, 1, 1, 1, " ", 0);
   Background_0x0_pass_prefit_projy1_stack_1_stack_1->SetLineColor(ci);
   Background_0x0_pass_prefit_projy1_stack_1_stack_1->SetLineStyle(0);
   Background_0x0_pass_prefit_projy1_stack_1_stack_1->GetXaxis()->SetTitle("p_{T}");
   Background_0x0_pass_prefit_projy1_stack_1_stack_1->GetXaxis()->SetLabelFont(42);
   Background_0x0_pass_prefit_projy1_stack_1_stack_1->GetXaxis()->SetLabelOffset(0.007);
   Background_0x0_pass_prefit_projy1_stack_1_stack_1->GetXaxis()->SetLabelSize(0.05);
   Background_0x0_pass_prefit_projy1_stack_1_stack_1->GetXaxis()->SetTitleSize(0.08);
   Background_0x0_pass_prefit_projy1_stack_1_stack_1->GetXaxis()->SetTitleOffset(1.25);
   Background_0x0_pass_prefit_projy1_stack_1_stack_1->GetXaxis()->SetTitleFont(42);
   Background_0x0_pass_prefit_projy1_stack_1_stack_1->GetYaxis()->SetTitle("Events / bin");
   Background_0x0_pass_prefit_projy1_stack_1_stack_1->GetYaxis()->SetLabelFont(42);
   Background_0x0_pass_prefit_projy1_stack_1_stack_1->GetYaxis()->SetLabelOffset(0.007);
   Background_0x0_pass_prefit_projy1_stack_1_stack_1->GetYaxis()->SetLabelSize(0.05);
   Background_0x0_pass_prefit_projy1_stack_1_stack_1->GetYaxis()->SetTitleSize(0.08);
   Background_0x0_pass_prefit_projy1_stack_1_stack_1->GetYaxis()->SetTitleOffset(1.25);
   Background_0x0_pass_prefit_projy1_stack_1_stack_1->GetYaxis()->SetTitleFont(42);
   Background_0x0_pass_prefit_projy1_stack_1_stack_1->GetZaxis()->SetLabelFont(42);
   Background_0x0_pass_prefit_projy1_stack_1_stack_1->GetZaxis()->SetLabelOffset(0.007);
   Background_0x0_pass_prefit_projy1_stack_1_stack_1->GetZaxis()->SetLabelSize(0.05);
   Background_0x0_pass_prefit_projy1_stack_1_stack_1->GetZaxis()->SetTitleSize(0.08);
   Background_0x0_pass_prefit_projy1_stack_1_stack_1->GetZaxis()->SetTitleFont(42);
   prefit_projy1_pass_stack->Add(Background_0x0_pass_prefit_projy1_stack_1_stack_1,"");
   prefit_projy1_pass_stack->Draw("hist same");
   Double_t xAxis710[2] = {50, 200}; 
   
   TH1D *Signal_ppStaumI557_pass_prefit_projy1__450 = new TH1D("Signal_ppStaumI557_pass_prefit_projy1__450","HSCP signal, pass, prefit, 0.24-1.0",1, xAxis710);
   Signal_ppStaumI557_pass_prefit_projy1__450->SetBinContent(1,0.232382);
   Signal_ppStaumI557_pass_prefit_projy1__450->SetBinError(1,0.03381868);
   Signal_ppStaumI557_pass_prefit_projy1__450->SetMinimum(0);
   Signal_ppStaumI557_pass_prefit_projy1__450->SetEntries(47.21626);
   Signal_ppStaumI557_pass_prefit_projy1__450->SetLineColor(2);
   Signal_ppStaumI557_pass_prefit_projy1__450->SetLineStyle(0);
   Signal_ppStaumI557_pass_prefit_projy1__450->GetXaxis()->SetTitle("p_{T}");
   Signal_ppStaumI557_pass_prefit_projy1__450->GetXaxis()->SetLabelFont(42);
   Signal_ppStaumI557_pass_prefit_projy1__450->GetXaxis()->SetLabelOffset(0.007);
   Signal_ppStaumI557_pass_prefit_projy1__450->GetXaxis()->SetLabelSize(0.05);
   Signal_ppStaumI557_pass_prefit_projy1__450->GetXaxis()->SetTitleSize(0.08);
   Signal_ppStaumI557_pass_prefit_projy1__450->GetXaxis()->SetTitleOffset(1.25);
   Signal_ppStaumI557_pass_prefit_projy1__450->GetXaxis()->SetTitleFont(42);
   Signal_ppStaumI557_pass_prefit_projy1__450->GetYaxis()->SetTitle("Events / bin");
   Signal_ppStaumI557_pass_prefit_projy1__450->GetYaxis()->SetLabelFont(42);
   Signal_ppStaumI557_pass_prefit_projy1__450->GetYaxis()->SetLabelOffset(0.007);
   Signal_ppStaumI557_pass_prefit_projy1__450->GetYaxis()->SetLabelSize(0.05);
   Signal_ppStaumI557_pass_prefit_projy1__450->GetYaxis()->SetTitleSize(0.08);
   Signal_ppStaumI557_pass_prefit_projy1__450->GetYaxis()->SetTitleOffset(1.25);
   Signal_ppStaumI557_pass_prefit_projy1__450->GetYaxis()->SetTitleFont(42);
   Signal_ppStaumI557_pass_prefit_projy1__450->GetZaxis()->SetLabelFont(42);
   Signal_ppStaumI557_pass_prefit_projy1__450->GetZaxis()->SetLabelOffset(0.007);
   Signal_ppStaumI557_pass_prefit_projy1__450->GetZaxis()->SetLabelSize(0.05);
   Signal_ppStaumI557_pass_prefit_projy1__450->GetZaxis()->SetTitleSize(0.08);
   Signal_ppStaumI557_pass_prefit_projy1__450->GetZaxis()->SetTitleFont(42);
   Signal_ppStaumI557_pass_prefit_projy1__450->Draw("hist same");
   Double_t xAxis711[2] = {50, 200}; 
   
   TH1D *TotalBkg_pass_prefit_projy1__451 = new TH1D("TotalBkg_pass_prefit_projy1__451","TotalBkg, pass, prefit, 0.24-1.0",1, xAxis711);
   TotalBkg_pass_prefit_projy1__451->SetBinContent(1,62.44);
   TotalBkg_pass_prefit_projy1__451->SetBinError(1,42.67506);
   TotalBkg_pass_prefit_projy1__451->SetMinimum(0);
   TotalBkg_pass_prefit_projy1__451->SetEntries(2.140807);
   TotalBkg_pass_prefit_projy1__451->SetLineStyle(0);
   TotalBkg_pass_prefit_projy1__451->SetMarkerStyle(0);
   TotalBkg_pass_prefit_projy1__451->GetXaxis()->SetTitle("p_{T}");
   TotalBkg_pass_prefit_projy1__451->GetXaxis()->SetLabelFont(42);
   TotalBkg_pass_prefit_projy1__451->GetXaxis()->SetLabelOffset(0.007);
   TotalBkg_pass_prefit_projy1__451->GetXaxis()->SetLabelSize(0.05);
   TotalBkg_pass_prefit_projy1__451->GetXaxis()->SetTitleSize(0.08);
   TotalBkg_pass_prefit_projy1__451->GetXaxis()->SetTitleOffset(1.25);
   TotalBkg_pass_prefit_projy1__451->GetXaxis()->SetTitleFont(42);
   TotalBkg_pass_prefit_projy1__451->GetYaxis()->SetTitle("Events / bin");
   TotalBkg_pass_prefit_projy1__451->GetYaxis()->SetLabelFont(42);
   TotalBkg_pass_prefit_projy1__451->GetYaxis()->SetLabelOffset(0.007);
   TotalBkg_pass_prefit_projy1__451->GetYaxis()->SetLabelSize(0.05);
   TotalBkg_pass_prefit_projy1__451->GetYaxis()->SetTitleSize(0.08);
   TotalBkg_pass_prefit_projy1__451->GetYaxis()->SetTitleOffset(1.25);
   TotalBkg_pass_prefit_projy1__451->GetYaxis()->SetTitleFont(42);
   TotalBkg_pass_prefit_projy1__451->GetZaxis()->SetLabelFont(42);
   TotalBkg_pass_prefit_projy1__451->GetZaxis()->SetLabelOffset(0.007);
   TotalBkg_pass_prefit_projy1__451->GetZaxis()->SetLabelSize(0.05);
   TotalBkg_pass_prefit_projy1__451->GetZaxis()->SetTitleSize(0.08);
   TotalBkg_pass_prefit_projy1__451->GetZaxis()->SetTitleFont(42);
   TotalBkg_pass_prefit_projy1__451->Draw("hist same");
   Double_t xAxis712[2] = {50, 200}; 
   
   TH1D *TotalBkg_pass_prefit_projy1__452 = new TH1D("TotalBkg_pass_prefit_projy1__452","TotalBkg, pass, prefit, 0.24-1.0",1, xAxis712);
   TotalBkg_pass_prefit_projy1__452->SetBinContent(1,62.44);
   TotalBkg_pass_prefit_projy1__452->SetBinError(1,42.67506);
   TotalBkg_pass_prefit_projy1__452->SetMinimum(0);
   TotalBkg_pass_prefit_projy1__452->SetEntries(2.140807);
   TotalBkg_pass_prefit_projy1__452->SetFillColor(1);
   TotalBkg_pass_prefit_projy1__452->SetFillStyle(3354);
   TotalBkg_pass_prefit_projy1__452->SetLineStyle(0);
   TotalBkg_pass_prefit_projy1__452->SetLineWidth(0);
   TotalBkg_pass_prefit_projy1__452->SetMarkerStyle(0);
   TotalBkg_pass_prefit_projy1__452->GetXaxis()->SetTitle("p_{T}");
   TotalBkg_pass_prefit_projy1__452->GetXaxis()->SetLabelFont(42);
   TotalBkg_pass_prefit_projy1__452->GetXaxis()->SetLabelOffset(0.007);
   TotalBkg_pass_prefit_projy1__452->GetXaxis()->SetLabelSize(0.05);
   TotalBkg_pass_prefit_projy1__452->GetXaxis()->SetTitleSize(0.08);
   TotalBkg_pass_prefit_projy1__452->GetXaxis()->SetTitleOffset(1.25);
   TotalBkg_pass_prefit_projy1__452->GetXaxis()->SetTitleFont(42);
   TotalBkg_pass_prefit_projy1__452->GetYaxis()->SetTitle("Events / bin");
   TotalBkg_pass_prefit_projy1__452->GetYaxis()->SetLabelFont(42);
   TotalBkg_pass_prefit_projy1__452->GetYaxis()->SetLabelOffset(0.007);
   TotalBkg_pass_prefit_projy1__452->GetYaxis()->SetLabelSize(0.05);
   TotalBkg_pass_prefit_projy1__452->GetYaxis()->SetTitleSize(0.08);
   TotalBkg_pass_prefit_projy1__452->GetYaxis()->SetTitleOffset(1.25);
   TotalBkg_pass_prefit_projy1__452->GetYaxis()->SetTitleFont(42);
   TotalBkg_pass_prefit_projy1__452->GetZaxis()->SetLabelFont(42);
   TotalBkg_pass_prefit_projy1__452->GetZaxis()->SetLabelOffset(0.007);
   TotalBkg_pass_prefit_projy1__452->GetZaxis()->SetLabelSize(0.05);
   TotalBkg_pass_prefit_projy1__452->GetZaxis()->SetTitleSize(0.08);
   TotalBkg_pass_prefit_projy1__452->GetZaxis()->SetTitleFont(42);
   TotalBkg_pass_prefit_projy1__452->Draw("e2 same");
   Double_t xAxis713[2] = {50, 200}; 
   
   TH1D *data_obs_pass_prefit_projy1__453 = new TH1D("data_obs_pass_prefit_projy1__453","",1, xAxis713);
   data_obs_pass_prefit_projy1__453->SetBinContent(1,990);
   data_obs_pass_prefit_projy1__453->SetBinError(1,31.46427);
   data_obs_pass_prefit_projy1__453->SetMinimum(0);
   data_obs_pass_prefit_projy1__453->SetMaximum(1336.5);
   data_obs_pass_prefit_projy1__453->SetEntries(990);

   ci = TColor::GetColor("#000000");
   data_obs_pass_prefit_projy1__453->SetLineColor(ci);
   data_obs_pass_prefit_projy1__453->SetLineStyle(0);

   ci = TColor::GetColor("#000000");
   data_obs_pass_prefit_projy1__453->SetMarkerColor(ci);
   data_obs_pass_prefit_projy1__453->SetMarkerStyle(8);
   data_obs_pass_prefit_projy1__453->GetXaxis()->SetTitle("p_{T}");
   data_obs_pass_prefit_projy1__453->GetXaxis()->SetLabelFont(42);
   data_obs_pass_prefit_projy1__453->GetXaxis()->SetLabelOffset(0.05);
   data_obs_pass_prefit_projy1__453->GetXaxis()->SetLabelSize(0.07);
   data_obs_pass_prefit_projy1__453->GetXaxis()->SetTitleSize(0.09);
   data_obs_pass_prefit_projy1__453->GetXaxis()->SetTitleOffset(1.15);
   data_obs_pass_prefit_projy1__453->GetXaxis()->SetTitleFont(42);
   data_obs_pass_prefit_projy1__453->GetYaxis()->SetTitle("Events / bin");
   data_obs_pass_prefit_projy1__453->GetYaxis()->SetNdivisions(508);
   data_obs_pass_prefit_projy1__453->GetYaxis()->SetLabelFont(42);
   data_obs_pass_prefit_projy1__453->GetYaxis()->SetLabelOffset(0.007);
   data_obs_pass_prefit_projy1__453->GetYaxis()->SetLabelSize(0.07);
   data_obs_pass_prefit_projy1__453->GetYaxis()->SetTitleSize(0.09);
   data_obs_pass_prefit_projy1__453->GetYaxis()->SetTitleOffset(0.8);
   data_obs_pass_prefit_projy1__453->GetYaxis()->SetTitleFont(42);
   data_obs_pass_prefit_projy1__453->GetZaxis()->SetLabelFont(42);
   data_obs_pass_prefit_projy1__453->GetZaxis()->SetLabelOffset(0.007);
   data_obs_pass_prefit_projy1__453->GetZaxis()->SetLabelSize(0.05);
   data_obs_pass_prefit_projy1__453->GetZaxis()->SetTitleSize(0.08);
   data_obs_pass_prefit_projy1__453->GetZaxis()->SetTitleFont(42);
   data_obs_pass_prefit_projy1__453->Draw("pe X0 same");
   
   TLegend *leg = new TLegend(0.65,0.64,0.9,0.88,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(1001);
   TLegendEntry *entry=leg->AddEntry("data_obs_pass_prefit_projy1","Data","pe X0");

   ci = TColor::GetColor("#000000");
   entry->SetLineColor(ci);
   entry->SetLineWidth(1);

   ci = TColor::GetColor("#000000");
   entry->SetMarkerColor(ci);
   entry->SetMarkerStyle(8);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("TotalBkg_pass_prefit_projy1","Total bkg unc.","F");
   entry->SetFillColor(1);
   entry->SetFillStyle(3354);
   entry->SetLineColor(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("Signal_ppStau-557_pass_prefit_projy1","HSCP signal","L");
   entry->SetLineColor(2);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("Background_0x0_pass_prefit_projy1_stack_1_stack_1","Background","f");

   ci = TColor::GetColor("#ffff00");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = 1435;
   color = new TColor(ci, 1, 1, 1, " ", 0);
   entry->SetLineColor(ci);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   leg->Draw();
   Double_t xAxis714[2] = {50, 200}; 
   
   TH1D *data_obs_pass_prefit_projy1_copy__454 = new TH1D("data_obs_pass_prefit_projy1_copy__454","",1, xAxis714);
   data_obs_pass_prefit_projy1_copy__454->SetBinContent(1,990);
   data_obs_pass_prefit_projy1_copy__454->SetBinError(1,31.46427);
   data_obs_pass_prefit_projy1_copy__454->SetMinimum(0);
   data_obs_pass_prefit_projy1_copy__454->SetMaximum(1336.5);
   data_obs_pass_prefit_projy1_copy__454->SetEntries(990);
   data_obs_pass_prefit_projy1_copy__454->SetDirectory(0);

   ci = TColor::GetColor("#000000");
   data_obs_pass_prefit_projy1_copy__454->SetLineColor(ci);
   data_obs_pass_prefit_projy1_copy__454->SetLineStyle(0);

   ci = TColor::GetColor("#000000");
   data_obs_pass_prefit_projy1_copy__454->SetMarkerColor(ci);
   data_obs_pass_prefit_projy1_copy__454->SetMarkerStyle(8);
   data_obs_pass_prefit_projy1_copy__454->GetXaxis()->SetTitle("p_{T}");
   data_obs_pass_prefit_projy1_copy__454->GetXaxis()->SetLabelFont(42);
   data_obs_pass_prefit_projy1_copy__454->GetXaxis()->SetLabelOffset(0.05);
   data_obs_pass_prefit_projy1_copy__454->GetXaxis()->SetLabelSize(0.07);
   data_obs_pass_prefit_projy1_copy__454->GetXaxis()->SetTitleSize(0.09);
   data_obs_pass_prefit_projy1_copy__454->GetXaxis()->SetTitleOffset(1.15);
   data_obs_pass_prefit_projy1_copy__454->GetXaxis()->SetTitleFont(42);
   data_obs_pass_prefit_projy1_copy__454->GetYaxis()->SetTitle("Events / bin");
   data_obs_pass_prefit_projy1_copy__454->GetYaxis()->SetNdivisions(508);
   data_obs_pass_prefit_projy1_copy__454->GetYaxis()->SetLabelFont(42);
   data_obs_pass_prefit_projy1_copy__454->GetYaxis()->SetLabelOffset(0.007);
   data_obs_pass_prefit_projy1_copy__454->GetYaxis()->SetLabelSize(0.07);
   data_obs_pass_prefit_projy1_copy__454->GetYaxis()->SetTitleSize(0.09);
   data_obs_pass_prefit_projy1_copy__454->GetYaxis()->SetTitleOffset(0.8);
   data_obs_pass_prefit_projy1_copy__454->GetYaxis()->SetTitleFont(42);
   data_obs_pass_prefit_projy1_copy__454->GetZaxis()->SetLabelFont(42);
   data_obs_pass_prefit_projy1_copy__454->GetZaxis()->SetLabelOffset(0.007);
   data_obs_pass_prefit_projy1_copy__454->GetZaxis()->SetLabelSize(0.05);
   data_obs_pass_prefit_projy1_copy__454->GetZaxis()->SetTitleSize(0.08);
   data_obs_pass_prefit_projy1_copy__454->GetZaxis()->SetTitleFont(42);
   data_obs_pass_prefit_projy1_copy__454->Draw("sameaxis");
   TLatex *   tex = new TLatex(0.21,0.83,"55 < p_{T} < 200 GeV, F^{Pixels}_{i} > 0.9");
tex->SetNDC();
   tex->SetTextAlign(12);
   tex->SetTextFont(42);
   tex->SetTextSize(0.06);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.17,0.92,"CMS");
tex->SetNDC();
   tex->SetTextFont(61);
   tex->SetTextSize(0.0675);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.25,0.92,"Preliminary");
tex->SetNDC();
   tex->SetTextFont(52);
   tex->SetTextSize(0.0485);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.95,0.92,"101 fb^{-1} (13 TeV)");
tex->SetNDC();
   tex->SetTextAlign(31);
   tex->SetTextFont(42);
   tex->SetTextSize(0.07);
   tex->SetLineWidth(2);
   tex->Draw();
   data_obs_pass_prefit_projy1_main->Modified();
   plots_fit_b/base_figs/prefit_projy1_pass->cd();
  
// ------------>Primitives in pad: data_obs_pass_prefit_projy1_sub
   TPad *data_obs_pass_prefit_projy1_sub = new TPad("data_obs_pass_prefit_projy1_sub", "data_obs_pass_prefit_projy1_sub",0,0,1,0.35);
   data_obs_pass_prefit_projy1_sub->Draw();
   data_obs_pass_prefit_projy1_sub->cd();
   data_obs_pass_prefit_projy1_sub->Range(17.30769,-6.023077,209.6154,2.9);
   data_obs_pass_prefit_projy1_sub->SetFillColor(0);
   data_obs_pass_prefit_projy1_sub->SetBorderMode(0);
   data_obs_pass_prefit_projy1_sub->SetBorderSize(2);
   data_obs_pass_prefit_projy1_sub->SetTickx(1);
   data_obs_pass_prefit_projy1_sub->SetTicky(1);
   data_obs_pass_prefit_projy1_sub->SetLeftMargin(0.17);
   data_obs_pass_prefit_projy1_sub->SetRightMargin(0.05);
   data_obs_pass_prefit_projy1_sub->SetTopMargin(0);
   data_obs_pass_prefit_projy1_sub->SetBottomMargin(0.35);
   data_obs_pass_prefit_projy1_sub->SetFrameFillStyle(0);
   data_obs_pass_prefit_projy1_sub->SetFrameBorderMode(0);
   data_obs_pass_prefit_projy1_sub->SetFrameFillStyle(0);
   data_obs_pass_prefit_projy1_sub->SetFrameBorderMode(0);
   Double_t xAxis715[2] = {50, 200}; 
   
   TH1D *data_obs_pass_prefit_projy1_pull__455 = new TH1D("data_obs_pass_prefit_projy1_pull__455","",1, xAxis715);
   data_obs_pass_prefit_projy1_pull__455->SetBinContent(1,17.49544);
   data_obs_pass_prefit_projy1_pull__455->SetBinError(1,53.02038);
   data_obs_pass_prefit_projy1_pull__455->SetMinimum(-2.9);
   data_obs_pass_prefit_projy1_pull__455->SetMaximum(2.9);
   data_obs_pass_prefit_projy1_pull__455->SetEntries(307.0542);
   data_obs_pass_prefit_projy1_pull__455->SetStats(0);

   ci = TColor::GetColor("#0000ff");
   data_obs_pass_prefit_projy1_pull__455->SetFillColor(ci);

   ci = TColor::GetColor("#000000");
   data_obs_pass_prefit_projy1_pull__455->SetLineColor(ci);
   data_obs_pass_prefit_projy1_pull__455->SetLineStyle(0);

   ci = TColor::GetColor("#000000");
   data_obs_pass_prefit_projy1_pull__455->SetMarkerColor(ci);
   data_obs_pass_prefit_projy1_pull__455->SetMarkerStyle(8);
   data_obs_pass_prefit_projy1_pull__455->GetXaxis()->SetTitle("p_{T}");
   data_obs_pass_prefit_projy1_pull__455->GetXaxis()->SetLabelFont(42);
   data_obs_pass_prefit_projy1_pull__455->GetXaxis()->SetLabelOffset(0.05);
   data_obs_pass_prefit_projy1_pull__455->GetXaxis()->SetLabelSize(0.13);
   data_obs_pass_prefit_projy1_pull__455->GetXaxis()->SetTitleSize(0.15);
   data_obs_pass_prefit_projy1_pull__455->GetXaxis()->SetTitleOffset(1.15);
   data_obs_pass_prefit_projy1_pull__455->GetXaxis()->SetTitleFont(42);
   data_obs_pass_prefit_projy1_pull__455->GetYaxis()->SetTitle("(Data-Bkg)/#sigma");
   data_obs_pass_prefit_projy1_pull__455->GetYaxis()->SetNdivisions(306);
   data_obs_pass_prefit_projy1_pull__455->GetYaxis()->SetLabelFont(42);
   data_obs_pass_prefit_projy1_pull__455->GetYaxis()->SetLabelOffset(0.007);
   data_obs_pass_prefit_projy1_pull__455->GetYaxis()->SetLabelSize(0.13);
   data_obs_pass_prefit_projy1_pull__455->GetYaxis()->SetTitleSize(0.12);
   data_obs_pass_prefit_projy1_pull__455->GetYaxis()->SetTitleOffset(0.4);
   data_obs_pass_prefit_projy1_pull__455->GetYaxis()->SetTitleFont(42);
   data_obs_pass_prefit_projy1_pull__455->GetZaxis()->SetLabelFont(42);
   data_obs_pass_prefit_projy1_pull__455->GetZaxis()->SetLabelOffset(0.007);
   data_obs_pass_prefit_projy1_pull__455->GetZaxis()->SetLabelSize(0.05);
   data_obs_pass_prefit_projy1_pull__455->GetZaxis()->SetTitleSize(0.08);
   data_obs_pass_prefit_projy1_pull__455->GetZaxis()->SetTitleFont(42);
   data_obs_pass_prefit_projy1_pull__455->Draw("hist");
   data_obs_pass_prefit_projy1_sub->Modified();
   plots_fit_b/base_figs/prefit_projy1_pass->cd();
   plots_fit_b/base_figs/prefit_projy1_pass->Modified();
   plots_fit_b/base_figs/prefit_projy1_pass->cd();
   plots_fit_b/base_figs/prefit_projy1_pass->SetSelected(plots_fit_b/base_figs/prefit_projy1_pass);
}
