void prefit_projy1_fail_logy()
{
//=========Macro generated from canvas: plots_fit_b/base_figs/prefit_projy1_fail_logy/plots_fit_b/base_figs/prefit_projy1_fail_logy
//=========  (Fri Jan 12 21:00:27 2024) by ROOT version 6.14/09
   TCanvas *plots_fit_b/base_figs/prefit_projy1_fail_logy = new TCanvas("plots_fit_b/base_figs/prefit_projy1_fail_logy", "plots_fit_b/base_figs/prefit_projy1_fail_logy",0,0,800,700);
   gStyle->SetOptFit(1);
   gStyle->SetOptStat(0);
   plots_fit_b/base_figs/prefit_projy1_fail_logy->SetHighLightColor(2);
   plots_fit_b/base_figs/prefit_projy1_fail_logy->Range(0,0,1,1);
   plots_fit_b/base_figs/prefit_projy1_fail_logy->SetFillColor(0);
   plots_fit_b/base_figs/prefit_projy1_fail_logy->SetBorderMode(0);
   plots_fit_b/base_figs/prefit_projy1_fail_logy->SetBorderSize(2);
   plots_fit_b/base_figs/prefit_projy1_fail_logy->SetTickx(1);
   plots_fit_b/base_figs/prefit_projy1_fail_logy->SetTicky(1);
   plots_fit_b/base_figs/prefit_projy1_fail_logy->SetLeftMargin(0.16);
   plots_fit_b/base_figs/prefit_projy1_fail_logy->SetRightMargin(0);
   plots_fit_b/base_figs/prefit_projy1_fail_logy->SetTopMargin(0);
   plots_fit_b/base_figs/prefit_projy1_fail_logy->SetBottomMargin(0);
   plots_fit_b/base_figs/prefit_projy1_fail_logy->SetFrameFillStyle(0);
   plots_fit_b/base_figs/prefit_projy1_fail_logy->SetFrameBorderMode(0);
  
// ------------>Primitives in pad: data_obs_fail_prefit_projy1_main
   TPad *data_obs_fail_prefit_projy1_main = new TPad("data_obs_fail_prefit_projy1_main", "data_obs_fail_prefit_projy1_main",0,0.35,1,1);
   data_obs_fail_prefit_projy1_main->Draw();
   data_obs_fail_prefit_projy1_main->cd();
   data_obs_fail_prefit_projy1_main->Range(17.30769,-3.407214,209.6154,6.773135);
   data_obs_fail_prefit_projy1_main->SetFillColor(0);
   data_obs_fail_prefit_projy1_main->SetBorderMode(0);
   data_obs_fail_prefit_projy1_main->SetBorderSize(2);
   data_obs_fail_prefit_projy1_main->SetLogy();
   data_obs_fail_prefit_projy1_main->SetTickx(1);
   data_obs_fail_prefit_projy1_main->SetTicky(1);
   data_obs_fail_prefit_projy1_main->SetLeftMargin(0.17);
   data_obs_fail_prefit_projy1_main->SetRightMargin(0.05);
   data_obs_fail_prefit_projy1_main->SetBottomMargin(0.04);
   data_obs_fail_prefit_projy1_main->SetFrameFillStyle(0);
   data_obs_fail_prefit_projy1_main->SetFrameBorderMode(0);
   data_obs_fail_prefit_projy1_main->SetFrameFillStyle(0);
   data_obs_fail_prefit_projy1_main->SetFrameBorderMode(0);
   Double_t xAxis639[2] = {50, 200}; 
   
   TH1D *data_obs_fail_prefit_projy1__407 = new TH1D("data_obs_fail_prefit_projy1__407","",1, xAxis639);
   data_obs_fail_prefit_projy1__407->SetBinContent(1,6244);
   data_obs_fail_prefit_projy1__407->SetBinError(1,79.01899);
   data_obs_fail_prefit_projy1__407->SetMinimum(0.001);
   data_obs_fail_prefit_projy1__407->SetMaximum(568984.5);
   data_obs_fail_prefit_projy1__407->SetEntries(6244);

   Int_t ci;      // for color index setting
   TColor *color; // for color definition with alpha
   ci = TColor::GetColor("#000000");
   data_obs_fail_prefit_projy1__407->SetLineColor(ci);
   data_obs_fail_prefit_projy1__407->SetLineStyle(0);

   ci = TColor::GetColor("#000000");
   data_obs_fail_prefit_projy1__407->SetMarkerColor(ci);
   data_obs_fail_prefit_projy1__407->SetMarkerStyle(8);
   data_obs_fail_prefit_projy1__407->GetXaxis()->SetTitle("p_{T}");
   data_obs_fail_prefit_projy1__407->GetXaxis()->SetLabelFont(42);
   data_obs_fail_prefit_projy1__407->GetXaxis()->SetLabelOffset(0.05);
   data_obs_fail_prefit_projy1__407->GetXaxis()->SetLabelSize(0.07);
   data_obs_fail_prefit_projy1__407->GetXaxis()->SetTitleSize(0.09);
   data_obs_fail_prefit_projy1__407->GetXaxis()->SetTitleOffset(1.15);
   data_obs_fail_prefit_projy1__407->GetXaxis()->SetTitleFont(42);
   data_obs_fail_prefit_projy1__407->GetYaxis()->SetTitle("Events / bin");
   data_obs_fail_prefit_projy1__407->GetYaxis()->SetNdivisions(508);
   data_obs_fail_prefit_projy1__407->GetYaxis()->SetLabelFont(42);
   data_obs_fail_prefit_projy1__407->GetYaxis()->SetLabelOffset(0.007);
   data_obs_fail_prefit_projy1__407->GetYaxis()->SetLabelSize(0.07);
   data_obs_fail_prefit_projy1__407->GetYaxis()->SetTitleSize(0.09);
   data_obs_fail_prefit_projy1__407->GetYaxis()->SetTitleOffset(0.8);
   data_obs_fail_prefit_projy1__407->GetYaxis()->SetTitleFont(42);
   data_obs_fail_prefit_projy1__407->GetZaxis()->SetLabelFont(42);
   data_obs_fail_prefit_projy1__407->GetZaxis()->SetLabelOffset(0.007);
   data_obs_fail_prefit_projy1__407->GetZaxis()->SetLabelSize(0.05);
   data_obs_fail_prefit_projy1__407->GetZaxis()->SetTitleSize(0.08);
   data_obs_fail_prefit_projy1__407->GetZaxis()->SetTitleFont(42);
   data_obs_fail_prefit_projy1__407->Draw("pe X0");
   
   THStack *prefit_projy1_fail_logy_stack = new THStack();
   prefit_projy1_fail_logy_stack->SetName("prefit_projy1_fail_logy_stack");
   prefit_projy1_fail_logy_stack->SetTitle("prefit_projy1_fail_logy_stack");
   prefit_projy1_fail_logy_stack->SetMinimum(0.001);
   Double_t xAxis640[2] = {50, 200}; 
   
   TH1F *prefit_projy1_fail_logy_stack_stack_117 = new TH1F("prefit_projy1_fail_logy_stack_stack_117","prefit_projy1_fail_logy_stack",1, xAxis640);
   prefit_projy1_fail_logy_stack_stack_117->SetMinimum(0.00022739);
   prefit_projy1_fail_logy_stack_stack_117->SetMaximum(14730.17);
   prefit_projy1_fail_logy_stack_stack_117->SetDirectory(0);
   prefit_projy1_fail_logy_stack_stack_117->SetStats(0);
   prefit_projy1_fail_logy_stack_stack_117->SetLineStyle(0);
   prefit_projy1_fail_logy_stack_stack_117->GetXaxis()->SetLabelFont(42);
   prefit_projy1_fail_logy_stack_stack_117->GetXaxis()->SetLabelOffset(0.007);
   prefit_projy1_fail_logy_stack_stack_117->GetXaxis()->SetLabelSize(0.05);
   prefit_projy1_fail_logy_stack_stack_117->GetXaxis()->SetTitleSize(0.08);
   prefit_projy1_fail_logy_stack_stack_117->GetXaxis()->SetTitleOffset(0.9);
   prefit_projy1_fail_logy_stack_stack_117->GetXaxis()->SetTitleFont(42);
   prefit_projy1_fail_logy_stack_stack_117->GetYaxis()->SetNdivisions(508);
   prefit_projy1_fail_logy_stack_stack_117->GetYaxis()->SetLabelFont(42);
   prefit_projy1_fail_logy_stack_stack_117->GetYaxis()->SetLabelOffset(0.007);
   prefit_projy1_fail_logy_stack_stack_117->GetYaxis()->SetLabelSize(0.05);
   prefit_projy1_fail_logy_stack_stack_117->GetYaxis()->SetTitleSize(0.08);
   prefit_projy1_fail_logy_stack_stack_117->GetYaxis()->SetTitleOffset(1.25);
   prefit_projy1_fail_logy_stack_stack_117->GetYaxis()->SetTitleFont(42);
   prefit_projy1_fail_logy_stack_stack_117->GetZaxis()->SetLabelFont(42);
   prefit_projy1_fail_logy_stack_stack_117->GetZaxis()->SetLabelOffset(0.007);
   prefit_projy1_fail_logy_stack_stack_117->GetZaxis()->SetLabelSize(0.05);
   prefit_projy1_fail_logy_stack_stack_117->GetZaxis()->SetTitleSize(0.08);
   prefit_projy1_fail_logy_stack_stack_117->GetZaxis()->SetTitleFont(42);
   prefit_projy1_fail_logy_stack->SetHistogram(prefit_projy1_fail_logy_stack_stack_117);
   
   Double_t xAxis641[2] = {50, 200}; 
   
   TH1D *Background_fail_prefit_projy1_stack_1 = new TH1D("Background_fail_prefit_projy1_stack_1","Background, fail, prefit, 0.24-1.0",1, xAxis641);
   Background_fail_prefit_projy1_stack_1->SetBinContent(1,6244);
   Background_fail_prefit_projy1_stack_1->SetMinimum(0.001);
   Background_fail_prefit_projy1_stack_1->SetEntries(6244);

   ci = TColor::GetColor("#ffff00");
   Background_fail_prefit_projy1_stack_1->SetFillColor(ci);

   ci = 1423;
   color = new TColor(ci, 1, 1, 1, " ", 0);
   Background_fail_prefit_projy1_stack_1->SetLineColor(ci);
   Background_fail_prefit_projy1_stack_1->SetLineStyle(0);
   Background_fail_prefit_projy1_stack_1->GetXaxis()->SetTitle("p_{T}");
   Background_fail_prefit_projy1_stack_1->GetXaxis()->SetLabelFont(42);
   Background_fail_prefit_projy1_stack_1->GetXaxis()->SetLabelOffset(0.007);
   Background_fail_prefit_projy1_stack_1->GetXaxis()->SetLabelSize(0.05);
   Background_fail_prefit_projy1_stack_1->GetXaxis()->SetTitleSize(0.08);
   Background_fail_prefit_projy1_stack_1->GetXaxis()->SetTitleOffset(1.25);
   Background_fail_prefit_projy1_stack_1->GetXaxis()->SetTitleFont(42);
   Background_fail_prefit_projy1_stack_1->GetYaxis()->SetTitle("Events / bin");
   Background_fail_prefit_projy1_stack_1->GetYaxis()->SetLabelFont(42);
   Background_fail_prefit_projy1_stack_1->GetYaxis()->SetLabelOffset(0.007);
   Background_fail_prefit_projy1_stack_1->GetYaxis()->SetLabelSize(0.05);
   Background_fail_prefit_projy1_stack_1->GetYaxis()->SetTitleSize(0.08);
   Background_fail_prefit_projy1_stack_1->GetYaxis()->SetTitleOffset(1.25);
   Background_fail_prefit_projy1_stack_1->GetYaxis()->SetTitleFont(42);
   Background_fail_prefit_projy1_stack_1->GetZaxis()->SetLabelFont(42);
   Background_fail_prefit_projy1_stack_1->GetZaxis()->SetLabelOffset(0.007);
   Background_fail_prefit_projy1_stack_1->GetZaxis()->SetLabelSize(0.05);
   Background_fail_prefit_projy1_stack_1->GetZaxis()->SetTitleSize(0.08);
   Background_fail_prefit_projy1_stack_1->GetZaxis()->SetTitleFont(42);
   prefit_projy1_fail_logy_stack->Add(Background_fail_prefit_projy1_stack_1,"");
   prefit_projy1_fail_logy_stack->Draw("hist same");
   
   prefit_projy1_fail_logy_stack = new THStack();
   prefit_projy1_fail_logy_stack->SetName("prefit_projy1_fail_logy_stack");
   prefit_projy1_fail_logy_stack->SetTitle("prefit_projy1_fail_logy_stack");
   prefit_projy1_fail_logy_stack->SetMinimum(0.001);
   Double_t xAxis642[2] = {50, 200}; 
   
   TH1F *prefit_projy1_fail_logy_stack_stack_117_stack_118 = new TH1F("prefit_projy1_fail_logy_stack_stack_117_stack_118","prefit_projy1_fail_logy_stack",1, xAxis642);
   prefit_projy1_fail_logy_stack_stack_117_stack_118->SetMinimum(0.00022739);
   prefit_projy1_fail_logy_stack_stack_117_stack_118->SetMaximum(14730.17);
   prefit_projy1_fail_logy_stack_stack_117_stack_118->SetDirectory(0);
   prefit_projy1_fail_logy_stack_stack_117_stack_118->SetStats(0);
   prefit_projy1_fail_logy_stack_stack_117_stack_118->SetLineStyle(0);
   prefit_projy1_fail_logy_stack_stack_117_stack_118->GetXaxis()->SetLabelFont(42);
   prefit_projy1_fail_logy_stack_stack_117_stack_118->GetXaxis()->SetLabelOffset(0.007);
   prefit_projy1_fail_logy_stack_stack_117_stack_118->GetXaxis()->SetLabelSize(0.05);
   prefit_projy1_fail_logy_stack_stack_117_stack_118->GetXaxis()->SetTitleSize(0.08);
   prefit_projy1_fail_logy_stack_stack_117_stack_118->GetXaxis()->SetTitleOffset(0.9);
   prefit_projy1_fail_logy_stack_stack_117_stack_118->GetXaxis()->SetTitleFont(42);
   prefit_projy1_fail_logy_stack_stack_117_stack_118->GetYaxis()->SetNdivisions(508);
   prefit_projy1_fail_logy_stack_stack_117_stack_118->GetYaxis()->SetLabelFont(42);
   prefit_projy1_fail_logy_stack_stack_117_stack_118->GetYaxis()->SetLabelOffset(0.007);
   prefit_projy1_fail_logy_stack_stack_117_stack_118->GetYaxis()->SetLabelSize(0.05);
   prefit_projy1_fail_logy_stack_stack_117_stack_118->GetYaxis()->SetTitleSize(0.08);
   prefit_projy1_fail_logy_stack_stack_117_stack_118->GetYaxis()->SetTitleOffset(1.25);
   prefit_projy1_fail_logy_stack_stack_117_stack_118->GetYaxis()->SetTitleFont(42);
   prefit_projy1_fail_logy_stack_stack_117_stack_118->GetZaxis()->SetLabelFont(42);
   prefit_projy1_fail_logy_stack_stack_117_stack_118->GetZaxis()->SetLabelOffset(0.007);
   prefit_projy1_fail_logy_stack_stack_117_stack_118->GetZaxis()->SetLabelSize(0.05);
   prefit_projy1_fail_logy_stack_stack_117_stack_118->GetZaxis()->SetTitleSize(0.08);
   prefit_projy1_fail_logy_stack_stack_117_stack_118->GetZaxis()->SetTitleFont(42);
   prefit_projy1_fail_logy_stack->SetHistogram(prefit_projy1_fail_logy_stack_stack_117_stack_118);
   
   Double_t xAxis643[2] = {50, 200}; 
   
   TH1D *Background_fail_prefit_projy1_stack_1_stack_1 = new TH1D("Background_fail_prefit_projy1_stack_1_stack_1","Background, fail, prefit, 0.24-1.0",1, xAxis643);
   Background_fail_prefit_projy1_stack_1_stack_1->SetBinContent(1,6244);
   Background_fail_prefit_projy1_stack_1_stack_1->SetMinimum(0.001);
   Background_fail_prefit_projy1_stack_1_stack_1->SetEntries(6244);

   ci = TColor::GetColor("#ffff00");
   Background_fail_prefit_projy1_stack_1_stack_1->SetFillColor(ci);

   ci = 1423;
   color = new TColor(ci, 1, 1, 1, " ", 0);
   Background_fail_prefit_projy1_stack_1_stack_1->SetLineColor(ci);
   Background_fail_prefit_projy1_stack_1_stack_1->SetLineStyle(0);
   Background_fail_prefit_projy1_stack_1_stack_1->GetXaxis()->SetTitle("p_{T}");
   Background_fail_prefit_projy1_stack_1_stack_1->GetXaxis()->SetLabelFont(42);
   Background_fail_prefit_projy1_stack_1_stack_1->GetXaxis()->SetLabelOffset(0.007);
   Background_fail_prefit_projy1_stack_1_stack_1->GetXaxis()->SetLabelSize(0.05);
   Background_fail_prefit_projy1_stack_1_stack_1->GetXaxis()->SetTitleSize(0.08);
   Background_fail_prefit_projy1_stack_1_stack_1->GetXaxis()->SetTitleOffset(1.25);
   Background_fail_prefit_projy1_stack_1_stack_1->GetXaxis()->SetTitleFont(42);
   Background_fail_prefit_projy1_stack_1_stack_1->GetYaxis()->SetTitle("Events / bin");
   Background_fail_prefit_projy1_stack_1_stack_1->GetYaxis()->SetLabelFont(42);
   Background_fail_prefit_projy1_stack_1_stack_1->GetYaxis()->SetLabelOffset(0.007);
   Background_fail_prefit_projy1_stack_1_stack_1->GetYaxis()->SetLabelSize(0.05);
   Background_fail_prefit_projy1_stack_1_stack_1->GetYaxis()->SetTitleSize(0.08);
   Background_fail_prefit_projy1_stack_1_stack_1->GetYaxis()->SetTitleOffset(1.25);
   Background_fail_prefit_projy1_stack_1_stack_1->GetYaxis()->SetTitleFont(42);
   Background_fail_prefit_projy1_stack_1_stack_1->GetZaxis()->SetLabelFont(42);
   Background_fail_prefit_projy1_stack_1_stack_1->GetZaxis()->SetLabelOffset(0.007);
   Background_fail_prefit_projy1_stack_1_stack_1->GetZaxis()->SetLabelSize(0.05);
   Background_fail_prefit_projy1_stack_1_stack_1->GetZaxis()->SetTitleSize(0.08);
   Background_fail_prefit_projy1_stack_1_stack_1->GetZaxis()->SetTitleFont(42);
   prefit_projy1_fail_logy_stack->Add(Background_fail_prefit_projy1_stack_1_stack_1,"");
   prefit_projy1_fail_logy_stack->Draw("hist same");
   Double_t xAxis644[2] = {50, 200}; 
   
   TH1D *Signal_ppStaumI557_fail_prefit_projy1__408 = new TH1D("Signal_ppStaumI557_fail_prefit_projy1__408","HSCP signal, fail, prefit, 0.24-1.0",1, xAxis644);
   Signal_ppStaumI557_fail_prefit_projy1__408->SetBinContent(1,4.56e-05);
   Signal_ppStaumI557_fail_prefit_projy1__408->SetBinError(1,6.498974e-07);
   Signal_ppStaumI557_fail_prefit_projy1__408->SetMinimum(0.001);
   Signal_ppStaumI557_fail_prefit_projy1__408->SetEntries(4923.116);
   Signal_ppStaumI557_fail_prefit_projy1__408->SetLineColor(2);
   Signal_ppStaumI557_fail_prefit_projy1__408->SetLineStyle(0);
   Signal_ppStaumI557_fail_prefit_projy1__408->GetXaxis()->SetTitle("p_{T}");
   Signal_ppStaumI557_fail_prefit_projy1__408->GetXaxis()->SetLabelFont(42);
   Signal_ppStaumI557_fail_prefit_projy1__408->GetXaxis()->SetLabelOffset(0.007);
   Signal_ppStaumI557_fail_prefit_projy1__408->GetXaxis()->SetLabelSize(0.05);
   Signal_ppStaumI557_fail_prefit_projy1__408->GetXaxis()->SetTitleSize(0.08);
   Signal_ppStaumI557_fail_prefit_projy1__408->GetXaxis()->SetTitleOffset(1.25);
   Signal_ppStaumI557_fail_prefit_projy1__408->GetXaxis()->SetTitleFont(42);
   Signal_ppStaumI557_fail_prefit_projy1__408->GetYaxis()->SetTitle("Events / bin");
   Signal_ppStaumI557_fail_prefit_projy1__408->GetYaxis()->SetLabelFont(42);
   Signal_ppStaumI557_fail_prefit_projy1__408->GetYaxis()->SetLabelOffset(0.007);
   Signal_ppStaumI557_fail_prefit_projy1__408->GetYaxis()->SetLabelSize(0.05);
   Signal_ppStaumI557_fail_prefit_projy1__408->GetYaxis()->SetTitleSize(0.08);
   Signal_ppStaumI557_fail_prefit_projy1__408->GetYaxis()->SetTitleOffset(1.25);
   Signal_ppStaumI557_fail_prefit_projy1__408->GetYaxis()->SetTitleFont(42);
   Signal_ppStaumI557_fail_prefit_projy1__408->GetZaxis()->SetLabelFont(42);
   Signal_ppStaumI557_fail_prefit_projy1__408->GetZaxis()->SetLabelOffset(0.007);
   Signal_ppStaumI557_fail_prefit_projy1__408->GetZaxis()->SetLabelSize(0.05);
   Signal_ppStaumI557_fail_prefit_projy1__408->GetZaxis()->SetTitleSize(0.08);
   Signal_ppStaumI557_fail_prefit_projy1__408->GetZaxis()->SetTitleFont(42);
   Signal_ppStaumI557_fail_prefit_projy1__408->Draw("hist same");
   Double_t xAxis645[2] = {50, 200}; 
   
   TH1D *TotalBkg_fail_prefit_projy1__409 = new TH1D("TotalBkg_fail_prefit_projy1__409","TotalBkg, fail, prefit, 0.24-1.0",1, xAxis645);
   TotalBkg_fail_prefit_projy1__409->SetBinContent(1,6244);
   TotalBkg_fail_prefit_projy1__409->SetMinimum(0.001);
   TotalBkg_fail_prefit_projy1__409->SetEntries(6244);
   TotalBkg_fail_prefit_projy1__409->SetLineStyle(0);
   TotalBkg_fail_prefit_projy1__409->SetMarkerStyle(0);
   TotalBkg_fail_prefit_projy1__409->GetXaxis()->SetTitle("p_{T}");
   TotalBkg_fail_prefit_projy1__409->GetXaxis()->SetLabelFont(42);
   TotalBkg_fail_prefit_projy1__409->GetXaxis()->SetLabelOffset(0.007);
   TotalBkg_fail_prefit_projy1__409->GetXaxis()->SetLabelSize(0.05);
   TotalBkg_fail_prefit_projy1__409->GetXaxis()->SetTitleSize(0.08);
   TotalBkg_fail_prefit_projy1__409->GetXaxis()->SetTitleOffset(1.25);
   TotalBkg_fail_prefit_projy1__409->GetXaxis()->SetTitleFont(42);
   TotalBkg_fail_prefit_projy1__409->GetYaxis()->SetTitle("Events / bin");
   TotalBkg_fail_prefit_projy1__409->GetYaxis()->SetLabelFont(42);
   TotalBkg_fail_prefit_projy1__409->GetYaxis()->SetLabelOffset(0.007);
   TotalBkg_fail_prefit_projy1__409->GetYaxis()->SetLabelSize(0.05);
   TotalBkg_fail_prefit_projy1__409->GetYaxis()->SetTitleSize(0.08);
   TotalBkg_fail_prefit_projy1__409->GetYaxis()->SetTitleOffset(1.25);
   TotalBkg_fail_prefit_projy1__409->GetYaxis()->SetTitleFont(42);
   TotalBkg_fail_prefit_projy1__409->GetZaxis()->SetLabelFont(42);
   TotalBkg_fail_prefit_projy1__409->GetZaxis()->SetLabelOffset(0.007);
   TotalBkg_fail_prefit_projy1__409->GetZaxis()->SetLabelSize(0.05);
   TotalBkg_fail_prefit_projy1__409->GetZaxis()->SetTitleSize(0.08);
   TotalBkg_fail_prefit_projy1__409->GetZaxis()->SetTitleFont(42);
   TotalBkg_fail_prefit_projy1__409->Draw("hist same");
   Double_t xAxis646[2] = {50, 200}; 
   
   TH1D *TotalBkg_fail_prefit_projy1__410 = new TH1D("TotalBkg_fail_prefit_projy1__410","TotalBkg, fail, prefit, 0.24-1.0",1, xAxis646);
   TotalBkg_fail_prefit_projy1__410->SetBinContent(1,6244);
   TotalBkg_fail_prefit_projy1__410->SetMinimum(0.001);
   TotalBkg_fail_prefit_projy1__410->SetEntries(6244);
   TotalBkg_fail_prefit_projy1__410->SetFillColor(1);
   TotalBkg_fail_prefit_projy1__410->SetFillStyle(3354);
   TotalBkg_fail_prefit_projy1__410->SetLineStyle(0);
   TotalBkg_fail_prefit_projy1__410->SetLineWidth(0);
   TotalBkg_fail_prefit_projy1__410->SetMarkerStyle(0);
   TotalBkg_fail_prefit_projy1__410->GetXaxis()->SetTitle("p_{T}");
   TotalBkg_fail_prefit_projy1__410->GetXaxis()->SetLabelFont(42);
   TotalBkg_fail_prefit_projy1__410->GetXaxis()->SetLabelOffset(0.007);
   TotalBkg_fail_prefit_projy1__410->GetXaxis()->SetLabelSize(0.05);
   TotalBkg_fail_prefit_projy1__410->GetXaxis()->SetTitleSize(0.08);
   TotalBkg_fail_prefit_projy1__410->GetXaxis()->SetTitleOffset(1.25);
   TotalBkg_fail_prefit_projy1__410->GetXaxis()->SetTitleFont(42);
   TotalBkg_fail_prefit_projy1__410->GetYaxis()->SetTitle("Events / bin");
   TotalBkg_fail_prefit_projy1__410->GetYaxis()->SetLabelFont(42);
   TotalBkg_fail_prefit_projy1__410->GetYaxis()->SetLabelOffset(0.007);
   TotalBkg_fail_prefit_projy1__410->GetYaxis()->SetLabelSize(0.05);
   TotalBkg_fail_prefit_projy1__410->GetYaxis()->SetTitleSize(0.08);
   TotalBkg_fail_prefit_projy1__410->GetYaxis()->SetTitleOffset(1.25);
   TotalBkg_fail_prefit_projy1__410->GetYaxis()->SetTitleFont(42);
   TotalBkg_fail_prefit_projy1__410->GetZaxis()->SetLabelFont(42);
   TotalBkg_fail_prefit_projy1__410->GetZaxis()->SetLabelOffset(0.007);
   TotalBkg_fail_prefit_projy1__410->GetZaxis()->SetLabelSize(0.05);
   TotalBkg_fail_prefit_projy1__410->GetZaxis()->SetTitleSize(0.08);
   TotalBkg_fail_prefit_projy1__410->GetZaxis()->SetTitleFont(42);
   TotalBkg_fail_prefit_projy1__410->Draw("e2 same");
   Double_t xAxis647[2] = {50, 200}; 
   
   TH1D *data_obs_fail_prefit_projy1__411 = new TH1D("data_obs_fail_prefit_projy1__411","",1, xAxis647);
   data_obs_fail_prefit_projy1__411->SetBinContent(1,6244);
   data_obs_fail_prefit_projy1__411->SetBinError(1,79.01899);
   data_obs_fail_prefit_projy1__411->SetMinimum(0.001);
   data_obs_fail_prefit_projy1__411->SetMaximum(568984.5);
   data_obs_fail_prefit_projy1__411->SetEntries(6244);

   ci = TColor::GetColor("#000000");
   data_obs_fail_prefit_projy1__411->SetLineColor(ci);
   data_obs_fail_prefit_projy1__411->SetLineStyle(0);

   ci = TColor::GetColor("#000000");
   data_obs_fail_prefit_projy1__411->SetMarkerColor(ci);
   data_obs_fail_prefit_projy1__411->SetMarkerStyle(8);
   data_obs_fail_prefit_projy1__411->GetXaxis()->SetTitle("p_{T}");
   data_obs_fail_prefit_projy1__411->GetXaxis()->SetLabelFont(42);
   data_obs_fail_prefit_projy1__411->GetXaxis()->SetLabelOffset(0.05);
   data_obs_fail_prefit_projy1__411->GetXaxis()->SetLabelSize(0.07);
   data_obs_fail_prefit_projy1__411->GetXaxis()->SetTitleSize(0.09);
   data_obs_fail_prefit_projy1__411->GetXaxis()->SetTitleOffset(1.15);
   data_obs_fail_prefit_projy1__411->GetXaxis()->SetTitleFont(42);
   data_obs_fail_prefit_projy1__411->GetYaxis()->SetTitle("Events / bin");
   data_obs_fail_prefit_projy1__411->GetYaxis()->SetNdivisions(508);
   data_obs_fail_prefit_projy1__411->GetYaxis()->SetLabelFont(42);
   data_obs_fail_prefit_projy1__411->GetYaxis()->SetLabelOffset(0.007);
   data_obs_fail_prefit_projy1__411->GetYaxis()->SetLabelSize(0.07);
   data_obs_fail_prefit_projy1__411->GetYaxis()->SetTitleSize(0.09);
   data_obs_fail_prefit_projy1__411->GetYaxis()->SetTitleOffset(0.8);
   data_obs_fail_prefit_projy1__411->GetYaxis()->SetTitleFont(42);
   data_obs_fail_prefit_projy1__411->GetZaxis()->SetLabelFont(42);
   data_obs_fail_prefit_projy1__411->GetZaxis()->SetLabelOffset(0.007);
   data_obs_fail_prefit_projy1__411->GetZaxis()->SetLabelSize(0.05);
   data_obs_fail_prefit_projy1__411->GetZaxis()->SetTitleSize(0.08);
   data_obs_fail_prefit_projy1__411->GetZaxis()->SetTitleFont(42);
   data_obs_fail_prefit_projy1__411->Draw("pe X0 same");
   
   TLegend *leg = new TLegend(0.65,0.64,0.9,0.88,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(1001);
   TLegendEntry *entry=leg->AddEntry("data_obs_fail_prefit_projy1","Data","pe X0");

   ci = TColor::GetColor("#000000");
   entry->SetLineColor(ci);
   entry->SetLineWidth(1);

   ci = TColor::GetColor("#000000");
   entry->SetMarkerColor(ci);
   entry->SetMarkerStyle(8);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("TotalBkg_fail_prefit_projy1","Total bkg unc.","F");
   entry->SetFillColor(1);
   entry->SetFillStyle(3354);
   entry->SetLineColor(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("Signal_ppStau-557_fail_prefit_projy1","HSCP signal","L");
   entry->SetLineColor(2);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("Background_fail_prefit_projy1_stack_1_stack_1","Background","f");

   ci = TColor::GetColor("#ffff00");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = 1423;
   color = new TColor(ci, 1, 1, 1, " ", 0);
   entry->SetLineColor(ci);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   leg->Draw();
   Double_t xAxis648[2] = {50, 200}; 
   
   TH1D *data_obs_fail_prefit_projy1_copy__412 = new TH1D("data_obs_fail_prefit_projy1_copy__412","",1, xAxis648);
   data_obs_fail_prefit_projy1_copy__412->SetBinContent(1,6244);
   data_obs_fail_prefit_projy1_copy__412->SetBinError(1,79.01899);
   data_obs_fail_prefit_projy1_copy__412->SetMinimum(0.001);
   data_obs_fail_prefit_projy1_copy__412->SetMaximum(568984.5);
   data_obs_fail_prefit_projy1_copy__412->SetEntries(6244);
   data_obs_fail_prefit_projy1_copy__412->SetDirectory(0);

   ci = TColor::GetColor("#000000");
   data_obs_fail_prefit_projy1_copy__412->SetLineColor(ci);
   data_obs_fail_prefit_projy1_copy__412->SetLineStyle(0);

   ci = TColor::GetColor("#000000");
   data_obs_fail_prefit_projy1_copy__412->SetMarkerColor(ci);
   data_obs_fail_prefit_projy1_copy__412->SetMarkerStyle(8);
   data_obs_fail_prefit_projy1_copy__412->GetXaxis()->SetTitle("p_{T}");
   data_obs_fail_prefit_projy1_copy__412->GetXaxis()->SetLabelFont(42);
   data_obs_fail_prefit_projy1_copy__412->GetXaxis()->SetLabelOffset(0.05);
   data_obs_fail_prefit_projy1_copy__412->GetXaxis()->SetLabelSize(0.07);
   data_obs_fail_prefit_projy1_copy__412->GetXaxis()->SetTitleSize(0.09);
   data_obs_fail_prefit_projy1_copy__412->GetXaxis()->SetTitleOffset(1.15);
   data_obs_fail_prefit_projy1_copy__412->GetXaxis()->SetTitleFont(42);
   data_obs_fail_prefit_projy1_copy__412->GetYaxis()->SetTitle("Events / bin");
   data_obs_fail_prefit_projy1_copy__412->GetYaxis()->SetNdivisions(508);
   data_obs_fail_prefit_projy1_copy__412->GetYaxis()->SetLabelFont(42);
   data_obs_fail_prefit_projy1_copy__412->GetYaxis()->SetLabelOffset(0.007);
   data_obs_fail_prefit_projy1_copy__412->GetYaxis()->SetLabelSize(0.07);
   data_obs_fail_prefit_projy1_copy__412->GetYaxis()->SetTitleSize(0.09);
   data_obs_fail_prefit_projy1_copy__412->GetYaxis()->SetTitleOffset(0.8);
   data_obs_fail_prefit_projy1_copy__412->GetYaxis()->SetTitleFont(42);
   data_obs_fail_prefit_projy1_copy__412->GetZaxis()->SetLabelFont(42);
   data_obs_fail_prefit_projy1_copy__412->GetZaxis()->SetLabelOffset(0.007);
   data_obs_fail_prefit_projy1_copy__412->GetZaxis()->SetLabelSize(0.05);
   data_obs_fail_prefit_projy1_copy__412->GetZaxis()->SetTitleSize(0.08);
   data_obs_fail_prefit_projy1_copy__412->GetZaxis()->SetTitleFont(42);
   data_obs_fail_prefit_projy1_copy__412->Draw("sameaxis");
   TLatex *   tex = new TLatex(0.21,0.83,"55 < p_{T} < 200 GeV, F^{Pixels}_{i} < 0.9");
tex->SetNDC();
   tex->SetTextAlign(12);
   tex->SetTextFont(42);
   tex->SetTextSize(0.06);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.17,0.92,"CMS");
tex->SetNDC();
   tex->SetTextFont(61);
   tex->SetTextSize(0.0675);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.25,0.92,"Preliminary");
tex->SetNDC();
   tex->SetTextFont(52);
   tex->SetTextSize(0.0485);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.95,0.92,"101 fb^{-1} (13 TeV)");
tex->SetNDC();
   tex->SetTextAlign(31);
   tex->SetTextFont(42);
   tex->SetTextSize(0.07);
   tex->SetLineWidth(2);
   tex->Draw();
   data_obs_fail_prefit_projy1_main->Modified();
   plots_fit_b/base_figs/prefit_projy1_fail_logy->cd();
  
// ------------>Primitives in pad: data_obs_fail_prefit_projy1_sub
   TPad *data_obs_fail_prefit_projy1_sub = new TPad("data_obs_fail_prefit_projy1_sub", "data_obs_fail_prefit_projy1_sub",0,0,1,0.35);
   data_obs_fail_prefit_projy1_sub->Draw();
   data_obs_fail_prefit_projy1_sub->cd();
   data_obs_fail_prefit_projy1_sub->Range(17.30769,-6.023077,209.6154,2.9);
   data_obs_fail_prefit_projy1_sub->SetFillColor(0);
   data_obs_fail_prefit_projy1_sub->SetBorderMode(0);
   data_obs_fail_prefit_projy1_sub->SetBorderSize(2);
   data_obs_fail_prefit_projy1_sub->SetTickx(1);
   data_obs_fail_prefit_projy1_sub->SetTicky(1);
   data_obs_fail_prefit_projy1_sub->SetLeftMargin(0.17);
   data_obs_fail_prefit_projy1_sub->SetRightMargin(0.05);
   data_obs_fail_prefit_projy1_sub->SetTopMargin(0);
   data_obs_fail_prefit_projy1_sub->SetBottomMargin(0.35);
   data_obs_fail_prefit_projy1_sub->SetFrameFillStyle(0);
   data_obs_fail_prefit_projy1_sub->SetFrameBorderMode(0);
   data_obs_fail_prefit_projy1_sub->SetFrameFillStyle(0);
   data_obs_fail_prefit_projy1_sub->SetFrameBorderMode(0);
   Double_t xAxis649[2] = {50, 200}; 
   
   TH1D *data_obs_fail_prefit_projy1_pull__413 = new TH1D("data_obs_fail_prefit_projy1_pull__413","",1, xAxis649);
   data_obs_fail_prefit_projy1_pull__413->SetBinContent(1,-1.544859e-06);
   data_obs_fail_prefit_projy1_pull__413->SetBinError(1,79.01899);
   data_obs_fail_prefit_projy1_pull__413->SetMinimum(-2.9);
   data_obs_fail_prefit_projy1_pull__413->SetMaximum(2.9);
   data_obs_fail_prefit_projy1_pull__413->SetEntries(1.000122);
   data_obs_fail_prefit_projy1_pull__413->SetStats(0);

   ci = TColor::GetColor("#0000ff");
   data_obs_fail_prefit_projy1_pull__413->SetFillColor(ci);

   ci = TColor::GetColor("#000000");
   data_obs_fail_prefit_projy1_pull__413->SetLineColor(ci);
   data_obs_fail_prefit_projy1_pull__413->SetLineStyle(0);

   ci = TColor::GetColor("#000000");
   data_obs_fail_prefit_projy1_pull__413->SetMarkerColor(ci);
   data_obs_fail_prefit_projy1_pull__413->SetMarkerStyle(8);
   data_obs_fail_prefit_projy1_pull__413->GetXaxis()->SetTitle("p_{T}");
   data_obs_fail_prefit_projy1_pull__413->GetXaxis()->SetLabelFont(42);
   data_obs_fail_prefit_projy1_pull__413->GetXaxis()->SetLabelOffset(0.05);
   data_obs_fail_prefit_projy1_pull__413->GetXaxis()->SetLabelSize(0.13);
   data_obs_fail_prefit_projy1_pull__413->GetXaxis()->SetTitleSize(0.15);
   data_obs_fail_prefit_projy1_pull__413->GetXaxis()->SetTitleOffset(1.15);
   data_obs_fail_prefit_projy1_pull__413->GetXaxis()->SetTitleFont(42);
   data_obs_fail_prefit_projy1_pull__413->GetYaxis()->SetTitle("(Data-Bkg)/#sigma");
   data_obs_fail_prefit_projy1_pull__413->GetYaxis()->SetNdivisions(306);
   data_obs_fail_prefit_projy1_pull__413->GetYaxis()->SetLabelFont(42);
   data_obs_fail_prefit_projy1_pull__413->GetYaxis()->SetLabelOffset(0.007);
   data_obs_fail_prefit_projy1_pull__413->GetYaxis()->SetLabelSize(0.13);
   data_obs_fail_prefit_projy1_pull__413->GetYaxis()->SetTitleSize(0.12);
   data_obs_fail_prefit_projy1_pull__413->GetYaxis()->SetTitleOffset(0.4);
   data_obs_fail_prefit_projy1_pull__413->GetYaxis()->SetTitleFont(42);
   data_obs_fail_prefit_projy1_pull__413->GetZaxis()->SetLabelFont(42);
   data_obs_fail_prefit_projy1_pull__413->GetZaxis()->SetLabelOffset(0.007);
   data_obs_fail_prefit_projy1_pull__413->GetZaxis()->SetLabelSize(0.05);
   data_obs_fail_prefit_projy1_pull__413->GetZaxis()->SetTitleSize(0.08);
   data_obs_fail_prefit_projy1_pull__413->GetZaxis()->SetTitleFont(42);
   data_obs_fail_prefit_projy1_pull__413->Draw("hist");
   data_obs_fail_prefit_projy1_sub->Modified();
   plots_fit_b/base_figs/prefit_projy1_fail_logy->cd();
   plots_fit_b/base_figs/prefit_projy1_fail_logy->Modified();
   plots_fit_b/base_figs/prefit_projy1_fail_logy->cd();
   plots_fit_b/base_figs/prefit_projy1_fail_logy->SetSelected(plots_fit_b/base_figs/prefit_projy1_fail_logy);
}
