void prefit_projy0_fail()
{
//=========Macro generated from canvas: plots_fit_b/base_figs/prefit_projy0_fail/plots_fit_b/base_figs/prefit_projy0_fail
//=========  (Fri Jan 12 21:00:27 2024) by ROOT version 6.14/09
   TCanvas *plots_fit_b/base_figs/prefit_projy0_fail = new TCanvas("plots_fit_b/base_figs/prefit_projy0_fail", "plots_fit_b/base_figs/prefit_projy0_fail",0,0,800,700);
   gStyle->SetOptFit(1);
   gStyle->SetOptStat(0);
   plots_fit_b/base_figs/prefit_projy0_fail->SetHighLightColor(2);
   plots_fit_b/base_figs/prefit_projy0_fail->Range(0,0,1,1);
   plots_fit_b/base_figs/prefit_projy0_fail->SetFillColor(0);
   plots_fit_b/base_figs/prefit_projy0_fail->SetBorderMode(0);
   plots_fit_b/base_figs/prefit_projy0_fail->SetBorderSize(2);
   plots_fit_b/base_figs/prefit_projy0_fail->SetTickx(1);
   plots_fit_b/base_figs/prefit_projy0_fail->SetTicky(1);
   plots_fit_b/base_figs/prefit_projy0_fail->SetLeftMargin(0.16);
   plots_fit_b/base_figs/prefit_projy0_fail->SetRightMargin(0);
   plots_fit_b/base_figs/prefit_projy0_fail->SetTopMargin(0);
   plots_fit_b/base_figs/prefit_projy0_fail->SetBottomMargin(0);
   plots_fit_b/base_figs/prefit_projy0_fail->SetFrameFillStyle(0);
   plots_fit_b/base_figs/prefit_projy0_fail->SetFrameBorderMode(0);
  
// ------------>Primitives in pad: data_obs_fail_prefit_projy0_main
   TPad *data_obs_fail_prefit_projy0_main = new TPad("data_obs_fail_prefit_projy0_main", "data_obs_fail_prefit_projy0_main",0,0.35,1,1);
   data_obs_fail_prefit_projy0_main->Draw();
   data_obs_fail_prefit_projy0_main->cd();
   data_obs_fail_prefit_projy0_main->Range(17.30769,-884431.9,209.6154,2.122636e+07);
   data_obs_fail_prefit_projy0_main->SetFillColor(0);
   data_obs_fail_prefit_projy0_main->SetBorderMode(0);
   data_obs_fail_prefit_projy0_main->SetBorderSize(2);
   data_obs_fail_prefit_projy0_main->SetTickx(1);
   data_obs_fail_prefit_projy0_main->SetTicky(1);
   data_obs_fail_prefit_projy0_main->SetLeftMargin(0.17);
   data_obs_fail_prefit_projy0_main->SetRightMargin(0.05);
   data_obs_fail_prefit_projy0_main->SetBottomMargin(0.04);
   data_obs_fail_prefit_projy0_main->SetFrameFillStyle(0);
   data_obs_fail_prefit_projy0_main->SetFrameBorderMode(0);
   data_obs_fail_prefit_projy0_main->SetFrameFillStyle(0);
   data_obs_fail_prefit_projy0_main->SetFrameBorderMode(0);
   Double_t xAxis562[2] = {50, 200}; 
   
   TH1D *data_obs_fail_prefit_projy0__358 = new TH1D("data_obs_fail_prefit_projy0__358","",1, xAxis562);
   data_obs_fail_prefit_projy0__358->SetBinContent(1,1.40854e+07);
   data_obs_fail_prefit_projy0__358->SetBinError(1,3753.052);
   data_obs_fail_prefit_projy0__358->SetMinimum(0);
   data_obs_fail_prefit_projy0__358->SetMaximum(1.901528e+07);
   data_obs_fail_prefit_projy0__358->SetEntries(1.40854e+07);

   Int_t ci;      // for color index setting
   TColor *color; // for color definition with alpha
   ci = TColor::GetColor("#000000");
   data_obs_fail_prefit_projy0__358->SetLineColor(ci);
   data_obs_fail_prefit_projy0__358->SetLineStyle(0);

   ci = TColor::GetColor("#000000");
   data_obs_fail_prefit_projy0__358->SetMarkerColor(ci);
   data_obs_fail_prefit_projy0__358->SetMarkerStyle(8);
   data_obs_fail_prefit_projy0__358->GetXaxis()->SetTitle("p_{T}");
   data_obs_fail_prefit_projy0__358->GetXaxis()->SetLabelFont(42);
   data_obs_fail_prefit_projy0__358->GetXaxis()->SetLabelOffset(0.05);
   data_obs_fail_prefit_projy0__358->GetXaxis()->SetLabelSize(0.07);
   data_obs_fail_prefit_projy0__358->GetXaxis()->SetTitleSize(0.09);
   data_obs_fail_prefit_projy0__358->GetXaxis()->SetTitleOffset(1.15);
   data_obs_fail_prefit_projy0__358->GetXaxis()->SetTitleFont(42);
   data_obs_fail_prefit_projy0__358->GetYaxis()->SetTitle("Events / bin");
   data_obs_fail_prefit_projy0__358->GetYaxis()->SetNdivisions(508);
   data_obs_fail_prefit_projy0__358->GetYaxis()->SetLabelFont(42);
   data_obs_fail_prefit_projy0__358->GetYaxis()->SetLabelOffset(0.007);
   data_obs_fail_prefit_projy0__358->GetYaxis()->SetLabelSize(0.07);
   data_obs_fail_prefit_projy0__358->GetYaxis()->SetTitleSize(0.09);
   data_obs_fail_prefit_projy0__358->GetYaxis()->SetTitleOffset(0.8);
   data_obs_fail_prefit_projy0__358->GetYaxis()->SetTitleFont(42);
   data_obs_fail_prefit_projy0__358->GetZaxis()->SetLabelFont(42);
   data_obs_fail_prefit_projy0__358->GetZaxis()->SetLabelOffset(0.007);
   data_obs_fail_prefit_projy0__358->GetZaxis()->SetLabelSize(0.05);
   data_obs_fail_prefit_projy0__358->GetZaxis()->SetTitleSize(0.08);
   data_obs_fail_prefit_projy0__358->GetZaxis()->SetTitleFont(42);
   data_obs_fail_prefit_projy0__358->Draw("pe X0");
   
   THStack *prefit_projy0_fail_stack = new THStack();
   prefit_projy0_fail_stack->SetName("prefit_projy0_fail_stack");
   prefit_projy0_fail_stack->SetTitle("prefit_projy0_fail_stack");
   Double_t xAxis563[2] = {50, 200}; 
   
   TH1F *prefit_projy0_fail_stack_stack_103 = new TH1F("prefit_projy0_fail_stack_stack_103","prefit_projy0_fail_stack",1, xAxis563);
   prefit_projy0_fail_stack_stack_103->SetMinimum(0);
   prefit_projy0_fail_stack_stack_103->SetMaximum(1.478967e+07);
   prefit_projy0_fail_stack_stack_103->SetDirectory(0);
   prefit_projy0_fail_stack_stack_103->SetStats(0);
   prefit_projy0_fail_stack_stack_103->SetLineStyle(0);
   prefit_projy0_fail_stack_stack_103->GetXaxis()->SetLabelFont(42);
   prefit_projy0_fail_stack_stack_103->GetXaxis()->SetLabelOffset(0.007);
   prefit_projy0_fail_stack_stack_103->GetXaxis()->SetLabelSize(0.05);
   prefit_projy0_fail_stack_stack_103->GetXaxis()->SetTitleSize(0.08);
   prefit_projy0_fail_stack_stack_103->GetXaxis()->SetTitleOffset(0.9);
   prefit_projy0_fail_stack_stack_103->GetXaxis()->SetTitleFont(42);
   prefit_projy0_fail_stack_stack_103->GetYaxis()->SetNdivisions(508);
   prefit_projy0_fail_stack_stack_103->GetYaxis()->SetLabelFont(42);
   prefit_projy0_fail_stack_stack_103->GetYaxis()->SetLabelOffset(0.007);
   prefit_projy0_fail_stack_stack_103->GetYaxis()->SetLabelSize(0.05);
   prefit_projy0_fail_stack_stack_103->GetYaxis()->SetTitleSize(0.08);
   prefit_projy0_fail_stack_stack_103->GetYaxis()->SetTitleOffset(1.25);
   prefit_projy0_fail_stack_stack_103->GetYaxis()->SetTitleFont(42);
   prefit_projy0_fail_stack_stack_103->GetZaxis()->SetLabelFont(42);
   prefit_projy0_fail_stack_stack_103->GetZaxis()->SetLabelOffset(0.007);
   prefit_projy0_fail_stack_stack_103->GetZaxis()->SetLabelSize(0.05);
   prefit_projy0_fail_stack_stack_103->GetZaxis()->SetTitleSize(0.08);
   prefit_projy0_fail_stack_stack_103->GetZaxis()->SetTitleFont(42);
   prefit_projy0_fail_stack->SetHistogram(prefit_projy0_fail_stack_stack_103);
   
   Double_t xAxis564[2] = {50, 200}; 
   
   TH1D *Background_fail_prefit_projy0_stack_1 = new TH1D("Background_fail_prefit_projy0_stack_1","Background, fail, prefit, 0.0-0.24",1, xAxis564);
   Background_fail_prefit_projy0_stack_1->SetBinContent(1,1.40854e+07);
   Background_fail_prefit_projy0_stack_1->SetMinimum(0);
   Background_fail_prefit_projy0_stack_1->SetEntries(1.40854e+07);

   ci = TColor::GetColor("#ffff00");
   Background_fail_prefit_projy0_stack_1->SetFillColor(ci);

   ci = 1422;
   color = new TColor(ci, 1, 1, 1, " ", 0);
   Background_fail_prefit_projy0_stack_1->SetLineColor(ci);
   Background_fail_prefit_projy0_stack_1->SetLineStyle(0);
   Background_fail_prefit_projy0_stack_1->GetXaxis()->SetTitle("p_{T}");
   Background_fail_prefit_projy0_stack_1->GetXaxis()->SetLabelFont(42);
   Background_fail_prefit_projy0_stack_1->GetXaxis()->SetLabelOffset(0.007);
   Background_fail_prefit_projy0_stack_1->GetXaxis()->SetLabelSize(0.05);
   Background_fail_prefit_projy0_stack_1->GetXaxis()->SetTitleSize(0.08);
   Background_fail_prefit_projy0_stack_1->GetXaxis()->SetTitleOffset(1.25);
   Background_fail_prefit_projy0_stack_1->GetXaxis()->SetTitleFont(42);
   Background_fail_prefit_projy0_stack_1->GetYaxis()->SetTitle("Events / bin");
   Background_fail_prefit_projy0_stack_1->GetYaxis()->SetLabelFont(42);
   Background_fail_prefit_projy0_stack_1->GetYaxis()->SetLabelOffset(0.007);
   Background_fail_prefit_projy0_stack_1->GetYaxis()->SetLabelSize(0.05);
   Background_fail_prefit_projy0_stack_1->GetYaxis()->SetTitleSize(0.08);
   Background_fail_prefit_projy0_stack_1->GetYaxis()->SetTitleOffset(1.25);
   Background_fail_prefit_projy0_stack_1->GetYaxis()->SetTitleFont(42);
   Background_fail_prefit_projy0_stack_1->GetZaxis()->SetLabelFont(42);
   Background_fail_prefit_projy0_stack_1->GetZaxis()->SetLabelOffset(0.007);
   Background_fail_prefit_projy0_stack_1->GetZaxis()->SetLabelSize(0.05);
   Background_fail_prefit_projy0_stack_1->GetZaxis()->SetTitleSize(0.08);
   Background_fail_prefit_projy0_stack_1->GetZaxis()->SetTitleFont(42);
   prefit_projy0_fail_stack->Add(Background_fail_prefit_projy0_stack_1,"");
   prefit_projy0_fail_stack->Draw("hist same");
   
   prefit_projy0_fail_stack = new THStack();
   prefit_projy0_fail_stack->SetName("prefit_projy0_fail_stack");
   prefit_projy0_fail_stack->SetTitle("prefit_projy0_fail_stack");
   Double_t xAxis565[2] = {50, 200}; 
   
   TH1F *prefit_projy0_fail_stack_stack_103_stack_104 = new TH1F("prefit_projy0_fail_stack_stack_103_stack_104","prefit_projy0_fail_stack",1, xAxis565);
   prefit_projy0_fail_stack_stack_103_stack_104->SetMinimum(0);
   prefit_projy0_fail_stack_stack_103_stack_104->SetMaximum(1.478967e+07);
   prefit_projy0_fail_stack_stack_103_stack_104->SetDirectory(0);
   prefit_projy0_fail_stack_stack_103_stack_104->SetStats(0);
   prefit_projy0_fail_stack_stack_103_stack_104->SetLineStyle(0);
   prefit_projy0_fail_stack_stack_103_stack_104->GetXaxis()->SetLabelFont(42);
   prefit_projy0_fail_stack_stack_103_stack_104->GetXaxis()->SetLabelOffset(0.007);
   prefit_projy0_fail_stack_stack_103_stack_104->GetXaxis()->SetLabelSize(0.05);
   prefit_projy0_fail_stack_stack_103_stack_104->GetXaxis()->SetTitleSize(0.08);
   prefit_projy0_fail_stack_stack_103_stack_104->GetXaxis()->SetTitleOffset(0.9);
   prefit_projy0_fail_stack_stack_103_stack_104->GetXaxis()->SetTitleFont(42);
   prefit_projy0_fail_stack_stack_103_stack_104->GetYaxis()->SetNdivisions(508);
   prefit_projy0_fail_stack_stack_103_stack_104->GetYaxis()->SetLabelFont(42);
   prefit_projy0_fail_stack_stack_103_stack_104->GetYaxis()->SetLabelOffset(0.007);
   prefit_projy0_fail_stack_stack_103_stack_104->GetYaxis()->SetLabelSize(0.05);
   prefit_projy0_fail_stack_stack_103_stack_104->GetYaxis()->SetTitleSize(0.08);
   prefit_projy0_fail_stack_stack_103_stack_104->GetYaxis()->SetTitleOffset(1.25);
   prefit_projy0_fail_stack_stack_103_stack_104->GetYaxis()->SetTitleFont(42);
   prefit_projy0_fail_stack_stack_103_stack_104->GetZaxis()->SetLabelFont(42);
   prefit_projy0_fail_stack_stack_103_stack_104->GetZaxis()->SetLabelOffset(0.007);
   prefit_projy0_fail_stack_stack_103_stack_104->GetZaxis()->SetLabelSize(0.05);
   prefit_projy0_fail_stack_stack_103_stack_104->GetZaxis()->SetTitleSize(0.08);
   prefit_projy0_fail_stack_stack_103_stack_104->GetZaxis()->SetTitleFont(42);
   prefit_projy0_fail_stack->SetHistogram(prefit_projy0_fail_stack_stack_103_stack_104);
   
   Double_t xAxis566[2] = {50, 200}; 
   
   TH1D *Background_fail_prefit_projy0_stack_1_stack_1 = new TH1D("Background_fail_prefit_projy0_stack_1_stack_1","Background, fail, prefit, 0.0-0.24",1, xAxis566);
   Background_fail_prefit_projy0_stack_1_stack_1->SetBinContent(1,1.40854e+07);
   Background_fail_prefit_projy0_stack_1_stack_1->SetMinimum(0);
   Background_fail_prefit_projy0_stack_1_stack_1->SetEntries(1.40854e+07);

   ci = TColor::GetColor("#ffff00");
   Background_fail_prefit_projy0_stack_1_stack_1->SetFillColor(ci);

   ci = 1422;
   color = new TColor(ci, 1, 1, 1, " ", 0);
   Background_fail_prefit_projy0_stack_1_stack_1->SetLineColor(ci);
   Background_fail_prefit_projy0_stack_1_stack_1->SetLineStyle(0);
   Background_fail_prefit_projy0_stack_1_stack_1->GetXaxis()->SetTitle("p_{T}");
   Background_fail_prefit_projy0_stack_1_stack_1->GetXaxis()->SetLabelFont(42);
   Background_fail_prefit_projy0_stack_1_stack_1->GetXaxis()->SetLabelOffset(0.007);
   Background_fail_prefit_projy0_stack_1_stack_1->GetXaxis()->SetLabelSize(0.05);
   Background_fail_prefit_projy0_stack_1_stack_1->GetXaxis()->SetTitleSize(0.08);
   Background_fail_prefit_projy0_stack_1_stack_1->GetXaxis()->SetTitleOffset(1.25);
   Background_fail_prefit_projy0_stack_1_stack_1->GetXaxis()->SetTitleFont(42);
   Background_fail_prefit_projy0_stack_1_stack_1->GetYaxis()->SetTitle("Events / bin");
   Background_fail_prefit_projy0_stack_1_stack_1->GetYaxis()->SetLabelFont(42);
   Background_fail_prefit_projy0_stack_1_stack_1->GetYaxis()->SetLabelOffset(0.007);
   Background_fail_prefit_projy0_stack_1_stack_1->GetYaxis()->SetLabelSize(0.05);
   Background_fail_prefit_projy0_stack_1_stack_1->GetYaxis()->SetTitleSize(0.08);
   Background_fail_prefit_projy0_stack_1_stack_1->GetYaxis()->SetTitleOffset(1.25);
   Background_fail_prefit_projy0_stack_1_stack_1->GetYaxis()->SetTitleFont(42);
   Background_fail_prefit_projy0_stack_1_stack_1->GetZaxis()->SetLabelFont(42);
   Background_fail_prefit_projy0_stack_1_stack_1->GetZaxis()->SetLabelOffset(0.007);
   Background_fail_prefit_projy0_stack_1_stack_1->GetZaxis()->SetLabelSize(0.05);
   Background_fail_prefit_projy0_stack_1_stack_1->GetZaxis()->SetTitleSize(0.08);
   Background_fail_prefit_projy0_stack_1_stack_1->GetZaxis()->SetTitleFont(42);
   prefit_projy0_fail_stack->Add(Background_fail_prefit_projy0_stack_1_stack_1,"");
   prefit_projy0_fail_stack->Draw("hist same");
   Double_t xAxis567[2] = {50, 200}; 
   
   TH1D *Signal_ppStaumI557_fail_prefit_projy0__359 = new TH1D("Signal_ppStaumI557_fail_prefit_projy0__359","HSCP signal, fail, prefit, 0.0-0.24",1, xAxis567);
   Signal_ppStaumI557_fail_prefit_projy0__359->SetBinContent(1,0.000411045);
   Signal_ppStaumI557_fail_prefit_projy0__359->SetBinError(1,3.743176e-05);
   Signal_ppStaumI557_fail_prefit_projy0__359->SetMinimum(0);
   Signal_ppStaumI557_fail_prefit_projy0__359->SetEntries(120.5864);
   Signal_ppStaumI557_fail_prefit_projy0__359->SetLineColor(2);
   Signal_ppStaumI557_fail_prefit_projy0__359->SetLineStyle(0);
   Signal_ppStaumI557_fail_prefit_projy0__359->GetXaxis()->SetTitle("p_{T}");
   Signal_ppStaumI557_fail_prefit_projy0__359->GetXaxis()->SetLabelFont(42);
   Signal_ppStaumI557_fail_prefit_projy0__359->GetXaxis()->SetLabelOffset(0.007);
   Signal_ppStaumI557_fail_prefit_projy0__359->GetXaxis()->SetLabelSize(0.05);
   Signal_ppStaumI557_fail_prefit_projy0__359->GetXaxis()->SetTitleSize(0.08);
   Signal_ppStaumI557_fail_prefit_projy0__359->GetXaxis()->SetTitleOffset(1.25);
   Signal_ppStaumI557_fail_prefit_projy0__359->GetXaxis()->SetTitleFont(42);
   Signal_ppStaumI557_fail_prefit_projy0__359->GetYaxis()->SetTitle("Events / bin");
   Signal_ppStaumI557_fail_prefit_projy0__359->GetYaxis()->SetLabelFont(42);
   Signal_ppStaumI557_fail_prefit_projy0__359->GetYaxis()->SetLabelOffset(0.007);
   Signal_ppStaumI557_fail_prefit_projy0__359->GetYaxis()->SetLabelSize(0.05);
   Signal_ppStaumI557_fail_prefit_projy0__359->GetYaxis()->SetTitleSize(0.08);
   Signal_ppStaumI557_fail_prefit_projy0__359->GetYaxis()->SetTitleOffset(1.25);
   Signal_ppStaumI557_fail_prefit_projy0__359->GetYaxis()->SetTitleFont(42);
   Signal_ppStaumI557_fail_prefit_projy0__359->GetZaxis()->SetLabelFont(42);
   Signal_ppStaumI557_fail_prefit_projy0__359->GetZaxis()->SetLabelOffset(0.007);
   Signal_ppStaumI557_fail_prefit_projy0__359->GetZaxis()->SetLabelSize(0.05);
   Signal_ppStaumI557_fail_prefit_projy0__359->GetZaxis()->SetTitleSize(0.08);
   Signal_ppStaumI557_fail_prefit_projy0__359->GetZaxis()->SetTitleFont(42);
   Signal_ppStaumI557_fail_prefit_projy0__359->Draw("hist same");
   Double_t xAxis568[2] = {50, 200}; 
   
   TH1D *TotalBkg_fail_prefit_projy0__360 = new TH1D("TotalBkg_fail_prefit_projy0__360","TotalBkg, fail, prefit, 0.0-0.24",1, xAxis568);
   TotalBkg_fail_prefit_projy0__360->SetBinContent(1,1.40854e+07);
   TotalBkg_fail_prefit_projy0__360->SetMinimum(0);
   TotalBkg_fail_prefit_projy0__360->SetEntries(1.40854e+07);
   TotalBkg_fail_prefit_projy0__360->SetLineStyle(0);
   TotalBkg_fail_prefit_projy0__360->SetMarkerStyle(0);
   TotalBkg_fail_prefit_projy0__360->GetXaxis()->SetTitle("p_{T}");
   TotalBkg_fail_prefit_projy0__360->GetXaxis()->SetLabelFont(42);
   TotalBkg_fail_prefit_projy0__360->GetXaxis()->SetLabelOffset(0.007);
   TotalBkg_fail_prefit_projy0__360->GetXaxis()->SetLabelSize(0.05);
   TotalBkg_fail_prefit_projy0__360->GetXaxis()->SetTitleSize(0.08);
   TotalBkg_fail_prefit_projy0__360->GetXaxis()->SetTitleOffset(1.25);
   TotalBkg_fail_prefit_projy0__360->GetXaxis()->SetTitleFont(42);
   TotalBkg_fail_prefit_projy0__360->GetYaxis()->SetTitle("Events / bin");
   TotalBkg_fail_prefit_projy0__360->GetYaxis()->SetLabelFont(42);
   TotalBkg_fail_prefit_projy0__360->GetYaxis()->SetLabelOffset(0.007);
   TotalBkg_fail_prefit_projy0__360->GetYaxis()->SetLabelSize(0.05);
   TotalBkg_fail_prefit_projy0__360->GetYaxis()->SetTitleSize(0.08);
   TotalBkg_fail_prefit_projy0__360->GetYaxis()->SetTitleOffset(1.25);
   TotalBkg_fail_prefit_projy0__360->GetYaxis()->SetTitleFont(42);
   TotalBkg_fail_prefit_projy0__360->GetZaxis()->SetLabelFont(42);
   TotalBkg_fail_prefit_projy0__360->GetZaxis()->SetLabelOffset(0.007);
   TotalBkg_fail_prefit_projy0__360->GetZaxis()->SetLabelSize(0.05);
   TotalBkg_fail_prefit_projy0__360->GetZaxis()->SetTitleSize(0.08);
   TotalBkg_fail_prefit_projy0__360->GetZaxis()->SetTitleFont(42);
   TotalBkg_fail_prefit_projy0__360->Draw("hist same");
   Double_t xAxis569[2] = {50, 200}; 
   
   TH1D *TotalBkg_fail_prefit_projy0__361 = new TH1D("TotalBkg_fail_prefit_projy0__361","TotalBkg, fail, prefit, 0.0-0.24",1, xAxis569);
   TotalBkg_fail_prefit_projy0__361->SetBinContent(1,1.40854e+07);
   TotalBkg_fail_prefit_projy0__361->SetMinimum(0);
   TotalBkg_fail_prefit_projy0__361->SetEntries(1.40854e+07);
   TotalBkg_fail_prefit_projy0__361->SetFillColor(1);
   TotalBkg_fail_prefit_projy0__361->SetFillStyle(3354);
   TotalBkg_fail_prefit_projy0__361->SetLineStyle(0);
   TotalBkg_fail_prefit_projy0__361->SetLineWidth(0);
   TotalBkg_fail_prefit_projy0__361->SetMarkerStyle(0);
   TotalBkg_fail_prefit_projy0__361->GetXaxis()->SetTitle("p_{T}");
   TotalBkg_fail_prefit_projy0__361->GetXaxis()->SetLabelFont(42);
   TotalBkg_fail_prefit_projy0__361->GetXaxis()->SetLabelOffset(0.007);
   TotalBkg_fail_prefit_projy0__361->GetXaxis()->SetLabelSize(0.05);
   TotalBkg_fail_prefit_projy0__361->GetXaxis()->SetTitleSize(0.08);
   TotalBkg_fail_prefit_projy0__361->GetXaxis()->SetTitleOffset(1.25);
   TotalBkg_fail_prefit_projy0__361->GetXaxis()->SetTitleFont(42);
   TotalBkg_fail_prefit_projy0__361->GetYaxis()->SetTitle("Events / bin");
   TotalBkg_fail_prefit_projy0__361->GetYaxis()->SetLabelFont(42);
   TotalBkg_fail_prefit_projy0__361->GetYaxis()->SetLabelOffset(0.007);
   TotalBkg_fail_prefit_projy0__361->GetYaxis()->SetLabelSize(0.05);
   TotalBkg_fail_prefit_projy0__361->GetYaxis()->SetTitleSize(0.08);
   TotalBkg_fail_prefit_projy0__361->GetYaxis()->SetTitleOffset(1.25);
   TotalBkg_fail_prefit_projy0__361->GetYaxis()->SetTitleFont(42);
   TotalBkg_fail_prefit_projy0__361->GetZaxis()->SetLabelFont(42);
   TotalBkg_fail_prefit_projy0__361->GetZaxis()->SetLabelOffset(0.007);
   TotalBkg_fail_prefit_projy0__361->GetZaxis()->SetLabelSize(0.05);
   TotalBkg_fail_prefit_projy0__361->GetZaxis()->SetTitleSize(0.08);
   TotalBkg_fail_prefit_projy0__361->GetZaxis()->SetTitleFont(42);
   TotalBkg_fail_prefit_projy0__361->Draw("e2 same");
   Double_t xAxis570[2] = {50, 200}; 
   
   TH1D *data_obs_fail_prefit_projy0__362 = new TH1D("data_obs_fail_prefit_projy0__362","",1, xAxis570);
   data_obs_fail_prefit_projy0__362->SetBinContent(1,1.40854e+07);
   data_obs_fail_prefit_projy0__362->SetBinError(1,3753.052);
   data_obs_fail_prefit_projy0__362->SetMinimum(0);
   data_obs_fail_prefit_projy0__362->SetMaximum(1.901528e+07);
   data_obs_fail_prefit_projy0__362->SetEntries(1.40854e+07);

   ci = TColor::GetColor("#000000");
   data_obs_fail_prefit_projy0__362->SetLineColor(ci);
   data_obs_fail_prefit_projy0__362->SetLineStyle(0);

   ci = TColor::GetColor("#000000");
   data_obs_fail_prefit_projy0__362->SetMarkerColor(ci);
   data_obs_fail_prefit_projy0__362->SetMarkerStyle(8);
   data_obs_fail_prefit_projy0__362->GetXaxis()->SetTitle("p_{T}");
   data_obs_fail_prefit_projy0__362->GetXaxis()->SetLabelFont(42);
   data_obs_fail_prefit_projy0__362->GetXaxis()->SetLabelOffset(0.05);
   data_obs_fail_prefit_projy0__362->GetXaxis()->SetLabelSize(0.07);
   data_obs_fail_prefit_projy0__362->GetXaxis()->SetTitleSize(0.09);
   data_obs_fail_prefit_projy0__362->GetXaxis()->SetTitleOffset(1.15);
   data_obs_fail_prefit_projy0__362->GetXaxis()->SetTitleFont(42);
   data_obs_fail_prefit_projy0__362->GetYaxis()->SetTitle("Events / bin");
   data_obs_fail_prefit_projy0__362->GetYaxis()->SetNdivisions(508);
   data_obs_fail_prefit_projy0__362->GetYaxis()->SetLabelFont(42);
   data_obs_fail_prefit_projy0__362->GetYaxis()->SetLabelOffset(0.007);
   data_obs_fail_prefit_projy0__362->GetYaxis()->SetLabelSize(0.07);
   data_obs_fail_prefit_projy0__362->GetYaxis()->SetTitleSize(0.09);
   data_obs_fail_prefit_projy0__362->GetYaxis()->SetTitleOffset(0.8);
   data_obs_fail_prefit_projy0__362->GetYaxis()->SetTitleFont(42);
   data_obs_fail_prefit_projy0__362->GetZaxis()->SetLabelFont(42);
   data_obs_fail_prefit_projy0__362->GetZaxis()->SetLabelOffset(0.007);
   data_obs_fail_prefit_projy0__362->GetZaxis()->SetLabelSize(0.05);
   data_obs_fail_prefit_projy0__362->GetZaxis()->SetTitleSize(0.08);
   data_obs_fail_prefit_projy0__362->GetZaxis()->SetTitleFont(42);
   data_obs_fail_prefit_projy0__362->Draw("pe X0 same");
   
   TLegend *leg = new TLegend(0.65,0.64,0.9,0.88,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(1001);
   TLegendEntry *entry=leg->AddEntry("data_obs_fail_prefit_projy0","Data","pe X0");

   ci = TColor::GetColor("#000000");
   entry->SetLineColor(ci);
   entry->SetLineWidth(1);

   ci = TColor::GetColor("#000000");
   entry->SetMarkerColor(ci);
   entry->SetMarkerStyle(8);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("TotalBkg_fail_prefit_projy0","Total bkg unc.","F");
   entry->SetFillColor(1);
   entry->SetFillStyle(3354);
   entry->SetLineColor(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("Signal_ppStau-557_fail_prefit_projy0","HSCP signal","L");
   entry->SetLineColor(2);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("Background_fail_prefit_projy0_stack_1_stack_1","Background","f");

   ci = TColor::GetColor("#ffff00");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = 1422;
   color = new TColor(ci, 1, 1, 1, " ", 0);
   entry->SetLineColor(ci);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   leg->Draw();
   Double_t xAxis571[2] = {50, 200}; 
   
   TH1D *data_obs_fail_prefit_projy0_copy__363 = new TH1D("data_obs_fail_prefit_projy0_copy__363","",1, xAxis571);
   data_obs_fail_prefit_projy0_copy__363->SetBinContent(1,1.40854e+07);
   data_obs_fail_prefit_projy0_copy__363->SetBinError(1,3753.052);
   data_obs_fail_prefit_projy0_copy__363->SetMinimum(0);
   data_obs_fail_prefit_projy0_copy__363->SetMaximum(1.901528e+07);
   data_obs_fail_prefit_projy0_copy__363->SetEntries(1.40854e+07);
   data_obs_fail_prefit_projy0_copy__363->SetDirectory(0);

   ci = TColor::GetColor("#000000");
   data_obs_fail_prefit_projy0_copy__363->SetLineColor(ci);
   data_obs_fail_prefit_projy0_copy__363->SetLineStyle(0);

   ci = TColor::GetColor("#000000");
   data_obs_fail_prefit_projy0_copy__363->SetMarkerColor(ci);
   data_obs_fail_prefit_projy0_copy__363->SetMarkerStyle(8);
   data_obs_fail_prefit_projy0_copy__363->GetXaxis()->SetTitle("p_{T}");
   data_obs_fail_prefit_projy0_copy__363->GetXaxis()->SetLabelFont(42);
   data_obs_fail_prefit_projy0_copy__363->GetXaxis()->SetLabelOffset(0.05);
   data_obs_fail_prefit_projy0_copy__363->GetXaxis()->SetLabelSize(0.07);
   data_obs_fail_prefit_projy0_copy__363->GetXaxis()->SetTitleSize(0.09);
   data_obs_fail_prefit_projy0_copy__363->GetXaxis()->SetTitleOffset(1.15);
   data_obs_fail_prefit_projy0_copy__363->GetXaxis()->SetTitleFont(42);
   data_obs_fail_prefit_projy0_copy__363->GetYaxis()->SetTitle("Events / bin");
   data_obs_fail_prefit_projy0_copy__363->GetYaxis()->SetNdivisions(508);
   data_obs_fail_prefit_projy0_copy__363->GetYaxis()->SetLabelFont(42);
   data_obs_fail_prefit_projy0_copy__363->GetYaxis()->SetLabelOffset(0.007);
   data_obs_fail_prefit_projy0_copy__363->GetYaxis()->SetLabelSize(0.07);
   data_obs_fail_prefit_projy0_copy__363->GetYaxis()->SetTitleSize(0.09);
   data_obs_fail_prefit_projy0_copy__363->GetYaxis()->SetTitleOffset(0.8);
   data_obs_fail_prefit_projy0_copy__363->GetYaxis()->SetTitleFont(42);
   data_obs_fail_prefit_projy0_copy__363->GetZaxis()->SetLabelFont(42);
   data_obs_fail_prefit_projy0_copy__363->GetZaxis()->SetLabelOffset(0.007);
   data_obs_fail_prefit_projy0_copy__363->GetZaxis()->SetLabelSize(0.05);
   data_obs_fail_prefit_projy0_copy__363->GetZaxis()->SetTitleSize(0.08);
   data_obs_fail_prefit_projy0_copy__363->GetZaxis()->SetTitleFont(42);
   data_obs_fail_prefit_projy0_copy__363->Draw("sameaxis");
   TLatex *   tex = new TLatex(0.21,0.83,"55 < p_{T} < 200 GeV, F^{Pixels}_{i} < 0.9");
tex->SetNDC();
   tex->SetTextAlign(12);
   tex->SetTextFont(42);
   tex->SetTextSize(0.06);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.17,0.92,"CMS");
tex->SetNDC();
   tex->SetTextFont(61);
   tex->SetTextSize(0.0675);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.25,0.92,"Preliminary");
tex->SetNDC();
   tex->SetTextFont(52);
   tex->SetTextSize(0.0485);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.95,0.92,"101 fb^{-1} (13 TeV)");
tex->SetNDC();
   tex->SetTextAlign(31);
   tex->SetTextFont(42);
   tex->SetTextSize(0.07);
   tex->SetLineWidth(2);
   tex->Draw();
   data_obs_fail_prefit_projy0_main->Modified();
   plots_fit_b/base_figs/prefit_projy0_fail->cd();
  
// ------------>Primitives in pad: data_obs_fail_prefit_projy0_sub
   TPad *data_obs_fail_prefit_projy0_sub = new TPad("data_obs_fail_prefit_projy0_sub", "data_obs_fail_prefit_projy0_sub",0,0,1,0.35);
   data_obs_fail_prefit_projy0_sub->Draw();
   data_obs_fail_prefit_projy0_sub->cd();
   data_obs_fail_prefit_projy0_sub->Range(17.30769,-6.023077,209.6154,2.9);
   data_obs_fail_prefit_projy0_sub->SetFillColor(0);
   data_obs_fail_prefit_projy0_sub->SetBorderMode(0);
   data_obs_fail_prefit_projy0_sub->SetBorderSize(2);
   data_obs_fail_prefit_projy0_sub->SetTickx(1);
   data_obs_fail_prefit_projy0_sub->SetTicky(1);
   data_obs_fail_prefit_projy0_sub->SetLeftMargin(0.17);
   data_obs_fail_prefit_projy0_sub->SetRightMargin(0.05);
   data_obs_fail_prefit_projy0_sub->SetTopMargin(0);
   data_obs_fail_prefit_projy0_sub->SetBottomMargin(0.35);
   data_obs_fail_prefit_projy0_sub->SetFrameFillStyle(0);
   data_obs_fail_prefit_projy0_sub->SetFrameBorderMode(0);
   data_obs_fail_prefit_projy0_sub->SetFrameFillStyle(0);
   data_obs_fail_prefit_projy0_sub->SetFrameBorderMode(0);
   Double_t xAxis572[2] = {50, 200}; 
   
   TH1D *data_obs_fail_prefit_projy0_pull__364 = new TH1D("data_obs_fail_prefit_projy0_pull__364","",1, xAxis572);
   data_obs_fail_prefit_projy0_pull__364->SetBinContent(1,-1.040542e-06);
   data_obs_fail_prefit_projy0_pull__364->SetBinError(1,3753.052);
   data_obs_fail_prefit_projy0_pull__364->SetMinimum(-2.9);
   data_obs_fail_prefit_projy0_pull__364->SetMaximum(2.9);
   data_obs_fail_prefit_projy0_pull__364->SetEntries(1.003906);
   data_obs_fail_prefit_projy0_pull__364->SetStats(0);

   ci = TColor::GetColor("#0000ff");
   data_obs_fail_prefit_projy0_pull__364->SetFillColor(ci);

   ci = TColor::GetColor("#000000");
   data_obs_fail_prefit_projy0_pull__364->SetLineColor(ci);
   data_obs_fail_prefit_projy0_pull__364->SetLineStyle(0);

   ci = TColor::GetColor("#000000");
   data_obs_fail_prefit_projy0_pull__364->SetMarkerColor(ci);
   data_obs_fail_prefit_projy0_pull__364->SetMarkerStyle(8);
   data_obs_fail_prefit_projy0_pull__364->GetXaxis()->SetTitle("p_{T}");
   data_obs_fail_prefit_projy0_pull__364->GetXaxis()->SetLabelFont(42);
   data_obs_fail_prefit_projy0_pull__364->GetXaxis()->SetLabelOffset(0.05);
   data_obs_fail_prefit_projy0_pull__364->GetXaxis()->SetLabelSize(0.13);
   data_obs_fail_prefit_projy0_pull__364->GetXaxis()->SetTitleSize(0.15);
   data_obs_fail_prefit_projy0_pull__364->GetXaxis()->SetTitleOffset(1.15);
   data_obs_fail_prefit_projy0_pull__364->GetXaxis()->SetTitleFont(42);
   data_obs_fail_prefit_projy0_pull__364->GetYaxis()->SetTitle("(Data-Bkg)/#sigma");
   data_obs_fail_prefit_projy0_pull__364->GetYaxis()->SetNdivisions(306);
   data_obs_fail_prefit_projy0_pull__364->GetYaxis()->SetLabelFont(42);
   data_obs_fail_prefit_projy0_pull__364->GetYaxis()->SetLabelOffset(0.007);
   data_obs_fail_prefit_projy0_pull__364->GetYaxis()->SetLabelSize(0.13);
   data_obs_fail_prefit_projy0_pull__364->GetYaxis()->SetTitleSize(0.12);
   data_obs_fail_prefit_projy0_pull__364->GetYaxis()->SetTitleOffset(0.4);
   data_obs_fail_prefit_projy0_pull__364->GetYaxis()->SetTitleFont(42);
   data_obs_fail_prefit_projy0_pull__364->GetZaxis()->SetLabelFont(42);
   data_obs_fail_prefit_projy0_pull__364->GetZaxis()->SetLabelOffset(0.007);
   data_obs_fail_prefit_projy0_pull__364->GetZaxis()->SetLabelSize(0.05);
   data_obs_fail_prefit_projy0_pull__364->GetZaxis()->SetTitleSize(0.08);
   data_obs_fail_prefit_projy0_pull__364->GetZaxis()->SetTitleFont(42);
   data_obs_fail_prefit_projy0_pull__364->Draw("hist");
   data_obs_fail_prefit_projy0_sub->Modified();
   plots_fit_b/base_figs/prefit_projy0_fail->cd();
   plots_fit_b/base_figs/prefit_projy0_fail->Modified();
   plots_fit_b/base_figs/prefit_projy0_fail->cd();
   plots_fit_b/base_figs/prefit_projy0_fail->SetSelected(plots_fit_b/base_figs/prefit_projy0_fail);
}
