void prefit_projx1_fail()
{
//=========Macro generated from canvas: plots_fit_b/base_figs/prefit_projx1_fail/plots_fit_b/base_figs/prefit_projx1_fail
//=========  (Fri Jan 12 21:00:27 2024) by ROOT version 6.14/09
   TCanvas *plots_fit_b/base_figs/prefit_projx1_fail = new TCanvas("plots_fit_b/base_figs/prefit_projx1_fail", "plots_fit_b/base_figs/prefit_projx1_fail",0,0,800,700);
   gStyle->SetOptFit(1);
   gStyle->SetOptStat(0);
   plots_fit_b/base_figs/prefit_projx1_fail->SetHighLightColor(2);
   plots_fit_b/base_figs/prefit_projx1_fail->Range(0,0,1,1);
   plots_fit_b/base_figs/prefit_projx1_fail->SetFillColor(0);
   plots_fit_b/base_figs/prefit_projx1_fail->SetBorderMode(0);
   plots_fit_b/base_figs/prefit_projx1_fail->SetBorderSize(2);
   plots_fit_b/base_figs/prefit_projx1_fail->SetTickx(1);
   plots_fit_b/base_figs/prefit_projx1_fail->SetTicky(1);
   plots_fit_b/base_figs/prefit_projx1_fail->SetLeftMargin(0.16);
   plots_fit_b/base_figs/prefit_projx1_fail->SetRightMargin(0);
   plots_fit_b/base_figs/prefit_projx1_fail->SetTopMargin(0);
   plots_fit_b/base_figs/prefit_projx1_fail->SetBottomMargin(0);
   plots_fit_b/base_figs/prefit_projx1_fail->SetFrameFillStyle(0);
   plots_fit_b/base_figs/prefit_projx1_fail->SetFrameBorderMode(0);
  
// ------------>Primitives in pad: data_obs_fail_prefit_projx1_main
   TPad *data_obs_fail_prefit_projx1_main = new TPad("data_obs_fail_prefit_projx1_main", "data_obs_fail_prefit_projx1_main",0,0.35,1,1);
   data_obs_fail_prefit_projx1_main->Draw();
   data_obs_fail_prefit_projx1_main->cd();
   data_obs_fail_prefit_projx1_main->Range(-0.2179487,-0.04651163,1.064103,1.116279);
   data_obs_fail_prefit_projx1_main->SetFillColor(0);
   data_obs_fail_prefit_projx1_main->SetBorderMode(0);
   data_obs_fail_prefit_projx1_main->SetBorderSize(2);
   data_obs_fail_prefit_projx1_main->SetTickx(1);
   data_obs_fail_prefit_projx1_main->SetTicky(1);
   data_obs_fail_prefit_projx1_main->SetLeftMargin(0.17);
   data_obs_fail_prefit_projx1_main->SetRightMargin(0.05);
   data_obs_fail_prefit_projx1_main->SetBottomMargin(0.04);
   data_obs_fail_prefit_projx1_main->SetFrameFillStyle(0);
   data_obs_fail_prefit_projx1_main->SetFrameBorderMode(0);
   data_obs_fail_prefit_projx1_main->SetFrameFillStyle(0);
   data_obs_fail_prefit_projx1_main->SetFrameBorderMode(0);
   Double_t xAxis540[10] = {0, 0.04, 0.08, 0.12, 0.16, 0.2, 0.24, 0.28, 0.32, 1}; 
   
   TH1D *data_obs_fail_prefit_projx1__344 = new TH1D("data_obs_fail_prefit_projx1__344","",9, xAxis540);
   data_obs_fail_prefit_projx1__344->SetMinimum(0);
   data_obs_fail_prefit_projx1__344->SetMaximum(0);

   Int_t ci;      // for color index setting
   TColor *color; // for color definition with alpha
   ci = TColor::GetColor("#000000");
   data_obs_fail_prefit_projx1__344->SetLineColor(ci);
   data_obs_fail_prefit_projx1__344->SetLineStyle(0);

   ci = TColor::GetColor("#000000");
   data_obs_fail_prefit_projx1__344->SetMarkerColor(ci);
   data_obs_fail_prefit_projx1__344->SetMarkerStyle(8);
   data_obs_fail_prefit_projx1__344->GetXaxis()->SetTitle("G_{i}^{Strips}");
   data_obs_fail_prefit_projx1__344->GetXaxis()->SetLabelFont(42);
   data_obs_fail_prefit_projx1__344->GetXaxis()->SetLabelOffset(0.05);
   data_obs_fail_prefit_projx1__344->GetXaxis()->SetLabelSize(0.07);
   data_obs_fail_prefit_projx1__344->GetXaxis()->SetTitleSize(0.09);
   data_obs_fail_prefit_projx1__344->GetXaxis()->SetTitleOffset(1.15);
   data_obs_fail_prefit_projx1__344->GetXaxis()->SetTitleFont(42);
   data_obs_fail_prefit_projx1__344->GetYaxis()->SetTitle("Events / bin");
   data_obs_fail_prefit_projx1__344->GetYaxis()->SetNdivisions(508);
   data_obs_fail_prefit_projx1__344->GetYaxis()->SetLabelFont(42);
   data_obs_fail_prefit_projx1__344->GetYaxis()->SetLabelOffset(0.007);
   data_obs_fail_prefit_projx1__344->GetYaxis()->SetLabelSize(0.07);
   data_obs_fail_prefit_projx1__344->GetYaxis()->SetTitleSize(0.09);
   data_obs_fail_prefit_projx1__344->GetYaxis()->SetTitleOffset(0.8);
   data_obs_fail_prefit_projx1__344->GetYaxis()->SetTitleFont(42);
   data_obs_fail_prefit_projx1__344->GetZaxis()->SetLabelFont(42);
   data_obs_fail_prefit_projx1__344->GetZaxis()->SetLabelOffset(0.007);
   data_obs_fail_prefit_projx1__344->GetZaxis()->SetLabelSize(0.05);
   data_obs_fail_prefit_projx1__344->GetZaxis()->SetTitleSize(0.08);
   data_obs_fail_prefit_projx1__344->GetZaxis()->SetTitleFont(42);
   data_obs_fail_prefit_projx1__344->Draw("pe X0");
   
   THStack *prefit_projx1_fail_stack = new THStack();
   prefit_projx1_fail_stack->SetName("prefit_projx1_fail_stack");
   prefit_projx1_fail_stack->SetTitle("prefit_projx1_fail_stack");
   Double_t xAxis541[10] = {0, 0.04, 0.08, 0.12, 0.16, 0.2, 0.24, 0.28, 0.32, 1}; 
   
   TH1F *prefit_projx1_fail_stack_stack_99 = new TH1F("prefit_projx1_fail_stack_stack_99","prefit_projx1_fail_stack",9, xAxis541);
   prefit_projx1_fail_stack_stack_99->SetMinimum(0);
   prefit_projx1_fail_stack_stack_99->SetMaximum(0);
   prefit_projx1_fail_stack_stack_99->SetDirectory(0);
   prefit_projx1_fail_stack_stack_99->SetStats(0);
   prefit_projx1_fail_stack_stack_99->SetLineStyle(0);
   prefit_projx1_fail_stack_stack_99->GetXaxis()->SetLabelFont(42);
   prefit_projx1_fail_stack_stack_99->GetXaxis()->SetLabelOffset(0.007);
   prefit_projx1_fail_stack_stack_99->GetXaxis()->SetLabelSize(0.05);
   prefit_projx1_fail_stack_stack_99->GetXaxis()->SetTitleSize(0.08);
   prefit_projx1_fail_stack_stack_99->GetXaxis()->SetTitleOffset(0.9);
   prefit_projx1_fail_stack_stack_99->GetXaxis()->SetTitleFont(42);
   prefit_projx1_fail_stack_stack_99->GetYaxis()->SetNdivisions(508);
   prefit_projx1_fail_stack_stack_99->GetYaxis()->SetLabelFont(42);
   prefit_projx1_fail_stack_stack_99->GetYaxis()->SetLabelOffset(0.007);
   prefit_projx1_fail_stack_stack_99->GetYaxis()->SetLabelSize(0.05);
   prefit_projx1_fail_stack_stack_99->GetYaxis()->SetTitleSize(0.08);
   prefit_projx1_fail_stack_stack_99->GetYaxis()->SetTitleOffset(1.25);
   prefit_projx1_fail_stack_stack_99->GetYaxis()->SetTitleFont(42);
   prefit_projx1_fail_stack_stack_99->GetZaxis()->SetLabelFont(42);
   prefit_projx1_fail_stack_stack_99->GetZaxis()->SetLabelOffset(0.007);
   prefit_projx1_fail_stack_stack_99->GetZaxis()->SetLabelSize(0.05);
   prefit_projx1_fail_stack_stack_99->GetZaxis()->SetTitleSize(0.08);
   prefit_projx1_fail_stack_stack_99->GetZaxis()->SetTitleFont(42);
   prefit_projx1_fail_stack->SetHistogram(prefit_projx1_fail_stack_stack_99);
   
   Double_t xAxis542[10] = {0, 0.04, 0.08, 0.12, 0.16, 0.2, 0.24, 0.28, 0.32, 1}; 
   
   TH1D *Background_fail_prefit_projx1_stack_1 = new TH1D("Background_fail_prefit_projx1_stack_1","Background, fail, prefit, 50-50",9, xAxis542);
   Background_fail_prefit_projx1_stack_1->SetMinimum(0);

   ci = TColor::GetColor("#ffff00");
   Background_fail_prefit_projx1_stack_1->SetFillColor(ci);

   ci = 1420;
   color = new TColor(ci, 1, 1, 1, " ", 0);
   Background_fail_prefit_projx1_stack_1->SetLineColor(ci);
   Background_fail_prefit_projx1_stack_1->SetLineStyle(0);
   Background_fail_prefit_projx1_stack_1->GetXaxis()->SetTitle("G_{i}^{Strips}");
   Background_fail_prefit_projx1_stack_1->GetXaxis()->SetLabelFont(42);
   Background_fail_prefit_projx1_stack_1->GetXaxis()->SetLabelOffset(0.007);
   Background_fail_prefit_projx1_stack_1->GetXaxis()->SetLabelSize(0.05);
   Background_fail_prefit_projx1_stack_1->GetXaxis()->SetTitleSize(0.08);
   Background_fail_prefit_projx1_stack_1->GetXaxis()->SetTitleOffset(0.9);
   Background_fail_prefit_projx1_stack_1->GetXaxis()->SetTitleFont(42);
   Background_fail_prefit_projx1_stack_1->GetYaxis()->SetTitle("Events / bin");
   Background_fail_prefit_projx1_stack_1->GetYaxis()->SetLabelFont(42);
   Background_fail_prefit_projx1_stack_1->GetYaxis()->SetLabelOffset(0.007);
   Background_fail_prefit_projx1_stack_1->GetYaxis()->SetLabelSize(0.05);
   Background_fail_prefit_projx1_stack_1->GetYaxis()->SetTitleSize(0.08);
   Background_fail_prefit_projx1_stack_1->GetYaxis()->SetTitleOffset(1.25);
   Background_fail_prefit_projx1_stack_1->GetYaxis()->SetTitleFont(42);
   Background_fail_prefit_projx1_stack_1->GetZaxis()->SetLabelFont(42);
   Background_fail_prefit_projx1_stack_1->GetZaxis()->SetLabelOffset(0.007);
   Background_fail_prefit_projx1_stack_1->GetZaxis()->SetLabelSize(0.05);
   Background_fail_prefit_projx1_stack_1->GetZaxis()->SetTitleSize(0.08);
   Background_fail_prefit_projx1_stack_1->GetZaxis()->SetTitleFont(42);
   prefit_projx1_fail_stack->Add(Background_fail_prefit_projx1_stack_1,"");
   prefit_projx1_fail_stack->Draw("hist same");
   
   prefit_projx1_fail_stack = new THStack();
   prefit_projx1_fail_stack->SetName("prefit_projx1_fail_stack");
   prefit_projx1_fail_stack->SetTitle("prefit_projx1_fail_stack");
   Double_t xAxis543[10] = {0, 0.04, 0.08, 0.12, 0.16, 0.2, 0.24, 0.28, 0.32, 1}; 
   
   TH1F *prefit_projx1_fail_stack_stack_99_stack_100 = new TH1F("prefit_projx1_fail_stack_stack_99_stack_100","prefit_projx1_fail_stack",9, xAxis543);
   prefit_projx1_fail_stack_stack_99_stack_100->SetMinimum(0);
   prefit_projx1_fail_stack_stack_99_stack_100->SetMaximum(0);
   prefit_projx1_fail_stack_stack_99_stack_100->SetDirectory(0);
   prefit_projx1_fail_stack_stack_99_stack_100->SetStats(0);
   prefit_projx1_fail_stack_stack_99_stack_100->SetLineStyle(0);
   prefit_projx1_fail_stack_stack_99_stack_100->GetXaxis()->SetLabelFont(42);
   prefit_projx1_fail_stack_stack_99_stack_100->GetXaxis()->SetLabelOffset(0.007);
   prefit_projx1_fail_stack_stack_99_stack_100->GetXaxis()->SetLabelSize(0.05);
   prefit_projx1_fail_stack_stack_99_stack_100->GetXaxis()->SetTitleSize(0.08);
   prefit_projx1_fail_stack_stack_99_stack_100->GetXaxis()->SetTitleOffset(0.9);
   prefit_projx1_fail_stack_stack_99_stack_100->GetXaxis()->SetTitleFont(42);
   prefit_projx1_fail_stack_stack_99_stack_100->GetYaxis()->SetNdivisions(508);
   prefit_projx1_fail_stack_stack_99_stack_100->GetYaxis()->SetLabelFont(42);
   prefit_projx1_fail_stack_stack_99_stack_100->GetYaxis()->SetLabelOffset(0.007);
   prefit_projx1_fail_stack_stack_99_stack_100->GetYaxis()->SetLabelSize(0.05);
   prefit_projx1_fail_stack_stack_99_stack_100->GetYaxis()->SetTitleSize(0.08);
   prefit_projx1_fail_stack_stack_99_stack_100->GetYaxis()->SetTitleOffset(1.25);
   prefit_projx1_fail_stack_stack_99_stack_100->GetYaxis()->SetTitleFont(42);
   prefit_projx1_fail_stack_stack_99_stack_100->GetZaxis()->SetLabelFont(42);
   prefit_projx1_fail_stack_stack_99_stack_100->GetZaxis()->SetLabelOffset(0.007);
   prefit_projx1_fail_stack_stack_99_stack_100->GetZaxis()->SetLabelSize(0.05);
   prefit_projx1_fail_stack_stack_99_stack_100->GetZaxis()->SetTitleSize(0.08);
   prefit_projx1_fail_stack_stack_99_stack_100->GetZaxis()->SetTitleFont(42);
   prefit_projx1_fail_stack->SetHistogram(prefit_projx1_fail_stack_stack_99_stack_100);
   
   Double_t xAxis544[10] = {0, 0.04, 0.08, 0.12, 0.16, 0.2, 0.24, 0.28, 0.32, 1}; 
   
   TH1D *Background_fail_prefit_projx1_stack_1_stack_1 = new TH1D("Background_fail_prefit_projx1_stack_1_stack_1","Background, fail, prefit, 50-50",9, xAxis544);
   Background_fail_prefit_projx1_stack_1_stack_1->SetMinimum(0);

   ci = TColor::GetColor("#ffff00");
   Background_fail_prefit_projx1_stack_1_stack_1->SetFillColor(ci);

   ci = 1420;
   color = new TColor(ci, 1, 1, 1, " ", 0);
   Background_fail_prefit_projx1_stack_1_stack_1->SetLineColor(ci);
   Background_fail_prefit_projx1_stack_1_stack_1->SetLineStyle(0);
   Background_fail_prefit_projx1_stack_1_stack_1->GetXaxis()->SetTitle("G_{i}^{Strips}");
   Background_fail_prefit_projx1_stack_1_stack_1->GetXaxis()->SetLabelFont(42);
   Background_fail_prefit_projx1_stack_1_stack_1->GetXaxis()->SetLabelOffset(0.007);
   Background_fail_prefit_projx1_stack_1_stack_1->GetXaxis()->SetLabelSize(0.05);
   Background_fail_prefit_projx1_stack_1_stack_1->GetXaxis()->SetTitleSize(0.08);
   Background_fail_prefit_projx1_stack_1_stack_1->GetXaxis()->SetTitleOffset(0.9);
   Background_fail_prefit_projx1_stack_1_stack_1->GetXaxis()->SetTitleFont(42);
   Background_fail_prefit_projx1_stack_1_stack_1->GetYaxis()->SetTitle("Events / bin");
   Background_fail_prefit_projx1_stack_1_stack_1->GetYaxis()->SetLabelFont(42);
   Background_fail_prefit_projx1_stack_1_stack_1->GetYaxis()->SetLabelOffset(0.007);
   Background_fail_prefit_projx1_stack_1_stack_1->GetYaxis()->SetLabelSize(0.05);
   Background_fail_prefit_projx1_stack_1_stack_1->GetYaxis()->SetTitleSize(0.08);
   Background_fail_prefit_projx1_stack_1_stack_1->GetYaxis()->SetTitleOffset(1.25);
   Background_fail_prefit_projx1_stack_1_stack_1->GetYaxis()->SetTitleFont(42);
   Background_fail_prefit_projx1_stack_1_stack_1->GetZaxis()->SetLabelFont(42);
   Background_fail_prefit_projx1_stack_1_stack_1->GetZaxis()->SetLabelOffset(0.007);
   Background_fail_prefit_projx1_stack_1_stack_1->GetZaxis()->SetLabelSize(0.05);
   Background_fail_prefit_projx1_stack_1_stack_1->GetZaxis()->SetTitleSize(0.08);
   Background_fail_prefit_projx1_stack_1_stack_1->GetZaxis()->SetTitleFont(42);
   prefit_projx1_fail_stack->Add(Background_fail_prefit_projx1_stack_1_stack_1,"");
   prefit_projx1_fail_stack->Draw("hist same");
   Double_t xAxis545[10] = {0, 0.04, 0.08, 0.12, 0.16, 0.2, 0.24, 0.28, 0.32, 1}; 
   
   TH1D *Signal_ppStaumI557_fail_prefit_projx1__345 = new TH1D("Signal_ppStaumI557_fail_prefit_projx1__345","HSCP signal, fail, prefit, 50-50",9, xAxis545);
   Signal_ppStaumI557_fail_prefit_projx1__345->SetMinimum(0);
   Signal_ppStaumI557_fail_prefit_projx1__345->SetLineColor(2);
   Signal_ppStaumI557_fail_prefit_projx1__345->SetLineStyle(0);
   Signal_ppStaumI557_fail_prefit_projx1__345->GetXaxis()->SetTitle("G_{i}^{Strips}");
   Signal_ppStaumI557_fail_prefit_projx1__345->GetXaxis()->SetLabelFont(42);
   Signal_ppStaumI557_fail_prefit_projx1__345->GetXaxis()->SetLabelOffset(0.007);
   Signal_ppStaumI557_fail_prefit_projx1__345->GetXaxis()->SetLabelSize(0.05);
   Signal_ppStaumI557_fail_prefit_projx1__345->GetXaxis()->SetTitleSize(0.08);
   Signal_ppStaumI557_fail_prefit_projx1__345->GetXaxis()->SetTitleOffset(0.9);
   Signal_ppStaumI557_fail_prefit_projx1__345->GetXaxis()->SetTitleFont(42);
   Signal_ppStaumI557_fail_prefit_projx1__345->GetYaxis()->SetTitle("Events / bin");
   Signal_ppStaumI557_fail_prefit_projx1__345->GetYaxis()->SetLabelFont(42);
   Signal_ppStaumI557_fail_prefit_projx1__345->GetYaxis()->SetLabelOffset(0.007);
   Signal_ppStaumI557_fail_prefit_projx1__345->GetYaxis()->SetLabelSize(0.05);
   Signal_ppStaumI557_fail_prefit_projx1__345->GetYaxis()->SetTitleSize(0.08);
   Signal_ppStaumI557_fail_prefit_projx1__345->GetYaxis()->SetTitleOffset(1.25);
   Signal_ppStaumI557_fail_prefit_projx1__345->GetYaxis()->SetTitleFont(42);
   Signal_ppStaumI557_fail_prefit_projx1__345->GetZaxis()->SetLabelFont(42);
   Signal_ppStaumI557_fail_prefit_projx1__345->GetZaxis()->SetLabelOffset(0.007);
   Signal_ppStaumI557_fail_prefit_projx1__345->GetZaxis()->SetLabelSize(0.05);
   Signal_ppStaumI557_fail_prefit_projx1__345->GetZaxis()->SetTitleSize(0.08);
   Signal_ppStaumI557_fail_prefit_projx1__345->GetZaxis()->SetTitleFont(42);
   Signal_ppStaumI557_fail_prefit_projx1__345->Draw("hist same");
   Double_t xAxis546[10] = {0, 0.04, 0.08, 0.12, 0.16, 0.2, 0.24, 0.28, 0.32, 1}; 
   
   TH1D *TotalBkg_fail_prefit_projx1__346 = new TH1D("TotalBkg_fail_prefit_projx1__346","TotalBkg, fail, prefit, 50-50",9, xAxis546);
   TotalBkg_fail_prefit_projx1__346->SetMinimum(0);
   TotalBkg_fail_prefit_projx1__346->SetLineStyle(0);
   TotalBkg_fail_prefit_projx1__346->SetMarkerStyle(0);
   TotalBkg_fail_prefit_projx1__346->GetXaxis()->SetTitle("G_{i}^{Strips}");
   TotalBkg_fail_prefit_projx1__346->GetXaxis()->SetLabelFont(42);
   TotalBkg_fail_prefit_projx1__346->GetXaxis()->SetLabelOffset(0.007);
   TotalBkg_fail_prefit_projx1__346->GetXaxis()->SetLabelSize(0.05);
   TotalBkg_fail_prefit_projx1__346->GetXaxis()->SetTitleSize(0.08);
   TotalBkg_fail_prefit_projx1__346->GetXaxis()->SetTitleOffset(0.9);
   TotalBkg_fail_prefit_projx1__346->GetXaxis()->SetTitleFont(42);
   TotalBkg_fail_prefit_projx1__346->GetYaxis()->SetTitle("Events / bin");
   TotalBkg_fail_prefit_projx1__346->GetYaxis()->SetLabelFont(42);
   TotalBkg_fail_prefit_projx1__346->GetYaxis()->SetLabelOffset(0.007);
   TotalBkg_fail_prefit_projx1__346->GetYaxis()->SetLabelSize(0.05);
   TotalBkg_fail_prefit_projx1__346->GetYaxis()->SetTitleSize(0.08);
   TotalBkg_fail_prefit_projx1__346->GetYaxis()->SetTitleOffset(1.25);
   TotalBkg_fail_prefit_projx1__346->GetYaxis()->SetTitleFont(42);
   TotalBkg_fail_prefit_projx1__346->GetZaxis()->SetLabelFont(42);
   TotalBkg_fail_prefit_projx1__346->GetZaxis()->SetLabelOffset(0.007);
   TotalBkg_fail_prefit_projx1__346->GetZaxis()->SetLabelSize(0.05);
   TotalBkg_fail_prefit_projx1__346->GetZaxis()->SetTitleSize(0.08);
   TotalBkg_fail_prefit_projx1__346->GetZaxis()->SetTitleFont(42);
   TotalBkg_fail_prefit_projx1__346->Draw("hist same");
   Double_t xAxis547[10] = {0, 0.04, 0.08, 0.12, 0.16, 0.2, 0.24, 0.28, 0.32, 1}; 
   
   TH1D *TotalBkg_fail_prefit_projx1__347 = new TH1D("TotalBkg_fail_prefit_projx1__347","TotalBkg, fail, prefit, 50-50",9, xAxis547);
   TotalBkg_fail_prefit_projx1__347->SetMinimum(0);
   TotalBkg_fail_prefit_projx1__347->SetFillColor(1);
   TotalBkg_fail_prefit_projx1__347->SetFillStyle(3354);
   TotalBkg_fail_prefit_projx1__347->SetLineStyle(0);
   TotalBkg_fail_prefit_projx1__347->SetLineWidth(0);
   TotalBkg_fail_prefit_projx1__347->SetMarkerStyle(0);
   TotalBkg_fail_prefit_projx1__347->GetXaxis()->SetTitle("G_{i}^{Strips}");
   TotalBkg_fail_prefit_projx1__347->GetXaxis()->SetLabelFont(42);
   TotalBkg_fail_prefit_projx1__347->GetXaxis()->SetLabelOffset(0.007);
   TotalBkg_fail_prefit_projx1__347->GetXaxis()->SetLabelSize(0.05);
   TotalBkg_fail_prefit_projx1__347->GetXaxis()->SetTitleSize(0.08);
   TotalBkg_fail_prefit_projx1__347->GetXaxis()->SetTitleOffset(0.9);
   TotalBkg_fail_prefit_projx1__347->GetXaxis()->SetTitleFont(42);
   TotalBkg_fail_prefit_projx1__347->GetYaxis()->SetTitle("Events / bin");
   TotalBkg_fail_prefit_projx1__347->GetYaxis()->SetLabelFont(42);
   TotalBkg_fail_prefit_projx1__347->GetYaxis()->SetLabelOffset(0.007);
   TotalBkg_fail_prefit_projx1__347->GetYaxis()->SetLabelSize(0.05);
   TotalBkg_fail_prefit_projx1__347->GetYaxis()->SetTitleSize(0.08);
   TotalBkg_fail_prefit_projx1__347->GetYaxis()->SetTitleOffset(1.25);
   TotalBkg_fail_prefit_projx1__347->GetYaxis()->SetTitleFont(42);
   TotalBkg_fail_prefit_projx1__347->GetZaxis()->SetLabelFont(42);
   TotalBkg_fail_prefit_projx1__347->GetZaxis()->SetLabelOffset(0.007);
   TotalBkg_fail_prefit_projx1__347->GetZaxis()->SetLabelSize(0.05);
   TotalBkg_fail_prefit_projx1__347->GetZaxis()->SetTitleSize(0.08);
   TotalBkg_fail_prefit_projx1__347->GetZaxis()->SetTitleFont(42);
   TotalBkg_fail_prefit_projx1__347->Draw("e2 same");
   Double_t xAxis548[10] = {0, 0.04, 0.08, 0.12, 0.16, 0.2, 0.24, 0.28, 0.32, 1}; 
   
   TH1D *data_obs_fail_prefit_projx1__348 = new TH1D("data_obs_fail_prefit_projx1__348","",9, xAxis548);
   data_obs_fail_prefit_projx1__348->SetMinimum(0);
   data_obs_fail_prefit_projx1__348->SetMaximum(0);

   ci = TColor::GetColor("#000000");
   data_obs_fail_prefit_projx1__348->SetLineColor(ci);
   data_obs_fail_prefit_projx1__348->SetLineStyle(0);

   ci = TColor::GetColor("#000000");
   data_obs_fail_prefit_projx1__348->SetMarkerColor(ci);
   data_obs_fail_prefit_projx1__348->SetMarkerStyle(8);
   data_obs_fail_prefit_projx1__348->GetXaxis()->SetTitle("G_{i}^{Strips}");
   data_obs_fail_prefit_projx1__348->GetXaxis()->SetLabelFont(42);
   data_obs_fail_prefit_projx1__348->GetXaxis()->SetLabelOffset(0.05);
   data_obs_fail_prefit_projx1__348->GetXaxis()->SetLabelSize(0.07);
   data_obs_fail_prefit_projx1__348->GetXaxis()->SetTitleSize(0.09);
   data_obs_fail_prefit_projx1__348->GetXaxis()->SetTitleOffset(1.15);
   data_obs_fail_prefit_projx1__348->GetXaxis()->SetTitleFont(42);
   data_obs_fail_prefit_projx1__348->GetYaxis()->SetTitle("Events / bin");
   data_obs_fail_prefit_projx1__348->GetYaxis()->SetNdivisions(508);
   data_obs_fail_prefit_projx1__348->GetYaxis()->SetLabelFont(42);
   data_obs_fail_prefit_projx1__348->GetYaxis()->SetLabelOffset(0.007);
   data_obs_fail_prefit_projx1__348->GetYaxis()->SetLabelSize(0.07);
   data_obs_fail_prefit_projx1__348->GetYaxis()->SetTitleSize(0.09);
   data_obs_fail_prefit_projx1__348->GetYaxis()->SetTitleOffset(0.8);
   data_obs_fail_prefit_projx1__348->GetYaxis()->SetTitleFont(42);
   data_obs_fail_prefit_projx1__348->GetZaxis()->SetLabelFont(42);
   data_obs_fail_prefit_projx1__348->GetZaxis()->SetLabelOffset(0.007);
   data_obs_fail_prefit_projx1__348->GetZaxis()->SetLabelSize(0.05);
   data_obs_fail_prefit_projx1__348->GetZaxis()->SetTitleSize(0.08);
   data_obs_fail_prefit_projx1__348->GetZaxis()->SetTitleFont(42);
   data_obs_fail_prefit_projx1__348->Draw("pe X0 same");
   
   TLegend *leg = new TLegend(0.65,0.64,0.9,0.88,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(1001);
   TLegendEntry *entry=leg->AddEntry("data_obs_fail_prefit_projx1","Data","pe X0");

   ci = TColor::GetColor("#000000");
   entry->SetLineColor(ci);
   entry->SetLineWidth(1);

   ci = TColor::GetColor("#000000");
   entry->SetMarkerColor(ci);
   entry->SetMarkerStyle(8);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("TotalBkg_fail_prefit_projx1","Total bkg unc.","F");
   entry->SetFillColor(1);
   entry->SetFillStyle(3354);
   entry->SetLineColor(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("Signal_ppStau-557_fail_prefit_projx1","HSCP signal","L");
   entry->SetLineColor(2);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("Background_fail_prefit_projx1_stack_1_stack_1","Background","f");

   ci = TColor::GetColor("#ffff00");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = 1420;
   color = new TColor(ci, 1, 1, 1, " ", 0);
   entry->SetLineColor(ci);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   leg->Draw();
   Double_t xAxis549[10] = {0, 0.04, 0.08, 0.12, 0.16, 0.2, 0.24, 0.28, 0.32, 1}; 
   
   TH1D *data_obs_fail_prefit_projx1_copy__349 = new TH1D("data_obs_fail_prefit_projx1_copy__349","",9, xAxis549);
   data_obs_fail_prefit_projx1_copy__349->SetMinimum(0);
   data_obs_fail_prefit_projx1_copy__349->SetMaximum(0);
   data_obs_fail_prefit_projx1_copy__349->SetDirectory(0);

   ci = TColor::GetColor("#000000");
   data_obs_fail_prefit_projx1_copy__349->SetLineColor(ci);
   data_obs_fail_prefit_projx1_copy__349->SetLineStyle(0);

   ci = TColor::GetColor("#000000");
   data_obs_fail_prefit_projx1_copy__349->SetMarkerColor(ci);
   data_obs_fail_prefit_projx1_copy__349->SetMarkerStyle(8);
   data_obs_fail_prefit_projx1_copy__349->GetXaxis()->SetTitle("G_{i}^{Strips}");
   data_obs_fail_prefit_projx1_copy__349->GetXaxis()->SetLabelFont(42);
   data_obs_fail_prefit_projx1_copy__349->GetXaxis()->SetLabelOffset(0.05);
   data_obs_fail_prefit_projx1_copy__349->GetXaxis()->SetLabelSize(0.07);
   data_obs_fail_prefit_projx1_copy__349->GetXaxis()->SetTitleSize(0.09);
   data_obs_fail_prefit_projx1_copy__349->GetXaxis()->SetTitleOffset(1.15);
   data_obs_fail_prefit_projx1_copy__349->GetXaxis()->SetTitleFont(42);
   data_obs_fail_prefit_projx1_copy__349->GetYaxis()->SetTitle("Events / bin");
   data_obs_fail_prefit_projx1_copy__349->GetYaxis()->SetNdivisions(508);
   data_obs_fail_prefit_projx1_copy__349->GetYaxis()->SetLabelFont(42);
   data_obs_fail_prefit_projx1_copy__349->GetYaxis()->SetLabelOffset(0.007);
   data_obs_fail_prefit_projx1_copy__349->GetYaxis()->SetLabelSize(0.07);
   data_obs_fail_prefit_projx1_copy__349->GetYaxis()->SetTitleSize(0.09);
   data_obs_fail_prefit_projx1_copy__349->GetYaxis()->SetTitleOffset(0.8);
   data_obs_fail_prefit_projx1_copy__349->GetYaxis()->SetTitleFont(42);
   data_obs_fail_prefit_projx1_copy__349->GetZaxis()->SetLabelFont(42);
   data_obs_fail_prefit_projx1_copy__349->GetZaxis()->SetLabelOffset(0.007);
   data_obs_fail_prefit_projx1_copy__349->GetZaxis()->SetLabelSize(0.05);
   data_obs_fail_prefit_projx1_copy__349->GetZaxis()->SetTitleSize(0.08);
   data_obs_fail_prefit_projx1_copy__349->GetZaxis()->SetTitleFont(42);
   data_obs_fail_prefit_projx1_copy__349->Draw("sameaxis");
   TLatex *   tex = new TLatex(0.21,0.83,"55 < p_{T} < 200 GeV, F^{Pixels}_{i} < 0.9");
tex->SetNDC();
   tex->SetTextAlign(12);
   tex->SetTextFont(42);
   tex->SetTextSize(0.06);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.17,0.92,"CMS");
tex->SetNDC();
   tex->SetTextFont(61);
   tex->SetTextSize(0.0675);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.25,0.92,"Preliminary");
tex->SetNDC();
   tex->SetTextFont(52);
   tex->SetTextSize(0.0485);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.95,0.92,"101 fb^{-1} (13 TeV)");
tex->SetNDC();
   tex->SetTextAlign(31);
   tex->SetTextFont(42);
   tex->SetTextSize(0.07);
   tex->SetLineWidth(2);
   tex->Draw();
   data_obs_fail_prefit_projx1_main->Modified();
   plots_fit_b/base_figs/prefit_projx1_fail->cd();
  
// ------------>Primitives in pad: data_obs_fail_prefit_projx1_sub
   TPad *data_obs_fail_prefit_projx1_sub = new TPad("data_obs_fail_prefit_projx1_sub", "data_obs_fail_prefit_projx1_sub",0,0,1,0.35);
   data_obs_fail_prefit_projx1_sub->Draw();
   data_obs_fail_prefit_projx1_sub->cd();
   data_obs_fail_prefit_projx1_sub->Range(-0.2179487,-6.023077,1.064103,2.9);
   data_obs_fail_prefit_projx1_sub->SetFillColor(0);
   data_obs_fail_prefit_projx1_sub->SetBorderMode(0);
   data_obs_fail_prefit_projx1_sub->SetBorderSize(2);
   data_obs_fail_prefit_projx1_sub->SetTickx(1);
   data_obs_fail_prefit_projx1_sub->SetTicky(1);
   data_obs_fail_prefit_projx1_sub->SetLeftMargin(0.17);
   data_obs_fail_prefit_projx1_sub->SetRightMargin(0.05);
   data_obs_fail_prefit_projx1_sub->SetTopMargin(0);
   data_obs_fail_prefit_projx1_sub->SetBottomMargin(0.35);
   data_obs_fail_prefit_projx1_sub->SetFrameFillStyle(0);
   data_obs_fail_prefit_projx1_sub->SetFrameBorderMode(0);
   data_obs_fail_prefit_projx1_sub->SetFrameFillStyle(0);
   data_obs_fail_prefit_projx1_sub->SetFrameBorderMode(0);
   Double_t xAxis550[10] = {0, 0.04, 0.08, 0.12, 0.16, 0.2, 0.24, 0.28, 0.32, 1}; 
   
   TH1D *data_obs_fail_prefit_projx1_pull__350 = new TH1D("data_obs_fail_prefit_projx1_pull__350","",9, xAxis550);
   data_obs_fail_prefit_projx1_pull__350->SetMinimum(-2.9);
   data_obs_fail_prefit_projx1_pull__350->SetMaximum(2.9);
   data_obs_fail_prefit_projx1_pull__350->SetEntries(18);
   data_obs_fail_prefit_projx1_pull__350->SetStats(0);

   ci = TColor::GetColor("#0000ff");
   data_obs_fail_prefit_projx1_pull__350->SetFillColor(ci);

   ci = TColor::GetColor("#000000");
   data_obs_fail_prefit_projx1_pull__350->SetLineColor(ci);
   data_obs_fail_prefit_projx1_pull__350->SetLineStyle(0);

   ci = TColor::GetColor("#000000");
   data_obs_fail_prefit_projx1_pull__350->SetMarkerColor(ci);
   data_obs_fail_prefit_projx1_pull__350->SetMarkerStyle(8);
   data_obs_fail_prefit_projx1_pull__350->GetXaxis()->SetTitle("G_{i}^{Strips}");
   data_obs_fail_prefit_projx1_pull__350->GetXaxis()->SetLabelFont(42);
   data_obs_fail_prefit_projx1_pull__350->GetXaxis()->SetLabelOffset(0.05);
   data_obs_fail_prefit_projx1_pull__350->GetXaxis()->SetLabelSize(0.13);
   data_obs_fail_prefit_projx1_pull__350->GetXaxis()->SetTitleSize(0.15);
   data_obs_fail_prefit_projx1_pull__350->GetXaxis()->SetTitleOffset(1.15);
   data_obs_fail_prefit_projx1_pull__350->GetXaxis()->SetTitleFont(42);
   data_obs_fail_prefit_projx1_pull__350->GetYaxis()->SetTitle("(Data-Bkg)/#sigma");
   data_obs_fail_prefit_projx1_pull__350->GetYaxis()->SetNdivisions(306);
   data_obs_fail_prefit_projx1_pull__350->GetYaxis()->SetLabelFont(42);
   data_obs_fail_prefit_projx1_pull__350->GetYaxis()->SetLabelOffset(0.007);
   data_obs_fail_prefit_projx1_pull__350->GetYaxis()->SetLabelSize(0.13);
   data_obs_fail_prefit_projx1_pull__350->GetYaxis()->SetTitleSize(0.12);
   data_obs_fail_prefit_projx1_pull__350->GetYaxis()->SetTitleOffset(0.4);
   data_obs_fail_prefit_projx1_pull__350->GetYaxis()->SetTitleFont(42);
   data_obs_fail_prefit_projx1_pull__350->GetZaxis()->SetLabelFont(42);
   data_obs_fail_prefit_projx1_pull__350->GetZaxis()->SetLabelOffset(0.007);
   data_obs_fail_prefit_projx1_pull__350->GetZaxis()->SetLabelSize(0.05);
   data_obs_fail_prefit_projx1_pull__350->GetZaxis()->SetTitleSize(0.08);
   data_obs_fail_prefit_projx1_pull__350->GetZaxis()->SetTitleFont(42);
   data_obs_fail_prefit_projx1_pull__350->Draw("hist");
   data_obs_fail_prefit_projx1_sub->Modified();
   plots_fit_b/base_figs/prefit_projx1_fail->cd();
   plots_fit_b/base_figs/prefit_projx1_fail->Modified();
   plots_fit_b/base_figs/prefit_projx1_fail->cd();
   plots_fit_b/base_figs/prefit_projx1_fail->SetSelected(plots_fit_b/base_figs/prefit_projx1_fail);
}
