void prefit_projy0_pass_logy()
{
//=========Macro generated from canvas: plots_fit_b/base_figs/prefit_projy0_pass_logy/plots_fit_b/base_figs/prefit_projy0_pass_logy
//=========  (Fri Jan 12 21:00:28 2024) by ROOT version 6.14/09
   TCanvas *plots_fit_b/base_figs/prefit_projy0_pass_logy = new TCanvas("plots_fit_b/base_figs/prefit_projy0_pass_logy", "plots_fit_b/base_figs/prefit_projy0_pass_logy",0,0,800,700);
   gStyle->SetOptFit(1);
   gStyle->SetOptStat(0);
   plots_fit_b/base_figs/prefit_projy0_pass_logy->SetHighLightColor(2);
   plots_fit_b/base_figs/prefit_projy0_pass_logy->Range(0,0,1,1);
   plots_fit_b/base_figs/prefit_projy0_pass_logy->SetFillColor(0);
   plots_fit_b/base_figs/prefit_projy0_pass_logy->SetBorderMode(0);
   plots_fit_b/base_figs/prefit_projy0_pass_logy->SetBorderSize(2);
   plots_fit_b/base_figs/prefit_projy0_pass_logy->SetTickx(1);
   plots_fit_b/base_figs/prefit_projy0_pass_logy->SetTicky(1);
   plots_fit_b/base_figs/prefit_projy0_pass_logy->SetLeftMargin(0.16);
   plots_fit_b/base_figs/prefit_projy0_pass_logy->SetRightMargin(0);
   plots_fit_b/base_figs/prefit_projy0_pass_logy->SetTopMargin(0);
   plots_fit_b/base_figs/prefit_projy0_pass_logy->SetBottomMargin(0);
   plots_fit_b/base_figs/prefit_projy0_pass_logy->SetFrameFillStyle(0);
   plots_fit_b/base_figs/prefit_projy0_pass_logy->SetFrameBorderMode(0);
  
// ------------>Primitives in pad: data_obs_pass_prefit_projy0_main
   TPad *data_obs_pass_prefit_projy0_main = new TPad("data_obs_pass_prefit_projy0_main", "data_obs_pass_prefit_projy0_main",0,0.35,1,1);
   data_obs_pass_prefit_projy0_main->Draw();
   data_obs_pass_prefit_projy0_main->cd();
   data_obs_pass_prefit_projy0_main->Range(17.30769,-3.526819,209.6154,9.643647);
   data_obs_pass_prefit_projy0_main->SetFillColor(0);
   data_obs_pass_prefit_projy0_main->SetBorderMode(0);
   data_obs_pass_prefit_projy0_main->SetBorderSize(2);
   data_obs_pass_prefit_projy0_main->SetLogy();
   data_obs_pass_prefit_projy0_main->SetTickx(1);
   data_obs_pass_prefit_projy0_main->SetTicky(1);
   data_obs_pass_prefit_projy0_main->SetLeftMargin(0.17);
   data_obs_pass_prefit_projy0_main->SetRightMargin(0.05);
   data_obs_pass_prefit_projy0_main->SetBottomMargin(0.04);
   data_obs_pass_prefit_projy0_main->SetFrameFillStyle(0);
   data_obs_pass_prefit_projy0_main->SetFrameBorderMode(0);
   data_obs_pass_prefit_projy0_main->SetFrameFillStyle(0);
   data_obs_pass_prefit_projy0_main->SetFrameBorderMode(0);
   Double_t xAxis760[2] = {50, 200}; 
   
   TH1D *data_obs_pass_prefit_projy0__484 = new TH1D("data_obs_pass_prefit_projy0__484","",1, xAxis760);
   data_obs_pass_prefit_projy0__484->SetBinContent(1,2327894);
   data_obs_pass_prefit_projy0__484->SetBinError(1,1525.744);
   data_obs_pass_prefit_projy0__484->SetMinimum(0.001);
   data_obs_pass_prefit_projy0__484->SetMaximum(2.121293e+08);
   data_obs_pass_prefit_projy0__484->SetEntries(2327894);

   Int_t ci;      // for color index setting
   TColor *color; // for color definition with alpha
   ci = TColor::GetColor("#000000");
   data_obs_pass_prefit_projy0__484->SetLineColor(ci);
   data_obs_pass_prefit_projy0__484->SetLineStyle(0);

   ci = TColor::GetColor("#000000");
   data_obs_pass_prefit_projy0__484->SetMarkerColor(ci);
   data_obs_pass_prefit_projy0__484->SetMarkerStyle(8);
   data_obs_pass_prefit_projy0__484->GetXaxis()->SetTitle("p_{T}");
   data_obs_pass_prefit_projy0__484->GetXaxis()->SetLabelFont(42);
   data_obs_pass_prefit_projy0__484->GetXaxis()->SetLabelOffset(0.05);
   data_obs_pass_prefit_projy0__484->GetXaxis()->SetLabelSize(0.07);
   data_obs_pass_prefit_projy0__484->GetXaxis()->SetTitleSize(0.09);
   data_obs_pass_prefit_projy0__484->GetXaxis()->SetTitleOffset(1.15);
   data_obs_pass_prefit_projy0__484->GetXaxis()->SetTitleFont(42);
   data_obs_pass_prefit_projy0__484->GetYaxis()->SetTitle("Events / bin");
   data_obs_pass_prefit_projy0__484->GetYaxis()->SetNdivisions(508);
   data_obs_pass_prefit_projy0__484->GetYaxis()->SetLabelFont(42);
   data_obs_pass_prefit_projy0__484->GetYaxis()->SetLabelOffset(0.007);
   data_obs_pass_prefit_projy0__484->GetYaxis()->SetLabelSize(0.07);
   data_obs_pass_prefit_projy0__484->GetYaxis()->SetTitleSize(0.09);
   data_obs_pass_prefit_projy0__484->GetYaxis()->SetTitleOffset(0.8);
   data_obs_pass_prefit_projy0__484->GetYaxis()->SetTitleFont(42);
   data_obs_pass_prefit_projy0__484->GetZaxis()->SetLabelFont(42);
   data_obs_pass_prefit_projy0__484->GetZaxis()->SetLabelOffset(0.007);
   data_obs_pass_prefit_projy0__484->GetZaxis()->SetLabelSize(0.05);
   data_obs_pass_prefit_projy0__484->GetZaxis()->SetTitleSize(0.08);
   data_obs_pass_prefit_projy0__484->GetZaxis()->SetTitleFont(42);
   data_obs_pass_prefit_projy0__484->Draw("pe X0");
   
   THStack *prefit_projy0_pass_logy_stack = new THStack();
   prefit_projy0_pass_logy_stack->SetName("prefit_projy0_pass_logy_stack");
   prefit_projy0_pass_logy_stack->SetTitle("prefit_projy0_pass_logy_stack");
   prefit_projy0_pass_logy_stack->SetMinimum(0.001);
   Double_t xAxis761[2] = {50, 200}; 
   
   TH1F *prefit_projy0_pass_logy_stack_stack_139 = new TH1F("prefit_projy0_pass_logy_stack_stack_139","prefit_projy0_pass_logy_stack",1, xAxis761);
   prefit_projy0_pass_logy_stack_stack_139->SetMinimum(0.0001919797);
   prefit_projy0_pass_logy_stack_stack_139->SetMaximum(702230.9);
   prefit_projy0_pass_logy_stack_stack_139->SetDirectory(0);
   prefit_projy0_pass_logy_stack_stack_139->SetStats(0);
   prefit_projy0_pass_logy_stack_stack_139->SetLineStyle(0);
   prefit_projy0_pass_logy_stack_stack_139->GetXaxis()->SetLabelFont(42);
   prefit_projy0_pass_logy_stack_stack_139->GetXaxis()->SetLabelOffset(0.007);
   prefit_projy0_pass_logy_stack_stack_139->GetXaxis()->SetLabelSize(0.05);
   prefit_projy0_pass_logy_stack_stack_139->GetXaxis()->SetTitleSize(0.08);
   prefit_projy0_pass_logy_stack_stack_139->GetXaxis()->SetTitleOffset(0.9);
   prefit_projy0_pass_logy_stack_stack_139->GetXaxis()->SetTitleFont(42);
   prefit_projy0_pass_logy_stack_stack_139->GetYaxis()->SetNdivisions(508);
   prefit_projy0_pass_logy_stack_stack_139->GetYaxis()->SetLabelFont(42);
   prefit_projy0_pass_logy_stack_stack_139->GetYaxis()->SetLabelOffset(0.007);
   prefit_projy0_pass_logy_stack_stack_139->GetYaxis()->SetLabelSize(0.05);
   prefit_projy0_pass_logy_stack_stack_139->GetYaxis()->SetTitleSize(0.08);
   prefit_projy0_pass_logy_stack_stack_139->GetYaxis()->SetTitleOffset(1.25);
   prefit_projy0_pass_logy_stack_stack_139->GetYaxis()->SetTitleFont(42);
   prefit_projy0_pass_logy_stack_stack_139->GetZaxis()->SetLabelFont(42);
   prefit_projy0_pass_logy_stack_stack_139->GetZaxis()->SetLabelOffset(0.007);
   prefit_projy0_pass_logy_stack_stack_139->GetZaxis()->SetLabelSize(0.05);
   prefit_projy0_pass_logy_stack_stack_139->GetZaxis()->SetTitleSize(0.08);
   prefit_projy0_pass_logy_stack_stack_139->GetZaxis()->SetTitleFont(42);
   prefit_projy0_pass_logy_stack->SetHistogram(prefit_projy0_pass_logy_stack_stack_139);
   
   Double_t xAxis762[2] = {50, 200}; 
   
   TH1D *Background_0x0_pass_prefit_projy0_stack_1 = new TH1D("Background_0x0_pass_prefit_projy0_stack_1","Background, pass, prefit, 0.0-0.24",1, xAxis762);
   Background_0x0_pass_prefit_projy0_stack_1->SetBinContent(1,140854);
   Background_0x0_pass_prefit_projy0_stack_1->SetBinError(1,120825.5);
   Background_0x0_pass_prefit_projy0_stack_1->SetMinimum(0.001);
   Background_0x0_pass_prefit_projy0_stack_1->SetEntries(1.359005);

   ci = TColor::GetColor("#ffff00");
   Background_0x0_pass_prefit_projy0_stack_1->SetFillColor(ci);

   ci = 1434;
   color = new TColor(ci, 1, 1, 1, " ", 0);
   Background_0x0_pass_prefit_projy0_stack_1->SetLineColor(ci);
   Background_0x0_pass_prefit_projy0_stack_1->SetLineStyle(0);
   Background_0x0_pass_prefit_projy0_stack_1->GetXaxis()->SetTitle("p_{T}");
   Background_0x0_pass_prefit_projy0_stack_1->GetXaxis()->SetLabelFont(42);
   Background_0x0_pass_prefit_projy0_stack_1->GetXaxis()->SetLabelOffset(0.007);
   Background_0x0_pass_prefit_projy0_stack_1->GetXaxis()->SetLabelSize(0.05);
   Background_0x0_pass_prefit_projy0_stack_1->GetXaxis()->SetTitleSize(0.08);
   Background_0x0_pass_prefit_projy0_stack_1->GetXaxis()->SetTitleOffset(1.25);
   Background_0x0_pass_prefit_projy0_stack_1->GetXaxis()->SetTitleFont(42);
   Background_0x0_pass_prefit_projy0_stack_1->GetYaxis()->SetTitle("Events / bin");
   Background_0x0_pass_prefit_projy0_stack_1->GetYaxis()->SetLabelFont(42);
   Background_0x0_pass_prefit_projy0_stack_1->GetYaxis()->SetLabelOffset(0.007);
   Background_0x0_pass_prefit_projy0_stack_1->GetYaxis()->SetLabelSize(0.05);
   Background_0x0_pass_prefit_projy0_stack_1->GetYaxis()->SetTitleSize(0.08);
   Background_0x0_pass_prefit_projy0_stack_1->GetYaxis()->SetTitleOffset(1.25);
   Background_0x0_pass_prefit_projy0_stack_1->GetYaxis()->SetTitleFont(42);
   Background_0x0_pass_prefit_projy0_stack_1->GetZaxis()->SetLabelFont(42);
   Background_0x0_pass_prefit_projy0_stack_1->GetZaxis()->SetLabelOffset(0.007);
   Background_0x0_pass_prefit_projy0_stack_1->GetZaxis()->SetLabelSize(0.05);
   Background_0x0_pass_prefit_projy0_stack_1->GetZaxis()->SetTitleSize(0.08);
   Background_0x0_pass_prefit_projy0_stack_1->GetZaxis()->SetTitleFont(42);
   prefit_projy0_pass_logy_stack->Add(Background_0x0_pass_prefit_projy0_stack_1,"");
   prefit_projy0_pass_logy_stack->Draw("hist same");
   
   prefit_projy0_pass_logy_stack = new THStack();
   prefit_projy0_pass_logy_stack->SetName("prefit_projy0_pass_logy_stack");
   prefit_projy0_pass_logy_stack->SetTitle("prefit_projy0_pass_logy_stack");
   prefit_projy0_pass_logy_stack->SetMinimum(0.001);
   Double_t xAxis763[2] = {50, 200}; 
   
   TH1F *prefit_projy0_pass_logy_stack_stack_139_stack_140 = new TH1F("prefit_projy0_pass_logy_stack_stack_139_stack_140","prefit_projy0_pass_logy_stack",1, xAxis763);
   prefit_projy0_pass_logy_stack_stack_139_stack_140->SetMinimum(0.0001919797);
   prefit_projy0_pass_logy_stack_stack_139_stack_140->SetMaximum(702230.9);
   prefit_projy0_pass_logy_stack_stack_139_stack_140->SetDirectory(0);
   prefit_projy0_pass_logy_stack_stack_139_stack_140->SetStats(0);
   prefit_projy0_pass_logy_stack_stack_139_stack_140->SetLineStyle(0);
   prefit_projy0_pass_logy_stack_stack_139_stack_140->GetXaxis()->SetLabelFont(42);
   prefit_projy0_pass_logy_stack_stack_139_stack_140->GetXaxis()->SetLabelOffset(0.007);
   prefit_projy0_pass_logy_stack_stack_139_stack_140->GetXaxis()->SetLabelSize(0.05);
   prefit_projy0_pass_logy_stack_stack_139_stack_140->GetXaxis()->SetTitleSize(0.08);
   prefit_projy0_pass_logy_stack_stack_139_stack_140->GetXaxis()->SetTitleOffset(0.9);
   prefit_projy0_pass_logy_stack_stack_139_stack_140->GetXaxis()->SetTitleFont(42);
   prefit_projy0_pass_logy_stack_stack_139_stack_140->GetYaxis()->SetNdivisions(508);
   prefit_projy0_pass_logy_stack_stack_139_stack_140->GetYaxis()->SetLabelFont(42);
   prefit_projy0_pass_logy_stack_stack_139_stack_140->GetYaxis()->SetLabelOffset(0.007);
   prefit_projy0_pass_logy_stack_stack_139_stack_140->GetYaxis()->SetLabelSize(0.05);
   prefit_projy0_pass_logy_stack_stack_139_stack_140->GetYaxis()->SetTitleSize(0.08);
   prefit_projy0_pass_logy_stack_stack_139_stack_140->GetYaxis()->SetTitleOffset(1.25);
   prefit_projy0_pass_logy_stack_stack_139_stack_140->GetYaxis()->SetTitleFont(42);
   prefit_projy0_pass_logy_stack_stack_139_stack_140->GetZaxis()->SetLabelFont(42);
   prefit_projy0_pass_logy_stack_stack_139_stack_140->GetZaxis()->SetLabelOffset(0.007);
   prefit_projy0_pass_logy_stack_stack_139_stack_140->GetZaxis()->SetLabelSize(0.05);
   prefit_projy0_pass_logy_stack_stack_139_stack_140->GetZaxis()->SetTitleSize(0.08);
   prefit_projy0_pass_logy_stack_stack_139_stack_140->GetZaxis()->SetTitleFont(42);
   prefit_projy0_pass_logy_stack->SetHistogram(prefit_projy0_pass_logy_stack_stack_139_stack_140);
   
   Double_t xAxis764[2] = {50, 200}; 
   
   TH1D *Background_0x0_pass_prefit_projy0_stack_1_stack_1 = new TH1D("Background_0x0_pass_prefit_projy0_stack_1_stack_1","Background, pass, prefit, 0.0-0.24",1, xAxis764);
   Background_0x0_pass_prefit_projy0_stack_1_stack_1->SetBinContent(1,140854);
   Background_0x0_pass_prefit_projy0_stack_1_stack_1->SetBinError(1,120825.5);
   Background_0x0_pass_prefit_projy0_stack_1_stack_1->SetMinimum(0.001);
   Background_0x0_pass_prefit_projy0_stack_1_stack_1->SetEntries(1.359005);

   ci = TColor::GetColor("#ffff00");
   Background_0x0_pass_prefit_projy0_stack_1_stack_1->SetFillColor(ci);

   ci = 1434;
   color = new TColor(ci, 1, 1, 1, " ", 0);
   Background_0x0_pass_prefit_projy0_stack_1_stack_1->SetLineColor(ci);
   Background_0x0_pass_prefit_projy0_stack_1_stack_1->SetLineStyle(0);
   Background_0x0_pass_prefit_projy0_stack_1_stack_1->GetXaxis()->SetTitle("p_{T}");
   Background_0x0_pass_prefit_projy0_stack_1_stack_1->GetXaxis()->SetLabelFont(42);
   Background_0x0_pass_prefit_projy0_stack_1_stack_1->GetXaxis()->SetLabelOffset(0.007);
   Background_0x0_pass_prefit_projy0_stack_1_stack_1->GetXaxis()->SetLabelSize(0.05);
   Background_0x0_pass_prefit_projy0_stack_1_stack_1->GetXaxis()->SetTitleSize(0.08);
   Background_0x0_pass_prefit_projy0_stack_1_stack_1->GetXaxis()->SetTitleOffset(1.25);
   Background_0x0_pass_prefit_projy0_stack_1_stack_1->GetXaxis()->SetTitleFont(42);
   Background_0x0_pass_prefit_projy0_stack_1_stack_1->GetYaxis()->SetTitle("Events / bin");
   Background_0x0_pass_prefit_projy0_stack_1_stack_1->GetYaxis()->SetLabelFont(42);
   Background_0x0_pass_prefit_projy0_stack_1_stack_1->GetYaxis()->SetLabelOffset(0.007);
   Background_0x0_pass_prefit_projy0_stack_1_stack_1->GetYaxis()->SetLabelSize(0.05);
   Background_0x0_pass_prefit_projy0_stack_1_stack_1->GetYaxis()->SetTitleSize(0.08);
   Background_0x0_pass_prefit_projy0_stack_1_stack_1->GetYaxis()->SetTitleOffset(1.25);
   Background_0x0_pass_prefit_projy0_stack_1_stack_1->GetYaxis()->SetTitleFont(42);
   Background_0x0_pass_prefit_projy0_stack_1_stack_1->GetZaxis()->SetLabelFont(42);
   Background_0x0_pass_prefit_projy0_stack_1_stack_1->GetZaxis()->SetLabelOffset(0.007);
   Background_0x0_pass_prefit_projy0_stack_1_stack_1->GetZaxis()->SetLabelSize(0.05);
   Background_0x0_pass_prefit_projy0_stack_1_stack_1->GetZaxis()->SetTitleSize(0.08);
   Background_0x0_pass_prefit_projy0_stack_1_stack_1->GetZaxis()->SetTitleFont(42);
   prefit_projy0_pass_logy_stack->Add(Background_0x0_pass_prefit_projy0_stack_1_stack_1,"");
   prefit_projy0_pass_logy_stack->Draw("hist same");
   Double_t xAxis765[2] = {50, 200}; 
   
   TH1D *Signal_ppStaumI557_pass_prefit_projy0__485 = new TH1D("Signal_ppStaumI557_pass_prefit_projy0__485","HSCP signal, pass, prefit, 0.0-0.24",1, xAxis765);
   Signal_ppStaumI557_pass_prefit_projy0__485->SetBinContent(1,1.44e-05);
   Signal_ppStaumI557_pass_prefit_projy0__485->SetBinError(1,9.331967e-08);
   Signal_ppStaumI557_pass_prefit_projy0__485->SetMinimum(0.001);
   Signal_ppStaumI557_pass_prefit_projy0__485->SetEntries(23811.05);
   Signal_ppStaumI557_pass_prefit_projy0__485->SetLineColor(2);
   Signal_ppStaumI557_pass_prefit_projy0__485->SetLineStyle(0);
   Signal_ppStaumI557_pass_prefit_projy0__485->GetXaxis()->SetTitle("p_{T}");
   Signal_ppStaumI557_pass_prefit_projy0__485->GetXaxis()->SetLabelFont(42);
   Signal_ppStaumI557_pass_prefit_projy0__485->GetXaxis()->SetLabelOffset(0.007);
   Signal_ppStaumI557_pass_prefit_projy0__485->GetXaxis()->SetLabelSize(0.05);
   Signal_ppStaumI557_pass_prefit_projy0__485->GetXaxis()->SetTitleSize(0.08);
   Signal_ppStaumI557_pass_prefit_projy0__485->GetXaxis()->SetTitleOffset(1.25);
   Signal_ppStaumI557_pass_prefit_projy0__485->GetXaxis()->SetTitleFont(42);
   Signal_ppStaumI557_pass_prefit_projy0__485->GetYaxis()->SetTitle("Events / bin");
   Signal_ppStaumI557_pass_prefit_projy0__485->GetYaxis()->SetLabelFont(42);
   Signal_ppStaumI557_pass_prefit_projy0__485->GetYaxis()->SetLabelOffset(0.007);
   Signal_ppStaumI557_pass_prefit_projy0__485->GetYaxis()->SetLabelSize(0.05);
   Signal_ppStaumI557_pass_prefit_projy0__485->GetYaxis()->SetTitleSize(0.08);
   Signal_ppStaumI557_pass_prefit_projy0__485->GetYaxis()->SetTitleOffset(1.25);
   Signal_ppStaumI557_pass_prefit_projy0__485->GetYaxis()->SetTitleFont(42);
   Signal_ppStaumI557_pass_prefit_projy0__485->GetZaxis()->SetLabelFont(42);
   Signal_ppStaumI557_pass_prefit_projy0__485->GetZaxis()->SetLabelOffset(0.007);
   Signal_ppStaumI557_pass_prefit_projy0__485->GetZaxis()->SetLabelSize(0.05);
   Signal_ppStaumI557_pass_prefit_projy0__485->GetZaxis()->SetTitleSize(0.08);
   Signal_ppStaumI557_pass_prefit_projy0__485->GetZaxis()->SetTitleFont(42);
   Signal_ppStaumI557_pass_prefit_projy0__485->Draw("hist same");
   Double_t xAxis766[2] = {50, 200}; 
   
   TH1D *TotalBkg_pass_prefit_projy0__486 = new TH1D("TotalBkg_pass_prefit_projy0__486","TotalBkg, pass, prefit, 0.0-0.24",1, xAxis766);
   TotalBkg_pass_prefit_projy0__486->SetBinContent(1,140854);
   TotalBkg_pass_prefit_projy0__486->SetBinError(1,120825.5);
   TotalBkg_pass_prefit_projy0__486->SetMinimum(0.001);
   TotalBkg_pass_prefit_projy0__486->SetEntries(1.359005);
   TotalBkg_pass_prefit_projy0__486->SetLineStyle(0);
   TotalBkg_pass_prefit_projy0__486->SetMarkerStyle(0);
   TotalBkg_pass_prefit_projy0__486->GetXaxis()->SetTitle("p_{T}");
   TotalBkg_pass_prefit_projy0__486->GetXaxis()->SetLabelFont(42);
   TotalBkg_pass_prefit_projy0__486->GetXaxis()->SetLabelOffset(0.007);
   TotalBkg_pass_prefit_projy0__486->GetXaxis()->SetLabelSize(0.05);
   TotalBkg_pass_prefit_projy0__486->GetXaxis()->SetTitleSize(0.08);
   TotalBkg_pass_prefit_projy0__486->GetXaxis()->SetTitleOffset(1.25);
   TotalBkg_pass_prefit_projy0__486->GetXaxis()->SetTitleFont(42);
   TotalBkg_pass_prefit_projy0__486->GetYaxis()->SetTitle("Events / bin");
   TotalBkg_pass_prefit_projy0__486->GetYaxis()->SetLabelFont(42);
   TotalBkg_pass_prefit_projy0__486->GetYaxis()->SetLabelOffset(0.007);
   TotalBkg_pass_prefit_projy0__486->GetYaxis()->SetLabelSize(0.05);
   TotalBkg_pass_prefit_projy0__486->GetYaxis()->SetTitleSize(0.08);
   TotalBkg_pass_prefit_projy0__486->GetYaxis()->SetTitleOffset(1.25);
   TotalBkg_pass_prefit_projy0__486->GetYaxis()->SetTitleFont(42);
   TotalBkg_pass_prefit_projy0__486->GetZaxis()->SetLabelFont(42);
   TotalBkg_pass_prefit_projy0__486->GetZaxis()->SetLabelOffset(0.007);
   TotalBkg_pass_prefit_projy0__486->GetZaxis()->SetLabelSize(0.05);
   TotalBkg_pass_prefit_projy0__486->GetZaxis()->SetTitleSize(0.08);
   TotalBkg_pass_prefit_projy0__486->GetZaxis()->SetTitleFont(42);
   TotalBkg_pass_prefit_projy0__486->Draw("hist same");
   Double_t xAxis767[2] = {50, 200}; 
   
   TH1D *TotalBkg_pass_prefit_projy0__487 = new TH1D("TotalBkg_pass_prefit_projy0__487","TotalBkg, pass, prefit, 0.0-0.24",1, xAxis767);
   TotalBkg_pass_prefit_projy0__487->SetBinContent(1,140854);
   TotalBkg_pass_prefit_projy0__487->SetBinError(1,120825.5);
   TotalBkg_pass_prefit_projy0__487->SetMinimum(0.001);
   TotalBkg_pass_prefit_projy0__487->SetEntries(1.359005);
   TotalBkg_pass_prefit_projy0__487->SetFillColor(1);
   TotalBkg_pass_prefit_projy0__487->SetFillStyle(3354);
   TotalBkg_pass_prefit_projy0__487->SetLineStyle(0);
   TotalBkg_pass_prefit_projy0__487->SetLineWidth(0);
   TotalBkg_pass_prefit_projy0__487->SetMarkerStyle(0);
   TotalBkg_pass_prefit_projy0__487->GetXaxis()->SetTitle("p_{T}");
   TotalBkg_pass_prefit_projy0__487->GetXaxis()->SetLabelFont(42);
   TotalBkg_pass_prefit_projy0__487->GetXaxis()->SetLabelOffset(0.007);
   TotalBkg_pass_prefit_projy0__487->GetXaxis()->SetLabelSize(0.05);
   TotalBkg_pass_prefit_projy0__487->GetXaxis()->SetTitleSize(0.08);
   TotalBkg_pass_prefit_projy0__487->GetXaxis()->SetTitleOffset(1.25);
   TotalBkg_pass_prefit_projy0__487->GetXaxis()->SetTitleFont(42);
   TotalBkg_pass_prefit_projy0__487->GetYaxis()->SetTitle("Events / bin");
   TotalBkg_pass_prefit_projy0__487->GetYaxis()->SetLabelFont(42);
   TotalBkg_pass_prefit_projy0__487->GetYaxis()->SetLabelOffset(0.007);
   TotalBkg_pass_prefit_projy0__487->GetYaxis()->SetLabelSize(0.05);
   TotalBkg_pass_prefit_projy0__487->GetYaxis()->SetTitleSize(0.08);
   TotalBkg_pass_prefit_projy0__487->GetYaxis()->SetTitleOffset(1.25);
   TotalBkg_pass_prefit_projy0__487->GetYaxis()->SetTitleFont(42);
   TotalBkg_pass_prefit_projy0__487->GetZaxis()->SetLabelFont(42);
   TotalBkg_pass_prefit_projy0__487->GetZaxis()->SetLabelOffset(0.007);
   TotalBkg_pass_prefit_projy0__487->GetZaxis()->SetLabelSize(0.05);
   TotalBkg_pass_prefit_projy0__487->GetZaxis()->SetTitleSize(0.08);
   TotalBkg_pass_prefit_projy0__487->GetZaxis()->SetTitleFont(42);
   TotalBkg_pass_prefit_projy0__487->Draw("e2 same");
   Double_t xAxis768[2] = {50, 200}; 
   
   TH1D *data_obs_pass_prefit_projy0__488 = new TH1D("data_obs_pass_prefit_projy0__488","",1, xAxis768);
   data_obs_pass_prefit_projy0__488->SetBinContent(1,2327894);
   data_obs_pass_prefit_projy0__488->SetBinError(1,1525.744);
   data_obs_pass_prefit_projy0__488->SetMinimum(0.001);
   data_obs_pass_prefit_projy0__488->SetMaximum(2.121293e+08);
   data_obs_pass_prefit_projy0__488->SetEntries(2327894);

   ci = TColor::GetColor("#000000");
   data_obs_pass_prefit_projy0__488->SetLineColor(ci);
   data_obs_pass_prefit_projy0__488->SetLineStyle(0);

   ci = TColor::GetColor("#000000");
   data_obs_pass_prefit_projy0__488->SetMarkerColor(ci);
   data_obs_pass_prefit_projy0__488->SetMarkerStyle(8);
   data_obs_pass_prefit_projy0__488->GetXaxis()->SetTitle("p_{T}");
   data_obs_pass_prefit_projy0__488->GetXaxis()->SetLabelFont(42);
   data_obs_pass_prefit_projy0__488->GetXaxis()->SetLabelOffset(0.05);
   data_obs_pass_prefit_projy0__488->GetXaxis()->SetLabelSize(0.07);
   data_obs_pass_prefit_projy0__488->GetXaxis()->SetTitleSize(0.09);
   data_obs_pass_prefit_projy0__488->GetXaxis()->SetTitleOffset(1.15);
   data_obs_pass_prefit_projy0__488->GetXaxis()->SetTitleFont(42);
   data_obs_pass_prefit_projy0__488->GetYaxis()->SetTitle("Events / bin");
   data_obs_pass_prefit_projy0__488->GetYaxis()->SetNdivisions(508);
   data_obs_pass_prefit_projy0__488->GetYaxis()->SetLabelFont(42);
   data_obs_pass_prefit_projy0__488->GetYaxis()->SetLabelOffset(0.007);
   data_obs_pass_prefit_projy0__488->GetYaxis()->SetLabelSize(0.07);
   data_obs_pass_prefit_projy0__488->GetYaxis()->SetTitleSize(0.09);
   data_obs_pass_prefit_projy0__488->GetYaxis()->SetTitleOffset(0.8);
   data_obs_pass_prefit_projy0__488->GetYaxis()->SetTitleFont(42);
   data_obs_pass_prefit_projy0__488->GetZaxis()->SetLabelFont(42);
   data_obs_pass_prefit_projy0__488->GetZaxis()->SetLabelOffset(0.007);
   data_obs_pass_prefit_projy0__488->GetZaxis()->SetLabelSize(0.05);
   data_obs_pass_prefit_projy0__488->GetZaxis()->SetTitleSize(0.08);
   data_obs_pass_prefit_projy0__488->GetZaxis()->SetTitleFont(42);
   data_obs_pass_prefit_projy0__488->Draw("pe X0 same");
   
   TLegend *leg = new TLegend(0.65,0.64,0.9,0.88,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(1001);
   TLegendEntry *entry=leg->AddEntry("data_obs_pass_prefit_projy0","Data","pe X0");

   ci = TColor::GetColor("#000000");
   entry->SetLineColor(ci);
   entry->SetLineWidth(1);

   ci = TColor::GetColor("#000000");
   entry->SetMarkerColor(ci);
   entry->SetMarkerStyle(8);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("TotalBkg_pass_prefit_projy0","Total bkg unc.","F");
   entry->SetFillColor(1);
   entry->SetFillStyle(3354);
   entry->SetLineColor(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("Signal_ppStau-557_pass_prefit_projy0","HSCP signal","L");
   entry->SetLineColor(2);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("Background_0x0_pass_prefit_projy0_stack_1_stack_1","Background","f");

   ci = TColor::GetColor("#ffff00");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = 1434;
   color = new TColor(ci, 1, 1, 1, " ", 0);
   entry->SetLineColor(ci);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   leg->Draw();
   Double_t xAxis769[2] = {50, 200}; 
   
   TH1D *data_obs_pass_prefit_projy0_copy__489 = new TH1D("data_obs_pass_prefit_projy0_copy__489","",1, xAxis769);
   data_obs_pass_prefit_projy0_copy__489->SetBinContent(1,2327894);
   data_obs_pass_prefit_projy0_copy__489->SetBinError(1,1525.744);
   data_obs_pass_prefit_projy0_copy__489->SetMinimum(0.001);
   data_obs_pass_prefit_projy0_copy__489->SetMaximum(2.121293e+08);
   data_obs_pass_prefit_projy0_copy__489->SetEntries(2327894);
   data_obs_pass_prefit_projy0_copy__489->SetDirectory(0);

   ci = TColor::GetColor("#000000");
   data_obs_pass_prefit_projy0_copy__489->SetLineColor(ci);
   data_obs_pass_prefit_projy0_copy__489->SetLineStyle(0);

   ci = TColor::GetColor("#000000");
   data_obs_pass_prefit_projy0_copy__489->SetMarkerColor(ci);
   data_obs_pass_prefit_projy0_copy__489->SetMarkerStyle(8);
   data_obs_pass_prefit_projy0_copy__489->GetXaxis()->SetTitle("p_{T}");
   data_obs_pass_prefit_projy0_copy__489->GetXaxis()->SetLabelFont(42);
   data_obs_pass_prefit_projy0_copy__489->GetXaxis()->SetLabelOffset(0.05);
   data_obs_pass_prefit_projy0_copy__489->GetXaxis()->SetLabelSize(0.07);
   data_obs_pass_prefit_projy0_copy__489->GetXaxis()->SetTitleSize(0.09);
   data_obs_pass_prefit_projy0_copy__489->GetXaxis()->SetTitleOffset(1.15);
   data_obs_pass_prefit_projy0_copy__489->GetXaxis()->SetTitleFont(42);
   data_obs_pass_prefit_projy0_copy__489->GetYaxis()->SetTitle("Events / bin");
   data_obs_pass_prefit_projy0_copy__489->GetYaxis()->SetNdivisions(508);
   data_obs_pass_prefit_projy0_copy__489->GetYaxis()->SetLabelFont(42);
   data_obs_pass_prefit_projy0_copy__489->GetYaxis()->SetLabelOffset(0.007);
   data_obs_pass_prefit_projy0_copy__489->GetYaxis()->SetLabelSize(0.07);
   data_obs_pass_prefit_projy0_copy__489->GetYaxis()->SetTitleSize(0.09);
   data_obs_pass_prefit_projy0_copy__489->GetYaxis()->SetTitleOffset(0.8);
   data_obs_pass_prefit_projy0_copy__489->GetYaxis()->SetTitleFont(42);
   data_obs_pass_prefit_projy0_copy__489->GetZaxis()->SetLabelFont(42);
   data_obs_pass_prefit_projy0_copy__489->GetZaxis()->SetLabelOffset(0.007);
   data_obs_pass_prefit_projy0_copy__489->GetZaxis()->SetLabelSize(0.05);
   data_obs_pass_prefit_projy0_copy__489->GetZaxis()->SetTitleSize(0.08);
   data_obs_pass_prefit_projy0_copy__489->GetZaxis()->SetTitleFont(42);
   data_obs_pass_prefit_projy0_copy__489->Draw("sameaxis");
   TLatex *   tex = new TLatex(0.21,0.83,"55 < p_{T} < 200 GeV, F^{Pixels}_{i} > 0.9");
tex->SetNDC();
   tex->SetTextAlign(12);
   tex->SetTextFont(42);
   tex->SetTextSize(0.06);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.17,0.92,"CMS");
tex->SetNDC();
   tex->SetTextFont(61);
   tex->SetTextSize(0.0675);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.25,0.92,"Preliminary");
tex->SetNDC();
   tex->SetTextFont(52);
   tex->SetTextSize(0.0485);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.95,0.92,"101 fb^{-1} (13 TeV)");
tex->SetNDC();
   tex->SetTextAlign(31);
   tex->SetTextFont(42);
   tex->SetTextSize(0.07);
   tex->SetLineWidth(2);
   tex->Draw();
   data_obs_pass_prefit_projy0_main->Modified();
   plots_fit_b/base_figs/prefit_projy0_pass_logy->cd();
  
// ------------>Primitives in pad: data_obs_pass_prefit_projy0_sub
   TPad *data_obs_pass_prefit_projy0_sub = new TPad("data_obs_pass_prefit_projy0_sub", "data_obs_pass_prefit_projy0_sub",0,0,1,0.35);
   data_obs_pass_prefit_projy0_sub->Draw();
   data_obs_pass_prefit_projy0_sub->cd();
   data_obs_pass_prefit_projy0_sub->Range(17.30769,-6.023077,209.6154,2.9);
   data_obs_pass_prefit_projy0_sub->SetFillColor(0);
   data_obs_pass_prefit_projy0_sub->SetBorderMode(0);
   data_obs_pass_prefit_projy0_sub->SetBorderSize(2);
   data_obs_pass_prefit_projy0_sub->SetTickx(1);
   data_obs_pass_prefit_projy0_sub->SetTicky(1);
   data_obs_pass_prefit_projy0_sub->SetLeftMargin(0.17);
   data_obs_pass_prefit_projy0_sub->SetRightMargin(0.05);
   data_obs_pass_prefit_projy0_sub->SetTopMargin(0);
   data_obs_pass_prefit_projy0_sub->SetBottomMargin(0.35);
   data_obs_pass_prefit_projy0_sub->SetFrameFillStyle(0);
   data_obs_pass_prefit_projy0_sub->SetFrameBorderMode(0);
   data_obs_pass_prefit_projy0_sub->SetFrameFillStyle(0);
   data_obs_pass_prefit_projy0_sub->SetFrameBorderMode(0);
   Double_t xAxis770[2] = {50, 200}; 
   
   TH1D *data_obs_pass_prefit_projy0_pull__490 = new TH1D("data_obs_pass_prefit_projy0_pull__490","",1, xAxis770);
   data_obs_pass_prefit_projy0_pull__490->SetBinContent(1,18.09937);
   data_obs_pass_prefit_projy0_pull__490->SetBinError(1,120835.1);
   data_obs_pass_prefit_projy0_pull__490->SetMinimum(-2.9);
   data_obs_pass_prefit_projy0_pull__490->SetMaximum(2.9);
   data_obs_pass_prefit_projy0_pull__490->SetEntries(328.5873);
   data_obs_pass_prefit_projy0_pull__490->SetStats(0);

   ci = TColor::GetColor("#0000ff");
   data_obs_pass_prefit_projy0_pull__490->SetFillColor(ci);

   ci = TColor::GetColor("#000000");
   data_obs_pass_prefit_projy0_pull__490->SetLineColor(ci);
   data_obs_pass_prefit_projy0_pull__490->SetLineStyle(0);

   ci = TColor::GetColor("#000000");
   data_obs_pass_prefit_projy0_pull__490->SetMarkerColor(ci);
   data_obs_pass_prefit_projy0_pull__490->SetMarkerStyle(8);
   data_obs_pass_prefit_projy0_pull__490->GetXaxis()->SetTitle("p_{T}");
   data_obs_pass_prefit_projy0_pull__490->GetXaxis()->SetLabelFont(42);
   data_obs_pass_prefit_projy0_pull__490->GetXaxis()->SetLabelOffset(0.05);
   data_obs_pass_prefit_projy0_pull__490->GetXaxis()->SetLabelSize(0.13);
   data_obs_pass_prefit_projy0_pull__490->GetXaxis()->SetTitleSize(0.15);
   data_obs_pass_prefit_projy0_pull__490->GetXaxis()->SetTitleOffset(1.15);
   data_obs_pass_prefit_projy0_pull__490->GetXaxis()->SetTitleFont(42);
   data_obs_pass_prefit_projy0_pull__490->GetYaxis()->SetTitle("(Data-Bkg)/#sigma");
   data_obs_pass_prefit_projy0_pull__490->GetYaxis()->SetNdivisions(306);
   data_obs_pass_prefit_projy0_pull__490->GetYaxis()->SetLabelFont(42);
   data_obs_pass_prefit_projy0_pull__490->GetYaxis()->SetLabelOffset(0.007);
   data_obs_pass_prefit_projy0_pull__490->GetYaxis()->SetLabelSize(0.13);
   data_obs_pass_prefit_projy0_pull__490->GetYaxis()->SetTitleSize(0.12);
   data_obs_pass_prefit_projy0_pull__490->GetYaxis()->SetTitleOffset(0.4);
   data_obs_pass_prefit_projy0_pull__490->GetYaxis()->SetTitleFont(42);
   data_obs_pass_prefit_projy0_pull__490->GetZaxis()->SetLabelFont(42);
   data_obs_pass_prefit_projy0_pull__490->GetZaxis()->SetLabelOffset(0.007);
   data_obs_pass_prefit_projy0_pull__490->GetZaxis()->SetLabelSize(0.05);
   data_obs_pass_prefit_projy0_pull__490->GetZaxis()->SetTitleSize(0.08);
   data_obs_pass_prefit_projy0_pull__490->GetZaxis()->SetTitleFont(42);
   data_obs_pass_prefit_projy0_pull__490->Draw("hist");
   data_obs_pass_prefit_projy0_sub->Modified();
   plots_fit_b/base_figs/prefit_projy0_pass_logy->cd();
   plots_fit_b/base_figs/prefit_projy0_pass_logy->Modified();
   plots_fit_b/base_figs/prefit_projy0_pass_logy->cd();
   plots_fit_b/base_figs/prefit_projy0_pass_logy->SetSelected(plots_fit_b/base_figs/prefit_projy0_pass_logy);
}
