void prefit_projy0_pass()
{
//=========Macro generated from canvas: plots_fit_b/base_figs/prefit_projy0_pass/plots_fit_b/base_figs/prefit_projy0_pass
//=========  (Fri Jan 12 21:00:28 2024) by ROOT version 6.14/09
   TCanvas *plots_fit_b/base_figs/prefit_projy0_pass = new TCanvas("plots_fit_b/base_figs/prefit_projy0_pass", "plots_fit_b/base_figs/prefit_projy0_pass",0,0,800,700);
   gStyle->SetOptFit(1);
   gStyle->SetOptStat(0);
   plots_fit_b/base_figs/prefit_projy0_pass->SetHighLightColor(2);
   plots_fit_b/base_figs/prefit_projy0_pass->Range(0,0,1,1);
   plots_fit_b/base_figs/prefit_projy0_pass->SetFillColor(0);
   plots_fit_b/base_figs/prefit_projy0_pass->SetBorderMode(0);
   plots_fit_b/base_figs/prefit_projy0_pass->SetBorderSize(2);
   plots_fit_b/base_figs/prefit_projy0_pass->SetTickx(1);
   plots_fit_b/base_figs/prefit_projy0_pass->SetTicky(1);
   plots_fit_b/base_figs/prefit_projy0_pass->SetLeftMargin(0.16);
   plots_fit_b/base_figs/prefit_projy0_pass->SetRightMargin(0);
   plots_fit_b/base_figs/prefit_projy0_pass->SetTopMargin(0);
   plots_fit_b/base_figs/prefit_projy0_pass->SetBottomMargin(0);
   plots_fit_b/base_figs/prefit_projy0_pass->SetFrameFillStyle(0);
   plots_fit_b/base_figs/prefit_projy0_pass->SetFrameBorderMode(0);
  
// ------------>Primitives in pad: data_obs_pass_prefit_projy0_main
   TPad *data_obs_pass_prefit_projy0_main = new TPad("data_obs_pass_prefit_projy0_main", "data_obs_pass_prefit_projy0_main",0,0.35,1,1);
   data_obs_pass_prefit_projy0_main->Draw();
   data_obs_pass_prefit_projy0_main->cd();
   data_obs_pass_prefit_projy0_main->Range(17.30769,-146170.1,209.6154,3508082);
   data_obs_pass_prefit_projy0_main->SetFillColor(0);
   data_obs_pass_prefit_projy0_main->SetBorderMode(0);
   data_obs_pass_prefit_projy0_main->SetBorderSize(2);
   data_obs_pass_prefit_projy0_main->SetTickx(1);
   data_obs_pass_prefit_projy0_main->SetTicky(1);
   data_obs_pass_prefit_projy0_main->SetLeftMargin(0.17);
   data_obs_pass_prefit_projy0_main->SetRightMargin(0.05);
   data_obs_pass_prefit_projy0_main->SetBottomMargin(0.04);
   data_obs_pass_prefit_projy0_main->SetFrameFillStyle(0);
   data_obs_pass_prefit_projy0_main->SetFrameBorderMode(0);
   data_obs_pass_prefit_projy0_main->SetFrameFillStyle(0);
   data_obs_pass_prefit_projy0_main->SetFrameBorderMode(0);
   Double_t xAxis694[2] = {50, 200}; 
   
   TH1D *data_obs_pass_prefit_projy0__442 = new TH1D("data_obs_pass_prefit_projy0__442","",1, xAxis694);
   data_obs_pass_prefit_projy0__442->SetBinContent(1,2327894);
   data_obs_pass_prefit_projy0__442->SetBinError(1,1525.744);
   data_obs_pass_prefit_projy0__442->SetMinimum(0);
   data_obs_pass_prefit_projy0__442->SetMaximum(3142657);
   data_obs_pass_prefit_projy0__442->SetEntries(2327894);

   Int_t ci;      // for color index setting
   TColor *color; // for color definition with alpha
   ci = TColor::GetColor("#000000");
   data_obs_pass_prefit_projy0__442->SetLineColor(ci);
   data_obs_pass_prefit_projy0__442->SetLineStyle(0);

   ci = TColor::GetColor("#000000");
   data_obs_pass_prefit_projy0__442->SetMarkerColor(ci);
   data_obs_pass_prefit_projy0__442->SetMarkerStyle(8);
   data_obs_pass_prefit_projy0__442->GetXaxis()->SetTitle("p_{T}");
   data_obs_pass_prefit_projy0__442->GetXaxis()->SetLabelFont(42);
   data_obs_pass_prefit_projy0__442->GetXaxis()->SetLabelOffset(0.05);
   data_obs_pass_prefit_projy0__442->GetXaxis()->SetLabelSize(0.07);
   data_obs_pass_prefit_projy0__442->GetXaxis()->SetTitleSize(0.09);
   data_obs_pass_prefit_projy0__442->GetXaxis()->SetTitleOffset(1.15);
   data_obs_pass_prefit_projy0__442->GetXaxis()->SetTitleFont(42);
   data_obs_pass_prefit_projy0__442->GetYaxis()->SetTitle("Events / bin");
   data_obs_pass_prefit_projy0__442->GetYaxis()->SetNdivisions(508);
   data_obs_pass_prefit_projy0__442->GetYaxis()->SetLabelFont(42);
   data_obs_pass_prefit_projy0__442->GetYaxis()->SetLabelOffset(0.007);
   data_obs_pass_prefit_projy0__442->GetYaxis()->SetLabelSize(0.07);
   data_obs_pass_prefit_projy0__442->GetYaxis()->SetTitleSize(0.09);
   data_obs_pass_prefit_projy0__442->GetYaxis()->SetTitleOffset(0.8);
   data_obs_pass_prefit_projy0__442->GetYaxis()->SetTitleFont(42);
   data_obs_pass_prefit_projy0__442->GetZaxis()->SetLabelFont(42);
   data_obs_pass_prefit_projy0__442->GetZaxis()->SetLabelOffset(0.007);
   data_obs_pass_prefit_projy0__442->GetZaxis()->SetLabelSize(0.05);
   data_obs_pass_prefit_projy0__442->GetZaxis()->SetTitleSize(0.08);
   data_obs_pass_prefit_projy0__442->GetZaxis()->SetTitleFont(42);
   data_obs_pass_prefit_projy0__442->Draw("pe X0");
   
   THStack *prefit_projy0_pass_stack = new THStack();
   prefit_projy0_pass_stack->SetName("prefit_projy0_pass_stack");
   prefit_projy0_pass_stack->SetTitle("prefit_projy0_pass_stack");
   Double_t xAxis695[2] = {50, 200}; 
   
   TH1F *prefit_projy0_pass_stack_stack_127 = new TH1F("prefit_projy0_pass_stack_stack_127","prefit_projy0_pass_stack",1, xAxis695);
   prefit_projy0_pass_stack_stack_127->SetMinimum(0);
   prefit_projy0_pass_stack_stack_127->SetMaximum(274763.4);
   prefit_projy0_pass_stack_stack_127->SetDirectory(0);
   prefit_projy0_pass_stack_stack_127->SetStats(0);
   prefit_projy0_pass_stack_stack_127->SetLineStyle(0);
   prefit_projy0_pass_stack_stack_127->GetXaxis()->SetLabelFont(42);
   prefit_projy0_pass_stack_stack_127->GetXaxis()->SetLabelOffset(0.007);
   prefit_projy0_pass_stack_stack_127->GetXaxis()->SetLabelSize(0.05);
   prefit_projy0_pass_stack_stack_127->GetXaxis()->SetTitleSize(0.08);
   prefit_projy0_pass_stack_stack_127->GetXaxis()->SetTitleOffset(0.9);
   prefit_projy0_pass_stack_stack_127->GetXaxis()->SetTitleFont(42);
   prefit_projy0_pass_stack_stack_127->GetYaxis()->SetNdivisions(508);
   prefit_projy0_pass_stack_stack_127->GetYaxis()->SetLabelFont(42);
   prefit_projy0_pass_stack_stack_127->GetYaxis()->SetLabelOffset(0.007);
   prefit_projy0_pass_stack_stack_127->GetYaxis()->SetLabelSize(0.05);
   prefit_projy0_pass_stack_stack_127->GetYaxis()->SetTitleSize(0.08);
   prefit_projy0_pass_stack_stack_127->GetYaxis()->SetTitleOffset(1.25);
   prefit_projy0_pass_stack_stack_127->GetYaxis()->SetTitleFont(42);
   prefit_projy0_pass_stack_stack_127->GetZaxis()->SetLabelFont(42);
   prefit_projy0_pass_stack_stack_127->GetZaxis()->SetLabelOffset(0.007);
   prefit_projy0_pass_stack_stack_127->GetZaxis()->SetLabelSize(0.05);
   prefit_projy0_pass_stack_stack_127->GetZaxis()->SetTitleSize(0.08);
   prefit_projy0_pass_stack_stack_127->GetZaxis()->SetTitleFont(42);
   prefit_projy0_pass_stack->SetHistogram(prefit_projy0_pass_stack_stack_127);
   
   Double_t xAxis696[2] = {50, 200}; 
   
   TH1D *Background_0x0_pass_prefit_projy0_stack_1 = new TH1D("Background_0x0_pass_prefit_projy0_stack_1","Background, pass, prefit, 0.0-0.24",1, xAxis696);
   Background_0x0_pass_prefit_projy0_stack_1->SetBinContent(1,140854);
   Background_0x0_pass_prefit_projy0_stack_1->SetBinError(1,120825.5);
   Background_0x0_pass_prefit_projy0_stack_1->SetMinimum(0);
   Background_0x0_pass_prefit_projy0_stack_1->SetEntries(1.359005);

   ci = TColor::GetColor("#ffff00");
   Background_0x0_pass_prefit_projy0_stack_1->SetFillColor(ci);

   ci = 1434;
   color = new TColor(ci, 1, 1, 1, " ", 0);
   Background_0x0_pass_prefit_projy0_stack_1->SetLineColor(ci);
   Background_0x0_pass_prefit_projy0_stack_1->SetLineStyle(0);
   Background_0x0_pass_prefit_projy0_stack_1->GetXaxis()->SetTitle("p_{T}");
   Background_0x0_pass_prefit_projy0_stack_1->GetXaxis()->SetLabelFont(42);
   Background_0x0_pass_prefit_projy0_stack_1->GetXaxis()->SetLabelOffset(0.007);
   Background_0x0_pass_prefit_projy0_stack_1->GetXaxis()->SetLabelSize(0.05);
   Background_0x0_pass_prefit_projy0_stack_1->GetXaxis()->SetTitleSize(0.08);
   Background_0x0_pass_prefit_projy0_stack_1->GetXaxis()->SetTitleOffset(1.25);
   Background_0x0_pass_prefit_projy0_stack_1->GetXaxis()->SetTitleFont(42);
   Background_0x0_pass_prefit_projy0_stack_1->GetYaxis()->SetTitle("Events / bin");
   Background_0x0_pass_prefit_projy0_stack_1->GetYaxis()->SetLabelFont(42);
   Background_0x0_pass_prefit_projy0_stack_1->GetYaxis()->SetLabelOffset(0.007);
   Background_0x0_pass_prefit_projy0_stack_1->GetYaxis()->SetLabelSize(0.05);
   Background_0x0_pass_prefit_projy0_stack_1->GetYaxis()->SetTitleSize(0.08);
   Background_0x0_pass_prefit_projy0_stack_1->GetYaxis()->SetTitleOffset(1.25);
   Background_0x0_pass_prefit_projy0_stack_1->GetYaxis()->SetTitleFont(42);
   Background_0x0_pass_prefit_projy0_stack_1->GetZaxis()->SetLabelFont(42);
   Background_0x0_pass_prefit_projy0_stack_1->GetZaxis()->SetLabelOffset(0.007);
   Background_0x0_pass_prefit_projy0_stack_1->GetZaxis()->SetLabelSize(0.05);
   Background_0x0_pass_prefit_projy0_stack_1->GetZaxis()->SetTitleSize(0.08);
   Background_0x0_pass_prefit_projy0_stack_1->GetZaxis()->SetTitleFont(42);
   prefit_projy0_pass_stack->Add(Background_0x0_pass_prefit_projy0_stack_1,"");
   prefit_projy0_pass_stack->Draw("hist same");
   
   prefit_projy0_pass_stack = new THStack();
   prefit_projy0_pass_stack->SetName("prefit_projy0_pass_stack");
   prefit_projy0_pass_stack->SetTitle("prefit_projy0_pass_stack");
   Double_t xAxis697[2] = {50, 200}; 
   
   TH1F *prefit_projy0_pass_stack_stack_127_stack_128 = new TH1F("prefit_projy0_pass_stack_stack_127_stack_128","prefit_projy0_pass_stack",1, xAxis697);
   prefit_projy0_pass_stack_stack_127_stack_128->SetMinimum(0);
   prefit_projy0_pass_stack_stack_127_stack_128->SetMaximum(274763.4);
   prefit_projy0_pass_stack_stack_127_stack_128->SetDirectory(0);
   prefit_projy0_pass_stack_stack_127_stack_128->SetStats(0);
   prefit_projy0_pass_stack_stack_127_stack_128->SetLineStyle(0);
   prefit_projy0_pass_stack_stack_127_stack_128->GetXaxis()->SetLabelFont(42);
   prefit_projy0_pass_stack_stack_127_stack_128->GetXaxis()->SetLabelOffset(0.007);
   prefit_projy0_pass_stack_stack_127_stack_128->GetXaxis()->SetLabelSize(0.05);
   prefit_projy0_pass_stack_stack_127_stack_128->GetXaxis()->SetTitleSize(0.08);
   prefit_projy0_pass_stack_stack_127_stack_128->GetXaxis()->SetTitleOffset(0.9);
   prefit_projy0_pass_stack_stack_127_stack_128->GetXaxis()->SetTitleFont(42);
   prefit_projy0_pass_stack_stack_127_stack_128->GetYaxis()->SetNdivisions(508);
   prefit_projy0_pass_stack_stack_127_stack_128->GetYaxis()->SetLabelFont(42);
   prefit_projy0_pass_stack_stack_127_stack_128->GetYaxis()->SetLabelOffset(0.007);
   prefit_projy0_pass_stack_stack_127_stack_128->GetYaxis()->SetLabelSize(0.05);
   prefit_projy0_pass_stack_stack_127_stack_128->GetYaxis()->SetTitleSize(0.08);
   prefit_projy0_pass_stack_stack_127_stack_128->GetYaxis()->SetTitleOffset(1.25);
   prefit_projy0_pass_stack_stack_127_stack_128->GetYaxis()->SetTitleFont(42);
   prefit_projy0_pass_stack_stack_127_stack_128->GetZaxis()->SetLabelFont(42);
   prefit_projy0_pass_stack_stack_127_stack_128->GetZaxis()->SetLabelOffset(0.007);
   prefit_projy0_pass_stack_stack_127_stack_128->GetZaxis()->SetLabelSize(0.05);
   prefit_projy0_pass_stack_stack_127_stack_128->GetZaxis()->SetTitleSize(0.08);
   prefit_projy0_pass_stack_stack_127_stack_128->GetZaxis()->SetTitleFont(42);
   prefit_projy0_pass_stack->SetHistogram(prefit_projy0_pass_stack_stack_127_stack_128);
   
   Double_t xAxis698[2] = {50, 200}; 
   
   TH1D *Background_0x0_pass_prefit_projy0_stack_1_stack_1 = new TH1D("Background_0x0_pass_prefit_projy0_stack_1_stack_1","Background, pass, prefit, 0.0-0.24",1, xAxis698);
   Background_0x0_pass_prefit_projy0_stack_1_stack_1->SetBinContent(1,140854);
   Background_0x0_pass_prefit_projy0_stack_1_stack_1->SetBinError(1,120825.5);
   Background_0x0_pass_prefit_projy0_stack_1_stack_1->SetMinimum(0);
   Background_0x0_pass_prefit_projy0_stack_1_stack_1->SetEntries(1.359005);

   ci = TColor::GetColor("#ffff00");
   Background_0x0_pass_prefit_projy0_stack_1_stack_1->SetFillColor(ci);

   ci = 1434;
   color = new TColor(ci, 1, 1, 1, " ", 0);
   Background_0x0_pass_prefit_projy0_stack_1_stack_1->SetLineColor(ci);
   Background_0x0_pass_prefit_projy0_stack_1_stack_1->SetLineStyle(0);
   Background_0x0_pass_prefit_projy0_stack_1_stack_1->GetXaxis()->SetTitle("p_{T}");
   Background_0x0_pass_prefit_projy0_stack_1_stack_1->GetXaxis()->SetLabelFont(42);
   Background_0x0_pass_prefit_projy0_stack_1_stack_1->GetXaxis()->SetLabelOffset(0.007);
   Background_0x0_pass_prefit_projy0_stack_1_stack_1->GetXaxis()->SetLabelSize(0.05);
   Background_0x0_pass_prefit_projy0_stack_1_stack_1->GetXaxis()->SetTitleSize(0.08);
   Background_0x0_pass_prefit_projy0_stack_1_stack_1->GetXaxis()->SetTitleOffset(1.25);
   Background_0x0_pass_prefit_projy0_stack_1_stack_1->GetXaxis()->SetTitleFont(42);
   Background_0x0_pass_prefit_projy0_stack_1_stack_1->GetYaxis()->SetTitle("Events / bin");
   Background_0x0_pass_prefit_projy0_stack_1_stack_1->GetYaxis()->SetLabelFont(42);
   Background_0x0_pass_prefit_projy0_stack_1_stack_1->GetYaxis()->SetLabelOffset(0.007);
   Background_0x0_pass_prefit_projy0_stack_1_stack_1->GetYaxis()->SetLabelSize(0.05);
   Background_0x0_pass_prefit_projy0_stack_1_stack_1->GetYaxis()->SetTitleSize(0.08);
   Background_0x0_pass_prefit_projy0_stack_1_stack_1->GetYaxis()->SetTitleOffset(1.25);
   Background_0x0_pass_prefit_projy0_stack_1_stack_1->GetYaxis()->SetTitleFont(42);
   Background_0x0_pass_prefit_projy0_stack_1_stack_1->GetZaxis()->SetLabelFont(42);
   Background_0x0_pass_prefit_projy0_stack_1_stack_1->GetZaxis()->SetLabelOffset(0.007);
   Background_0x0_pass_prefit_projy0_stack_1_stack_1->GetZaxis()->SetLabelSize(0.05);
   Background_0x0_pass_prefit_projy0_stack_1_stack_1->GetZaxis()->SetTitleSize(0.08);
   Background_0x0_pass_prefit_projy0_stack_1_stack_1->GetZaxis()->SetTitleFont(42);
   prefit_projy0_pass_stack->Add(Background_0x0_pass_prefit_projy0_stack_1_stack_1,"");
   prefit_projy0_pass_stack->Draw("hist same");
   Double_t xAxis699[2] = {50, 200}; 
   
   TH1D *Signal_ppStaumI557_pass_prefit_projy0__443 = new TH1D("Signal_ppStaumI557_pass_prefit_projy0__443","HSCP signal, pass, prefit, 0.0-0.24",1, xAxis699);
   Signal_ppStaumI557_pass_prefit_projy0__443->SetBinContent(1,1.44e-05);
   Signal_ppStaumI557_pass_prefit_projy0__443->SetBinError(1,9.331967e-08);
   Signal_ppStaumI557_pass_prefit_projy0__443->SetMinimum(0);
   Signal_ppStaumI557_pass_prefit_projy0__443->SetEntries(23811.05);
   Signal_ppStaumI557_pass_prefit_projy0__443->SetLineColor(2);
   Signal_ppStaumI557_pass_prefit_projy0__443->SetLineStyle(0);
   Signal_ppStaumI557_pass_prefit_projy0__443->GetXaxis()->SetTitle("p_{T}");
   Signal_ppStaumI557_pass_prefit_projy0__443->GetXaxis()->SetLabelFont(42);
   Signal_ppStaumI557_pass_prefit_projy0__443->GetXaxis()->SetLabelOffset(0.007);
   Signal_ppStaumI557_pass_prefit_projy0__443->GetXaxis()->SetLabelSize(0.05);
   Signal_ppStaumI557_pass_prefit_projy0__443->GetXaxis()->SetTitleSize(0.08);
   Signal_ppStaumI557_pass_prefit_projy0__443->GetXaxis()->SetTitleOffset(1.25);
   Signal_ppStaumI557_pass_prefit_projy0__443->GetXaxis()->SetTitleFont(42);
   Signal_ppStaumI557_pass_prefit_projy0__443->GetYaxis()->SetTitle("Events / bin");
   Signal_ppStaumI557_pass_prefit_projy0__443->GetYaxis()->SetLabelFont(42);
   Signal_ppStaumI557_pass_prefit_projy0__443->GetYaxis()->SetLabelOffset(0.007);
   Signal_ppStaumI557_pass_prefit_projy0__443->GetYaxis()->SetLabelSize(0.05);
   Signal_ppStaumI557_pass_prefit_projy0__443->GetYaxis()->SetTitleSize(0.08);
   Signal_ppStaumI557_pass_prefit_projy0__443->GetYaxis()->SetTitleOffset(1.25);
   Signal_ppStaumI557_pass_prefit_projy0__443->GetYaxis()->SetTitleFont(42);
   Signal_ppStaumI557_pass_prefit_projy0__443->GetZaxis()->SetLabelFont(42);
   Signal_ppStaumI557_pass_prefit_projy0__443->GetZaxis()->SetLabelOffset(0.007);
   Signal_ppStaumI557_pass_prefit_projy0__443->GetZaxis()->SetLabelSize(0.05);
   Signal_ppStaumI557_pass_prefit_projy0__443->GetZaxis()->SetTitleSize(0.08);
   Signal_ppStaumI557_pass_prefit_projy0__443->GetZaxis()->SetTitleFont(42);
   Signal_ppStaumI557_pass_prefit_projy0__443->Draw("hist same");
   Double_t xAxis700[2] = {50, 200}; 
   
   TH1D *TotalBkg_pass_prefit_projy0__444 = new TH1D("TotalBkg_pass_prefit_projy0__444","TotalBkg, pass, prefit, 0.0-0.24",1, xAxis700);
   TotalBkg_pass_prefit_projy0__444->SetBinContent(1,140854);
   TotalBkg_pass_prefit_projy0__444->SetBinError(1,120825.5);
   TotalBkg_pass_prefit_projy0__444->SetMinimum(0);
   TotalBkg_pass_prefit_projy0__444->SetEntries(1.359005);
   TotalBkg_pass_prefit_projy0__444->SetLineStyle(0);
   TotalBkg_pass_prefit_projy0__444->SetMarkerStyle(0);
   TotalBkg_pass_prefit_projy0__444->GetXaxis()->SetTitle("p_{T}");
   TotalBkg_pass_prefit_projy0__444->GetXaxis()->SetLabelFont(42);
   TotalBkg_pass_prefit_projy0__444->GetXaxis()->SetLabelOffset(0.007);
   TotalBkg_pass_prefit_projy0__444->GetXaxis()->SetLabelSize(0.05);
   TotalBkg_pass_prefit_projy0__444->GetXaxis()->SetTitleSize(0.08);
   TotalBkg_pass_prefit_projy0__444->GetXaxis()->SetTitleOffset(1.25);
   TotalBkg_pass_prefit_projy0__444->GetXaxis()->SetTitleFont(42);
   TotalBkg_pass_prefit_projy0__444->GetYaxis()->SetTitle("Events / bin");
   TotalBkg_pass_prefit_projy0__444->GetYaxis()->SetLabelFont(42);
   TotalBkg_pass_prefit_projy0__444->GetYaxis()->SetLabelOffset(0.007);
   TotalBkg_pass_prefit_projy0__444->GetYaxis()->SetLabelSize(0.05);
   TotalBkg_pass_prefit_projy0__444->GetYaxis()->SetTitleSize(0.08);
   TotalBkg_pass_prefit_projy0__444->GetYaxis()->SetTitleOffset(1.25);
   TotalBkg_pass_prefit_projy0__444->GetYaxis()->SetTitleFont(42);
   TotalBkg_pass_prefit_projy0__444->GetZaxis()->SetLabelFont(42);
   TotalBkg_pass_prefit_projy0__444->GetZaxis()->SetLabelOffset(0.007);
   TotalBkg_pass_prefit_projy0__444->GetZaxis()->SetLabelSize(0.05);
   TotalBkg_pass_prefit_projy0__444->GetZaxis()->SetTitleSize(0.08);
   TotalBkg_pass_prefit_projy0__444->GetZaxis()->SetTitleFont(42);
   TotalBkg_pass_prefit_projy0__444->Draw("hist same");
   Double_t xAxis701[2] = {50, 200}; 
   
   TH1D *TotalBkg_pass_prefit_projy0__445 = new TH1D("TotalBkg_pass_prefit_projy0__445","TotalBkg, pass, prefit, 0.0-0.24",1, xAxis701);
   TotalBkg_pass_prefit_projy0__445->SetBinContent(1,140854);
   TotalBkg_pass_prefit_projy0__445->SetBinError(1,120825.5);
   TotalBkg_pass_prefit_projy0__445->SetMinimum(0);
   TotalBkg_pass_prefit_projy0__445->SetEntries(1.359005);
   TotalBkg_pass_prefit_projy0__445->SetFillColor(1);
   TotalBkg_pass_prefit_projy0__445->SetFillStyle(3354);
   TotalBkg_pass_prefit_projy0__445->SetLineStyle(0);
   TotalBkg_pass_prefit_projy0__445->SetLineWidth(0);
   TotalBkg_pass_prefit_projy0__445->SetMarkerStyle(0);
   TotalBkg_pass_prefit_projy0__445->GetXaxis()->SetTitle("p_{T}");
   TotalBkg_pass_prefit_projy0__445->GetXaxis()->SetLabelFont(42);
   TotalBkg_pass_prefit_projy0__445->GetXaxis()->SetLabelOffset(0.007);
   TotalBkg_pass_prefit_projy0__445->GetXaxis()->SetLabelSize(0.05);
   TotalBkg_pass_prefit_projy0__445->GetXaxis()->SetTitleSize(0.08);
   TotalBkg_pass_prefit_projy0__445->GetXaxis()->SetTitleOffset(1.25);
   TotalBkg_pass_prefit_projy0__445->GetXaxis()->SetTitleFont(42);
   TotalBkg_pass_prefit_projy0__445->GetYaxis()->SetTitle("Events / bin");
   TotalBkg_pass_prefit_projy0__445->GetYaxis()->SetLabelFont(42);
   TotalBkg_pass_prefit_projy0__445->GetYaxis()->SetLabelOffset(0.007);
   TotalBkg_pass_prefit_projy0__445->GetYaxis()->SetLabelSize(0.05);
   TotalBkg_pass_prefit_projy0__445->GetYaxis()->SetTitleSize(0.08);
   TotalBkg_pass_prefit_projy0__445->GetYaxis()->SetTitleOffset(1.25);
   TotalBkg_pass_prefit_projy0__445->GetYaxis()->SetTitleFont(42);
   TotalBkg_pass_prefit_projy0__445->GetZaxis()->SetLabelFont(42);
   TotalBkg_pass_prefit_projy0__445->GetZaxis()->SetLabelOffset(0.007);
   TotalBkg_pass_prefit_projy0__445->GetZaxis()->SetLabelSize(0.05);
   TotalBkg_pass_prefit_projy0__445->GetZaxis()->SetTitleSize(0.08);
   TotalBkg_pass_prefit_projy0__445->GetZaxis()->SetTitleFont(42);
   TotalBkg_pass_prefit_projy0__445->Draw("e2 same");
   Double_t xAxis702[2] = {50, 200}; 
   
   TH1D *data_obs_pass_prefit_projy0__446 = new TH1D("data_obs_pass_prefit_projy0__446","",1, xAxis702);
   data_obs_pass_prefit_projy0__446->SetBinContent(1,2327894);
   data_obs_pass_prefit_projy0__446->SetBinError(1,1525.744);
   data_obs_pass_prefit_projy0__446->SetMinimum(0);
   data_obs_pass_prefit_projy0__446->SetMaximum(3142657);
   data_obs_pass_prefit_projy0__446->SetEntries(2327894);

   ci = TColor::GetColor("#000000");
   data_obs_pass_prefit_projy0__446->SetLineColor(ci);
   data_obs_pass_prefit_projy0__446->SetLineStyle(0);

   ci = TColor::GetColor("#000000");
   data_obs_pass_prefit_projy0__446->SetMarkerColor(ci);
   data_obs_pass_prefit_projy0__446->SetMarkerStyle(8);
   data_obs_pass_prefit_projy0__446->GetXaxis()->SetTitle("p_{T}");
   data_obs_pass_prefit_projy0__446->GetXaxis()->SetLabelFont(42);
   data_obs_pass_prefit_projy0__446->GetXaxis()->SetLabelOffset(0.05);
   data_obs_pass_prefit_projy0__446->GetXaxis()->SetLabelSize(0.07);
   data_obs_pass_prefit_projy0__446->GetXaxis()->SetTitleSize(0.09);
   data_obs_pass_prefit_projy0__446->GetXaxis()->SetTitleOffset(1.15);
   data_obs_pass_prefit_projy0__446->GetXaxis()->SetTitleFont(42);
   data_obs_pass_prefit_projy0__446->GetYaxis()->SetTitle("Events / bin");
   data_obs_pass_prefit_projy0__446->GetYaxis()->SetNdivisions(508);
   data_obs_pass_prefit_projy0__446->GetYaxis()->SetLabelFont(42);
   data_obs_pass_prefit_projy0__446->GetYaxis()->SetLabelOffset(0.007);
   data_obs_pass_prefit_projy0__446->GetYaxis()->SetLabelSize(0.07);
   data_obs_pass_prefit_projy0__446->GetYaxis()->SetTitleSize(0.09);
   data_obs_pass_prefit_projy0__446->GetYaxis()->SetTitleOffset(0.8);
   data_obs_pass_prefit_projy0__446->GetYaxis()->SetTitleFont(42);
   data_obs_pass_prefit_projy0__446->GetZaxis()->SetLabelFont(42);
   data_obs_pass_prefit_projy0__446->GetZaxis()->SetLabelOffset(0.007);
   data_obs_pass_prefit_projy0__446->GetZaxis()->SetLabelSize(0.05);
   data_obs_pass_prefit_projy0__446->GetZaxis()->SetTitleSize(0.08);
   data_obs_pass_prefit_projy0__446->GetZaxis()->SetTitleFont(42);
   data_obs_pass_prefit_projy0__446->Draw("pe X0 same");
   
   TLegend *leg = new TLegend(0.65,0.64,0.9,0.88,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(1001);
   TLegendEntry *entry=leg->AddEntry("data_obs_pass_prefit_projy0","Data","pe X0");

   ci = TColor::GetColor("#000000");
   entry->SetLineColor(ci);
   entry->SetLineWidth(1);

   ci = TColor::GetColor("#000000");
   entry->SetMarkerColor(ci);
   entry->SetMarkerStyle(8);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("TotalBkg_pass_prefit_projy0","Total bkg unc.","F");
   entry->SetFillColor(1);
   entry->SetFillStyle(3354);
   entry->SetLineColor(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("Signal_ppStau-557_pass_prefit_projy0","HSCP signal","L");
   entry->SetLineColor(2);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("Background_0x0_pass_prefit_projy0_stack_1_stack_1","Background","f");

   ci = TColor::GetColor("#ffff00");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = 1434;
   color = new TColor(ci, 1, 1, 1, " ", 0);
   entry->SetLineColor(ci);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   leg->Draw();
   Double_t xAxis703[2] = {50, 200}; 
   
   TH1D *data_obs_pass_prefit_projy0_copy__447 = new TH1D("data_obs_pass_prefit_projy0_copy__447","",1, xAxis703);
   data_obs_pass_prefit_projy0_copy__447->SetBinContent(1,2327894);
   data_obs_pass_prefit_projy0_copy__447->SetBinError(1,1525.744);
   data_obs_pass_prefit_projy0_copy__447->SetMinimum(0);
   data_obs_pass_prefit_projy0_copy__447->SetMaximum(3142657);
   data_obs_pass_prefit_projy0_copy__447->SetEntries(2327894);
   data_obs_pass_prefit_projy0_copy__447->SetDirectory(0);

   ci = TColor::GetColor("#000000");
   data_obs_pass_prefit_projy0_copy__447->SetLineColor(ci);
   data_obs_pass_prefit_projy0_copy__447->SetLineStyle(0);

   ci = TColor::GetColor("#000000");
   data_obs_pass_prefit_projy0_copy__447->SetMarkerColor(ci);
   data_obs_pass_prefit_projy0_copy__447->SetMarkerStyle(8);
   data_obs_pass_prefit_projy0_copy__447->GetXaxis()->SetTitle("p_{T}");
   data_obs_pass_prefit_projy0_copy__447->GetXaxis()->SetLabelFont(42);
   data_obs_pass_prefit_projy0_copy__447->GetXaxis()->SetLabelOffset(0.05);
   data_obs_pass_prefit_projy0_copy__447->GetXaxis()->SetLabelSize(0.07);
   data_obs_pass_prefit_projy0_copy__447->GetXaxis()->SetTitleSize(0.09);
   data_obs_pass_prefit_projy0_copy__447->GetXaxis()->SetTitleOffset(1.15);
   data_obs_pass_prefit_projy0_copy__447->GetXaxis()->SetTitleFont(42);
   data_obs_pass_prefit_projy0_copy__447->GetYaxis()->SetTitle("Events / bin");
   data_obs_pass_prefit_projy0_copy__447->GetYaxis()->SetNdivisions(508);
   data_obs_pass_prefit_projy0_copy__447->GetYaxis()->SetLabelFont(42);
   data_obs_pass_prefit_projy0_copy__447->GetYaxis()->SetLabelOffset(0.007);
   data_obs_pass_prefit_projy0_copy__447->GetYaxis()->SetLabelSize(0.07);
   data_obs_pass_prefit_projy0_copy__447->GetYaxis()->SetTitleSize(0.09);
   data_obs_pass_prefit_projy0_copy__447->GetYaxis()->SetTitleOffset(0.8);
   data_obs_pass_prefit_projy0_copy__447->GetYaxis()->SetTitleFont(42);
   data_obs_pass_prefit_projy0_copy__447->GetZaxis()->SetLabelFont(42);
   data_obs_pass_prefit_projy0_copy__447->GetZaxis()->SetLabelOffset(0.007);
   data_obs_pass_prefit_projy0_copy__447->GetZaxis()->SetLabelSize(0.05);
   data_obs_pass_prefit_projy0_copy__447->GetZaxis()->SetTitleSize(0.08);
   data_obs_pass_prefit_projy0_copy__447->GetZaxis()->SetTitleFont(42);
   data_obs_pass_prefit_projy0_copy__447->Draw("sameaxis");
   TLatex *   tex = new TLatex(0.21,0.83,"55 < p_{T} < 200 GeV, F^{Pixels}_{i} > 0.9");
tex->SetNDC();
   tex->SetTextAlign(12);
   tex->SetTextFont(42);
   tex->SetTextSize(0.06);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.17,0.92,"CMS");
tex->SetNDC();
   tex->SetTextFont(61);
   tex->SetTextSize(0.0675);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.25,0.92,"Preliminary");
tex->SetNDC();
   tex->SetTextFont(52);
   tex->SetTextSize(0.0485);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.95,0.92,"101 fb^{-1} (13 TeV)");
tex->SetNDC();
   tex->SetTextAlign(31);
   tex->SetTextFont(42);
   tex->SetTextSize(0.07);
   tex->SetLineWidth(2);
   tex->Draw();
   data_obs_pass_prefit_projy0_main->Modified();
   plots_fit_b/base_figs/prefit_projy0_pass->cd();
  
// ------------>Primitives in pad: data_obs_pass_prefit_projy0_sub
   TPad *data_obs_pass_prefit_projy0_sub = new TPad("data_obs_pass_prefit_projy0_sub", "data_obs_pass_prefit_projy0_sub",0,0,1,0.35);
   data_obs_pass_prefit_projy0_sub->Draw();
   data_obs_pass_prefit_projy0_sub->cd();
   data_obs_pass_prefit_projy0_sub->Range(17.30769,-6.023077,209.6154,2.9);
   data_obs_pass_prefit_projy0_sub->SetFillColor(0);
   data_obs_pass_prefit_projy0_sub->SetBorderMode(0);
   data_obs_pass_prefit_projy0_sub->SetBorderSize(2);
   data_obs_pass_prefit_projy0_sub->SetTickx(1);
   data_obs_pass_prefit_projy0_sub->SetTicky(1);
   data_obs_pass_prefit_projy0_sub->SetLeftMargin(0.17);
   data_obs_pass_prefit_projy0_sub->SetRightMargin(0.05);
   data_obs_pass_prefit_projy0_sub->SetTopMargin(0);
   data_obs_pass_prefit_projy0_sub->SetBottomMargin(0.35);
   data_obs_pass_prefit_projy0_sub->SetFrameFillStyle(0);
   data_obs_pass_prefit_projy0_sub->SetFrameBorderMode(0);
   data_obs_pass_prefit_projy0_sub->SetFrameFillStyle(0);
   data_obs_pass_prefit_projy0_sub->SetFrameBorderMode(0);
   Double_t xAxis704[2] = {50, 200}; 
   
   TH1D *data_obs_pass_prefit_projy0_pull__448 = new TH1D("data_obs_pass_prefit_projy0_pull__448","",1, xAxis704);
   data_obs_pass_prefit_projy0_pull__448->SetBinContent(1,18.09937);
   data_obs_pass_prefit_projy0_pull__448->SetBinError(1,120835.1);
   data_obs_pass_prefit_projy0_pull__448->SetMinimum(-2.9);
   data_obs_pass_prefit_projy0_pull__448->SetMaximum(2.9);
   data_obs_pass_prefit_projy0_pull__448->SetEntries(328.5873);
   data_obs_pass_prefit_projy0_pull__448->SetStats(0);

   ci = TColor::GetColor("#0000ff");
   data_obs_pass_prefit_projy0_pull__448->SetFillColor(ci);

   ci = TColor::GetColor("#000000");
   data_obs_pass_prefit_projy0_pull__448->SetLineColor(ci);
   data_obs_pass_prefit_projy0_pull__448->SetLineStyle(0);

   ci = TColor::GetColor("#000000");
   data_obs_pass_prefit_projy0_pull__448->SetMarkerColor(ci);
   data_obs_pass_prefit_projy0_pull__448->SetMarkerStyle(8);
   data_obs_pass_prefit_projy0_pull__448->GetXaxis()->SetTitle("p_{T}");
   data_obs_pass_prefit_projy0_pull__448->GetXaxis()->SetLabelFont(42);
   data_obs_pass_prefit_projy0_pull__448->GetXaxis()->SetLabelOffset(0.05);
   data_obs_pass_prefit_projy0_pull__448->GetXaxis()->SetLabelSize(0.13);
   data_obs_pass_prefit_projy0_pull__448->GetXaxis()->SetTitleSize(0.15);
   data_obs_pass_prefit_projy0_pull__448->GetXaxis()->SetTitleOffset(1.15);
   data_obs_pass_prefit_projy0_pull__448->GetXaxis()->SetTitleFont(42);
   data_obs_pass_prefit_projy0_pull__448->GetYaxis()->SetTitle("(Data-Bkg)/#sigma");
   data_obs_pass_prefit_projy0_pull__448->GetYaxis()->SetNdivisions(306);
   data_obs_pass_prefit_projy0_pull__448->GetYaxis()->SetLabelFont(42);
   data_obs_pass_prefit_projy0_pull__448->GetYaxis()->SetLabelOffset(0.007);
   data_obs_pass_prefit_projy0_pull__448->GetYaxis()->SetLabelSize(0.13);
   data_obs_pass_prefit_projy0_pull__448->GetYaxis()->SetTitleSize(0.12);
   data_obs_pass_prefit_projy0_pull__448->GetYaxis()->SetTitleOffset(0.4);
   data_obs_pass_prefit_projy0_pull__448->GetYaxis()->SetTitleFont(42);
   data_obs_pass_prefit_projy0_pull__448->GetZaxis()->SetLabelFont(42);
   data_obs_pass_prefit_projy0_pull__448->GetZaxis()->SetLabelOffset(0.007);
   data_obs_pass_prefit_projy0_pull__448->GetZaxis()->SetLabelSize(0.05);
   data_obs_pass_prefit_projy0_pull__448->GetZaxis()->SetTitleSize(0.08);
   data_obs_pass_prefit_projy0_pull__448->GetZaxis()->SetTitleFont(42);
   data_obs_pass_prefit_projy0_pull__448->Draw("hist");
   data_obs_pass_prefit_projy0_sub->Modified();
   plots_fit_b/base_figs/prefit_projy0_pass->cd();
   plots_fit_b/base_figs/prefit_projy0_pass->Modified();
   plots_fit_b/base_figs/prefit_projy0_pass->cd();
   plots_fit_b/base_figs/prefit_projy0_pass->SetSelected(plots_fit_b/base_figs/prefit_projy0_pass);
}
